import type { ModuleExamPlan } from "./types";

/**
 * B1 modül sınavlarının elle yazılan içeriği (müfredatın üretilmiş modülleri).
 *
 * B1'de metinlerin işi değişiyor: artık bilgi taşımıyorlar, bir DURUŞ
 * taşıyorlar (bir ret mektubu, bir gider hesabı, bir forum yazısı) ve soru
 * "ne yazıyor" değil "ne demeye getiriyor" diye soruyor. Yazma görevleri de
 * bu yüzden uzun: 70–80 kelime altında B1 üretimi ölçülemiyor.
 */
export const B1_EXAMS: ModuleExamPlan[] = [
  {
    level: "B1",
    index: 0,
    code: "B1.1",
    titleDe: "Arbeitswelt und Bewerbung",
    titleTr: "İş dünyası",
    focus: [
      { de: "Nebensatz mit weil und obwohl", tr: "sebep ve zıtlık" },
      { de: "Präteritum im Lebenslauf", tr: "özgeçmişin zamanı" },
      { de: "um … zu + Infinitiv", tr: "amaç bildirmek" },
      { de: "indirekte Frage", tr: "„…nasıl olduğunu söyleyebilir misiniz“" },
      { de: "Konjunktiv II", tr: "kibar rica ve dilek" },
    ],
    canDo: [
      { de: "Ich kann mich in einem Vorstellungsgespräch vorstellen.", tr: "İş görüşmesinde kendimi tanıtabiliyorum.", en: "I can introduce myself in a job interview." },
      { de: "Ich kann meinen Werdegang zusammenhängend erzählen.", tr: "Kariyer geçmişimi bütünlüklü anlatabiliyorum.", en: "I can describe my career path coherently." },
      { de: "Ich kann über Stärken und Schwächen sprechen.", tr: "Güçlü ve zayıf yönlerimden bahsedebiliyorum.", en: "I can talk about strengths and weaknesses." },
      { de: "Ich kann meine Motivation mit „um … zu“ begründen.", tr: "Motivasyonumu amaç cümlesiyle gerekçelendirebiliyorum.", en: "I can justify my motivation with a purpose clause." },
      { de: "Ich kann höfliche Fragen und Bitten formulieren.", tr: "Kibar soru ve rica cümleleri kurabiliyorum.", en: "I can formulate polite questions and requests." },
    ],
    listening: {
      title: "Das Vorstellungsgespräch",
      titleTr: "İş görüşmesi",
      situation: "Bir aday insan kaynakları uzmanıyla görüşüyor.",
      turns: [
        { speaker: "Personalerin", de: "Frau Kaya, erzählen Sie doch kurz von Ihrem Werdegang.", tr: "Bayan Kaya, kariyer geçmişinizden kısaca bahseder misiniz?" },
        { speaker: "Frau Kaya", de: "Gern. Ich habe in Izmir Betriebswirtschaft studiert und arbeitete danach vier Jahre in einer Spedition. Vor zwei Jahren wechselte ich in den Kundenservice.", tr: "Tabii. İzmir'de işletme okudum, ardından dört yıl bir nakliye şirketinde çalıştım. İki yıl önce müşteri hizmetlerine geçtim." },
        { speaker: "Personalerin", de: "Und warum möchten Sie zu uns?", tr: "Peki neden bize gelmek istiyorsunuz?" },
        { speaker: "Frau Kaya", de: "Ich bewerbe mich, um mehr Verantwortung zu übernehmen. Obwohl mir mein Team gefällt, gibt es dort kaum Entwicklungsmöglichkeiten.", tr: "Daha fazla sorumluluk almak için başvuruyorum. Ekibimi sevsem de orada gelişim imkânı neredeyse yok." },
        { speaker: "Personalerin", de: "Verstehe. Hätten Sie eine Frage an uns?", tr: "Anlıyorum. Bize bir sorunuz var mı?" },
        { speaker: "Frau Kaya", de: "Ja — könnten Sie mir sagen, wie die Einarbeitung abläuft?", tr: "Evet — işe alışma sürecinin nasıl işlediğini söyleyebilir misiniz?" },
        { speaker: "Personalerin", de: "Natürlich. In den ersten vier Wochen begleitet Sie eine feste Ansprechpartnerin.", tr: "Tabii. İlk dört hafta size sabit bir sorumlu eşlik ediyor." },
      ],
      questions: [
        { de: "Wo hat Frau Kaya nach dem Studium gearbeitet?", tr: "Bayan Kaya okuldan sonra nerede çalıştı?", options: ["Im Kundenservice", "In einer Spedition", "An einer Universität", "Bei einer Bank"], answer: 1 },
        { de: "Warum möchte sie wechseln?", tr: "Neden iş değiştirmek istiyor?", options: ["Das Gehalt ist zu niedrig", "Sie möchte mehr Verantwortung", "Ihr Team ist unfreundlich", "Der Weg ist zu weit"], answer: 1 },
        { de: "Wonach fragt Frau Kaya?", tr: "Bayan Kaya neyi soruyor?", options: ["Nach dem Gehalt", "Nach der Einarbeitung", "Nach den Überstunden", "Nach dem Urlaub"], answer: 1 },
      ],
    },
    reading: {
      title: "Eine Absage",
      titleTr: "Ret yazısı",
      genre: "Resmî e-posta",
      text: "Sehr geehrte Frau Kaya,\n\nvielen Dank für Ihre Bewerbung und für das freundliche Gespräch am 12. April. Wir haben uns die Unterlagen aller Kandidatinnen und Kandidaten genau angesehen.\n\nLeider müssen wir Ihnen mitteilen, dass wir uns für eine andere Person entschieden haben. Der Grund liegt nicht an Ihrer Qualifikation: Die ausgewählte Bewerberin hatte bereits mehrere Jahre in derselben Branche gearbeitet.\n\nGern behalten wir Ihre Unterlagen sechs Monate, falls Sie einverstanden sind. Für Ihren weiteren Weg wünschen wir Ihnen alles Gute.\n\nMit freundlichen Grüßen\nPetra Lohmann, Personalabteilung",
      questions: [
        { de: "Was ist das Ergebnis der Bewerbung?", tr: "Başvurunun sonucu ne?", options: ["Frau Kaya bekommt die Stelle", "Frau Kaya bekommt eine Absage", "Sie wird zu einem zweiten Gespräch eingeladen", "Die Stelle wurde gestrichen"], answer: 1 },
        { de: "Warum hat die andere Bewerberin die Stelle bekommen?", tr: "Diğer aday işi neden aldı?", options: ["Sie war günstiger", "Sie hatte schon Erfahrung in der Branche", "Sie wohnt näher", "Sie sprach besser Deutsch"], answer: 1 },
      ],
    },
    speaking: [
      { situation: "İş görüşmesinde motivasyonunu anlatıyorsun.", de: "Ich bewerbe mich bei Ihnen, um mehr Verantwortung zu übernehmen und mich weiterzuentwickeln.", tr: "Daha fazla sorumluluk almak ve kendimi geliştirmek için size başvuruyorum." },
      { situation: "Görüşmenin sonunda kibarca soru soruyorsun.", de: "Könnten Sie mir sagen, wie die Einarbeitung bei Ihnen abläuft?", tr: "İşe alışma sürecinin nasıl işlediğini söyleyebilir misiniz?" },
    ],
    writing: {
      prompt: "Bir iş ilanına başvuru mektubu (Anschreiben) yaz.",
      checklist: [
        "Hangi pozisyona başvurduğunu ve nereden gördüğünü yaz",
        "Deneyimini kısaca anlat",
        "Motivasyonunu „um … zu“ ile yaz",
        "Kibar bir soru ya da kapanış cümlesi kur",
      ],
      minWords: 70,
      phrases: [
        { de: "Mit großem Interesse habe ich Ihre Anzeige gelesen.", tr: "İlanınızı büyük ilgiyle okudum.", en: "I read your advertisement with great interest." },
        { de: "Ich bewerbe mich, um … zu …", tr: "… yapmak için başvuruyorum", en: "I am applying in order to …" },
        { de: "Nach meinem Studium arbeitete ich …", tr: "Öğrenimimden sonra … çalıştım", en: "After my studies I worked …" },
        { de: "Meine Stärke liegt in …", tr: "Güçlü yönüm …", en: "My strength lies in …" },
        { de: "Über eine Einladung würde ich mich sehr freuen.", tr: "Bir görüşme daveti beni çok sevindirir.", en: "I would be delighted to be invited for an interview." },
      ],
      sample:
        "Sehr geehrte Frau Lohmann,\n\nmit großem Interesse habe ich Ihre Anzeige für die Stelle im Kundenservice gelesen. Ich bewerbe mich, um meine Erfahrung in einem größeren Team einzubringen.\n\nNach meinem Studium in Izmir arbeitete ich vier Jahre in einer Spedition, zuletzt war ich für die Betreuung von Firmenkunden zuständig. Obwohl mir die Arbeit dort gefällt, suche ich eine Aufgabe mit mehr Verantwortung. Meine Stärke liegt im ruhigen Umgang mit schwierigen Situationen; an meinem schriftlichen Deutsch arbeite ich weiter.\n\nÜber eine Einladung zu einem Gespräch würde ich mich sehr freuen. Könnten Sie mir mitteilen, bis wann Sie eine Entscheidung treffen?\n\nMit freundlichen Grüßen\nSelin Kaya",
    },
  },

  {
    level: "B1",
    index: 1,
    code: "B1.2",
    titleDe: "Wohnen und Mietrecht",
    titleTr: "Ev ve kira dünyası",
    focus: [
      { de: "Konjunktiv II", tr: "Könnten Sie …? / Wäre es möglich …?" },
      { de: "indirekte Frage", tr: "Ich wüsste gern, ob …" },
      { de: "Passiv", tr: "Die Kaution wird gezahlt." },
      { de: "Adjektivdeklination", tr: "der große helle Raum" },
      { de: "bevor / während / obwohl", tr: "zaman ve zıtlık bağlaçları" },
    ],
    canDo: [
      { de: "Ich kann bei einer Besichtigung gezielt Fragen stellen.", tr: "Daire gezerken yerinde sorular sorabiliyorum.", en: "I can ask targeted questions during a viewing." },
      { de: "Ich kann höflich bitten und nachfragen.", tr: "Kibarca rica edip sorabiliyorum.", en: "I can make polite requests and follow-up questions." },
      { de: "Ich kann Passivsätze verstehen und bilden.", tr: "Edilgen cümleleri anlayıp kurabiliyorum.", en: "I can understand and form passive sentences." },
      { de: "Ich kann einen Schaden schriftlich melden und eine Frist setzen.", tr: "Bir arızayı yazılı bildirip süre verebiliyorum.", en: "I can report a defect in writing and set a deadline." },
      { de: "Ich kann einer Abrechnung widersprechen.", tr: "Bir hesaba itiraz edebiliyorum.", en: "I can object to a statement of costs." },
    ],
    listening: {
      title: "Die Wohnungsbesichtigung",
      titleTr: "Daire gezme",
      situation: "Bir kiracı adayı daireyi geziyor ve ayrıntıları soruyor.",
      turns: [
        { speaker: "Interessent", de: "Guten Tag. Ich wüsste gern, ob die Wohnung schon renoviert ist.", tr: "İyi günler. Dairenin tadilatlı olup olmadığını öğrenmek isterim." },
        { speaker: "Vermieterin", de: "Das Bad wurde letztes Jahr komplett renoviert, die Küche ist älter.", tr: "Banyo geçen yıl tamamen yenilendi, mutfak daha eski." },
        { speaker: "Interessent", de: "Und wie hoch sind die Nebenkosten?", tr: "Peki aidat ne kadar?" },
        { speaker: "Vermieterin", de: "180 Euro monatlich. Heizung und Wasser sind enthalten, Strom nicht.", tr: "Aylık 180 euro. Isıtma ve su dahil, elektrik değil." },
        { speaker: "Interessent", de: "Könnten Sie mir sagen, wann ich einziehen könnte?", tr: "Ne zaman taşınabileceğimi söyleyebilir misiniz?" },
        { speaker: "Vermieterin", de: "Ab dem ersten Oktober. Die Kaution wird bei der Vertragsunterschrift gezahlt — drei Kaltmieten.", tr: "1 Ekim'den itibaren. Depozito sözleşme imzasında ödeniyor — üç kira bedeli." },
        { speaker: "Interessent", de: "Wäre es möglich, die Kaution in drei Raten zu zahlen?", tr: "Depozitoyu üç taksitte ödemek mümkün olur mu?" },
        { speaker: "Vermieterin", de: "Ja, das ist gesetzlich erlaubt.", tr: "Evet, yasal olarak buna izin var." },
      ],
      questions: [
        { de: "Was wurde letztes Jahr renoviert?", tr: "Geçen yıl ne yenilendi?", options: ["Die Küche", "Das Bad", "Das Wohnzimmer", "Das ganze Haus"], answer: 1 },
        { de: "Was ist in den Nebenkosten nicht enthalten?", tr: "Aidata dahil olmayan ne?", options: ["Heizung", "Wasser", "Strom", "Müll"], answer: 2 },
        { de: "Wie kann die Kaution gezahlt werden?", tr: "Depozito nasıl ödenebilir?", options: ["Nur auf einmal", "In drei Raten", "Erst nach dem Einzug", "Gar nicht"], answer: 1 },
      ],
    },
    reading: {
      title: "Nebenkostenabrechnung",
      titleTr: "Gider hesabı",
      genre: "Resmî mektup",
      text: "Nebenkostenabrechnung für das Jahr 2025\n\nSehr geehrte Frau Demir,\n\nnachstehend erhalten Sie die Abrechnung für Ihre Wohnung in der Lindenstraße 8.\n\nVorauszahlungen: 12 × 180,00 € = 2.160,00 €\nTatsächliche Kosten: 2.517,40 €\nNachzahlung: 357,40 €\n\nDer Betrag wird am 1. März von Ihrem Konto abgebucht. Die Erhöhung ergibt sich vor allem aus den gestiegenen Heizkosten.\n\nDie Belege können innerhalb von vier Wochen in unserem Büro eingesehen werden. Ein Widerspruch muss schriftlich erfolgen.\n\nMit freundlichen Grüßen\nHausverwaltung Kruse",
      questions: [
        { de: "Wie hoch ist die Nachzahlung?", tr: "Ek ödeme ne kadar?", options: ["180,00 €", "2.160,00 €", "357,40 €", "2.517,40 €"], answer: 2 },
        { de: "Was muss man tun, wenn man nicht einverstanden ist?", tr: "Kabul etmiyorsa ne yapmalı?", options: ["Anrufen", "Schriftlich widersprechen", "Nicht zahlen", "Ausziehen"], answer: 1 },
      ],
    },
    speaking: [
      { situation: "Ev sahibine kibar bir soru soruyorsun.", de: "Könnten Sie mir sagen, ob die Nebenkosten die Heizung enthalten?", tr: "Aidatın ısıtmayı kapsayıp kapsamadığını söyleyebilir misiniz?" },
      { situation: "Arıza için süre veriyorsun.", de: "Die Heizung tropft seit einer Woche. Ich bitte darum, dass der Schaden bis Freitag repariert wird.", tr: "Kalorifer bir haftadır damlıyor. Arızanın cumaya kadar giderilmesini rica ediyorum." },
    ],
    writing: {
      prompt: "Ev sahibine bir arızayı bildiren ve süre veren resmî bir e-posta yaz.",
      checklist: [
        "Arızayı ve ne zamandır sürdüğünü yaz",
        "En az bir kibar rica cümlesi kur",
        "Bir tarih ya da süre ver",
        "Bir edilgen (Passiv) cümle kullan",
      ],
      minWords: 70,
      phrases: [
        { de: "Ich wohne seit … in …", tr: "…'dan beri …'da oturuyorum", en: "I have been living in … since …" },
        { de: "Seit … tropft / funktioniert … nicht.", tr: "…'dan beri … damlıyor / çalışmıyor.", en: "Since … the … has been leaking / not working." },
        { de: "Ich bitte darum, dass … repariert wird.", tr: "…'in onarılmasını rica ediyorum.", en: "I request that … be repaired." },
        { de: "bis spätestens …", tr: "en geç …'a kadar", en: "by … at the latest" },
        { de: "Könnten Sie mir mitteilen, wann …?", tr: "…'in ne zaman olacağını bildirebilir misiniz?", en: "Could you let me know when …?" },
      ],
      sample:
        "Sehr geehrte Frau Kruse,\n\nich wohne seit zwei Jahren in der Lindenstraße 8, Wohnung 4. Seit dem vergangenen Wochenende tropft der Wasserhahn im Bad, und seit Montag wird die Heizung im Wohnzimmer nicht mehr richtig warm.\n\nBevor ich Ihnen geschrieben habe, hatte ich bereits den Hausmeister informiert; leider wurde der Schaden bisher nicht behoben. Obwohl es draußen kälter wird, kann ich das Zimmer im Moment kaum nutzen.\n\nIch bitte darum, dass die Reparatur bis spätestens Freitag, den 14. März, durchgeführt wird. Könnten Sie mir mitteilen, wann der Handwerker kommt? Am Nachmittag bin ich in der Regel zu Hause.\n\nMit freundlichen Grüßen\nAyse Demir",
    },
  },

  {
    level: "B1",
    index: 2,
    code: "B1.3",
    titleDe: "Konnektoren meistern",
    titleTr: "Bağlaç ustalığı",
    focus: [
      { de: "damit und um … zu", tr: "amaç anlatmanın iki yolu" },
      { de: "obwohl und trotzdem", tr: "zıtlık: yan cümle mi bağlayıcı mı" },
      { de: "als und wenn", tr: "bir kerelik geçmiş mi tekrar mı" },
      { de: "nachdem, bevor, während", tr: "olayları sıraya koymak" },
      { de: "je … desto, entweder … oder", tr: "orantı ve ikili bağlaçlar" },
    ],
    canDo: [
      { de: "Ich kann Absichten mit „damit“ und „um … zu“ ausdrücken.", tr: "Amaçlarımı iki farklı yapıyla anlatabiliyorum.", en: "I can express intentions with purpose clauses." },
      { de: "Ich kann Gegensätze mit „obwohl“ und „trotzdem“ formulieren.", tr: "Zıtlığı „obwohl“ ve „trotzdem“ ile kurabiliyorum.", en: "I can express contrast with „obwohl“ and „trotzdem“." },
      { de: "Ich kann „als“ und „wenn“ richtig unterscheiden.", tr: "„als“ ile „wenn“ arasındaki farkı doğru kullanabiliyorum.", en: "I can distinguish „als“ and „wenn“ correctly." },
      { de: "Ich kann Ereignisse zeitlich ordnen.", tr: "Olayları zaman sırasına dizebiliyorum.", en: "I can order events in time." },
      { de: "Ich kann mit zweiteiligen Konnektoren Alternativen ausdrücken.", tr: "İkili bağlaçlarla seçenek sunabiliyorum.", en: "I can express alternatives with paired conjunctions." },
    ],
    listening: {
      title: "Der Wechsel",
      titleTr: "İş değişikliği",
      situation: "İki arkadaş iş değiştirme kararını konuşuyor.",
      turns: [
        { speaker: "Mert", de: "Du siehst zufrieden aus. Wie läuft die neue Stelle?", tr: "Memnun görünüyorsun. Yeni iş nasıl gidiyor?" },
        { speaker: "Lisa", de: "Sehr gut. Nachdem ich den alten Job gekündigt hatte, habe ich zwei Monate lang nichts gefunden.", tr: "Çok iyi. Eski işten ayrıldıktan sonra iki ay hiçbir şey bulamamıştım." },
        { speaker: "Mert", de: "Das war sicher anstrengend.", tr: "Kesin yorucuydu." },
        { speaker: "Lisa", de: "Obwohl ich am Anfang nervös war, habe ich weitergesucht. Ich habe jeden Tag geübt, um im Gespräch sicherer zu sprechen.", tr: "Başta gergin olsam da aramaya devam ettim. Görüşmede daha rahat konuşmak için her gün çalıştım." },
        { speaker: "Mert", de: "Und jetzt?", tr: "Peki şimdi?" },
        { speaker: "Lisa", de: "Jetzt arbeite ich vier Tage, damit ich freitags studieren kann. Je mehr ich lerne, desto leichter wird es.", tr: "Şimdi dört gün çalışıyorum, cumaları okuyabilmek için. Ne kadar çok öğrenirsem o kadar kolaylaşıyor." },
        { speaker: "Mert", de: "Also entweder Arbeit oder Studium?", tr: "Yani ya iş ya okul mu?" },
        { speaker: "Lisa", de: "Nein — sowohl Arbeit als auch Studium.", tr: "Hayır — hem iş hem okul." },
      ],
      questions: [
        { de: "Was ist passiert, nachdem Lisa gekündigt hatte?", tr: "Lisa istifa ettikten sonra ne oldu?", options: ["Sie hat sofort eine Stelle gefunden", "Sie hat zwei Monate lang nichts gefunden", "Sie hat sofort studiert", "Sie hat Urlaub gemacht"], answer: 1 },
        { de: "Warum arbeitet Lisa nur vier Tage?", tr: "Lisa neden sadece dört gün çalışıyor?", options: ["Weil sie krank ist", "Damit sie freitags studieren kann", "Weil die Firma es so will", "Obwohl sie mehr arbeiten möchte"], answer: 1 },
        { de: "Wozu hat Lisa jeden Tag geübt?", tr: "Lisa her gün ne için çalıştı?", options: ["Um sicherer zu sprechen", "Weil der Chef es verlangt hat", "Damit sie mehr verdient", "Obwohl sie keine Zeit hatte"], answer: 0 },
      ],
    },
    reading: {
      title: "Sprachen lernen als Erwachsener",
      titleTr: "Yetişkinlikte dil öğrenmek",
      genre: "Forum yazısı",
      text: "Forum: Sprachen lernen als Erwachsener\n\nViele glauben, dass man als Erwachsener keine Sprache mehr richtig lernen kann. Das stimmt so nicht. Zwar lernen Kinder die Aussprache leichter, aber Erwachsene verstehen Strukturen schneller, weil sie schon eine Sprache analysiert haben.\n\nEntscheidend ist die Regelmäßigkeit: Je öfter man übt, desto stabiler wird das Gelernte. Zwanzig Minuten täglich bringen mehr als drei Stunden am Sonntag.\n\nWichtig ist außerdem, dass man spricht, bevor man sich sicher fühlt. Wer wartet, bis alles perfekt ist, fängt nie an. Obwohl Fehler unangenehm sind, sind sie der schnellste Weg zum Fortschritt.",
      questions: [
        { de: "Was können Erwachsene laut Text besser als Kinder?", tr: "Metne göre yetişkinler çocuklardan neyi daha iyi yapıyor?", options: ["Die Aussprache", "Strukturen schneller verstehen", "Länger üben", "Fehler vermeiden"], answer: 1 },
        { de: "Was empfiehlt der Text?", tr: "Metin neyi öneriyor?", options: ["Drei Stunden am Sonntag üben", "Jeden Tag kurz üben", "Erst sprechen, wenn man sicher ist", "Fehler unbedingt vermeiden"], answer: 1 },
      ],
    },
    speaking: [
      { situation: "Bir amacını anlatıyorsun.", de: "Ich stehe früher auf, damit ich vor der Arbeit noch eine halbe Stunde lernen kann.", tr: "İşten önce yarım saat çalışabilmek için daha erken kalkıyorum." },
      { situation: "Bir zıtlığı anlatıyorsun.", de: "Obwohl das Angebot gut war, habe ich es abgelehnt; trotzdem bereue ich nichts.", tr: "Teklif iyi olmasına rağmen reddettim; yine de pişman değilim." },
    ],
    writing: {
      prompt: "Hayatında verdiğin bir kararı anlat: neden verdin, öncesinde ve sonrasında ne oldu, bugün nasıl görüyorsun.",
      checklist: [
        "„nachdem“ ile bir cümle kur (öncesi Plusquamperfekt)",
        "„obwohl“ ya da „trotzdem“ kullan",
        "„damit“ ya da „um … zu“ ile bir amaç yaz",
        "„je … desto“ ya da bir ikili bağlaç kullan",
      ],
      minWords: 80,
      phrases: [
        { de: "Nachdem ich … hatte, …", tr: "…'dıktan sonra …", en: "After I had …, …" },
        { de: "Obwohl …, …", tr: "…-e rağmen …", en: "Although …, …" },
        { de: "…, damit …", tr: "… diye / … olsun diye", en: "…, so that …" },
        { de: "Je mehr …, desto …", tr: "Ne kadar çok …, o kadar …", en: "The more …, the …" },
        { de: "entweder … oder … / sowohl … als auch …", tr: "ya … ya … / hem … hem …", en: "either … or … / both … and …" },
      ],
      sample:
        "Vor drei Jahren habe ich meine Stelle gekündigt, obwohl ich dort gut verdient habe. Der Grund war einfach: Ich wollte etwas lernen, das mich wirklich interessiert.\n\nNachdem ich gekündigt hatte, war ich zwei Monate ohne Arbeit. Diese Zeit war schwierig, trotzdem habe ich sie genutzt: Ich habe jeden Tag Deutsch geübt, um bei Bewerbungsgesprächen sicherer zu sprechen. Bevor ich mich beworben habe, habe ich außerdem einen kurzen Kurs gemacht.\n\nHeute arbeite ich vier Tage pro Woche, damit ich freitags studieren kann. Je länger ich das mache, desto sicherer werde ich. Entweder man wartet auf den perfekten Moment oder man fängt einfach an — ich habe mich für das Zweite entschieden.",
    },
  },

  {
    level: "B1",
    index: 3,
    code: "B1.4",
    titleDe: "Beschreiben und definieren",
    titleTr: "İlgi cümleleri",
    focus: [
      { de: "Relativsatz im Nominativ", tr: "der / die / das ile tanımlama" },
      { de: "Relativsatz im Akkusativ", tr: "nesnede der yerine den" },
      { de: "Relativsatz im Dativ", tr: "dem / der / denen" },
      { de: "Präposition + Relativpronomen", tr: "in dem, mit dem, von dem" },
      { de: "alles, was … / jemand, der …", tr: "belirsiz sözlerle ilgi cümlesi" },
    ],
    canDo: [
      { de: "Ich kann Personen genau beschreiben.", tr: "İnsanları ayrıntılı tarif edebiliyorum.", en: "I can describe people in detail." },
      { de: "Ich kann etwas beschreiben, wenn ich den Namen nicht weiß.", tr: "Adını bilmediğim bir şeyi tarif edebiliyorum.", en: "I can describe something when I don't know its name." },
      { de: "Ich kann das Relativpronomen im Nominativ, Akkusativ und Dativ richtig wählen.", tr: "İlgi zamirini yalın, belirtme ve yönelme hâlinde doğru seçebiliyorum.", en: "I can choose the right relative pronoun in all three cases." },
      { de: "Ich kann eine Präposition vor das Relativpronomen stellen.", tr: "İlgi zamirinin önüne edat koyabiliyorum.", en: "I can put a preposition before the relative pronoun." },
      { de: "Ich kann im Fundbüro einen verlorenen Gegenstand beschreiben.", tr: "Kayıp eşya bürosunda kaybettiğim eşyayı tarif edebiliyorum.", en: "I can describe a lost item at the lost-and-found office." },
    ],
    listening: {
      title: "Im Fundbüro",
      titleTr: "Kayıp eşya bürosunda",
      situation: "Bir adam tramvayda unuttuğu çantayı arıyor.",
      turns: [
        { speaker: "Beamtin", de: "Guten Tag. Was haben Sie denn verloren?", tr: "İyi günler. Neyinizi kaybettiniz?" },
        { speaker: "Herr Solak", de: "Eine Tasche, die ich gestern in der Straßenbahn vergessen habe.", tr: "Dün tramvayda unuttuğum bir çanta." },
        { speaker: "Beamtin", de: "Können Sie die Tasche beschreiben?", tr: "Çantayı tarif edebilir misiniz?" },
        { speaker: "Herr Solak", de: "Sie ist dunkelblau, aus Stoff, mit einem roten Band am Griff.", tr: "Koyu mavi, kumaştan, sapında kırmızı bir bant var." },
        { speaker: "Beamtin", de: "Und was war darin?", tr: "Peki içinde ne vardı?" },
        { speaker: "Herr Solak", de: "Ein Laptop, ein Ladegerät und ein Buch, das ich aus der Bibliothek geliehen habe.", tr: "Bir dizüstü, bir şarj aleti ve kütüphaneden aldığım bir kitap." },
        { speaker: "Beamtin", de: "Einen Moment. Wir haben hier eine blaue Tasche, die gestern Abend abgegeben wurde.", tr: "Bir dakika. Dün akşam teslim edilen mavi bir çanta var." },
        { speaker: "Herr Solak", de: "Das rote Band — ja, das ist meine!", tr: "Kırmızı bant — evet, bu benimki!" },
      ],
      questions: [
        { de: "Wo hat Herr Solak die Tasche vergessen?", tr: "Bay Solak çantayı nerede unuttu?", options: ["Im Bus", "In der Straßenbahn", "Im Zug", "Im Café"], answer: 1 },
        { de: "Woran erkennt man die Tasche?", tr: "Çanta neyden tanınıyor?", options: ["An einem Namensschild", "An einem roten Band am Griff", "An der Größe", "An einem Aufkleber"], answer: 1 },
        { de: "Was war in der Tasche?", tr: "Çantada ne vardı?", options: ["Nur ein Laptop", "Ein Laptop, ein Ladegerät und ein Buch", "Ein Buch und ein Handy", "Kleidung und Schuhe"], answer: 1 },
      ],
    },
    reading: {
      title: "Schwarzes Brett — Nachbarschaftshilfe",
      titleTr: "Mahalle panosundaki ilan",
      genre: "İlan",
      text: "Schwarzes Brett — Nachbarschaftshilfe\n\nGesucht: jemand, der zweimal pro Woche mit unserem Hund spazieren geht. Wir suchen keine Firma, sondern eine Person aus dem Viertel, die Zeit und Geduld hat.\n\nUnser Hund heißt Emil. Er ist ein ruhiger Mischling, der Kinder mag und der nicht an der Leine zieht.\n\nWir zahlen zwölf Euro pro Stunde. Wer Interesse hat, meldet sich unter 0176 55 43 21 — am besten abends, weil wir tagsüber arbeiten.\n\nFamilie Brandt, Haus Nr. 14",
      questions: [
        { de: "Wen sucht Familie Brandt?", tr: "Brandt ailesi kimi arıyor?", options: ["Eine Hundeschule", "Eine Person aus dem Viertel", "Einen Tierarzt", "Eine Firma"], answer: 1 },
        { de: "Wann soll man am besten anrufen?", tr: "En iyisi ne zaman aranmalı?", options: ["Morgens", "Mittags", "Abends", "Am Wochenende"], answer: 2 },
      ],
    },
    speaking: [
      { situation: "Bir arkadaşına sevdiğin filmi öneriyorsun.", de: "Das ist ein Film, den ich schon dreimal gesehen habe.", tr: "Bu, üç kez izlediğim bir film." },
      { situation: "Kayıp eşya bürosunda çantanı tarif ediyorsun.", de: "Ich suche eine Tasche, die ich in der Straßenbahn vergessen habe.", tr: "Tramvayda unuttuğum bir çanta arıyorum." },
    ],
    writing: {
      prompt: "Mahalle panosuna bir ilan yaz: bir şey arıyorsun ya da bir şey veriyorsun.",
      checklist: [
        "Ne aradığını ya da ne verdiğini yaz",
        "En az iki ilgi cümlesi kur",
        "Bir tanesinde ilgi zamirinin önüne edat koy",
        "Nasıl ve ne zaman ulaşılacağını yaz",
      ],
      minWords: 70,
      phrases: [
        { de: "Ich suche jemanden, der …", tr: "… olan birini arıyorum", en: "I am looking for someone who …" },
        { de: "…, den ich … habe", tr: "…-dığım …", en: "…, which I have …" },
        { de: "…, in dem / in der …", tr: "içinde … olan", en: "… in which …" },
        { de: "Wer Interesse hat, meldet sich unter …", tr: "İlgilenen … numarasından ulaşsın", en: "Anyone interested can get in touch at …" },
        { de: "am besten abends", tr: "en iyisi akşamları", en: "preferably in the evening" },
      ],
      sample:
        "Suche Rad-Begleitung\n\nIch suche jemanden, der zweimal pro Woche mit mir zur Arbeit fährt. Ich wohne im Bezirk Ehrenfeld, in dem es zum Glück viele ruhige Radwege gibt, und arbeite in der Innenstadt.\n\nIch habe ein altes Rad, das nicht besonders schnell ist — Tempo ist mir also nicht wichtig. Wichtiger ist mir jemand, dem man morgens auch mal in Ruhe zuhören kann.\n\nWer Interesse hat, meldet sich unter 0176 22 11 09, am besten abends. Ich freue mich!",
    },
  },

  {
    level: "B1",
    index: 4,
    code: "B1.5",
    titleDe: "Ämter und Anträge",
    titleTr: "Bürokrasi",
    focus: [
      { de: "Passiv im Präsens", tr: "wird artı Partizip II" },
      { de: "Passiv im Präteritum", tr: "wurde artı Partizip II" },
      { de: "Passiv mit Modalverb", tr: "muss vorgelegt werden" },
      { de: "Konjunktiv II für höfliche Bitten", tr: "Wäre es möglich …?" },
      { de: "indirekte Frage", tr: "Wissen Sie, wann …?" },
    ],
    canDo: [
      { de: "Ich kann Behördenbriefe im Passiv verstehen.", tr: "Resmî yazılardaki edilgen cümleleri anlayabiliyorum.", en: "I can understand official letters written in the passive." },
      { de: "Ich kann sagen, welche Unterlagen benötigt werden.", tr: "Hangi belgelerin gerektiğini söyleyebiliyorum.", en: "I can say which documents are required." },
      { de: "Ich kann einen Amtstermin höflich verschieben.", tr: "Resmî bir randevuyu kibarca erteleyebiliyorum.", en: "I can politely postpone an appointment at a public office." },
      { de: "Ich kann schriftlich Widerspruch einlegen und ihn begründen.", tr: "Yazılı itiraz edip gerekçelendirebiliyorum.", en: "I can lodge a written objection and justify it." },
      { de: "Ich kann höflich nachfragen, was verlangt wird.", tr: "Neyin istendiğini kibarca sorabiliyorum.", en: "I can politely ask what is required." },
    ],
    listening: {
      title: "Bei der Ausländerbehörde",
      titleTr: "Yabancılar dairesinde",
      situation: "Bir kadın oturma iznini uzatmak için memurla konuşuyor.",
      turns: [
        { speaker: "Sachbearbeiter", de: "Guten Tag. Ihre Aufenthaltserlaubnis läuft im Mai ab, richtig?", tr: "İyi günler. Oturma izniniz mayısta doluyor, değil mi?" },
        { speaker: "Frau Nuri", de: "Ja, am fünfzehnten Mai. Ich möchte sie verlängern lassen.", tr: "Evet, 15 Mayıs'ta. Uzatmak istiyorum." },
        { speaker: "Sachbearbeiter", de: "Dann werden drei Dinge benötigt: der Pass, der Mietvertrag und ein Nachweis über Ihr Einkommen.", tr: "O zaman üç şey gerekiyor: pasaport, kira sözleşmesi ve gelir belgesi." },
        { speaker: "Frau Nuri", de: "Den Mietvertrag habe ich dabei. Muss das Original vorgelegt werden?", tr: "Kira sözleşmesi yanımda. Asıl nüsha mı ibraz edilmeli?" },
        { speaker: "Sachbearbeiter", de: "Beim Pass ja, beim Mietvertrag reicht eine Kopie.", tr: "Pasaportta evet, kira sözleşmesinde fotokopi yeterli." },
        { speaker: "Frau Nuri", de: "Und wie lange wird der Antrag bearbeitet?", tr: "Peki başvuru ne kadar sürede işleme alınıyor?" },
        { speaker: "Sachbearbeiter", de: "In der Regel vier bis sechs Wochen. Der Bescheid wird Ihnen zugeschickt.", tr: "Genelde dört ila altı hafta. Karar yazısı size gönderilir." },
        { speaker: "Frau Nuri", de: "Gut. Dann bringe ich den Einkommensnachweis morgen vorbei.", tr: "Peki. O zaman gelir belgesini yarın getiririm." },
      ],
      questions: [
        { de: "Was läuft im Mai ab?", tr: "Mayısta neyin süresi doluyor?", options: ["Der Mietvertrag", "Die Aufenthaltserlaubnis", "Der Pass", "Die Widerspruchsfrist"], answer: 1 },
        { de: "Wovon reicht eine Kopie?", tr: "Neyin fotokopisi yeterli?", options: ["Vom Pass", "Vom Mietvertrag", "Vom Einkommensnachweis", "Von allen Unterlagen"], answer: 1 },
        { de: "Wie lange dauert die Bearbeitung?", tr: "İşlem ne kadar sürüyor?", options: ["Zwei Wochen", "Vier bis sechs Wochen", "Drei Monate", "Das sagt der Sachbearbeiter nicht"], answer: 1 },
      ],
    },
    reading: {
      title: "Bescheid des Straßenverkehrsamts",
      titleTr: "Trafik dairesinden karar yazısı",
      genre: "Resmî yazı",
      text: "Stadt Bonn — Straßenverkehrsamt\n\nSehr geehrte Frau Aydin,\n\nIhr Antrag auf Umschreibung des Führerscheins wurde am 12. März bearbeitet. Leider konnte er nicht bewilligt werden, weil der Sehtest fehlt.\n\nDer Nachweis kann bis zum 30. April nachgereicht werden. Danach wird der Antrag ohne weitere Prüfung abgelehnt.\n\nDie Gebühr von 43 Euro wurde bereits gebucht und wird nicht erstattet.\n\nMit freundlichen Grüßen\nIm Auftrag\nR. Seidel",
      questions: [
        { de: "Warum wurde der Antrag nicht bewilligt?", tr: "Başvuru neden onaylanmadı?", options: ["Die Gebühr fehlt", "Der Sehtest fehlt", "Der Pass ist abgelaufen", "Die Frist ist vorbei"], answer: 1 },
        { de: "Was passiert mit der Gebühr?", tr: "Ücrete ne oluyor?", options: ["Sie wird erstattet", "Sie wird nicht erstattet", "Sie muss noch gezahlt werden", "Sie wird halbiert"], answer: 1 },
      ],
    },
    speaking: [
      { situation: "Dairede hangi belgelerin gerektiğini soruyorsun.", de: "Können Sie mir sagen, welche Unterlagen benötigt werden?", tr: "Hangi belgelerin gerektiğini söyleyebilir misiniz?" },
      { situation: "Randevunu kibarca ertelemek istiyorsun.", de: "Wäre es möglich, den Termin um eine Woche zu verschieben?", tr: "Randevuyu bir hafta ertelemek mümkün olur mu?" },
    ],
    writing: {
      prompt: "Aşağıdaki karara yazılı olarak itiraz et.",
      stimulus: "Ihr Antrag auf Verlängerung der Aufenthaltserlaubnis wurde abgelehnt, da der Einkommensnachweis nicht fristgerecht eingereicht wurde.",
      checklist: [
        "Neye itiraz ettiğini ilk cümlede yaz",
        "İtirazını gerekçelendir",
        "En az bir edilgen cümle kullan",
        "Ricanı bir yan cümleyle yaz",
      ],
      minWords: 70,
      phrases: [
        { de: "Hiermit widerspreche ich …", tr: "İşbu yazıyla …'e itiraz ediyorum", en: "I hereby object to …" },
        { de: "Ich bitte darum, dass …", tr: "…-mesini rica ediyorum", en: "I request that …" },
        { de: "fristgerecht", tr: "süresi içinde", en: "within the deadline" },
        { de: "in der Anlage", tr: "ekte", en: "enclosed" },
        { de: "Mit freundlichen Grüßen", tr: "Saygılarımla", en: "Yours sincerely" },
      ],
      sample:
        "Sehr geehrte Damen und Herren,\n\nhiermit widerspreche ich Ihrem Bescheid vom 14. April, mit dem mein Antrag auf Verlängerung der Aufenthaltserlaubnis abgelehnt wurde.\n\nDer Einkommensnachweis wurde meiner Ansicht nach fristgerecht eingereicht: Ich habe ihn am 3. April persönlich abgegeben. Eine Kopie mit dem Eingangsstempel füge ich in der Anlage bei.\n\nIch bitte darum, dass der Antrag erneut geprüft wird. Über eine kurze Bestätigung, dass mein Widerspruch eingegangen ist, wäre ich dankbar.\n\nMit freundlichen Grüßen\nLeyla Aydin",
    },
  },

  {
    level: "B1",
    index: 5,
    code: "B1.6",
    titleDe: "Lernen und Weiterkommen",
    titleTr: "Eğitim ve gelişim",
    focus: [
      { de: "Infinitiv mit zu", tr: "niyet ve değerlendirme: … zu …" },
      { de: "um … zu + Infinitiv", tr: "amaç bildirmek" },
      { de: "indirekte Frage", tr: "Ich weiß nicht, wann …" },
      { de: "Konjunktiv II", tr: "An deiner Stelle würde ich …" },
      { de: "zweiteilige Konnektoren", tr: "sowohl … als auch …" },
    ],
    canDo: [
      { de: "Ich kann meine Lernziele nennen und begründen.", tr: "Öğrenme hedeflerimi söyleyip gerekçelendirebiliyorum.", en: "I can state and justify my learning goals." },
      { de: "Ich kann zwei Kurse vergleichen und mich entscheiden.", tr: "İki kursu karşılaştırıp karar verebiliyorum.", en: "I can compare two courses and make a decision." },
      { de: "Ich kann nach Informationen fragen, die ich nicht habe.", tr: "Bilmediğim bilgileri sorabiliyorum.", en: "I can ask for information I don't have." },
      { de: "Ich kann eine Erfahrung wie ein Praktikum schriftlich beschreiben.", tr: "Staj gibi bir deneyimi yazılı anlatabiliyorum.", en: "I can describe an experience such as an internship in writing." },
      { de: "Ich kann Rat geben und um Rückmeldung bitten.", tr: "Tavsiye verip geri bildirim isteyebiliyorum.", en: "I can give advice and ask for feedback." },
    ],
    listening: {
      title: "Welcher Kurs passt?",
      titleTr: "Hangi kurs uygun?",
      situation: "Bir kurs danışmanı iki kursu karşılaştırıyor.",
      turns: [
        { speaker: "Beraterin", de: "Sie haben A2 abgeschlossen. Wollen Sie den Intensivkurs oder den Abendkurs?", tr: "A2'yi bitirmişsiniz. Yoğun kursu mu akşam kursunu mu istersiniz?" },
        { speaker: "Herr Demir", de: "Ich arbeite Vollzeit. Wie oft findet der Abendkurs statt?", tr: "Tam zamanlı çalışıyorum. Akşam kursu ne sıklıkta?" },
        { speaker: "Beraterin", de: "Zweimal pro Woche, jeweils von achtzehn bis halb neun. Der Intensivkurs läuft täglich am Vormittag.", tr: "Haftada iki kez, her seferinde altıdan sekiz buçuğa. Yoğun kurs her gün öğleden önce." },
        { speaker: "Herr Demir", de: "Und wie lange dauert es bis zur B1-Prüfung?", tr: "Peki B1 sınavına kadar ne kadar sürüyor?" },
        { speaker: "Beraterin", de: "Im Intensivkurs drei Monate, im Abendkurs etwa sechs.", tr: "Yoğun kursta üç ay, akşam kursunda yaklaşık altı." },
        { speaker: "Herr Demir", de: "Sechs Monate sind lang. Aber tagsüber kann ich nicht.", tr: "Altı ay uzun. Ama gündüz olmuyor." },
        { speaker: "Beraterin", de: "Dann nehmen Sie den Abendkurs. Vorher machen Sie bitte den Einstufungstest.", tr: "O zaman akşam kursunu alın. Öncesinde lütfen seviye tespit sınavına girin." },
        { speaker: "Herr Demir", de: "Gut. Wann kann ich den machen?", tr: "Peki. Ne zaman girebilirim?" },
      ],
      questions: [
        { de: "Warum kommt der Intensivkurs nicht infrage?", tr: "Yoğun kurs neden olmuyor?", options: ["Er ist zu teuer", "Herr Demir arbeitet tagsüber", "Es gibt keine Plätze", "Er dauert zu lange"], answer: 1 },
        { de: "Wie lange dauert der Abendkurs bis zur Prüfung?", tr: "Akşam kursu sınava kadar ne kadar sürüyor?", options: ["Drei Monate", "Etwa sechs Monate", "Zwei Monate", "Ein Jahr"], answer: 1 },
        { de: "Was soll Herr Demir vorher machen?", tr: "Bay Demir öncesinde ne yapmalı?", options: ["Die Gebühr zahlen", "Den Einstufungstest machen", "Einen Termin absagen", "Ein Praktikum machen"], answer: 1 },
      ],
    },
    reading: {
      title: "Weiterbildung: Digitale Buchhaltung",
      titleTr: "Mesleki eğitim duyurusu",
      genre: "Kurs tanıtımı",
      text: "Weiterbildung: Digitale Buchhaltung\n\nDer Kurs richtet sich an Berufstätige, die ihre Kenntnisse berufsbegleitend erweitern möchten. Unterricht: freitags von sechzehn bis zwanzig Uhr, zwölf Wochen.\n\nZiel ist es, am Ende selbstständig mit den gängigen Programmen zu arbeiten. Ein Zertifikat wird nach bestandener Abschlussprüfung ausgestellt.\n\nKosten: 890 Euro. Die Hälfte kann über den Arbeitgeber finanziert werden — fragen Sie vorher nach.\n\nAnmeldung bis zwei Wochen vor Kursbeginn.",
      questions: [
        { de: "Für wen ist der Kurs gedacht?", tr: "Kurs kimler için?", options: ["Für Studierende", "Für Berufstätige", "Für Anfänger ohne Erfahrung", "Für Arbeitslose"], answer: 1 },
        { de: "Wann bekommt man das Zertifikat?", tr: "Sertifika ne zaman veriliyor?", options: ["Am ersten Kurstag", "Nach der Anmeldung", "Nach bestandener Abschlussprüfung", "Nach zwölf Wochen automatisch"], answer: 2 },
      ],
    },
    speaking: [
      { situation: "Kurs danışmanına hedefini anlatıyorsun.", de: "Mein Ziel ist es, in sechs Monaten die Prüfung zu bestehen.", tr: "Hedefim altı ayda sınavı geçmek." },
      { situation: "Bir arkadaşına tavsiye veriyorsun.", de: "An deiner Stelle würde ich zuerst den Einstufungstest machen.", tr: "Senin yerinde olsam önce seviye tespit sınavına girerdim." },
    ],
    writing: {
      prompt: "Bir kurs merkezine e-posta yaz: hangi kursu istiyorsun, hedefin ne, neyi bilmen gerekiyor.",
      checklist: [
        "Hangi kursla ilgilendiğini yaz",
        "Hedefini bir mastar öbeğiyle yaz",
        "Bir amacını 'um … zu' ile gerekçelendir",
        "En az iki dolaylı soru sor",
      ],
      minWords: 70,
      phrases: [
        { de: "Mein Ziel ist es, … zu …", tr: "Hedefim … yapmak", en: "My goal is to …" },
        { de: "Ich mache das, um … zu …", tr: "Bunu … yapmak için yapıyorum", en: "I am doing this in order to …" },
        { de: "Ich möchte wissen, ob …", tr: "…-ip …-mediğini bilmek istiyorum", en: "I would like to know whether …" },
        { de: "Können Sie mir sagen, wann …?", tr: "…-in ne zaman olduğunu söyleyebilir misiniz?", en: "Could you tell me when …?" },
        { de: "berufsbegleitend", tr: "işle birlikte", en: "alongside work" },
      ],
      sample:
        "Sehr geehrte Damen und Herren,\n\nich interessiere mich für Ihren Abendkurs auf dem Niveau B1. Mein Ziel ist es, in etwa sechs Monaten die Prüfung zu bestehen. Ich lerne berufsbegleitend, denn ich arbeite Vollzeit und kann tagsüber nicht kommen.\n\nIch mache den Kurs vor allem, um im Beruf sicherer zu sprechen. Deshalb ist mir eine kleine Gruppe wichtiger als ein schnelles Tempo.\n\nKönnen Sie mir sagen, wann der nächste Einstufungstest stattfindet? Außerdem möchte ich wissen, ob man den Kurs in Raten bezahlen kann.\n\nVielen Dank und freundliche Grüße\nMurat Demir",
    },
  },

  {
    level: "B1",
    index: 6,
    code: "B1.7",
    titleDe: "Meinung und Diskussion",
    titleTr: "Fikir ve tartışma",
    focus: [
      { de: "dass-Satz", tr: "görüşü yan cümleyle söylemek" },
      { de: "zweiteilige Konnektoren", tr: "einerseits … andererseits" },
      { de: "Konjunktiv II", tr: "kibar itiraz: Da wäre ich vorsichtig" },
      { de: "Verben mit Präposition", tr: "Es hängt davon ab, ob …" },
      { de: "indirekte Frage", tr: "Ich bezweifle, dass …" },
    ],
    canDo: [
      { de: "Ich kann meine Meinung sagen und begründen.", tr: "Görüşümü söyleyip gerekçelendirebiliyorum.", en: "I can state and justify my opinion." },
      { de: "Ich kann Vor- und Nachteile gegenüberstellen.", tr: "Artıları ve eksileri karşı karşıya koyabiliyorum.", en: "I can weigh advantages against disadvantages." },
      { de: "Ich kann höflich widersprechen, ohne unhöflich zu wirken.", tr: "Kaba görünmeden kibarca karşı çıkabiliyorum.", en: "I can disagree politely without sounding rude." },
      { de: "Ich kann eine Behauptung hinterfragen.", tr: "Bir iddiayı sorgulayabiliyorum.", en: "I can question a claim." },
      { de: "Ich kann einen Film oder ein Buch bewerten.", tr: "Bir filmi ya da kitabı değerlendirebiliyorum.", en: "I can review a film or a book." },
    ],
    listening: {
      title: "Sonntags einkaufen?",
      titleTr: "Pazar günü alışveriş?",
      situation: "İki meslektaş pazar günü açık marketleri tartışıyor.",
      turns: [
        { speaker: "Jonas", de: "Ich finde, die Läden sollten auch sonntags öffnen dürfen.", tr: "Bence dükkânlar pazar günü de açılabilmeli." },
        { speaker: "Meral", de: "Da wäre ich vorsichtig. Einerseits ist es praktisch, andererseits arbeitet dann jemand.", tr: "Burada temkinli olurdum. Bir yandan pratik, öte yandan biri çalışıyor demek." },
        { speaker: "Jonas", de: "Aber diese Leute werden bezahlt. Wer sonntags arbeitet, bekommt mehr Geld.", tr: "Ama o insanlara ödeme yapılıyor. Pazar çalışan daha çok para alıyor." },
        { speaker: "Meral", de: "Das stimmt. Trotzdem bezweifle ich, dass sie wirklich frei entscheiden können.", tr: "Doğru. Yine de gerçekten özgürce karar verebildiklerinden şüpheliyim." },
        { speaker: "Jonas", de: "Kannst du das nachvollziehen, wenn Familien nur sonntags Zeit haben?", tr: "Ailelerin sadece pazar vakti olduğunu düşününce anlayabiliyor musun?" },
        { speaker: "Meral", de: "Teilweise. Ich hätte lieber längere Öffnungszeiten unter der Woche.", tr: "Kısmen. Ben hafta içi daha uzun açılış saatlerini tercih ederdim." },
        { speaker: "Jonas", de: "Das wäre ein Kompromiss, ja.", tr: "Bu bir uzlaşma olurdu, evet." },
        { speaker: "Meral", de: "Zusammenfassend: Ich bin dagegen, aber ich verstehe dein Argument.", tr: "Özetle: Karşıyım ama argümanını anlıyorum." },
      ],
      questions: [
        { de: "Was ist Jonas' Meinung?", tr: "Jonas'ın görüşü ne?", options: ["Die Läden sollen sonntags schließen", "Die Läden sollen sonntags öffnen dürfen", "Das Thema ist ihm egal", "Er will kürzere Öffnungszeiten"], answer: 1 },
        { de: "Welchen Kompromiss schlägt Meral vor?", tr: "Meral hangi uzlaşmayı öneriyor?", options: ["Sonntags nur kleine Läden", "Längere Öffnungszeiten unter der Woche", "Höhere Löhne am Sonntag", "Gar keinen"], answer: 1 },
        { de: "Wie endet die Diskussion?", tr: "Tartışma nasıl bitiyor?", options: ["Meral ändert ihre Meinung", "Meral bleibt dagegen, versteht aber das Argument", "Jonas gibt seine Meinung auf", "Die beiden streiten sich"], answer: 1 },
      ],
    },
    reading: {
      title: "Leserbrief: Weniger Autos, mehr Platz",
      titleTr: "Okur mektubu",
      genre: "Okur mektubu",
      text: "Leserbrief: Weniger Autos, mehr Platz\n\nSeit Januar ist unsere Hauptstraße für Autos gesperrt. Einerseits verstehe ich den Ärger der Geschäftsleute: Kundschaft, die früher kurz hielt, kommt heute seltener.\n\nAndererseits hat sich etwas verändert, das man kaum in Zahlen fassen kann. Kinder spielen wieder auf der Straße, und abends sitzen Nachbarn draußen, die sich vorher nie gegrüßt haben.\n\nZusammenfassend halte ich die Sperrung für richtig. Man sollte aber prüfen, ob die Lieferzeiten für die Läden ausreichen.\n\nB. Karaca, Nordstadt",
      questions: [
        { de: "Was kritisieren die Geschäftsleute?", tr: "Esnaf neyi eleştiriyor?", options: ["Den Lärm", "Weniger Kundschaft", "Die hohen Mieten", "Die neuen Bäume"], answer: 1 },
        { de: "Wie steht der Autor zur Sperrung?", tr: "Yazar kapatma kararına nasıl bakıyor?", options: ["Er hält sie für falsch", "Er hält sie für richtig", "Er hat keine Meinung", "Er will die Straße ganz abreißen"], answer: 1 },
      ],
    },
    speaking: [
      { situation: "Bir tartışmada görüşünü söylüyorsun.", de: "Meiner Meinung nach überwiegen die Vorteile deutlich.", tr: "Bence avantajlar açık ara ağır basıyor." },
      { situation: "Kibarca karşı çıkıyorsun.", de: "Da wäre ich vorsichtig, das sehe ich etwas anders.", tr: "Burada temkinli olurdum, ben biraz farklı görüyorum." },
    ],
    writing: {
      prompt: "Bir gazetenin okur köşesine kısa bir yazı yaz: şehrindeki bir karar hakkında görüşünü söyle.",
      checklist: [
        "Görüşünü ilk cümlede söyle",
        "Bir artı ve bir eksi yaz",
        "En az bir kez kibarca karşı çık",
        "Sonucu bir cümleyle özetle",
      ],
      minWords: 80,
      phrases: [
        { de: "Meiner Meinung nach …", tr: "Bence …", en: "In my opinion …" },
        { de: "Einerseits …, andererseits …", tr: "Bir yandan …, öte yandan …", en: "On the one hand …, on the other hand …" },
        { de: "Da wäre ich vorsichtig.", tr: "Burada temkinli olurdum.", en: "I would be careful there." },
        { de: "Ich bezweifle, dass …", tr: "…-dığından şüpheliyim", en: "I doubt that …" },
        { de: "Zusammenfassend …", tr: "Özetle …", en: "To sum up …" },
      ],
      sample:
        "Meiner Meinung nach war die Sperrung der Hauptstraße die richtige Entscheidung.\n\nEinerseits verstehe ich die Geschäftsleute: Wer früher kurz vor dem Laden hielt, fährt heute weiter. Andererseits ist der Platz vor den Häusern zurückgekommen. Abends sitzen dort Nachbarn, die sich vorher kaum gegrüßt haben.\n\nBei einem Argument wäre ich allerdings vorsichtig. Es heißt, die Umsätze seien überall gesunken. Ich bezweifle, dass das für alle Läden gilt — Zahlen habe ich dazu nicht gesehen.\n\nZusammenfassend: Die Straße sollte gesperrt bleiben, aber die Lieferzeiten für die Geschäfte müssen verlängert werden.",
    },
  },

  {
    level: "B1",
    index: 7,
    code: "B1.8",
    titleDe: "Das Gesundheitssystem",
    titleTr: "Sağlık sistemi",
    focus: [
      { de: "Verben mit Präposition", tr: "Ich leide unter …" },
      { de: "Passiv im Präsens", tr: "Ein Termin wird vergeben." },
      { de: "Nebensatz mit wenn", tr: "Wenn Sie … einnehmen, …" },
      { de: "Plusquamperfekt", tr: "Nachdem ich gestürzt war, …" },
      { de: "Konjunktiv II", tr: "An Ihrer Stelle würde ich …" },
    ],
    canDo: [
      { de: "Ich kann eine länger andauernde Beschwerde beschreiben.", tr: "Uzun süredir devam eden bir şikâyeti anlatabiliyorum.", en: "I can describe a long-standing complaint." },
      { de: "Ich kann eine Überweisung und einen Termin organisieren.", tr: "Sevk ve randevu işini halledebiliyorum.", en: "I can arrange a referral and an appointment." },
      { de: "Ich kann in der Apotheke nach Wechselwirkungen fragen.", tr: "Eczanede ilaç etkileşimini sorabiliyorum.", en: "I can ask about drug interactions at the pharmacy." },
      { de: "Ich kann erzählen, was in der Notaufnahme passiert ist.", tr: "Acilde ne olduğunu sırasıyla anlatabiliyorum.", en: "I can tell what happened at the emergency room." },
      { de: "Ich kann Ratschläge geben und Hilfe anbieten.", tr: "Tavsiye verip yardım teklif edebiliyorum.", en: "I can give advice and offer help." },
    ],
    listening: {
      title: "Beim Hausarzt",
      titleTr: "Aile hekiminde",
      situation: "Bir hasta aylardır süren sırt ağrısını anlatıyor.",
      turns: [
        { speaker: "Ärztin", de: "Sie sagten am Telefon, es geht schon länger so. Seit wann genau?", tr: "Telefonda bir süredir böyle olduğunu söylediniz. Tam olarak ne zamandan beri?" },
        { speaker: "Herr Yalcin", de: "Seit etwa drei Monaten leide ich unter Rückenschmerzen.", tr: "Yaklaşık üç aydır sırt ağrısı çekiyorum." },
        { speaker: "Ärztin", de: "Sitzen Sie viel?", tr: "Çok oturuyor musunuz?" },
        { speaker: "Herr Yalcin", de: "Acht Stunden am Schreibtisch. Abends sind die Schultern ganz verspannt.", tr: "Günde sekiz saat masada. Akşamları omuzlarım tamamen kasılıyor." },
        { speaker: "Ärztin", de: "Das hängt wahrscheinlich damit zusammen. Heute wird nicht geröntgt — erst wird Physiotherapie versucht.", tr: "Muhtemelen bununla bağlantılı. Bugün röntgen çekilmiyor — önce fizyoterapi denenecek." },
        { speaker: "Herr Yalcin", de: "Brauche ich dafür eine Überweisung?", tr: "Bunun için sevk gerekiyor mu?" },
        { speaker: "Ärztin", de: "Die schreibe ich Ihnen gleich. Die Wartezeit beträgt leider vier bis sechs Wochen.", tr: "Hemen yazıyorum. Bekleme süresi maalesef dört ila altı hafta." },
        { speaker: "Herr Yalcin", de: "Und bis dahin?", tr: "Peki o zamana kadar?" },
        { speaker: "Ärztin", de: "Sie sollten sich jede Stunde kurz dehnen. An Ihrer Stelle würde ich auch den Schreibtisch höher stellen.", tr: "Her saat başı kısaca esnemelisiniz. Sizin yerinizde olsam masayı da yükseltirdim." },
      ],
      questions: [
        { de: "Seit wann hat Herr Yalcin Schmerzen?", tr: "Bay Yalçın'ın ağrısı ne zamandan beri var?", options: ["Seit einer Woche", "Seit etwa drei Monaten", "Seit einem Jahr", "Seit gestern"], answer: 1 },
        { de: "Was wird heute nicht gemacht?", tr: "Bugün ne yapılmıyor?", options: ["Die Überweisung", "Das Röntgen", "Die Untersuchung", "Das Gespräch"], answer: 1 },
        { de: "Was soll Herr Yalcin bis zum Termin tun?", tr: "Bay Yalçın randevuya kadar ne yapmalı?", options: ["Nichts", "Sich jede Stunde kurz dehnen", "Tabletten nehmen", "Nicht mehr arbeiten"], answer: 1 },
      ],
    },
    reading: {
      title: "Praxis Dr. Lang — Informationen",
      titleTr: "Muayenehane bilgi notu",
      genre: "Bilgi notu",
      text: "Praxis Dr. Lang — Informationen für Patientinnen und Patienten\n\nTermine werden nur telefonisch vergeben, montags bis freitags von acht bis elf Uhr. Bitte bringen Sie zu jedem Termin Ihre Versichertenkarte mit.\n\nWenn Sie einen Termin nicht wahrnehmen können, sagen Sie bitte spätestens 24 Stunden vorher ab. Sonst wird eine Gebühr von 20 Euro berechnet.\n\nAkute Notfälle werden ohne Termin behandelt. Kommen Sie in diesem Fall bitte vor zehn Uhr.",
      questions: [
        { de: "Wie werden Termine vergeben?", tr: "Randevular nasıl veriliyor?", options: ["Online", "Nur telefonisch", "Persönlich in der Praxis", "Per E-Mail"], answer: 1 },
        { de: "Was passiert, wenn man zu spät absagt?", tr: "Randevu geç iptal edilirse ne oluyor?", options: ["Nichts", "Eine Gebühr wird berechnet", "Der Termin wird verschoben", "Man bekommt nie wieder einen Termin"], answer: 1 },
      ],
    },
    speaking: [
      { situation: "Doktora sürekli şikâyetini anlatıyorsun.", de: "Ich leide seit drei Monaten unter Rückenschmerzen.", tr: "Üç aydır sırt ağrısı çekiyorum." },
      { situation: "Bir yakınına tavsiye veriyorsun.", de: "An deiner Stelle würde ich das mit dem Hausarzt besprechen.", tr: "Senin yerinde olsam bunu aile hekimiyle konuşurdum." },
    ],
    writing: {
      prompt: "Bir yakınına hastaneye gidişini anlatan bir mesaj yaz.",
      checklist: [
        "Ne olduğunu sırayla anlat",
        "Önce olan bir işi bir basamak geriye çek",
        "En az bir edilgen cümle kullan",
        "Şimdi ne yapman gerektiğini yaz",
      ],
      minWords: 70,
      phrases: [
        { de: "Nachdem ich … war, …", tr: "…-dıktan sonra …", en: "After I had …, …" },
        { de: "Es wird geröntgt.", tr: "Röntgen çekiliyor.", en: "An X-ray is taken." },
        { de: "Ich leide unter …", tr: "…'den muzdaribim", en: "I suffer from …" },
        { de: "Ich muss … zur Beobachtung bleiben.", tr: "Gözlem için … kalmam gerekiyor.", en: "I have to stay … for observation." },
        { de: "Mach dir keine Sorgen.", tr: "Merak etme.", en: "Don't worry." },
      ],
      sample:
        "Hallo Aylin,\n\nkurze Nachricht, damit du dich nicht wunderst: Ich war gestern in der Notaufnahme.\n\nNachdem ich auf der Treppe gestürzt war, konnte ich den Arm kaum bewegen. Eine Nachbarin hat mich hergefahren. Zuerst wurde geröntgt, danach kam eine Ärztin. Zum Glück ist nichts gebrochen — es besteht nur der Verdacht auf eine Zerrung.\n\nIch muss den Arm zwei Wochen schonen und darf nichts Schweres heben. Nächste Woche wird noch einmal kontrolliert.\n\nMach dir keine Sorgen, mir geht es schon besser. Melde dich, wenn du Zeit hast!\n\nLeyla",
    },
  },

  {
    level: "B1",
    index: 8,
    code: "B1.9",
    titleDe: "Umwelt und Stadtleben",
    titleTr: "Çevre ve şehir yaşamı",
    focus: [
      { de: "Passiv im Präsens", tr: "kuralı kişisiz anlatmak" },
      { de: "Passiv im Präteritum", tr: "değişimi anlatmak: wurde saniert" },
      { de: "um … zu + Infinitiv", tr: "önerinin amacı" },
      { de: "zweiteilige Konnektoren", tr: "einerseits … andererseits" },
      { de: "immer + Komparativ", tr: "gitgide artan değişim" },
    ],
    canDo: [
      { de: "Ich kann Regeln zur Mülltrennung verstehen und erklären.", tr: "Çöp ayrıştırma kurallarını anlayıp anlatabiliyorum.", en: "I can understand and explain recycling rules." },
      { de: "Ich kann einen Vorschlag machen und ihn begründen.", tr: "Bir öneri sunup gerekçelendirebiliyorum.", en: "I can make a proposal and justify it." },
      { de: "Ich kann über Verkehr und Mobilität diskutieren.", tr: "Ulaşım üzerine tartışabiliyorum.", en: "I can discuss traffic and mobility." },
      { de: "Ich kann beschreiben, wie sich mein Viertel verändert hat.", tr: "Mahallemin nasıl değiştiğini anlatabiliyorum.", en: "I can describe how my neighbourhood has changed." },
      { de: "Ich kann sagen, warum ich mich engagiere.", tr: "Neden gönüllü çalıştığımı söyleyebiliyorum.", en: "I can say why I volunteer." },
    ],
    listening: {
      title: "Das Nachbarschaftstreffen",
      titleTr: "Komşu toplantısı",
      situation: "Apartman sakinleri ortak bahçe kurmayı konuşuyor.",
      turns: [
        { speaker: "Frau Bauer", de: "Wir wollen den Innenhof zu einem Gemeinschaftsgarten machen. Wer beteiligt sich?", tr: "İç avluyu ortak bahçeye çevirmek istiyoruz. Kim katılıyor?" },
        { speaker: "Herr Ercan", de: "Ich gern. Aber wer kümmert sich im Urlaub um die Beete?", tr: "Ben memnuniyetle. Ama tatilde tarhlarla kim ilgilenecek?" },
        { speaker: "Frau Bauer", de: "Wir machen einen Plan. Jede Woche wird eine andere Familie eingeteilt.", tr: "Bir plan yapacağız. Her hafta başka bir aile görevlendiriliyor." },
        { speaker: "Herr Ercan", de: "Und die Ernte?", tr: "Peki hasat?" },
        { speaker: "Frau Bauer", de: "Die Ernte wird unter allen geteilt, die mitarbeiten.", tr: "Hasat, çalışanlar arasında paylaşılıyor." },
        { speaker: "Herr Ercan", de: "Was ist mit den Kosten? Erde und Werkzeug sind nicht billig.", tr: "Peki masraflar? Toprak ve alet ucuz değil." },
        { speaker: "Frau Bauer", de: "Die Stadt zahlt die Hälfte, um solche Projekte zu fördern. Den Rest teilen wir.", tr: "Belediye böyle projeleri desteklemek için yarısını ödüyor. Kalanı biz paylaşıyoruz." },
        { speaker: "Herr Ercan", de: "Gut. Dann bin ich dabei.", tr: "Peki. O zaman ben varım." },
      ],
      questions: [
        { de: "Was soll im Innenhof entstehen?", tr: "İç avluda ne kurulacak?", options: ["Ein Parkplatz", "Ein Gemeinschaftsgarten", "Ein Spielplatz", "Ein Fahrradkeller"], answer: 1 },
        { de: "Wer bekommt etwas von der Ernte?", tr: "Hasattan kim pay alıyor?", options: ["Alle im Haus", "Nur wer mitarbeitet", "Nur Familien mit Kindern", "Die Stadt"], answer: 1 },
        { de: "Wer zahlt die Hälfte der Kosten?", tr: "Masrafın yarısını kim ödüyor?", options: ["Die Nachbarn", "Die Stadt", "Der Vermieter", "Niemand"], answer: 1 },
      ],
    },
    reading: {
      title: "Information zur Mülltrennung",
      titleTr: "Çöp ayrıştırma duyurusu",
      genre: "Duyuru",
      text: "Stadt Köln — Information zur Mülltrennung\n\nAb dem 1. September werden die gelben Säcke nur noch alle zwei Wochen abgeholt, jeweils montags. Bitte stellen Sie die Säcke erst am Vorabend heraus.\n\nAltglas wird nach Farben sortiert und zu den Containern an der Ecke Lindenstraße gebracht. Der Einwurf ist täglich von sieben bis zwanzig Uhr erlaubt — nicht an Sonn- und Feiertagen.\n\nWer Sperrmüll hat, meldet ihn online an. Eine Abholung pro Jahr ist kostenlos.",
      questions: [
        { de: "Wie oft werden die gelben Säcke abgeholt?", tr: "Sarı torbalar ne sıklıkta toplanıyor?", options: ["Jede Woche", "Alle zwei Wochen", "Einmal im Monat", "Täglich"], answer: 1 },
        { de: "Wann darf man kein Altglas einwerfen?", tr: "Cam ne zaman atılamaz?", options: ["Vormittags", "Am Samstag", "An Sonn- und Feiertagen", "Vor sieben Uhr und nach zwanzig Uhr sowie an Sonn- und Feiertagen"], answer: 3 },
      ],
    },
    speaking: [
      { situation: "Komşuna çöp kuralını açıklıyorsun.", de: "Das Altglas wird nach Farben sortiert.", tr: "Cam renklerine göre ayrılıyor." },
      { situation: "Bir öneriyi gerekçelendiriyorsun.", de: "Um Strom zu sparen, sollten wir die Beleuchtung umstellen.", tr: "Elektrik tasarrufu için aydınlatmayı değiştirmeliyiz." },
    ],
    writing: {
      prompt: "Belediyeye mahallen için bir öneri mektubu yaz.",
      checklist: [
        "Neyi önerdiğini ilk cümlede yaz",
        "Önerinin amacını „um … zu“ ile yaz",
        "En az bir edilgen cümle kullan",
        "Olası bir itirazı önceden karşıla",
      ],
      minWords: 80,
      phrases: [
        { de: "Ich möchte anregen, dass …", tr: "…-mesini önermek istiyorum", en: "I would like to suggest that …" },
        { de: "Um … zu …, …", tr: "… için …", en: "In order to …, …" },
        { de: "Es wird … eingerichtet.", tr: "… kuruluyor.", en: "… is being set up." },
        { de: "Einerseits …, andererseits …", tr: "Bir yandan …, öte yandan …", en: "On the one hand …, on the other hand …" },
        { de: "Über eine Rückmeldung würde ich mich freuen.", tr: "Bir geri dönüş beni sevindirir.", en: "I would appreciate a reply." },
      ],
      sample:
        "Sehr geehrte Damen und Herren,\n\nich möchte anregen, dass der Innenhof in der Lindenstraße 8 zu einem Gemeinschaftsgarten wird.\n\nUm die Fläche wieder nutzbar zu machen, bräuchten wir nur wenige Beete und einen Wasseranschluss. Die Arbeit würde von den Bewohnerinnen und Bewohnern übernommen; ein Plan für die Pflege ist bereits abgesprochen. Die Ernte wird unter allen geteilt, die mitmachen.\n\nEinerseits kostet ein solches Projekt am Anfang Geld, andererseits spart die Stadt langfristig bei der Pflege der Fläche. Außerdem sind Nachbarn, die sich kennen, ein Gewinn für das ganze Viertel.\n\nÜber eine Rückmeldung würde ich mich sehr freuen.\n\nMit freundlichen Grüßen\nSelin Ercan",
    },
  },

  {
    level: "B1",
    index: 9,
    code: "B1.10",
    titleDe: "Wünsche und Rückblick",
    titleTr: "Duygular ve hayaller",
    focus: [
      { de: "irrealer Konjunktiv II", tr: "Wenn ich … wäre, würde ich …" },
      { de: "Konjunktiv II der Vergangenheit", tr: "Ich hätte … sollen" },
      { de: "als und wenn", tr: "bir kerelik geçmiş mi tekrar mı" },
      { de: "Plusquamperfekt", tr: "önce olanı geriye çekmek" },
      { de: "damit", tr: "amaç: özne değiştiğinde" },
    ],
    canDo: [
      { de: "Ich kann über eine nicht wirkliche Situation sprechen.", tr: "Gerçek olmayan bir durumu konuşabiliyorum.", en: "I can talk about a hypothetical situation." },
      { de: "Ich kann sagen, was ich bereue.", tr: "Neyden pişman olduğumu söyleyebiliyorum.", en: "I can say what I regret." },
      { de: "Ich kann Gefühle und Sehnsucht beschreiben.", tr: "Duygularımı ve özlemimi anlatabiliyorum.", en: "I can describe feelings and longing." },
      { de: "Ich kann einen Konflikt ansprechen, ohne Vorwürfe zu machen.", tr: "Bir anlaşmazlığı suçlamadan konuşabiliyorum.", en: "I can raise a conflict without making accusations." },
      { de: "Ich kann meinen eigenen Weg zusammenfassen.", tr: "Kendi yolumu özetleyebiliyorum.", en: "I can sum up my own path." },
    ],
    listening: {
      title: "Wenn ich noch mal anfangen könnte",
      titleTr: "Yeniden başlayabilseydim",
      situation: "İki arkadaş yıllar sonra geriye bakıyor.",
      turns: [
        { speaker: "Deniz", de: "Wenn du noch mal anfangen könntest — würdest du wieder herkommen?", tr: "Yeniden başlayabilseydin — gene buraya gelir miydin?" },
        { speaker: "Kerem", de: "Sofort. Aber ich hätte früher angefangen, Deutsch zu lernen.", tr: "Hemen. Ama Almanca öğrenmeye daha erken başlardım." },
        { speaker: "Deniz", de: "Warum?", tr: "Neden?" },
        { speaker: "Kerem", de: "Die ersten zwei Jahre habe ich nur geschwiegen. Ich wünschte, ich hätte mich früher getraut.", tr: "İlk iki yıl sadece sustum. Keşke daha erken cesaret etseydim." },
        { speaker: "Deniz", de: "Bereust du es?", tr: "Pişman mısın?" },
        { speaker: "Kerem", de: "Im Nachhinein nicht. Nachdem ich den ersten Kurs gemacht hatte, ging alles schneller.", tr: "Sonradan bakınca değil. İlk kursu yaptıktan sonra her şey hızlandı." },
        { speaker: "Deniz", de: "Und heute?", tr: "Peki bugün?" },
        { speaker: "Kerem", de: "Ohne Deutsch hätte ich meine Arbeit nie bekommen. Beides gehört zu mir — die Heimat und hier.", tr: "Almanca olmasaydı işimi hiç alamazdım. İkisi de bana ait — memleket ve burası." },
      ],
      questions: [
        { de: "Was würde Kerem anders machen?", tr: "Kerem neyi farklı yapardı?", options: ["Er würde nicht herkommen", "Er würde früher Deutsch lernen", "Er würde eine andere Arbeit suchen", "Er würde zurückgehen"], answer: 1 },
        { de: "Was hat sich nach dem ersten Kurs verändert?", tr: "İlk kurstan sonra ne değişti?", options: ["Nichts", "Alles ging schneller", "Er hat aufgehört", "Er ist umgezogen"], answer: 1 },
        { de: "Wie sieht Kerem seine zwei Länder?", tr: "Kerem iki ülkesini nasıl görüyor?", options: ["Nur die Heimat zählt", "Beide gehören zu ihm", "Er fühlt sich nirgends zu Hause", "Er möchte die Heimat vergessen"], answer: 1 },
      ],
    },
    reading: {
      title: "Zwischen zwei Sprachen",
      titleTr: "İki dil arasında",
      genre: "Kişisel yazı",
      text: "Zwischen zwei Sprachen\n\nAls ich vor neun Jahren ankam, verstand ich kein Wort. Ich hatte einen Koffer, eine Adresse und die feste Absicht, nach einem Jahr zurückzugehen.\n\nHeute weiß ich: Wenn ich damals zurückgegangen wäre, hätte ich vieles nicht erlebt. Ich hätte meine Freundinnen hier nie kennengelernt, und ich hätte nie erfahren, wie es sich anfühlt, in einer zweiten Sprache zu träumen.\n\nSehnsucht bleibt trotzdem. Aber sie ist kein Schmerz mehr, sondern ein Teil von mir. Meine Wurzeln sind dort — mein Alltag ist hier. Beides gehört zusammen.",
      questions: [
        { de: "Was wollte die Person am Anfang?", tr: "Kişi başlangıçta ne istiyordu?", options: ["Für immer bleiben", "Nach einem Jahr zurückgehen", "Sofort arbeiten", "Eine Wohnung kaufen"], answer: 1 },
        { de: "Wie sieht die Person die Sehnsucht heute?", tr: "Kişi özlemi bugün nasıl görüyor?", options: ["Als Schmerz", "Als einen Teil von sich", "Als Fehler", "Sie hat keine Sehnsucht mehr"], answer: 1 },
      ],
    },
    speaking: [
      { situation: "Gerçekleşmemiş bir dileği söylüyorsun.", de: "Ich wünschte, ich hätte früher damit angefangen.", tr: "Keşke buna daha erken başlasaydım." },
      { situation: "Bir olasılığı anlatıyorsun.", de: "Ohne diesen Kurs würde ich immer noch schweigen.", tr: "Bu kurs olmasaydı hâlâ susuyor olurdum." },
    ],
    writing: {
      prompt: "B1'i bitirdin. Kendi öğrenme yolunu anlatan bir metin yaz.",
      checklist: [
        "Nasıl başladığını „als“ ile anlat",
        "En zorunun ne olduğunu yaz",
        "Bir gerçekdışı cümle kur („Ohne … hätte ich …“)",
        "Sırada ne olduğunu yaz",
      ],
      minWords: 80,
      phrases: [
        { de: "Als ich anfing, …", tr: "Başladığımda …", en: "When I started, …" },
        { de: "Am schwersten war es, … zu …", tr: "En zoru … yapmaktı", en: "The hardest thing was to …" },
        { de: "Ohne … hätte ich …", tr: "… olmasaydı …", en: "Without … I would have …" },
        { de: "Ich bin stolz darauf, dass …", tr: "…-dığım için gurur duyuyorum", en: "I am proud that …" },
        { de: "Als Nächstes möchte ich …", tr: "Sırada … var", en: "Next I would like to …" },
      ],
      sample:
        "Als ich vor drei Jahren mit Deutsch anfing, konnte ich nur „Hallo“ und „Danke“ sagen. Im Supermarkt habe ich auf die Zahlen an der Kasse gestarrt, weil ich sie nicht verstanden habe.\n\nAm schwersten war es, den Mund aufzumachen. Grammatik kann man üben, aber Angst nicht. Nachdem ich das erste Mal mit einer Nachbarin geredet hatte, wurde es leichter — sie hat einfach gewartet, bis ich meinen Satz zu Ende gebracht habe.\n\nOhne Deutsch hätte ich meine jetzige Stelle nie bekommen. Ich bin stolz darauf, dass ich nicht aufgegeben habe, obwohl ich oft müde war.\n\nAls Nächstes möchte ich B2 machen und irgendwann eine Weiterbildung auf Deutsch.",
    },
  },
];
