import type { SkillExercise } from "../types";

/** B1 — okuma, dinleme ve yazma egzersizleri. */
export const b1: SkillExercise[] = [
  // ── Okuma ──────────────────────────────────────────────────────────────
  {
    id: "b1-r1",
    level: "B1",
    skill: "reading",
    title: "Zweites Leben für alte Geräte",
    genre: "Makale",
    intro: "Leipzig'deki bir tamir kafesini tanıtan bu gazete makalesini oku ve soruları yanıtla.",
    minutes: 5,
    text: "In Deutschland landen jedes Jahr Tausende Tonnen Elektrogeräte im Müll, obwohl viele davon noch repariert werden könnten. Gegen diese Verschwendung engagiert sich das Repair-Café in Leipzig-Plagwitz. Jeden ersten Samstag im Monat treffen sich dort ehrenamtliche Helferinnen und Helfer, die kaputte Toaster, Lampen oder Fahrräder gemeinsam mit den Besitzern reparieren.\n\n„Bei uns wird nichts einfach weggeworfen“, erklärt Organisatorin Karin Melzer. „Etwa siebzig Prozent der Geräte, die zu uns gebracht werden, funktionieren danach wieder.“ Die Reparatur selbst ist kostenlos, nur Ersatzteile müssen bezahlt werden. Wer möchte, kann eine kleine Spende dalassen, mit der Werkzeug und Miete finanziert werden.\n\nDas Angebot wird immer beliebter: Kamen im ersten Jahr rund zwanzig Besucher pro Termin, sind es heute oft mehr als sechzig. Melzer wünscht sich trotzdem mehr Unterstützung von der Stadt, zum Beispiel größere Räume. Außerdem sucht das Team dringend Freiwillige, die sich mit Computern auskennen, denn gerade elektronische Geräte werden immer häufiger gebracht.",
    gloss: [
      { de: "das Gerät", tr: "cihaz, alet" },
      { de: "die Verschwendung", tr: "israf" },
      { de: "ehrenamtlich", tr: "gönüllü olarak" },
      { de: "das Ersatzteil", tr: "yedek parça" },
      { de: "die Spende", tr: "bağış" },
      { de: "das Werkzeug", tr: "takım, alet edevat" },
      { de: "die Miete", tr: "kira" },
      { de: "die Unterstützung", tr: "destek" },
      { de: "der Freiwillige", tr: "gönüllü (kişi)" },
      { de: "sich auskennen mit", tr: "bir konudan iyi anlamak" },
    ],
    questions: [
      {
        text: "Worum geht es in dem Text?",
        options: [
          "Um ein Geschäft, das gebrauchte Geräte verkauft",
          "Um ein Projekt, bei dem Geräte gemeinsam repariert werden",
          "Um eine Firma, die Elektromüll ins Ausland transportiert",
        ],
        answer: 1,
        explain: "Metin, Leipzig'deki Repair-Café'yi anlatıyor: gönüllüler bozuk eşyaları sahipleriyle birlikte tamir ediyor („gemeinsam mit den Besitzern reparieren“). Satış ya da nakliye söz konusu değil.",
      },
      {
        text: "Für die Reparatur selbst muss man nichts bezahlen, nur für Ersatzteile.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Metinde açıkça geçiyor: „Die Reparatur selbst ist kostenlos, nur Ersatzteile müssen bezahlt werden.“ Bağış ise tamamen isteğe bağlı.",
      },
      {
        text: "Wie viele der gebrachten Geräte funktionieren nach der Reparatur wieder?",
        options: ["Fast alle", "Etwa siebzig Prozent", "Weniger als die Hälfte"],
        answer: 1,
        explain: "Karin Melzer'in sözlerinde geçiyor: „Etwa siebzig Prozent der Geräte … funktionieren danach wieder.“",
      },
      {
        text: "Was wünscht sich Karin Melzer von der Stadt?",
        options: ["Größere Räume", "Mehr Geld für Ersatzteile", "Kostenlose Werbung"],
        answer: 0,
        explain: "Son paragrafta şehirden daha fazla destek istediği, örnek olarak da büyük mekân („zum Beispiel größere Räume“) verildiği belirtiliyor.",
      },
      {
        text: "Das Repair-Café sucht besonders Freiwillige, die sich mit Computern auskennen.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Son cümlede ekibin acilen bilgisayardan anlayan gönüllüler aradığı yazıyor, çünkü elektronik cihazlar giderek daha sık getiriliyor.",
      },
    ],
  },
  {
    id: "b1-r2",
    level: "B1",
    skill: "reading",
    title: "Mein Monat ohne Instagram",
    genre: "Blog yazısı",
    intro: "Bir blog yazarının sosyal medyadan uzak geçirdiği bir ayı anlattığı bu yazıyı oku.",
    minutes: 4,
    text: "Vor sechs Wochen habe ich ein Experiment gestartet: einen Monat ohne Instagram, TikTok und Co. Der Grund war einfach — laut meiner Handy-Statistik verbrachte ich täglich fast drei Stunden in sozialen Netzwerken, oft ohne es zu merken.\n\nDie ersten Tage waren schwieriger als gedacht. Ständig griff ich automatisch zum Handy, nur um festzustellen, dass die Apps gelöscht waren. Nach etwa einer Woche wurde es besser. Ich las abends wieder Bücher, traf mich häufiger mit Freunden und schlief deutlich besser, weil ich das Handy nicht mehr mit ins Bett nahm.\n\nNatürlich gab es auch Nachteile. Von manchen Verabredungen erfuhr ich zu spät, weil sie nur in einer Gruppe gepostet wurden. Und ehrlich gesagt fehlten mir die lustigen Videos manchmal.\n\nMein Fazit: Ganz verzichten möchte ich nicht, aber ich habe mir feste Regeln gesetzt. Die Apps sind vom Startbildschirm verschwunden, und nach 21 Uhr bleibt das Handy in der Küche. Probiert es aus — es lohnt sich!",
    gloss: [
      { de: "das Experiment", tr: "deney" },
      { de: "verbringen", tr: "(zaman) geçirmek" },
      { de: "feststellen", tr: "fark etmek, saptamak" },
      { de: "die Verabredung", tr: "buluşma, sözleşilen randevu" },
      { de: "erfahren von", tr: "bir şeyden haberdar olmak" },
      { de: "verzichten auf", tr: "bir şeyden vazgeçmek" },
      { de: "das Fazit", tr: "sonuç, çıkarım" },
      { de: "die Regel", tr: "kural" },
      { de: "sich lohnen", tr: "değmek, zahmete değer olmak" },
    ],
    questions: [
      {
        text: "Warum hat die Autorin das Experiment gestartet?",
        options: [
          "Ihre Freunde haben es ihr empfohlen",
          "Ihr Handy war kaputt",
          "Sie verbrachte täglich sehr viel Zeit in sozialen Netzwerken",
        ],
        answer: 2,
        explain: "Gerekçe ilk paragrafta: telefon istatistiğine göre günde neredeyse üç saatini sosyal ağlarda geçiriyordu („fast drei Stunden in sozialen Netzwerken“).",
      },
      {
        text: "Der Verzicht fiel der Autorin von Anfang an leicht.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Tam tersi: „Die ersten Tage waren schwieriger als gedacht“ — ilk günler beklediğinden zor geçmiş, ancak bir hafta sonra rahatlamış.",
      },
      {
        text: "Was war ein Vorteil des Experiments?",
        options: [
          "Sie hat deutlich besser geschlafen",
          "Sie hat neue Apps entdeckt",
          "Sie hat mehr Zeit im Internet verbracht",
        ],
        answer: 0,
        explain: "İkinci paragrafta telefonu yatağa götürmediği için çok daha iyi uyuduğunu („schlief deutlich besser“) yazıyor.",
      },
      {
        text: "Welchen Nachteil nennt die Autorin?",
        options: [
          "Ihre Freunde waren beleidigt",
          "Sie erfuhr von manchen Verabredungen zu spät",
          "Sie konnte nicht mehr für die Arbeit recherchieren",
        ],
        answer: 1,
        explain: "Dezavantaj olarak bazı buluşmalardan geç haberdar olduğunu söylüyor, çünkü bunlar yalnızca bir grupta paylaşılıyordu.",
      },
      {
        text: "Wie benutzt die Autorin soziale Netzwerke heute?",
        options: [
          "Gar nicht mehr",
          "Genauso wie früher",
          "Mit festen Regeln, zum Beispiel ohne Handy nach 21 Uhr",
        ],
        answer: 2,
        explain: "Sonuç bölümünde tamamen bırakmak istemediğini ama kendine kesin kurallar koyduğunu belirtiyor: uygulamalar ana ekrandan kalktı, akşam 21'den sonra telefon mutfakta kalıyor.",
      },
    ],
  },
  {
    id: "b1-r3",
    level: "B1",
    skill: "reading",
    title: "Ihr Praktikum bei Medienhaus Süd",
    genre: "E-posta",
    intro: "Bir yayınevinin staj başvurusuna verdiği bu yarı resmi yanıtı oku ve ayrıntıları yakala.",
    minutes: 4,
    text: "Liebe Frau Yılmaz,\n\nvielen Dank für Ihre Bewerbung um ein Praktikum in unserer Online-Redaktion. Wir freuen uns, Ihnen mitteilen zu können, dass wir Ihnen den Platz anbieten möchten. Das Praktikum beginnt am 1. März und dauert acht Wochen. Die Arbeitszeit ist montags bis freitags von 9 bis 15 Uhr, an zwei Tagen pro Woche können Sie von zu Hause arbeiten.\n\nIn den ersten zwei Wochen werden Sie von unserer Redakteurin Frau Sommer betreut. Sie zeigt Ihnen, wie Artikel für unsere Webseite geschrieben und Fotos bearbeitet werden. Danach dürfen Sie eigene kleine Beiträge veröffentlichen.\n\nLeider können wir das Praktikum nicht bezahlen, aber Sie erhalten ein Ticket für den Nahverkehr und ein Mittagessen in unserer Kantine. Bitte teilen Sie uns bis zum 15. Februar mit, ob Sie das Angebot annehmen. Falls Sie noch Fragen haben, können Sie mich gern anrufen.\n\nMit freundlichen Grüßen\nKatrin Albrecht\nPersonalabteilung",
    gloss: [
      { de: "die Bewerbung", tr: "başvuru" },
      { de: "das Praktikum", tr: "staj" },
      { de: "die Redaktion", tr: "yazı işleri, redaksiyon" },
      { de: "betreuen", tr: "ilgilenmek, rehberlik etmek" },
      { de: "bearbeiten", tr: "işlemek, düzenlemek" },
      { de: "der Beitrag", tr: "yazı, katkı" },
      { de: "veröffentlichen", tr: "yayımlamak" },
      { de: "der Nahverkehr", tr: "şehir içi toplu taşıma" },
      { de: "die Kantine", tr: "yemekhane" },
      { de: "ein Angebot annehmen", tr: "bir teklifi kabul etmek" },
    ],
    questions: [
      {
        text: "Warum schreibt Frau Albrecht diese E-Mail?",
        options: [
          "Sie lädt Frau Yılmaz zu einem Vorstellungsgespräch ein",
          "Sie sagt das Praktikum leider ab",
          "Sie bietet Frau Yılmaz einen Praktikumsplatz an",
        ],
        answer: 2,
        explain: "İlk paragrafta açıkça yazıyor: „dass wir Ihnen den Platz anbieten möchten“ — staj yeri teklif ediliyor, görüşme daveti ya da ret söz konusu değil.",
      },
      {
        text: "Frau Yılmaz muss an allen fünf Arbeitstagen ins Büro kommen.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: haftada iki gün evden çalışabilir („an zwei Tagen pro Woche können Sie von zu Hause arbeiten“).",
      },
      {
        text: "Welche Aufgabe hat Frau Sommer?",
        options: [
          "Sie betreut Frau Yılmaz in den ersten zwei Wochen",
          "Sie leitet die Personalabteilung",
          "Sie organisiert das Mittagessen in der Kantine",
        ],
        answer: 0,
        explain: "İkinci paragrafa göre ilk iki hafta redaktör Frau Sommer rehberlik edecek; personel bölümünü yöneten kişi ise e-postayı yazan Frau Albrecht.",
      },
      {
        text: "Was bekommt Frau Yılmaz für ihre Arbeit?",
        options: [
          "Ein monatliches Gehalt",
          "Ein Nahverkehrsticket und ein Mittagessen",
          "Einen eigenen Laptop",
        ],
        answer: 1,
        explain: "Staj ücretsiz („können wir das Praktikum nicht bezahlen“), ama toplu taşıma bileti ve yemekhanede öğle yemeği veriliyor.",
      },
      {
        text: "Bis wann soll Frau Yılmaz antworten?",
        options: ["Bis zum 1. März", "Innerhalb von acht Wochen", "Bis zum 15. Februar"],
        answer: 2,
        explain: "Son paragrafta teklifi kabul edip etmediğini 15 Şubat'a kadar bildirmesi isteniyor. 1 Mart stajın başlangıcı, sekiz hafta ise süresi — tipik çeldiriciler.",
      },
    ],
  },
  {
    id: "b1-r4",
    level: "B1",
    skill: "reading",
    title: "Gesund essen im Büroalltag",
    genre: "Kılavuz",
    intro: "Tüketici danışma merkezinin ofis çalışanlarına yönelik beslenme önerilerini oku.",
    minutes: 4,
    text: "Wer den ganzen Tag im Büro sitzt, greift in der Mittagspause oft zu Fast Food oder Fertiggerichten. Dabei lässt sich gesunde Ernährung auch mit wenig Zeit organisieren. Die Verbraucherzentrale Hessen gibt dazu einige praktische Tipps.\n\nErstens: Planen Sie Ihre Mahlzeiten am Wochenende. Wenn Suppen oder Salate schon vorbereitet sind, müssen sie am Abend nur noch eingepackt werden. Dieses sogenannte Meal-Prep spart nicht nur Zeit, sondern auch Geld, weil weniger Lebensmittel weggeworfen werden.\n\nZweitens: Trinken Sie genug. Viele Beschäftigte trinken zu wenig, was zu Kopfschmerzen und Müdigkeit führen kann. Eine Flasche Wasser auf dem Schreibtisch hilft, daran zu denken.\n\nDrittens: Essen Sie nicht am Arbeitsplatz. Wer vor dem Bildschirm isst, isst meistens schneller und mehr. Besser ist eine echte Pause, am besten mit einem kurzen Spaziergang.\n\nÜbrigens: Süßigkeiten müssen nicht komplett verboten werden. Ein Stück Schokolade am Nachmittag ist erlaubt — es sollte nur nicht die ganze Tafel sein.",
    gloss: [
      { de: "die Ernährung", tr: "beslenme" },
      { de: "das Fertiggericht", tr: "hazır yemek" },
      { de: "die Mahlzeit", tr: "öğün" },
      { de: "vorbereiten", tr: "hazırlamak" },
      { de: "einpacken", tr: "paketlemek, yanına almak" },
      { de: "der Beschäftigte", tr: "çalışan" },
      { de: "die Müdigkeit", tr: "yorgunluk" },
      { de: "der Bildschirm", tr: "ekran" },
      { de: "der Spaziergang", tr: "yürüyüş" },
      { de: "die Tafel Schokolade", tr: "tablet çikolata" },
    ],
    questions: [
      {
        text: "An wen richtet sich der Text vor allem?",
        options: [
          "An Menschen, die im Büro arbeiten",
          "An Köchinnen und Köche in Kantinen",
          "An Sportlerinnen und Sportler",
        ],
        answer: 0,
        explain: "Metin ilk cümlede hedef kitleyi belirtiyor: bütün gün ofiste oturanlar („Wer den ganzen Tag im Büro sitzt“).",
      },
      {
        text: "Welchen Vorteil hat Meal-Prep laut dem Text?",
        options: [
          "Das Essen schmeckt besser",
          "Man spart Zeit und Geld",
          "Man muss nie mehr kochen",
        ],
        answer: 1,
        explain: "İkinci paragrafa göre Meal-Prep hem zaman hem para kazandırıyor („spart nicht nur Zeit, sondern auch Geld“), çünkü daha az yiyecek çöpe gidiyor.",
      },
      {
        text: "Wer zu wenig trinkt, kann Kopfschmerzen und Müdigkeit bekommen.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Üçüncü paragrafta az su içmenin baş ağrısına ve yorgunluğa yol açabileceği („was zu Kopfschmerzen und Müdigkeit führen kann“) söyleniyor.",
      },
      {
        text: "Warum soll man nicht am Schreibtisch essen?",
        options: [
          "Weil es in vielen Büros verboten ist",
          "Weil sich die Kollegen gestört fühlen",
          "Weil man dort schneller und mehr isst",
        ],
        answer: 2,
        explain: "Gerekçe metinde: ekran karşısında yemek yiyen kişi genellikle daha hızlı ve daha çok yer („isst meistens schneller und mehr“). Yasak ya da rahatsız olan meslektaşlardan söz edilmiyor.",
      },
      {
        text: "Der Text empfiehlt, komplett auf Süßigkeiten zu verzichten.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: tatlılar tamamen yasak değil („müssen nicht komplett verboten werden“) — öğleden sonra bir parça çikolataya izin var, yeter ki bütün tablet olmasın.",
      },
    ],
  },
  {
    id: "b1-r5",
    level: "B1",
    skill: "reading",
    title: "Mehr Platz für Menschen statt Autos",
    genre: "Okur mektubu",
    intro: "Yaya bölgesi tartışmasına katılan bir okurun gazeteye yazdığı mektubu oku.",
    minutes: 4,
    text: "Leserbrief zum Artikel „Streit um die neue Fußgängerzone“ vom 12. Mai\n\nSehr geehrte Redaktion,\n\nmit großem Interesse habe ich Ihren Artikel über die geplante Fußgängerzone in der Bahnhofstraße gelesen. Als Anwohnerin kann ich die Kritik einiger Geschäftsleute nicht verstehen. Sie befürchten, dass weniger Kunden kommen, wenn man nicht mehr direkt vor den Läden parken kann. Studien aus anderen Städten zeigen jedoch das Gegenteil: Wo weniger Autos fahren, bleiben die Menschen länger und kaufen sogar mehr ein.\n\nIch wohne seit fünfzehn Jahren in dieser Straße und erlebe den Lärm und die schlechte Luft jeden Tag. Meine Kinder können hier nicht draußen spielen, weil ständig Autos vorbeifahren. Eine Fußgängerzone mit Bänken und Bäumen würde die Lebensqualität für alle verbessern.\n\nNatürlich müssen auch Lösungen für ältere Menschen gefunden werden, die nicht gut zu Fuß unterwegs sind. Ein kleiner Elektrobus, wie es ihn in Freiburg gibt, wäre eine Möglichkeit.\n\nMit freundlichen Grüßen\nSabine Krüger",
    gloss: [
      { de: "der Leserbrief", tr: "okur mektubu" },
      { de: "die Fußgängerzone", tr: "yaya bölgesi" },
      { de: "die Anwohnerin", tr: "(o sokakta oturan) kadın sakin" },
      { de: "die Geschäftsleute", tr: "esnaf, iş insanları" },
      { de: "befürchten", tr: "endişe etmek, korkmak" },
      { de: "das Gegenteil", tr: "tam tersi" },
      { de: "der Lärm", tr: "gürültü" },
      { de: "die Lebensqualität", tr: "yaşam kalitesi" },
      { de: "die Lösung", tr: "çözüm" },
      { de: "zu Fuß unterwegs sein", tr: "yaya olarak hareket etmek" },
    ],
    questions: [
      {
        text: "Welche Meinung vertritt Sabine Krüger?",
        options: [
          "Sie ist gegen die geplante Fußgängerzone",
          "Sie unterstützt die geplante Fußgängerzone",
          "Sie findet das Thema nicht wichtig",
        ],
        answer: 1,
        explain: "Mektubun tamamı yaya bölgesini savunuyor: esnafın eleştirisini anlamadığını söylüyor ve bölgenin yaşam kalitesini artıracağını („würde die Lebensqualität für alle verbessern“) yazıyor.",
      },
      {
        text: "Was befürchten einige Geschäftsleute?",
        options: [
          "Dass die Mieten steigen",
          "Dass die Straße zu laut wird",
          "Dass weniger Kunden kommen",
        ],
        answer: 2,
        explain: "İlk paragrafa göre esnaf, dükkânların önüne park edilemeyince müşteri sayısının düşmesinden korkuyor („dass weniger Kunden kommen“).",
      },
      {
        text: "Laut Studien kaufen Menschen in autofreien Straßen sogar mehr ein.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Frau Krüger başka şehirlerdeki araştırmalara dayanıyor: az araba geçen yerlerde insanlar daha uzun kalıyor ve daha çok alışveriş yapıyor („bleiben die Menschen länger und kaufen sogar mehr ein“).",
      },
      {
        text: "Welches Problem erlebt Frau Krüger in ihrer Straße?",
        options: [
          "Lärm und schlechte Luft",
          "Zu wenige Geschäfte",
          "Fehlende Parkplätze für Anwohner",
        ],
        answer: 0,
        explain: "İkinci paragrafta on beş yıldır bu sokakta yaşadığını, her gün gürültüye ve kötü havaya („den Lärm und die schlechte Luft“) maruz kaldığını anlatıyor.",
      },
      {
        text: "Was schlägt sie für ältere Menschen vor?",
        options: [
          "Einen kostenlosen Lieferservice",
          "Einen kleinen Elektrobus wie in Freiburg",
          "Mehr Parkplätze direkt vor den Läden",
        ],
        answer: 1,
        explain: "Son paragrafta yürümekte zorlanan yaşlılar için Freiburg'daki gibi küçük bir elektrikli otobüsü çözüm olarak öneriyor.",
      },
    ],
  },
  {
    id: "b1-r6",
    level: "B1",
    skill: "reading",
    title: "Vier Tage arbeiten, fünf Tage bezahlt werden",
    genre: "Dergi makalesi",
    intro: "Dört günlük çalışma haftasını deneyen şirketleri konu alan bu dergi makalesini oku.",
    minutes: 5,
    text: "Immer mehr deutsche Unternehmen testen die Vier-Tage-Woche. Die Idee: Die Beschäftigten arbeiten nur noch vier Tage, bekommen aber das gleiche Gehalt wie vorher. Eine der ersten Firmen war die Werbeagentur „Kolibri“ aus Köln, die das Modell seit zwei Jahren anbietet.\n\nGeschäftsführer Jan Petersen ist zufrieden: „Unsere Mitarbeiterinnen und Mitarbeiter sind seltener krank und deutlich motivierter. Außerdem bekommen wir viel mehr Bewerbungen als früher.“ Damit die Arbeit trotzdem geschafft wird, wurden die Meetings verkürzt und viele Aufgaben digitalisiert.\n\nDoch nicht überall funktioniert das Modell. In Krankenhäusern, Schulen oder im Handwerk kann die Arbeit nicht einfach auf vier Tage verteilt werden, weil die Menschen dort täglich gebraucht werden. Kritiker warnen außerdem, dass der Stress steigen könnte, wenn dieselbe Arbeit in kürzerer Zeit erledigt werden muss.\n\nEine aktuelle Umfrage zeigt trotzdem klare Zahlen: 71 Prozent der Beschäftigten in Deutschland würden gern vier Tage pro Woche arbeiten — die meisten allerdings nur, wenn das Gehalt gleich bleibt.",
    gloss: [
      { de: "das Unternehmen", tr: "şirket" },
      { de: "der Beschäftigte", tr: "çalışan" },
      { de: "das Gehalt", tr: "maaş" },
      { de: "die Werbeagentur", tr: "reklam ajansı" },
      { de: "der Geschäftsführer", tr: "genel müdür" },
      { de: "die Bewerbung", tr: "iş başvurusu" },
      { de: "verkürzen", tr: "kısaltmak" },
      { de: "verteilen auf", tr: "bölüştürmek, dağıtmak" },
      { de: "das Handwerk", tr: "zanaat, el işi meslekleri" },
      { de: "erledigen", tr: "halletmek, bitirmek" },
      { de: "die Umfrage", tr: "anket" },
    ],
    questions: [
      {
        text: "Was bedeutet die Vier-Tage-Woche bei der Agentur „Kolibri“?",
        options: [
          "Man arbeitet vier Tage und verdient entsprechend weniger",
          "Man arbeitet nur vier Stunden pro Tag",
          "Man arbeitet vier Tage bei gleichem Gehalt",
        ],
        answer: 2,
        explain: "Model ilk paragrafta tanımlanıyor: çalışanlar dört gün çalışıyor ama önceki maaşın aynısını alıyor („bekommen aber das gleiche Gehalt wie vorher“).",
      },
      {
        text: "Welche Erfahrung hat Geschäftsführer Petersen gemacht?",
        options: [
          "Die Mitarbeiter sind seltener krank und motivierter",
          "Die Firma bekommt weniger Bewerbungen",
          "Die Meetings dauern jetzt länger",
        ],
        answer: 0,
        explain: "Petersen'in sözlerinde geçiyor: çalışanlar daha az hastalanıyor ve daha motive („seltener krank und deutlich motivierter“); başvurular da azalmadı, arttı.",
      },
      {
        text: "In Krankenhäusern und Schulen lässt sich das Modell leicht einführen.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: üçüncü paragrafa göre hastane, okul ve zanaat işlerinde iş dört güne kolayca bölünemez, çünkü oralarda insanlara her gün ihtiyaç var.",
      },
      {
        text: "Wovor warnen Kritiker?",
        options: [
          "Vor höheren Kosten für die Firmen",
          "Vor mehr Stress in kürzerer Arbeitszeit",
          "Vor weniger Urlaubstagen",
        ],
        answer: 1,
        explain: "Eleştirmenler, aynı işin daha kısa sürede bitirilmesi gerekirse stresin artabileceği („dass der Stress steigen könnte“) konusunda uyarıyor.",
      },
      {
        text: "Die meisten Beschäftigten möchten die Vier-Tage-Woche nur, wenn das Gehalt gleich bleibt.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Son cümle bunu doğruluyor: yüzde 71 dört gün çalışmak istiyor, ama çoğu yalnızca maaş aynı kalırsa („nur, wenn das Gehalt gleich bleibt“).",
      },
    ],
  },

  // ── Dinleme ────────────────────────────────────────────────────────────
  {
    id: "b1-l1",
    level: "B1",
    skill: "listening",
    title: "Die Lange Nacht der Museen",
    genre: "Radyo duyurusu",
    intro: "Radyodaki hafta sonu etkinlik duyurusunu dinle ve ayrıntıları not et.",
    minutes: 3,
    segments: [
      {
        text: "Und nun die Veranstaltungstipps für das Wochenende. Am Samstag findet in Nürnberg wieder die Lange Nacht der Museen statt. Von 18 Uhr abends bis 1 Uhr nachts öffnen mehr als vierzig Museen und Galerien ihre Türen. Das Eintrittsband kostet 17 Euro, ermäßigt 12 Euro, und gilt für alle teilnehmenden Häuser. Kinder unter zwölf Jahren haben freien Eintritt.",
      },
      {
        text: "Besonders empfehlen möchten wir das neue Zukunftsmuseum: Dort können Besucherinnen und Besucher ab 20 Uhr Roboter selbst steuern. Im Stadtmuseum wird stündlich eine Führung durch die Ausstellung über das mittelalterliche Nürnberg angeboten.",
      },
      {
        text: "Zwischen den Museen fahren kostenlose Shuttlebusse, die alle zehn Minuten an den Haltestellen abfahren. Die Veranstalter empfehlen, das Auto zu Hause zu lassen, da die Innenstadt teilweise gesperrt ist. Karten gibt es online oder an der Abendkasse. Im vergangenen Jahr waren sie allerdings schon am frühen Abend ausverkauft.",
      },
    ],
    gloss: [
      { de: "die Veranstaltung", tr: "etkinlik" },
      { de: "der Eintritt", tr: "giriş (ücreti)" },
      { de: "ermäßigt", tr: "indirimli" },
      { de: "die Führung", tr: "rehberli tur" },
      { de: "die Ausstellung", tr: "sergi" },
      { de: "mittelalterlich", tr: "orta çağa ait" },
      { de: "die Haltestelle", tr: "durak" },
      { de: "gesperrt", tr: "(trafiğe) kapalı" },
      { de: "die Abendkasse", tr: "gişe (etkinlik günü açılan)" },
      { de: "ausverkauft", tr: "tükenmiş, satılıp bitmiş" },
    ],
    questions: [
      {
        text: "Wann beginnt die Lange Nacht der Museen?",
        options: ["Um 17 Uhr", "Um 18 Uhr", "Um 20 Uhr"],
        answer: 1,
        explain: "Duyuruda etkinliğin akşam 18'den gece 1'e kadar sürdüğü söyleniyor. 20 Uhr yalnızca robot etkinliğinin başlangıcı — dikkat çeldiriciye.",
      },
      {
        text: "Kinder unter zwölf Jahren zahlen keinen Eintritt.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "İlk bölümde geçiyor: „Kinder unter zwölf Jahren haben freien Eintritt“ — on iki yaş altı çocuklara giriş ücretsiz.",
      },
      {
        text: "Was kann man ab 20 Uhr im Zukunftsmuseum machen?",
        options: [
          "Roboter selbst steuern",
          "An einer Führung über das Mittelalter teilnehmen",
          "Kostenlos zu Abend essen",
        ],
        answer: 0,
        explain: "Zukunftsmuseum'da ziyaretçiler saat 20'den itibaren robotları kendileri yönetebiliyor. Orta çağ turu ise Stadtmuseum'da yapılıyor.",
      },
      {
        text: "Wie oft fahren die Shuttlebusse?",
        options: ["Alle zehn Minuten", "Alle zwanzig Minuten", "Einmal pro Stunde"],
        answer: 0,
        explain: "Son bölümde ücretsiz servis otobüslerinin duraklardan her on dakikada bir („alle zehn Minuten“) kalktığı belirtiliyor.",
      },
      {
        text: "Warum sollte man die Karten früh kaufen?",
        options: [
          "Weil sie online billiger sind",
          "Weil sie letztes Jahr früh ausverkauft waren",
          "Weil die Abendkasse geschlossen bleibt",
        ],
        answer: 1,
        explain: "Duyurunun sonunda geçen yıl biletlerin akşamın erken saatlerinde tükendiği („schon am frühen Abend ausverkauft“) hatırlatılıyor.",
      },
    ],
  },
  {
    id: "b1-l2",
    level: "B1",
    skill: "listening",
    title: "Ehrenamt bei der Tafel",
    genre: "Radyo röportajı",
    intro: "Gıda bankasında gönüllü çalışan Herr Weber ile yapılan radyo röportajını dinle.",
    minutes: 4,
    segments: [
      {
        speaker: "Moderatorin",
        text: "Willkommen zurück bei Radio Neckarwelle. Zu Gast ist heute Thomas Weber, der sich seit fünf Jahren ehrenamtlich bei der Heidelberger Tafel engagiert. Herr Weber, was genau machen Sie dort?",
      },
      {
        speaker: "Herr Weber",
        text: "Wir sammeln Lebensmittel, die Supermärkte nicht mehr verkaufen können, die aber noch gut sind. Diese verteilen wir dann an Menschen mit wenig Geld. Ich fahre zweimal pro Woche mit dem Kühlwagen zu den Märkten und hole die Ware ab.",
      },
      {
        speaker: "Moderatorin",
        text: "Wie sind Sie zu diesem Ehrenamt gekommen?",
      },
      {
        speaker: "Herr Weber",
        text: "Ganz zufällig. Nach meiner Rente hatte ich plötzlich viel Zeit und habe einen Zeitungsartikel über die Tafel gelesen. Am nächsten Tag habe ich einfach dort angerufen.",
      },
      {
        speaker: "Moderatorin",
        text: "Was gibt Ihnen die Arbeit persönlich?",
      },
      {
        speaker: "Herr Weber",
        text: "Sehr viel. Man bekommt direkte Dankbarkeit, und ich habe tolle Menschen kennengelernt. Aber ich will ehrlich sein: Manchmal ist es auch traurig zu sehen, wie viele Familien Hilfe brauchen.",
      },
      {
        speaker: "Moderatorin",
        text: "Sucht die Tafel noch Unterstützung?",
      },
      {
        speaker: "Herr Weber",
        text: "Unbedingt! Besonders Fahrerinnen und Fahrer werden gesucht. Wer Interesse hat, findet alle Informationen auf unserer Webseite.",
      },
    ],
    gloss: [
      { de: "das Ehrenamt", tr: "gönüllü görev" },
      { de: "die Tafel", tr: "gıda bankası" },
      { de: "sich engagieren", tr: "gönüllü olarak çalışmak" },
      { de: "die Lebensmittel", tr: "gıda maddeleri" },
      { de: "verteilen", tr: "dağıtmak" },
      { de: "die Ware abholen", tr: "malı teslim almak" },
      { de: "die Rente", tr: "emeklilik" },
      { de: "zufällig", tr: "tesadüfen" },
      { de: "die Dankbarkeit", tr: "minnettarlık" },
      { de: "die Unterstützung", tr: "destek" },
    ],
    questions: [
      {
        text: "Was macht Herr Weber bei der Tafel?",
        options: [
          "Er verkauft günstige Lebensmittel",
          "Er holt Lebensmittel von Supermärkten ab",
          "Er kocht warme Mahlzeiten für Familien",
        ],
        answer: 1,
        explain: "Kendi anlatıyor: haftada iki kez soğutuculu araçla marketlere gidip malları teslim alıyor („hole die Ware ab“). Satış ya da yemek pişirme yok.",
      },
      {
        text: "Herr Weber arbeitet jeden Tag für die Tafel.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: haftada iki kez („zweimal pro Woche“) araçla marketleri dolaştığını söylüyor.",
      },
      {
        text: "Wie hat Herr Weber von der Tafel erfahren?",
        options: [
          "Durch einen Freund",
          "Durch eine Radiosendung",
          "Durch einen Zeitungsartikel",
        ],
        answer: 2,
        explain: "Emekli olduktan sonra Tafel hakkında bir gazete makalesi okumuş („einen Zeitungsartikel über die Tafel gelesen“) ve ertesi gün aramış.",
      },
      {
        text: "Was findet Herr Weber manchmal traurig?",
        options: [
          "Dass so viele Familien Hilfe brauchen",
          "Dass sich niemand bei ihm bedankt",
          "Dass die Arbeit körperlich anstrengend ist",
        ],
        answer: 0,
        explain: "Dürüstçe itiraf ediyor: bu kadar çok ailenin yardıma ihtiyaç duyduğunu görmek bazen üzücü. Teşekkür eksikliğinden şikâyet etmiyor, aksine doğrudan minnettarlık gördüğünü söylüyor.",
      },
      {
        text: "Wen sucht die Tafel im Moment besonders?",
        options: ["Köchinnen und Köche", "Fahrerinnen und Fahrer", "Verkäuferinnen und Verkäufer"],
        answer: 1,
        explain: "Son cevapta özellikle şoför arandığı („Besonders Fahrerinnen und Fahrer werden gesucht“) vurgulanıyor.",
      },
    ],
  },
  {
    id: "b1-l3",
    level: "B1",
    skill: "listening",
    title: "Ein Garten für alle",
    genre: "Günlük konuşma",
    intro: "İki komşunun, binalarının arkasına yapılacak ortak bahçe hakkındaki konuşmasını dinle.",
    minutes: 3,
    segments: [
      {
        speaker: "Jonas",
        text: "Hallo Elif! Hast du schon gehört? Auf der freien Fläche hinter unserem Haus soll ein Gemeinschaftsgarten entstehen.",
      },
      {
        speaker: "Elif",
        text: "Ja, ich habe den Aushang im Treppenhaus gesehen. Ich bin mir aber nicht sicher, ob das funktioniert. Wer soll sich denn darum kümmern?",
      },
      {
        speaker: "Jonas",
        text: "Die Idee ist, dass jeder Haushalt ein kleines Beet bekommt. Um die gemeinsamen Wege und die Obstbäume kümmern wir uns zusammen. Nächsten Samstag um zehn gibt es ein erstes Treffen.",
      },
      {
        speaker: "Elif",
        text: "Hm, ich habe ehrlich gesagt noch nie etwas angepflanzt. Ich hätte Angst, dass bei mir alles vertrocknet.",
      },
      {
        speaker: "Jonas",
        text: "Das macht doch nichts! Frau Behrens aus dem dritten Stock war früher Gärtnerin, sie will Anfängern helfen. Und stell dir vor: eigene Tomaten, frische Kräuter direkt vor der Tür.",
      },
      {
        speaker: "Elif",
        text: "Das klingt schon verlockend. Und die Kinder könnten draußen spielen, während wir im Garten arbeiten. Weißt du was? Ich komme am Samstag einfach mal mit.",
      },
      {
        speaker: "Jonas",
        text: "Super! Ich hole dich um kurz vor zehn ab.",
      },
    ],
    gloss: [
      { de: "der Gemeinschaftsgarten", tr: "ortak bahçe" },
      { de: "die Fläche", tr: "alan, arazi" },
      { de: "der Aushang", tr: "duyuru, ilan" },
      { de: "das Treppenhaus", tr: "merdiven boşluğu, apartman girişi" },
      { de: "sich kümmern um", tr: "ilgilenmek, bakmak" },
      { de: "der Haushalt", tr: "hane" },
      { de: "das Beet", tr: "tarh, ekim yatağı" },
      { de: "anpflanzen", tr: "ekmek, dikmek" },
      { de: "vertrocknen", tr: "kuruyup gitmek" },
      { de: "verlockend", tr: "cazip, çekici" },
    ],
    questions: [
      {
        text: "Worüber sprechen Elif und Jonas?",
        options: [
          "Über einen neuen Spielplatz im Hof",
          "Über einen geplanten Gemeinschaftsgarten",
          "Über einen Flohmarkt am Wochenende",
        ],
        answer: 1,
        explain: "Jonas ilk cümlede haberi veriyor: binanın arkasındaki boş alanda ortak bir bahçe kurulacak („soll ein Gemeinschaftsgarten entstehen“).",
      },
      {
        text: "Jeder Haushalt soll ein eigenes kleines Beet bekommen.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Jonas planı açıklıyor: her haneye küçük bir tarh düşecek, ortak yollar ve meyve ağaçlarıyla ise birlikte ilgilenilecek.",
      },
      {
        text: "Warum ist Elif zuerst unsicher?",
        options: [
          "Sie hat am Samstag keine Zeit",
          "Sie mag kein frisches Gemüse",
          "Sie hat noch nie etwas angepflanzt",
        ],
        answer: 2,
        explain: "Elif hiç bitki yetiştirmediğini („noch nie etwas angepflanzt“) ve her şeyin kuruyup gitmesinden korktuğunu söylüyor.",
      },
      {
        text: "Wer will den Anfängern im Garten helfen?",
        options: ["Frau Behrens aus dem dritten Stock", "Der Hausmeister", "Jonas selbst"],
        answer: 0,
        explain: "Jonas'a göre üçüncü kattaki Frau Behrens eskiden bahçıvanmış ve yeni başlayanlara yardım etmek istiyor.",
      },
      {
        text: "Was machen die beiden am Samstag?",
        options: [
          "Sie kaufen zusammen Pflanzen",
          "Sie gehen gemeinsam zum ersten Treffen",
          "Sie besuchen Frau Behrens",
        ],
        answer: 1,
        explain: "Elif „Ich komme am Samstag einfach mal mit“ diyor, Jonas da onu ondan az önce alacağını söylüyor — yani ilk toplantıya birlikte gidecekler.",
      },
    ],
  },
  {
    id: "b1-l4",
    level: "B1",
    skill: "listening",
    title: "Station fünf: die Speicherstadt",
    genre: "Sesli rehber",
    intro: "Hamburg Liman Müzesi'ndeki sesli rehberin Speicherstadt bölümünü dinle.",
    minutes: 3,
    segments: [
      {
        text: "Herzlich willkommen im Hafenmuseum Hamburg. Sie hören Station fünf: die Speicherstadt. Vor Ihnen sehen Sie ein Modell des größten historischen Lagerhauskomplexes der Welt. Die Speicherstadt wurde zwischen 1883 und 1927 gebaut. In den roten Backsteingebäuden lagerten Kaffee, Tee, Gewürze und Teppiche aus der ganzen Welt.",
      },
      {
        text: "Beachten Sie die kleinen Türen in den oberen Stockwerken: Dort wurden die Waren früher mit Seilwinden direkt aus den Schiffen nach oben gezogen. Bis heute riecht es in einigen Gebäuden nach Gewürzen.",
      },
      {
        text: "Seit 2015 gehört die Speicherstadt zum Weltkulturerbe der UNESCO. Heute befinden sich in den alten Speichern Museen, Büros und Cafés. In der Vitrine rechts neben dem Modell sehen Sie originale Werkzeuge der Hafenarbeiter, die hier bis in die achtziger Jahre gearbeitet haben.",
      },
      {
        text: "Wenn Sie mehr über den modernen Containerhafen erfahren möchten, folgen Sie dem blauen Pfeil zur Station sechs im nächsten Raum. Wir wünschen Ihnen einen angenehmen Aufenthalt.",
      },
    ],
    gloss: [
      { de: "das Lagerhaus", tr: "depo binası, antrepo" },
      { de: "der Backstein", tr: "tuğla" },
      { de: "lagern", tr: "depolamak" },
      { de: "das Gewürz", tr: "baharat" },
      { de: "der Teppich", tr: "halı" },
      { de: "das Stockwerk", tr: "kat" },
      { de: "die Ware", tr: "mal, ürün" },
      { de: "das Weltkulturerbe", tr: "dünya kültür mirası" },
      { de: "die Vitrine", tr: "vitrin, cam dolap" },
      { de: "der Aufenthalt", tr: "kalış, ziyaret" },
    ],
    questions: [
      {
        text: "Was sehen die Besucher an Station fünf?",
        options: [
          "Ein originales Handelsschiff",
          "Einen Film über den Hafen",
          "Ein Modell der Speicherstadt",
        ],
        answer: 2,
        explain: "Rehber baştan söylüyor: ziyaretçilerin önünde dünyanın en büyük tarihi depo kompleksinin bir maketi („ein Modell“) duruyor.",
      },
      {
        text: "Was wurde früher in der Speicherstadt gelagert?",
        options: [
          "Kaffee, Tee, Gewürze und Teppiche",
          "Autos und Maschinen",
          "Fisch und Fleisch",
        ],
        answer: 0,
        explain: "İlk bölümde kırmızı tuğla binalarda dünyanın dört bir yanından gelen kahve, çay, baharat ve halıların depolandığı anlatılıyor.",
      },
      {
        text: "Die Speicherstadt gehört seit 2015 zum UNESCO-Weltkulturerbe.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Üçüncü bölümde aynen geçiyor: „Seit 2015 gehört die Speicherstadt zum Weltkulturerbe der UNESCO.“",
      },
      {
        text: "Wozu dienten die kleinen Türen in den oberen Stockwerken?",
        options: [
          "Die Arbeiter gingen dort zur Mittagspause hinaus",
          "Die Waren wurden dort nach oben gezogen",
          "Sie dienten zum Lüften der Räume",
        ],
        answer: 1,
        explain: "Rehbere göre mallar eskiden vinç halatlarıyla („mit Seilwinden“) gemilerden doğrudan bu kapılara çekiliyordu.",
      },
      {
        text: "Wohin sollen Besucher gehen, die sich für den Containerhafen interessieren?",
        options: ["Zur Station sechs", "Zur Kasse im Erdgeschoss", "In das Café im Speicher"],
        answer: 0,
        explain: "Son bölümde modern konteyner limanını merak edenlerin mavi oku izleyip yan salondaki altıncı istasyona geçmesi isteniyor.",
      },
    ],
  },
  {
    id: "b1-l5",
    level: "B1",
    skill: "listening",
    title: "Tag der offenen Tür an der Volkshochschule",
    genre: "Duyuru",
    intro: "Halk eğitim merkezinin açık kapı gününde yapılan anonsu dinle.",
    minutes: 3,
    segments: [
      {
        text: "Liebe Besucherinnen und Besucher, herzlich willkommen zum Tag der offenen Tür der Volkshochschule Bochum. Bevor die einzelnen Kurse vorgestellt werden, einige wichtige Informationen. Das neue Programmheft für das Herbstsemester liegt am Empfang für Sie bereit. Insgesamt werden über vierhundert Kurse angeboten, von Sprachen über Computerkurse bis zu Gesundheit und Kochen.",
      },
      {
        text: "Neu in diesem Semester ist der Bereich Digitale Sicherheit: Hier lernen Sie zum Beispiel, wie Sie sichere Passwörter erstellen und Betrug im Internet erkennen. Wer sich heute für einen Kurs anmeldet, erhält zehn Prozent Rabatt auf die Kursgebühr. Die Anmeldung ist in Raum zwölf im Erdgeschoss möglich, bitte bringen Sie dafür Ihren Ausweis mit.",
      },
      {
        text: "Um 15 Uhr stellen unsere Sprachlehrerinnen und Sprachlehrer im großen Saal die neuen Konversationskurse vor. Dort können Sie auch einen kostenlosen Einstufungstest machen, wenn Sie nicht sicher sind, welches Niveau zu Ihnen passt. Die Cafeteria im ersten Stock ist bis 17 Uhr geöffnet. Wir wünschen Ihnen einen schönen Tag!",
      },
    ],
    gloss: [
      { de: "der Tag der offenen Tür", tr: "açık kapı günü" },
      { de: "die Volkshochschule", tr: "halk eğitim merkezi" },
      { de: "das Programmheft", tr: "program kitapçığı" },
      { de: "der Empfang", tr: "danışma, resepsiyon" },
      { de: "der Betrug", tr: "dolandırıcılık" },
      { de: "sich anmelden", tr: "kaydolmak" },
      { de: "die Kursgebühr", tr: "kurs ücreti" },
      { de: "der Ausweis", tr: "kimlik" },
      { de: "der Einstufungstest", tr: "seviye tespit sınavı" },
      { de: "das Niveau", tr: "seviye, düzey" },
    ],
    questions: [
      {
        text: "Wo findet diese Durchsage statt?",
        options: [
          "An einer Volkshochschule",
          "An einer Universität",
          "In einer Sprachschule für Kinder",
        ],
        answer: 0,
        explain: "Anonsun başında yer belirtiliyor: Bochum Volkshochschule'nin açık kapı günü.",
      },
      {
        text: "Welcher Bereich ist in diesem Semester neu?",
        options: ["Gesundheit und Kochen", "Digitale Sicherheit", "Konversationskurse"],
        answer: 1,
        explain: "İkinci bölümde bu dönemin yeniliği olarak Digitale Sicherheit alanı tanıtılıyor: güvenli şifre oluşturma ve internette dolandırıcılığı tanıma.",
      },
      {
        text: "Wer sich heute anmeldet, zahlt zehn Prozent weniger.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Doğru: bugün kaydolanlar kurs ücretinde yüzde on indirim („zehn Prozent Rabatt auf die Kursgebühr“) alıyor.",
      },
      {
        text: "Was braucht man für die Anmeldung?",
        options: ["Ein Passfoto", "Ein Zeugnis", "Den Ausweis"],
        answer: 2,
        explain: "Kayıt zemin kattaki on iki numaralı odada yapılıyor ve kimlik getirilmesi („bitte bringen Sie dafür Ihren Ausweis mit“) isteniyor.",
      },
      {
        text: "Was kann man um 15 Uhr im großen Saal machen?",
        options: [
          "Einen kostenlosen Einstufungstest machen",
          "Das Programmheft kaufen",
          "In der Cafeteria Kuchen essen",
        ],
        answer: 0,
        explain: "Saat 15'te büyük salonda konuşma kursları tanıtılacak ve seviyesinden emin olmayanlar ücretsiz seviye testi yapabilecek. Kafeterya ise birinci katta.",
      },
    ],
  },
  {
    id: "b1-l6",
    level: "B1",
    skill: "listening",
    title: "Wie viel Handy ist zu viel?",
    genre: "Radyo röportajı",
    intro: "Gençlerin telefon kullanımı üzerine yapılan araştırmayı anlatan uzman röportajını dinle.",
    minutes: 4,
    segments: [
      {
        speaker: "Moderator",
        text: "Wie viel Zeit verbringen Jugendliche am Handy? Eine neue Studie der Universität Mannheim liefert Antworten. Frau Doktor Lindner, Sie haben die Studie geleitet. Was sind die wichtigsten Ergebnisse?",
      },
      {
        speaker: "Frau Lindner",
        text: "Jugendliche zwischen zwölf und siebzehn Jahren nutzen ihr Smartphone im Durchschnitt dreieinhalb Stunden täglich. Das klingt erst einmal viel, aber uns hat etwas anderes überrascht: Die meisten Jugendlichen finden selbst, dass das zu viel ist. Zwei Drittel wünschen sich, weniger Zeit am Handy zu verbringen.",
      },
      {
        speaker: "Moderator",
        text: "Und schaffen sie das auch?",
      },
      {
        speaker: "Frau Lindner",
        text: "Selten, denn die Apps sind so gebaut, dass man immer weiterschauen möchte. Verbote helfen unserer Erfahrung nach wenig. Sinnvoller sind gemeinsame Regeln in der Familie, zum Beispiel handyfreie Zeiten beim Abendessen. Diese Regeln sollten dann übrigens auch für die Eltern gelten.",
      },
      {
        speaker: "Moderator",
        text: "Gibt es auch positive Ergebnisse?",
      },
      {
        speaker: "Frau Lindner",
        text: "Ja, durchaus. Viele Jugendliche nutzen das Handy für die Schule, lernen mit Videos oder bleiben mit der Familie im Ausland in Kontakt. Das Smartphone ist also nicht nur ein Problem. Es kommt darauf an, wie man es benutzt.",
      },
    ],
    gloss: [
      { de: "der Jugendliche", tr: "genç" },
      { de: "die Studie", tr: "bilimsel araştırma" },
      { de: "leiten", tr: "yönetmek" },
      { de: "das Ergebnis", tr: "sonuç" },
      { de: "im Durchschnitt", tr: "ortalama olarak" },
      { de: "überraschen", tr: "şaşırtmak" },
      { de: "das Verbot", tr: "yasak" },
      { de: "sinnvoll", tr: "mantıklı, anlamlı" },
      { de: "gelten für", tr: "için geçerli olmak" },
      { de: "in Kontakt bleiben", tr: "iletişimde kalmak" },
    ],
    questions: [
      {
        text: "Wie lange nutzen Jugendliche ihr Smartphone im Durchschnitt pro Tag?",
        options: ["Zweieinhalb Stunden", "Dreieinhalb Stunden", "Viereinhalb Stunden"],
        answer: 1,
        explain: "Frau Lindner araştırmanın sonucunu veriyor: 12-17 yaş arası gençler telefonlarını günde ortalama üç buçuk saat („dreieinhalb Stunden“) kullanıyor.",
      },
      {
        text: "Was hat die Forscherinnen und Forscher überrascht?",
        options: [
          "Dass die meisten Jugendlichen selbst weniger Handyzeit möchten",
          "Dass Jugendliche kaum noch Apps benutzen",
          "Dass Eltern mehr am Handy sind als ihre Kinder",
        ],
        answer: 0,
        explain: "Şaşırtıcı bulgu: gençlerin üçte ikisi telefonla daha az vakit geçirmeyi kendisi istiyor („Zwei Drittel wünschen sich, weniger Zeit am Handy zu verbringen“).",
      },
      {
        text: "Frau Lindner empfiehlt strenge Handyverbote für Jugendliche.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: deneyimlerine göre yasaklar pek işe yaramıyor („Verbote helfen … wenig“); bunun yerine ailede ortak kurallar öneriyor.",
      },
      {
        text: "Welche Regel nennt Frau Lindner als Beispiel?",
        options: [
          "Handyfreie Zeiten beim Abendessen",
          "Handy nur am Wochenende",
          "Keine Videos nach 20 Uhr",
        ],
        answer: 0,
        explain: "Örnek olarak akşam yemeğinde telefonsuz zamanları („handyfreie Zeiten beim Abendessen“) veriyor — ve bu kural ebeveynler için de geçerli olmalı.",
      },
      {
        text: "Das Smartphone hat laut Frau Lindner auch positive Seiten.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Son cevapta gençlerin telefonu okul için, videolarla öğrenmek ve yurt dışındaki aileyle iletişim kurmak için de kullandığını söylüyor: „Es kommt darauf an, wie man es benutzt.“",
      },
    ],
  },

  // ── Yazma ──────────────────────────────────────────────────────────────
  {
    id: "b1-w1",
    level: "B1",
    skill: "writing",
    title: "Ein Fest für die Nachbarschaft",
    genre: "Yarı resmi e-posta",
    intro: "Komşularınla bir mahalle şenliği planlıyorsun — önce cümle kur, sonra bina yönetimine izin e-postası yaz.",
    minutes: 10,
    gloss: [
      { de: "der Aushang", tr: "duyuru, ilan" },
      { de: "die Nachbarn einladen", tr: "komşuları davet etmek" },
      { de: "der Innenhof", tr: "iç avlu" },
      { de: "die Hausverwaltung", tr: "bina yönetimi" },
      { de: "die Erlaubnis", tr: "izin" },
      { de: "aufbauen", tr: "kurmak (masa, çadır)" },
      { de: "aufräumen", tr: "toplamak, temizlemek" },
      { de: "die Lautstärke", tr: "ses düzeyi" },
    ],
    tasks: [
      {
        kind: "build",
        tr: "Komşuları davet etmek için bir duyuru asıyorum.",
        answer: "Ich hänge einen Aushang auf, um die Nachbarn einzuladen.",
        alternatives: ["Um die Nachbarn einzuladen, hänge ich einen Aushang auf."],
        hint: "Amaç bildirmek için „um … zu“ kalıbı: fiil mastarı sona gider (einzuladen).",
      },
      {
        kind: "build",
        tr: "Herkes yiyecek bir şeyler getirse ne güzel olurdu.",
        answer: "Es wäre schön, wenn jeder etwas zu essen mitbringen würde.",
        alternatives: ["Wenn jeder etwas zu essen mitbringen würde, wäre es schön."],
        hint: "Konjunktiv II ile kibar dilek: „Es wäre schön, wenn … würde“. Yan cümlede çekimli fiil sonda.",
      },
      {
        kind: "free",
        prompt: "Komşularınla 14 Haziran Cumartesi günü bir mahalle şenliği düzenlemek istiyorsunuz. Bina yönetiminden Frau Winter'e yarı resmi bir e-posta yaz: kendini tanıt, planınızı açıkla, iç avluyu kullanmak için izin iste ve ses düzeni gibi kurallar olup olmadığını sor.",
        checklist: [
          "Uygun hitap (Sehr geehrte …) ve kapanış (Mit freundlichen Grüßen) kullandın mı?",
          "Şenliğin tarihini, yerini ve amacını açıkladın mı?",
          "İzni kibarca, Konjunktiv II ile istedin mi (dürften wir, wäre es möglich)?",
          "Toparlama ve ses düzeyi gibi konulara değinip yanıt rica ettin mi?",
        ],
        minWords: 60,
        phrases: [
          { de: "Ich schreibe Ihnen, weil …", tr: "Size yazıyorum çünkü …" },
          { de: "Wir möchten gern … organisieren.", tr: "… düzenlemek istiyoruz." },
          { de: "Ich möchte Sie fragen, ob …", tr: "Size … olup olmadığını sormak istiyorum." },
          { de: "Dürften wir dafür … benutzen?", tr: "Bunun için … kullanabilir miyiz acaba?" },
          { de: "Es wäre schön, wenn …", tr: "… olursa çok iyi olur." },
          { de: "Wir würden natürlich alles wieder aufräumen.", tr: "Elbette her şeyi yeniden toplarız." },
          { de: "Über eine kurze Antwort würde ich mich freuen.", tr: "Kısa bir yanıta sevinirim." },
        ],
        sample: "Sehr geehrte Frau Winter,\n\nich wohne seit drei Jahren in der Gartenstraße 5 und schreibe Ihnen im Namen mehrerer Nachbarn. Wir möchten am Samstag, dem 14. Juni, ein kleines Nachbarschaftsfest organisieren, damit sich die Bewohner besser kennenlernen. Deshalb möchte ich Sie fragen, ob wir dafür den Innenhof benutzen dürfen.\n\nWir würden Tische und Bänke selbst aufbauen und den Hof am Abend natürlich wieder aufräumen. Es wäre schön, wenn Sie uns außerdem sagen könnten, ob es Regeln zur Lautstärke gibt.\n\nÜber eine kurze Antwort bis Ende Mai würde ich mich sehr freuen.\n\nMit freundlichen Grüßen\nDeniz Aksoy",
      },
    ],
  },
  {
    id: "b1-w2",
    level: "B1",
    skill: "writing",
    title: "Soziale Netzwerke: Fluch oder Segen?",
    genre: "Forum",
    intro: "Bir internet forumunda sosyal medya tartışmasına katılıyorsun — görüşünü gerekçeleriyle yaz.",
    minutes: 10,
    gloss: [
      { de: "das soziale Netzwerk", tr: "sosyal ağ" },
      { de: "das Konto löschen", tr: "hesabı silmek" },
      { de: "meiner Meinung nach", tr: "bence, benim görüşüme göre" },
      { de: "einerseits … andererseits", tr: "bir yandan … öte yandan" },
      { de: "die Benachrichtigung", tr: "bildirim" },
      { de: "die Bildschirmzeit", tr: "ekran süresi" },
      { de: "empfehlen", tr: "tavsiye etmek" },
      { de: "es kommt darauf an", tr: "duruma bağlı, -e bağlı" },
    ],
    tasks: [
      {
        kind: "build",
        tr: "Bence birçok insan internette çok fazla zaman geçiriyor.",
        answer: "Meiner Meinung nach verbringen viele Menschen zu viel Zeit online.",
        alternatives: ["Viele Menschen verbringen meiner Meinung nach zu viel Zeit online."],
        hint: "„Meiner Meinung nach“ cümlenin başındaysa fiil hemen ardından gelir (verbringen).",
      },
      {
        kind: "build",
        tr: "Yalnızca beni gerçekten ilgilendiren sayfaları takip ediyorum.",
        answer: "Ich folge nur Seiten, die mich wirklich interessieren.",
        hint: "Relativsatz: „Seiten, die …“ — ilgi cümlesinde çekimli fiil (interessieren) sona gider.",
      },
      {
        kind: "free",
        prompt: "„Digitales Leben“ forumundaki soruya bir yorum yaz: sosyal ağlar hakkındaki görüşünü açıkla, kendi deneyiminden en az bir örnek ver ve okuyanlara somut bir öneride bulun.",
        stimulus: "Immer mehr Menschen löschen ihre Social-Media-Konten. Brauchen wir soziale Netzwerke wirklich? Was meint ihr? — Beitrag von Markus82 im Forum „Digitales Leben“",
        checklist: [
          "Görüşünü açık bir kalıpla belirttin mi (meiner Meinung nach, ich finde, dass …)?",
          "En az bir avantaj ve bir dezavantajı karşılaştırdın mı (einerseits … andererseits)?",
          "Kendi deneyiminden somut bir örnek verdin mi?",
          "Sonunda okuyanlara bir öneri sundun mu?",
        ],
        minWords: 60,
        phrases: [
          { de: "Ich habe lange über diese Frage nachgedacht.", tr: "Bu soruyu uzun uzun düşündüm." },
          { de: "Meiner Meinung nach …", tr: "Bence …" },
          { de: "Einerseits …, andererseits …", tr: "Bir yandan …, öte yandan …" },
          { de: "Ich habe die Erfahrung gemacht, dass …", tr: "Şu deneyimi yaşadım: …" },
          { de: "Deshalb habe ich mir feste Regeln gesetzt.", tr: "Bu yüzden kendime kesin kurallar koydum." },
          { de: "Ich würde jedem empfehlen, …", tr: "Herkese … tavsiye ederim." },
          { de: "Es kommt darauf an, wie man es benutzt.", tr: "Nasıl kullandığına bağlı." },
        ],
        sample: "Ich habe lange über diese Frage nachgedacht, weil ich selbst viel Zeit am Handy verbringe. Meiner Meinung nach sind soziale Netzwerke weder gut noch schlecht. Es kommt darauf an, wie man sie benutzt.\n\nEinerseits bleibe ich durch Instagram mit meiner Familie in der Türkei in Kontakt, was mir sehr wichtig ist. Andererseits merke ich, dass ich oft ohne Grund durch Videos scrolle und danach müde bin.\n\nDeshalb habe ich mir feste Regeln gesetzt: keine Apps vor der Arbeit und keine Benachrichtigungen am Abend. Ich würde jedem empfehlen, die eigene Bildschirmzeit einmal pro Woche zu kontrollieren. Ganz löschen möchte ich meine Konten aber nicht.",
      },
    ],
  },
  {
    id: "b1-w3",
    level: "B1",
    skill: "writing",
    title: "Absage an die Kursleiterin",
    genre: "Yarı resmi e-posta",
    intro: "Sınav hazırlık dersine katılamayacaksın — kurs öğretmenine durumu açıklayan bir e-posta yaz.",
    minutes: 8,
    gloss: [
      { de: "die Prüfungsvorbereitung", tr: "sınav hazırlığı" },
      { de: "teilnehmen an", tr: "katılmak" },
      { de: "absagen", tr: "iptal etmek, katılamayacağını bildirmek" },
      { de: "verschieben", tr: "ertelemek" },
      { de: "die Unterlagen", tr: "belgeler, dokümanlar" },
      { de: "das Übungsblatt", tr: "alıştırma kâğıdı" },
      { de: "der Arbeitgeber", tr: "işveren" },
      { de: "das Verständnis", tr: "anlayış" },
    ],
    tasks: [
      {
        kind: "build",
        tr: "Kurs, tatil nedeniyle bir hafta ertelendi.",
        answer: "Der Kurs wurde wegen der Ferien um eine Woche verschoben.",
        alternatives: ["Wegen der Ferien wurde der Kurs um eine Woche verschoben."],
        hint: "Passiv Präteritum: „wurde … verschoben“. „wegen“ edatı Genitiv ister (wegen der Ferien).",
      },
      {
        kind: "build",
        tr: "Belgeleri bana lütfen e-postayla gönderebilir misiniz?",
        answer: "Könnten Sie mir bitte die Unterlagen per E-Mail schicken?",
        alternatives: ["Könnten Sie mir die Unterlagen bitte per E-Mail schicken?"],
        hint: "Kibar rica için Konjunktiv II: „Könnten Sie …?“ Mastar (schicken) cümlenin sonunda.",
      },
      {
        kind: "free",
        prompt: "Cuma günkü sınav hazırlık dersine iş yerindeki önemli bir toplantı yüzünden katılamayacaksın. Kurs öğretmenin Frau Berger'e yarı resmi bir e-posta yaz: özür dile, nedenini açıkla, ders materyallerini rica et ve kaçırdıklarını nasıl telafi edeceğini öner.",
        checklist: [
          "Katılamayacağını ve nedenini ilk cümlelerde net söyledin mi?",
          "Uygun bir özür kalıbı kullandın mı (das tut mir sehr leid)?",
          "Materyalleri Konjunktiv II ile kibarca istedin mi (wäre es möglich, könnten Sie)?",
          "Telafi için somut bir öneri yaptın mı?",
        ],
        minWords: 50,
        phrases: [
          { de: "Leider kann ich am … nicht teilnehmen.", tr: "Maalesef … günü katılamıyorum." },
          { de: "Das tut mir sehr leid.", tr: "Bunun için çok üzgünüm." },
          { de: "Ich habe an diesem Tag einen wichtigen Termin.", tr: "O gün önemli bir randevum var." },
          { de: "Wäre es möglich, dass …?", tr: "… mümkün olur mu acaba?" },
          { de: "Könnten Sie mir … schicken?", tr: "Bana … gönderebilir misiniz?" },
          { de: "Ich würde die Aufgaben zu Hause bearbeiten.", tr: "Ödevleri evde çalışırım." },
          { de: "Vielen Dank für Ihr Verständnis.", tr: "Anlayışınız için çok teşekkürler." },
        ],
        sample: "Sehr geehrte Frau Berger,\n\nleider kann ich am kommenden Freitag nicht an der Prüfungsvorbereitung teilnehmen, weil ich an diesem Tag einen wichtigen Termin bei meinem Arbeitgeber habe. Das tut mir sehr leid, denn dieser Unterricht ist kurz vor der Prüfung besonders wichtig.\n\nWäre es möglich, dass Sie mir die Übungsblätter per E-Mail schicken? Ich würde die Aufgaben am Wochenende zu Hause bearbeiten. Falls etwas unklar ist, könnte ich am Montag ein paar Minuten früher kommen und Ihnen Fragen stellen.\n\nVielen Dank für Ihr Verständnis.\n\nMit freundlichen Grüßen\nMurat Şahin",
      },
    ],
  },
  {
    id: "b1-w4",
    level: "B1",
    skill: "writing",
    title: "Autofreie Innenstadt: Ja oder Nein?",
    genre: "Forum",
    intro: "Şehir portalındaki arabasız şehir merkezi tartışmasına görüşünle katıl.",
    minutes: 12,
    gloss: [
      { de: "autofrei", tr: "arabasız, trafiğe kapalı" },
      { de: "die Innenstadt", tr: "şehir merkezi" },
      { de: "sperren für", tr: "(trafiğe) kapatmak" },
      { de: "die Luftqualität", tr: "hava kalitesi" },
      { de: "öffentliche Verkehrsmittel", tr: "toplu taşıma araçları" },
      { de: "der Handwerker", tr: "zanaatkâr, usta" },
      { de: "vorschlagen", tr: "önermek" },
      { de: "die Alternative", tr: "alternatif, seçenek" },
    ],
    tasks: [
      {
        kind: "build",
        tr: "Şehir merkezi hafta sonları arabalara kapatılmalı.",
        answer: "Die Innenstadt sollte am Wochenende für Autos gesperrt werden.",
        alternatives: ["Am Wochenende sollte die Innenstadt für Autos gesperrt werden."],
        hint: "„sollte“ + Passiv mastarı: „gesperrt werden“ cümlenin sonunda blok hâlinde durur.",
      },
      {
        kind: "build",
        tr: "Otobüsler daha ucuz olsaydı, daha çok insan onları kullanırdı.",
        answer: "Wenn die Busse billiger wären, würden mehr Menschen sie benutzen.",
        alternatives: ["Mehr Menschen würden die Busse benutzen, wenn sie billiger wären."],
        hint: "Gerçek dışı koşul: iki tarafta da Konjunktiv II (wären / würden … benutzen).",
      },
      {
        kind: "free",
        prompt: "Şehir portalındaki soruya bir yorum yaz: arabasız şehir merkezi hakkındaki görüşünü belirt, en az iki gerekçe ver, karşı görüşe de kısaca değin ve bir çözüm öner.",
        stimulus: "Unsere Stadt diskutiert: Soll die Innenstadt für private Autos gesperrt werden? Schreiben Sie uns Ihre Meinung! — Umfrage auf dem Stadtportal Ludwigsburg",
        checklist: [
          "Görüşünü net bir cümleyle ortaya koydun mu?",
          "En az iki gerekçe verdin mi (hava kalitesi, güvenlik, yaşam kalitesi …)?",
          "Karşı görüşü kısaca kabul edip yanıtladın mı (natürlich …, aber …)?",
          "Somut bir öneriyle bitirdin mi (ich schlage vor, dass …)?",
        ],
        minWords: 60,
        phrases: [
          { de: "Ich finde diese Idee großartig.", tr: "Bu fikri harika buluyorum." },
          { de: "Der wichtigste Grund ist für mich …", tr: "Benim için en önemli neden …" },
          { de: "Außerdem …", tr: "Ayrıca …" },
          { de: "Natürlich brauchen manche Menschen das Auto.", tr: "Elbette bazı insanların arabaya ihtiyacı var." },
          { de: "Deshalb schlage ich vor, dass …", tr: "Bu yüzden … öneriyorum." },
          { de: "So hätte jeder eine gute Alternative.", tr: "Böylece herkesin iyi bir alternatifi olurdu." },
        ],
        sample: "In meiner Heimatstadt gibt es seit einem Jahr einen autofreien Sonntag pro Monat, und ich finde diese Idee großartig. Meiner Meinung nach sollten noch mehr Städte das ausprobieren.\n\nDer wichtigste Grund ist für mich die Luftqualität. Außerdem ist es viel angenehmer, durch die Stadt zu laufen, wenn keine Autos fahren. Kinder können sicher mit dem Rad fahren, und die Cafés stellen ihre Tische auf die Straße.\n\nNatürlich brauchen manche Menschen das Auto, zum Beispiel Handwerker oder Familien mit kleinen Kindern. Deshalb schlage ich vor, dass Busse und Bahnen an diesen Tagen kostenlos fahren. So hätte jeder eine gute Alternative.",
      },
    ],
  },
];
