import type { SkillExercise } from "../types";

/** C1 — okuma, dinleme ve yazma egzersizleri. */
export const c1: SkillExercise[] = [
  // ---------------------------------------------------------------- OKUMA
  {
    id: "c1-r1",
    level: "C1",
    skill: "reading",
    title: "Die Verantwortungslücke",
    genre: "Deneme",
    intro: "Algoritmalar karar veriyor — ama yanıldıklarında sorumluluğu kim üstleniyor? Bu fikir yazısında yazarın savını ve ince ayrımlarını yakala.",
    minutes: 7,
    gloss: [
      { de: "die Vergabe", tr: "verme, tahsis" },
      { de: "die Urteilskraft", tr: "muhakeme gücü" },
      { de: "voreingenommen", tr: "önyargılı" },
      { de: "der Vertrauensvorschuss", tr: "peşin güven" },
      { de: "die Rechenschaft", tr: "hesap verme" },
      { de: "jemandem etwas zurechnen", tr: "birine atfetmek" },
      { de: "die Bonität", tr: "kredi itibarı" },
      { de: "strukturschwach", tr: "yapısal olarak zayıf (bölge)" },
      { de: "etwas fortschreiben", tr: "sürdürmek, devam ettirmek" },
      { de: "wohlfeil", tr: "ucuz, kolaycı (mecazi)" },
      { de: "einklagbar", tr: "dava yoluyla talep edilebilir" },
      { de: "etwas revidieren", tr: "gözden geçirip düzeltmek" },
    ],
    text: "Ob bei der Vergabe von Krediten, der Vorauswahl von Bewerbungen oder der Diagnose seltener Krankheiten – algorithmische Systeme treffen längst Entscheidungen, die tief in Lebensläufe eingreifen. Ihre Befürworter verweisen auf Effizienz und vermeintliche Objektivität; wer je einem voreingenommenen Sachbearbeiter gegenübersaß, mag der Maschine sogar mehr Fairness zutrauen. Doch dieser Vertrauensvorschuss beruht auf einer folgenreichen Verwechslung: Rechenleistung ist nicht Urteilskraft.\n\nDas Kernproblem lässt sich als Verantwortungslücke beschreiben. Irrt ein menschlicher Entscheider, kann er zur Rechenschaft gezogen werden; irrt ein lernendes System, verteilt sich die Verantwortung auf Entwickler, Betreiber und Datenlieferanten, bis sie am Ende niemandem mehr zuzurechnen ist. Die Technikphilosophin Judith Aschmann hat dafür das Bild der „organisierten Unverantwortlichkeit“ geprägt: Je komplexer das System, desto leichter fällt es jedem Beteiligten, auf die anderen zu verweisen.\n\nEmpirisch ist das Problem keineswegs marginal. Eine Untersuchung des Karlsruher Instituts für Technikfolgenabschätzung wertete im vergangenen Jahr rund 1.200 automatisierte Kreditentscheidungen aus und stellte fest, dass Antragsteller aus strukturschwachen Stadtteilen bei gleicher Bonität signifikant häufiger abgelehnt wurden. Der Fehler lag nicht im Code, sondern in den historischen Daten, die vergangene Diskriminierung schlicht fortschrieben. Besonders brisant: Die Betroffenen erfuhren in der Regel gar nicht, dass eine Maschine über sie geurteilt hatte – ein Widerspruch war damit faktisch ausgeschlossen.\n\nDaraus folgt nicht, algorithmische Systeme zu verbieten; eine solche Forderung wäre so wohlfeil wie wirkungslos. Zu verlangen ist vielmehr eine einklagbare Rechenschaftspflicht: Wer automatisierte Entscheidungen einsetzt, muss sie erklären, unabhängig überprüfen lassen und im Zweifel revidieren können. Die europäische KI-Verordnung weist in diese Richtung, bleibt bei den Sanktionen jedoch halbherzig. Solange sich Verantwortung im Geflecht der Zuständigkeiten verliert, gilt: Nicht die künstliche Intelligenz ist das eigentliche Risiko, sondern die menschliche Bequemlichkeit, ihr das Urteil zu überlassen.",
    questions: [
      {
        text: "Welche These vertritt der Autor in erster Linie?",
        options: [
          "Algorithmische Entscheidungen müssen mit einer durchsetzbaren Rechenschaftspflicht verbunden werden.",
          "Algorithmische Systeme sollten aus sensiblen Lebensbereichen vollständig verbannt werden.",
          "Maschinen entscheiden nachweislich fairer als voreingenommene Sachbearbeiter.",
        ],
        answer: 0,
        explain: "Yazar yasaklamayı „so wohlfeil wie wirkungslos“ (kolaycı ve etkisiz) diye reddediyor; asıl talebi „eine einklagbare Rechenschaftspflicht“, yani dava edilebilir bir hesap verme yükümlülüğü.",
      },
      {
        text: "Was ist mit der „Verantwortungslücke“ gemeint?",
        options: [
          "Entwicklern fehlt das juristische Wissen, um Verantwortung zu übernehmen.",
          "Bei Fehlern lernender Systeme verteilt sich die Verantwortung so, dass sie niemandem mehr zugerechnet werden kann.",
          "Der Staat hat bisher keine Behörde geschaffen, die Algorithmen kontrolliert.",
        ],
        answer: 1,
        explain: "İkinci paragraf tanımlıyor: sorumluluk geliştirici, işletmeci ve veri sağlayıcılar arasında dağılıyor, „bis sie am Ende niemandem mehr zuzurechnen ist“. Diğer şıklar metinde geçmeyen çıkarımlar.",
      },
      {
        text: "Laut der Karlsruher Untersuchung lag die Ursache der Benachteiligung in einem fehlerhaften Programmcode.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Metin tam tersini söylüyor: „Der Fehler lag nicht im Code, sondern in den historischen Daten“ — ayrımcılığı sürdüren şey geçmiş veriler.",
      },
      {
        text: "Wie beurteilt der Autor die europäische KI-Verordnung?",
        options: [
          "Sie geht in die richtige Richtung, ist bei den Sanktionen aber zu zurückhaltend.",
          "Sie verhindert wirksam, dass sich Verantwortung im Geflecht der Zuständigkeiten verliert.",
          "Sie ist gescheitert, weil sie automatisierte Entscheidungen pauschal verbietet.",
        ],
        answer: 0,
        explain: "Son paragrafta ince bir değerlendirme var: yönetmelik „weist in diese Richtung“ ama yaptırımlarda „halbherzig“ (gönülsüz) kalıyor.",
      },
      {
        text: "Die von der Studie untersuchten Antragsteller wussten meist nicht, dass eine Maschine über sie entschieden hatte.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Üçüncü paragraf bunu açıkça belirtiyor: „Die Betroffenen erfuhren in der Regel gar nicht, dass eine Maschine über sie geurteilt hatte“ — bu yüzden itiraz da fiilen imkânsızdı.",
      },
    ],
  },
  {
    id: "c1-r2",
    level: "C1",
    skill: "reading",
    title: "Ganztagsschule: Mehr als Aufbewahrung?",
    genre: "Bilimsel makale",
    intro: "Almanya'daki tam gün okul reformunu inceleyen bu makalede araştırma bulgularıyla siyasi vaatler arasındaki gerilimi çözümle.",
    minutes: 7,
    gloss: [
      { de: "der Rechtsanspruch", tr: "yasal hak" },
      { de: "händeringend", tr: "büyük bir çaresizlikle, acilen" },
      { de: "ernüchternd", tr: "hayal kırıklığına uğratan" },
      { de: "etwas verzahnen", tr: "birbirine geçirmek, bütünleştirmek" },
      { de: "aufholen", tr: "arayı kapatmak" },
      { de: "die Fachkraft", tr: "uzman eleman" },
      { de: "der Etikettenschwindel", tr: "etiket aldatmacası" },
      { de: "die Aufbewahrung", tr: "muhafaza; (burada) çocuk bekletme" },
      { de: "verbindlich", tr: "bağlayıcı" },
      { de: "leer ausgehen", tr: "eli boş kalmak" },
      { de: "auf etwas ausweichen", tr: "bir alternatife yönelmek" },
    ],
    text: "Ab dem Schuljahr 2026/27 haben Grundschulkinder in Deutschland einen Rechtsanspruch auf Ganztagsbetreuung – ein bildungspolitisches Großprojekt, das Eltern entlasten und Chancengleichheit fördern soll. Doch während die Kommunen händeringend Räume und Personal suchen, mehren sich die Zweifel, ob der Ausbau hält, was die Politik verspricht.\n\nNeue Befunde liefert die Langzeitstudie „LernZeit“ des Bamberger Instituts für Bildungsverläufe, die seit 2018 rund 9.400 Schülerinnen und Schüler begleitet. Das zentrale Ergebnis wirkt zunächst ernüchternd: Der bloße Besuch einer Ganztagsschule verbessert die Leistungen in Deutsch und Mathematik im Durchschnitt kaum. Entscheidend sei nicht die dort verbrachte Zeit, sondern deren Gestaltung, betont Studienleiterin Carolin Weidner. Erst wenn Unterricht, Förderung und Freizeitangebote systematisch verzahnt würden und qualifiziertes Personal die Lernbegleitung übernehme, zeigten sich messbare Effekte – dann allerdings deutliche: Kinder aus einkommensschwachen Familien holten in gut strukturierten Ganztagsschulen binnen zwei Jahren etwa ein halbes Schuljahr auf.\n\nGenau hier liegt das Dilemma. Nach Schätzungen des Deutschen Jugendinstituts fehlen bis 2030 mindestens 30.000 pädagogische Fachkräfte, um den Rechtsanspruch überhaupt zu erfüllen – von Qualität ist dabei noch gar nicht die Rede. Viele Träger behelfen sich bereits heute mit ungelerntem Personal und gekürzten Angeboten; mancherorts besteht der „Ganztag“ aus wenig mehr als beaufsichtigtem Warten.\n\nKritiker sprechen deshalb von einem drohenden Etikettenschwindel: Wo Ganztag draufstehe, dürfe nicht bloße Aufbewahrung drinstecken. Die Studienautoren plädieren dafür, den weiteren Ausbau an verbindliche Qualitätsstandards zu koppeln, statt allein die Zahl der Plätze zu zählen. Andernfalls drohe ein bitteres Paradox: Gut situierte Familien wichen auf private Angebote aus, während öffentliche Schulen in benachteiligten Vierteln mit unbesetzten Stellen kämpften – und ausgerechnet jene Kinder leer ausgingen, denen der Ganztag am meisten nützen könnte.",
    questions: [
      {
        text: "Was ist das zentrale Ergebnis der Studie „LernZeit“?",
        options: [
          "Ganztagsschulen verbessern die Leistungen aller Kinder deutlich und dauerhaft.",
          "Nicht die verbrachte Zeit, sondern die Qualität der Gestaltung entscheidet über den Lernerfolg.",
          "Der Besuch einer Ganztagsschule wirkt sich negativ auf Deutsch und Mathematik aus.",
        ],
        answer: 1,
        explain: "Çalışma yöneticisi Weidner'in vurgusu: „Entscheidend sei nicht die dort verbrachte Zeit, sondern deren Gestaltung“. İlk şık aşırı genelleme, üçüncüsü çarpıtma — metin ‚kaum verbessert‘ diyor, ‚verschlechtert‘ değil.",
      },
      {
        text: "Kinder aus einkommensschwachen Familien holten in gut strukturierten Ganztagsschulen innerhalb von zwei Jahren etwa ein halbes Schuljahr auf.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "İkinci paragrafın sonunda aynen böyle geçiyor — ama dikkat: bu etki yalnızca „gut strukturierte“ okullar için geçerli, genel ortalama için değil.",
      },
      {
        text: "Welche Rolle spielt der Fachkräftemangel im Text?",
        options: [
          "Er wurde durch den Rechtsanspruch bereits weitgehend behoben.",
          "Er betrifft ausschließlich private Träger von Ganztagsangeboten.",
          "Er gefährdet schon die reine Erfüllung des Rechtsanspruchs, noch bevor über Qualität gesprochen werden kann.",
        ],
        answer: 2,
        explain: "Üçüncü paragraf: 2030'a dek en az 30.000 pedagojik uzman eksik — „von Qualität ist dabei noch gar nicht die Rede“, yani nitelik tartışması bir yana, yasal hakkın kendisi bile tehlikede.",
      },
      {
        text: "Was fordern die Studienautoren?",
        options: [
          "Den Ausbau an verbindliche Qualitätsstandards zu koppeln, statt nur Plätze zu zählen.",
          "Den Rechtsanspruch zu verschieben, bis genügend Personal ausgebildet ist.",
          "Private Ganztagsangebote stärker staatlich zu fördern.",
        ],
        answer: 0,
        explain: "Son paragraf: yazarlar genişlemeyi „an verbindliche Qualitätsstandards zu koppeln“ öneriyor. Erteleme ya da özel teşvik metinde talep olarak geçmiyor.",
      },
      {
        text: "Der Autor deutet an, dass die Reform ausgerechnet den bedürftigsten Kindern am wenigsten nützen könnte.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Kapanıştaki „bitteres Paradox“: varlıklı aileler özel kurumlara kayarken dezavantajlı semtlerdeki okullar boş kadrolarla boğuşuyor — en çok yarar görecek çocuklar „leer ausgehen“ (eli boş kalma) riskinde.",
      },
    ],
  },
  {
    id: "c1-r3",
    level: "C1",
    skill: "reading",
    title: "Arbeitsmarkt 2035: Die Lücke",
    genre: "Kurumsal rapor",
    intro: "Bir araştırma merkezinin işgücü piyasası raporundan bu bölümde sayıları, bölgesel farkları ve önerilen önlem paketini takip et.",
    minutes: 7,
    gloss: [
      { de: "die Umwälzung", tr: "köklü dönüşüm" },
      { de: "altersbedingt", tr: "yaşa bağlı" },
      { de: "nachrücken", tr: "yerine gelmek, arkadan yetişmek" },
      { de: "die Wertschöpfung", tr: "katma değer üretimi" },
      { de: "der Ballungsraum", tr: "metropol bölgesi" },
      { de: "der Zuzug", tr: "göçle gelen nüfus" },
      { de: "die Nahversorgung", tr: "yerel temel hizmetler" },
      { de: "überzogen", tr: "abartılı" },
      { de: "personennah", tr: "insana dönük (hizmet)" },
      { de: "die Erwerbsbeteiligung", tr: "işgücüne katılım" },
      { de: "die Stellschraube", tr: "ayar vidası; müdahale kaldıracı" },
      { de: "das Zusammenspiel", tr: "birlikte işleyiş" },
    ],
    text: "Der deutsche Arbeitsmarkt steht vor der tiefgreifendsten Umwälzung seit der Wiedervereinigung. Nach Berechnungen des Mannheimer Zentrums für Arbeitsmarktanalysen scheiden bis 2035 rund 7,2 Millionen Erwerbstätige altersbedingt aus dem Berufsleben aus, während nur etwa 5,1 Millionen junge Menschen nachrücken. Die Lücke von über zwei Millionen Arbeitskräften trifft eine Volkswirtschaft, deren Wohlstandsmodell auf industrieller Wertschöpfung und einem dichten Netz mittelständischer Betriebe beruht.\n\nDie Folgen sind bereits heute messbar. In der Pflege bleibt gegenwärtig jede sechste Stelle unbesetzt; im Handwerk warten Kunden im Schnitt neun Wochen auf einen Termin. Bemerkenswert ist dabei die regionale Asymmetrie: Während Ballungsräume wie München oder Leipzig ihre Erwerbsbevölkerung durch Zuzug weitgehend stabil halten, verlieren ländliche Kreise vor allem in Ostdeutschland bis 2035 voraussichtlich ein Viertel ihrer Arbeitskräfte – mit entsprechenden Folgen für Nahversorgung, Steuerbasis und kommunale Infrastruktur.\n\nAls Gegenmittel wird häufig die Automatisierung angeführt. Der Bericht dämpft jedoch überzogene Erwartungen: Zwar ließen sich nach den Modellrechnungen bis zu 1,5 Millionen Stellen durch Digitalisierung und Robotik kompensieren, doch konzentriere sich dieses Potenzial auf standardisierbare Tätigkeiten in Industrie und Verwaltung. In personennahen Dienstleistungen – der Pflege, der Erziehung, dem Gesundheitswesen – stoße die Technik an offenkundige Grenzen; gerade dort aber wachse der Bedarf am schnellsten.\n\nDie Autoren plädieren daher für ein Maßnahmenbündel: eine qualifizierte Zuwanderung von jährlich mindestens 400.000 Personen, eine höhere Erwerbsbeteiligung von Frauen durch den konsequenten Ausbau der Kinderbetreuung sowie flexiblere Übergänge in den Ruhestand. Keine dieser Stellschrauben reiche für sich genommen aus; erst ihr Zusammenspiel könne die Lücke annähernd schließen. Der Bericht endet mit einer unbequemen Feststellung: Der demografische Wandel sei keine ferne Prognose mehr, sondern betriebswirtschaftlicher Alltag – und wer ihn weiterhin als Zukunftsthema behandle, habe die Gegenwart nicht verstanden.",
    questions: [
      {
        text: "Wie groß ist die erwartete Arbeitskräftelücke bis 2035?",
        options: [
          "Rund 7,2 Millionen Personen.",
          "Über zwei Millionen Personen.",
          "Etwa 400.000 Personen.",
        ],
        answer: 1,
        explain: "7,2 milyon ayrılan eksi 5,1 milyon gelen: „Die Lücke von über zwei Millionen Arbeitskräften“. 7,2 milyon toplam ayrılanların sayısı, 400.000 ise önerilen yıllık göç hedefi — tipik sayı çeldiricileri.",
      },
      {
        text: "Laut Bericht sind Ballungsräume und ländliche Kreise in gleichem Maße vom Verlust ihrer Erwerbsbevölkerung betroffen.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Metin „regionale Asymmetrie“ vurguluyor: metropoller göçle nüfusu koruyor, Doğu Almanya'nın kırsal ilçeleri ise işgücünün dörtte birini kaybediyor.",
      },
      {
        text: "Wie bewertet der Bericht das Potenzial der Automatisierung?",
        options: [
          "Sie kann die Lücke vollständig schließen, wenn sie konsequent umgesetzt wird.",
          "Sie hilft vor allem bei standardisierbaren Tätigkeiten, stößt aber in personennahen Dienstleistungen an Grenzen.",
          "Sie verschärft das Problem, weil sie zusätzliche Stellen vernichtet.",
        ],
        answer: 1,
        explain: "Üçüncü paragraf beklentileri frenliyor: 1,5 milyona kadar telafi mümkün, ama „in personennahen Dienstleistungen … stoße die Technik an offenkundige Grenzen“ — üstelik ihtiyaç en hızlı orada büyüyor.",
      },
      {
        text: "Was ist mit dem Bild der „Stellschrauben“ gemeint?",
        options: [
          "Jede einzelne Maßnahme könnte die Lücke auch allein schließen.",
          "Technische Lösungen sind den politischen Maßnahmen vorzuziehen.",
          "Nur das Zusammenspiel mehrerer Maßnahmen kann die Lücke annähernd schließen.",
        ],
        answer: 2,
        explain: "Metin açık: „Keine dieser Stellschrauben reiche für sich genommen aus; erst ihr Zusammenspiel könne die Lücke annähernd schließen.“ Konjunktiv I burada raporun aktarılan görüşünü işaretliyor.",
      },
      {
        text: "Der Bericht bezeichnet den demografischen Wandel als ein Problem, das erst in ferner Zukunft praktische Bedeutung erlangen wird.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Kapanış cümlesi tersini söylüyor: dönüşüm „keine ferne Prognose mehr, sondern betriebswirtschaftlicher Alltag“ — onu hâlâ gelecek konusu sayan, bugünü anlamamıştır.",
      },
    ],
  },
  {
    id: "c1-r4",
    level: "C1",
    skill: "reading",
    title: "„Kein Kind denkt in nur einer Sprache“",
    genre: "Röportaj",
    intro: "Dil bilimci Prof. Ayla Demir'le çok dillilik ve kimlik üzerine bu röportajda konuşmacının tezlerini ve itirazlara verdiği yanıtları izle.",
    minutes: 8,
    gloss: [
      { de: "die Mehrsprachigkeit", tr: "çok dillilik" },
      { de: "das Defizit", tr: "eksiklik" },
      { de: "die Herkunftssprache", tr: "köken dili" },
      { de: "etwas belegen", tr: "kanıtlamak" },
      { de: "das Sprachprestige", tr: "dil prestiji" },
      { de: "geringschätzen", tr: "küçümsemek" },
      { de: "das Sprachregister", tr: "dil kesiti, register" },
      { de: "die Bildungssprache", tr: "akademik dil" },
      { de: "etwas verkennen", tr: "yanlış değerlendirmek, görememek" },
      { de: "die Ressource", tr: "kaynak" },
      { de: "das Selbstverständnis", tr: "öz algı, kendini tanımlama" },
    ],
    text: "Frau Professor Demir, Sie behaupten, Mehrsprachigkeit werde in Deutschland noch immer als Problem behandelt. Ist dieser Vorwurf nicht längst überholt?\n\nDemir: Leider nein. In Sonntagsreden gilt Mehrsprachigkeit als Reichtum, im Schulalltag dagegen oft als Störfaktor. Entscheidend ist dabei, um welche Sprachen es geht: Ein Kind, das Englisch und Französisch spricht, wird bewundert; ein Kind, das Türkisch oder Arabisch mitbringt, gilt schnell als förderbedürftig. Das ist keine Frage der Sprachen selbst, sondern ihres gesellschaftlichen Prestiges.\n\nKritiker wenden ein, dass Kinder zuerst sicher Deutsch lernen sollten, bevor die Familiensprache gefördert wird.\n\nDemir: Diese Entgegensetzung verkennt, wie Spracherwerb funktioniert. Vier Jahrzehnte Forschung belegen: Wer seine Herkunftssprache gut beherrscht, lernt die Umgebungssprache nicht langsamer, sondern in der Regel schneller, weil grammatisches Wissen und Begriffsbildung übertragbar sind. Unsere Frankfurter Längsschnittstudie mit 2.300 Grundschulkindern zeigt zudem: Wird die Familiensprache systematisch einbezogen, verbessern sich mittelfristig auch die Deutschleistungen. Was Kindern tatsächlich schadet, ist nicht die zweite Sprache, sondern das Signal, ein Teil ihrer selbst sei in der Schule unerwünscht.\n\nWas bedeutet das für die Identität der Kinder?\n\nDemir: Sprache ist nie nur Werkzeug, sie ist Selbstverständnis. Wer die Sprache der Großeltern geringschätzt, geringschätzt einen Teil der Biografie des Kindes. Viele meiner Studierenden erzählen, sie hätten sich jahrelang für ihr Türkisch geschämt und es erst an der Universität als Ressource entdeckt. Diese verlorenen Jahre sind vermeidbar.\n\nWas müsste sich konkret ändern?\n\nDemir: Dreierlei. Herkunftssprachlicher Unterricht muss reguläres, benotetes Schulfach werden statt Randstunde am Nachmittag. Lehrkräfte brauchen in der Ausbildung verpflichtende Module zur Mehrsprachigkeitsdidaktik. Und wir sollten aufhören, Bildungssprache und Familiensprache gegeneinander auszuspielen: Ziel ist nicht weniger Deutsch, sondern mehr Sprachbewusstsein insgesamt. Ein Kind, das zwischen Registern und Sprachen wechseln kann, hat genau die Kompetenz erworben, die wir sonst teuer in Fremdsprachenkursen einzukaufen versuchen.",
    questions: [
      {
        text: "Worin sieht Demir den Kern des Problems im Umgang mit Mehrsprachigkeit?",
        options: [
          "Deutsche Schulen bieten generell zu wenige Fremdsprachen an.",
          "Nicht die Sprachen selbst, sondern ihr unterschiedliches gesellschaftliches Prestige entscheidet über die Bewertung.",
          "Kinder mit Türkisch oder Arabisch lernen nachweislich langsamer Deutsch.",
        ],
        answer: 1,
        explain: "Demir'in ilk cevabındaki karşıtlık: İngilizce-Fransızca bilen çocuk „bewundert“, Türkçe-Arapça getiren „förderbedürftig“ sayılıyor — „keine Frage der Sprachen selbst, sondern ihres gesellschaftlichen Prestiges“.",
      },
      {
        text: "Wie reagiert Demir auf den Einwand, Kinder sollten zuerst Deutsch lernen?",
        options: [
          "Sie hält die Entgegensetzung für falsch, weil eine gefestigte Herkunftssprache den Deutscherwerb sogar beschleunigt.",
          "Sie räumt ein, dass die Familiensprache den Deutscherwerb anfangs verzögert.",
          "Sie fordert, den Deutschunterricht zugunsten der Herkunftssprachen zu kürzen.",
        ],
        answer: 0,
        explain: "„Diese Entgegensetzung verkennt, wie Spracherwerb funktioniert“ — kırk yıllık araştırma, köken dilini iyi bilenin çevre dilini „in der Regel schneller“ öğrendiğini gösteriyor. Üçüncü şık, son cevaptaki „nicht weniger Deutsch“ ifadesiyle açıkça çelişir.",
      },
      {
        text: "Die Frankfurter Studie zeigt, dass sich die Deutschleistungen verbessern, wenn die Familiensprache systematisch einbezogen wird.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Demir 2.300 ilkokul çocuğuyla yapılan boylamsal çalışmayı aktarıyor: aile dili sistematik biçimde dahil edilince „mittelfristig auch die Deutschleistungen“ iyileşiyor.",
      },
      {
        text: "Was schadet Kindern laut Demir tatsächlich?",
        options: [
          "Das frühe Erlernen einer zweiten Sprache.",
          "Das Signal, ein Teil ihrer selbst sei in der Schule unerwünscht.",
          "Der verpflichtende herkunftssprachliche Unterricht am Nachmittag.",
        ],
        answer: 1,
        explain: "Cümle metinde birebir var: zarar veren ikinci dil değil, „das Signal, ein Teil ihrer selbst sei in der Schule unerwünscht“. Konjunktiv I burada aktarılan mesajı gösteriyor.",
      },
      {
        text: "Demir fordert, herkunftssprachlichen Unterricht als freiwillige Nachmittagsstunde beizubehalten.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Tam tersi: köken dili dersi „reguläres, benotetes Schulfach werden statt Randstunde am Nachmittag“ — yani öğleden sonraki kenar saat olmaktan çıkmalı.",
      },
    ],
  },
  {
    id: "c1-r5",
    level: "C1",
    skill: "reading",
    title: "Das Museum als Mitmachzone",
    genre: "Kültür eleştirisi",
    intro: "Bir kültür eleştirmeni, müzelerdeki „katılım“ modasını mercek altına alıyor — eleştirinin nerede keskinleştiğine, nerede kendini sınırladığına dikkat et.",
    minutes: 7,
    gloss: [
      { de: "die Teilhabe", tr: "katılım, pay alma" },
      { de: "die Verheißung", tr: "vaat" },
      { de: "die Schwellenangst", tr: "eşik korkusu, çekingenlik" },
      { de: "etwas bespielen", tr: "(bir mekânı) etkinlikle doldurmak" },
      { de: "die Zumutung", tr: "zorlayıcı talep, külfet" },
      { de: "die Kontemplation", tr: "derin düşünme, temaşa" },
      { de: "verwechselbar", tr: "birbirinden ayırt edilemez" },
      { de: "die Kennzahl", tr: "performans göstergesi" },
      { de: "der Selbstzweck", tr: "kendinde amaç" },
      { de: "etwas preisgeben", tr: "feda etmek, elden çıkarmak" },
      { de: "die Ermäßigung", tr: "indirim" },
    ],
    text: "Kaum ein Begriff wird in deutschen Museen derzeit häufiger beschworen als „Teilhabe“. Besucher sollen nicht mehr betrachten, sondern mitmachen: Selfie-Stationen im Barocksaal, Abstimmungsterminals neben der Videokunst, Workshops, in denen jeder „seine eigene Geschichte“ erzählen darf. Die Verheißung dahinter ist sympathisch – das Museum, einst Tempel des Bildungsbürgertums, öffnet sich endlich allen. Wer wollte dagegen sein?\n\nUnd tatsächlich: Die Kritik an der alten Ehrfurchtsarchitektur war berechtigt. Museen, deren Schwellenangst höher lag als ihre Besucherzahlen, haben ihren öffentlichen Auftrag verfehlt. Dass Häuser wie das Essener Industriemuseum Zollstern heute Schichtarbeiter, Schulklassen und Nachbarschaftsinitiativen erreichen, ist ein Gewinn, den niemand ernsthaft bestreiten kann.\n\nDoch inzwischen kippt die Bewegung ins Gegenteil. Wo jede Ausstellung zur „Erlebniswelt“ bespielt wird, verschwindet ausgerechnet das, was das Museum von allen anderen Orten unterscheidet: die Erlaubnis zur langsamen, konzentrierten Wahrnehmung. Kunst ist auch eine Zumutung – sie verlangt Zeit, Irritation, mitunter Langeweile, aus der erst Aufmerksamkeit entsteht. Ein Haus, das jede Reibung durch Interaktionsangebote glättet, behandelt seine Besucher nicht als mündiges Publikum, sondern als Kundschaft, deren Verweildauer optimiert werden muss. Das Ergebnis sind Ausstellungen, die sich weltweit zum Verwechseln ähneln: dieselben Touchscreens, dieselben Mitmachwände, dieselbe freundliche Belanglosigkeit.\n\nDie Ursache liegt weniger bei den Kuratoren als bei den Kennzahlen. Wer seine Förderung über Besucherstatistiken und „Interaktionsraten“ rechtfertigen muss, programmiert eben das, was sich zählen lässt. Teilhabe aber ist kein Selbstzweck und schon gar kein Klickmaß; sie bemisst sich daran, ob Menschen das Haus anders verlassen, als sie es betreten haben. Ein Museum, das seine Eigenzeit preisgibt, um niemanden zu überfordern, unterfordert am Ende alle – und verspielt gerade jenes Vertrauen in die Urteilsfähigkeit seines Publikums, das echte Öffnung erst möglich machen würde.",
    questions: [
      {
        text: "Wie steht der Autor zur Öffnung der Museen insgesamt?",
        options: [
          "Er hält sie grundsätzlich für einen Gewinn, kritisiert aber ihre aktuelle Übertreibung.",
          "Er lehnt sie ab und wünscht sich die alte Ehrfurchtsarchitektur zurück.",
          "Er hält sie für gescheitert, weil sie keine neuen Besuchergruppen erreicht hat.",
        ],
        answer: 0,
        explain: "İkinci paragraf açılımı savunuyor („ein Gewinn, den niemand ernsthaft bestreiten kann“), üçüncüsü „Doch inzwischen kippt die Bewegung ins Gegenteil“ diyerek abartıya yöneliyor — tipik C1 nüansı: eleştiri, reddiye değil.",
      },
      {
        text: "Was geht laut Autor verloren, wenn jede Ausstellung zur „Erlebniswelt“ wird?",
        options: [
          "Die finanzielle Unabhängigkeit der Museen.",
          "Die Möglichkeit zur langsamen, konzentrierten Wahrnehmung.",
          "Der Zugang von Schulklassen und Nachbarschaftsinitiativen.",
        ],
        answer: 1,
        explain: "Üçüncü paragraf: kaybolan şey müzeyi diğer mekânlardan ayıran „die Erlaubnis zur langsamen, konzentrierten Wahrnehmung“. Okul sınıfları örneği tam tersine kazanç hanesinde anılıyor.",
      },
      {
        text: "Der Autor macht in erster Linie die Kuratoren für die Entwicklung verantwortlich.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "„Die Ursache liegt weniger bei den Kuratoren als bei den Kennzahlen“ — sorumluluk küratörlerden çok, teşvikleri ziyaretçi istatistiklerine bağlayan gösterge mantığında.",
      },
      {
        text: "Woran bemisst sich echte Teilhabe nach Ansicht des Autors?",
        options: [
          "An der Zahl der Interaktionen pro Ausstellung.",
          "An der durchschnittlichen Verweildauer der Besucher.",
          "Daran, ob Menschen das Haus anders verlassen, als sie es betreten haben.",
        ],
        answer: 2,
        explain: "Son paragraf: katılım „kein Klickmaß“; ölçüsü, insanların müzeden girdiklerinden farklı çıkıp çıkmadığı. İlk iki şık metnin eleştirdiği sayaç mantığının ta kendisi.",
      },
      {
        text: "Mit der Formulierung „Kunst ist auch eine Zumutung“ meint der Autor, dass Kunst dem Publikum etwas abverlangen darf.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Cümlenin devamı bunu açıklıyor: sanat „Zeit, Irritation, mitunter Langeweile“ talep eder — dikkat ancak bu zorlanmadan doğar. „Zumutung“ burada olumsuz değil, üretken bir külfet.",
      },
    ],
  },
  {
    id: "c1-r6",
    level: "C1",
    skill: "reading",
    title: "Slowbalisierung: Das Ende einer Illusion?",
    genre: "Analiz",
    intro: "Küreselleşme geri mi çekiliyor, yoksa biçim mi değiştiriyor? Bu ekonomi analizinde yazarın verilerle kurduğu ayrımları çöz.",
    minutes: 8,
    gloss: [
      { de: "die Lieferkette", tr: "tedarik zinciri" },
      { de: "die Arbeitsteilung", tr: "iş bölümü" },
      { de: "das Schlagwort", tr: "moda kavram, slogan" },
      { de: "die Rückverlagerung", tr: "üretimi geri taşıma" },
      { de: "stagnieren", tr: "durağanlaşmak" },
      { de: "die Verflechtung", tr: "iç içe geçmişlik" },
      { de: "geopolitisch", tr: "jeopolitik" },
      { de: "die Abhängigkeit", tr: "bağımlılık" },
      { de: "etwas diversifizieren", tr: "çeşitlendirmek" },
      { de: "die Standortentscheidung", tr: "yer seçimi kararı" },
      { de: "vollmundig", tr: "iddialı, abartılı (söylem)" },
      { de: "die Neuordnung", tr: "yeniden düzenleme" },
    ],
    text: "Als im Frühjahr 2021 ein quergestelltes Containerschiff den Suezkanal blockierte, wurde das Bild binnen Stunden zur Metapher: Die Weltwirtschaft, so schien es, hatte sich in ihrer eigenen Effizienz verkeilt. Seither hat das Schlagwort von der „Deglobalisierung“ Konjunktur. Pandemie, Kriege und Handelskonflikte, heißt es, beendeten das Zeitalter der grenzenlosen Arbeitsteilung; die Zukunft gehöre der heimischen Fabrik. Doch ein nüchterner Blick auf die Daten erzählt eine kompliziertere Geschichte.\n\nRichtig ist: Der Welthandel wächst seit gut einem Jahrzehnt langsamer als die Weltwirtschaft – Ökonomen sprechen von „Slowbalisierung“. Richtig ist auch, dass Regierungen Halbleiter, Arzneimittel und Batterien inzwischen als strategische Güter behandeln und ihre Produktion mit Milliardensubventionen ins eigene Land holen. Von einer breiten Rückverlagerung kann dennoch keine Rede sein. Nach einer Auswertung des Kieler Instituts für Weltwirtschaftsforschung haben von 1.800 befragten europäischen Industrieunternehmen lediglich vier Prozent Produktion tatsächlich zurückgeholt; mehr als ein Drittel hat stattdessen seine Lieferanten diversifiziert – weg von der Konzentration auf ein einzelnes Land, hin zu einem Netz aus mehreren Standorten.\n\nWas sich verändert, ist also weniger das Ausmaß als die Landkarte der Verflechtung. An die Stelle der reinen Kostenlogik tritt eine geopolitische: Gehandelt wird zunehmend mit Partnern, die als politisch verlässlich gelten – „Friendshoring“ nennt das die Fachdebatte. Für Deutschland, dessen Wohlstand wie in kaum einem anderen Land am Export hängt, ist das eine unbequeme Neuordnung: Sicherheit kostet Effizienz, und die Rechnung zahlen zunächst die Verbraucher.\n\nDie vollmundige Rede vom Ende der Globalisierung verfehlt daher den Kern. Die weltwirtschaftliche Verflechtung verschwindet nicht, sie wird neu sortiert – langsamer, teurer, politischer. Wer diesen Unterschied ignoriert, dem entgehen die eigentlichen Fragen: Welche Abhängigkeiten sind tragbar, welche nicht? Und wer entscheidet darüber – Märkte oder Parlamente?",
    questions: [
      {
        text: "Welche Kernaussage vertritt der Text?",
        options: [
          "Die Globalisierung endet, und die Produktion kehrt in die Heimatländer zurück.",
          "Die weltwirtschaftliche Verflechtung verschwindet nicht, sondern wird neu geordnet.",
          "Der Welthandel wächst wieder schneller als die Weltwirtschaft.",
        ],
        answer: 1,
        explain: "Son paragraf tezi özetliyor: „Die weltwirtschaftliche Verflechtung verschwindet nicht, sie wird neu sortiert – langsamer, teurer, politischer.“ İlk şık, metnin eleştirdiği „vollmundige Rede“nin kendisi.",
      },
      {
        text: "Was ergab die Auswertung des Kieler Instituts?",
        options: [
          "Mehr als ein Drittel der Unternehmen hat seine Lieferanten diversifiziert, nur vier Prozent haben Produktion zurückgeholt.",
          "Vier Prozent der Unternehmen haben ihre Lieferketten diversifiziert.",
          "Mehr als ein Drittel der Unternehmen hat Produktion nach Europa zurückverlagert.",
        ],
        answer: 0,
        explain: "Sayı çeldiricisine dikkat: geri taşıyan yalnızca yüzde 4, tedarikçilerini çeşitlendiren „mehr als ein Drittel“. Diğer iki şık bu iki sayıyı yer değiştiriyor.",
      },
      {
        text: "Der Begriff „Slowbalisierung“ bezeichnet ein Schrumpfen des Welthandels auf das Niveau der 1990er Jahre.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Kavram küçülmeyi değil yavaşlamayı anlatıyor: dünya ticareti on yıldır dünya ekonomisinden „langsamer wächst“ — hâlâ büyüyor, sadece daha yavaş.",
      },
      {
        text: "Was ist mit „Friendshoring“ gemeint?",
        options: [
          "Der Handel mit politisch als verlässlich geltenden Partnern statt nach reiner Kostenlogik.",
          "Die Verlagerung der Produktion in Länder mit den niedrigsten Löhnen.",
          "Ein Subventionsprogramm der Europäischen Union für Halbleiter.",
        ],
        answer: 0,
        explain: "Üçüncü paragraf tanımlıyor: maliyet mantığının yerini jeopolitik mantık alıyor, ticaret „mit Partnern, die als politisch verlässlich gelten“ yapılıyor.",
      },
      {
        text: "Der Autor weist darauf hin, dass die neue Sicherheitsorientierung ihren Preis hat, den zunächst die Verbraucher zahlen.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Almanya için „unbequeme Neuordnung“: „Sicherheit kostet Effizienz, und die Rechnung zahlen zunächst die Verbraucher.“",
      },
    ],
  },

  // -------------------------------------------------------------- DİNLEME
  {
    id: "c1-l1",
    level: "C1",
    skill: "listening",
    title: "Warum Fakten allein nicht überzeugen",
    genre: "Konferans",
    intro: "Bilim iletişimi kongresindeki bu açılış konuşmasında konuşmacının çürüttüğü modeli ve önerdiği üç sonucu not al.",
    minutes: 6,
    gloss: [
      { de: "das Defizitmodell", tr: "eksiklik modeli" },
      { de: "die Zustimmung", tr: "onay, kabul" },
      { de: "etwas widerlegen", tr: "çürütmek" },
      { de: "die Einstellung", tr: "tutum" },
      { de: "die Zugehörigkeit", tr: "aidiyet" },
      { de: "die Glaubwürdigkeit", tr: "inandırıcılık" },
      { de: "etwas offenlegen", tr: "açıkça ortaya koymak" },
      { de: "Gewissheit vortäuschen", tr: "kesinlik taslamak" },
      { de: "Fehler einräumen", tr: "hatayı kabul etmek" },
      { de: "die Unfehlbarkeit", tr: "yanılmazlık" },
    ],
    segments: [
      {
        text: "Meine Damen und Herren, ich freue mich, Sie zur diesjährigen Tagung des Netzwerks Wissenschaftskommunikation begrüßen zu dürfen. Mein Thema klingt zunächst paradox: Warum überzeugen Fakten allein nicht – und was folgt daraus für unseren Umgang mit der Öffentlichkeit?",
      },
      {
        text: "Jahrzehntelang folgte die Wissenschaftskommunikation dem sogenannten Defizitmodell. Die Annahme lautete: Wenn Menschen Forschungsergebnisse ablehnen, fehlt ihnen schlicht das Wissen. Man müsse die Lücke nur mit verständlichen Informationen füllen, dann stelle sich die Zustimmung von selbst ein.",
      },
      {
        text: "Die empirische Forschung hat dieses Modell gründlich widerlegt. Eine Auswertung von mehr als achtzig Einzelstudien, die wir im vergangenen Jahr an der Universität Erfurt abgeschlossen haben, zeigt: Zusätzliches Wissen verändert Einstellungen kaum, sobald ein Thema die eigene Identität berührt. Wer sich einer Gemeinschaft zugehörig fühlt, die etwa dem Impfen skeptisch gegenübersteht, verarbeitet neue Informationen nicht neutral, sondern als Angriff auf diese Zugehörigkeit.",
      },
      {
        text: "Entscheidend ist stattdessen Vertrauen. Menschen fragen nicht zuerst: Stimmt das? Sie fragen: Wer sagt das, und meint diese Person es gut mit mir? Unsere Daten zeigen deutlich: Kommunikation, die Unsicherheiten offenlegt und eigene Interessenkonflikte benennt, wirkt glaubwürdiger als eine, die Gewissheit vortäuscht.",
      },
      {
        text: "Daraus ergeben sich drei praktische Konsequenzen. Erstens: Hören Sie zu, bevor Sie senden – wer die Sorgen seines Publikums nicht kennt, redet an ihm vorbei. Zweitens: Erzählen Sie von Menschen und Entscheidungen, nicht nur von Zahlen; Geschichten schaffen die Anschlussstellen, an denen Fakten überhaupt erst haften bleiben. Drittens: Räumen Sie Fehler öffentlich ein, auch wenn es unbequem ist.",
      },
      {
        text: "Denn das ist der Kern meiner Botschaft: Wissenschaft verliert ihre Autorität nicht durch das Eingeständnis von Grenzen, sondern durch den Anschein der Unfehlbarkeit. Vielen Dank für Ihre Aufmerksamkeit.",
      },
    ],
    questions: [
      {
        text: "Was besagt das sogenannte Defizitmodell?",
        options: [
          "Ablehnung von Forschung beruht auf fehlendem Wissen und verschwindet durch verständliche Information.",
          "Der Wissenschaft fehlen die finanziellen Mittel für gute Kommunikation.",
          "Das Publikum vertraut Forschern grundsätzlich weniger als Journalisten.",
        ],
        answer: 0,
        explain: "İkinci bölümde tanımlanıyor: insanlar bilgiyi reddediyorsa „fehlt ihnen schlicht das Wissen“ varsayımı — boşluğu bilgiyle doldurunca onayın kendiliğinden geleceği düşünülüyordu.",
      },
      {
        text: "Unter welcher Bedingung verändert zusätzliches Wissen die Einstellungen kaum?",
        options: [
          "Wenn die Informationen zu kompliziert formuliert sind.",
          "Wenn das Thema die eigene Identität berührt.",
          "Wenn die Studienlage widersprüchlich ist.",
        ],
        answer: 1,
        explain: "Erfurt araştırmasının bulgusu: „sobald ein Thema die eigene Identität berührt“ — aidiyet devreye girince yeni bilgi saldırı olarak işleniyor.",
      },
      {
        text: "Laut Vortrag wirkt Kommunikation glaubwürdiger, wenn sie Unsicherheiten verschweigt und Sicherheit ausstrahlt.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Konuşmacı tersini söylüyor: belirsizlikleri açıklayan ve çıkar çatışmalarını adlandıran iletişim, „Gewissheit vortäuscht“ olandan daha inandırıcı.",
      },
      {
        text: "Welche Funktion haben Geschichten laut dem Vortrag?",
        options: [
          "Sie ersetzen Zahlen, die das Publikum ohnehin nicht versteht.",
          "Sie lenken von unbequemen Forschungsergebnissen ab.",
          "Sie schaffen Anschlussstellen, an denen Fakten haften bleiben.",
        ],
        answer: 2,
        explain: "İkinci pratik sonuç: hikâyeler „die Anschlussstellen, an denen Fakten überhaupt erst haften bleiben“ yaratıyor — sayıların yerine geçmiyor, tutunmasını sağlıyor.",
      },
      {
        text: "Der Redner warnt, Wissenschaft verliere ihre Autorität vor allem durch das öffentliche Eingeständnis von Fehlern.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Kapanış cümlesi tam tersi: otorite kaybının nedeni sınırların itirafı değil, „der Anschein der Unfehlbarkeit“ — yanılmazlık görüntüsü.",
      },
    ],
  },
  {
    id: "c1-l2",
    level: "C1",
    skill: "listening",
    title: "Streitfall Nachverdichtung",
    genre: "Panel",
    intro: "Kent gelişimi panelinde iki uzman yoğunlaştırma konusunda karşı karşıya — kimin hangi gerekçeyle nerede uzlaştığını yakala.",
    minutes: 6,
    gloss: [
      { de: "die Nachverdichtung", tr: "kentsel yoğunlaştırma" },
      { de: "die Wohnungsnot", tr: "konut sıkıntısı" },
      { de: "die Baulücke", tr: "yapı boşluğu, boş parsel" },
      { de: "etwas aufstocken", tr: "kat çıkmak" },
      { de: "die Versiegelung", tr: "zemini betonla kaplama" },
      { de: "die Frischluftschneise", tr: "temiz hava koridoru" },
      { de: "die Hitzeinsel", tr: "ısı adası" },
      { de: "der Bestand", tr: "mevcut yapı stoku" },
      { de: "der Leerstand", tr: "boş duran konut/bina" },
      { de: "die Umnutzung", tr: "işlev değişikliği" },
      { de: "der Zielkonflikt", tr: "hedef çatışması" },
    ],
    segments: [
      {
        speaker: "Moderatorin",
        text: "Willkommen zu unserem Stadtgespräch. In den deutschen Großstädten fehlen nach aktuellen Schätzungen rund 550.000 Wohnungen. Zugleich heizen sich die Innenstädte im Sommer immer stärker auf. Frau Professor Wenzel, Sie sagen: Wir müssen dichter bauen. Warum?",
      },
      {
        speaker: "Professorin Wenzel",
        text: "Weil jede nicht gebaute Wohnung in der Stadt am Stadtrand doppelt gebaut wird – mit neuen Straßen, langen Pendelwegen und deutlich höherem Flächenverbrauch. Nachverdichtung heißt ja nicht, jeden Hof zuzubetonieren. Es heißt: Baulücken schließen, Gebäude aufstocken, eingeschossige Supermärkte mit Wohnungen überbauen. Allein durch Aufstockung ließen sich nach unseren Berechnungen bundesweit etwa 400.000 Wohnungen schaffen, ohne einen einzigen Quadratmeter zusätzlich zu versiegeln.",
      },
      {
        speaker: "Moderatorin",
        text: "Herr Roth, Sie sind Landschaftsarchitekt und sehen das kritischer.",
      },
      {
        speaker: "Herr Roth",
        text: "Ich widerspreche gar nicht grundsätzlich, aber die Praxis sieht anders aus. Verdichtet wird dort, wo es am billigsten ist: auf Grünflächen und in Innenhöfen. Genau diese Flächen kühlen aber die Stadt. Wenn wir Frischluftschneisen zubauen, verwandeln wir Quartiere in Hitzeinseln – und die Leidtragenden sind ältere Menschen und Familien, die sich keine Klimaanlage leisten können. Wohnungsbau gegen Klimaanpassung auszuspielen, halte ich für kurzsichtig.",
      },
      {
        speaker: "Professorin Wenzel",
        text: "Da bin ich völlig bei Ihnen – deshalb spreche ich von qualifizierter Dichte. Wer aufstockt, muss zugleich Dächer begrünen, Fassaden beschatten und Höfe entsiegeln. Und wir sollten endlich über den Bestand reden: Millionen Quadratmeter Büros stehen seit der Pandemie leer. Ihre Umnutzung zu Wohnraum wäre die klimafreundlichste Verdichtung überhaupt.",
      },
      {
        speaker: "Herr Roth",
        text: "Wenn Verdichtung so verstanden wird, trage ich sie mit. Meine Bedingung bleibt allerdings: Für jeden neuen Quadratmeter Wohnfläche muss die Stadt an anderer Stelle messbar grüner werden. Sonst lösen wir die Wohnungsnot und schaffen die nächste Krise gleich mit.",
      },
      {
        speaker: "Moderatorin",
        text: "Qualifizierte Dichte statt bloßer Masse – so weit scheint der Konsens zu reichen. Vielen Dank Ihnen beiden für dieses Gespräch.",
      },
    ],
    questions: [
      {
        text: "Mit welchem Argument begründet Professorin Wenzel die Nachverdichtung?",
        options: [
          "Wohnungen am Stadtrand sind für Familien unattraktiv geworden.",
          "Jede nicht gebaute Wohnung in der Stadt verursacht am Stadtrand höheren Flächenverbrauch.",
          "Innenhöfe und Grünflächen werden in Großstädten kaum genutzt.",
        ],
        answer: 1,
        explain: "Wenzel'in açılış argümanı: şehirde yapılmayan konut kenar mahallede „doppelt gebaut“ oluyor — yeni yollar, uzun mesafeler, daha çok arazi tüketimi.",
      },
      {
        text: "Wovor warnt Herr Roth?",
        options: [
          "Dass Verdichtung in der Praxis auf kühlenden Grünflächen stattfindet und Hitzeinseln erzeugt.",
          "Dass Aufstockungen die Statik älterer Gebäude gefährden.",
          "Dass Nachverdichtung die Mieten in den Innenstädten weiter erhöht.",
        ],
        answer: 0,
        explain: "Roth pratiğe itiraz ediyor: yoğunlaştırma en ucuz yerde, yani yeşil alanlarda oluyor; hava koridorları kapanınca mahalleler „Hitzeinseln“e dönüşüyor. Statik ve kira konusu hiç geçmiyor.",
      },
      {
        text: "Herr Roth lehnt jede Form von Nachverdichtung grundsätzlich ab.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Kendisi açıkça „Ich widerspreche gar nicht grundsätzlich“ diyor ve sonda koşullu destek veriyor — itirazı ilkeye değil uygulamaya.",
      },
      {
        text: "Was versteht Wenzel unter „qualifizierter Dichte“?",
        options: [
          "Verdichtung nur in Vierteln mit hoher Nachfrage.",
          "Verdichtung, die mit Dachbegrünung, Beschattung und Entsiegelung einhergeht.",
          "Verdichtung ausschließlich durch den Neubau von Hochhäusern.",
        ],
        answer: 1,
        explain: "Wenzel kavramı tanımlıyor: kat çıkan „zugleich Dächer begrünen, Fassaden beschatten und Höfe entsiegeln“ zorunda — yoğunlaşma iklim önlemleriyle birlikte gitmeli.",
      },
      {
        text: "Beide Fachleute sehen in der Umnutzung leerstehender Büros eine sinnvolle Möglichkeit, Wohnraum zu schaffen.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Wenzel boş ofislerin dönüşümünü „die klimafreundlichste Verdichtung überhaupt“ diye öneriyor; Roth da „Wenn Verdichtung so verstanden wird, trage ich sie mit“ diyerek katılıyor.",
      },
    ],
  },
  {
    id: "c1-l3",
    level: "C1",
    skill: "listening",
    title: "Künstliche Intelligenz in der Diagnostik",
    genre: "Akademik röportaj",
    intro: "Bir tıp bilişimi profesörüyle yapılan bu akademik söyleşide fırsatlarla riskler arasındaki dengeyi ve sorumluluk sorusunu izle.",
    minutes: 6,
    gloss: [
      { de: "die Diagnostik", tr: "tanı bilimi" },
      { de: "die Treffsicherheit", tr: "isabet oranı" },
      { de: "etwas übersehen", tr: "gözden kaçırmak" },
      { de: "der Automatisierungsbias", tr: "otomasyon yanlılığı" },
      { de: "die Haftung", tr: "yasal sorumluluk" },
      { de: "das Werkzeug", tr: "araç" },
      { de: "die Zulassung", tr: "ruhsat, onay" },
      { de: "der Befund", tr: "bulgu" },
      { de: "etwas hinterfragen", tr: "sorgulamak" },
      { de: "die Entlastung", tr: "yük hafifletme" },
    ],
    segments: [
      {
        speaker: "Moderator",
        text: "Herr Professor Lehmann, Sie erforschen den Einsatz künstlicher Intelligenz in der medizinischen Diagnostik. Wie gut sind diese Systeme inzwischen wirklich?",
      },
      {
        speaker: "Professor Lehmann",
        text: "In eng umgrenzten Aufgaben erstaunlich gut. In unserer Heidelberger Studie hat ein Bilderkennungssystem verdächtige Hautveränderungen mit einer Treffsicherheit von 94 Prozent erkannt, erfahrene Fachärzte kamen auf 87 Prozent. Aber dieser Vergleich führt in die Irre, wenn man ihn absolut setzt. Die Maschine erkennt Muster in Bildern – sie kennt weder die Krankengeschichte noch die Lebensumstände des Patienten.",
      },
      {
        speaker: "Moderator",
        text: "Trotzdem klingt das nach einer klaren Verbesserung. Wo liegt das Problem?",
      },
      {
        speaker: "Professor Lehmann",
        text: "Im sogenannten Automatisierungsbias. Wir haben Ärztinnen und Ärzte absichtlich mit fehlerhaften Systemvorschlägen konfrontiert. Das Ergebnis hat uns beunruhigt: Fast ein Drittel übernahm die falsche Einschätzung, obwohl sie ohne das System richtig geurteilt hätte. Je überzeugender die Technik auftritt, desto eher schaltet der Mensch das eigene Urteil ab. Genau das Gegenteil dessen, was wir wollen.",
      },
      {
        speaker: "Moderator",
        text: "Wer haftet denn, wenn eine solche gemeinsame Entscheidung falsch ist?",
      },
      {
        speaker: "Professor Lehmann",
        text: "Rechtlich ist das eindeutig: die behandelnde Ärztin oder der behandelnde Arzt. Die Systeme sind als Unterstützung zugelassen, nicht als Entscheider. Deshalb sage ich meinen Studierenden immer: Die künstliche Intelligenz ist ein Werkzeug, kein Kollege. Ein Befund, den ich nicht hinterfragen kann, ist keine Entlastung, sondern ein Risiko.",
      },
      {
        speaker: "Moderator",
        text: "Was müsste sich ändern, damit die Technik verantwortungsvoll eingesetzt wird?",
      },
      {
        speaker: "Professor Lehmann",
        text: "Drei Dinge. Die Systeme müssen ihre Unsicherheit anzeigen, statt nur ein Ergebnis zu liefern. Der Umgang mit ihnen muss fester Teil des Medizinstudiums werden. Und wir brauchen eine fortlaufende Kontrolle nach der Zulassung, denn diese Systeme verändern sich mit neuen Daten. Unter diesen Bedingungen kann künstliche Intelligenz die Versorgung tatsächlich verbessern – vor allem dort, wo Fachärzte fehlen.",
      },
    ],
    questions: [
      {
        text: "Wie ordnet Lehmann das Heidelberger Studienergebnis ein?",
        options: [
          "Der Vergleich führt in die Irre, wenn man ihn absolut setzt, denn die Maschine kennt den Patienten nicht.",
          "Die Fachärzte schnitten besser ab als das System.",
          "Das System ist der ärztlichen Diagnose in jeder Hinsicht überlegen.",
        ],
        answer: 0,
        explain: "Sayılar sistemin lehine (yüzde 94'e karşı 87) ama Lehmann hemen sınırlıyor: makine yalnızca görüntü deseni tanıyor, „weder die Krankengeschichte noch die Lebensumstände“ biliyor.",
      },
      {
        text: "Was zeigte das Experiment mit den fehlerhaften Systemvorschlägen?",
        options: [
          "Die Ärzte erkannten fast alle fehlerhaften Vorschläge sofort.",
          "Fast ein Drittel der Ärzte übernahm die falsche Einschätzung des Systems.",
          "Nur unerfahrene Ärzte ließen sich von den Vorschlägen täuschen.",
        ],
        answer: 1,
        explain: "Otomasyon yanlılığı bulgusu: „Fast ein Drittel übernahm die falsche Einschätzung, obwohl sie ohne das System richtig geurteilt hätte.“ Deneyim ayrımı söyleşide geçmiyor.",
      },
      {
        text: "Rechtlich haftet bei einer falschen Entscheidung der Hersteller des Systems.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Lehmann net: sorumluluk „die behandelnde Ärztin oder der behandelnde Arzt“ta — sistemler karar verici olarak değil, „als Unterstützung“ ruhsatlı.",
      },
      {
        text: "Was meint Lehmann mit dem Satz „Die künstliche Intelligenz ist ein Werkzeug, kein Kollege“?",
        options: [
          "Die Technik ist noch zu unzuverlässig für den klinischen Alltag.",
          "Die Systeme sollten künftig eigenständig über Behandlungen entscheiden dürfen.",
          "Das ärztliche Urteil bleibt unverzichtbar; die Systemvorschläge müssen hinterfragbar sein.",
        ],
        answer: 2,
        explain: "Cümlenin devamı anahtarı veriyor: „Ein Befund, den ich nicht hinterfragen kann, ist keine Entlastung, sondern ein Risiko“ — araç destekler, hekimin yargısının yerine geçmez.",
      },
      {
        text: "Lehmann fordert unter anderem, dass die Systeme ihre eigene Unsicherheit anzeigen und nach der Zulassung fortlaufend kontrolliert werden.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Son cevaptaki üç talepten ikisi bunlar; üçüncüsü yapay zekâyla çalışmanın tıp eğitiminin sabit parçası olması.",
      },
    ],
  },
  {
    id: "c1-l4",
    level: "C1",
    skill: "listening",
    title: "Wildenhain: Ein Dorf erfindet sich neu",
    genre: "Radyo belgeseli",
    intro: "Bu radyo belgeselinde küçülen bir Doğu Almanya köyünün rakamlarını ve beklenmedik dönüş hikâyesini dinle.",
    minutes: 6,
    gloss: [
      { de: "die Landflucht", tr: "kırsaldan kente göç" },
      { de: "die Ausdünnung", tr: "seyrekleşme" },
      { de: "der Wegzug", tr: "göç edip gitme" },
      { de: "die Überalterung", tr: "nüfusun yaşlanması" },
      { de: "der Rückkehrer", tr: "geri dönen kişi" },
      { de: "der Glasfaseranschluss", tr: "fiber internet bağlantısı" },
      { de: "der Gemeinschaftsraum", tr: "ortak kullanım mekânı" },
      { de: "die Genossenschaft", tr: "kooperatif" },
      { de: "tragfähig", tr: "sürdürülebilir, taşıyıcı" },
      { de: "die Trendwende", tr: "eğilimin tersine dönmesi" },
      { de: "verhalten", tr: "temkinli, ölçülü" },
    ],
    segments: [
      {
        speaker: "Sprecherin",
        text: "Ein Montagmorgen in Wildenhain, einem Dorf im Norden Sachsens. Der Bäcker hat vor sieben Jahren geschlossen, die Grundschule vor fünf. Von den einst 1.900 Einwohnern sind noch knapp 1.100 geblieben, mehr als ein Drittel von ihnen ist älter als 65. Wildenhain ist kein Einzelfall – es ist der Normalfall in weiten Teilen des ländlichen Ostdeutschlands.",
      },
      {
        speaker: "Sprecherin",
        text: "Im Rathaus empfängt uns Bürgermeisterin Anke Petzold. Seit elf Jahren verwaltet sie die Ausdünnung ihres Ortes: erst gingen die Jungen, dann die Läden, zuletzt die Buslinie nach Torgau.",
      },
      {
        speaker: "Bürgermeisterin Petzold",
        text: "Das Schlimmste war nicht der Wegzug selbst, sondern die Stimmung, die er hinterlässt. Wenn die Schule schließt, sagt das jeder jungen Familie: Hier ist keine Zukunft. Gegen dieses Gefühl kämpfen wir bis heute an.",
      },
      {
        speaker: "Sprecherin",
        text: "Doch seit etwa drei Jahren registriert die Gemeinde etwas Neues. Erst waren es zwei Familien aus Leipzig, dann ein halbes Dutzend. Inzwischen zählt Wildenhain 74 Zugezogene – die meisten zwischen 30 und 45, viele davon mit Berufen, die nur einen Bildschirm brauchen. Möglich wurde das durch einen Zufall der Infrastrukturpolitik: Wildenhain bekam früher als die Nachbarorte einen flächendeckenden Glasfaseranschluss.",
      },
      {
        speaker: "Bürgermeisterin Petzold",
        text: "Die Neuen wollen kein Museumsdorf und keine Vorstadt, sie wollen Mitgestaltung. Sie haben den alten Konsum als Genossenschaft wiederbelebt, mit Dorfladen, Café und Arbeitsplätzen zum Mieten. Und plötzlich reden die Alteingesessenen und die Zugezogenen am selben Tresen miteinander.",
      },
      {
        speaker: "Sprecherin",
        text: "Forschende der Universität Halle beobachten solche Entwicklungen inzwischen in mehreren Regionen, warnen jedoch vor verfrühter Euphorie. Von einer Trendwende könne erst die Rede sein, wenn Kitas, Ärzte und Busverbindungen nachzögen – Zuzug allein mache noch keine tragfähige Infrastruktur. Bürgermeisterin Petzold formuliert es verhaltener: Wildenhain sei nicht gerettet, sagt sie. Aber es habe zum ersten Mal seit Jahrzehnten wieder eine Richtung.",
      },
    ],
    questions: [
      {
        text: "Was beschreibt die Sprecherin zu Beginn als „Normalfall“ im ländlichen Ostdeutschland?",
        options: [
          "Den wirtschaftlichen Aufschwung kleiner Gemeinden.",
          "Schrumpfung und Überalterung von Dörfern wie Wildenhain.",
          "Die Rückkehr junger Familien aus den Großstädten.",
        ],
        answer: 1,
        explain: "Giriş: 1.900 kişiden 1.100'e düşüş, üçte birden fazlası 65 üstü — „Wildenhain ist kein Einzelfall – es ist der Normalfall“.",
      },
      {
        text: "Was war für Bürgermeisterin Petzold das Schlimmste am Schrumpfen des Dorfes?",
        options: [
          "Die Stimmung der Zukunftslosigkeit, die der Wegzug hinterlässt.",
          "Der Verlust von Steuereinnahmen für die Gemeinde.",
          "Die Schließung der Buslinie nach Torgau.",
        ],
        answer: 0,
        explain: "Petzold'un sözleri: „Das Schlimmste war nicht der Wegzug selbst, sondern die Stimmung, die er hinterlässt“ — okulun kapanması genç ailelere ‚burada gelecek yok‘ mesajı veriyor.",
      },
      {
        text: "Der frühe Glasfaserausbau war ein entscheidender Grund dafür, dass Zugezogene nach Wildenhain kamen.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Anlatıcı bunu „ein Zufall der Infrastrukturpolitik“ diye açıklıyor: köy komşularından önce yaygın fiber bağlantı aldı; gelenlerin çoğu „Berufe, die nur einen Bildschirm brauchen“ sahibi.",
      },
      {
        text: "Was haben die Zugezogenen im Dorf aufgebaut?",
        options: [
          "Ein Museumsdorf für Touristen aus Leipzig.",
          "Eine private Grundschule mit digitalem Unterricht.",
          "Eine Genossenschaft mit Dorfladen, Café und mietbaren Arbeitsplätzen.",
        ],
        answer: 2,
        explain: "Petzold anlatıyor: eski „Konsum“ mağazası kooperatif olarak canlandırıldı — „mit Dorfladen, Café und Arbeitsplätzen zum Mieten“. Müze köy tam da istemedikleri şey.",
      },
      {
        text: "Die Forschenden der Universität Halle sprechen bereits von einer gesicherten Trendwende für ländliche Regionen.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Araştırmacılar „vor verfrühter Euphorie“ uyarıyor: kreşler, doktorlar ve otobüs hatları gelmedikçe eğilim dönmüş sayılmaz — Konjunktiv I („könne … die Rede sein“) temkinli aktarımı gösteriyor.",
      },
    ],
  },
  {
    id: "c1-l5",
    level: "C1",
    skill: "listening",
    title: "Englisch als Wissenschaftssprache: Gewinn oder Verlust?",
    genre: "Konferans",
    intro: "Bu üniversite konuşmasında bilimin İngilizceleşmesinin kazanç ve kayıp hanelerini konuşmacının nasıl tarttığını izle.",
    minutes: 6,
    gloss: [
      { de: "die Wissenschaftssprache", tr: "bilim dili" },
      { de: "die Fachzeitschrift", tr: "akademik dergi" },
      { de: "der Austausch", tr: "alışveriş, iletişim" },
      { de: "der Domänenverlust", tr: "alan kaybı (dilin bir alandan çekilmesi)" },
      { de: "die Begriffsbildung", tr: "kavram oluşturma" },
      { de: "etwas verkümmern lassen", tr: "körelmeye bırakmak" },
      { de: "die Rechenschaftspflicht", tr: "hesap verme yükümlülüğü" },
      { de: "der Steuerzahler", tr: "vergi mükellefi" },
      { de: "die Erstsprache", tr: "ana dil, birinci dil" },
      { de: "das Plädoyer", tr: "savunma konuşması, çağrı" },
    ],
    segments: [
      {
        text: "Sehr geehrte Damen und Herren, noch vor hundert Jahren war Deutsch eine führende Wissenschaftssprache – wer in Chemie oder Physik mitreden wollte, las deutsche Fachzeitschriften. Heute erscheinen über 95 Prozent der naturwissenschaftlichen Veröffentlichungen weltweit auf Englisch. Die Frage meines Vortrags lautet: Was gewinnen wir dadurch, und was verlieren wir?",
      },
      {
        text: "Beginnen wir mit den Gewinnen, denn sie sind erheblich. Eine gemeinsame Verkehrssprache macht Forschung weltweit anschlussfähig. Eine Doktorandin in Ankara, ein Labor in Seoul und eine Arbeitsgruppe in Leipzig können ohne Verzögerung aufeinander aufbauen. Diesen Zugewinn an Austausch und Überprüfbarkeit sollte niemand kleinreden, der internationale Zusammenarbeit ernst nimmt.",
      },
      {
        text: "Doch der Preis wird selten beziffert. Sprachwissenschaftler nennen ihn Domänenverlust: Eine Sprache, in der nicht mehr geforscht wird, hört allmählich auf, neue Fachbegriffe zu bilden. Wo das Deutsche keine eigenen Begriffe mehr entwickelt, können wir wissenschaftliche Sachverhalte irgendwann nur noch auf Englisch präzise verhandeln – im Labor mag das verschmerzbar sein, in der Gesellschaft ist es das nicht.",
      },
      {
        text: "Denn Wissenschaft hat eine Rechenschaftspflicht gegenüber denen, die sie finanzieren. Ob Impfstoffe, Energiewende oder künstliche Intelligenz: Die öffentliche Debatte über Forschung findet in der Landessprache statt. Wenn Fachleute ihre eigenen Ergebnisse nicht mehr allgemeinverständlich auf Deutsch erklären können, entsteht genau die Distanz zwischen Wissenschaft und Öffentlichkeit, über die wir uns anschließend beklagen.",
      },
      {
        text: "Hinzu kommt ein oft übersehener Befund aus der Lehr-Lern-Forschung: Studierende verarbeiten komplexe Inhalte in ihrer Erstsprache nachweislich tiefer. Wer die Lehre vollständig anglisiert, erleichtert den internationalen Austausch – und erschwert zugleich einem Teil der eigenen Studierenden das Verstehen.",
      },
      {
        text: "Mein Plädoyer ist daher kein nostalgisches. Publizieren wir auf Englisch, wo die Fachwelt unser Publikum ist. Aber lehren, erklären und debattieren wir auch in der Landessprache – nicht aus Traditionspflege, sondern weil eine Demokratie nur über Wissenschaft streiten kann, die sie sprachlich erreicht. Vielen Dank.",
      },
    ],
    questions: [
      {
        text: "Wie bewertet der Redner die gemeinsame Verkehrssprache Englisch?",
        options: [
          "Als bedauerlichen Irrweg, der rückgängig gemacht werden sollte.",
          "Als Übergangsphänomen ohne dauerhafte Bedeutung.",
          "Als erheblichen Gewinn für Austausch und Überprüfbarkeit der Forschung.",
        ],
        answer: 2,
        explain: "İkinci bölümde net: kazançlar „erheblich“, ortak dil araştırmayı dünya çapında „anschlussfähig“ kılıyor — konuşmacı bunu küçümseyene karşı çıkıyor.",
      },
      {
        text: "Was bezeichnet der Begriff „Domänenverlust“?",
        options: [
          "Eine Sprache, in der nicht mehr geforscht wird, bildet allmählich keine neuen Fachbegriffe mehr.",
          "Universitäten verlieren ganze Fachbereiche an ausländische Hochschulen.",
          "Deutsche Fachzeitschriften verlieren ihre internationalen Abonnenten.",
        ],
        answer: 0,
        explain: "Üçüncü bölümdeki tanım: araştırma yapılmayan dil „hört allmählich auf, neue Fachbegriffe zu bilden“ — kayıp kurumsal değil, dilsel.",
      },
      {
        text: "Laut Vortrag findet die öffentliche Debatte über Forschung überwiegend auf Englisch statt.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Tam tersi: „Die öffentliche Debatte über Forschung findet in der Landessprache statt“ — bilim insanları sonuçlarını Almanca anlatamazsa toplumla arasındaki mesafe büyüyor.",
      },
      {
        text: "Welcher Befund aus der Lehr-Lern-Forschung wird angeführt?",
        options: [
          "Englischsprachige Lehre verbessert die Karrierechancen aller Absolventen.",
          "Studierende verarbeiten komplexe Inhalte in ihrer Erstsprache tiefer.",
          "Studierende bevorzugen mehrheitlich englischsprachige Lehrveranstaltungen.",
        ],
        answer: 1,
        explain: "Beşinci bölüm: „Studierende verarbeiten komplexe Inhalte in ihrer Erstsprache nachweislich tiefer“ — tam İngilizceleşme bir kesimin anlamasını zorlaştırıyor.",
      },
      {
        text: "Der Redner fordert, wissenschaftliche Veröffentlichungen künftig wieder überwiegend auf Deutsch zu publizieren.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Kapanış çağrısı ikili: „Publizieren wir auf Englisch, wo die Fachwelt unser Publikum ist“ — Almanca ise öğretim, açıklama ve kamusal tartışma için savunuluyor. Nostaljik bir geri dönüş talebi yok.",
      },
    ],
  },
  {
    id: "c1-l6",
    level: "C1",
    skill: "listening",
    title: "Tablets für alle – und dann?",
    genre: "Panel",
    intro: "Okullarda dijitalleşme panelinde bir eğitim araştırmacısı ile bir öğretmen sahadaki gerçeği tartışıyor — ortak vardıkları formülü yakala.",
    minutes: 6,
    gloss: [
      { de: "die Ausstattung", tr: "donanım" },
      { de: "flächendeckend", tr: "her yeri kapsayan" },
      { de: "der Mehrwert", tr: "katma değer" },
      { de: "die Ablenkung", tr: "dikkat dağınıklığı" },
      { de: "das Endgerät", tr: "uç cihaz (tablet, dizüstü)" },
      { de: "die Fortbildung", tr: "hizmet içi eğitim" },
      { de: "das Konzept", tr: "kavramsal plan, konsept" },
      { de: "etwas verstauben", tr: "tozlanmak, atıl kalmak" },
      { de: "die Wartung", tr: "bakım" },
      { de: "die Lernwirkung", tr: "öğrenme etkisi" },
      { de: "didaktisch", tr: "öğretim yöntemine ilişkin" },
    ],
    segments: [
      {
        speaker: "Moderator",
        text: "Willkommen zu unserer Runde über die digitale Schule. Milliarden aus dem Digitalpakt sind ausgegeben, viele Klassenzimmer flächendeckend mit Tablets ausgestattet. Frau Doktor Kaya, Sie haben die Lernwirkung untersucht. Hat sich die Investition gelohnt?",
      },
      {
        speaker: "Doktor Kaya",
        text: "Die unbequeme Antwort lautet: Das Gerät allein bewirkt nichts. Wir haben 120 Schulen über vier Jahre begleitet. Dort, wo Tablets lediglich das Arbeitsblatt ersetzten, blieben die Leistungen unverändert – in Mathematik gingen sie teilweise sogar leicht zurück, vor allem durch Ablenkung. Deutliche Lernzuwächse fanden wir nur an Schulen, die zuerst ein didaktisches Konzept entwickelt und dann die Technik angeschafft haben. Die Reihenfolge ist entscheidend.",
      },
      {
        speaker: "Moderator",
        text: "Herr Brandt, Sie unterrichten seit zwanzig Jahren an einer Gesamtschule in Dortmund. Deckt sich das mit Ihrer Erfahrung?",
      },
      {
        speaker: "Herr Brandt",
        text: "Vollkommen. Bei uns kamen vor drei Jahren 800 Tablets an – aber keine einzige Stunde Fortbildung, wie man damit sinnvoll unterrichtet. Ein halbes Jahr lang verstaubten die Koffer im Keller. Und niemand hatte an die Wartung gedacht: Ich bin Mathematiklehrer und nebenbei unbezahlter Techniker für 800 Geräte. Was mich an der Debatte stört, ist ihre Schieflage: Diskutiert wird über Endgeräte, nicht über Unterricht.",
      },
      {
        speaker: "Doktor Kaya",
        text: "Das bestätigen unsere Daten. Der stärkste Einzelfaktor war nicht die Zahl der Geräte, sondern die Zahl der Fortbildungsstunden pro Lehrkraft. Überspitzt gesagt: Ein Euro für Fortbildung bringt mehr Lernwirkung als drei Euro für Hardware.",
      },
      {
        speaker: "Herr Brandt",
        text: "Wobei ich die Geräte nicht verteufeln möchte. Wenn meine Schüler Messdaten im Physikunterricht selbst auswerten oder ein Erklärvideo für die Parallelklasse produzieren, passiert genau das, was Unterricht soll: Sie denken selbst. Das Tablet ist dann Werkzeug – nicht Belohnung und nicht Babysitter.",
      },
      {
        speaker: "Moderator",
        text: "Technik folgt dem Konzept, nicht umgekehrt – das scheint mir das Fazit dieser Runde. Vielen Dank Ihnen beiden.",
      },
    ],
    questions: [
      {
        text: "Was ist das zentrale Ergebnis der Studie von Doktor Kaya?",
        options: [
          "Tablets verbessern die Leistungen unabhängig vom Unterrichtskonzept.",
          "Lernzuwächse gab es nur an Schulen, die zuerst ein didaktisches Konzept entwickelten und dann die Technik anschafften.",
          "Digitale Geräte verschlechtern die Leistungen in allen Fächern erheblich.",
        ],
        answer: 1,
        explain: "Kaya'nın vurgusu: „Die Reihenfolge ist entscheidend“ — önce konsept, sonra teknoloji. Üçüncü şık aşırı genelleme: gerileme yalnızca matematikte ve „teilweise … leicht“.",
      },
      {
        text: "Welche Probleme schildert Herr Brandt aus seiner Schule?",
        options: [
          "Fehlende Fortbildung und ungeklärte Wartung der Geräte.",
          "Die Schüler lehnten die Arbeit mit den Tablets mehrheitlich ab.",
          "Die Schule erhielt deutlich weniger Geräte als zugesagt.",
        ],
        answer: 0,
        explain: "Brandt somut anlatıyor: 800 tablet geldi ama „keine einzige Stunde Fortbildung“; bakım da düşünülmemiş — kendisi ücretsiz teknisyene dönüşmüş.",
      },
      {
        text: "Laut Kaya bringt ein Euro für Fortbildung mehr Lernwirkung als drei Euro für Hardware.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Kaya bunu „überspitzt gesagt“ (bilerek keskinleştirilmiş) formülüyle söylüyor; en güçlü tekil faktör cihaz sayısı değil, öğretmen başına hizmet içi eğitim saati.",
      },
      {
        text: "Herr Brandt lehnt den Einsatz von Tablets im Unterricht grundsätzlich ab.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "„Wobei ich die Geräte nicht verteufeln möchte“ — fizik verisi değerlendirme ve açıklayıcı video örnekleriyle tableti savunuyor; itirazı araca değil, konseptsiz kullanıma.",
      },
      {
        text: "Welches Fazit zieht der Moderator am Ende?",
        options: [
          "Die Schulen brauchen vor allem mehr und neuere Endgeräte.",
          "Technik folgt dem Konzept, nicht umgekehrt.",
          "Der Digitalpakt sollte beendet werden.",
        ],
        answer: 1,
        explain: "Kapanış cümlesi birebir: „Technik folgt dem Konzept, nicht umgekehrt – das scheint mir das Fazit dieser Runde.“",
      },
    ],
  },

  // --------------------------------------------------------------- YAZMA
  {
    id: "c1-w1",
    level: "C1",
    skill: "writing",
    title: "Grafikbeschreibung: Arbeiten im Homeoffice",
    genre: "Grafik yorumu",
    intro: "Goethe C1'in klasik görevi: bir grafiği akademik dille betimleyip yorumlayacaksın — önce iki kalıp cümle kur, sonra kompozisyonu yaz.",
    minutes: 14,
    gloss: [
      { de: "der Anteil", tr: "pay, oran" },
      { de: "sich verdreifachen", tr: "üç katına çıkmak" },
      { de: "der Anstieg", tr: "artış" },
      { de: "etwas verzeichnen", tr: "kaydetmek" },
      { de: "die Erhebung", tr: "anket, veri toplama" },
      { de: "der Befragte", tr: "ankete katılan" },
      { de: "etwas auf etwas zurückführen", tr: "bir şeye bağlamak" },
      { de: "die Vereinbarkeit", tr: "bağdaştırılabilirlik" },
      { de: "hervorgehen aus", tr: "(veriden) anlaşılmak" },
      { de: "sich belaufen auf", tr: "(miktarı) bulmak, ulaşmak" },
    ],
    tasks: [
      {
        kind: "build",
        tr: "Grafik, evden çalışanların payının 2019'dan bu yana üç katına çıktığını göstermektedir.",
        answer: "Die Grafik zeigt, dass sich der Anteil der im Homeoffice Arbeitenden seit 2019 verdreifacht hat.",
        hint: "Nominalleştirilmiş sıfat-fiil: „die im Homeoffice Arbeitenden“ = evden çalışanlar. „sich verdreifachen“ dönüşlü fiil, Perfekt'te „hat“ ile.",
      },
      {
        kind: "build",
        tr: "Bu gelişmenin nedenlerinden biri, pandemi sırasında dijital altyapının hızla genişletilmesidir.",
        answer: "Eine der Ursachen für diese Entwicklung ist der rasche Ausbau der digitalen Infrastruktur während der Pandemie.",
        alternatives: [
          "Der rasche Ausbau der digitalen Infrastruktur während der Pandemie ist eine der Ursachen für diese Entwicklung.",
        ],
        hint: "Nominalstil: fiil yerine isim — „der Ausbau der Infrastruktur“ (Genitiv zinciri). „eine der Ursachen“ + Genitiv çoğul kalıbını koru.",
      },
      {
        kind: "free",
        prompt: "Bir seminer ödevi için aşağıdaki anket verilerini yorumlayan kısa bir kompozisyon yaz: önce verileri betimle, sonra olası nedenleri tartış ve kendi değerlendirmenle bitir.",
        stimulus: "Erhebung des Instituts für Arbeitswelt (10.000 Befragte):\n\nAnteil der Beschäftigten, die mindestens teilweise im Homeoffice arbeiten: 2019: 13 Prozent — 2021: 31 Prozent — 2025: 39 Prozent.\n\nGewünschter Anteil laut Befragung 2025: 58 Prozent.\n\nHäufigste Gründe für den Wunsch: Wegfall des Arbeitswegs (71 Prozent), bessere Vereinbarkeit von Beruf und Familie (64 Prozent), konzentrierteres Arbeiten (48 Prozent).",
        checklist: [
          "Girişte grafiğin kaynağını, kapsamını ve konusunu tek cümlede tanıt",
          "En çarpıcı gelişmeyi sayılarla betimle (2019-2025 artışı, fiili ve arzu edilen oran arasındaki fark)",
          "En az iki olası neden tartış ve verideki gerekçelere bağla",
          "Kendi değerlendirmeni gerekçelendir (işveren-çalışan perspektifi, olası sakıncalar)",
          "Akademik register kullan: Nominalstil, „lässt sich“, „ist davon auszugehen“ gibi kalıplar",
        ],
        minWords: 130,
        phrases: [
          { de: "Aus der Grafik geht hervor, dass …", tr: "Grafikten anlaşılıyor ki …" },
          { de: "Ein deutlicher Anstieg ist zu verzeichnen.", tr: "Belirgin bir artış kaydediliyor." },
          { de: "Der Anteil beläuft sich auf …", tr: "Oran …'i buluyor." },
          { de: "Im Vergleich zu 2019 …", tr: "2019'a kıyasla …" },
          { de: "Dies lässt sich darauf zurückführen, dass …", tr: "Bu, şuna bağlanabilir: …" },
          { de: "Auffällig ist die Diskrepanz zwischen …", tr: "… arasındaki fark dikkat çekici." },
          { de: "Es ist davon auszugehen, dass …", tr: "…olduğu varsayılabilir." },
          { de: "Zusammenfassend lässt sich festhalten, dass …", tr: "Özetle şu saptanabilir: …" },
          { de: "Meines Erachtens …", tr: "Kanaatimce …" },
        ],
        sample: "Die vorliegende Erhebung des Instituts für Arbeitswelt, für die 10.000 Beschäftigte befragt wurden, dokumentiert die Entwicklung der Arbeit im Homeoffice zwischen 2019 und 2025.\n\nAus den Daten geht hervor, dass sich der Anteil der zumindest teilweise von zu Hause Arbeitenden in diesem Zeitraum verdreifacht hat: von 13 Prozent im Jahr 2019 auf 39 Prozent im Jahr 2025, wobei der stärkste Anstieg auf die Pandemiejahre entfällt. Auffällig ist die Diskrepanz zwischen tatsächlichem und gewünschtem Anteil – mit 58 Prozent würden deutlich mehr Beschäftigte gern mobil arbeiten, als es derzeit tun.\n\nDiese Entwicklung lässt sich zum einen auf den erzwungenen Digitalisierungsschub während der Pandemie zurückführen, der die technischen Voraussetzungen flächendeckend schuf. Zum anderen nennen die Befragten handfeste Gründe: der Wegfall des Arbeitswegs und die bessere Vereinbarkeit von Beruf und Familie stehen mit 71 beziehungsweise 64 Prozent an der Spitze.\n\nMeines Erachtens ist die Rückkehr zur reinen Präsenzkultur unwahrscheinlich. Allerdings sollten die Risiken – etwa die schleichende Entgrenzung von Arbeit und Privatleben – nicht ausgeblendet werden. Es ist davon auszugehen, dass hybride Modelle zum Normalfall werden; entscheidend wird sein, sie verbindlich und fair zu gestalten.",
      },
    ],
  },
  {
    id: "c1-w2",
    level: "C1",
    skill: "writing",
    title: "Formeller Widerspruch",
    genre: "Resmi itiraz",
    intro: "Haksız bir ücret talebine karşı resmi itiraz mektubu yazacaksın — kesin, mesafeli ve hukuki register burada her şey.",
    minutes: 13,
    gloss: [
      { de: "der Widerspruch", tr: "itiraz" },
      { de: "der Bescheid", tr: "resmi karar yazısı" },
      { de: "fristgerecht", tr: "süresi içinde" },
      { de: "die Erstattung", tr: "iade" },
      { de: "die Teilnahmegebühr", tr: "katılım ücreti" },
      { de: "etwas aufheben", tr: "(kararı) iptal etmek" },
      { de: "die Allgemeinen Geschäftsbedingungen", tr: "genel işlem koşulları" },
      { de: "sich auf etwas berufen", tr: "bir şeye dayanmak" },
      { de: "rechtliche Schritte", tr: "hukuki yollar" },
      { de: "die Anlage", tr: "ek (belge)" },
    ],
    tasks: [
      {
        kind: "build",
        tr: "İşbu yazıyla 3 Mayıs tarihli karara süresi içinde itiraz ediyorum.",
        answer: "Hiermit lege ich fristgerecht Widerspruch gegen den Bescheid vom dritten Mai ein.",
        alternatives: [
          "Hiermit lege ich gegen den Bescheid vom dritten Mai fristgerecht Widerspruch ein.",
        ],
        hint: "Resmi kalıp: „Widerspruch einlegen gegen“ + Akkusativ. „Hiermit“ mektubu açan tipik hukuk dili sinyali.",
      },
      {
        kind: "build",
        tr: "Görevli telefonda, ücretin iadesinin ne yazık ki mümkün olmadığını söyledi.",
        answer: "Der Sachbearbeiter erklärte am Telefon, eine Erstattung der Gebühr sei leider nicht möglich.",
        alternatives: [
          "Eine Erstattung der Gebühr sei leider nicht möglich, erklärte der Sachbearbeiter am Telefon.",
        ],
        hint: "Dolaylı aktarım Konjunktiv I ile: „sei“ (ist değil). İtiraz mektubunda karşı tarafın sözünü böyle aktarırsın.",
      },
      {
        kind: "free",
        prompt: "Kayıtlı olduğun „Wirtschaftsdeutsch C1“ kursu, halk eğitim merkezi tarafından ikinci haftada iptal edildi; buna rağmen 240 Euro'luk ücretin yalnızca yarısı iade edildi. Aşağıdaki yazıya resmi bir itiraz mektubu yaz: durumu özetle, tam iade talep et, gerekçelendir ve bir süre belirle.",
        stimulus: "Volkshochschule Neustadt, Bescheid vom 12. März:\n\nSehr geehrte Frau Aydın, der Kurs „Wirtschaftsdeutsch C1“ wurde aus organisatorischen Gründen nach der zweiten Woche eingestellt. Gemäß Abschnitt 7 unserer Allgemeinen Geschäftsbedingungen erstatten wir Ihnen 50 Prozent der Teilnahmegebühr, das heißt 120 Euro. Weitere Ansprüche bestehen nicht. Mit freundlichen Grüßen, Ihre Volkshochschule Neustadt",
        checklist: [
          "Konu satırı ve resmi hitapla başla; hangi karara itiraz ettiğini tarihiyle belirt",
          "Olayı tek paragrafta nesnel biçimde özetle (kursun iptali, kısmi iade)",
          "Talebini gerekçelendir: iptal senin kusurun değil, hizmetin büyük bölümü verilmedi",
          "Somut talep + süre koy (örn. 14 gün içinde kalan 120 Euro'nun iadesi)",
          "Mesafeli ama nazik kapanış: gerekirse hukuki yolları saklı tuttuğunu belirt",
        ],
        minWords: 120,
        phrases: [
          { de: "hiermit lege ich Widerspruch gegen … ein", tr: "işbu yazıyla …'e itiraz ediyorum" },
          { de: "ich beziehe mich auf Ihren Bescheid vom …", tr: "… tarihli kararınıza atıfta bulunuyorum" },
          { de: "entgegen Ihrer Darstellung", tr: "sizin ifadenizin aksine" },
          { de: "die Kündigung ist nicht von mir zu vertreten", tr: "iptal benim kusurumdan kaynaklanmıyor" },
          { de: "ich fordere Sie auf, … zu erstatten", tr: "…'i iade etmenizi talep ediyorum" },
          { de: "ich bitte Sie, den Bescheid aufzuheben", tr: "kararı iptal etmenizi rica ediyorum" },
          { de: "innerhalb von 14 Tagen", tr: "14 gün içinde" },
          { de: "andernfalls behalte ich mir rechtliche Schritte vor", tr: "aksi hâlde hukuki yolları saklı tutarım" },
          { de: "in der Anlage finden Sie …", tr: "ekte …'i bulabilirsiniz" },
        ],
        sample: "Betreff: Widerspruch gegen Ihren Bescheid vom 12. März – Kurs „Wirtschaftsdeutsch C1“\n\nSehr geehrte Damen und Herren,\n\nhiermit lege ich fristgerecht Widerspruch gegen Ihren oben genannten Bescheid ein, mit dem Sie mir lediglich 50 Prozent der Teilnahmegebühr erstatten.\n\nZum Sachverhalt: Der Kurs, für den ich 240 Euro entrichtet habe, wurde nach nur zwei von zwölf Wochen aus organisatorischen Gründen eingestellt. Die Absage ist somit ausschließlich von Ihnen zu vertreten; mehr als achtzig Prozent der zugesagten Leistung wurden nie erbracht. Entgegen Ihrer Darstellung kann Abschnitt 7 Ihrer Allgemeinen Geschäftsbedingungen hier nicht greifen: Diese Klausel betrifft dem Wortlaut nach den Rücktritt der Teilnehmenden, nicht die Einstellung des Kurses durch den Anbieter. Eine pauschale Kürzung um die Hälfte steht zudem in keinem Verhältnis zum tatsächlich erbrachten Unterricht.\n\nIch fordere Sie daher auf, mir die verbleibenden 120 Euro innerhalb von 14 Tagen auf das Ihnen bekannte Konto zu erstatten. Sollte ich bis dahin keinen Zahlungseingang feststellen, behalte ich mir vor, rechtliche Schritte einzuleiten und die Verbraucherzentrale einzuschalten.\n\nIn der Anlage finden Sie die Anmeldebestätigung sowie den Zahlungsbeleg.\n\nMit freundlichen Grüßen\nElif Aydın",
      },
    ],
  },
  {
    id: "c1-w3",
    level: "C1",
    skill: "writing",
    title: "Erörterung: Künstliche Intelligenz im Studium",
    genre: "Tartışmalı deneme",
    intro: "Goethe C1 Schreiben'in kalbi: tartışmalı bir konuda tez-antitez-sentez kuran yapılandırılmış bir deneme yazacaksın.",
    minutes: 16,
    gloss: [
      { de: "die Erörterung", tr: "tartışma yazısı" },
      { de: "der Einsatz", tr: "kullanım" },
      { de: "etwas aufwerfen", tr: "(soru) ortaya atmak" },
      { de: "eigenständig", tr: "bağımsız, kendi başına" },
      { de: "die Schwächung", tr: "zayıflama" },
      { de: "der Befürworter", tr: "savunucu" },
      { de: "etwas ins Feld führen", tr: "(argüman) öne sürmek" },
      { de: "einer Sache entgegenhalten", tr: "karşı argüman getirmek" },
      { de: "etwas abwägen", tr: "tartmak, karşılaştırmak" },
      { de: "unter dem Strich", tr: "sonuç olarak, hesabın sonunda" },
      { de: "die Eigenleistung", tr: "kişisel katkı, özgün emek" },
    ],
    tasks: [
      {
        kind: "build",
        tr: "Yapay zekânın kullanımı, bilimsel yazmanın doğasına ilişkin temel sorular ortaya atmaktadır.",
        answer: "Der Einsatz künstlicher Intelligenz wirft grundlegende Fragen nach dem Wesen wissenschaftlichen Schreibens auf.",
        hint: "Nominalstil: „der Einsatz künstlicher Intelligenz“ (Genitiv, artikelsiz). Ayrılabilir fiil „aufwerfen“ — „wirft … auf“ çerçevesi.",
      },
      {
        kind: "build",
        tr: "Eleştirmenler, öğrencilerde bağımsız düşünmenin giderek zayıflamasından kaygı duymaktadır.",
        answer: "Kritiker befürchten eine allmähliche Schwächung des eigenständigen Denkens bei den Studierenden.",
        alternatives: [
          "Kritiker befürchten bei den Studierenden eine allmähliche Schwächung des eigenständigen Denkens.",
        ],
        hint: "Yan cümle yerine isimleştirme: „dass das Denken schwächer wird“ değil, „eine Schwächung des Denkens“ — C1 akademik üslubun imzası.",
      },
      {
        kind: "free",
        prompt: "Üniversitenin öğrenci dergisi için şu soruyu tartışan yapılandırılmış bir deneme yaz: „Sollten Studierende künstliche Intelligenz beim Verfassen von Hausarbeiten nutzen dürfen?“ Her iki tarafın argümanlarını tart, kendi konumunu gerekçelendir.",
        checklist: [
          "Girişte konunun güncelliğini ve tartışma sorusunu formüle et",
          "En az iki lehte argümanı örneklerle geliştir (verimlilik, dil desteği, gerçek çalışma hayatına hazırlık)",
          "En az iki aleyhte argümanı ciddiyetle ele al (Eigenleistung, düşünme becerisi, değerlendirme adaleti)",
          "Karşı argümanlara yanıt ver — çürüt ya da sınırla („dem ist entgegenzuhalten …“)",
          "Sonuçta net, gerekçeli ve nüanslı bir konum al; koşul veya öneri formüle et",
        ],
        minWords: 150,
        phrases: [
          { de: "Kaum eine Frage wird derzeit so kontrovers diskutiert wie …", tr: "Şu sıralar hiçbir soru … kadar tartışılmıyor." },
          { de: "Befürworter führen ins Feld, dass …", tr: "Savunucular şunu öne sürüyor: …" },
          { de: "Es lässt sich nicht von der Hand weisen, dass …", tr: "…olduğu yadsınamaz." },
          { de: "Dem ist entgegenzuhalten, dass …", tr: "Buna karşı şu söylenmeli: …" },
          { de: "Bei näherer Betrachtung zeigt sich, dass …", tr: "Daha yakından bakıldığında görülüyor ki …" },
          { de: "Zwar …, doch …", tr: "Gerçi …, ama …" },
          { de: "Entscheidend ist letztlich, ob …", tr: "Sonuçta belirleyici olan, … olup olmadığı." },
          { de: "Unter dem Strich überwiegen …", tr: "Hesabın sonunda … ağır basıyor." },
          { de: "Daraus ergibt sich die Forderung, …", tr: "Buradan şu talep doğuyor: …" },
        ],
        sample: "Kaum eine Frage wird an den Hochschulen derzeit so kontrovers diskutiert wie der Umgang mit künstlicher Intelligenz: Dürfen Studierende sie beim Verfassen von Hausarbeiten nutzen – oder untergräbt das den Sinn des Studiums?\n\nBefürworter führen ins Feld, dass die Technologie längst zur beruflichen Realität gehört; ein Verbot bereite auf eine Arbeitswelt vor, die es nicht mehr gibt. Zudem wirken die Werkzeuge ausgleichend: Wer nicht in seiner Erstsprache studiert, erhält sprachliche Unterstützung, die früher teuren Lektoraten vorbehalten war.\n\nDem ist allerdings entgegenzuhalten, dass eine Hausarbeit kein Produkt, sondern eine Übung ist. Wer das Strukturieren von Argumenten vollständig delegiert, trainiert genau die Fähigkeit nicht, die das Studium vermitteln soll. Auch die Frage der Bewertungsgerechtigkeit wiegt schwer: Benotet würde sonst die Geschicklichkeit im Umgang mit dem Werkzeug, nicht die Eigenleistung.\n\nBei näherer Betrachtung erweist sich das Entweder-oder jedoch als Scheinalternative. Entscheidend ist nicht, ob die Technik genutzt wird, sondern wofür: Recherche und sprachliche Glättung sind legitim, die Auslagerung des Denkens ist es nicht. Unter dem Strich plädiere ich daher für eine Kennzeichnungspflicht statt eines Verbots – verbunden mit Prüfungsformen, etwa mündlichen Verteidigungen, in denen sich Eigenleistung nicht simulieren lässt.",
      },
    ],
  },
  {
    id: "c1-w4",
    level: "C1",
    skill: "writing",
    title: "Bewerbung um ein Stipendium",
    genre: "Başvuru mektubu",
    intro: "Bir değişim bursu için motivasyon mektubu yazacaksın — kendini övmeden ikna eden, resmi ama kişilikli bir metin.",
    minutes: 14,
    gloss: [
      { de: "die Ausschreibung", tr: "ilan, duyuru" },
      { de: "sich um etwas bewerben", tr: "bir şeye başvurmak" },
      { de: "der Auslandsaufenthalt", tr: "yurtdışında kalış" },
      { de: "die Vertiefung", tr: "derinleştirme" },
      { de: "zu etwas beitragen", tr: "katkıda bulunmak" },
      { de: "die Voraussetzung", tr: "ön koşul" },
      { de: "etwas nachweisen", tr: "belgelemek, kanıtlamak" },
      { de: "das Vorhaben", tr: "tasarı, proje" },
      { de: "die Förderung", tr: "destek, teşvik" },
      { de: "zur Verfügung stehen", tr: "hazır bulunmak, emrine olmak" },
    ],
    tasks: [
      {
        kind: "build",
        tr: "İlanınızda duyurulan burs için başvurumu sunmak isterim.",
        answer: "Hiermit möchte ich mich um das in Ihrer Ausschreibung angekündigte Stipendium bewerben.",
        hint: "Partizipialkonstruktion: „das in Ihrer Ausschreibung angekündigte Stipendium“ — ilişki cümlesi yerine sıfatlaşmış Partizip II. Fiil kalıbı: „sich bewerben um“.",
      },
      {
        kind: "build",
        tr: "Yurtdışında kalmak, dil yetkinliklerimin derinleşmesine önemli ölçüde katkı sağlayacaktır.",
        answer: "Ein Auslandsaufenthalt würde wesentlich zur Vertiefung meiner sprachlichen Kompetenzen beitragen.",
        hint: "„beitragen zu“ + isimleştirme: „zur Vertiefung meiner Kompetenzen“. Würde-formu burada kibar bir öngörü tonu katıyor.",
      },
      {
        kind: "free",
        prompt: "Aşağıdaki burs ilanına başvuran bir motivasyon mektubu yaz: motivasyonunu, akademik uygunluğunu ve dönüşte topluluğa nasıl katkı vereceğini somut örneklerle anlat.",
        stimulus: "Ausschreibung der Ida-Sommerfeld-Stiftung:\n\nDie Stiftung vergibt zum Wintersemester fünf Teilstipendien für ein Austauschsemester an einer deutschen Universität. Gefördert werden Studierende aller Fächer mit sehr guten Deutschkenntnissen, die ein klares Studienvorhaben verfolgen und bereit sind, nach ihrer Rückkehr ehrenamtlich in der Studienberatung der Stiftung mitzuwirken. Bewerbungen mit Motivationsschreiben richten Sie bitte an die Geschäftsstelle der Stiftung.",
        checklist: [
          "Resmi hitap ve ilk cümlede başvurunun konusu: hangi burs, hangi dönem",
          "Motivasyonunu somutlaştır: neden bu alan, neden Almanya, neden şimdi",
          "Uygunluğunu kanıtla: akademik başarı, dil düzeyi, önceki deneyimler — iddia değil örnek",
          "İlanın özel şartına yanıt ver: dönüşte öğrenci danışmanlığında gönüllü katkı",
          "Kendinden emin ama abartısız kapanış: görüşmeye hazır olduğunu belirt",
        ],
        minWords: 130,
        phrases: [
          { de: "mit großem Interesse habe ich Ihre Ausschreibung gelesen", tr: "ilanınızı büyük ilgiyle okudum" },
          { de: "ich bewerbe mich um …", tr: "…'e başvuruyorum" },
          { de: "mein Studienvorhaben besteht darin, …", tr: "çalışma tasarım şudur: …" },
          { de: "wie Sie meinen Unterlagen entnehmen können", tr: "belgelerimden görebileceğiniz üzere" },
          { de: "meine Kenntnisse habe ich durch … nachgewiesen", tr: "bilgimi … ile belgeledim" },
          { de: "darüber hinaus", tr: "bunun ötesinde" },
          { de: "ich bin gern bereit, …", tr: "…'e memnuniyetle hazırım" },
          { de: "für ein persönliches Gespräch stehe ich jederzeit zur Verfügung", tr: "kişisel görüşme için her zaman hazırım" },
          { de: "über eine positive Rückmeldung würde ich mich sehr freuen", tr: "olumlu bir dönüş beni çok sevindirir" },
        ],
        sample: "Sehr geehrte Damen und Herren,\n\nmit großem Interesse habe ich Ihre Ausschreibung gelesen und bewerbe mich hiermit um eines der Teilstipendien für ein Austauschsemester zum kommenden Wintersemester.\n\nIch studiere im fünften Semester Wirtschaftsinformatik an der Universität Istanbul und beschäftige mich in meiner Studienarbeit mit dem Einsatz künstlicher Intelligenz in der öffentlichen Verwaltung. Mein Studienvorhaben besteht darin, an der Universität Leipzig die dort angebotenen Module zur Datenethik zu belegen – ein Schwerpunkt, den es in dieser Form an meiner Heimatuniversität nicht gibt. Ein Semester in Deutschland würde daher nicht nur wesentlich zur Vertiefung meiner sprachlichen Kompetenzen beitragen, sondern meinem Studienprofil eine fachliche Richtung geben, die mir sonst verschlossen bliebe.\n\nMeine Deutschkenntnisse habe ich zuletzt durch das Goethe-Zertifikat B2 mit der Note „sehr gut“ nachgewiesen; derzeit bereite ich mich auf die C1-Prüfung vor. Darüber hinaus bringe ich Erfahrung in der Beratung mit: Seit zwei Jahren betreue ich an meiner Fakultät Erstsemester als Mentorin. Umso mehr freue ich mich auf die Möglichkeit, nach meiner Rückkehr ehrenamtlich in der Studienberatung Ihrer Stiftung mitzuwirken und meine Erfahrungen an künftige Bewerberinnen und Bewerber weiterzugeben.\n\nFür ein persönliches Gespräch stehe ich jederzeit zur Verfügung. Über eine positive Rückmeldung würde ich mich sehr freuen.\n\nMit freundlichen Grüßen\nZeynep Kaya",
      },
    ],
  },
];
