import type { DialogueReply, DialogueTurn } from "@/lib/dialogue";
import type { SpeakingDialogueExercise } from "../types";

/**
 * Karşılıklı konuşma alıştırmaları, ikinci küme (WP-72 / WP-23 adım 3):
 * seviye başına 5'e tamamlayan 18 diyalog. Biçim `dialogue.ts` ile aynı:
 * niyet eşleştirmeli senaryo (sağlayıcısız yedek) + `theme` (sağlayıcı
 * varken açık uçlu model). Sahneler kapalı ve gündelik: her turda 2–3 dal,
 * her dalda kullanılan kalıp; `fallback.example` somut bir çıkış cümlesi.
 */
const reply = (match: string[], say: string, sayTr: string, next?: string, uses?: string[]): DialogueReply => ({ match, say, sayTr, next, uses });
const turn = (id: string, ask: string, askTr: string, cue: string, replies: DialogueReply[], fallback: DialogueTurn["fallback"]): DialogueTurn => ({ id, ask, askTr, cue, replies, fallback });

export const dialogues2: SpeakingDialogueExercise[] = [
  // ── A1 ──
  {
    id: "a1-d2", level: "A1", skill: "speaking", title: "Beim Bäcker", genre: "Diyalog",
    theme: { role: "Verkäuferin in einer Bäckerei", goal: "Ne istediğini sor, miktarı ve fiyatı söyle, başka bir şey isteyip istemediğini sor, ödemeyi al.", limits: "Fiyatlar 1–6 Euro arası." },
    intro: "Fırındasın. Satıcı seninle konuşuyor; ne istediğini Almanca söyle.",
    minutes: 5,
    gloss: [{ de: "das Brötchen", tr: "küçük ekmek", en: "bread roll" }, { de: "das Brot", tr: "ekmek", en: "bread" }, { de: "die Brezel", tr: "Alman simidi", en: "pretzel" }, { de: "sonst noch etwas?", tr: "başka bir şey?", en: "anything else?" }],
    targets: [
      { de: "Ich hätte gern …", tr: "… istiyorum", en: "I'd like …" },
      { de: "Was kostet …?", tr: "… ne kadar?", en: "How much is …?" },
      { de: "Das ist alles.", tr: "Hepsi bu.", en: "That's all." },
      { de: "Danke, tschüss!", tr: "Teşekkürler, hoşça kal!", en: "Thanks, bye!" },
    ],
    dialogue: [
      turn("start", "Guten Morgen! Was darf es sein?", "Günaydın! Ne istersiniz?", "Ne istediğini söyle: „Ich hätte gern vier Brötchen.“",
        [reply(["brötchen", "brotchen"], "Vier Brötchen, gern. Möchten Sie auch Brot?", "Dört küçük ekmek, tabii. Ekmek de ister misiniz?", "more", ["Ich hätte gern …"]),
         reply(["brot", "brote", "laib"], "Ein Brot, sehr gern. Sonst noch etwas?", "Bir ekmek, memnuniyetle. Başka bir şey?", "more", ["Ich hätte gern …"]),
         reply(["brezel", "brezeln"], "Zwei Brezeln, bitte schön. Sonst noch etwas?", "İki simit, buyurun. Başka bir şey?", "more", ["Ich hätte gern …"])],
        { say: "Entschuldigung, was möchten Sie? Brötchen, Brot oder Brezeln?", sayTr: "Pardon, ne istiyorsunuz? Küçük ekmek, ekmek mi, simit mi?", example: "Ich hätte gern vier Brötchen." }),
      turn("more", "Möchten Sie noch etwas?", "Başka bir şey ister misiniz?", "Fiyat sor ya da „Das ist alles“ de.",
        [reply(["kostet", "wie viel", "preis"], "Das macht zusammen drei Euro zwanzig.", "Toplam üç euro yirmi.", "pay", ["Was kostet …?"]),
         reply(["alles", "nichts", "das ist alles", "nein"], "Gut, das macht zwei Euro achtzig.", "Peki, iki euro seksen.", "pay", ["Das ist alles."]),
         reply(["kuchen", "croissant"], "Ein Croissant dazu. Das macht vier Euro.", "Bir de kruvasan. Dört euro.", "pay", ["Ich hätte gern …"])],
        { say: "Möchten Sie noch etwas, oder ist das alles?", sayTr: "Başka bir şey mi, yoksa hepsi bu mu?", example: "Das ist alles, danke." }),
      turn("pay", "Bar oder mit Karte?", "Nakit mi kart mı?", "Nasıl ödeyeceğini söyle ve vedalaş.",
        [reply(["bar", "bargeld"], "Bar, gern. Vielen Dank und einen schönen Tag!", "Nakit, tabii. Teşekkürler, iyi günler!", undefined, ["Danke, tschüss!"]),
         reply(["karte", "kreditkarte", "ec"], "Mit Karte, kein Problem. Danke und tschüss!", "Kartla, sorun değil. Teşekkürler, hoşça kalın!", undefined, ["Danke, tschüss!"])],
        { say: "Zahlen Sie bar oder mit Karte?", sayTr: "Nakit mi kartla mı ödüyorsunuz?", example: "Mit Karte, bitte. Danke, tschüss!" }),
    ],
  },
  {
    id: "a1-d3", level: "A1", skill: "speaking", title: "Im Restaurant", genre: "Diyalog",
    theme: { role: "Kellner in einem Restaurant", goal: "Masa sor, içecek ve yemek siparişi al, bir tavsiye ver, sonunda tatlı sor.", limits: "Menü: Schnitzel, Salat, Suppe; içecek: Wasser, Cola, Apfelschorle." },
    intro: "Restorandasın. Garson soruyor; sipariş ver.",
    minutes: 5,
    gloss: [{ de: "die Speisekarte", tr: "menü", en: "menu" }, { de: "das Schnitzel", tr: "şnitzel", en: "schnitzel" }, { de: "die Suppe", tr: "çorba", en: "soup" }, { de: "die Apfelschorle", tr: "elma sodası", en: "apple spritzer" }],
    targets: [
      { de: "Einen Tisch für zwei, bitte.", tr: "İki kişilik bir masa, lütfen.", en: "A table for two, please." },
      { de: "Ich nehme …", tr: "… alıyorum", en: "I'll have …" },
      { de: "Was empfehlen Sie?", tr: "Ne tavsiye edersiniz?", en: "What do you recommend?" },
      { de: "Nein, danke.", tr: "Hayır, teşekkürler.", en: "No, thanks." },
    ],
    dialogue: [
      turn("start", "Guten Abend! Haben Sie reserviert?", "İyi akşamlar! Rezervasyonunuz var mı?", "Masa iste: „Einen Tisch für zwei, bitte.“",
        [reply(["tisch", "zwei", "personen", "nein"], "Kein Problem, hier bitte. Was möchten Sie trinken?", "Sorun değil, buyurun. Ne içmek istersiniz?", "drink", ["Einen Tisch für zwei, bitte."]),
         reply(["reserviert", "ja", "name"], "Ah ja, Ihr Tisch ist hier. Was möchten Sie trinken?", "Ah evet, masanız burada. Ne içersiniz?", "drink", [])],
        { say: "Möchten Sie einen Tisch? Für wie viele Personen?", sayTr: "Masa ister misiniz? Kaç kişilik?", example: "Einen Tisch für zwei, bitte." }),
      turn("drink", "Was möchten Sie trinken?", "Ne içmek istersiniz?", "İçecek söyle: „Ich nehme ein Wasser.“",
        [reply(["wasser", "mineral"], "Ein Wasser, gern. Und zu essen?", "Bir su, tabii. Yemek olarak?", "food", ["Ich nehme …"]),
         reply(["cola", "schorle", "saft", "bier"], "Kommt sofort. Und zu essen?", "Hemen geliyor. Yemek olarak?", "food", ["Ich nehme …"])],
        { say: "Wasser, Cola oder Apfelschorle?", sayTr: "Su, kola, elma sodası?", example: "Ich nehme ein Wasser, bitte." }),
      turn("food", "Und was möchten Sie essen?", "Ne yemek istersiniz?", "Sipariş ver ya da tavsiye sor: „Was empfehlen Sie?“",
        [reply(["empfehlen", "empfiehlst", "tipp"], "Das Schnitzel ist heute sehr gut. Möchten Sie das?", "Bugün şnitzel çok iyi. Onu ister misiniz?", "dessert", ["Was empfehlen Sie?"]),
         reply(["schnitzel", "salat", "suppe", "nehme"], "Sehr gute Wahl. Kommt gleich.", "Çok iyi seçim. Hemen geliyor.", "dessert", ["Ich nehme …"])],
        { say: "Wir haben Schnitzel, Salat und Suppe. Was nehmen Sie?", sayTr: "Şnitzel, salata ve çorba var. Ne alırsınız?", example: "Ich nehme das Schnitzel." }),
      turn("dessert", "Möchten Sie noch einen Nachtisch?", "Tatlı ister misiniz?", "Kabul et ya da reddet: „Nein, danke.“",
        [reply(["nein", "danke", "satt"], "Alles klar. Ich bringe die Rechnung.", "Tamam. Hesabı getiriyorum.", undefined, ["Nein, danke."]),
         reply(["ja", "gern", "kuchen", "eis"], "Ein Eis, gern. Kommt sofort.", "Dondurma, tabii. Hemen.", undefined, ["Ich nehme …"])],
        { say: "Nachtisch — ja oder nein?", sayTr: "Tatlı — evet mi hayır mı?", example: "Nein, danke. Die Rechnung, bitte." }),
    ],
  },
  {
    id: "a1-d4", level: "A1", skill: "speaking", title: "Am Bahnhof", genre: "Diyalog",
    theme: { role: "Mitarbeiter am Fahrkartenschalter", goal: "Nereye gideceğini, ne zaman, tek yön mü gidiş-dönüş mü sor; fiyat ve peron söyle.", limits: "Fiyat 20–60 Euro; peron 1–9." },
    intro: "Tren istasyonunda gişedesin. Bilet al.",
    minutes: 5,
    gloss: [{ de: "die Fahrkarte", tr: "bilet", en: "ticket" }, { de: "einfach / hin und zurück", tr: "tek yön / gidiş-dönüş", en: "one-way / return" }, { de: "das Gleis", tr: "peron", en: "platform" }, { de: "abfahren", tr: "kalkmak", en: "to depart" }],
    targets: [
      { de: "Eine Fahrkarte nach …, bitte.", tr: "…'e bir bilet, lütfen.", en: "A ticket to …, please." },
      { de: "Wann fährt der Zug?", tr: "Tren ne zaman kalkıyor?", en: "When does the train leave?" },
      { de: "Von welchem Gleis?", tr: "Hangi perondan?", en: "From which platform?" },
      { de: "Hin und zurück.", tr: "Gidiş-dönüş.", en: "Return." },
    ],
    dialogue: [
      turn("start", "Guten Tag, wohin möchten Sie fahren?", "İyi günler, nereye gitmek istiyorsunuz?", "Nereye gideceğini söyle: „Eine Fahrkarte nach Berlin, bitte.“",
        [reply(["berlin", "münchen", "hamburg", "köln", "nach"], "Gern. Einfach oder hin und zurück?", "Tabii. Tek yön mü, gidiş-dönüş mü?", "type", ["Eine Fahrkarte nach …, bitte."])],
        { say: "Wohin möchten Sie? Nach Berlin, München oder Hamburg?", sayTr: "Nereye? Berlin, Münih, Hamburg?", example: "Eine Fahrkarte nach Berlin, bitte." }),
      turn("type", "Einfach oder hin und zurück?", "Tek yön mü, gidiş-dönüş mü?", "Cevap ver: „Hin und zurück.“ ya da „Einfach.“",
        [reply(["zurück", "hin und", "zuruck"], "Hin und zurück, das macht 58 Euro.", "Gidiş-dönüş, 58 euro.", "when", ["Hin und zurück."]),
         reply(["einfach", "nur hin"], "Einfach, das macht 32 Euro.", "Tek yön, 32 euro.", "when", [])],
        { say: "Nur hin, oder auch zurück?", sayTr: "Sadece gidiş mi, dönüş de mi?", example: "Hin und zurück, bitte." }),
      turn("when", "Möchten Sie noch etwas wissen?", "Başka bir şey öğrenmek ister misiniz?", "Saati ya da peronu sor.",
        [reply(["wann", "uhr", "fährt", "abfahrt"], "Der nächste Zug fährt um 14:20 Uhr.", "Sonraki tren 14:20'de kalkıyor.", "gleis", ["Wann fährt der Zug?"]),
         reply(["gleis", "welchem", "wo"], "Von Gleis 7. Gute Reise!", "Peron 7'den. İyi yolculuklar!", undefined, ["Von welchem Gleis?"])],
        { say: "Möchten Sie die Uhrzeit oder das Gleis wissen?", sayTr: "Saati mi peronu mu öğrenmek istiyorsunuz?", example: "Wann fährt der Zug?" }),
      turn("gleis", "Der Zug fährt um 14:20 Uhr. Noch eine Frage?", "Tren 14:20'de. Başka soru?", "Peronu sor: „Von welchem Gleis?“",
        [reply(["gleis", "welchem", "wo"], "Von Gleis 7. Gute Reise!", "Peron 7'den. İyi yolculuklar!", undefined, ["Von welchem Gleis?"]),
         reply(["danke", "nein", "alles"], "Gern geschehen. Gute Reise!", "Rica ederim. İyi yolculuklar!", undefined, [])],
        { say: "Möchten Sie das Gleis wissen?", sayTr: "Peronu öğrenmek ister misiniz?", example: "Von welchem Gleis fährt der Zug?" }),
    ],
  },
  {
    id: "a1-d5", level: "A1", skill: "speaking", title: "Beim Arzt anrufen", genre: "Diyalog",
    theme: { role: "Sprechstundenhilfe in einer Arztpraxis", goal: "Randevu talebi al: neden, ne zaman uygun, isim ve doğum tarihi sor; randevu ver.", limits: "Randevu bu hafta içinde, sabah ya da öğleden sonra." },
    intro: "Doktoru arayıp randevu alıyorsun.",
    minutes: 5,
    gloss: [{ de: "der Termin", tr: "randevu", en: "appointment" }, { de: "die Schmerzen", tr: "ağrı", en: "pain" }, { de: "der Vormittag", tr: "öğleden önce", en: "morning" }, { de: "das Geburtsdatum", tr: "doğum tarihi", en: "date of birth" }],
    targets: [
      { de: "Ich hätte gern einen Termin.", tr: "Randevu almak istiyorum.", en: "I'd like an appointment." },
      { de: "Ich habe … Schmerzen.", tr: "… ağrım var.", en: "I have … pain." },
      { de: "Am Vormittag passt es mir.", tr: "Sabah bana uyar.", en: "Morning suits me." },
      { de: "Vielen Dank, auf Wiederhören.", tr: "Teşekkürler, hoşça kalın (telefonda).", en: "Thanks, goodbye." },
    ],
    dialogue: [
      turn("start", "Praxis Dr. Weber, guten Tag. Was kann ich für Sie tun?", "Dr. Weber muayenehanesi, iyi günler. Nasıl yardımcı olabilirim?", "Randevu iste: „Ich hätte gern einen Termin.“",
        [reply(["termin", "arzt", "sprechstunde"], "Gern. Worum geht es denn?", "Tabii. Ne için?", "why", ["Ich hätte gern einen Termin."])],
        { say: "Möchten Sie einen Termin?", sayTr: "Randevu mu istiyorsunuz?", example: "Ich hätte gern einen Termin." }),
      turn("why", "Worum geht es?", "Ne için?", "Şikâyetini söyle: „Ich habe Kopfschmerzen.“",
        [reply(["schmerzen", "kopf", "hals", "bauch", "fieber", "krank"], "Verstehe. Passt es Ihnen am Vormittag oder am Nachmittag?", "Anladım. Sabah mı öğleden sonra mı uyar?", "when", ["Ich habe … Schmerzen."])],
        { say: "Haben Sie Schmerzen, oder ist es eine Kontrolle?", sayTr: "Ağrınız mı var, kontrol mü?", example: "Ich habe Halsschmerzen." }),
      turn("when", "Vormittag oder Nachmittag?", "Sabah mı, öğleden sonra mı?", "Uygun zamanı söyle.",
        [reply(["vormittag", "morgen", "früh"], "Am Donnerstag um 9 Uhr? Wie ist Ihr Name?", "Perşembe 9'da? Adınız?", "name", ["Am Vormittag passt es mir."]),
         reply(["nachmittag", "abend", "spät"], "Am Donnerstag um 15 Uhr? Wie ist Ihr Name?", "Perşembe 15'te? Adınız?", "name", [])],
        { say: "Passt es am Vormittag oder am Nachmittag?", sayTr: "Sabah mı öğleden sonra mı uyar?", example: "Am Vormittag passt es mir." }),
      turn("name", "Wie ist Ihr Name und Ihr Geburtsdatum?", "Adınız ve doğum tarihiniz?", "Adını ve doğum tarihini söyle, sonra vedalaş.",
        [reply(["heiße", "name", "geboren", "mein"], "Danke, der Termin ist notiert. Auf Wiederhören!", "Teşekkürler, randevu kaydedildi. Hoşça kalın!", undefined, ["Vielen Dank, auf Wiederhören."])],
        { say: "Sagen Sie mir bitte Ihren Namen.", sayTr: "Lütfen adınızı söyleyin.", example: "Ich heiße Deniz Kaya, geboren am 3. Mai 1995. Vielen Dank, auf Wiederhören." }),
    ],
  },

  // ── A2 ──
  {
    id: "a2-d2", level: "A2", skill: "speaking", title: "Wohnungsbesichtigung", genre: "Diyalog",
    theme: { role: "Vermieterin bei einer Wohnungsbesichtigung", goal: "Daireyi göster, kira ve yan giderleri söyle, ne zaman taşınabileceğini sor, belgeleri iste.", limits: "Kira 650–900 Euro; taşınma 1 Ekim." },
    intro: "Kiralık daireyi geziyorsun. Ev sahibiyle konuş.",
    minutes: 6,
    gloss: [{ de: "die Miete", tr: "kira", en: "rent" }, { de: "die Nebenkosten", tr: "yan giderler", en: "utilities" }, { de: "einziehen", tr: "eve taşınmak", en: "to move in" }, { de: "die Kaution", tr: "depozito", en: "deposit" }],
    targets: [
      { de: "Wie hoch ist die Miete?", tr: "Kira ne kadar?", en: "How much is the rent?" },
      { de: "Sind die Nebenkosten inklusive?", tr: "Yan giderler dâhil mi?", en: "Are utilities included?" },
      { de: "Wann kann ich einziehen?", tr: "Ne zaman taşınabilirim?", en: "When can I move in?" },
      { de: "Ich würde die Wohnung gern nehmen.", tr: "Daireyi tutmak isterim.", en: "I'd like to take the flat." },
    ],
    dialogue: [
      turn("start", "Willkommen! Das ist das Wohnzimmer, dort die Küche. Haben Sie Fragen?", "Hoş geldiniz! Burası oturma odası, orası mutfak. Sorunuz var mı?", "Kirayı sor: „Wie hoch ist die Miete?“",
        [reply(["miete", "kostet", "hoch", "preis"], "Die Miete beträgt 780 Euro kalt.", "Kira 780 euro, yan giderler hariç.", "neben", ["Wie hoch ist die Miete?"]),
         reply(["zimmer", "groß", "quadratmeter"], "Die Wohnung hat 62 Quadratmeter und zwei Zimmer.", "Daire 62 metrekare, iki oda.", "neben", [])],
        { say: "Möchten Sie etwas zur Miete oder zur Wohnung wissen?", sayTr: "Kira ya da daire hakkında bir şey sormak ister misiniz?", example: "Wie hoch ist die Miete?" }),
      turn("neben", "Möchten Sie noch etwas wissen?", "Başka bir şey?", "Yan giderleri sor.",
        [reply(["nebenkosten", "inklusive", "heizung", "strom"], "Die Nebenkosten sind 120 Euro extra, Strom kommt dazu.", "Yan giderler 120 euro ek, elektrik ayrı.", "when", ["Sind die Nebenkosten inklusive?"]),
         reply(["kaution", "deposit"], "Die Kaution ist zwei Monatsmieten.", "Depozito iki aylık kira.", "when", [])],
        { say: "Fragen Sie nach den Nebenkosten oder der Kaution?", sayTr: "Yan giderleri mi depozitoyu mu soruyorsunuz?", example: "Sind die Nebenkosten inklusive?" }),
      turn("when", "Alles klar. Noch Fragen?", "Tamam. Başka soru?", "Ne zaman taşınabileceğini sor.",
        [reply(["einziehen", "wann", "ab wann", "frei"], "Ab dem 1. Oktober. Möchten Sie die Wohnung?", "1 Ekim'den itibaren. Daireyi istiyor musunuz?", "decide", ["Wann kann ich einziehen?"])],
        { say: "Möchten Sie wissen, ab wann die Wohnung frei ist?", sayTr: "Dairenin ne zaman boşalacağını mı sormak istiyorsunuz?", example: "Wann kann ich einziehen?" }),
      turn("decide", "Möchten Sie die Wohnung nehmen?", "Daireyi tutmak istiyor musunuz?", "Karar ver.",
        [reply(["nehmen", "gern", "ja", "würde"], "Wunderbar! Dann brauche ich Ihre Gehaltsnachweise.", "Harika! O zaman maaş belgelerinizi rica ederim.", undefined, ["Ich würde die Wohnung gern nehmen."]),
         reply(["überlegen", "nein", "später", "denken"], "Kein Problem, melden Sie sich einfach bis Freitag.", "Sorun değil, cumaya kadar haber verin.", undefined, [])],
        { say: "Nehmen Sie die Wohnung, oder möchten Sie überlegen?", sayTr: "Tutuyor musunuz, yoksa düşünecek misiniz?", example: "Ich würde die Wohnung gern nehmen." }),
    ],
  },
  {
    id: "a2-d3", level: "A2", skill: "speaking", title: "Reklamation im Geschäft", genre: "Diyalog",
    theme: { role: "Verkäufer an der Kundeninformation", goal: "Sorunu dinle, fişi sor, değişim ya da iade seç, işlemi tamamla.", limits: "İade fişle 14 gün içinde; fiş yoksa yalnız değişim." },
    intro: "Aldığın ceket bozuk çıktı. Mağazada şikâyet ediyorsun.",
    minutes: 6,
    gloss: [{ de: "die Jacke", tr: "ceket", en: "jacket" }, { de: "der Reißverschluss", tr: "fermuar", en: "zipper" }, { de: "der Kassenbon", tr: "fiş", en: "receipt" }, { de: "umtauschen", tr: "değiştirmek", en: "to exchange" }],
    targets: [
      { de: "Ich möchte … reklamieren.", tr: "… şikâyet etmek istiyorum.", en: "I'd like to make a complaint about …" },
      { de: "… ist kaputt.", tr: "… bozuk.", en: "… is broken." },
      { de: "Ich habe den Kassenbon.", tr: "Fişim var.", en: "I have the receipt." },
      { de: "Kann ich das Geld zurückbekommen?", tr: "Parayı geri alabilir miyim?", en: "Can I get a refund?" },
    ],
    dialogue: [
      turn("start", "Guten Tag, wie kann ich Ihnen helfen?", "İyi günler, nasıl yardımcı olabilirim?", "Sorunu söyle: „Ich möchte diese Jacke reklamieren.“",
        [reply(["reklamieren", "kaputt", "jacke", "problem", "reißverschluss"], "Oh, das tut mir leid. Was genau ist das Problem?", "Üzgünüm. Sorun tam olarak ne?", "problem", ["Ich möchte … reklamieren."])],
        { say: "Möchten Sie etwas reklamieren?", sayTr: "Bir şikâyetiniz mi var?", example: "Ich möchte diese Jacke reklamieren." }),
      turn("problem", "Was genau ist das Problem?", "Sorun ne?", "Ne bozuk, söyle.",
        [reply(["reißverschluss", "kaputt", "geht nicht", "defekt", "loch"], "Verstehe. Haben Sie den Kassenbon dabei?", "Anladım. Fişiniz yanınızda mı?", "bon", ["… ist kaputt."])],
        { say: "Was ist kaputt?", sayTr: "Ne bozuk?", example: "Der Reißverschluss ist kaputt." }),
      turn("bon", "Haben Sie den Kassenbon?", "Fişiniz var mı?", "Fişin olup olmadığını söyle.",
        [reply(["ja", "habe", "hier", "bon"], "Prima. Möchten Sie umtauschen oder das Geld zurück?", "Harika. Değişim mi, para iadesi mi?", "choice", ["Ich habe den Kassenbon."]),
         reply(["nein", "verloren", "nicht"], "Ohne Bon können wir nur umtauschen. Ist das okay?", "Fişsiz yalnız değişim yapabiliriz. Uyar mı?", "choice", [])],
        { say: "Haben Sie den Kassenbon dabei — ja oder nein?", sayTr: "Fişiniz yanınızda mı — evet mi hayır mı?", example: "Ja, ich habe den Kassenbon." }),
      turn("choice", "Umtauschen oder Geld zurück?", "Değişim mi, para iadesi mi?", "Tercihini söyle.",
        [reply(["geld", "zurück", "zurückbekommen", "erstatten"], "Kein Problem, ich buche das Geld auf Ihre Karte zurück.", "Sorun değil, parayı kartınıza iade ediyorum.", undefined, ["Kann ich das Geld zurückbekommen?"]),
         reply(["umtauschen", "tauschen", "neue", "andere"], "Gern, welche Größe brauchen Sie?", "Tabii, hangi beden?", undefined, [])],
        { say: "Möchten Sie das Geld zurück oder eine neue Jacke?", sayTr: "Parayı mı geri istiyorsunuz, yeni ceket mi?", example: "Kann ich das Geld zurückbekommen?" }),
    ],
  },
  {
    id: "a2-d4", level: "A2", skill: "speaking", title: "Auf dem Amt", genre: "Diyalog",
    theme: { role: "Sachbearbeiterin im Bürgeramt", goal: "Ne için geldiğini sor, adres kaydı için belgeleri iste, randevu numarasını kontrol et, işlemi bitir.", limits: "Gereken belgeler: pasaport ve Wohnungsgeberbestätigung." },
    intro: "Belediyede adres kaydı (Anmeldung) yaptırıyorsun.",
    minutes: 6,
    gloss: [{ de: "sich anmelden", tr: "kayıt yaptırmak", en: "to register" }, { de: "der Reisepass", tr: "pasaport", en: "passport" }, { de: "die Wohnungsgeberbestätigung", tr: "ev sahibi onayı", en: "landlord confirmation" }, { de: "das Formular", tr: "form", en: "form" }],
    targets: [
      { de: "Ich möchte mich anmelden.", tr: "Kayıt yaptırmak istiyorum.", en: "I'd like to register." },
      { de: "Hier ist mein Reisepass.", tr: "İşte pasaportum.", en: "Here is my passport." },
      { de: "Welche Unterlagen brauche ich?", tr: "Hangi belgeler gerekiyor?", en: "Which documents do I need?" },
      { de: "Könnten Sie das bitte wiederholen?", tr: "Tekrar edebilir misiniz?", en: "Could you repeat that?" },
    ],
    dialogue: [
      turn("start", "Guten Tag, Sie haben Termin 42? Worum geht es?", "İyi günler, randevu 42 sizde mi? Konu ne?", "Ne istediğini söyle: „Ich möchte mich anmelden.“",
        [reply(["anmelden", "anmeldung", "wohnung", "adresse", "umgezogen"], "Gut. Dafür brauche ich Ihren Reisepass und die Wohnungsgeberbestätigung.", "Peki. Bunun için pasaportunuz ve ev sahibi onayı gerekiyor.", "docs", ["Ich möchte mich anmelden."]),
         reply(["unterlagen", "brauche", "welche"], "Für die Anmeldung: Reisepass und Wohnungsgeberbestätigung.", "Kayıt için: pasaport ve ev sahibi onayı.", "docs", ["Welche Unterlagen brauche ich?"])],
        { say: "Möchten Sie sich anmelden?", sayTr: "Kayıt mı yaptıracaksınız?", example: "Ich möchte mich anmelden." }),
      turn("docs", "Haben Sie die Unterlagen dabei?", "Belgeler yanınızda mı?", "Belgeleri ver ya da anlamadıysan tekrar iste.",
        [reply(["hier", "reisepass", "pass", "bestätigung", "ja"], "Danke. Bitte füllen Sie noch dieses Formular aus.", "Teşekkürler. Şu formu da doldurun lütfen.", "form", ["Hier ist mein Reisepass."]),
         reply(["wiederholen", "langsam", "verstehe nicht", "bitte noch"], "Natürlich: Reisepass und Wohnungsgeberbestätigung — die Bestätigung vom Vermieter.", "Tabii: pasaport ve ev sahibi onayı — ev sahibinden alınan belge.", "form", ["Könnten Sie das bitte wiederholen?"])],
        { say: "Haben Sie Ihren Reisepass dabei?", sayTr: "Pasaportunuz yanınızda mı?", example: "Ja, hier ist mein Reisepass." }),
      turn("form", "Ist das Formular fertig?", "Form hazır mı?", "Formu ver ya da bir soru sor.",
        [reply(["fertig", "hier", "ja", "bitte"], "Perfekt. Sie sind jetzt angemeldet. Hier ist Ihre Bestätigung.", "Mükemmel. Kaydınız yapıldı. İşte belgeniz.", undefined, []),
         reply(["frage", "wie lange", "dauert", "kostet"], "Es kostet nichts und ist sofort fertig. Bitte unterschreiben Sie hier.", "Ücretsiz ve hemen hazır. Buraya imza atın.", undefined, [])],
        { say: "Geben Sie mir bitte das Formular.", sayTr: "Formu bana verin lütfen.", example: "Hier ist das Formular, fertig." }),
    ],
  },
  {
    id: "a2-d5", level: "A2", skill: "speaking", title: "Ein Treffen verabreden", genre: "Diyalog",
    theme: { role: "Freundin, die sich verabreden will", goal: "Buluşma önerin, gün ve saat üstünde anlaşın, yer belirleyin; bir öneriyi reddedip alternatif sunun.", limits: "Öğrenci bir gün için 'olmaz' desin ki alternatif çıksın." },
    intro: "Arkadaşın seninle buluşmak istiyor. Gün, saat ve yer kararlaştırın.",
    minutes: 5,
    gloss: [{ de: "sich treffen", tr: "buluşmak", en: "to meet" }, { de: "passen", tr: "uymak", en: "to suit" }, { de: "leider", tr: "maalesef", en: "unfortunately" }, { de: "der Vorschlag", tr: "öneri", en: "suggestion" }],
    targets: [
      { de: "Hast du am … Zeit?", tr: "… günü vaktin var mı?", en: "Are you free on …?" },
      { de: "Das passt mir leider nicht.", tr: "Bu bana maalesef uymuyor.", en: "That doesn't suit me." },
      { de: "Wie wäre es mit …?", tr: "… nasıl olur?", en: "How about …?" },
      { de: "Wo treffen wir uns?", tr: "Nerede buluşuyoruz?", en: "Where shall we meet?" },
    ],
    dialogue: [
      turn("start", "Hey! Wollen wir uns diese Woche treffen? Hast du am Dienstag Zeit?", "Selam! Bu hafta buluşalım mı? Salı vaktin var mı?", "Kabul et ya da reddedip başka gün öner.",
        [reply(["nicht", "leider", "passt nicht", "keine zeit", "arbeite"], "Schade. Wie wäre es mit Donnerstag?", "Yazık. Perşembe nasıl?", "alt", ["Das passt mir leider nicht."]),
         reply(["ja", "passt", "gern", "zeit"], "Super! Um wie viel Uhr?", "Süper! Saat kaçta?", "time", ["Hast du am … Zeit?"])],
        { say: "Passt dir Dienstag, oder lieber ein anderer Tag?", sayTr: "Salı uyar mı, yoksa başka gün mü?", example: "Das passt mir leider nicht. Wie wäre es mit Donnerstag?" }),
      turn("alt", "Donnerstag also? Oder hast du einen anderen Vorschlag?", "Perşembe o zaman? Ya da başka önerin var mı?", "Kabul et ya da öner: „Wie wäre es mit Freitag?“",
        [reply(["freitag", "samstag", "wie wäre", "vorschlag", "lieber"], "Okay, das geht auch. Um wie viel Uhr?", "Tamam, o da olur. Saat kaçta?", "time", ["Wie wäre es mit …?"]),
         reply(["donnerstag", "ja", "passt", "gut"], "Perfekt, Donnerstag. Um wie viel Uhr?", "Mükemmel, perşembe. Saat kaçta?", "time", [])],
        { say: "Donnerstag oder ein anderer Tag?", sayTr: "Perşembe mi, başka gün mü?", example: "Wie wäre es mit Freitag?" }),
      turn("time", "Um wie viel Uhr?", "Saat kaçta?", "Saat söyle ve yeri sor.",
        [reply(["uhr", "um", "abend", "nachmittag", "halb"], "Passt. Und wo treffen wir uns?", "Uyar. Peki nerede buluşuyoruz?", "where", []),
         reply(["wo", "treffen", "ort"], "Vielleicht im Café am Markt, um sieben?", "Belki Markt'taki kafede, yedide?", "where", ["Wo treffen wir uns?"])],
        { say: "Sag mir eine Uhrzeit.", sayTr: "Bir saat söyle.", example: "Um sieben Uhr. Wo treffen wir uns?" }),
      turn("where", "Wo treffen wir uns?", "Nerede buluşuyoruz?", "Yer öner.",
        [reply(["café", "cafe", "markt", "bahnhof", "bei mir", "park", "kino"], "Gute Idee! Bis dann!", "İyi fikir! Görüşürüz!", undefined, ["Wo treffen wir uns?"])],
        { say: "Im Café oder am Bahnhof?", sayTr: "Kafede mi istasyonda mı?", example: "Im Café am Markt." }),
    ],
  },

  // ── B1 ──
  {
    id: "b1-d2", level: "B1", skill: "speaking", title: "Beschwerde beim Vermieter", genre: "Diyalog",
    theme: { role: "Vermieter am Telefon", goal: "Şikâyeti dinle (ısıtma bozuk), ne zamandır sor, tamirci için tarih öner, kira indirimi talebine ölçülü cevap ver.", limits: "Tamirci en erken üç gün sonra; indirim 'bakarız'." },
    intro: "Isıtma üç gündür çalışmıyor. Ev sahibini arayıp çözüm istiyorsun.",
    minutes: 6,
    gloss: [{ de: "die Heizung", tr: "ısıtma", en: "heating" }, { de: "der Handwerker", tr: "tamirci", en: "repairman" }, { de: "die Mietminderung", tr: "kira indirimi", en: "rent reduction" }, { de: "dringend", tr: "acil", en: "urgent" }],
    targets: [
      { de: "Ich rufe an, weil …", tr: "… için arıyorum", en: "I'm calling because …" },
      { de: "Seit drei Tagen …", tr: "Üç gündür …", en: "For three days …" },
      { de: "Könnten Sie bitte einen Handwerker schicken?", tr: "Tamirci gönderebilir misiniz?", en: "Could you send a repairman?" },
      { de: "Ich möchte eine Mietminderung beantragen.", tr: "Kira indirimi talep ediyorum.", en: "I'd like to request a rent reduction." },
    ],
    dialogue: [
      turn("start", "Müller, guten Tag. Was kann ich für Sie tun?", "Müller, iyi günler. Ne yapabilirim?", "Neden aradığını söyle: „Ich rufe an, weil die Heizung nicht funktioniert.“",
        [reply(["heizung", "kalt", "funktioniert", "rufe an", "weil"], "Oh, das ist ärgerlich. Seit wann ist das so?", "Bu can sıkıcı. Ne zamandır böyle?", "since", ["Ich rufe an, weil …"])],
        { say: "Geht es um die Wohnung? Was ist das Problem?", sayTr: "Daireyle mi ilgili? Sorun ne?", example: "Ich rufe an, weil die Heizung nicht funktioniert." }),
      turn("since", "Seit wann ist das so?", "Ne zamandır?", "Süreyi söyle: „Seit drei Tagen.“",
        [reply(["seit", "tagen", "tage", "woche", "gestern"], "Verstehe. Ich kann frühestens Montag einen Handwerker schicken.", "Anladım. En erken pazartesi tamirci gönderebilirim.", "repair", ["Seit drei Tagen …"])],
        { say: "Seit wann funktioniert die Heizung nicht?", sayTr: "Isıtma ne zamandır çalışmıyor?", example: "Seit drei Tagen ist es in der Wohnung kalt." }),
      turn("repair", "Montag passt Ihnen?", "Pazartesi uyar mı?", "Daha erken iste ya da kabul et; tamirci talebini açıkça söyle.",
        [reply(["früher", "dringend", "schnell", "sofort", "kalt"], "Ich verstehe die Dringlichkeit. Ich versuche es für Freitag.", "Aciliyeti anlıyorum. Cuma için deneyeceğim.", "minderung", ["Könnten Sie bitte einen Handwerker schicken?"]),
         reply(["montag", "okay", "passt", "gut", "handwerker"], "Gut, Montag zwischen 9 und 12 Uhr.", "Tamam, pazartesi 9–12 arası.", "minderung", ["Könnten Sie bitte einen Handwerker schicken?"])],
        { say: "Passt Montag, oder brauchen Sie es früher?", sayTr: "Pazartesi uyar mı, yoksa daha erken mi gerek?", example: "Könnten Sie bitte früher einen Handwerker schicken? Es ist dringend." }),
      turn("minderung", "Gibt es sonst noch etwas?", "Başka bir şey var mı?", "Kira indirimi talep et ya da teşekkür edip kapat.",
        [reply(["mietminderung", "miete", "weniger", "reduzieren", "beantragen"], "Das prüfe ich, sobald der Handwerker da war. Ich melde mich.", "Tamirci geldikten sonra bakarım. Size dönerim.", undefined, ["Ich möchte eine Mietminderung beantragen."]),
         reply(["danke", "nein", "das war", "wiederhören"], "Gern. Auf Wiederhören!", "Rica ederim. Hoşça kalın!", undefined, [])],
        { say: "Möchten Sie noch etwas besprechen?", sayTr: "Konuşmak istediğiniz başka bir şey var mı?", example: "Ich möchte eine Mietminderung beantragen." }),
    ],
  },
  {
    id: "b1-d3", level: "B1", skill: "speaking", title: "Small Talk in der Pause", genre: "Diyalog",
    theme: { role: "Kollegin in der Kaffeepause", goal: "Hafta sonu, hobi ve iş hakkında sohbet et; bir soru sor, bir görüş bildir, kibarca konuyu değiştir.", limits: "Özel konulara girme." },
    intro: "İş yerinde kahve molası. Yeni iş arkadaşınla sohbet et.",
    minutes: 5,
    gloss: [{ de: "das Wochenende", tr: "hafta sonu", en: "weekend" }, { de: "das Hobby", tr: "hobi", en: "hobby" }, { de: "stressig", tr: "stresli", en: "stressful" }, { de: "übrigens", tr: "bu arada", en: "by the way" }],
    targets: [
      { de: "Wie war dein Wochenende?", tr: "Hafta sonun nasıldı?", en: "How was your weekend?" },
      { de: "Ich finde, dass …", tr: "Bence …", en: "I think that …" },
      { de: "Übrigens, …", tr: "Bu arada, …", en: "By the way, …" },
      { de: "Wir sollten mal …", tr: "Bir ara … yapmalıyız.", en: "We should … sometime." },
    ],
    dialogue: [
      turn("start", "Hey, na? Wie war dein Wochenende?", "Selam! Hafta sonun nasıldı?", "Anlat ve geri sor.",
        [reply(["gut", "schön", "war", "ruhig", "wochenende"], "Klingt gut! Ich war wandern. Was machst du sonst so in deiner Freizeit?", "Kulağa hoş geliyor! Ben yürüyüşe gittim. Boş zamanında ne yaparsın?", "hobby", ["Wie war dein Wochenende?"]),
         reply(["stressig", "gearbeitet", "müde", "viel"], "Oh je. Dann brauchst du Erholung. Hast du ein Hobby?", "Off. O zaman dinlenmen lazım. Bir hobin var mı?", "hobby", [])],
        { say: "Erzähl mal — wie war dein Wochenende?", sayTr: "Anlat — hafta sonun nasıldı?", example: "Es war ruhig. Und wie war dein Wochenende?" }),
      turn("hobby", "Was machst du in deiner Freizeit?", "Boş zamanında ne yaparsın?", "Hobinden bahset, görüş bildir: „Ich finde, dass …“",
        [reply(["finde", "dass", "meinung", "glaube"], "Da hast du recht. Und wie findest du die Arbeit hier bisher?", "Haklısın. Peki buradaki işi nasıl buluyorsun?", "work", ["Ich finde, dass …"]),
         reply(["sport", "lesen", "kochen", "musik", "spiele", "fahre"], "Cool! Und wie findest du die Arbeit hier bisher?", "Harika! Peki buradaki işi şimdiye kadar nasıl buldun?", "work", [])],
        { say: "Hast du ein Hobby?", sayTr: "Hobin var mı?", example: "Ich koche gern. Ich finde, dass Kochen entspannt." }),
      turn("work", "Wie findest du die Arbeit hier?", "Buradaki işi nasıl buluyorsun?", "Görüşünü söyle ya da konuyu değiştir: „Übrigens, …“",
        [reply(["übrigens", "apropos", "andere frage"], "Ach ja? Erzähl!", "Öyle mi? Anlat!", "plan", ["Übrigens, …"]),
         reply(["finde", "gut", "stressig", "interessant", "nett", "kollegen"], "Das freut mich. Wir sollten mal zusammen Mittag essen.", "Buna sevindim. Bir ara birlikte öğle yemeği yemeliyiz.", "plan", ["Ich finde, dass …"])],
        { say: "Gefällt dir die Arbeit?", sayTr: "İşi seviyor musun?", example: "Ich finde, dass die Kollegen sehr nett sind. Übrigens, gibt es hier eine Kantine?" }),
      turn("plan", "Wollen wir mal zusammen Mittag essen?", "Bir ara birlikte öğle yemeği yiyelim mi?", "Öner: „Wir sollten mal …“",
        [reply(["sollten", "gern", "ja", "mittag", "donnerstag", "morgen"], "Abgemacht! Dann bis später.", "Anlaştık! Sonra görüşürüz.", undefined, ["Wir sollten mal …"])],
        { say: "Hast du Lust auf ein gemeinsames Mittagessen?", sayTr: "Birlikte öğle yemeğine var mısın?", example: "Gern! Wir sollten mal am Donnerstag essen gehen." }),
    ],
  },
  {
    id: "b1-d4", level: "B1", skill: "speaking", title: "Beim Kundenservice", genre: "Diyalog",
    theme: { role: "Mitarbeiter der Telefonhotline eines Internetanbieters", goal: "Sorunu tanımla (internet yok), müşteri numarasını sor, iki kontrol adımı iste, teknisyen ya da telafi öner.", limits: "Müşteri numarası 8 haneli." },
    intro: "İnternetin iki gündür yok. Servis hattını arıyorsun.",
    minutes: 6,
    gloss: [{ de: "die Kundennummer", tr: "müşteri numarası", en: "customer number" }, { de: "der Router", tr: "modem", en: "router" }, { de: "neu starten", tr: "yeniden başlatmak", en: "to restart" }, { de: "der Techniker", tr: "teknisyen", en: "technician" }],
    targets: [
      { de: "Seit zwei Tagen habe ich kein Internet.", tr: "İki gündür internetim yok.", en: "I've had no internet for two days." },
      { de: "Das habe ich schon versucht.", tr: "Bunu zaten denedim.", en: "I've already tried that." },
      { de: "Wann kann ein Techniker kommen?", tr: "Teknisyen ne zaman gelebilir?", en: "When can a technician come?" },
      { de: "Bekomme ich eine Gutschrift?", tr: "Bir telafi/iade alacak mıyım?", en: "Will I get a credit?" },
    ],
    dialogue: [
      turn("start", "Kundenservice, mein Name ist Berger. Wie kann ich helfen?", "Müşteri hizmetleri, ben Berger. Nasıl yardımcı olabilirim?", "Sorunu söyle: „Seit zwei Tagen habe ich kein Internet.“",
        [reply(["internet", "kein", "funktioniert", "verbindung", "seit"], "Das tut mir leid. Nennen Sie mir bitte Ihre Kundennummer.", "Üzgünüm. Müşteri numaranızı söyler misiniz?", "number", ["Seit zwei Tagen habe ich kein Internet."])],
        { say: "Worum geht es — Internet, Telefon oder Rechnung?", sayTr: "Konu ne — internet, telefon, fatura?", example: "Seit zwei Tagen habe ich kein Internet." }),
      turn("number", "Ihre Kundennummer, bitte.", "Müşteri numaranız?", "Numarayı söyle (rakam rakam).",
        [reply(["null", "eins", "zwei", "drei", "vier", "fünf", "sechs", "sieben", "acht", "neun", "nummer"], "Danke. Haben Sie den Router schon neu gestartet?", "Teşekkürler. Modemi yeniden başlattınız mı?", "check", [])],
        { say: "Bitte nennen Sie mir die acht Ziffern Ihrer Kundennummer.", sayTr: "Müşteri numaranızın sekiz rakamını söyleyin.", example: "Meine Kundennummer ist vier sieben eins zwei null drei acht fünf." }),
      turn("check", "Haben Sie den Router neu gestartet?", "Modemi yeniden başlattınız mı?", "Zaten denediğini söyle ya da deneyeceğini.",
        [reply(["schon", "versucht", "gemacht", "natürlich", "mehrmals"], "Verstehe. Dann liegt es wohl an der Leitung. Ich kann einen Techniker schicken.", "Anladım. O zaman hat sorunu olmalı. Teknisyen gönderebilirim.", "tech", ["Das habe ich schon versucht."]),
         reply(["nein", "noch nicht", "mache", "jetzt"], "Bitte tun Sie das jetzt und warten Sie zwei Minuten. … Geht es?", "Şimdi yapın ve iki dakika bekleyin. … Oldu mu?", "tech", [])],
        { say: "Haben Sie den Router aus- und wieder eingeschaltet?", sayTr: "Modemi kapatıp açtınız mı?", example: "Das habe ich schon versucht, mehrmals." }),
      turn("tech", "Ich kann einen Techniker schicken. Noch Fragen?", "Teknisyen gönderebilirim. Başka soru?", "Zamanı sor ya da telafi iste.",
        [reply(["wann", "techniker", "kommen", "termin"], "Frühestens übermorgen zwischen 8 und 13 Uhr.", "En erken öbür gün 8–13 arası.", undefined, ["Wann kann ein Techniker kommen?"]),
         reply(["gutschrift", "geld", "erstattung", "rabatt", "entschädigung"], "Ja, für die Ausfalltage schreiben wir Ihnen die Grundgebühr gut.", "Evet, kesinti günleri için temel ücreti iade ederiz.", undefined, ["Bekomme ich eine Gutschrift?"])],
        { say: "Möchten Sie einen Termin für den Techniker oder etwas zur Rechnung wissen?", sayTr: "Teknisyen randevusu mu, fatura konusu mu?", example: "Wann kann ein Techniker kommen? Und bekomme ich eine Gutschrift?" }),
    ],
  },
  {
    id: "b1-d5", level: "B1", skill: "speaking", title: "Elternabend", genre: "Diyalog",
    theme: { role: "Klassenlehrerin beim Elterngespräch", goal: "Çocuğun durumunu anlat (notlar iyi, derse katılım az), velinin sorularını cevapla, evde destek öner, bir sonraki görüşme.", limits: "Çocuk: Emre, 4. sınıf." },
    intro: "Çocuğunun öğretmeniyle veli görüşmesindesin.",
    minutes: 6,
    gloss: [{ de: "die Note", tr: "not", en: "grade" }, { de: "sich melden", tr: "söz almak", en: "to raise one's hand" }, { de: "die Hausaufgaben", tr: "ev ödevi", en: "homework" }, { de: "unterstützen", tr: "desteklemek", en: "to support" }],
    targets: [
      { de: "Wie läuft es bei … in der Schule?", tr: "…'nin okulda durumu nasıl?", en: "How is … doing at school?" },
      { de: "Gibt es Probleme?", tr: "Sorun var mı?", en: "Are there any problems?" },
      { de: "Wie können wir ihn zu Hause unterstützen?", tr: "Onu evde nasıl destekleyebiliriz?", en: "How can we support him at home?" },
      { de: "Vielen Dank für das Gespräch.", tr: "Görüşme için teşekkürler.", en: "Thank you for the meeting." },
    ],
    dialogue: [
      turn("start", "Schön, dass Sie da sind, Frau Kaya. Was möchten Sie wissen?", "Geldiğiniz için teşekkürler, Bayan Kaya. Ne öğrenmek istersiniz?", "Sor: „Wie läuft es bei Emre in der Schule?“",
        [reply(["läuft", "wie", "schule", "emre", "geht"], "Insgesamt gut: Die Noten sind ordentlich. Er meldet sich aber selten.", "Genel olarak iyi: notlar düzgün. Ama nadiren söz alıyor.", "problems", ["Wie läuft es bei … in der Schule?"])],
        { say: "Fragen Sie mich ruhig, wie es Emre in der Schule geht.", sayTr: "Emre'nin okulda nasıl olduğunu sormaktan çekinmeyin.", example: "Wie läuft es bei Emre in der Schule?" }),
      turn("problems", "Er ist sehr still im Unterricht.", "Derste çok sessiz.", "Sorun olup olmadığını sor.",
        [reply(["probleme", "problem", "sorgen", "schlimm", "warum"], "Keine echten Probleme. Er ist nur schüchtern, wenn er vor der Klasse sprechen soll.", "Gerçek bir sorun yok. Sınıf önünde konuşacağında çekingen oluyor.", "support", ["Gibt es Probleme?"]),
         reply(["zu hause", "auch", "ruhig", "still"], "Interessant. In kleinen Gruppen redet er mehr.", "İlginç. Küçük gruplarda daha çok konuşuyor.", "support", [])],
        { say: "Möchten Sie wissen, ob es Probleme gibt?", sayTr: "Sorun olup olmadığını mı sormak istiyorsunuz?", example: "Gibt es Probleme im Unterricht?" }),
      turn("support", "Er braucht ein bisschen Mut.", "Biraz cesarete ihtiyacı var.", "Evde nasıl destekleyeceğini sor.",
        [reply(["unterstützen", "helfen", "zu hause", "wie können", "tun"], "Lassen Sie ihn zu Hause laut vorlesen und Fragen stellen — zehn Minuten am Tag reichen.", "Evde yüksek sesle okumasını ve soru sormasını sağlayın — günde on dakika yeter.", "end", ["Wie können wir ihn zu Hause unterstützen?"])],
        { say: "Fragen Sie mich, wie Sie ihn zu Hause unterstützen können.", sayTr: "Onu evde nasıl destekleyebileceğinizi sorun.", example: "Wie können wir ihn zu Hause unterstützen?" }),
      turn("end", "Sollen wir in zwei Monaten noch einmal sprechen?", "İki ay sonra tekrar görüşelim mi?", "Kabul et ve teşekkür et.",
        [reply(["ja", "gern", "danke", "gespräch", "zwei monaten"], "Sehr gern. Vielen Dank, dass Sie gekommen sind.", "Memnuniyetle. Geldiğiniz için teşekkürler.", undefined, ["Vielen Dank für das Gespräch."])],
        { say: "Passt Ihnen ein Termin in zwei Monaten?", sayTr: "İki ay sonra bir görüşme uyar mı?", example: "Ja, gern. Vielen Dank für das Gespräch." }),
    ],
  },

  // ── B2 ──
  {
    id: "b2-d2", level: "B2", skill: "speaking", title: "Gehaltsverhandlung", genre: "Diyalog",
    theme: { role: "Abteilungsleiterin im Jahresgespräch", goal: "Performansı değerlendir, maaş talebini gerekçe iste, karşı teklif yap, ek yan haklar öner, anlaşmayı özetle.", limits: "Bütçe en fazla %6 artış; alternatif: fazladan izin günü, eğitim bütçesi." },
    intro: "Yıllık görüşmede maaş artışı istiyorsun. Gerekçelerini sun, karşı teklifle başa çık.",
    minutes: 7,
    gloss: [{ de: "die Gehaltserhöhung", tr: "maaş artışı", en: "pay rise" }, { de: "die Verantwortung übernehmen", tr: "sorumluluk üstlenmek", en: "to take on responsibility" }, { de: "der Gegenvorschlag", tr: "karşı teklif", en: "counteroffer" }, { de: "die Weiterbildung", tr: "ileri eğitim", en: "further training" }],
    targets: [
      { de: "Ich möchte über mein Gehalt sprechen.", tr: "Maaşım hakkında konuşmak istiyorum.", en: "I'd like to talk about my salary." },
      { de: "Im letzten Jahr habe ich … übernommen.", tr: "Geçen yıl … üstlendim.", en: "Last year I took on …" },
      { de: "Ich stelle mir … vor.", tr: "… düşünüyorum (talep).", en: "I have … in mind." },
      { de: "Könnten wir uns auf … einigen?", tr: "… üzerinde anlaşabilir miyiz?", en: "Could we agree on …?" },
    ],
    dialogue: [
      turn("start", "Schön, dass wir uns Zeit nehmen. Was liegt Ihnen am Herzen?", "Vakit ayırdığımıza sevindim. Aklınızda ne var?", "Konuyu aç: „Ich möchte über mein Gehalt sprechen.“",
        [reply(["gehalt", "sprechen", "erhöhung", "lohn"], "Verstehe. Womit begründen Sie Ihren Wunsch?", "Anlıyorum. Talebinizi neyle gerekçelendiriyorsunuz?", "reason", ["Ich möchte über mein Gehalt sprechen."])],
        { say: "Geht es um Ihre Aufgaben oder um das Gehalt?", sayTr: "Görevleriniz mi, maaş mı?", example: "Ich möchte über mein Gehalt sprechen." }),
      turn("reason", "Womit begründen Sie das?", "Gerekçeniz ne?", "Somut başarı söyle: „Im letzten Jahr habe ich das Projekt X übernommen.“",
        [reply(["übernommen", "projekt", "verantwortung", "letzten jahr", "erfolgreich", "kunden"], "Das stimmt, das war stark. Welche Zahl stellen Sie sich vor?", "Doğru, güçlüydü. Hangi rakamı düşünüyorsunuz?", "number", ["Im letzten Jahr habe ich … übernommen."])],
        { say: "Nennen Sie mir bitte ein konkretes Beispiel aus dem letzten Jahr.", sayTr: "Geçen yıldan somut bir örnek verin.", example: "Im letzten Jahr habe ich die Leitung des Kundenprojekts übernommen." }),
      turn("number", "Welche Zahl stellen Sie sich vor?", "Hangi rakam?", "Talebini söyle: „Ich stelle mir zehn Prozent mehr vor.“",
        [reply(["prozent", "euro", "stelle mir", "vor", "mehr"], "Zehn Prozent sind in diesem Jahr nicht drin. Ich kann Ihnen sechs Prozent anbieten.", "Yüzde on bu yıl mümkün değil. Yüzde altı teklif edebilirim.", "counter", ["Ich stelle mir … vor."])],
        { say: "Sagen Sie mir eine konkrete Zahl.", sayTr: "Somut bir rakam söyleyin.", example: "Ich stelle mir zehn Prozent mehr vor." }),
      turn("counter", "Sechs Prozent — wie klingt das?", "Yüzde altı — nasıl?", "Anlaşma öner: „Könnten wir uns auf … einigen?“ ya da yan hak iste.",
        [reply(["einigen", "könnten wir", "acht", "sieben", "kompromiss"], "Sieben Prozent plus zwei zusätzliche Urlaubstage — damit kann ich leben. Einverstanden?", "Yüzde yedi artı iki ek izin günü — bununla yaşayabilirim. Anlaştık mı?", undefined, ["Könnten wir uns auf … einigen?"]),
         reply(["weiterbildung", "urlaub", "urlaubstage", "homeoffice", "zusätzlich"], "Das lässt sich machen: sechs Prozent plus ein Weiterbildungsbudget von 1.500 Euro.", "Olabilir: yüzde altı artı 1.500 euro eğitim bütçesi.", undefined, ["Könnten wir uns auf … einigen?"])],
        { say: "Nehmen Sie die sechs Prozent, oder haben Sie einen Gegenvorschlag?", sayTr: "Yüzde altıyı kabul mü, karşı teklif mi?", example: "Könnten wir uns auf acht Prozent einigen?" }),
    ],
  },
  {
    id: "b2-d3", level: "B2", skill: "speaking", title: "Konflikt mit dem Nachbarn", genre: "Diyalog",
    theme: { role: "Nachbar, der nachts laute Musik hört", goal: "Şikâyeti savun ama uzlaşmaya açık ol; öğrenci sorunu nazikçe dile getirsin, sınır koysun, çözüm önersin.", limits: "Komşu başta savunmacı, sonra ikna olur." },
    intro: "Komşun gece geç saatte yüksek sesle müzik dinliyor. Konuyu nazikçe ama net konuş.",
    minutes: 6,
    gloss: [{ de: "die Nachtruhe", tr: "gece sessizliği", en: "quiet hours" }, { de: "sich beschweren", tr: "şikâyet etmek", en: "to complain" }, { de: "der Kompromiss", tr: "uzlaşma", en: "compromise" }, { de: "Rücksicht nehmen", tr: "saygı göstermek", en: "to be considerate" }],
    targets: [
      { de: "Ich wollte Sie auf etwas ansprechen.", tr: "Sizinle bir konuyu konuşmak istedim.", en: "I wanted to bring something up." },
      { de: "Es stört mich, wenn …", tr: "… beni rahatsız ediyor.", en: "It bothers me when …" },
      { de: "Ich hätte einen Vorschlag.", tr: "Bir önerim var.", en: "I have a suggestion." },
      { de: "Können wir uns darauf einigen, dass …?", tr: "… konusunda anlaşabilir miyiz?", en: "Can we agree that …?" },
    ],
    dialogue: [
      turn("start", "Ah, hallo! Wollten Sie etwas?", "Ah, merhaba! Bir şey mi istediniz?", "Konuyu nazikçe aç.",
        [reply(["ansprechen", "sprechen", "musik", "laut", "nacht", "stört"], "Die Musik? Ich habe die Musik gar nicht so laut gehört…", "Müzik mi? O kadar yüksek değildi ki…", "explain", ["Ich wollte Sie auf etwas ansprechen."])],
        { say: "Gibt es ein Problem?", sayTr: "Bir sorun mu var?", example: "Ich wollte Sie auf etwas ansprechen: die Musik nachts." }),
      turn("explain", "So laut war das doch nicht, oder?", "O kadar yüksek değildi, değil mi?", "Rahatsızlığı somut anlat: „Es stört mich, wenn …“",
        [reply(["stört", "wenn", "schlafen", "uhr", "nach", "kinder", "arbeite"], "Okay, das verstehe ich. Ich wusste nicht, dass die Wände so dünn sind.", "Tamam, anlıyorum. Duvarların bu kadar ince olduğunu bilmiyordum.", "proposal", ["Es stört mich, wenn …"])],
        { say: "Erklären Sie mir bitte, was genau stört.", sayTr: "Tam olarak neyin rahatsız ettiğini anlatın.", example: "Es stört mich, wenn nach 23 Uhr noch Musik läuft — ich muss früh aufstehen." }),
      turn("proposal", "Was schlagen Sie vor?", "Ne öneriyorsunuz?", "Öneri sun: „Ich hätte einen Vorschlag: …“",
        [reply(["vorschlag", "22", "23", "leiser", "kopfhörer", "wochenende", "bis"], "Das klingt fair. Unter der Woche ab 22 Uhr leise, am Wochenende bis 24 Uhr?", "Adil. Hafta içi 22'den sonra sessiz, hafta sonu 24'e kadar?", "agree", ["Ich hätte einen Vorschlag."])],
        { say: "Haben Sie einen konkreten Vorschlag?", sayTr: "Somut bir öneriniz var mı?", example: "Ich hätte einen Vorschlag: unter der Woche ab 22 Uhr leise." }),
      turn("agree", "Können wir das so machen?", "Böyle yapabilir miyiz?", "Anlaşmayı onayla.",
        [reply(["einigen", "einverstanden", "gut", "ja", "danke", "abgemacht"], "Abgemacht. Und sagen Sie mir direkt Bescheid, wenn es wieder zu laut ist.", "Anlaştık. Yine yüksek olursa doğrudan söyleyin.", undefined, ["Können wir uns darauf einigen, dass …?"])],
        { say: "Sind Sie damit einverstanden?", sayTr: "Bununla mutabık mısınız?", example: "Können wir uns darauf einigen, dass es unter der Woche ab 22 Uhr ruhig ist?" }),
    ],
  },
  {
    id: "b2-d4", level: "B2", skill: "speaking", title: "Arztgespräch: Diagnose verstehen", genre: "Diyalog",
    theme: { role: "Hausärztin, die Untersuchungsergebnisse erklärt", goal: "Tahlil sonucunu (yüksek tansiyon) anlat, yaşam tarzı ve ilaç seçeneklerini sun, hastanın sorularına açık cevap ver, kontrol randevusu.", limits: "Ciddi tanı yok; ilaç düşük doz." },
    intro: "Tahlil sonuçlarını dinliyorsun. Anlamadığını sor, seçenekleri tart.",
    minutes: 6,
    gloss: [{ de: "der Blutdruck", tr: "tansiyon", en: "blood pressure" }, { de: "die Nebenwirkung", tr: "yan etki", en: "side effect" }, { de: "die Ernährung umstellen", tr: "beslenmeyi değiştirmek", en: "to change one's diet" }, { de: "die Kontrolle", tr: "kontrol", en: "check-up" }],
    targets: [
      { de: "Was bedeutet das genau?", tr: "Bu tam olarak ne demek?", en: "What exactly does that mean?" },
      { de: "Welche Möglichkeiten gibt es?", tr: "Hangi seçenekler var?", en: "What options are there?" },
      { de: "Gibt es Nebenwirkungen?", tr: "Yan etkisi var mı?", en: "Are there side effects?" },
      { de: "Ich würde es zuerst ohne Medikamente versuchen.", tr: "Önce ilaçsız denemek isterim.", en: "I'd like to try without medication first." },
    ],
    dialogue: [
      turn("start", "Ihre Werte sind da. Der Blutdruck ist leicht erhöht.", "Değerleriniz geldi. Tansiyon hafif yüksek.", "Ne anlama geldiğini sor.",
        [reply(["bedeutet", "heißt", "genau", "schlimm", "gefährlich"], "Nicht gefährlich, aber ein Warnsignal: Auf Dauer belastet das Herz und Gefäße.", "Tehlikeli değil ama uyarı: uzun vadede kalbi ve damarları yorar.", "options", ["Was bedeutet das genau?"])],
        { say: "Möchten Sie wissen, was das bedeutet?", sayTr: "Ne anlama geldiğini öğrenmek ister misiniz?", example: "Was bedeutet das genau?" }),
      turn("options", "Wir sollten etwas tun.", "Bir şey yapmalıyız.", "Seçenekleri sor.",
        [reply(["möglichkeiten", "optionen", "was kann", "tun", "behandlung"], "Zwei Wege: Lebensstil — weniger Salz, mehr Bewegung — oder ein niedrig dosiertes Medikament.", "İki yol: yaşam tarzı — az tuz, çok hareket — ya da düşük dozlu bir ilaç.", "side", ["Welche Möglichkeiten gibt es?"])],
        { say: "Fragen Sie mich nach den Möglichkeiten.", sayTr: "Seçenekleri sorun.", example: "Welche Möglichkeiten gibt es?" }),
      turn("side", "Beides ist möglich.", "İkisi de mümkün.", "Yan etkileri sor ya da tercihini söyle.",
        [reply(["nebenwirkungen", "nebenwirkung", "risiko", "vertragen"], "Selten: Müdigkeit oder Schwindel in den ersten Wochen. Meist gut verträglich.", "Nadiren: ilk haftalarda yorgunluk ya da baş dönmesi. Genelde iyi tolere edilir.", "decision", ["Gibt es Nebenwirkungen?"]),
         reply(["ohne", "zuerst", "versuchen", "lebensstil", "bewegung"], "Das finde ich vernünftig. Wir kontrollieren in drei Monaten.", "Bunu mantıklı buluyorum. Üç ay sonra kontrol ederiz.", undefined, ["Ich würde es zuerst ohne Medikamente versuchen."])],
        { say: "Haben Sie Fragen zu den Nebenwirkungen, oder möchten Sie sich entscheiden?", sayTr: "Yan etkiler hakkında soru mu, karar mı?", example: "Gibt es Nebenwirkungen?" }),
      turn("decision", "Wie möchten Sie vorgehen?", "Nasıl ilerlemek istersiniz?", "Karar ver.",
        [reply(["ohne", "zuerst", "versuchen", "lebensstil", "medikamente"], "Gut. Dann sehen wir uns in drei Monaten zur Kontrolle.", "Peki. Üç ay sonra kontrolde görüşürüz.", undefined, ["Ich würde es zuerst ohne Medikamente versuchen."]),
         reply(["medikament", "tablette", "nehmen", "lieber"], "In Ordnung, ich stelle ein Rezept aus. Kontrolle in sechs Wochen.", "Tamam, reçete yazıyorum. Altı hafta sonra kontrol.", undefined, [])],
        { say: "Ohne Medikamente versuchen oder mit?", sayTr: "İlaçsız mı deneyeceksiniz, ilaçla mı?", example: "Ich würde es zuerst ohne Medikamente versuchen." }),
    ],
  },

  // ── C1 ──
  {
    id: "c1-d2", level: "C1", skill: "speaking", title: "Podiumsdiskussion: Homeoffice-Pflicht?", genre: "Diyalog",
    theme: { role: "Moderator einer Podiumsdiskussion", goal: "Tezi sor, karşı argümanla sına, kaynak/örnek iste, nüans talep et, kapanış cümlesi iste.", limits: "Konu: 'Şirketler haftada iki gün evden çalışmayı zorunlu tutmalı mı?'" },
    intro: "Panelde konuşmacısın. Moderatör seni sıkıştırıyor; tezini savun ve nüans göster.",
    minutes: 7,
    gloss: [{ de: "die These", tr: "tez", en: "thesis" }, { de: "der Einwand", tr: "itiraz", en: "objection" }, { de: "belegen", tr: "kanıtlamak", en: "to substantiate" }, { de: "differenzieren", tr: "ayrım yapmak", en: "to differentiate" }],
    targets: [
      { de: "Ich vertrete die Auffassung, dass …", tr: "… görüşünü savunuyorum.", en: "I hold the view that …" },
      { de: "Dem Einwand lässt sich entgegenhalten, dass …", tr: "Bu itiraza karşı …", en: "One can counter that objection by …" },
      { de: "Ein Beleg dafür ist …", tr: "Buna kanıt …", en: "Evidence for this is …" },
      { de: "Man muss allerdings differenzieren: …", tr: "Ancak ayrım yapmak gerek: …", en: "However, one must differentiate: …" },
    ],
    dialogue: [
      turn("start", "Frau Kaya, Sie sind für eine Homeoffice-Pflicht. Warum?", "Bayan Kaya, siz evden çalışma zorunluluğundan yanasınız. Neden?", "Tezini kur: „Ich vertrete die Auffassung, dass …“",
        [reply(["auffassung", "vertrete", "meinung", "weil", "pflicht", "dafür"], "Kritiker sagen, das zerstöre die Teamkultur. Was entgegnen Sie?", "Eleştirmenler bunun takım kültürünü yok ettiğini söylüyor. Ne cevap verirsiniz?", "objection", ["Ich vertrete die Auffassung, dass …"])],
        { say: "Formulieren Sie bitte Ihre These in einem Satz.", sayTr: "Tezinizi tek cümlede söyleyin.", example: "Ich vertrete die Auffassung, dass zwei Homeoffice-Tage die Produktivität erhöhen." }),
      turn("objection", "Was entgegnen Sie dem Einwand mit der Teamkultur?", "Takım kültürü itirazına cevabınız?", "Karşı çık: „Dem Einwand lässt sich entgegenhalten, dass …“",
        [reply(["entgegenhalten", "einwand", "gegenteil", "allerdings", "stimmt nicht", "vielmehr"], "Haben Sie dafür Belege, oder ist das Ihre Erfahrung?", "Bunun kanıtı var mı, yoksa kişisel deneyim mi?", "evidence", ["Dem Einwand lässt sich entgegenhalten, dass …"])],
        { say: "Bitte antworten Sie direkt auf den Einwand.", sayTr: "Lütfen itiraza doğrudan cevap verin.", example: "Dem Einwand lässt sich entgegenhalten, dass Teamkultur von festen Bürotagen lebt, nicht von fünf." }),
      turn("evidence", "Haben Sie Belege?", "Kanıtınız var mı?", "Kanıt ver: „Ein Beleg dafür ist …“",
        [reply(["beleg", "studie", "zahlen", "beispiel", "daten", "prozent", "untersuchung"], "Interessant. Gilt das aber für alle Branchen gleichermaßen?", "İlginç. Peki bu her sektör için aynı derecede geçerli mi?", "nuance", ["Ein Beleg dafür ist …"])],
        { say: "Nennen Sie bitte eine Studie oder ein Beispiel.", sayTr: "Bir çalışma ya da örnek verin.", example: "Ein Beleg dafür ist eine Stanford-Studie, nach der hybride Teams seltener kündigen." }),
      turn("nuance", "Gilt das für alle Branchen?", "Her sektör için mi?", "Nüans yap: „Man muss allerdings differenzieren: …“",
        [reply(["differenzieren", "allerdings", "nicht für alle", "kommt darauf an", "branche", "unterschied"], "Ein guter Schlusspunkt. Vielen Dank, Frau Kaya.", "İyi bir kapanış. Teşekkürler, Bayan Kaya.", undefined, ["Man muss allerdings differenzieren: …"])],
        { say: "Bitte differenzieren Sie: Für wen gilt Ihre These, für wen nicht?", sayTr: "Ayrım yapın: teziniz kimin için geçerli, kimin için değil?", example: "Man muss allerdings differenzieren: In der Pflege ist Homeoffice schlicht unmöglich." }),
    ],
  },
  {
    id: "c1-d3", level: "C1", skill: "speaking", title: "Bewerbungsgespräch für eine Führungsposition", genre: "Diyalog",
    theme: { role: "Geschäftsführerin im zweiten Bewerbungsgespräch", goal: "Liderlik anlayışını, bir başarısızlık örneğini ve çatışma yönetimini sor; cevaplarda somutluk iste; adayın sorularına cevap ver.", limits: "Pozisyon: 8 kişilik ekibin lideri." },
    intro: "İkinci tur görüşmedesin: takım lideri pozisyonu. Somut örneklerle konuş.",
    minutes: 7,
    gloss: [{ de: "der Führungsstil", tr: "liderlik tarzı", en: "leadership style" }, { de: "scheitern", tr: "başarısız olmak", en: "to fail" }, { de: "die Lehre ziehen", tr: "ders çıkarmak", en: "to learn a lesson" }, { de: "den Konflikt moderieren", tr: "çatışmayı yönetmek", en: "to mediate a conflict" }],
    targets: [
      { de: "Mein Führungsstil lässt sich als … beschreiben.", tr: "Liderlik tarzım … olarak tanımlanabilir.", en: "My leadership style can be described as …" },
      { de: "Ein Beispiel, in dem ich gescheitert bin, …", tr: "Başarısız olduğum bir örnek …", en: "An example where I failed …" },
      { de: "Daraus habe ich die Lehre gezogen, dass …", tr: "Bundan … dersini çıkardım.", en: "From that I learned that …" },
      { de: "Ich hätte noch eine Frage zu …", tr: "… hakkında bir sorum var.", en: "I have a question about …" },
    ],
    dialogue: [
      turn("start", "Willkommen zur zweiten Runde. Wie würden Sie Ihren Führungsstil beschreiben?", "İkinci tura hoş geldiniz. Liderlik tarzınızı nasıl tanımlarsınız?", "Tarzını tanımla ve bir örnekle destekle.",
        [reply(["führungsstil", "beschreiben", "kooperativ", "situativ", "vertrauen", "klar"], "Und wie sieht das konkret aus — nennen Sie mir eine Situation.", "Somut olarak nasıl — bir durum anlatın.", "fail", ["Mein Führungsstil lässt sich als … beschreiben."])],
        { say: "Beschreiben Sie bitte Ihren Führungsstil.", sayTr: "Liderlik tarzınızı tanımlayın.", example: "Mein Führungsstil lässt sich als kooperativ mit klaren Zielen beschreiben." }),
      turn("fail", "Erzählen Sie mir von einem Projekt, das nicht gut lief.", "İyi gitmeyen bir projeden bahsedin.", "Başarısızlık örneği ver.",
        [reply(["gescheitert", "beispiel", "nicht gut", "fehler", "problem", "verzögert"], "Und was haben Sie daraus gelernt?", "Ondan ne öğrendiniz?", "lesson", ["Ein Beispiel, in dem ich gescheitert bin, …"])],
        { say: "Nennen Sie bitte ein konkretes Beispiel für einen Misserfolg.", sayTr: "Somut bir başarısızlık örneği verin.", example: "Ein Beispiel, in dem ich gescheitert bin, war eine Software-Einführung ohne Schulung." }),
      turn("lesson", "Was haben Sie daraus gelernt?", "Ne ders çıkardınız?", "Dersi söyle.",
        [reply(["lehre", "gelernt", "daraus", "seitdem", "heute"], "Das klingt reflektiert. Wie gehen Sie mit Konflikten im Team um?", "Düşünülmüş bir cevap. Ekipteki çatışmalarla nasıl başa çıkarsınız?", "conflict", ["Daraus habe ich die Lehre gezogen, dass …"])],
        { say: "Welche Lehre haben Sie gezogen?", sayTr: "Hangi dersi çıkardınız?", example: "Daraus habe ich die Lehre gezogen, dass Veränderung ohne Beteiligung scheitert." }),
      turn("conflict", "Wie moderieren Sie Konflikte? Und haben Sie Fragen an uns?", "Çatışmaları nasıl yönetirsiniz? Bize sorunuz var mı?", "Yaklaşımını anlat ve bir soru sor.",
        [reply(["frage", "hätte noch", "wie ist", "team", "erwartungen", "einarbeitung"], "Gute Frage — das Team ist gemischt erfahren, und die Einarbeitung dauert drei Monate. Vielen Dank für das Gespräch.", "İyi soru — ekip karışık deneyimli, oryantasyon üç ay. Görüşme için teşekkürler.", undefined, ["Ich hätte noch eine Frage zu …"]),
         reply(["konflikt", "gespräch", "moderieren", "zuhören", "beide", "lösung"], "Danke. Haben Sie noch Fragen an uns?", "Teşekkürler. Bize sorunuz var mı?", undefined, [])],
        { say: "Beschreiben Sie Ihren Umgang mit Konflikten oder stellen Sie eine Frage.", sayTr: "Çatışma yaklaşımınızı anlatın ya da bir soru sorun.", example: "Ich hätte noch eine Frage zu den Erwartungen in den ersten hundert Tagen." }),
    ],
  },
  {
    id: "c1-d4", level: "C1", skill: "speaking", title: "Beratungsgespräch bei der Bank", genre: "Diyalog",
    theme: { role: "Bankberaterin für Baufinanzierung", goal: "Kredi ihtiyacını sor, faiz/sabit dönem/aylık taksit açıkla, riskleri belirt, adayın karşı sorularına ve pazarlığına cevap ver.", limits: "Faiz %3,6, sabit 10 yıl; öz kaynak en az %20." },
    intro: "Ev kredisi için bankadasın. Koşulları sorgula, riskleri anla, pazarlık et.",
    minutes: 7,
    gloss: [{ de: "der Zinssatz", tr: "faiz oranı", en: "interest rate" }, { de: "die Zinsbindung", tr: "sabit faiz dönemi", en: "fixed-rate period" }, { de: "das Eigenkapital", tr: "öz kaynak", en: "equity" }, { de: "die Sondertilgung", tr: "ara ödeme", en: "extra repayment" }],
    targets: [
      { de: "Wie hoch wäre der Zinssatz bei …?", tr: "… için faiz ne olur?", en: "What would the interest rate be for …?" },
      { de: "Welche Risiken sehen Sie?", tr: "Hangi riskleri görüyorsunuz?", en: "What risks do you see?" },
      { de: "Wäre eine Sondertilgung möglich?", tr: "Ara ödeme mümkün mü?", en: "Would extra repayments be possible?" },
      { de: "Könnten Sie mir das schriftlich geben?", tr: "Bunu yazılı verebilir misiniz?", en: "Could you give me that in writing?" },
    ],
    dialogue: [
      turn("start", "Guten Tag. Sie interessieren sich für eine Baufinanzierung — um welche Summe geht es?", "İyi günler. Konut kredisi — hangi tutar?", "Tutarı söyle ve faizi sor.",
        [reply(["zinssatz", "zins", "wie hoch", "euro", "tausend", "summe"], "Bei 300.000 Euro und zehn Jahren Zinsbindung liegen wir bei 3,6 Prozent.", "300.000 euro ve on yıl sabit dönemde yüzde 3,6.", "risk", ["Wie hoch wäre der Zinssatz bei …?"])],
        { say: "Nennen Sie mir bitte die Summe.", sayTr: "Tutarı söyleyin.", example: "Wie hoch wäre der Zinssatz bei 300.000 Euro?" }),
      turn("risk", "Die Rate läge bei etwa 1.450 Euro im Monat.", "Taksit ayda yaklaşık 1.450 euro.", "Riskleri sor.",
        [reply(["risiken", "risiko", "gefahr", "was passiert", "nach zehn"], "Das Hauptrisiko: Nach der Zinsbindung kann der Zins deutlich höher sein. Deshalb empfehle ich hohe Tilgung.", "Ana risk: sabit dönem bitince faiz çok daha yüksek olabilir. Bu yüzden yüksek anapara ödemesi öneririm.", "special", ["Welche Risiken sehen Sie?"])],
        { say: "Fragen Sie mich ruhig nach den Risiken.", sayTr: "Riskleri sormaktan çekinmeyin.", example: "Welche Risiken sehen Sie bei dieser Finanzierung?" }),
      turn("special", "Hohe Tilgung senkt das Risiko.", "Yüksek anapara ödemesi riski düşürür.", "Ara ödeme sor ya da pazarlık yap.",
        [reply(["sondertilgung", "sonderzahlung", "früher zurückzahlen", "zusätzlich"], "Ja, bis zu fünf Prozent der Summe pro Jahr kostenlos.", "Evet, yılda tutarın yüzde beşine kadar ücretsiz.", "written", ["Wäre eine Sondertilgung möglich?"]),
         reply(["niedriger", "verhandeln", "besser", "konkurrenz", "angebot"], "Mit 25 Prozent Eigenkapital könnte ich 3,4 Prozent anbieten.", "Yüzde 25 öz kaynakla yüzde 3,4 teklif edebilirim.", "written", [])],
        { say: "Möchten Sie etwas zur Sondertilgung wissen oder über den Zins verhandeln?", sayTr: "Ara ödeme mi, faiz pazarlığı mı?", example: "Wäre eine Sondertilgung möglich?" }),
      turn("written", "Möchten Sie das Angebot mitnehmen?", "Teklifi götürmek ister misiniz?", "Yazılı iste.",
        [reply(["schriftlich", "angebot", "mitnehmen", "e-mail", "unterlagen"], "Selbstverständlich. Ich schicke Ihnen das Angebot heute per E-Mail.", "Elbette. Teklifi bugün e-postayla gönderiyorum.", undefined, ["Könnten Sie mir das schriftlich geben?"])],
        { say: "Soll ich Ihnen das Angebot schriftlich geben?", sayTr: "Teklifi yazılı vereyim mi?", example: "Könnten Sie mir das bitte schriftlich geben?" }),
    ],
  },
];
