import type { SpeakingDrillExercise, SpeakingTask } from "../types";

/** Telaffuz drilleri, ikinci küme — B1/B2/C1 (WP-72 / WP-21 adım 2). Biçim `speaking-2a.ts` ile aynı. */
const t = (de: string, tr: string, hint: string, heard?: string[], fix?: string, expected?: string): SpeakingTask => ({
  de,
  tr,
  hint,
  ...(heard && fix ? { confusions: [{ heard, fix, expected }] } : {}),
});

const drill = (
  id: string,
  level: SpeakingDrillExercise["level"],
  title: string,
  intro: string,
  gloss: { de: string; tr: string }[],
  tasks: SpeakingTask[],
): SpeakingDrillExercise => ({ id, level, skill: "speaking", title, genre: "Ses çalışması", intro, gloss, minutes: 5, tasks });

export const speaking2b: SpeakingDrillExercise[] = [
  // ── B1 ──
  drill("b1-p1", "B1", "Das „-ig“ am Ende", "Sondaki „-ig“ standart Almancada „-ich“ okunur: König = KÖÖ-nih, wichtig = VİH-tih. Sert g ya da k okumak Güney lehçesi; ölçüm standarda göre.",
    [{ de: "wichtig", tr: "önemli" }, { de: "der König", tr: "kral" }, { de: "billig", tr: "ucuz" }],
    [
      t("Das ist sehr wichtig.", "Bu çok önemli.", "„wichtig“: VİH-tih, iki yumuşak ch.", ["wichtik", "Wichtig"], "„wichtig“ sonundaki -ig yumuşak ch: -tih.", "wichtig"),
      t("Der König ist alt.", "Kral yaşlı.", "„König“: KÖÖ-nih.", ["Könik", "Könige"], "„König“ sonunda -ih, k değil.", "König"),
      t("Das Hotel ist billig.", "Otel ucuz.", "„billig“: Bİ-lih.", ["Bild", "Billig"], "„billig“ sonundaki -ig: -ih.", "billig"),
      t("Es ist ruhig hier.", "Burası sakin.", "„ruhig“: RUU-ih.", ["Ruhe", "ruhige"], "„ruhig“: uzun u, sonda yumuşak -ih.", "ruhig"),
      t("Die Königin lächelt.", "Kraliçe gülümsüyor.", "„Königin“: KÖÖ-ni-gin — ünlü gelince g yeniden g!", ["Könichin", "König"], "„Königin“de -ig arkasına ünlü geldiği için g okunur.", "Königin"),
    ]),
  drill("b1-p2", "B1", "„chs“, „ck“ und kurze Vokale", "„chs“ ks okunur (sechs, Fuchs); „ck“ önündeki ünlüyü kısaltır (Ecke, Zucker). Türkçe konuşan „ch“ görünce h/ş yapıyor, „ck“de ünlüyü uzatıyor.",
    [{ de: "der Fuchs", tr: "tilki" }, { de: "die Ecke", tr: "köşe" }, { de: "wachsen", tr: "büyümek" }],
    [
      t("Der Fuchs läuft schnell.", "Tilki hızlı koşuyor.", "„Fuchs“: FUKS.", ["Fuß", "Fuchse"], "„Fuchs“te chs = ks: FUKS.", "Fuchs"),
      t("Das Café ist an der Ecke.", "Kafe köşede.", "„Ecke“: EK-kı, e KISA.", ["Ehe", "Eke"], "„Ecke“de e kısa, ck sert.", "Ecke"),
      t("Die Kinder wachsen schnell.", "Çocuklar hızlı büyüyor.", "„wachsen“: VAK-sen.", ["waschen", "wachen"], "„wachsen“ (büyümek) yerine „waschen“ (yıkamak) duyuldu: chs = ks.", "wachsen"),
      t("Ich nehme Zucker.", "Şeker alıyorum.", "„Zucker“: TSU-ka, u kısa.", ["Zuker", "suchen"], "„Zucker“: z = ts, u kısa, ck sert.", "Zucker"),
      t("Der Wechsel ist einfach.", "Değişim kolay.", "„Wechsel“: VEK-sel.", ["Weschel", "wechseln"], "„Wechsel“de chs = ks.", "Wechsel"),
    ]),
  drill("b1-p3", "B1", "Vokalisiertes „r“", "Sondaki „-er“ ve ünlüden sonraki „r“ ünlüye dönüşür: der = DEA, wer = VEA, Uhr = UUA. Dil ucuyla r söylemek anlaşılır ama Türkçe aksanın en belirgin izidir.",
    [{ de: "der Lehrer", tr: "öğretmen" }, { de: "die Uhr", tr: "saat" }, { de: "hier", tr: "burada" }],
    [
      t("Der Lehrer ist nett.", "Öğretmen nazik.", "„Lehrer“: LEE-ra — sondaki -er hafif a.", ["Lehre", "leerer"], "„Lehrer“ sonundaki -er: ünlü gibi, r titremez.", "Lehrer"),
      t("Es ist vier Uhr.", "Saat dört.", "„vier“: FİİA; „Uhr“: UUA.", ["Ur", "für"], "„Uhr“da r ünlüleşir: UUA.", "Uhr"),
      t("Wer ist das?", "Bu kim?", "„wer“: VEA.", ["wir", "Wehr"], "„wer“ (kim) yerine „wir“ (biz) duyuldu: e açık ve uzun.", "wer"),
      t("Meine Mutter arbeitet hier.", "Annem burada çalışıyor.", "„Mutter“: MU-ta; „hier“: HİİA.", ["Mutti", "Mütter"], "„Mutter“ sonundaki -er a gibi; u düz.", "Mutter"),
      t("Das Wetter wird besser.", "Hava düzeliyor.", "„Wetter“, „besser“: -er = a; „wird“: VİAT.", ["Weder", "Wette"], "„Wetter“ sonundaki -er: VE-ta.", "Wetter"),
    ]),
  drill("b1-p4", "B1", "„-tion“ und „-ssion“", "„-tion“ TSİON okunur (Information = in-for-ma-TSİON), vurgu sonda. Türkçe „-syon“ alışkanlığı „ş“ yaptırıyor; tanıyıcı o zaman kelimeyi bulamıyor.",
    [{ de: "die Information", tr: "bilgi" }, { de: "die Station", tr: "durak" }, { de: "die Diskussion", tr: "tartışma" }],
    [
      t("Ich brauche eine Information.", "Bir bilgiye ihtiyacım var.", "„Information“: …ma-TSİOON, vurgu sonda.", ["Informaschon", "Informationen"], "„-tion“ = tsion; ş değil.", "Information"),
      t("Die nächste Station ist Mitte.", "Sonraki durak Mitte.", "„Station“: ŞTA-TSİOON — başta şt, sonda tsion.", ["Stadion", "Stationen"], "„Station“ (durak) yerine „Stadion“ duyuldu: -tsion sonda.", "Station"),
      t("Die Diskussion war lang.", "Tartışma uzundu.", "„Diskussion“: dis-ku-SİOON, ss = s.", ["Diskussionen", "Diskus"], "„Diskussion“ vurgu sonda: -SİOON.", "Diskussion"),
      t("Wir haben eine Lösung.", "Bir çözümümüz var.", "„Lösung“: LÖÖ-zun(g); s ötümlü.", ["Losung", "Lösungen"], "„Lösung“: ö uzun, s z gibi.", "Lösung"),
      t("Die Situation ist schwierig.", "Durum zor.", "„Situation“: zi-tu-a-TSİOON.", ["Situazion", "Situationen"], "„Situation“da dört hece; -tsion sonda vurgulu.", "Situation"),
    ]),
  drill("b1-p5", "B1", "Satzakzent: Was ist neu?", "Cümlede vurgu YENİ bilgiye gider. „Ich fahre MORGEN nach Berlin“ (ne zaman?) ile „Ich fahre morgen nach BERLIN“ (nereye?) farklı soruların cevabıdır. Türkçede sıra değişir, Almancada vurgu.",
    [{ de: "morgen", tr: "yarın" }, { de: "nach Berlin", tr: "Berlin'e" }],
    [
      t("Ich fahre morgen nach Berlin.", "Yarın Berlin'e gidiyorum. (Nereye? → BERLIN vurgulu)", "Vurgu „Berlin“de: sesi orada yükselt, gerisi düz.", ["Ich fahre morgen", "nach Berlin"], "Cümle vurgusu „Berlin“de.", "Berlin"),
      t("Ich fahre morgen nach Berlin.", "Yarın Berlin'e gidiyorum. (Ne zaman? → MORGEN vurgulu)", "Vurgu „morgen“de.", ["Ich fahre nach Berlin", "morgen nach"], "Vurguyu „morgen“e taşı.", "morgen"),
      t("Nicht ich, sondern mein Bruder fährt.", "Ben değil, kardeşim gidiyor.", "Karşıtlık: „ich“ ve „Bruder“ vurgulu.", ["Nicht ich sondern mein Bruder", "mein Bruder fährt"], "Karşıtlık vurgusu: ICH ↔ BRUDER.", "Bruder"),
      t("Das habe ich nicht gesagt.", "Bunu ben söylemedim.", "Vurgu „nicht“te: inkâr.", ["Das habe ich gesagt", "nicht gesagt"], "„nicht“ vurgulu, gerisi düşük.", "nicht"),
      t("Das habe ich nicht gesagt.", "Bunu BEN söylemedim (başkası söyledi).", "Vurgu „ich“te: karşıtlık.", ["Das habe ich nicht gesagt", "ich gesagt"], "Vurguyu „ich“e al: ben değil, bir başkası.", "ich"),
    ]),
  drill("b1-p6", "B1", "„v“ in Fremdwörtern", "Almanca kelimelerde „v“ = f (Vater, viel); yabancı kökenli kelimelerde „v“ = v (Vase, Video, Universität). Hangisi olduğunu kelime söyler.",
    [{ de: "der Vater", tr: "baba" }, { de: "die Vase", tr: "vazo" }, { de: "die Universität", tr: "üniversite" }],
    [
      t("Mein Vater kommt.", "Babam geliyor.", "„Vater“: FAA-ta, v = f.", ["Water", "Vata"], "„Vater“ f ile: FAA-ta.", "Vater"),
      t("Die Vase ist aus Glas.", "Vazo camdan.", "„Vase“: VAA-zı, v = v (yabancı).", ["Fase", "Phase"], "„Vase“ (vazo) yerine „Phase“ duyuldu: burada v = v.", "Vase"),
      t("Sie studiert an der Universität.", "Üniversitede okuyor.", "„Universität“: u-ni-ver-zi-TEET, v = v.", ["Unifersität", "Universitäten"], "„Universität“te v = v, vurgu sonda.", "Universität"),
      t("Ich habe viel Zeit.", "Çok vaktim var.", "„viel“: FİİL, v = f.", ["Wiel", "fiel"], "„viel“ f ile: FİİL.", "viel"),
      t("Das Video ist kurz.", "Video kısa.", "„Video“: Vİ-de-o, v = v.", ["Fideo", "Videos"], "„Video“da v = v.", "Video"),
    ]),
  drill("b1-p7", "B1", "„st“ und „sp“ in der Wortmitte", "Kelime başında „st/sp“ şt/şp; ama kelime ORTASINDA ve sonunda s+t: Fenster = FENS-ta, ist = İST. Baştaki kuralı her yere yaymak Türkçe konuşanın sık hatası.",
    [{ de: "das Fenster", tr: "pencere" }, { de: "die Post", tr: "posta" }, { de: "die Wespe", tr: "yaban arısı" }],
    [
      t("Das Fenster ist offen.", "Pencere açık.", "„Fenster“: FENS-ta — ortada s, ş değil.", ["Fenschter", "Fester"], "„Fenster“ ortasındaki st: s + t, ş yok.", "Fenster"),
      t("Die Post ist da.", "Posta geldi.", "„Post“: POST, sonda s + t.", ["Pošt", "Posten"], "„Post“ sonundaki st sert s ile.", "Post"),
      t("Eine Wespe fliegt hier.", "Burada bir yaban arısı uçuyor.", "„Wespe“: VES-pı, ortada s.", ["Weschpe", "Wesen"], "„Wespe“ ortasındaki sp: s + p.", "Wespe"),
      t("Die Straße ist gesperrt.", "Cadde kapalı.", "„Straße“: ŞTRAA-sı (başta şt!), „gesperrt“: ge-ŞPERT (önekten sonra da şp).", ["Strasse", "gespert"], "„gesperrt“: ge- önekinden sonra kök başı sayılır → şp.", "gesperrt"),
      t("Hast du Lust?", "Canın istiyor mu?", "„Hast“, „Lust“: sonda s + t.", ["Lušt", "Lust"], "„Lust“ sonundaki st: s + t.", "Lust"),
    ]),
  drill("b1-p8", "B1", "Lange „ie“ vs. „i“", "„ie“ ve „ih“ uzun i; tek „i“ kısa. Uzunluk anlam değiştirir: Miete (kira) / Mitte (orta), bieten (sunmak) / bitten (rica etmek).",
    [{ de: "die Miete / die Mitte", tr: "kira / orta" }, { de: "bieten / bitten", tr: "sunmak / rica etmek" }, { de: "das Lied", tr: "şarkı" }],
    [
      t("Die Miete ist hoch.", "Kira yüksek.", "„Miete“: Mİİ-tı, i uzun.", ["Mitte", "Mieter"], "„Miete“ (kira) yerine „Mitte“ (orta) duyuldu: i'yi uzat.", "Miete"),
      t("Wir wohnen in der Mitte.", "Merkezde oturuyoruz.", "„Mitte“: Mİ-tı, i KISA, çift t.", ["Miete", "mit"], "„Mitte“de i kısa; uzatınca „Miete“ oluyor.", "Mitte"),
      t("Ich bitte dich.", "Senden rica ediyorum.", "„bitte“: Bİ-tı, kısa i.", ["biete", "bieten"], "„bitte“ (rica) yerine „biete“ (sunuyorum) duyuldu: i kısa.", "bitte"),
      t("Wir bieten Hilfe an.", "Yardım sunuyoruz.", "„bieten“: Bİİ-ten, uzun i.", ["bitten", "beten"], "„bieten“ (sunmak) yerine „bitten“ (rica etmek) duyuldu: i uzun.", "bieten"),
      t("Das Lied ist schön.", "Şarkı güzel.", "„Lied“: LİİT, uzun i, sondaki d t.", ["litt", "Lid"], "„Lied“ (şarkı) yerine „Lid“ (göz kapağı) duyuldu: i uzun.", "Lied"),
    ]),

  // ── B2 ──
  drill("b2-p1", "B2", "Langes „ä“ vs. „e“", "Standart telaffuzda uzun „ä“ açık e'dir (Käse = KEE-zı, ağız daha açık); „e“ kapalı (Kehle). Çoğu konuşur ikisini birleştirir; tanıyıcı da hoşgörülü — hedef, „ä“yi „a“ yapmamak.",
    [{ de: "der Käse", tr: "peynir" }, { de: "spät", tr: "geç" }, { de: "das Mädchen", tr: "kız" }],
    [
      t("Ich esse gern Käse.", "Peynir yemeyi severim.", "„Käse“: KEE-zı (açık e), KAA değil.", ["Kasse", "Kase"], "„Käse“ (peynir) yerine „Kasse“ (kasa) duyuldu: ä = açık e.", "Käse"),
      t("Es ist schon spät.", "Artık geç.", "„spät“: ŞPEET.", ["Spat", "spat"], "„spät“: ä uzun açık e; a değil.", "spät"),
      t("Wir zählen die Gäste.", "Konukları sayıyoruz.", "„zählen“: TSEE-len; „Gäste“: GES-tı.", ["zahlen", "Zahlen"], "„zählen“ (saymak) yerine „zahlen“ (ödemek) duyuldu: ä = e.", "zählen"),
      t("Die Bäume sind hoch.", "Ağaçlar yüksek.", "„Bäume“: BOY-mı (äu = oy).", ["Baume", "Bauer"], "„Bäume“ (ağaçlar) yerine „Bauer“ duyuldu: äu = oy.", "Bäume"),
      t("Er erzählt eine Geschichte.", "Bir hikâye anlatıyor.", "„erzählt“: ea-TSEELT.", ["erzahlt", "zählt"], "„erzählt“te ä açık e.", "erzählt"),
    ]),
  drill("b2-p2", "B2", "„kn“, „gn“ und „pfl“", "Kelime başındaki ünsüz kümeleri Almancada TAM okunur: Knie = KNİİ (k sessiz değil), Gnade = GNAA-dı, Pflanze = PFLAN-tsı. Türkçe araya ünlü sokar (kınie).",
    [{ de: "das Knie", tr: "diz" }, { de: "die Pflanze", tr: "bitki" }, { de: "der Knopf", tr: "düğme" }],
    [
      t("Mein Knie tut weh.", "Dizim ağrıyor.", "„Knie“: KNİİ — k ve n bitişik, araya ünlü yok.", ["nie", "Nie"], "„Knie“ (diz) yerine „nie“ (asla) duyuldu: baştaki k'yı söyle.", "Knie"),
      t("Die Pflanze braucht Wasser.", "Bitkinin suya ihtiyacı var.", "„Pflanze“: PFLAN-tsı.", ["Flanze", "Pflanzen"], "„Pflanze“ başında pf + l birlikte.", "Pflanze"),
      t("Der Knopf ist ab.", "Düğme koptu.", "„Knopf“: KNOPF.", ["Kopf", "Nopf"], "„Knopf“ (düğme) yerine „Kopf“ (baş) duyuldu: kn kümesi.", "Knopf"),
      t("Wir pflegen die Oma.", "Büyükanneye bakıyoruz.", "„pflegen“: PFLEE-gen.", ["flegen", "fliegen"], "„pflegen“ (bakmak) yerine „fliegen“ (uçmak) duyuldu: pf başta.", "pflegen"),
      t("Das Gnu lebt in Afrika.", "Gnu Afrika'da yaşar.", "„Gnu“: GNUU.", ["Nu", "nur"], "„Gnu“da g sessiz değil.", "Gnu"),
    ]),
  drill("b2-p3", "B2", "Der Glottisschlag", "Almanca ünlüyle başlayan her heceyi küçük bir gırtlak kapanmasıyla ayırır: be|obachten, Ver|ein, er|innern. Türkçe ulama yapar (Ve-rein) — anlaşılır ama sınırlar kaybolur.",
    [{ de: "beobachten", tr: "gözlemlemek" }, { de: "der Verein", tr: "dernek" }, { de: "erinnern", tr: "hatırlamak" }],
    [
      t("Ich beobachte die Vögel.", "Kuşları gözlemliyorum.", "„be|obachte“: be ve o arasında minik duraklama.", ["Bobachte", "beachte"], "„beobachte“ yerine „beachte“ duyuldu: be|o ayrımı.", "beobachte"),
      t("Er ist im Verein.", "O dernekte.", "„Ver|ein“: ver ile ein ayrı.", ["Verrein", "verein"], "„Verein“: ver|ein, r'yi ein'e bağlama.", "Verein"),
      t("Ich erinnere mich.", "Hatırlıyorum.", "„er|innere“: er, sonra kapanma, innere.", ["Erinnere", "innere"], "„erinnere“: er|innere, iki parça.", "erinnere"),
      t("Das ist ein Ereignis.", "Bu bir olay.", "„Er|eignis“: er|aygnis.", ["Reignis", "Ergebnis"], "„Ereignis“: er ile eignis arasında gırtlak duraklaması.", "Ereignis"),
      t("Wir sind am Anfang.", "Başlangıçtayız.", "„am |Anfang“: kelime sınırında kapanma — „ma-manfang“ değil.", ["Manfang", "Amanfang"], "Kelime başındaki ünlüden önce dur: am | Anfang.", "Anfang"),
    ]),
  drill("b2-p4", "B2", "Betonung in Fremdwörtern", "Yabancı kelimelerde vurgu genelde SONDA: MuSİK, KafFEE, StuDENT, IdeE. Türkçe de sona vurgular ama Almancadaki uzun son ünlüyü kısa bırakır.",
    [{ de: "die Musik", tr: "müzik" }, { de: "der Kaffee", tr: "kahve" }, { de: "die Idee", tr: "fikir" }],
    [
      t("Ich höre gern Musik.", "Müzik dinlemeyi severim.", "„Musik“: mu-ZİİK, vurgu ve uzun i sonda.", ["Musik", "Mosaik"], "„Musik“ vurgu sonda, i uzun.", "Musik"),
      t("Ein Kaffee, bitte.", "Bir kahve, lütfen.", "„Kaffee“: KA-fee ya da ka-FEE — ikisi de doğru, e uzun.", ["Kaffe", "Café"], "„Kaffee“ sonundaki ee uzun.", "Kaffee"),
      t("Das ist eine gute Idee.", "Bu iyi bir fikir.", "„Idee“: i-DEE, vurgu ve uzun e sonda.", ["Ide", "Idee"], "„Idee“: vurgu sonda, e uzun.", "Idee"),
      t("Er ist Student.", "O öğrenci.", "„Student“: ştu-DENT.", ["Studenten", "Stunde"], "„Student“ vurgu sonda: -DENT.", "Student"),
      t("Das Hotel ist voll.", "Otel dolu.", "„Hotel“: ho-TEL.", ["Hotel", "Hotels"], "„Hotel“ vurgu sonda.", "Hotel"),
    ]),
  drill("b2-p5", "B2", "Konsonantenhäufung", "Almanca art arda 3–4 ünsüz koyar: Herbst (rbst), du sprichst (chst), Arzt (rtst). Türkçe konuşan araya ünlü sokar ya da birini düşürür.",
    [{ de: "der Herbst", tr: "sonbahar" }, { de: "der Arzt", tr: "doktor" }, { de: "du sprichst", tr: "konuşuyorsun" }],
    [
      t("Im Herbst regnet es.", "Sonbaharda yağmur yağar.", "„Herbst“: HERPST — r-b-s-t art arda, ünlü yok.", ["Herbs", "Herr"], "„Herbst“ sonundaki bst'yi tam söyle.", "Herbst"),
      t("Ich gehe zum Arzt.", "Doktora gidiyorum.", "„Arzt“: ARTST.", ["Art", "Ast"], "„Arzt“ (doktor) yerine „Art“ duyuldu: -tst sonda.", "Arzt"),
      t("Du sprichst gut Deutsch.", "İyi Almanca konuşuyorsun.", "„sprichst“: ŞPRİHST.", ["sprich", "spricht"], "„sprichst“ sonundaki -chst: yumuşak ch + st.", "sprichst"),
      t("Das Obst ist frisch.", "Meyve taze.", "„Obst“: OOPST.", ["Ost", "Obs"], "„Obst“: p + s + t art arda.", "Obst"),
      t("Er ist der Beste.", "O en iyisi.", "„selbst“: ZELPST; „Beste“: BES-tı.", ["Bester", "Besten"], "„Beste“ sonundaki -e'yi ver.", "Beste"),
    ]),
  drill("b2-p6", "B2", "Reduktion: „-en“ und „haben“", "Konuşmada „-en“ eki kısalır: haben → HAABM, sagen → ZAAGN, gehen → GEEN. Bunu anlamak dinleme için şart; söylemek isteğe bağlı ama doğal kılar.",
    [{ de: "haben", tr: "sahip olmak" }, { de: "sagen", tr: "söylemek" }, { de: "wir gehen", tr: "gidiyoruz" }],
    [
      t("Wir haben das gesehen.", "Bunu gördük.", "„haben“: HAABM (b'den sonra e düşer, n dudakta m olur).", ["Habe", "hab"], "„haben“ sonundaki -en kısalabilir ama düşmez.", "haben"),
      t("Was willst du sagen?", "Ne demek istiyorsun?", "„sagen“: ZAAGN.", ["sag", "Sage"], "„sagen“ sonundaki -en: n'yi bırakma.", "sagen"),
      t("Wir gehen jetzt.", "Şimdi gidiyoruz.", "„gehen“: GEEN, tek uzun e.", ["gehn", "geben"], "„gehen“: uzun e + n.", "gehen"),
      t("Sie können kommen.", "Gelebilirler.", "„können“: KÖNN, „kommen“: KOMM.", ["kennen", "kommt"], "„kommen“ sonundaki -en: m'ye eriyor, düşmüyor.", "kommen"),
      t("Wir laufen nach Hause.", "Eve yürüyoruz.", "„laufen“: LAUFN.", ["lauf", "Laufen"], "„laufen“: f'den sonra n.", "laufen"),
    ]),
  drill("b2-p7", "B2", "„tz“, „z“ und „ts“", "Üçü de aynı ses: ts. Katze = KAT-sı, Platz = PLATS, nichts = NİHTS. Türkçe konuşan z'yi „z“ okuyunca „Zeit“ „sayt/zayt“ olmuyor, tanıyıcı „seit“ yakalıyor.",
    [{ de: "die Katze", tr: "kedi" }, { de: "der Platz", tr: "yer, meydan" }, { de: "die Zeit", tr: "zaman" }],
    [
      t("Die Katze schläft.", "Kedi uyuyor.", "„Katze“: KAT-sı.", ["Kasse", "Karte"], "„Katze“ (kedi) yerine „Kasse“ duyuldu: tz = ts.", "Katze"),
      t("Ist der Platz frei?", "Bu yer boş mu?", "„Platz“: PLATS.", ["Plaz", "Blatt"], "„Platz“ sonunda ts.", "Platz"),
      t("Ich habe keine Zeit.", "Vaktim yok.", "„Zeit“: TSAYT.", ["seit", "Seite"], "„Zeit“ (zaman) yerine „seit“ (-den beri) duyuldu: z = ts.", "Zeit"),
      t("Das ist nichts.", "Bu hiçbir şey değil.", "„nichts“: NİHTS — yumuşak ch + ts.", ["nicht", "nix"], "„nichts“ (hiçbir şey) yerine „nicht“ (değil) duyuldu: sondaki -s.", "nichts"),
      t("Jetzt sitzen wir.", "Şimdi oturuyoruz.", "„jetzt“: YETST; „sitzen“: ZİT-sen.", ["jetz", "setzen"], "„jetzt“: y + e + tst.", "jetzt"),
    ]),
  drill("b2-p8", "B2", "Rhythmus und Pausen", "Almanca vurgulu heceler arasında eşit zaman bırakır (vurgu zamanlı); vurgusuz heceler sıkışır. Türkçe her heceye eşit süre verir — cümle „robot gibi“ duyulur.",
    [{ de: "eigentlich", tr: "aslında" }, { de: "wahrscheinlich", tr: "muhtemelen" }, { de: "die Verantwortung", tr: "sorumluluk" }],
    [
      t("Eigentlich wollte ich nicht kommen.", "Aslında gelmek istemiyordum.", "Vurgu: EI-gentlich WOLL-te ich nicht KOM-men — aradakiler hızlı.", ["Eigentlich wollte ich kommen", "Eigentlich wollte ich"], "Vurgulu heceleri uzat, vurgusuzları sıkıştır; „nicht“i düşürme.", "nicht"),
      t("Wahrscheinlich regnet es morgen.", "Muhtemelen yarın yağmur yağacak.", "„wahr-SCHEIN-lich“: orta hece vurgulu.", ["Wahrscheinlich regnet es", "regnet es morgen"], "„wahrscheinlich“: vurgu SCHEIN'de.", "wahrscheinlich"),
      t("Das ist meine Verantwortung.", "Bu benim sorumluluğum.", "„Ver-ANT-wor-tung“: ikinci hece vurgulu, gerisi hızlı.", ["Verantwortung", "Antwort"], "„Verantwortung“da vurgu ANT'ta.", "Verantwortung"),
      t("Ich habe es dir doch gesagt.", "Sana söylemiştim ya.", "„doch“ vurgulu, „habe es dir“ hızlı geçer.", ["Ich habe es dir gesagt", "dir doch"], "Kip parçacığı „doch“ vurgulu; önündekiler sıkışır.", "doch"),
      t("Können Sie das bitte wiederholen?", "Bunu tekrar edebilir misiniz?", "„KÖN-nen Sie das bit-te wie-der-HO-len“: iki vurgu.", ["Können Sie das wiederholen", "wiederholen"], "İki vurgu noktası: KÖN- ve -HO-; aradakiler hızlı.", "wiederholen"),
    ]),

  // ── C1 ──
  drill("c1-p1", "C1", "Französische Lehnwörter", "Fransızcadan gelen kelimeler Almancada Fransızca okunur: Garage = ga-RAA-jı (j = Türkçe j), Ingenieur = in-jen-YÖÖR, Restaurant = res-to-RAAN (burundan). Alman okuma kuralı burada işlemez.",
    [{ de: "die Garage", tr: "garaj" }, { de: "der Ingenieur", tr: "mühendis" }, { de: "das Restaurant", tr: "restoran" }],
    [
      t("Das Auto steht in der Garage.", "Araba garajda.", "„Garage“: ga-RAA-jı, j Türkçe j.", ["Garagen", "Grage"], "„Garage“ sonundaki -ge j gibi, ge değil.", "Garage"),
      t("Mein Bruder ist Ingenieur.", "Kardeşim mühendis.", "„Ingenieur“: in-jen-YÖÖR, sonda uzun ö.", ["Ingenieure", "Ingenieurin"], "„Ingenieur“: vurgu sonda, -eur = öör.", "Ingenieur"),
      t("Wir essen im Restaurant.", "Restoranda yiyoruz.", "„Restaurant“: res-to-RAAN, sondaki t okunmaz, a burundan.", ["Restaurants", "Rest"], "„Restaurant“ sonundaki t sessiz; a nazal.", "Restaurant"),
      t("Das Büro ist im ersten Stock.", "Büro birinci katta.", "„Büro“: bü-ROO, vurgu sonda.", ["Buro", "Büros"], "„Büro“: ü yuvarlak, vurgu sonda.", "Büro"),
      t("Sie hat ein gutes Niveau.", "İyi bir seviyesi var.", "„Niveau“: ni-VOO — eau = o.", ["Niveaus", "Nivo"], "„Niveau“ sonu o okunur.", "Niveau"),
    ]),
  drill("c1-p2", "C1", "„y“, „ph“, „th“ und „ch“ in griechischen Wörtern", "Yunanca kökenlilerde y = ü (Physik = FÜ-zik, Typ = TÜP), ph = f, th = t (Thema = TEE-ma), ch = k (Chor = KOOR, Chemie = şe-Mİİ ya da ke-Mİİ).",
    [{ de: "die Physik", tr: "fizik" }, { de: "das Thema", tr: "konu" }, { de: "der Chor", tr: "koro" }],
    [
      t("Ich studiere Physik.", "Fizik okuyorum.", "„Physik“: fü-ZİİK, y = ü, vurgu sonda.", ["Fisik", "Physiker"], "„Physik“te y = ü: fü-ZİİK.", "Physik"),
      t("Das Thema ist schwierig.", "Konu zor.", "„Thema“: TEE-ma, th = t.", ["Tema", "Themen"], "„Thema“: th sadece t; ingilizce th yok.", "Thema"),
      t("Er singt im Chor.", "Koroda söylüyor.", "„Chor“: KOOR, ch = k.", ["Kor", "Chore"], "„Chor“ başında ch = k.", "Chor"),
      t("Das ist typisch deutsch.", "Bu tipik Almanca.", "„typisch“: TÜÜ-piş, y = ü.", ["tipisch", "Typ"], "„typisch“te y = ü.", "typisch"),
      t("Sie hat Charakter.", "Karakteri var.", "„Charakter“: ka-RAK-ta, ch = k.", ["Charaktere", "Karate"], "„Charakter“ başında ch = k, vurgu ortada.", "Charakter"),
    ]),
  drill("c1-p3", "C1", "Nasale Vokale", "Fransızca kökenli kelimelerde burundan ünlü: Balkon = bal-KON (n zayıf, o burundan), Parfum = par-FÖN, Chance = ŞANS(ı). Alman okuma kuralı ile „bal-kon“ demek anlaşılır ama işaretlidir.",
    [{ de: "der Balkon", tr: "balkon" }, { de: "das Parfum", tr: "parfüm" }, { de: "die Chance", tr: "şans" }],
    [
      t("Wir sitzen auf dem Balkon.", "Balkonda oturuyoruz.", "„Balkon“: bal-KOON (Kuzey) ya da bal-KON burundan — ikisi de kabul.", ["Balkone", "Ballon"], "„Balkon“ (balkon) yerine „Ballon“ duyuldu: -kon sonda vurgulu.", "Balkon"),
      t("Das Parfum riecht gut.", "Parfüm güzel kokuyor.", "„Parfum“: par-FÖN, burundan.", ["Parfüm", "Farm"], "„Parfum“: sonda nazal ö.", "Parfum"),
      t("Das ist eine gute Chance.", "Bu iyi bir şans.", "„Chance“: ŞAN-sı, a burundan.", ["Schanze", "Chancen"], "„Chance“: ş + nazal a + sı.", "Chance"),
      t("Der Saison beginnt im Mai.", "Sezon Mayıs'ta başlıyor.", "„Saison“: se-ZON, burundan.", ["Season", "Saisons"], "„Saison“ sonu nazal o.", "Saison"),
      t("Ich mag das Ambiente.", "Ortamı seviyorum.", "„Ambiente“: am-bi-EN-tı (İtalyanca).", ["Ambiance", "Ambient"], "„Ambiente“: vurgu EN'de, sondaki -e var.", "Ambiente"),
    ]),
  drill("c1-p4", "C1", "Betonung in langen Komposita", "Bileşik kelimede ana vurgu İLK öğede, ikincil vurgu son öğede: KRANkenversicherung, ARbeitsvertrag. Türkçe konuşan sona vurgular; kelime tanınır ama anlam gruplaması bozulur.",
    [{ de: "die Krankenversicherung", tr: "sağlık sigortası" }, { de: "der Arbeitsvertrag", tr: "iş sözleşmesi" }, { de: "die Wohnungssuche", tr: "ev arama" }],
    [
      t("Die Krankenversicherung ist teuer.", "Sağlık sigortası pahalı.", "„KRAN-ken-ver-si-che-rung“: ilk hece ana vurgu.", ["Krankenversicherungen", "Versicherung"], "Bileşikte ana vurgu ilk öğede: KRANken-.", "Krankenversicherung"),
      t("Ich habe den Arbeitsvertrag unterschrieben.", "İş sözleşmesini imzaladım.", "„AR-beits-ver-trag“: ilk hece vurgulu.", ["Arbeitsverträge", "Vertrag"], "„Arbeitsvertrag“: vurgu AR-'da.", "Arbeitsvertrag"),
      t("Die Wohnungssuche dauert lange.", "Ev arama uzun sürüyor.", "„WOH-nungs-su-che“.", ["Wohnung", "Suche"], "„Wohnungssuche“: tek kelime, vurgu başta.", "Wohnungssuche"),
      t("Wir brauchen eine Aufenthaltsgenehmigung.", "Oturma iznine ihtiyacımız var.", "„AUF-ent-halts-ge-neh-mi-gung“.", ["Aufenthaltsgenehmigungen", "Genehmigung"], "„Aufenthaltsgenehmigung“: ana vurgu AUF'ta.", "Aufenthaltsgenehmigung"),
      t("Das Bundesverfassungsgericht entscheidet.", "Federal Anayasa Mahkemesi karar veriyor.", "„BUN-des-ver-fas-sungs-ge-richt“.", ["Verfassungsgericht", "Bundesgericht"], "Uzun bileşikte ilk öğe vurgulu, gerisi düşük.", "Bundesverfassungsgericht"),
    ]),
  drill("c1-p5", "C1", "Ironie und Nachdruck", "Aynı cümle tonla övgü ya da alay olur: „Das ist ja TOLL“ (gerçek) / „Das ist ja toll…“ (uzatılmış, düşen: ironi). Kip parçacıkları (ja, doch, mal) vurgusuz kalır; vurgulanınca anlam kayar.",
    [{ de: "toll", tr: "harika" }, { de: "ja", tr: "ya, işte (parçacık)" }, { de: "doch", tr: "ama, ya (parçacık)" }],
    [
      t("Das ist ja toll!", "Bu harika ya! (gerçek sevinç)", "„toll“ kısa ve yüksek; „ja“ vurgusuz.", ["Das ist ja toll", "toll"], "Sevinç: „toll“ yukarı ve kısa.", "toll"),
      t("Das ist ja toll.", "Harika (ironik: hiç değil).", "„toll“ uzatılmış, düşen ton; ses tekdüze.", ["Das ist ja toll", "Das ist toll"], "İroni: „toll“ uzun ve düşük.", "toll"),
      t("Komm doch mal vorbei!", "Uğrasana!", "„doch mal“ vurgusuz ve hızlı; vurgu „vorBEI“de.", ["Komm mal vorbei", "vorbei"], "Parçacıklar vurgusuz; „vorbei“ vurgulu.", "vorbei"),
      t("Das habe ich DOCH gesagt!", "Söyledim ya işte!", "Burada „doch“ vurgulu: karşı çıkma.", ["Das habe ich gesagt", "doch gesagt"], "Vurgulu „doch“ = itiraz; vurgusuz „doch“ = yumuşatma.", "doch"),
      t("Na, wenn das mal gut geht.", "Bakalım bu iyi gidecek mi… (şüphe)", "„mal“ vurgusuz, „gut“ hafif uzatılmış, düşen ton.", ["Wenn das gut geht", "das mal gut"], "Şüphe tonu: „gut“ uzatılır, cümle düşer.", "gut"),
    ]),
  drill("c1-p6", "C1", "Auslautverhärtung in Wortfugen", "Sondaki b/d/g kelime sonunda p/t/k olur — bileşiklerin ORTASINDA da: Handtuch = HANT-tuh, Abteilung = AP-tay-lun(g). Türkçe konuşan yazıma bakıp d/b söyler.",
    [{ de: "das Handtuch", tr: "havlu" }, { de: "die Abteilung", tr: "bölüm" }, { de: "der Flugzeug", tr: "uçak" }],
    [
      t("Das Handtuch ist nass.", "Havlu ıslak.", "„Handtuch“: HANT-tuh, d → t.", ["Handtücher", "Hand"], "„Handtuch“ ortasındaki d t okunur.", "Handtuch"),
      t("Ich arbeite in der Abteilung.", "Bölümde çalışıyorum.", "„Abteilung“: AP-tay-lun(g), b → p.", ["Abteilungen", "Teilung"], "„Abteilung“: ab- sonundaki b p okunur.", "Abteilung"),
      t("Das Flugzeug landet.", "Uçak iniyor.", "„Flugzeug“: FLUUK-tsoyk, iki g de k.", ["Flugzeuge", "Zeug"], "„Flugzeug“: g'ler k okunur.", "Flugzeug"),
      t("Der Tagdienst beginnt um sechs.", "Gündüz nöbeti altıda başlıyor.", "„Tagdienst“: TAAK-diinst.", ["Tagdienste", "Dienst"], "„Tag“ sonundaki g k; „Dienst“te d ötümlü kalır.", "Tagdienst"),
      t("Die Abgabe ist morgen.", "Teslim yarın.", "„Abgabe“: AP-gaa-bı.", ["Abgaben", "Aufgabe"], "„Abgabe“: ab- sonundaki b p; gabe'nin b'si ötümlü.", "Abgabe"),
    ]),
  drill("c1-p7", "C1", "Umgangssprachliche Kontraktionen", "Doğal konuşmada kelimeler kaynaşır: haben wir → hamwa, hast du → haste, gehen wir → gehmwa, ein → 'n. Söylemek zorunlu değil; ama tanımak C1 dinlemenin parçası. Bu drill standart hâli söyletir.",
    [{ de: "haben wir", tr: "-miz var" }, { de: "hast du", tr: "sende var mı" }, { de: "gehen wir", tr: "gidelim" }],
    [
      t("Haben wir noch Zeit?", "Hâlâ vaktimiz var mı?", "Standart: HAA-ben VİİA; konuşmada „hamwa“.", ["Hamwa noch Zeit", "Haben wir Zeit"], "Standart biçimde söyle: haben + wir ayrı.", "Haben wir noch Zeit?"),
      t("Hast du das gesehen?", "Bunu gördün mü?", "Standart: HAST DU; konuşmada „haste“.", ["Haste das gesehen", "Hast das gesehen"], "„Hast du“ iki kelime; „haste“ yalnız konuşma dili.", "Hast du das gesehen?"),
      t("Gehen wir nach Hause?", "Eve gidelim mi?", "Standart: GEE-en VİİA.", ["Gehmwa nach Hause", "Gehen nach Hause"], "„Gehen wir“: wir'i düşürme.", "Gehen wir nach Hause?"),
      t("Ich habe einen Termin.", "Bir randevum var.", "Standart: AY-nen; konuşmada „'nen“.", ["Ich hab nen Termin", "Ich habe Termin"], "„einen“ tam: ay-nen.", "einen"),
      t("Was ist denn los?", "Ne oluyor?", "„denn“ vurgusuz; konuşmada „Was is'n los“.", ["Was is los", "Was ist los"], "„denn“ parçacığı düşük ama var.", "denn"),
    ]),
  drill("c1-p8", "C1", "Silbentrennung und Endsilben", "Uzun kelimelerde hece sınırları: In-te-res-se (vurgu ilk hecede, ikinci e uzun), Ge-schich-te, Me-di-ka-MENT. Yanlış bölme yanlış vurguya, o da tanınmamaya yol açar.",
    [{ de: "das Interesse", tr: "ilgi" }, { de: "die Geschichte", tr: "tarih, hikâye" }, { de: "das Medikament", tr: "ilaç" }],
    [
      t("Ich habe großes Interesse.", "Büyük ilgim var.", "„In-te-RES-se“: vurgu RES'te.", ["Interessen", "Intresse"], "„Interesse“: dört hece, vurgu üçüncüde.", "Interesse"),
      t("Die Geschichte ist lang.", "Hikâye uzun.", "„Ge-SCHICH-te“: vurgu ortada, ge- vurgusuz.", ["Geschichten", "Schicht"], "„Geschichte“: ge- kısa, SCHICH vurgulu, -te var.", "Geschichte"),
      t("Nehmen Sie das Medikament.", "İlacı alın.", "„Me-di-ka-MENT“: vurgu sonda.", ["Medikamente", "Moment"], "„Medikament“: vurgu son hecede.", "Medikament"),
      t("Die Entwicklung ist positiv.", "Gelişme olumlu.", "„Ent-WICK-lung“: vurgu WICK'te.", ["Entwicklungen", "Wicklung"], "„Entwicklung“: ent- vurgusuz.", "Entwicklung"),
      t("Wir diskutieren die Möglichkeiten.", "Olanakları tartışıyoruz.", "„MÖG-lich-kei-ten“: vurgu başta, üç zayıf hece.", ["Möglichkeit", "möglich"], "„Möglichkeiten“: vurgu ilk hecede, çoğul -en sonda.", "Möglichkeiten"),
    ]),
  drill("c1-p9", "C1", "Schnelles Vorlesen", "Akıcılık drilli: uzun cümleyi tek nefeste, doğal ritimle oku. Hedef sesler değil bağlantı; duraklamalar virgülde, vurgular anlam odağında.",
    [{ de: "die Voraussetzung", tr: "ön koşul" }, { de: "die Zusammenarbeit", tr: "iş birliği" }, { de: "die Herausforderung", tr: "zorluk" }],
    [
      t("Die wichtigste Voraussetzung ist gegenseitiges Vertrauen.", "En önemli ön koşul karşılıklı güvendir.", "Tek nefes; vurgu „wichtigste“ ve „Vertrauen“.", ["Die wichtigste Voraussetzung", "gegenseitiges Vertrauen"], "Cümleyi bölme; iki vurgu noktasıyla tek nefeste oku.", "Vertrauen"),
      t("Ohne Zusammenarbeit lässt sich das Problem nicht lösen.", "İş birliği olmadan sorun çözülemez.", "„Zusammenarbeit“ ve „lösen“ vurgulu.", ["Ohne Zusammenarbeit", "lässt sich das Problem lösen"], "„nicht“ düşürülmesin.", "nicht"),
      t("Die größte Herausforderung besteht darin, alle Beteiligten zu überzeugen.", "En büyük zorluk, bütün tarafları ikna etmektir.", "Virgülde kısa duraklama; „überzeugen“ vurgulu.", ["Die größte Herausforderung", "alle Beteiligten überzeugen"], "Virgülden sonra ikinci parçayı tam oku.", "überzeugen"),
      t("Ich bin davon überzeugt, dass wir das gemeinsam schaffen.", "Bunu birlikte başaracağımıza inanıyorum.", "„überzeugt“ ve „schaffen“ vurgulu; „dass“ vurgusuz.", ["Ich bin davon überzeugt", "dass wir das schaffen"], "„gemeinsam“ı atlama.", "gemeinsam"),
      t("Unter diesen Umständen wäre eine Verschiebung sinnvoll.", "Bu koşullar altında bir erteleme mantıklı olurdu.", "„Umständen“, „Verschiebung“, „sinnvoll“ vurgulu.", ["Unter diesen Umständen", "eine Verschiebung sinnvoll"], "„wäre“ Konjunktiv: ä açık e.", "wäre"),
    ]),
];
