import type { SkillExercise } from "../types";

/**
 * Zürih Almancası (gsw-zh) A1 — okuma, dinleme ve yazma egzersizleri.
 * Metinler Züritüütsch (Dieth yazımı, data/zurich/style-guide.md bağlayıcı);
 * yönerge ve açıklamalar Türkçe.
 */
export const zhA1: SkillExercise[] = [
  // ─────────────────────────── OKUMA ───────────────────────────
  {
    id: "zh-a1-r1",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Träffe mer üs am Bellevue?",
    genre: "Mesaj",
    intro: "Lara'nın arkadaşı Deniz'e lehçeyle yazdığı bir WhatsApp mesajını okuyacaksın.",
    gloss: [
      { de: "Wie gaats der?", tr: "Nasılsın? (wie geht es dir)" },
      { de: "de Namitag", tr: "öğleden sonra (Nachmittag)" },
      { de: "an See gaa", tr: "göle gitmek" },
      { de: "d Tramhaltstell", tr: "tramvay durağı" },
      { de: "s Velo", tr: "bisiklet (İsviçre'de Fahrrad yerine)" },
      { de: "d Glace", tr: "dondurma (İsviçre'de Eis yerine)" },
      { de: "de Aabig", tr: "akşam (Abend)" },
    ],
    minutes: 3,
    text:
      "Hoi Deniz! Wie gaats der? Ich ha morn am Namitag frei. S Wätter isch schöön — wämmer zäme an See gaa? Mir träffed üs am zwäi am Bellevue, bi de Tramhaltstell. Ich nime s Velo, du chasch mit em Tram Nummere 4 choo. Nachhär gömmer no es Glace ässe. Mini Kollegin Anna chunt au mit. Schriib mer bitte bis hüt am Aabig!\n\nLiebi Grüess\nLara",
    questions: [
      {
        text: "Wänn träffed sich d Lara und de Deniz?",
        options: ["Am zwäi", "Am vieri", "Am Aabig"],
        answer: 0,
        explain:
          "Mesajta „Mir träffed üs am zwäi am Bellevue“ yazıyor — saat ikide buluşuyorlar. Akşam yalnızca cevap yazma sınırı.",
      },
      {
        text: "Richtig oder falsch? De Deniz söll mit em Velo choo.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain:
          "Yanlış: Bisikleti Lara alıyor („Ich nime s Velo“), Deniz'e 4 numaralı tramvayla gelmesini söylüyor.",
      },
      {
        text: "Was mached si nachhär?",
        options: ["Es Glace ässe", "E Pizza ässe", "Häi gaa"],
        answer: 0,
        explain: "„Nachhär gömmer no es Glace ässe“ — sonrasında dondurma yemeye gidiyorlar.",
      },
      {
        text: "Wär chunt au no mit?",
        options: ["D Anna", "De Murat", "Niemert"],
        answer: 0,
        explain: "„Mini Kollegin Anna chunt au mit“ — Lara'nın arkadaşı Anna da geliyor.",
      },
    ],
  },
  {
    id: "zh-a1-r2",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Zimmer z Züri z vermiete",
    genre: "İlan",
    intro: "Zürih'in 4. bölgesinde (Chreis 4) kiralık bir oda ilanı okuyacaksın.",
    gloss: [
      { de: "z vermiete", tr: "kiralık (zu vermieten)" },
      { de: "de Chreis", tr: "Zürih'te ilçe/bölge (Kreis)" },
      { de: "d Wohnig", tr: "daire (Wohnung)" },
      { de: "inbegriffe", tr: "dahil (giderler kiraya dahil)" },
      { de: "ewägg", tr: "uzakta (entfernt/weg)" },
      { de: "s Huustier", tr: "evcil hayvan" },
      { de: "aalüte", tr: "telefon etmek (anrufen)" },
      { de: "d Bsichtigung", tr: "evi gezip görme" },
    ],
    minutes: 3,
    text:
      "Schööns Zimmer i de Stadt Züri z vermiete, im Chreis 4. S Zimmer isch 18 Quadratmeter grooss und hät en grosse Balkon. D Wohnig isch im dritte Stock, mit Lift. D Miete isch 850 Franke im Monet, alles inbegriffe. D Tramhaltstell isch nur zwäi Minute z Fuess ewägg. Käi Huustier! Frei ab em 1. Septämber.\n\nHäsch Intresse? Denn lüt em Herr Huber aa: 044 123 45 67. Bsichtigung am Samschtig vo de zääni bis am zwölfi.",
    questions: [
      {
        text: "Richtig oder falsch? S Zimmer hät en Balkon.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Doğru: İlanda „hät en grosse Balkon“ yazıyor.",
      },
      {
        text: "Wie vil choschtet s Zimmer im Monet?",
        options: ["850 Franke", "1'044 Franke", "450 Franke"],
        answer: 0,
        explain:
          "„D Miete isch 850 Franke im Monet, alles inbegriffe“ — kira ayda 850 frank, giderler dahil.",
      },
      {
        text: "Wänn cha me s Zimmer go aaluege?",
        options: ["Am Samschtig vo 10 bis 12", "Am 1. Septämber", "Am Sunntig am Namitag"],
        answer: 0,
        explain:
          "Son cümle: „Bsichtigung am Samschtig vo de zääni bis am zwölfi“. 1 Eylül odanın boşalacağı tarih.",
      },
      {
        text: "Richtig oder falsch? Me törf e Chatz mitnää.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: „Käi Huustier!“ — evcil hayvan (kedi dahil) yasak.",
      },
    ],
  },

  {
    id: "zh-a1-r3",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Iiladig zum Geburi",
    genre: "E-posta",
    intro: "Lena, arkadaşı Sara'yı doğum günü partisine çağırıyor. Davetiyeyi okuyacaksın.",
    gloss: [
      { de: "s Geburi", tr: "doğum günü (Geburtstag)" },
      { de: "dihäi", tr: "evde (zu Hause)" },
      { de: "es gaat … los", tr: "… başlıyor" },
      { de: "de Schtock", tr: "kat" },
      { de: "s Gschänk", tr: "hediye" },
      { de: "öb", tr: "… -ıp -madığı (ob)" },
      { de: "sich fröie uf", tr: "dört gözle beklemek" },
    ],
    minutes: 3,
    text:
      "Liebi Sara\n\nAm Samschtig wird ich drissg! Drum mach ich e chlini Party bi mir dihäi. Es gaat am sibni am Aabig los. Mini Adrässe: Langstrass 42, im zwäite Schtock.\n\nZum Ässe git s Pizza und Salaat. Öppis z trinke bringed d Gescht sälber mit. Bitte nimm kä Gschänk mit — chum äifach!\n\nChasch mer bis am Mittwuch säge, öb du chunsch? Ich fröi mi uf di.\n\nLiebi Grüess\nLena",
    questions: [
      {
        text: "Wänn gaat d Party los?",
        options: ["Am sibni am Aabig", "Am zwäi am Namitag", "Am Mittwuch"],
        answer: 0,
        explain: "„Es gaat am sibni am Aabig los“ — parti akşam yedide başlıyor.",
      },
      {
        text: "Wo isch d Party?",
        options: ["Bi de Lena dihäi", "Im Reschtorant", "Im Quartierzäntrum"],
        answer: 0,
        explain: "„Ich mach e chlini Party bi mir dihäi“ — Lena evinde, Langstrass 42'de.",
      },
      {
        text: "Richtig oder falsch? Me söll es Gschänk mitbringe.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: „Bitte nimm kä Gschänk mit“ — hediye istemiyor, sadece gelinmesini.",
      },
      {
        text: "Bis wänn söll d Sara antworte?",
        options: ["Bis am Mittwuch", "Bis am Samschtig", "Bis am Sunntig"],
        answer: 0,
        explain: "„Chasch mer bis am Mittwuch säge, öb du chunsch?“ — çarşambaya kadar.",
      },
    ],
  },
  {
    id: "zh-a1-r4",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Nöii Öffnigsziite",
    genre: "Duyuru",
    intro: "Mahalle kütüphanesinin kapısına asılan yeni çalışma saatleri duyurusunu okuyacaksın.",
    gloss: [
      { de: "d Öffnigsziite", tr: "açılış saatleri" },
      { de: "gschlosse / zue", tr: "kapalı" },
      { de: "zruggbringe", tr: "geri getirmek" },
      { de: "de Chaschte", tr: "kutu, dolap (Kasten)" },
      { de: "d Iigangstür", tr: "giriş kapısı" },
      { de: "usserhalb", tr: "dışında" },
    ],
    minutes: 3,
    text:
      "Liebi Bsuecherinne und Bsuecher\n\nAb em erschte Oktober händ mir nöii Öffnigsziite:\n\nMäändig: gschlosse\nZischtig bis Friitig: 9 bis 19 Uhr\nSamschtig: 9 bis 16 Uhr\nSunntig: gschlosse\n\nD Büecher chöned Si au usserhalb vo de Öffnigsziite zruggbringe: de Chaschte isch näb de Iigangstür.\n\nAchtung: Am 24. Dezämber isch d Bibliothek de ganz Tag zue.\n\nIhres Bibliothekstiim",
    questions: [
      {
        text: "Wänn isch d Bibliothek gschlosse?",
        options: ["Am Määndig und am Sunntig", "Nume am Sunntig", "Am Samschtig"],
        answer: 0,
        explain: "Listede hem „Määndig: gschlosse“ hem „Sunntig: gschlosse“ yazıyor.",
      },
      {
        text: "Bis wänn hät s am Samschtig offe?",
        options: ["Bis am vieri", "Bis am sibni", "Bis am zwölfi"],
        answer: 0,
        explain: "Cumartesi 9–16, yani saat dörde kadar. 19 (sibni) hafta içi kapanış saati.",
      },
      {
        text: "Wo cha me d Büecher zruggbringe, wänn zue isch?",
        options: ["Im Chaschte näb de Iigangstür", "Bi de Poscht", "Im Kafi näbenaa"],
        answer: 0,
        explain: "„De Chaschte isch näb de Iigangstür“ — kapalıyken kitaplar bu kutuya bırakılır.",
      },
      {
        text: "Richtig oder falsch? Am 24. Dezämber hät d Bibliothek offe.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: „Am 24. Dezämber isch d Bibliothek de ganz Tag zue.“",
      },
    ],
  },
  {
    id: "zh-a1-r5",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Kurs im Quartierzäntrum",
    genre: "Program",
    intro: "Wipkingen semt merkezinin sonbahar kurs programını okuyacaksın.",
    gloss: [
      { de: "de Aafänger", tr: "yeni başlayan" },
      { de: "s Gricht", tr: "yemek (Gericht)" },
      { de: "d Mundart", tr: "lehçe" },
      { de: "d Aamäldig", tr: "kayıt (Anmeldung)" },
      { de: "de Schalter", tr: "gişe" },
      { de: "de Rabatt", tr: "indirim" },
      { de: "s Kulturlegi", tr: "düşük gelirliler için kültür kartı (İsviçre)" },
    ],
    minutes: 4,
    text:
      "Kurs im Quartierzäntrum Wipkinge — Herbscht\n\nChoche für Aafänger\nMäändig, 18.30–20.30 · 8 Aabig · 240 Franke\nMir choched äifachi Grichte us de ganze Wält.\n\nZüritüütsch für Aaglernti\nMittwuch, 19.00–20.30 · 10 Aabig · 200 Franke\nFür alli, wo scho Hochdüütsch chönd und jetz d Mundart wänd verstaa.\n\nYoga am Morge\nFriitig, 7.00–8.00 · 12 Mal · 180 Franke\n\nAamäldig online oder am Schalter, bis zwäi Wuche vor em Aafang. Lüüt mit em Kulturlegi überchömed drissg Prozänt Rabatt.",
    questions: [
      {
        text: "Wänn isch de Züritüütsch-Kurs?",
        options: ["Am Mittwuch am Aabig", "Am Määndig am Aabig", "Am Friitig am Morge"],
        answer: 0,
        explain: "„Züritüütsch für Aaglernti — Mittwuch, 19.00–20.30“. Pazartesi yemek kursu.",
      },
      {
        text: "Wie vil choschtet de Chochkurs?",
        options: ["240 Franke", "200 Franke", "180 Franke"],
        answer: 0,
        explain: "Yemek kursu 240 frank; 200 lehçe kursu, 180 yoga.",
      },
      {
        text: "Richtig oder falsch? Me cha sich nume online aamälde.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: „Aamäldig online oder am Schalter“ — gişeden de kayıt olunabiliyor.",
      },
      {
        text: "Wär überchunt Rabatt?",
        options: ["Lüüt mit em Kulturlegi", "Studänte", "Alli Aafänger"],
        answer: 0,
        explain: "Son cümle: Kulturlegi kartı olanlar %30 indirim alıyor.",
      },
    ],
  },
  {
    id: "zh-a1-r6",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Information für üsi Fahrgäscht",
    genre: "Duyuru",
    intro: "Zürih toplu taşımasının (VBZ) duraklara astığı yol çalışması duyurusunu okuyacaksın.",
    gloss: [
      { de: "de Fahrgascht", tr: "yolcu" },
      { de: "s Gläis", tr: "ray, peron (Gleis)" },
      { de: "umbaue", tr: "yenilemek, tadilat yapmak" },
      { de: "gälte", tr: "geçerli olmak" },
      { de: "rächne mit", tr: "hesaba katmak" },
      { de: "d Umständ", tr: "zahmet, rahatsızlık" },
    ],
    minutes: 3,
    text:
      "Liebi Fahrgäscht\n\nVom 3. bis am 17. Juli baued mir d Gläis am Central um. S Tram Nummere 6 und 10 fahred i dere Ziit nöd bis zum Central.\n\nStatt em Tram fahrt en Bus. De Bus haltet vor em Hauptbahnhof, uf de andere Strasseziite.\n\nBitte rächned mit zää Minute meh Ziit. S Billett giltet au im Bus.\n\nMir entschuldiged üs für d Umständ.\nVerchehrsbetriib Züri",
    questions: [
      {
        text: "Was passiert vom 3. bis am 17. Juli?",
        options: ["D Gläis am Central wärded umbaut", "S Tram fahrt hüüfiger", "De Bahnhof isch zue"],
        answer: 0,
        explain: "„Vom 3. bis am 17. Juli baued mir d Gläis am Central um.“",
      },
      {
        text: "Welli Tram fahred nöd bis zum Central?",
        options: ["Nummere 6 und 10", "Nummere 4", "Alli Tram"],
        answer: 0,
        explain: "Yalnızca 6 ve 10 numaralı tramvaylar Central'a çıkmıyor.",
      },
      {
        text: "Wo haltet de Bus?",
        options: ["Vor em Hauptbahnhof", "Am Bellevue", "Am See"],
        answer: 0,
        explain: "„De Bus haltet vor em Hauptbahnhof, uf de andere Strasseziite.“",
      },
      {
        text: "Richtig oder falsch? Me bruucht es nöis Billett für de Bus.",
        options: ["Richtig", "Falsch"],
        answer: 1,
        explain: "Yanlış: „S Billett giltet au im Bus“ — mevcut bilet otobüste de geçerli.",
      },
    ],
  },

  // ── Hikâye dizisi: Meral'in oğlu Kerem Chindsgi'ye başlıyor. A1'in yeni
  //    alıştırmalarında mektup → not → veli kahvesi → telefon → cevap sırası.
  {
    id: "zh-a1-r7",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Willkomme im Chindsgi",
    genre: "Mektup",
    intro:
      "Zürih'te anaokulundan gelen hoş geldin mektubu. A1'de takip edeceğin hikâyenin başlangıcı.",
    gloss: [
      { de: "de Chindsgi", tr: "anaokulu (Kindergarten)" },
      { de: "de Turnsack", tr: "spor torbası" },
      { de: "s Znüni", tr: "kuşluk atıştırmalığı" },
      { de: "aaschriibe", tr: "üzerine ad yazmak" },
      { de: "de Finkli", tr: "ev terliği (çocuk)" },
      { de: "abgää", tr: "teslim etmek" },
      { de: "de Elteraabig", tr: "veli toplantısı" },
    ],
    minutes: 3,
    text:
      "Liebi Frau Yıldız\n\nMir fröied üs uf de Kerem! De erscht Tag isch am Määndig, em 19. Auguscht, am nüüni.\n\nWas de Kerem bruucht:\n– Finkli für s Zimmer\n– en Turnsack mit Turnschueh\n– jede Tag es Znüni (käi Süessigkäite, bitte)\n– e Flasche Wasser\n\nBitte alles aaschriibe mit em Name. Es git bi eus zwölf Chind und sächs händ e rot Flasche.\n\nAm erschte Tag chönd Si bis am halbi zäni bliibe. Nachhär isch s für d Chind äifacher ohni d Eltere.\n\nDe Elteraabig isch am 3. Septämber am achti.\n\nHärzlichi Grüess\nFrau Suter, Chindsgi Hardau",
    questions: [
      {
        text: "Wänn fangt de Chindsgi aa?",
        options: ["Am Määndig am nüüni", "Am 3. Septämber", "Am halbi zäni"],
        answer: 0,
        explain: "„De erscht Tag isch am Määndig, em 19. Auguscht, am nüüni.“",
      },
      {
        text: "Was söll de Kerem NÖD im Znüni haa?",
        options: ["Süessigkäite", "Wasser", "Brot"],
        answer: 0,
        explain: "„käi Süessigkäite, bitte“.",
      },
      {
        text: "Warum söll me alles aaschriibe?",
        options: [
          "Well vill Chind s Gliiche händ",
          "Well d Lehrerin es so wott",
          "Well s sünsch verlore gaat",
        ],
        answer: 0,
        explain: "„Es git bi eus zwölf Chind und sächs händ e rot Flasche.“",
      },
      {
        text: "Wie lang chönd d Eltere am erschte Tag bliibe?",
        options: ["Bis am halbi zäni", "De ganz Tag", "Bis am nüüni"],
        answer: 0,
        explain: "Sonrasında çocuklar için ailesiz daha kolay oluyor.",
      },
    ],
  },
  {
    id: "zh-a1-r8",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Was ghört is Znüni?",
    genre: "Bilgi yazısı",
    intro:
      "İsviçre'de her okulda asılı olan liste: kuşluk molasında ne yenir. Küçük ama günlük hayatın merkezinde.",
    gloss: [
      { de: "s Znüni", tr: "kuşluk yemeği (saat 9 civarı)" },
      { de: "de Zvieri", tr: "ikindi atıştırmalığı (saat 4)" },
      { de: "s Gmües", tr: "sebze" },
      { de: "d Nuss", tr: "fındık, ceviz" },
      { de: "s Böxli", tr: "küçük kutu" },
      { de: "verbote", tr: "yasak" },
      { de: "de Znünibrunne", tr: "okuldaki su çeşmesi" },
    ],
    minutes: 3,
    text:
      "S Znüni — es paar Tipps\n\nGuet sind: Brot, Chääs, es Rüebli, en Öpfel, e Banane, Nüss, Jogurt.\n\nWeniger guet: Schoggistängeli, Chips, Gipfeli mit Schoggi. Süessi Getränk sind bi eus verbote — s Wasser git s gratis am Znünibrunne.\n\nBitte s Znüni imene Böxli mitgää, nöd im Plastiksäckli. Mir wänd weniger Abfall.\n\nWichtig: Es paar Chind händ e Nussallergie. Drum bitte käi Nüss, wänn Ihres Chind i de Gruppe Sunne isch.\n\nDe Zvieri isch nöd nötig — d Chind sind am zwäi scho dihäi.",
    questions: [
      {
        text: "Was isch es guets Znüni?",
        options: ["En Öpfel und Brot mit Chääs", "Chips", "E Cola"],
        answer: 0,
        explain: "İyi olanlar listesinde ekmek, peynir, elma sayılıyor.",
      },
      {
        text: "Was isch verbote?",
        options: ["Süessi Getränk", "Wasser", "Jogurt"],
        answer: 0,
        explain: "„Süessi Getränk sind bi eus verbote.“",
      },
      {
        text: "Warum söll me es Böxli bruuche?",
        options: ["Wäge em Abfall", "Well s billiger isch", "Well s schöner isch"],
        answer: 0,
        explain: "„Mir wänd weniger Abfall.“",
      },
      {
        text: "Für wär gilt s Nuss-Verbot?",
        options: [
          "Für d Gruppe Sunne",
          "Für alli Chind",
          "Nume für Chind mit Allergie",
        ],
        answer: 0,
        explain: "„wänn Ihres Chind i de Gruppe Sunne isch.“",
      },
    ],
  },
  {
    id: "zh-a1-r9",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "De Samichlaus chunt",
    genre: "Kültür",
    intro:
      "6 Aralık'ta İsviçre'de kapıya gelen figür: Samichlaus. Mahalle duyurusunu okuyacaksın.",
    gloss: [
      { de: "de Samichlaus", tr: "Noel Baba'nın İsviçre hâli (6 Aralık)" },
      { de: "de Schmutzli", tr: "Samichlaus'un siyah giysili yardımcısı" },
      { de: "de Sack", tr: "çuval" },
      { de: "s Värsli", tr: "kısa şiir, tekerleme" },
      { de: "d Nuss", tr: "ceviz, fındık" },
      { de: "s Mandarindli", tr: "küçük mandalina" },
      { de: "aamälde", tr: "kaydolmak" },
    ],
    minutes: 3,
    text:
      "Samichlaus im Quartier\n\nAm 6. Dezämber chunt de Samichlaus mit em Schmutzli is Quartier. Si chömed zu Ine hei, vo de füfi bis am achti am Aabig.\n\nDe Bsuech duuret öppe zää Minute. D Chind chönd es Värsli säge — si müend aber nöd. De Samichlaus hät Nüss, Mandarindli und Schoggi im Sack.\n\nDe Bsuech choschtet 40 Franke. S Gäld gaat a de Quartierverein.\n\nAamäldig bis am 25. Novämber: samichlaus@quartier-hardau.ch\n\nWichtig für nöii Familie: De Samichlaus isch nöd böös. Wänn es Chind Angscht hät, bliibt er a de Tür.",
    questions: [
      {
        text: "Wänn chunt de Samichlaus?",
        options: ["Am 6. Dezämber am Aabig", "Am 25. Novämber", "A Wienachte"],
        answer: 0,
        explain: "Akşam beş ile sekiz arası eve geliyor; 25 Kasım kayıt son tarihi.",
      },
      {
        text: "Müend d Chind es Värsli säge?",
        options: ["Nei, si chönd", "Ja, alli", "Nur di Grosse"],
        answer: 0,
        explain: "„si müend aber nöd.“",
      },
      {
        text: "Was isch im Sack?",
        options: ["Nüss, Mandarindli und Schoggi", "Bücher", "Spielsache"],
        answer: 0,
        explain: "Metinde bu üçü sayılıyor.",
      },
      {
        text: "Was passiert, wänn es Chind Angscht hät?",
        options: ["De Samichlaus bliibt a de Tür", "Er gaat wider", "Er chunt spöter"],
        answer: 0,
        explain: "Son cümle yeni ailelere bunu özellikle söylüyor.",
      },
    ],
  },
  {
    id: "zh-a1-r10",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "Vier Aazäige",
    genre: "Sınav formatı",
    intro:
      "Kısa ilanları okuyup kimin neye ihtiyacı olduğunu eşleştireceksin. Önce dördünü de oku.",
    gloss: [
      { de: "d Aazäig", tr: "ilan" },
      { de: "sueche", tr: "aramak" },
      { de: "verschänke", tr: "bedava vermek" },
      { de: "abhole", tr: "gelip almak" },
      { de: "d Stund", tr: "saat, ders saati" },
      { de: "de Hüetdienscht", tr: "çocuk bakımı" },
      { de: "gratis", tr: "ücretsiz" },
    ],
    minutes: 4,
    text:
      "A) Züritüütsch für Aafänger. Ich bi Schtudäntin und gib Schtunde. 30 Franke pro Schtund, nur am Wuchenänd. Tel. 076 555 12 12\n\nB) Velo z verchaufe, blau, drei Jaar alt, fahrt guet. 120 Franke. Nur abhole, käi Poscht. Tel. 079 888 40 40\n\nC) Mir verschänked es Bett (140 cm) und en Tisch. Alles guet erhalte. Sofort abhole im Chreis 4. Tel. 044 240 33 22\n\nD) Hüetdienscht: Ich lueg am Määndig und Mittwuch am Namitag zu Irem Chind. Ich han Erfaarig. Tel. 078 222 33 44",
    questions: [
      {
        text: "D Selin schafft vo Määndig bis Friitig und wott Mundart lerne. Welli Aazäig passt?",
        options: ["A", "C", "D"],
        answer: 0,
        explain: "A ilanı yalnızca hafta sonu ders veriyor — hafta içi çalışan Selin'e uygun.",
      },
      {
        text: "D Familie Roth bruucht am Mittwuch am Namitag öpper für s Chind. Welli Nummere?",
        options: ["078 222 33 44", "076 555 12 12", "044 240 33 22"],
        answer: 0,
        explain: "D ilanı pazartesi ve çarşamba öğleden sonra bakıyor.",
      },
      {
        text: "De Murat hät käis Auto. Cha er s Velo us Aazäig B chaufe?",
        options: [
          "Ja, aber er mues es sälber abhole",
          "Ja, si schicked s",
          "Nei, s isch verchauft",
        ],
        answer: 0,
        explain: "„Nur abhole, käi Poscht.“",
      },
      {
        text: "Welli Aazäig choschtet nüüt?",
        options: ["C", "B", "A"],
        answer: 0,
        explain: "„Mir verschänked es Bett … und en Tisch.“",
      },
    ],
  },
  {
    id: "zh-a1-r11",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "En Zettel vo de Frau Suter",
    genre: "Not",
    intro:
      "Hikâyenin ikinci bölümü: Meral, Kerem'in çantasında bir not buluyor.",
    gloss: [
      { de: "de Zettel", tr: "not" },
      { de: "d Jagge", tr: "mont, ceket" },
      { de: "vergässe", tr: "unutmak" },
      { de: "de Ussflug", tr: "gezi" },
      { de: "de Wald", tr: "orman" },
      { de: "warmi Chläider", tr: "kalın giysi" },
      { de: "Bschäid gää", tr: "haber vermek" },
    ],
    minutes: 3,
    text:
      "Liebi Frau Yıldız\n\nDrü chliini Sache:\n\n1. De Kerem hät sini Jagge scho zwäimal vergässe. Si hanget na bi eus. Bitte am Määndig dra dänke.\n\n2. Am Dunschtig mached mir en Ussflug id Wald. Bitte warmi Chläider und guet Schueh — s isch nass. S Znüni nämed mir mit.\n\n3. De Kerem redt underdesse vill meh. Er hät hüt em Nachbarschind ghulfe, d Finkli z finde. Das wett ich Ine grad säge.\n\nGänd Si mir bitte bis am Mittwuch Bschäid, öb de Kerem am Ussflug cha mitcho.\n\nFründlichi Grüess\nR. Suter",
    questions: [
      {
        text: "Was hät de Kerem vergässe?",
        options: ["Sini Jagge", "S Znüni", "D Finkli"],
        answer: 0,
        explain: "„De Kerem hät sini Jagge scho zwäimal vergässe.“",
      },
      {
        text: "Was bruucht s für de Ussflug?",
        options: ["Warmi Chläider und guet Schueh", "Es Velo", "Gäld"],
        answer: 0,
        explain: "Hava yaş olduğu için kalın giysi ve iyi ayakkabı.",
      },
      {
        text: "Was schriibt d Lehrerin über de Kerem?",
        options: [
          "Er redt meh und hät eme Chind ghulfe",
          "Er isch immer müed",
          "Er wott nöd spile",
        ],
        answer: 0,
        explain: "Üçüncü madde iyi bir haber: daha çok konuşuyor ve yardım etmiş.",
      },
      {
        text: "Bis wänn söll d Meral antworte?",
        options: ["Bis am Mittwuch", "Bis am Määndig", "Bis am Dunschtig"],
        answer: 0,
        explain: "„Gänd Si mir bitte bis am Mittwuch Bschäid.“",
      },
    ],
  },
  {
    id: "zh-a1-r12",
    course: "gsw-zh",
    level: "A1",
    skill: "reading",
    title: "S Billett und d Zone",
    genre: "Bilgi yazısı",
    intro:
      "Zürih'te bilet sistemi bölge (Zone) mantığıyla çalışır. En sık yapılan hatayı önleyen kısa bilgi.",
    gloss: [
      { de: "s Billett", tr: "bilet" },
      { de: "d Zone", tr: "bölge" },
      { de: "gälte", tr: "geçerli olmak" },
      { de: "s Tageskarte", tr: "günlük bilet" },
      { de: "kontrolliere", tr: "denetlemek" },
      { de: "d Buess", tr: "ceza" },
      { de: "s Halbtax", tr: "yarım ücret kartı (İsviçre)" },
    ],
    minutes: 4,
    text:
      "Billett und Zone — s Wichtigschte\n\nD Stadt Züri isch d Zone 110. Für alli Fahrte i de Stadt bruuchsch nur die äi Zone.\n\nEs Billett für äi Zone giltet 30 Minute. Für zwo Zone giltet s äi Stund. Du chasch i dere Ziit so oft umschtiige, wie du wottsch — au mit em Tram, Bus, Zug oder Schiff.\n\nAb drei Fahrte am Tag lohnt sich s Tageskarte.\n\nWichtig: S Billett muesch VOR em Iischtiige löse. Es git käi Verchauf im Tram. Wänn du käis häsch, choschtet s 100 Franke Buess — au wänn du s vergässe häsch.\n\nMit em Halbtax zaalsch überall d Hälfti. S choschtet 190 Franke im Jaar und lohnt sich scho ab öppe zwänzg Fahrte.",
    questions: [
      {
        text: "Welli Zone isch d Stadt Züri?",
        options: ["110", "30", "190"],
        answer: 0,
        explain: "„D Stadt Züri isch d Zone 110.“",
      },
      {
        text: "Wie lang giltet es Billett für äi Zone?",
        options: ["30 Minute", "Ei Stund", "De ganz Tag"],
        answer: 0,
        explain: "Bir saat iki bölge için geçerli.",
      },
      {
        text: "Wo chauft me s Billett?",
        options: ["Vor em Iischtiige", "Im Tram", "Bim Fahrer"],
        answer: 0,
        explain: "„Es git käi Verchauf im Tram.“",
      },
      {
        text: "Wie hööch isch d Buess ohni Billett?",
        options: ["100 Franke", "190 Franke", "30 Franke"],
        answer: 0,
        explain: "Unutmuş olmak da mazeret sayılmıyor.",
      },
      {
        text: "Ab wänn lohnt sich s Halbtax?",
        options: ["Ab öppe zwänzg Fahrte", "Ab drei Fahrte", "Ab hundert Fahrte"],
        answer: 0,
        explain: "Günde üç yolculuk ise Tageskarte, yılda ~20 yolculuk ise Halbtax.",
      },
    ],
  },

  // ─────────────────────────── DİNLEME ───────────────────────────
  {
    id: "zh-a1-l1",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "Im Kafi",
    genre: "Diyalog",
    intro: "Elif Zürih'te bir kafede sipariş veriyor; garsonla konuşmasını dinleyeceksin.",
    gloss: [
      { de: "Was törfs sii?", tr: "Ne alırdınız? (sipariş kalıbı)" },
      { de: "Ich hett gärn …", tr: "… rica ediyorum / … alayım" },
      { de: "de Kafi crème", tr: "sütlü kahve (İsviçre klasiği)" },
      { de: "s Gipfeli", tr: "kruvasan" },
      { de: "choschte", tr: "fiyatı … olmak (kosten)" },
      { de: "zrugg", tr: "geri (para üstü)" },
      { de: "Merci vilmal", tr: "çok teşekkürler (İsviçre'de yaygın)" },
    ],
    minutes: 2,
    segments: [
      { speaker: "Serviererin", text: "Grüezi! Was törfs sii?" },
      { speaker: "Elif", text: "Grüezi. Ich hett gärn en Kafi crème, bitte." },
      {
        speaker: "Serviererin",
        text: "Gärn. Möchted Si au öppis z ässe? Mir händ frischi Gipfeli.",
      },
      { speaker: "Elif", text: "Ja, es Gipfeli, bitte. Was choschtet das zäme?" },
      {
        speaker: "Serviererin",
        text: "De Kafi choschtet vier Franke füfzg und s Gipfeli äis füfzg — macht zäme sächs Franke.",
      },
      { speaker: "Elif", text: "Da sind zää Franke." },
      { speaker: "Serviererin", text: "Merci vilmal. Und vier Franke zrugg. En schööne Taag no!" },
    ],
    questions: [
      {
        text: "Was bstellt d Elif?",
        options: ["En Kafi und es Gipfeli", "Nume en Kafi", "En Tee und es Brötli"],
        answer: 0,
        explain:
          "Elif önce „en Kafi crème“, sonra „es Gipfeli“ istiyor — yani kahve ve kruvasan.",
      },
      {
        text: "Wie vil choschtet alles zäme?",
        options: ["Sächs Franke", "Vier Franke füfzg", "Zää Franke"],
        answer: 0,
        explain:
          "Garson „macht zäme sächs Franke“ diyor: 4.50 kahve + 1.50 kruvasan = 6 frank. 10 frank Elif'in verdiği para.",
      },
      {
        text: "Richtig oder falsch? D Elif zaalt mit zää Franke.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Doğru: „Da sind zää Franke“ diyor ve 4 frank para üstü alıyor.",
      },
    ],
  },
  {
    id: "zh-a1-l2",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "A de Tramhaltstell",
    genre: "Diyalog",
    intro:
      "Herr Yılmaz tramvay durağında komşusu Frau Keller ile karşılaşıyor; konuşmalarını dinleyeceksin.",
    gloss: [
      { de: "warte uf", tr: "…i beklemek" },
      { de: "d Verspaatig", tr: "rötar, gecikme (Verspätung)" },
      { de: "d Aazäig", tr: "gösterge, pano (Anzeige)" },
      { de: "go schaffe", tr: "işe (çalışmaya) gitmek" },
      { de: "d Egge", tr: "köşe" },
      { de: "näb", tr: "yanında (neben)" },
      { de: "Ade", tr: "hoşça kal (İsviçre vedası)" },
    ],
    minutes: 2,
    segments: [
      { speaker: "Frau Keller", text: "Grüezi Herr Yilmaz! Warted Si au ufs Tram?" },
      {
        speaker: "Herr Yilmaz",
        text: "Grüezi Frau Keller. Ja, ufs Tram Nummere vier, Richtig Hauptbahnhof.",
      },
      {
        speaker: "Frau Keller",
        text: "S Tram hät hüt Verspaatig — zää Minute, staat da a de Aazäig.",
      },
      { speaker: "Herr Yilmaz", text: "Oje. Ich mues am nüüni bi de Arbet sii." },
      {
        speaker: "Frau Keller",
        text: "Denn nämed Si doch de Bus Nummere 31, de fahrt au zum Hauptbahnhof.",
      },
      { speaker: "Herr Yilmaz", text: "Gueti Idee! Wo isch d Bushaltstell?" },
      { speaker: "Frau Keller", text: "Grad um d Egge, näb de Migros." },
      { speaker: "Herr Yilmaz", text: "Merci vilmal! Ade!" },
    ],
    questions: [
      {
        text: "Uf was warted d Lüüt?",
        options: ["Ufs Tram", "Uf de Zug", "Ufs Taxi"],
        answer: 0,
        explain: "İlk cümle: „Warted Si au ufs Tram?“ — ikisi de tramvay bekliyor.",
      },
      {
        text: "Wie vil Verspaatig hät s Tram?",
        options: ["Zää Minute", "Föif Minute", "E halb Stund"],
        answer: 0,
        explain: "Frau Keller „zää Minute“ diyor — panoda 10 dakika gecikme yazıyor.",
      },
      {
        text: "Richtig oder falsch? De Herr Yilmaz nimmt de Bus Nummere 31.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain:
          "Doğru: Frau Keller 31 numaralı otobüsü öneriyor, Herr Yılmaz „Gueti Idee!“ diyerek kabul ediyor.",
      },
      {
        text: "Wo isch d Bushaltstell?",
        options: ["Näb de Migros", "Am Hauptbahnhof", "Vor em Kino"],
        answer: 0,
        explain: "„Grad um d Egge, näb de Migros“ — köşeyi dönünce, Migros'un yanında.",
      },
    ],
  },

  {
    id: "zh-a1-l3",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "Uf em Märt",
    genre: "Diyalog",
    intro: "Ayşe, Bürkliplatz'taki pazarda alışveriş yapıyor. Satıcıyla konuşmasını dinleyeceksin.",
    gloss: [
      { de: "de Märt", tr: "pazar (Markt)" },
      { de: "s Rüebli", tr: "havuç" },
      { de: "s Chörbli", tr: "küçük sepet, kutu" },
      { de: "d Ärdbeeri", tr: "çilek" },
      { de: "de Peterli", tr: "maydanoz" },
      { de: "de Bund", tr: "demet" },
      { de: "bsunders", tr: "özellikle" },
    ],
    minutes: 2,
    segments: [
      { speaker: "Verchäufer", text: "Grüezi! Was törf s sii?" },
      { speaker: "Ayşe", text: "Grüezi. Ich bruuche äis Kilo Tomate und es halbs Kilo Rüebli." },
      { speaker: "Verchäufer", text: "Gärn. D Tomate sind hüt bsunders guet — die sind us em Tessin." },
      { speaker: "Ayşe", text: "Und was choschtet s Chörbli Ärdbeeri?" },
      { speaker: "Verchäufer", text: "Sibe Franke. Wänn Si zwäi nämed, choschted si zäme zwölf." },
      { speaker: "Ayşe", text: "Guet, denn nime ich zwäi Chörbli. Und äin Bund Peterli, bitte." },
      { speaker: "Verchäufer", text: "Zäme macht das nüünzää Franke füfzg." },
      { speaker: "Ayşe", text: "Da sind zwänzg. Merci!" },
    ],
    questions: [
      {
        text: "Was chauft d Ayşe?",
        options: [
          "Tomate, Rüebli, Ärdbeeri und Peterli",
          "Nume Ärdbeeri",
          "Öpfel und Härdöpfel",
        ],
        answer: 0,
        explain: "Sırayla domates, havuç, iki sepet çilek ve bir demet maydanoz alıyor.",
      },
      {
        text: "Wie vil Chörbli Ärdbeeri nimmt si?",
        options: ["Zwäi", "Äis", "Drüü"],
        answer: 0,
        explain: "„Denn nime ich zwäi Chörbli“ — iki sepet 12 franka geliyor.",
      },
      {
        text: "Wie vil zaalt si zäme?",
        options: ["Nüünzää Franke füfzg", "Zwänzg Franke", "Zwölf Franke"],
        answer: 0,
        explain: "Satıcı „macht das nüünzää Franke füfzg“ diyor; 20 frank verdiği para.",
      },
    ],
  },
  {
    id: "zh-a1-l4",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "Aaruef i de Arztpraxis",
    genre: "Telesekreter",
    intro: "Bir doktor muayenehanesinin telesekreter mesajını dinleyeceksin.",
    gloss: [
      { de: "de Aaruef", tr: "telefon araması" },
      { de: "de Termin", tr: "randevu" },
      { de: "s Rezäpt", tr: "reçete" },
      { de: "dringend", tr: "acil" },
      { de: "de Fall", tr: "durum, vaka" },
      { de: "wähle", tr: "(numara) çevirmek" },
      { de: "drucke", tr: "basmak (drücken)" },
    ],
    minutes: 2,
    segments: [
      { text: "Grüezi und härzlich willkomme i de Praxis vom Doktor Baumann." },
      {
        text: "Üsi Öffnigsziite: Määndig bis Friitig vo de achti bis am zwölfi und vo de zwäi bis am füfi. Am Mittwuch Namitag isch d Praxis zue.",
      },
      { text: "Für en Termin drucked Si d Äis. Für es Rezäpt drucked Si d Zwäi." },
      { text: "I dringende Fäll wähled Si bitte d Nummere hundertvierevierzg." },
      { text: "Merci für Ihre Aaruef und en schööne Tag." },
    ],
    questions: [
      {
        text: "Wänn isch d Praxis am Mittwuch zue?",
        options: ["Am Namitag", "Am Morge", "De ganz Tag"],
        answer: 0,
        explain: "„Am Mittwuch Namitag isch d Praxis zue“ — sadece öğleden sonra kapalı.",
      },
      {
        text: "Was mues me drucke für en Termin?",
        options: ["D Äis", "D Zwäi", "D Drüü"],
        answer: 0,
        explain: "Randevu için 1, reçete için 2 tuşlanıyor.",
      },
      {
        text: "Welli Nummere gilt i dringende Fäll?",
        options: ["144", "117", "112"],
        answer: 0,
        explain: "„d Nummere hundertvierevierzg“ = 144, İsviçre'de ambulans numarası.",
      },
    ],
  },
  {
    id: "zh-a1-l5",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "Durchsaag im Bahnhof",
    genre: "Anons",
    intro: "Zürih Hauptbahnhof'ta bir peron anonsunu dinleyeceksin.",
    gloss: [
      { de: "d Durchsaag", tr: "anons" },
      { de: "s Gläis", tr: "peron, ray" },
      { de: "d Abfaart", tr: "kalkış" },
      { de: "öppe", tr: "yaklaşık" },
      { de: "de Täil", tr: "bölüm, kısım" },
      { de: "achte uf", tr: "…e dikkat etmek" },
    ],
    minutes: 2,
    segments: [
      {
        text: "Achtung uf Gläis sibe: De Interregio uf Sanggalle, Abfaart am halbi zää, fahrt hüt vo Gläis nüün ab.",
      },
      { text: "De Zug hät öppe füf Minute Verspaatig." },
      {
        text: "Im vordere Täil vom Zug hät s Plätz i de erschte Klass, im hindere Täil i de zwäite Klass.",
      },
      { text: "Mir bitted Si, uf d Aazäige z achte. Guet Reis!" },
    ],
    questions: [
      {
        text: "Vo welem Gläis fahrt de Zug ab?",
        options: ["Vo Gläis nüün", "Vo Gläis sibe", "Vo Gläis zää"],
        answer: 0,
        explain: "Anons 7. perondan duyuruluyor ama tren „vo Gläis nüün“ kalkıyor — peron değişti.",
      },
      {
        text: "Wie vil Verspaatig hät de Zug?",
        options: ["Öppe füf Minute", "Zää Minute", "Käini"],
        answer: 0,
        explain: "„De Zug hät öppe füf Minute Verspaatig.“",
      },
      {
        text: "Richtig oder falsch? Di zwäit Klass isch im hindere Täil.",
        options: ["Richtig", "Falsch"],
        answer: 0,
        explain: "Doğru: „im hindere Täil i de zwäite Klass“.",
      },
    ],
  },
  {
    id: "zh-a1-l6",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "E Sprachnachricht vom Deniz",
    genre: "Mesaj",
    intro: "Deniz, Elif'e sesli mesaj bırakıyor. Ne istediğini dinleyeceksin.",
    gloss: [
      { de: "es bitzeli", tr: "biraz" },
      { de: "spöter", tr: "daha geç" },
      { de: "drusse", tr: "dışarıda" },
      { de: "gää", tr: "vermek (geben)" },
      { de: "Bis gliich!", tr: "Birazdan görüşürüz!" },
    ],
    minutes: 2,
    segments: [
      { speaker: "Deniz", text: "Hoi Elif, ich bi s, de Deniz." },
      {
        speaker: "Deniz",
        text: "Du, ich chume hüt es bitzeli spöter — öppe füfzää Minute. Ich bi na im Büro.",
      },
      {
        speaker: "Deniz",
        text: "Chasch du scho emal en Tisch reserviere? Am beschte drusse, s isch so schöön warm.",
      },
      { speaker: "Deniz", text: "Und bring bitte s Buech mit, wo ich der ggää ha. Ich bruuch s morn." },
      { speaker: "Deniz", text: "Bis gliich!" },
    ],
    questions: [
      {
        text: "Warum chunt de Deniz spöter?",
        options: ["Er isch na im Büro", "Er isch chrank", "S Tram hät Verspaatig"],
        answer: 0,
        explain: "„Ich bi na im Büro“ — hâlâ ofiste olduğu için gecikiyor.",
      },
      {
        text: "Was söll d Elif mache?",
        options: [
          "En Tisch reserviere und s Buech mitbringe",
          "En Kafi chaufe",
          "Im Büro verbii choo",
        ],
        answer: 0,
        explain: "İki ricası var: masa ayırtmak ve verdiği kitabı getirmek.",
      },
      {
        text: "Wie vil spöter chunt er?",
        options: ["Öppe füfzää Minute", "E halb Stund", "Zää Minute"],
        answer: 0,
        explain: "„öppe füfzää Minute“ — yaklaşık on beş dakika.",
      },
    ],
  },

  {
    id: "zh-a1-l7",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "Am Elterekafi",
    genre: "Diyalog",
    intro:
      "Hikâyenin üçüncü bölümü: Meral, anaokulunun veli kahvesinde başka bir anneyle tanışıyor.",
    gloss: [
      { de: "s Elterekafi", tr: "veli kahvesi (okulda tanışma)" },
      { de: "de Hort", tr: "okul sonrası bakım" },
      { de: "d Aamäldig", tr: "kayıt" },
      { de: "d Warteliste", tr: "bekleme listesi" },
      { de: "sich melde", tr: "başvurmak" },
      { de: "de Tipp", tr: "tavsiye" },
      { de: "nöi da", tr: "yeni gelmiş" },
    ],
    minutes: 3,
    segments: [
      { speaker: "Sandra", text: "Grüezi! Sind Si au nöi da? Ich han Si na nie gseh." },
      { speaker: "Meral", text: "Grüezi. Ja, min Sohn hät letschti Wuche aagfange. Ich bi d Meral." },
      { speaker: "Sandra", text: "Sandra. Mini Tochter isch scho s zwäite Jaar da. Wie gaat s em Chliine?" },
      {
        speaker: "Meral",
        text: "Guet, glaub ich. Er redt na nöd vill Tüütsch. Ich mach mer es bitzeli Sorge.",
      },
      {
        speaker: "Sandra",
        text: "Das gaat schnäll. Mini Tochter hät im Auguscht käis Wort gredt und im Dezämber hät si mich korrigiert.",
      },
      { speaker: "Meral", text: "Wörkli?" },
      {
        speaker: "Sandra",
        text: "Wörkli. Aber ich gib Ine en Tipp: Mälded Si sich für de Hort aa, au wänn Si en jetz nöd bruuched.",
      },
      { speaker: "Meral", text: "Warum?" },
      {
        speaker: "Sandra",
        text: "D Warteliste isch lang. Wär im Auguscht aafangt, mues sich im Januar mälde. Das säit eim niemert.",
      },
      { speaker: "Meral", text: "Merci vilmal. Das han ich würkli nöd gwüsst." },
    ],
    questions: [
      {
        text: "Sit wänn isch de Sohn vo de Meral im Chindsgi?",
        options: ["Sit letschter Wuche", "Sit eme Jaar", "Sit Auguscht"],
        answer: 0,
        explain: "„min Sohn hät letschti Wuche aagfange.“",
      },
      {
        text: "Was macht de Meral Sorge?",
        options: [
          "Ihre Sohn redt na nöd vill Tüütsch",
          "De Chindsgi isch z wiit",
          "Es Znüni fählt",
        ],
        answer: 0,
        explain: "„Er redt na nöd vill Tüütsch. Ich mach mer es bitzeli Sorge.“",
      },
      {
        text: "Was verzellt d Sandra über ihri Tochter?",
        options: [
          "Im Auguscht käis Wort, im Dezämber hät si korrigiert",
          "Si redt na immer nöd",
          "Si hät zwäi Jaar bruucht",
        ],
        answer: 0,
        explain: "Meral'i rahatlatmak için verdiği örnek.",
      },
      {
        text: "Welle Tipp git d Sandra?",
        options: [
          "Sich früeh für de Hort aamälde",
          "Meh Tüütsch dihäi rede",
          "En andere Chindsgi sueche",
        ],
        answer: 0,
        explain: "Ağustosta başlayan, ocakta kaydolmalı — „Das säit eim niemert.“",
      },
    ],
  },
  {
    id: "zh-a1-l8",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "A de Kasse",
    genre: "Diyalog",
    intro: "Coop kasasında bir konuşma — İsviçre'de günde bir kez duyduğun cümleler.",
    gloss: [
      { de: "s Sackli", tr: "poşet" },
      { de: "d Kasse", tr: "kasa" },
      { de: "s Kleingäld", tr: "bozuk para" },
      { de: "de Bon", tr: "fiş" },
      { de: "s Twint", tr: "İsviçre'nin telefonla ödeme uygulaması" },
      { de: "d Superkarte", tr: "market puan kartı" },
      { de: "iipacke", tr: "poşete koymak" },
    ],
    minutes: 2,
    segments: [
      { speaker: "Kassiererin", text: "Grüezi. Händ Si e Superkarte?" },
      { speaker: "Meral", text: "Grüezi. Nei, han ich nöd." },
      { speaker: "Kassiererin", text: "Bruuched Si es Sackli?" },
      { speaker: "Meral", text: "Ja, äis bitte." },
      { speaker: "Kassiererin", text: "Das macht denn füfeddriissg Franke zwänzg." },
      { speaker: "Meral", text: "Cha ich mit Twint zaale?" },
      { speaker: "Kassiererin", text: "Sicher. Do isch de Code." },
      { speaker: "Meral", text: "So … es hät klappt." },
      { speaker: "Kassiererin", text: "Perfäkt. Wänd Si de Bon?" },
      { speaker: "Meral", text: "Nei, merci. Schöne Tag!" },
    ],
    questions: [
      {
        text: "Was fröget d Kassiererin als Erschts?",
        options: ["Öb si e Superkarte hät", "Öb si es Sackli wott", "Wie si zaalt"],
        answer: 0,
        explain: "„Händ Si e Superkarte?“ — İsviçre kasalarının ilk sorusu.",
      },
      {
        text: "Wie vil choschtet alles?",
        options: ["35.20", "25.20", "53.20"],
        answer: 0,
        explain: "„füfeddriissg Franke zwänzg“ = 35,20.",
      },
      {
        text: "Wie zaalt d Meral?",
        options: ["Mit Twint", "Bar", "Mit Karte"],
        answer: 0,
        explain: "„Cha ich mit Twint zaale?“ — İsviçre'nin telefon ödemesi.",
      },
    ],
  },
  {
    id: "zh-a1-l9",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "Drüü Durchsäge",
    genre: "Sınav formatı",
    intro:
      "Üç kısa anons, her birine bir soru. Anonslar birbirinden bağımsız — her birini ayrı dinleyebilirsin.",
    gloss: [
      { de: "d Durchsaag", tr: "anons" },
      { de: "s Gläis", tr: "peron" },
      { de: "d Verspaatig", tr: "gecikme" },
      { de: "zue", tr: "kapalı" },
      { de: "s Aagebot", tr: "kampanya" },
      { de: "de Iigang", tr: "giriş" },
      { de: "verlore", tr: "kayıp" },
    ],
    minutes: 3,
    segments: [
      {
        speaker: "Durchsaag 1",
        text: "Achtung uf Gläis füf: De Zug uf Winterthur, Abfaart am zwölfi zwänzg, hät hüt öppe zää Minute Verspaatig.",
      },
      {
        speaker: "Durchsaag 2",
        text: "Liebi Chundschaft, üse Lade schlüsst hüt scho am sächsi, nöd am achti. Bitte chömed Si a d Kasse. Morn sind mir wider normal für Si da.",
      },
      {
        speaker: "Durchsaag 3",
        text: "Mir händ es chliises Mäitli gfunde, öppe vier Jaar alt, rot Jagge. Es wartet bim Iigang Nord näb de Information.",
      },
    ],
    questions: [
      {
        text: "Durchsaag 1: Wänn fahrt de Zug öppe?",
        options: ["Am halbi äis", "Am zwölfi zwänzg", "Am zäni"],
        answer: 0,
        explain: "12:20 + yaklaşık 10 dakika = yaklaşık 12:30.",
      },
      {
        text: "Durchsaag 2: Was isch hüt anders?",
        options: [
          "De Lade schlüsst zwo Stund früener",
          "De Lade isch zue",
          "De Lade hät lenger offe",
        ],
        answer: 0,
        explain: "„am sächsi, nöd am achti“ — iki saat erken.",
      },
      {
        text: "Durchsaag 3: Wo wartet s Chind?",
        options: ["Bim Iigang Nord", "A de Kasse", "Uf Gläis füf"],
        answer: 0,
        explain: "„Es wartet bim Iigang Nord näb de Information.“",
      },
    ],
  },
  {
    id: "zh-a1-l10",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "Was isch en Apéro?",
    genre: "Kültür",
    intro:
      "İsviçre'de her davetin adı: Apéro. Ne demek, ne zaman biter, ne giyilir — kısa bir açıklama.",
    gloss: [
      { de: "de Apéro", tr: "içki-atıştırmalık buluşması" },
      { de: "s Salzstängeli", tr: "tuzlu çubuk kraker" },
      { de: "aastoosse", tr: "kadeh kaldırmak" },
      { de: "s Ässe", tr: "yemek" },
      { de: "stoo", tr: "ayakta durmak" },
      { de: "pünktlich", tr: "dakik" },
      { de: "nachhär", tr: "sonrasında" },
    ],
    minutes: 3,
    segments: [
      { speaker: "Meral", text: "Sandra, ich bi zu me Apéro iiglade. Was isch das genau?" },
      {
        speaker: "Sandra",
        text: "Es isch käis Ässe. Me trinkt öppis, isst chliini Sache — Salzstängeli, Chääs, Oliven — und me staat.",
      },
      { speaker: "Meral", text: "Me sitzt nöd?" },
      { speaker: "Sandra", text: "Mäischtens nöd. Drum cha me au äifach vo eim zum andere gaa." },
      { speaker: "Meral", text: "Und wie lang gaat das?" },
      {
        speaker: "Sandra",
        text: "Öppe zwo Stund. Wänn s am sibni aafangt, isch s am nüüni fertig — und denn isch s würkli fertig.",
      },
      { speaker: "Meral", text: "Mues ich öppis mitbringe?" },
      { speaker: "Sandra", text: "E Flasche Wii isch immer richtig. Aber niemert erwartet s." },
      { speaker: "Meral", text: "Und pünktlich?" },
      {
        speaker: "Sandra",
        text: "Ja. Nöd zwänzg Minute z spaat wie a de Party — bim Apéro chunt me pünktlich.",
      },
    ],
    questions: [
      {
        text: "Isch en Apéro es Ässe?",
        options: ["Nei, nur chliini Sache", "Ja, es grosses Ässe", "Nur am Mittag"],
        answer: 0,
        explain: "„Es isch käis Ässe“ — küçük şeyler ve içecek.",
      },
      {
        text: "Sitzt me bim Apéro?",
        options: ["Mäischtens nöd", "Immer", "Nur am Aafang"],
        answer: 0,
        explain: "Ayakta olduğu için insanlar arasında dolaşmak kolay.",
      },
      {
        text: "Wie lang duuret er?",
        options: ["Öppe zwo Stund", "De ganz Aabig", "E halbi Stund"],
        answer: 0,
        explain: "Yedide başlarsa dokuzda biter — ve gerçekten biter.",
      },
      {
        text: "Wie isch s mit de Pünktlichkäit?",
        options: [
          "Me chunt pünktlich",
          "Me chunt zwänzg Minute spöter",
          "Es spielt käi Rolle",
        ],
        answer: 0,
        explain: "Partiden farkı tam burada: Apéro'ya dakik gelinir.",
      },
    ],
  },
  {
    id: "zh-a1-l11",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "En Termin bim Zaanarzt",
    genre: "Telefon",
    intro: "Diş hekiminden randevu almak — telefonda ilk yapılan konuşmalardan biri.",
    gloss: [
      { de: "de Zaanarzt", tr: "diş hekimi" },
      { de: "d Zaanweh", tr: "diş ağrısı" },
      { de: "de Termin", tr: "randevu" },
      { de: "dringend", tr: "acil" },
      { de: "d Kontroll", tr: "kontrol" },
      { de: "vorbiicho", tr: "uğramak" },
      { de: "d Versicherigskarte", tr: "sigorta kartı" },
    ],
    minutes: 3,
    segments: [
      { speaker: "Praxis", text: "Zaanarztpraxis Meier, grüezi." },
      {
        speaker: "Meral",
        text: "Grüezi. Ich hett gärn en Termin. Ich han sit gescht Zaanweh.",
      },
      { speaker: "Praxis", text: "Isch es starch?" },
      { speaker: "Meral", text: "Am Aabig isch es schlimmer. Ich han schlächt gschlaafe." },
      {
        speaker: "Praxis",
        text: "Denn nämed mir Si hüt. Chönd Si am halbi drüü choo?",
      },
      { speaker: "Meral", text: "Ja, das gaat." },
      {
        speaker: "Praxis",
        text: "Guet. Sind Si scho emal bi eus gsii?",
      },
      { speaker: "Meral", text: "Nei, s isch s erschte Mal." },
      {
        speaker: "Praxis",
        text: "Denn bringed Si bitte d Versicherigskarte mit und chömed Si zää Minute früener — s git es Formular.",
      },
      { speaker: "Meral", text: "Alles klar. Merci vilmal!" },
    ],
    questions: [
      {
        text: "Warum rüeft d Meral aa?",
        options: ["Si hät Zaanweh", "Si wott e Kontroll", "Si wott en Termin absäge"],
        answer: 0,
        explain: "„Ich han sit gescht Zaanweh.“",
      },
      {
        text: "Wänn cha si choo?",
        options: ["Hüt am halbi drüü", "Morn am drüü", "Nächschti Wuche"],
        answer: 0,
        explain: "Ağrı şiddetli olduğu için aynı gün alıyorlar.",
      },
      {
        text: "Was mues si mitbringe?",
        options: ["D Versicherigskarte", "Es Rezäpt", "Gäld"],
        answer: 0,
        explain: "İlk kez geldiği için ayrıca on dakika erken gelmesi isteniyor.",
      },
      {
        text: "Warum söll si früener choo?",
        options: ["Wäge eme Formular", "Well d Praxis voll isch", "Well s Tram spaat isch"],
        answer: 0,
        explain: "„s git es Formular.“",
      },
    ],
  },
  {
    id: "zh-a1-l12",
    course: "gsw-zh",
    level: "A1",
    skill: "listening",
    title: "Meral rüeft d Frau Suter aa",
    genre: "Telefon",
    intro:
      "Hikâyenin dördüncü bölümü: Meral, öğretmenin notuna telefonla cevap veriyor.",
    gloss: [
      { de: "de Ussflug", tr: "gezi" },
      { de: "mitcho", tr: "birlikte gelmek" },
      { de: "d Jagge", tr: "mont" },
      { de: "s Gummistifeli", tr: "yağmur çizmesi" },
      { de: "sich fröie", tr: "sevinmek" },
      { de: "de Rucksack", tr: "sırt çantası" },
      { de: "Merci vilmal", tr: "çok teşekkürler" },
    ],
    minutes: 3,
    segments: [
      { speaker: "Frau Suter", text: "Chindsgi Hardau, Suter." },
      { speaker: "Meral", text: "Grüezi Frau Suter, do isch d Meral Yıldız, d Mueter vom Kerem." },
      { speaker: "Frau Suter", text: "Grüezi Frau Yıldız! Sie händ min Zettel gläse?" },
      {
        speaker: "Meral",
        text: "Ja, merci. De Kerem chunt gärn am Ussflug mit. Ich han au d Jagge gfunde — si isch under em Bett gsii.",
      },
      { speaker: "Frau Suter", text: "Perfäkt. Denn schriib ich en uf d Lischte." },
      { speaker: "Meral", text: "Bruucht er Gummistifeli? Mir händ käini." },
      {
        speaker: "Frau Suter",
        text: "Wär ideal, aber alti Schueh gönd au. Mir händ im Chindsgi zwäi Paar zum Uusleihe — welli Grössi hät er?",
      },
      { speaker: "Meral", text: "Vierezwänzg." },
      { speaker: "Frau Suter", text: "Das passt. Ich leg s bereit." },
      {
        speaker: "Meral",
        text: "Merci vilmal. Und … danke au für das, wo Si über s Rede gschriibe händ. Das hät mer guet taa.",
      },
      { speaker: "Frau Suter", text: "Das han ich gärn gschriibe. Es stimmt ja." },
    ],
    questions: [
      {
        text: "Warum rüeft d Meral aa?",
        options: [
          "Zum säge, dass de Kerem am Ussflug mitchunt",
          "Zum de Ussflug absäge",
          "Wäge em Znüni",
        ],
        answer: 0,
        explain: "„De Kerem chunt gärn am Ussflug mit.“",
      },
      {
        text: "Wo isch d Jagge gsii?",
        options: ["Under em Bett", "Im Chindsgi", "Im Rucksack"],
        answer: 0,
        explain: "„si isch under em Bett gsii.“",
      },
      {
        text: "Was macht d Frau Suter wäge de Gummistifeli?",
        options: [
          "Si leit es Paar zum Uusleihe bereit",
          "Si säit, er cha nöd mitcho",
          "Si chauft neui",
        ],
        answer: 0,
        explain: "Anaokulunda ödünç iki çift var; 24 numara uyuyor.",
      },
      {
        text: "Wofür bedankt sich d Meral am Schluss?",
        options: [
          "Für das, wo d Lehrerin über s Rede gschriibe hät",
          "Für d Gummistifeli",
          "Für de Ussflug",
        ],
        answer: 0,
        explain: "„Das hät mer guet taa.“ — notun üçüncü maddesi.",
      },
    ],
  },

  // ─────────────────────────── YAZMA ───────────────────────────
  {
    id: "zh-a1-w1",
    course: "gsw-zh",
    level: "A1",
    skill: "writing",
    title: "Sich vorstelle",
    genre: "Tanışma",
    intro:
      "Kendini lehçeyle tanıtmayı çalışacaksın: önce cümleler kur, sonra kısa bir grup mesajı yaz.",
    gloss: [
      { de: "häisse", tr: "adında olmak (heißen)" },
      { de: "choo us", tr: "…den gelmek, …li olmak (ich chume us …)" },
      { de: "wohne z", tr: "…de oturmak (z Züri = Zürih'te)" },
      { de: "schaffe als", tr: "… olarak çalışmak (arbeiten yerine)" },
      { de: "s Hobby", tr: "hobi" },
    ],
    minutes: 6,
    tasks: [
      {
        kind: "build",
        tr: "Benim adım Elif ve Türkiye'den geliyorum.",
        answer: "Ich häisse Elif und chume us de Türkei.",
        hint: "heißen lehçede häisse; kommen fiilinin şimdiki hali: ich chume.",
      },
      {
        kind: "build",
        tr: "Zürih'te oturuyorum ve tramvayla işe gidiyorum.",
        answer: "Ich wohne z Züri und gaa mit em Tram go schaffe.",
        alternatives: ["Ich wohne z Züri und gaa go schaffe mit em Tram."],
        hint: "z Züri = Zürih'te; «go schaffe» kalıbı: işe/çalışmaya gitmek.",
      },
      {
        kind: "build",
        tr: "Öğretmen olarak çalışıyorum.",
        answer: "Ich schaffe als Lehrerin.",
        hint: "arbeiten yerine lehçede schaffe kullanılır; meslek söylerken «als», artikel gerekmez.",
      },
      {
        kind: "free",
        prompt:
          "Zürih'teki dil kursunun grup sohbetine kendini lehçeyle tanıtan kısa bir mesaj yaz. Şu üç noktaya değin: adın ve nereli olduğun, nerede oturduğun, işin veya hobin.",
        checklist: [
          "Selamlama ile başladın mı? (Hoi zäme!)",
          "Üç içerik noktasının hepsine değindin mi: isim ve memleket, oturduğun yer, iş veya hobi?",
          "Lehçe biçimlerini kullandın mı? (ich bi, ich ha, ich chume, ich schaffe)",
          "Veda ile bitirdin mi? (Bis bald! / Ade!)",
        ],
        minWords: 20,
        phrases: [
          { de: "Ich häisse …", tr: "Benim adım …" },
          { de: "Ich chume us …", tr: "…den geliyorum / …liyim" },
          { de: "Ich wohne z …", tr: "…de oturuyorum" },
          { de: "Ich schaffe als …", tr: "… olarak çalışıyorum" },
          { de: "Mis Hobby isch …", tr: "Hobim …" },
          { de: "Bis bald!", tr: "Görüşürüz!" },
        ],
        sample:
          "Hoi zäme! Ich häisse Emre und chume us de Türkei, us Ankara. Jetz wohne ich z Züri, im Chreis 5. Ich schaffe als Ingenieur. Mini Hobbys sind Fuessball und Choche. Ich lerne Züritüütsch für de Alltag. Bis bald! Emre",
      },
    ],
  },
  {
    id: "zh-a1-w2",
    course: "gsw-zh",
    level: "A1",
    skill: "writing",
    title: "E Nachricht an en Kolleg",
    genre: "Mesaj",
    intro:
      "Bir buluşmayı ertelemeyi lehçeyle yazacaksın: önce cümleler kur, sonra kısa bir mesaj yaz.",
    gloss: [
      { de: "läider", tr: "maalesef (leider)" },
      { de: "chrank", tr: "hasta" },
      { de: "d Ziit", tr: "vakit, zaman" },
      { de: "passe", tr: "uymak (bir zaman için)" },
      { de: "Bschäid gää", tr: "haber vermek" },
    ],
    minutes: 6,
    tasks: [
      {
        kind: "build",
        tr: "Bugün maalesef gelemiyorum, hastayım.",
        answer: "Ich cha hüt läider nöd choo, ich bi chrank.",
        hint: "können lehçede chöne olur: ich cha. kommen → choo, nicht → nöd.",
      },
      {
        kind: "build",
        tr: "Yarın öğleden sonra vaktin var mı?",
        answer: "Häsch du morn am Namitag Ziit?",
        alternatives: ["Häsch du morn Namitag Ziit?"],
        hint: "haben → haa: du häsch. Nachmittag lehçede Namitag.",
      },
      {
        kind: "build",
        tr: "Sana akşam yazarım.",
        answer: "Ich schriibe der am Aabig.",
        hint: "schreiben → schriibe (uzun i çift yazılır), dir → der, Abend → Aabig.",
      },
      {
        kind: "free",
        prompt:
          "Bir arkadaşına lehçeyle kısa bir mesaj yaz: bugünkü buluşmayı erteliyorsun. Üç noktaya değin: gelemeyeceğin, nedeni, yeni bir gün önerisi.",
        checklist: [
          "Selamlama ile başladın mı? (Hoi …!)",
          "Gelemeyeceğini ve nedenini yazdın mı?",
          "Yeni bir gün/saat önerdin mi?",
          "Lehçe biçimleri kullandın mı? (ich cha, ich mues, mir chönted)",
        ],
        minWords: 25,
        phrases: [
          { de: "Ich cha läider nöd choo.", tr: "Maalesef gelemiyorum." },
          { de: "Ich mues lenger schaffe.", tr: "Daha uzun çalışmam gerek." },
          { de: "Passt s der am …?", tr: "… sana uyar mı?" },
          { de: "Mir chönted üs … träffe.", tr: "… buluşabiliriz." },
          { de: "Gib mer churz Bschäid.", tr: "Kısaca haber ver." },
        ],
        sample:
          "Hoi Murat! Sorry, ich cha hüt am Aabig läider nöd choo — ich mues lenger schaffe. Passt s der am Friitig am sächsi? Mir chönted üs bim Bellevue träffe und nachhär öppis go ässe. Gib mer churz Bschäid. Liebi Grüess, Elif",
      },
    ],
  },
  {
    id: "zh-a1-w3",
    course: "gsw-zh",
    level: "A1",
    skill: "writing",
    title: "Iichaufe und Ässe",
    genre: "Günlük yaşam",
    intro: "Alışveriş ve yemek konusunu lehçeyle yazacaksın.",
    gloss: [
      { de: "chaufe", tr: "satın almak (kaufen)" },
      { de: "de Zmorge", tr: "kahvaltı (Frühstück)" },
      { de: "de Chääs", tr: "peynir (Käse)" },
      { de: "choche", tr: "yemek pişirmek" },
      { de: "de Znacht", tr: "akşam yemeği" },
      { de: "d Iichaufsliste", tr: "alışveriş listesi" },
    ],
    minutes: 6,
    tasks: [
      {
        kind: "build",
        tr: "Süt ve ekmek almam lazım.",
        answer: "Ich mues Milch und Brot chaufe.",
        hint: "müssen → müesse: ich mues. kaufen söz başındaki k yüzünden chaufe olur.",
      },
      {
        kind: "build",
        tr: "Kahvaltıda çoğunlukla peynirli ekmek yerim.",
        answer: "Zum Zmorge iss ich meischtens es Brot mit Chääs.",
        alternatives: ["Zum Zmorge iss ich meischtens Brot mit Chääs."],
        hint: "Frühstück → Zmorge, Käse → Chääs, meistens → meischtens (st → scht).",
      },
      {
        kind: "build",
        tr: "Bu akşam bize gelmek ister misin? Bir şeyler pişireceğim.",
        answer: "Wottsch du hüt am Aabig zu üs choo? Ich choche öppis.",
        hint: "wollen → wölle: du wottsch. etwas → öppis, kochen → choche.",
      },
      {
        kind: "free",
        prompt:
          "Bir arkadaşını akşam yemeğine davet eden kısa bir mesaj yaz. Üç noktaya değin: davet, ne pişireceğin, saat. İstersen ne alması gerektiğini de yaz.",
        checklist: [
          "Daveti açıkça yazdın mı?",
          "Ne pişireceğini söyledin mi?",
          "Saati belirttin mi? (am sächsi, am halbi sibni …)",
          "Lehçe biçimleri kullandın mı? (ich choche, wottsch du, mir ässed)",
        ],
        minWords: 25,
        phrases: [
          { de: "Chunsch du zum Znacht?", tr: "Akşam yemeğine gelir misin?" },
          { de: "Ich choche …", tr: "… pişiriyorum." },
          { de: "Mir ässed am …", tr: "Saat …'de yiyoruz." },
          { de: "Bring doch … mit.", tr: "… getirsene." },
          { de: "Ich fröie mi!", tr: "Sevinirim / dört gözle bekliyorum!" },
        ],
        sample:
          "Hoi Sara! Chunsch du am Friitig zum Znacht zu mir? Ich choche öppis us de Türkei — Linsesuppe und Reis mit Gmües. Mir ässed am halbi sibni. Wänn du wottsch, bring doch en Salaat mit. Säg mer bis am Dunschtig Bschäid. Ich fröie mi! Elif",
      },
    ],
  },
  {
    id: "zh-a1-w4",
    course: "gsw-zh",
    level: "A1",
    skill: "writing",
    title: "Mini Wohnig, min Alltag",
    genre: "Günlük yaşam",
    intro: "Evini ve günlük düzenini lehçeyle anlatacaksın.",
    gloss: [
      { de: "d Wohnig", tr: "daire" },
      { de: "ufschtaa", tr: "kalkmak (aufstehen)" },
      { de: "viertel ab", tr: "…i çeyrek geçe" },
      { de: "dihäi", tr: "evde" },
      { de: "läse", tr: "okumak (ich lise)" },
      { de: "de Feierabig", tr: "iş sonrası, mesai sonu" },
    ],
    minutes: 6,
    tasks: [
      {
        kind: "build",
        tr: "Zürih'te küçük bir dairede oturuyorum.",
        answer: "Ich wohne z Züri i ere chliine Wohnig.",
        hint: "in einer → i ere; klein → chlii (söz başı k → ch).",
      },
      {
        kind: "build",
        tr: "Sabah yediyi çeyrek geçe kalkarım.",
        answer: "Ich schtaa am viertel ab sibni uf.",
        alternatives: ["Am Morge schtaa ich am viertel ab sibni uf."],
        hint: "aufstehen ayrılabilir: ich schtaa … uf. Saat: viertel ab sibni = 7.15.",
      },
      {
        kind: "build",
        tr: "Akşamları çoğunlukla evdeyim ve kitap okurum.",
        answer: "Am Aabig bin ich meischtens dihäi und lise es Buech.",
        hint: "zu Hause → dihäi; lesen → läse, ich lise. Buch → Buech.",
      },
      {
        kind: "free",
        prompt:
          "Bir gününü lehçeyle anlat. Üç noktaya değin: kaçta kalkıp ne yaptığın, gün içinde nereye gittiğin, akşamları ne yapmayı sevdiğin.",
        checklist: [
          "Sabah rutinini yazdın mı?",
          "Gün içinde nereye gittiğini yazdın mı? (go schaffe, i d Schuel …)",
          "Akşamları ne yaptığını yazdın mı?",
          "Saat ifadelerini lehçeyle kullandın mı? (am sibni, am halbi achti)",
        ],
        minWords: 30,
        phrases: [
          { de: "Ich schtaa am … uf.", tr: "Saat …'de kalkarım." },
          { de: "Zum Zmorge iss ich …", tr: "Kahvaltıda … yerim." },
          { de: "Ich gaa mit em Tram go schaffe.", tr: "İşe tramvayla giderim." },
          { de: "Am Namitag …", tr: "Öğleden sonra …" },
          { de: "Am Aabig bin ich dihäi.", tr: "Akşamları evdeyim." },
        ],
        sample:
          "Ich schtaa am viertel ab sibni uf. Zum Zmorge iss ich es Brot mit Chääs und trinke en Kafi. Denn gaa ich mit em Tram Nummere 11 go schaffe. Am Mittag iss ich mit mine Kollege i de Kantine. Am Namitag gaa ich no schnäll i d Migros. Am Aabig bin ich meischtens dihäi: ich choche öppis, lise es Buech oder lueg e Serie. Am Samschtig gaa ich gärn an See.",
      },
    ],
  },
  {
    id: "zh-a1-w5",
    course: "gsw-zh",
    level: "A1",
    skill: "writing",
    title: "E Entschuldigung für de Chindsgi",
    genre: "Resmî yazı",
    intro:
      "Çocuğun okula gitmediği her gün yazılan kısa not. Lehçede yazılır ama kibar biçimi vardır.",
    gloss: [
      { de: "chrank", tr: "hasta" },
      { de: "s Fieber", tr: "ateş" },
      { de: "fääle", tr: "gelmemek, devamsızlık" },
      { de: "entschuldige", tr: "mazur görmek" },
      { de: "hoffentlich", tr: "umarım" },
      { de: "d Unterschrift", tr: "imza" },
    ],
    minutes: 6,
    tasks: [
      {
        kind: "build",
        tr: "Oğlum Kerem bugün hasta.",
        answer: "Min Sohn Kerem isch hüt chrank.",
        hint: "mein → min; ist → isch; krank → chrank (söz başı k → ch).",
      },
      {
        kind: "build",
        tr: "Ateşi var ve Chindsgi'ye gelemiyor.",
        answer: "Er hät Fieber und cha nöd in Chindsgi choo.",
        hint: "haben → haa: er hät. können → chöne: er cha. kommen → choo.",
      },
      {
        kind: "build",
        tr: "Lütfen bugünkü devamsızlığını mazur görün.",
        answer: "Bitte entschuldiged Si sis Fääle hüt.",
        hint: "Nezaket biçimi: entschuldiged Si. sein (onun) → sis.",
      },
      {
        kind: "free",
        prompt:
          "Anaokulu öğretmenine kısa bir mazeret notu yaz. Dört noktaya değin: hitap, çocuğun adı, neden gelmediği ve hangi gün(ler), kapanış ve imza.",
        checklist: [
          "Hitapla başladın mı? (Liebi Frau …)",
          "Çocuğun adını yazdın mı?",
          "Nedeni ve günü yazdın mı?",
          "Lehçe biçimlerini kullandın mı? (isch, hät, cha)",
          "İsim ve tarihle bitirdin mi?",
        ],
        minWords: 25,
        phrases: [
          { de: "Liebi Frau …", tr: "Sayın … Hanım," },
          { de: "Min Sohn / Mini Tochter …", tr: "Oğlum / kızım …" },
          { de: "isch sit gescht chrank", tr: "dünden beri hasta" },
          { de: "Bitte entschuldiged Si …", tr: "Lütfen … mazur görün." },
          { de: "Fründlichi Grüess", tr: "Saygılarımla" },
        ],
        sample:
          "Liebi Frau Suter\n\nMin Sohn Kerem isch sit gescht chrank. Er hät Fieber und cha hüt und morn nöd in Chindsgi choo. Bitte entschuldiged Si sis Fääle.\n\nAm Dunschtig isch er hoffentlich wider da.\n\nFründlichi Grüess\nMeral Yıldız\n14. Mai",
      },
    ],
  },
  {
    id: "zh-a1-w6",
    course: "gsw-zh",
    level: "A1",
    skill: "writing",
    title: "Aamäldig und churzi Nachricht",
    genre: "Sınav formatı",
    intro:
      "İki tipik görev: kısa bilgi alanlarını doldurmak ve üç noktaya değinen kısa bir mesaj yazmak.",
    gloss: [
      { de: "s Formular", tr: "form" },
      { de: "de Familiename", tr: "soyadı" },
      { de: "de Vorname", tr: "ad" },
      { de: "d Aamäldig", tr: "kayıt" },
      { de: "de Kurs", tr: "kurs" },
      { de: "d Ziit haa", tr: "vakti olmak" },
      { de: "de Priis", tr: "fiyat" },
    ],
    minutes: 7,
    tasks: [
      {
        kind: "build",
        tr: "Bir Züritüütsch kursuna kaydolmak istiyorum.",
        answer: "Ich möcht mich für en Züritüütsch-Kurs aamälde.",
        hint: "sich anmelden für → sich aamälde für; „mich“ fiilden sonra gelir.",
      },
      {
        kind: "build",
        tr: "Akşamları altıdan sonra vaktim var.",
        answer: "Am Aabig nach de sächsi han ich Ziit.",
        alternatives: ["Ich han am Aabig nach de sächsi Ziit."],
        hint: "Abend → Aabig; saat: nach de sächsi.",
      },
      {
        kind: "build",
        tr: "Lütfen bana fiyatı yazın.",
        answer: "Schriibed Si mer bitte de Priis.",
        hint: "Nezaket emri: fiil başta, Si arkasında; mir → mer.",
      },
      {
        kind: "free",
        prompt:
          "Bir dil okuluna kısa bir e-posta yaz. Üç noktaya değin: hangi kursa kaydolmak istediğin, hangi gün ve saatlerde vaktin olduğu, öğrenmek istediğin bir bilgi (fiyat, süre veya başlangıç tarihi).",
        checklist: [
          "Selamlama ve kapanış var mı?",
          "Üç noktanın hepsine değindin mi?",
          "Bir soru sordun mu?",
          "Lehçe biçimleri kullandın mı? (ich möcht, han ich, chönd Si)",
          "Adını yazdın mı?",
        ],
        minWords: 30,
        phrases: [
          { de: "Grüezi mitenand,", tr: "Merhaba," },
          { de: "Ich möcht mich für … aamälde.", tr: "… için kaydolmak istiyorum." },
          { de: "Am … han ich Ziit.", tr: "… günü vaktim var." },
          { de: "Was choschtet de Kurs?", tr: "Kurs ne kadar?" },
          { de: "Wänn fangt er aa?", tr: "Ne zaman başlıyor?" },
          { de: "Merci vilmal und liebi Grüess", tr: "Teşekkürler, sevgiler" },
        ],
        sample:
          "Grüezi mitenand\n\nIch möcht mich für en Züritüütsch-Kurs für Aafänger aamälde. Ich schaffe bis am füfi, drum han ich nur am Aabig nach de sächsi Ziit — am beschte am Määndig oder Mittwuch.\n\nWas choschtet de Kurs und wänn fangt er aa? Schriibed Si mer bitte au, wie lang er duuret.\n\nMerci vilmal und liebi Grüess\nMeral Yıldız",
      },
    ],
  },
  {
    id: "zh-a1-w7",
    course: "gsw-zh",
    level: "A1",
    skill: "writing",
    title: "S Znüni erkläre",
    genre: "Kültür",
    intro:
      "Ülkendeki bir arkadaşına İsviçre'deki günlük bir âdeti anlatacaksın — kültürü anlatmak, dili en çok geliştiren yazma türüdür.",
    gloss: [
      { de: "erkläre", tr: "açıklamak" },
      { de: "s Znüni", tr: "kuşluk yemeği" },
      { de: "d Pause", tr: "mola" },
      { de: "zäme", tr: "birlikte" },
      { de: "anders", tr: "farklı" },
      { de: "bi eus", tr: "bizde" },
      { de: "komisch", tr: "tuhaf, garip" },
    ],
    minutes: 6,
    tasks: [
      {
        kind: "build",
        tr: "İsviçre'de saat dokuzda bir mola var.",
        answer: "I de Schwiiz git s am nüüni e Pause.",
        hint: "es gibt → git s; saat: am nüüni.",
      },
      {
        kind: "build",
        tr: "Herkes bir şeyler yer — buna Znüni denir.",
        answer: "Alli ässed öppis — das häisst Znüni.",
        hint: "etwas → öppis; heißen → häisse.",
      },
      {
        kind: "build",
        tr: "Başlangıçta bu bana tuhaf geldi.",
        answer: "Am Aafang isch mer das komisch vorcho.",
        hint: "vorkommen → vorcho; Perfekt: isch … vorcho.",
      },
      {
        kind: "free",
        prompt:
          "Ülkendeki bir arkadaşına İsviçre'den bir âdeti anlat (Znüni, Apéro, Samichlaus, pazar sessizliği — kendin seç). Dört noktaya değin: âdet nedir, ne zaman olur, insanlar ne yapar, senin ilk tepkin ve bugün ne düşündüğün.",
        checklist: [
          "Âdeti kısaca tanımladın mı?",
          "Zamanını yazdın mı?",
          "İnsanların ne yaptığını yazdın mı?",
          "Kendi tepkini yazdın mı?",
          "Selamlama ve kapanış var mı?",
        ],
        minWords: 30,
        phrases: [
          { de: "Bi eus i de Schwiiz git s …", tr: "Bizde, İsviçre'de … var." },
          { de: "Das isch am …", tr: "Bu … zamanında olur." },
          { de: "D Lüüt …", tr: "İnsanlar …" },
          { de: "Am Aafang han ich das komisch gfunde.", tr: "Başta tuhaf bulmuştum." },
          { de: "Hüt find ich s guet.", tr: "Bugün iyi buluyorum." },
        ],
        sample:
          "Hoi Zeynep\n\nIch verzell der öppis us de Schwiiz. Bi eus git s am nüüni e chliini Pause — au i de Schuel, au im Gschäft. Das häisst Znüni.\n\nAlli ässed denn öppis Chliises: es Brot, en Öpfel, es Jogurt. D Chind händ s im Rucksack, d Erwachsene gönd zäme i d Kantine oder stönd i de Chuchi.\n\nAm Aafang isch mer das komisch vorcho — ich han doch am achti Zmorge gha! Hüt find ich s aber guet: me redt zää Minute mit de Lüüt, und denn schaffed alli wider.\n\nLiebi Grüess\nMeral",
      },
    ],
  },
  {
    id: "zh-a1-w8",
    course: "gsw-zh",
    level: "A1",
    skill: "writing",
    title: "Antwort a d Frau Suter",
    genre: "Not",
    intro:
      "Hikâyenin son bölümü: öğretmenin notuna (zh-a1-r11) yazılı cevap vereceksin — üç maddesine de.",
    gloss: [
      { de: "danke für", tr: "… için teşekkür" },
      { de: "dra dänke", tr: "unutmamak, aklında tutmak" },
      { de: "mitcho", tr: "birlikte gelmek" },
      { de: "sich fröie", tr: "sevinmek" },
      { de: "gärn", tr: "memnuniyetle" },
      { de: "es hät mi gfröit", tr: "beni sevindirdi" },
    ],
    minutes: 6,
    tasks: [
      {
        kind: "build",
        tr: "Not için teşekkürler.",
        answer: "Merci vilmal für de Zettel.",
        hint: "İsviçre'de danke yerine çok sık „merci vilmal“ kullanılır.",
      },
      {
        kind: "build",
        tr: "Ceketi unutmayacağım.",
        answer: "A d Jagge dänk ich.",
        alternatives: ["Ich dänk a d Jagge."],
        hint: "denken an + Akkusativ; nesneyi öne alırsan fiil ikinci sırada kalır.",
      },
      {
        kind: "build",
        tr: "Kerem geziye seve seve geliyor.",
        answer: "De Kerem chunt gärn am Ussflug mit.",
        hint: "mitkommen ayrılabilir: chunt … mit.",
      },
      {
        kind: "free",
        prompt:
          "Frau Suter'in notuna kısa bir cevap yaz. Dört noktaya değin: teşekkür, ceket konusuna cevap, gezi için onay ve bir soru (ne getirmeli), oğlun hakkında yazdığı iyi habere bir cümle.",
        checklist: [
          "Hitapla başladın mı?",
          "Notun üç maddesine de değindin mi?",
          "Bir soru sordun mu?",
          "Nezaket biçimini (Si) kullandın mı?",
          "İmzaladın mı?",
        ],
        minWords: 30,
        phrases: [
          { de: "Merci vilmal für de Zettel.", tr: "Not için teşekkürler." },
          { de: "A d Jagge dänk ich.", tr: "Ceketi unutmam." },
          { de: "De Kerem chunt gärn mit.", tr: "Kerem seve seve geliyor." },
          { de: "Was mues er mitnää?", tr: "Ne getirmesi gerekiyor?" },
          { de: "Das hät mi gfröit.", tr: "Bu beni sevindirdi." },
        ],
        sample:
          "Liebi Frau Suter\n\nMerci vilmal für de Zettel.\n\nA d Jagge dänk ich — si isch under em Bett gsii. Am Määndig nimmt er si mit.\n\nDe Kerem chunt gärn am Ussflug mit. Was mues er mitnää? Mir händ käini Gummistifeli, aber alti Schueh scho.\n\nUnd das mit em Rede hät mi würkli gfröit. Dihäi redt er au meh.\n\nFründlichi Grüess\nMeral Yıldız",
      },
    ],
  },
];
