import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 1 — Profesyonel iletişim (001–010).
 *
 * B2'nin ilk modülü seviyenin sesini kuruyor. B1'de öğrenci kendi hayatını
 * anlatıyordu; B2'de bir KURUMUN dilini konuşuyor ve o dilin iki belirgin
 * alışkanlığı var: fiili isme çevirmek (nachdem wir geprüft haben → nach der
 * Prüfung) ve eylemi failinden ayırmak (edilgen ve edilgen yerine geçen
 * yapılar).
 *
 * Türkçe konuşan için asıl zorluk kelime değil TON: aynı cümle Almancada
 * kurum içinde kurulunca daha uzun, daha isimleşmiş ve daha dolaylı olur.
 * Bu yüzden modül tek bir kuralı değil bir üslubu çalıştırıyor — sunum açmak,
 * grafik anlatmak, toplantı yönetmek, tutanak tutmak, soru karşılamak, görev
 * dağıtmak, süre pazarlığı yapmak.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B01: Lesson[] = [
  {
    id: "de-b2-praesentation",
    icon: "chart",
    level: "B2",
    course: "de",
    title: "Die Präsentation eröffnen",
    titleTr: "Sunuma giriş",
    summary: "Bir sunumu açmayı ve planı isimleşmiş kurum diliyle anlatmayı öğretir.",
    minutes: 11,
    focusId: "Nominalisierung",
    vocab: [
      { de: "der Vortrag", tr: "sunum" },
      { de: "der Überblick", tr: "genel bakış" },
      { de: "die Gliederung", tr: "sunum planı" },
      { de: "das Anliegen", tr: "amaç, mesele" },
      { de: "eingehen auf", tr: "değinmek" },
    ],
    patterns: [
      { de: "Ziel meines Vortrags ist es, … zu …", tr: "sunumun amacını söyler" },
      { de: "Zunächst gebe ich einen Überblick über …", tr: "planı duyurur" },
      { de: "Kommen wir zu …", tr: "bölümler arası geçiş" },
    ],
    lecture: [
      { say: [tr("Merhaba ve B2'ye hoş geldin! Bu seviyede artık kendi hayatını değil, bir kurumun dilini konuşacaksın. İlk ders: bir sunumu açmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kurum dilinin en belirgin alışkanlığı fiili isme çevirmek. Türkçede 'kontrol ettikten sonra' deriz; Almanca kurum dili 'kontrolden sonra' der. Kısalır ve resmîleşir. Önce kelimeler.")] },
      word("İlk", { de: "der Vortrag", tr: "sunum" }),
      word("İkinci", { de: "der Überblick", tr: "genel bakış" }),
      word("Üçüncü", { de: "die Gliederung", tr: "sunum planı" }),
      word("Dördüncü", { de: "das Anliegen", tr: "amaç, mesele" }),
      word("Son", { de: "eingehen auf", tr: "değinmek" }),
      { say: [tr("Kalıbımız:"), de("Ziel meines Vortrags ist es, … zu …"), tr("Baştaki isim öbeği amacı taşıyor; asıl eylem sona, mastar öbeğine geçiyor.")] },
      { say: [tr("Örnek:"), de("Ziel meines Vortrags ist es, Ihnen unser neues Verfahren vorzustellen."), tr("Lütfen tekrar edin:"), de("Ziel meines Vortrags ist es, Ihnen unser neues Verfahren vorzustellen")], expect: repeat("Ziel meines Vortrags ist es, Ihnen unser neues Verfahren vorzustellen") },
      { say: [tr("Sıra sende: 'Önce süreç hakkında bir genel bakış vereceğim.'")], expect: produce("Zunächst gebe ich Ihnen einen Überblick über den Ablauf", [tr("Zaman zarfı başta, fiil ikinci sırada:"), de("Zunächst gebe ich Ihnen einen Überblick über den Ablauf."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu noktaya birazdan ayrıntılı değineceğim.'")], expect: produce("Auf diesen Punkt gehe ich später ausführlich ein", [tr("Edat öbeği başta, ayrılabilen fiilin öneki en sonda:"), de("Auf diesen Punkt gehe ich später ausführlich ein."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, tamamen isimleştirerek: 'Sunumun amacı, kararı hazırlamaktır.'")], expect: produce("Ziel des Vortrags ist die Vorbereitung der Entscheidung", [tr("Fiil isme dönüşüyor ve tamlama kuruluyor:"), de("Ziel des Vortrags ist die Vorbereitung der Entscheidung."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ziel meines Vortrags ist, Ihnen das Verfahren vorstellen."), tr("cümlesi doğru mu?")], expect: truefalse("Ziel meines Vortrags ist, Ihnen das Verfahren vorstellen.", false, [tr("Mastar öbeği eksik kurulmuş; sahte özne ve zu gerekiyor:"), de("Ziel meines Vortrags ist es, Ihnen das Verfahren vorzustellen.")]) },
      { say: [tr("Son: 'Şimdi ikinci bölüme geçelim.'")], expect: produce("Kommen wir nun zum zweiten Teil", [tr("Rica biçiminde çoğul; fiil en başta:"), de("Kommen wir nun zum zweiten Teil."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir ekip önünde sunumunu açacaksın: amacını söyle, planı duyur ve ilk bölüme geç.")] },
    ],
    roleplay: {
      scene: "Bir ekip toplantısında sunumunu açıyorsun. Amacını söyle, sunum planını duyur, dinleyiciye ne zaman soru sorabileceğini belirt ve ilk bölüme geç.",
      partner: "ilgili ama araya girip soru soran bir bölüm yöneticisi",
      opening: "Bevor Sie anfangen: Wie viel Zeit haben Sie eingeplant, und wollen Sie Fragen zwischendurch oder am Ende?",
      openingTr: "Başlamadan önce: Ne kadar süre ayırdınız ve soruları arada mı, sonda mı almak istersiniz?",
      goal: "Sunumun amacı, planı ve soru düzeni duyurulmuş; ilk bölüme geçilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-folien",
    icon: "chart",
    level: "B2",
    course: "de",
    title: "Wie die Grafik zeigt",
    titleTr: "Grafik anlatmak",
    summary: "Sayıları ve eğilimleri edilgen Perfekt ile anlatmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "die Grafik", tr: "grafik" },
      { de: "darstellen", tr: "göstermek (grafikte)" },
      { de: "der Anstieg", tr: "artış" },
      { de: "der Rückgang", tr: "düşüş" },
      { de: "auffällig", tr: "dikkat çekici" },
    ],
    patterns: [
      { de: "Wie in der Grafik dargestellt wurde, …", tr: "grafiğe gönderme yapar" },
      { de: "… ist … worden", tr: "edilgen Perfekt: yapılmış olan" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sayıları anlatacağız. Sunumda kimin yaptığı değil neyin olduğu önemlidir, o yüzden dil edilgendir — ama bu kez geçmişte tamamlanmış hâliyle. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Küçük ama kritik bir ayrıntı var: edilgen geçmişte yardımcı fiil kısalır. Bu, B1'de öğrendiğin kuralın sunum dilindeki karşılığı. Önce kelimeler.")] },
      word("İlk", { de: "die Grafik", tr: "grafik" }),
      word("İkinci", { de: "darstellen", tr: "göstermek (grafikte)" }),
      word("Üçüncü", { de: "der Anstieg", tr: "artış" }),
      word("Dördüncü", { de: "der Rückgang", tr: "düşüş" }),
      word("Son", { de: "auffällig", tr: "dikkat çekici" }),
      { say: [tr("Kalıbımız:"), de("… ist … worden"), tr("Yardımcı fiil sein, sonra ortaç, en sonda kısalmış biçim. Sunumda çok sık duyulur.")] },
      { say: [tr("Örnek:"), de("Diese Grafik ist im März erstellt worden."), tr("Tekrar edin:"), de("Diese Grafik ist im März erstellt worden")], expect: repeat("Diese Grafik ist im März erstellt worden") },
      { say: [tr("Sıra sende: 'Veriler geçen hafta güncellendi.'")], expect: produce("Die Daten sind letzte Woche aktualisiert worden", [tr("Çoğul özne, sein yardımcı fiili, sonda kısalmış biçim:"), de("Die Daten sind letzte Woche aktualisiert worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi grafiğe gönderme yap: 'Grafikte gösterildiği gibi maliyetler düştü.'")], expect: produce("Wie in der Grafik dargestellt wurde, sind die Kosten gesunken", [tr("Yan cümle başta olduğu için ana cümle fiille başlar:"), de("Wie in der Grafik dargestellt wurde, sind die Kosten gesunken."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Dikkat çekici olan, artışın mayısta başlamış olması.'")], expect: produce("Auffällig ist, dass der Anstieg im Mai begonnen hat", [tr("Sıfat başta, yan cümlede yardımcı fiil sonda:"), de("Auffällig ist, dass der Anstieg im Mai begonnen hat."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wie in der Grafik dargestellt wurde, sind die Kosten gesunken."), tr("cümlesi doğru mu?")], expect: truefalse("Wie in der Grafik dargestellt wurde, sind die Kosten gesunken.", true, [tr("Doğru. Yan cümlede edilgen geçmiş, ana cümlede hareket fiili sein ile çekilmiş ve fiil virgülden hemen sonra geliyor.")]) },
      { say: [tr("Son: 'Bu yöntem daha önce hiç denenmedi.'")], expect: produce("Diese Methode ist vorher nie getestet worden", [tr("Olumsuzluk ortaçtan önce, kısalmış biçim en sonda:"), de("Diese Methode ist vorher nie getestet worden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir meslektaşına çeyrek sonuçlarını anlatacaksın: eğilim ne, dikkat çeken ne, neden böyle.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşına çeyrek sonuçlarının grafiğini anlatıyorsun: eğilim ne yönde, dikkat çeken nokta ne, sebebi ne olabilir. Sayıları edilgen geçmişle anlat.",
      partner: "rakamları sorgulayan, kaynak soran bir meslektaş",
      opening: "Ich sehe hier einen ziemlichen Sprung im Mai. Woher kommt der — und sind die Zahlen schon geprüft worden?",
      openingTr: "Mayısta ciddi bir sıçrama görüyorum. Nereden geliyor bu — ve rakamlar kontrol edildi mi?",
      goal: "Eğilim, dikkat çeken nokta ve olası sebebi anlatılmış; rakamların nasıl doğrulandığı söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-meeting-leiten",
    icon: "job",
    level: "B2",
    course: "de",
    title: "Das Meeting moderieren",
    titleTr: "Toplantı yönetmek",
    summary: "Toplantıyı dilek kipiyle yönlendirmeyi ve karar kayda geçirmeyi öğretir.",
    minutes: 11,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "moderieren", tr: "yönetmek (toplantı)" },
      { de: "festhalten", tr: "kayda geçirmek" },
      { de: "der Tagesordnungspunkt", tr: "gündem maddesi" },
      { de: "die Abstimmung", tr: "oylama" },
      { de: "vertagen", tr: "ertelemek (toplantıyı)" },
    ],
    patterns: [
      { de: "Ich würde vorschlagen, … zu …", tr: "öneriyi yumuşatır" },
      { de: "Könnten wir festhalten, dass …?", tr: "kararı kayda geçirir" },
      { de: "Fassen wir zusammen: …", tr: "toparlar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün toplantıyı sen yöneteceksin. Yönetmek emretmek değil: yön veren cümleler dilek kipiyle kurulur, çünkü karşındakine hâlâ itiraz alanı bırakır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Üç hamle yeter: öneri getirmek, kararı kayda geçirmek ve toparlamak. Üçü de kalıp hâlinde ve üçünü de bugün kuracağız. Önce kelimeler.")] },
      word("İlk", { de: "moderieren", tr: "yönetmek (toplantı)" }),
      word("İkinci", { de: "festhalten", tr: "kayda geçirmek" }),
      word("Üçüncü", { de: "der Tagesordnungspunkt", tr: "gündem maddesi" }),
      word("Dördüncü", { de: "die Abstimmung", tr: "oylama" }),
      word("Son", { de: "vertagen", tr: "ertelemek (toplantıyı)" }),
      { say: [tr("Kalıbımız:"), de("Ich würde vorschlagen, … zu …"), tr("Düz kipte söylenseydi bir karar olurdu; dilek kipi onu bir öneriye çeviriyor.")] },
      { say: [tr("Örnek:"), de("Ich würde vorschlagen, zuerst die Zahlen anzusehen."), tr("Tekrar edin:"), de("Ich würde vorschlagen, zuerst die Zahlen anzusehen")], expect: repeat("Ich würde vorschlagen, zuerst die Zahlen anzusehen") },
      { say: [tr("Sıra sende: 'Önce bu gündem maddesini görüşmeyi öneririm.'")], expect: produce("Ich würde vorschlagen, zuerst diesen Punkt zu besprechen", [tr("Dilek kipi ana cümlede, mastar öbeği virgülden sonra:"), de("Ich würde vorschlagen, zuerst diesen Punkt zu besprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi kararı kayda geçir: 'Bu konuda anlaştığımızı kayda geçirebilir miyiz?'")], expect: produce("Könnten wir festhalten, dass wir uns einig sind", [tr("Kibar soru, yan cümlede fiil sonda:"), de("Könnten wir festhalten, dass wir uns einig sind?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Toparlayalım: üç noktada anlaştık.'")], expect: produce("Fassen wir zusammen: In drei Punkten sind wir uns einig", [tr("Rica biçiminde fiil başta; ikinci cümlede tümleç öne alınmış:"), de("Fassen wir zusammen: In drei Punkten sind wir uns einig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Könnten wir festhalten, dass wir sind uns einig?"), tr("cümlesi doğru mu?")], expect: truefalse("Könnten wir festhalten, dass wir sind uns einig?", false, [tr("Yan cümlede çekimli fiil en sona gider:"), de("Könnten wir festhalten, dass wir uns einig sind?")]) },
      { say: [tr("Son: 'Oylamayı bir sonraki toplantıya ertelesek olur mu?'")], expect: produce("Wäre es möglich, die Abstimmung zu vertagen", [tr("En kibar rica biçimi, mastar öbeğiyle:"), de("Wäre es möglich, die Abstimmung zu vertagen?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir toplantıyı yöneteceksin: gündemi aç, tartışmayı yönlendir, kararı kayda geçir ve kapat.")] },
    ],
    roleplay: {
      scene: "Bir ekip toplantısını sen yönetiyorsun. Gündemi aç, konuşmayı yönlendir, itiraz gelirse dinle, kararı kayda geçir ve toplantıyı bir özetle kapat.",
      partner: "konuyu dağıtmaya meyilli, itirazı olan bir ekip üyesi",
      opening: "Bevor wir loslegen: Können wir den letzten Punkt vorziehen? Der ist für mich zeitkritisch.",
      openingTr: "Başlamadan önce: Son maddeyi öne alabilir miyiz? Benim için zamanı kritik.",
      goal: "Gündem işlenmiş, bir karar kayda geçirilmiş ve toplantı özetle kapatılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-protokoll",
    icon: "pen",
    level: "B2",
    course: "de",
    title: "Das Protokoll",
    titleTr: "Tutanak dili",
    summary: "Söylenenleri tutanak diline, dolaylı aktarımla geçirmeyi öğretir.",
    minutes: 11,
    focusId: "Indirekte-Rede-Einstieg",
    vocab: [
      { de: "das Protokoll", tr: "tutanak" },
      { de: "beschließen", tr: "karara bağlamak" },
      { de: "anmerken", tr: "belirtmek" },
      { de: "der Beschluss", tr: "karar" },
      { de: "veranlassen", tr: "başlatmak, yaptırmak" },
    ],
    patterns: [
      { de: "Es wurde beschlossen, dass …", tr: "kararı kişisiz aktarır" },
      { de: "Herr X merkte an, … sei …", tr: "söyleneni dolaylı aktarır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün tutanak yazacağız ve orada tuhaf bir fiil biçimi var: söyleneni aktarırken fiil değişir. Buna dolaylı aktarım kipi diyoruz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sebebi şu: tutanağı yazan kişi söylenene katılmıyor da, karşı da çıkmıyor. Sadece aktarıyor. Fiilin değişmesi bu mesafeyi kuruyor. Önce kelimeler.")] },
      word("İlk", { de: "das Protokoll", tr: "tutanak" }),
      word("İkinci", { de: "beschließen", tr: "karara bağlamak" }),
      word("Üçüncü", { de: "anmerken", tr: "belirtmek" }),
      word("Dördüncü", { de: "der Beschluss", tr: "karar" }),
      word("Son", { de: "veranlassen", tr: "başlatmak, yaptırmak" }),
      { say: [tr("Kalıbımız:"), de("Herr X merkte an, … sei …"), tr("Olmak fiilinin aktarım biçimi budur ve tutanakta en çok o geçer.")] },
      { say: [tr("Örnek:"), de("Frau Berg merkte an, der Termin sei zu früh."), tr("Tekrar edin:"), de("Frau Berg merkte an, der Termin sei zu früh")], expect: repeat("Frau Berg merkte an, der Termin sei zu früh") },
      { say: [tr("Sıra sende: 'Bay Klein sürenin çok kısa olduğunu belirtti.'")], expect: produce("Herr Klein merkte an, die Frist sei zu kurz", [tr("Aktarım kipinde olmak fiili biçim değiştirir:"), de("Herr Klein merkte an, die Frist sei zu kurz."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi kararı yaz: 'Bütçenin artırılmasına karar verildi.'")], expect: produce("Es wurde beschlossen, dass das Budget erhöht wird", [tr("Öznesiz edilgen; yan cümlede edilgen ve fiil sonda:"), de("Es wurde beschlossen, dass das Budget erhöht wird."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sonraki adımların cumaya kadar tamamlanması gerekiyor.'")], expect: produce("Die nächsten Schritte seien bis Freitag zu erledigen", [tr("Aktarım kipi çoğulda seien; sein artı zu edilgen yerine geçer:"), de("Die nächsten Schritte seien bis Freitag zu erledigen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Herr Klein merkte an, die Frist ist zu kurz."), tr("cümlesi doğru mu?")], expect: truefalse("Herr Klein merkte an, die Frist ist zu kurz.", false, [tr("Tutanakta söylenen aktarılırken fiil aktarım kipine girer:"), de("Herr Klein merkte an, die Frist sei zu kurz.")]) },
      { say: [tr("Son: 'Bir sonraki toplantı iki hafta sonra yapılacak.'")], expect: produce("Die nächste Sitzung findet in zwei Wochen statt", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Die nächste Sitzung findet in zwei Wochen statt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir meslektaşınla toplantı tutanağını gözden geçireceksin: ne karara bağlandı, kim ne belirtti, ne eksik.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşınla dünkü toplantının tutanağını gözden geçiriyorsunuz: hangi kararlar alındı, kim ne belirtti, hangi madde eksik kalmış. Söylenenleri dolaylı aktarımla anlat.",
      partner: "titiz, her maddeyi kaynağına soran bir meslektaş",
      opening: "Ich habe das Protokoll überflogen. Bei Punkt drei fehlt mir etwas — was genau ist da beschlossen worden?",
      openingTr: "Tutanağı göz gezdirdim. Üçüncü maddede bir eksik var — orada tam olarak ne karara bağlandı?",
      goal: "Alınan kararlar aktarılmış, eksik madde bulunmuş ve tutanağın nasıl düzeltileceği kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-rueckfragen",
    icon: "question",
    level: "B2",
    course: "de",
    title: "Auf Rückfragen reagieren",
    titleTr: "Soru karşılamak",
    summary: "Sunum sonrası soruları anlamayı, ertelemeyi ve netleştirmeyi öğretir.",
    minutes: 11,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "die Rückfrage", tr: "geri soru" },
      { de: "missverstehen", tr: "yanlış anlamak" },
      { de: "zurückkommen auf", tr: "geri dönmek (konuya)" },
      { de: "erläutern", tr: "açıklamak" },
      { de: "präzisieren", tr: "netleştirmek" },
    ],
    patterns: [
      { de: "Wenn ich Sie richtig verstehe, …", tr: "soruyu yeniden ifade eder" },
      { de: "Darauf komme ich gleich zurück.", tr: "soruyu erteler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Sunumun en zor kısmı sunum değil, sonrasıdır: sorular. İyi haber şu ki soruyu karşılamanın üç hazır hamlesi var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Üç hamle: soruyu kendi cümlenle tekrarlamak, cevabı sıraya koymak ve gerekirse kendi söylediğini netleştirmek. Hepsinde dolaylı soru kalıbı işine yarar. Önce kelimeler.")] },
      word("İlk", { de: "die Rückfrage", tr: "geri soru" }),
      word("İkinci", { de: "missverstehen", tr: "yanlış anlamak" }),
      word("Üçüncü", { de: "zurückkommen auf", tr: "geri dönmek (konuya)" }),
      word("Dördüncü", { de: "erläutern", tr: "açıklamak" }),
      word("Son", { de: "präzisieren", tr: "netleştirmek" }),
      { say: [tr("Kalıbımız:"), de("Wenn ich Sie richtig verstehe, …"), tr("Soruyu kendi cümlenle tekrar etmek iki iş görür: zaman kazanırsın ve yanlış anlamayı baştan önlersin.")] },
      { say: [tr("Örnek:"), de("Wenn ich Sie richtig verstehe, geht es um die Kosten."), tr("Tekrar edin:"), de("Wenn ich Sie richtig verstehe, geht es um die Kosten")], expect: repeat("Wenn ich Sie richtig verstehe, geht es um die Kosten") },
      { say: [tr("Sıra sende: 'Doğru anladıysam zaman planını sorguluyorsunuz.'")], expect: produce("Wenn ich Sie richtig verstehe, stellen Sie den Zeitplan infrage", [tr("Yan cümle başta, ana cümle fiille başlar:"), de("Wenn ich Sie richtig verstehe, stellen Sie den Zeitplan infrage."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi soruyu ertele: 'Buna birazdan döneceğim.'")], expect: produce("Darauf komme ich gleich zurück", [tr("Edat öbeği başta, ayrılabilen fiilin öneki sonda:"), de("Darauf komme ich gleich zurück."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sorunuzun neye dayandığını sorabilir miyim?'")], expect: produce("Darf ich fragen, worauf sich Ihre Frage bezieht", [tr("Dolaylı soruda edat soru zamiriyle kaynaşır, fiil sonda:"), de("Darf ich fragen, worauf sich Ihre Frage bezieht?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn ich Sie richtig verstehe, geht es um die Kosten."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn ich Sie richtig verstehe, geht es um die Kosten.", true, [tr("Doğru. Koşul yan cümlesi başta, ana cümle fiille başlıyor ve edat öbeği yerinde.")]) },
      { say: [tr("Son: 'Bu noktayı biraz daha netleştirebilir miyim?'")], expect: produce("Darf ich diesen Punkt noch etwas präzisieren", [tr("Modal fiil başta, mastar en sonda:"), de("Darf ich diesen Punkt noch etwas präzisieren?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sunumun bitti ve soru turu başlıyor: soruları karşıla, birini ertele, birini netleştir.")] },
    ],
    roleplay: {
      scene: "Sunumun bitti ve soru turundasın. Gelen soruyu kendi cümlenle tekrarla, bir soruyu kibarca ertele, bir yanlış anlamayı düzelt ve turu kapat.",
      partner: "zor ama haksız olmayan sorular soran bir dinleyici",
      opening: "Danke für den Vortrag. Eine Frage vorweg: Sie sagen, das Verfahren spare Zeit — auf welche Zahlen stützen Sie das?",
      openingTr: "Sunum için teşekkürler. Baştan bir soru: Yöntemin zaman kazandırdığını söylüyorsunuz — bunu hangi rakamlara dayandırıyorsunuz?",
      goal: "Sorular karşılanmış, biri ertelenmiş, bir yanlış anlama düzeltilmiş ve soru turu kapatılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-smalltalk-business",
    icon: "handshake",
    level: "B2",
    course: "de",
    title: "Small Talk im Aufzug",
    titleTr: "İş ortamında kısa sohbet",
    summary: "Kısa, bağlayıcı olmayan iş sohbetini kibar kalıplarla kurmayı öğretir.",
    minutes: 11,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "unverbindlich", tr: "bağlayıcı olmayan" },
      { de: "sich erkundigen", tr: "sormak, hâl hatır sormak" },
      { de: "beiläufig", tr: "geçerken, laf arasında" },
      { de: "die Belegschaft", tr: "çalışanlar" },
      { de: "ansprechen", tr: "konuyu açmak" },
    ],
    patterns: [
      { de: "Hätten Sie kurz Zeit?", tr: "kibarca vakit ister" },
      { de: "Man müsste mal wieder …", tr: "bağlayıcı olmayan öneri" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün çok kısa ama çok işlevsel bir tür: asansör sohbeti. Kimse gerçek bir konu açmaz ama ilişki tam da orada kurulur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu sohbetin dili bilerek bağlayıcı değildir. 'Bir ara yapmalıyız' der, tarih vermez. Dilek kipi bu belirsizliği kibarca taşır. Önce kelimeler.")] },
      word("İlk", { de: "unverbindlich", tr: "bağlayıcı olmayan" }),
      word("İkinci", { de: "sich erkundigen", tr: "hâl hatır sormak" }),
      word("Üçüncü", { de: "beiläufig", tr: "laf arasında" }),
      word("Dördüncü", { de: "die Belegschaft", tr: "çalışanlar" }),
      word("Son", { de: "ansprechen", tr: "konuyu açmak" }),
      { say: [tr("Kalıbımız:"), de("Man müsste mal wieder …"), tr("Belirsiz özne ve dilek kipi: kimse söz vermiyor ama kapı açık kalıyor.")] },
      { say: [tr("Örnek:"), de("Man müsste mal wieder zusammen essen gehen."), tr("Tekrar edin:"), de("Man müsste mal wieder zusammen essen gehen")], expect: repeat("Man müsste mal wieder zusammen essen gehen") },
      { say: [tr("Sıra sende: 'Bir dakikanız var mı?'")], expect: produce("Hätten Sie kurz einen Moment Zeit", [tr("Sahip olma fiilinin dilek kipiyle kibar soru:"), de("Hätten Sie kurz einen Moment Zeit?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sizde işler şu sıra nasıl gidiyor?'")], expect: produce("Wie läuft es zurzeit bei Ihnen", [tr("Soru kelimesi başta, fiil ikinci sırada:"), de("Wie läuft es zurzeit bei Ihnen?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Rahatsız etmek istemem ama bir sorum olacaktı.'")], expect: produce("Ich möchte Sie nicht stören, aber ich hätte eine Frage", [tr("İki bağımsız cümle; ikincisinde dilek kipi kibarlığı taşır:"), de("Ich möchte Sie nicht stören, aber ich hätte eine Frage."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Man müsste mal wieder zusammen essen zu gehen."), tr("cümlesi doğru mu?")], expect: truefalse("Man müsste mal wieder zusammen essen zu gehen.", false, [tr("Modal fiilden sonra mastar zu almaz:"), de("Man müsste mal wieder zusammen essen gehen.")]) },
      { say: [tr("Son: 'Bunu laf arasında açmak istedim.'")], expect: produce("Ich wollte das nur beiläufig ansprechen", [tr("Ayrılabilen fiilin mastarı sonda:"), de("Ich wollte das nur beiläufig ansprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada asansörde bir üst yöneticiyle karşılaşacaksın: kısa konuş, bir konuyu laf arasında aç ve kibarca ayrıl.")] },
    ],
    roleplay: {
      scene: "Asansörde bir üst yöneticiyle karşılaştın ve altı katın var. Kısa bir sohbet aç, laf arasında küçük bir konuyu gündeme getir ve kata varmadan kibarca kapat.",
      partner: "nazik ama acelesi olan bir üst yönetici",
      opening: "Guten Morgen! Sie sind ja früh dran heute. Alles in Ordnung bei Ihnen im Team?",
      openingTr: "Günaydın! Bugün erken gelmişsiniz. Ekipte her şey yolunda mı?",
      goal: "Kısa bir sohbet edilmiş, bir konu laf arasında açılmış ve bağlayıcı olmayan bir sözle kapatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-delegieren",
    icon: "job",
    level: "B2",
    course: "de",
    title: "Aufgaben verteilen",
    titleTr: "Görev dağıtmak",
    summary: "Edilgen yerine geçen yapılarla görev dağıtmayı ve yapılabilirliği söylemeyi öğretir.",
    minutes: 11,
    focusId: "Passiversatz",
    vocab: [
      { de: "delegieren", tr: "görev devretmek" },
      { de: "die Zuständigkeit", tr: "sorumluluk alanı" },
      { de: "abarbeiten", tr: "sırayla bitirmek" },
      { de: "die Kapazität", tr: "kapasite" },
      { de: "beauftragen", tr: "görevlendirmek" },
    ],
    patterns: [
      { de: "Das lässt sich bis … erledigen.", tr: "yapılabilirliği söyler" },
      { de: "… ist zu prüfen.", tr: "yapılması gerekeni söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün edilgenin kardeşlerini öğreneceğiz. Almanca kurum dilinde 'yapılabilir' ve 'yapılmalı' için edilgen kurmadan da üç ayrı yol var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Üçü de aynı işi görür ama tonları farklıdır: biri imkânı söyler, biri zorunluluğu, biri de sıfat gibi durur. Önce kelimeler.")] },
      word("İlk", { de: "delegieren", tr: "görev devretmek" }),
      word("İkinci", { de: "die Zuständigkeit", tr: "sorumluluk alanı" }),
      word("Üçüncü", { de: "abarbeiten", tr: "sırayla bitirmek" }),
      word("Dördüncü", { de: "die Kapazität", tr: "kapasite" }),
      word("Son", { de: "beauftragen", tr: "görevlendirmek" }),
      { say: [tr("Kalıbımız:"), de("Das lässt sich bis Freitag erledigen."), tr("Anlamı 'bu cumaya kadar halledilebilir'. Edilgen kurmadan aynı şeyi söylüyor ve daha akıcı duruyor.")] },
      { say: [tr("Tekrar edin:"), de("Das lässt sich bis Freitag erledigen")], expect: repeat("Das lässt sich bis Freitag erledigen") },
      { say: [tr("Sıra sende: 'Bu rapor bugün bitirilebilir.'")], expect: produce("Dieser Bericht lässt sich heute abschließen", [tr("lassen artı dönüşlü zamir; mastar en sonda:"), de("Dieser Bericht lässt sich heute abschließen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi zorunluluk biçimiyle: 'Rakamların önce kontrol edilmesi gerekiyor.'")], expect: produce("Die Zahlen sind zuerst zu prüfen", [tr("sein artı zu artı mastar: yapılması gerekeni söyler:"), de("Die Zahlen sind zuerst zu prüfen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, sıfat biçimiyle: 'Sorun birkaç adımda çözülebilir.'")], expect: produce("Das Problem ist in wenigen Schritten lösbar", [tr("Fiilden türeyen sıfat aynı anlamı taşır:"), de("Das Problem ist in wenigen Schritten lösbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das lässt sich bis Freitag zu erledigen."), tr("cümlesi doğru mu?")], expect: truefalse("Das lässt sich bis Freitag zu erledigen.", false, [tr("Bu yapıda mastar zu almaz:"), de("Das lässt sich bis Freitag erledigen.")]) },
      { say: [tr("Son bir soru sor: 'Bu görevi kim üstleniyor?'")], expect: produce("Wer übernimmt diese Aufgabe", [tr("Soru zamiri özne, fiil ikinci sırada:"), de("Wer übernimmt diese Aufgabe?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada ekibinle işleri paylaşacaksın: neyin yapılabileceğini, neyin öncelikli olduğunu ve kimin neyi üstleneceğini konuş.")] },
    ],
    roleplay: {
      scene: "Yoğun bir haftada ekibinle işleri paylaşıyorsun: neyin bu hafta yapılabileceğini, neyin ertelenmesi gerektiğini ve kimin neyi üstleneceğini konuş.",
      partner: "kapasitesinin dolu olduğunu söyleyen bir ekip üyesi",
      opening: "Bevor du verteilst: Bei mir liegen noch zwei Sachen von letzter Woche. Was hat denn wirklich Priorität?",
      openingTr: "Dağıtmadan önce: Bende geçen haftadan iki iş duruyor. Gerçekten önceliği olan ne?",
      goal: "Öncelik belirlenmiş, kimin neyi üstleneceği paylaşılmış ve ertelenen iş için yeni bir tarih verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-deadline",
    icon: "clock",
    level: "B2",
    course: "de",
    title: "Die Frist brennt",
    titleTr: "Süre baskısı",
    summary: "Koşullu söz vermeyi sofern ve es sei denn ile kurmayı öğretir.",
    minutes: 11,
    focusId: "Nebensatz-sofern",
    vocab: [
      { de: "der Abgabetermin", tr: "teslim tarihi" },
      { de: "dazwischenkommen", tr: "araya girmek (aksilik)" },
      { de: "straffen", tr: "sıkılaştırmak (program)" },
      { de: "der Puffer", tr: "pay, yedek süre" },
      { de: "einhalten", tr: "uymak (süreye)" },
    ],
    patterns: [
      { de: "Sofern nichts dazwischenkommt, …", tr: "koşullu söz: olursa" },
      { de: "…, es sei denn, …", tr: "tek istisna: olmadıkça" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün iş hayatının en gergin cümlesini kuracağız: söz vermek ama koşullu söz vermek. Almancada bunun iki kalıbı var ve ikisi de resmî. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Biri koşulu olumlu koyar: şu olursa yaparız. Öteki istisnayı söyler: şu olmadıkça yaparız. İkisini karıştırmak sözün anlamını tersine çevirir. Önce kelimeler.")] },
      word("İlk", { de: "der Abgabetermin", tr: "teslim tarihi" }),
      word("İkinci", { de: "dazwischenkommen", tr: "araya girmek (aksilik)" }),
      word("Üçüncü", { de: "straffen", tr: "sıkılaştırmak (program)" }),
      word("Dördüncü", { de: "der Puffer", tr: "pay, yedek süre" }),
      word("Son", { de: "einhalten", tr: "uymak (süreye)" }),
      { say: [tr("Kalıbımız:"), de("Sofern nichts dazwischenkommt, …"), tr("Yan cümle bağlacı, yani fiil sona gidiyor ve ana cümle fiille başlıyor.")] },
      { say: [tr("Örnek:"), de("Sofern nichts dazwischenkommt, liefern wir am Freitag."), tr("Tekrar edin:"), de("Sofern nichts dazwischenkommt, liefern wir am Freitag")], expect: repeat("Sofern nichts dazwischenkommt, liefern wir am Freitag") },
      { say: [tr("Sıra sende: 'Ekip tam olursa süreye uyarız.'")], expect: produce("Sofern das Team vollzählig ist, halten wir die Frist ein", [tr("Yan cümle önde; ana cümlede ayrılabilen fiilin öneki sonda:"), de("Sofern das Team vollzählig ist, halten wir die Frist ein."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi istisnayla: 'Müşteri erteleme istemedikçe plan aynı kalır.'")], expect: produce("Der Plan bleibt, es sei denn, der Kunde verschiebt den Termin", [tr("İstisna bağlacından sonra düz cümle dizilimi korunur:"), de("Der Plan bleibt, es sei denn, der Kunde verschiebt den Termin."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunu ancak paralel çalışarak yetiştiririz.'")], expect: produce("Wir schaffen das nur, indem wir parallel arbeiten", [tr("Yöntem bağlacı; yan cümlede fiil sonda:"), de("Wir schaffen das nur, indem wir parallel arbeiten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Sofern nichts dazwischenkommt, liefern wir am Freitag."), tr("cümlesi doğru mu?")], expect: truefalse("Sofern nichts dazwischenkommt, liefern wir am Freitag.", true, [tr("Doğru. Yan cümlenin fiili sonda, ana cümle fiille başlıyor ve koşul olumlu kurulmuş.")]) },
      { say: [tr("Son: 'Programı biraz sıkıştırmamız gerekiyor.'")], expect: produce("Wir müssen den Zeitplan etwas straffen", [tr("Modal fiil çekimli, mastar en sonda:"), de("Wir müssen den Zeitplan etwas straffen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada müşteriye teslim tarihini konuşacaksın: neyin mümkün olduğunu koşullu söyle ve bir istisna belirt.")] },
    ],
    roleplay: {
      scene: "Bir müşteriyle teslim tarihini konuşuyorsun. Neyin mümkün olduğunu koşula bağlayarak söyle, bir istisna belirt, gerekirse programı sıkıştırmayı öner ve bir tarihte anlaş.",
      partner: "tarihi öne çekmek isteyen, ısrarcı ama makul bir müşteri",
      opening: "Wir bräuchten das eine Woche früher. Ist das machbar — und wenn ja, unter welchen Bedingungen?",
      openingTr: "Bize bir hafta önce lazım. Mümkün mü — mümkünse hangi koşullarda?",
      goal: "Neyin hangi koşulla mümkün olduğu söylenmiş, bir istisna belirtilmiş ve bir teslim tarihinde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-homeoffice-regeln",
    icon: "tech",
    level: "B2",
    course: "de",
    title: "Hybrid arbeiten",
    titleTr: "Uzaktan çalışma düzeni",
    summary: "Çalışma düzeni kurallarını isimleşmiş kurum diliyle anlatmayı öğretir.",
    minutes: 11,
    focusId: "Nominalisierung",
    vocab: [
      { de: "die Anwesenheit", tr: "ofiste bulunma" },
      { de: "die Absprache", tr: "mutabakat" },
      { de: "die Regelung", tr: "düzenleme" },
      { de: "betrieblich", tr: "şirket içi" },
      { de: "die Erreichbarkeit", tr: "ulaşılabilirlik" },
    ],
    patterns: [
      { de: "Nach Absprache mit …", tr: "isim öbeğiyle koşul" },
      { de: "Beim Arbeiten von zu Hause …", tr: "isimleşmiş mastarla zaman" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün şirket kurallarının dilini çalışacağız. O dilde cümleler yan cümleyle değil, isim öbekleriyle kısaltılır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Örnek: 'şefinle konuştuktan sonra' yerine 'şefinle mutabakat sonrası'. Aynı anlam, daha kısa ve resmî. Bunu iki yönde de yapabilmen gerekiyor. Önce kelimeler.")] },
      word("İlk", { de: "die Anwesenheit", tr: "ofiste bulunma" }),
      word("İkinci", { de: "die Absprache", tr: "mutabakat" }),
      word("Üçüncü", { de: "die Regelung", tr: "düzenleme" }),
      word("Dördüncü", { de: "betrieblich", tr: "şirket içi" }),
      word("Son", { de: "die Erreichbarkeit", tr: "ulaşılabilirlik" }),
      { say: [tr("Kalıbımız:"), de("Nach Absprache mit der Teamleitung ist Homeoffice möglich."), tr("Yan cümle yok; koşul bir isim öbeğine sığmış durumda.")] },
      { say: [tr("Tekrar edin:"), de("Nach Absprache mit der Teamleitung ist Homeoffice möglich")], expect: repeat("Nach Absprache mit der Teamleitung ist Homeoffice möglich") },
      { say: [tr("Sıra sende: 'Salı günleri ofiste bulunmak zorunludur.'")], expect: produce("Die Anwesenheit im Büro ist dienstags verpflichtend", [tr("Fiil isme dönüşmüş; sıfat sonda:"), de("Die Anwesenheit im Büro ist dienstags verpflichtend."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Evden çalışırken ulaşılabilir olmanız gerekiyor.'")], expect: produce("Beim Arbeiten von zu Hause müssen Sie erreichbar sein", [tr("İsimleşmiş mastar tümleç olarak başta, fiil ikinci sırada:"), de("Beim Arbeiten von zu Hause müssen Sie erreichbar sein."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Düzenleme yıl sonuna kadar geçerli.'")], expect: produce("Die Regelung gilt bis zum Jahresende", [tr("Kısa ve resmî bir cümle:"), de("Die Regelung gilt bis zum Jahresende."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Beim Arbeiten von zu Hause man muss erreichbar sein."), tr("cümlesi doğru mu?")], expect: truefalse("Beim Arbeiten von zu Hause man muss erreichbar sein.", false, [tr("Cümle bir tümleçle başlayınca çekimli fiil ikinci sıraya gelir:"), de("Beim Arbeiten von zu Hause muss man erreichbar sein.")]) },
      { say: [tr("Son: 'Bunu şefinle görüştükten sonra karara bağlarız.'")], expect: produce("Nach der Absprache mit deinem Chef entscheiden wir das", [tr("Koşul isim öbeğinde, fiil ikinci sırada:"), de("Nach der Absprache mit deinem Chef entscheiden wir das."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada insan kaynaklarıyla uzaktan çalışma düzenini konuşacaksın: kaç gün, hangi koşulla, hangi kural.")] },
    ],
    roleplay: {
      scene: "İnsan kaynaklarıyla uzaktan çalışma düzenini konuşuyorsun: haftada kaç gün evden çalışabilirsin, hangi günler ofiste bulunmak zorunlu, ulaşılabilirlik nasıl tanımlanıyor.",
      partner: "kuralları ezbere bilen, esnekliğe temkinli yaklaşan bir insan kaynakları uzmanı",
      opening: "Sie wollten über die Homeoffice-Regelung sprechen. Sagen Sie mir zuerst: Wie stellen Sie sich die Woche vor?",
      openingTr: "Uzaktan çalışma düzeni hakkında konuşmak istemiştiniz. Önce şunu söyleyin: Haftayı nasıl düşünüyorsunuz?",
      goal: "Kaç gün evden çalışılacağı, ofis zorunluluğu ve ulaşılabilirlik koşulu netleşmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-konferenz",
    icon: "school",
    level: "B2",
    course: "de",
    title: "Auf der Fachkonferenz",
    titleTr: "Konferansta ağ kurmak",
    summary: "Genitiv edatlarıyla gerekçe ve zaman bildirerek konferansta tanışmayı öğretir.",
    minutes: 11,
    focusId: "Genitivpräpositionen",
    vocab: [
      { de: "die Fachkonferenz", tr: "uzmanlık konferansı" },
      { de: "der Referent", tr: "konuşmacı" },
      { de: "der Austausch", tr: "fikir alışverişi" },
      { de: "sich vernetzen", tr: "bağlantı kurmak" },
      { de: "die Teilnahme", tr: "katılım" },
    ],
    patterns: [
      { de: "aufgrund + Genitiv", tr: "resmî gerekçe" },
      { de: "trotz + Genitiv / während + Genitiv", tr: "zıtlık ve süre" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi. Bugün resmî Almancanın küçük ama belirgin bir işareti: bazı edatlar tamlayan hâli ister. Konuşurken bunu doğru kullanmak seviyeni hemen belli eder. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Günlük dilde bu edatlardan sonra yönelme hâli duyarsın ve yanlış sayılmaz; ama yazıda ve resmî konuşmada tamlayan hâli beklenir. Önce kelimeler.")] },
      word("İlk", { de: "die Fachkonferenz", tr: "uzmanlık konferansı" }),
      word("İkinci", { de: "der Referent", tr: "konuşmacı" }),
      word("Üçüncü", { de: "der Austausch", tr: "fikir alışverişi" }),
      word("Dördüncü", { de: "sich vernetzen", tr: "bağlantı kurmak" }),
      word("Son", { de: "die Teilnahme", tr: "katılım" }),
      { say: [tr("Kalıbımız:"), de("trotz des vollen Programms"), tr("Edattan sonra isim tamlayan hâline giriyor ve eril ile nötr isimler bir ek alıyor.")] },
      { say: [tr("Örnek:"), de("Trotz des vollen Programms hatten wir Zeit für ein Gespräch."), tr("Tekrar edin:"), de("Trotz des vollen Programms hatten wir Zeit für ein Gespräch")], expect: repeat("Trotz des vollen Programms hatten wir Zeit für ein Gespräch") },
      { say: [tr("Sıra sende: 'Deneyimim sayesinde bu konuyu üstlenebilirim.'")], expect: produce("Aufgrund meiner Erfahrung kann ich dieses Thema übernehmen", [tr("Tümleç başta, modal fiil ikinci sırada, mastar sonda:"), de("Aufgrund meiner Erfahrung kann ich dieses Thema übernehmen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Molada birkaç kişiyle tanıştım.'")], expect: produce("Während der Pause habe ich einige Leute kennengelernt", [tr("Süre bildiren edat tamlayan hâli ister; ortaç sonda:"), de("Während der Pause habe ich einige Leute kennengelernt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu, bağlantı kurmak için iyi bir fırsat.'")], expect: produce("Das ist eine gute Gelegenheit, sich zu vernetzen", [tr("İsim artı mastar öbeği; dönüşlü fiil zu ile:"), de("Das ist eine gute Gelegenheit, sich zu vernetzen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wegen dem Regen ist der Empfang ausgefallen."), tr("cümlesi doğru mu?")], expect: truefalse("Wegen dem Regen ist der Empfang ausgefallen.", false, [tr("Bu edat resmî dilde tamlayan hâli ister:"), de("Wegen des Regens ist der Empfang ausgefallen.")]) },
      { say: [tr("Son: 'Yoğun programa rağmen sunumu kaçırmadım.'")], expect: produce("Trotz des vollen Programms habe ich den Vortrag nicht verpasst", [tr("Tümleç başta, yardımcı fiil ikinci, ortaç sonda:"), de("Trotz des vollen Programms habe ich den Vortrag nicht verpasst."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir konferansta tanışacaksın: kendini tanıt, ne üzerine çalıştığını anlat ve bağlantı kur.")] },
    ],
    roleplay: {
      scene: "Bir uzmanlık konferansının molasındasın ve tanımadığın bir katılımcıyla konuşuyorsun. Kendini ve çalıştığın konuyu tanıt, onun sunumu hakkında soru sor ve iletişim bilgisi paylaş.",
      partner: "az önce sunum yapmış, ilgiyle karşılık veren bir konuşmacı",
      opening: "Sie waren doch eben im Saal zwei, oder? Was hat Sie zu diesem Thema gebracht?",
      openingTr: "Az önce ikinci salonda değil miydiniz? Sizi bu konuya çeken ne oldu?",
      goal: "Karşılıklı tanışılmış, çalışılan konular öğrenilmiş ve iletişim için somut bir adım kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
];
