import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 10 — Resmî yazışma ve B2 kapanışı (091–100).
 *
 * Son modül iki iş yapıyor. Birincisi eksik kalan tek alanı kapatmak: resmî
 * yazışmanın sabit kalıpları (hitap, konu satırı, ek, kapanış). Bunlar
 * yaratıcılık istemiyor, ezber istiyor — ve tam da bu yüzden derste kalıp
 * olarak veriliyor, kurdurulmuyor.
 *
 * İkincisi seviyeyi TOPLAMAK. 094'ten itibaren dersler yeni bir kural
 * getirmiyor; B2 boyunca öğrenilenleri gerçek bir işin içinde yan yana
 * çalıştırıyor: mülakatta soru sormak (dolaylı soru), sunum kapatmak
 * (isimleşme), veda konuşması (Plusquamperfekt), referans yazmak (ortaç
 * sıfatları), tersine kültür şoku (als ob), C1 hazırlığı (öznel kipler).
 *
 * Kapanış dersi bilerek edilgen geçmişle yazıldı — B2'nin ilk modülünde
 * öğretilen yapı, seviyenin son cümlesinde geri dönüyor: "Vieles ist erreicht
 * worden."
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B10: Lesson[] = [
  {
    id: "de-b2-formeller-brief",
    icon: "mail",
    level: "B2",
    course: "de",
    title: "Sehr geehrte Damen und Herren",
    titleTr: "Resmî mektup",
    summary: "Resmî yazının sabit kalıplarını ve iskeletini öğretir.",
    minutes: 12,
    focusId: "Nominalisierung",
    vocab: [
      { de: "das Rundschreiben", tr: "genelge" },
      { de: "der Posteingang", tr: "gelen evrak" },
      { de: "der Verteiler", tr: "dağıtım listesi" },
      { de: "die Ablage", tr: "dosyalama" },
      { de: "die Aktennotiz", tr: "dosya notu" },
      { de: "das Formblatt", tr: "standart form" },
      { de: "archivieren", tr: "arşivlemek" },
      { de: "amtlich", tr: "resmî" },
    ],
    patterns: [
      { de: "Als Anlage erhalten Sie …", tr: "ek gönderirken" },
      { de: "Mit freundlichen Grüßen", tr: "resmî kapanış" },
    ],
    lecture: [
      { say: [tr("Merhaba! Son modüle geldik. İlk ders resmî mektup ve burada yaratıcılık istenmiyor — kalıplar sabittir ve tam olarak öyle kullanılır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir resmî yazının iskeleti dörttür: konu satırı, hitap, gövde, kapanış. Bugün dördünü de kuracağız. Önce kelimeler.")] },
      word("İlk", { de: "das Rundschreiben", tr: "genelge" }, "Herkese aynı anda giden resmî yazı."),
      word("İkinci", { de: "der Verteiler", tr: "dağıtım listesi" }),
      word("Üçüncü", { de: "der Posteingang", tr: "gelen evrak" }),
      word("Dördüncü", { de: "die Ablage", tr: "dosyalama" }),
      word("Beşinci", { de: "die Aktennotiz", tr: "dosya notu" }),
      word("Altıncı", { de: "das Formblatt", tr: "standart form" }),
      word("Yedinci", { de: "archivieren", tr: "arşivlemek" }),
      word("Son", { de: "amtlich", tr: "resmî" }),
      { say: [tr("Kalıbımız:"), de("Anbei erhalten Sie …"), tr("Ek gönderirken kullanılan sabit ifade.")] },
      { say: [tr("Örnek:"), de("Als Anlage erhalten Sie die gewünschten Unterlagen."), tr("Tekrar edin:"), de("Als Anlage erhalten Sie die gewünschten Unterlagen")], expect: repeat("Als Anlage erhalten Sie die gewünschten Unterlagen") },
      { say: [tr("Sıra sende: 'Numarayı konu satırına yazın.'")], expect: produce("Schreiben Sie die Nummer in den Betreff", [tr("Rica biçimi; yön bildiren edat belirtme hâliyle:"), de("Schreiben Sie die Nummer in den Betreff."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ekleri e-postaya iliştirdim.'")], expect: produce("Die Anlagen habe ich der E-Mail beigefügt", [tr("Nesne öne alınmış; bu fiil yönelme hâli ister:"), de("Die Anlagen habe ich der E-Mail beigefügt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Muhatabı bilmiyorsanız genel hitap kullanılır.'")], expect: produce("Kennt man den Empfänger nicht, verwendet man die allgemeine Anrede", [tr("Bağlaçsız koşul cümlesi fiille başlar:"), de("Kennt man den Empfänger nicht, verwendet man die allgemeine Anrede."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Anlagen habe ich der E-Mail beifügt."), tr("cümlesi doğru mu?")], expect: truefalse("Die Anlagen habe ich der E-Mail beifügt.", false, [tr("Ayrılabilen fiilin ortacı ge- ekini ortasına alır:"), de("Die Anlagen habe ich der E-Mail beigefügt.")]) },
      { say: [tr("Son: 'Genelge bütün dağıtım listesine gidiyor.'")], expect: produce("Das Rundschreiben geht an den ganzen Verteiler", [tr("Yön bildiren edat belirtme hâli ister:"), de("Das Rundschreiben geht an den ganzen Verteiler."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir yazının nasıl kurulacağını birlikte planlayacaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın resmî bir yazı yazacak ve senden yardım istiyor. Konu satırında ne yazacağını, hangi hitabı kullanacağını, gövdede neyi hangi sırayla söyleyeceğini ve nasıl kapatacağını birlikte belirleyin.",
      partner: "resmî yazışmada acemi, adım adım soran bir meslektaş",
      opening: "Ich muss dem Amt schreiben und weiß nicht mal, wie ich anfangen soll. Was kommt eigentlich zuerst?",
      openingTr: "Daireye yazmam gerek ve nasıl başlayacağımı bile bilmiyorum. Önce ne geliyor?",
      goal: "Konu satırı, hitap, gövdenin sırası ve kapanış birlikte belirlenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-anfrage",
    icon: "mail",
    level: "B2",
    course: "de",
    title: "Die höfliche Anfrage",
    titleTr: "Bilgi talebi",
    summary: "Bilgi talebini dilek kipiyle kibarca kurmayı öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "zeitnah", tr: "kısa sürede" },
      { de: "der Klärungsbedarf", tr: "açıklığa kavuşturma ihtiyacı" },
      { de: "der Handlungsbedarf", tr: "harekete geçme gereği" },
      { de: "der Auftraggeber", tr: "sipariş veren" },
      { de: "die Nutzungsbedingungen", tr: "kullanım koşulları" },
      { de: "die Versandkosten", tr: "kargo ücreti" },
      { de: "anmahnen", tr: "ihtar etmek" },
      { de: "terminieren", tr: "tarih belirlemek" },
    ],
    patterns: [
      { de: "Wir wären Ihnen … dankbar.", tr: "en kibar rica" },
      { de: "Könnten Sie uns … mitteilen?", tr: "bilgi ister" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bilgi soracağız — ama resmî olarak. Resmî ricanın kibarlığı yine dilek kipinden geliyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki hazır kalıp var ve ikisi de kurumsal yazışmada neredeyse standarttır. Bir de fiillerin nesne hâline dikkat edeceğiz. Önce kelimeler.")] },
      word("İlk", { de: "zeitnah", tr: "kısa sürede" }),
      word("İkinci", { de: "der Klärungsbedarf", tr: "açıklığa kavuşturma ihtiyacı" }, "Resmî yazının 'şu nokta belirsiz' deme biçimi."),
      word("Üçüncü", { de: "der Handlungsbedarf", tr: "harekete geçme gereği" }),
      word("Dördüncü", { de: "der Auftraggeber", tr: "sipariş veren" }),
      word("Beşinci", { de: "die Nutzungsbedingungen", tr: "kullanım koşulları" }),
      word("Altıncı", { de: "die Versandkosten", tr: "kargo ücreti" }),
      word("Yedinci", { de: "anmahnen", tr: "ihtar etmek" }),
      word("Son", { de: "terminieren", tr: "tarih belirlemek" }),
      { say: [tr("Kalıbımız:"), de("Wir wären Ihnen … dankbar."), tr("Dilek kipiyle en kibar rica biçimi.")] },
      { say: [tr("Örnek:"), de("Wir wären Ihnen für eine kurze Auskunft dankbar."), tr("Tekrar edin:"), de("Wir wären Ihnen für eine kurze Auskunft dankbar")], expect: repeat("Wir wären Ihnen für eine kurze Auskunft dankbar") },
      { say: [tr("Sıra sende: 'Bize fiyatı bildirebilir misiniz?'")], expect: produce("Könnten Sie uns den Preis mitteilen", [tr("Kip fiili başta soru; ayrılabilen mastar sonda:"), de("Könnten Sie uns den Preis mitteilen?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kısa sürede bir cevap rica ediyoruz.'")], expect: produce("Wir bitten um eine zeitnahe Antwort", [tr("bitten fiili um edatıyla ve belirtme hâliyle:"), de("Wir bitten um eine zeitnahe Antwort."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kargo ücretini öğrenmek isterdik.'")], expect: produce("Wir würden die Versandkosten gern erfahren", [tr("Dilek kipi; mastar sonda:"), de("Wir würden die Versandkosten gern erfahren."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Unser Klärungsbedarf betrifft der Lieferzeit."), tr("cümlesi doğru mu?")], expect: truefalse("Unser Klärungsbedarf betrifft der Lieferzeit.", false, [tr("Bu fiil nesnesini belirtme hâliyle alır:"), de("Unser Klärungsbedarf betrifft die Lieferzeit.")]) },
      { say: [tr("Son: 'Sorumuz teslim süresiyle ilgili.'")], expect: produce("Unser Klärungsbedarf betrifft die Lieferzeit", [tr("Nesne belirtme hâlinde:"), de("Unser Klärungsbedarf betrifft die Lieferzeit."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir firmadan bilgi isteyeceksin.")] },
    ],
    roleplay: {
      scene: "Bir firmadan teklif ve bilgi istiyorsun: fiyat, teslim süresi, koşullar. Kibar kalıplarla sor, eksik kalan bir noktayı netleştir ve yazılı teyit iste.",
      partner: "yardımsever ama her şeyi yazıya dökmek isteyen bir firma çalışanı",
      opening: "Vielen Dank für Ihr Interesse. Was genau möchten Sie denn wissen?",
      openingTr: "İlginiz için teşekkürler. Tam olarak neyi bilmek istiyorsunuz?",
      goal: "Fiyat, teslim süresi ve koşullar öğrenilmiş ve yazılı teyit sözü alınmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-angebot-vergleichen",
    icon: "chart",
    level: "B2",
    course: "de",
    title: "Drei Angebote",
    titleTr: "Teklif kıyaslama",
    summary: "Teklifleri tartıp gerekçeli karar vermeyi öğretir.",
    minutes: 12,
    focusId: "Je-desto",
    vocab: [
      { de: "der Kostenvoranschlag", tr: "fiyat teklifi" },
      { de: "der Preisvergleich", tr: "fiyat karşılaştırması" },
      { de: "das Sortiment", tr: "ürün yelpazesi" },
      { de: "der Kaufvertrag", tr: "satış sözleşmesi" },
      { de: "die Gutschrift", tr: "alacak kaydı" },
      { de: "die Haltbarkeit", tr: "raf ömrü" },
      { de: "der Einzelhandel", tr: "perakende" },
      { de: "die Filiale", tr: "şube" },
    ],
    patterns: [
      { de: "Je detaillierter …, desto …", tr: "orantı kurar" },
      { de: "Wir entscheiden uns für …", tr: "kararı bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün elimizde üç teklif var ve birini seçeceğiz. Karar cümlesi gerekçesiz kurulmaz — orantı bağlacı burada gerekçeyi taşıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de kalıplaşmış bir fiil var: karar vermek. Dönüşlü ve sabit bir edat alıyor. Önce kelimeler.")] },
      word("İlk", { de: "der Kostenvoranschlag", tr: "fiyat teklifi" }),
      word("İkinci", { de: "der Preisvergleich", tr: "fiyat karşılaştırması" }),
      word("Üçüncü", { de: "das Sortiment", tr: "ürün yelpazesi" }),
      word("Dördüncü", { de: "der Kaufvertrag", tr: "satış sözleşmesi" }),
      word("Beşinci", { de: "die Gutschrift", tr: "alacak kaydı" }, "Para iadesi yerine hesaba yazılan alacak."),
      word("Altıncı", { de: "die Haltbarkeit", tr: "raf ömrü" }),
      word("Yedinci", { de: "der Einzelhandel", tr: "perakende" }),
      word("Son", { de: "die Filiale", tr: "şube" }),
      { say: [tr("Kalıbımız:"), de("Je detaillierter …, desto …"), tr("Ayrıntı arttıkça kıyas kolaylaşıyor.")] },
      { say: [tr("Örnek:"), de("Je detaillierter das Angebot ist, desto leichter fällt der Vergleich."), tr("Tekrar edin:"), de("Je detaillierter das Angebot ist, desto leichter fällt der Vergleich")], expect: repeat("Je detaillierter das Angebot ist, desto leichter fällt der Vergleich") },
      { say: [tr("Sıra sende: 'Fiyat karşılaştırmasında ikincisi daha cazip.'")], expect: produce("Im Preisvergleich ist das zweite attraktiver", [tr("Tümleç başta, fiil ikinci sırada:"), de("Im Preisvergleich ist das zweite attraktiver."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ürün yelpazesini karşılaştırdık.'")], expect: produce("Wir haben das Sortiment verglichen", [tr("Ayrılmayan fiilin ortacı ge- almaz:"), de("Wir haben das Sortiment verglichen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Üçüncüsünü seçiyoruz.'")], expect: produce("Wir entscheiden uns für das dritte", [tr("Dönüşlü fiil, sabit edat belirtme hâliyle:"), de("Wir entscheiden uns für das dritte."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Je detaillierter das Angebot ist, desto leichter fällt der Vergleich."), tr("cümlesi doğru mu?")], expect: truefalse("Je detaillierter das Angebot ist, desto leichter fällt der Vergleich.", true, [tr("Doğru. İlk parçada fiil sonda, ikincide karşılaştırma biçimi bağlacın hemen arkasında ve fiil onun ardından geliyor.")]) },
      { say: [tr("Son bir soru: 'Fiyat teklifi yazılı geldi mi?'")], expect: produce("Ist der Kostenvoranschlag schriftlich gekommen", [tr("Fiil başta soru; ortaç sonda:"), de("Ist der Kostenvoranschlag schriftlich gekommen?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada üç teklif arasından birini seçeceksin.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşınla üç teklifi kıyaslıyorsunuz: fiyat, kapsam ve süre bakımından hangisi ne sunuyor, hangi risk var ve hangisini seçiyorsunuz. Kararınızı gerekçelendirin.",
      partner: "en ucuzu savunan, riskleri hafife alan bir meslektaş",
      opening: "Das billigste ist tausend Euro günstiger. Gibt es einen Grund, warum wir es nicht nehmen sollten?",
      openingTr: "En ucuzu bin euro daha uygun. Onu almamamız için bir sebep var mı?",
      goal: "Üç teklif fiyat, kapsam ve risk bakımından tartılmış ve biri gerekçesiyle seçilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-bewerbungsgespraech-b2",
    icon: "job",
    level: "B2",
    course: "de",
    title: "Die Rückfrage-Runde",
    titleTr: "Mülakatta soru sormak",
    summary: "Mülakatın sonunda dolaylı sorularla bilgi almayı öğretir.",
    minutes: 12,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "die Probezeit", tr: "deneme süresi" },
      { de: "der Ablauf", tr: "akış, süreç" },
      { de: "der Verantwortungsbereich", tr: "sorumluluk alanı" },
      { de: "das Arbeitspaket", tr: "iş paketi" },
      { de: "der Meilenstein", tr: "kilometre taşı" },
      { de: "die Fertigkeit", tr: "beceri" },
      { de: "die Auffassungsgabe", tr: "kavrayış" },
      { de: "anspruchsvoll", tr: "zorlu" },
    ],
    patterns: [
      { de: "Mich würde interessieren, wie …", tr: "kibar dolaylı soru" },
      { de: "Wann darf ich mit … rechnen?", tr: "zaman sorar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Mülakatın sonundasın ve sana 'sorunuz var mı' diye soruldu. Bu an bir sınav anıdır ve doğru sorular kadar doğru CÜMLE de sayılır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu cümleler dolaylı sorulardır, yani fiil sona gider. Doğrudan soru sormak kaba değildir ama dolaylısı seviyeni gösterir. Önce kelimeler.")] },
      word("İlk", { de: "die Probezeit", tr: "deneme süresi" }),
      word("İkinci", { de: "der Ablauf", tr: "akış, süreç" }),
      word("Üçüncü", { de: "der Verantwortungsbereich", tr: "sorumluluk alanı" }),
      word("Dördüncü", { de: "das Arbeitspaket", tr: "iş paketi" }),
      word("Beşinci", { de: "der Meilenstein", tr: "kilometre taşı" }, "Projede önceden belirlenmiş ara hedef."),
      word("Altıncı", { de: "die Fertigkeit", tr: "beceri" }),
      word("Yedinci", { de: "die Auffassungsgabe", tr: "kavrayış" }),
      word("Son", { de: "anspruchsvoll", tr: "zorlu" }),
      { say: [tr("Kalıbımız:"), de("Mich würde interessieren, wie …"), tr("Dilek kipiyle giriş, sonra dolaylı soru.")] },
      { say: [tr("Örnek:"), de("Mich würde interessieren, wie die Einarbeitung abläuft."), tr("Tekrar edin:"), de("Mich würde interessieren, wie die Einarbeitung abläuft")], expect: repeat("Mich würde interessieren, wie die Einarbeitung abläuft") },
      { say: [tr("Sıra sende: 'Deneme süresinin nasıl düzenlendiğini merak ediyorum.'")], expect: produce("Mich würde interessieren, wie die Probezeit geregelt ist", [tr("Yan cümlede çekimli fiil en sonda:"), de("Mich würde interessieren, wie die Probezeit geregelt ist."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ne zaman cevap bekleyebilirim?'")], expect: produce("Wann darf ich mit einer Zusage rechnen", [tr("Bu fiilin sabit edatı mit ve yönelme hâli ister:"), de("Wann darf ich mit einer Zusage rechnen?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sürecin nasıl devam ettiğini sorabilir miyim?'")], expect: produce("Darf ich fragen, wie der Ablauf weitergeht", [tr("Dolaylı soruda ayrılabilen fiil sonda birleşir:"), de("Darf ich fragen, wie der Ablauf weitergeht?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Mich würde interessieren, wie ist die Probezeit geregelt."), tr("cümlesi doğru mu?")], expect: truefalse("Mich würde interessieren, wie ist die Probezeit geregelt.", false, [tr("Dolaylı soru bir yan cümledir; çekimli fiil sona gider:"), de("Mich würde interessieren, wie die Probezeit geregelt ist.")]) },
      { say: [tr("Son: 'Sorumluluk alanım ne kadar geniş?'")], expect: produce("Wie groß ist mein Verantwortungsbereich", [tr("Soru sıfatı başta, fiil ikinci sırada:"), de("Wie groß ist mein Verantwortungsbereich?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada mülakatın soru turundasın.")] },
    ],
    roleplay: {
      scene: "Bir iş görüşmesinin sonundasın ve sıra senin sorularında. En az üç şey sor (süreç, ekip, deneme süresi ya da beklentiler), bir cevabı kendi cümlenle özetle ve ne zaman haber alacağını öğren.",
      partner: "açık sözlü, sorulara ayrıntılı cevap veren bir işveren",
      opening: "So weit von unserer Seite. Jetzt sind Sie dran — was möchten Sie noch wissen?",
      openingTr: "Bizim tarafımızdan bu kadar. Şimdi sıra sizde — başka neyi bilmek istersiniz?",
      goal: "En az üç soru sorulmuş, bir cevap özetlenerek doğrulanmış ve ne zaman haber alınacağı öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-praesentation-abschluss",
    icon: "chart",
    level: "B2",
    course: "de",
    title: "Der starke Schluss",
    titleTr: "Sunum kapanışı",
    summary: "Sunumu özet, sonuç ve ileriye bakışla kapatmayı öğretir.",
    minutes: 12,
    focusId: "Nominalisierung",
    vocab: [
      { de: "die Zusammenfassung", tr: "özet" },
      { de: "der Ausblick", tr: "ileriye bakış" },
      { de: "die Aufmerksamkeit", tr: "dikkat, ilgi" },
      { de: "der Zwischenbericht", tr: "ara rapor" },
      { de: "der Projektauftrag", tr: "proje görev tanımı" },
      { de: "die Kennzahl", tr: "gösterge" },
      { de: "die Abweichung", tr: "sapma" },
      { de: "lückenlos", tr: "kesintisiz" },
    ],
    patterns: [
      { de: "Zusammenfassend lässt sich sagen, dass …", tr: "özetler" },
      { de: "Meine Zusammenfassung lautet: …", tr: "sonucu bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! İlk modülde bir sunum açmıştın; şimdi kapatacaksın. Kapanışın üç parçası var: özet, sonuç, ileriye bakış. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kapanış cümleleri kalıptır ve tam olarak kalıp hâlinde kullanılır — burada özgünlük değil, netlik aranır. Önce kelimeler.")] },
      word("İlk", { de: "die Zusammenfassung", tr: "özet" }),
      word("İkinci", { de: "der Ausblick", tr: "ileriye bakış" }),
      word("Üçüncü", { de: "die Aufmerksamkeit", tr: "dikkat, ilgi" }),
      word("Dördüncü", { de: "der Zwischenbericht", tr: "ara rapor" }),
      word("Beşinci", { de: "der Projektauftrag", tr: "proje görev tanımı" }),
      word("Altıncı", { de: "die Kennzahl", tr: "gösterge" }, "Sunumda tek bakışta okunan sayı."),
      word("Yedinci", { de: "die Abweichung", tr: "sapma" }),
      word("Son", { de: "lückenlos", tr: "kesintisiz" }),
      { say: [tr("Kalıbımız:"), de("Zusammenfassend lässt sich sagen, dass …"), tr("Edilgen yerine geçen yapı burada kişiyi cümleden çıkarıyor.")] },
      { say: [tr("Örnek:"), de("Zusammenfassend lässt sich sagen, dass sich der Aufwand gelohnt hat."), tr("Tekrar edin:"), de("Zusammenfassend lässt sich sagen, dass sich der Aufwand gelohnt hat")], expect: repeat("Zusammenfassend lässt sich sagen, dass sich der Aufwand gelohnt hat") },
      { say: [tr("Sıra sende: 'Özetim şu: yöntem işe yarıyor.'")], expect: produce("Meine Zusammenfassung lautet: Das Verfahren funktioniert", [tr("Kalıplaşmış giriş, sonra düz cümle:"), de("Meine Zusammenfassung lautet: Das Verfahren funktioniert."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kısa bir ileriye bakışla bitirmek istiyorum.'")], expect: produce("Ich möchte mit einem kurzen Ausblick schließen", [tr("Edat yönelme hâli ister; mastar sonda:"), de("Ich möchte mit einem kurzen Ausblick schließen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Böylece ara rapor tamamlanmış oluyor.'")], expect: produce("Damit ist der Zwischenbericht vollständig", [tr("Durum bildiren cümle; sıfat sonda:"), de("Damit ist der Zwischenbericht vollständig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Vielen Dank für Ihrer Aufmerksamkeit."), tr("cümlesi doğru mu?")], expect: truefalse("Vielen Dank für Ihrer Aufmerksamkeit.", false, [tr("Bu edat belirtme hâli ister:"), de("Vielen Dank für Ihre Aufmerksamkeit.")]) },
      { say: [tr("Son: 'İlginiz için çok teşekkürler.'")], expect: produce("Vielen Dank für Ihre Aufmerksamkeit", [tr("Edat belirtme hâliyle:"), de("Vielen Dank für Ihre Aufmerksamkeit."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sunumunu kapatıp son soruları alacaksın.")] },
    ],
    roleplay: {
      scene: "Sunumunun sonundasın. Bulgularını özetle, sonucunu tek cümlede söyle, kısa bir ileriye bakış ver, teşekkür et ve gelen son soruyu cevapla.",
      partner: "kapanışta bir sonraki adımı soran bir dinleyici",
      opening: "Bevor Sie schließen: Was heißt das für uns konkret im nächsten Quartal?",
      openingTr: "Kapatmadan önce: Bu bizim için önümüzdeki çeyrekte somut olarak ne anlama geliyor?",
      goal: "Bulgular özetlenmiş, sonuç ve ileriye bakış söylenmiş ve son soru cevaplanarak sunum kapatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-verabschiedung-kollegen",
    icon: "party",
    level: "B2",
    course: "de",
    title: "Der Abschied",
    titleTr: "Veda konuşması",
    summary: "Kısa bir veda konuşmasını geçmişin geçmişiyle kurmayı öğretir.",
    minutes: 12,
    focusId: "Plusquamperfekt",
    vocab: [
      { de: "die Laufbahn", tr: "meslek yolu" },
      { de: "der Werdegang", tr: "meslek geçmişi" },
      { de: "die Verbundenheit", tr: "bağlılık" },
      { de: "die Bewunderung", tr: "hayranlık" },
      { de: "die Zuwendung", tr: "sevgi" },
      { de: "der Lebensabend", tr: "yaşlılık günleri" },
      { de: "wohltuend", tr: "iyi gelen" },
      { de: "gesellig", tr: "sosyal" },
    ],
    patterns: [
      { de: "Nachdem wir … hatten, …", tr: "önce olanı işaretler" },
      { de: "Ich blicke dankbar zurück.", tr: "geriye bakış" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün veda edeceğiz. Veda konuşmalarının zamanı özeldir: önce olanı anlatmak için geçmişin geçmişi kullanılır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu zamanı B1'de öğrenmiştin. Buradaki iş onu bir konuşmanın açılışında kullanmak — 'birlikte çalıştıktan sonra ayrılmak zor geliyor'. Önce kelimeler.")] },
      word("İlk", { de: "die Laufbahn", tr: "meslek yolu" }),
      word("İkinci", { de: "der Werdegang", tr: "meslek geçmişi" }, "Bir insanın nereden nereye geldiği."),
      word("Üçüncü", { de: "die Verbundenheit", tr: "bağlılık" }),
      word("Dördüncü", { de: "die Bewunderung", tr: "hayranlık" }),
      word("Beşinci", { de: "die Zuwendung", tr: "sevgi" }),
      word("Altıncı", { de: "der Lebensabend", tr: "yaşlılık günleri" }),
      word("Yedinci", { de: "wohltuend", tr: "iyi gelen" }),
      word("Son", { de: "gesellig", tr: "sosyal" }),
      { say: [tr("Kalıbımız:"), de("Nachdem wir … hatten, …"), tr("Yan cümlede geçmişin geçmişi, ana cümlede şimdiki ya da geçmiş zaman.")] },
      { say: [tr("Örnek:"), de("Nachdem wir drei Jahre zusammengearbeitet hatten, fällt der Abschied schwer."), tr("Tekrar edin:"), de("Nachdem wir drei Jahre zusammengearbeitet hatten, fällt der Abschied schwer")], expect: repeat("Nachdem wir drei Jahre zusammengearbeitet hatten, fällt der Abschied schwer") },
      { say: [tr("Sıra sende: 'Bu bağlılığı özleyeceğim.'")], expect: produce("Diese Verbundenheit werde ich vermissen", [tr("Nesne öne alınmış; mastar sonda:"), de("Diese Verbundenheit werde ich vermissen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Minnettarlıkla geriye bakıyorum.'")], expect: produce("Ich blicke dankbar zurück", [tr("Ayrılabilen fiilin öneki sonda:"), de("Ich blicke dankbar zurück."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Buna bir kadeh kaldıralım.'")], expect: produce("Lasst uns darauf anstoßen", [tr("Rica biçimi; edat zamirle kaynaşır:"), de("Lasst uns darauf anstoßen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nachdem wir drei Jahre zusammengearbeitet hatten, fällt der Abschied schwer."), tr("cümlesi doğru mu?")], expect: truefalse("Nachdem wir drei Jahre zusammengearbeitet hatten, fällt der Abschied schwer.", true, [tr("Doğru. Önce olan olay geçmişin geçmişinde, sonuç şimdiki zamanda ve yan cümlenin fiili sonda.")]) },
      { say: [tr("Son: 'Senin meslek yolun devam ediyor.'")], expect: produce("Deine Laufbahn geht weiter", [tr("Kısa ve vurgulu bir kapanış:"), de("Deine Laufbahn geht weiter."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada ayrılan bir meslektaşınla vedalaşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın işten ayrılıyor ve veda toplantısındasınız. Birlikte geçen zamanı an, ona ne kattığını söyle, iyi dileklerini ilet ve iletişimi sürdürmek için bir söz alın.",
      partner: "duygulanmış, geriye dönük konuşan bir meslektaş",
      opening: "Fünf Jahre — ich kann es kaum glauben. Weißt du noch, wie chaotisch mein erster Tag war?",
      openingTr: "Beş yıl — inanamıyorum. İlk günümün ne kadar karışık olduğunu hatırlıyor musun?",
      goal: "Ortak bir anı anılmış, iyi dilekler iletilmiş ve iletişimi sürdürmek için somut bir söz alınmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-empfehlung-schreiben",
    icon: "pen",
    level: "B2",
    course: "de",
    title: "Das Empfehlungsschreiben",
    titleTr: "Referans yazmak",
    summary: "Referans mektubunun ortaç yoğun resmî dilini öğretir.",
    minutes: 12,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "das Empfehlungsschreiben", tr: "referans mektubu" },
      { de: "das Abschlusszeugnis", tr: "mezuniyet belgesi" },
      { de: "die Begabung", tr: "kabiliyet" },
      { de: "die Zuverlässigkeit", tr: "güvenilirlik" },
      { de: "zielstrebig", tr: "azimli" },
      { de: "lernbereit", tr: "öğrenmeye istekli" },
      { de: "wissbegierig", tr: "bilgiye aç" },
      { de: "durchsetzungsfähig", tr: "dediğini yaptırabilen" },
    ],
    patterns: [
      { de: "die von ihr geleistete Arbeit", tr: "ortaç öbeği" },
      { de: "ohne Einschränkung empfehlen", tr: "çekincesiz tavsiye" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün birine referans yazacağız. Bu türün dili ortaçlarla doludur ve her kelimesi tartılır — çünkü söylenmeyen de bir anlam taşır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Örneğin 'çekincesiz tavsiye ederim' güçlüdür; sadece 'tavsiye ederim' demek Almancada zayıf sayılır. Önce kelimeler.")] },
      word("İlk", { de: "das Empfehlungsschreiben", tr: "referans mektubu" }),
      word("İkinci", { de: "das Abschlusszeugnis", tr: "mezuniyet belgesi" }),
      word("Üçüncü", { de: "die Begabung", tr: "kabiliyet" }),
      word("Dördüncü", { de: "die Zuverlässigkeit", tr: "güvenilirlik" }),
      word("Beşinci", { de: "zielstrebig", tr: "azimli" }),
      word("Altıncı", { de: "lernbereit", tr: "öğrenmeye istekli" }),
      word("Yedinci", { de: "wissbegierig", tr: "bilgiye aç" }),
      word("Son", { de: "durchsetzungsfähig", tr: "dediğini yaptırabilen" }, "Almanca referansların klasik övgüsü."),
      { say: [tr("Kalıbımız:"), de("die von ihr geleistete Arbeit"), tr("Ortaç öbeği ismin önünde; kim yaptığı araya giriyor.")] },
      { say: [tr("Örnek:"), de("Die von ihr geleistete Arbeit war stets zuverlässig."), tr("Tekrar edin:"), de("Die von ihr geleistete Arbeit war stets zuverlässig")], expect: repeat("Die von ihr geleistete Arbeit war stets zuverlässig") },
      { say: [tr("Sıra sende: 'Özellikle kabiliyetiyle ikna etti.'")], expect: produce("Sie überzeugte besonders durch ihre Begabung", [tr("Edat belirtme hâli ister; geçmiş zaman tek fiille:"), de("Sie überzeugte besonders durch ihre Begabung."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Verilen görevleri bağımsız çözdü.'")], expect: produce("Die übertragenen Aufgaben löste sie selbstständig", [tr("Ortaç çoğulda -en ekini alır; nesne öne alınmış:"), de("Die übertragenen Aufgaben löste sie selbstständig."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Onu çekincesiz tavsiye ediyorum.'")], expect: produce("Ich empfehle sie ohne Einschränkung", [tr("Kalıplaşmış ifade; edat belirtme hâliyle:"), de("Ich empfehle sie ohne Einschränkung."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die übertragene Aufgaben löste sie selbstständig."), tr("cümlesi doğru mu?")], expect: truefalse("Die übertragene Aufgaben löste sie selbstständig.", false, [tr("Belirtili çoğulda ortaç -en ekini alır:"), de("Die übertragenen Aufgaben löste sie selbstständig.")]) },
      { say: [tr("Son: 'Her zaman azimli ve öğrenmeye istekliydi.'")], expect: produce("Sie war stets zielstrebig und lernbereit", [tr("İki sıfat bağlaçla:"), de("Sie war stets zielstrebig und lernbereit."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada birine referans yazmayı konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir eski ekip arkadaşın senden referans mektubu istiyor. Hangi güçlü yanlarını yazacağını konuş, hangi örneği kullanacağını sor, dürüst kalabileceğin sınırı söyle ve ne zaman hazır olacağını bildir.",
      partner: "heyecanlı, kendisi hakkında çok şey yazılmasını isteyen eski bir ekip arkadaşı",
      opening: "Wäre das okay für dich? Und könntest du auch etwas über meine Führungsqualitäten schreiben?",
      openingTr: "Senin için uygun olur mu? Ve liderlik özelliklerim hakkında da bir şey yazabilir misin?",
      goal: "Hangi güçlü yanların yazılacağı ve hangi örneğin kullanılacağı kararlaşmış, dürüstlük sınırı söylenmiş ve teslim zamanı bildirilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-kulturschock-rueckwaerts",
    icon: "plane",
    level: "B2",
    course: "de",
    title: "Fremd im eigenen Land",
    titleTr: "Tersine kültür şoku",
    summary: "İki yer arasında kalmayı als ob ile anlatmayı öğretir.",
    minutes: 12,
    focusId: "Als-ob",
    vocab: [
      { de: "sich entfremden", tr: "yabancılaşmak" },
      { de: "die Weltoffenheit", tr: "dünyaya açıklık" },
      { de: "die Eingliederung", tr: "topluma uyum" },
      { de: "die Herkunftssprache", tr: "köken dili" },
      { de: "das Aufnahmeland", tr: "kabul eden ülke" },
      { de: "die Willkommenskultur", tr: "karşılama kültürü" },
      { de: "die Parallelgesellschaft", tr: "paralel toplum" },
      { de: "mehrsprachig", tr: "çok dilli" },
    ],
    patterns: [
      { de: "Es fühlt sich an, als ob …", tr: "hissi tarif eder" },
      { de: "Beides ist Heimat.", tr: "iki aidiyeti birlikte söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün tuhaf bir duyguyu anlatacağız: kendi ülkene döndüğünde yabancı hissetmek. Bunun dili 'sanki' yapısıdır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Çünkü bu duygu bir olgu değil bir benzetmedir: yabancı DEĞİLSİN ama öyle hissediyorsun. Dilek kipi tam olarak bunu taşır. Önce kelimeler.")] },
      word("İlk", { de: "sich entfremden", tr: "yabancılaşmak" }),
      word("İkinci", { de: "die Herkunftssprache", tr: "köken dili" }, "Evde konuşulan, ilk öğrenilen dil."),
      word("Üçüncü", { de: "das Aufnahmeland", tr: "kabul eden ülke" }),
      word("Dördüncü", { de: "die Eingliederung", tr: "topluma uyum" }),
      word("Beşinci", { de: "die Willkommenskultur", tr: "karşılama kültürü" }),
      word("Altıncı", { de: "die Parallelgesellschaft", tr: "paralel toplum" }),
      word("Yedinci", { de: "die Weltoffenheit", tr: "dünyaya açıklık" }),
      word("Son", { de: "mehrsprachig", tr: "çok dilli" }),
      { say: [tr("Kalıbımız:"), de("Es fühlt sich an, als ob …"), tr("Duyguyu tarif etmenin en doğal biçimi.")] },
      { say: [tr("Örnek:"), de("Es fühlt sich an, als ob ich hier fremd wäre."), tr("Tekrar edin:"), de("Es fühlt sich an, als ob ich hier fremd wäre")], expect: repeat("Es fühlt sich an, als ob ich hier fremd wäre") },
      { say: [tr("Sıra sende: 'Her şey aynı ama ben başkayım.'")], expect: produce("Alles ist gleich, aber ich bin anders", [tr("İki kısa cümle, zıtlık bağlacıyla:"), de("Alles ist gleich, aber ich bin anders."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İkisi de memleket.'")], expect: produce("Beides ist Heimat", [tr("Belirsiz zamir tekil çekim alır:"), de("Beides ist Heimat."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Şimdi ikisine de daha açık bakıyorum.'")], expect: produce("Jetzt sehe ich beides mit mehr Weltoffenheit", [tr("Zarf başta, fiil ikinci sırada; edat yönelme hâli ister:"), de("Jetzt sehe ich beides mit mehr Weltoffenheit."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es fühlt sich an, als ob ich hier fremd bin."), tr("cümlesi doğru mu?")], expect: truefalse("Es fühlt sich an, als ob ich hier fremd bin.", false, [tr("Bu bağlaçtan sonra dilek kipi gelir, çünkü söylenen gerçek değil bir benzetmedir:"), de("Es fühlt sich an, als ob ich hier fremd wäre.")]) },
      { say: [tr("Son: 'Nereye ait olduğumu bilmiyorum.'")], expect: produce("Ich weiß nicht, wohin ich gehöre", [tr("Dolaylı soruda fiil sonda:"), de("Ich weiß nicht, wohin ich gehöre."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada iki ülke arasındaki hayatını anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Uzun bir aradan sonra eski memleketine döndün ve bir yakınınla konuşuyorsun: ne değişmiş, sen ne değişmişsin, nereye ait hissediyorsun ve bundan sonra nasıl olacak.",
      partner: "seni özlemiş ama değişimini fark etmiş bir yakın",
      opening: "Du bist zurück — und trotzdem ist irgendetwas anders. Liegt es an uns oder an dir?",
      openingTr: "Döndün — ama yine de bir şey farklı. Bizden mi, senden mi?",
      goal: "Neyin değiştiği iki taraftan da anlatılmış, aidiyet duygusu ifade edilmiş ve bundan sonrası için bir şey söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-c1-vorbereitung",
    icon: "school",
    level: "B2",
    course: "de",
    title: "Fit für C1?",
    titleTr: "C1'e hazırlık",
    summary: "Kendi seviyeni değerlendirip hedefli plan yapmayı öğretir.",
    minutes: 12,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "die Wissenslücke", tr: "bilgi eksiği" },
      { de: "die Lernmethode", tr: "öğrenme yöntemi" },
      { de: "festigen", tr: "pekiştirmek" },
      { de: "sich einprägen", tr: "aklına kazımak" },
      { de: "aufholen", tr: "açığı kapatmak" },
      { de: "erlernen", tr: "öğrenip edinmek" },
      { de: "sich spezialisieren", tr: "uzmanlaşmak" },
      { de: "fortgeschritten", tr: "ileri düzey" },
    ],
    patterns: [
      { de: "Das dürfte machbar sein.", tr: "temkinli iyimserlik" },
      { de: "Wo ist noch eine Wissenslücke?", tr: "zayıf noktayı sorar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Sondan bir önceki ders ve konusu sen: B2'yi bitirdin, C1 ne kadar uzakta? Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kendi seviyeni değerlendirirken ne fazla iddialı ne fazla kararsız olmak gerekiyor — öznel kip fiilleri tam bu ölçüyü veriyor. Önce kelimeler.")] },
      word("İlk", { de: "die Wissenslücke", tr: "bilgi eksiği" }),
      word("İkinci", { de: "die Lernmethode", tr: "öğrenme yöntemi" }),
      word("Üçüncü", { de: "festigen", tr: "pekiştirmek" }, "Bilineni sağlamlaştırmak."),
      word("Dördüncü", { de: "sich einprägen", tr: "aklına kazımak" }),
      word("Beşinci", { de: "aufholen", tr: "açığı kapatmak" }),
      word("Altıncı", { de: "erlernen", tr: "öğrenip edinmek" }),
      word("Yedinci", { de: "sich spezialisieren", tr: "uzmanlaşmak" }),
      word("Son", { de: "fortgeschritten", tr: "ileri düzey" }),
      { say: [tr("Kalıbımız:"), de("Das dürfte machbar sein."), tr("Ne 'kesin yaparım' ne 'yapamam' — ölçülü bir güven.")] },
      { say: [tr("Örnek:"), de("Das dürfte machbar sein, wenn du regelmäßig übst."), tr("Tekrar edin:"), de("Das dürfte machbar sein, wenn du regelmäßig übst")], expect: repeat("Das dürfte machbar sein, wenn du regelmäßig übst") },
      { say: [tr("Sıra sende: 'Nerede hâlâ bilgi eksiği var?'")], expect: produce("Wo ist noch eine Wissenslücke", [tr("Soru kelimesi başta, fiil ikinci sırada:"), de("Wo ist noch eine Wissenslücke?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Öğrenme yöntemimi biliyorum.'")], expect: produce("Ich kenne meine Lernmethode", [tr("Nesne belirtme hâlinde:"), de("Ich kenne meine Lernmethode."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yazmada epey açığımı kapattım.'")], expect: produce("Im Schreiben habe ich viel aufgeholt", [tr("İsimleşmiş mastar tümleç olarak başta; ayrılabilen ortaç sonda:"), de("Im Schreiben habe ich viel aufgeholt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das dürfte machbar sein, wenn du regelmäßig übst."), tr("cümlesi doğru mu?")], expect: truefalse("Das dürfte machbar sein, wenn du regelmäßig übst.", true, [tr("Doğru. Kip fiili ölçülü bir tahmin veriyor ve koşul yan cümlesinin fiili sonda duruyor.")]) },
      { say: [tr("Son: 'Bilgimi pekiştirmek istiyorum.'")], expect: produce("Ich möchte mein Wissen festigen", [tr("Nesne ortada; mastar en sonda:"), de("Ich möchte mein Wissen festigen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir öğretmenle C1 planını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir öğretmenle C1'e hazırlığını konuşuyorsun: hangi beceride iyisin, nerede aksıyorsun, ne kadar sürede hazır olabilirsin ve nasıl çalışacaksın.",
      partner: "dürüst değerlendirme yapan, plan kurmayı seven bir öğretmen",
      opening: "Sie haben B2 abgeschlossen — gut gemacht. Sagen Sie mir ehrlich: Wo ist Ihrer Meinung nach noch eine Wissenslücke?",
      openingTr: "B2'yi tamamladınız — tebrikler. Dürüstçe söyleyin: Sizce hâlâ nerede bilgi eksiği var?",
      goal: "Güçlü ve zayıf beceriler adlandırılmış, bir süre hedefi konuşulmuş ve somut bir çalışma planı kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-rueckblick",
    icon: "star",
    level: "B2",
    course: "de",
    title: "Vom Können zum Beherrschen",
    titleTr: "B2 kapanışı",
    summary: "Kat edilen yolu edilgen geçmişle özetlemeyi öğretir.",
    minutes: 12,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "die Etappe", tr: "etap" },
      { de: "zurücklegen", tr: "kat etmek" },
      { de: "beherrschen", tr: "hâkim olmak" },
      { de: "der Wortschatz", tr: "kelime hazinesi" },
      { de: "der Sprachkurs", tr: "dil kursu" },
      { de: "der Muttersprachler", tr: "ana dili konuşuru" },
      { de: "begreifen", tr: "kavramak" },
      { de: "akzentfrei", tr: "aksansız" },
    ],
    patterns: [
      { de: "Vieles ist erreicht worden.", tr: "kat edilen yol" },
      { de: "Rückblickend …", tr: "geriye bakarak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Son ders. B2'nin ilk modülünde edilgen geçmişi öğrenmiştin; seviyeyi onunla kapatıyoruz — çünkü bu seviyede olan biten senin başına gelmedi, sen yaptın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yüz ders boyunca kurum dilini, edilgeni, aktarılan sözü, ortaç sıfatlarını ve neden-sonuç dilini kurdun. Bugün hepsini bir cümlede toplayacağız. Önce kelimeler.")] },
      word("İlk", { de: "die Etappe", tr: "etap" }),
      word("İkinci", { de: "zurücklegen", tr: "kat etmek" }),
      word("Üçüncü", { de: "beherrschen", tr: "hâkim olmak" }, "Bilmekten bir adım ötesi: kullanabilmek."),
      word("Dördüncü", { de: "der Wortschatz", tr: "kelime hazinesi" }),
      word("Beşinci", { de: "der Sprachkurs", tr: "dil kursu" }),
      word("Altıncı", { de: "der Muttersprachler", tr: "ana dili konuşuru" }),
      word("Yedinci", { de: "begreifen", tr: "kavramak" }),
      word("Son", { de: "akzentfrei", tr: "aksansız" }),
      { say: [tr("Kalıbımız:"), de("Vieles ist erreicht worden."), tr("Seviyenin ilk dersinde kurduğun yapı, son cümlesinde geri dönüyor.")] },
      { say: [tr("Tekrar edin:"), de("Vieles ist in diesem Jahr erreicht worden")], expect: repeat("Vieles ist in diesem Jahr erreicht worden") },
      { say: [tr("Sıra sende: 'Uzun bir yol kat edildi.'")], expect: produce("Ein langer Weg ist zurückgelegt worden", [tr("Ayrılabilen fiilin ortacı; kısalmış biçim sonda:"), de("Ein langer Weg ist zurückgelegt worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Dile artık gerçekten hâkimim.'")], expect: produce("Ich beherrsche die Sprache jetzt wirklich", [tr("Ayrılmayan fiil; nesne belirtme hâlinde:"), de("Ich beherrsche die Sprache jetzt wirklich."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Geriye bakınca kelime hazinesi büyümüş.'")], expect: produce("Rückblickend ist der Wortschatz gewachsen", [tr("Zarf başta, fiil ikinci sırada; ortaç sonda:"), de("Rückblickend ist der Wortschatz gewachsen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ein langer Weg ist zurückgelegt geworden."), tr("cümlesi doğru mu?")], expect: truefalse("Ein langer Weg ist zurückgelegt geworden.", false, [tr("Edilgen geçmişte yardımcı fiil kısalır — B2'nin ilk modülünde öğrendiğin kural:"), de("Ein langer Weg ist zurückgelegt worden.")]) },
      { say: [tr("Son: 'Bir sonraki etabın adı C1.'")], expect: produce("Die nächste Etappe heißt C1", [tr("Kısa ve net bir kapanış:"), de("Die nächste Etappe heißt C1."), tr("Tekrar dene.")]) },
      { say: [tr("B2'yi bitirdin. Konuşmada bu yolu birlikte değerlendireceksin — son kez.")] },
    ],
    roleplay: {
      scene: "Öğretmeninle B2'nin sonunda bir değerlendirme yapıyorsun: yol nasıl geçti, en zoru neydi, neyi artık gerçekten yapabiliyorsun, neyle gurur duyuyorsun ve bundan sonra ne var.",
      partner: "seni baştan beri izlemiş, dürüst ve destekleyici bir öğretmen",
      opening: "Hundert Lektionen sind geschafft. Bevor wir abschließen: Was können Sie heute, was Sie am Anfang nicht konnten?",
      openingTr: "Yüz ders tamamlandı. Kapatmadan önce: Bugün başlangıçta yapamadığınız neyi yapabiliyorsunuz?",
      goal: "Kat edilen yol, en zor kısım ve artık yapılabilenler anlatılmış; bundan sonraki hedef söylenmiş olur.",
      minTurns: 9,
    },
  },
];
