import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 6 — Toplum ve ekonomi (051–060).
 *
 * Bu modülün dilbilgisel omurgası tamlayan hâli isteyen edatlar (wegen,
 * trotz, während, aufgrund, infolge, angesichts) ve orantı bağlacı (je …
 * desto). İkisinin ortak işi aynı: NEDEN-SONUÇ ilişkisini tek cümlede,
 * yan cümle kurmadan söylemek.
 *
 * Bunun neden bu modülde olduğu içerikle ilgili: toplumsal ve ekonomik
 * konularda konuşmak, olguları birbirine bağlamayı gerektiriyor. "Kira
 * arttı" bir haber; "talep arzı aştığı için kira arttı" bir argüman. B2
 * öğrencisinden beklenen ikincisi.
 *
 * Not: günlük konuşmada bu edatlardan sonra yönelme hâli de duyulur ve
 * yanlış sayılmaz. Dersler bunu saklamıyor ama sınav ve yazı için tamlayan
 * hâlini çalıştırıyor — seviyeyi belli eden ayrıntı orası.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B06: Lesson[] = [
  {
    id: "de-b2-wegen-trotz",
    icon: "weather",
    level: "B2",
    course: "de",
    title: "Wegen des Wetters, trotz allem",
    titleTr: "Genitiv edatları",
    summary: "Sebep ve zıtlığı tamlayan hâli isteyen edatlarla kurmayı öğretir.",
    minutes: 12,
    focusId: "Genitivpräpositionen",
    vocab: [
      { de: "das Unwetter", tr: "fırtına" },
      { de: "der Niederschlag", tr: "yağış" },
      { de: "der Hagel", tr: "dolu" },
      { de: "der Frost", tr: "don" },
      { de: "das Tauwetter", tr: "karların erimesi" },
      { de: "die Temperaturschwankung", tr: "sıcaklık dalgalanması" },
      { de: "der Umstand", tr: "koşul" },
      { de: "betreffen", tr: "ilgilendirmek" },
    ],
    patterns: [
      { de: "wegen + Genitiv", tr: "sebep bildirir" },
      { de: "trotz + Genitiv", tr: "zıtlık bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: toplum ve ekonomi. Ama bu konuları konuşabilmek için önce olguları birbirine bağlamayı öğreneceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki edatla başlıyoruz: biri sebep, biri zıtlık. İkisi de tamlayan hâli ister. Günlük dilde yönelme hâli de duyarsın ama yazıda ve sınavda beklenen bu. Önce kelimeler.")] },
      word("İlk", { de: "das Unwetter", tr: "fırtına" }),
      word("İkinci", { de: "der Niederschlag", tr: "yağış" }, "Hava raporunun yağmur ve kar için ortak sözcüğü."),
      word("Üçüncü", { de: "der Hagel", tr: "dolu" }),
      word("Dördüncü", { de: "der Frost", tr: "don" }),
      word("Beşinci", { de: "das Tauwetter", tr: "karların erimesi" }),
      word("Altıncı", { de: "die Temperaturschwankung", tr: "sıcaklık dalgalanması" }),
      word("Yedinci", { de: "der Umstand", tr: "koşul" }),
      word("Son", { de: "betreffen", tr: "ilgilendirmek" }),
      { say: [tr("Kalıbımız:"), de("wegen des Unwetters"), tr("Eril ve nötr isimler tamlayan hâlinde bir ek alıyor; belirteç de değişiyor.")] },
      { say: [tr("Örnek:"), de("Wegen des Unwetters ist das Konzert ausgefallen."), tr("Tekrar edin:"), de("Wegen des Unwetters ist das Konzert ausgefallen")], expect: repeat("Wegen des Unwetters ist das Konzert ausgefallen") },
      { say: [tr("Sıra sende, bu kez zıtlıkla: 'Fırtınaya rağmen gitti.'")], expect: produce("Trotz des Unwetters ist er gegangen", [tr("Tümleç başta, yardımcı fiil ikinci sırada, ortaç sonda:"), de("Trotz des Unwetters ist er gegangen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Doluya rağmen tarihte kalıyoruz.'")], expect: produce("Trotz des Hagels bleiben wir bei dem Termin", [tr("Tümleç başta, fiil ikinci sırada; edat tamlayan hâli ister:"), de("Trotz des Hagels bleiben wir bei dem Termin."), tr("Tekrar dene.")], ["Trotz des Hagels bleiben wir beim Termin"]) },
      { say: [tr("Bir tane daha: 'Bu durumda değişen bir şey yok.'")], expect: produce("An diesem Umstand ändert sich nichts", [tr("Tümleç başta, fiil ikinci sırada, dönüşlü zamir hemen sonra:"), de("An diesem Umstand ändert sich nichts."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Trotz des Unwetters er ist gegangen."), tr("cümlesi doğru mu?")], expect: truefalse("Trotz des Unwetters er ist gegangen.", false, [tr("Cümle bir tümleçle başlayınca çekimli fiil ikinci sıraya gelir, özne arkasına geçer:"), de("Trotz des Unwetters ist er gegangen.")]) },
      { say: [tr("Son: 'Bu sıcaklık dalgalanması hepimizi ilgilendiriyor.'")], expect: produce("Diese Temperaturschwankung betrifft uns alle", [tr("Nesne belirtme hâlinde:"), de("Diese Temperaturschwankung betrifft uns alle."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada iptal olan bir etkinliği konuşacaksın: neden iptal oldu, neye rağmen ne yapılıyor.")] },
    ],
    roleplay: {
      scene: "Katılacağın bir etkinlik hava yüzünden iptal oldu. Düzenleyiciyle konuş: neden iptal edildiğini öğren, yine de yapılabilecek bir şey olup olmadığını sor ve yeni bir tarih ya da iade konuş.",
      partner: "üzgün ama çözüm üretmeye çalışan bir etkinlik düzenleyicisi",
      opening: "Wegen des Unwetters mussten wir absagen — es tut mir wirklich leid. Waren Sie schon angereist?",
      openingTr: "Fırtına yüzünden iptal etmek zorunda kaldık — gerçekten çok üzgünüm. Yola çıkmış mıydınız?",
      goal: "İptalin sebebi öğrenilmiş ve yeni bir tarih ya da iade konusunda bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-aufgrund-infolge",
    icon: "office",
    level: "B2",
    course: "de",
    title: "Aufgrund der Lage",
    titleTr: "Resmî neden dili",
    summary: "Resmî duyuru dilinde sebep bildiren edatları kullanmayı öğretir.",
    minutes: 12,
    focusId: "Genitivpräpositionen",
    vocab: [
      { de: "die Maßnahme", tr: "tedbir" },
      { de: "angesichts", tr: "…-in karşısında" },
      { de: "die Bekanntmachung", tr: "resmî duyuru" },
      { de: "erlassen", tr: "yürürlüğe koymak" },
      { de: "aussetzen", tr: "askıya almak" },
      { de: "vorübergehend", tr: "geçici" },
      { de: "gegebenenfalls", tr: "gerekirse" },
      { de: "ordnungsgemäß", tr: "kurallara uygun" },
    ],
    patterns: [
      { de: "aufgrund + Genitiv", tr: "resmî sebep" },
      { de: "infolge + Genitiv", tr: "sonucunda" },
    ],
    lecture: [
      { say: [tr("Merhaba! Dün günlük sebep edatlarını kurduk; bugün onların resmî kardeşleri. Duyurularda, kararlarda ve haberlerde bunları görürsün. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Aralarında ince bir fark var: biri sebebi, öteki sonucu vurgular, üçüncüsü de bir durumun karşısında alınan tavrı. Önce kelimeler.")] },
      word("İlk", { de: "die Maßnahme", tr: "tedbir" }),
      word("İkinci", { de: "angesichts", tr: "…-in karşısında" }, "Ardından tamlayan hâli gelir."),
      word("Üçüncü", { de: "die Bekanntmachung", tr: "resmî duyuru" }),
      word("Dördüncü", { de: "erlassen", tr: "yürürlüğe koymak" }),
      word("Beşinci", { de: "aussetzen", tr: "askıya almak" }),
      word("Altıncı", { de: "vorübergehend", tr: "geçici" }),
      word("Yedinci", { de: "gegebenenfalls", tr: "gerekirse" }, "Resmî yazının 'duruma göre' demenin yolu."),
      word("Son", { de: "ordnungsgemäß", tr: "kurallara uygun" }),
      { say: [tr("Kalıbımız:"), de("aufgrund + tamlayan hâli"), tr("Resmî yazışmanın en sık sebep bağlacı.")] },
      { say: [tr("Örnek:"), de("Aufgrund der aktuellen Lage bleibt das Amt geschlossen."), tr("Tekrar edin:"), de("Aufgrund der aktuellen Lage bleibt das Amt geschlossen")], expect: repeat("Aufgrund der aktuellen Lage bleibt das Amt geschlossen") },
      { say: [tr("Sıra sende: 'Yeni tedbirin sonucunda hizmet durduruldu.'")], expect: produce("Infolge der neuen Maßnahme wurde der Dienst eingestellt", [tr("Sonuç bildiren edat tamlayan hâli ister; edilgen geçmiş zamanda:"), de("Infolge der neuen Maßnahme wurde der Dienst eingestellt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Durum karşısında bir tedbir alındı.'")], expect: produce("Angesichts der Lage wurde eine Maßnahme ergriffen", [tr("Bu edat da tamlayan hâli ister:"), de("Angesichts der Lage wurde eine Maßnahme ergriffen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Duyuru geçici olarak geçerli.'")], expect: produce("Die Bekanntmachung gilt vorübergehend", [tr("Kısa ve resmî bir cümle:"), de("Die Bekanntmachung gilt vorübergehend."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Aufgrund der aktuellen Lage bleibt das Amt geschlossen."), tr("cümlesi doğru mu?")], expect: truefalse("Aufgrund der aktuellen Lage bleibt das Amt geschlossen.", true, [tr("Doğru. Edattan sonra tamlayan hâli var, sıfat ek almış ve tümleç başta olduğu için fiil ikinci sırada.")]) },
      { say: [tr("Son: 'İşleyiş ikinci bir duyuruya kadar askıya alındı.'")], expect: produce("Der Betrieb wurde bis auf Weiteres ausgesetzt", [tr("Edilgen geçmiş; ayrılabilen fiilin ortacı en sonda:"), de("Der Betrieb wurde bis auf Weiteres ausgesetzt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kurumun aldığı kararı ve gerekçesini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir kurumun hizmeti geçici olarak durduruldu ve sen bilgi almak için aradın. Kararın gerekçesini sor, ne kadar süreceğini öğren, seni nasıl etkilediğini anlat ve bir alternatif iste.",
      partner: "resmî dille konuşan, kuralları tekrarlayan bir görevli",
      opening: "Aufgrund der aktuellen Lage ist der Dienst vorläufig eingestellt. Worum geht es bei Ihnen konkret?",
      openingTr: "Mevcut durum sebebiyle hizmet geçici olarak durduruldu. Sizin konunuz tam olarak nedir?",
      goal: "Kararın gerekçesi ve süresi öğrenilmiş, etkisi anlatılmış ve bir alternatif ya da istisna konuşulmuş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-inflation",
    icon: "money",
    level: "B2",
    course: "de",
    title: "Alles wird teurer",
    titleTr: "Enflasyon sohbeti",
    summary: "Fiyat artışını isimleşmiş ekonomi diliyle anlatmayı öğretir.",
    minutes: 12,
    focusId: "Nominalisierung",
    vocab: [
      { de: "die Inflation", tr: "enflasyon" },
      { de: "spürbar", tr: "hissedilir" },
      { de: "die Konjunktur", tr: "konjonktür" },
      { de: "die Rezession", tr: "resesyon" },
      { de: "der Aufschwung", tr: "ekonomik canlanma" },
      { de: "der Verbraucher", tr: "tüketici" },
      { de: "die Verschuldung", tr: "borçlanma" },
      { de: "schwanken", tr: "dalgalanmak" },
    ],
    patterns: [
      { de: "die Zunahme der Preise", tr: "isimleşmiş artış" },
      { de: "im Vergleich zum letzten Jahr", tr: "kıyaslama kalıbı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün herkesin konuştuğu konu: her şeyin pahalanması. Ekonomi dili bunu fiillerle değil isimlerle söyler ve o isimler tamlama hâliyle bağlanır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de çoğulda yönelme hâlinin küçük bir eki var — 'bei Lebensmitteln' gibi. Bunu dersin sonunda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "die Inflation", tr: "enflasyon" }),
      word("İkinci", { de: "spürbar", tr: "hissedilir" }),
      word("Üçüncü", { de: "die Konjunktur", tr: "konjonktür" }, "Ekonominin genel gidişatı."),
      word("Dördüncü", { de: "die Rezession", tr: "resesyon" }),
      word("Beşinci", { de: "der Aufschwung", tr: "ekonomik canlanma" }, "Resesyonun karşıtı."),
      word("Altıncı", { de: "der Verbraucher", tr: "tüketici" }),
      word("Yedinci", { de: "die Verschuldung", tr: "borçlanma" }),
      word("Son", { de: "schwanken", tr: "dalgalanmak" }),
      { say: [tr("Kalıbımız:"), de("der Anstieg der Preise"), tr("İki isim tamlama hâliyle bağlanıyor; fiil hiç yok.")] },
      { say: [tr("Örnek:"), de("Die Zunahme der Preise ist im Alltag deutlich spürbar."), tr("Tekrar edin:"), de("Die Zunahme der Preise ist im Alltag deutlich spürbar")], expect: repeat("Die Zunahme der Preise ist im Alltag deutlich spürbar") },
      { say: [tr("Sıra sende: 'Bunu ilk tüketici hissediyor.'")], expect: produce("Der Verbraucher spürt es zuerst", [tr("Tekil özne; fiil tekil çekimde:"), de("Der Verbraucher spürt es zuerst."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Geçen yıla göre her şey daha pahalı.'")], expect: produce("Im Vergleich zum letzten Jahr ist alles teurer", [tr("Kalıplaşmış kıyaslama başta, fiil ikinci sırada:"), de("Im Vergleich zum letzten Jahr ist alles teurer."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Fiyat artışı özellikle gıdada hissediliyor.'")], expect: produce("Die Inflation ist besonders bei Lebensmitteln spürbar", [tr("Çoğul yönelme hâlinde isim -n eki alır:"), de("Die Inflation ist besonders bei Lebensmitteln spürbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Inflation ist besonders bei Lebensmittel spürbar."), tr("cümlesi doğru mu?")], expect: truefalse("Die Inflation ist besonders bei Lebensmittel spürbar.", false, [tr("Çoğul yönelme hâlinde isim -n ekini alır:"), de("Die Inflation ist besonders bei Lebensmitteln spürbar.")]) },
      { say: [tr("Son: 'Borçlanma artmaya devam ediyor.'")], expect: produce("Die Verschuldung wächst weiter", [tr("Kısa bir hüküm cümlesi; zarf en sonda:"), de("Die Verschuldung wächst weiter."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada pahalılığın günlük hayatına etkisini anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla pahalılığı konuşuyorsunuz: nerede en çok hissediyorsun, neyi değiştirdin, geçen yıla göre ne fark var. Somut örneklerle anlat.",
      partner: "kendi örneklerini de anlatan, karşılaştırma yapan bir tanıdık",
      opening: "Ich habe gestern den Kassenzettel angeschaut und wollte es nicht glauben. Wo merken Sie es am stärksten?",
      openingTr: "Dün fişe baktım ve inanmak istemedim. Siz en çok nerede fark ediyorsunuz?",
      goal: "Pahalılığın en çok hissedildiği alanlar ve değiştirilen alışkanlıklar karşılıklı anlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-wohnungsmarkt",
    icon: "home",
    level: "B2",
    course: "de",
    title: "Der enge Markt",
    titleTr: "Konut piyasası",
    summary: "Orantı bağlacıyla arz-talep ilişkisini anlatmayı öğretir.",
    minutes: 12,
    focusId: "Je-desto",
    vocab: [
      { de: "der Wohnraum", tr: "konut" },
      { de: "der Neubau", tr: "yeni yapı" },
      { de: "der Leerstand", tr: "boş konut" },
      { de: "die Sozialwohnung", tr: "sosyal konut" },
      { de: "die Wohnfläche", tr: "kullanım alanı" },
      { de: "der Mietspiegel", tr: "kira endeksi" },
      { de: "die Gentrifizierung", tr: "soylulaştırma" },
      { de: "der Makler", tr: "emlakçı" },
    ],
    patterns: [
      { de: "Je …, desto …", tr: "orantı: ne kadar … o kadar" },
      { de: "Die Nachfrage ist größer als das Angebot.", tr: "arz-talep dengesizliği" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün iki şeyin birlikte değiştiğini anlatacağız: biri artınca öteki de artıyor. Almancanın bunun için çift parçalı bir bağlacı var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural biraz tuhaf: ilk parçada fiil sona gider, ikinci parçada hemen sıfattan sonra gelir. Ezberlenecek bir kalıp. Önce kelimeler.")] },
      word("İlk", { de: "der Wohnraum", tr: "konut" }, "Oturulacak alan; kira tartışmasının resmî sözcüğü."),
      word("İkinci", { de: "der Neubau", tr: "yeni yapı" }),
      word("Üçüncü", { de: "der Leerstand", tr: "boş konut" }),
      word("Dördüncü", { de: "die Sozialwohnung", tr: "sosyal konut" }),
      word("Beşinci", { de: "die Wohnfläche", tr: "kullanım alanı" }),
      word("Altıncı", { de: "der Mietspiegel", tr: "kira endeksi" }, "Bir semtte kiranın ne olması gerektiğini gösteren resmî tablo."),
      word("Yedinci", { de: "die Gentrifizierung", tr: "soylulaştırma" }),
      word("Son", { de: "der Makler", tr: "emlakçı" }),
      { say: [tr("Kalıbımız:"), de("Je …, desto …"), tr("İkisinden sonra da karşılaştırma biçimi gelir.")] },
      { say: [tr("Örnek:"), de("Je zentraler die Wohnung ist, desto teurer ist die Miete."), tr("Tekrar edin:"), de("Je zentraler die Wohnung ist, desto teurer ist die Miete")], expect: repeat("Je zentraler die Wohnung ist, desto teurer ist die Miete") },
      { say: [tr("Sıra sende: 'Talep arzdan büyük.'")], expect: produce("Die Nachfrage ist größer als das Angebot", [tr("Karşılaştırma als ile; iki taraf da yalın hâlde:"), de("Die Nachfrage ist größer als das Angebot."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ne kadar çok yeni yapı olursa kiralar o kadar durulur.'")], expect: produce("Je mehr neu gebaut wird, desto ruhiger werden die Mieten", [tr("İlk parçada fiil sonda, ikincide sıfattan hemen sonra:"), de("Je mehr neu gebaut wird, desto ruhiger werden die Mieten."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kırsalda boş konut var.'")], expect: produce("Auf dem Land gibt es Leerstand", [tr("Kalıplaşmış yer ifadesi başta, fiil ikinci sırada:"), de("Auf dem Land gibt es Leerstand."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Je zentraler die Wohnung ist, desto die Miete ist teurer."), tr("cümlesi doğru mu?")], expect: truefalse("Je zentraler die Wohnung ist, desto die Miete ist teurer.", false, [tr("İkinci parçada karşılaştırma biçimi bağlacın hemen arkasına gelir:"), de("Je zentraler die Wohnung ist, desto teurer ist die Miete.")]) },
      { say: [tr("Son: 'Uygun fiyatlı konut zor bulunuyor.'")], expect: produce("Bezahlbarer Wohnraum ist schwer zu finden", [tr("sein artı zu artı mastar; imkânsızlığa yakın zorluk:"), de("Bezahlbarer Wohnraum ist schwer zu finden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada konut piyasasını tartışacaksın: neden böyle, ne yapılabilir.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla konut piyasasını konuşuyorsunuz: kiralar neden bu kadar yükseldi, merkez ile kırsal arasındaki fark ne, ne yapılabilir. Orantı cümleleriyle bağlantı kur.",
      partner: "kendi ev arama deneyimini anlatan, çözüme meraklı bir tanıdık",
      opening: "Ich suche seit vier Monaten und habe noch nichts gefunden. Woran liegt das eigentlich?",
      openingTr: "Dört aydır arıyorum ve hâlâ bir şey bulamadım. Bunun sebebi ne aslında?",
      goal: "Kiraların yükselme sebebi orantı cümleleriyle açıklanmış ve en az bir çözüm önerisi tartışılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-arbeitsmarkt",
    icon: "job",
    level: "B2",
    course: "de",
    title: "Fachkräfte gesucht",
    titleTr: "İş gücü piyasası",
    summary: "Eleman açığını edilgen yerine geçen yapılarla anlatmayı öğretir.",
    minutes: 12,
    focusId: "Passiversatz",
    vocab: [
      { de: "die Fachkraft", tr: "nitelikli eleman" },
      { de: "der Fachkräftemangel", tr: "nitelikli eleman eksikliği" },
      { de: "der Mindestlohn", tr: "asgari ücret" },
      { de: "die Erwerbstätigkeit", tr: "gelir getiren çalışma" },
      { de: "sich qualifizieren", tr: "hak kazanmak" },
      { de: "befristet", tr: "süreli" },
      { de: "unbefristet", tr: "süresiz" },
      { de: "wettbewerbsfähig", tr: "rekabetçi" },
    ],
    patterns: [
      { de: "… sind kaum zu besetzen", tr: "doldurulamıyor" },
      { de: "Es mangelt an …", tr: "… eksikliği var" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün iş gücü piyasasını konuşacağız. Bu konunun cümleleri hep faili gizler: 'kadro doldurulamıyor' — kim dolduramıyor, söylenmez. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de eksiklik bildiren kişisiz bir kalıp öğreneceğiz. Sabit bir edat alıyor ve o edat yönelme hâli istiyor. Önce kelimeler.")] },
      word("İlk", { de: "die Fachkraft", tr: "nitelikli eleman" }),
      word("İkinci", { de: "der Fachkräftemangel", tr: "nitelikli eleman eksikliği" }),
      word("Üçüncü", { de: "der Mindestlohn", tr: "asgari ücret" }),
      word("Dördüncü", { de: "die Erwerbstätigkeit", tr: "gelir getiren çalışma" }),
      word("Beşinci", { de: "sich qualifizieren", tr: "hak kazanmak" }),
      word("Altıncı", { de: "befristet", tr: "süreli" }),
      word("Yedinci", { de: "unbefristet", tr: "süresiz" }, "İş ilanlarının en çok aranan kelimesi."),
      word("Son", { de: "wettbewerbsfähig", tr: "rekabetçi" }),
      { say: [tr("Kalıbımız:"), de("Es mangelt an …"), tr("Sahte özne es ve sabit edat; arkasından yönelme hâli.")] },
      { say: [tr("Örnek:"), de("Viele Stellen sind kaum zu besetzen."), tr("Tekrar edin:"), de("Viele Stellen sind kaum zu besetzen")], expect: repeat("Viele Stellen sind kaum zu besetzen") },
      { say: [tr("Sıra sende: 'Süresiz kadrolar nadiren sunuluyor.'")], expect: produce("Unbefristete Stellen werden selten angeboten", [tr("Şimdiki zaman edilgeni; çoğul özne werden alır:"), de("Unbefristete Stellen werden selten angeboten."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Rekabetçi maaş eksikliği var.'")], expect: produce("Es mangelt an wettbewerbsfähigem Gehalt", [tr("Edattan sonra yönelme hâli; belirteçsiz sıfat -em ekini alır:"), de("Es mangelt an wettbewerbsfähigem Gehalt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu boşluk kolay doldurulamıyor.'")], expect: produce("Diese Lücke lässt sich nicht leicht schließen", [tr("lassen artı sich; olumsuzluk mastardan önce:"), de("Diese Lücke lässt sich nicht leicht schließen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Viele Stellen sind kaum zu besetzen."), tr("cümlesi doğru mu?")], expect: truefalse("Viele Stellen sind kaum zu besetzen.", true, [tr("Doğru. sein artı zu artı mastar yapısı edilgen anlamı taşıyor ve çoğul özne sind alıyor.")]) },
      { say: [tr("Son bir soru: 'Bunun sebebi ne?'")], expect: produce("Woran liegt das", [tr("Edat soru zamiriyle kaynaşır; kalıp bu hâliyle sabittir:"), de("Woran liegt das?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada eleman bulamayan bir işletmeyle konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Eleman bulamayan bir işletmenin sorumlusuyla konuşuyorsun: hangi kadrolar boş, neden doldurulamıyor, ne denendi ve ne yapılabilir.",
      partner: "yorgun, çözüm arayan bir işletme sorumlusu",
      opening: "Wir suchen seit einem Jahr — die Stelle ist einfach nicht zu besetzen. Haben Sie eine Idee, woran das liegt?",
      openingTr: "Bir yıldır arıyoruz — kadro bir türlü doldurulamıyor. Sebebinin ne olduğuna dair bir fikriniz var mı?",
      goal: "Hangi kadroların neden boş kaldığı konuşulmuş, denenenler öğrenilmiş ve en az bir öneri getirilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-ehrenamt-b2",
    icon: "feelings",
    level: "B2",
    course: "de",
    title: "Ohne Ehrenamt läuft nichts",
    titleTr: "Sivil toplum",
    summary: "Gönüllülüğün ne yaptığını yöntem bağlacıyla anlatmayı öğretir.",
    minutes: 12,
    focusId: "Nebensatz-indem",
    vocab: [
      { de: "das Ehrenamt", tr: "gönüllü görev" },
      { de: "ehrenamtlich", tr: "fahri" },
      { de: "sich engagieren", tr: "angaje olmak" },
      { de: "die Zivilgesellschaft", tr: "sivil toplum" },
      { de: "die Solidarität", tr: "dayanışma" },
      { de: "der Zusammenhalt", tr: "birlik duygusu" },
      { de: "die Bürgerinitiative", tr: "yurttaş girişimi" },
      { de: "das Gemeinwohl", tr: "kamu yararı" },
    ],
    patterns: [
      { de: "…, indem sie …", tr: "yaptıklarıyla" },
      { de: "Das Ehrenamt trägt das Gemeinwohl.", tr: "gönüllülüğün işlevini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün gönüllülüğü konuşacağız ve dilbilgisi olarak yine yöntem bağlacındayız: birileri bir şeyi NASIL taşıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu bağlacı bu modülde ikinci kez görüyorsun; fark şurada: burada yöntem bir tarif değil, bir katkı anlatıyor. Önce kelimeler.")] },
      word("İlk", { de: "das Ehrenamt", tr: "gönüllü görev" }),
      word("İkinci", { de: "ehrenamtlich", tr: "fahri" }, "Ücret almadan, gönüllü olarak yapılan."),
      word("Üçüncü", { de: "sich engagieren", tr: "angaje olmak" }),
      word("Dördüncü", { de: "die Zivilgesellschaft", tr: "sivil toplum" }),
      word("Beşinci", { de: "die Solidarität", tr: "dayanışma" }),
      word("Altıncı", { de: "der Zusammenhalt", tr: "birlik duygusu" }),
      word("Yedinci", { de: "die Bürgerinitiative", tr: "yurttaş girişimi" }),
      word("Son", { de: "das Gemeinwohl", tr: "kamu yararı" }),
      { say: [tr("Kalıbımız:"), de("…, indem sie …"), tr("Yan cümle; fiil sonda.")] },
      { say: [tr("Örnek:"), de("Sie tragen das Gemeinwohl, indem sie ehrenamtlich helfen."), tr("Tekrar edin:"), de("Sie tragen das Gemeinwohl, indem sie ehrenamtlich helfen")], expect: repeat("Sie tragen das Gemeinwohl, indem sie ehrenamtlich helfen") },
      { say: [tr("Sıra sende: 'Küçük başlayarak bir şeyler değiştirirsin.'")], expect: produce("Man verändert etwas, indem man klein anfängt", [tr("Yan cümlede ayrılabilen fiilin öneki de sonda kalır:"), de("Man verändert etwas, indem man klein anfängt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sivil toplum dayanışmaya muhtaç.'")], expect: produce("Die Zivilgesellschaft braucht Solidarität", [tr("Kısa bir hüküm cümlesi; nesne belirteçsiz:"), de("Die Zivilgesellschaft braucht Solidarität."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Dayanışma bundan besleniyor.'")], expect: produce("Der Zusammenhalt lebt davon", [tr("Edat zamirle kaynaşır:"), de("Der Zusammenhalt lebt davon."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Man verändert etwas, indem man fängt klein an."), tr("cümlesi doğru mu?")], expect: truefalse("Man verändert etwas, indem man fängt klein an.", false, [tr("Yan cümlede çekimli fiil sona gider ve ayrılabilen fiil orada birleşir:"), de("Man verändert etwas, indem man klein anfängt.")]) },
      { say: [tr("Son: 'Ben iki yıldır angaje oluyorum.'")], expect: produce("Ich engagiere mich seit zwei Jahren", [tr("Dönüşlü fiil; süre seit ile:"), de("Ich engagiere mich seit zwei Jahren."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir gönüllü kuruluşunun ne yaptığını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir gönüllü kuruluşunun temsilcisiyle konuşuyorsun: kuruluş tam olarak ne yapıyor, bunu nasıl başarıyor, sen nasıl katkı verebilirsin ve ne kadar zaman gerekiyor.",
      partner: "işini anlatmayı seven, yeni gönüllü arayan bir dernek temsilcisi",
      opening: "Schön, dass Sie fragen! Die meisten wissen gar nicht, wie viel hier unbezahlt läuft. Was interessiert Sie denn?",
      openingTr: "Sormanız güzel! Çoğu kişi burada ne kadar işin ücretsiz döndüğünü bilmiyor. Sizi ne ilgilendiriyor?",
      goal: "Kuruluşun ne yaptığı ve bunu nasıl başardığı öğrenilmiş, katkı biçimi ve zaman konusunda somut bir adım kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-generationen",
    icon: "family",
    level: "B2",
    course: "de",
    title: "Jung und Alt",
    titleTr: "Kuşak sohbeti",
    summary: "İki tarafı birlikte anan çift bağlaçlarla kuşakları tartışmayı öğretir.",
    minutes: 12,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "der Umgang", tr: "ilişki biçimi" },
      { de: "das Vorurteil", tr: "önyargı" },
      { de: "prägen", tr: "biçimlendirmek" },
      { de: "die Bevölkerungsgruppe", tr: "nüfus grubu" },
      { de: "der Wandel", tr: "değişim" },
      { de: "die Lebenserwartung", tr: "ortalama ömür" },
      { de: "die Ungleichheit", tr: "eşitsizlik" },
      { de: "die Gerechtigkeit", tr: "adalet" },
    ],
    patterns: [
      { de: "sowohl … als auch …", tr: "her ikisi de" },
      { de: "weder … noch …", tr: "ne … ne …" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kuşakları konuşacağız ve bunun için iki tarafı birlikte anan bağlaçlar lazım — çünkü kuşak tartışması tek tarafı suçlayınca biter. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki kalıp: biri ikisini de kapsar, öteki ikisini de dışarıda bırakır. Fiilin tekil mi çoğul mu olacağı dikkat ister. Önce kelimeler.")] },
      word("İlk", { de: "der Umgang", tr: "ilişki biçimi" }),
      word("İkinci", { de: "das Vorurteil", tr: "önyargı" }),
      word("Üçüncü", { de: "prägen", tr: "biçimlendirmek" }, "Bir dönem insanı nasıl şekillendirir."),
      word("Dördüncü", { de: "die Bevölkerungsgruppe", tr: "nüfus grubu" }),
      word("Beşinci", { de: "der Wandel", tr: "değişim" }),
      word("Altıncı", { de: "die Lebenserwartung", tr: "ortalama ömür" }),
      word("Yedinci", { de: "die Ungleichheit", tr: "eşitsizlik" }),
      word("Son", { de: "die Gerechtigkeit", tr: "adalet" }),
      { say: [tr("Kalıbımız:"), de("sowohl … als auch …"), tr("İki özneyi birlikte andığı için fiil çoğul olur.")] },
      { say: [tr("Örnek:"), de("Sowohl die Jungen als auch die Alten können voneinander lernen."), tr("Tekrar edin:"), de("Sowohl die Jungen als auch die Alten können voneinander lernen")], expect: repeat("Sowohl die Jungen als auch die Alten können voneinander lernen") },
      { say: [tr("Sıra sende: 'Ne gençler ne yaşlılar suçlu.'")], expect: produce("Weder die Jungen noch die Alten sind schuld", [tr("İki parça da özneyi kapsar; fiil çoğul:"), de("Weder die Jungen noch die Alten sind schuld."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Önyargılar iki tarafta da var.'")], expect: produce("Vorurteile gibt es auf beiden Seiten", [tr("Nesne öne alınmış; kalıplaşmış fiil ikinci sırada:"), de("Vorurteile gibt es auf beiden Seiten."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu değişim iki nüfus grubunu da biçimlendiriyor.'")], expect: produce("Dieser Wandel prägt beide Bevölkerungsgruppen", [tr("Nesne belirtme hâlinde; çoğulda isim ekini alır:"), de("Dieser Wandel prägt beide Bevölkerungsgruppen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Sowohl die Jungen als auch die Alten kann voneinander lernen."), tr("cümlesi doğru mu?")], expect: truefalse("Sowohl die Jungen als auch die Alten kann voneinander lernen.", false, [tr("Bağlaç iki özneyi birlikte andığı için fiil çoğul olur:"), de("Sowohl die Jungen als auch die Alten können voneinander lernen.")]) },
      { say: [tr("Son: 'Birbirimizden çok şey öğrenebiliriz.'")], expect: produce("Wir können viel voneinander lernen", [tr("Modal fiil ikinci sırada, mastar sonda:"), de("Wir können viel voneinander lernen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada kuşaklar arası bir meseleyi tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Farklı kuşaktan bir tanıdığınla kuşaklar arası bir meseleyi tartışıyorsunuz (iş ahlakı, teknoloji, konut). İki tarafın da haklı yanını söyle, önyargıları adlandır ve ortak bir zemin bul.",
      partner: "kendi kuşağını savunan ama dinlemeye açık bir tanıdık",
      opening: "Eure Generation will alles sofort, das ist doch das Problem. Oder sehen Sie das anders?",
      openingTr: "Sizin kuşağınız her şeyi hemen istiyor, sorun bu işte. Yoksa siz başka mı görüyorsunuz?",
      goal: "İki kuşağın da haklı yanı söylenmiş, önyargılar adlandırılmış ve ortak bir zemin bulunmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-landflucht",
    icon: "city",
    level: "B2",
    course: "de",
    title: "Stadt oder Land?",
    titleTr: "Kır-kent tartışması",
    summary: "Göç eğilimini orantı bağlacıyla açıklamayı öğretir.",
    minutes: 12,
    focusId: "Je-desto",
    vocab: [
      { de: "die Infrastruktur", tr: "altyapı" },
      { de: "der Ballungsraum", tr: "yığılma bölgesi" },
      { de: "der Zuzug", tr: "gelip yerleşme" },
      { de: "der Pendler", tr: "banliyö yolcusu" },
      { de: "der Nahverkehr", tr: "toplu taşıma" },
      { de: "die Stadtentwicklung", tr: "kentsel gelişim" },
      { de: "das Stadtviertel", tr: "semt" },
      { de: "die Innenstadt", tr: "şehir merkezi" },
    ],
    patterns: [
      { de: "Je größer …, desto …", tr: "orantı kurar" },
      { de: "Der Trend geht zu …", tr: "eğilimi bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün insanların neden şehre taşındığını konuşacağız. Orantı bağlacını bu modülde ikinci kez kullanacaksın — bu sefer bir toplumsal eğilim için. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Hatırlatma: ilk parçada fiil sonda, ikinci parçada karşılaştırma biçiminden hemen sonra. Önce kelimeler.")] },
      word("İlk", { de: "die Infrastruktur", tr: "altyapı" }),
      word("İkinci", { de: "der Ballungsraum", tr: "yığılma bölgesi" }, "Nüfusun yığıldığı büyük şehir bölgesi."),
      word("Üçüncü", { de: "der Zuzug", tr: "gelip yerleşme" }),
      word("Dördüncü", { de: "der Pendler", tr: "banliyö yolcusu" }),
      word("Beşinci", { de: "der Nahverkehr", tr: "toplu taşıma" }),
      word("Altıncı", { de: "die Stadtentwicklung", tr: "kentsel gelişim" }),
      word("Yedinci", { de: "das Stadtviertel", tr: "semt" }),
      word("Son", { de: "die Innenstadt", tr: "şehir merkezi" }),
      { say: [tr("Kalıbımız:"), de("Je größer …, desto …"), tr("İki büyüklük arasında doğru orantı.")] },
      { say: [tr("Örnek:"), de("Je größer die Stadt ist, desto anonymer ist das Leben."), tr("Tekrar edin:"), de("Je größer die Stadt ist, desto anonymer ist das Leben")], expect: repeat("Je größer die Stadt ist, desto anonymer ist das Leben") },
      { say: [tr("Sıra sende: 'Gençler şehir merkezine taşınıyor.'")], expect: produce("Junge Menschen ziehen in die Innenstadt", [tr("Hareket bildiren edat belirtme hâli ister:"), de("Junge Menschen ziehen in die Innenstadt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Altyapı ne kadar iyiyse o kadar az insan gidiyor.'")], expect: produce("Je besser die Infrastruktur ist, desto weniger Menschen gehen weg", [tr("İkinci parçada karşılaştırma biçimi bağlacın hemen arkasında:"), de("Je besser die Infrastruktur ist, desto weniger Menschen gehen weg."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Koca semtler değişiyor.'")], expect: produce("Ganze Stadtviertel verändern sich", [tr("Belirteçsiz çoğulda sıfat -e ekini alır; fiil dönüşlü:"), de("Ganze Stadtviertel verändern sich."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Je besser die Infrastruktur ist, desto weniger Menschen gehen weg."), tr("cümlesi doğru mu?")], expect: truefalse("Je besser die Infrastruktur ist, desto weniger Menschen gehen weg.", true, [tr("Doğru. İlk parçada fiil sonda, ikinci parçada karşılaştırma biçimi bağlacın hemen arkasında duruyor.")]) },
      { say: [tr("Son: 'Eğilim büyük şehirlere doğru.'")], expect: produce("Der Trend geht zu den Ballungsräumen", [tr("Edat yönelme hâli ister; çoğulda isim -n eki alır:"), de("Der Trend geht zu den Ballungsräumen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada şehirde mi kırsalda mı yaşamanın daha iyi olduğunu tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla şehirde mi kırsalda mı yaşamanın daha iyi olduğunu tartışıyorsunuz. İki tarafın artılarını orantı cümleleriyle bağla, kendi tercihini gerekçelendir ve karşı tarafın bir noktasına hak ver.",
      partner: "kırsala taşınmayı ciddi ciddi düşünen bir tanıdık",
      opening: "Ich überlege ernsthaft, aufs Land zu ziehen. Aber alle sagen, ich würde es bereuen. Was meinen Sie?",
      openingTr: "Ciddi ciddi kırsala taşınmayı düşünüyorum. Ama herkes pişman olacağımı söylüyor. Siz ne dersiniz?",
      goal: "İki tarafın artıları orantı cümleleriyle bağlanmış, kendi tercih gerekçelendirilmiş ve karşı tarafın bir noktasına hak verilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-steuern-b2",
    icon: "money",
    level: "B2",
    course: "de",
    title: "Wofür zahlen wir?",
    titleTr: "Vergi tartışması",
    summary: "Kamu harcamalarını edilgenle anlatıp tartışmayı öğretir.",
    minutes: 12,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Steuerlast", tr: "vergi yükü" },
      { de: "die Steuererklärung", tr: "vergi beyannamesi" },
      { de: "die Steuererhöhung", tr: "vergi artışı" },
      { de: "die Sozialabgabe", tr: "sosyal güvenlik kesintisi" },
      { de: "die Sozialleistung", tr: "sosyal yardım" },
      { de: "die Investition", tr: "yatırım" },
      { de: "erheben", tr: "tahsil etmek" },
      { de: "kürzen", tr: "kısmak" },
    ],
    patterns: [
      { de: "… wird aus … finanziert", tr: "kaynağı bildirir" },
      { de: "… wird erhoben", tr: "verginin tahsil edildiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün paranın nereye gittiğini konuşacağız. Kamu maliyesi dili edilgendir: bir şey finanse edilir, kim finanse ettiği söylenmez. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de yararlanma fiili var; sabit bir edat alıyor ve o edat zamirle kaynaşıyor. Önce kelimeler.")] },
      word("İlk", { de: "die Steuerlast", tr: "vergi yükü" }),
      word("İkinci", { de: "die Steuererklärung", tr: "vergi beyannamesi" }),
      word("Üçüncü", { de: "die Steuererhöhung", tr: "vergi artışı" }),
      word("Dördüncü", { de: "die Sozialabgabe", tr: "sosyal güvenlik kesintisi" }, "Maaştan doğrudan kesilen sigorta payı."),
      word("Beşinci", { de: "die Sozialleistung", tr: "sosyal yardım" }),
      word("Altıncı", { de: "die Investition", tr: "yatırım" }),
      word("Yedinci", { de: "erheben", tr: "tahsil etmek" }, "Devletin vergiyi almasının resmî fiili."),
      word("Son", { de: "kürzen", tr: "kısmak" }),
      { say: [tr("Kalıbımız:"), de("… wird aus … finanziert"), tr("Kaynak bildiren edat yönelme hâli ister ve çoğulda isim ek alır.")] },
      { say: [tr("Örnek:"), de("Schulen werden aus öffentlichen Mitteln finanziert."), tr("Tekrar edin:"), de("Schulen werden aus öffentlichen Mitteln finanziert")], expect: repeat("Schulen werden aus öffentlichen Mitteln finanziert") },
      { say: [tr("Sıra sende: 'Bu vergi her yıl tahsil ediliyor.'")], expect: produce("Diese Steuer wird jährlich erhoben", [tr("Şimdiki zaman edilgeni; ortaç sonda:"), de("Diese Steuer wird jährlich erhoben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sosyal yardımlar her yıl güncelleniyor.'")], expect: produce("Die Sozialleistungen werden jedes Jahr angepasst", [tr("Çoğul edilgen; ortaç sonda:"), de("Die Sozialleistungen werden jedes Jahr angepasst."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Vergi artışı parlamentoda karara bağlanıyor.'")], expect: produce("Die Steuererhöhung wird im Parlament beschlossen", [tr("Tekil edilgen; yer bildiren edat yönelme hâlinde:"), de("Die Steuererhöhung wird im Parlament beschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Was wird mit diesem Geld finanziert werden?"), tr("cümlesi doğru mu?")], expect: truefalse("Was wird mit diesem Geld finanziert werden?", false, [tr("Şimdiki zaman edilgeninde sondaki ikinci werden fazladır:"), de("Was wird mit diesem Geld finanziert?")]) },
      { say: [tr("Son: 'Bu paranın nereye gittiğini bilmek istiyorum.'")], expect: produce("Ich möchte wissen, wohin dieses Geld fließt", [tr("Dolaylı soruda fiil sonda:"), de("Ich möchte wissen, wohin dieses Geld fließt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada verginin nereye harcanması gerektiğini tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla kamu parasının nereye harcanması gerektiğini tartışıyorsunuz: neye daha çok bütçe ayrılmalı, neyden kısılabilir, kim yararlanıyor. Görüşünü gerekçelendir.",
      partner: "her kalemi sorgulayan, örnek isteyen bir tanıdık",
      opening: "Ich zahle jeden Monat ordentlich Steuern und sehe davon wenig. Wofür wird das Geld eigentlich ausgegeben?",
      openingTr: "Her ay epey vergi ödüyorum ve karşılığını pek görmüyorum. Bu para aslında neye harcanıyor?",
      goal: "Paranın nereye gittiği örneklerle konuşulmuş, hangi kaleme daha çok ayrılması gerektiği gerekçelendirilmiş ve bir noktada uzlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-wahl",
    icon: "flag",
    level: "B2",
    course: "de",
    title: "Vor der Wahl",
    titleTr: "Seçim sohbeti",
    summary: "Seçim tahminlerini ve vaatleri kaynağıyla birlikte konuşmayı öğretir.",
    minutes: 12,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "das Wahlversprechen", tr: "seçim vaadi" },
      { de: "der Wahlkampf", tr: "seçim kampanyası" },
      { de: "die Hochrechnung", tr: "seçim tahmini" },
      { de: "die Beteiligung", tr: "katılım" },
      { de: "die Koalition", tr: "koalisyon" },
      { de: "die Opposition", tr: "muhalefet" },
      { de: "kandidieren", tr: "aday olmak" },
      { de: "umsetzen", tr: "hayata geçirmek" },
    ],
    patterns: [
      { de: "Die Partei will … erreicht haben.", tr: "kendi iddiası" },
      { de: "… dürfte knapp werden", tr: "temkinli tahmin" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi: seçim. Bu konuda konuşurken en önemli şey neyin vaat, neyin anket, neyin senin tahminin olduğunu ayırmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Öznel kip fiilleri tam olarak bunu yapıyor. Bir partinin kendi iddiası ile senin tahminin aynı cümle kalıbıyla söylenmez. Önce kelimeler.")] },
      word("İlk", { de: "das Wahlversprechen", tr: "seçim vaadi" }),
      word("İkinci", { de: "der Wahlkampf", tr: "seçim kampanyası" }),
      word("Üçüncü", { de: "die Hochrechnung", tr: "seçim tahmini" }, "Sandıkların bir kısmı sayılınca yapılan sonuç tahmini."),
      word("Dördüncü", { de: "die Beteiligung", tr: "katılım" }),
      word("Beşinci", { de: "die Koalition", tr: "koalisyon" }),
      word("Altıncı", { de: "die Opposition", tr: "muhalefet" }),
      word("Yedinci", { de: "kandidieren", tr: "aday olmak" }),
      word("Son", { de: "umsetzen", tr: "hayata geçirmek" }),
      { say: [tr("Kalıbımız:"), de("Die Partei will … erreicht haben."), tr("Yani parti bunu başardığını İDDİA ediyor; sen doğrulamıyorsun.")] },
      { say: [tr("Örnek:"), de("Das Ergebnis dürfte knapp werden."), tr("Tekrar edin:"), de("Das Ergebnis dürfte knapp werden")], expect: repeat("Das Ergebnis dürfte knapp werden") },
      { say: [tr("Sıra sende: 'Parti hedefe ulaştığını iddia ediyor.'")], expect: produce("Die Partei will das Ziel erreicht haben", [tr("Kendi iddiası wollen ile; geçmiş mastar sonda:"), de("Die Partei will das Ziel erreicht haben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi duyulan bilgiyle: 'Katılım geçen seferden yüksekmiş.'")], expect: produce("Die Beteiligung soll höher sein als beim letzten Mal", [tr("Duyulan bilgi sollen ile; karşılaştırma als ile:"), de("Die Beteiligung soll höher sein als beim letzten Mal."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Seçim tahmini yakın bir sonuç gösteriyor.'")], expect: produce("Die Hochrechnung zeigt ein knappes Ergebnis", [tr("Belirtisiz nötr tekilde sıfat -es ekini alır:"), de("Die Hochrechnung zeigt ein knappes Ergebnis."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wahlversprechen werden selten umsetzen."), tr("cümlesi doğru mu?")], expect: truefalse("Wahlversprechen werden selten umsetzen.", false, [tr("Edilgende mastar değil ortaç gelir:"), de("Wahlversprechen werden selten umgesetzt.")]) },
      { say: [tr("Son: 'Oyumu kime vereceğime henüz karar vermedim.'")], expect: produce("Ich habe noch nicht entschieden, wem ich meine Stimme gebe", [tr("Yan cümlede fiil sonda; soru zamiri yönelme hâlinde:"), de("Ich habe noch nicht entschieden, wem ich meine Stimme gebe."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada yaklaşan bir seçimi konuşacaksın: ne vaat ediliyor, anketler ne diyor, sen ne bekliyorsun.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla yaklaşan bir seçimi konuşuyorsunuz: hangi vaatler var, anketler ne gösteriyor, sen ne bekliyorsun ve neye göre karar veriyorsun. Vaat, anket ve kendi tahminini ayır.",
      partner: "kararsız, hangi vaade inanacağını bilemeyen bir tanıdık",
      opening: "Alle versprechen dasselbe und am Ende wird nichts umgesetzt. Wonach entscheiden Sie sich denn?",
      openingTr: "Herkes aynı şeyi vaat ediyor ve sonunda hiçbiri hayata geçmiyor. Siz neye göre karar veriyorsunuz?",
      goal: "Vaat, anket ve kendi tahmini ayrılmış ve neye göre karar verileceği konusunda somut bir ölçüt söylenmiş olur.",
      minTurns: 8,
    },
  },
];
