import { de, tr, type LectureStep, type Lesson, type Segment } from "../types";

/**
 * B1 · Modül 13 — Yolculuk ve ulaşım (121–130).
 *
 * Üçüncü genişleme modülü; alan yine havuzdan çıktı. Bu kümenin kendine
 * özgü yanı SESLE duyulması: gar anonsunda, uçakta, yol tabelasında bu
 * sözcükler okunmuyor, söyleniyor. O yüzden derslerin çoğu dinleyip
 * anlamaya, sonra soru sormaya dayanıyor.
 *
 * Yayı yolculuğun kendi sırası: trenden uçağa, arabadan trafik kurallarına,
 * konaklamadan şehre ve doğaya, taşınmaya, acil duruma ve sonunda dönüp
 * anlatmaya.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [
      tr(`${n} kelimemiz:`),
      de(w.de),
      tr(`Türkçesi '${w.tr}' demek${note ? ` — ${note}` : ""}. Lütfen`),
      de(w.de),
      tr("deyin."),
    ],
    expect: repeat(w.de),
  };
}

export const deB1B13: Lesson[] = [
  {
    id: "de-b1-bahn-fahren",
    icon: "train",
    level: "B1",
    course: "de",
    title: "Mit der Bahn",
    titleTr: "Trenle yolculuk",
    summary: "Garda bilmediğin ayrıntıları dolaylı soru kalıplarıyla sormayı öğretir.",
    minutes: 10,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "der Hauptbahnhof", tr: "ana gar" },
      { de: "der Perron", tr: "peron" },
      { de: "die Linie", tr: "hat" },
      { de: "das Billett", tr: "bilet" },
      { de: "die Eisenbahn", tr: "demiryolu" },
      { de: "die Rückfahrt", tr: "dönüş yolculuğu" },
      { de: "der Aufenthalt", tr: "kalış, mola" },
      { de: "das Tram", tr: "tramvay" },
    ],
    patterns: [
      { de: "Wissen Sie, von welchem Perron …?", tr: "peronu kibarca sorar" },
      { de: "Ich bin nicht sicher, ob …", tr: "emin olmadığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün gardayız. Gardaki en önemli beceri konuşmak değil, doğru soruyu sormak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dolaylı soruda soru sözcüğü bağlaç olur ve fiil en sona gider. Anons anlaşılmadığında bu kalıp seni kurtarır. Önce kelimeler.")] },
      word("İlk", { de: "der Hauptbahnhof", tr: "ana gar" }),
      word("İkinci", { de: "der Perron", tr: "peron" }, "İsviçre ve Avusturya'da yaygın"),
      word("Üçüncü", { de: "die Linie", tr: "hat" }),
      word("Dördüncü", { de: "das Billett", tr: "bilet" }),
      word("Beşinci", { de: "die Eisenbahn", tr: "demiryolu" }),
      word("Altıncı", { de: "die Rückfahrt", tr: "dönüş yolculuğu" }),
      word("Yedinci", { de: "der Aufenthalt", tr: "kalış, mola" }),
      word("Son", { de: "das Tram", tr: "tramvay" }),
      { say: [tr("İlk kalıbımız peronu soruyor. Soru sözcüğü öbeği bağlaç oluyor ve fiil yan cümlenin sonuna geçiyor.")] },
      { say: [tr("Örnek:"), de("Wissen Sie, von welchem Perron der Zug abfährt?"), tr("Tekrar edin:"), de("Wissen Sie, von welchem Perron der Zug abfährt")], expect: repeat("Wissen Sie, von welchem Perron der Zug abfährt") },
      { say: [tr("Sıra sende: 'Hangi hattın ana gara gittiğini biliyor musunuz?'")], expect: produce("Wissen Sie, welche Linie zum Hauptbahnhof fährt", [tr("Soru sözcüğü bağlaç, fiil sonda:"), de("Wissen Sie, welche Linie zum Hauptbahnhof fährt?"), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız emin olmadığını söylüyor. Soru sözcüğü yoksa kullanılan bağlaç budur.")] },
      { say: [tr("Şimdi: 'Biletin dönüş için de geçerli olup olmadığından emin değilim.'")], expect: produce("Ich bin nicht sicher, ob das Billett auch für die Rückfahrt gilt", [tr("Bağlaçtan sonra fiil en sonda:"), de("Ich bin nicht sicher, ob das Billett auch für die Rückfahrt gilt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wissen Sie, wie lang ist der Aufenthalt?"), tr("cümlesi doğru mu?")], expect: truefalse("Wissen Sie, wie lang ist der Aufenthalt?", false, [tr("Dolaylı soruda fiil öne gelmez, sona gider:"), de("Wissen Sie, wie lang der Aufenthalt ist?")]) },
      { say: [tr("Son: 'Tramvayın nereden kalktığını sorabilir miyim?'")], expect: produce("Darf ich fragen, wo das Tram abfährt", [tr("Kibar giriş, sonra bağlaç ve sonda fiil:"), de("Darf ich fragen, wo das Tram abfährt?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi gardasın ve treni bulmak için soru soracaksın.")] },
    ],
    roleplay: {
      scene: "Ana garda trenini arıyorsun. Anonsu tam anlamadın: peronu, kalkış saatini ve biletinin dönüş için geçerli olup olmadığını soruyorsun.",
      partner: "acelesi olan ama yardımsever bir gar görevlisi",
      opening: "Kann ich Ihnen helfen? Sie sehen aus, als würden Sie etwas suchen.",
      openingTr: "Yardımcı olabilir miyim? Bir şey arıyor gibisiniz.",
      goal: "Peron, kalkış saati ve biletin kapsamı öğrenilmiş ve yolcu doğru trene yönlendirilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-am-flughafen",
    icon: "plane",
    level: "B1",
    course: "de",
    title: "Am Flughafen",
    titleTr: "Havalimanında",
    summary: "Uçuşta olan biteni edilgen çatının geçmişiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "der Passagier", tr: "yolcu" },
      { de: "die Passagierin", tr: "kadın yolcu" },
      { de: "der Steward", tr: "kabin görevlisi" },
      { de: "die Stewardess", tr: "hostes" },
      { de: "die Kabine", tr: "kabin" },
      { de: "die Landung", tr: "iniş" },
      { de: "landen", tr: "iniş yapmak" },
      { de: "der Notausgang", tr: "acil çıkış" },
    ],
    patterns: [
      { de: "Der Flug wurde … verschoben.", tr: "geçmişte yapılan bir işlemi anlatır" },
      { de: "Die Passagiere wurden informiert.", tr: "kimin bilgilendirildiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Havalimanındayız ve bir şeyler ters gitti. Havalimanı anonsları neredeyse hep edilgendir: kimin yaptığı söylenmez. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgenin geçmişinde yardımcı fiil geçmiş biçimde ikinci sırada, ortaç en sonda. Önce kelimeler.")] },
      word("İlk", { de: "der Passagier", tr: "yolcu" }),
      word("İkinci", { de: "die Passagierin", tr: "kadın yolcu" }),
      word("Üçüncü", { de: "der Steward", tr: "kabin görevlisi" }),
      word("Dördüncü", { de: "die Stewardess", tr: "hostes" }),
      word("Beşinci", { de: "die Kabine", tr: "kabin" }),
      word("Altıncı", { de: "die Landung", tr: "iniş" }),
      word("Yedinci", { de: "landen", tr: "iniş yapmak" }),
      word("Son", { de: "der Notausgang", tr: "acil çıkış" }),
      { say: [tr("İlk kalıbımız gecikmeyi anlatıyor. Yardımcı fiil geçmiş biçiminde ve ikinci sırada, ortaç sonda.")] },
      { say: [tr("Örnek:"), de("Der Flug wurde um zwei Stunden verschoben."), tr("Tekrar edin:"), de("Der Flug wurde um zwei Stunden verschoben")], expect: repeat("Der Flug wurde um zwei Stunden verschoben") },
      { say: [tr("Sıra sende: 'İniş ertelendi.'")], expect: produce("Die Landung wurde verschoben", [tr("Tekil özne, yardımcı fiil tekil:"), de("Die Landung wurde verschoben."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız çoğul özneyle çalışıyor. Özne çoğul olunca yardımcı fiil de çoğula girer — Türkçede böyle bir uyum yok, o yüzden atlanıyor.")] },
      { say: [tr("Şimdi: 'Yolcular geç bilgilendirildi.'")], expect: produce("Die Passagiere wurden spät informiert", [tr("Çoğul özne, çoğul yardımcı fiil:"), de("Die Passagiere wurden spät informiert."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Kabine wurde nicht kontrollieren."), tr("cümlesi doğru mu?")], expect: truefalse("Die Kabine wurde nicht kontrollieren.", false, [tr("Edilgende asıl fiil ortaç hâlinde olmalı:"), de("Die Kabine wurde nicht kontrolliert.")]) },
      { say: [tr("Son: 'Acil çıkışlar gösterildi ve sonra uçak indi.'")], expect: produce("Die Notausgänge wurden gezeigt und dann ist das Flugzeug gelandet", [tr("Edilgen ve etken bir arada; ikinci cümle yer değiştirme fiili olduğu için başka bir yardımcı fiil alıyor:"), de("Die Notausgänge wurden gezeigt und dann ist das Flugzeug gelandet."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi havalimanı bankosunda ne olduğunu anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Uçuşun ertelendi ve bağlantını kaçırdın. Havalimanı bankosunda ne olduğunu sırayla anlatıp yeni bir çözüm istiyorsun.",
      partner: "sisteme bakan, çözüm arayan bir havayolu görevlisi",
      opening: "Guten Tag! Was ist denn passiert — welchen Flug hatten Sie gebucht?",
      openingTr: "İyi günler! Ne oldu — hangi uçuşu almıştınız?",
      goal: "Olan biten sırayla anlatılmış ve yeni bir uçuş ya da konaklama çözümü bulunmuş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-auto-unterwegs",
    icon: "car",
    level: "B1",
    course: "de",
    title: "Unterwegs mit dem Auto",
    titleTr: "Arabayla yolda",
    summary: "Koşul cümleleriyle yolda ne yapılacağını anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-wenn",
    vocab: [
      { de: "das Fahrzeug", tr: "araç" },
      { de: "das Kraftfahrzeug", tr: "motorlu taşıt" },
      { de: "das Motorrad", tr: "motosiklet" },
      { de: "die Bremse", tr: "fren" },
      { de: "die Kurve", tr: "viraj" },
      { de: "das Benzin", tr: "benzin" },
      { de: "das Kennzeichen", tr: "plaka" },
      { de: "der Gang", tr: "vites" },
    ],
    patterns: [
      { de: "Wenn …, dann …", tr: "koşula bağlı sonucu söyler" },
      { de: "Sobald …, …", tr: "bir şey olur olmaz ne yapılacağını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün arabayla yoldayız. Yol dili koşullarla kuruludur: yağmur yağarsa, benzin biterse. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Koşul bağlacından sonra fiil sona gider; yan cümle başta olduğunda ana cümle fiille başlar. Önce kelimeler.")] },
      word("İlk", { de: "das Fahrzeug", tr: "araç" }),
      word("İkinci", { de: "das Kraftfahrzeug", tr: "motorlu taşıt" }, "resmî yazışmada kullanılır"),
      word("Üçüncü", { de: "das Motorrad", tr: "motosiklet" }),
      word("Dördüncü", { de: "die Bremse", tr: "fren" }),
      word("Beşinci", { de: "die Kurve", tr: "viraj" }),
      word("Altıncı", { de: "das Benzin", tr: "benzin" }),
      word("Yedinci", { de: "das Kennzeichen", tr: "plaka" }),
      word("Son", { de: "der Gang", tr: "vites" }),
      { say: [tr("İlk kalıbımız koşul ve sonuç. Yan cümle başta olduğu için ana cümle fiille başlıyor; araya giren zarf bunu değiştirmiyor.")] },
      { say: [tr("Örnek:"), de("Wenn das Benzin knapp wird, halten wir an der Tankstelle."), tr("Tekrar edin:"), de("Wenn das Benzin knapp wird, halten wir an der Tankstelle")], expect: repeat("Wenn das Benzin knapp wird, halten wir an der Tankstelle") },
      { say: [tr("Sıra sende: 'Fren zayıfsa yavaş sür.'")], expect: produce("Wenn die Bremse schwach ist, fahr langsam", [tr("Yan cümlede fiil sonda, ana cümle emir kipiyle:"), de("Wenn die Bremse schwach ist, fahr langsam."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız zamanı sıkıştırıyor: bir şey olur olmaz. Koşuldan farkı, olacağından emin olman.")] },
      { say: [tr("Şimdi: 'Viraj biter bitmez vites büyütüyorum.'")], expect: produce("Sobald die Kurve zu Ende ist, schalte ich in den höheren Gang", [tr("Bağlaçtan sonra fiil sonda, ana cümle fiille başlıyor:"), de("Sobald die Kurve zu Ende ist, schalte ich in den höheren Gang."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn das Fahrzeug alt ist, es braucht mehr Benzin."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn das Fahrzeug alt ist, es braucht mehr Benzin.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar, özneyle değil:"), de("Wenn das Fahrzeug alt ist, braucht es mehr Benzin.")]) },
      { say: [tr("Son: 'Plakayı görürsen bana söyle.'")], expect: produce("Wenn du das Kennzeichen siehst, sag es mir", [tr("Yan cümlede fiil sonda, ana cümle emir kipiyle:"), de("Wenn du das Kennzeichen siehst, sag es mir."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi uzun bir yolculuk planlayacak ve olası durumları konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla arabayla uzun bir yolculuğa çıkıyorsunuz. Yolda ne olursa ne yapacağınızı konuşuyorsunuz: benzin, mola, hava.",
      partner: "her ihtimali önceden konuşmak isteyen bir yol arkadaşı",
      opening: "Sechs Stunden Fahrt — was machen wir, wenn wir müde werden?",
      openingTr: "Altı saatlik yol — yorulursak ne yapacağız?",
      goal: "En az üç olasılık için ne yapılacağı koşul cümleleriyle kararlaştırılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-verkehrsregeln",
    icon: "transport",
    level: "B1",
    course: "de",
    title: "Regeln auf der Straße",
    titleTr: "Trafik kuralları",
    summary: "Kuralları edilgen cümlelerle anlamayı ve açıklamayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Vorfahrt", tr: "geçiş önceliği" },
      { de: "die Fahrbahn", tr: "taşıt yolu" },
      { de: "der Gehsteig", tr: "kaldırım" },
      { de: "die Einbahnstraße", tr: "tek yönlü yol" },
      { de: "die Umleitung", tr: "alternatif yol" },
      { de: "überqueren", tr: "karşıya geçmek" },
      { de: "der Führerausweis", tr: "ehliyet" },
      { de: "losfahren", tr: "yola çıkmak" },
    ],
    patterns: [
      { de: "Hier wird … nicht erlaubt.", tr: "bir yasağı kişisiz biçimde söyler" },
      { de: "Die Vorfahrt wird beachtet.", tr: "kuralın uygulandığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Trafik kuralları hiçbir dilde 'sen şunu yap' demez; hep kişisiz konuşur. Almancada bunun yolu edilgen çatı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgende yardımcı fiil ikinci sırada, ortaç sonda. Yer tümleciyle başlayan cümlelerde özne fiilin arkasına geçer. Önce kelimeler.")] },
      word("İlk", { de: "die Vorfahrt", tr: "geçiş önceliği" }),
      word("İkinci", { de: "die Fahrbahn", tr: "taşıt yolu" }),
      word("Üçüncü", { de: "der Gehsteig", tr: "kaldırım" }),
      word("Dördüncü", { de: "die Einbahnstraße", tr: "tek yönlü yol" }),
      word("Beşinci", { de: "die Umleitung", tr: "alternatif yol" }),
      word("Altıncı", { de: "überqueren", tr: "karşıya geçmek" }),
      word("Yedinci", { de: "der Führerausweis", tr: "ehliyet" }, "İsviçre'de kullanılan biçim"),
      word("Son", { de: "losfahren", tr: "yola çıkmak" }),
      { say: [tr("İlk kalıbımız yasağı söylüyor. Yer tümleci başta olduğu için yardımcı fiil hemen arkasından geliyor.")] },
      { say: [tr("Örnek:"), de("Hier wird das Parken nicht erlaubt."), tr("Tekrar edin:"), de("Hier wird das Parken nicht erlaubt")], expect: repeat("Hier wird das Parken nicht erlaubt") },
      { say: [tr("Sıra sende: 'Kaldırımda bisiklet sürülmez.'")], expect: produce("Auf dem Gehsteig wird nicht Rad gefahren", [tr("Yer tümleci başta, yardımcı fiil ikinci sırada:"), de("Auf dem Gehsteig wird nicht Rad gefahren."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız kuralın uygulandığını söylüyor. Bu biçim bir gözlem gibi durur ama aslında bir buyruktur.")] },
      { say: [tr("Şimdi: 'Geçiş önceliğine burada uyulur.'")], expect: produce("Die Vorfahrt wird hier beachtet", [tr("Özne başta, yardımcı fiil ikinci sırada, ortaç sonda:"), de("Die Vorfahrt wird hier beachtet."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("In der Einbahnstraße werden nicht rückwärts gefahren."), tr("cümlesi doğru mu?")], expect: truefalse("In der Einbahnstraße werden nicht rückwärts gefahren.", false, [tr("Öznesiz edilgende yardımcı fiil tekil kalır:"), de("In der Einbahnstraße wird nicht rückwärts gefahren.")]) },
      { say: [tr("Son: 'Alternatif yol tabelalarla gösterilir.'")], expect: produce("Die Umleitung wird mit Schildern gezeigt", [tr("Araç edatı yönelme hâli istiyor:"), de("Die Umleitung wird mit Schildern gezeigt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi yeni gelen birine buradaki trafik kurallarını anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Ülkeye yeni gelmiş bir arkadaşına buradaki trafik kurallarını anlatıyorsun: öncelik, tek yön, kaldırım, park. Kuralları kişisiz biçimde söyle.",
      partner: "başka bir ülkede araba kullanmış, karşılaştırmayı seven bir arkadaş",
      opening: "Bei uns war das ganz anders — was ist hier eigentlich verboten?",
      openingTr: "Bizde bu tamamen farklıydı — burada aslında ne yasak?",
      goal: "En az üç kural kişisiz biçimde anlatılmış ve iki ülke arasındaki bir fark söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-unterkunft-suchen",
    icon: "suitcase",
    level: "B1",
    course: "de",
    title: "Wo übernachten wir?",
    titleTr: "Konaklama seçmek",
    summary: "İki konaklama seçeneğini karşılaştırmayı ve tercihini savunmayı öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "die Übernachtung", tr: "konaklama" },
      { de: "die Hütte", tr: "dağ evi" },
      { de: "die Saison", tr: "sezon" },
      { de: "der Tourismus", tr: "turizm" },
      { de: "die Touristin", tr: "kadın turist" },
      { de: "das Souvenir", tr: "hediyelik eşya" },
      { de: "die Rundfahrt", tr: "şehir turu" },
      { de: "die Rückkehr", tr: "dönüş" },
    ],
    patterns: [
      { de: "… ist ruhiger als …", tr: "iki seçeneği karşılaştırır" },
      { de: "je nach Saison", tr: "sezona göre değiştiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Nerede kalacağınıza karar vereceksiniz. Karar vermek karşılaştırmak demek: hangisi daha ucuz, hangisi daha sessiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karşılaştırma sıfata ek getirir; sezona bağlı değişimi ise bir edat öbeğiyle söylüyoruz. Önce kelimeler.")] },
      word("İlk", { de: "die Übernachtung", tr: "konaklama" }, "bir gecelik kalış"),
      word("İkinci", { de: "die Hütte", tr: "dağ evi" }),
      word("Üçüncü", { de: "die Saison", tr: "sezon" }),
      word("Dördüncü", { de: "der Tourismus", tr: "turizm" }),
      word("Beşinci", { de: "die Touristin", tr: "kadın turist" }),
      word("Altıncı", { de: "das Souvenir", tr: "hediyelik eşya" }),
      word("Yedinci", { de: "die Rundfahrt", tr: "şehir turu" }),
      word("Son", { de: "die Rückkehr", tr: "dönüş" }),
      { say: [tr("İlk kalıbımız iki yeri karşılaştırıyor: sıfat artı ek, sonra kıyas sözcüğü.")] },
      { say: [tr("Örnek:"), de("Die Hütte ist ruhiger als das Hotel."), tr("Tekrar edin:"), de("Die Hütte ist ruhiger als das Hotel")], expect: repeat("Die Hütte ist ruhiger als das Hotel") },
      { say: [tr("Sıra sende: 'Konaklama sezonda daha pahalı.'")], expect: produce("Die Übernachtung ist in der Saison teurer", [tr("Sıfat düzensiz karşılaştırma alıyor:"), de("Die Übernachtung ist in der Saison teurer."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız değişkenliği söylüyor: bir edat öbeği. Fiyat konuşmalarında çok geçer.")] },
      { say: [tr("Şimdi: 'Fiyat sezona göre değişiyor.'")], expect: produce("Der Preis ändert sich je nach Saison", [tr("Dönüşlü fiil, sonra edat öbeği:"), de("Der Preis ändert sich je nach Saison."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Rundfahrt ist mehr billig als das Museum."), tr("cümlesi doğru mu?")], expect: truefalse("Die Rundfahrt ist mehr billig als das Museum.", false, [tr("Karşılaştırma ayrı bir zarfla değil, sıfata gelen ekle yapılır:"), de("Die Rundfahrt ist billiger als das Museum.")]) },
      { say: [tr("Son: 'Dönüş için en ucuz gün pazartesi.'")], expect: produce("Für die Rückkehr ist der Montag am billigsten", [tr("En üstün derece edatlı biçimde:"), de("Für die Rückkehr ist der Montag am billigsten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir arkadaşınla nerede kalacağınıza karar vereceksiniz.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla tatil için iki konaklama seçeneğini karşılaştırıyorsunuz: fiyat, konum, sessizlik. Sonunda birini seçiyorsunuz.",
      partner: "bütçeye dikkat eden ama konfordan da vazgeçmeyen bir arkadaş",
      opening: "Also, Hütte oder Hotel? Ich kann mich echt nicht entscheiden.",
      openingTr: "Peki, dağ evi mi otel mi? Gerçekten karar veremiyorum.",
      goal: "İki seçenek en az üç ölçütle karşılaştırılmış ve gerekçeli bir karar verilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-hafenstadt",
    icon: "map",
    level: "B1",
    course: "de",
    title: "In der Hafenstadt",
    titleTr: "Liman şehrinde",
    summary: "Bir yeri edatlı ilgi cümleleriyle tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Präposition",
    vocab: [
      { de: "der Hafen", tr: "liman" },
      { de: "die Fähre", tr: "feribot" },
      { de: "die Küste", tr: "sahil" },
      { de: "der Sand", tr: "kum" },
      { de: "der Stein", tr: "taş" },
      { de: "der Turm", tr: "kule" },
      { de: "die Burg", tr: "kale" },
      { de: "das Denkmal", tr: "anıt" },
    ],
    patterns: [
      { de: "der Turm, von dem man …", tr: "bakış noktasını tanımlar" },
      { de: "die Fähre, mit der wir …", tr: "aracı tanımlar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bir liman şehrindeyiz ve gezdiğimiz yerleri tarif edeceğiz. Bunun için edatlı ilgi cümlesi gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edat ilgi zamirinin önüne gelir ve hâlini belirler. Türkçede bu bilgi ekle taşındığı için sıra ters geliyor. Önce kelimeler.")] },
      word("İlk", { de: "der Hafen", tr: "liman" }),
      word("İkinci", { de: "die Fähre", tr: "feribot" }),
      word("Üçüncü", { de: "die Küste", tr: "sahil" }),
      word("Dördüncü", { de: "der Sand", tr: "kum" }),
      word("Beşinci", { de: "der Stein", tr: "taş" }),
      word("Altıncı", { de: "der Turm", tr: "kule" }),
      word("Yedinci", { de: "die Burg", tr: "kale" }),
      word("Son", { de: "das Denkmal", tr: "anıt" }),
      { say: [tr("İlk kalıbımız bakış noktasını tanımlıyor. Kaynağı gösteren edat yönelme hâli istiyor.")] },
      { say: [tr("Örnek:"), de("Das ist der Turm, von dem man den ganzen Hafen sieht."), tr("Tekrar edin:"), de("Das ist der Turm, von dem man den ganzen Hafen sieht")], expect: repeat("Das ist der Turm, von dem man den ganzen Hafen sieht") },
      { say: [tr("Sıra sende: 'Bu, üstünde yürüdüğümüz sahil.'")], expect: produce("Das ist die Küste, an der wir gelaufen sind", [tr("Dişil adda edat yönelme hâli istiyor:"), de("Das ist die Küste, an der wir gelaufen sind."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız aracı tanımlıyor: birlikte anlamındaki edat, yine yönelme hâliyle.")] },
      { say: [tr("Şimdi: 'Bu, adaya gittiğimiz feribot.'")], expect: produce("Das ist die Fähre, mit der wir zur Insel gefahren sind", [tr("Edat zamirin önünde, fiil yan cümlenin sonunda:"), de("Das ist die Fähre, mit der wir zur Insel gefahren sind."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist die Burg, die wir gestern gewesen sind."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist die Burg, die wir gestern gewesen sind.", false, [tr("Bir yerde bulunmak yer edatı ister ve o edat zamirin önüne gelir:"), de("Das ist die Burg, in der wir gestern gewesen sind.")]) },
      { say: [tr("Son: 'Bu, üstünde adların yazdığı anıt.'")], expect: produce("Das ist das Denkmal, auf dem die Namen stehen", [tr("Nötr adda edat yine yönelme hâli istiyor:"), de("Das ist das Denkmal, auf dem die Namen stehen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir arkadaşına gezdiğin şehri anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir liman şehrini gezdin. Arkadaşına gördüğün yerleri anlatıyorsun: hangi kuleden ne göründüğünü, hangi feribotla nereye gittiğini.",
      partner: "aynı şehre gitmeyi planlayan, ayrıntı soran bir arkadaş",
      opening: "Erzähl mal — was hat dir in der Hafenstadt am besten gefallen?",
      openingTr: "Anlat bakalım — liman şehrinde en çok ne hoşuna gitti?",
      goal: "En az üç yer edatlı ilgi cümleleriyle tanımlanmış ve bir tavsiye verilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-berg-und-tal",
    icon: "mountain",
    level: "B1",
    course: "de",
    title: "Über Berg und Tal",
    titleTr: "Doğada yürüyüş",
    summary: "Geçmişte tek seferlik bir olayı als bağlacıyla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-als",
    vocab: [
      { de: "das Gebirge", tr: "dağlık bölge" },
      { de: "der Hügel", tr: "tepe" },
      { de: "das Tal", tr: "vadi" },
      { de: "die Wiese", tr: "çayır" },
      { de: "das Gras", tr: "çimen" },
      { de: "der Nebel", tr: "sis" },
      { de: "der Sturm", tr: "fırtına" },
      { de: "die Region", tr: "bölge" },
    ],
    patterns: [
      { de: "Als wir oben waren, …", tr: "geçmişte tek seferlik olayı anlatır" },
      { de: "Immer wenn …, …", tr: "tekrarlanan olayı anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün dağda bir yürüyüşü anlatacağız. Almancada geçmişte BİR KEZ olan olayın bağlacı, tekrarlananınkinden farklıdır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tek seferlik geçmiş için bir bağlaç, tekrarlanan için başka bir bağlaç kullanılır. Türkçede ikisi de aynı ekle çıktığı için bu ayrım gözden kaçar. Önce kelimeler.")] },
      word("İlk", { de: "das Gebirge", tr: "dağlık bölge" }),
      word("İkinci", { de: "der Hügel", tr: "tepe" }),
      word("Üçüncü", { de: "das Tal", tr: "vadi" }),
      word("Dördüncü", { de: "die Wiese", tr: "çayır" }),
      word("Beşinci", { de: "das Gras", tr: "çimen" }),
      word("Altıncı", { de: "der Nebel", tr: "sis" }),
      word("Yedinci", { de: "der Sturm", tr: "fırtına" }),
      word("Son", { de: "die Region", tr: "bölge" }),
      { say: [tr("İlk bağlacımız geçmişte bir kez olanı anlatıyor. Yan cümlede fiil sona gider ve yan cümle başta olursa ana cümle fiille başlar.")] },
      { say: [tr("Örnek:"), de("Als wir oben waren, kam plötzlich der Nebel."), tr("Tekrar edin:"), de("Als wir oben waren, kam plötzlich der Nebel")], expect: repeat("Als wir oben waren, kam plötzlich der Nebel") },
      { say: [tr("Sıra sende: 'Vadiye indiğimizde fırtına dinmişti.'")], expect: produce("Als wir ins Tal kamen, war der Sturm vorbei", [tr("Yan cümlede fiil sonda, ana cümle fiille başlıyor:"), de("Als wir ins Tal kamen, war der Sturm vorbei."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci bağlacımız tekrarlananı anlatıyor. Başına bir zarf gelince tekrar olduğu kesinleşiyor.")] },
      { say: [tr("Şimdi: 'Ne zaman bu bölgeye gelsek yağmur yağıyor.'")], expect: produce("Immer wenn wir in diese Region kommen, regnet es", [tr("Yan cümlede fiil sonda, ana cümle fiille başlıyor:"), de("Immer wenn wir in diese Region kommen, regnet es."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn ich zum ersten Mal im Gebirge war, hatte ich Angst."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn ich zum ersten Mal im Gebirge war, hatte ich Angst.", false, [tr("Geçmişte bir kez olan olay için başka bir bağlaç gerekir:"), de("Als ich zum ersten Mal im Gebirge war, hatte ich Angst.")]) },
      { say: [tr("Son: 'Çayırda oturduğumuzda çimenler ıslaktı.'")], expect: produce("Als wir auf der Wiese saßen, war das Gras nass", [tr("Yan cümlede geçmiş zaman, ana cümle fiille başlıyor:"), de("Als wir auf der Wiese saßen, war das Gras nass."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir doğa yürüyüşünü anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Geçen hafta sonu dağda yürüyüşe çıktın ve hava bozdu. Bir arkadaşına ne olduğunu sırayla anlatıyorsun.",
      partner: "doğa yürüyüşünü seven, ayrıntı soran bir arkadaş",
      opening: "Ich habe gehört, ihr wart im Gebirge. Wie war es denn — habt ihr Glück mit dem Wetter gehabt?",
      openingTr: "Duydum ki dağdaymışsınız. Nasıldı — havada şansınız yaver gitti mi?",
      goal: "Yürüyüşün başı, hava değişimi ve dönüş sırayla anlatılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-wohnort-wechseln",
    icon: "home",
    level: "B1",
    course: "de",
    title: "Umgezogen",
    titleTr: "Şehir değiştirmek",
    summary: "Kendi geçmişini yazı diline yakın geçmiş zamanla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Präteritum",
    vocab: [
      { de: "der Wohnort", tr: "ikamet yeri" },
      { de: "der Wohnsitz", tr: "ikametgâh" },
      { de: "der Vorort", tr: "banliyö" },
      { de: "das Quartier", tr: "semt" },
      { de: "die Metropole", tr: "metropol" },
      { de: "die Zone", tr: "bölge" },
      { de: "der Kreis", tr: "ilçe" },
      { de: "das Eck", tr: "köşe" },
    ],
    patterns: [
      { de: "Ich zog … um.", tr: "yazı dilinin geçmişiyle taşınmayı anlatır" },
      { de: "Damals wohnte ich …", tr: "eskiden nerede oturduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün nerelerde yaşadığını anlatacaksın. Resmî formlarda ve özgeçmişte konuşma dilinin geçmişi kullanılmaz; yazı dilinin geçmişi kullanılır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu geçmiş tek parçadır: yardımcı fiil yok, fiil kendi eki ile geçmişe girer. Anlatı ve resmî metin bunu tercih eder. Önce kelimeler.")] },
      word("İlk", { de: "der Wohnort", tr: "ikamet yeri" }),
      word("İkinci", { de: "der Wohnsitz", tr: "ikametgâh" }, "resmî kayıttaki adres"),
      word("Üçüncü", { de: "der Vorort", tr: "banliyö" }),
      word("Dördüncü", { de: "das Quartier", tr: "semt" }),
      word("Beşinci", { de: "die Metropole", tr: "metropol" }),
      word("Altıncı", { de: "die Zone", tr: "bölge" }),
      word("Yedinci", { de: "der Kreis", tr: "ilçe" }),
      word("Son", { de: "das Eck", tr: "köşe" }),
      { say: [tr("İlk kalıbımız taşınmayı anlatıyor. Ayrılabilen bir fiil olduğu için öneki cümlenin sonunda kalıyor.")] },
      { say: [tr("Örnek:"), de("Vor drei Jahren zog ich in einen Vorort um."), tr("Tekrar edin:"), de("Vor drei Jahren zog ich in einen Vorort um")], expect: repeat("Vor drei Jahren zog ich in einen Vorort um") },
      { say: [tr("Sıra sende: 'Sonra metropole taşındım.'")], expect: produce("Danach zog ich in die Metropole um", [tr("Zarf başta olduğu için fiil ikinci sırada, önek sonda:"), de("Danach zog ich in die Metropole um."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız eskiyi anlatıyor: bir zaman zarfı ve düzenli bir fiilin yazı dili geçmişi.")] },
      { say: [tr("Şimdi: 'O zamanlar sakin bir semtte oturuyordum.'")], expect: produce("Damals wohnte ich in einem ruhigen Quartier", [tr("Fiil kendi ekiyle geçmişe giriyor, yardımcı fiil yok:"), de("Damals wohnte ich in einem ruhigen Quartier."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Damals ich wohnte im Kreis Nord."), tr("cümlesi doğru mu?")], expect: truefalse("Damals ich wohnte im Kreis Nord.", false, [tr("Cümle bir zarfla başlayınca çekimli fiil ikinci sıraya gelir:"), de("Damals wohnte ich im Kreis Nord.")]) },
      { say: [tr("Son: 'İkametgâhımı değiştirdim ve idareye bildirdim.'")], expect: produce("Ich änderte meinen Wohnsitz und meldete es der Verwaltung", [tr("İki fiil de yazı dili geçmişinde:"), de("Ich änderte meinen Wohnsitz und meldete es der Verwaltung."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi nerelerde yaşadığını sırayla anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Yeni bir tanıdıkla nerelerde yaşadığını konuşuyorsun: hangi şehirler, hangi semtler, neden taşındın. Anlatırken yazı dilinin geçmişini kullan.",
      partner: "kendi taşınma hikâyesini de anlatmak isteyen bir tanıdık",
      opening: "Du bist ja schon oft umgezogen — wo hast du denn vorher gewohnt?",
      openingTr: "Sık taşınmışsın — daha önce nerede oturuyordun?",
      goal: "En az iki eski ikamet yeri ve taşınma sebepleri sırayla anlatılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-notfall-unterwegs",
    icon: "car",
    level: "B1",
    course: "de",
    title: "Notfall unterwegs",
    titleTr: "Yolda acil durum",
    summary: "Ne yapılması gerektiğini dilek kipiyle kibarca önermeyi öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "der Notfall", tr: "acil durum" },
      { de: "der Alarm", tr: "alarm" },
      { de: "die Feuerwehr", tr: "itfaiye" },
      { de: "der Transport", tr: "nakliye" },
      { de: "die Mobilität", tr: "hareketlilik" },
      { de: "der Sitz", tr: "koltuk" },
      { de: "das Lager", tr: "depo" },
      { de: "der Blitz", tr: "şimşek" },
    ],
    patterns: [
      { de: "An deiner Stelle würde ich …", tr: "yerinde olsam diye tavsiye verir" },
      { de: "Es wäre besser, wenn …", tr: "daha iyi olanı kibarca söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yolda bir şey ters gitti ve birinin ne yapacağını bilmesi gerekiyor. Tavsiye vermenin en kibar yolu dilek kipi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dilek kipiyle verilen tavsiye emir gibi durmaz; öneri gibi durur. Panik anında bu fark önemli. Önce kelimeler.")] },
      word("İlk", { de: "der Notfall", tr: "acil durum" }),
      word("İkinci", { de: "der Alarm", tr: "alarm" }),
      word("Üçüncü", { de: "die Feuerwehr", tr: "itfaiye" }),
      word("Dördüncü", { de: "der Transport", tr: "nakliye" }),
      word("Beşinci", { de: "die Mobilität", tr: "hareketlilik" }),
      word("Altıncı", { de: "der Sitz", tr: "koltuk" }),
      word("Yedinci", { de: "das Lager", tr: "depo" }),
      word("Son", { de: "der Blitz", tr: "şimşek" }),
      { say: [tr("İlk kalıbımız yerine geçerek tavsiye veriyor: bir edat öbeği, sonra dilek kipi ve sonda mastar.")] },
      { say: [tr("Örnek:"), de("An deiner Stelle würde ich sofort die Feuerwehr rufen."), tr("Tekrar edin:"), de("An deiner Stelle würde ich sofort die Feuerwehr rufen")], expect: repeat("An deiner Stelle würde ich sofort die Feuerwehr rufen") },
      { say: [tr("Sıra sende: 'Senin yerinde olsam alarmı çalıştırırdım.'")], expect: produce("An deiner Stelle würde ich den Alarm auslösen", [tr("Dilek kipi ikinci sırada, mastar sonda:"), de("An deiner Stelle würde ich den Alarm auslösen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız daha iyi olanı söylüyor: kişisiz bir dilek kipi ve koşul yan cümlesi.")] },
      { say: [tr("Şimdi: 'Aracı depoya çekseler daha iyi olurdu.'")], expect: produce("Es wäre besser, wenn sie das Fahrzeug ins Lager bringen würden", [tr("Yan cümlede dilek kipi ve fiil sonda:"), de("Es wäre besser, wenn sie das Fahrzeug ins Lager bringen würden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es wäre besser, wenn wir rufen die Feuerwehr."), tr("cümlesi doğru mu?")], expect: truefalse("Es wäre besser, wenn wir rufen die Feuerwehr.", false, [tr("Koşul bağlacından sonra çekimli fiil cümlenin en sonuna gider:"), de("Es wäre besser, wenn wir die Feuerwehr rufen.")]) },
      { say: [tr("Son: 'Acil durumda koltukta oturup kalmak olmaz.'")], expect: produce("Im Notfall sollte man nicht einfach im Sitz bleiben", [tr("Kişisiz özne ve tavsiye kipi:"), de("Im Notfall sollte man nicht einfach im Sitz bleiben."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi yolda bir arıza yaşayan arkadaşına telefonda yol göstereceksin.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın yolda kaldı ve seni arıyor. Sakinleştiriyor, ne yapması gerektiğini dilek kipiyle öneriyor ve kimi arayacağını söylüyorsun.",
      partner: "telaşlı, hızlı konuşan bir arkadaş",
      opening: "Ich stehe hier am Straßenrand und weiß nicht weiter — was soll ich machen?",
      openingTr: "Yol kenarında kaldım ve ne yapacağımı bilmiyorum — ne yapmalıyım?",
      goal: "Durum anlaşılmış, en az üç adım tavsiye edilmiş ve kimin aranacağı kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-reise-erzaehlen",
    icon: "camera",
    level: "B1",
    course: "de",
    title: "Nach der Reise",
    titleTr: "Dönüşte anlatmak",
    summary: "Önce olan olayı geriye çekerek anlatmayı öğretir: iki geçmiş katmanı.",
    minutes: 11,
    focusId: "Plusquamperfekt",
    vocab: [
      { de: "das Abenteuer", tr: "macera" },
      { de: "die Erzählung", tr: "öykü" },
      { de: "die Fotografie", tr: "fotoğrafçılık" },
      { de: "der Fotograf", tr: "fotoğrafçı" },
      { de: "das Video", tr: "video" },
      { de: "der Mond", tr: "ay" },
      { de: "der Stern", tr: "yıldız" },
      { de: "der Ozean", tr: "okyanus" },
    ],
    patterns: [
      { de: "Nachdem wir … hatten, …", tr: "önce olanı geriye alır" },
      { de: "Bis dahin hatte ich … nie gesehen.", tr: "o ana kadar olmayanı anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yolculuk bitti ve anlatma vakti. İyi bir anlatıda iki geçmiş katmanı vardır: olan ve ondan önce olan. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Daha eski olan katman ayrı bir geçmiş biçimiyle kurulur: yardımcı fiil geçmişte, asıl fiil ortaç hâlinde. Önce kelimeler.")] },
      word("İlk", { de: "das Abenteuer", tr: "macera" }),
      word("İkinci", { de: "die Erzählung", tr: "öykü" }),
      word("Üçüncü", { de: "die Fotografie", tr: "fotoğrafçılık" }),
      word("Dördüncü", { de: "der Fotograf", tr: "fotoğrafçı" }),
      word("Beşinci", { de: "das Video", tr: "video" }),
      word("Altıncı", { de: "der Mond", tr: "ay" }),
      word("Yedinci", { de: "der Stern", tr: "yıldız" }),
      word("Son", { de: "der Ozean", tr: "okyanus" }),
      { say: [tr("İlk kalıbımız sırayı kuruyor: önce olan yan cümlede eski geçmişle, sonra olan ana cümlede normal geçmişle.")] },
      { say: [tr("Örnek:"), de("Nachdem wir den Ozean gesehen hatten, wurde alles anders."), tr("Tekrar edin:"), de("Nachdem wir den Ozean gesehen hatten, wurde alles anders")], expect: repeat("Nachdem wir den Ozean gesehen hatten, wurde alles anders") },
      { say: [tr("Sıra sende: 'Videoyu çektikten sonra yıldızlara baktık.'")], expect: produce("Nachdem wir das Video gemacht hatten, schauten wir die Sterne an", [tr("Yan cümlede eski geçmiş, ana cümlede normal geçmiş:"), de("Nachdem wir das Video gemacht hatten, schauten wir die Sterne an."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız o ana kadar olmayanı anlatıyor. Anlatıya bir dönüm noktası koyar.")] },
      { say: [tr("Şimdi: 'O zamana kadar okyanusu hiç görmemiştim.'")], expect: produce("Bis dahin hatte ich den Ozean nie gesehen", [tr("Zarf başta, yardımcı fiil ikinci sırada, ortaç sonda:"), de("Bis dahin hatte ich den Ozean nie gesehen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nachdem wir angekommen waren, wir gingen zum Hafen."), tr("cümlesi doğru mu?")], expect: truefalse("Nachdem wir angekommen waren, wir gingen zum Hafen.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar:"), de("Nachdem wir angekommen waren, gingen wir zum Hafen.")]) },
      { say: [tr("Son: 'Fotoğrafçı gittikten sonra ayı çektim.'")], expect: produce("Nachdem der Fotograf gegangen war, fotografierte ich den Mond", [tr("Yer değiştirme fiili eski geçmişte başka bir yardımcı fiil alıyor:"), de("Nachdem der Fotograf gegangen war, fotografierte ich den Mond."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi yolculuğunu bir arkadaşına anlatacaksın: önce ne oldu, ondan önce ne olmuştu.")] },
    ],
    roleplay: {
      scene: "Uzun bir yolculuktan döndün. Bir arkadaşına en çok aklında kalan günü anlatıyorsun: ne olduğunu ve ondan önce ne olmuş olduğunu.",
      partner: "hikâyeyi bölmeden dinleyen, sonra ayrıntı soran bir arkadaş",
      opening: "Endlich zurück! Erzähl — welcher Tag ist dir am meisten geblieben?",
      openingTr: "Nihayet döndün! Anlat — en çok hangi gün aklında kaldı?",
      goal: "Bir gün iki geçmiş katmanıyla anlatılmış ve arkadaşın sorusu yanıtlanmış olur.",
      minTurns: 9,
    },
  },
];
