import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 5 — Bilim ve teknoloji (041–050).
 *
 * Modülün omurgası ortaç sıfatları: Almanca yazı dilinin bir ilgi cümlesini
 * tek bir sıfata sıkıştırma alışkanlığı. "Filmde gösterilen görüntüler",
 * "yeni geliştirilen yöntem", "giderek artan eğilim" — Türkçe bunu ortaçla
 * zaten yapıyor, ama Almancada sıfat EKİ de gerekiyor ve o ek ismin cinsine,
 * hâline ve belirteciyle olan ilişkisine bağlı. Bu yüzden iki ders (041, 042)
 * doğrudan buna ayrıldı ve modül boyunca üç yerde daha çalıştırılıyor.
 *
 * İkinci hat yöntem dili: bir şeyin NASIL yapıldığını `indem` ile anlatmak.
 * Deney, arıza giderme ve süreç anlatımı hep bu bağlaçla kuruluyor.
 *
 * Sahneler bilimsel ama günlük: bir araştırma özeti, mutfak deneyi, çöken bir
 * program, veri gizliliği görüşmesi. B2 öğrencisi laboratuvarda değil, bu
 * konuların konuşulduğu masada oturuyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B05: Lesson[] = [
  {
    id: "de-b2-partizip-1",
    icon: "baby",
    level: "B2",
    course: "de",
    title: "Die lachenden Kinder",
    titleTr: "Partizip I sıfatı",
    summary: "Fiilden 'yapmakta olan' anlamında sıfat türetmeyi öğretir.",
    minutes: 11,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "laufend", tr: "süregelen" },
      { de: "steigend", tr: "artan" },
      { de: "zunehmend", tr: "giderek artan" },
      { de: "die Beobachtung", tr: "gözlem" },
      { de: "das Verhalten", tr: "davranış" },
    ],
    patterns: [
      { de: "die steigenden Preise", tr: "Partizip I: artmakta olan" },
      { de: "die laufenden Kosten", tr: "süregelen giderler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: bilim ve teknoloji. Ama önce bu alanın dilini kuralım — ve o dilin en belirgin aracı fiilden sıfat yapmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural basit: mastarın sonuna bir d eklenir, sonra normal bir sıfat gibi çekilir. Anlamı 'yapmakta olan'. Zor kısım ek değil, ekin çekimi. Önce kelimeler.")] },
      word("İlk", { de: "laufend", tr: "süregelen" }),
      word("İkinci", { de: "steigend", tr: "artan" }),
      word("Üçüncü", { de: "zunehmend", tr: "giderek artan" }),
      word("Dördüncü", { de: "die Beobachtung", tr: "gözlem" }),
      word("Son", { de: "das Verhalten", tr: "davranış" }),
      { say: [tr("Kalıbımız:"), de("die steigenden Preise"), tr("Yani 'artmakta olan fiyatlar'. Belirtili çoğulda sıfat -en ekini alıyor.")] },
      { say: [tr("Örnek:"), de("Die steigenden Preise beunruhigen viele."), tr("Tekrar edin:"), de("Die steigenden Preise beunruhigen viele")], expect: repeat("Die steigenden Preise beunruhigen viele") },
      { say: [tr("Sıra sende: 'Süregelen masraflar bütçeyi zorluyor.'")], expect: produce("Die laufenden Kosten belasten das Budget", [tr("Belirtili çoğulda ortaç -en ekini alır:"), de("Die laufenden Kosten belasten das Budget."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Giderek artan bir eğilim gözlemleniyor.'")], expect: produce("Eine zunehmende Tendenz wird beobachtet", [tr("Belirtisiz dişil tekilde ortaç -e ekini alır:"), de("Eine zunehmende Tendenz wird beobachtet."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Oynayan çocuklar hiçbir şey fark etmedi.'")], expect: produce("Die spielenden Kinder haben nichts gemerkt", [tr("Aynı kural, bu kez insanlar için:"), de("Die spielenden Kinder haben nichts gemerkt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die steigende Preise beunruhigen viele."), tr("cümlesi doğru mu?")], expect: truefalse("Die steigende Preise beunruhigen viele.", false, [tr("Belirtili çoğulda sıfat -en ekini alır:"), de("Die steigenden Preise beunruhigen viele.")]) },
      { say: [tr("Son: 'Bu gözlem davranışı açıklıyor.'")], expect: produce("Diese Beobachtung erklärt das Verhalten", [tr("Düz bir cümle; nesne belirtme hâlinde:"), de("Diese Beobachtung erklärt das Verhalten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir eğilimi tartışacaksın: ne artıyor, ne azalıyor, sen ne gözlemliyorsun.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla son yıllarda artan bir eğilimi konuşuyorsunuz (ekran süresi, kira, ulaşım maliyeti — hangisini seçersen). Ne arttığını, ne azaldığını ve kendi gözlemini anlat.",
      partner: "sayılara meraklı, örnek isteyen bir tanıdık",
      opening: "Mir fällt in letzter Zeit etwas auf: Alles wird teurer, aber niemand redet über die laufenden Kosten. Was beobachten Sie denn?",
      openingTr: "Son zamanlarda dikkatimi çeken bir şey var: Her şey pahalanıyor ama kimse süregelen giderlerden konuşmuyor. Siz ne gözlemliyorsunuz?",
      goal: "Artan ve azalan eğilimler örneklerle anlatılmış ve iki taraf ortak bir gözlemde buluşmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-partizip-2",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Das gelöste Problem",
    titleTr: "Partizip II sıfatı",
    summary: "Fiilden 'yapılmış olan' anlamında sıfat türetmeyi öğretir.",
    minutes: 11,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "das Verfahren", tr: "yöntem, süreç" },
      { de: "entwickeln", tr: "geliştirmek" },
      { de: "erprobt", tr: "denenmiş" },
      { de: "die Methode", tr: "yöntem" },
      { de: "zugelassen", tr: "ruhsatlı, onaylı" },
    ],
    patterns: [
      { de: "das entwickelte Verfahren", tr: "Partizip II: geliştirilmiş" },
      { de: "die getestete Methode", tr: "test edilmiş yöntem" },
    ],
    lecture: [
      { say: [tr("Merhaba! Dün 'yapmakta olan' sıfatını kurduk. Bugün ikizi: 'yapılmış olan'. İkisi zıt yönlere bakıyor ve karıştırmak anlamı tersine çeviriyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu kez ortaç geçmiş biçimden geliyor. 'Geliştiren yöntem' başka, 'geliştirilen yöntem' başka; Almancada bu fark tek bir ortaçla söyleniyor. Önce kelimeler.")] },
      word("İlk", { de: "das Verfahren", tr: "yöntem, süreç" }),
      word("İkinci", { de: "entwickeln", tr: "geliştirmek" }),
      word("Üçüncü", { de: "erprobt", tr: "denenmiş" }),
      word("Dördüncü", { de: "die Methode", tr: "yöntem" }),
      word("Son", { de: "zugelassen", tr: "ruhsatlı, onaylı" }),
      { say: [tr("Kalıbımız:"), de("das entwickelte Verfahren"), tr("Yani 'geliştirilmiş olan yöntem'. Edilgen anlam ortacın içinde.")] },
      { say: [tr("Örnek:"), de("Das entwickelte Verfahren ist bereits erprobt."), tr("Tekrar edin:"), de("Das entwickelte Verfahren ist bereits erprobt")], expect: repeat("Das entwickelte Verfahren ist bereits erprobt") },
      { say: [tr("Sıra sende: 'Test edilen yöntem daha hızlı.'")], expect: produce("Die getestete Methode ist schneller", [tr("Belirtili dişil tekilde ortaç -e ekini alır:"), de("Die getestete Methode ist schneller."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Onaylı ilaçlar listede.'")], expect: produce("Die zugelassenen Medikamente stehen auf der Liste", [tr("Belirtili çoğulda -en eki:"), de("Die zugelassenen Medikamente stehen auf der Liste."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yeni geliştirilen program ücretsiz.'")], expect: produce("Das neu entwickelte Programm ist kostenlos", [tr("Zarf ortaçtan önce, ikisi birlikte ismin önünde:"), de("Das neu entwickelte Programm ist kostenlos."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das neu entwickelte Programm ist kostenlos."), tr("cümlesi doğru mu?")], expect: truefalse("Das neu entwickelte Programm ist kostenlos.", true, [tr("Doğru. Zarf ve ortaç ismin önünde sırayla duruyor ve ortaç nötr tekilde -e ekini almış.")]) },
      { say: [tr("Son bir soru: 'Bu denenmiş bir yöntem mi?'")], expect: produce("Ist das ein erprobtes Verfahren", [tr("Belirtisiz nötr tekilde sıfat -es ekini alır:"), de("Ist das ein erprobtes Verfahren?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada yeni bir yöntemi değerlendireceksin: nasıl geliştirildi, denendi mi, güvenilir mi.")] },
    ],
    roleplay: {
      scene: "İş yerinde yeni bir yöntem öneriliyor. Nasıl geliştirildiğini, denenip denenmediğini ve hangi sonuçların alındığını sor; sonra kendi değerlendirmeni söyle.",
      partner: "yöntemi savunan, ayrıntı verebilen bir proje sorumlusu",
      opening: "Das neu entwickelte Verfahren spart uns ein Drittel der Zeit. Wo sehen Sie das Problem?",
      openingTr: "Yeni geliştirilen yöntem bize zamanın üçte birini kazandırıyor. Sorunu nerede görüyorsunuz?",
      goal: "Yöntemin nasıl geliştirildiği ve denendiği öğrenilmiş, öğrencinin değerlendirmesi gerekçesiyle söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-ki-alltag",
    icon: "tech",
    level: "B2",
    course: "de",
    title: "KI im Alltag",
    titleTr: "Yapay zekâ sohbeti",
    summary: "Neyin otomatikleştirilebileceğini edilgen yerine geçen yapılarla tartışmayı öğretir.",
    minutes: 11,
    focusId: "Passiversatz",
    vocab: [
      { de: "automatisieren", tr: "otomatikleştirmek" },
      { de: "der Algorithmus", tr: "algoritma" },
      { de: "erstellen", tr: "oluşturmak" },
      { de: "fragwürdig", tr: "şüpheli" },
      { de: "die Anwendung", tr: "uygulama" },
    ],
    patterns: [
      { de: "… lässt sich automatisieren", tr: "otomatikleştirilebilir" },
      { de: "Es bleibt zu fragen, …", tr: "açık kalan soru" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün yapay zekâyı konuşacağız ve bu konunun dili edilgendir: neyin yapılabildiği konuşulur, kimin yaptığı değil. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de tartışmayı açık bırakan güzel bir kalıp var: 'sorulması gereken şu ki'. Cevap vermeden soruyu masaya koyar. Önce kelimeler.")] },
      word("İlk", { de: "automatisieren", tr: "otomatikleştirmek" }),
      word("İkinci", { de: "der Algorithmus", tr: "algoritma" }),
      word("Üçüncü", { de: "erstellen", tr: "oluşturmak" }),
      word("Dördüncü", { de: "fragwürdig", tr: "şüpheli" }),
      word("Son", { de: "die Anwendung", tr: "uygulama" }),
      { say: [tr("Kalıbımız:"), de("… lässt sich automatisieren"), tr("Edilgen kurmadan aynı anlamı veriyor ve konuşma dilinde çok daha doğal.")] },
      { say: [tr("Örnek:"), de("Vieles lässt sich inzwischen automatisieren."), tr("Tekrar edin:"), de("Vieles lässt sich inzwischen automatisieren")], expect: repeat("Vieles lässt sich inzwischen automatisieren") },
      { say: [tr("Sıra sende: 'Bu adım otomatikleştirilebilir.'")], expect: produce("Dieser Schritt lässt sich automatisieren", [tr("lassen artı dönüşlü zamir; mastar sonda:"), de("Dieser Schritt lässt sich automatisieren."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi ortaç sıfatıyla: 'Yapay zekâyla oluşturulan metinler işaretlenmeli.'")], expect: produce("Von KI erstellte Texte sollten gekennzeichnet werden", [tr("Ortaç öbeği ismin önünde; sonda ortaç ve werden:"), de("Von KI erstellte Texte sollten gekennzeichnet werden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sorulması gereken şu: kim sorumlu?'")], expect: produce("Es bleibt zu fragen, wer verantwortlich ist", [tr("Sahte özne es; yan cümlede fiil sonda:"), de("Es bleibt zu fragen, wer verantwortlich ist."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dieser Schritt lässt sich automatisieren werden."), tr("cümlesi doğru mu?")], expect: truefalse("Dieser Schritt lässt sich automatisieren werden.", false, [tr("Bu yapı zaten edilgen anlamı taşır; sonda ayrıca werden bulunmaz:"), de("Dieser Schritt lässt sich automatisieren.")]) },
      { say: [tr("Son: 'Uygulama bana şüpheli geliyor.'")], expect: produce("Die Anwendung erscheint mir fragwürdig", [tr("Bu fiil yönelme hâli ister:"), de("Die Anwendung erscheint mir fragwürdig."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada yapay zekânın işinde ne kadar yeri olduğunu tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşınla yapay zekânın işinizde ne kadar yer alması gerektiğini tartışıyorsunuz: ne otomatikleştirilebilir, ne otomatikleştirilmemeli, sorumluluk kimde kalır.",
      partner: "yapay zekâya hevesli, sınır tanımayan bir meslektaş",
      opening: "Ich lasse inzwischen fast alles vorschreiben — spart enorm Zeit. Wo würdest du die Grenze ziehen?",
      openingTr: "Artık neredeyse her şeyi ona yazdırıyorum — müthiş zaman kazandırıyor. Sen sınırı nereye çekerdin?",
      goal: "Otomatikleştirilebilecek ve edilmemesi gereken işler ayrılmış ve sorumluluğun kimde kalacağı konuşulmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-studie",
    icon: "school",
    level: "B2",
    course: "de",
    title: "Die neue Studie",
    titleTr: "Araştırma özetleme",
    summary: "Bir araştırmanın bulgularını isimleşmiş akademik dille aktarmayı öğretir.",
    minutes: 11,
    focusId: "Nominalisierung",
    vocab: [
      { de: "die Untersuchung", tr: "araştırma" },
      { de: "die Auswertung", tr: "değerlendirme" },
      { de: "der Durchschnitt", tr: "ortalama" },
      { de: "die Stichprobe", tr: "örneklem" },
      { de: "belegen", tr: "kanıtlamak" },
    ],
    patterns: [
      { de: "Die Untersuchung zeigt, dass …", tr: "bulguyu bildirir" },
      { de: "Bei der Auswertung …", tr: "isim öbeğiyle aşama" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir araştırmayı özetleyeceğiz. Akademik dilin işi kısaltmaktır ve kısaltma yöntemi hep aynı: fiili isme çevirmek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Verileri değerlendirirken' yerine 'değerlendirmede' denir. Bu, ilk modülde öğrendiğin yapının bilimsel hâli. Önce kelimeler.")] },
      word("İlk", { de: "die Untersuchung", tr: "araştırma" }),
      word("İkinci", { de: "die Auswertung", tr: "değerlendirme" }),
      word("Üçüncü", { de: "der Durchschnitt", tr: "ortalama" }),
      word("Dördüncü", { de: "die Stichprobe", tr: "örneklem" }),
      word("Son", { de: "belegen", tr: "kanıtlamak" }),
      { say: [tr("Kalıbımız:"), de("Bei der Auswertung …"), tr("Bir aşama, yan cümle kurmadan isim öbeğiyle söyleniyor.")] },
      { say: [tr("Örnek:"), de("Die Untersuchung zeigt einen deutlichen Zusammenhang."), tr("Tekrar edin:"), de("Die Untersuchung zeigt einen deutlichen Zusammenhang")], expect: repeat("Die Untersuchung zeigt einen deutlichen Zusammenhang") },
      { say: [tr("Sıra sende: 'Değerlendirme sırasında bir hata fark edildi.'")], expect: produce("Bei der Auswertung ist ein Fehler aufgefallen", [tr("Tümleç başta olduğu için fiil ikinci sırada:"), de("Bei der Auswertung ist ein Fehler aufgefallen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ortalamada katılımcılar altı saat uyuyor.'")], expect: produce("Im Durchschnitt schlafen die Teilnehmenden sechs Stunden", [tr("Kalıplaşmış ifade başta, fiil ikinci sırada:"), de("Im Durchschnitt schlafen die Teilnehmenden sechs Stunden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Örneklem çok küçüktü.'")], expect: produce("Die Stichprobe war zu klein", [tr("Kısa bir hüküm; geçmiş zamanda:"), de("Die Stichprobe war zu klein."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Bei der Auswertung ein Fehler ist aufgefallen."), tr("cümlesi doğru mu?")], expect: truefalse("Bei der Auswertung ein Fehler ist aufgefallen.", false, [tr("Cümle bir tümleçle başlayınca çekimli fiil hemen ikinci sıraya gelir:"), de("Bei der Auswertung ist ein Fehler aufgefallen.")]) },
      { say: [tr("Son bir soru: 'Bu sonucu ne kanıtlıyor?'")], expect: produce("Was belegt dieses Ergebnis", [tr("Soru zamiri özne, fiil ikinci sırada:"), de("Was belegt dieses Ergebnis?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada okuduğun bir araştırmayı anlatacaksın: ne buldu, nasıl ölçtü, sen ne düşünüyorsun.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına okuduğun bir araştırmayı anlatıyorsun: ne buldu, kaç kişiyle yapıldı, sonucu ne kadar güvenilir ve sen ne düşünüyorsun.",
      partner: "araştırmalara şüpheyle bakan, yöntemi soran bir arkadaş",
      opening: "Studien sagen doch jedes Jahr etwas anderes. Wie viele Leute waren denn überhaupt dabei?",
      openingTr: "Araştırmalar her yıl başka bir şey söylüyor zaten. Kaç kişi katılmış ki bu araştırmaya?",
      goal: "Araştırmanın bulgusu, yöntemi ve örneklemi anlatılmış; ne kadar güvenilir olduğu konusunda ortak bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-experiment",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Das Küchenexperiment",
    titleTr: "Deney anlatımı",
    summary: "Bir şeyin nasıl yapıldığını indem bağlacıyla anlatmayı öğretir.",
    minutes: 11,
    focusId: "Nebensatz-indem",
    vocab: [
      { de: "der Versuch", tr: "deney, deneme" },
      { de: "messen", tr: "ölçmek" },
      { de: "die Bedingung", tr: "koşul" },
      { de: "nachvollziehbar", tr: "izlenebilir, anlaşılır" },
      { de: "verblüffend", tr: "şaşırtıcı" },
    ],
    patterns: [
      { de: "…, indem man …", tr: "yöntem: … yaparak" },
      { de: "Dadurch, dass …", tr: "sebep-yöntem bağı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir yöntem anlatacağız: bir şey NASIL yapılıyor. Almancada bunun kendi bağlacı var ve Türkçedeki '-arak' ekine karşılık geliyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dikkat: bu bir yan cümle bağlacı, yani fiil sona gidiyor. Türkçe konuşan burada çok kayar çünkü '-arak' ekinde böyle bir sıra yok. Önce kelimeler.")] },
      word("İlk", { de: "der Versuch", tr: "deney, deneme" }),
      word("İkinci", { de: "messen", tr: "ölçmek" }),
      word("Üçüncü", { de: "die Bedingung", tr: "koşul" }),
      word("Dördüncü", { de: "nachvollziehbar", tr: "izlenebilir, anlaşılır" }),
      word("Son", { de: "verblüffend", tr: "şaşırtıcı" }),
      { say: [tr("Kalıbımız:"), de("…, indem man …"), tr("Yan cümle olduğu için çekimli fiil en sonda durur.")] },
      { say: [tr("Örnek:"), de("Man misst die Temperatur, indem man das Gerät eintaucht."), tr("Tekrar edin:"), de("Man misst die Temperatur, indem man das Gerät eintaucht")], expect: repeat("Man misst die Temperatur, indem man das Gerät eintaucht") },
      { say: [tr("Sıra sende: 'Sonucu, koşulları değiştirerek kontrol edersin.'")], expect: produce("Man prüft das Ergebnis, indem man die Bedingungen ändert", [tr("Yan cümlede fiil en sonda:"), de("Man prüft das Ergebnis, indem man die Bedingungen ändert."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Deney izlenebilir olmalı.'")], expect: produce("Der Versuch muss nachvollziehbar sein", [tr("Modal fiil çekimli, mastar sonda:"), de("Der Versuch muss nachvollziehbar sein."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sıcaklık her beş dakikada ölçülüyor.'")], expect: produce("Die Temperatur wird alle fünf Minuten gemessen", [tr("Şimdiki zaman edilgeni; ortaç sonda:"), de("Die Temperatur wird alle fünf Minuten gemessen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Man prüft das Ergebnis, indem man ändert die Bedingungen."), tr("cümlesi doğru mu?")], expect: truefalse("Man prüft das Ergebnis, indem man ändert die Bedingungen.", false, [tr("Bu bir yan cümle bağlacıdır; çekimli fiil en sona gider:"), de("Man prüft das Ergebnis, indem man die Bedingungen ändert.")]) },
      { say: [tr("Son: 'Sonuç şaşırtıcıydı.'")], expect: produce("Das Ergebnis war verblüffend", [tr("Kısa bir hüküm cümlesi:"), de("Das Ergebnis war verblüffend."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada birine basit bir deneyi anlatacaksın: nasıl yapılıyor, ne ölçülüyor, sonuç ne.")] },
    ],
    roleplay: {
      scene: "Birine evde yapılabilecek basit bir deneyi anlatıyorsun: ne gerekiyor, nasıl yapılıyor, ne ölçülüyor ve sonuç neden şaşırtıcı. Her adımı yöntem bağlacıyla anlat.",
      partner: "meraklı ama her adımı sorgulayan bir dinleyici",
      opening: "Ein Experiment in der Küche? Gut — aber sagen Sie mir zuerst: Was genau will man damit herausfinden?",
      openingTr: "Mutfakta deney mi? Peki — ama önce şunu söyleyin: Bununla tam olarak ne bulunmak isteniyor?",
      goal: "Deneyin amacı, adımları ve sonucu anlatılmış; dinleyen kendi cümlesiyle özetleyebilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-datenschutz",
    icon: "law",
    level: "B2",
    course: "de",
    title: "Meine Daten gehören mir",
    titleTr: "Veri gizliliği",
    summary: "Veri haklarını kipli edilgenle savunmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "der Datenschutz", tr: "veri koruma" },
      { de: "weitergeben", tr: "üçüncü tarafa vermek" },
      { de: "speichern", tr: "kaydetmek" },
      { de: "widersprechen", tr: "itiraz etmek" },
      { de: "personenbezogen", tr: "kişisel veriye ilişkin" },
    ],
    patterns: [
      { de: "dürfen nicht … werden", tr: "yasak: verilemez" },
      { de: "Dem können Sie widersprechen.", tr: "itiraz hakkı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kendi verilerini savunacaksın. Bu alanın dili kipli edilgendir çünkü kural kimin ne yapacağını değil, neyin yapılamayacağını söyler. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de itiraz fiili var ve o fiil yönelme hâli istiyor — bunu kaçırmak cümleyi bozar. Önce kelimeler.")] },
      word("İlk", { de: "der Datenschutz", tr: "veri koruma" }),
      word("İkinci", { de: "weitergeben", tr: "üçüncü tarafa vermek" }),
      word("Üçüncü", { de: "speichern", tr: "kaydetmek" }),
      word("Dördüncü", { de: "widersprechen", tr: "itiraz etmek" }),
      word("Son", { de: "personenbezogen", tr: "kişisel veriye ilişkin" }),
      { say: [tr("Kalıbımız:"), de("dürfen nicht … werden"), tr("Yasak bildiren kipli edilgen; sonda ortaç ve werden.")] },
      { say: [tr("Örnek:"), de("Personenbezogene Daten dürfen nicht weitergegeben werden."), tr("Tekrar edin:"), de("Personenbezogene Daten dürfen nicht weitergegeben werden")], expect: repeat("Personenbezogene Daten dürfen nicht weitergegeben werden") },
      { say: [tr("Sıra sende: 'Veriler yalnızca rıza ile kaydedilebilir.'")], expect: produce("Daten dürfen nur mit Einwilligung gespeichert werden", [tr("Kip fiili ikinci sırada; sonda ortaç ve werden:"), de("Daten dürfen nur mit Einwilligung gespeichert werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Buna itiraz edebilirsiniz.'")], expect: produce("Dem können Sie widersprechen", [tr("Bu fiil yönelme hâli ister; tümleç öne alınmış:"), de("Dem können Sie widersprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kişisel veriler korunmalı.'")], expect: produce("Personenbezogene Daten müssen geschützt werden", [tr("Zorunluluk müssen ile; sonda ortaç ve werden:"), de("Personenbezogene Daten müssen geschützt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Personenbezogene Daten dürfen nicht weitergegeben werden."), tr("cümlesi doğru mu?")], expect: truefalse("Personenbezogene Daten dürfen nicht weitergegeben werden.", true, [tr("Doğru. Sıfat belirtisiz çoğulda -e ekini almış ve kipli edilgen sonda ortaç ile werden sırasında.")]) },
      { say: [tr("Son bir soru: 'Verilerim ne kadar süre saklanıyor?'")], expect: produce("Wie lange werden meine Daten gespeichert", [tr("Soru öbeği başta, çekimli fiil ikinci sırada:"), de("Wie lange werden meine Daten gespeichert?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir hizmet sağlayıcıyla veri kullanımını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir hizmet sağlayıcının müşteri temsilcisiyle verilerinin nasıl kullanıldığını konuşuyorsun: ne kaydediliyor, kime veriliyor, ne kadar saklanıyor ve neye itiraz edebilirsin.",
      partner: "kuralları bilen ama ayrıntıya girmek istemeyen bir müşteri temsilcisi",
      opening: "Sie haben eine Frage zum Datenschutz? Grundsätzlich halten wir uns natürlich an alle Vorgaben. Was genau möchten Sie wissen?",
      openingTr: "Veri koruma hakkında bir sorunuz mu var? Prensipte elbette bütün kurallara uyuyoruz. Tam olarak neyi bilmek istiyorsunuz?",
      goal: "Hangi verilerin kaydedildiği, kimlerle paylaşıldığı ve ne kadar saklandığı öğrenilmiş; bir itiraz iletilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-weltraum",
    icon: "star",
    level: "B2",
    course: "de",
    title: "Aufbruch ins All",
    titleTr: "Uzay sohbeti",
    summary: "Ortaç sıfatlarıyla planlanan ve keşfedilen şeyleri anlatmayı öğretir.",
    minutes: 11,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "die Raumfahrt", tr: "uzay yolculuğu" },
      { de: "bemannt", tr: "insanlı" },
      { de: "die Umlaufbahn", tr: "yörünge" },
      { de: "die Mission", tr: "görev, misyon" },
      { de: "erforschen", tr: "araştırmak, keşfetmek" },
    ],
    patterns: [
      { de: "die geplante Mission", tr: "planlanan görev" },
      { de: "der neu entdeckte Planet", tr: "yeni keşfedilen gezegen" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün gökyüzüne bakıyoruz. Bu konunun dili ortaç sıfatlarıyla dolu: planlanan görev, insanlı yolculuk, yeni keşfedilen gezegen. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de yer bildirirken dikkat edeceğin bir nokta var: bir şeyin nerede OLDUĞUNU söylerken hâl değişir. Bunu sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "die Raumfahrt", tr: "uzay yolculuğu" }),
      word("İkinci", { de: "bemannt", tr: "insanlı" }),
      word("Üçüncü", { de: "die Umlaufbahn", tr: "yörünge" }),
      word("Dördüncü", { de: "die Mission", tr: "görev, misyon" }),
      word("Son", { de: "erforschen", tr: "araştırmak, keşfetmek" }),
      { say: [tr("Kalıbımız:"), de("die geplante Mission"), tr("Ortaç ismin önünde ve sıfat ekini almış durumda.")] },
      { say: [tr("Örnek:"), de("Die geplante Mission startet im Herbst."), tr("Tekrar edin:"), de("Die geplante Mission startet im Herbst")], expect: repeat("Die geplante Mission startet im Herbst") },
      { say: [tr("Sıra sende: 'İnsanlı uzay yolculuğu pahalı.'")], expect: produce("Die bemannte Raumfahrt ist teuer", [tr("Belirtili dişil tekilde sıfat -e ekini alır:"), de("Die bemannte Raumfahrt ist teuer."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yeni keşfedilen gezegen çok uzakta.'")], expect: produce("Der neu entdeckte Planet ist sehr weit weg", [tr("Zarf ve ortaç birlikte ismin önünde:"), de("Der neu entdeckte Planet ist sehr weit weg."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Uydu yörüngede.'")], expect: produce("Der Satellit ist in der Umlaufbahn", [tr("Yer bildirirken bu edat yönelme hâli ister:"), de("Der Satellit ist in der Umlaufbahn."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Satellit ist in die Umlaufbahn."), tr("cümlesi doğru mu?")], expect: truefalse("Der Satellit ist in die Umlaufbahn.", false, [tr("Hareket değil konum bildiriliyor, o yüzden yönelme hâli gerekir:"), de("Der Satellit ist in der Umlaufbahn.")]) },
      { say: [tr("Son bir soru: 'Uzayı neden araştırıyoruz?'")], expect: produce("Warum erforschen wir den Weltraum", [tr("Soru kelimesi başta, fiil ikinci sırada:"), de("Warum erforschen wir den Weltraum?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada uzay araştırmalarının değerini tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla uzay araştırmalarına bu kadar para harcanmasının doğru olup olmadığını tartışıyorsunuz. Görüşünü gerekçelendir, karşı tarafın itirazına karşılık ver ve ortak bir noktada buluşun.",
      partner: "parayı dünyadaki sorunlara harcamak isteyen bir arkadaş",
      opening: "Milliarden für eine geplante Mission zum Mars — und hier unten funktioniert nicht mal der Nahverkehr. Findest du das richtig?",
      openingTr: "Planlanan bir Mars görevine milyarlar — ve burada toplu taşıma bile düzgün işlemiyor. Bunu doğru buluyor musun?",
      goal: "İki taraf da görüşünü gerekçelendirmiş, itirazlara karşılık verilmiş ve ortak bir noktada buluşulmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-medizin-fortschritt",
    icon: "doctor",
    level: "B2",
    course: "de",
    title: "Der Durchbruch",
    titleTr: "Tıpta gelişme",
    summary: "Tıbbi gelişmeleri edilgen geçmişle aktarmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "der Durchbruch", tr: "atılım" },
      { de: "klinisch", tr: "klinik olarak" },
      { de: "zulassen", tr: "ruhsatlandırmak" },
      { de: "die Nebenwirkung", tr: "yan etki" },
      { de: "heilbar", tr: "tedavi edilebilir" },
    ],
    patterns: [
      { de: "ist … erprobt worden", tr: "denenmiş oldu" },
      { de: "sind … untersucht worden", tr: "çoğul: incelendiler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün tıptaki bir gelişmeyi aktaracağız. Bu tür haberlerde her cümle edilgen geçmiştir çünkü önemli olan kimin yaptığı değil, neyin yapılmış olduğu. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tek dikkat noktası yardımcı fiilin tekil mi çoğul mu olduğu. Kolay görünüyor ama hızlı konuşurken en çok orada kayılıyor. Önce kelimeler.")] },
      word("İlk", { de: "der Durchbruch", tr: "atılım" }),
      word("İkinci", { de: "klinisch", tr: "klinik olarak" }),
      word("Üçüncü", { de: "zulassen", tr: "ruhsatlandırmak" }),
      word("Dördüncü", { de: "die Nebenwirkung", tr: "yan etki" }),
      word("Son", { de: "heilbar", tr: "tedavi edilebilir" }),
      { say: [tr("Kalıbımız:"), de("ist … erprobt worden"), tr("Çoğulda sind. Kısalmış biçim her zaman en sonda.")] },
      { say: [tr("Örnek:"), de("Der Wirkstoff ist zehn Jahre lang erprobt worden."), tr("Tekrar edin:"), de("Der Wirkstoff ist zehn Jahre lang erprobt worden")], expect: repeat("Der Wirkstoff ist zehn Jahre lang erprobt worden") },
      { say: [tr("Sıra sende: 'İlaç geçen yıl ruhsatlandırıldı.'")], expect: produce("Das Medikament ist letztes Jahr zugelassen worden", [tr("Tekil özne ist alır; ayrılabilen fiilin ortacı:"), de("Das Medikament ist letztes Jahr zugelassen worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi çoğulla: 'Yan etkiler klinik olarak incelendi.'")], expect: produce("Die Nebenwirkungen sind klinisch untersucht worden", [tr("Çoğul özne sind ister:"), de("Die Nebenwirkungen sind klinisch untersucht worden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Hastalık artık tedavi edilebilir.'")], expect: produce("Die Krankheit ist inzwischen heilbar", [tr("Sıfat biçimi; edilgen kurmaya gerek yok:"), de("Die Krankheit ist inzwischen heilbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Nebenwirkungen ist klinisch untersucht worden."), tr("cümlesi doğru mu?")], expect: truefalse("Die Nebenwirkungen ist klinisch untersucht worden.", false, [tr("Özne çoğul olduğu için yardımcı fiil de çoğul olur:"), de("Die Nebenwirkungen sind klinisch untersucht worden.")]) },
      { say: [tr("Son: 'Bu birçok insan için bir atılım.'")], expect: produce("Das ist ein Durchbruch für viele Menschen", [tr("Belirtisiz eril tekil; edat belirtme hâli ister:"), de("Das ist ein Durchbruch für viele Menschen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada duyduğun bir tıbbi gelişmeyi anlatacaksın: ne bulundu, nasıl denendi, ne anlama geliyor.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığına duyduğun tıbbi bir gelişmeyi anlatıyorsun: ne bulundu, nasıl ve ne kadar denendi, kimler için ne anlama geliyor ve neye dikkat etmek gerekiyor.",
      partner: "umutlanan ama abartıya karşı temkinli bir tanıdık",
      opening: "Ich habe davon gehört — angeblich ist alles schon getestet worden. Stimmt das wirklich?",
      openingTr: "Duydum bunu — güya her şey çoktan test edilmiş. Bu gerçekten doğru mu?",
      goal: "Gelişmenin ne olduğu, nasıl denendiği ve kimler için ne anlama geldiği anlatılmış; abartıya karşı bir uyarı yapılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-technikfrust",
    icon: "tech",
    level: "B2",
    course: "de",
    title: "Warum geht das nicht?",
    titleTr: "Teknoloji hayal kırıklığı",
    summary: "Arızayı tarif etmeyi ve çözümü yöntem bağlacıyla anlatmayı öğretir.",
    minutes: 11,
    focusId: "Nebensatz-indem",
    vocab: [
      { de: "abstürzen", tr: "çökmek (program)" },
      { de: "einfrieren", tr: "donmak (ekran)" },
      { de: "der Neustart", tr: "yeniden başlatma" },
      { de: "umständlich", tr: "zahmetli" },
      { de: "nerven", tr: "sinir bozmak" },
    ],
    patterns: [
      { de: "Man löst es, indem man …", tr: "çözümü yöntemle söyler" },
      { de: "Das nervt.", tr: "kısa şikâyet" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün herkesin bildiği bir duygu: teknoloji çalışmıyor. İyi haber, şikâyetin de çözümün de hazır kalıpları var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Çözüm cümlesi yine yöntem bağlacıyla kuruluyor — 'yeniden başlatarak çözersin'. Bu ders o yapının günlük hâli. Önce kelimeler.")] },
      word("İlk", { de: "abstürzen", tr: "çökmek (program)" }),
      word("İkinci", { de: "einfrieren", tr: "donmak (ekran)" }),
      word("Üçüncü", { de: "der Neustart", tr: "yeniden başlatma" }),
      word("Dördüncü", { de: "umständlich", tr: "zahmetli" }),
      word("Son", { de: "nerven", tr: "sinir bozmak" }),
      { say: [tr("Kalıbımız:"), de("Man löst es, indem man …"), tr("Yan cümlede fiil sonda; bu kuralı bu modülde üçüncü kez görüyorsun.")] },
      { say: [tr("Örnek:"), de("Man löst es meistens, indem man das Gerät neu startet."), tr("Tekrar edin:"), de("Man löst es meistens, indem man das Gerät neu startet")], expect: repeat("Man löst es meistens, indem man das Gerät neu startet") },
      { say: [tr("Sıra sende: 'Program yine çöktü.'")], expect: produce("Das Programm ist schon wieder abgestürzt", [tr("Bu fiil sein ile çekilir; ortaç sonda:"), de("Das Programm ist schon wieder abgestürzt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ekran donuyor.'")], expect: produce("Der Bildschirm friert ein", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Der Bildschirm friert ein."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Süreç gereksiz yere zahmetli.'")], expect: produce("Der Vorgang ist unnötig umständlich", [tr("Zarf sıfattan önce:"), de("Der Vorgang ist unnötig umständlich."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Man löst es meistens, indem man das Gerät neu startet."), tr("cümlesi doğru mu?")], expect: truefalse("Man löst es meistens, indem man das Gerät neu startet.", true, [tr("Doğru. Yöntem bağlacından sonra çekimli fiil yan cümlenin sonunda duruyor.")]) },
      { say: [tr("Son: 'Bu beni gerçekten sinir ediyor.'")], expect: produce("Das nervt mich wirklich", [tr("Kısa ve günlük bir şikâyet:"), de("Das nervt mich wirklich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşından teknik yardım isteyeceksin: sorunu tarif et, denediklerini söyle ve çözümü öğren.")] },
    ],
    roleplay: {
      scene: "Bilgisayarın sürekli donuyor ve teknikten anlayan bir arkadaşından yardım istiyorsun. Sorunu tarif et, ne zaman olduğunu söyle, ne denediğini anlat ve çözümü kendi cümlenle tekrarla.",
      partner: "sabırlı ama önce hep 'yeniden başlattın mı' diye soran bir arkadaş",
      opening: "Warte, langsam. Wann friert er ein — immer, oder nur bei bestimmten Programmen?",
      openingTr: "Dur, yavaş. Ne zaman donuyor — hep mi, yoksa sadece belli programlarda mı?",
      goal: "Sorun tarif edilmiş, denenenler söylenmiş ve çözüm öğrenilip kendi cümlesiyle tekrarlanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-zukunftstechnologien",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Morgen schon Realität?",
    titleTr: "Gelecek teknolojileri",
    summary: "Gelecek tahminlerini emin olma derecesine göre söylemeyi öğretir.",
    minutes: 11,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "sich durchsetzen", tr: "yaygınlaşmak" },
      { de: "abwarten", tr: "beklemek, görmek" },
      { de: "bahnbrechend", tr: "çığır açan" },
      { de: "die Serienreife", tr: "seri üretime hazırlık" },
      { de: "skeptisch", tr: "şüpheci" },
    ],
    patterns: [
      { de: "… dürfte sich durchsetzen", tr: "temkinli tahmin" },
      { de: "Es bleibt abzuwarten, …", tr: "cevabı açık bırakır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve konusu gelecek. Gelecek hakkında konuşurken Almanca ne kadar emin olduğunu fiille gösterir — kesin, olası ya da sadece duyulmuş. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("dürfte: büyük ihtimalle. soll: öyle diyorlar. wird: kesin. Üçünü doğru seçmek, tahminini savunulabilir kılar. Önce kelimeler.")] },
      word("İlk", { de: "sich durchsetzen", tr: "yaygınlaşmak" }),
      word("İkinci", { de: "abwarten", tr: "beklemek, görmek" }),
      word("Üçüncü", { de: "bahnbrechend", tr: "çığır açan" }),
      word("Dördüncü", { de: "die Serienreife", tr: "seri üretime hazırlık" }),
      word("Son", { de: "skeptisch", tr: "şüpheci" }),
      { say: [tr("Kalıbımız:"), de("… dürfte sich durchsetzen"), tr("Yani 'büyük ihtimalle yaygınlaşır'. Kesin konuşmadan tahmin etmek.")] },
      { say: [tr("Örnek:"), de("Diese Technik dürfte sich durchsetzen."), tr("Tekrar edin:"), de("Diese Technik dürfte sich durchsetzen")], expect: repeat("Diese Technik dürfte sich durchsetzen") },
      { say: [tr("Sıra sende: 'Çığır açıcı olduğu söyleniyor.'")], expect: produce("Sie soll bahnbrechend sein", [tr("Duyulan bilgi sollen ile; mastar sonda:"), de("Sie soll bahnbrechend sein."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Seri üretime ne zaman hazır olacağı belli değil, göreceğiz.'")], expect: produce("Es bleibt abzuwarten, wann die Serienreife erreicht wird", [tr("Sahte özne es; ayrılabilen fiilde zu ortaya girer:"), de("Es bleibt abzuwarten, wann die Serienreife erreicht wird."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ben bu konuda daha çok şüpheciyim.'")], expect: produce("Ich bin da eher skeptisch", [tr("Kısa ve doğal bir görüş cümlesi:"), de("Ich bin da eher skeptisch."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Diese Technik dürfte sich durchsetzen werden."), tr("cümlesi doğru mu?")], expect: truefalse("Diese Technik dürfte sich durchsetzen werden.", false, [tr("Kip fiilinden sonra tek bir mastar gelir; sondaki werden fazla:"), de("Diese Technik dürfte sich durchsetzen.")]) },
      { say: [tr("Son: 'Bu yaygınlaşmayacak.'")], expect: produce("Das wird sich nicht durchsetzen", [tr("Kesin tahmin werden ile; mastar sonda:"), de("Das wird sich nicht durchsetzen."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir teknolojinin geleceğini tartışacaksın: ne kadar eminsin, neye dayanıyorsun.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla yeni bir teknolojinin geleceğini tartışıyorsunuz. Neyin kesin, neyin olası, neyin sadece duyulmuş olduğunu ayır; kendi tahminini gerekçelendir ve nerede yanılabileceğini söyle.",
      partner: "her yeniliğe hemen inanan, heyecanlı bir tanıdık",
      opening: "In fünf Jahren fährt keiner mehr selbst, sagen sie. Glauben Sie das auch?",
      openingTr: "Beş yıl içinde kimse kendi arabasını sürmeyecekmiş diyorlar. Siz de buna inanıyor musunuz?",
      goal: "Kesin, olası ve duyulmuş ayrılmış; kendi tahmini gerekçelendirilmiş ve nerede yanılınabileceği söylenmiş olur.",
      minTurns: 8,
    },
  },
];
