import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 5 — Bilim ve teknoloji (041–050).
 *
 * Modülün omurgası ortaç sıfatları: Almanca yazı dilinin bir ilgi cümlesini
 * tek bir sıfata sıkıştırma alışkanlığı. "Filmde gösterilen görüntüler",
 * "yeni geliştirilen yöntem", "giderek artan eğilim" — Türkçe bunu ortaçla
 * zaten yapıyor, ama Almancada sıfat EKİ de gerekiyor ve o ek ismin cinsine,
 * hâline ve belirteciyle olan ilişkisine bağlı. Bu yüzden iki ders (041, 042)
 * doğrudan buna ayrıldı ve modül boyunca üç yerde daha çalıştırılıyor.
 *
 * İkinci hat yöntem dili: bir şeyin NASIL yapıldığını `indem` ile anlatmak.
 * Deney, arıza giderme ve süreç anlatımı hep bu bağlaçla kuruluyor.
 *
 * Sahneler bilimsel ama günlük: bir araştırma özeti, mutfak deneyi, çöken bir
 * program, veri gizliliği görüşmesi. B2 öğrencisi laboratuvarda değil, bu
 * konuların konuşulduğu masada oturuyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B05: Lesson[] = [
  {
    id: "de-b2-partizip-1",
    icon: "baby",
    level: "B2",
    course: "de",
    title: "Die lachenden Kinder",
    titleTr: "Partizip I sıfatı",
    summary: "Fiilden 'yapmakta olan' anlamında sıfat türetmeyi öğretir.",
    minutes: 12,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "die Innovation", tr: "inovasyon" },
      { de: "die Neuerung", tr: "yenilik" },
      { de: "die Verfügbarkeit", tr: "kullanılabilirlik" },
      { de: "wissenschaftlich", tr: "bilimsel" },
      { de: "vielfältig", tr: "çeşitli" },
      { de: "zeitgemäß", tr: "çağa uygun" },
      { de: "veraltet", tr: "eskimiş" },
      { de: "aufwendig", tr: "zahmetli" },
    ],
    patterns: [
      { de: "die steigenden Preise", tr: "Partizip I: artmakta olan" },
      { de: "die laufenden Kosten", tr: "süregelen giderler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: bilim ve teknoloji. Ama önce bu alanın dilini kuralım — ve o dilin en belirgin aracı fiilden sıfat yapmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural basit: mastarın sonuna bir d eklenir, sonra normal bir sıfat gibi çekilir. Anlamı 'yapmakta olan'. Zor kısım ek değil, ekin çekimi. Önce kelimeler.")] },
      word("İlk", { de: "die Innovation", tr: "inovasyon" }),
      word("İkinci", { de: "die Neuerung", tr: "yenilik" }),
      word("Üçüncü", { de: "die Verfügbarkeit", tr: "kullanılabilirlik" }, "Bir şeyin elde bulunup bulunmadığı."),
      word("Dördüncü", { de: "wissenschaftlich", tr: "bilimsel" }),
      word("Beşinci", { de: "vielfältig", tr: "çeşitli" }),
      word("Altıncı", { de: "zeitgemäß", tr: "çağa uygun" }),
      word("Yedinci", { de: "veraltet", tr: "eskimiş" }),
      word("Son", { de: "aufwendig", tr: "zahmetli" }),
      { say: [tr("Kalıbımız:"), de("die steigenden Preise"), tr("Yani 'artmakta olan fiyatlar'. Belirtili çoğulda sıfat -en ekini alıyor.")] },
      { say: [tr("Örnek:"), de("Die steigenden Preise beunruhigen viele."), tr("Tekrar edin:"), de("Die steigenden Preise beunruhigen viele")], expect: repeat("Die steigenden Preise beunruhigen viele") },
      { say: [tr("Sıra sende: 'Süregelen masraflar bütçeyi zorluyor.'")], expect: produce("Die laufenden Kosten belasten das Budget", [tr("Belirtili çoğulda ortaç -en ekini alır:"), de("Die laufenden Kosten belasten das Budget."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İkna edici bir yenilik bekleniyor.'")], expect: produce("Eine überzeugende Neuerung wird erwartet", [tr("Belirtisiz dişil tekilde ortaç -e ekini alır:"), de("Eine überzeugende Neuerung wird erwartet."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Oynayan çocuklar hiçbir şey fark etmedi.'")], expect: produce("Die spielenden Kinder haben nichts gemerkt", [tr("Aynı kural, bu kez insanlar için:"), de("Die spielenden Kinder haben nichts gemerkt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die steigende Preise beunruhigen viele."), tr("cümlesi doğru mu?")], expect: truefalse("Die steigende Preise beunruhigen viele.", false, [tr("Belirtili çoğulda sıfat -en ekini alır:"), de("Die steigenden Preise beunruhigen viele.")]) },
      { say: [tr("Son: 'Bu inovasyon bugün bile eskimiş.'")], expect: produce("Diese Innovation ist heute schon veraltet", [tr("Ortaç sıfat gibi yüklem yerinde duruyor:"), de("Diese Innovation ist heute schon veraltet."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir eğilimi tartışacaksın: ne artıyor, ne azalıyor, sen ne gözlemliyorsun.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla son yıllarda artan bir eğilimi konuşuyorsunuz (ekran süresi, kira, ulaşım maliyeti — hangisini seçersen). Ne arttığını, ne azaldığını ve kendi gözlemini anlat.",
      partner: "sayılara meraklı, örnek isteyen bir tanıdık",
      opening: "Mir fällt in letzter Zeit etwas auf: Alles wird teurer, aber niemand redet über die laufenden Kosten. Was beobachten Sie denn?",
      openingTr: "Son zamanlarda dikkatimi çeken bir şey var: Her şey pahalanıyor ama kimse süregelen giderlerden konuşmuyor. Siz ne gözlemliyorsunuz?",
      goal: "Artan ve azalan eğilimler örneklerle anlatılmış ve iki taraf ortak bir gözlemde buluşmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-partizip-2",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Das gelöste Problem",
    titleTr: "Partizip II sıfatı",
    summary: "Fiilden 'yapılmış olan' anlamında sıfat türetmeyi öğretir.",
    minutes: 12,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "das Verfahren", tr: "yöntem" },
      { de: "der Testlauf", tr: "deneme çalışması" },
      { de: "die Handhabung", tr: "kullanım" },
      { de: "aktualisieren", tr: "güncellemek" },
      { de: "ausführen", tr: "çalıştırmak" },
      { de: "wiederherstellen", tr: "geri yüklemek" },
      { de: "kompatibel", tr: "uyumlu" },
      { de: "standardmäßig", tr: "varsayılan olarak" },
    ],
    patterns: [
      { de: "das entwickelte Verfahren", tr: "Partizip II: geliştirilmiş" },
      { de: "die getestete Methode", tr: "test edilmiş yöntem" },
    ],
    lecture: [
      { say: [tr("Merhaba! Dün 'yapmakta olan' sıfatını kurduk. Bugün ikizi: 'yapılmış olan'. İkisi zıt yönlere bakıyor ve karıştırmak anlamı tersine çeviriyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu kez ortaç geçmiş biçimden geliyor. 'Geliştiren yöntem' başka, 'geliştirilen yöntem' başka; Almancada bu fark tek bir ortaçla söyleniyor. Önce kelimeler.")] },
      word("İlk", { de: "das Verfahren", tr: "yöntem" }),
      word("İkinci", { de: "der Testlauf", tr: "deneme çalışması" }),
      word("Üçüncü", { de: "die Handhabung", tr: "kullanım" }),
      word("Dördüncü", { de: "aktualisieren", tr: "güncellemek" }),
      word("Beşinci", { de: "ausführen", tr: "çalıştırmak" }),
      word("Altıncı", { de: "wiederherstellen", tr: "geri yüklemek" }),
      word("Yedinci", { de: "kompatibel", tr: "uyumlu" }),
      word("Son", { de: "standardmäßig", tr: "varsayılan olarak" }),
      { say: [tr("Kalıbımız:"), de("das entwickelte Verfahren"), tr("Yani 'geliştirilmiş olan yöntem'. Edilgen anlam ortacın içinde.")] },
      { say: [tr("Örnek:"), de("Das entwickelte Verfahren ist bereits im Testlauf."), tr("Tekrar edin:"), de("Das entwickelte Verfahren ist bereits im Testlauf")], expect: repeat("Das entwickelte Verfahren ist bereits im Testlauf") },
      { say: [tr("Sıra sende: 'Test edilen yöntem daha hızlı.'")], expect: produce("Die getestete Methode ist schneller", [tr("Belirtili dişil tekilde ortaç -e ekini alır:"), de("Die getestete Methode ist schneller."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Güncellenen veriler sistemde.'")], expect: produce("Die aktualisierten Daten stehen im System", [tr("Belirtili çoğulda -en eki:"), de("Die aktualisierten Daten stehen im System."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yeni geliştirilen program ücretsiz.'")], expect: produce("Das neu entwickelte Programm ist kostenlos", [tr("Zarf ortaçtan önce, ikisi birlikte ismin önünde:"), de("Das neu entwickelte Programm ist kostenlos."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das neu entwickelte Programm ist kostenlos."), tr("cümlesi doğru mu?")], expect: truefalse("Das neu entwickelte Programm ist kostenlos.", true, [tr("Doğru. Zarf ve ortaç ismin önünde sırayla duruyor ve ortaç nötr tekilde -e ekini almış.")]) },
      { say: [tr("Son bir soru: 'Bu uyumlu bir cihaz mı?'")], expect: produce("Ist das ein kompatibles Gerät", [tr("Belirtisiz nötr tekilde sıfat -es ekini alır:"), de("Ist das ein kompatibles Gerät?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada yeni bir yöntemi değerlendireceksin: nasıl geliştirildi, denendi mi, güvenilir mi.")] },
    ],
    roleplay: {
      scene: "İş yerinde yeni bir yöntem öneriliyor. Nasıl geliştirildiğini, denenip denenmediğini ve hangi sonuçların alındığını sor; sonra kendi değerlendirmeni söyle.",
      partner: "yöntemi savunan, ayrıntı verebilen bir proje sorumlusu",
      opening: "Das neu entwickelte Verfahren spart uns ein Drittel der Zeit. Wo sehen Sie das Problem?",
      openingTr: "Yeni geliştirilen yöntem bize zamanın üçte birini kazandırıyor. Sorunu nerede görüyorsunuz?",
      goal: "Yöntemin nasıl geliştirildiği ve denendiği öğrenilmiş, öğrencinin değerlendirmesi gerekçesiyle söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-ki-alltag",
    icon: "tech",
    level: "B2",
    course: "de",
    title: "KI im Alltag",
    titleTr: "Yapay zekâ sohbeti",
    summary: "Neyin otomatikleştirilebileceğini edilgen yerine geçen yapılarla tartışmayı öğretir.",
    minutes: 12,
    focusId: "Passiversatz",
    vocab: [
      { de: "automatisieren", tr: "otomatikleştirmek" },
      { de: "der Algorithmus", tr: "algoritma" },
      { de: "die Anwendung", tr: "uygulama" },
      { de: "der Entwickler", tr: "geliştirici" },
      { de: "die Rechenleistung", tr: "işlem gücü" },
      { de: "die Datenbank", tr: "veri tabanı" },
      { de: "der Roboter", tr: "robot" },
      { de: "programmieren", tr: "programlamak" },
    ],
    patterns: [
      { de: "… lässt sich automatisieren", tr: "otomatikleştirilebilir" },
      { de: "Es bleibt zu fragen, …", tr: "açık kalan soru" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün yapay zekâyı konuşacağız ve bu konunun dili edilgendir: neyin yapılabildiği konuşulur, kimin yaptığı değil. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de tartışmayı açık bırakan güzel bir kalıp var: 'sorulması gereken şu ki'. Cevap vermeden soruyu masaya koyar. Önce kelimeler.")] },
      word("İlk", { de: "automatisieren", tr: "otomatikleştirmek" }),
      word("İkinci", { de: "der Algorithmus", tr: "algoritma" }),
      word("Üçüncü", { de: "die Anwendung", tr: "uygulama" }),
      word("Dördüncü", { de: "der Entwickler", tr: "geliştirici" }),
      word("Beşinci", { de: "die Rechenleistung", tr: "işlem gücü" }),
      word("Altıncı", { de: "die Datenbank", tr: "veri tabanı" }),
      word("Yedinci", { de: "der Roboter", tr: "robot" }),
      word("Son", { de: "programmieren", tr: "programlamak" }),
      { say: [tr("Kalıbımız:"), de("… lässt sich automatisieren"), tr("Edilgen kurmadan aynı anlamı veriyor ve konuşma dilinde çok daha doğal.")] },
      { say: [tr("Örnek:"), de("Vieles lässt sich inzwischen automatisieren."), tr("Tekrar edin:"), de("Vieles lässt sich inzwischen automatisieren")], expect: repeat("Vieles lässt sich inzwischen automatisieren") },
      { say: [tr("Sıra sende: 'Bu adım otomatikleştirilebilir.'")], expect: produce("Dieser Schritt lässt sich automatisieren", [tr("lassen artı dönüşlü zamir; mastar sonda:"), de("Dieser Schritt lässt sich automatisieren."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi ortaç sıfatıyla: 'Yapay zekâyla oluşturulan metinler işaretlenmeli.'")], expect: produce("Von KI erstellte Texte sollten gekennzeichnet werden", [tr("Ortaç öbeği ismin önünde; sonda ortaç ve werden:"), de("Von KI erstellte Texte sollten gekennzeichnet werden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sorulması gereken şu: kim sorumlu?'")], expect: produce("Es bleibt zu fragen, wer verantwortlich ist", [tr("Sahte özne es; yan cümlede fiil sonda:"), de("Es bleibt zu fragen, wer verantwortlich ist."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dieser Schritt lässt sich automatisieren werden."), tr("cümlesi doğru mu?")], expect: truefalse("Dieser Schritt lässt sich automatisieren werden.", false, [tr("Bu yapı zaten edilgen anlamı taşır; sonda ayrıca werden bulunmaz:"), de("Dieser Schritt lässt sich automatisieren.")]) },
      { say: [tr("Son: 'Uygulama çok işlem gücü istiyor.'")], expect: produce("Die Anwendung braucht viel Rechenleistung", [tr("Düz bir cümle; nesne belirtme hâlinde:"), de("Die Anwendung braucht viel Rechenleistung."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada yapay zekânın işinde ne kadar yeri olduğunu tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşınla yapay zekânın işinizde ne kadar yer alması gerektiğini tartışıyorsunuz: ne otomatikleştirilebilir, ne otomatikleştirilmemeli, sorumluluk kimde kalır.",
      partner: "yapay zekâya hevesli, sınır tanımayan bir meslektaş",
      opening: "Ich lasse inzwischen fast alles vorschreiben — spart enorm Zeit. Wo würdest du die Grenze ziehen?",
      openingTr: "Artık neredeyse her şeyi ona yazdırıyorum — müthiş zaman kazandırıyor. Sen sınırı nereye çekerdin?",
      goal: "Otomatikleştirilebilecek ve edilmemesi gereken işler ayrılmış ve sorumluluğun kimde kalacağı konuşulmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-studie",
    icon: "school",
    level: "B2",
    course: "de",
    title: "Die neue Studie",
    titleTr: "Araştırma özetleme",
    summary: "Bir araştırmanın bulgularını isimleşmiş akademik dille aktarmayı öğretir.",
    minutes: 12,
    focusId: "Nominalisierung",
    vocab: [
      { de: "die Erkenntnis", tr: "bulgu" },
      { de: "die Meinungsumfrage", tr: "kamuoyu araştırması" },
      { de: "die Größenordnung", tr: "büyüklük mertebesi" },
      { de: "auswerten", tr: "çözümlemek" },
      { de: "ermitteln", tr: "tespit etmek" },
      { de: "signifikant", tr: "anlamlı" },
      { de: "schätzungsweise", tr: "tahminen" },
      { de: "vergleichsweise", tr: "görece" },
    ],
    patterns: [
      { de: "Die Untersuchung zeigt, dass …", tr: "bulguyu bildirir" },
      { de: "Die Erkenntnis lautet: …", tr: "bulguyu tek cümlede verir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir araştırmayı özetleyeceğiz. Akademik dilin işi kısaltmaktır ve kısaltma yöntemi hep aynı: fiili isme çevirmek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Verileri değerlendirirken' yerine 'değerlendirmede' denir. Bu, ilk modülde öğrendiğin yapının bilimsel hâli. Önce kelimeler.")] },
      word("İlk", { de: "die Erkenntnis", tr: "bulgu" }),
      word("İkinci", { de: "die Meinungsumfrage", tr: "kamuoyu araştırması" }),
      word("Üçüncü", { de: "die Größenordnung", tr: "büyüklük mertebesi" }, "Kesin sayı değil, kabaca hangi büyüklükte."),
      word("Dördüncü", { de: "auswerten", tr: "çözümlemek" }),
      word("Beşinci", { de: "ermitteln", tr: "tespit etmek" }),
      word("Altıncı", { de: "signifikant", tr: "anlamlı" }, "İstatistikte 'rastlantı olamayacak kadar belirgin'."),
      word("Yedinci", { de: "schätzungsweise", tr: "tahminen" }),
      word("Son", { de: "vergleichsweise", tr: "görece" }),
      { say: [tr("Kalıbımız:"), de("Bei der Auswertung …"), tr("Bir aşama, yan cümle kurmadan isim öbeğiyle söyleniyor.")] },
      { say: [tr("Örnek:"), de("Die Untersuchung zeigt einen deutlichen Zusammenhang."), tr("Tekrar edin:"), de("Die Untersuchung zeigt einen deutlichen Zusammenhang")], expect: repeat("Die Untersuchung zeigt einen deutlichen Zusammenhang") },
      { say: [tr("Sıra sende: 'Kamuoyu araştırmasında bir hata fark edildi.'")], expect: produce("Bei der Meinungsumfrage ist ein Fehler aufgefallen", [tr("Tümleç başta olduğu için fiil ikinci sırada:"), de("Bei der Meinungsumfrage ist ein Fehler aufgefallen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ortalamada katılımcılar altı saat uyuyor.'")], expect: produce("Im Durchschnitt schlafen die Teilnehmenden sechs Stunden", [tr("Kalıplaşmış ifade başta, fiil ikinci sırada:"), de("Im Durchschnitt schlafen die Teilnehmenden sechs Stunden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Fark anlamlı değildi.'")], expect: produce("Der Unterschied war nicht signifikant", [tr("Kısa bir hüküm; geçmiş zamanda:"), de("Der Unterschied war nicht signifikant."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Bei der Meinungsumfrage ein Fehler ist aufgefallen."), tr("cümlesi doğru mu?")], expect: truefalse("Bei der Meinungsumfrage ein Fehler ist aufgefallen.", false, [tr("Cümle bir tümleçle başlayınca çekimli fiil hemen ikinci sıraya gelir:"), de("Bei der Meinungsumfrage ist ein Fehler aufgefallen.")]) },
      { say: [tr("Son bir soru: 'Bu sonuç nasıl tespit edildi?'")], expect: produce("Wie wurde dieses Ergebnis ermittelt", [tr("Soru kelimesi başta, edilgen geçmiş; ortaç sonda:"), de("Wie wurde dieses Ergebnis ermittelt?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada okuduğun bir araştırmayı anlatacaksın: ne buldu, nasıl ölçtü, sen ne düşünüyorsun.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına okuduğun bir araştırmayı anlatıyorsun: ne buldu, kaç kişiyle yapıldı, sonucu ne kadar güvenilir ve sen ne düşünüyorsun.",
      partner: "araştırmalara şüpheyle bakan, yöntemi soran bir arkadaş",
      opening: "Studien sagen doch jedes Jahr etwas anderes. Wie viele Leute waren denn überhaupt dabei?",
      openingTr: "Araştırmalar her yıl başka bir şey söylüyor zaten. Kaç kişi katılmış ki bu araştırmaya?",
      goal: "Araştırmanın bulgusu, yöntemi ve örneklemi anlatılmış; ne kadar güvenilir olduğu konusunda ortak bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-experiment",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Das Küchenexperiment",
    titleTr: "Deney anlatımı",
    summary: "Bir şeyin nasıl yapıldığını indem bağlacıyla anlatmayı öğretir.",
    minutes: 12,
    focusId: "Nebensatz-indem",
    vocab: [
      { de: "das Messgerät", tr: "ölçüm aleti" },
      { de: "die Toleranz", tr: "tolerans" },
      { de: "die Fehlerquote", tr: "hata oranı" },
      { de: "das Molekül", tr: "molekül" },
      { de: "die Zelle", tr: "hücre" },
      { de: "vermessen", tr: "ölçüm yapmak" },
      { de: "betrachten", tr: "incelemek" },
      { de: "erfassen", tr: "kaydetmek" },
    ],
    patterns: [
      { de: "…, indem man …", tr: "yöntem: … yaparak" },
      { de: "Dadurch, dass …", tr: "sebep-yöntem bağı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir yöntem anlatacağız: bir şey NASIL yapılıyor. Almancada bunun kendi bağlacı var ve Türkçedeki '-arak' ekine karşılık geliyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dikkat: bu bir yan cümle bağlacı, yani fiil sona gidiyor. Türkçe konuşan burada çok kayar çünkü '-arak' ekinde böyle bir sıra yok. Önce kelimeler.")] },
      word("İlk", { de: "das Messgerät", tr: "ölçüm aleti" }),
      word("İkinci", { de: "vermessen", tr: "ölçüm yapmak" }),
      word("Üçüncü", { de: "die Toleranz", tr: "tolerans" }, "Ölçümde kabul edilen sapma payı."),
      word("Dördüncü", { de: "die Fehlerquote", tr: "hata oranı" }),
      word("Beşinci", { de: "betrachten", tr: "incelemek" }),
      word("Altıncı", { de: "erfassen", tr: "kaydetmek" }),
      word("Yedinci", { de: "das Molekül", tr: "molekül" }),
      word("Son", { de: "die Zelle", tr: "hücre" }),
      { say: [tr("Kalıbımız:"), de("…, indem man …"), tr("Yan cümle olduğu için çekimli fiil en sonda durur.")] },
      { say: [tr("Örnek:"), de("Man misst die Temperatur, indem man das Messgerät eintaucht."), tr("Tekrar edin:"), de("Man misst die Temperatur, indem man das Messgerät eintaucht")], expect: repeat("Man misst die Temperatur, indem man das Messgerät eintaucht") },
      { say: [tr("Sıra sende: 'Sonucu, koşulları değiştirerek kontrol edersin.'")], expect: produce("Man prüft das Ergebnis, indem man die Bedingungen ändert", [tr("Yan cümlede fiil en sonda:"), de("Man prüft das Ergebnis, indem man die Bedingungen ändert."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Deney tam olarak kaydedilmeli.'")], expect: produce("Der Versuch muss genau erfasst werden", [tr("Kipli edilgen; sonda ortaç ve werden:"), de("Der Versuch muss genau erfasst werden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sıcaklık her beş dakikada ölçülüyor.'")], expect: produce("Die Temperatur wird alle fünf Minuten gemessen", [tr("Şimdiki zaman edilgeni; ortaç sonda:"), de("Die Temperatur wird alle fünf Minuten gemessen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Man prüft das Ergebnis, indem man ändert die Bedingungen."), tr("cümlesi doğru mu?")], expect: truefalse("Man prüft das Ergebnis, indem man ändert die Bedingungen.", false, [tr("Bu bir yan cümle bağlacıdır; çekimli fiil en sona gider:"), de("Man prüft das Ergebnis, indem man die Bedingungen ändert.")]) },
      { say: [tr("Son: 'Hata oranı çok düşüktü.'")], expect: produce("Die Fehlerquote war sehr niedrig", [tr("Kısa bir hüküm cümlesi:"), de("Die Fehlerquote war sehr niedrig."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada birine basit bir deneyi anlatacaksın: nasıl yapılıyor, ne ölçülüyor, sonuç ne.")] },
    ],
    roleplay: {
      scene: "Birine evde yapılabilecek basit bir deneyi anlatıyorsun: ne gerekiyor, nasıl yapılıyor, ne ölçülüyor ve sonuç neden şaşırtıcı. Her adımı yöntem bağlacıyla anlat.",
      partner: "meraklı ama her adımı sorgulayan bir dinleyici",
      opening: "Ein Experiment in der Küche? Gut — aber sagen Sie mir zuerst: Was genau will man damit herausfinden?",
      openingTr: "Mutfakta deney mi? Peki — ama önce şunu söyleyin: Bununla tam olarak ne bulunmak isteniyor?",
      goal: "Deneyin amacı, adımları ve sonucu anlatılmış; dinleyen kendi cümlesiyle özetleyebilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-datenschutz",
    icon: "law",
    level: "B2",
    course: "de",
    title: "Meine Daten gehören mir",
    titleTr: "Veri gizliliği",
    summary: "Veri haklarını kipli edilgenle savunmayı öğretir.",
    minutes: 12,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "der Datenschutz", tr: "veri koruma" },
      { de: "die Datensicherheit", tr: "veri güvenliği" },
      { de: "der Datenmissbrauch", tr: "veri kötüye kullanımı" },
      { de: "die Berechtigung", tr: "yetki" },
      { de: "das Nutzerkonto", tr: "kullanıcı hesabı" },
      { de: "der Zugriff", tr: "erişim" },
      { de: "verschlüsseln", tr: "şifrelemek" },
      { de: "unbefugt", tr: "yetkisiz" },
    ],
    patterns: [
      { de: "dürfen nicht … werden", tr: "yasak: verilemez" },
      { de: "Dem können Sie widersprechen.", tr: "itiraz hakkı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kendi verilerini savunacaksın. Bu alanın dili kipli edilgendir çünkü kural kimin ne yapacağını değil, neyin yapılamayacağını söyler. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de itiraz fiili var ve o fiil yönelme hâli istiyor — bunu kaçırmak cümleyi bozar. Önce kelimeler.")] },
      word("İlk", { de: "der Datenschutz", tr: "veri koruma" }),
      word("İkinci", { de: "die Datensicherheit", tr: "veri güvenliği" }),
      word("Üçüncü", { de: "der Datenmissbrauch", tr: "veri kötüye kullanımı" }),
      word("Dördüncü", { de: "die Berechtigung", tr: "yetki" }),
      word("Beşinci", { de: "das Nutzerkonto", tr: "kullanıcı hesabı" }),
      word("Altıncı", { de: "der Zugriff", tr: "erişim" }),
      word("Yedinci", { de: "verschlüsseln", tr: "şifrelemek" }),
      word("Son", { de: "unbefugt", tr: "yetkisiz" }, "Yetkisi olmadan; resmî metinlerin sık sözcüğü."),
      { say: [tr("Kalıbımız:"), de("dürfen nicht … werden"), tr("Yasak bildiren kipli edilgen; sonda ortaç ve werden.")] },
      { say: [tr("Örnek:"), de("Ohne Berechtigung dürfen die Daten nicht abgerufen werden."), tr("Tekrar edin:"), de("Ohne Berechtigung dürfen die Daten nicht abgerufen werden")], expect: repeat("Ohne Berechtigung dürfen die Daten nicht abgerufen werden") },
      { say: [tr("Sıra sende: 'Veriler yalnızca rıza ile kaydedilebilir.'")], expect: produce("Daten dürfen nur mit Einwilligung gespeichert werden", [tr("Kip fiili ikinci sırada; sonda ortaç ve werden:"), de("Daten dürfen nur mit Einwilligung gespeichert werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Buna itiraz edebilirsiniz.'")], expect: produce("Dem können Sie widersprechen", [tr("Bu fiil yönelme hâli ister; tümleç öne alınmış:"), de("Dem können Sie widersprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Hassas veriler şifrelenmeli.'")], expect: produce("Sensible Daten müssen verschlüsselt werden", [tr("Zorunluluk müssen ile; sonda ortaç ve werden:"), de("Sensible Daten müssen verschlüsselt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ohne Berechtigung dürfen die Daten nicht abgerufen werden."), tr("cümlesi doğru mu?")], expect: truefalse("Ohne Berechtigung dürfen die Daten nicht abgerufen werden.", true, [tr("Doğru. Cümle tümleçle başladığı için kip fiili ikinci sırada; sonda önce ortaç, sonra werden geliyor.")]) },
      { say: [tr("Son bir soru: 'Verilerim ne kadar süre saklanıyor?'")], expect: produce("Wie lange werden meine Daten gespeichert", [tr("Soru öbeği başta, çekimli fiil ikinci sırada:"), de("Wie lange werden meine Daten gespeichert?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir hizmet sağlayıcıyla veri kullanımını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir hizmet sağlayıcının müşteri temsilcisiyle verilerinin nasıl kullanıldığını konuşuyorsun: ne kaydediliyor, kime veriliyor, ne kadar saklanıyor ve neye itiraz edebilirsin.",
      partner: "kuralları bilen ama ayrıntıya girmek istemeyen bir müşteri temsilcisi",
      opening: "Sie haben eine Frage zum Datenschutz? Grundsätzlich halten wir uns natürlich an alle Vorgaben. Was genau möchten Sie wissen?",
      openingTr: "Veri koruma hakkında bir sorunuz mu var? Prensipte elbette bütün kurallara uyuyoruz. Tam olarak neyi bilmek istiyorsunuz?",
      goal: "Hangi verilerin kaydedildiği, kimlerle paylaşıldığı ve ne kadar saklandığı öğrenilmiş; bir itiraz iletilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-weltraum",
    icon: "star",
    level: "B2",
    course: "de",
    title: "Die bedrohte Vielfalt",
    titleTr: "İklim ve doğa",
    summary: "Ortaç sıfatlarıyla tehdit altındaki doğayı anlatmayı öğretir.",
    minutes: 12,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "der Klimawandel", tr: "iklim değişikliği" },
      { de: "das Ökosystem", tr: "ekosistem" },
      { de: "die Artenvielfalt", tr: "tür çeşitliliği" },
      { de: "der Lebensraum", tr: "yaşam alanı" },
      { de: "das Aussterben", tr: "yok oluş" },
      { de: "die Dürre", tr: "kuraklık" },
      { de: "die Nachhaltigkeit", tr: "sürdürülebilirlik" },
      { de: "bedrohen", tr: "tehdit etmek" },
    ],
    patterns: [
      { de: "die bedrohten Arten", tr: "tehdit altındaki türler" },
      { de: "der stark veränderte Lebensraum", tr: "ağır biçimde değişmiş yaşam alanı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün gökyüzüne bakıyoruz. Bu konunun dili ortaç sıfatlarıyla dolu: planlanan görev, insanlı yolculuk, yeni keşfedilen gezegen. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de yer bildirirken dikkat edeceğin bir nokta var: bir şeyin nerede OLDUĞUNU söylerken hâl değişir. Bunu sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "der Klimawandel", tr: "iklim değişikliği" }),
      word("İkinci", { de: "das Ökosystem", tr: "ekosistem" }),
      word("Üçüncü", { de: "die Artenvielfalt", tr: "tür çeşitliliği" }),
      word("Dördüncü", { de: "der Lebensraum", tr: "yaşam alanı" }),
      word("Beşinci", { de: "das Aussterben", tr: "yok oluş" }, "Bir türün tamamen kaybolması."),
      word("Altıncı", { de: "die Dürre", tr: "kuraklık" }),
      word("Yedinci", { de: "die Nachhaltigkeit", tr: "sürdürülebilirlik" }),
      word("Son", { de: "bedrohen", tr: "tehdit etmek" }),
      { say: [tr("Kalıbımız:"), de("die bedrohten Arten"), tr("Ortaç ismin önünde ve sıfat ekini almış durumda.")] },
      { say: [tr("Örnek:"), de("Die bedrohten Arten brauchen Schutz."), tr("Tekrar edin:"), de("Die bedrohten Arten brauchen Schutz")], expect: repeat("Die bedrohten Arten brauchen Schutz") },
      { say: [tr("Sıra sende: 'Tehdit altındaki tür çeşitliliği korunmaya muhtaç.'")], expect: produce("Die bedrohte Artenvielfalt braucht Schutz", [tr("Belirtili dişil tekilde ortaç -e ekini alır:"), de("Die bedrohte Artenvielfalt braucht Schutz."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ağır biçimde değişen yaşam alanı asıl sorun.'")], expect: produce("Der stark veränderte Lebensraum ist das Problem", [tr("Zarf ve ortaç birlikte ismin önünde:"), de("Der stark veränderte Lebensraum ist das Problem."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ekosistem dengede.'")], expect: produce("Das Ökosystem ist im Gleichgewicht", [tr("Yer bildirirken bu edat yönelme hâli ister:"), de("Das Ökosystem ist im Gleichgewicht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Ökosystem ist in das Gleichgewicht."), tr("cümlesi doğru mu?")], expect: truefalse("Das Ökosystem ist in das Gleichgewicht.", false, [tr("Hareket değil konum bildiriliyor, o yüzden yönelme hâli gerekir:"), de("Das Ökosystem ist im Gleichgewicht.")]) },
      { say: [tr("Son bir soru: 'Sürdürülebilirlik senin için ne demek?'")], expect: produce("Was bedeutet Nachhaltigkeit für dich", [tr("Soru kelimesi başta, fiil ikinci sırada:"), de("Was bedeutet Nachhaltigkeit für dich?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada iklim önlemlerinin ne kadar ileri gitmesi gerektiğini tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla iklim önlemlerinin günlük hayata ne kadar karışması gerektiğini tartışıyorsunuz. Görüşünü gerekçelendir, karşı tarafın itirazına karşılık ver ve ortak bir noktada buluşun.",
      partner: "önlemleri abartılı bulan, ama doğayı da önemseyen bir arkadaş",
      opening: "Verbote für alles — und der bedrohte Wald wächst davon auch nicht schneller. Findest du das wirklich richtig?",
      openingTr: "Her şeye yasak — tehdit altındaki orman bundan daha hızlı büyümüyor ki. Bunu gerçekten doğru buluyor musun?",
      goal: "İki taraf da görüşünü gerekçelendirmiş, itirazlara karşılık verilmiş ve ortak bir noktada buluşulmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-medizin-fortschritt",
    icon: "doctor",
    level: "B2",
    course: "de",
    title: "Der Durchbruch",
    titleTr: "Tıpta gelişme",
    summary: "Tıbbi gelişmeleri edilgen geçmişle aktarmayı öğretir.",
    minutes: 12,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "der Durchbruch", tr: "atılım" },
      { de: "das Arzneimittel", tr: "ilaç" },
      { de: "der Wirkstoff", tr: "etken madde" },
      { de: "die Dosierung", tr: "dozaj" },
      { de: "die Nebenwirkung", tr: "yan etki" },
      { de: "die Früherkennung", tr: "erken teşhis" },
      { de: "zulassen", tr: "ruhsatlandırmak" },
      { de: "lindern", tr: "hafifletmek" },
    ],
    patterns: [
      { de: "ist … erprobt worden", tr: "denenmiş oldu" },
      { de: "sind … untersucht worden", tr: "çoğul: incelendiler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün tıptaki bir gelişmeyi aktaracağız. Bu tür haberlerde her cümle edilgen geçmiştir çünkü önemli olan kimin yaptığı değil, neyin yapılmış olduğu. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tek dikkat noktası yardımcı fiilin tekil mi çoğul mu olduğu. Kolay görünüyor ama hızlı konuşurken en çok orada kayılıyor. Önce kelimeler.")] },
      word("İlk", { de: "der Durchbruch", tr: "atılım" }),
      word("İkinci", { de: "das Arzneimittel", tr: "ilaç" }, "Resmî dilde Medikament yerine bu geçer."),
      word("Üçüncü", { de: "der Wirkstoff", tr: "etken madde" }),
      word("Dördüncü", { de: "die Dosierung", tr: "dozaj" }),
      word("Beşinci", { de: "die Nebenwirkung", tr: "yan etki" }),
      word("Altıncı", { de: "die Früherkennung", tr: "erken teşhis" }),
      word("Yedinci", { de: "zulassen", tr: "ruhsatlandırmak" }),
      word("Son", { de: "lindern", tr: "hafifletmek" }, "İyileştirmez ama ağrıyı azaltır."),
      { say: [tr("Kalıbımız:"), de("ist … erprobt worden"), tr("Çoğulda sind. Kısalmış biçim her zaman en sonda.")] },
      { say: [tr("Örnek:"), de("Der Wirkstoff ist zehn Jahre lang getestet worden."), tr("Tekrar edin:"), de("Der Wirkstoff ist zehn Jahre lang getestet worden")], expect: repeat("Der Wirkstoff ist zehn Jahre lang getestet worden") },
      { say: [tr("Sıra sende: 'İlaç geçen yıl ruhsatlandırıldı.'")], expect: produce("Das Medikament ist letztes Jahr zugelassen worden", [tr("Tekil özne ist alır; ayrılabilen fiilin ortacı:"), de("Das Medikament ist letztes Jahr zugelassen worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi çoğulla: 'Yan etkiler defalarca incelendi.'")], expect: produce("Die Nebenwirkungen sind mehrfach untersucht worden", [tr("Çoğul özne sind ister:"), de("Die Nebenwirkungen sind mehrfach untersucht worden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Şikâyetler artık hafifletilebiliyor.'")], expect: produce("Die Beschwerden lassen sich inzwischen lindern", [tr("Edilgen yerine geçen yapı; mastar sonda:"), de("Die Beschwerden lassen sich inzwischen lindern."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Nebenwirkungen ist mehrfach untersucht worden."), tr("cümlesi doğru mu?")], expect: truefalse("Die Nebenwirkungen ist mehrfach untersucht worden.", false, [tr("Özne çoğul olduğu için yardımcı fiil de çoğul olur:"), de("Die Nebenwirkungen sind mehrfach untersucht worden.")]) },
      { say: [tr("Son: 'Bu birçok insan için bir atılım.'")], expect: produce("Das ist ein Durchbruch für viele Menschen", [tr("Belirtisiz eril tekil; edat belirtme hâli ister:"), de("Das ist ein Durchbruch für viele Menschen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada duyduğun bir tıbbi gelişmeyi anlatacaksın: ne bulundu, nasıl denendi, ne anlama geliyor.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığına duyduğun tıbbi bir gelişmeyi anlatıyorsun: ne bulundu, nasıl ve ne kadar denendi, kimler için ne anlama geliyor ve neye dikkat etmek gerekiyor.",
      partner: "umutlanan ama abartıya karşı temkinli bir tanıdık",
      opening: "Ich habe davon gehört — angeblich ist alles schon getestet worden. Stimmt das wirklich?",
      openingTr: "Duydum bunu — güya her şey çoktan test edilmiş. Bu gerçekten doğru mu?",
      goal: "Gelişmenin ne olduğu, nasıl denendiği ve kimler için ne anlama geldiği anlatılmış; abartıya karşı bir uyarı yapılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-technikfrust",
    icon: "tech",
    level: "B2",
    course: "de",
    title: "Warum geht das nicht?",
    titleTr: "Teknoloji hayal kırıklığı",
    summary: "Arızayı tarif etmeyi ve çözümü yöntem bağlacıyla anlatmayı öğretir.",
    minutes: 12,
    focusId: "Nebensatz-indem",
    vocab: [
      { de: "abstürzen", tr: "çökmek (program)" },
      { de: "das Endgerät", tr: "uç cihaz" },
      { de: "das Ladegerät", tr: "şarj cihazı" },
      { de: "die Stromversorgung", tr: "elektrik beslemesi" },
      { de: "der Virenschutz", tr: "virüs koruması" },
      { de: "freischalten", tr: "etkinleştirmek" },
      { de: "blockieren", tr: "engellemek" },
      { de: "kabellos", tr: "kablosuz" },
    ],
    patterns: [
      { de: "Man löst es, indem man …", tr: "çözümü yöntemle söyler" },
      { de: "Das nervt.", tr: "kısa şikâyet" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün herkesin bildiği bir duygu: teknoloji çalışmıyor. İyi haber, şikâyetin de çözümün de hazır kalıpları var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Çözüm cümlesi yine yöntem bağlacıyla kuruluyor — 'yeniden başlatarak çözersin'. Bu ders o yapının günlük hâli. Önce kelimeler.")] },
      word("İlk", { de: "abstürzen", tr: "çökmek (program)" }),
      word("İkinci", { de: "das Endgerät", tr: "uç cihaz" }, "Telefon, tablet, bilgisayar için ortak resmî sözcük."),
      word("Üçüncü", { de: "das Ladegerät", tr: "şarj cihazı" }),
      word("Dördüncü", { de: "die Stromversorgung", tr: "elektrik beslemesi" }),
      word("Beşinci", { de: "der Virenschutz", tr: "virüs koruması" }),
      word("Altıncı", { de: "freischalten", tr: "etkinleştirmek" }),
      word("Yedinci", { de: "blockieren", tr: "engellemek" }),
      word("Son", { de: "kabellos", tr: "kablosuz" }),
      { say: [tr("Kalıbımız:"), de("Man löst es, indem man …"), tr("Yan cümlede fiil sonda; bu kuralı bu modülde üçüncü kez görüyorsun.")] },
      { say: [tr("Örnek:"), de("Man löst es meistens, indem man das Gerät neu startet."), tr("Tekrar edin:"), de("Man löst es meistens, indem man das Gerät neu startet")], expect: repeat("Man löst es meistens, indem man das Gerät neu startet") },
      { say: [tr("Sıra sende: 'Program yine çöktü.'")], expect: produce("Das Programm ist schon wieder abgestürzt", [tr("Bu fiil sein ile çekilir; ortaç sonda:"), de("Das Programm ist schon wieder abgestürzt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ekran donuyor.'")], expect: produce("Der Bildschirm friert ein", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Der Bildschirm friert ein."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Elektrik beslemesi kesildi.'")], expect: produce("Die Stromversorgung ist unterbrochen", [tr("Durum bildiren edilgen; ortaç sonda:"), de("Die Stromversorgung ist unterbrochen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Man löst es meistens, indem man das Gerät neu startet."), tr("cümlesi doğru mu?")], expect: truefalse("Man löst es meistens, indem man das Gerät neu startet.", true, [tr("Doğru. Yöntem bağlacından sonra çekimli fiil yan cümlenin sonunda duruyor.")]) },
      { say: [tr("Son: 'Bu beni gerçekten sinir ediyor.'")], expect: produce("Das nervt mich wirklich", [tr("Kısa ve günlük bir şikâyet:"), de("Das nervt mich wirklich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşından teknik yardım isteyeceksin: sorunu tarif et, denediklerini söyle ve çözümü öğren.")] },
    ],
    roleplay: {
      scene: "Bilgisayarın sürekli donuyor ve teknikten anlayan bir arkadaşından yardım istiyorsun. Sorunu tarif et, ne zaman olduğunu söyle, ne denediğini anlat ve çözümü kendi cümlenle tekrarla.",
      partner: "sabırlı ama önce hep 'yeniden başlattın mı' diye soran bir arkadaş",
      opening: "Warte, langsam. Wann friert er ein — immer, oder nur bei bestimmten Programmen?",
      openingTr: "Dur, yavaş. Ne zaman donuyor — hep mi, yoksa sadece belli programlarda mı?",
      goal: "Sorun tarif edilmiş, denenenler söylenmiş ve çözüm öğrenilip kendi cümlesiyle tekrarlanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-zukunftstechnologien",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Morgen schon Realität?",
    titleTr: "Gelecek teknolojileri",
    summary: "Gelecek tahminlerini emin olma derecesine göre söylemeyi öğretir.",
    minutes: 12,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "sich durchsetzen", tr: "yaygınlaşmak" },
      { de: "der Prototyp", tr: "prototip" },
      { de: "der Sensor", tr: "sensör" },
      { de: "die Fernsteuerung", tr: "uzaktan kontrol" },
      { de: "der Halbleiter", tr: "yarı iletken" },
      { de: "die Elektromobilität", tr: "elektrikli ulaşım" },
      { de: "die Ladestation", tr: "şarj istasyonu" },
      { de: "serienreif", tr: "seri üretime hazır" },
    ],
    patterns: [
      { de: "… dürfte sich durchsetzen", tr: "temkinli tahmin" },
      { de: "Es bleibt abzuwarten, …", tr: "cevabı açık bırakır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve konusu gelecek. Gelecek hakkında konuşurken Almanca ne kadar emin olduğunu fiille gösterir — kesin, olası ya da sadece duyulmuş. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("dürfte: büyük ihtimalle. soll: öyle diyorlar. wird: kesin. Üçünü doğru seçmek, tahminini savunulabilir kılar. Önce kelimeler.")] },
      word("İlk", { de: "sich durchsetzen", tr: "yaygınlaşmak" }),
      word("İkinci", { de: "der Prototyp", tr: "prototip" }),
      word("Üçüncü", { de: "serienreif", tr: "seri üretime hazır" }, "Prototipten sonraki aşama: fabrikada basılabilir."),
      word("Dördüncü", { de: "der Sensor", tr: "sensör" }),
      word("Beşinci", { de: "die Fernsteuerung", tr: "uzaktan kontrol" }),
      word("Altıncı", { de: "der Halbleiter", tr: "yarı iletken" }),
      word("Yedinci", { de: "die Elektromobilität", tr: "elektrikli ulaşım" }),
      word("Son", { de: "die Ladestation", tr: "şarj istasyonu" }),
      { say: [tr("Kalıbımız:"), de("… dürfte sich durchsetzen"), tr("Yani 'büyük ihtimalle yaygınlaşır'. Kesin konuşmadan tahmin etmek.")] },
      { say: [tr("Örnek:"), de("Diese Technik dürfte sich durchsetzen."), tr("Tekrar edin:"), de("Diese Technik dürfte sich durchsetzen")], expect: repeat("Diese Technik dürfte sich durchsetzen") },
      { say: [tr("Sıra sende: 'Seri üretime hazır olduğu söyleniyor.'")], expect: produce("Sie soll serienreif sein", [tr("Duyulan bilgi sollen ile; mastar sonda:"), de("Sie soll serienreif sein."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Prototipin ne zaman biteceğini göreceğiz.'")], expect: produce("Es bleibt abzuwarten, wann der Prototyp fertig wird", [tr("Sahte özne es; ayrılabilen fiilde zu ortaya girer:"), de("Es bleibt abzuwarten, wann der Prototyp fertig wird."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ben burada daha çok elektrikli ulaşımı önde görüyorum.'")], expect: produce("Ich sehe da eher die Elektromobilität vorn", [tr("Kısa ve doğal bir görüş cümlesi:"), de("Ich sehe da eher die Elektromobilität vorn."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Diese Technik dürfte sich durchsetzen werden."), tr("cümlesi doğru mu?")], expect: truefalse("Diese Technik dürfte sich durchsetzen werden.", false, [tr("Kip fiilinden sonra tek bir mastar gelir; sondaki werden fazla:"), de("Diese Technik dürfte sich durchsetzen.")]) },
      { say: [tr("Son: 'Bu yaygınlaşmayacak.'")], expect: produce("Das wird sich nicht durchsetzen", [tr("Kesin tahmin werden ile; mastar sonda:"), de("Das wird sich nicht durchsetzen."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir teknolojinin geleceğini tartışacaksın: ne kadar eminsin, neye dayanıyorsun.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla yeni bir teknolojinin geleceğini tartışıyorsunuz. Neyin kesin, neyin olası, neyin sadece duyulmuş olduğunu ayır; kendi tahminini gerekçelendir ve nerede yanılabileceğini söyle.",
      partner: "her yeniliğe hemen inanan, heyecanlı bir tanıdık",
      opening: "In fünf Jahren fährt keiner mehr selbst, sagen sie. Glauben Sie das auch?",
      openingTr: "Beş yıl içinde kimse kendi arabasını sürmeyecekmiş diyorlar. Siz de buna inanıyor musunuz?",
      goal: "Kesin, olası ve duyulmuş ayrılmış; kendi tahmini gerekçelendirilmiş ve nerede yanılınabileceği söylenmiş olur.",
      minTurns: 8,
    },
  },
];
