import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 9 — İnsan ilişkileri ve psikoloji (081–090).
 *
 * Modülün dilbilgisel yeniliği tek: `als ob` ve dilek kipi. Bu yapı Almancada
 * GERÇEK OLMAYANI işaretliyor — "sanki hiçbir şey olmamış gibi davranıyor"
 * cümlesindeki 'gibi'. Türkçe bunu bir edatla geçiştirir; Almanca fiili
 * değiştirir ve o değişiklik, konuşanın söylenene inanmadığını gösterir.
 * İç dünyayı anlatırken bundan kaçış yok: duygular çoğu zaman olguyla değil
 * olgunun nasıl HİSSETTİRDİĞİYLE anlatılıyor.
 *
 * İkinci hat modülün ikinci yarısında: alışkanlık, motivasyon ve değişim
 * derslerinde yöntem bağlacı geri dönüyor — çünkü psikolojide asıl soru
 * "ne" değil "nasıl": küçük başlayarak, tetikleyiciyi tanıyarak, bırakmayı
 * öğrenerek.
 *
 * Sahneler kişisel ama sömürücü değil: her rol yapma bir sonuca bağlanıyor
 * (bir sınır, bir söz, bir sonraki adım) — konuşma teşhis koymuyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B09: Lesson[] = [
  {
    id: "de-b2-als-ob",
    icon: "feelings",
    level: "B2",
    course: "de",
    title: "Als ob nichts wäre",
    titleTr: "Sanki kipi",
    summary: "Gerçek olmayan benzetmeleri als ob ile kurmayı öğretir.",
    minutes: 11,
    focusId: "Als-ob",
    vocab: [
      { de: "vortäuschen", tr: "numara yapmak" },
      { de: "gleichgültig", tr: "kayıtsız" },
      { de: "sich verstellen", tr: "rol yapmak" },
      { de: "der Anschein", tr: "görünüş" },
      { de: "spüren", tr: "hissetmek" },
    ],
    patterns: [
      { de: "Er tut so, als ob … wäre.", tr: "sanki: gerçek değil" },
      { de: "Als wäre nichts passiert.", tr: "kısa biçim" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: insan ilişkileri. İlk ders küçük ama çok işlevsel bir yapı — 'sanki'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şu: bu bağlaçtan sonra fiil dilek kipine girer, çünkü söylenen gerçek DEĞİL. Türkçede 'gibi' der geçeriz; Almanca bunu fiilde işaretler. Önce kelimeler.")] },
      word("İlk", { de: "vortäuschen", tr: "numara yapmak" }),
      word("İkinci", { de: "gleichgültig", tr: "kayıtsız" }),
      word("Üçüncü", { de: "sich verstellen", tr: "rol yapmak" }),
      word("Dördüncü", { de: "der Anschein", tr: "görünüş" }),
      word("Son", { de: "spüren", tr: "hissetmek" }),
      { say: [tr("Kalıbımız:"), de("Er tut so, als ob nichts passiert wäre."), tr("Bağlaçtan sonra fiil sona gidiyor ve dilek kipinde.")] },
      { say: [tr("Tekrar edin:"), de("Er tut so, als ob nichts passiert wäre")], expect: repeat("Er tut so, als ob nichts passiert wäre") },
      { say: [tr("Sıra sende, kısa biçimle: 'Sanki hiçbir şey olmamış gibi.'")], expect: produce("Als wäre nichts passiert", [tr("Kısa biçimde bağlaç düşer ve fiil hemen başa geçer:"), de("Als wäre nichts passiert."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bana kayıtsızmış gibi geliyor.'")], expect: produce("Es kommt mir vor, als ob es ihm gleichgültig wäre", [tr("Kalıplaşmış giriş, sonra dilek kipiyle benzetme:"), de("Es kommt mir vor, als ob es ihm gleichgültig wäre."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bir şeyi gizlediğini hissediyorum.'")], expect: produce("Ich spüre, dass er etwas vortäuscht", [tr("Yan cümlede fiil sonda; burada gerçek bir iddia olduğu için düz kip:"), de("Ich spüre, dass er etwas vortäuscht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Er tut so, als ob nichts passiert ist."), tr("cümlesi doğru mu?")], expect: truefalse("Er tut so, als ob nichts passiert ist.", false, [tr("Bu bağlaçtan sonra dilek kipi gelir, çünkü söylenen gerçek değildir:"), de("Er tut so, als ob nichts passiert wäre.")]) },
      { say: [tr("Son: 'Rol yapmak zorunda hissediyor.'")], expect: produce("Er fühlt sich gezwungen, sich zu verstellen", [tr("Mastar öbeğinde dönüşlü zamir ve zu:"), de("Er fühlt sich gezwungen, sich zu verstellen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla, bir tanıdığınızın davranışını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla ortak bir tanıdığınızın son zamanlardaki davranışını konuşuyorsunuz: nasıl davranıyor, sana nasıl geliyor, gerçekte ne oluyor olabilir ve ne yapmalısınız.",
      partner: "endişeli ama acele yorum yapmak istemeyen bir arkadaş",
      opening: "Er tut, als wäre alles in Ordnung — aber irgendetwas stimmt nicht. Merkst du das auch?",
      openingTr: "Sanki her şey yolundaymış gibi davranıyor — ama bir şey ters. Sen de fark ediyor musun?",
      goal: "Gözlemler paylaşılmış, aceleci yorumdan kaçınılmış ve ne yapılacağı konusunda somut bir adım kararlaşmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-vermutungen",
    icon: "question",
    level: "B2",
    course: "de",
    title: "Das dürfte stimmen",
    titleTr: "Tahmin dili",
    summary: "Emin olma derecesini dürfte, müsste ve könnte ile ayırmayı öğretir.",
    minutes: 11,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "die Vermutung", tr: "tahmin" },
      { de: "vermutlich", tr: "muhtemelen" },
      { de: "ausschließen", tr: "olasılık dışı bırakmak" },
      { de: "die Gewissheit", tr: "kesinlik" },
      { de: "zweifeln", tr: "şüphe etmek" },
    ],
    patterns: [
      { de: "dürfte / müsste / könnte", tr: "emin olma dereceleri" },
      { de: "Das schließe ich nicht aus.", tr: "olasılığı açık bırakır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün üç kip fiiliyle üç ayrı emin olma derecesi kuracağız. Türkçede hepsi 'olabilir' olur; Almancada arada ciddi fark var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("dürfte: büyük ihtimalle. müsste: mantıken öyle olmalı. könnte: sadece mümkün. Yanlış seçim seni ya fazla emin ya fazla kararsız gösterir. Önce kelimeler.")] },
      word("İlk", { de: "die Vermutung", tr: "tahmin" }),
      word("İkinci", { de: "vermutlich", tr: "muhtemelen" }),
      word("Üçüncü", { de: "ausschließen", tr: "olasılık dışı bırakmak" }),
      word("Dördüncü", { de: "die Gewissheit", tr: "kesinlik" }),
      word("Son", { de: "zweifeln", tr: "şüphe etmek" }),
      { say: [tr("Kalıbımız:"), de("dürfte / müsste / könnte"), tr("Üçü de dilek kipinde ve üçü de mastarla birlikte kullanılıyor.")] },
      { say: [tr("Örnek:"), de("Das dürfte stimmen, sicher bin ich aber nicht."), tr("Tekrar edin:"), de("Das dürfte stimmen, sicher bin ich aber nicht")], expect: repeat("Das dürfte stimmen, sicher bin ich aber nicht") },
      { say: [tr("Sıra sende, mantıksal çıkarımla: 'Şimdiye gelmiş olmalı.'")], expect: produce("Er müsste inzwischen angekommen sein", [tr("Geçmişe dönük tahminde ortaç ve sein birlikte gelir:"), de("Er müsste inzwischen angekommen sein."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi en zayıf derece: 'Bu da mümkün olabilir.'")], expect: produce("Das könnte auch möglich sein", [tr("Kip fiili ikinci sırada, mastar sonda:"), de("Das könnte auch möglich sein."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunu tamamen dışlamıyorum.'")], expect: produce("Das schließe ich nicht ganz aus", [tr("Nesne öne alınmış; ayrılabilen önek sonda:"), de("Das schließe ich nicht ganz aus."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Er müsste inzwischen ankommen sein."), tr("cümlesi doğru mu?")], expect: truefalse("Er müsste inzwischen ankommen sein.", false, [tr("Geçmişe dönük tahminde mastar değil ortaç gelir:"), de("Er müsste inzwischen angekommen sein.")]) },
      { say: [tr("Son: 'Kesinlik yok.'")], expect: produce("Gewissheit gibt es nicht", [tr("Nesne öne alınmış; kalıplaşmış fiil ikinci sırada:"), de("Gewissheit gibt es nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada belirsiz bir durumu birlikte yorumlayacaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşınla belirsiz bir durumu yorumluyorsunuz (bir gecikme, bir sessizlik, bir karar). Her tahminini emin olma derecesine göre söyle, hangi ihtimalleri dışladığını belirt ve bir sonraki adımı kararlaştırın.",
      partner: "hemen en kötü ihtimale atlayan bir meslektaş",
      opening: "Seit drei Tagen keine Antwort. Das kann doch nur eins bedeuten, oder?",
      openingTr: "Üç gündür cevap yok. Bunun tek bir anlamı olabilir, değil mi?",
      goal: "Tahminler emin olma derecesine göre ayrılmış, en kötü ihtimale atlamadan bir sonraki adım kararlaşmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-koerpersprache",
    icon: "greet",
    level: "B2",
    course: "de",
    title: "Was Gesten verraten",
    titleTr: "Beden dili",
    summary: "Beden dilinin nasıl etki ettiğini yöntem bağlacıyla anlatmayı öğretir.",
    minutes: 11,
    focusId: "Nebensatz-indem",
    vocab: [
      { de: "die Geste", tr: "jest" },
      { de: "verschränken", tr: "kavuşturmak (kol)" },
      { de: "der Blickkontakt", tr: "göz teması" },
      { de: "verraten", tr: "ele vermek" },
      { de: "die Haltung", tr: "duruş" },
    ],
    patterns: [
      { de: "…, indem wir …", tr: "nasıl olduğunu söyler" },
      { de: "Blickkontakt halten", tr: "göz teması kurmak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün konuşmayan bir dili konuşacağız: beden dili. Ve anlatmak için yine yöntem bağlacı lazım — 'kollarımızı kavuşturmayarak açıklık gösteririz'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu bağlacı artık biliyorsun; buradaki yenilik kelimeler ve bir de fiilin sabit nesnesi. Önce kelimeler.")] },
      word("İlk", { de: "die Geste", tr: "jest" }),
      word("İkinci", { de: "verschränken", tr: "kavuşturmak (kol)" }),
      word("Üçüncü", { de: "der Blickkontakt", tr: "göz teması" }),
      word("Dördüncü", { de: "verraten", tr: "ele vermek" }),
      word("Son", { de: "die Haltung", tr: "duruş" }),
      { say: [tr("Kalıbımız:"), de("…, indem wir …"), tr("Yan cümle; fiil sonda.")] },
      { say: [tr("Örnek:"), de("Wir zeigen Offenheit, indem wir die Arme nicht verschränken."), tr("Tekrar edin:"), de("Wir zeigen Offenheit, indem wir die Arme nicht verschränken")], expect: repeat("Wir zeigen Offenheit, indem wir die Arme nicht verschränken") },
      { say: [tr("Sıra sende: 'Yavaş konuşarak sakinlik yaratıyorsun.'")], expect: produce("Du erzeugst Ruhe, indem du langsam sprichst", [tr("Yan cümlede fiil sonda:"), de("Du erzeugst Ruhe, indem du langsam sprichst."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kavuşturulmuş kollar mesafeyi ele veriyor.'")], expect: produce("Die verschränkten Arme verraten Distanz", [tr("Ortaç sıfatı çoğulda -en ekini alır:"), de("Die verschränkten Arme verraten Distanz."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Göz teması kurmak gerekir.'")], expect: produce("Man sollte Blickkontakt halten", [tr("Kalıplaşmış ifade; belirteçsiz nesne:"), de("Man sollte Blickkontakt halten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Du erzeugst Ruhe, indem du langsam sprichst."), tr("cümlesi doğru mu?")], expect: truefalse("Du erzeugst Ruhe, indem du langsam sprichst.", true, [tr("Doğru. Yöntem bağlacından sonra çekimli fiil yan cümlenin sonunda duruyor.")]) },
      { say: [tr("Son: 'Duruş ruh hâlini ele veriyor.'")], expect: produce("Die Haltung verrät die Stimmung", [tr("Kısa cümle; nesne belirtme hâlinde:"), de("Die Haltung verrät die Stimmung."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada zor bir görüşmeye hazırlanacaksın: nasıl durmalı, nasıl konuşmalısın.")] },
    ],
    roleplay: {
      scene: "Yarın zor bir görüşmen var ve bir arkadaşınla nasıl davranman gerektiğini konuşuyorsunuz: nasıl durmalı, ne yapmamalı, gerginliği nasıl azaltmalısın. Her tavsiyeyi yöntem bağlacıyla kur.",
      partner: "böyle görüşmeleri çok yapmış, somut tavsiye veren bir arkadaş",
      opening: "Ich merke immer sofort, wenn jemand nervös ist. Was machst du denn normalerweise mit deinen Händen?",
      openingTr: "Birinin gergin olduğunu hemen fark ederim. Sen normalde ellerini ne yapıyorsun?",
      goal: "En az iki somut davranış tavsiyesi verilmiş ve öğrenci yarın ne yapacağını kendi cümlesiyle söylemiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-missverstaendnis",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Das große Missverständnis",
    titleTr: "Yanlış anlama",
    summary: "Yanlış anlamayı als ob ile adlandırıp düzeltmeyi öğretir.",
    minutes: 11,
    focusId: "Als-ob",
    vocab: [
      { de: "das Missverständnis", tr: "yanlış anlama" },
      { de: "klingen", tr: "kulağa gelmek" },
      { de: "die Absicht", tr: "niyet" },
      { de: "auffassen", tr: "algılamak" },
      { de: "richtigstellen", tr: "düzeltmek" },
    ],
    patterns: [
      { de: "Es klang, als ob …", tr: "nasıl duyulduğunu söyler" },
      { de: "Gemeint war aber …", tr: "kastedileni açıklar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir yanlış anlamayı düzelteceğiz. Bunun sırası bellidir: önce nasıl duyulduğunu kabul et, sonra ne kastettiğini söyle. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İlk hamle 'sanki' yapısıyla kurulur ve bu, karşı tarafı haksız çıkarmadan sorunu adlandırmanı sağlar. Önce kelimeler.")] },
      word("İlk", { de: "das Missverständnis", tr: "yanlış anlama" }),
      word("İkinci", { de: "klingen", tr: "kulağa gelmek" }),
      word("Üçüncü", { de: "die Absicht", tr: "niyet" }),
      word("Dördüncü", { de: "auffassen", tr: "algılamak" }),
      word("Son", { de: "richtigstellen", tr: "düzeltmek" }),
      { say: [tr("Kalıbımız:"), de("Es klang, als ob …"), tr("Yani 'sanki şöyleymiş gibi duyuldu'. Suçlama yok, gözlem var.")] },
      { say: [tr("Örnek:"), de("Es klang, als ob ich dich kritisieren wollte."), tr("Tekrar edin:"), de("Es klang, als ob ich dich kritisieren wollte")], expect: repeat("Es klang, als ob ich dich kritisieren wollte") },
      { say: [tr("Sıra sende: 'Kastedilen ise başka bir şeydi.'")], expect: produce("Gemeint war aber etwas anderes", [tr("Ortaç başta, fiil ikinci sırada:"), de("Gemeint war aber etwas anderes."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Belki bunu yanlış algıladın.'")], expect: produce("Vielleicht hast du das falsch aufgefasst", [tr("Zarf başta olunca fiil ikinci sıraya geçer:"), de("Vielleicht hast du das falsch aufgefasst."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Niyetim seni incitmek değildi.'")], expect: produce("Meine Absicht war nicht, dich zu verletzen", [tr("Mastar öbeği virgülden sonra, zu ile:"), de("Meine Absicht war nicht, dich zu verletzen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Vielleicht du hast das falsch aufgefasst."), tr("cümlesi doğru mu?")], expect: truefalse("Vielleicht du hast das falsch aufgefasst.", false, [tr("Cümle bir zarfla başlayınca çekimli fiil ikinci sıraya gelir:"), de("Vielleicht hast du das falsch aufgefasst.")]) },
      { say: [tr("Son: 'Bunu düzeltmek istiyorum.'")], expect: produce("Das möchte ich richtigstellen", [tr("Nesne öne alınmış; ayrılabilen mastar sonda:"), de("Das möchte ich richtigstellen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir yanlış anlamayı çözeceksin.")] },
    ],
    roleplay: {
      scene: "Söylediğin bir şey yanlış anlaşıldı ve karşındaki kırgın. Nasıl duyulduğunu kabul et, ne kastettiğini açıkla, özrün gerekiyorsa dile getir ve ilişkiyi onarmak için bir adım öner.",
      partner: "kırgın ama konuşmaya açık bir yakın arkadaş",
      opening: "Ich habe lange überlegt, ob ich es anspreche. Es klang, als hättest du mich vor allen bloßstellen wollen — war das so gemeint?",
      openingTr: "Konuyu açıp açmamayı uzun düşündüm. Sanki beni herkesin önünde küçük düşürmek istemişsin gibi geldi — öyle mi demek istedin?",
      goal: "Nasıl duyulduğu kabul edilmiş, kastedilen açıklanmış ve ilişkiyi onarmak için somut bir adım kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-motivation-psy",
    icon: "run",
    level: "B2",
    course: "de",
    title: "Der innere Schweinehund",
    titleTr: "Motivasyon",
    summary: "Erteleme ve kendini aşmayı edilgen yerine geçen yapılarla konuşmayı öğretir.",
    minutes: 11,
    focusId: "Passiversatz",
    vocab: [
      { de: "die Überwindung", tr: "kendini aşma" },
      { de: "durchziehen", tr: "sonuna kadar götürmek" },
      { de: "die Ausrede", tr: "bahane" },
      { de: "die Hürde", tr: "engel" },
      { de: "aufschieben", tr: "ertelemek" },
    ],
    patterns: [
      { de: "… lässt sich überwinden", tr: "aşılabilir" },
      { de: "Es hilft, … zu …", tr: "işe yarayan şeyi söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün herkesin tanıdığı bir düşman: erteleme. Almancada bunun bir adı bile var ve o adla kurulan cümleler edilgen yerine geçen yapılarla söylenir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sebebi ince: 'aşılabilir' demek 'sen aşabilirsin' demekten daha az suçlayıcı. Dil burada bir tavır seçiyor. Önce kelimeler.")] },
      word("İlk", { de: "die Überwindung", tr: "kendini aşma" }),
      word("İkinci", { de: "durchziehen", tr: "sonuna kadar götürmek" }),
      word("Üçüncü", { de: "die Ausrede", tr: "bahane" }),
      word("Dördüncü", { de: "die Hürde", tr: "engel" }),
      word("Son", { de: "aufschieben", tr: "ertelemek" }),
      { say: [tr("Kalıbımız:"), de("… lässt sich überwinden"), tr("Yani 'aşılabilir'; fail yok, imkân var.")] },
      { say: [tr("Örnek:"), de("Der innere Schweinehund lässt sich überwinden."), tr("Tekrar edin:"), de("Der innere Schweinehund lässt sich überwinden")], expect: repeat("Der innere Schweinehund lässt sich überwinden") },
      { say: [tr("Sıra sende: 'İlk engel en büyüğüdür.'")], expect: produce("Die erste Hürde ist die größte", [tr("Üstünlük biçimi belirtili sıfat gibi çekilir:"), de("Die erste Hürde ist die größte."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Küçük başlamak yardımcı oluyor.'")], expect: produce("Es hilft, klein anzufangen", [tr("Sahte özne es; ayrılabilen fiilde zu ortaya girer:"), de("Es hilft, klein anzufangen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bahaneler her zaman bulunur.'")], expect: produce("Ausreden finden sich immer", [tr("Dönüşlü fiil edilgen anlamı taşır:"), de("Ausreden finden sich immer."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der innere Schweinehund lässt sich überwinden, wenn man klein anfangen."), tr("cümlesi doğru mu?")], expect: truefalse("Der innere Schweinehund lässt sich überwinden, wenn man klein anfangen.", false, [tr("Yan cümlenin sonunda mastar değil çekimli fiil bulunur:"), de("Der innere Schweinehund lässt sich überwinden, wenn man klein anfängt.")]) },
      { say: [tr("Son: 'Bunu sonuna kadar götürmek istiyorum.'")], expect: produce("Ich möchte das durchziehen", [tr("Nesne ortada; ayrılabilen mastar sonda:"), de("Ich möchte das durchziehen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada ertelediğin bir işi konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Aylardır ertelediğin bir işi bir arkadaşınla konuşuyorsun: ne erteliyorsun, hangi bahaneleri kullanıyorsun, ilk adım ne olabilir ve nasıl devam edeceksin.",
      partner: "yargılamayan ama somut adım isteyen bir arkadaş",
      opening: "Du redest seit Monaten davon. Was ist denn die kleinste Sache, die du diese Woche machen könntest?",
      openingTr: "Aylardır bundan bahsediyorsun. Bu hafta yapabileceğin en küçük şey ne olurdu?",
      goal: "Ertelenen iş ve bahaneler adlandırılmış, bu hafta atılacak en küçük somut adım kararlaşmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-gewohnheiten",
    icon: "clock",
    level: "B2",
    course: "de",
    title: "Die Macht der Gewohnheit",
    titleTr: "Alışkanlıklar",
    summary: "Alışkanlığın nasıl kurulduğunu ve bırakıldığını anlatmayı öğretir.",
    minutes: 11,
    focusId: "Nebensatz-indem",
    vocab: [
      { de: "die Gewohnheit", tr: "alışkanlık" },
      { de: "sich angewöhnen", tr: "alışkanlık edinmek" },
      { de: "ablegen", tr: "bırakmak (alışkanlık)" },
      { de: "der Auslöser", tr: "tetikleyici" },
      { de: "beständig", tr: "istikrarlı" },
    ],
    patterns: [
      { de: "…, indem man sie wiederholt", tr: "nasıl oluştuğunu söyler" },
      { de: "sich etwas angewöhnen", tr: "alışkanlık edinmek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün alışkanlıkları konuşacağız. Bu konunun cümleleri hep 'nasıl' sorusuna cevap verir, o yüzden yöntem bağlacı yine merkezde. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de iki dönüşlü fiil var: biri alışkanlık edinmek, öteki bırakmak. İkisi de yönelme hâlinde zamir ister. Önce kelimeler.")] },
      word("İlk", { de: "die Gewohnheit", tr: "alışkanlık" }),
      word("İkinci", { de: "sich angewöhnen", tr: "alışkanlık edinmek" }),
      word("Üçüncü", { de: "ablegen", tr: "bırakmak (alışkanlık)" }),
      word("Dördüncü", { de: "der Auslöser", tr: "tetikleyici" }),
      word("Son", { de: "beständig", tr: "istikrarlı" }),
      { say: [tr("Kalıbımız:"), de("…, indem man sie täglich wiederholt"), tr("Yan cümle; fiil sonda.")] },
      { say: [tr("Örnek:"), de("Eine Gewohnheit entsteht, indem man sie täglich wiederholt."), tr("Tekrar edin:"), de("Eine Gewohnheit entsteht, indem man sie täglich wiederholt")], expect: repeat("Eine Gewohnheit entsteht, indem man sie täglich wiederholt") },
      { say: [tr("Sıra sende: 'Yeni bir alışkanlık edinmek istiyorum.'")], expect: produce("Ich möchte mir eine neue Gewohnheit angewöhnen", [tr("Dönüşlü zamir yönelme hâlinde; ayrılabilen mastar sonda:"), de("Ich möchte mir eine neue Gewohnheit angewöhnen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kötü bir alışkanlığı bırakmak zordur.'")], expect: produce("Eine schlechte Gewohnheit abzulegen ist schwer", [tr("Mastar öbeği özne olarak başta:"), de("Eine schlechte Gewohnheit abzulegen ist schwer."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Tetikleyiciyi tanımak gerekir.'")], expect: produce("Man muss den Auslöser kennen", [tr("Nesne belirtme hâlinde; mastar sonda:"), de("Man muss den Auslöser kennen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Eine Gewohnheit entsteht, indem man sie täglich wiederholt."), tr("cümlesi doğru mu?")], expect: truefalse("Eine Gewohnheit entsteht, indem man sie täglich wiederholt.", true, [tr("Doğru. Yöntem bağlacından sonra çekimli fiil yan cümlenin sonunda duruyor.")]) },
      { say: [tr("Son: 'Otuz gün sonra daha kolay geliyor.'")], expect: produce("Nach dreißig Tagen fällt es leichter", [tr("Zaman ifadesi başta, fiil ikinci sırada:"), de("Nach dreißig Tagen fällt es leichter."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir alışkanlık planı kuracaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla alışkanlık kurmayı konuşuyorsunuz: hangi alışkanlığı istiyorsun, tetikleyicin ne, hangi kötü alışkanlığı bırakmak istiyorsun ve ilk hafta planın ne.",
      partner: "kendi denemelerini anlatan, plan yapmayı seven bir arkadaş",
      opening: "Ich habe es dreimal versucht und dreimal aufgegeben. Was ist denn bei dir der Auslöser?",
      openingTr: "Üç kez denedim, üç kez bıraktım. Sende tetikleyici ne?",
      goal: "İstenen alışkanlık, tetikleyicisi ve ilk haftanın planı konuşulmuş ve iki taraf da somut bir söz vermiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-empathie",
    icon: "family",
    level: "B2",
    course: "de",
    title: "Sich hineinversetzen",
    titleTr: "Empati",
    summary: "Kendini başkasının yerine koymayı dilek kipiyle anlatmayı öğretir.",
    minutes: 11,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "sich hineinversetzen", tr: "kendini yerine koymak" },
      { de: "das Mitgefühl", tr: "şefkat, empati" },
      { de: "die Sichtweise", tr: "bakış açısı" },
      { de: "zuhören", tr: "dinlemek" },
      { de: "urteilen", tr: "yargılamak" },
    ],
    patterns: [
      { de: "An seiner Stelle hätte ich …", tr: "kendini yerine koyar" },
      { de: "Wie würdest du dich fühlen?", tr: "empatiye davet eder" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün empatiyi kuracağız ve dilbilgisi tam da buna uygun: kendini başkasının yerine koymak, gerçek olmayan bir durumu kurmaktır — yani dilek kipi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Geçmişe dönük dilek kipinde bir tuzak var: yardımcı fiilden sonra mastar değil ortaç gelir. Sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "sich hineinversetzen", tr: "kendini yerine koymak" }),
      word("İkinci", { de: "das Mitgefühl", tr: "şefkat, empati" }),
      word("Üçüncü", { de: "die Sichtweise", tr: "bakış açısı" }),
      word("Dördüncü", { de: "zuhören", tr: "dinlemek" }),
      word("Son", { de: "urteilen", tr: "yargılamak" }),
      { say: [tr("Kalıbımız:"), de("An seiner Stelle hätte ich …"), tr("Yani 'onun yerinde olsam şöyle yapardım'.")] },
      { say: [tr("Örnek:"), de("An seiner Stelle hätte ich genauso reagiert."), tr("Tekrar edin:"), de("An seiner Stelle hätte ich genauso reagiert")], expect: repeat("An seiner Stelle hätte ich genauso reagiert") },
      { say: [tr("Sıra sende: 'Sen olsan nasıl hissederdin?'")], expect: produce("Wie würdest du dich fühlen", [tr("Soru kelimesi başta, dilek kipi ikinci sırada:"), de("Wie würdest du dich fühlen?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kendimi onun yerine koymaya çalışıyorum.'")], expect: produce("Ich versuche, mich in ihn hineinzuversetzen", [tr("Ayrılabilen ve dönüşlü fiilde zu ortaya girer:"), de("Ich versuche, mich in ihn hineinzuversetzen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Önce dinlemek, sonra yargılamak.'")], expect: produce("Erst zuhören, dann urteilen", [tr("İki mastar, kısa ve vurgulu:"), de("Erst zuhören, dann urteilen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("An seiner Stelle hätte ich genauso reagieren."), tr("cümlesi doğru mu?")], expect: truefalse("An seiner Stelle hätte ich genauso reagieren.", false, [tr("Bu yardımcı fiilden sonra mastar değil ortaç gelir:"), de("An seiner Stelle hätte ich genauso reagiert.")]) },
      { say: [tr("Son: 'Onun bakış açısını anlıyorum.'")], expect: produce("Ich verstehe seine Sichtweise", [tr("Nesne belirtme hâlinde:"), de("Ich verstehe seine Sichtweise."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir anlaşmazlığa iki taraftan da bakacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın üçüncü bir kişiyle yaşadığı anlaşmazlığı anlatıyor. Önce dinle, sonra karşı tarafın bakış açısını da ortaya koy, yargılamadan bir soru sor ve ne yapabileceğini birlikte düşünün.",
      partner: "kırgın, kendi haklılığından emin bir arkadaş",
      opening: "Sie hat einfach aufgelegt. Nach allem, was ich für sie gemacht habe — übertreibe ich da wirklich?",
      openingTr: "Telefonu kapattı öylece. Onun için yaptığım onca şeyden sonra — gerçekten abartıyor muyum?",
      goal: "Arkadaşın hikâyesi dinlenmiş, karşı tarafın bakış açısı yargılamadan ortaya konmuş ve bir sonraki adım birlikte düşünülmüş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-streitkultur",
    icon: "handshake",
    level: "B2",
    course: "de",
    title: "Fair streiten",
    titleTr: "Tartışma kültürü",
    summary: "Adil tartışmanın kurallarını çift bağlaçlarla anlatmayı öğretir.",
    minutes: 11,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "die Ich-Botschaft", tr: "ben dili" },
      { de: "schreien", tr: "bağırmak" },
      { de: "schweigen", tr: "susmak" },
      { de: "fair", tr: "adil" },
      { de: "unterbrechen", tr: "sözünü kesmek" },
    ],
    patterns: [
      { de: "weder … noch …", tr: "ikisi de değil" },
      { de: "einerseits … andererseits …", tr: "iki yanı tartar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün tartışmanın kurallarını konuşacağız. İlginç olan şu: adil tartışmanın dili de çift parçalıdır, çünkü iki tarafı aynı anda tutar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu bağlaçları altıncı modülde kurmuştun; buradaki zorluk ikinci parçadan sonra fiilin nereye gideceği. Sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "die Ich-Botschaft", tr: "ben dili" }),
      word("İkinci", { de: "schreien", tr: "bağırmak" }),
      word("Üçüncü", { de: "schweigen", tr: "susmak" }),
      word("Dördüncü", { de: "fair", tr: "adil" }),
      word("Son", { de: "unterbrechen", tr: "sözünü kesmek" }),
      { say: [tr("Kalıbımız:"), de("weder … noch …"), tr("İki seçeneği birden dışarıda bırakır.")] },
      { say: [tr("Örnek:"), de("Weder schreien noch schweigen hilft."), tr("Tekrar edin:"), de("Weder schreien noch schweigen hilft")], expect: repeat("Weder schreien noch schweigen hilft") },
      { say: [tr("Sıra sende: 'Bir yandan haklısın, öte yandan sert söylendi.'")], expect: produce("Einerseits hast du recht, andererseits war es hart gesagt", [tr("Her iki parça da cümlenin ilk öğesidir; fiil hemen arkalarından gelir:"), de("Einerseits hast du recht, andererseits war es hart gesagt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Lütfen sözümü kesme.'")], expect: produce("Unterbrich mich bitte nicht", [tr("Emir kipi; olumsuzluk sonda:"), de("Unterbrich mich bitte nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ben dilini kullanmayı öğrendim.'")], expect: produce("Ich habe gelernt, Ich-Botschaften zu benutzen", [tr("Mastar öbeği virgülden sonra, zu ile:"), de("Ich habe gelernt, Ich-Botschaften zu benutzen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Einerseits hast du recht, andererseits es war hart gesagt."), tr("cümlesi doğru mu?")], expect: truefalse("Einerseits hast du recht, andererseits es war hart gesagt.", false, [tr("Bu bağlaç cümlenin ilk öğesidir, o yüzden fiil hemen arkasından gelir:"), de("Einerseits hast du recht, andererseits war es hart gesagt.")]) },
      { say: [tr("Son: 'Adil tartışmak öğrenilebilir.'")], expect: produce("Fair zu streiten kann man lernen", [tr("Mastar öbeği başta, nesne olarak:"), de("Fair zu streiten kann man lernen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir tartışmanın kurallarını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Yakın biriyle son tartışmanızın nasıl yürüdüğünü konuşuyorsunuz: ne iyi gitmedi, kim neyi yaptı, bir dahaki sefere hangi kurala uyacaksınız. Suçlama yerine ben dili kullan.",
      partner: "savunmaya geçmeye hazır ama iyi niyetli bir yakın",
      opening: "Wir haben gestern beide Sachen gesagt, die wir nicht so meinten. Wie machen wir das nächste Mal besser?",
      openingTr: "Dün ikimiz de öyle demek istemediğimiz şeyler söyledik. Bir dahaki sefere nasıl daha iyi yaparız?",
      goal: "Neyin iyi gitmediği ben diliyle söylenmiş ve bir dahaki sefer için en az iki kural üzerinde anlaşılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-perfektionismus",
    icon: "star",
    level: "B2",
    course: "de",
    title: "Gut ist gut genug",
    titleTr: "Mükemmeliyetçilik",
    summary: "Kendine koyulan gerçekdışı ölçütleri als ob ile adlandırmayı öğretir.",
    minutes: 11,
    focusId: "Als-ob",
    vocab: [
      { de: "der Leistungsdruck", tr: "performans baskısı" },
      { de: "loslassen", tr: "bırakmak" },
      { de: "genügen", tr: "yetmek" },
      { de: "der Maßstab", tr: "ölçüt" },
      { de: "sich quälen", tr: "kendine eziyet etmek" },
    ],
    patterns: [
      { de: "Ich tue so, als ob … müsste.", tr: "kendi kuralını adlandırır" },
      { de: "Gut ist gut genug.", tr: "ölçüyü indirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kendine koyduğun kuralları konuşacağız. 'Sanki' yapısı burada başkasını değil kendini anlatmak için işe yarıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Sanki her şey kusursuz olmak zorundaymış gibi davranıyorum' — bu cümle bir kuralı adlandırıyor ve adlandırılan kural tartışılabilir hâle geliyor. Önce kelimeler.")] },
      word("İlk", { de: "der Leistungsdruck", tr: "performans baskısı" }),
      word("İkinci", { de: "loslassen", tr: "bırakmak" }),
      word("Üçüncü", { de: "genügen", tr: "yetmek" }),
      word("Dördüncü", { de: "der Maßstab", tr: "ölçüt" }),
      word("Son", { de: "sich quälen", tr: "kendine eziyet etmek" }),
      { say: [tr("Kalıbımız:"), de("Ich tue so, als ob alles perfekt sein müsste."), tr("Bağlaçtan sonra dilek kipi, çünkü bu bir gerçek değil bir varsayım.")] },
      { say: [tr("Tekrar edin:"), de("Ich tue oft so, als ob alles perfekt sein müsste")], expect: repeat("Ich tue oft so, als ob alles perfekt sein müsste") },
      { say: [tr("Sıra sende: 'İyi olan yeterlidir.'")], expect: produce("Gut ist gut genug", [tr("Kısa ve kalıplaşmış bir cümle:"), de("Gut ist gut genug."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ölçütlerim çok yüksekti.'")], expect: produce("Meine Maßstäbe waren zu hoch", [tr("Çoğul özne; geçmiş zamanda:"), de("Meine Maßstäbe waren zu hoch."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunu bırakmayı öğreniyorum.'")], expect: produce("Ich lerne, das loszulassen", [tr("Ayrılabilen fiilde zu ortaya girer:"), de("Ich lerne, das loszulassen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich tue oft so, als ob alles perfekt sein müsste."), tr("cümlesi doğru mu?")], expect: truefalse("Ich tue oft so, als ob alles perfekt sein müsste.", true, [tr("Doğru. Bağlaçtan sonra dilek kipi kullanılmış ve fiil öbeği yan cümlenin sonunda duruyor.")]) },
      { say: [tr("Son: 'Bu performans baskısı bana eziyet ediyor.'")], expect: produce("Dieser Leistungsdruck quält mich", [tr("Kısa cümle; nesne belirtme hâlinde:"), de("Dieser Leistungsdruck quält mich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada kendi ölçütlerini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla kendine koyduğun yüksek ölçütleri konuşuyorsun: nerede kendini zorluyorsun, bu ölçüt nereden geliyor, neyi bırakabilirsin ve 'yeterli' senin için ne demek.",
      partner: "seni tanıyan, aşırı ölçütlerini fark etmiş bir arkadaş",
      opening: "Du hast die Präsentation viermal umgebaut. Ab wann ist es denn für dich gut genug?",
      openingTr: "Sunumu dört kez baştan kurdun. Senin için ne zaman yeterince iyi oluyor?",
      goal: "Kendine konan ölçüt adlandırılmış, nereden geldiği konuşulmuş ve neyin bırakılabileceği söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-veraenderung-b2",
    icon: "mountain",
    level: "B2",
    course: "de",
    title: "Raus aus der Komfortzone",
    titleTr: "Değişim cesareti",
    summary: "Değişimi koşullu bağlaçlarla ve cesaret diliyle konuşmayı öğretir.",
    minutes: 11,
    focusId: "Nebensatz-sofern",
    vocab: [
      { de: "die Komfortzone", tr: "rahat alan" },
      { de: "das Wachstum", tr: "büyüme, gelişim" },
      { de: "wagen", tr: "cesaret etmek" },
      { de: "der Rückschritt", tr: "geri adım" },
      { de: "bereit", tr: "hazır" },
    ],
    patterns: [
      { de: "Sofern man bereit ist, …", tr: "koşullu cesaret" },
      { de: "Wage den ersten Schritt.", tr: "emir kipiyle cesaret" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve konusu değişim. Değişim hakkında konuşurken hiçbir söz kesin verilmez, hep bir koşula bağlanır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de emir kipi var: 'ilk adımı at'. Emirde nesnenin hâline dikkat etmen gerekiyor. Sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "die Komfortzone", tr: "rahat alan" }),
      word("İkinci", { de: "das Wachstum", tr: "büyüme, gelişim" }),
      word("Üçüncü", { de: "wagen", tr: "cesaret etmek" }),
      word("Dördüncü", { de: "der Rückschritt", tr: "geri adım" }),
      word("Son", { de: "bereit", tr: "hazır" }),
      { say: [tr("Kalıbımız:"), de("Sofern …, …"), tr("Koşul yan cümlede; ana cümle fiille başlar.")] },
      { say: [tr("Örnek:"), de("Sofern du in der Komfortzone bleibst, ändert sich nichts."), tr("Tekrar edin:"), de("Sofern du in der Komfortzone bleibst, ändert sich nichts")], expect: repeat("Sofern du in der Komfortzone bleibst, ändert sich nichts") },
      { say: [tr("Sıra sende: 'İlk adımı atmaya cesaret et.'")], expect: produce("Wage den ersten Schritt", [tr("Emir kipi; nesne belirtme hâlinde:"), de("Wage den ersten Schritt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir geri adım son değildir.'")], expect: produce("Ein Rückschritt ist kein Ende", [tr("Olumsuz belirteç nötr isimle:"), de("Ein Rückschritt ist kein Ende."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Gelişim rahatsızlıkta başlar.'")], expect: produce("Wachstum beginnt im Unbequemen", [tr("İsimleşmiş sıfat yönelme hâlinde:"), de("Wachstum beginnt im Unbequemen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wage der erste Schritt."), tr("cümlesi doğru mu?")], expect: truefalse("Wage der erste Schritt.", false, [tr("Bu fiilin nesnesi belirtme hâline girer:"), de("Wage den ersten Schritt.")]) },
      { say: [tr("Son: 'Hazır olursan yardım ederim.'")], expect: produce("Sofern du bereit bist, helfe ich dir", [tr("Yan cümle önde; ana cümle fiille başlar:"), de("Sofern du bereit bist, helfe ich dir."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada büyük bir değişimi konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın büyük bir değişimin eşiğinde ve tereddüt ediyor. Neyden korktuğunu sor, hangi koşulda yapabileceğini konuş, en küçük ilk adımı birlikte bul ve ne zaman atacağına karar verin.",
      partner: "hem istekli hem korkan, karar aşamasındaki bir arkadaş",
      opening: "Ich weiß, dass ich es will. Aber jedes Mal, wenn ich kurz davor bin, finde ich einen Grund zu warten. Kennst du das?",
      openingTr: "İstediğimi biliyorum. Ama her seferinde tam eşiğe geldiğimde beklemek için bir sebep buluyorum. Tanıdık geliyor mu?",
      goal: "Korkunun ne olduğu adlandırılmış, hangi koşulda yapılabileceği konuşulmuş ve ilk adım ile tarihi kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
];
