import { de, tr, type LectureStep, type Lesson, type Segment } from "../types";

/**
 * B1 · Modül 16 — Meslekler ve iş yaşamı (151–160).
 *
 * Modül 1 iş dünyasının KONUŞMASINI öğretmişti: görüşme, maaş, istifa.
 * Bu modül o dünyanın adlarını veriyor — hangi meslek ne, hangi eğitim
 * hangi belgeyi getirir, sendika ne yapar.
 *
 * Meslek adlarının çoğu havuzda eril ve dişil biçimiyle ayrı kayıt. İkisini
 * aynı derse koymak normalizasyonda tek anahtara düşüyor ve öğrenciye aynı
 * kelimeyi iki kez öğretiyor; o yüzden çiftler bilerek ayrıldı ya da yalnız
 * biri alındı.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [
      tr(`${n} kelimemiz:`),
      de(w.de),
      tr(`Türkçesi '${w.tr}' demek${note ? ` — ${note}` : ""}. Lütfen`),
      de(w.de),
      tr("deyin."),
    ],
    expect: repeat(w.de),
  };
}

export const deB1B16: Lesson[] = [
  {
    id: "de-b1-berufe-vorstellen",
    icon: "job",
    level: "B1",
    course: "de",
    title: "Was macht man da eigentlich?",
    titleTr: "Meslekleri tanıtmak",
    summary: "Bir mesleği ilgi cümlesiyle tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Nominativ",
    vocab: [
      { de: "der Ingenieur", tr: "mühendis" },
      { de: "der Architekt", tr: "mimar" },
      { de: "die Architektin", tr: "kadın mimar" },
      { de: "der Maler", tr: "ressam" },
      { de: "der Musiker", tr: "müzisyen" },
      { de: "der Übersetzer", tr: "çevirmen" },
      { de: "der Metzger", tr: "kasap" },
      { de: "der Sozialarbeiter", tr: "sosyal hizmet uzmanı" },
    ],
    patterns: [
      { de: "Das ist jemand, der …", tr: "mesleği yaptığı işle tanımlar" },
      { de: "Man braucht dafür …", tr: "mesleğin ne gerektirdiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün meslekleri tanıtacağız. Bir mesleğin adını bilmek yetmez; ne yaptığını bir cümlede anlatabilmek gerekir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bunun yolu ilgi cümlesi. Tanımlanan kişi yan cümlenin öznesi olduğunda ilgi zamiri yalın hâlde kalır ve fiil sona gider. Önce meslekler.")] },
      word("İlk", { de: "der Ingenieur", tr: "mühendis" }),
      word("İkinci", { de: "der Architekt", tr: "mimar" }),
      word("Üçüncü", { de: "die Architektin", tr: "kadın mimar" }),
      word("Dördüncü", { de: "der Maler", tr: "ressam" }, "boyacı anlamına da gelir"),
      word("Beşinci", { de: "der Musiker", tr: "müzisyen" }),
      word("Altıncı", { de: "der Übersetzer", tr: "çevirmen" }),
      word("Yedinci", { de: "der Metzger", tr: "kasap" }),
      word("Son", { de: "der Sozialarbeiter", tr: "sosyal hizmet uzmanı" }),
      { say: [tr("İlk kalıbımız mesleği işiyle tanımlıyor. Belirsiz bir kişi zamiri kullanıyoruz, sonra ilgi cümlesi geliyor.")] },
      { say: [tr("Örnek:"), de("Ein Übersetzer ist jemand, der Texte in eine andere Sprache bringt."), tr("Tekrar edin:"), de("Ein Übersetzer ist jemand, der Texte in eine andere Sprache bringt")], expect: repeat("Ein Übersetzer ist jemand, der Texte in eine andere Sprache bringt") },
      { say: [tr("Sıra sende: 'Mimar, binaları tasarlayan kişidir.'")], expect: produce("Ein Architekt ist jemand, der Gebäude plant", [tr("İlgi zamiri yalın hâlde, fiil yan cümlenin sonunda:"), de("Ein Architekt ist jemand, der Gebäude plant."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız mesleğin ne gerektirdiğini söylüyor: belirsiz özne ve bir edat öbeği.")] },
      { say: [tr("Şimdi: 'Bunun için uzun bir eğitim gerekiyor.'")], expect: produce("Man braucht dafür eine lange Ausbildung", [tr("Belirsiz özne, nesne belirtme hâlinde:"), de("Man braucht dafür eine lange Ausbildung."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Architektin ist jemand, die Häuser baut."), tr("cümlesi doğru mu?")], expect: truefalse("Die Architektin ist jemand, die Häuser baut.", false, [tr("Bu belirsiz kişi zamiri her zaman eril sayılır, ilgi zamiri de ona uyar:"), de("Die Architektin ist jemand, der Häuser baut.")]) },
      { say: [tr("Son: 'Kasap, eti hazırlayıp satan kişidir.'")], expect: produce("Ein Metzger ist jemand, der Fleisch verkauft", [tr("İlgi cümlesinde fiil sonda:"), de("Ein Metzger ist jemand, der Fleisch verkauft."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir kariyer gününde meslekleri tanıtacaksın.")] },
    ],
    roleplay: {
      scene: "Bir okulda kariyer günündesin. Gençlere üç mesleği tanıtıyor, her birinin ne yaptığını ve ne gerektirdiğini anlatıyorsun.",
      partner: "hangi mesleği seçeceğini bilmeyen meraklı bir öğrenci",
      opening: "Ich weiß echt nicht, was ich werden soll — was machen die Leute in Ihrem Beruf denn so?",
      openingTr: "Ne olacağımı gerçekten bilmiyorum — sizin mesleğinizdekiler ne yapıyor?",
      goal: "En az üç meslek işiyle tanımlanmış ve her biri için gereken eğitim söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-lehre-machen",
    icon: "school",
    level: "B1",
    course: "de",
    title: "Lehre oder Studium?",
    titleTr: "Çıraklık mı üniversite mi?",
    summary: "Niyet ve amaç bildiren mastar öbekleriyle eğitim yolunu anlatmayı öğretir.",
    minutes: 10,
    focusId: "Infinitiv-zu",
    vocab: [
      { de: "die Lehrstelle", tr: "çıraklık yeri" },
      { de: "der Lehrling", tr: "çırak" },
      { de: "die Lehre", tr: "çıraklık eğitimi" },
      { de: "die Fortbildung", tr: "hizmet içi eğitim" },
      { de: "das Diplom", tr: "diploma" },
      { de: "das Zertifikat", tr: "sertifika" },
      { de: "das Abitur", tr: "lise diploması" },
      { de: "die Matura", tr: "olgunluk sınavı" },
    ],
    patterns: [
      { de: "Ich habe mich entschieden, … zu …", tr: "kararını mastar öbeğiyle söyler" },
      { de: "Es lohnt sich, … zu …", tr: "bir şeyin değdiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Almanya'da liseden sonra iki yol var: çıraklık ya da üniversite. Bugün hangisini neden seçtiğini anlatacaksın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karar ve gerekçe mastar öbeğiyle kurulur: küçük bir edat ve mastar, ikisi de cümlenin sonunda. Önce kelimeler.")] },
      word("İlk", { de: "die Lehrstelle", tr: "çıraklık yeri" }),
      word("İkinci", { de: "der Lehrling", tr: "çırak" }),
      word("Üçüncü", { de: "die Lehre", tr: "çıraklık eğitimi" }, "okul ve işyeri birlikte yürür"),
      word("Dördüncü", { de: "die Fortbildung", tr: "hizmet içi eğitim" }),
      word("Beşinci", { de: "das Diplom", tr: "diploma" }),
      word("Altıncı", { de: "das Zertifikat", tr: "sertifika" }),
      word("Yedinci", { de: "das Abitur", tr: "lise diploması" }, "Almanya'daki biçim"),
      word("Son", { de: "die Matura", tr: "olgunluk sınavı" }, "Avusturya ve İsviçre'deki karşılığı"),
      { say: [tr("İlk kalıbımız kararı söylüyor: dönüşlü bir fiil ve mastar öbeği. Dönüşlü zamir fiilden hemen sonra geliyor.")] },
      { say: [tr("Örnek:"), de("Ich habe mich entschieden, eine Lehre zu machen."), tr("Tekrar edin:"), de("Ich habe mich entschieden, eine Lehre zu machen")], expect: repeat("Ich habe mich entschieden, eine Lehre zu machen") },
      { say: [tr("Sıra sende: 'Bir sertifika almaya karar verdim.'")], expect: produce("Ich habe mich entschieden, ein Zertifikat zu machen", [tr("Nesne mastardan önce, mastar sonda:"), de("Ich habe mich entschieden, ein Zertifikat zu machen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız gerekçe veriyor: dönüşlü ve kişisiz bir fiil. Bir yatırımın değip değmediğini söyler.")] },
      { say: [tr("Şimdi: 'Hizmet içi eğitim almak buna değer.'")], expect: produce("Es lohnt sich, eine Fortbildung zu machen", [tr("Kişisiz özne, mastar sonda:"), de("Es lohnt sich, eine Fortbildung zu machen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es lohnt sich, zu suchen eine Lehrstelle."), tr("cümlesi doğru mu?")], expect: truefalse("Es lohnt sich, zu suchen eine Lehrstelle.", false, [tr("Mastar öbeğinde nesne mastardan ÖNCE gelir:"), de("Es lohnt sich, eine Lehrstelle zu suchen.")]) },
      { say: [tr("Son: 'Çırak olarak başlamayı planlıyorum.'")], expect: produce("Ich habe vor, als Lehrling anzufangen", [tr("Ayrılabilen fiilde edat önek ile kök arasına giriyor:"), de("Ich habe vor, als Lehrling anzufangen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir danışmanla eğitim yolunu konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslek danışmanıyla konuşuyorsun: çıraklık mı üniversite mi, hangi belgeler gerekiyor, neyin değdiğini düşünüyorsun.",
      partner: "iki yolu da tanıyan, karar vermeni kolaylaştırmaya çalışan bir danışman",
      opening: "Sie sitzen zwischen zwei Wegen, richtig? Was zieht Sie denn mehr — Lehre oder Studium?",
      openingTr: "İki yol arasında kaldınız, değil mi? Sizi daha çok hangisi çekiyor — çıraklık mı üniversite mi?",
      goal: "İki yol karşılaştırılmış, bir karar gerekçesiyle söylenmiş ve gereken belgeler öğrenilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-experte-fragen",
    icon: "idea",
    level: "B1",
    course: "de",
    title: "Fragen Sie den Fachmann",
    titleTr: "Uzmana danışmak",
    summary: "Bilmediğin uzmanlık ayrıntılarını dolaylı soruyla sormayı öğretir.",
    minutes: 10,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "der Experte", tr: "uzman" },
      { de: "der Spezialist", tr: "uzman kişi" },
      { de: "die Spezialistin", tr: "kadın uzman" },
      { de: "der Fachmann", tr: "ehil kişi" },
      { de: "die Fachfrau", tr: "ehil kadın" },
      { de: "die Fachleute", tr: "uzmanlar" },
      { de: "das Institut", tr: "enstitü" },
      { de: "die Forschung", tr: "araştırma" },
    ],
    patterns: [
      { de: "Wissen Sie, ob …?", tr: "emin olmadığın bir şeyi sorar" },
      { de: "Ich würde gern wissen, wie …", tr: "kibarca bilgi ister" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bir uzmana danışacaksın. Uzmana soru sormanın kuralı var: doğrudan sormak değil, dolaylı sormak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dolaylı soruda soru sözcüğü bağlaca döner ve fiil en sona gider; soru sözcüğü yoksa emin olmadığını bildiren bağlaç gelir. Önce kelimeler.")] },
      word("İlk", { de: "der Experte", tr: "uzman" }),
      word("İkinci", { de: "der Spezialist", tr: "uzman kişi" }),
      word("Üçüncü", { de: "die Spezialistin", tr: "kadın uzman" }),
      word("Dördüncü", { de: "der Fachmann", tr: "ehil kişi" }),
      word("Beşinci", { de: "die Fachfrau", tr: "ehil kadın" }),
      word("Altıncı", { de: "die Fachleute", tr: "uzmanlar" }, "çoğulu düzensiz"),
      word("Yedinci", { de: "das Institut", tr: "enstitü" }),
      word("Son", { de: "die Forschung", tr: "araştırma" }),
      { say: [tr("İlk kalıbımız emin olmadığını söylüyor. Soru sözcüğü olmayan sorularda bu bağlaç kullanılır ve fiil sona gider.")] },
      { say: [tr("Örnek:"), de("Wissen Sie, ob das Institut auch Kurse anbietet?"), tr("Tekrar edin:"), de("Wissen Sie, ob das Institut auch Kurse anbietet")], expect: repeat("Wissen Sie, ob das Institut auch Kurse anbietet") },
      { say: [tr("Sıra sende: 'Araştırmanın bittiğini biliyor musunuz?'")], expect: produce("Wissen Sie, ob die Forschung fertig ist", [tr("Bağlaçtan sonra fiil en sonda:"), de("Wissen Sie, ob die Forschung fertig ist?"), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız kibarca bilgi istiyor: dilek kipi ve soru sözcüğü bağlacı. Uzmanla konuşmanın standart açılışı.")] },
      { say: [tr("Şimdi: 'Bunun nasıl işlediğini öğrenmek isterdim.'")], expect: produce("Ich würde gern wissen, wie das funktioniert", [tr("Dilek kipi başta, bağlaçtan sonra fiil sonda:"), de("Ich würde gern wissen, wie das funktioniert."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich würde gern wissen, wie viel kostet das."), tr("cümlesi doğru mu?")], expect: truefalse("Ich würde gern wissen, wie viel kostet das.", false, [tr("Dolaylı soruda fiil öne gelmez, cümlenin sonuna gider:"), de("Ich würde gern wissen, wie viel das kostet.")]) },
      { say: [tr("Son: 'Uzmanların bu konuda ne düşündüğünü sorabilir miyim?'")], expect: produce("Darf ich fragen, was die Fachleute davon halten", [tr("Kibar giriş, bağlaç ve sonda fiil:"), de("Darf ich fragen, was die Fachleute davon halten?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir uzmana danışacak ve bilmediklerini soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir konuda uzman görüşü almak için bir enstitüyü aradın. Ne bilmek istediğini dolaylı sorularla soruyor ve bir randevu ayarlıyorsun.",
      partner: "kısa cevap veren ama zorlayınca açıklayan bir uzman",
      opening: "Institut für Forschung, guten Tag. Womit kann ich Ihnen helfen?",
      openingTr: "Araştırma Enstitüsü, iyi günler. Size nasıl yardımcı olabilirim?",
      goal: "En az üç soru dolaylı biçimde sorulmuş ve bir görüşme ayarlanmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-buero-alltag",
    icon: "office",
    level: "B1",
    course: "de",
    title: "Im Büro",
    titleTr: "Ofis günü",
    summary: "Ofiste yapılan işleri edilgen cümlelerle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "der Sekretär", tr: "sekreter" },
      { de: "die Sekretärin", tr: "kadın sekreter" },
      { de: "die Mitarbeiterin", tr: "kadın çalışan" },
      { de: "die Praktikantin", tr: "kadın stajyer" },
      { de: "die Konferenz", tr: "konferans" },
      { de: "die Präsentation", tr: "sunum" },
      { de: "das Seminar", tr: "seminer" },
      { de: "präsentieren", tr: "sunmak" },
    ],
    patterns: [
      { de: "Die Konferenz wird vorbereitet.", tr: "yapılan işi kişisiz anlatır" },
      { de: "Von wem wird das gemacht?", tr: "kimin yaptığını sorar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Ofiste bir gün. Ofis dili kişisizdir: kimin yaptığı değil, neyin yapıldığı konuşulur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgende yardımcı fiil ikinci sırada, ortaç sonda. Yapanı söylemek gerekirse ayrı bir edat kullanılır ve o edat yönelme hâli ister. Önce kelimeler.")] },
      word("İlk", { de: "der Sekretär", tr: "sekreter" }),
      word("İkinci", { de: "die Sekretärin", tr: "kadın sekreter" }),
      word("Üçüncü", { de: "die Mitarbeiterin", tr: "kadın çalışan" }),
      word("Dördüncü", { de: "die Praktikantin", tr: "kadın stajyer" }),
      word("Beşinci", { de: "die Konferenz", tr: "konferans" }),
      word("Altıncı", { de: "die Präsentation", tr: "sunum" }),
      word("Yedinci", { de: "das Seminar", tr: "seminer" }),
      word("Son", { de: "präsentieren", tr: "sunmak" }),
      { say: [tr("İlk kalıbımız işi anlatıyor. Yapanı söylemiyor çünkü ofiste iş kişiye değil role bağlıdır.")] },
      { say: [tr("Örnek:"), de("Die Konferenz wird gerade vorbereitet."), tr("Tekrar edin:"), de("Die Konferenz wird gerade vorbereitet")], expect: repeat("Die Konferenz wird gerade vorbereitet") },
      { say: [tr("Sıra sende: 'Sunum yarın yapılıyor.'")], expect: produce("Die Präsentation wird morgen gehalten", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Die Präsentation wird morgen gehalten."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız yapanı soruyor. Bu soru için özel bir edat var ve o edat yönelme hâli istiyor.")] },
      { say: [tr("Şimdi: 'Seminer kim tarafından veriliyor?'")], expect: produce("Von wem wird das Seminar gehalten", [tr("Edat başta, yardımcı fiil ikinci sırada, ortaç sonda:"), de("Von wem wird das Seminar gehalten?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Unterlagen wird von der Sekretärin kopiert."), tr("cümlesi doğru mu?")], expect: truefalse("Die Unterlagen wird von der Sekretärin kopiert.", false, [tr("Özne çoğul olduğunda yardımcı fiil de çoğula girer:"), de("Die Unterlagen werden von der Sekretärin kopiert.")]) },
      { say: [tr("Son: 'Sonuçlar stajyer tarafından sunuluyor.'")], expect: produce("Die Ergebnisse werden von der Praktikantin präsentiert", [tr("Çoğul özne, çoğul yardımcı fiil, yapan edatla:"), de("Die Ergebnisse werden von der Praktikantin präsentiert."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir ofis toplantısında işleri paylaştıracaksın.")] },
    ],
    roleplay: {
      scene: "Kısa bir ofis toplantısındasın. Haftanın işlerini sayıyor, kimin neyi yaptığını soruyor ve eksik kalanı paylaştırıyorsun.",
      partner: "işleri üstlenmeye istekli ama zamanı sınırlı bir iş arkadaşı",
      opening: "Also, kurz die Woche durchgehen — was wird bis Freitag alles gebraucht?",
      openingTr: "Peki, haftayı kısaca gözden geçirelim — cumaya kadar neler gerekiyor?",
      goal: "İşler sayılmış, kimin neyi yapacağı sorulmuş ve eksik işler paylaştırılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-arbeitsrecht",
    icon: "law",
    level: "B1",
    course: "de",
    title: "Was steht mir zu?",
    titleTr: "Çalışanın hakları",
    summary: "Geçmişte alınan kararları edilgen çatının geçmişiyle anlatmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "die Gewerkschaft", tr: "sendika" },
      { de: "der Betriebsrat", tr: "işçi konseyi" },
      { de: "die Arbeitserlaubnis", tr: "çalışma izni" },
      { de: "die Arbeitslosigkeit", tr: "işsizlik" },
      { de: "die Entlassung", tr: "işten çıkarma" },
      { de: "der Angestellte", tr: "çalışan" },
      { de: "die Beschäftigung", tr: "istihdam" },
      { de: "die Tätigkeit", tr: "faaliyet" },
    ],
    patterns: [
      { de: "Die Entlassung wurde … erklärt.", tr: "geçmişte alınan kararı anlatır" },
      { de: "Dagegen kann man vorgehen.", tr: "itiraz yolunun açık olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün çalışanın haklarını konuşacağız. Hukuk dili geçmişte alınan kararları hep kişisiz anlatır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgenin geçmişinde yardımcı fiil geçmiş biçimde ikinci sırada, ortaç sonda. Önce kelimeler.")] },
      word("İlk", { de: "die Gewerkschaft", tr: "sendika" }),
      word("İkinci", { de: "der Betriebsrat", tr: "işçi konseyi" }, "işyerinde çalışanları temsil eder"),
      word("Üçüncü", { de: "die Arbeitserlaubnis", tr: "çalışma izni" }),
      word("Dördüncü", { de: "die Arbeitslosigkeit", tr: "işsizlik" }),
      word("Beşinci", { de: "die Entlassung", tr: "işten çıkarma" }),
      word("Altıncı", { de: "der Angestellte", tr: "çalışan" }),
      word("Yedinci", { de: "die Beschäftigung", tr: "istihdam" }),
      word("Son", { de: "die Tätigkeit", tr: "faaliyet" }),
      { say: [tr("İlk kalıbımız kararı anlatıyor. Yardımcı fiil geçmiş biçiminde, ortaç sonda; kararı kimin verdiği söylenmiyor.")] },
      { say: [tr("Örnek:"), de("Die Entlassung wurde ohne Begründung erklärt."), tr("Tekrar edin:"), de("Die Entlassung wurde ohne Begründung erklärt")], expect: repeat("Die Entlassung wurde ohne Begründung erklärt") },
      { say: [tr("Sıra sende: 'Çalışma izni geçen ay verildi.'")], expect: produce("Die Arbeitserlaubnis wurde letzten Monat erteilt", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Die Arbeitserlaubnis wurde letzten Monat erteilt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız itiraz yolunu söylüyor: bir zarf ve belirsiz özne. Hak aramanın anahtar cümlesidir.")] },
      { say: [tr("Şimdi: 'Buna karşı itiraz edilebilir.'")], expect: produce("Dagegen kann man vorgehen", [tr("Zarf başta, modal fiil ikinci sırada, mastar sonda:"), de("Dagegen kann man vorgehen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Betriebsrat wurde nicht informieren."), tr("cümlesi doğru mu?")], expect: truefalse("Der Betriebsrat wurde nicht informieren.", false, [tr("Edilgende asıl fiil ortaç hâlinde olmalı:"), de("Der Betriebsrat wurde nicht informiert.")]) },
      { say: [tr("Son: 'Sendika tarafından bir toplantı düzenlendi.'")], expect: produce("Von der Gewerkschaft wurde eine Versammlung organisiert", [tr("Yapan edatla başta, yardımcı fiil ikinci sırada:"), de("Von der Gewerkschaft wurde eine Versammlung organisiert."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir sendika danışmanıyla durumunu konuşacaksın.")] },
    ],
    roleplay: {
      scene: "İşten çıkarıldın ve sendika danışmanına gittin. Ne olduğunu sırayla anlatıyor, haklarını soruyor ve ne yapacağını öğreniyorsun.",
      partner: "hakları iyi bilen, sakin bir sendika danışmanı",
      opening: "Setzen Sie sich. Erzählen Sie mir bitte — wann wurde Ihnen gekündigt?",
      openingTr: "Buyurun oturun. Lütfen anlatın — size ne zaman çıkış verildi?",
      goal: "Olay sırayla anlatılmış, haklar sorulmuş ve bir sonraki adım kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-chefin-gespraech",
    icon: "handshake",
    level: "B1",
    course: "de",
    title: "Ein Wort mit der Chefin",
    titleTr: "Yöneticiyle konuşma",
    summary: "Öneri ve ricayı dilek kipiyle kibarca sunmayı öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Chefin", tr: "kadın patron" },
      { de: "leiten", tr: "yönetmek" },
      { de: "die Leitung", tr: "yönetim" },
      { de: "einsetzen", tr: "görevlendirmek" },
      { de: "anstellen", tr: "işe almak" },
      { de: "vorschlagen", tr: "önermek" },
      { de: "mitteilen", tr: "bildirmek" },
      { de: "ausrichten", tr: "iletmek" },
    ],
    patterns: [
      { de: "Ich würde vorschlagen, dass …", tr: "öneriyi kibarca sunar" },
      { de: "Könnten Sie ihr bitte ausrichten, dass …?", tr: "mesaj iletmeyi rica eder" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yöneticinle konuşacaksın. Almanca iş dilinde öneri emir gibi durmamalı; dilek kipi bunu sağlıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dilek kipiyle sunulan öneri hem kibardır hem geri çekilebilir — muhatabın hayır demesi kolaylaşır ve bu bilinçli bir nezakettir. Önce kelimeler.")] },
      word("İlk", { de: "die Chefin", tr: "kadın patron" }),
      word("İkinci", { de: "leiten", tr: "yönetmek" }),
      word("Üçüncü", { de: "die Leitung", tr: "yönetim" }),
      word("Dördüncü", { de: "einsetzen", tr: "görevlendirmek" }),
      word("Beşinci", { de: "anstellen", tr: "işe almak" }),
      word("Altıncı", { de: "vorschlagen", tr: "önermek" }),
      word("Yedinci", { de: "mitteilen", tr: "bildirmek" }),
      word("Son", { de: "ausrichten", tr: "iletmek" }, "başkasına mesaj iletmek"),
      { say: [tr("İlk kalıbımız öneriyi sunuyor: dilek kipi ve bir yan cümle. Bağlaçtan sonra fiil sona gidiyor.")] },
      { say: [tr("Örnek:"), de("Ich würde vorschlagen, dass wir eine Person mehr anstellen."), tr("Tekrar edin:"), de("Ich würde vorschlagen, dass wir eine Person mehr anstellen")], expect: repeat("Ich würde vorschlagen, dass wir eine Person mehr anstellen") },
      { say: [tr("Sıra sende: 'Projeyi benim yönetmemi öneririm.'")], expect: produce("Ich würde vorschlagen, dass ich das Projekt leite", [tr("Bağlaçtan sonra fiil en sonda:"), de("Ich würde vorschlagen, dass ich das Projekt leite."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız mesaj iletmeyi rica ediyor: dilek kipiyle soru ve yan cümle. Ofiste çok geçen bir kalıp.")] },
      { say: [tr("Şimdi: 'Ona geç kalacağımı iletebilir misiniz?'")], expect: produce("Könnten Sie ihr bitte ausrichten, dass ich später komme", [tr("Yönelme hâlindeki kişi fiilden sonra, bağlaçtan sonra fiil sonda:"), de("Könnten Sie ihr bitte ausrichten, dass ich später komme?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich würde vorschlagen, dass setzen wir zwei Leute ein."), tr("cümlesi doğru mu?")], expect: truefalse("Ich würde vorschlagen, dass setzen wir zwei Leute ein.", false, [tr("Bağlaçtan sonra çekimli fiil cümlenin sonuna gider, önek ondan da sonra kalamaz:"), de("Ich würde vorschlagen, dass wir zwei Leute einsetzen.")]) },
      { say: [tr("Son: 'Kararı yönetime bugün bildiririm.'")], expect: produce("Ich teile der Leitung die Entscheidung heute mit", [tr("Ayrılabilen fiilin öneki cümlenin sonunda:"), de("Ich teile der Leitung die Entscheidung heute mit."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi yöneticinle bir öneri konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Yöneticinle kısa bir görüşmedesin. Ekipteki bir sorunu anlatıyor, bir çözüm öneriyor ve kararın nasıl duyurulacağını konuşuyorsun.",
      partner: "kısa konuşan, gerekçe isteyen bir yönetici",
      opening: "Sie wollten mich sprechen — worum geht es denn?",
      openingTr: "Benimle konuşmak istemiştiniz — konu nedir?",
      goal: "Sorun anlatılmış, bir öneri kibarca sunulmuş ve bir sonraki adım kararlaştırılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-stellensuche",
    icon: "mail",
    level: "B1",
    course: "de",
    title: "Auf Stellensuche",
    titleTr: "İş ararken",
    summary: "İş arama sürecini geçmiş katmanlarıyla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Plusquamperfekt",
    vocab: [
      { de: "die Arbeitsstelle", tr: "iş yeri" },
      { de: "der Arbeiter", tr: "işçi" },
      { de: "der Bauer", tr: "çiftçi" },
      { de: "die Bestätigung", tr: "onay yazısı" },
      { de: "der Kandidat", tr: "aday" },
      { de: "das Vorstellungsgespräch", tr: "iş görüşmesi" },
      { de: "die Umfrage", tr: "anket" },
      { de: "üblich", tr: "alışılmış" },
    ],
    patterns: [
      { de: "Nachdem ich … hatte, …", tr: "önce olan olayı geriye alır" },
      { de: "Das ist hier üblich.", tr: "bir şeyin normal olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! İş arama süreci hep iki katmanlıdır: başvurdum, sonra çağırdılar. Bugün o iki katmanı ayıracağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Daha eski katman ayrı bir geçmiş biçimiyle kurulur: yardımcı fiil geçmişte, asıl fiil ortaç hâlinde. Önce kelimeler.")] },
      word("İlk", { de: "die Arbeitsstelle", tr: "iş yeri" }),
      word("İkinci", { de: "der Arbeiter", tr: "işçi" }),
      word("Üçüncü", { de: "der Bauer", tr: "çiftçi" }),
      word("Dördüncü", { de: "die Bestätigung", tr: "onay yazısı" }),
      word("Beşinci", { de: "der Kandidat", tr: "aday" }),
      word("Altıncı", { de: "das Vorstellungsgespräch", tr: "iş görüşmesi" }),
      word("Yedinci", { de: "die Umfrage", tr: "anket" }),
      word("Son", { de: "üblich", tr: "alışılmış" }),
      { say: [tr("İlk kalıbımız sırayı kuruyor: önce olan yan cümlede eski geçmişle, sonra olan ana cümlede normal geçmişle.")] },
      { say: [tr("Örnek:"), de("Nachdem ich mich beworben hatte, kam die Bestätigung."), tr("Tekrar edin:"), de("Nachdem ich mich beworben hatte, kam die Bestätigung")], expect: repeat("Nachdem ich mich beworben hatte, kam die Bestätigung") },
      { say: [tr("Sıra sende: 'Onay yazısını aldıktan sonra görüşmeye gittim.'")], expect: produce("Nachdem ich die Bestätigung bekommen hatte, ging ich zum Vorstellungsgespräch", [tr("Yan cümlede eski geçmiş, ana cümle fiille başlıyor:"), de("Nachdem ich die Bestätigung bekommen hatte, ging ich zum Vorstellungsgespräch."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız bir şeyin normal olduğunu söylüyor. Yeni bir ülkede en çok ihtiyaç duyulan cümlelerden biri.")] },
      { say: [tr("Şimdi: 'Burada bu alışılmış bir şey.'")], expect: produce("Das ist hier üblich", [tr("Kısa ana cümle, fiil ikinci sırada:"), de("Das ist hier üblich."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nachdem der Kandidat gegangen war, wir haben entschieden."), tr("cümlesi doğru mu?")], expect: truefalse("Nachdem der Kandidat gegangen war, wir haben entschieden.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar:"), de("Nachdem der Kandidat gegangen war, haben wir entschieden.")]) },
      { say: [tr("Son: 'Anketi doldurduktan sonra iş yerini gezdim.'")], expect: produce("Nachdem ich die Umfrage ausgefüllt hatte, sah ich die Arbeitsstelle an", [tr("Yan cümlede eski geçmiş, ana cümlede ayrılabilen fiilin öneki sonda:"), de("Nachdem ich die Umfrage ausgefüllt hatte, sah ich die Arbeitsstelle an."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi iş arama sürecini bir arkadaşına anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın iş arıyor ve senin nasıl bulduğunu soruyor. Süreci sırayla anlatıyorsun: önce ne yaptın, sonra ne oldu.",
      partner: "aynı yolu yeni başlayan, her adımı soran bir arkadaş",
      opening: "Du hast es ja geschafft — wie ist das bei dir eigentlich gelaufen?",
      openingTr: "Sen başardın — sende bu süreç nasıl işledi?",
      goal: "Süreç en az dört adımda ve iki geçmiş katmanıyla anlatılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-projekt-praesentieren",
    icon: "chart",
    level: "B1",
    course: "de",
    title: "Zahlen im Projekt",
    titleTr: "Proje sunumu",
    summary: "Rakamları ikili bağlaçlarla dengeli sunmayı öğretir.",
    minutes: 10,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "die Studie", tr: "çalışma, araştırma" },
      { de: "analysieren", tr: "çözümlemek" },
      { de: "erstellen", tr: "hazırlamak" },
      { de: "enthalten", tr: "içermek" },
      { de: "insgesamt", tr: "toplamda" },
      { de: "ausreichend", tr: "yeterli" },
      { de: "gering", tr: "az" },
      { de: "häufig", tr: "sık sık" },
    ],
    patterns: [
      { de: "einerseits …, andererseits …", tr: "aynı konunun iki yanını söyler" },
      { de: "zwar …, aber …", tr: "kabul edip sonra çekince koyar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bir proje sunacaksın. İyi sunum tek yanlı değildir: rakamın hem güçlü hem zayıf yanını söyler. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki bağlaç kullanacağız: biri iki yanı yan yana koyuyor, öteki önce kabul edip sonra çekince koyuyor. Önce kelimeler.")] },
      word("İlk", { de: "die Studie", tr: "çalışma, araştırma" }),
      word("İkinci", { de: "analysieren", tr: "çözümlemek" }),
      word("Üçüncü", { de: "erstellen", tr: "hazırlamak" }),
      word("Dördüncü", { de: "enthalten", tr: "içermek" }),
      word("Beşinci", { de: "insgesamt", tr: "toplamda" }),
      word("Altıncı", { de: "ausreichend", tr: "yeterli" }),
      word("Yedinci", { de: "gering", tr: "az" }),
      word("Son", { de: "häufig", tr: "sık sık" }),
      { say: [tr("İlk kalıbımız iki yanı gösteriyor. Her iki bölüm de zarfla başladığı için ikisinde de fiil ikinci sıraya geçiyor.")] },
      { say: [tr("Örnek:"), de("Einerseits ist die Zahl gering, andererseits steigt sie häufig."), tr("Tekrar edin:"), de("Einerseits ist die Zahl gering, andererseits steigt sie häufig")], expect: repeat("Einerseits ist die Zahl gering, andererseits steigt sie häufig") },
      { say: [tr("Sıra sende: 'Bir yandan veri yeterli, öbür yandan çok eski.'")], expect: produce("Einerseits sind die Daten ausreichend, andererseits sind sie sehr alt", [tr("İki bölümde de fiil ikinci sırada:"), de("Einerseits sind die Daten ausreichend, andererseits sind sie sehr alt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız önce kabul ediyor sonra çekince koyuyor. İlk sözcük 'evet doğru ama' anlamını taşıyor.")] },
      { say: [tr("Şimdi: 'Çalışma gerçi kısa ama çok şey içeriyor.'")], expect: produce("Die Studie ist zwar kurz, aber sie enthält viel", [tr("İlk bölümde zarf ortada, ikinci bölüm zıtlık bağlacıyla:"), de("Die Studie ist zwar kurz, aber sie enthält viel."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Einerseits es ist teuer, andererseits ist es schnell."), tr("cümlesi doğru mu?")], expect: truefalse("Einerseits es ist teuer, andererseits ist es schnell.", false, [tr("Cümle bu zarfla başlayınca çekimli fiil ikinci sıraya gelir:"), de("Einerseits ist es teuer, andererseits ist es schnell.")]) },
      { say: [tr("Son: 'Toplamda üç çalışma çözümlendi.'")], expect: produce("Insgesamt wurden drei Studien analysiert", [tr("Zarf başta, çoğul özne için çoğul yardımcı fiil:"), de("Insgesamt wurden drei Studien analysiert."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi projenin sonuçlarını sunacaksın.")] },
    ],
    roleplay: {
      scene: "Küçük bir ekibe proje sonuçlarını sunuyorsun. Her rakamın iki yanını söylüyor ve gelen itirazları dengeli biçimde yanıtlıyorsun.",
      partner: "rakamlara güvenmeyen, kaynak soran bir ekip arkadaşı",
      opening: "Bevor du anfängst — woher kommen diese Zahlen eigentlich?",
      openingTr: "Başlamadan önce — bu rakamlar aslında nereden geliyor?",
      goal: "Kaynak açıklanmış, en az iki rakamın iki yanı söylenmiş ve bir itiraz yanıtlanmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-selbststaendig",
    icon: "money",
    level: "B1",
    course: "de",
    title: "Sich selbstständig machen",
    titleTr: "Kendi işini kurmak",
    summary: "Bir kararın amacını damit yan cümlesiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-damit",
    vocab: [
      { de: "gründen", tr: "kurmak" },
      { de: "produzieren", tr: "üretmek" },
      { de: "der Handel", tr: "ticaret" },
      { de: "handeln", tr: "ticaret yapmak" },
      { de: "die Aktion", tr: "kampanya" },
      { de: "garantieren", tr: "garanti etmek" },
      { de: "fällig", tr: "vadesi gelmiş" },
      { de: "weltweit", tr: "dünya çapında" },
    ],
    patterns: [
      { de: "…, damit die Kunden zufrieden sind", tr: "amaç söyler; özne farklıdır" },
      { de: "Ich gründe eine Firma, um … zu …", tr: "özne aynıysa amacı mastarla söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Kendi işini kurmayı düşünüyorsun. Her kararın bir amacı olacak ve o amacı söylemen gerekecek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amaç iki biçimde söylenir: özne farklıysa yan cümleyle, aynıysa mastar öbeğiyle. Bu ayrım Türkçede yok, o yüzden dikkat ister. Önce kelimeler.")] },
      word("İlk", { de: "gründen", tr: "kurmak" }),
      word("İkinci", { de: "produzieren", tr: "üretmek" }),
      word("Üçüncü", { de: "der Handel", tr: "ticaret" }),
      word("Dördüncü", { de: "handeln", tr: "ticaret yapmak" }, "bir de 'davranmak' anlamı var"),
      word("Beşinci", { de: "die Aktion", tr: "kampanya" }),
      word("Altıncı", { de: "garantieren", tr: "garanti etmek" }),
      word("Yedinci", { de: "fällig", tr: "vadesi gelmiş" }),
      word("Son", { de: "weltweit", tr: "dünya çapında" }),
      { say: [tr("İlk kalıbımız amacı yan cümleyle söylüyor. Özne farklı: ben yapıyorum ki MÜŞTERİ memnun olsun.")] },
      { say: [tr("Örnek:"), de("Wir liefern schnell, damit die Kunden zufrieden sind."), tr("Tekrar edin:"), de("Wir liefern schnell, damit die Kunden zufrieden sind")], expect: repeat("Wir liefern schnell, damit die Kunden zufrieden sind") },
      { say: [tr("Sıra sende: 'Bir kampanya yapıyoruz ki insanlar bizi tanısın.'")], expect: produce("Wir machen eine Aktion, damit die Leute uns kennen", [tr("Bağlaçtan sonra fiil en sonda:"), de("Wir machen eine Aktion, damit die Leute uns kennen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız özne aynıyken kullanılıyor: mastar öbeği. Yan cümle kurmaya gerek kalmıyor.")] },
      { say: [tr("Şimdi: 'Bağımsız olmak için bir şirket kuruyorum.'")], expect: produce("Ich gründe eine Firma, um unabhängig zu sein", [tr("Özne aynı olduğu için mastar öbeği yeter:"), de("Ich gründe eine Firma, um unabhängig zu sein."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich produziere selbst, damit ich spare Geld."), tr("cümlesi doğru mu?")], expect: truefalse("Ich produziere selbst, damit ich spare Geld.", false, [tr("Bu bağlaçtan sonra çekimli fiil cümlenin sonuna gider; özne aynı olduğu için mastar öbeği de kullanılabilirdi:"), de("Ich produziere selbst, um Geld zu sparen.")]) },
      { say: [tr("Son: 'Fatura yarın vadesi geliyor, dünya çapında satış yapıyoruz.'")], expect: produce("Die Rechnung ist morgen fällig, wir verkaufen weltweit", [tr("İki ana cümle, ikisinde de fiil ikinci sırada:"), de("Die Rechnung ist morgen fällig, wir verkaufen weltweit."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi iş fikrini bir danışmana anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir işletme danışmanına iş fikrini anlatıyorsun: ne üreteceksin, kime satacaksın, her kararın amacı ne.",
      partner: "riskleri sorgulayan ama destekleyici bir işletme danışmanı",
      opening: "Erzählen Sie mal von Ihrer Idee — was genau wollen Sie gründen?",
      openingTr: "Fikrinizi anlatın bakalım — tam olarak ne kurmak istiyorsunuz?",
      goal: "İş fikri anlatılmış, en az üç kararın amacı söylenmiş ve bir risk konuşulmuş olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-arbeitszufriedenheit",
    icon: "feelings",
    level: "B1",
    course: "de",
    title: "Macht die Arbeit noch Spaß?",
    titleTr: "İşten memnun muyuz?",
    summary: "İşten memnuniyeti edatı sabit fiillerle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Verben-mit-Präpositionen",
    vocab: [
      { de: "anstrengend", tr: "yorucu" },
      { de: "sich langweilen", tr: "canı sıkılmak" },
      { de: "die Langeweile", tr: "can sıkıntısı" },
      { de: "sich bemühen", tr: "çaba göstermek" },
      { de: "angenehm", tr: "hoş" },
      { de: "gewohnt", tr: "alışkın" },
      { de: "körperlich", tr: "bedensel" },
      { de: "nebenbei", tr: "bir yandan" },
    ],
    patterns: [
      { de: "sich bemühen um + Akkusativ", tr: "bir şey için çaba gösterir" },
      { de: "gewohnt sein an + Akkusativ", tr: "bir şeye alışkın olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi: işinden memnun musun? Bu konuşmanın fiilleri edatını sabit taşıyor ve yanlış edat cümleyi bozuyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki fiilin de edatı ezberlenir, mantığı yoktur. İkisi de belirtme hâli istiyor. Önce kelimeler.")] },
      word("İlk", { de: "anstrengend", tr: "yorucu" }),
      word("İkinci", { de: "sich langweilen", tr: "canı sıkılmak" }),
      word("Üçüncü", { de: "die Langeweile", tr: "can sıkıntısı" }),
      word("Dördüncü", { de: "sich bemühen", tr: "çaba göstermek" }),
      word("Beşinci", { de: "angenehm", tr: "hoş" }),
      word("Altıncı", { de: "gewohnt", tr: "alışkın" }),
      word("Yedinci", { de: "körperlich", tr: "bedensel" }),
      word("Son", { de: "nebenbei", tr: "bir yandan" }),
      { say: [tr("İlk kalıbımız çabayı söylüyor: dönüşlü fiil ve sabit edat. Edattan sonra belirtme hâli geliyor.")] },
      { say: [tr("Örnek:"), de("Ich bemühe mich um eine bessere Stelle."), tr("Tekrar edin:"), de("Ich bemühe mich um eine bessere Stelle")], expect: repeat("Ich bemühe mich um eine bessere Stelle") },
      { say: [tr("Sıra sende: 'Daha hoş bir çalışma ortamı için çaba gösteriyorum.'")], expect: produce("Ich bemühe mich um ein angenehmes Arbeitsklima", [tr("Edat sabit, ad belirtme hâlinde:"), de("Ich bemühe mich um ein angenehmes Arbeitsklima."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız alışkanlığı söylüyor: bir sıfat ve sabit edat. Bu edat da belirtme hâli istiyor.")] },
      { say: [tr("Şimdi: 'Bedensel işe alışkınım.'")], expect: produce("Ich bin an körperliche Arbeit gewöhnt", [tr("Edat belirtme hâli istiyor, sıfat sonda:"), de("Ich bin an körperliche Arbeit gewöhnt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich bemühe mich für eine neue Stelle."), tr("cümlesi doğru mu?")], expect: truefalse("Ich bemühe mich für eine neue Stelle.", false, [tr("Bu fiilin edatı sabittir ve başka bir edatla değiştirilemez:"), de("Ich bemühe mich um eine neue Stelle.")]) },
      { say: [tr("Son: 'İş yorucu ama bir yandan can sıkıcı da.'")], expect: produce("Die Arbeit ist anstrengend, aber nebenbei auch langweilig", [tr("İki bölüm zıtlık bağlacıyla birleşiyor:"), de("Die Arbeit ist anstrengend, aber nebenbei auch langweilig."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir iş arkadaşınla işten memnun olup olmadığınızı konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir iş arkadaşınla öğle arasında konuşuyorsunuz: iş yorucu mu, sıkıcı mı, neyi değiştirmek isterdiniz.",
      partner: "işinden şikâyet eden ama ayrılmayı da düşünmeyen bir iş arkadaşı",
      opening: "Sag mal ehrlich — macht dir die Arbeit eigentlich noch Spaß?",
      openingTr: "Dürüstçe söyle — iş sana hâlâ keyif veriyor mu?",
      goal: "İşin iyi ve zor yanları söylenmiş, bir değişiklik isteği dile getirilmiş olur.",
      minTurns: 8,
    },
  },
];
