import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 2 — Müzakere ve şikâyet (011–020).
 *
 * Bu modülün konusu tek kelimeyle DİPLOMASİ. B1'de öğrenci itirazını
 * söyleyebiliyordu; B2'de itirazını karşı tarafı kaybetmeden söylemesi
 * gerekiyor ve Almanca bunu iki araçla yapıyor: dilek kipi (karar yerine
 * öneri) ve isimleşmiş resmî dil (kişi yerine mesele).
 *
 * Türkçe konuşan için tuzak şurada: Türkçede sertlik tonla ayarlanır, Almanca
 * yazışmada ise DİLBİLGİSİYLE. "Fesih ediyorum" ile "kendimi feshetmek
 * zorunda görüyorum" arasındaki fark bir kibarlık süsü değil, hukuki bir
 * kayıt farkıdır — ve bu modül o farkı çalıştırıyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B02: Lesson[] = [
  {
    id: "de-b2-verhandeln",
    icon: "money",
    level: "B2",
    course: "de",
    title: "Der Preis ist verhandelbar",
    titleTr: "Pazarlık",
    summary: "Fiyat ve koşul pazarlığını dilek kipiyle, kapıyı kapatmadan yürütmeyi öğretir.",
    minutes: 11,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "verhandeln", tr: "pazarlık etmek" },
      { de: "der Spielraum", tr: "pazarlık payı" },
      { de: "das Entgegenkommen", tr: "jest, esneklik" },
      { de: "die Konditionen", tr: "koşullar" },
      { de: "sich einigen", tr: "anlaşmak" },
    ],
    patterns: [
      { de: "Wir könnten uns … vorstellen.", tr: "teklifi öneri olarak sunar" },
      { de: "Kämen Sie uns bei … entgegen?", tr: "karşı taraftan jest ister" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: müzakere. Pazarlıkta Almancanın kuralı basit — kesin cümle kurarsan karşı tarafın geri adım alanı kalmaz. O yüzden teklif dilek kipiyle söylenir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Kırk euro veriyoruz' bir karardır; 'kırk euroyu düşünebiliriz' bir tekliftir. İkisi de aynı rakam ama ikincisi konuşmayı sürdürür. Önce kelimeler.")] },
      word("İlk", { de: "verhandeln", tr: "pazarlık etmek" }),
      word("İkinci", { de: "der Spielraum", tr: "pazarlık payı" }),
      word("Üçüncü", { de: "das Entgegenkommen", tr: "jest, esneklik" }),
      word("Dördüncü", { de: "die Konditionen", tr: "koşullar" }),
      word("Son", { de: "sich einigen", tr: "anlaşmak" }),
      { say: [tr("Kalıbımız:"), de("Wir könnten uns … vorstellen."), tr("Kelimesi kelimesine 'düşünebilirdik'; iş dilinde 'şuna varız' demektir.")] },
      { say: [tr("Örnek:"), de("Wir könnten uns einen Preis von vierzig Euro vorstellen."), tr("Tekrar edin:"), de("Wir könnten uns einen Preis von vierzig Euro vorstellen")], expect: repeat("Wir könnten uns einen Preis von vierzig Euro vorstellen") },
      { say: [tr("Sıra sende: 'Fiyatta biraz payınız var mı?'")], expect: produce("Haben Sie beim Preis noch etwas Spielraum", [tr("Fiil başta soru; edat öbeği ortada:"), de("Haben Sie beim Preis noch etwas Spielraum?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi jest iste: 'Miktar konusunda bize biraz yaklaşır mısınız?'")], expect: produce("Kämen Sie uns bei der Menge entgegen", [tr("Gelmek fiilinin dilek kipi kämen; ayrılabilen önek sonda:"), de("Kämen Sie uns bei der Menge entgegen?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu koşullarla kabul edebilirdik.'")], expect: produce("Zu diesen Konditionen könnten wir zusagen", [tr("Tümleç başta, dilek kipi ikinci sırada, mastar sonda:"), de("Zu diesen Konditionen könnten wir zusagen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Kämen Sie uns bei der Menge entgegen?"), tr("cümlesi doğru mu?")], expect: truefalse("Kämen Sie uns bei der Menge entgegen?", true, [tr("Doğru. Dilek kipi soruyu bir ricaya çeviriyor ve ayrılabilen fiilin öneki cümlenin sonunda duruyor.")]) },
      { say: [tr("Son: 'Ortada bir yerde anlaşalım.'")], expect: produce("Einigen wir uns auf die Mitte", [tr("Rica biçiminde fiil başta; dönüşlü zamir hemen sonra:"), de("Einigen wir uns auf die Mitte."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir tedarikçiyle fiyat pazarlığı yapacaksın: teklifini sun, jest iste ve bir rakamda anlaş.")] },
    ],
    roleplay: {
      scene: "Bir tedarikçiyle yıllık sözleşmenin fiyatını pazarlık ediyorsun. Teklifini dilek kipiyle sun, jest iste, karşı teklife tepki ver ve bir rakamda ya da koşulda anlaş.",
      partner: "deneyimli, kolay indirim vermeyen ama ilişkiyi önemseyen bir satış müdürü",
      opening: "Unser Angebot liegt bei achtundvierzig Euro pro Einheit. Was schwebt Ihnen denn vor?",
      openingTr: "Teklifimiz birim başına kırk sekiz euro. Sizin aklınızda ne var?",
      goal: "Karşılıklı teklifler sunulmuş ve bir fiyat ya da koşul üzerinde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-beschwerde-formell",
    icon: "mail",
    level: "B2",
    course: "de",
    title: "Die formelle Beschwerde",
    titleTr: "Resmî şikâyet",
    summary: "Resmî şikâyet mektubunun isimleşmiş, mesafeli dilini kurmayı öğretir.",
    minutes: 11,
    focusId: "Nominalisierung",
    vocab: [
      { de: "das Schreiben", tr: "resmî yazı" },
      { de: "die Stellungnahme", tr: "görüş bildirme" },
      { de: "sich gezwungen sehen", tr: "mecbur kalmak" },
      { de: "die Bearbeitung", tr: "işleme alma" },
      { de: "unzumutbar", tr: "kabul edilemez" },
    ],
    patterns: [
      { de: "Bezug nehmend auf …", tr: "yazıya atıf yapar" },
      { de: "Ich sehe mich gezwungen, … zu …", tr: "mecburiyeti mesafeli söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün resmî şikâyet yazacağız. Burada dikkat: Almanca resmî yazışmada öfke tonla değil, dilbilgisiyle taşınır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kilit fark şu: 'sözleşmeyi feshediyorum' bir tehdittir, 'kendimi feshetmek zorunda görüyorum' bir kayıttır. İkincisi daha sert bir belgedir ama daha kibar durur. Önce kelimeler.")] },
      word("İlk", { de: "das Schreiben", tr: "resmî yazı" }),
      word("İkinci", { de: "die Stellungnahme", tr: "görüş bildirme" }),
      word("Üçüncü", { de: "sich gezwungen sehen", tr: "mecbur kalmak" }),
      word("Dördüncü", { de: "die Bearbeitung", tr: "işleme alma" }),
      word("Son", { de: "unzumutbar", tr: "kabul edilemez" }),
      { say: [tr("Kalıbımız:"), de("Bezug nehmend auf …"), tr("Mektubun ilk cümlesi neredeyse her zaman budur: neye atıf yapıldığı baştan söylenir.")] },
      { say: [tr("Örnek:"), de("Bezug nehmend auf Ihr Schreiben vom dritten Mai teile ich Ihnen Folgendes mit."), tr("Tekrar edin:"), de("Bezug nehmend auf Ihr Schreiben vom dritten Mai teile ich Ihnen Folgendes mit")], expect: repeat("Bezug nehmend auf Ihr Schreiben vom dritten Mai teile ich Ihnen Folgendes mit") },
      { say: [tr("Sıra sende: 'Sözleşmeyi feshetmek zorunda kalıyorum.'")], expect: produce("Ich sehe mich gezwungen, den Vertrag zu kündigen", [tr("Dönüşlü fiil, sonra virgülle mastar öbeği:"), de("Ich sehe mich gezwungen, den Vertrag zu kündigen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sizden on dört gün içinde görüş bildirmenizi rica ediyorum.'")], expect: produce("Ich bitte Sie um eine Stellungnahme innerhalb von vierzehn Tagen", [tr("bitten fiili um edatıyla; süre en sonda:"), de("Ich bitte Sie um eine Stellungnahme innerhalb von vierzehn Tagen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, tamamen isimleştirerek: 'İşlemin bu kadar gecikmesi kabul edilemez.'")], expect: produce("Die Verzögerung der Bearbeitung ist unzumutbar", [tr("İki isim tamlama hâlinde bağlanıyor, hüküm sonda:"), de("Die Verzögerung der Bearbeitung ist unzumutbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich sehe mich gezwungen, den Vertrag kündigen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich sehe mich gezwungen, den Vertrag kündigen.", false, [tr("Mastar öbeğinde zu eksik:"), de("Ich sehe mich gezwungen, den Vertrag zu kündigen.")]) },
      { say: [tr("Son: 'On iki Mart tarihli faturanıza atıfla yazıyorum.'")], expect: produce("Bezug nehmend auf Ihre Rechnung vom zwölften März schreibe ich Ihnen", [tr("Uzun tümleçten sonra fiil ikinci öğe olarak gelir:"), de("Bezug nehmend auf Ihre Rechnung vom zwölften März schreibe ich Ihnen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir müşteri hizmetleri sorumlusuyla şikâyetini resmî dille anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir müşteri hizmetleri sorumlusuyla telefondasın ve resmî bir şikâyeti dile getiriyorsun: neye atıf yapıyorsun, sorun ne, ne talep ediyorsun ve ne kadar süre tanıyorsun.",
      partner: "kibar ama sorumluluğu üstlenmekten kaçınan bir müşteri hizmetleri sorumlusu",
      opening: "Sie haben uns bereits geschrieben, richtig? Nennen Sie mir bitte kurz, worum es genau geht.",
      openingTr: "Bize daha önce yazmıştınız, değil mi? Kısaca tam olarak neyle ilgili olduğunu söyleyin lütfen.",
      goal: "Şikâyetin konusu ve gerekçesi anlatılmış, somut bir talep ile süre bildirilmiş ve karşı tarafın ne yapacağı söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-hotline",
    icon: "phone",
    level: "B2",
    course: "de",
    title: "In der Warteschleife",
    titleTr: "Çağrı merkezinde",
    summary: "Arızayı tarif etmeyi ve edilgen yerine geçen yapılarla çözüm istemeyi öğretir.",
    minutes: 11,
    focusId: "Passiversatz",
    vocab: [
      { de: "die Warteschleife", tr: "bekleme hattı" },
      { de: "verbinden", tr: "bağlamak (telefonda)" },
      { de: "die Störung", tr: "arıza" },
      { de: "der Sachbearbeiter", tr: "ilgili görevli" },
      { de: "sich melden", tr: "dönüş yapmak" },
    ],
    patterns: [
      { de: "Das Problem lässt sich …", tr: "çözülebilirliği söyler" },
      { de: "Es ist zu klären, ob/wo …", tr: "netleşmesi gerekeni söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün çağrı merkezi. Burada iki taraf da edilgen konuşur: kimse 'ben yaptım' demez, 'yapılabilir' ya da 'açıklığa kavuşturulması gerekiyor' der. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yapıların Almancada üç biçimi vardı ve ikisini geçen modülde gördün. Bugün onları telefonun hızında kullanacaksın. Önce kelimeler.")] },
      word("İlk", { de: "die Warteschleife", tr: "bekleme hattı" }),
      word("İkinci", { de: "verbinden", tr: "bağlamak (telefonda)" }),
      word("Üçüncü", { de: "die Störung", tr: "arıza" }),
      word("Dördüncü", { de: "der Sachbearbeiter", tr: "ilgili görevli" }),
      word("Son", { de: "sich melden", tr: "dönüş yapmak" }),
      { say: [tr("Kalıbımız:"), de("Es ist zu klären, ob …"), tr("Kim netleştirecek belli değil; önemli olan netleşmesi gerektiği. Resmî dilin tam kalbi.")] },
      { say: [tr("Örnek:"), de("Das Problem lässt sich meistens aus der Ferne lösen."), tr("Tekrar edin:"), de("Das Problem lässt sich meistens aus der Ferne lösen")], expect: repeat("Das Problem lässt sich meistens aus der Ferne lösen") },
      { say: [tr("Sıra sende: 'Beni ilgili görevliye bağlayabilir misiniz?'")], expect: produce("Können Sie mich mit dem Sachbearbeiter verbinden", [tr("Modal fiil başta soru; mastar en sonda:"), de("Können Sie mich mit dem Sachbearbeiter verbinden?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Arızanın nereden geldiğinin açıklığa kavuşturulması gerekiyor.'")], expect: produce("Es ist zu klären, woher die Störung kommt", [tr("Sahte özne es, sonra yan cümlede fiil sonda:"), de("Es ist zu klären, woher die Störung kommt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yirmi dakikadır bekleme hattındayım.'")], expect: produce("Ich bin seit zwanzig Minuten in der Warteschleife", [tr("Süre seit ile, yönelme hâlinde:"), de("Ich bin seit zwanzig Minuten in der Warteschleife."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es ist zu klären, woher kommt die Störung."), tr("cümlesi doğru mu?")], expect: truefalse("Es ist zu klären, woher kommt die Störung.", false, [tr("Dolaylı soru bir yan cümledir, fiil sona gider:"), de("Es ist zu klären, woher die Störung kommt.")]) },
      { say: [tr("Son: 'Yarına kadar bana dönmenizi rica ediyorum.'")], expect: produce("Ich bitte Sie, sich bis morgen bei mir zu melden", [tr("Mastar öbeğinde dönüşlü zamir başta, zu ile mastar sonda:"), de("Ich bitte Sie, sich bis morgen bei mir zu melden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir teknik destek hattını arayacaksın: arızayı tarif et, ne denediğini söyle ve bir çözüm ya da randevu al.")] },
    ],
    roleplay: {
      scene: "İnternetin üç gündür kesik ve teknik destek hattını aradın. Arızayı tarif et, ne denediğini söyle, ne zaman düzeleceğini sor ve bir çözüm ya da teknisyen randevusu al.",
      partner: "senaryodan okuyan, önce standart soruları soran bir destek görevlisi",
      opening: "Technischer Support, mein Name ist Weber. Beschreiben Sie mir bitte die Störung — seit wann besteht sie?",
      openingTr: "Teknik destek, ben Weber. Arızayı tarif eder misiniz — ne zamandır sürüyor?",
      goal: "Arıza tarif edilmiş, denenenler söylenmiş ve bir çözüm ya da teknisyen randevusu kararlaştırılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-schadenersatz",
    icon: "law",
    level: "B2",
    course: "de",
    title: "Wer zahlt den Schaden?",
    titleTr: "Tazminat talebi",
    summary: "Zararın sebebini ve hak talebini Genitiv edatlarıyla kurmayı öğretir.",
    minutes: 11,
    focusId: "Genitivpräpositionen",
    vocab: [
      { de: "der Schadenersatz", tr: "tazminat" },
      { de: "infolge", tr: "sonucunda" },
      { de: "der Anspruch", tr: "hak talebi" },
      { de: "haften", tr: "sorumlu olmak" },
      { de: "die Erstattung", tr: "geri ödeme" },
    ],
    patterns: [
      { de: "wegen / infolge + Genitiv", tr: "resmî sebep bildirir" },
      { de: "Anspruch auf … haben", tr: "hak talebini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün para isteyeceğiz — ama hukuk diliyle. Bu dilde sebep bildiren edatlar tamlayan hâli ister ve doğru kullanılmadığında talep amatör durur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de kalıplaşmış bir ifade öğreneceğiz: 'bir şeye hakkı olmak'. Almancada bu, isimle ve sabit bir edatla kurulur. Önce kelimeler.")] },
      word("İlk", { de: "der Schadenersatz", tr: "tazminat" }),
      word("İkinci", { de: "infolge", tr: "sonucunda" }),
      word("Üçüncü", { de: "der Anspruch", tr: "hak talebi" }),
      word("Dördüncü", { de: "haften", tr: "sorumlu olmak" }),
      word("Son", { de: "die Erstattung", tr: "geri ödeme" }),
      { say: [tr("Kalıbımız:"), de("Anspruch auf … haben"), tr("Edat sabittir ve arkasından belirtme hâli gelir; ezberlenmesi gereken bir birliktelik.")] },
      { say: [tr("Örnek:"), de("Wegen des Schadens fordere ich eine Erstattung."), tr("Tekrar edin:"), de("Wegen des Schadens fordere ich eine Erstattung")], expect: repeat("Wegen des Schadens fordere ich eine Erstattung") },
      { say: [tr("Sıra sende: 'Gecikme sonucunda ek masraflar doğdu.'")], expect: produce("Infolge der Verspätung sind zusätzliche Kosten entstanden", [tr("Edat tamlayan hâli ister; ortaç en sonda:"), de("Infolge der Verspätung sind zusätzliche Kosten entstanden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Tazminat hakkım olduğunu düşünüyorum.'")], expect: produce("Ich denke, dass ich Anspruch auf Schadenersatz habe", [tr("Yan cümlede fiil sonda; kalıptaki edat değişmez:"), de("Ich denke, dass ich Anspruch auf Schadenersatz habe."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Zarardan kim sorumlu?'")], expect: produce("Wer haftet für den Schaden", [tr("Soru zamiri özne; fiilin sabit edatı für:"), de("Wer haftet für den Schaden?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Infolge der Verspätung sind zusätzliche Kosten entstanden."), tr("cümlesi doğru mu?")], expect: truefalse("Infolge der Verspätung sind zusätzliche Kosten entstanden.", true, [tr("Doğru. Edattan sonra tamlayan hâli var, hareket fiili sein ile çekilmiş ve ortaç sonda.")]) },
      { say: [tr("Son: 'Masrafların geri ödenmesini talep ediyorum.'")], expect: produce("Ich fordere die Erstattung der Kosten", [tr("İki isim tamlama hâlinde bağlanır:"), de("Ich fordere die Erstattung der Kosten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir sigorta ya da firma temsilcisinden zararının karşılanmasını isteyeceksin.")] },
    ],
    roleplay: {
      scene: "Bir nakliye firmasının temsilcisiyle konuşuyorsun: taşınmada eşyan hasar gördü. Ne olduğunu anlat, sorumluluğun kimde olduğunu söyle, talebini rakamla belirt ve süreç hakkında bilgi al.",
      partner: "sorumluluğu paylaştırmaya çalışan, belge isteyen bir firma temsilcisi",
      opening: "Ich habe Ihren Schadensfall vor mir. Schildern Sie mir bitte: Was genau ist passiert?",
      openingTr: "Hasar dosyanız önümde. Anlatır mısınız: Tam olarak ne oldu?",
      goal: "Zarar anlatılmış, sorumluluk konuşulmuş, rakamlı bir talep iletilmiş ve sürecin nasıl işleyeceği öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-kompromiss",
    icon: "handshake",
    level: "B2",
    course: "de",
    title: "Der goldene Mittelweg",
    titleTr: "Uzlaşma",
    summary: "İki taraflı bağlaçlarla taviz ve uzlaşma cümleleri kurmayı öğretir.",
    minutes: 11,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "das Zugeständnis", tr: "taviz" },
      { de: "nachgeben", tr: "geri adım atmak" },
      { de: "die Einigung", tr: "uzlaşma" },
      { de: "beiderseitig", tr: "karşılıklı" },
      { de: "tragfähig", tr: "sürdürülebilir" },
    ],
    patterns: [
      { de: "zwar …, aber …", tr: "kabul edip sınır koyar" },
      { de: "sowohl … als auch …", tr: "iki tarafı birlikte anar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Uzlaşmanın dili iki parçalıdır: önce karşı tarafa hak verirsin, sonra kendi sınırını koyarsın. Almanca bunu çift bağlaçlarla yapar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("En işlevlisi 'gerçi ama' ikilisi: 'gerçi ideal değil, ama iki taraf için de taşınabilir'. Tek cümlede hem anlayış hem sınır var. Önce kelimeler.")] },
      word("İlk", { de: "das Zugeständnis", tr: "taviz" }),
      word("İkinci", { de: "nachgeben", tr: "geri adım atmak" }),
      word("Üçüncü", { de: "die Einigung", tr: "uzlaşma" }),
      word("Dördüncü", { de: "beiderseitig", tr: "karşılıklı" }),
      word("Son", { de: "tragfähig", tr: "sürdürülebilir" }),
      { say: [tr("Kalıbımız:"), de("zwar …, aber …"), tr("İlk parça ana cümlenin içinde durur, ikinci parça yeni bir ana cümle açar.")] },
      { say: [tr("Örnek:"), de("Das ist zwar nicht ideal, aber für beide Seiten tragfähig."), tr("Tekrar edin:"), de("Das ist zwar nicht ideal, aber für beide Seiten tragfähig")], expect: repeat("Das ist zwar nicht ideal, aber für beide Seiten tragfähig") },
      { say: [tr("Sıra sende: 'Hem sizin taraf hem bizim taraf kazanmalı.'")], expect: produce("Sowohl Ihre Seite als auch unsere Seite muss gewinnen", [tr("Çift bağlacın iki parçası iki özneyi kucaklar:"), de("Sowohl Ihre Seite als auch unsere Seite muss gewinnen."), tr("Tekrar dene.")], ["Sowohl Ihre als auch unsere Seite muss gewinnen"]) },
      { say: [tr("Şimdi: 'Bir taviz vermeye hazırım.'")], expect: produce("Ich bin bereit, ein Zugeständnis zu machen", [tr("Sıfattan sonra virgülle mastar öbeği:"), de("Ich bin bereit, ein Zugeständnis zu machen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Fiyatta geri adım atmam, ama tarihte esneğim.'")], expect: produce("Beim Preis gebe ich nicht nach, aber beim Termin bin ich flexibel", [tr("Tümleç başta olduğu için fiil ikinci sırada, önek sonda:"), de("Beim Preis gebe ich nicht nach, aber beim Termin bin ich flexibel."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Beim Preis ich gebe nicht nach."), tr("cümlesi doğru mu?")], expect: truefalse("Beim Preis ich gebe nicht nach.", false, [tr("Cümle tümleçle başlayınca özne fiilin arkasına geçer:"), de("Beim Preis gebe ich nicht nach.")]) },
      { say: [tr("Son: 'Sonunda bir uzlaşmaya vardık.'")], expect: produce("Am Ende sind wir zu einer Einigung gekommen", [tr("Hareket fiili sein ile çekilir, ortaç sonda:"), de("Am Ende sind wir zu einer Einigung gekommen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada tıkanmış bir pazarlığı uzlaşmayla bitireceksin.")] },
    ],
    roleplay: {
      scene: "Bir ortak projede iki taraf tıkandı: sen tarihte, karşı taraf bütçede esnemiyor. Karşı tarafa hak verdiğin noktayı söyle, kendi sınırını koy, bir taviz öner ve ortak bir çözümde anlaş.",
      partner: "haklı gerekçeleri olan, ama uzlaşmaya açık bir proje ortağı",
      opening: "Wir drehen uns im Kreis. Sagen Sie mir ehrlich: Wo können Sie wirklich nicht nachgeben?",
      openingTr: "Aynı yerde dönüyoruz. Açık söyleyin: Gerçekten nerede geri adım atamıyorsunuz?",
      goal: "Her iki tarafın sınırı söylenmiş, bir taviz önerilmiş ve iki tarafın da kabul ettiği bir çözümde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-eskalation",
    icon: "feelings",
    level: "B2",
    course: "de",
    title: "Ruhig bleiben",
    titleTr: "Gerilimi düşürmek",
    summary: "Öfkeli bir muhatabı anlayış ve dilek kipiyle yatıştırmayı öğretir.",
    minutes: 11,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "eskalieren", tr: "tırmanmak" },
      { de: "sachlich", tr: "nesnel" },
      { de: "nachvollziehen", tr: "anlayışla karşılamak" },
      { de: "einlenken", tr: "yumuşamak" },
      { de: "der Vorwurf", tr: "suçlama" },
    ],
    patterns: [
      { de: "Ich kann … nachvollziehen.", tr: "duyguyu tanır" },
      { de: "Wäre es hilfreich, wenn …?", tr: "çözümü soru olarak sunar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünün konusu zor: karşındaki sinirli. Almancada gerilimi düşürmenin sırası bellidir — önce duyguyu tanı, sonra konuya dön, en son çözümü öner. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Ve çözüm asla emir kipiyle sunulmaz. 'Size yedek cihaz veriyoruz' değil, 'yedek cihaz versek yardımcı olur mu' denir. Soru, karşı tarafa kontrolü geri verir. Önce kelimeler.")] },
      word("İlk", { de: "eskalieren", tr: "tırmanmak" }),
      word("İkinci", { de: "sachlich", tr: "nesnel" }),
      word("Üçüncü", { de: "nachvollziehen", tr: "anlayışla karşılamak" }),
      word("Dördüncü", { de: "einlenken", tr: "yumuşamak" }),
      word("Son", { de: "der Vorwurf", tr: "suçlama" }),
      { say: [tr("Kalıbımız:"), de("Wäre es hilfreich, wenn …?"), tr("Dilek kipinde sahte özne ve koşul cümlesi: en yumuşak çözüm önerme biçimi.")] },
      { say: [tr("Örnek:"), de("Ich kann Ihren Ärger gut nachvollziehen."), tr("Tekrar edin:"), de("Ich kann Ihren Ärger gut nachvollziehen")], expect: repeat("Ich kann Ihren Ärger gut nachvollziehen") },
      { say: [tr("Sıra sende: 'Nesnel kalalım.'")], expect: produce("Lassen Sie uns sachlich bleiben", [tr("lassen ile rica; mastar en sonda:"), de("Lassen Sie uns sachlich bleiben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi çözümü soru yap: 'Size yedek bir cihaz versek yardımcı olur mu?'")], expect: produce("Wäre es hilfreich, wenn wir Ihnen ein Ersatzgerät geben", [tr("Dilek kipi başta, koşul cümlesinde fiil sonda:"), de("Wäre es hilfreich, wenn wir Ihnen ein Ersatzgerät geben?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu bir suçlama değil, bir rica.'")], expect: produce("Das ist kein Vorwurf, sondern eine Bitte", [tr("Olumsuzluktan sonra düzeltme sondern ile yapılır:"), de("Das ist kein Vorwurf, sondern eine Bitte."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist kein Vorwurf, aber eine Bitte."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist kein Vorwurf, aber eine Bitte.", false, [tr("Olumsuzlanan şeyin yerine doğrusu konuyorsa bağlaç sondern olur:"), de("Das ist kein Vorwurf, sondern eine Bitte.")]) },
      { say: [tr("Son: 'Bu noktada yumuşayabilirim.'")], expect: produce("An dieser Stelle könnte ich einlenken", [tr("Tümleç başta, dilek kipi ikinci sırada, mastar sonda:"), de("An dieser Stelle könnte ich einlenken."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada öfkeli bir müşteriyle konuşacaksın: önce duyguyu tanı, sonra konuya dön ve bir çözüm öner.")] },
    ],
    roleplay: {
      scene: "Öfkeli bir müşteri seni arıyor: teslimat üçüncü kez gecikti. Önce duygusunu tanı, konuyu nesnel zemine çek, ne olduğunu açıkla ve bir çözüm öner.",
      partner: "sesini yükselten ama haksız olmayan, sonunda yumuşayabilen bir müşteri",
      opening: "Das ist jetzt das dritte Mal! Ich habe wirklich keine Lust mehr auf Ausreden — was machen Sie jetzt?",
      openingTr: "Bu üçüncü kez oluyor! Bahanelerden gerçekten bıktım — şimdi ne yapacaksınız?",
      goal: "Öfke tanınmış, konu nesnel zemine çekilmiş ve müşterinin kabul ettiği somut bir çözüm kararlaştırılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-vertrag-kuendigen",
    icon: "office",
    level: "B2",
    course: "de",
    title: "Das Abo kündigen",
    titleTr: "Abonelik iptali",
    summary: "Fesih bildirimini süre, onay ve cayma diliyle kurmayı öğretir.",
    minutes: 11,
    focusId: "Nominalisierung",
    vocab: [
      { de: "fristgerecht", tr: "süresine uygun" },
      { de: "die Kündigungsbestätigung", tr: "fesih onayı" },
      { de: "der Widerruf", tr: "cayma" },
      { de: "die Einwilligung", tr: "rıza" },
      { de: "wirksam", tr: "geçerli, yürürlükte" },
    ],
    patterns: [
      { de: "fristgerecht zum …", tr: "fesih tarihini bildirir" },
      { de: "Ich bitte um …", tr: "resmî talepte bulunur" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir sözleşmeyi feshedeceğiz. Almanca fesihte üç şey olmazsa yazı geçersiz sayılabilir: tarih, süreye uygunluk ve yazılı onay talebi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu üçü sabit kalıplarla söylenir; cümleyi kendin kurmaya çalışmak yerine kalıbı olduğu gibi kullanmak daha güvenli. Önce kelimeler.")] },
      word("İlk", { de: "fristgerecht", tr: "süresine uygun" }),
      word("İkinci", { de: "die Kündigungsbestätigung", tr: "fesih onayı" }),
      word("Üçüncü", { de: "der Widerruf", tr: "cayma" }),
      word("Dördüncü", { de: "die Einwilligung", tr: "rıza" }),
      word("Son", { de: "wirksam", tr: "geçerli, yürürlükte" }),
      { say: [tr("Kalıbımız:"), de("fristgerecht zum …"), tr("Ardından tarih gelir ve tarih yönelme hâlindedir.")] },
      { say: [tr("Örnek:"), de("Hiermit kündige ich meinen Vertrag fristgerecht zum einunddreißigsten Dezember."), tr("Tekrar edin:"), de("Hiermit kündige ich meinen Vertrag fristgerecht zum einunddreißigsten Dezember")], expect: repeat("Hiermit kündige ich meinen Vertrag fristgerecht zum einunddreißigsten Dezember") },
      { say: [tr("Sıra sende: 'Yazılı bir fesih onayı rica ediyorum.'")], expect: produce("Ich bitte um eine schriftliche Kündigungsbestätigung", [tr("bitten fiili um edatıyla ve belirtme hâliyle:"), de("Ich bitte um eine schriftliche Kündigungsbestätigung."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Reklam için verdiğim rızayı geri çekiyorum.'")], expect: produce("Ich widerrufe meine Einwilligung in die Werbung", [tr("Fiilin sabit edatı in ve belirtme hâli:"), de("Ich widerrufe meine Einwilligung in die Werbung."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Feshin ne zaman geçerli olacağını bilmek istiyorum.'")], expect: produce("Ich möchte wissen, wann die Kündigung wirksam wird", [tr("Dolaylı soruda fiil sona gider:"), de("Ich möchte wissen, wann die Kündigung wirksam wird."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich möchte wissen, wann wird die Kündigung wirksam."), tr("cümlesi doğru mu?")], expect: truefalse("Ich möchte wissen, wann wird die Kündigung wirksam.", false, [tr("Dolaylı soru yan cümledir; çekimli fiil sonda durur:"), de("Ich möchte wissen, wann die Kündigung wirksam wird.")]) },
      { say: [tr("Son: 'Sözleşmeyi en yakın tarihte feshediyorum.'")], expect: produce("Ich kündige den Vertrag zum nächstmöglichen Termin", [tr("Kalıplaşmış zaman ifadesi zum ile:"), de("Ich kündige den Vertrag zum nächstmöglichen Termin."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada aboneliğini iptal ettireceksin — ve karşı taraf seni tutmaya çalışacak.")] },
    ],
    roleplay: {
      scene: "Bir spor salonunun müşteri hattını aradın ve üyeliğini iptal ettirmek istiyorsun. Feshi bildir, tarihi söyle, tutma tekliflerine kararlılıkla cevap ver ve yazılı onay iste.",
      partner: "seni tutmak için indirim ve dondurma teklif eden bir müşteri danışmanı",
      opening: "Schade, dass Sie gehen wollen. Darf ich fragen, woran es liegt? Vielleicht finden wir eine Lösung.",
      openingTr: "Ayrılmak istemenize üzüldük. Sebebini sorabilir miyim? Belki bir çözüm buluruz.",
      goal: "Fesih bildirilmiş, tarih netleşmiş, tutma teklifleri reddedilmiş ve yazılı onay sözü alınmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-nachbarschaftsstreit",
    icon: "home",
    level: "B2",
    course: "de",
    title: "Der Zaunstreit",
    titleTr: "Sınır anlaşmazlığı",
    summary: "Komşu anlaşmazlığını koşullu bağlaçlarla dostane çözmeyi öğretir.",
    minutes: 11,
    focusId: "Nebensatz-sofern",
    vocab: [
      { de: "der Zaun", tr: "çit" },
      { de: "die Grundstücksgrenze", tr: "parsel sınırı" },
      { de: "gütlich", tr: "dostane" },
      { de: "der Rechtsweg", tr: "hukuk yolu" },
      { de: "das Einvernehmen", tr: "mutabakat" },
    ],
    patterns: [
      { de: "Sofern Sie einverstanden sind, …", tr: "koşullu öneri" },
      { de: "gütlich einigen", tr: "dostane çözüm" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün komşuyla anlaşmazlık var ve Almanya'da bunun bir kuralı var: mahkemeden önce dostane çözüm denenir. Bu deneme dilde de görünür. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Anahtar cümle koşullu olandır: 'siz de kabul ederseniz'. Karşı tarafa itiraz hakkı bırakır ve konuşmayı hukuk yolundan uzak tutar. Önce kelimeler.")] },
      word("İlk", { de: "der Zaun", tr: "çit" }),
      word("İkinci", { de: "die Grundstücksgrenze", tr: "parsel sınırı" }),
      word("Üçüncü", { de: "gütlich", tr: "dostane" }),
      word("Dördüncü", { de: "der Rechtsweg", tr: "hukuk yolu" }),
      word("Son", { de: "das Einvernehmen", tr: "mutabakat" }),
      { say: [tr("Kalıbımız:"), de("Sofern Sie einverstanden sind, …"), tr("Yan cümle bağlacı; fiil sona gidiyor ve ana cümle fiille başlıyor.")] },
      { say: [tr("Örnek:"), de("Sofern Sie einverstanden sind, teilen wir die Kosten."), tr("Tekrar edin:"), de("Sofern Sie einverstanden sind, teilen wir die Kosten")], expect: repeat("Sofern Sie einverstanden sind, teilen wir die Kosten") },
      { say: [tr("Sıra sende: 'Bunu dostane çözmeyi tercih ederim.'")], expect: produce("Ich würde das lieber gütlich lösen", [tr("Dilek kipiyle tercih; mastar sonda:"), de("Ich würde das lieber gütlich lösen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi olguyu söyle: 'Çit, sınırın otuz santim içinde duruyor.'")], expect: produce("Der Zaun steht dreißig Zentimeter innerhalb der Grenze", [tr("Ölçü fiilden sonra, edat tamlayan hâli ister:"), de("Der Zaun steht dreißig Zentimeter innerhalb der Grenze."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Mutabakata varırsak bir yazı hazırlarım.'")], expect: produce("Sofern wir ein Einvernehmen erzielen, setze ich etwas auf", [tr("Yan cümle önde; ana cümlede ayrılabilen önek sonda:"), de("Sofern wir ein Einvernehmen erzielen, setze ich etwas auf."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Sofern Sie einverstanden sind, teilen wir die Kosten."), tr("cümlesi doğru mu?")], expect: truefalse("Sofern Sie einverstanden sind, teilen wir die Kosten.", true, [tr("Doğru. Koşul yan cümlesinin fiili sonda, ana cümle fiille başlıyor.")]) },
      { say: [tr("Son: 'Hukuk yoluna gitmek istemiyorum.'")], expect: produce("Ich möchte nicht den Rechtsweg gehen", [tr("Olumsuzluk nesneden önce; mastar sonda:"), de("Ich möchte nicht den Rechtsweg gehen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada komşunla çit meselesini konuşacaksın: olguyu söyle, suçlamadan öner ve dostane bir çözümde anlaş.")] },
    ],
    roleplay: {
      scene: "Komşun çiti senin parselinin otuz santim içine kurmuş. Olguyu suçlamadan söyle, ne istediğini belirt, masraf paylaşımı öner ve dostane bir çözümde anlaş.",
      partner: "önce savunmaya geçen, sonra makul davranan bir komşu",
      opening: "Sie wollten mich sprechen? Wenn es um den Zaun geht — der stand schon so, als ich eingezogen bin.",
      openingTr: "Benimle konuşmak mı istediniz? Çitle ilgiliyse — ben taşındığımda da öyleydi.",
      goal: "Olgu suçlamadan anlatılmış, bir çözüm ve masraf paylaşımı önerilmiş ve dostane bir mutabakata varılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-reklamation-b2",
    icon: "repair",
    level: "B2",
    course: "de",
    title: "Der dritte Defekt",
    titleTr: "Israrlı şikâyet",
    summary: "Tekrarlayan arızayı edilgen geçmişle anlatıp değişim talep etmeyi öğretir.",
    minutes: 11,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "der Defekt", tr: "arıza" },
      { de: "die Nachbesserung", tr: "tamir denemesi" },
      { de: "bestehen auf", tr: "ısrar etmek" },
      { de: "die Kulanz", tr: "iyi niyet jesti" },
      { de: "unbrauchbar", tr: "kullanılamaz" },
    ],
    patterns: [
      { de: "… ist bereits … worden", tr: "yapılmış olanı sayar" },
      { de: "Ich bestehe auf …", tr: "talebi kararlı söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün üçüncü kez bozulan bir cihaz var. Bu konuşmanın gücü bir listeden gelir: şimdiye kadar ne YAPILDI. Ve o liste edilgen geçmişle kurulur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Neden edilgen? Çünkü kimin tamir ettiği önemsiz; önemli olan tamirin işe yaramamış olması. Fail silinince olgu öne çıkar. Önce kelimeler.")] },
      word("İlk", { de: "der Defekt", tr: "arıza" }),
      word("İkinci", { de: "die Nachbesserung", tr: "tamir denemesi" }),
      word("Üçüncü", { de: "bestehen auf", tr: "ısrar etmek" }),
      word("Dördüncü", { de: "die Kulanz", tr: "iyi niyet jesti" }),
      word("Son", { de: "unbrauchbar", tr: "kullanılamaz" }),
      { say: [tr("Kalıbımız:"), de("… ist bereits … worden"), tr("Edilgen geçmişte yardımcı fiil sona geçerken kısalır — bu ayrıntı cümleyi ya doğru ya yanlış yapar.")] },
      { say: [tr("Örnek:"), de("Das Gerät ist bereits zweimal repariert worden."), tr("Tekrar edin:"), de("Das Gerät ist bereits zweimal repariert worden")], expect: repeat("Das Gerät ist bereits zweimal repariert worden") },
      { say: [tr("Sıra sende: 'Cihaz üçüncü kez bozuldu.'")], expect: produce("Das Gerät ist zum dritten Mal kaputtgegangen", [tr("Hareket ve durum değişimi sein ile çekilir:"), de("Das Gerät ist zum dritten Mal kaputtgegangen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Tamir denendi ama bir işe yaramadı.'")], expect: produce("Die Nachbesserung ist versucht worden, aber sie hat nichts gebracht", [tr("İlk cümle edilgen geçmiş, ikincisi normal geçmiş:"), de("Die Nachbesserung ist versucht worden, aber sie hat nichts gebracht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yeni bir cihaz konusunda ısrar ediyorum.'")], expect: produce("Ich bestehe auf einem neuen Gerät", [tr("Bu fiilin sabit edatı auf ve arkasından yönelme hâli gelir:"), de("Ich bestehe auf einem neuen Gerät."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Gerät ist bereits zweimal repariert geworden."), tr("cümlesi doğru mu?")], expect: truefalse("Das Gerät ist bereits zweimal repariert geworden.", false, [tr("Edilgen geçmişte yardımcı fiil kısalır:"), de("Das Gerät ist bereits zweimal repariert worden.")]) },
      { say: [tr("Son: 'Cihaz bu hâliyle kullanılamaz durumda.'")], expect: produce("Das Gerät ist so unbrauchbar", [tr("Kısa hüküm cümlesi; sıfat sonda:"), de("Das Gerät ist so unbrauchbar."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada mağazada üçüncü kez bozulan cihazı geri götüreceksin: sayarak anlat ve değişim iste.")] },
    ],
    roleplay: {
      scene: "Aynı cihaz üçüncü kez bozuldu ve mağazadasın. Şimdiye kadar ne yapıldığını sırayla say, cihazın kullanılamaz olduğunu söyle, değişim ya da para iadesi iste ve bir sonuca bağla.",
      partner: "önce yine tamir öneren, ısrar karşısında yetkiliye danışan bir mağaza görevlisi",
      opening: "Sie waren doch schon mal hier, oder? Lassen Sie es mich noch einmal einschicken, das geht am schnellsten.",
      openingTr: "Daha önce de gelmiştiniz, değil mi? Bir kez daha servise göndereyim, en hızlısı bu.",
      goal: "Yapılan tamirler sayılmış, tekrar tamir teklifi reddedilmiş ve değişim ya da iade konusunda bir sonuca varılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-feedbackgespraech",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Kritik verpacken",
    titleTr: "Yapıcı eleştiri",
    summary: "Eleştiriyi gözlem, öneri ve soru sırasıyla vermeyi öğretir.",
    minutes: 11,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Rückmeldung", tr: "geri bildirim" },
      { de: "auffallen", tr: "dikkatini çekmek" },
      { de: "der Verbesserungsvorschlag", tr: "iyileştirme önerisi" },
      { de: "wertschätzend", tr: "takdir edici" },
      { de: "auf Augenhöhe", tr: "eşit düzeyde" },
    ],
    patterns: [
      { de: "Mir ist aufgefallen, dass …", tr: "gözlemi kişiselleştirmeden söyler" },
      { de: "An Ihrer Stelle würde ich …", tr: "öneriyi dilek kipiyle verir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve en faydalısı: eleştiriyi nasıl söylersin. Almancada üçlü bir sıra var — gözlem, öneri, soru. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Gözlem 'sen şöylesin' değil 'şu dikkatimi çekti' diye kurulur; öneri dilek kipindedir; soru da kararı karşı tarafa bırakır. Önce kelimeler.")] },
      word("İlk", { de: "die Rückmeldung", tr: "geri bildirim" }),
      word("İkinci", { de: "auffallen", tr: "dikkatini çekmek" }),
      word("Üçüncü", { de: "der Verbesserungsvorschlag", tr: "iyileştirme önerisi" }),
      word("Dördüncü", { de: "wertschätzend", tr: "takdir edici" }),
      word("Son", { de: "auf Augenhöhe", tr: "eşit düzeyde" }),
      { say: [tr("Kalıbımız:"), de("Mir ist aufgefallen, dass …"), tr("Özne sen değilsin, gözlem; suçlama yok, olgu var.")] },
      { say: [tr("Örnek:"), de("Mir ist aufgefallen, dass die Berichte oft spät kommen."), tr("Tekrar edin:"), de("Mir ist aufgefallen, dass die Berichte oft spät kommen")], expect: repeat("Mir ist aufgefallen, dass die Berichte oft spät kommen") },
      { say: [tr("Sıra sende: 'Sizin yerinizde olsam önce ekiple konuşurdum.'")], expect: produce("An Ihrer Stelle würde ich zuerst mit dem Team sprechen", [tr("Tümleç başta, dilek kipi ikinci sırada, mastar sonda:"), de("An Ihrer Stelle würde ich zuerst mit dem Team sprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir iyileştirme önerim olurdu.'")], expect: produce("Ich hätte einen Verbesserungsvorschlag", [tr("Sahip olma fiilinin dilek kipi teklifi yumuşatır:"), de("Ich hätte einen Verbesserungsvorschlag."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, kararı ona bırak: 'Bu konuda ne düşünürsünüz?'")], expect: produce("Was halten Sie davon", [tr("Kalıplaşmış soru; edat davon ile birleşir:"), de("Was halten Sie davon?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("An Ihrer Stelle würde ich zuerst mit dem Team gesprochen."), tr("cümlesi doğru mu?")], expect: truefalse("An Ihrer Stelle würde ich zuerst mit dem Team gesprochen.", false, [tr("würde yardımcı fiilinden sonra ortaç değil mastar gelir:"), de("An Ihrer Stelle würde ich zuerst mit dem Team sprechen.")]) },
      { say: [tr("Son: 'Bunu eşit düzeyde konuşmak istiyorum.'")], expect: produce("Ich möchte das auf Augenhöhe besprechen", [tr("Kalıplaşmış ifade; mastar sonda:"), de("Ich möchte das auf Augenhöhe besprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir ekip arkadaşına zor bir geri bildirim vereceksin — gözlem, öneri, soru sırasıyla.")] },
    ],
    roleplay: {
      scene: "Bir ekip arkadaşına zor bir geri bildirim veriyorsun: teslimler sürekli gecikiyor. Önce takdir ettiğin yanı söyle, gözlemini kişiselleştirmeden aktar, bir öneri ver ve kararı ona bırak.",
      partner: "önce savunmaya geçen, sonra dinleyen bir ekip arkadaşı",
      opening: "Du wolltest reden? Wenn es wieder um die Termine geht — ich hänge selbst an drei Zulieferungen fest.",
      openingTr: "Konuşmak mı istedin? Yine tarihlerle ilgiliyse — ben de üç tedarikte takılı durumdayım.",
      goal: "Takdir ve gözlem ayrı ayrı söylenmiş, bir öneri verilmiş ve karşı tarafın ne yapacağı birlikte kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
];
