import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B1 · Modül 3 — Bağlaç ustalığı (021–030). WP-71 pilotu.
 *
 * Modülün derdi tek: cümleleri BAĞLAMAK. A2 weil/dass'ı verdi; burada amaç
 * (damit / um…zu), zıtlık (obwohl / trotzdem), zaman (als / wenn / nachdem /
 * bevor / während), sonuç (deshalb) ve ikili bağlaçlar (je…desto,
 * entweder…oder) sırayla geliyor. Her dersin tek bir bağlacı var ve
 * karşıtıyla birlikte öğretiliyor (damit ↔ um…zu, als ↔ wenn), çünkü Türkçe
 * konuşanın hatası bağlacı bilmemek değil, ikisini karıştırmak.
 *
 * Adım dengesi (WP-71): tekrar ≤ %40, üret ≥ %30; her derste 4 üret + 1
 * doğru/yanlış. Kelimeler havuzdan; kalıplar konuşma fazına taşınıyor.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB1B03: Lesson[] = [
  {
    id: "de-b1-damit",
    icon: "idea",
    level: "B1",
    course: "de",
    title: "Damit es allen gut geht",
    titleTr: "Amaç anlatmak: damit",
    summary: "Özne farklıysa amacı damit yan cümlesiyle söylemeyi öğretir.",
    minutes: 10,
    focusId: "Nebensatz-damit",
    vocab: [
      { de: "rechtzeitig", tr: "zamanında" },
      { de: "sich erholen", tr: "dinlenmek, toparlanmak" },
      { de: "damit", tr: "-sin diye" },
      { de: "der Zweck", tr: "amaç" },
      { de: "unterstützen", tr: "desteklemek" },
      { de: "dafür", tr: "bunun için" },
      { de: "gelingen", tr: "başarılı olmak" },
      { de: "eigentlich", tr: "aslında" },
    ],
    patterns: [
      { de: "…, damit …", tr: "amaç söyler; özne farklıysa kullanılır, fiil sona gider" },
      { de: "Ich spare, damit meine Kinder studieren können.", tr: "damit ile tam cümle" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir şeyi NEDEN yaptığını söylemeyi öğreneceğiz: 'çocuklarım okuyabilsin diye', 'sağlıklı kalsınlar diye'. Almancada bunun için 'damit' var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Türkçede amaç tek ekle çıkar: -sin diye, -mesi için. Almancada bir yan cümle kurulur ve fiil sona gider. Önce dersin kelimeleri.")] },
      word("İlk", { de: "rechtzeitig", tr: "zamanında" }),
      word("İkinci", { de: "sich erholen", tr: "dinlenmek, toparlanmak" }),
      word("Üçüncü", { de: "damit", tr: "-sin diye" }),
      word("Dördüncü", { de: "der Zweck", tr: "amaç" }),
      word("Beşinci", { de: "unterstützen", tr: "desteklemek" }),
      word("Altıncı", { de: "dafür", tr: "bunun için" }),
      word("Yedinci", { de: "gelingen", tr: "başarılı olmak" }),
      word("Son", { de: "eigentlich", tr: "aslında" }),
      { say: [tr("Kalıbımız:"), de("damit"), tr("'-sin diye, -mesi için' demek. Yan cümle bağlacı: çekimli fiil en sona gider. Özne farklı olduğunda tercih edilir — ben biriktiriyorum, çocuklarım okusun.")] },
      { say: [tr("Örnek:"), de("Ich spare, damit meine Kinder studieren können."), tr("Lütfen tekrar edin:"), de("Ich spare, damit meine Kinder studieren können")], expect: repeat("Ich spare, damit meine Kinder studieren können") },
      { say: [tr("Sıra sende: 'Erken çıkıyorum, zamanında varalım diye.' — 'Ich gehe früh los, damit wir …' ile bitir.")], expect: produce("Ich gehe früh los, damit wir rechtzeitig ankommen", [tr("damit'ten sonra fiil en sona:"), de("Ich gehe früh los, damit wir rechtzeitig ankommen."), tr("Tekrar dene.")], ["Ich gehe früh los, damit wir rechtzeitig da sind"]) },
      { say: [tr("Şimdi: 'Sağlıklı kalsın diye ona meyve veriyorum.' — 'Ich gebe ihm Obst, damit …'")], expect: produce("Ich gebe ihm Obst, damit er gesund bleibt", [tr("Özne farklı (ben veriyorum, o kalıyor) → damit; fiil sona:"), de("Ich gebe ihm Obst, damit er gesund bleibt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir de zıddı: 'Dinlenebilmem için tatile ihtiyacım var.' — 'Ich brauche Urlaub, damit ich mich …'")], expect: produce("Ich brauche Urlaub, damit ich mich erholen kann", [tr("Dönüşlü fiil ve modal: erholen kann, ikisi de sonda:"), de("Ich brauche Urlaub, damit ich mich erholen kann."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich lerne Deutsch, damit ich finde eine Stelle."), tr("cümlesi doğru mu?")], expect: truefalse("Ich lerne Deutsch, damit ich finde eine Stelle.", false, [de("damit"), tr("yan cümle kurar, fiil sona gider:"), de("Ich lerne Deutsch, damit ich eine Stelle finde.")]) },
      { say: [tr("Son bir tane: 'Herkes iyi olsun diye çalışıyorum.' — 'Ich arbeite, damit es …'")], expect: produce("Ich arbeite, damit es allen gut geht", [tr("'es geht allen gut' → damit ile fiil sona: allen gut geht:"), de("Ich arbeite, damit es allen gut geht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir arkadaşınla planlarını konuşacaksın ve her kararının amacını damit ile söyleyeceksin.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla önümüzdeki yıl planlarını konuşuyorsun: para biriktirmek, kurs, tatil. Her planın amacını 'damit' ile söyle; arkadaşın 'warum?' diye sorar.",
      partner: "meraklı ve destekleyici bir arkadaş",
      opening: "Hey! Du hast gesagt, du hast große Pläne für nächstes Jahr. Erzähl mal — was hast du vor, und warum?",
      openingTr: "Hey! Gelecek yıl için büyük planların varmış. Anlat — ne yapacaksın ve neden?",
      goal: "Her planın amacı söylenmiş ve arkadaşın hangisini en çok merak ettiğini belirtmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-um-zu",
    icon: "run",
    level: "B1",
    course: "de",
    title: "Um besser zu werden",
    titleTr: "Amaç anlatmak: um … zu",
    summary: "Özne aynıysa amacı um … zu mastar yapısıyla söylemeyi öğretir.",
    minutes: 10,
    focusId: "Um-zu",
    vocab: [
      { de: "das Wissen", tr: "bilgi" },
      { de: "erwarten", tr: "beklemek" },
      { de: "ständig", tr: "sürekli" },
      { de: "bisher", tr: "şimdiye kadar" },
      { de: "kaum", tr: "zar zor" },
      { de: "perfekt", tr: "mükemmel" },
      { de: "nämlich", tr: "yani; çünkü" },
      { de: "der Zufall", tr: "tesadüf" },
    ],
    patterns: [
      { de: "um … zu + Infinitiv", tr: "amaç söyler; özne aynıysa; mastar sona" },
      { de: "Ich lerne jeden Tag, um die Prüfung zu bestehen.", tr: "um…zu ile tam cümle" },
    ],
    lecture: [
      { say: [tr("Merhaba! Geçen ders 'damit' idi. Bugün onun kardeşi: 'um … zu'. Aynı şeyi söyler — amaç — ama daha kısa, çünkü özne aynı olduğunda yan cümleye gerek yok. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şu: 'Ben öğreniyorum, ben geçeyim diye' → özne aynı → um … zu. 'Ben biriktiriyorum, çocuklarım okusun diye' → özne farklı → damit. Önce kelimeler.")] },
      word("İlk", { de: "das Wissen", tr: "bilgi" }),
      word("İkinci", { de: "erwarten", tr: "beklemek" }),
      word("Üçüncü", { de: "ständig", tr: "sürekli" }),
      word("Dördüncü", { de: "bisher", tr: "şimdiye kadar" }),
      word("Beşinci", { de: "kaum", tr: "zar zor" }),
      word("Altıncı", { de: "perfekt", tr: "mükemmel" }),
      word("Yedinci", { de: "nämlich", tr: "yani; çünkü" }),
      word("Son", { de: "der Zufall", tr: "tesadüf" }),
      { say: [tr("Kalıbımız:"), de("um … zu"), tr("'-mek için' demek. 'um' virgülden sonra gelir, 'zu' mastarın hemen önüne. Ayrılabilen fiilde zu araya girer: um … anzurufen.")] },
      { say: [tr("Örnek:"), de("Ich lerne jeden Tag, um die Prüfung zu bestehen."), tr("Tekrar edin:"), de("Ich lerne jeden Tag, um die Prüfung zu bestehen")], expect: repeat("Ich lerne jeden Tag, um die Prüfung zu bestehen") },
      { say: [tr("Sıra sende: 'Almancamı geliştirmek için okuyorum.' — 'Ich lese, um …'")], expect: produce("Ich lese, um mein Deutsch zu verbessern", [tr("um + nesne + zu + mastar:"), de("Ich lese, um mein Deutsch zu verbessern."), tr("Tekrar dene.")]) },
      { say: [tr("'Formda kalmak için antrenman yapıyorum.' — 'Ich trainiere, um …' (fit bleiben)")], expect: produce("Ich trainiere, um fit zu bleiben", [tr("zu mastarın önüne: fit zu bleiben:"), de("Ich trainiere, um fit zu bleiben."), tr("Tekrar dene.")]) },
      { say: [tr("Hangisi? 'Çocuklarım iyi bir okula gitsin diye taşınıyorum.' Özne farklı — cümleyi kur: 'Ich ziehe um, …'")], expect: produce("Ich ziehe um, damit meine Kinder eine gute Schule haben", [tr("Özne farklı (ben taşınıyorum, çocuklar gidiyor) → damit, um…zu değil:"), de("Ich ziehe um, damit meine Kinder eine gute Schule haben."), tr("Tekrar dene.")], ["Ich ziehe um, damit meine Kinder auf eine gute Schule gehen können"]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich spare Geld, um ich ein Auto kaufe."), tr("cümlesi doğru mu?")], expect: truefalse("Ich spare Geld, um ich ein Auto kaufe.", false, [de("um … zu"), tr("yapısında özne tekrar edilmez, fiil mastar olur:"), de("Ich spare Geld, um ein Auto zu kaufen.")]) },
      { say: [tr("Son: 'Seni aramak için telefonumu açtım.' — 'Ich habe mein Handy eingeschaltet, um dich …' (ayrılabilen fiil!)")], expect: produce("Ich habe mein Handy eingeschaltet, um dich anzurufen", [tr("Ayrılabilen fiilde zu araya girer: an-zu-rufen:"), de("Ich habe mein Handy eingeschaltet, um dich anzurufen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir koçla hedeflerini konuşacaksın: neden çalıştığını um…zu ile söyle, koç 'wozu?' diye soracak.")] },
    ],
    roleplay: {
      scene: "Bir dil kursunda danışmanla hedef görüşmesi: neden Almanca öğrendiğini, sınava neden girdiğini 'um … zu' ile anlat; danışman planını sorgular.",
      partner: "soruları net, cesaretlendirici bir kurs danışmanı",
      opening: "Guten Tag! Schön, dass Sie da sind. Sagen Sie mir zuerst: Wozu lernen Sie eigentlich Deutsch?",
      openingTr: "İyi günler! Geldiğinize sevindim. Önce şunu söyleyin: Almancayı ne için öğreniyorsunuz?",
      goal: "Almanca öğrenme ve sınava girme amacın anlatılmış, danışman planını değerlendirmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-obwohl",
    icon: "question",
    level: "B1",
    course: "de",
    title: "Trotzdem mache ich es",
    titleTr: "Zıtlık: obwohl ve trotzdem",
    summary: "Beklentiye aykırı durumu obwohl yan cümlesi ve trotzdem zarfıyla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-obwohl",
    vocab: [
      { de: "die Erkältung", tr: "soğuk algınlığı" },
      { de: "jedoch", tr: "ancak" },
      { de: "allerdings", tr: "ancak, gerçi" },
      { de: "unglaublich", tr: "inanılmaz" },
      { de: "ernst", tr: "ciddi" },
      { de: "wohl", tr: "galiba" },
      { de: "überhaupt", tr: "aslında; hiç" },
      { de: "bloß", tr: "yalnızca" },
    ],
    patterns: [
      { de: "Obwohl …, …", tr: "-e rağmen; yan cümle, fiil sona" },
      { de: "…, trotzdem …", tr: "yine de; zarf, birinci sırayı kaplar, fiil hemen arkasına" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün beklenmeyeni söylemeyi öğreneceğiz: 'Hastayım ama yine de geliyorum.' İki yol var: obwohl (-e rağmen) ve trotzdem (yine de). Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkisi aynı anlamı taşır, dizilişleri farklıdır: obwohl yan cümle kurar ve fiili sona atar; trotzdem ana cümlenin başına gelir ve fiili hemen arkasına çeker. Önce kelimeler.")] },
      word("İlk", { de: "die Erkältung", tr: "soğuk algınlığı" }),
      word("İkinci", { de: "jedoch", tr: "ancak" }),
      word("Üçüncü", { de: "allerdings", tr: "ancak, gerçi" }),
      word("Dördüncü", { de: "unglaublich", tr: "inanılmaz" }),
      word("Beşinci", { de: "ernst", tr: "ciddi" }),
      word("Altıncı", { de: "wohl", tr: "galiba" }),
      word("Yedinci", { de: "überhaupt", tr: "aslında; hiç" }),
      word("Son", { de: "bloß", tr: "yalnızca" }),
      { say: [tr("İlk kalıp:"), de("obwohl"), tr("'-e rağmen' demek. Yan cümle: 'Obwohl ich eine Erkältung habe, gehe ich arbeiten.' Yan cümle önde olunca ana cümle fiille başlar: gehe ich.")] },
      { say: [tr("Tekrar edin:"), de("Obwohl ich müde bin, gehe ich zum Sport")], expect: repeat("Obwohl ich müde bin, gehe ich zum Sport") },
      { say: [tr("Sıra sende: 'Maaş iyi olmasına rağmen istifa ediyorum.' — 'Obwohl das Gehalt gut ist, …'")], expect: produce("Obwohl das Gehalt gut ist, kündige ich", [tr("Yan cümle önde → ana cümle fiille başlar: kündige ich:"), de("Obwohl das Gehalt gut ist, kündige ich."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıp:"), de("trotzdem"), tr("'yine de' demek. Ana cümle zarfı: birinci sırayı kaplar, fiil ikinci, özne üçüncü. 'Ich bin müde, trotzdem gehe ich zum Sport.'")] },
      { say: [tr("Aynı cümleyi trotzdem ile kur: 'Das Gehalt ist gut, trotzdem …'")], expect: produce("Das Gehalt ist gut, trotzdem kündige ich", [tr("trotzdem birinci sırada, fiil hemen arkasında, özne sonra:"), de("Das Gehalt ist gut, trotzdem kündige ich."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich bin zufrieden, trotzdem ich suche eine neue Stelle."), tr("cümlesi doğru mu?")], expect: truefalse("Ich bin zufrieden, trotzdem ich suche eine neue Stelle.", false, [de("trotzdem"), tr("birinci sırayı kaplar, fiil hemen arkasına gelir:"), de("…, trotzdem suche ich eine neue Stelle.")]) },
      { say: [tr("Son: 'Yağmur yağmasına rağmen dışarı çıkıyoruz.' — obwohl ile.")], expect: produce("Obwohl es regnet, gehen wir raus", [tr("Obwohl + fiil sona; sonra fiil + özne:"), de("Obwohl es regnet, gehen wir raus."), tr("Tekrar dene.")], ["Wir gehen raus, obwohl es regnet"]) },
      { say: [tr("Hazırsın. Konuşmada bir kararını savunacaksın: karşındaki 'ama…' diyecek, sen obwohl ve trotzdem ile cevap vereceksin.")] },
    ],
    roleplay: {
      scene: "Arkadaşın, iyi maaşlı işinden istifa etme kararını sorguluyor. Kararını 'obwohl' ve 'trotzdem' ile savun: memnun değilsin, yorgunsun, yeni bir şey istiyorsun.",
      partner: "endişeli ama iyi niyetli bir arkadaş",
      opening: "Was? Du willst wirklich kündigen? Das Gehalt ist doch super. Warum denn?",
      openingTr: "Ne? Gerçekten istifa mı edeceksin? Maaş süper ama. Neden ki?",
      goal: "İstifa kararın zıtlık cümleleriyle savunulmuş ve arkadaşın kararını anlamış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-als-wenn",
    icon: "baby",
    level: "B1",
    course: "de",
    title: "Als ich ein Kind war",
    titleTr: "Zaman: als mi wenn mi",
    summary: "Geçmişte tek seferlik olay için als, tekrarlanan ve gelecek için wenn kullanmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-als",
    vocab: [
      { de: "die Kindheit", tr: "çocukluk" },
      { de: "jedes Mal", tr: "her seferinde" },
      { de: "die Erinnerung", tr: "anı" },
      { de: "das Erlebnis", tr: "yaşantı" },
      { de: "der Augenblick", tr: "an" },
      { de: "irgendwann", tr: "bir gün" },
      { de: "damals", tr: "o zamanlar" },
      { de: "der Held", tr: "kahraman" },
    ],
    patterns: [
      { de: "Als …, …", tr: "geçmişte bir kez olan; fiil sona" },
      { de: "(Immer) wenn …, …", tr: "tekrarlanan ya da gelecekteki durum" },
    ],
    lecture: [
      { say: [tr("Merhaba! Türkçede 'çocukken' tek kelime; Almancada iki bağlaç var ve seçim zamana bağlı: geçmişte BİR KEZ olduysa als, tekrarlandıysa ya da gelecekteyse wenn. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Test cümlesi: 'Berlin'e taşındığımda' — bir kez oldu → als. 'Her Berlin'e gittiğimde' — tekrar → wenn. Önce kelimeler.")] },
      word("İlk", { de: "die Kindheit", tr: "çocukluk" }),
      word("İkinci", { de: "jedes Mal", tr: "her seferinde" }),
      word("Üçüncü", { de: "die Erinnerung", tr: "anı" }),
      word("Dördüncü", { de: "das Erlebnis", tr: "yaşantı" }),
      word("Beşinci", { de: "der Augenblick", tr: "an" }),
      word("Altıncı", { de: "irgendwann", tr: "bir gün" }),
      word("Yedinci", { de: "damals", tr: "o zamanlar" }),
      word("Son", { de: "der Held", tr: "kahraman" }),
      { say: [tr("İlk kalıp:"), de("als"), tr("geçmişte tek seferlik olay ya da dönem: 'Als ich ein Kind war, wohnten wir in Izmir.' Çocukluk tek bir dönem → als.")] },
      { say: [tr("Tekrar edin:"), de("Als ich ein Kind war, wohnten wir in Izmir")], expect: repeat("Als ich ein Kind war, wohnten wir in Izmir") },
      { say: [tr("Sıra sende: 'Almanya'ya geldiğimde 20 yaşındaydım.' — 'Als ich nach Deutschland kam, …'")], expect: produce("Als ich nach Deutschland kam, war ich 20", [tr("Tek seferlik → als; yan cümle önde, fiil sonra: war ich:"), de("Als ich nach Deutschland kam, war ich 20."), tr("Tekrar dene.")], ["Als ich nach Deutschland kam, war ich zwanzig", "Als ich nach Deutschland kam, war ich 20 Jahre alt"]) },
      { say: [tr("İkinci kalıp:"), de("wenn"), tr("tekrarlanan olay ya da gelecek: 'Immer wenn ich diese Musik höre, erinnere ich mich an damals.' Her seferinde → wenn.")] },
      { say: [tr("Sıra sende: 'Her taşındığımızda bir şey kaybederim.' Cümleye 'jedes Mal' ile başla.")], expect: produce("Jedes Mal, wenn wir umziehen, verliere ich etwas", [tr("Tekrarlanan olay → wenn; yan cümleden sonra ana cümle fiille başlar:"), de("Jedes Mal, wenn wir umziehen, verliere ich etwas."), tr("Tekrar dene.")], ["Immer wenn wir umziehen, verliere ich etwas"]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn ich gestern nach Hause kam, war es schon dunkel."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn ich gestern nach Hause kam, war es schon dunkel.", false, [tr("Geçmişte bir kez (gestern) →"), de("als"), tr(":"), de("Als ich gestern nach Hause kam, war es schon dunkel.")]) },
      { say: [tr("Son: 'Taşındığımızda kızım üç yaşındaydı.' — als ile.")], expect: produce("Als wir umgezogen sind, war meine Tochter drei", [tr("Tek seferlik geçmiş → als; Perfekt'te sind sona:"), de("Als wir umgezogen sind, war meine Tochter drei."), tr("Tekrar dene.")], ["Als wir umzogen, war meine Tochter drei", "Als wir umgezogen sind, war meine Tochter drei Jahre alt"]) },
      { say: [tr("Hazırsın. Konuşmada çocukluğunu anlatacaksın: als ile anılar, wenn ile alışkanlıklar.")] },
    ],
    roleplay: {
      scene: "Yeni bir tanıdık çocukluğunu soruyor. Tek seferlik anıları 'als' ile, tekrarlanan alışkanlıkları 'immer wenn' ile anlat.",
      partner: "ilgiyle dinleyen, soru soran bir tanıdık",
      opening: "Du bist also in Izmir aufgewachsen? Wie war deine Kindheit dort? Erzähl mal von damals.",
      openingTr: "Demek İzmir'de büyüdün? Orada çocukluğun nasıldı? O zamanları anlatsana.",
      goal: "Tek seferlik anıların ve tekrarlanan alışkanlıkların ayrı ayrı anlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-nachdem",
    icon: "clock",
    level: "B1",
    course: "de",
    title: "Nachdem ich gegessen hatte",
    titleTr: "Sıralı geçmiş: nachdem",
    summary: "Önce olanı nachdem + Plusquamperfekt ile söylemeyi öğretir.",
    minutes: 10,
    focusId: "Nebensatz-nachdem",
    vocab: [
      { de: "danach", tr: "ondan sonra" },
      { de: "die Reihenfolge", tr: "sıralama" },
      { de: "inzwischen", tr: "bu sırada" },
      { de: "nun", tr: "artık" },
      { de: "eben", tr: "az önce" },
      { de: "seitdem", tr: "o zamandan beri" },
      { de: "übrigens", tr: "bu arada" },
      { de: "jemals", tr: "hiç" },
    ],
    patterns: [
      { de: "Nachdem … hatte/war, …", tr: "önce olan Plusquamperfekt, sonra olan Präteritum/Perfekt" },
      { de: "Zuerst …, danach …", tr: "sıralama zarfları" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün iki geçmiş olayı sıraya koymayı öğreneceğiz: 'Yemek yedikten sonra dışarı çıktım.' Almancada 'nachdem' önce olanı alır ve o fiil bir kat daha geçmişe gider. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yeni zaman: Plusquamperfekt — hatte/war + Partizip II. 'Nachdem ich gegessen HATTE, ging ich raus.' Türkçedeki '-dikten sonra' burada. Önce kelimeler.")] },
      word("İlk", { de: "danach", tr: "ondan sonra" }),
      word("İkinci", { de: "die Reihenfolge", tr: "sıralama" }),
      word("Üçüncü", { de: "inzwischen", tr: "bu sırada" }),
      word("Dördüncü", { de: "nun", tr: "artık" }),
      word("Beşinci", { de: "eben", tr: "az önce" }),
      word("Altıncı", { de: "seitdem", tr: "o zamandan beri" }),
      word("Yedinci", { de: "übrigens", tr: "bu arada" }),
      word("Son", { de: "jemals", tr: "hiç" }),
      { say: [tr("Kalıbımız:"), de("Nachdem … hatte, …"), tr("Yan cümlede Plusquamperfekt (hatte/war + Partizip), ana cümlede Präteritum ya da Perfekt. Hareket fiillerinde war: 'Nachdem ich angekommen war…'")] },
      { say: [tr("Tekrar edin:"), de("Nachdem ich gegessen hatte, ging ich raus")], expect: repeat("Nachdem ich gegessen hatte, ging ich raus") },
      { say: [tr("Sıra sende: 'Eğitimimi bitirdikten sonra başvurdum.' — 'Nachdem ich die Ausbildung abgeschlossen hatte, …'")], expect: produce("Nachdem ich die Ausbildung abgeschlossen hatte, habe ich mich beworben", [tr("Önce olan: Plusquamperfekt (abgeschlossen hatte); sonra olan Perfekt:"), de("Nachdem ich die Ausbildung abgeschlossen hatte, habe ich mich beworben."), tr("Tekrar dene.")], ["Nachdem ich die Ausbildung abgeschlossen hatte, bewarb ich mich"]) },
      { say: [tr("'Olumlu cevabı aldıktan sonra taşındım.' — 'Nachdem ich die Zusage bekommen hatte, …'")], expect: produce("Nachdem ich die Zusage bekommen hatte, bin ich umgezogen", [tr("bekommen hatte (önce), bin umgezogen (sonra, sein!):"), de("Nachdem ich die Zusage bekommen hatte, bin ich umgezogen."), tr("Tekrar dene.")], ["Nachdem ich die Zusage bekommen hatte, zog ich um"]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nachdem ich gefrühstückt habe, ging ich zur Arbeit."), tr("cümlesi doğru mu?")], expect: truefalse("Nachdem ich gefrühstückt habe, ging ich zur Arbeit.", false, [de("nachdem"), tr("yan cümlesi bir kat daha geçmişte olmalı — Plusquamperfekt:"), de("Nachdem ich gefrühstückt hatte, ging ich zur Arbeit.")]) },
      { say: [tr("Son: 'Vardıktan sonra ailemi aradım.' — 'Nachdem ich angekommen war, …' (hareket → war)")], expect: produce("Nachdem ich angekommen war, habe ich meine Familie angerufen", [tr("ankommen hareket → war angekommen; sonra Perfekt:"), de("Nachdem ich angekommen war, habe ich meine Familie angerufen."), tr("Tekrar dene.")], ["Nachdem ich angekommen war, rief ich meine Familie an"]) },
      { say: [tr("Hazırsın. Konuşmada Almanya'ya geliş hikâyeni sırayla anlatacaksın: nachdem, zuerst, danach.")] },
    ],
    roleplay: {
      scene: "Bir entegrasyon kursunda tanıştığın biri Almanya'ya nasıl geldiğini soruyor. Olayları sırayla anlat: 'Nachdem … hatte, …', 'Zuerst …, danach …'.",
      partner: "kendi hikâyesini de paylaşan, meraklı bir kurs arkadaşı",
      opening: "Ich bin vor zwei Jahren gekommen. Und du — wie war das bei dir? Was hast du zuerst gemacht, nachdem du angekommen warst?",
      openingTr: "Ben iki yıl önce geldim. Peki sen — sende nasıldı? Vardıktan sonra ilk ne yaptın?",
      goal: "Buraya geliş hikâyen olay olay, doğru sırayla anlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-bevor-waehrend",
    icon: "film",
    level: "B1",
    course: "de",
    title: "Bevor der Film beginnt",
    titleTr: "Önce ve sırasında: bevor, während",
    summary: "Olayları bevor (-meden önce) ve während (-irken) ile bağlamayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-bevor-während",
    vocab: [
      { de: "die Vorstellung", tr: "gösterim, seans" },
      { de: "gleichzeitig", tr: "aynı anda" },
      { de: "sich unterhalten", tr: "sohbet etmek" },
      { de: "unterwegs", tr: "yolda" },
      { de: "los", tr: "hadi" },
      { de: "mal", tr: "kez" },
      { de: "raus", tr: "dışarı" },
      { de: "dabei", tr: "yanında, o sırada" },
    ],
    patterns: [
      { de: "Bevor …, …", tr: "-meden önce; fiil sona" },
      { de: "Während …, …", tr: "-irken; iki olay aynı anda" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün zamanın iki bağlacı daha: bevor (-meden önce) ve während (-irken). Sinemadayız: film başlamadan önce, film sürerken. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkisi de yan cümle bağlacı: fiil sona. Türkçeden fark, olumsuzlukta: 'gitmeden önce' Almancada olumlu 'bevor ich gehe' — nicht eklenmez. Önce kelimeler.")] },
      word("İlk", { de: "die Vorstellung", tr: "gösterim, seans" }),
      word("İkinci", { de: "gleichzeitig", tr: "aynı anda" }),
      word("Üçüncü", { de: "sich unterhalten", tr: "sohbet etmek" }),
      word("Dördüncü", { de: "unterwegs", tr: "yolda" }),
      word("Beşinci", { de: "los", tr: "hadi" }),
      word("Altıncı", { de: "mal", tr: "kez" }),
      word("Yedinci", { de: "raus", tr: "dışarı" }),
      word("Son", { de: "dabei", tr: "yanında, o sırada" }),
      { say: [tr("İlk kalıp:"), de("bevor"), tr("'-meden önce'. 'Bevor der Film beginnt, schalte ich das Handy aus.' Dikkat: bevor cümlesinde nicht YOK.")] },
      { say: [tr("Tekrar edin:"), de("Bevor der Film beginnt, schalte ich das Handy aus")], expect: repeat("Bevor der Film beginnt, schalte ich das Handy aus") },
      { say: [tr("Sıra sende: 'Çıkmadan önce kapıyı kilitliyorum.' — 'Bevor ich gehe, …' (abschließen)")], expect: produce("Bevor ich gehe, schließe ich die Tür ab", [tr("bevor + fiil sona (gehe); ana cümlede önek sona: schließe … ab:"), de("Bevor ich gehe, schließe ich die Tür ab."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıp:"), de("während"), tr("'-irken': iki olay aynı anda. 'Während er kocht, deckt sie den Tisch.' Fiil yine sona.")] },
      { say: [tr("Sıra sende: 'Ara sırasında sohbet ediyoruz.' — 'Während die Pause ist, …' yerine daha doğal: 'Während der Pause …' ama biz yan cümle kuralım: 'Während wir warten, …'")], expect: produce("Während wir warten, unterhalten wir uns", [tr("während yan cümle, fiil sona; ana cümle fiille başlar:"), de("Während wir warten, unterhalten wir uns."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Bevor ich nicht frühstücke, trinke ich Kaffee."), tr("cümlesi doğru mu?")], expect: truefalse("Bevor ich nicht frühstücke, trinke ich Kaffee.", false, [de("bevor"), tr("cümlesi olumludur; Türkçedeki '-meden' Almancaya nicht olarak geçmez:"), de("Bevor ich frühstücke, trinke ich Kaffee.")]) },
      { say: [tr("Son: 'O yemek yaparken ben çocuklarla oynuyorum.' — 'Während er kocht, …'")], expect: produce("Während er kocht, spiele ich mit den Kindern", [tr("Aynı anda → während; ana cümle fiille:"), de("Während er kocht, spiele ich mit den Kindern."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir sinema akşamı planlayacaksın: filmden önce ne yapılacak, film sırasında ne olacak.")] },
    ],
    roleplay: {
      scene: "Arkadaşınla sinema akşamı planlıyorsun: filmden önce yemek, bilet, film sırasında kurallar, sonra kafe. 'bevor' ve 'während' ile sırala.",
      partner: "plan yapmayı seven, pratik bir arkadaş",
      opening: "Also, Kino um acht. Was machen wir vorher — essen wir noch etwas, bevor der Film anfängt?",
      openingTr: "Peki, sinema sekizde. Öncesinde ne yapıyoruz — film başlamadan önce bir şeyler yiyelim mi?",
      goal: "Film öncesi, film sırası ve sonrası için plan sıraya konmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-deshalb-trotzdem",
    icon: "chart",
    level: "B1",
    course: "de",
    title: "Deshalb oder trotzdem?",
    titleTr: "Sonuç bağlaçları: deshalb, darum, trotzdem",
    summary: "Sonuç ve beklenmeyen sonucu ana cümle zarflarıyla (V1 dizilişi) söylemeyi öğretir.",
    minutes: 10,
    focusId: "Konnektor-denn",
    vocab: [
      { de: "der Stau", tr: "trafik sıkışıklığı" },
      { de: "die Entscheidung", tr: "karar" },
      { de: "ablehnen", tr: "reddetmek" },
      { de: "deswegen", tr: "bu yüzden" },
      { de: "die Ursache", tr: "neden" },
      { de: "wieso", tr: "niye" },
      { de: "etwa", tr: "yaklaşık" },
      { de: "völlig", tr: "tamamen" },
    ],
    patterns: [
      { de: "…, deshalb / darum / deswegen …", tr: "bu yüzden; zarf birinci sırada, fiil ikinci" },
      { de: "…, trotzdem …", tr: "yine de; aynı diziliş" },
      { de: "…, denn …", tr: "çünkü; sıra değişmez" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün cümleleri sonuçla bağlayacağız: 'Trafik vardı, bu yüzden geç kaldım.' Almancada deshalb, darum, deswegen aynı şey; hepsi bir kurala uyar: birinci sırayı kaplar, fiil hemen arkasına. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Üç tür bağlaç var: yan cümle bağlaçları fiili sona atar (weil), ana cümle bağlaçları sırayı bozmaz (denn), zarflar birinci sırayı kaplar (deshalb). Bugün zarflar. Önce kelimeler.")] },
      word("İlk", { de: "der Stau", tr: "trafik sıkışıklığı" }),
      word("İkinci", { de: "die Entscheidung", tr: "karar" }),
      word("Üçüncü", { de: "ablehnen", tr: "reddetmek" }),
      word("Dördüncü", { de: "deswegen", tr: "bu yüzden" }),
      word("Beşinci", { de: "die Ursache", tr: "neden" }),
      word("Altıncı", { de: "wieso", tr: "niye" }),
      word("Yedinci", { de: "etwa", tr: "yaklaşık" }),
      word("Son", { de: "völlig", tr: "tamamen" }),
      { say: [tr("Kalıp:"), de("deshalb"), tr("'bu yüzden'. 'Es gab Stau, deshalb habe ich mich verspätet.' deshalb birinci sırada, habe ikinci, ich üçüncü.")] },
      { say: [tr("Tekrar edin:"), de("Es gab Stau, deshalb habe ich mich verspätet")], expect: repeat("Es gab Stau, deshalb habe ich mich verspätet") },
      { say: [tr("Sıra sende: 'Teklif kötüydü, bu yüzden reddettim.' — 'Das Angebot war schlecht, deshalb …'")], expect: produce("Das Angebot war schlecht, deshalb habe ich es abgelehnt", [tr("deshalb + fiil + özne: deshalb habe ich:"), de("Das Angebot war schlecht, deshalb habe ich es abgelehnt."), tr("Tekrar dene.")], ["Das Angebot war schlecht, deshalb lehnte ich es ab", "Das Angebot war schlecht, darum habe ich es abgelehnt"]) },
      { say: [tr("Karşıtı trotzdem: beklenenin tersi. 'Das Angebot war gut, trotzdem habe ich es abgelehnt.' Aynı diziliş.")] },
      { say: [tr("Sıra sende: 'Yorgundum, yine de spora gittim.' — 'Ich war müde, trotzdem …'")], expect: produce("Ich war müde, trotzdem bin ich zum Sport gegangen", [tr("trotzdem + fiil + özne; gehen → bin gegangen:"), de("Ich war müde, trotzdem bin ich zum Sport gegangen."), tr("Tekrar dene.")], ["Ich war müde, trotzdem ging ich zum Sport"]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich hatte keine Zeit, deshalb ich bin nicht gekommen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich hatte keine Zeit, deshalb ich bin nicht gekommen.", false, [de("deshalb"), tr("birinci sırayı kaplar; fiil ikinci sırada olmalı:"), de("…, deshalb bin ich nicht gekommen.")]) },
      { say: [tr("Son: aynı fikri denn ile — 'Geç kaldım, çünkü trafik vardı.' — 'Ich habe mich verspätet, denn …' (sıra değişmez!)")], expect: produce("Ich habe mich verspätet, denn es gab Stau", [tr("denn ana cümle bağlacı: özne + fiil sırası korunur: denn es gab:"), de("Ich habe mich verspätet, denn es gab Stau."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada geç kalmanın sebebini ve buna rağmen ne yaptığını anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Patronuna toplantıya neden geç kaldığını açıklıyorsun: sebep (denn/deshalb), yine de neyi yetiştirdiğin (trotzdem), bundan sonra ne yapacağın.",
      partner: "ciddi ama adil bir yönetici",
      opening: "Sie sind zwanzig Minuten zu spät. Was ist passiert?",
      openingTr: "Yirmi dakika geç kaldınız. Ne oldu?",
      goal: "Geç kalma sebebi, yine de yetiştirdiğin iş ve bundan sonraki önlemin söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-je-desto",
    icon: "chart",
    level: "B1",
    course: "de",
    title: "Je mehr, desto besser",
    titleTr: "Orantı: je … desto",
    summary: "İki şeyin birlikte arttığını je … desto ile söylemeyi öğretir.",
    minutes: 10,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "flüssig", tr: "akıcı" },
      { de: "je", tr: "başına; ne kadar" },
      { de: "tatsächlich", tr: "gerçekten de" },
      { de: "absolut", tr: "kesinlikle" },
      { de: "interessiert", tr: "ilgilenen" },
      { de: "gar", tr: "hiç" },
      { de: "klasse", tr: "şahane" },
      { de: "wert", tr: "değerinde" },
    ],
    patterns: [
      { de: "Je + Komparativ …, desto + Komparativ …", tr: "ne kadar … o kadar …" },
      { de: "Je mehr ich übe, desto besser werde ich.", tr: "je…desto ile tam cümle" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün 'ne kadar çok çalışırsam o kadar iyi olurum' demeyi öğreneceğiz: je … desto. İki karşılaştırma, iki cümle, tek kural. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yapı: 'Je' + Komparativ + yan cümle (fiil sona), virgül, 'desto' + Komparativ + fiil + özne. İlk yarı yan cümle, ikinci yarı ana cümle. Önce kelimeler.")] },
      word("İlk", { de: "flüssig", tr: "akıcı" }),
      word("İkinci", { de: "je", tr: "başına; ne kadar" }),
      word("Üçüncü", { de: "tatsächlich", tr: "gerçekten de" }),
      word("Dördüncü", { de: "absolut", tr: "kesinlikle" }),
      word("Beşinci", { de: "interessiert", tr: "ilgilenen" }),
      word("Altıncı", { de: "gar", tr: "hiç" }),
      word("Yedinci", { de: "klasse", tr: "şahane" }),
      word("Son", { de: "wert", tr: "değerinde" }),
      { say: [tr("Kalıp:"), de("Je …, desto …"), tr("'Je mehr ich übe, desto besser werde ich.' — je yarısında fiil sonda (übe), desto yarısında fiil özneden önce (werde ich).")] },
      { say: [tr("Tekrar edin:"), de("Je mehr ich übe, desto besser werde ich")], expect: repeat("Je mehr ich übe, desto besser werde ich") },
      { say: [tr("Sıra sende: 'Ne kadar çok okursam kelime hazinem o kadar büyük olur.' — 'Je mehr ich lese, desto …' (groß → größer)")], expect: produce("Je mehr ich lese, desto größer wird mein Wortschatz", [tr("desto + Komparativ + fiil + özne: desto größer wird mein Wortschatz:"), de("Je mehr ich lese, desto größer wird mein Wortschatz."), tr("Tekrar dene.")]) },
      { say: [tr("'Ne kadar çok deneyimim olursa o kadar özgüvenli olurum.' — 'Je mehr Erfahrung ich habe, desto …'")], expect: produce("Je mehr Erfahrung ich habe, desto selbstbewusster bin ich", [tr("selbstbewusst → selbstbewusster; desto yarısı: bin ich:"), de("Je mehr Erfahrung ich habe, desto selbstbewusster bin ich."), tr("Tekrar dene.")], ["Je mehr Erfahrung ich habe, desto selbstbewusster werde ich"]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Je länger ich lerne, desto ich spreche flüssiger."), tr("cümlesi doğru mu?")], expect: truefalse("Je länger ich lerne, desto ich spreche flüssiger.", false, [de("desto"), tr("yarısında Komparativ hemen desto'dan sonra, ardından fiil ve özne:"), de("Je länger ich lerne, desto flüssiger spreche ich.")]) },
      { say: [tr("Son: 'Ne kadar erken başlarsan o kadar kolay olur.' — 'Je früher du anfängst, desto …' (leicht → leichter)")], expect: produce("Je früher du anfängst, desto leichter ist es", [tr("je früher … anfängst (ayrılabilen fiil birleşik, sonda), desto leichter ist es:"), de("Je früher du anfängst, desto leichter ist es."), tr("Tekrar dene.")], ["Je früher du anfängst, desto leichter wird es"]) },
      { say: [tr("Hazırsın. Konuşmada dil öğrenme tavsiyesi vereceksin: je…desto ile üç kural.")] },
    ],
    roleplay: {
      scene: "Almanca öğrenmeye yeni başlayan biri sana tavsiye soruyor. En az üç öğüdü 'je … desto' ile ver; karşındaki 'stimmt das wirklich?' diye sorgular.",
      partner: "yeni başlayan, biraz kaygılı bir öğrenci",
      opening: "Du sprichst schon so gut! Ich fange gerade erst an. Hast du Tipps für mich?",
      openingTr: "Sen çok iyi konuşuyorsun! Ben daha yeni başlıyorum. Bana tavsiyen var mı?",
      goal: "En az üç öğüt verilmiş ve karşındaki hangisini deneyeceğini söylemiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-entweder-oder",
    icon: "question",
    level: "B1",
    course: "de",
    title: "Entweder … oder …",
    titleTr: "İkili bağlaçlar: entweder…oder, sowohl…als auch, weder…noch",
    summary: "Seçenekleri, ikisini birden ve hiçbirini ikili bağlaçlarla söylemeyi öğretir.",
    minutes: 10,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "die Alternative", tr: "seçenek" },
      { de: "vegetarisch", tr: "vejetaryen" },
      { de: "auswählen", tr: "seçmek" },
      { de: "sondern", tr: "aksine" },
      { de: "dagegen", tr: "buna karşı" },
      { de: "der Typ", tr: "tip" },
      { de: "eher", tr: "daha çok" },
      { de: "genauso", tr: "aynen" },
    ],
    patterns: [
      { de: "entweder … oder …", tr: "ya … ya da …" },
      { de: "sowohl … als auch …", tr: "hem … hem de …" },
      { de: "weder … noch …", tr: "ne … ne de … (olumsuz, nicht eklenmez)" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün üç ikili bağlaç: ya…ya da, hem…hem de, ne…ne de. Türkçede de ikili; tuzak sonuncuda: 'weder…noch' zaten olumsuz, nicht eklenmez. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Üçü de aynı cinsten öğeleri bağlar: iki isim, iki fiil, iki cümle. Önce kelimeler.")] },
      word("İlk", { de: "die Alternative", tr: "seçenek" }),
      word("İkinci", { de: "vegetarisch", tr: "vejetaryen" }),
      word("Üçüncü", { de: "auswählen", tr: "seçmek" }),
      word("Dördüncü", { de: "sondern", tr: "aksine" }),
      word("Beşinci", { de: "dagegen", tr: "buna karşı" }),
      word("Altıncı", { de: "der Typ", tr: "tip" }),
      word("Yedinci", { de: "eher", tr: "daha çok" }),
      word("Son", { de: "genauso", tr: "aynen" }),
      { say: [tr("İlk kalıp:"), de("entweder … oder"), tr("'ya … ya da'. 'Ich fahre entweder mit dem Fahrrad oder mit dem Bus.'")] },
      { say: [tr("Tekrar edin:"), de("Ich fahre entweder mit dem Fahrrad oder mit dem Bus")], expect: repeat("Ich fahre entweder mit dem Fahrrad oder mit dem Bus") },
      { say: [tr("Sıra sende: 'Ya bugün ya da yarın karar veriyoruz.' — 'Wir entscheiden uns entweder …'")], expect: produce("Wir entscheiden uns entweder heute oder morgen", [tr("entweder … oder iki zarfı bağlar:"), de("Wir entscheiden uns entweder heute oder morgen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıp:"), de("sowohl … als auch"), tr("'hem … hem de'. 'Sie spricht sowohl Deutsch als auch Türkisch.' Üçüncüsü:"), de("weder … noch"), tr("'ne … ne de': 'Ich esse weder Fleisch noch Fisch.' — nicht YOK.")] },
      { say: [tr("Sıra sende: 'Hem et hem balık yiyorum.' — 'Ich esse sowohl …'")], expect: produce("Ich esse sowohl Fleisch als auch Fisch", [tr("sowohl X als auch Y:"), de("Ich esse sowohl Fleisch als auch Fisch."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich trinke weder Kaffee noch nicht Tee."), tr("cümlesi doğru mu?")], expect: truefalse("Ich trinke weder Kaffee noch nicht Tee.", false, [de("weder … noch"), tr("zaten olumsuzdur; nicht eklenmez:"), de("Ich trinke weder Kaffee noch Tee.")]) },
      { say: [tr("Son: 'Ne vaktim ne de param var.' — 'Ich habe weder …'")], expect: produce("Ich habe weder Zeit noch Geld", [tr("weder Zeit noch Geld, nicht/kein olmadan:"), de("Ich habe weder Zeit noch Geld."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir hafta sonu planı için seçenekleri tartacaksın: ya…ya da, hem…hem de, ne…ne de.")] },
    ],
    roleplay: {
      scene: "Arkadaşınla hafta sonu planı: iki seçenek arasında karar (entweder…oder), ikisini birden yapmak (sowohl…als auch), yapmak istemediklerin (weder…noch).",
      partner: "kararsız, seçenek üreten bir arkadaş",
      opening: "Samstag: Wandern oder Museum? Oder beides? Ich kann mich nicht entscheiden — was meinst du?",
      openingTr: "Cumartesi: yürüyüş mü müze mi? Ya da ikisi de? Karar veremiyorum — sen ne dersin?",
      goal: "Hafta sonu için seçenekler tartılmış ve tek bir planda anlaşılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-geschichte",
    icon: "book",
    level: "B1",
    course: "de",
    title: "Eine runde Geschichte",
    titleTr: "Bağlaçlarla anlatı",
    summary: "Modülün bağlaçlarını bir hikâyede birleştirmeyi öğretir: zuerst, nachdem, während, deshalb, am Ende.",
    minutes: 12,
    focusId: "Nebensatz-nachdem",
    vocab: [
      { de: "geschehen", tr: "meydana gelmek" },
      { de: "retten", tr: "kurtarmak" },
      { de: "verschwinden", tr: "kaybolmak" },
      { de: "erfahren", tr: "öğrenmek" },
      { de: "die Wahrheit", tr: "gerçek" },
      { de: "plötzlich", tr: "aniden" },
      { de: "die Tat", tr: "eylem" },
      { de: "die Freude", tr: "sevinç" },
    ],
    patterns: [
      { de: "Zuerst …, dann …, am Ende …", tr: "anlatı iskeleti" },
      { de: "Nachdem … hatte, …", tr: "sıralı geçmiş" },
      { de: "Während …, … / …, deshalb …", tr: "eş zaman ve sonuç" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bu modülün son dersi: öğrendiğin bağlaçlarla yuvarlak bir hikâye anlatacaksın. İskelet: zuerst, nachdem, während, plötzlich, deshalb, am Ende. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İyi bir anlatı üç şey ister: sıra (zuerst, dann, danach), bağ (nachdem, während, weil) ve kapanış (am Ende, zum Schluss). Önce kelimeler.")] },
      word("İlk", { de: "geschehen", tr: "meydana gelmek" }),
      word("İkinci", { de: "retten", tr: "kurtarmak" }),
      word("Üçüncü", { de: "verschwinden", tr: "kaybolmak" }),
      word("Dördüncü", { de: "erfahren", tr: "öğrenmek" }),
      word("Beşinci", { de: "die Wahrheit", tr: "gerçek" }),
      word("Altıncı", { de: "plötzlich", tr: "aniden" }),
      word("Yedinci", { de: "die Tat", tr: "eylem" }),
      word("Son", { de: "die Freude", tr: "sevinç" }),
      { say: [tr("Hikâyemiz: Geç kalınan bir tren. Başlangıç:"), de("Zuerst habe ich in Ruhe gefrühstückt."), tr("Tekrar edin:"), de("Zuerst habe ich in Ruhe gefrühstückt")], expect: repeat("Zuerst habe ich in Ruhe gefrühstückt") },
      { say: [tr("Devam et: 'Kahvaltı ettikten sonra istasyona gittim.' — 'Nachdem ich gefrühstückt hatte, …'")], expect: produce("Nachdem ich gefrühstückt hatte, bin ich zum Bahnhof gegangen", [tr("nachdem + Plusquamperfekt, sonra Perfekt:"), de("Nachdem ich gefrühstückt hatte, bin ich zum Bahnhof gegangen."), tr("Tekrar dene.")], ["Nachdem ich gefrühstückt hatte, ging ich zum Bahnhof"]) },
      { say: [tr("'Beklerken aniden telefonum çaldı.' — 'Während ich wartete, …' (klingeln)")], expect: produce("Während ich wartete, hat plötzlich mein Handy geklingelt", [tr("während yan cümle; ana cümle fiille: hat plötzlich mein Handy geklingelt:"), de("Während ich wartete, hat plötzlich mein Handy geklingelt."), tr("Tekrar dene.")], ["Während ich wartete, klingelte plötzlich mein Handy"]) },
      { say: [tr("'Uzun konuştum, bu yüzden treni kaçırdım.' — 'Ich habe lange telefoniert, deshalb …'")], expect: produce("Ich habe lange telefoniert, deshalb habe ich den Zug verpasst", [tr("deshalb + fiil + özne:"), de("Ich habe lange telefoniert, deshalb habe ich den Zug verpasst."), tr("Tekrar dene.")], ["Ich habe lange telefoniert, deshalb verpasste ich den Zug"]) },
      { say: [tr("Doğru mu yanlış mı: anlatı sırası için"), de("Am Ende bin ich mit dem nächsten Zug gefahren und war erleichtert."), tr("cümlesi doğru mu?")], expect: truefalse("Am Ende bin ich mit dem nächsten Zug gefahren und war erleichtert.", true, [de("Am Ende"), tr("kapanış zarfı; birinci sırayı kaplar, fiil ikinci: bin ich. Doğru.")]) },
      { say: [tr("Son: kapanışı sen yaz — 'Sonunda bir sonraki trene bindim.' — 'Am Ende …' (nehmen)")], expect: produce("Am Ende habe ich den nächsten Zug genommen", [tr("Am Ende + fiil + özne; nehmen → genommen:"), de("Am Ende habe ich den nächsten Zug genommen."), tr("Tekrar dene.")], ["Am Ende nahm ich den nächsten Zug", "Zum Schluss habe ich den nächsten Zug genommen"]) },
      { say: [tr("Hazırsın. Konuşmada kendi başından geçen küçük bir olayı baştan sona anlatacaksın; karşındaki ayrıntı isteyecek.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına başından geçen küçük bir olayı (geç kalma, kayıp eşya, sürpriz) baştan sona anlat: zuerst, nachdem, während, plötzlich, deshalb, am Ende.",
      partner: "ayrıntı isteyen, 'und dann?' diye soran bir arkadaş",
      opening: "Du siehst aus, als hättest du etwas erlebt. Erzähl von Anfang an — was ist passiert?",
      openingTr: "Bir şey yaşamış gibisin. Baştan anlat — ne oldu?",
      goal: "Olay baştan sona, sırasıyla anlatılmış ve nasıl bittiği söylenmiş olur.",
      minTurns: 8,
    },
  },
];
