import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 7 — Kültür ve sanat (061–070).
 *
 * Bu modülün dilbilgisel merkezi ilgi cümlesinin en son ve en zor hâli:
 * tamlayan hâlindeki ilgi zamiri (dessen / deren). B1'de "kitabı okuduğumuz
 * yazar" için iki cümle gerekiyordu; B2'de tek cümle yetiyor — ama zamirin
 * biçimi ÖNCEKİ ismin cinsine, çekimli fiil ise SONRAKİ ismin sayısına
 * bağlı. İki ayrı yere bakmak gerekiyor ve öğrenci genellikle birine bakıp
 * ötekini unutuyor; modülün doğru/yanlış maddeleri bilerek bu iki noktaya
 * ayrıldı.
 *
 * İkinci hat ince tanımlama: sanat konuşmak, bir şeyin nasıl olduğunu değil
 * SANA NE YAPTIĞINI anlatmayı gerektiriyor. Bu yüzden ortaç sıfatları,
 * yöntem bağlacı ve orantı bağlacı burada estetik yargı kurmak için
 * kullanılıyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B07: Lesson[] = [
  {
    id: "de-b2-roman",
    icon: "book",
    level: "B2",
    course: "de",
    title: "Ein Roman, über den man spricht",
    titleTr: "Edebiyat sohbeti",
    summary: "Bir kitabı edatlı ilgi cümleleriyle tanıtmayı öğretir.",
    minutes: 11,
    focusId: "Relativsatz-Präposition",
    vocab: [
      { de: "der Roman", tr: "roman" },
      { de: "die Handlung", tr: "olay örgüsü" },
      { de: "der Erzähler", tr: "anlatıcı" },
      { de: "fesseln", tr: "sarmak, esir almak" },
      { de: "das Kapitel", tr: "bölüm" },
    ],
    patterns: [
      { de: "ein Buch, über das …", tr: "edatlı ilgi cümlesi" },
      { de: "Die Handlung dreht sich um …", tr: "konuyu özetler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: kültür ve sanat. Bir kitaptan söz ederken Almanca çoğu zaman ilgi cümlesi kurar ve o cümle bir edatla başlar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kritik nokta şu: edattan sonraki zamir, ismin CİNSİNE göre değişir. Nötr bir isim için başka, eril için başka. Önce kelimeler.")] },
      word("İlk", { de: "der Roman", tr: "roman" }),
      word("İkinci", { de: "die Handlung", tr: "olay örgüsü" }),
      word("Üçüncü", { de: "der Erzähler", tr: "anlatıcı" }),
      word("Dördüncü", { de: "fesseln", tr: "sarmak, esir almak" }),
      word("Son", { de: "das Kapitel", tr: "bölüm" }),
      { say: [tr("Kalıbımız:"), de("ein Buch, über das man lange spricht"), tr("Kitap nötr olduğu için zamir de nötr biçimde.")] },
      { say: [tr("Örnek:"), de("Das ist ein Buch, über das man lange spricht."), tr("Tekrar edin:"), de("Das ist ein Buch, über das man lange spricht")], expect: repeat("Das ist ein Buch, über das man lange spricht") },
      { say: [tr("Sıra sende: 'Olay örgüsü bir aile etrafında dönüyor.'")], expect: produce("Die Handlung dreht sich um eine Familie", [tr("Bu dönüşlü fiil um edatını belirtme hâliyle alır:"), de("Die Handlung dreht sich um eine Familie."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Uzun süre üzerine düşündüğüm bir kitap.'")], expect: produce("Ein Buch, über das ich lange nachgedacht habe", [tr("Yan cümlede yardımcı fiil en sonda:"), de("Ein Buch, über das ich lange nachgedacht habe."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Beni ilk sayfadan itibaren sardı.'")], expect: produce("Es hat mich ab der ersten Seite gefesselt", [tr("Edat yönelme hâli ister; ortaç sonda:"), de("Es hat mich ab der ersten Seite gefesselt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist ein Buch, über den man lange spricht."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist ein Buch, über den man lange spricht.", false, [tr("İlgi zamiri kendinden önceki ismin cinsini alır ve kitap nötrdür:"), de("Das ist ein Buch, über das man lange spricht.")]) },
      { say: [tr("Son: 'Son bölümü iki kez okudum.'")], expect: produce("Das letzte Kapitel habe ich zweimal gelesen", [tr("Nesne öne alınmış; yardımcı fiil ikinci sırada:"), de("Das letzte Kapitel habe ich zweimal gelesen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kitabı önereceksin: konusu ne, neyi iyi yapıyor, kime uygun.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına okuduğun bir romanı öneriyorsun: konusu ne, anlatıcısı nasıl, neyi iyi yapıyor ve kime uygun. Kitabı ilgi cümleleriyle tanıt.",
      partner: "kalın kitaplardan çekinen, ikna edilmesi gereken bir arkadaş",
      opening: "Sechshundert Seiten? Sag mir in einem Satz, worum es geht — dann entscheide ich.",
      openingTr: "Altı yüz sayfa mı? Tek cümleyle ne hakkında olduğunu söyle — sonra karar veririm.",
      goal: "Kitabın konusu ve güçlü yanı anlatılmış ve arkadaşın okuyup okumayacağına karar vermiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-dessen-deren",
    icon: "pen",
    level: "B2",
    course: "de",
    title: "Der Autor, dessen Buch…",
    titleTr: "İlgi cümlesi: tamlayan hâli",
    summary: "dessen ve deren ile iki cümleyi tek cümlede birleştirmeyi öğretir.",
    minutes: 11,
    focusId: "Relativsatz-Genitiv",
    vocab: [
      { de: "der Umschlag", tr: "kapak" },
      { de: "die Band", tr: "müzik grubu" },
      { de: "überraschen", tr: "şaşırtmak" },
      { de: "der Titel", tr: "başlık, ad" },
      { de: "verfassen", tr: "kaleme almak" },
    ],
    patterns: [
      { de: "…, dessen …", tr: "eril ve nötr: onun …-i" },
      { de: "…, deren …", tr: "dişil ve çoğul: onun …-i" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ilgi cümlesinin en son hâli: sahiplik bildiren biçimi. Türkçede 'kitabı ünlü olan yazar' deriz; Almanca bunu iki zamirle yapar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural: eril ve nötr isimler için bir biçim, dişil ve çoğul için başka biçim. Ve dikkat — fiil, zamirin değil ARKASINDAKİ ismin sayısına uyar. Önce kelimeler.")] },
      word("İlk", { de: "der Umschlag", tr: "kapak" }),
      word("İkinci", { de: "die Band", tr: "müzik grubu" }),
      word("Üçüncü", { de: "überraschen", tr: "şaşırtmak" }),
      word("Dördüncü", { de: "der Titel", tr: "başlık, ad" }),
      word("Son", { de: "verfassen", tr: "kaleme almak" }),
      { say: [tr("Kalıbımız:"), de("…, dessen …"), tr("ve"), de("…, deren …"), tr("Birincisi eril ve nötr, ikincisi dişil ve çoğul.")] },
      { say: [tr("Örnek:"), de("Der Autor, dessen Buch wir lesen, kommt aus Wien."), tr("Tekrar edin:"), de("Der Autor, dessen Buch wir lesen, kommt aus Wien")], expect: repeat("Der Autor, dessen Buch wir lesen, kommt aus Wien") },
      { say: [tr("Sıra sende: 'Sonu beni şaşırtan film.'")], expect: produce("Der Film, dessen Ende mich überrascht hat", [tr("Eril isimden sonra dessen; yan cümlede yardımcı fiil sonda:"), de("Der Film, dessen Ende mich überrascht hat."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi dişille: 'Şarkılarını herkesin bildiği bir grup.'")], expect: produce("Eine Band, deren Lieder jeder kennt", [tr("Dişil isimden sonra deren; fiil yan cümlenin sonunda:"), de("Eine Band, deren Lieder jeder kennt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kapağı çok güzel olan bir kitap.'")], expect: produce("Ein Buch, dessen Umschlag sehr schön ist", [tr("Nötr isimden sonra da dessen:"), de("Ein Buch, dessen Umschlag sehr schön ist."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Eine Band, deren Lieder jeder kennt."), tr("cümlesi doğru mu?")], expect: truefalse("Eine Band, deren Lieder jeder kennt.", true, [tr("Doğru. Dişil isimden sonra deren geliyor ve fiil yan cümlenin sonunda duruyor.")]) },
      { say: [tr("Son: 'Adını unuttuğum yazar.'")], expect: produce("Die Autorin, deren Namen ich vergessen habe", [tr("Dişil isimden sonra deren; nesne belirtme hâlinde:"), de("Die Autorin, deren Namen ich vergessen habe."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sevdiğin eserleri tanıtacaksın: hangisinin nesi seni etkiledi.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla sevdiğiniz eserleri konuşuyorsunuz: hangi kitabın sonu, hangi filmin müziği, hangi grubun sözleri seni etkiledi. Her birini tek cümlede, sahiplik bildiren ilgi cümlesiyle tanıt.",
      partner: "kendi örneklerini de anlatan, meraklı bir arkadaş",
      opening: "Ich frage sowas gern: Gibt es ein Buch, dessen Ende dich wirklich umgehauen hat?",
      openingTr: "Bunu sormayı severim: Sonu seni gerçekten çarpan bir kitap var mı?",
      goal: "En az iki eser sahiplik bildiren ilgi cümleleriyle tanıtılmış ve neden etkilediği anlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-theater",
    icon: "art",
    level: "B2",
    course: "de",
    title: "Nach der Premiere",
    titleTr: "Tiyatro yorumu",
    summary: "Bir sahnelemeyi ortaç sıfatlarıyla değerlendirmeyi öğretir.",
    minutes: 11,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "die Inszenierung", tr: "sahneleme" },
      { de: "das Bühnenbild", tr: "dekor" },
      { de: "überzeugen", tr: "ikna etmek" },
      { de: "die Premiere", tr: "prömiyer" },
      { de: "der Applaus", tr: "alkış" },
    ],
    patterns: [
      { de: "die gefeierte Inszenierung", tr: "övülen sahneleme" },
      { de: "Die Schauspieler haben überzeugt.", tr: "kısa yargı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Tiyatrodan yeni çıktın ve fikrini söyleyeceksin. Sanat yorumunun dili sıkışıktır: bir sıfat, bir yargı, bir gerekçe. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Ortaç sıfatları burada çok işine yarar — 'övülen sahneleme', 'yeni tasarlanan dekor'. Tek kelimede hem bilgi hem yargı var. Önce kelimeler.")] },
      word("İlk", { de: "die Inszenierung", tr: "sahneleme" }),
      word("İkinci", { de: "das Bühnenbild", tr: "dekor" }),
      word("Üçüncü", { de: "überzeugen", tr: "ikna etmek" }),
      word("Dördüncü", { de: "die Premiere", tr: "prömiyer" }),
      word("Son", { de: "der Applaus", tr: "alkış" }),
      { say: [tr("Kalıbımız:"), de("die gefeierte Inszenierung"), tr("Ortaç ismin önünde, sıfat ekiyle.")] },
      { say: [tr("Örnek:"), de("Die gefeierte Inszenierung läuft noch bis Mai."), tr("Tekrar edin:"), de("Die gefeierte Inszenierung läuft noch bis Mai")], expect: repeat("Die gefeierte Inszenierung läuft noch bis Mai") },
      { say: [tr("Sıra sende: 'Oyuncular ikna ediciydi.'")], expect: produce("Die Schauspieler haben überzeugt", [tr("Bu fiil nesnesiz de kullanılır ve 'başarılıydı' anlamına gelir:"), de("Die Schauspieler haben überzeugt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yeni tasarlanan dekor sade.'")], expect: produce("Das neu gestaltete Bühnenbild ist schlicht", [tr("Zarf ve ortaç birlikte ismin önünde:"), de("Das neu gestaltete Bühnenbild ist schlicht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Prömiyerden sonra uzun bir alkış vardı.'")], expect: produce("Nach der Premiere gab es langen Applaus", [tr("Edat yönelme hâli ister; kalıplaşmış fiil ikinci sırada:"), de("Nach der Premiere gab es langen Applaus."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nach die Premiere gab es langen Applaus."), tr("cümlesi doğru mu?")], expect: truefalse("Nach die Premiere gab es langen Applaus.", false, [tr("Bu edat her zaman yönelme hâli ister:"), de("Nach der Premiere gab es langen Applaus.")]) },
      { say: [tr("Son: 'Beklediğim şey bu değildi.'")], expect: produce("Das war nicht das, was ich erwartet hatte", [tr("İşaret zamiri ve ilgi cümlesi; yardımcı fiil sonda:"), de("Das war nicht das, was ich erwartet hatte."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada gördüğün oyunu değerlendireceksin: neyi beğendin, neyi beğenmedin.")] },
    ],
    roleplay: {
      scene: "Bir tiyatro çıkışındasın ve yanındaki kişiyle oyunu değerlendiriyorsun: sahneleme, oyunculuk ve dekor hakkında ne düşünüyorsun, neyi beğenmedin ve yine de tavsiye eder misin.",
      partner: "oyunu çok beğenmiş, senin itirazlarını merak eden bir tiyatrosever",
      opening: "Ich fand das großartig — vor allem das Bühnenbild. Wie hat es Ihnen gefallen?",
      openingTr: "Bence harikaydı — özellikle dekor. Size nasıl geldi?",
      goal: "Sahneleme, oyunculuk ve dekor hakkında ayrı ayrı yargı verilmiş ve tavsiye edilip edilmeyeceği söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-museum-fuehrung",
    icon: "culture",
    level: "B2",
    course: "de",
    title: "Die Führung leiten",
    titleTr: "Müzede rehberlik",
    summary: "Eserleri edilgen geçmiş zamanla tanıtmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "das Gemälde", tr: "tablo" },
      { de: "erbauen", tr: "inşa etmek" },
      { de: "stammen aus", tr: "…-den gelmek" },
      { de: "die Epoche", tr: "dönem" },
      { de: "der Rundgang", tr: "tur, gezi" },
    ],
    patterns: [
      { de: "wurde … gemalt / erbaut", tr: "eserin yapılış zamanı" },
      { de: "stammt aus …", tr: "kökenini bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün rehber sensin. Müze anlatımının dili edilgen geçmiş zamandır: eser ne zaman yapıldı, kim yaptığı çoğu zaman ikinci planda. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu zamanı kaza raporunda görmüştün; burada aynı yapı, çok daha sakin bir tonla. Önce kelimeler.")] },
      word("İlk", { de: "das Gemälde", tr: "tablo" }),
      word("İkinci", { de: "erbauen", tr: "inşa etmek" }),
      word("Üçüncü", { de: "stammen aus", tr: "…-den gelmek" }),
      word("Dördüncü", { de: "die Epoche", tr: "dönem" }),
      word("Son", { de: "der Rundgang", tr: "tur, gezi" }),
      { say: [tr("Kalıbımız:"), de("wurde … gemalt"), tr("Edilgen geçmiş zaman; yazıda ve anlatımda tercih edilen biçim.")] },
      { say: [tr("Örnek:"), de("Dieses Gemälde wurde sechzehnhundertzweiundvierzig gemalt."), tr("Tekrar edin:"), de("Dieses Gemälde wurde sechzehnhundertzweiundvierzig gemalt")], expect: repeat("Dieses Gemälde wurde sechzehnhundertzweiundvierzig gemalt") },
      { say: [tr("Sıra sende: 'Bina on sekizinci yüzyılda inşa edildi.'")], expect: produce("Das Gebäude wurde im achtzehnten Jahrhundert erbaut", [tr("Zaman ortaçtan önce; ortaç en sonda:"), de("Das Gebäude wurde im achtzehnten Jahrhundert erbaut."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu eser Barok döneminden geliyor.'")], expect: produce("Dieses Werk stammt aus der Epoche des Barock", [tr("Edat yönelme hâli ister; sonrasında tamlama:"), de("Dieses Werk stammt aus der Epoche des Barock."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Turumuz burada başlıyor.'")], expect: produce("Unser Rundgang beginnt hier", [tr("Kısa ve net bir açılış cümlesi:"), de("Unser Rundgang beginnt hier."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Gebäude wurde im achtzehnten Jahrhundert erbauen."), tr("cümlesi doğru mu?")], expect: truefalse("Das Gebäude wurde im achtzehnten Jahrhundert erbauen.", false, [tr("Edilgende mastar değil ortaç gelir:"), de("Das Gebäude wurde im achtzehnten Jahrhundert erbaut.")]) },
      { say: [tr("Son: 'Lütfen ışığa dikkat edin.'")], expect: produce("Beachten Sie bitte das Licht", [tr("Rica biçiminde fiil başta:"), de("Beachten Sie bitte das Licht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir ziyaretçiye eseri anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir müzede küçük bir gruba rehberlik ediyorsun. Turun nereden başladığını söyle, bir eseri tanıt (ne zaman, hangi dönem), gelen soruyu cevapla ve turu bir sonraki salona bağla.",
      partner: "meraklı, ayrıntı soran bir ziyaretçi",
      opening: "Entschuldigen Sie — wissen Sie, wann dieses Bild eigentlich gemalt wurde?",
      openingTr: "Affedersiniz — bu tablonun ne zaman yapıldığını biliyor musunuz?",
      goal: "Bir eserin yapılış zamanı ve dönemi anlatılmış, bir soru cevaplanmış ve tur bir sonraki durağa bağlanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-musik-analyse",
    icon: "music",
    level: "B2",
    course: "de",
    title: "Warum berührt uns Musik?",
    titleTr: "Müzik analizi",
    summary: "Müziğin nasıl etki ettiğini yöntem bağlacıyla anlatmayı öğretir.",
    minutes: 11,
    focusId: "Nebensatz-indem",
    vocab: [
      { de: "berühren", tr: "etkilemek, dokunmak" },
      { de: "die Gänsehaut", tr: "tüylerin ürpermesi" },
      { de: "der Rhythmus", tr: "ritim" },
      { de: "die Melodie", tr: "melodi" },
      { de: "wirken", tr: "etki etmek" },
    ],
    patterns: [
      { de: "…, indem sie …", tr: "nasıl etki ettiğini söyler" },
      { de: "Gänsehaut bekommen", tr: "tüyleri ürpermek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün zor bir soru: müzik bizi neden etkiliyor. Cevabı 'nasıl' diye kurmak gerekiyor ve bunun bağlacını biliyorsun. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Anıları uyandırarak etkiliyor' — işte tam olarak bu yapı. Sanat konuşmasında en çok işe yarayan cümle biçimi bu. Önce kelimeler.")] },
      word("İlk", { de: "berühren", tr: "etkilemek, dokunmak" }),
      word("İkinci", { de: "die Gänsehaut", tr: "tüylerin ürpermesi" }),
      word("Üçüncü", { de: "der Rhythmus", tr: "ritim" }),
      word("Dördüncü", { de: "die Melodie", tr: "melodi" }),
      word("Son", { de: "wirken", tr: "etki etmek" }),
      { say: [tr("Kalıbımız:"), de("…, indem sie …"), tr("Yan cümle; çekimli fiil sonda.")] },
      { say: [tr("Örnek:"), de("Musik berührt uns, indem sie Erinnerungen weckt."), tr("Tekrar edin:"), de("Musik berührt uns, indem sie Erinnerungen weckt")], expect: repeat("Musik berührt uns, indem sie Erinnerungen weckt") },
      { say: [tr("Sıra sende: 'Ritmi değiştirerek gerilim yaratıyor.'")], expect: produce("Sie erzeugt Spannung, indem sie den Rhythmus ändert", [tr("Yan cümlede fiil sonda:"), de("Sie erzeugt Spannung, indem sie den Rhythmus ändert."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Melodi basit ama etkili.'")], expect: produce("Die Melodie ist einfach, wirkt aber stark", [tr("İkinci cümlede özne tekrarlanmıyor:"), de("Die Melodie ist einfach, wirkt aber stark."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Tüylerim ürperdi.'")], expect: produce("Ich habe eine Gänsehaut bekommen", [tr("Kalıplaşmış ifade; ortaç sonda:"), de("Ich habe eine Gänsehaut bekommen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dieses Lied erinnert mich an meiner Kindheit."), tr("cümlesi doğru mu?")], expect: truefalse("Dieses Lied erinnert mich an meiner Kindheit.", false, [tr("Bu fiilin sabit edatı belirtme hâli ister:"), de("Dieses Lied erinnert mich an meine Kindheit.")]) },
      { say: [tr("Son: 'Bu şarkı bana çocukluğumu hatırlatıyor.'")], expect: produce("Dieses Lied erinnert mich an meine Kindheit", [tr("Sabit edat belirtme hâliyle:"), de("Dieses Lied erinnert mich an meine Kindheit."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada seni etkileyen bir parçayı anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla müziğin insanı neden etkilediğini konuşuyorsunuz. Seni etkileyen bir parçayı anlat, nasıl etki ettiğini yöntem bağlacıyla söyle ve onun örneğini de dinle.",
      partner: "müzikten anlayan, teknik ayrıntı da veren bir arkadaş",
      opening: "Bei manchen Stücken bekomme ich sofort Gänsehaut — und ich weiß nicht genau, warum. Kennst du das?",
      openingTr: "Bazı parçalarda hemen tüylerim ürperiyor — ve nedenini tam bilmiyorum. Sende de olur mu?",
      goal: "Seni etkileyen bir parça anlatılmış, nasıl etki ettiği açıklanmış ve karşı tarafın örneği de konuşulmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-fotografie",
    icon: "camera",
    level: "B2",
    course: "de",
    title: "Der entscheidende Moment",
    titleTr: "Fotoğraf sanatı",
    summary: "Bir fotoğrafı ortaç sıfatlarıyla çözümlemeyi öğretir.",
    minutes: 11,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "der Augenblick", tr: "an" },
      { de: "der Bildausschnitt", tr: "kadraj" },
      { de: "gestellt", tr: "kurgulanmış" },
      { de: "einfangen", tr: "yakalamak" },
      { de: "authentisch", tr: "özgün, gerçek" },
    ],
    patterns: [
      { de: "der festgehaltene Augenblick", tr: "yakalanmış an" },
      { de: "gestellt oder authentisch?", tr: "kurgu mu gerçek mi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir fotoğrafa bakacağız ve fotoğraf konuşmasının en sık sorusunu soracağız: bu kurgu mu, gerçek mi? Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Ortaç sıfatları burada bir kez daha karşımıza çıkıyor ama bu kez teknik bir dille: yakalanmış an, seçilmiş kadraj. Önce kelimeler.")] },
      word("İlk", { de: "der Augenblick", tr: "an" }),
      word("İkinci", { de: "der Bildausschnitt", tr: "kadraj" }),
      word("Üçüncü", { de: "gestellt", tr: "kurgulanmış" }),
      word("Dördüncü", { de: "einfangen", tr: "yakalamak" }),
      word("Son", { de: "authentisch", tr: "özgün, gerçek" }),
      { say: [tr("Kalıbımız:"), de("der festgehaltene Augenblick"), tr("Yani 'yakalanmış an'. Ortaç eril tekilde -e ekini alıyor.")] },
      { say: [tr("Örnek:"), de("Der festgehaltene Augenblick wirkt echt."), tr("Tekrar edin:"), de("Der festgehaltene Augenblick wirkt echt")], expect: repeat("Der festgehaltene Augenblick wirkt echt") },
      { say: [tr("Sıra sende: 'Doğru ışık her şeyi değiştirir.'")], expect: produce("Das richtige Licht verändert alles", [tr("Belirtili nötr tekilde sıfat -e ekini alır:"), de("Das richtige Licht verändert alles."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi soruyu sor: 'Bu fotoğraf kurgu mu, gerçek mi?'")], expect: produce("Ist dieses Foto gestellt oder authentisch", [tr("Fiil başta soru; iki sıfat seçenek olarak:"), de("Ist dieses Foto gestellt oder authentisch?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kadraj çok dar seçilmiş.'")], expect: produce("Der Bildausschnitt ist zu eng gewählt", [tr("Durum bildiren edilgen; ortaç sonda:"), de("Der Bildausschnitt ist zu eng gewählt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Bildausschnitt ist zu eng gewählt."), tr("cümlesi doğru mu?")], expect: truefalse("Der Bildausschnitt ist zu eng gewählt.", true, [tr("Doğru. Bu bir durum edilgeni: kadraj öyle seçilmiş ve öyle duruyor.")]) },
      { say: [tr("Son: 'Doğru anı yakalamak istiyorum.'")], expect: produce("Ich möchte den richtigen Augenblick einfangen", [tr("Belirtili eril belirtme hâlinde sıfat -en ekini alır:"), de("Ich möchte den richtigen Augenblick einfangen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir fotoğrafı birlikte çözümleyeceksin.")] },
    ],
    roleplay: {
      scene: "Bir fotoğraf sergisindesin ve yanındaki kişiyle bir kareyi çözümlüyorsunuz: ne gösteriyor, kadraj nasıl seçilmiş, kurgu mu gerçek mi ve sende ne uyandırıyor.",
      partner: "fotoğrafla uğraşan, teknik yorum yapan bir sergi ziyaretçisi",
      opening: "Schauen Sie sich das mal an — halten Sie das für echt oder für gestellt?",
      openingTr: "Şuna bir bakın — sizce bu gerçek mi, kurgu mu?",
      goal: "Fotoğrafın ne gösterdiği, kadrajı ve gerçek mi kurgu mu olduğu tartışılmış ve iki taraf da izlenimini söylemiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-architektur",
    icon: "city",
    level: "B2",
    course: "de",
    title: "Beton oder Altbau?",
    titleTr: "Mimarlık tartışması",
    summary: "Binaları sahiplik bildiren ilgi cümleleriyle tarif etmeyi öğretir.",
    minutes: 11,
    focusId: "Relativsatz-Genitiv",
    vocab: [
      { de: "der Altbau", tr: "eski yapı" },
      { de: "erhaltenswert", tr: "korunmaya değer" },
      { de: "das Stadtbild", tr: "kent görünümü" },
      { de: "der Beton", tr: "beton" },
      { de: "abreißen", tr: "yıkmak" },
    ],
    patterns: [
      { de: "ein Gebäude, dessen Fassade …", tr: "sahiplik ilgi cümlesi" },
      { de: "prägt das Stadtbild", tr: "kent görünümünü belirler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün şehrin görünümünü tartışacağız ve binaları tarif etmek için sahiplik bildiren ilgi cümlesini kullanacaksın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Hatırlatma: zamir kendinden ÖNCEKİ ismin cinsine göre seçilir. Sonrasındaki isim ne olursa olsun bu değişmez. Önce kelimeler.")] },
      word("İlk", { de: "der Altbau", tr: "eski yapı" }),
      word("İkinci", { de: "erhaltenswert", tr: "korunmaya değer" }),
      word("Üçüncü", { de: "das Stadtbild", tr: "kent görünümü" }),
      word("Dördüncü", { de: "der Beton", tr: "beton" }),
      word("Son", { de: "abreißen", tr: "yıkmak" }),
      { say: [tr("Kalıbımız:"), de("ein Gebäude, dessen Fassade …"), tr("Bina nötr olduğu için zamir dessen.")] },
      { say: [tr("Örnek:"), de("Ein Gebäude, dessen Fassade erhalten bleibt, prägt das Stadtbild."), tr("Tekrar edin:"), de("Ein Gebäude, dessen Fassade erhalten bleibt, prägt das Stadtbild")], expect: repeat("Ein Gebäude, dessen Fassade erhalten bleibt, prägt das Stadtbild") },
      { say: [tr("Sıra sende: 'Cephesi yenilenen bir bina.'")], expect: produce("Ein Gebäude, dessen Fassade erneuert wird", [tr("Nötr isimden sonra dessen; yan cümlede edilgen ve fiil sonda:"), de("Ein Gebäude, dessen Fassade erneuert wird."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sahibi bilinmeyen bir ev.'")], expect: produce("Ein Haus, dessen Besitzer unbekannt ist", [tr("Yine nötr isim, yine dessen:"), de("Ein Haus, dessen Besitzer unbekannt ist."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Eski yapı korunmaya değer.'")], expect: produce("Der Altbau ist erhaltenswert", [tr("Kısa bir hüküm cümlesi:"), de("Der Altbau ist erhaltenswert."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ein Gebäude, deren Fassade erneuert wird."), tr("cümlesi doğru mu?")], expect: truefalse("Ein Gebäude, deren Fassade erneuert wird.", false, [tr("Zamir kendinden önceki ismin cinsini alır ve bina nötrdür:"), de("Ein Gebäude, dessen Fassade erneuert wird.")]) },
      { say: [tr("Son: 'Beton kent görünümünü belirliyor.'")], expect: produce("Beton prägt das Stadtbild", [tr("Belirteçsiz madde ismi; nesne belirtme hâlinde:"), de("Beton prägt das Stadtbild."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir binanın yıkılıp yıkılmaması gerektiğini tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Mahallendeki eski bir binanın yıkılıp yerine yeni bir yapı yapılması planlanıyor. Bir komşunla tartışıyorsunuz: bina korunmaya değer mi, kent görünümü ne olur, alternatif ne olabilir.",
      partner: "yeni yapıdan yana olan, pratik düşünen bir komşu",
      opening: "Das alte Haus steht seit Jahren leer. Warum sollte man das nicht einfach abreißen?",
      openingTr: "Eski ev yıllardır boş duruyor. Neden basitçe yıkılmasın ki?",
      goal: "Binanın korunmaya değer olup olmadığı iki taraftan da gerekçelendirilmiş ve bir alternatif konuşulmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-festival",
    icon: "music",
    level: "B2",
    course: "de",
    title: "Auf dem Festival",
    titleTr: "Festival deneyimi",
    summary: "Bir etkinlik deneyimini isimleşmiş ifadelerle anlatmayı öğretir.",
    minutes: 11,
    focusId: "Nominalisierung",
    vocab: [
      { de: "der Auftritt", tr: "sahne performansı" },
      { de: "die Stimmung", tr: "atmosfer" },
      { de: "das Gelände", tr: "alan" },
      { de: "der Andrang", tr: "izdiham" },
      { de: "durchhalten", tr: "dayanmak" },
    ],
    patterns: [
      { de: "beim Auftritt der Band", tr: "isimleşmiş zaman ifadesi" },
      { de: "die Stimmung der Menge", tr: "tamlama" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir festivali anlatacağız. Böyle anlatımlarda Almanca yan cümle kurmak yerine isim tamlamaları kullanır: 'grup sahneye çıkarken' değil, 'grubun performansında'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tamlamada belirteç değişiyor ve bu ayrıntı çok atlanıyor. Sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "der Auftritt", tr: "sahne performansı" }),
      word("İkinci", { de: "die Stimmung", tr: "atmosfer" }),
      word("Üçüncü", { de: "das Gelände", tr: "alan" }),
      word("Dördüncü", { de: "der Andrang", tr: "izdiham" }),
      word("Son", { de: "durchhalten", tr: "dayanmak" }),
      { say: [tr("Kalıbımız:"), de("beim Auftritt der Band"), tr("İki isim tamlamayla bağlanıyor ve zaman bildiriyor.")] },
      { say: [tr("Örnek:"), de("Beim Auftritt der Band war die Stimmung großartig."), tr("Tekrar edin:"), de("Beim Auftritt der Band war die Stimmung großartig")], expect: repeat("Beim Auftritt der Band war die Stimmung großartig") },
      { say: [tr("Sıra sende: 'Kalabalığın havası inanılmazdı.'")], expect: produce("Die Stimmung der Menge war unglaublich", [tr("Tamlamada dişil isim der belirtecini alır:"), de("Die Stimmung der Menge war unglaublich."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Girişte büyük bir izdiham vardı.'")], expect: produce("Am Eingang gab es großen Andrang", [tr("Kalıplaşmış fiil; nesne belirtme hâlinde:"), de("Am Eingang gab es großen Andrang."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Gece yarısına kadar dayandık.'")], expect: produce("Wir haben bis Mitternacht durchgehalten", [tr("Ayrılabilen fiilin ortacı ge- ekini ortada alır:"), de("Wir haben bis Mitternacht durchgehalten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Beim Auftritt die Band war die Stimmung großartig."), tr("cümlesi doğru mu?")], expect: truefalse("Beim Auftritt die Band war die Stimmung großartig.", false, [tr("İki isim tamlama hâliyle bağlanır ve dişil isim der belirtecini alır:"), de("Beim Auftritt der Band war die Stimmung großartig.")]) },
      { say: [tr("Son: 'Alan sabahları temizleniyor.'")], expect: produce("Das Gelände wird morgens gereinigt", [tr("Şimdiki zaman edilgeni; ortaç sonda:"), de("Das Gelände wird morgens gereinigt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada gittiğin bir festivali anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına gittiğin festivali anlatıyorsun: hangi performans en iyisiydi, atmosfer nasıldı, ne zordu ve bir daha gider miydin.",
      partner: "gitmeyi düşünen, pratik sorular soran bir arkadaş",
      opening: "Ich überlege, nächstes Jahr hinzufahren. War es die Sache wert — ehrlich?",
      openingTr: "Gelecek yıl gitmeyi düşünüyorum. Değer miydi — dürüst söyle?",
      goal: "En iyi performans, atmosfer ve zorluklar anlatılmış; bir daha gidilip gidilmeyeceği söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-kabarett",
    icon: "media",
    level: "B2",
    course: "de",
    title: "Zwischen den Zeilen",
    titleTr: "Hiciv anlamak",
    summary: "İma ve ironiyi öznel kip fiilleriyle çözmeyi öğretir.",
    minutes: 11,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "die Ironie", tr: "ironi" },
      { de: "die Anspielung", tr: "gönderme, ima" },
      { de: "der Seitenhieb", tr: "taş, dokundurma" },
      { de: "durchschauen", tr: "çözmek, anlamak" },
      { de: "beißend", tr: "iğneleyici" },
    ],
    patterns: [
      { de: "Das soll wohl witzig sein.", tr: "ironik mesafe" },
      { de: "Gemeint sein dürfte …", tr: "kastedileni tahmin eder" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün en zor dinleme türü: hiciv. Söylenen ile kastedilen ayrı ve o farkı dille işaretlemek gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Öznel kip fiilleri burada yeni bir iş yapıyor: 'kastedilen muhtemelen şu' diyebiliyorsun — emin olmadan, ama boş da konuşmadan. Önce kelimeler.")] },
      word("İlk", { de: "die Ironie", tr: "ironi" }),
      word("İkinci", { de: "die Anspielung", tr: "gönderme, ima" }),
      word("Üçüncü", { de: "der Seitenhieb", tr: "taş, dokundurma" }),
      word("Dördüncü", { de: "durchschauen", tr: "çözmek, anlamak" }),
      word("Son", { de: "beißend", tr: "iğneleyici" }),
      { say: [tr("Kalıbımız:"), de("Gemeint sein dürfte …"), tr("Yani 'kastedilen muhtemelen şu'. Tahmin ama gerekçeli.")] },
      { say: [tr("Örnek:"), de("Das soll wohl witzig sein."), tr("Tekrar edin:"), de("Das soll wohl witzig sein")], expect: repeat("Das soll wohl witzig sein") },
      { say: [tr("Sıra sende: 'Kastedilen muhtemelen belediye başkanı.'")], expect: produce("Gemeint sein dürfte der Bürgermeister", [tr("Mastar öbeği başta, kip fiili ikinci sırada:"), de("Gemeint sein dürfte der Bürgermeister."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Göndermeyi anlamadım.'")], expect: produce("Die Anspielung habe ich nicht verstanden", [tr("Nesne öne alınmış; ortaç sonda:"), de("Die Anspielung habe ich nicht verstanden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Mizahı iğneleyici ama adil.'")], expect: produce("Sein Humor ist beißend, aber fair", [tr("İki sıfat, ikinci cümlede fiil tekrarlanmıyor:"), de("Sein Humor ist beißend, aber fair."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Gemeint sein dürfte der Bürgermeister."), tr("cümlesi doğru mu?")], expect: truefalse("Gemeint sein dürfte der Bürgermeister.", true, [tr("Doğru. Mastar öbeği cümlenin ilk öğesi, çekimli kip fiili hemen arkasında ve özne sonda.")]) },
      { say: [tr("Son: 'Bunu hemen çözdüm.'")], expect: produce("Das habe ich sofort durchschaut", [tr("Ayrılmayan fiilin ortacı ge- almaz:"), de("Das habe ich sofort durchschaut."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada izlediğin bir hiciv gösterisini konuşacaksın: neye gönderme yapıyordu, sen ne anladın.")] },
    ],
    roleplay: {
      scene: "Bir hiciv gösterisinden çıktın ve yanındaki kişiyle konuşuyorsun: hangi göndermeleri anladın, hangisini kaçırdın, kime taş atıldı ve mizah adil miydi.",
      partner: "her göndermeyi anlamış, açıklamayı seven bir izleyici",
      opening: "Haben Sie die Stelle mit dem Bahnhof mitbekommen? Da ging es nicht wirklich um Züge.",
      openingTr: "Gar ile ilgili kısmı yakaladınız mı? Orada aslında trenlerden bahsedilmiyordu.",
      goal: "En az bir gönderme birlikte çözülmüş ve mizahın adil olup olmadığı konusunda görüş bildirilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-kunstmarkt",
    icon: "art",
    level: "B2",
    course: "de",
    title: "Was ist Kunst wert?",
    titleTr: "Sanat piyasası",
    summary: "Değer ve fiyat ilişkisini orantı bağlacıyla tartışmayı öğretir.",
    minutes: 11,
    focusId: "Je-desto",
    vocab: [
      { de: "die Auktion", tr: "müzayede" },
      { de: "ersteigern", tr: "müzayedede almak" },
      { de: "der Wert", tr: "değer" },
      { de: "umstritten", tr: "tartışmalı" },
      { de: "selten", tr: "nadir" },
    ],
    patterns: [
      { de: "Je seltener …, desto wertvoller …", tr: "orantı kurar" },
      { de: "für … ersteigert werden", tr: "müzayede fiyatı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi: bir sanat eserinin değeri neyle ölçülür? Bu tartışma orantı cümleleriyle yürür. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de dikkat edeceğin küçük bir nokta var: soru sorarken nesnenin hâli. Sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "die Auktion", tr: "müzayede" }),
      word("İkinci", { de: "ersteigern", tr: "müzayedede almak" }),
      word("Üçüncü", { de: "der Wert", tr: "değer" }),
      word("Dördüncü", { de: "umstritten", tr: "tartışmalı" }),
      word("Son", { de: "selten", tr: "nadir" }),
      { say: [tr("Kalıbımız:"), de("Je seltener …, desto wertvoller …"), tr("İki karşılaştırma biçimi, iki parça.")] },
      { say: [tr("Örnek:"), de("Je seltener ein Werk ist, desto wertvoller wird es."), tr("Tekrar edin:"), de("Je seltener ein Werk ist, desto wertvoller wird es")], expect: repeat("Je seltener ein Werk ist, desto wertvoller wird es") },
      { say: [tr("Sıra sende: 'Tablo iki milyona satıldı.'")], expect: produce("Das Bild wurde für zwei Millionen ersteigert", [tr("Edilgen geçmiş zaman; fiyat für ile:"), de("Das Bild wurde für zwei Millionen ersteigert."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ne kadar çok konuşulursa fiyat o kadar yükseliyor.'")], expect: produce("Je mehr darüber geredet wird, desto höher steigt der Preis", [tr("İlk parçada edilgen ve fiil sonda; ikincide karşılaştırma bağlacın hemen arkasında:"), de("Je mehr darüber geredet wird, desto höher steigt der Preis."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Fiyat tartışmalı.'")], expect: produce("Der Preis ist umstritten", [tr("Kısa bir hüküm cümlesi:"), de("Der Preis ist umstritten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Was bestimmt der Wert eines Kunstwerks?"), tr("cümlesi doğru mu?")], expect: truefalse("Was bestimmt der Wert eines Kunstwerks?", false, [tr("Burada değer nesnedir, o yüzden belirtme hâline girer:"), de("Was bestimmt den Wert eines Kunstwerks?")]) },
      { say: [tr("Son: 'Bir sanat eserinin değerini ne belirler?'")], expect: produce("Was bestimmt den Wert eines Kunstwerks", [tr("Nesne belirtme hâlinde; ardından tamlama:"), de("Was bestimmt den Wert eines Kunstwerks?"), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada sanatın fiyatını tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla sanat eserlerinin fiyatlarını tartışıyorsunuz: bir tabloya milyonlar ödenmesi anlamlı mı, değeri ne belirler, sen neye para verirdin. Orantı cümleleriyle bağlantı kur.",
      partner: "sanat piyasasını saçma bulan, örnek isteyen bir tanıdık",
      opening: "Zwei Millionen für ein Bild, das jeder kopieren könnte — können Sie mir das erklären?",
      openingTr: "Herkesin kopyalayabileceği bir tabloya iki milyon — bunu bana açıklayabilir misiniz?",
      goal: "Değeri neyin belirlediği tartışılmış, iki taraf da gerekçe vermiş ve ortak bir ölçüt konuşulmuş olur.",
      minTurns: 8,
    },
  },
];
