import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B1 · Modül 6 — Eğitim ve gelişim (051–060).
 *
 * Modülün konusu bir dilbilgisi kuralı değil bir DİL İŞLEVİ: hedef koymak,
 * gerekçelendirmek, yöntem anlatmak, tavsiye almak. Bunun için üç yapı
 * dönüşümlü çalışıyor — zu'lu mastar (niyet), um…zu (amaç) ve dolaylı soru
 * (bilmediğini sorma) — ve hepsi aynı yere bakıyor: gelecekteki bir işi
 * bugünden konuşabilmek.
 *
 * Türkçe konuşanın burada iki tökezleme noktası var. Birincisi zu'nun
 * ayrılabilen fiilin ORTASINA girmesi (anzurufen, dranzubleiben) — Türkçede
 * eki bölen bir şey yok. İkincisi dolaylı soruda fiilin sona gitmesi: soru
 * cümlesi dolaylı hâle gelince düz cümle gibi bozulur.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB1B06: Lesson[] = [
  {
    id: "de-b1-infinitiv-zu",
    icon: "idea",
    level: "B1",
    course: "de",
    title: "Ich habe vor, mehr zu lernen",
    titleTr: "zu'lu mastar",
    summary: "Niyeti zu artı mastar yapısıyla söylemeyi ve ayrılabilen fiilde zu'nun yerini öğretir.",
    minutes: 10,
    focusId: "Infinitiv-zu",
    vocab: [
      { de: "die Absicht", tr: "niyet" },
      { de: "dranbleiben", tr: "devam etmek" },
      { de: "die Gewohnheit", tr: "alışkanlık" },
      { de: "das Vorhaben", tr: "plan" },
      { de: "festlegen", tr: "belirlemek" },
    ],
    patterns: [
      { de: "Ich habe vor, … zu …", tr: "niyet bildirir; zu artı mastar en sonda" },
      { de: "Es ist wichtig, … zu …", tr: "değerlendirme cümlesi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün planlarını anlatmayı öğreneceğiz: neye niyetliyim, neyi denemek istiyorum. Almanca bunu küçük bir kelimeyle yapıyor ve o kelimenin yeri çok önemli. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Türkçede plan tek ekle çıkar: '-meyi düşünüyorum'. Almancada virgülden sonra bir mastar öbeği kurulur ve mastarın önüne küçük bir bağlaç girer. Önce kelimeler.")] },
      word("İlk", { de: "die Absicht", tr: "niyet" }),
      word("İkinci", { de: "dranbleiben", tr: "devam etmek" }),
      word("Üçüncü", { de: "die Gewohnheit", tr: "alışkanlık" }),
      word("Dördüncü", { de: "das Vorhaben", tr: "plan" }),
      word("Son", { de: "festlegen", tr: "belirlemek" }),
      { say: [tr("Kalıbımız:"), de("Ich habe vor, … zu …"), tr("Ayrılabilen bir fiilde küçük bağlaç önekle kökün ARASINA girer. Yani tek kelime olur ama ortası dolar.")] },
      { say: [tr("Örnek:"), de("Ich habe vor, jeden Tag zwanzig Minuten zu lernen."), tr("Lütfen tekrar edin:"), de("Ich habe vor, jeden Tag zwanzig Minuten zu lernen")], expect: repeat("Ich habe vor, jeden Tag zwanzig Minuten zu lernen") },
      { say: [tr("Sıra sende: 'Devam etmek önemli.' Ayrılabilen fiile dikkat.")], expect: produce("Es ist wichtig, dranzubleiben", [tr("Önekle kökün arasına giriyor:"), de("Es ist wichtig, dranzubleiben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir hedef belirlemeye karar verdim.'")], expect: produce("Ich habe beschlossen, ein Ziel festzulegen", [tr("Yine ayrılabilen fiil, yine ortada:"), de("Ich habe beschlossen, ein Ziel festzulegen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yeni bir alışkanlık edinmeye niyetliyim.'")], expect: produce("Ich habe vor, eine neue Gewohnheit aufzubauen", [tr("Niyet kalıbı artı ayrılabilen fiil:"), de("Ich habe vor, eine neue Gewohnheit aufzubauen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es ist wichtig, dranbleiben."), tr("cümlesi doğru mu?")], expect: truefalse("Es ist wichtig, dranbleiben.", false, [tr("Ayrılabilen fiilde bağlaç fiilin ORTASINA girer:"), de("Es ist wichtig, dranzubleiben.")]) },
      { say: [tr("Son: 'Pes etmeye niyetim yok.'")], expect: produce("Ich habe nicht vor aufzugeben", [tr("Olumsuzluk niyet fiilinin yanında durur:"), de("Ich habe nicht vor aufzugeben."), tr("Tekrar dene.")], ["Ich habe nicht die Absicht aufzugeben"]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşına bu yılki planlarını anlatacaksın: neye niyetlisin, neyi bırakacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla yılın planlarını konuşuyorsun: neyi öğrenmeye niyetlisin, hangi alışkanlığı kurmak istiyorsun, neyi bırakacaksın. Planlarını zu'lu mastarla anlat.",
      partner: "planlarını ciddiye alan, soru soran bir arkadaş",
      opening: "Du hast gesagt, dieses Jahr wird anders. Was hast du dir denn vorgenommen?",
      openingTr: "Bu yılın farklı olacağını söylemiştin. Peki neye niyetlendin?",
      goal: "Neyi öğrenmeye niyetli olduğun, hangi alışkanlığı kuracağın ve neyi bırakacağın anlatılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-lernziele",
    icon: "chart",
    level: "B1",
    course: "de",
    title: "Meine Lernziele",
    titleTr: "Öğrenme hedefleri",
    summary: "Hedefi ölçülebilir biçimde tanımlamayı ve ara adımlarla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Infinitiv-zu",
    vocab: [
      { de: "das Lernziel", tr: "öğrenme hedefi" },
      { de: "messbar", tr: "ölçülebilir" },
      { de: "erreichen", tr: "ulaşmak" },
      { de: "der Zwischenschritt", tr: "ara adım" },
      { de: "überprüfen", tr: "gözden geçirmek" },
    ],
    patterns: [
      { de: "Mein Ziel ist es, … zu …", tr: "hedefi tanımlar" },
      { de: "Ich versuche, … zu …", tr: "denemeyi anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Geçen ders niyeti öğrendik. Bugün niyeti hedefe çevireceğiz — ve iyi bir hedefin tek şartı var: ölçülebilir olmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Almancamı geliştireceğim' bir hedef değil, bir dilek. 'Altı ayda sınavı geçeceğim' hedeftir, çünkü ölçülebilir. Bugün ikisini de Almanca kuracağız. Önce kelimeler.")] },
      word("İlk", { de: "das Lernziel", tr: "öğrenme hedefi" }),
      word("İkinci", { de: "messbar", tr: "ölçülebilir" }),
      word("Üçüncü", { de: "erreichen", tr: "ulaşmak" }),
      word("Dördüncü", { de: "der Zwischenschritt", tr: "ara adım" }),
      word("Son", { de: "überprüfen", tr: "gözden geçirmek" }),
      { say: [tr("Kalıbımız:"), de("Mein Ziel ist es, … zu …"), tr("Baştaki küçük kelime sahte bir öznedir; asıl hedef virgülden sonra gelir.")] },
      { say: [tr("Örnek:"), de("Mein Ziel ist es, in einem Jahr B2 zu erreichen."), tr("Tekrar edin:"), de("Mein Ziel ist es, in einem Jahr B2 zu erreichen")], expect: repeat("Mein Ziel ist es, in einem Jahr B2 zu erreichen") },
      { say: [tr("Sıra sende: 'Hedefim altı ayda sınavı geçmek.'")], expect: produce("Mein Ziel ist es, in sechs Monaten die Prüfung zu bestehen", [tr("Süre ortada, mastar en sonda:"), de("Mein Ziel ist es, in sechs Monaten die Prüfung zu bestehen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Her hafta on kelime öğrenmeye çalışıyorum.'")], expect: produce("Ich versuche, jede Woche zehn Wörter zu lernen", [tr("Deneme kalıbı artı mastar:"), de("Ich versuche, jede Woche zehn Wörter zu lernen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, bu kez düz cümle: 'Bir öğrenme hedefi ölçülebilir olmalı.'")], expect: produce("Ein Lernziel muss messbar sein", [tr("Modal fiil çekimli, mastar en sonda:"), de("Ein Lernziel muss messbar sein."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Mein Ziel ist es, jeden Tag zu üben."), tr("cümlesi doğru mu?")], expect: truefalse("Mein Ziel ist es, jeden Tag zu üben.", true, [tr("Doğru. Sahte özneyle başlıyor, mastar öbeği virgülden sonra ve mastar en sonda.")]) },
      { say: [tr("Son: 'Ara adımlarımı ayda bir gözden geçiriyorum.'")], expect: produce("Ich überprüfe meine Zwischenschritte einmal im Monat", [tr("Basit düz cümle; sıklık ifadesi sonda:"), de("Ich überprüfe meine Zwischenschritte einmal im Monat."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kurs danışmanına hedeflerini anlatacaksın: ne kadar sürede ne istiyorsun, ara adımların ne.")] },
    ],
    roleplay: {
      scene: "Bir kurs danışmanıyla hedef görüşmesi yapıyorsun: ne kadar sürede neyi başarmak istiyorsun, ara adımların ne, ilerlemeyi nasıl ölçeceksin.",
      partner: "somut sayılar isteyen bir kurs danışmanı",
      opening: "Bevor wir einen Kurs auswählen: Was genau möchten Sie in den nächsten sechs Monaten erreichen?",
      openingTr: "Kurs seçmeden önce: Önümüzdeki altı ayda tam olarak neyi başarmak istiyorsunuz?",
      goal: "Süre, hedef ve ara adımlar netleşmiş; ilerlemenin nasıl ölçüleceği kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-sprachkurs",
    icon: "school",
    level: "B1",
    course: "de",
    title: "Welcher Kurs passt?",
    titleTr: "Kurs seçimi",
    summary: "İki kursu karşılaştırarak seçim yapmayı ve tercihini gerekçelendirmeyi öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "der Intensivkurs", tr: "yoğun kurs" },
      { de: "der Abendkurs", tr: "akşam kursu" },
      { de: "das Tempo", tr: "tempo" },
      { de: "der Einstufungstest", tr: "seviye tespit sınavı" },
      { de: "die Gruppengröße", tr: "grup büyüklüğü" },
    ],
    patterns: [
      { de: "… ist intensiver als …", tr: "iki seçeneği karşılaştırır" },
      { de: "im Vergleich zu …", tr: "resmî karşılaştırma" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün seçim yapmayı konuşacağız: yoğun kurs mu akşam kursu mu. Seçim demek karşılaştırma demek, o yüzden karşılaştırma biçimini tazeleyeceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karşılaştırmada bir tuzak var ve neredeyse herkes ona düşüyor: iki şeyi karşılaştırırken kullanılan bağlaç, benzetme bağlacından farklıdır. Sonda göreceğiz. Önce kelimeler.")] },
      word("İlk", { de: "der Intensivkurs", tr: "yoğun kurs" }),
      word("İkinci", { de: "der Abendkurs", tr: "akşam kursu" }),
      word("Üçüncü", { de: "das Tempo", tr: "tempo" }),
      word("Dördüncü", { de: "der Einstufungstest", tr: "seviye tespit sınavı" }),
      word("Son", { de: "die Gruppengröße", tr: "grup büyüklüğü" }),
      { say: [tr("Kalıbımız:"), de("Der Intensivkurs ist schneller als der Abendkurs."), tr("Sıfat karşılaştırma biçimine giriyor, sonra karşılaştırma bağlacı geliyor.")] },
      { say: [tr("Tekrar edin:"), de("Der Intensivkurs ist schneller als der Abendkurs")], expect: repeat("Der Intensivkurs ist schneller als der Abendkurs") },
      { say: [tr("Sıra sende: 'Akşam kursu daha ucuz ama daha uzun sürüyor.'")], expect: produce("Der Abendkurs ist billiger, aber er dauert länger", [tr("İki karşılaştırma biçimi bir cümlede:"), de("Der Abendkurs ist billiger, aber er dauert länger."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Daha küçük bir grupta daha çok konuşuyorsun.'")], expect: produce("In einer kleineren Gruppe spricht man mehr", [tr("Cümle tümleçle başladığı için fiil ikinci sırada:"), de("In einer kleineren Gruppe spricht man mehr."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, geçen modülden edilgenle: 'Seviye tespit sınavı olmadan kurs seçilemez.'")], expect: produce("Ohne Einstufungstest kann kein Kurs gewählt werden", [tr("Modal fiille edilgen; ortaç ve werden en sonda:"), de("Ohne Einstufungstest kann kein Kurs gewählt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi tuzak. Doğru mu yanlış mı:"), de("Der Intensivkurs ist teurer wie der Abendkurs."), tr("cümlesi doğru mu?")], expect: truefalse("Der Intensivkurs ist teurer wie der Abendkurs.", false, [tr("Karşılaştırmada başka bir bağlaç kullanılır:"), de("Der Intensivkurs ist teurer als der Abendkurs.")]) },
      { say: [tr("Son: 'Tempo bana çok hızlı geliyor.'")], expect: produce("Das Tempo ist mir zu schnell", [tr("Kişiye görelik yönelme hâliyle:"), de("Das Tempo ist mir zu schnell."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kurs sekreteriyle iki kursu karşılaştıracaksın ve birini seçeceksin.")] },
    ],
    roleplay: {
      scene: "Bir dil okulunun sekreterliğindesin: yoğun kursla akşam kursunu karşılaştır, fiyat, tempo ve grup büyüklüğünü sor, sonra birini gerekçesiyle seç.",
      partner: "iki kursu da iyi tanıyan, dürüst bir kurs sekreteri",
      opening: "Wir haben zwei Kurse, die für Sie infrage kommen. Wonach möchten Sie sich entscheiden?",
      openingTr: "Size uygun iki kursumuz var. Kararınızı neye göre vermek istersiniz?",
      goal: "İki kurs karşılaştırılmış ve biri gerekçesiyle seçilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-pruefung-b1",
    icon: "pen",
    level: "B1",
    course: "de",
    title: "Angst vor der Prüfung",
    titleTr: "Sınav stratejisi",
    summary: "Sınav kaygısını koşul cümleleriyle konuşmayı ve strateji anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-wenn",
    vocab: [
      { de: "die Panik", tr: "panik" },
      { de: "der Trick", tr: "numara" },
      { de: "durchfallen", tr: "kalmak (sınavda)" },
      { de: "wiederholen", tr: "tekrarlamak" },
      { de: "der Zeitdruck", tr: "zaman baskısı" },
    ],
    patterns: [
      { de: "Wenn ich nicht bestehe, …", tr: "koşul yan cümlesi; ana cümle fiille başlar" },
      { de: "Der Trick ist, … zu …", tr: "yöntemi tek cümlede söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün konu sınav ve onun yol arkadaşı: heyecan. İkisini de konuşabilmek gerekiyor, çünkü konuşulmayan kaygı büyüyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kaygı konuşulurken hep aynı yapı çıkıyor: 'şu olursa şunu yaparım'. Yani koşul yan cümlesi. Kural şu: koşul başta duruyorsa ana cümle fiille başlar. Önce kelimeler.")] },
      word("İlk", { de: "die Panik", tr: "panik" }),
      word("İkinci", { de: "der Trick", tr: "numara" }),
      word("Üçüncü", { de: "durchfallen", tr: "kalmak (sınavda)" }),
      word("Dördüncü", { de: "wiederholen", tr: "tekrarlamak" }),
      word("Son", { de: "der Zeitdruck", tr: "zaman baskısı" }),
      { say: [tr("Kalıbımız:"), de("Wenn ich nicht bestehe, wiederhole ich die Prüfung."), tr("Yan cümle önde, ana cümlenin fiili hemen virgülden sonra.")] },
      { say: [tr("Örnek:"), de("Wenn ich nervös werde, atme ich tief durch."), tr("Tekrar edin:"), de("Wenn ich nervös werde, atme ich tief durch")], expect: repeat("Wenn ich nervös werde, atme ich tief durch") },
      { say: [tr("Sıra sende: 'Sınavda kalırsam tekrar ederim.'")], expect: produce("Wenn ich durchfalle, wiederhole ich die Prüfung", [tr("Koşul başta, ana cümle fiille başlar:"), de("Wenn ich durchfalle, wiederhole ich die Prüfung."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Zaman baskısı olunca hata yapıyorum.'")], expect: produce("Wenn ich Zeitdruck habe, mache ich Fehler", [tr("Yan cümlenin fiili sonda, ana cümleninki başta:"), de("Wenn ich Zeitdruck habe, mache ich Fehler."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Numara, önce soruyu okumak.'")], expect: produce("Der Trick ist, zuerst die Frage zu lesen", [tr("Yöntem kalıbı zu'lu mastarla kurulur:"), de("Der Trick ist, zuerst die Frage zu lesen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn ich durchfalle, ich wiederhole die Prüfung."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn ich durchfalle, ich wiederhole die Prüfung.", false, [tr("Koşul yan cümlesi başta olduğunda ana cümle fiille başlar:"), de("Wenn ich durchfalle, wiederhole ich die Prüfung.")]) },
      { say: [tr("Son: 'Panik yaparsan cümleyi anlamazsın.'")], expect: produce("Wenn du in Panik gerätst, verstehst du den Satz nicht", [tr("İkinci tekil kişide de kural aynı:"), de("Wenn du in Panik gerätst, verstehst du den Satz nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sınav kaygısını bir öğretmenle konuşacaksın: neyden çekiniyorsun, ne olursa ne yaparsın.")] },
    ],
    roleplay: {
      scene: "Sınav öncesi öğretmeninle konuşuyorsun: neyden çekindiğini, hangi bölümün zor geldiğini ve olursa ne yapacağını anlat. Cümlelerini koşul yan cümleleriyle kur.",
      partner: "sakinleştiren, somut tavsiye veren bir öğretmen",
      opening: "Sie wirken angespannt. Wovor haben Sie bei der Prüfung am meisten Respekt?",
      openingTr: "Gergin görünüyorsunuz. Sınavda en çok neyden çekiniyorsunuz?",
      goal: "Çekindiğin bölüm söylenmiş, olursa ne yapacağın konuşulmuş ve bir strateji üzerinde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-weiterbildung",
    icon: "school",
    level: "B1",
    course: "de",
    title: "Die Weiterbildung",
    titleTr: "Mesleki gelişim",
    summary: "Bir eğitimin amacını um … zu ile gerekçelendirmeyi ve faydasını anlatmayı öğretir.",
    minutes: 10,
    focusId: "Um-zu",
    vocab: [
      { de: "die Weiterbildung", tr: "mesleki eğitim" },
      { de: "berufsbegleitend", tr: "işle birlikte" },
      { de: "der Nutzen", tr: "fayda" },
      { de: "finanzieren", tr: "finanse etmek" },
      { de: "die Teilzeit", tr: "yarı zamanlı çalışma" },
    ],
    patterns: [
      { de: "Ich mache das, um … zu …", tr: "amaç bildirir; özne aynıysa" },
      { de: "Das bringt mir …", tr: "faydayı söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün iş hayatının en çok sorulan sorusuna cevap vereceğiz: bunu neden yapıyorsun? Amaç anlatmanın kısa yolunu tazeleyeceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amaç iki yolla söylenir. Özne aynıysa kısa yol, farklıysa uzun yol. Bugün kısa yolu iş bağlamında çalıştıracağız. Önce kelimeler.")] },
      word("İlk", { de: "die Weiterbildung", tr: "mesleki eğitim" }),
      word("İkinci", { de: "berufsbegleitend", tr: "işle birlikte" }),
      word("Üçüncü", { de: "der Nutzen", tr: "fayda" }),
      word("Dördüncü", { de: "finanzieren", tr: "finanse etmek" }),
      word("Son", { de: "die Teilzeit", tr: "yarı zamanlı çalışma" }),
      { say: [tr("Kalıbımız:"), de("Ich mache das, um … zu …"), tr("Amaç öbeğinde özne tekrar edilmez; doğrudan mastara gidilir.")] },
      { say: [tr("Örnek:"), de("Ich mache die Weiterbildung, um mehr zu verdienen."), tr("Tekrar edin:"), de("Ich mache die Weiterbildung, um mehr zu verdienen")], expect: repeat("Ich mache die Weiterbildung, um mehr zu verdienen") },
      { say: [tr("Sıra sende: 'Daha iyi bir iş bulmak için eğitim alıyorum.'")], expect: produce("Ich mache eine Weiterbildung, um eine bessere Stelle zu finden", [tr("Amaç öbeği virgülden sonra, mastar en sonda:"), de("Ich mache eine Weiterbildung, um eine bessere Stelle zu finden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kursu işimle birlikte yapıyorum.'")], expect: produce("Ich mache den Kurs berufsbegleitend", [tr("Tek kelimelik bir zarf; cümlenin sonunda:"), de("Ich mache den Kurs berufsbegleitend."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Şirket eğitimin yarısını finanse ediyor.'")], expect: produce("Die Firma finanziert die Hälfte der Weiterbildung", [tr("Etken cümle; 'yarısı' tamlama olarak:"), de("Die Firma finanziert die Hälfte der Weiterbildung."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Weiterbildung wird von der Firma finanziert."), tr("cümlesi doğru mu?")], expect: truefalse("Die Weiterbildung wird von der Firma finanziert.", true, [tr("Doğru. Edilgen cümlede eylemi yapan taraf bir edatla eklenebilir ve ortaç en sonda duruyor.")]) },
      { say: [tr("Son bir soru sor: 'Bunun bana faydası ne?'")], expect: produce("Welchen Nutzen hat das für mich", [tr("Soru kelimesi belirtme hâlinde çekilir:"), de("Welchen Nutzen hat das für mich?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada şefinle eğitim talebini konuşacaksın: neden istiyorsun, şirkete faydası ne, nasıl finanse edilecek.")] },
    ],
    roleplay: {
      scene: "Şefinle mesleki eğitim talebini konuşuyorsun: neden istediğini amaç cümleleriyle anlat, şirkete faydasını söyle, finansmanı ve çalışma düzenini konuş.",
      partner: "bütçeyi düşünen ama açık fikirli bir şef",
      opening: "Sie wollten über eine Weiterbildung sprechen. Wozu genau brauchen Sie die?",
      openingTr: "Mesleki eğitim hakkında konuşmak istemiştiniz. Tam olarak ne için gerekiyor?",
      goal: "Eğitimin amacı, şirkete faydası ve finansmanı konuşulmuş; şefin bir cevap vermiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-studium",
    icon: "school",
    level: "B1",
    course: "de",
    title: "Studieren in Deutschland",
    titleTr: "Üniversite",
    summary: "Üniversite başvurusunda bilmediklerini dolaylı soru kalıplarıyla sormayı öğretir.",
    minutes: 10,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "das Studium", tr: "üniversite öğrenimi" },
      { de: "die Hochschule", tr: "yükseköğretim kurumu" },
      { de: "sich einschreiben", tr: "kayıt yaptırmak" },
      { de: "die Bewerbungsfrist", tr: "başvuru süresi" },
      { de: "der Studiengang", tr: "bölüm" },
    ],
    patterns: [
      { de: "Ich informiere mich, wie …", tr: "dolaylı soru; fiil sona gider" },
      { de: "Was braucht man, um … zu …?", tr: "koşul sorusu" },
    ],
    lecture: [
      { say: [tr("Merhaba! Üniversite başvurusu bir bilgi avıdır ve avın dili sorudur. Ama düz soru değil, yumuşatılmış soru: 'ne zaman bittiğini bilmiyorum'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dolaylı soruda düz soru cümlesi bozulur: çekimli fiil en sona gider. Türkçede de benzer bir şey oluyor, cümle bir isim öbeğine dönüşüyor. Önce kelimeler.")] },
      word("İlk", { de: "das Studium", tr: "üniversite öğrenimi" }),
      word("İkinci", { de: "die Hochschule", tr: "yükseköğretim kurumu" }),
      word("Üçüncü", { de: "sich einschreiben", tr: "kayıt yaptırmak" }),
      word("Dördüncü", { de: "die Bewerbungsfrist", tr: "başvuru süresi" }),
      word("Son", { de: "der Studiengang", tr: "bölüm" }),
      { say: [tr("Kalıbımız:"), de("Ich informiere mich, wie …"), tr("Soru kelimesi yan cümlenin başına geçiyor, fiil en sona.")] },
      { say: [tr("Örnek:"), de("Ich informiere mich, wie die Bewerbung funktioniert."), tr("Tekrar edin:"), de("Ich informiere mich, wie die Bewerbung funktioniert")], expect: repeat("Ich informiere mich, wie die Bewerbung funktioniert") },
      { say: [tr("Sıra sende: 'Başvuru süresinin ne zaman bittiğini bilmiyorum.'")], expect: produce("Ich weiß nicht, wann die Bewerbungsfrist endet", [tr("Soru kelimesi başta, fiil sonda:"), de("Ich weiß nicht, wann die Bewerbungsfrist endet."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Hangi bölümün bana uyduğunu soruyorum kendime.'")], expect: produce("Ich frage mich, welcher Studiengang zu mir passt", [tr("Soru sıfatı özneyle uyumlu çekilir:"), de("Ich frage mich, welcher Studiengang zu mir passt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kaydolabilir miyim, onu öğrenmek istiyorum.'")], expect: produce("Ich möchte wissen, ob ich mich einschreiben kann", [tr("Evet-hayır sorusu dolaylı hâle gelince bağlaç alır:"), de("Ich möchte wissen, ob ich mich einschreiben kann."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich informiere mich, wie funktioniert die Bewerbung."), tr("cümlesi doğru mu?")], expect: truefalse("Ich informiere mich, wie funktioniert die Bewerbung.", false, [tr("Dolaylı soruda çekimli fiil en sona gider:"), de("Ich informiere mich, wie die Bewerbung funktioniert.")]) },
      { say: [tr("Son: 'Okumak için ne gerekiyor?'")], expect: produce("Was braucht man, um zu studieren", [tr("Amaç öbeğinde özne yok, doğrudan mastar:"), de("Was braucht man, um zu studieren?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir öğrenci danışmanına başvuruyu soracaksın: ne zaman, nasıl, hangi belgelerle.")] },
    ],
    roleplay: {
      scene: "Üniversitenin öğrenci danışmanlığındasın: başvuru süresini, gereken belgeleri ve hangi bölümün sana uyduğunu sor. Sorularını dolaylı biçimde kur.",
      partner: "çok sayıda öğrenciyle konuşmuş, pratik bir öğrenci danışmanı",
      opening: "Setzen Sie sich. Sie interessieren sich für ein Studium bei uns — was möchten Sie zuerst klären?",
      openingTr: "Buyurun oturun. Bizde okumak istiyorsunuz — önce neyi netleştirelim?",
      goal: "Başvuru süresi, gereken belgeler ve sana uyan bölüm öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-praktikum",
    icon: "job",
    level: "B1",
    course: "de",
    title: "Das Praktikum",
    titleTr: "Staj deneyimi",
    summary: "Bir deneyimi yazı diline yakın geçmiş zamanla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Präteritum",
    vocab: [
      { de: "das Praktikum", tr: "staj" },
      { de: "der Betrieb", tr: "işletme" },
      { de: "betreuen", tr: "ilgilenmek (birisiyle)" },
      { de: "zusehen", tr: "izlemek" },
      { de: "der Einblick", tr: "fikir edinme" },
    ],
    patterns: [
      { de: "Ich lernte …", tr: "yazı dilinde geçmiş: Präteritum" },
      { de: "Am meisten brachte mir …", tr: "en çok neyin katkı yaptığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir deneyimi anlatacağız — ama konuşma dilinin geçmişiyle değil, yazının geçmişiyle. Özgeçmişte, başvuruda, raporda kullanılan biçim bu. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkisi de 'yaptım' demek; fark üslupta. Konuşurken iki parçalı biçim, yazarken tek parçalı biçim tercih edilir. Önce kelimeler.")] },
      word("İlk", { de: "das Praktikum", tr: "staj" }),
      word("İkinci", { de: "der Betrieb", tr: "işletme" }),
      word("Üçüncü", { de: "betreuen", tr: "ilgilenmek (birisiyle)" }),
      word("Dördüncü", { de: "zusehen", tr: "izlemek" }),
      word("Son", { de: "der Einblick", tr: "fikir edinme" }),
      { say: [tr("Kalıbımız:"), de("Ich machte ein Praktikum in einem kleinen Betrieb."), tr("Fiil tek parça ve ikinci sırada; yardımcı fiil yok.")] },
      { say: [tr("Tekrar edin:"), de("Ich machte ein Praktikum in einem kleinen Betrieb")], expect: repeat("Ich machte ein Praktikum in einem kleinen Betrieb") },
      { say: [tr("Sıra sende: 'Üç ay bir işletmede çalıştım.'")], expect: produce("Ich arbeitete drei Monate in einem Betrieb", [tr("Düzenli fiil, tek parça geçmiş:"), de("Ich arbeitete drei Monate in einem Betrieb."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir meslektaş benimle ilgilendi.'")], expect: produce("Eine Kollegin betreute mich", [tr("Yine düzenli fiil; nesne yalın hâlde değil belirtme hâlinde:"), de("Eine Kollegin betreute mich."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, ayrılabilen fiille: 'İlk hafta sadece izledim.'")], expect: produce("In der ersten Woche sah ich nur zu", [tr("Ayrılabilen fiilin öneki en sona:"), de("In der ersten Woche sah ich nur zu."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich machte ein Praktikum und lernte sehr viel."), tr("cümlesi doğru mu?")], expect: truefalse("Ich machte ein Praktikum und lernte sehr viel.", true, [tr("Doğru. İki fiil de tek parça geçmişte ve bağlaçtan sonra dizilim değişmiyor.")]) },
      { say: [tr("Son: 'Bana en çok ekip çalışması katkı sağladı.'")], expect: produce("Am meisten brachte mir die Arbeit im Team", [tr("Cümle bir zarfla başlıyor, fiil ikinci sırada:"), de("Am meisten brachte mir die Arbeit im Team."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir iş görüşmesinde stajını anlatacaksın: nerede, ne kadar, ne öğrendin.")] },
    ],
    roleplay: {
      scene: "Bir iş görüşmesinde stajını anlatıyorsun: hangi işletmede, ne kadar sürdü, hangi işleri yaptın, sana ne kattı. Anlatımı yazı dilinin geçmişiyle kur.",
      partner: "ayrıntı soran, not alan bir insan kaynakları uzmanı",
      opening: "In Ihrem Lebenslauf steht ein Praktikum. Erzählen Sie doch kurz: Was machten Sie dort?",
      openingTr: "Özgeçmişinizde bir staj yazıyor. Kısaca anlatır mısınız: Orada ne yaptınız?",
      goal: "Stajın yeri, süresi, yaptığın işler ve sana kattıkları anlatılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-lernmethoden",
    icon: "idea",
    level: "B1",
    course: "de",
    title: "So lerne ich am besten",
    titleTr: "Öğrenme teknikleri",
    summary: "İkili bağlaçlarla yöntemlerini anlatmayı ve en etkilisini söylemeyi öğretir.",
    minutes: 10,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "die Methode", tr: "yöntem" },
      { de: "die Karteikarte", tr: "kelime kartı" },
      { de: "abwechseln", tr: "dönüşümlü yapmak" },
      { de: "effektiv", tr: "etkili" },
      { de: "die Konzentration", tr: "konsantrasyon" },
    ],
    patterns: [
      { de: "sowohl … als auch …", tr: "hem … hem …" },
      { de: "nicht nur …, sondern auch …", tr: "yalnızca … değil, aynı zamanda …" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kendi öğrenme yöntemini anlatmayı öğreneceğiz. İki şeyi birden söylemek gerekecek, o yüzden ikili bağlaçlar lazım. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkili bağlaç iki parçadan oluşur ve ikisi de söylenir; birini unutmak cümleyi yarım bırakır. En çok karıştırılan yer de tam burası. Önce kelimeler.")] },
      word("İlk", { de: "die Methode", tr: "yöntem" }),
      word("İkinci", { de: "die Karteikarte", tr: "kelime kartı" }),
      word("Üçüncü", { de: "abwechseln", tr: "dönüşümlü yapmak" }),
      word("Dördüncü", { de: "effektiv", tr: "etkili" }),
      word("Son", { de: "die Konzentration", tr: "konsantrasyon" }),
      { say: [tr("Kalıbımız:"), de("sowohl … als auch …"), tr("İkinci parça iki kelimedir ve ikisi birlikte kullanılır. Öbürü ise")] },
      { say: [tr("Örnek:"), de("Ich lerne sowohl mit Karteikarten als auch mit Podcasts."), tr("Tekrar edin:"), de("Ich lerne sowohl mit Karteikarten als auch mit Podcasts")], expect: repeat("Ich lerne sowohl mit Karteikarten als auch mit Podcasts") },
      { say: [tr("Sıra sende: 'Yalnızca kitapla değil, videoyla da öğreniyorum.'")], expect: produce("Ich lerne nicht nur mit Büchern, sondern auch mit Videos", [tr("İkinci parça virgülden sonra gelir:"), de("Ich lerne nicht nur mit Büchern, sondern auch mit Videos."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yöntemleri düzenli olarak dönüşümlü kullanıyorum.'")], expect: produce("Ich wechsle die Methoden regelmäßig ab", [tr("Ayrılabilen fiilin öneki en sona:"), de("Ich wechsle die Methoden regelmäßig ab."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'En etkilisi yüksek sesle okumak.'")], expect: produce("Am effektivsten ist es, laut zu lesen", [tr("En üstünlük derecesi başta, zu'lu mastar sonda:"), de("Am effektivsten ist es, laut zu lesen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich lerne sowohl mit Karteikarten und auch mit Podcasts."), tr("cümlesi doğru mu?")], expect: truefalse("Ich lerne sowohl mit Karteikarten und auch mit Podcasts.", false, [tr("İkili bağlacın ikinci parçası başka bir kelimeyle kurulur:"), de("Ich lerne sowohl mit Karteikarten als auch mit Podcasts.")]) },
      { say: [tr("Son: 'Konsantrasyonum yirmi dakika sürüyor.'")], expect: produce("Meine Konzentration hält zwanzig Minuten", [tr("Düz cümle, süre sonda:"), de("Meine Konzentration hält zwanzig Minuten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kurs arkadaşına yöntemlerini anlatacaksın ve onunkini soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir kurs arkadaşınla öğrenme yöntemlerinizi karşılaştırıyorsunuz: neyi nasıl çalışıyorsun, ne işe yarıyor, ne yaramıyor. İkili bağlaçlarla iki şeyi birden söyle.",
      partner: "kendi yöntemini savunan, meraklı bir kurs arkadaşı",
      opening: "Sag mal, wie lernst du eigentlich? Ich komme mit meiner Methode gerade nicht weiter.",
      openingTr: "Söylesene, sen nasıl çalışıyorsun? Benim yöntemim bir yere varmıyor.",
      goal: "İkinizin yöntemleri karşılaştırılmış ve birbirinizden bir şey denemeye karar verilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-fehlerkultur",
    icon: "feelings",
    level: "B1",
    course: "de",
    title: "Fehler sind Freunde",
    titleTr: "Hatayla barışmak",
    summary: "Hata yapmayı zıtlık cümleleriyle konuşmayı ve cesareti korumayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-obwohl",
    vocab: [
      { de: "der Fehler", tr: "hata" },
      { de: "entmutigt", tr: "cesareti kırılmış" },
      { de: "zugeben", tr: "kabul etmek" },
      { de: "korrigieren", tr: "düzeltmek" },
      { de: "der Umgang", tr: "baş etme biçimi" },
    ],
    patterns: [
      { de: "Obwohl ich Fehler mache, …", tr: "zıtlık yan cümlesi" },
      { de: "Aus Fehlern lernt man.", tr: "genel doğru" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün dilbilgisinden çok bir tutum öğreneceğiz — ama onu da Almanca söyleyeceğiz. Konu hata. Hata konuşulmazsa büyür, konuşulursa küçülür. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bunun için zıtlık bağlacı lazım: 'yapmama rağmen'. Yan cümle olduğu için fiil sona gidiyor ve cümle başta duruyorsa ana cümle fiille başlıyor. Önce kelimeler.")] },
      word("İlk", { de: "der Fehler", tr: "hata" }),
      word("İkinci", { de: "entmutigt", tr: "cesareti kırılmış" }),
      word("Üçüncü", { de: "zugeben", tr: "kabul etmek" }),
      word("Dördüncü", { de: "korrigieren", tr: "düzeltmek" }),
      word("Son", { de: "der Umgang", tr: "baş etme biçimi" }),
      { say: [tr("Kalıbımız:"), de("Obwohl ich Fehler mache, spreche ich weiter."), tr("Yan cümlenin fiili sonda, ana cümleninki hemen virgülden sonra.")] },
      { say: [tr("Tekrar edin:"), de("Obwohl ich viele Fehler mache, spreche ich weiter")], expect: repeat("Obwohl ich viele Fehler mache, spreche ich weiter") },
      { say: [tr("Sıra sende: 'Hata yapmama rağmen cesaretim kırılmıyor.'")], expect: produce("Obwohl ich Fehler mache, bin ich nicht entmutigt", [tr("Ana cümle fiille başlar, sıfat sonda:"), de("Obwohl ich Fehler mache, bin ich nicht entmutigt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Hatamı kabul etmek bana kolay gelmiyor.'")], expect: produce("Es fällt mir nicht leicht, meinen Fehler zuzugeben", [tr("Ayrılabilen fiilde küçük bağlaç ortaya girer:"), de("Es fällt mir nicht leicht, meinen Fehler zuzugeben."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Öğretmen beni her cümlede düzeltiyor.'")], expect: produce("Die Lehrerin korrigiert mich in jedem Satz", [tr("Düz cümle; yer tümleci sonda:"), de("Die Lehrerin korrigiert mich in jedem Satz."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Obwohl ich müde bin, lerne ich weiter."), tr("cümlesi doğru mu?")], expect: truefalse("Obwohl ich müde bin, lerne ich weiter.", true, [tr("Doğru. Yan cümlenin fiili sonda, ana cümle fiille başlıyor.")]) },
      { say: [tr("Son: 'Hatayla baş etmek öğrenilebilir.'")], expect: produce("Der Umgang mit Fehlern kann gelernt werden", [tr("Modal fiille edilgen; ortaç ve werden en sonda:"), de("Der Umgang mit Fehlern kann gelernt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşına hata korkunu anlatacaksın: ne oluyor, neye rağmen devam ediyorsun.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla hata yapma korkusunu konuşuyorsun: konuşurken neden çekiniyorsun, neye rağmen devam ediyorsun, hataları nasıl karşılıyorsun. Zıtlık cümleleri kur.",
      partner: "kendi hatalarını rahatça anlatan, rahatlatıcı bir arkadaş",
      opening: "Du sagst kaum etwas im Kurs, obwohl du viel kannst. Was hält dich zurück?",
      openingTr: "Kursta neredeyse hiç konuşmuyorsun, oysa çok şey biliyorsun. Seni tutan ne?",
      goal: "Çekincenin sebebi anlatılmış ve neye rağmen devam edeceğin söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-mentor",
    icon: "handshake",
    level: "B1",
    course: "de",
    title: "Ein Gespräch mit dem Mentor",
    titleTr: "Mentorluk görüşmesi",
    summary: "Tavsiye vermeyi ve istemeyi dilek kipiyle kurmayı öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "der Mentor", tr: "mentor" },
      { de: "begleiten", tr: "eşlik etmek" },
      { de: "die Rückmeldung", tr: "geri bildirim" },
      { de: "ermutigen", tr: "cesaretlendirmek" },
      { de: "die Perspektive", tr: "bakış açısı" },
    ],
    patterns: [
      { de: "An deiner Stelle würde ich …", tr: "senin yerinde olsam" },
      { de: "Was würdest du tun?", tr: "tavsiye sorma" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi. Bugün tavsiye alışverişi yapacağız — vermek ve istemek. İkisi de aynı fiil biçimini kullanıyor: dilek kipi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tavsiyeyi düz kipte söylersen emir gibi durur. Dilek kipi araya bir yumuşaklık koyuyor: 'yaparım' değil, 'yapardım'. Önce kelimeler.")] },
      word("İlk", { de: "der Mentor", tr: "mentor" }),
      word("İkinci", { de: "begleiten", tr: "eşlik etmek" }),
      word("Üçüncü", { de: "die Rückmeldung", tr: "geri bildirim" }),
      word("Dördüncü", { de: "ermutigen", tr: "cesaretlendirmek" }),
      word("Son", { de: "die Perspektive", tr: "bakış açısı" }),
      { say: [tr("Kalıbımız:"), de("An deiner Stelle würde ich …"), tr("Cümle bir tümleçle başlıyor, o yüzden çekimli fiil ikinci sırada ve mastar en sonda.")] },
      { say: [tr("Örnek:"), de("An deiner Stelle würde ich mit der Chefin sprechen."), tr("Tekrar edin:"), de("An deiner Stelle würde ich mit der Chefin sprechen")], expect: repeat("An deiner Stelle würde ich mit der Chefin sprechen") },
      { say: [tr("Sıra sende: 'Senin yerinde olsam önce bir kurs yapardım.'")], expect: produce("An deiner Stelle würde ich zuerst einen Kurs machen", [tr("Tümleç başta, çekimli fiil ikinci, mastar sonda:"), de("An deiner Stelle würde ich zuerst einen Kurs machen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi kibar bir rica: 'Bana geri bildirim verebilir misin?'")], expect: produce("Könntest du mir eine Rückmeldung geben", [tr("Dilek kipiyle soru, mastar sonda:"), de("Könntest du mir eine Rückmeldung geben?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, geçen modülden ilgi cümlesiyle: 'Beni cesaretlendiren birine ihtiyacım var.'")], expect: produce("Ich brauche jemanden, der mich ermutigt", [tr("Belirsiz kişide ilgi zamiri eril:"), de("Ich brauche jemanden, der mich ermutigt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("An deiner Stelle ich würde warten."), tr("cümlesi doğru mu?")], expect: truefalse("An deiner Stelle ich würde warten.", false, [tr("Cümle tümleçle başlayınca çekimli fiil ikinci sıraya gelir:"), de("An deiner Stelle würde ich warten.")]) },
      { say: [tr("Son: 'Sen benim yerimde ne yapardın?'")], expect: produce("Was würdest du an meiner Stelle tun", [tr("Soru kelimesi başta, mastar en sonda:"), de("Was würdest du an meiner Stelle tun?"), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada mentorunla bir kararı konuşacaksın: seçeneklerin ne, o senin yerinde ne yapardı.")] },
    ],
    roleplay: {
      scene: "Mentorunla bir kariyer kararını konuşuyorsun: seçeneklerini anlat, onun ne yapacağını sor, geri bildirim iste. Tavsiye alışverişini dilek kipiyle kur.",
      partner: "deneyimli, doğrudan konuşan bir mentor",
      opening: "Du stehst also vor einer Entscheidung. Erzähl mir, welche Möglichkeiten du siehst — was würdest du am liebsten tun?",
      openingTr: "Demek bir karar aşamasındasın. Anlat bakalım, hangi seçenekleri görüyorsun — en çok ne yapmak isterdin?",
      goal: "Seçenekler anlatılmış, mentorun görüşü alınmış ve bir sonraki adım kararlaşmış olur.",
      minTurns: 9,
    },
  },
];
