import { de, tr, type LectureStep, type Lesson, type Segment } from "../types";

/**
 * B1 · Modül 18 — Kültür, spor ve doğa (171–180).
 *
 * B1'in son modülü. Buraya kadar dersler hep bir İŞİ hallediyordu: başvuru,
 * kira, randevu, şikâyet. Bu modül ilk kez zorunlu olmayanı konuşuyor —
 * konser, maç, doğa, tatil planı. B1'in gerçek eşiği budur: dili yalnız
 * gerektiği için değil, canı istediği için kullanabilmek.
 *
 * Son ders (de-b1-b1-abschluss) seviyenin kapanışı. Modül 10'un
 * «Zwischenbilanz» dersi ilk yüz dersin ara değerlendirmesiydi; kapanış
 * burada, çünkü katalog sırası ilerlemeyi de belirliyor.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [
      tr(`${n} kelimemiz:`),
      de(w.de),
      tr(`Türkçesi '${w.tr}' demek${note ? ` — ${note}` : ""}. Lütfen`),
      de(w.de),
      tr("deyin."),
    ],
    expect: repeat(w.de),
  };
}

export const deB1B18: Lesson[] = [
  {
    id: "de-b1-oper-konzert",
    icon: "music",
    level: "B1",
    course: "de",
    title: "Ein Abend in der Oper",
    titleTr: "Konser akşamı",
    summary: "Bir mekânı ve etkinliği edatlı ilgi cümleleriyle tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Präposition",
    vocab: [
      { de: "die Oper", tr: "opera" },
      { de: "das Orchester", tr: "orkestra" },
      { de: "das Ballett", tr: "bale" },
      { de: "die Flöte", tr: "flüt" },
      { de: "die Galerie", tr: "galeri" },
      { de: "der Zuhörer", tr: "dinleyici" },
      { de: "die Eröffnung", tr: "açılış" },
      { de: "eröffnen", tr: "açmak" },
    ],
    patterns: [
      { de: "der Saal, in dem …", tr: "mekânı tanımlayan edatlı ilgi cümlesi" },
      { de: "das Stück, von dem ich …", tr: "bahsedilen eseri tanımlar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bu modül ilk kez zorunlu olmayan bir şeyi konuşuyor: bir konser akşamı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Mekân ve eser tanımlarken edatlı ilgi cümlesi kuracağız. Edat zamirin önüne gelir ve hâlini belirler. Önce kelimeler.")] },
      word("İlk", { de: "die Oper", tr: "opera" }, "hem yapı hem sahne türü"),
      word("İkinci", { de: "das Orchester", tr: "orkestra" }),
      word("Üçüncü", { de: "das Ballett", tr: "bale" }),
      word("Dördüncü", { de: "die Flöte", tr: "flüt" }),
      word("Beşinci", { de: "die Galerie", tr: "galeri" }),
      word("Altıncı", { de: "der Zuhörer", tr: "dinleyici" }),
      word("Yedinci", { de: "die Eröffnung", tr: "açılış" }),
      word("Son", { de: "eröffnen", tr: "açmak" }),
      { say: [tr("İlk kalıbımız mekânı tanımlıyor. Yer edatı yönelme hâli istiyor, o yüzden ilgi zamiri de yönelme hâlinde.")] },
      { say: [tr("Örnek:"), de("Das ist der Saal, in dem das Orchester spielt."), tr("Tekrar edin:"), de("Das ist der Saal, in dem das Orchester spielt")], expect: repeat("Das ist der Saal, in dem das Orchester spielt") },
      { say: [tr("Sıra sende: 'Bu, açılışın yapıldığı galeri.'")], expect: produce("Das ist die Galerie, in der die Eröffnung war", [tr("Dişil adda edat yönelme hâli istiyor:"), de("Das ist die Galerie, in der die Eröffnung war."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız eseri tanımlıyor: bahsetmek fiilinin sabit edatı zamirin önüne geliyor.")] },
      { say: [tr("Şimdi: 'Bu, sana bahsettiğim bale.'")], expect: produce("Das ist das Ballett, von dem ich dir erzählt habe", [tr("Edat zamirin önünde, yardımcı fiil sonda:"), de("Das ist das Ballett, von dem ich dir erzählt habe."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist die Oper, die ich gestern war."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist die Oper, die ich gestern war.", false, [tr("Bir yerde bulunmak yer edatı ister ve o edat zamirin önüne gelir:"), de("Das ist die Oper, in der ich gestern war.")]) },
      { say: [tr("Son: 'Dinleyiciler flüte uzun uzun alkış tuttu.'")], expect: produce("Die Zuhörer klatschten lange für die Flöte", [tr("Çoğul özne, geçmiş zaman, edatlı öbek sonda:"), de("Die Zuhörer klatschten lange für die Flöte."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir arkadaşına gittiğin konseri anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Dün akşam bir konsere gittin. Arkadaşına salonu, çalınan eseri ve gecenin nasıl geçtiğini anlatıyorsun.",
      partner: "klasik müziğe uzak ama merak eden bir arkadaş",
      opening: "Du warst gestern in der Oper? Wie war es denn — lohnt sich das?",
      openingTr: "Dün operada mıydın? Nasıldı — değer mi?",
      goal: "Mekân ve eser tanımlanmış, gecenin nasıl geçtiği anlatılmış ve bir tavsiye verilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-literatur-lesen",
    icon: "book",
    level: "B1",
    course: "de",
    title: "Was liest du gerade?",
    titleTr: "Okuduğun kitap",
    summary: "Bir kitabı ve yazarı ilgi cümleleriyle tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Nominativ",
    vocab: [
      { de: "die Literatur", tr: "edebiyat" },
      { de: "das Märchen", tr: "masal" },
      { de: "der Dialog", tr: "diyalog" },
      { de: "die Recherche", tr: "araştırma" },
      { de: "vorlesen", tr: "sesli okumak" },
      { de: "abschreiben", tr: "kopya çekmek" },
      { de: "die Journalistin", tr: "kadın gazeteci" },
      { de: "der Schauspieler", tr: "oyuncu" },
    ],
    patterns: [
      { de: "ein Buch, das … erzählt", tr: "kitabı içeriğiyle tanımlar" },
      { de: "Es geht um …", tr: "konunun ne olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün okuduğun kitabı anlatacaksın. Bir kitabı anlatmanın en kısa yolu ilgi cümlesidir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tanımlanan şey yan cümlenin öznesi olduğunda ilgi zamiri yalın hâlde kalır ve fiil sona gider. Önce kelimeler.")] },
      word("İlk", { de: "die Literatur", tr: "edebiyat" }),
      word("İkinci", { de: "das Märchen", tr: "masal" }),
      word("Üçüncü", { de: "der Dialog", tr: "diyalog" }),
      word("Dördüncü", { de: "die Recherche", tr: "araştırma" }, "gazetecinin ön çalışması"),
      word("Beşinci", { de: "vorlesen", tr: "sesli okumak" }),
      word("Altıncı", { de: "abschreiben", tr: "kopya çekmek" }),
      word("Yedinci", { de: "die Journalistin", tr: "kadın gazeteci" }),
      word("Son", { de: "der Schauspieler", tr: "oyuncu" }),
      { say: [tr("İlk kalıbımız kitabı içeriğiyle tanımlıyor. İlgi zamiri tanımlanan adın cinsiyetini alıyor.")] },
      { say: [tr("Örnek:"), de("Es ist ein Buch, das eine wahre Geschichte erzählt."), tr("Tekrar edin:"), de("Es ist ein Buch, das eine wahre Geschichte erzählt")], expect: repeat("Es ist ein Buch, das eine wahre Geschichte erzählt") },
      { say: [tr("Sıra sende: 'Bu, çocuklara sesli okuduğum bir masal.'")], expect: produce("Das ist ein Märchen, das ich den Kindern vorlese", [tr("Ayrılabilen fiil yan cümlede birleşik kalır ve sona gider:"), de("Das ist ein Märchen, das ich den Kindern vorlese."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız konuyu söylüyor: kişisiz bir yapı ve sabit edat. Kitap ve film anlatırken standarttır.")] },
      { say: [tr("Şimdi: 'Konusu bir gazetecinin araştırması.'")], expect: produce("Es geht um die Recherche einer Journalistin", [tr("Kişisiz özne, edattan sonra belirtme hâli:"), de("Es geht um die Recherche einer Journalistin."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist ein Roman, der ich sehr mag."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist ein Roman, der ich sehr mag.", false, [tr("Roman burada sevilen şey, yani nesne; eril ad nesne olunca zamir değişir:"), de("Das ist ein Roman, den ich sehr mag.")]) },
      { say: [tr("Son: 'Diyaloglar bir oyuncu tarafından okundu.'")], expect: produce("Die Dialoge wurden von einem Schauspieler gelesen", [tr("Çoğul özne, edilgen geçmiş, yapan edatla:"), de("Die Dialoge wurden von einem Schauspieler gelesen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi okuduğun bir kitabı anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın kitap tavsiyesi istiyor. Son okuduğunu tanımlıyor, konusunu anlatıyor ve neden beğendiğini söylüyorsun.",
      partner: "uzun kitaplardan çekinen ama okumak isteyen bir arkadaş",
      opening: "Ich brauche was zu lesen — hast du einen Tipp für mich?",
      openingTr: "Okuyacak bir şeye ihtiyacım var — bana bir tavsiyen var mı?",
      goal: "Kitap tanımlanmış, konusu anlatılmış ve neden önerildiği söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-fest-feiern",
    icon: "party",
    level: "B1",
    course: "de",
    title: "Fasching und Karneval",
    titleTr: "Karnaval",
    summary: "Kutlamayı zaman bağlaçlarıyla sırayla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-bevor-während",
    vocab: [
      { de: "der Karneval", tr: "karnaval" },
      { de: "der Fasching", tr: "karnaval (güney)" },
      { de: "die Garderobe", tr: "vestiyer" },
      { de: "anhaben", tr: "üzerinde olmak" },
      { de: "sich amüsieren", tr: "eğlenmek" },
      { de: "sich vergnügen", tr: "hoşça vakit geçirmek" },
      { de: "vergnügt", tr: "keyifli" },
      { de: "grüßen", tr: "selamlamak" },
    ],
    patterns: [
      { de: "Bevor das Fest beginnt, …", tr: "kutlamadan öncesini anlatır" },
      { de: "Während alle tanzen, …", tr: "aynı anda olanı anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Almanya'nın güneyinde ve Ren bölgesinde yılın en büyük eğlencesi karnavaldır. Bugün onu sırayla anlatacağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki bağlaç kullanacağız: biri önceyi, biri aynı anı gösteriyor. İkisinde de fiil yan cümlenin sonuna gider. Önce kelimeler.")] },
      word("İlk", { de: "der Karneval", tr: "karnaval" }, "Ren bölgesindeki adı"),
      word("İkinci", { de: "der Fasching", tr: "karnaval (güney)" }, "Bavyera ve Avusturya'daki adı"),
      word("Üçüncü", { de: "die Garderobe", tr: "vestiyer" }),
      word("Dördüncü", { de: "anhaben", tr: "üzerinde olmak" }, "giysi için kullanılır"),
      word("Beşinci", { de: "sich amüsieren", tr: "eğlenmek" }),
      word("Altıncı", { de: "sich vergnügen", tr: "hoşça vakit geçirmek" }),
      word("Yedinci", { de: "vergnügt", tr: "keyifli" }),
      word("Son", { de: "grüßen", tr: "selamlamak" }),
      { say: [tr("İlk bağlacımız önceyi gösteriyor. Yan cümle başta olursa ana cümle fiille başlar.")] },
      { say: [tr("Örnek:"), de("Bevor das Fest beginnt, ziehen wir uns um."), tr("Tekrar edin:"), de("Bevor das Fest beginnt, ziehen wir uns um")], expect: repeat("Bevor das Fest beginnt, ziehen wir uns um") },
      { say: [tr("Sıra sende: 'Çıkmadan önce paltoyu vestiyere veriyoruz.'")], expect: produce("Bevor wir hineingehen, geben wir die Mäntel an der Garderobe ab", [tr("Yan cümlede fiil sonda, ana cümlede önek sonda:"), de("Bevor wir hineingehen, geben wir die Mäntel an der Garderobe ab."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci bağlacımız aynı anı gösteriyor: bir iş sürerken öteki oluyor.")] },
      { say: [tr("Şimdi: 'Herkes dans ederken ben herkesi selamlıyorum.'")], expect: produce("Während alle tanzen, grüße ich alle", [tr("Yan cümlede fiil sonda, ana cümle fiille başlıyor:"), de("Während alle tanzen, grüße ich alle."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Während wir feiern, wir vergessen die Zeit."), tr("cümlesi doğru mu?")], expect: truefalse("Während wir feiern, wir vergessen die Zeit.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar:"), de("Während wir feiern, vergessen wir die Zeit.")]) },
      { say: [tr("Son: 'Ne giydiğini sordu ve keyifle güldü.'")], expect: produce("Sie fragte, was ich anhabe, und lachte vergnügt", [tr("Dolaylı soruda fiil sonda, ikinci cümle bağlaçla ekleniyor:"), de("Sie fragte, was ich anhabe, und lachte vergnügt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir kutlamayı sırayla anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Karnavalda geçirdiğin bir günü anlatıyorsun: öncesinde ne yaptın, sırasında ne oldu, sonunda nasıl bitti.",
      partner: "karnavalı hiç yaşamamış, her ayrıntıyı soran bir arkadaş",
      opening: "Karneval — ich habe das noch nie erlebt. Wie läuft so ein Tag denn ab?",
      openingTr: "Karnaval — bunu hiç yaşamadım. Böyle bir gün nasıl geçiyor?",
      goal: "Günün öncesi, sırası ve sonu zaman bağlaçlarıyla anlatılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-sport-treiben",
    icon: "sport",
    level: "B1",
    course: "de",
    title: "Sport im Alltag",
    titleTr: "Spor yapmak",
    summary: "Niyet ve tavsiyeyi mastar öbeğiyle söylemeyi öğretir.",
    minutes: 10,
    focusId: "Infinitiv-zu",
    vocab: [
      { de: "die Sportart", tr: "spor dalı" },
      { de: "das Stadion", tr: "stadyum" },
      { de: "der Profi", tr: "profesyonel" },
      { de: "der Trainer", tr: "antrenör" },
      { de: "der Spieler", tr: "oyuncu" },
      { de: "das Hallenbad", tr: "kapalı havuz" },
      { de: "kräftig", tr: "güçlü" },
      { de: "schlank", tr: "ince" },
    ],
    patterns: [
      { de: "Ich versuche, … zu …", tr: "neyi denediğini söyler" },
      { de: "Es ist wichtig, … zu …", tr: "neyin önemli olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün spor konuşacağız. Niyet ve tavsiye cümleleri mastar öbeğiyle kurulur ve mastar en sona gider. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Türkçede niyet tek ekle çıkar; Almancada cümle ikiye bölünür ve nesne mastardan önce gelir. Önce kelimeler.")] },
      word("İlk", { de: "die Sportart", tr: "spor dalı" }),
      word("İkinci", { de: "das Stadion", tr: "stadyum" }),
      word("Üçüncü", { de: "der Profi", tr: "profesyonel" }),
      word("Dördüncü", { de: "der Trainer", tr: "antrenör" }),
      word("Beşinci", { de: "der Spieler", tr: "oyuncu" }),
      word("Altıncı", { de: "das Hallenbad", tr: "kapalı havuz" }),
      word("Yedinci", { de: "kräftig", tr: "güçlü" }),
      word("Son", { de: "schlank", tr: "ince" }),
      { say: [tr("İlk kalıbımız denemeyi söylüyor: bir fiil ve mastar öbeği. Kesin söz vermeden niyet bildirir.")] },
      { say: [tr("Örnek:"), de("Ich versuche, zweimal pro Woche zu schwimmen."), tr("Tekrar edin:"), de("Ich versuche, zweimal pro Woche zu schwimmen")], expect: repeat("Ich versuche, zweimal pro Woche zu schwimmen") },
      { say: [tr("Sıra sende: 'Yeni bir spor dalı denemeye çalışıyorum.'")], expect: produce("Ich versuche, eine neue Sportart auszuprobieren", [tr("Ayrılabilen fiilde edat önek ile kök arasına giriyor:"), de("Ich versuche, eine neue Sportart auszuprobieren."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız tavsiye veriyor: kişisiz bir yapı ve mastar öbeği. Kimseyi suçlamadan öneride bulunur.")] },
      { say: [tr("Şimdi: 'Düzenli hareket etmek önemli.'")], expect: produce("Es ist wichtig, sich regelmäßig zu bewegen", [tr("Dönüşlü zamir mastardan önce:"), de("Es ist wichtig, sich regelmäßig zu bewegen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es ist wichtig, zu trinken viel Wasser."), tr("cümlesi doğru mu?")], expect: truefalse("Es ist wichtig, zu trinken viel Wasser.", false, [tr("Mastar öbeğinde nesne mastardan ÖNCE gelir:"), de("Es ist wichtig, viel Wasser zu trinken.")]) },
      { say: [tr("Son: 'Antrenör oyuncuların güçlü olmasını istiyor.'")], expect: produce("Der Trainer will, dass die Spieler kräftig sind", [tr("İstemek fiili farklı özneyle yan cümle alır, fiil sonda:"), de("Der Trainer will, dass die Spieler kräftig sind."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir spor kulübünde bilgi alacaksın.")] },
    ],
    roleplay: {
      scene: "Bir spor kulübüne bilgi almaya gittin. Hangi spor dallarının olduğunu, saatleri ve ücreti soruyor, neyi denemek istediğini söylüyorsun.",
      partner: "herkesi bir şeye yazdırmak isteyen enerjik bir antrenör",
      opening: "Willkommen! Suchen Sie etwas Bestimmtes, oder wollen Sie sich erst mal umschauen?",
      openingTr: "Hoş geldiniz! Belirli bir şey mi arıyorsunuz, yoksa önce bakmak mı istersiniz?",
      goal: "Spor dalları ve koşullar öğrenilmiş, bir deneme dersi kararlaştırılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-wettkampf",
    icon: "sport",
    level: "B1",
    course: "de",
    title: "Das Spiel gestern",
    titleTr: "Dünkü maç",
    summary: "Maçta olanları edilgen çatının geçmişiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "der Sieger", tr: "galip" },
      { de: "der Sieg", tr: "zafer" },
      { de: "siegen", tr: "galip gelmek" },
      { de: "der Gegner", tr: "rakip" },
      { de: "der Verlierer", tr: "kaybeden" },
      { de: "der Rekord", tr: "rekor" },
      { de: "unentschieden", tr: "berabere" },
      { de: "das Tor", tr: "gol" },
    ],
    patterns: [
      { de: "Das Tor wurde in der letzten Minute geschossen.", tr: "maçta olanı kişisiz anlatır" },
      { de: "Es ging unentschieden aus.", tr: "sonucun beraberlik olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Dün bir maç vardı. Spor anlatımı da edilgendir: golü kimin attığı sonra söylenir, önce ne olduğu. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgenin geçmişinde yardımcı fiil geçmiş biçimde ikinci sırada, ortaç sonda. Önce kelimeler.")] },
      word("İlk", { de: "der Sieger", tr: "galip" }),
      word("İkinci", { de: "der Sieg", tr: "zafer" }),
      word("Üçüncü", { de: "siegen", tr: "galip gelmek" }),
      word("Dördüncü", { de: "der Gegner", tr: "rakip" }),
      word("Beşinci", { de: "der Verlierer", tr: "kaybeden" }),
      word("Altıncı", { de: "der Rekord", tr: "rekor" }),
      word("Yedinci", { de: "unentschieden", tr: "berabere" }),
      word("Son", { de: "das Tor", tr: "gol" }, "aynı sözcük 'kapı' anlamına da gelir"),
      { say: [tr("İlk kalıbımız golü anlatıyor. Yardımcı fiil ikinci sırada, ortaç sonda; atan kişi söylenmiyor.")] },
      { say: [tr("Örnek:"), de("Das Tor wurde in der letzten Minute geschossen."), tr("Tekrar edin:"), de("Das Tor wurde in der letzten Minute geschossen")], expect: repeat("Das Tor wurde in der letzten Minute geschossen") },
      { say: [tr("Sıra sende: 'Yeni bir rekor kırıldı.'")], expect: produce("Ein neuer Rekord wurde aufgestellt", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Ein neuer Rekord wurde aufgestellt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız sonucu söylüyor: ayrılabilen bir fiil, öneki sonda. Spor haberlerinde standart.")] },
      { say: [tr("Şimdi: 'Maç berabere bitti.'")], expect: produce("Das Spiel ging unentschieden aus", [tr("Ayrılabilen fiilin öneki cümlenin sonunda:"), de("Das Spiel ging unentschieden aus."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Sieger wurde gestern feiern."), tr("cümlesi doğru mu?")], expect: truefalse("Der Sieger wurde gestern feiern.", false, [tr("Edilgende asıl fiil ortaç hâlinde olmalı:"), de("Der Sieger wurde gestern gefeiert.")]) },
      { say: [tr("Son: 'Rakip iyi oynadı ama biz galip geldik.'")], expect: produce("Der Gegner spielte gut, aber wir siegten", [tr("İki ana cümle zıtlık bağlacıyla, ikisinde de geçmiş zaman:"), de("Der Gegner spielte gut, aber wir siegten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi dünkü maçı anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Dünkü maçı kaçıran bir arkadaşına anlatıyorsun: ne oldu, kim ne yaptı, sonuç ne çıktı.",
      partner: "maçı kaçırmış, sonucu bilmek istemeyen ama dayanamayan bir arkadaş",
      opening: "Sag es mir nicht! … Ach doch, sag es. Wie ist es ausgegangen?",
      openingTr: "Söyleme sakın! … Yok, söyle. Nasıl bitti?",
      goal: "Maçın gidişatı ve sonucu anlatılmış, en az iki olay kişisiz biçimde söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-natur-erleben",
    icon: "nature",
    level: "B1",
    course: "de",
    title: "Raus ins Grüne",
    titleTr: "Doğaya çıkmak",
    summary: "Geçmişte bir kez olan bir günü als bağlacıyla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-als",
    vocab: [
      { de: "der Rasen", tr: "çim" },
      { de: "das Feld", tr: "tarla" },
      { de: "der Hof", tr: "avlu" },
      { de: "blühen", tr: "çiçek açmak" },
      { de: "klettern", tr: "tırmanmak" },
      { de: "springen", tr: "atlamak" },
      { de: "tauchen", tr: "dalmak" },
      { de: "zelten", tr: "kamp yapmak" },
    ],
    patterns: [
      { de: "Als wir ankamen, …", tr: "geçmişte tek seferlik olayı anlatır" },
      { de: "Es hat sich gelohnt.", tr: "değdiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün doğada geçen bir günü anlatacağız. Geçmişte bir kez olan olayın bağlacı belli. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yan cümlede fiil sona gider; yan cümle başta olursa ana cümle fiille başlar. Önce kelimeler.")] },
      word("İlk", { de: "der Rasen", tr: "çim" }, "bakımlı, biçilmiş çim"),
      word("İkinci", { de: "das Feld", tr: "tarla" }),
      word("Üçüncü", { de: "der Hof", tr: "avlu" }, "çiftlik anlamına da gelir"),
      word("Dördüncü", { de: "blühen", tr: "çiçek açmak" }),
      word("Beşinci", { de: "klettern", tr: "tırmanmak" }),
      word("Altıncı", { de: "springen", tr: "atlamak" }),
      word("Yedinci", { de: "tauchen", tr: "dalmak" }),
      word("Son", { de: "zelten", tr: "kamp yapmak" }),
      { say: [tr("İlk kalıbımız varış anını anlatıyor. Yan cümle başta, ana cümle fiille başlıyor.")] },
      { say: [tr("Örnek:"), de("Als wir ankamen, blühte das ganze Feld."), tr("Tekrar edin:"), de("Als wir ankamen, blühte das ganze Feld")], expect: repeat("Als wir ankamen, blühte das ganze Feld") },
      { say: [tr("Sıra sende: 'Çadırı kurduğumuzda yağmur başladı.'")], expect: produce("Als wir das Zelt aufbauten, fing der Regen an", [tr("Yan cümlede fiil sonda, ana cümle fiille başlıyor:"), de("Als wir das Zelt aufbauten, fing der Regen an."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız değerlendirme yapıyor: dönüşlü ve kişisiz bir fiil. Bir günü kapatan cümle.")] },
      { say: [tr("Şimdi: 'Yine de değdi.'")], expect: produce("Trotzdem hat es sich gelohnt", [tr("Zarf başta, yardımcı fiil ikinci sırada, ortaç sonda:"), de("Trotzdem hat es sich gelohnt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Als die Sonne kam, wir sprangen ins Wasser."), tr("cümlesi doğru mu?")], expect: truefalse("Als die Sonne kam, wir sprangen ins Wasser.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar:"), de("Als die Sonne kam, sprangen wir ins Wasser.")]) },
      { say: [tr("Son: 'Çocuklar ağaca tırmandı, biz çimende oturduk.'")], expect: produce("Die Kinder kletterten auf den Baum, wir saßen auf dem Rasen", [tr("İki ana cümle, ikisinde de geçmiş zaman:"), de("Die Kinder kletterten auf den Baum, wir saßen auf dem Rasen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi doğada geçen bir günü anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Hafta sonu doğaya çıktın. Bir arkadaşına o günü anlatıyorsun: nereye gittiniz, ne yaptınız, değdi mi.",
      partner: "hafta sonunu evde geçirmiş, biraz kıskanan bir arkadaş",
      opening: "Ihr wart draußen? Ich habe den ganzen Tag drinnen gesessen — wie war es?",
      openingTr: "Dışarıda mıydınız? Ben bütün gün içeride oturdum — nasıldı?",
      goal: "Günün akışı sırayla anlatılmış ve değip değmediği söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-wetter-extrem",
    icon: "weather",
    level: "B1",
    course: "de",
    title: "So ein Wetter",
    titleTr: "Hava değişimi",
    summary: "Havayı ve arazi biçimlerini karşılaştırmayı öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "der Donner", tr: "gök gürültüsü" },
      { de: "donnern", tr: "gök gürlemek" },
      { de: "frieren", tr: "üşümek" },
      { de: "steil", tr: "dik" },
      { de: "flach", tr: "düz" },
      { de: "quer", tr: "enine" },
      { de: "trocknen", tr: "kurumak" },
      { de: "wild", tr: "vahşi" },
    ],
    patterns: [
      { de: "Es wird immer kälter.", tr: "artan bir değişimi anlatır" },
      { de: "Je höher, desto steiler.", tr: "iki şeyin birlikte arttığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Hava ve arazi konuşacağız. Bu konunun dili karşılaştırmadır: daha soğuk, daha dik, gittikçe kötü. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Artan değişim için sıfatın karşılaştırma biçimi bir zarfla tekrarlanır; orantı için ikili bağlaç kullanılır. Önce kelimeler.")] },
      word("İlk", { de: "der Donner", tr: "gök gürültüsü" }),
      word("İkinci", { de: "donnern", tr: "gök gürlemek" }),
      word("Üçüncü", { de: "frieren", tr: "üşümek" }),
      word("Dördüncü", { de: "steil", tr: "dik" }),
      word("Beşinci", { de: "flach", tr: "düz" }),
      word("Altıncı", { de: "quer", tr: "enine" }),
      word("Yedinci", { de: "trocknen", tr: "kurumak" }),
      word("Son", { de: "wild", tr: "vahşi" }),
      { say: [tr("İlk kalıbımız artan değişimi anlatıyor: bir zarf ve sıfatın karşılaştırma biçimi. Hava konuşmasının kalıbıdır.")] },
      { say: [tr("Örnek:"), de("Es wird immer kälter."), tr("Tekrar edin:"), de("Es wird immer kälter")], expect: repeat("Es wird immer kälter") },
      { say: [tr("Sıra sende: 'Yol gittikçe dikleşiyor.'")], expect: produce("Der Weg wird immer steiler", [tr("Zarf ve sıfatın karşılaştırma biçimi:"), de("Der Weg wird immer steiler."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız orantı kuruyor. Kısa biçiminde fiil hiç söylenmez; hava ve arazi konuşmasında çok geçer.")] },
      { say: [tr("Şimdi: 'Ne kadar yükseğe çıkarsak yol o kadar dikleşiyor.'")], expect: produce("Je höher wir steigen, desto steiler wird der Weg", [tr("İlk bölümde fiil sonda, ikinci bölümde fiil öznenin önünde:"), de("Je höher wir steigen, desto steiler wird der Weg."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es wird immer mehr kalt."), tr("cümlesi doğru mu?")], expect: truefalse("Es wird immer mehr kalt.", false, [tr("Karşılaştırma ayrı bir zarfla değil, sıfata gelen ekle yapılır:"), de("Es wird immer kälter.")]) },
      { say: [tr("Son: 'Gök gürledi ve çamaşırlar kurumadı.'")], expect: produce("Es donnerte und die Wäsche trocknete nicht", [tr("İki ana cümle bağlaçla, ikisinde de geçmiş zaman:"), de("Es donnerte und die Wäsche trocknete nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir yürüyüşte havanın nasıl değiştiğini anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir yürüyüşte hava aniden bozdu. Bir arkadaşınla neyin nasıl değiştiğini ve ne yapmanız gerektiğini konuşuyorsunuz.",
      partner: "üşüyen ve geri dönmek isteyen bir yürüyüş arkadaşı",
      opening: "Es wird immer kälter — sollen wir umkehren oder weitergehen?",
      openingTr: "Gittikçe soğuyor — geri mi dönelim yoksa devam mı edelim?",
      goal: "Havadaki değişim karşılaştırmalarla anlatılmış ve ortak bir karar verilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-tiere-natur",
    icon: "dog",
    level: "B1",
    course: "de",
    title: "Tiere um uns",
    titleTr: "Çevremizdeki hayvanlar",
    summary: "Bir canlıyı yönelme hâlli ilgi cümleleriyle tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Dativ",
    vocab: [
      { de: "das Gift", tr: "zehir" },
      { de: "giftig", tr: "zehirli" },
      { de: "fressen", tr: "yem yemek" },
      { de: "die Schlange", tr: "yılan" },
      { de: "ernähren", tr: "beslemek" },
      { de: "die Biologie", tr: "biyoloji" },
      { de: "künstlich", tr: "yapay" },
      { de: "entdecken", tr: "keşfetmek" },
    ],
    patterns: [
      { de: "das Tier, dem wir …", tr: "yönelme isteyen fiillerde ilgi zamiri" },
      { de: "sich ernähren von + Dativ", tr: "neyle beslendiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün hayvanları tanımlayacağız. Yönelme isteyen fiillerde ilgi zamiri de biçim değiştirir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yardım etmek, vermek, güvenmek gibi fiiller yönelme hâli ister; ilgi zamiri de o hâle girer. Önce kelimeler.")] },
      word("İlk", { de: "das Gift", tr: "zehir" }),
      word("İkinci", { de: "giftig", tr: "zehirli" }),
      word("Üçüncü", { de: "fressen", tr: "yem yemek" }, "hayvanlar için kullanılır"),
      word("Dördüncü", { de: "die Schlange", tr: "yılan" }, "aynı sözcük 'kuyruk' anlamına da gelir"),
      word("Beşinci", { de: "ernähren", tr: "beslemek" }),
      word("Altıncı", { de: "die Biologie", tr: "biyoloji" }),
      word("Yedinci", { de: "künstlich", tr: "yapay" }),
      word("Son", { de: "entdecken", tr: "keşfetmek" }),
      { say: [tr("İlk kalıbımız hayvanı tanımlıyor. Vermek fiili yönelme hâli istediği için ilgi zamiri de yönelme hâlinde.")] },
      { say: [tr("Örnek:"), de("Das ist das Tier, dem wir jeden Tag Wasser geben."), tr("Tekrar edin:"), de("Das ist das Tier, dem wir jeden Tag Wasser geben")], expect: repeat("Das ist das Tier, dem wir jeden Tag Wasser geben") },
      { say: [tr("Sıra sende: 'Bu, yem verdiğimiz kuş.'")], expect: produce("Das ist der Vogel, dem wir Futter geben", [tr("Eril adda yönelme hâlli ilgi zamiri nötrle aynı biçimi alır:"), de("Das ist der Vogel, dem wir Futter geben."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız beslenmeyi anlatıyor: dönüşlü fiil ve sabit edat. Edat yönelme hâli istiyor.")] },
      { say: [tr("Şimdi: 'Bu hayvan böceklerle besleniyor.'")], expect: produce("Dieses Tier ernährt sich von Insekten", [tr("Dönüşlü zamir fiilden sonra, edat yönelme hâli istiyor:"), de("Dieses Tier ernährt sich von Insekten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist die Schlange, die ich Angst habe."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist die Schlange, die ich Angst habe.", false, [tr("Korkmak edatlı kurulur ve o edat ilgi zamirinin önüne gelip hâlini belirler:"), de("Das ist die Schlange, vor der ich Angst habe.")]) },
      { say: [tr("Son: 'Bilim insanları zehirli olmayan yeni bir tür keşfetti.'")], expect: produce("Forscher haben eine neue Art entdeckt, die nicht giftig ist", [tr("Yardımcı fiil ikinci sırada, ilgi cümlesi sonda:"), de("Forscher haben eine neue Art entdeckt, die nicht giftig ist."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir hayvanı tarif edeceksin.")] },
    ],
    roleplay: {
      scene: "Bir doğa parkındasın ve gördüğün hayvanları arkadaşına tarif ediyorsun: hangisi neyle besleniyor, hangisi tehlikeli.",
      partner: "hayvanlardan biraz çekinen ama merak eden bir arkadaş",
      opening: "Was ist das denn da hinten? Ist das gefährlich?",
      openingTr: "Arkadaki de ne? Tehlikeli mi?",
      goal: "En az iki hayvan ilgi cümlesiyle tanımlanmış ve neyle beslendikleri söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-freizeit-planen",
    icon: "calendar",
    level: "B1",
    course: "de",
    title: "Was machen wir am Wochenende?",
    titleTr: "Hafta sonu planı",
    summary: "Plan yaparken kibar öneri ve rica kalıplarını dilek kipiyle öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "sich verabreden", tr: "sözleşmek" },
      { de: "verabredet", tr: "sözleşmiş" },
      { de: "jederzeit", tr: "her an" },
      { de: "gratis", tr: "ücretsiz" },
      { de: "inklusive", tr: "dâhil" },
      { de: "einschließlich", tr: "dâhil olmak üzere" },
      { de: "maximal", tr: "en fazla" },
      { de: "durchschnittlich", tr: "ortalama olarak" },
    ],
    patterns: [
      { de: "Wir könnten …", tr: "kibar bir öneri sunar" },
      { de: "Hättest du Lust, … zu …?", tr: "isteyip istemediğini sorar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Hafta sonu planı yapacaksınız. Almancada öneri dilek kipiyle sunulur; böylece karşındaki rahatça hayır diyebilir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu bir nezaket biçimi değil sadece; öneriyi bağlayıcı olmaktan çıkarıyor. Önce kelimeler.")] },
      word("İlk", { de: "sich verabreden", tr: "sözleşmek" }),
      word("İkinci", { de: "verabredet", tr: "sözleşmiş" }),
      word("Üçüncü", { de: "jederzeit", tr: "her an" }),
      word("Dördüncü", { de: "gratis", tr: "ücretsiz" }),
      word("Beşinci", { de: "inklusive", tr: "dâhil" }),
      word("Altıncı", { de: "einschließlich", tr: "dâhil olmak üzere" }),
      word("Yedinci", { de: "maximal", tr: "en fazla" }),
      word("Son", { de: "durchschnittlich", tr: "ortalama olarak" }),
      { say: [tr("İlk kalıbımız öneri sunuyor: yapabilmek fiilinin dilek kipi. Emir gibi durmuyor, kapı açık bırakıyor.")] },
      { say: [tr("Örnek:"), de("Wir könnten am Samstag ins Museum gehen."), tr("Tekrar edin:"), de("Wir könnten am Samstag ins Museum gehen")], expect: repeat("Wir könnten am Samstag ins Museum gehen") },
      { say: [tr("Sıra sende: 'Pazar günü sözleşebiliriz.'")], expect: produce("Wir könnten uns am Sonntag verabreden", [tr("Dönüşlü zamir fiilden sonra, mastar sonda:"), de("Wir könnten uns am Sonntag verabreden."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız isteyip istemediğini soruyor: sahip olmak fiilinin dilek kipi ve mastar öbeği.")] },
      { say: [tr("Şimdi: 'Yüzmeye gitmek ister miydin?'")], expect: produce("Hättest du Lust, schwimmen zu gehen", [tr("Dilek kipi başta, mastar öbeği virgülden sonra:"), de("Hättest du Lust, schwimmen zu gehen?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wir könnten gehen ins Kino am Freitag."), tr("cümlesi doğru mu?")], expect: truefalse("Wir könnten gehen ins Kino am Freitag.", false, [tr("Modal fiil ikinci sırada, mastar cümlenin en sonunda kalır:"), de("Wir könnten am Freitag ins Kino gehen.")]) },
      { say: [tr("Son: 'Giriş ücretsiz, içecek de dâhil.'")], expect: produce("Der Eintritt ist gratis, Getränke inklusive", [tr("İki bölüm, ikincisinde fiil söylenmiyor:"), de("Der Eintritt ist gratis, Getränke inklusive."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir arkadaşınla hafta sonunu planlayacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla hafta sonunu planlıyorsunuz: ne yapacaksınız, ne zaman, ne kadara. Önerileri kibar biçimde sunuyorsun.",
      partner: "her öneriye bir itirazı olan ama sonunda razı olan bir arkadaş",
      opening: "Also, Wochenende — hast du schon was vor?",
      openingTr: "Peki, hafta sonu — bir planın var mı?",
      goal: "En az üç öneri sunulmuş, biri kararlaştırılmış ve saat ile yer belirlenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-b1-abschluss",
    icon: "star",
    level: "B1",
    course: "de",
    title: "Das war B1",
    titleTr: "B1'in sonu",
    summary: "Geçilen yolu değerlendirmeyi ve sıradaki adımı ikili bağlaçlarla anlatmayı öğretir.",
    minutes: 12,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "optimistisch", tr: "iyimser" },
      { de: "realistisch", tr: "gerçekçi" },
      { de: "zurechtkommen", tr: "başa çıkmak" },
      { de: "erfüllen", tr: "yerine getirmek" },
      { de: "endgültig", tr: "kesin olarak" },
      { de: "nochmals", tr: "bir kez daha" },
      { de: "gleichfalls", tr: "size de" },
      { de: "Prost", tr: "şerefe" },
    ],
    patterns: [
      { de: "sowohl … als auch …", tr: "iki şeyi birden kapsar" },
      { de: "nicht nur …, sondern auch …", tr: "ikincisini öne çıkararak ekler" },
    ],
    lecture: [
      { say: [tr("Merhaba! B1'in son dersindesin. Bugün yeni bir kural yok; bugün geçtiğin yolu kendi cümlelerinle değerlendireceksin. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Değerlendirme dengeli olmalı: neyi başardın ve neyi başaramadın. İkili bağlaçlar tam bunun için var. Önce son kelimelerimiz.")] },
      word("İlk", { de: "optimistisch", tr: "iyimser" }),
      word("İkinci", { de: "realistisch", tr: "gerçekçi" }),
      word("Üçüncü", { de: "zurechtkommen", tr: "başa çıkmak" }),
      word("Dördüncü", { de: "erfüllen", tr: "yerine getirmek" }),
      word("Beşinci", { de: "endgültig", tr: "kesin olarak" }),
      word("Altıncı", { de: "nochmals", tr: "bir kez daha" }),
      word("Yedinci", { de: "gleichfalls", tr: "size de" }, "iyi dileğe karşılık verirken"),
      word("Son", { de: "Prost", tr: "şerefe" }),
      { say: [tr("İlk kalıbımız iki şeyi birden kapsıyor. İkinci parçası sabittir ve söylenmek zorundadır.")] },
      { say: [tr("Örnek:"), de("Ich komme sowohl im Alltag als auch im Beruf zurecht."), tr("Tekrar edin:"), de("Ich komme sowohl im Alltag als auch im Beruf zurecht")], expect: repeat("Ich komme sowohl im Alltag als auch im Beruf zurecht") },
      { say: [tr("Sıra sende: 'Hem iyimser hem gerçekçiyim.'")], expect: produce("Ich bin sowohl optimistisch als auch realistisch", [tr("İkili bağlacın iki parçası da söylenmeli:"), de("Ich bin sowohl optimistisch als auch realistisch."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız ikinciyi öne çıkarıyor. Bir başarıyı anlatırken en doğal biçim budur.")] },
      { say: [tr("Şimdi: 'Sadece kelime öğrenmedim, aynı zamanda konuşmayı da öğrendim.'")], expect: produce("Ich habe nicht nur Wörter gelernt, sondern auch sprechen gelernt", [tr("İkinci parça sabit, ortaç iki bölümde de sonda:"), de("Ich habe nicht nur Wörter gelernt, sondern auch sprechen gelernt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich habe sowohl gelernt als auch vergessen viel."), tr("cümlesi doğru mu?")], expect: truefalse("Ich habe sowohl gelernt als auch vergessen viel.", false, [tr("Nesne ortaçtan önce gelir, cümlenin sonuna atılmaz:"), de("Ich habe sowohl viel gelernt als auch viel vergessen.")]) },
      { say: [tr("Son cümlen: 'Hedefimi yerine getirdim ve bir kez daha başlıyorum.'")], expect: produce("Ich habe mein Ziel erfüllt und fange nochmals an", [tr("İki ana cümle bağlaçla, ikincisinde ayrılabilen fiilin öneki sonda:"), de("Ich habe mein Ziel erfüllt und fange nochmals an."), tr("Tekrar dene.")]) },
      { say: [tr("B1 bitti. Şimdi öğretmeninle son bir konuşma yapacaksın: yol nasıl geçti, neyi başardın, sırada ne var.")] },
    ],
    roleplay: {
      scene: "B1'i bitirdin. Öğretmeninle son bir değerlendirme yapıyorsun: neyi başardın, neyi hâlâ zor buluyorsun, bundan sonra ne yapacaksın.",
      partner: "seni yüz seksen ders boyunca izlemiş, gurur duyan bir öğretmen",
      opening: "Das war die letzte Stunde auf B1. Sagen Sie mir ehrlich — was können Sie heute, was Sie am Anfang nicht konnten?",
      openingTr: "Bu B1'in son dersiydi. Bana dürüstçe söyleyin — bugün başlangıçta yapamadığınız neyi yapabiliyorsunuz?",
      goal: "Kazanımlar ve kalan zorluklar dengeli biçimde söylenmiş ve bir sonraki hedef belirlenmiş olur.",
      minTurns: 9,
    },
  },
];
