import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 3 — Edilgenin bütün hâlleri (021–030).
 *
 * B1'de edilgenin iki zamanı öğrenilmişti. Bu modül onu bir SİSTEME
 * çeviriyor: geçmiş (ist … worden), kipli (muss … werden), durum (ist
 * geöffnet) ve edilgen yerine geçen üç yapı (lässt sich …, ist zu …, -bar).
 *
 * Türkçe konuşan için asıl ayrım şu ikisi arasında: "kapı açılıyor" bir
 * SÜREÇ, "kapı açık" bir DURUM. Türkçede ikisi de edilgen ekle kurulabilir,
 * Almancada iki ayrı yapıdır ve karıştırmak anlamı değiştirir. Bu yüzden
 * modülün ortasında ikisini karşı karşıya koyan bir ders var.
 *
 * Sahneler bilerek dağınık: şantiye, mutfak, kaza raporu, restorasyon, bakım
 * randevusu. Edilgen tek bir alanın dili değil, failin önemsizleştiği HER
 * alanın dili.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B03: Lesson[] = [
  {
    id: "de-b2-passiv-perfekt",
    icon: "office",
    level: "B2",
    course: "de",
    title: "Es ist erledigt worden",
    titleTr: "Edilgen Perfekt",
    summary: "Tamamlanmış işleri edilgen Perfekt ile bildirmeyi öğretir.",
    minutes: 11,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "erledigen", tr: "halletmek" },
      { de: "der Auftrag", tr: "iş emri, sipariş" },
      { de: "bearbeiten", tr: "işleme almak" },
      { de: "abschließen", tr: "tamamlamak" },
      { de: "bislang", tr: "şimdiye kadar" },
    ],
    patterns: [
      { de: "… ist … worden", tr: "tekil: yapılmış oldu" },
      { de: "… sind … worden", tr: "çoğul: yapılmış oldular" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül ve konusu tek bir yapı değil, bütün bir sistem: edilgen. Bugün en çok işine yarayacak hâliyle başlıyoruz — bitmiş işleri bildirmek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şu: sein yardımcı fiili, ortaç, sonra kısalmış biçim. Uzun biçim 'geworden' burada kullanılmaz ve bu, seviyenin en görünür işaretlerinden biri. Önce kelimeler.")] },
      word("İlk", { de: "erledigen", tr: "halletmek" }),
      word("İkinci", { de: "der Auftrag", tr: "iş emri, sipariş" }),
      word("Üçüncü", { de: "bearbeiten", tr: "işleme almak" }),
      word("Dördüncü", { de: "abschließen", tr: "tamamlamak" }),
      word("Son", { de: "bislang", tr: "şimdiye kadar" }),
      { say: [tr("Kalıbımız:"), de("… ist … worden"), tr("Çoğulda tek değişen yardımcı fiil oluyor: sind.")] },
      { say: [tr("Örnek:"), de("Der Auftrag ist gestern bearbeitet worden."), tr("Tekrar edin:"), de("Der Auftrag ist gestern bearbeitet worden")], expect: repeat("Der Auftrag ist gestern bearbeitet worden") },
      { say: [tr("Sıra sende: 'Sipariş şimdiye kadar işleme alınmadı.'")], expect: produce("Der Auftrag ist bislang nicht bearbeitet worden", [tr("Olumsuzluk ortaçtan önce, kısalmış biçim en sonda:"), de("Der Auftrag ist bislang nicht bearbeitet worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Proje geçen ay tamamlandı.'")], expect: produce("Das Projekt ist letzten Monat abgeschlossen worden", [tr("Ayrılabilen fiilin ortacı ge- ekini ortada alır:"), de("Das Projekt ist letzten Monat abgeschlossen worden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, çoğulla: 'Bugüne kadar üç başvuru işleme alındı.'")], expect: produce("Bis heute sind drei Anträge bearbeitet worden", [tr("Çoğul özne sind ister:"), de("Bis heute sind drei Anträge bearbeitet worden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Bis heute sind drei Anträge bearbeitet worden."), tr("cümlesi doğru mu?")], expect: truefalse("Bis heute sind drei Anträge bearbeitet worden.", true, [tr("Doğru. Çoğul özne sind alıyor, ortaç ortada ve kısalmış biçim sonda.")]) },
      { say: [tr("Son: 'Her şey halledildi.'")], expect: produce("Alles ist erledigt worden", [tr("Kısa ama tam bir edilgen geçmiş:"), de("Alles ist erledigt worden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada şefine haftanın durumunu bildireceksin: ne yapıldı, ne yapılmadı, sebebi ne.")] },
    ],
    roleplay: {
      scene: "Şefinle haftalık durum görüşmesindesin. Hangi işlerin tamamlandığını, hangilerinin hâlâ beklediğini ve sebebini edilgen geçmişle bildir; kalanlar için tarih ver.",
      partner: "kısa cevap isteyen, tarih soran bir bölüm şefi",
      opening: "Ich habe wenig Zeit — sagen Sie mir kurz: Was ist diese Woche erledigt worden und was nicht?",
      openingTr: "Vaktim az — kısaca söyleyin: Bu hafta ne halledildi, ne halledilmedi?",
      goal: "Biten ve bitmeyen işler sayılmış, gecikmenin sebebi söylenmiş ve kalanlar için tarih verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-passiv-modal",
    icon: "law",
    level: "B2",
    course: "de",
    title: "Das muss geprüft werden",
    titleTr: "Kipli edilgen",
    summary: "Zorunluluk ve imkânı edilgen yapıyla bildirmeyi öğretir.",
    minutes: 11,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "prüfen", tr: "incelemek" },
      { de: "bedenken", tr: "göz önünde bulundurmak" },
      { de: "genehmigen", tr: "onaylamak" },
      { de: "die Vorschrift", tr: "yönetmelik" },
      { de: "einreichen", tr: "sunmak, teslim etmek" },
    ],
    patterns: [
      { de: "muss/kann/soll … werden", tr: "kipli edilgen" },
      { de: "Das sollte bedacht werden.", tr: "kişisiz uyarı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün edilgene bir kip ekliyoruz. Resmî yazışmanın en sık cümlesi bu: 'incelenmeli', 'sunulabilir', 'değiştirilemez'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yapı basit ama sırası kritik: çekimli kip fiili ikinci sırada, sonda önce ortaç sonra werden. Bu iki kelimenin sırası çok karıştırılır. Önce kelimeler.")] },
      word("İlk", { de: "prüfen", tr: "incelemek" }),
      word("İkinci", { de: "bedenken", tr: "göz önünde bulundurmak" }),
      word("Üçüncü", { de: "genehmigen", tr: "onaylamak" }),
      word("Dördüncü", { de: "die Vorschrift", tr: "yönetmelik" }),
      word("Son", { de: "einreichen", tr: "sunmak, teslim etmek" }),
      { say: [tr("Kalıbımız:"), de("muss … geprüft werden"), tr("Sondaki iki kelime her zaman bu sırada: önce ortaç, sonra werden.")] },
      { say: [tr("Örnek:"), de("Der Antrag muss bis Freitag geprüft werden."), tr("Tekrar edin:"), de("Der Antrag muss bis Freitag geprüft werden")], expect: repeat("Der Antrag muss bis Freitag geprüft werden") },
      { say: [tr("Sıra sende: 'Belgeler çevrimiçi sunulabilir.'")], expect: produce("Die Unterlagen können online eingereicht werden", [tr("Çoğul kip fiili, sonda ortaç ve werden:"), de("Die Unterlagen können online eingereicht werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu göz önünde bulundurulmalı.'")], expect: produce("Das sollte bedacht werden", [tr("Kısa ve kişisiz bir uyarı cümlesi:"), de("Das sollte bedacht werden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, olumsuzla: 'Yönetmelik değiştirilemez.'")], expect: produce("Die Vorschrift kann nicht geändert werden", [tr("Olumsuzluk ortaçtan önce gelir:"), de("Die Vorschrift kann nicht geändert werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Unterlagen können online eingereicht sein."), tr("cümlesi doğru mu?")], expect: truefalse("Die Unterlagen können online eingereicht sein.", false, [tr("Kipli edilgende sonda sein değil werden bulunur:"), de("Die Unterlagen können online eingereicht werden.")]) },
      { say: [tr("Son: 'Başvurunun onaylanması gerekiyor.'")], expect: produce("Der Antrag muss genehmigt werden", [tr("Zorunluluk müssen ile, sonda ortaç ve werden:"), de("Der Antrag muss genehmigt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kurumda başvurunun hangi adımlardan geçmesi gerektiğini soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir kurumun danışma masasındasın ve başvurunun hangi adımlardan geçmesi gerektiğini soruyorsun: ne sunulmalı, ne incelenecek, ne kadar sürer, hangi belge onaylanmalı.",
      partner: "kuralları yönetmelik diliyle anlatan bir memur",
      opening: "Ihr Antrag liegt bei uns. Bevor er bearbeitet werden kann, muss allerdings noch etwas geklärt werden — wissen Sie, was fehlt?",
      openingTr: "Başvurunuz bizde. Ancak işleme alınabilmesi için bir şeyin netleşmesi gerekiyor — neyin eksik olduğunu biliyor musunuz?",
      goal: "Eksik belge öğrenilmiş, adımların sırası ve süresi netleşmiş ve ne zaman sonuç alınacağı söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-zustandspassiv",
    icon: "key",
    level: "B2",
    course: "de",
    title: "Die Tür ist geöffnet",
    titleTr: "Süreç mi, durum mu?",
    summary: "Süreç edilgeni ile durum edilgenini ayırt etmeyi öğretir.",
    minutes: 11,
    focusId: "Zustandspassiv",
    vocab: [
      { de: "der Vorgang", tr: "süreç, işlem" },
      { de: "der Zustand", tr: "durum" },
      { de: "verschlossen", tr: "kilitli" },
      { de: "gekippt", tr: "aralık (pencere)" },
      { de: "dauerhaft", tr: "kalıcı olarak" },
    ],
    patterns: [
      { de: "wird geöffnet", tr: "süreç: açılıyor" },
      { de: "ist geöffnet", tr: "durum: açık" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü ders küçük bir kelimeye bakıyor ama anlamı tamamen değiştiriyor. Türkçede 'kapı açılıyor' ve 'kapı açık' apayrı şeyler; Almanca bunu iki ayrı edilgenle ayırır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural: werden ile kurulan edilgen SÜREÇTİR — bir şey oluyor. sein ile kurulan edilgen DURUMDUR — bir şey olmuş ve öyle duruyor. Önce kelimeler.")] },
      word("İlk", { de: "der Vorgang", tr: "süreç, işlem" }),
      word("İkinci", { de: "der Zustand", tr: "durum" }),
      word("Üçüncü", { de: "verschlossen", tr: "kilitli" }),
      word("Dördüncü", { de: "gekippt", tr: "aralık (pencere)" }),
      word("Son", { de: "dauerhaft", tr: "kalıcı olarak" }),
      { say: [tr("Kalıbımız iki cümle:"), de("Die Tür wird geöffnet."), tr("süreç;"), de("Die Tür ist geöffnet."), tr("durum.")] },
      { say: [tr("Tekrar edin:"), de("Die Tür wird geöffnet, und danach ist sie geöffnet")], expect: repeat("Die Tür wird geöffnet, und danach ist sie geöffnet") },
      { say: [tr("Sıra sende, süreci söyle: 'Mağaza saat altıda kapatılıyor.'")], expect: produce("Der Laden wird um sechs geschlossen", [tr("Bir şeyin olması werden ile:"), de("Der Laden wird um sechs geschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi durumu söyle: 'Mağaza pazar günleri kapalı.'")], expect: produce("Der Laden ist sonntags geschlossen", [tr("Var olan hâl sein ile:"), de("Der Laden ist sonntags geschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Pencere aralık.'")], expect: produce("Das Fenster ist gekippt", [tr("Bu bir durum, süreç değil:"), de("Das Fenster ist gekippt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Fenster wird seit einer Stunde gekippt."), tr("cümlesi doğru mu?")], expect: truefalse("Das Fenster wird seit einer Stunde gekippt.", false, [tr("Bir saattir süren şey bir durumdur, süreç değil:"), de("Das Fenster ist seit einer Stunde gekippt.")]) },
      { say: [tr("Son: 'Arka kapı kalıcı olarak kilitli.'")], expect: produce("Die hintere Tür ist dauerhaft verschlossen", [tr("Sıfat gibi duran ortaç, sein ile:"), de("Die hintere Tür ist dauerhaft verschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir bina görevlisiyle konuşacaksın: ne zaman ne açılıyor, şu an ne açık.")] },
    ],
    roleplay: {
      scene: "Bir binanın görevlisiyle konuşuyorsun: hangi kapı ne zaman açılıyor, şu an neresi açık, hangi giriş kalıcı olarak kapalı. Süreç ile durumu ayırarak sor ve anlat.",
      partner: "kuralları ezbere bilen, kısa konuşan bir bina görevlisi",
      opening: "Sie stehen vor der falschen Tür — der Haupteingang ist heute geschlossen. Wohin wollen Sie denn?",
      openingTr: "Yanlış kapıdasınız — ana giriş bugün kapalı. Nereye gitmek istiyorsunuz?",
      goal: "Hangi girişin açık, hangisinin kapalı olduğu ve kapıların ne zaman açıldığı öğrenilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-passiversatz-lassen",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Das lässt sich machen",
    titleTr: "Edilgen yerine geçenler",
    summary: "lassen + sich, sein + zu ve -bar sıfatlarını ayırt etmeyi öğretir.",
    minutes: 11,
    focusId: "Passiversatz",
    vocab: [
      { de: "machbar", tr: "yapılabilir" },
      { de: "umsetzbar", tr: "uygulanabilir" },
      { de: "die Umsetzung", tr: "uygulama" },
      { de: "vermeidbar", tr: "kaçınılabilir" },
      { de: "nachweisen", tr: "kanıtlamak" },
    ],
    patterns: [
      { de: "Das lässt sich …", tr: "imkân: yapılabilir" },
      { de: "Das ist zu …", tr: "zorunluluk: yapılmalı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün edilgenin üç kısayolunu bir araya getiriyoruz. Üçü de edilgen anlamı taşır ama üçü farklı şey söyler ve karıştırmak cümleyi bozar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Birincisi imkân söyler, ikincisi zorunluluk, üçüncüsü de sıfat gibi durup nitelik söyler. Aynı cümlede ikisini birden kullanmak sık yapılan bir hata. Önce kelimeler.")] },
      word("İlk", { de: "machbar", tr: "yapılabilir" }),
      word("İkinci", { de: "umsetzbar", tr: "uygulanabilir" }),
      word("Üçüncü", { de: "die Umsetzung", tr: "uygulama" }),
      word("Dördüncü", { de: "vermeidbar", tr: "kaçınılabilir" }),
      word("Son", { de: "nachweisen", tr: "kanıtlamak" }),
      { say: [tr("Kalıbımız:"), de("Das lässt sich umsetzen."), tr("Yani 'bu uygulanabilir'. lassen artı dönüşlü zamir artı mastar.")] },
      { say: [tr("Tekrar edin:"), de("Das lässt sich umsetzen")], expect: repeat("Das lässt sich umsetzen") },
      { say: [tr("Sıra sende: 'Uygulama birkaç haftada yapılabilir.'")], expect: produce("Die Umsetzung lässt sich in wenigen Wochen schaffen", [tr("Özne, lassen artı sich, mastar en sonda:"), de("Die Umsetzung lässt sich in wenigen Wochen schaffen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi zorunluluk biçimiyle: 'Bunun kanıtlanması gerekiyor.'")], expect: produce("Das ist nachzuweisen", [tr("sein artı zu artı mastar; ayrılabilen fiilde zu ortaya girer:"), de("Das ist nachzuweisen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, sıfat biçimiyle: 'Bu hata önlenebilir.'")], expect: produce("Dieser Fehler ist vermeidbar", [tr("Fiilden türeyen sıfat, sein ile:"), de("Dieser Fehler ist vermeidbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Fehler lässt sich vermeidbar."), tr("cümlesi doğru mu?")], expect: truefalse("Der Fehler lässt sich vermeidbar.", false, [tr("İki yapı birbirine karışmış; ya biri ya öteki:"), de("Der Fehler lässt sich vermeiden."), tr("ya da"), de("Der Fehler ist vermeidbar.")]) },
      { say: [tr("Son bir soru: 'Öneri uygulanabilir mi?'")], expect: produce("Ist der Vorschlag umsetzbar", [tr("Fiil başta soru; sıfat sonda:"), de("Ist der Vorschlag umsetzbar?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir öneriyi değerlendireceksin: neyin mümkün, neyin zorunlu olduğunu ayır.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın yeni bir çalışma düzeni öneriyor. Önerinin neyinin uygulanabilir olduğunu, neyin zorunlu olarak çözülmesi gerektiğini ve neyin mümkün olmadığını söyleyip ortak bir sonuca varın.",
      partner: "önerisine bağlı ama itiraz dinleyen bir meslektaş",
      opening: "Ich hätte da eine Idee: Wir verlegen die Besprechung auf Montagmorgen. Lässt sich das machen?",
      openingTr: "Bir fikrim var: Toplantıyı pazartesi sabahına alalım. Bu yapılabilir mi?",
      goal: "Önerinin uygulanabilir ve uygulanamaz yanları ayrılmış, çözülmesi gereken nokta söylenmiş ve ortak bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-herstellung",
    icon: "food",
    level: "B2",
    course: "de",
    title: "Wie Schokolade entsteht",
    titleTr: "Üretim süreci",
    summary: "Bir üretim sürecini adım adım edilgenle anlatmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Herstellung", tr: "üretim" },
      { de: "ernten", tr: "hasat etmek" },
      { de: "verarbeiten", tr: "işlemek" },
      { de: "rösten", tr: "kavurmak" },
      { de: "anschließend", tr: "ardından" },
    ],
    patterns: [
      { de: "wird/werden … + Partizip", tr: "süreç anlatımı" },
      { de: "zuerst … anschließend … zum Schluss", tr: "adım sıralaması" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir şeyin nasıl yapıldığını anlatacağız. Böyle anlatımlarda kimin yaptığı hiç söylenmez — önemli olan sıradır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yüzden üretim anlatımı baştan sona edilgendir ve sıra belirteçleriyle bağlanır: önce, ardından, en son. Önce kelimeler.")] },
      word("İlk", { de: "die Herstellung", tr: "üretim" }),
      word("İkinci", { de: "ernten", tr: "hasat etmek" }),
      word("Üçüncü", { de: "verarbeiten", tr: "işlemek" }),
      word("Dördüncü", { de: "rösten", tr: "kavurmak" }),
      word("Son", { de: "anschließend", tr: "ardından" }),
      { say: [tr("Kalıbımız:"), de("wird / werden + Partizip"), tr("Şimdiki zaman edilgeni; çoğul öznede werden.")] },
      { say: [tr("Örnek:"), de("Die Bohnen werden zuerst geerntet."), tr("Tekrar edin:"), de("Die Bohnen werden zuerst geerntet")], expect: repeat("Die Bohnen werden zuerst geerntet") },
      { say: [tr("Sıra sende: 'Ardından çekirdekler kavruluyor.'")], expect: produce("Anschließend werden die Bohnen geröstet", [tr("Zarf başta olunca fiil ikinci sıraya geçer:"), de("Anschließend werden die Bohnen geröstet."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kakao birkaç adımda işleniyor.'")], expect: produce("Der Kakao wird in mehreren Schritten verarbeitet", [tr("Tekil özne wird alır, ortaç sonda:"), de("Der Kakao wird in mehreren Schritten verarbeitet."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kütle uzun süre karıştırılıyor.'")], expect: produce("Die Masse wird lange gerührt", [tr("Kısa ve düz bir edilgen:"), de("Die Masse wird lange gerührt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Anschließend werden die Bohnen geröstet."), tr("cümlesi doğru mu?")], expect: truefalse("Anschließend werden die Bohnen geröstet.", true, [tr("Doğru. Zarf başta, çekimli fiil ikinci sırada, ortaç en sonda.")]) },
      { say: [tr("Son bir soru: 'Üretim nasıl işliyor?'")], expect: produce("Wie läuft die Herstellung ab", [tr("Ayrılabilen fiilin öneki sonda:"), de("Wie läuft die Herstellung ab?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir fabrika turunda rehbere üretimin adımlarını soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir çikolata fabrikasının turundasın. Üretimin adımlarını sırayla sor, bir adımı kendi cümlenle özetle ve merak ettiğin bir ayrıntıyı sor.",
      partner: "işini seven, ayrıntı vermeyi seven bir fabrika rehberi",
      opening: "Willkommen! Wir stehen hier ganz am Anfang der Produktion. Wissen Sie schon, wie Kakao überhaupt zu uns kommt?",
      openingTr: "Hoş geldiniz! Şu an üretimin en başındayız. Kakaonun bize nasıl geldiğini biliyor musunuz?",
      goal: "Üretimin adımları sırayla öğrenilmiş, bir adım öğrenci tarafından özetlenmiş ve merak edilen bir ayrıntı cevaplanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-restaurierung",
    icon: "city",
    level: "B2",
    course: "de",
    title: "Die Altstadt wird saniert",
    titleTr: "Restorasyon",
    summary: "Yapılmış onarım işlerini edilgen geçmişle anlatmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "sanieren", tr: "yenilemek, restore etmek" },
      { de: "der Denkmalschutz", tr: "koruma statüsü" },
      { de: "originalgetreu", tr: "aslına uygun" },
      { de: "die Fassade", tr: "cephe" },
      { de: "erhalten", tr: "korumak, muhafaza etmek" },
    ],
    patterns: [
      { de: "ist … saniert worden", tr: "yapılmış onarım" },
      { de: "steht unter Denkmalschutz", tr: "koruma statüsü" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün eski bir şehir merkezindeyiz. Bu konunun dili tamamen edilgen geçmiş: kimin onardığı değil, neyin onarılmış olduğu konuşulur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de ince bir ayrım var: zaman belirtilmişse süreç anlatılıyordur ve kısalmış biçim gerekir. Bunu dersin sonunda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "sanieren", tr: "yenilemek, restore etmek" }),
      word("İkinci", { de: "der Denkmalschutz", tr: "koruma statüsü" }),
      word("Üçüncü", { de: "originalgetreu", tr: "aslına uygun" }),
      word("Dördüncü", { de: "die Fassade", tr: "cephe" }),
      word("Son", { de: "erhalten", tr: "korumak, muhafaza etmek" }),
      { say: [tr("Kalıbımız:"), de("ist … saniert worden"), tr("Tamamlanmış bir onarım süreci.")] },
      { say: [tr("Örnek:"), de("Die Altstadt ist in den letzten Jahren saniert worden."), tr("Tekrar edin:"), de("Die Altstadt ist in den letzten Jahren saniert worden")], expect: repeat("Die Altstadt ist in den letzten Jahren saniert worden") },
      { say: [tr("Sıra sende: 'Cephe aslına uygun onarıldı.'")], expect: produce("Die Fassade ist originalgetreu restauriert worden", [tr("Zarf ortaçtan önce, kısalmış biçim sonda:"), de("Die Fassade ist originalgetreu restauriert worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bina koruma altında.'")], expect: produce("Das Gebäude steht unter Denkmalschutz", [tr("Kalıplaşmış ifade; stehen fiiliyle:"), de("Das Gebäude steht unter Denkmalschutz."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Eski pencereler korunabildi.'")], expect: produce("Die alten Fenster konnten erhalten werden", [tr("Kipli edilgenin geçmişi; sonda ortaç ve werden:"), de("Die alten Fenster konnten erhalten werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Fassade ist letztes Jahr originalgetreu restauriert."), tr("cümlesi doğru mu?")], expect: truefalse("Die Fassade ist letztes Jahr originalgetreu restauriert.", false, [tr("Zaman belirtildiğine göre anlatılan bir süreçtir, o yüzden kısalmış biçim gerekir:"), de("Die Fassade ist letztes Jahr originalgetreu restauriert worden.")]) },
      { say: [tr("Son: 'Çalışmalar geçen yıl tamamlandı.'")], expect: produce("Die Arbeiten sind letztes Jahr abgeschlossen worden", [tr("Çoğul özne sind alır:"), de("Die Arbeiten sind letztes Jahr abgeschlossen worden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir şehir turunda rehbere yenilenen binaları soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir şehir turundasın ve rehbere eski merkezin nasıl yenilendiğini soruyorsun: ne onarıldı, ne korunabildi, hangi bina koruma altında, çalışmalar ne zaman bitti.",
      partner: "şehrin tarihini seven, ayrıntı veren bir şehir rehberi",
      opening: "Von hier aus sieht man es am besten: Diese Häuserzeile ist vor drei Jahren komplett saniert worden. Fällt Ihnen etwas auf?",
      openingTr: "Buradan en iyi görünüyor: Bu sıra evler üç yıl önce tamamen yenilendi. Dikkatinizi çeken bir şey var mı?",
      goal: "Neyin onarıldığı, neyin korunduğu ve çalışmaların ne zaman bittiği öğrenilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-unfallbericht",
    icon: "car",
    level: "B2",
    course: "de",
    title: "Der Unfallbericht",
    titleTr: "Kaza raporu",
    summary: "Olayı resmî rapor diliyle, edilgen geçmiş zamanda anlatmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "der Zeuge", tr: "tanık" },
      { de: "verständigen", tr: "haber vermek" },
      { de: "der Rettungswagen", tr: "ambulans" },
      { de: "die Fahrbahn", tr: "yol, şerit" },
      { de: "sperren", tr: "kapatmak (yolu)" },
    ],
    patterns: [
      { de: "wurde … + Partizip", tr: "raporun edilgen geçmişi" },
      { de: "Zeugen werden gesucht.", tr: "resmî çağrı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün resmî rapor dili öğreneceğiz. Polis ve basın raporlarında edilgenin geçmiş zaman hâli kullanılır — konuşurken duyduğun hâlden farklı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Konuşmada 'ist gerufen worden' dersin, raporda 'wurde gerufen' yazar. İkisi de doğru ama tür farklıdır ve rapor okuyabilmek B2'nin işlerinden. Önce kelimeler.")] },
      word("İlk", { de: "der Zeuge", tr: "tanık" }),
      word("İkinci", { de: "verständigen", tr: "haber vermek" }),
      word("Üçüncü", { de: "der Rettungswagen", tr: "ambulans" }),
      word("Dördüncü", { de: "die Fahrbahn", tr: "yol, şerit" }),
      word("Son", { de: "sperren", tr: "kapatmak (yolu)" }),
      { say: [tr("Kalıbımız:"), de("wurde + Partizip"), tr("Çoğulda wurden. Rapor cümleleri neredeyse hep böyle kurulur.")] },
      { say: [tr("Örnek:"), de("Der Rettungswagen wurde sofort verständigt."), tr("Tekrar edin:"), de("Der Rettungswagen wurde sofort verständigt")], expect: repeat("Der Rettungswagen wurde sofort verständigt") },
      { say: [tr("Sıra sende: 'Sürücü hastaneye götürüldü.'")], expect: produce("Der Fahrer wurde ins Krankenhaus gebracht", [tr("Edilgen geçmiş; yön bildiren edat belirtme hâliyle:"), de("Der Fahrer wurde ins Krankenhaus gebracht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yol iki saat kapatıldı.'")], expect: produce("Die Fahrbahn wurde zwei Stunden gesperrt", [tr("Süre ortaçtan önce:"), de("Die Fahrbahn wurde zwei Stunden gesperrt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, şimdiki zamanda: 'Tanıklar aranıyor.'")], expect: produce("Zeugen werden gesucht", [tr("Belirteçsiz çoğul özne, şimdiki zaman edilgeni:"), de("Zeugen werden gesucht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Fahrer wurde ins Krankenhaus gebracht worden."), tr("cümlesi doğru mu?")], expect: truefalse("Der Fahrer wurde ins Krankenhaus gebracht worden.", false, [tr("İki edilgen zaman üst üste binmiş; biri seçilmeli:"), de("Der Fahrer wurde ins Krankenhaus gebracht.")]) },
      { say: [tr("Son: 'Kaza saat yedide bildirildi.'")], expect: produce("Der Unfall wurde um sieben gemeldet", [tr("Saat ortaçtan önce:"), de("Der Unfall wurde um sieben gemeldet."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir polis memuruna tanık olduğun kazayı anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir kazaya tanık oldun ve polis memuruna ifade veriyorsun: ne gördün, hangi sırayla oldu, kim haber verdi, sonra ne oldu. Olayları sırayla ve nesnel anlat.",
      partner: "not tutan, tarih ve saat soran bir polis memuru",
      opening: "Sie haben den Unfall gesehen? Dann fangen wir von vorne an: Was genau ist als Erstes passiert?",
      openingTr: "Kazayı gördünüz mü? O hâlde baştan başlayalım: İlk olarak tam olarak ne oldu?",
      goal: "Olaylar sırayla anlatılmış, kimin ne yaptığı söylenmiş ve ifadenin sonunda iletişim bilgisi verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-rezept-profi",
    icon: "food",
    level: "B2",
    course: "de",
    title: "Perfekt gegart",
    titleTr: "Profesyonel mutfak",
    summary: "Mutfak talimatlarını kipli edilgenle vermeyi öğretir.",
    minutes: 11,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "garen", tr: "pişirmek" },
      { de: "abschmecken", tr: "tadını ayarlamak" },
      { de: "der Teig", tr: "hamur" },
      { de: "köcheln", tr: "kısık ateşte kaynamak" },
      { de: "die Konsistenz", tr: "kıvam" },
    ],
    patterns: [
      { de: "muss … gegart werden", tr: "mutfak zorunluluğu" },
      { de: "darf nicht … werden", tr: "yasak talimat" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün profesyonel mutfaktayız. Tarif kitabı 'sen şunu yap' demez; 'şu şöyle pişirilmeli' der. Yani kipli edilgen. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu ders geçen derslerdeki yapının mutfaktaki hâli: aynı kural, yeni kelimeler ve çok daha hızlı bir tempo. Önce kelimeler.")] },
      word("İlk", { de: "garen", tr: "pişirmek" }),
      word("İkinci", { de: "abschmecken", tr: "tadını ayarlamak" }),
      word("Üçüncü", { de: "der Teig", tr: "hamur" }),
      word("Dördüncü", { de: "köcheln", tr: "kısık ateşte kaynamak" }),
      word("Son", { de: "die Konsistenz", tr: "kıvam" }),
      { say: [tr("Kalıbımız:"), de("darf nicht … werden"), tr("Mutfakta yasak talimatı böyle verilir.")] },
      { say: [tr("Örnek:"), de("Die Soße darf nicht gekocht werden."), tr("Tekrar edin:"), de("Die Soße darf nicht gekocht werden")], expect: repeat("Die Soße darf nicht gekocht werden") },
      { say: [tr("Sıra sende: 'Et yavaşça pişirilmeli.'")], expect: produce("Das Fleisch muss langsam gegart werden", [tr("Zorunluluk müssen ile; sonda ortaç ve werden:"), de("Das Fleisch muss langsam gegart werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sos en sonda tatlandırılıyor.'")], expect: produce("Die Soße wird zum Schluss abgeschmeckt", [tr("Şimdiki zaman edilgeni; ayrılabilen fiilin ortacı:"), de("Die Soße wird zum Schluss abgeschmeckt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Hamurun bir saat dinlenmesi gerekiyor.'")], expect: produce("Der Teig muss eine Stunde ruhen", [tr("Bu fiil edilgen almaz; mastar doğrudan gelir:"), de("Der Teig muss eine Stunde ruhen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Soße wird zum Schluss abgeschmeckt werden."), tr("cümlesi doğru mu?")], expect: truefalse("Die Soße wird zum Schluss abgeschmeckt werden.", false, [tr("Şimdiki zaman edilgeninde ikinci werden fazladır:"), de("Die Soße wird zum Schluss abgeschmeckt.")]) },
      { say: [tr("Son bir soru: 'Kıvam nasıl olmalı?'")], expect: produce("Wie muss die Konsistenz sein", [tr("Soru kelimesi başta, mastar sonda:"), de("Wie muss die Konsistenz sein?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir aşçıdan tarifin püf noktalarını öğreneceksin.")] },
    ],
    roleplay: {
      scene: "Bir aşçıdan zor bir tarifin püf noktalarını öğreniyorsun: neyin nasıl pişirilmesi gerektiğini, neyin yapılmaması gerektiğini ve kıvamın nasıl anlaşıldığını sor.",
      partner: "aceleci ama öğretmeyi seven bir aşçı",
      opening: "Sie wollen es also selbst probieren? Gut. Sagen Sie mir zuerst: Womit fangen Sie an?",
      openingTr: "Demek kendiniz denemek istiyorsunuz? Güzel. Önce şunu söyleyin: Neyle başlıyorsunuz?",
      goal: "Pişirme adımları, bir yasak ve kıvamın nasıl anlaşılacağı öğrenilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-wartung",
    icon: "repair",
    level: "B2",
    course: "de",
    title: "Die Inspektion",
    titleTr: "Bakım süreci",
    summary: "Yapılması gerekenleri sein + zu ile bildirmeyi öğretir.",
    minutes: 11,
    focusId: "Passiversatz",
    vocab: [
      { de: "die Inspektion", tr: "periyodik bakım" },
      { de: "erneuern", tr: "yenilemek" },
      { de: "der Verschleiß", tr: "aşınma" },
      { de: "die Bremse", tr: "fren" },
      { de: "fällig", tr: "vadesi gelmiş" },
    ],
    patterns: [
      { de: "… ist/sind zu erneuern", tr: "yapılması gereken" },
      { de: "… lässt sich noch fahren", tr: "hâlâ mümkün olan" },
    ],
    lecture: [
      { say: [tr("Merhaba! Servisteyiz. Usta sana 'bunu değiştirmelisin' demez; 'bu yenilenmeli' der. Fail yok, iş var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki yapıyı yan yana kullanacağız: zorunlu olan sein artı zu ile, hâlâ mümkün olan lassen artı sich ile. Önce kelimeler.")] },
      word("İlk", { de: "die Inspektion", tr: "periyodik bakım" }),
      word("İkinci", { de: "erneuern", tr: "yenilemek" }),
      word("Üçüncü", { de: "der Verschleiß", tr: "aşınma" }),
      word("Dördüncü", { de: "die Bremse", tr: "fren" }),
      word("Son", { de: "fällig", tr: "vadesi gelmiş" }),
      { say: [tr("Kalıbımız:"), de("Die Bremsen sind zu erneuern."), tr("Yani 'frenlerin yenilenmesi gerekiyor'. Çoğulda sind.")] },
      { say: [tr("Tekrar edin:"), de("Die Bremsen sind zu erneuern")], expect: repeat("Die Bremsen sind zu erneuern") },
      { say: [tr("Sıra sende: 'Araç hâlâ sürülebilir.'")], expect: produce("Das Fahrzeug lässt sich noch fahren", [tr("İmkân lassen artı sich ile; mastar sonda:"), de("Das Fahrzeug lässt sich noch fahren."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Aşınma açıkça görülüyor.'")], expect: produce("Der Verschleiß ist deutlich sichtbar", [tr("Sıfat biçimi; sein ile:"), de("Der Verschleiß ist deutlich sichtbar."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bakımın vadesi geldi.'")], expect: produce("Die Inspektion ist fällig", [tr("Kısa hüküm cümlesi:"), de("Die Inspektion ist fällig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Bremsen sind zu erneuern."), tr("cümlesi doğru mu?")], expect: truefalse("Die Bremsen sind zu erneuern.", true, [tr("Doğru. Çoğul özne sind alıyor ve sein artı zu yapısı zorunluluğu kişisiz söylüyor.")]) },
      { say: [tr("Son: 'Randevu telefonla ayarlanıyor.'")], expect: produce("Der Termin wird telefonisch vereinbart", [tr("Şimdiki zaman edilgeni:"), de("Der Termin wird telefonisch vereinbart."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada servisteki ustayla bakımı konuşacaksın: ne zorunlu, ne bekleyebilir, ne kadar tutar.")] },
    ],
    roleplay: {
      scene: "Servisteki ustayla aracın bakımını konuşuyorsun: neyin mutlaka yapılması gerektiğini, neyin bekleyebileceğini, ne kadar tutacağını ve ne zaman hazır olacağını öğren.",
      partner: "dürüst ama acele eden bir servis ustası",
      opening: "Ich war einmal drunter. Zwei Sachen sind fällig, eine davon dringend — wollen Sie beides machen lassen?",
      openingTr: "Bir baktım altına. İki şeyin vakti gelmiş, biri acil — ikisini de yaptırmak ister misiniz?",
      goal: "Zorunlu ve bekleyebilecek işler ayrılmış, fiyat öğrenilmiş ve teslim zamanı kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-organisation",
    icon: "party",
    level: "B2",
    course: "de",
    title: "Wer macht was beim Fest?",
    titleTr: "Organizasyon",
    summary: "Yapılacak işleri kişisiz edilgenle dağıtmayı öğretir.",
    minutes: 11,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "besorgen", tr: "temin etmek" },
      { de: "zuteilen", tr: "paylaştırmak" },
      { de: "der Aufbau", tr: "kurulum" },
      { de: "der Ablaufplan", tr: "akış planı" },
      { de: "rechtzeitig", tr: "zamanında" },
    ],
    patterns: [
      { de: "Es muss noch … werden.", tr: "kişisiz zorunluluk" },
      { de: "… kann übernommen werden", tr: "üstlenilebilir olan" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve edilgenin en pratik hâli: iş bölümü. Kimsenin adını vermeden bütün işleri sayabilirsin. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sahte özne 'es' burada çok işine yarar: 'Es muss noch eingekauft werden' — alışveriş yapılması gerekiyor, kim yapacak henüz belli değil. Önce kelimeler.")] },
      word("İlk", { de: "besorgen", tr: "temin etmek" }),
      word("İkinci", { de: "zuteilen", tr: "paylaştırmak" }),
      word("Üçüncü", { de: "der Aufbau", tr: "kurulum" }),
      word("Dördüncü", { de: "der Ablaufplan", tr: "akış planı" }),
      word("Son", { de: "rechtzeitig", tr: "zamanında" }),
      { say: [tr("Kalıbımız:"), de("Es muss noch … werden."), tr("Sahte özne es cümleyi başlatır ve fail hiç anılmaz.")] },
      { say: [tr("Örnek:"), de("Es muss noch eingekauft werden."), tr("Tekrar edin:"), de("Es muss noch eingekauft werden")], expect: repeat("Es muss noch eingekauft werden") },
      { say: [tr("Sıra sende: 'Müzik üstlenilebilir.'")], expect: produce("Die Musik kann übernommen werden", [tr("İmkân können ile; sonda ortaç ve werden:"), de("Die Musik kann übernommen werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kurulum cuma günü yapılmalı.'")], expect: produce("Der Aufbau muss am Freitag gemacht werden", [tr("Zaman ortaçtan önce:"), de("Der Aufbau muss am Freitag gemacht werden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Görevler zamanında paylaştırılmalı.'")], expect: produce("Die Aufgaben müssen rechtzeitig zugeteilt werden", [tr("Çoğul kip fiili; ayrılabilen fiilin ortacı:"), de("Die Aufgaben müssen rechtzeitig zugeteilt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Aufgaben müssen rechtzeitig zuteilen werden."), tr("cümlesi doğru mu?")], expect: truefalse("Die Aufgaben müssen rechtzeitig zuteilen werden.", false, [tr("Edilgende mastar değil ortaç gelir:"), de("Die Aufgaben müssen rechtzeitig zugeteilt werden.")]) },
      { say: [tr("Son bir soru: 'Akış planını kim hazırlıyor?'")], expect: produce("Wer erstellt den Ablaufplan", [tr("Soru zamiri özne, fiil ikinci sırada:"), de("Wer erstellt den Ablaufplan?"), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir etkinliğin hazırlığını paylaşacaksın: ne yapılmalı, kim ne üstleniyor.")] },
    ],
    roleplay: {
      scene: "Bir mahalle şenliğinin hazırlığını iki kişi paylaşıyorsunuz. Yapılması gerekenleri kişisiz edilgenle say, kimin neyi üstleneceğini konuş ve akış planını bir tarihe bağla.",
      partner: "hevesli ama dağınık, sürekli yeni fikir atan bir komşu",
      opening: "Also, ich habe schon mal eine Liste gemacht — die ist allerdings ziemlich lang geworden. Womit sollen wir anfangen?",
      openingTr: "Ben bir liste yaptım — ama epey uzadı. Neyle başlayalım?",
      goal: "Yapılacak işler sayılmış, kimin neyi üstlendiği paylaşılmış ve akış planı bir tarihe bağlanmış olur.",
      minTurns: 9,
    },
  },
];
