import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B1 · Modül 10 — Duygular ve hayaller (091–100). B1'in kapanışı.
 *
 * Seviyenin son modülü bilinçli olarak GERÇEK OLMAYANI konuşuyor: olsaydı,
 * olsa, keşke olsaydı. Sebebi hem dilbilgisel hem insani. Dilbilgisel olan
 * şu — dilek kipi B1'in en son ve en zor yapısıdır ve üç ayrı işi vardır:
 * kibarlık (daha önce geçti), gerçekdışı koşul ve geçmişe dair pişmanlık.
 * Modül son ikisini üstleniyor.
 *
 * İnsani olan sebep daha önemli. Bir dili "biliyorum" diyebilmek için hava
 * durumunu ve randevuyu konuşabilmek yetmiyor; özlediğini, korktuğunu,
 * pişman olduğunu, birine ne hissettiğini söyleyebilmek gerekiyor. Bunlar
 * kelime meselesi değil, cümle biçimi meselesidir — ve o biçim burada.
 *
 * Son ders (100) bir ara bilanço: öğrenci kendi yolunu dilek kipiyle anlatıyor
 * ("Almanca olmasaydı …") ve bir sonraki etaba bakıyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB1B10: Lesson[] = [
  {
    id: "de-b1-irreal",
    icon: "money",
    level: "B1",
    course: "de",
    title: "Wenn ich reich wäre",
    titleTr: "Gerçekdışı koşul",
    summary: "Gerçek olmayan bir koşulu wäre ve hätte ile kurmayı öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II-irreal",
    vocab: [
      { de: "reich", tr: "zengin" },
      { de: "spenden", tr: "bağışlamak" },
      { de: "die Insel", tr: "ada" },
      { de: "sorgenfrei", tr: "dertsiz" },
      { de: "das Vermögen", tr: "servet" },
    ],
    patterns: [
      { de: "Wenn ich reich wäre, würde ich …", tr: "gerçekdışı koşul" },
      { de: "Was wäre, wenn …?", tr: "olasılık sorusu" },
    ],
    lecture: [
      { say: [tr("Merhaba! B1'in son modülüne geldik ve en güzel yapısıyla başlıyoruz: olmayan bir dünyayı anlatmak. 'Zengin olsam…' Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kibar rica için dilek kipini zaten kullandın. Şimdi aynı biçim başka bir iş yapıyor: gerçek olmayan bir koşul kurmak. İki fiil yeter, olmak ve sahip olmak. Önce kelimeler.")] },
      word("İlk", { de: "reich", tr: "zengin" }),
      word("İkinci", { de: "spenden", tr: "bağışlamak" }),
      word("Üçüncü", { de: "die Insel", tr: "ada" }),
      word("Dördüncü", { de: "sorgenfrei", tr: "dertsiz" }),
      word("Son", { de: "das Vermögen", tr: "servet" }),
      { say: [tr("Kalıbımız:"), de("Wenn ich reich wäre, würde ich …"), tr("Koşul yan cümlesinde dilek kipi, ana cümlede de dilek kipi. İkisi birden değişiyor.")] },
      { say: [tr("Örnek:"), de("Wenn ich reich wäre, würde ich ein Haus am Meer kaufen."), tr("Lütfen tekrar edin:"), de("Wenn ich reich wäre, würde ich ein Haus am Meer kaufen")], expect: repeat("Wenn ich reich wäre, würde ich ein Haus am Meer kaufen") },
      { say: [tr("Sıra sende: 'Daha çok vaktim olsa daha çok okurdum.'")], expect: produce("Wenn ich mehr Zeit hätte, würde ich mehr lesen", [tr("Koşulda sahip olmanın dilek kipi, ana cümlede mastar sonda:"), de("Wenn ich mehr Zeit hätte, würde ich mehr lesen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Servetimin yarısını bağışlardım.'")], expect: produce("Ich würde die Hälfte meines Vermögens spenden", [tr("Dilek kipiyle ana cümle; mastar en sonda:"), de("Ich würde die Hälfte meines Vermögens spenden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, soru sor: 'Ne olurdu, yarın işi bıraksaydım?'")], expect: produce("Was wäre, wenn ich morgen kündigen würde", [tr("Soru başta, koşul yan cümlesi arkadan:"), de("Was wäre, wenn ich morgen kündigen würde?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn ich reich bin, würde ich eine Insel kaufen."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn ich reich bin, würde ich eine Insel kaufen.", false, [tr("Gerçekdışı koşulda yan cümle de dilek kipine girer:"), de("Wenn ich reich wäre, würde ich eine Insel kaufen.")]) },
      { say: [tr("Son: 'Dertsiz bir hayat sıkıcı olurdu.'")], expect: produce("Ein sorgenfreies Leben wäre langweilig", [tr("Dilek kipi tek başına da kullanılır:"), de("Ein sorgenfreies Leben wäre langweilig."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla oyun oynayacaksın: zengin olsanız ne yapardınız.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla 'ya olsaydı' oyunu oynuyorsunuz: zengin olsan ne yapardın, nerede yaşardın, neyi değiştirmezdin. Cevaplarını gerçekdışı koşul cümleleriyle kur.",
      partner: "hayal kurmayı seven, sorular üreten bir arkadaş",
      opening: "Stell dir vor, du gewinnst morgen eine Million. Was würdest du als Erstes machen?",
      openingTr: "Düşün ki yarın bir milyon kazandın. İlk ne yapardın?",
      goal: "Zengin olsan ne yapacağın, nerede yaşayacağın ve neyi değiştirmeyeceğin söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-wuensche",
    icon: "star",
    level: "B1",
    course: "de",
    title: "Drei Wünsche frei",
    titleTr: "Dilekler",
    summary: "Gerçekleşmemiş bir dileği ich wünschte ve würde ile anlatmayı öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II-irreal",
    vocab: [
      { de: "unerfüllt", tr: "gerçekleşmemiş" },
      { de: "die Sehnsucht", tr: "özlem" },
      { de: "verwirklichen", tr: "gerçekleştirmek" },
      { de: "bescheiden", tr: "mütevazı" },
      { de: "endlos", tr: "sonsuz" },
    ],
    patterns: [
      { de: "Ich wünschte, …", tr: "gerçekleşmemiş dilek" },
      { de: "Am liebsten würde ich …", tr: "en çok isteneni söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Dün olmayan bir dünyayı kurduk. Bugün bir adım daha: olmasını istediğin ama olmayan şey. Türkçede 'keşke' diyoruz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bunun için tek bir fiil biçimi yeter ve o biçim geçmiş gibi görünür ama geçmişi anlatmaz. Dilek anlatır. Önce kelimeler.")] },
      word("İlk", { de: "unerfüllt", tr: "gerçekleşmemiş" }),
      word("İkinci", { de: "die Sehnsucht", tr: "özlem" }),
      word("Üçüncü", { de: "verwirklichen", tr: "gerçekleştirmek" }),
      word("Dördüncü", { de: "bescheiden", tr: "mütevazı" }),
      word("Son", { de: "endlos", tr: "sonsuz" }),
      { say: [tr("Kalıbımız:"), de("Ich wünschte, …"), tr("Ana cümledeki fiil dilek kipinde, yan cümle de öyle. Türkçedeki 'keşke' karşılığı.")] },
      { say: [tr("Örnek:"), de("Ich wünschte, ich hätte mehr Zeit für meine Familie."), tr("Tekrar edin:"), de("Ich wünschte, ich hätte mehr Zeit für meine Familie")], expect: repeat("Ich wünschte, ich hätte mehr Zeit für meine Familie") },
      { say: [tr("Sıra sende: 'Keşke daha yakın yaşasaydık.'")], expect: produce("Ich wünschte, wir würden näher wohnen", [tr("Dilek yan cümlesinde de dilek kipi:"), de("Ich wünschte, wir würden näher wohnen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'En çok bir yıl ara vermek isterdim.'")], expect: produce("Am liebsten würde ich ein Jahr Pause machen", [tr("En üstünlük derecesi başta, mastar en sonda:"), de("Am liebsten würde ich ein Jahr Pause machen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Dileklerim çok mütevazı.'")], expect: produce("Meine Wünsche sind sehr bescheiden", [tr("Çoğul özne, çoğul fiil:"), de("Meine Wünsche sind sehr bescheiden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich wünschte, ich hätte früher angefangen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich wünschte, ich hätte früher angefangen.", true, [tr("Doğru. Geçmişe dair bir dilek; yardımcı fiil dilek kipinde ve ortaç en sonda.")]) },
      { say: [tr("Son: 'Bu hayali gerçekleştirmek istiyorum.'")], expect: produce("Ich möchte diesen Traum verwirklichen", [tr("Modal fiil çekimli, mastar en sonda:"), de("Ich möchte diesen Traum verwirklichen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla dileklerinizi paylaşacaksınız: üç dilek hakkın olsa ne isterdin.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla dileklerinizi paylaşıyorsunuz: üç dilek hakkın olsa ne isterdin, hangi dileğin hâlâ gerçekleşmedi. Cevaplarını dilek kipiyle kur.",
      partner: "kendi dileklerini de anlatan, samimi bir arkadaş",
      opening: "Wenn du drei Wünsche frei hättest — aber ehrlich, keine Millionen: Was wären deine drei?",
      openingTr: "Üç dilek hakkın olsa — ama dürüstçe, milyonlar olmadan: Üçü ne olurdu?",
      goal: "Üç dilek söylenmiş ve hangisinin hâlâ gerçekleşmediği anlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-vergangen-bereuen",
    icon: "feelings",
    level: "B1",
    course: "de",
    title: "Hätte ich doch!",
    titleTr: "Pişmanlık",
    summary: "Geçmişe dair pişmanlığı hätte ve Partizip II ile anlatmayı öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II-irreal",
    vocab: [
      { de: "bereuen", tr: "pişman olmak" },
      { de: "versäumen", tr: "kaçırmak (fırsatı)" },
      { de: "zögern", tr: "tereddüt etmek" },
      { de: "im Nachhinein", tr: "sonradan bakınca" },
      { de: "die Chance", tr: "fırsat" },
    ],
    patterns: [
      { de: "Hätte ich doch …!", tr: "geçmişe dair pişmanlık" },
      { de: "Ich hätte … sollen.", tr: "yapmam gerekirdi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün en insani cümlelerden birini kuracağız: keşke yapsaydım. Bu, dilek kipinin geçmişe bakan hâli. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki biçim var. Biri ünlem gibi: 'keşke söyleseydim'. Öteki daha sakin: 'söylemem gerekirdi'. İkisinde de sahip olma fiilinin dilek kipi var. Önce kelimeler.")] },
      word("İlk", { de: "bereuen", tr: "pişman olmak" }),
      word("İkinci", { de: "versäumen", tr: "kaçırmak (fırsatı)" }),
      word("Üçüncü", { de: "zögern", tr: "tereddüt etmek" }),
      word("Dördüncü", { de: "im Nachhinein", tr: "sonradan bakınca" }),
      word("Son", { de: "die Chance", tr: "fırsat" }),
      { say: [tr("Kalıbımız:"), de("Ich hätte früher fragen sollen."), tr("Modal fiil mastar biçiminde en sonda kalıyor; bu, geçmiş dilek kipinin özel dizilimi.")] },
      { say: [tr("Tekrar edin:"), de("Ich hätte früher fragen sollen")], expect: repeat("Ich hätte früher fragen sollen") },
      { say: [tr("Sıra sende: 'Keşke o fırsatı kaçırmasaydım.'")], expect: produce("Hätte ich diese Chance doch nicht versäumt", [tr("Ünlem biçiminde yardımcı fiil en başa geçer:"), de("Hätte ich diese Chance doch nicht versäumt!"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi sakin biçimiyle: 'Daha az tereddüt etmeliydim.'")], expect: produce("Ich hätte weniger zögern sollen", [tr("Modal fiil mastar hâlinde en sonda:"), de("Ich hätte weniger zögern sollen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sonradan bakınca pişman değilim.'")], expect: produce("Im Nachhinein bereue ich nichts", [tr("Tümleç başta, fiil ikinci sırada:"), de("Im Nachhinein bereue ich nichts."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich hätte früher gefragt sollen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich hätte früher gefragt sollen.", false, [tr("Modal fiil varken asıl fiil ortaç değil mastar olur:"), de("Ich hätte früher fragen sollen.")]) },
      { say: [tr("Son: 'Bir dahaki sefere hemen söylerim.'")], expect: produce("Beim nächsten Mal sage ich es sofort", [tr("Tümleç başta, fiil ikinci sırada:"), de("Beim nächsten Mal sage ich es sofort."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşına geçmişteki bir kararını anlatacaksın: ne oldu, ne yapmalıydın, şimdi ne düşünüyorsun.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına geçmişte verdiğin bir kararı anlatıyorsun: ne olmuştu, geriye bakınca ne yapmalıydın, şimdi pişman mısın. Pişmanlık kalıplarını kullan.",
      partner: "yargılamayan, kendi pişmanlıklarını da anlatan bir arkadaş",
      opening: "Du hast neulich gesagt, du denkst noch oft an diese Sache. Was hättest du anders gemacht?",
      openingTr: "Geçen gün o meseleyi hâlâ sık düşündüğünü söylemiştin. Neyi farklı yapardın?",
      goal: "Karar anlatılmış, geriye bakınca ne yapman gerektiği söylenmiş ve bugün nasıl gördüğün belirtilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-zukunftsangst",
    icon: "question",
    level: "B1",
    course: "de",
    title: "Was, wenn es schiefgeht?",
    titleTr: "Kaygıyla konuşmak",
    summary: "Kaygıyı koşul cümleleriyle adlandırmayı ve dengelemeyi öğretir.",
    minutes: 10,
    focusId: "Nebensatz-wenn",
    vocab: [
      { de: "schiefgehen", tr: "ters gitmek" },
      { de: "die Sicherheit", tr: "güvence" },
      { de: "die Ungewissheit", tr: "belirsizlik" },
      { de: "bewältigen", tr: "üstesinden gelmek" },
      { de: "zuversichtlich", tr: "umutlu" },
    ],
    patterns: [
      { de: "Was ist, wenn …?", tr: "kaygıyı soruya çevirir" },
      { de: "Selbst wenn …, …", tr: "en kötü ihtimali karşılar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kaygıyı konuşacağız. Kaygının dili sorudur: 'ya olmazsa'. Ama bir de cevabı var: 'olsa bile'. İkisini de kuracağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkincisi ilkinden daha güçlü: en kötü ihtimali kabul edip yine de devam etmek. Almancada bunun tek kelimelik bir bağlacı var. Önce kelimeler.")] },
      word("İlk", { de: "schiefgehen", tr: "ters gitmek" }),
      word("İkinci", { de: "die Sicherheit", tr: "güvence" }),
      word("Üçüncü", { de: "die Ungewissheit", tr: "belirsizlik" }),
      word("Dördüncü", { de: "bewältigen", tr: "üstesinden gelmek" }),
      word("Son", { de: "zuversichtlich", tr: "umutlu" }),
      { say: [tr("Kalıbımız:"), de("Selbst wenn es schiefgeht, …"), tr("Yan cümle başta, ana cümle fiille başlıyor. Anlamı: olsa bile.")] },
      { say: [tr("Örnek:"), de("Selbst wenn es schiefgeht, lerne ich etwas daraus."), tr("Tekrar edin:"), de("Selbst wenn es schiefgeht, lerne ich etwas daraus")], expect: repeat("Selbst wenn es schiefgeht, lerne ich etwas daraus") },
      { say: [tr("Sıra sende: 'Ya işe alınmazsam?'")], expect: produce("Was ist, wenn ich die Stelle nicht bekomme", [tr("Soru başta, koşul yan cümlesi arkadan ve fiil sonda:"), de("Was ist, wenn ich die Stelle nicht bekomme?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Belirsizlik bana zor geliyor.'")], expect: produce("Die Ungewissheit fällt mir schwer", [tr("Bu kalıpta zorlanan kişi yönelme hâliyle gösterilir:"), de("Die Ungewissheit fällt mir schwer."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunun üstesinden geleceğime eminim.'")], expect: produce("Ich bin sicher, dass ich das bewältige", [tr("Yan cümlede fiil en sona gider:"), de("Ich bin sicher, dass ich das bewältige."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Selbst wenn es schiefgeht, ich mache weiter."), tr("cümlesi doğru mu?")], expect: truefalse("Selbst wenn es schiefgeht, ich mache weiter.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar:"), de("Selbst wenn es schiefgeht, mache ich weiter.")]) },
      { say: [tr("Son: 'Genel olarak umutluyum.'")], expect: produce("Insgesamt bin ich zuversichtlich", [tr("Tümleç başta, fiil ikinci sırada:"), de("Insgesamt bin ich zuversichtlich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir yakınınla gelecek kaygını konuşacaksın: neden korkuyorsun, olsa bile ne yaparsın.")] },
    ],
    roleplay: {
      scene: "Bir yakınınla gelecek kaygını konuşuyorsun: neyin ters gitmesinden korkuyorsun, en kötü ihtimalde ne yaparsın, seni ne rahatlatıyor.",
      partner: "sakinleştiren, sorularla düşündüren bir yakının",
      opening: "Du wirkst unruhig, seit die Entscheidung ansteht. Was ist die schlimmste Möglichkeit, an die du denkst?",
      openingTr: "Karar yaklaştığından beri huzursuz görünüyorsun. Aklındaki en kötü ihtimal ne?",
      goal: "Korkun adlandırılmış, en kötü ihtimalde ne yapacağın söylenmiş ve seni rahatlatan şey konuşulmuş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-freundschaft-pflegen",
    icon: "greet",
    level: "B1",
    course: "de",
    title: "Alte Freunde",
    titleTr: "Dostluğu korumak",
    summary: "Kopan ve yeniden kurulan bir ilişkiyi sıralı geçmişle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Plusquamperfekt",
    vocab: [
      { de: "pflegen", tr: "özen göstermek" },
      { de: "die Freundschaft", tr: "dostluk" },
      { de: "wiederfinden", tr: "yeniden bulmak" },
      { de: "vertraut", tr: "içten, tanıdık" },
      { de: "die Distanz", tr: "mesafe" },
    ],
    patterns: [
      { de: "Nachdem wir uns verloren hatten, …", tr: "önce olan iş bir basamak geride" },
      { de: "Wir haben uns wiedergefunden.", tr: "sonra olanı anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün uzun bir hikâyeyi kısa anlatmayı öğreneceğiz: bir dostluk kopmuş, sonra geri gelmiş. İki zaman katmanı var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Önce olan iş bir basamak geriye çekiliyor, sonra olan normal geçmişte kalıyor. Böylece sıra tek cümlede anlaşılıyor. Önce kelimeler.")] },
      word("İlk", { de: "pflegen", tr: "özen göstermek" }),
      word("İkinci", { de: "die Freundschaft", tr: "dostluk" }),
      word("Üçüncü", { de: "wiederfinden", tr: "yeniden bulmak" }),
      word("Dördüncü", { de: "vertraut", tr: "içten, tanıdık" }),
      word("Son", { de: "die Distanz", tr: "mesafe" }),
      { say: [tr("Kalıbımız:"), de("Nachdem wir uns verloren hatten, …"), tr("Kopuş önce oldu, o yüzden bir basamak geride.")] },
      { say: [tr("Örnek:"), de("Nachdem wir uns aus den Augen verloren hatten, kam eine lange Pause."), tr("Tekrar edin:"), de("Nachdem wir uns aus den Augen verloren hatten, kam eine lange Pause")], expect: repeat("Nachdem wir uns aus den Augen verloren hatten, kam eine lange Pause") },
      { say: [tr("Sıra sende: 'Taşındıktan sonra mesafe büyüdü.'")], expect: produce("Nachdem sie umgezogen war, wurde die Distanz größer", [tr("Önce olan iş bir basamak geride, ana cümle fiille başlar:"), de("Nachdem sie umgezogen war, wurde die Distanz größer."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'On yıl sonra birbirimizi yeniden bulduk.'")], expect: produce("Nach zehn Jahren haben wir uns wiedergefunden", [tr("Tümleç başta, ortaç en sonda:"), de("Nach zehn Jahren haben wir uns wiedergefunden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Dostluk özen ister.'")], expect: produce("Eine Freundschaft muss man pflegen", [tr("Nesne başa çekilmiş, modal fiil ikinci sırada:"), de("Eine Freundschaft muss man pflegen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nachdem wir uns getroffen hatten, war alles wieder vertraut."), tr("cümlesi doğru mu?")], expect: truefalse("Nachdem wir uns getroffen hatten, war alles wieder vertraut.", true, [tr("Doğru. Önce olan iş bir basamak geride, ana cümle normal geçmişte ve fiille başlıyor.")]) },
      { say: [tr("Son: 'Uzaklık dostluğu bitirmiyor.'")], expect: produce("Entfernung beendet eine Freundschaft nicht", [tr("Olumsuzluk cümlenin sonunda:"), de("Entfernung beendet eine Freundschaft nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada uzun zamandır görüşmediğin biriyle karşılaşacaksın: ne oldu, neden koptu, şimdi nasıl.")] },
    ],
    roleplay: {
      scene: "Yıllar sonra eski bir arkadaşınla karşılaştın: aradan ne geçti, dostluk neden koptu, şimdi nasıl. Sırayı önce olan işi geriye çekerek anlat.",
      partner: "sizi kaybetmiş olmaktan üzgün, konuşkan eski bir arkadaş",
      opening: "Ich glaub es nicht — wie lange ist das her? Erzähl, was ist bei dir alles passiert?",
      openingTr: "İnanamıyorum — ne kadar oldu? Anlat, sende neler oldu?",
      goal: "Aradan geçenler anlatılmış, kopuşun sebebi konuşulmuş ve yeniden görüşmek için söz verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-liebeserklaerung",
    icon: "ring",
    level: "B1",
    course: "de",
    title: "Mehr als Freunde?",
    titleTr: "Duygu itirafı",
    summary: "Duygu itirafını dilek kipiyle yumuşatarak söylemeyi öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "gestehen", tr: "itiraf etmek" },
      { de: "verliebt", tr: "âşık" },
      { de: "der Mut", tr: "cesaret" },
      { de: "zurückweisen", tr: "geri çevirmek" },
      { de: "die Gefühle", tr: "duygular" },
    ],
    patterns: [
      { de: "Ich würde gern mehr …", tr: "isteği yumuşak söyler" },
      { de: "Wie wäre es, wenn wir …?", tr: "teklifi soruya çevirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü ders zor bir cümle için: birine ne hissettiğini söylemek. Dilek kipi burada cesaret veriyor, çünkü hayır demeyi kolaylaştırıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Doğrudan söylemek karşı tarafı köşeye sıkıştırır. Dilek kipiyle söylenince kapı açık kalır ve ikisi de rahat eder. Önce kelimeler.")] },
      word("İlk", { de: "gestehen", tr: "itiraf etmek" }),
      word("İkinci", { de: "verliebt", tr: "âşık" }),
      word("Üçüncü", { de: "der Mut", tr: "cesaret" }),
      word("Dördüncü", { de: "zurückweisen", tr: "geri çevirmek" }),
      word("Son", { de: "die Gefühle", tr: "duygular" }),
      { say: [tr("Kalıbımız:"), de("Wie wäre es, wenn wir …?"), tr("Teklif bir soruya dönüşüyor; reddetmek kolaylaşıyor ve bu iyi bir şey.")] },
      { say: [tr("Örnek:"), de("Wie wäre es, wenn wir mal zusammen essen gehen?"), tr("Tekrar edin:"), de("Wie wäre es, wenn wir mal zusammen essen gehen")], expect: repeat("Wie wäre es, wenn wir mal zusammen essen gehen") },
      { say: [tr("Sıra sende: 'Seninle daha çok vakit geçirmek isterdim.'")], expect: produce("Ich würde gern mehr Zeit mit dir verbringen", [tr("Dilek kipi artı mastar; mastar en sonda:"), de("Ich würde gern mehr Zeit mit dir verbringen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bunu söylemeye cesaret edemiyorum.'")], expect: produce("Ich habe nicht den Mut, das zu sagen", [tr("İsim artı mastar öbeği:"), de("Ich habe nicht den Mut, das zu sagen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sana bir şey itiraf etmek istiyorum.'")], expect: produce("Ich möchte dir etwas gestehen", [tr("Yönelme nesnesi önce, belirtme sonra, mastar en sonda:"), de("Ich möchte dir etwas gestehen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wie wäre es, wenn wir gehen ins Kino?"), tr("cümlesi doğru mu?")], expect: truefalse("Wie wäre es, wenn wir gehen ins Kino?", false, [tr("Yan cümlede çekimli fiil en sona gider:"), de("Wie wäre es, wenn wir ins Kino gehen?")]) },
      { say: [tr("Son: 'Geri çevrilirsem de sorun değil.'")], expect: produce("Auch wenn du Nein sagst, ist das okay", [tr("Yan cümle başta, ana cümle fiille başlar:"), de("Auch wenn du Nein sagst, ist das okay."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada uzun zamandır arkadaş olduğun birine duygularını anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Uzun zamandır arkadaş olduğun birine duygularını anlatıyorsun: ne hissediyorsun, ne öneriyorsun, cevabı ne olursa olsun ilişkiyi korumak istiyorsun. Cümlelerini dilek kipiyle yumuşat.",
      partner: "şaşıran ama sıcak, düşünmek için zaman isteyen bir arkadaş",
      opening: "Du wolltest über etwas reden und guckst so ernst. Jetzt bin ich neugierig — was ist los?",
      openingTr: "Bir şey konuşmak istemiştin ve çok ciddi bakıyorsun. Şimdi merak ettim — ne oldu?",
      goal: "Duygun söylenmiş, bir teklif yapılmış ve cevabı ne olursa olsun ilişkinin süreceği belirtilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-konflikt-loesen",
    icon: "handshake",
    level: "B1",
    course: "de",
    title: "Reden statt schweigen",
    titleTr: "Çatışma çözmek",
    summary: "Bir anlaşmazlığı suçlamadan konuşmayı ve amacı damit ile söylemeyi öğretir.",
    minutes: 10,
    focusId: "Nebensatz-damit",
    vocab: [
      { de: "der Konflikt", tr: "anlaşmazlık" },
      { de: "schweigen", tr: "susmak" },
      { de: "klären", tr: "açıklığa kavuşturmak" },
      { de: "der Vorwurf", tr: "suçlama" },
      { de: "verletzen", tr: "kırmak (duygusal)" },
    ],
    patterns: [
      { de: "Ich sage das, damit …", tr: "amacı açıklar" },
      { de: "Lass uns das in Ruhe klären.", tr: "sakin konuşma teklifi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün zor bir konuşmayı yönetmeyi öğreneceğiz. Anahtar şu: söylediğin şeyin AMACINI söylemek. O zaman cümle suçlama olmaktan çıkıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amaç cümlesinde özne farklı olduğu için damit kullanılıyor: ben söylüyorum ki sen bilesin. Önce kelimeler.")] },
      word("İlk", { de: "der Konflikt", tr: "anlaşmazlık" }),
      word("İkinci", { de: "schweigen", tr: "susmak" }),
      word("Üçüncü", { de: "klären", tr: "açıklığa kavuşturmak" }),
      word("Dördüncü", { de: "der Vorwurf", tr: "suçlama" }),
      word("Son", { de: "verletzen", tr: "kırmak (duygusal)" }),
      { say: [tr("Kalıbımız:"), de("Ich sage das, damit du es weißt."), tr("Amaç yan cümlesinde fiil en sona gidiyor ve özne değişiyor.")] },
      { say: [tr("Tekrar edin:"), de("Ich sage das, damit du es weißt")], expect: repeat("Ich sage das, damit du es weißt") },
      { say: [tr("Sıra sende: 'Bunu seni kırmak için değil, anlaşmak için söylüyorum.'")], expect: produce("Ich sage das nicht, um dich zu verletzen, sondern damit wir uns verstehen", [tr("Özne aynıyken kısa yol, farklıyken damit:"), de("Ich sage das nicht, um dich zu verletzen, sondern damit wir uns verstehen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bunu sakin sakin konuşalım.'")], expect: produce("Lass uns das in Ruhe klären", [tr("Teklif kalıbı; mastar en sonda:"), de("Lass uns das in Ruhe klären."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu bir suçlama değil.'")], expect: produce("Das ist kein Vorwurf", [tr("Olumsuz artikel isimden önce:"), de("Das ist kein Vorwurf."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich sage das, damit du mich verstehst."), tr("cümlesi doğru mu?")], expect: truefalse("Ich sage das, damit du mich verstehst.", true, [tr("Doğru. Özne değiştiği için damit kullanılmış ve yan cümlenin fiili en sonda.")]) },
      { say: [tr("Son: 'Susmak hiçbir şeyi çözmüyor.'")], expect: produce("Schweigen löst nichts", [tr("Mastar özne olarak kullanılıyor:"), de("Schweigen löst nichts."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir yakınınla aranızdaki bir meseleyi konuşacaksın: ne oldu, ne hissettin, ne olsun istiyorsun.")] },
    ],
    roleplay: {
      scene: "Bir yakınınla aranızdaki bir meseleyi konuşuyorsun: ne oldu, ne hissettin, ne olmasını istiyorsun. Suçlama yerine amacını damit cümleleriyle söyle.",
      partner: "önce savunmaya geçen ama dinlemeye açılan bir yakının",
      opening: "Du bist seit Tagen komisch zu mir. Sagst du mir bitte, was eigentlich los ist?",
      openingTr: "Günlerdir bana karşı tuhafsın. Ne olduğunu söyler misin lütfen?",
      goal: "Ne olduğu ve ne hissettiğin suçlamadan anlatılmış; ne olmasını istediğin söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-heimweh",
    icon: "plane",
    level: "B1",
    course: "de",
    title: "Zwischen zwei Welten",
    titleTr: "İki dünya arasında",
    summary: "Aidiyet duygusunu als ile geçmişe bağlayarak anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-als",
    vocab: [
      { de: "die Wurzeln", tr: "kökler" },
      { de: "dazugehören", tr: "ait olmak" },
      { de: "die Fremde", tr: "gurbet" },
      { de: "zerrissen", tr: "ikiye bölünmüş" },
      { de: "die Ferne", tr: "uzak" },
    ],
    patterns: [
      { de: "Als ich ankam, …", tr: "geçmişte tek seferlik an" },
      { de: "Beides gehört zu mir.", tr: "iki aidiyeti birleştirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü konu birçok insanın hayatı: iki yere birden ait olmak. Bunu anlatmak için geçmişteki tek bir ana dönmemiz gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Hatırlatma: geçmişte bir kez olan şey için als, tekrarlanan için wenn. Geliş anı bir kez oldu, yani als. Önce kelimeler.")] },
      word("İlk", { de: "die Wurzeln", tr: "kökler" }),
      word("İkinci", { de: "dazugehören", tr: "ait olmak" }),
      word("Üçüncü", { de: "die Fremde", tr: "gurbet" }),
      word("Dördüncü", { de: "zerrissen", tr: "ikiye bölünmüş" }),
      word("Son", { de: "die Ferne", tr: "uzak" }),
      { say: [tr("Kalıbımız:"), de("Als ich ankam, …"), tr("Tek seferlik geçmiş an; yan cümlede fiil sonda, ana cümle fiille başlar.")] },
      { say: [tr("Örnek:"), de("Als ich ankam, verstand ich kein Wort."), tr("Tekrar edin:"), de("Als ich ankam, verstand ich kein Wort")], expect: repeat("Als ich ankam, verstand ich kein Wort") },
      { say: [tr("Sıra sende: 'İlk geldiğimde her şey yabancıydı.'")], expect: produce("Als ich zum ersten Mal kam, war alles fremd", [tr("Yan cümle önde, ana cümle fiille başlar:"), de("Als ich zum ersten Mal kam, war alles fremd."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bugün buraya ait hissediyorum.'")], expect: produce("Heute fühle ich, dass ich dazugehöre", [tr("Yan cümlede ayrılabilen fiil tek parça ve sonda:"), de("Heute fühle ich, dass ich dazugehöre."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Köklerim başka yerde ama hayatım burada.'")], expect: produce("Meine Wurzeln sind woanders, aber mein Leben ist hier", [tr("İki bağımsız cümle bir bağlaçla:"), de("Meine Wurzeln sind woanders, aber mein Leben ist hier."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn ich vor zehn Jahren ankam, war alles neu."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn ich vor zehn Jahren ankam, war alles neu.", false, [tr("Geçmişte bir kez olan olay için başka bir bağlaç kullanılır:"), de("Als ich vor zehn Jahren ankam, war alles neu.")]) },
      { say: [tr("Son: 'İkisi de bana ait.'")], expect: produce("Beides gehört zu mir", [tr("Kısa ve net bir kapanış cümlesi:"), de("Beides gehört zu mir."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada biri sana iki ülke arasındaki hayatını soracak: ne özlüyorsun, nereye aitsin.")] },
    ],
    roleplay: {
      scene: "Biri sana iki ülke arasındaki hayatını soruyor: geldiğinde nasıldı, neyi özlüyorsun, şimdi nereye ait hissediyorsun. Geçmiş anları als ile anlat.",
      partner: "içtenlikle merak eden, aceleci olmayan bir tanıdık",
      opening: "Darf ich was Persönliches fragen? Wo fühlst du dich eigentlich zu Hause — hier oder dort?",
      openingTr: "Kişisel bir şey sorabilir miyim? Kendini asıl nerede evinde hissediyorsun — burada mı orada mı?",
      goal: "Gelişinin nasıl olduğu, neyi özlediğin ve şimdi nereye ait hissettiğin anlatılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-lebenstraum",
    icon: "mountain",
    level: "B1",
    course: "de",
    title: "Mein großer Traum",
    titleTr: "Büyük hayal",
    summary: "Uzun vadeli bir hayali mastar öbekleriyle anlatmayı ve adımlara bölmeyi öğretir.",
    minutes: 10,
    focusId: "Infinitiv-zu",
    vocab: [
      { de: "die Vision", tr: "vizyon" },
      { de: "umsetzen", tr: "hayata geçirmek" },
      { de: "der Zweifel", tr: "kuşku" },
      { de: "der Antrieb", tr: "itici güç" },
      { de: "beharrlich", tr: "azimli" },
    ],
    patterns: [
      { de: "Ich träume davon, … zu …", tr: "hayali anlatır" },
      { de: "Schritt für Schritt", tr: "adım adım" },
    ],
    lecture: [
      { say: [tr("Merhaba! Sondan bir önceki ders ve konusu büyük: hayat hayali. Bunu anlatmanın kalıbı, edatı sabit bir fiille kurulan mastar öbeği. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Hayali söylemek kolay, adımlara bölmek zordur. İkisini de kuracağız — çünkü ikincisi olmadan ilki bir cümle olarak kalıyor. Önce kelimeler.")] },
      word("İlk", { de: "die Vision", tr: "vizyon" }),
      word("İkinci", { de: "umsetzen", tr: "hayata geçirmek" }),
      word("Üçüncü", { de: "der Zweifel", tr: "kuşku" }),
      word("Dördüncü", { de: "der Antrieb", tr: "itici güç" }),
      word("Son", { de: "beharrlich", tr: "azimli" }),
      { say: [tr("Kalıbımız:"), de("Ich träume davon, … zu …"), tr("Baştaki kelime fiilin edatını taşıyor, asıl hayal virgülden sonra geliyor.")] },
      { say: [tr("Örnek:"), de("Ich träume davon, ein eigenes Café zu eröffnen."), tr("Tekrar edin:"), de("Ich träume davon, ein eigenes Café zu eröffnen")], expect: repeat("Ich träume davon, ein eigenes Café zu eröffnen") },
      { say: [tr("Sıra sende: 'Bu fikri hayata geçirmeye çalışıyorum.'")], expect: produce("Ich versuche, diese Idee umzusetzen", [tr("Ayrılabilen fiilde küçük bağlaç ortaya girer:"), de("Ich versuche, diese Idee umzusetzen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kuşkularım var ama devam ediyorum.'")], expect: produce("Ich habe Zweifel, aber ich mache weiter", [tr("İki bağımsız cümle bir bağlaçla:"), de("Ich habe Zweifel, aber ich mache weiter."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Adım adım ilerliyorum.'")], expect: produce("Schritt für Schritt komme ich voran", [tr("Tümleç başta, ayrılabilen fiilin öneki sonda:"), de("Schritt für Schritt komme ich voran."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich träume davon, ein Café eröffnen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich träume davon, ein Café eröffnen.", false, [tr("Mastarın önündeki küçük bağlaç eksik:"), de("Ich träume davon, ein Café zu eröffnen.")]) },
      { say: [tr("Son: 'Beni asıl iten şey merak.'")], expect: produce("Mein größter Antrieb ist die Neugier", [tr("En üstünlük derecesi özne öbeğinde:"), de("Mein größter Antrieb ist die Neugier."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada birine hayalini anlatacaksın: ne, neden, ilk adım ne.")] },
    ],
    roleplay: {
      scene: "Birine büyük hayalini anlatıyorsun: ne olduğunu, neden istediğini, ilk adımın ne olacağını ve seni ne tuttuğunu söyle. Hayali mastar öbekleriyle kur.",
      partner: "gerçekçi sorular soran ama destekleyen bir dinleyici",
      opening: "Du hast mal von einem Plan erzählt, den du seit Jahren im Kopf hast. Was ist daraus geworden?",
      openingTr: "Yıllardır aklında olan bir plandan bahsetmiştin. Ondan ne oldu?",
      goal: "Hayalin, sebebi, ilk adımı ve seni tutan şey anlatılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-rueckblick",
    icon: "star",
    level: "B1",
    course: "de",
    title: "Die Zwischenbilanz",
    titleTr: "B1 kapanışı",
    summary: "Kendi öğrenme yolunu değerlendirmeyi ve bir sonraki etaba bakmayı öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Zwischenbilanz", tr: "ara değerlendirme" },
      { de: "zurückblicken", tr: "geriye bakmak" },
      { de: "der Meilenstein", tr: "dönüm noktası" },
      { de: "weiterhin", tr: "bundan böyle de" },
      { de: "die Etappe", tr: "etap" },
    ],
    patterns: [
      { de: "Ohne Deutsch hätte ich …", tr: "olmasaydı ne olurdu" },
      { de: "Ich bin stolz darauf, dass …", tr: "gurur duyulan şeyi söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! B1'in son dersindeyiz. Bugün yeni bir kural yok; bugün öğrendiklerinle kendi yolunu anlatacaksın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki kalıp kullanacağız: olmasaydı ne olurdu ve neyle gurur duyuyorsun. Birincisi dilek kipi, ikincisi yan cümle. Önce kelimeler.")] },
      word("İlk", { de: "die Zwischenbilanz", tr: "ara değerlendirme" }),
      word("İkinci", { de: "zurückblicken", tr: "geriye bakmak" }),
      word("Üçüncü", { de: "der Meilenstein", tr: "dönüm noktası" }),
      word("Dördüncü", { de: "weiterhin", tr: "bundan böyle de" }),
      word("Son", { de: "die Etappe", tr: "etap" }),
      { say: [tr("Kalıbımız:"), de("Ohne Deutsch hätte ich …"), tr("Bir koşul yan cümlesi kurmadan da gerçekdışı anlatılabilir: tümleç bunu tek başına yapıyor.")] },
      { say: [tr("Örnek:"), de("Ohne Deutsch hätte ich diesen Job nie bekommen."), tr("Tekrar edin:"), de("Ohne Deutsch hätte ich diesen Job nie bekommen")], expect: repeat("Ohne Deutsch hätte ich diesen Job nie bekommen") },
      { say: [tr("Sıra sende: 'Bu kurs olmasaydı hâlâ susuyor olurdum.'")], expect: produce("Ohne diesen Kurs würde ich immer noch schweigen", [tr("Tümleç başta, dilek kipi ikinci sırada, mastar sonda:"), de("Ohne diesen Kurs würde ich immer noch schweigen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Pes etmediğim için gurur duyuyorum.'")], expect: produce("Ich bin stolz darauf, dass ich nicht aufgegeben habe", [tr("Edat baştaki kelimede saklı, yan cümlede fiil sonda:"), de("Ich bin stolz darauf, dass ich nicht aufgegeben habe."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Geriye bakınca yol uzun görünüyor.'")], expect: produce("Wenn ich zurückblicke, war der Weg lang", [tr("Yan cümle başta, ana cümle fiille başlar:"), de("Wenn ich zurückblicke, war der Weg lang."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ohne Deutsch ich hätte den Job nicht bekommen."), tr("cümlesi doğru mu?")], expect: truefalse("Ohne Deutsch ich hätte den Job nicht bekommen.", false, [tr("Cümle bir tümleçle başlayınca çekimli fiil ikinci sıraya gelir:"), de("Ohne Deutsch hätte ich den Job nicht bekommen.")]) },
      { say: [tr("Son: 'Bir sonraki etaba hazırım.'")], expect: produce("Ich bin bereit für die nächste Etappe", [tr("Sıfat artı edat öbeği:"), de("Ich bin bereit für die nächste Etappe."), tr("Tekrar dene.")]) },
      { say: [tr("B1'i bitirdin. Konuşmada bir ara değerlendirme yapacaksın: yol nasıl geçti, neyle gurur duyuyorsun, sırada ne var.")] },
    ],
    roleplay: {
      scene: "Öğretmeninle bir ara değerlendirme yapıyorsun: yol nasıl geçti, en zoru neydi, neyle gurur duyuyorsun, bundan sonra ne yapacaksın.",
      partner: "seni baştan beri izlemiş, gurur duyan bir öğretmen",
      opening: "Wir sind am Ende von B1. Blicken Sie mal zurück: Was war für Sie der wichtigste Moment?",
      openingTr: "B1'in sonundayız. Biraz geriye bakın: Sizin için en önemli an neydi?",
      goal: "Yolun nasıl geçtiği, en zoru, gurur duyduğun şey ve sıradaki hedefin anlatılmış olur.",
      minTurns: 9,
    },
  },
];
