import { de, tr, type LectureStep, type Lesson, type Segment } from "../types";

/**
 * B1 · Modül 14 — Beden, bakım ve yaşlanma (131–140).
 *
 * Modül 8 sağlık SİSTEMİNİ öğretmişti: randevu, sevk, sigorta. Bu modül
 * bedenin ve bakımın kendi sözcüklerini veriyor — hangi organın adı ne,
 * kim kime bakıyor, kuşaklar arasında ne konuşuluyor.
 *
 * Havuzun sağlık kümesi modül 8'de büyük ölçüde tükendiği için buradaki
 * sözlükçenin dörtte biri genel B1 sözcüğü. Ama hiçbiri dolgu değil:
 * `brechen` kemik kırılmasında, `stecken` yaraya batan şeyde, `indem`
 * sağlık tavsiyesinde ("hareket ederek"), `aufhalten` yaşlanmayı
 * durdurmakta geçiyor. Kelime dersin cümlesinde yaşamıyorsa alınmadı.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [
      tr(`${n} kelimemiz:`),
      de(w.de),
      tr(`Türkçesi '${w.tr}' demek${note ? ` — ${note}` : ""}. Lütfen`),
      de(w.de),
      tr("deyin."),
    ],
    expect: repeat(w.de),
  };
}

export const deB1B14: Lesson[] = [
  {
    id: "de-b1-koerper-teile",
    icon: "doctor",
    level: "B1",
    course: "de",
    title: "Wo tut es weh?",
    titleTr: "Nerede ağrıyor?",
    summary: "Ağrının yerini edatı sabit fiillerle tarif etmeyi öğretir.",
    minutes: 10,
    focusId: "Verben-mit-Präpositionen",
    vocab: [
      { de: "der Muskel", tr: "kas" },
      { de: "das Knie", tr: "diz" },
      { de: "die Schulter", tr: "omuz" },
      { de: "die Brust", tr: "göğüs" },
      { de: "die Lippe", tr: "dudak" },
      { de: "die Nase", tr: "burun" },
      { de: "der Finger", tr: "parmak" },
      { de: "der Nerv", tr: "sinir" },
    ],
    patterns: [
      { de: "Ich leide an + Dativ", tr: "süregelen bir rahatsızlığı söyler" },
      { de: "Es zieht in + Dativ", tr: "ağrının yerini tarif eder" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ağrıyı tarif edeceğiz. Doktor 'nerede' diye sorunca organın adını bilmek yetmiyor, doğru edatı da bilmek gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bugünkü iki fiil edatını sabit taşıyor ve ikisi de yönelme hâli istiyor. Yanlış edat cümleyi anlaşılmaz yapar. Önce beden sözcükleri.")] },
      word("İlk", { de: "der Muskel", tr: "kas" }),
      word("İkinci", { de: "das Knie", tr: "diz" }),
      word("Üçüncü", { de: "die Schulter", tr: "omuz" }),
      word("Dördüncü", { de: "die Brust", tr: "göğüs" }),
      word("Beşinci", { de: "die Lippe", tr: "dudak" }),
      word("Altıncı", { de: "die Nase", tr: "burun" }),
      word("Yedinci", { de: "der Finger", tr: "parmak" }),
      word("Son", { de: "der Nerv", tr: "sinir" }),
      { say: [tr("İlk kalıbımız süregelen rahatsızlığı söylüyor: bir fiil ve sabit edat. Geçici bir ağrı için değil, aylardır süren için kullanılır.")] },
      { say: [tr("Örnek:"), de("Ich leide seit Wochen an Schmerzen im Knie."), tr("Tekrar edin:"), de("Ich leide seit Wochen an Schmerzen im Knie")], expect: repeat("Ich leide seit Wochen an Schmerzen im Knie") },
      { say: [tr("Sıra sende: 'Aylardır omuz ağrısı çekiyorum.'")], expect: produce("Ich leide seit Monaten an Schulterschmerzen", [tr("Fiilin edatı sabit ve yönelme hâli istiyor:"), de("Ich leide seit Monaten an Schulterschmerzen."), tr("Tekrar dene.")], ["Ich leide seit Monaten an Schmerzen in der Schulter"]) },
      { say: [tr("İkinci kalıbımız ağrının yerini tarif ediyor: çekmek anlamındaki fiil kişisiz kullanılıyor. Türkçedeki 'sancıyor' gibi.")] },
      { say: [tr("Şimdi: 'Kolumda bir çekme var.'")], expect: produce("Es zieht in meinem Arm", [tr("Kişisiz özne, edat yönelme hâli istiyor:"), de("Es zieht in meinem Arm."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich leide auf Rückenschmerzen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich leide auf Rückenschmerzen.", false, [tr("Bu fiilin edatı sabittir ve başka bir edatla değiştirilemez:"), de("Ich leide an Rückenschmerzen.")]) },
      { say: [tr("Son: 'Parmağım uyuştu, sinir sıkışmış olabilir.'")], expect: produce("Mein Finger ist taub, vielleicht ist ein Nerv eingeklemmt", [tr("İki ana cümle; ikincisi zarfla başladığı için fiil ikinci sırada:"), de("Mein Finger ist taub, vielleicht ist ein Nerv eingeklemmt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir doktora ağrının nerede ve ne zamandır olduğunu anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Doktordasın. Ağrının nerede olduğunu, ne zamandır sürdüğünü ve ne yaparken arttığını tarif ediyorsun.",
      partner: "kısa ve net soru soran bir aile hekimi",
      opening: "Guten Tag! Sagen Sie mir bitte genau — wo tut es weh?",
      openingTr: "İyi günler! Bana tam olarak söyleyin — nerede ağrıyor?",
      goal: "Ağrının yeri, süresi ve ne zaman arttığı anlatılmış ve hekim bir sonraki adımı söylemiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-kleine-verletzung",
    icon: "pill",
    level: "B1",
    course: "de",
    title: "Eine kleine Wunde",
    titleTr: "Küçük bir yara",
    summary: "İlk yardımın adımlarını edilgen cümlelerle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Wunde", tr: "yara" },
      { de: "das Pflaster", tr: "yara bandı" },
      { de: "die Spritze", tr: "şırınga" },
      { de: "das Schmerzmittel", tr: "ağrı kesici" },
      { de: "die Infektion", tr: "enfeksiyon" },
      { de: "brechen", tr: "kırmak" },
      { de: "stecken", tr: "sokmak / saplanmak" },
      { de: "der Fall", tr: "vaka / durum" },
    ],
    patterns: [
      { de: "Die Wunde wird gereinigt.", tr: "yapılan işlemi kişisiz anlatır" },
      { de: "In diesem Fall wird … gegeben.", tr: "duruma göre ne yapıldığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Küçük bir kaza oldu. İlk yardım anlatımı tarif gibidir: kimin yaptığı değil, ne yapıldığı önemli. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yüzden edilgen çatı kullanıyoruz: yardımcı fiil ikinci sırada, ortaç en sonda. Önce kelimeler.")] },
      word("İlk", { de: "die Wunde", tr: "yara" }),
      word("İkinci", { de: "das Pflaster", tr: "yara bandı" }),
      word("Üçüncü", { de: "die Spritze", tr: "şırınga" }),
      word("Dördüncü", { de: "das Schmerzmittel", tr: "ağrı kesici" }),
      word("Beşinci", { de: "die Infektion", tr: "enfeksiyon" }),
      word("Altıncı", { de: "brechen", tr: "kırmak" }),
      word("Yedinci", { de: "stecken", tr: "sokmak / saplanmak" }),
      word("Son", { de: "der Fall", tr: "vaka / durum" }),
      { say: [tr("İlk kalıbımız işlemi anlatıyor. Yardımcı fiil ikinci sırada, ortaç sonda; yapan kişi hiç söylenmiyor.")] },
      { say: [tr("Örnek:"), de("Die Wunde wird zuerst gereinigt."), tr("Tekrar edin:"), de("Die Wunde wird zuerst gereinigt")], expect: repeat("Die Wunde wird zuerst gereinigt") },
      { say: [tr("Sıra sende: 'Sonra yara bandı yapıştırılır.'")], expect: produce("Danach wird ein Pflaster aufgeklebt", [tr("Zarf başta olduğu için yardımcı fiil ikinci sırada:"), de("Danach wird ein Pflaster aufgeklebt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız duruma bağlıyor: bir yer tümleci ve edilgen. Tıbbi metinlerde çok geçer.")] },
      { say: [tr("Şimdi: 'Bu durumda ağrı kesici verilir.'")], expect: produce("In diesem Fall wird ein Schmerzmittel gegeben", [tr("Tümleç başta, yardımcı fiil ikinci sırada:"), de("In diesem Fall wird ein Schmerzmittel gegeben."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Spritze wird nur bei einer Infektion geben."), tr("cümlesi doğru mu?")], expect: truefalse("Die Spritze wird nur bei einer Infektion geben.", false, [tr("Edilgende asıl fiil ortaç hâlinde olmalı:"), de("Die Spritze wird nur bei einer Infektion gegeben.")]) },
      { say: [tr("Son: 'Kemik kırıldıysa hasta hastaneye götürülür.'")], expect: produce("Wenn ein Knochen gebrochen ist, wird der Patient ins Krankenhaus gebracht", [tr("Yan cümleden sonra ana cümle yardımcı fiille başlıyor:"), de("Wenn ein Knochen gebrochen ist, wird der Patient ins Krankenhaus gebracht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir ilk yardım kursunda adımları anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir ilk yardım kursundasın. Eğitmene küçük bir yarada hangi adımların hangi sırayla yapıldığını anlatıyorsun.",
      partner: "adımları teker teker sorgulayan bir ilk yardım eğitmeni",
      opening: "Gut. Und was wird gemacht, wenn sich jemand am Finger verletzt?",
      openingTr: "Güzel. Peki biri parmağını yaralarsa ne yapılır?",
      goal: "En az dört adım sırayla ve kişisiz biçimde anlatılmış ve bir istisna söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-vorsorge-alltag",
    icon: "run",
    level: "B1",
    course: "de",
    title: "Gesund bleiben",
    titleTr: "Sağlıklı kalmak",
    summary: "Bir sonuca nasıl varıldığını mastar öbeği ve araç bağlacıyla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Infinitiv-zu",
    vocab: [
      { de: "die Gymnastik", tr: "jimnastik" },
      { de: "schwitzen", tr: "terlemek" },
      { de: "das Vitamin", tr: "vitamin" },
      { de: "der Schnupfen", tr: "nezle" },
      { de: "indem", tr: "-erek" },
      { de: "fest", tr: "sıkı" },
      { de: "halb", tr: "yarım" },
      { de: "rein", tr: "saf / temiz" },
    ],
    patterns: [
      { de: "Es hilft, … zu …", tr: "neyin işe yaradığını söyler" },
      { de: "…, indem man …", tr: "bir şeyin nasıl yapıldığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sağlıklı kalmayı konuşacağız. Tavsiye verirken iki yapı işine yarayacak: neyin yardım ettiği ve bunun nasıl yapıldığı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Biri mastar öbeği, öteki araç bildiren bir bağlaç. İkincisi Türkçedeki '-erek' ekinin tam karşılığı ve fiili sona atıyor. Önce kelimeler.")] },
      word("İlk", { de: "die Gymnastik", tr: "jimnastik" }),
      word("İkinci", { de: "schwitzen", tr: "terlemek" }),
      word("Üçüncü", { de: "das Vitamin", tr: "vitamin" }),
      word("Dördüncü", { de: "der Schnupfen", tr: "nezle" }),
      word("Beşinci", { de: "indem", tr: "-erek" }),
      word("Altıncı", { de: "fest", tr: "sıkı" }),
      word("Yedinci", { de: "halb", tr: "yarım" }),
      word("Son", { de: "rein", tr: "saf / temiz" }),
      { say: [tr("İlk kalıbımız neyin işe yaradığını söylüyor: kişisiz bir fiil ve mastar öbeği. Kimseyi suçlamadan tavsiye verir.")] },
      { say: [tr("Örnek:"), de("Es hilft, jeden Tag Gymnastik zu machen."), tr("Tekrar edin:"), de("Es hilft, jeden Tag Gymnastik zu machen")], expect: repeat("Es hilft, jeden Tag Gymnastik zu machen") },
      { say: [tr("Sıra sende: 'Bol su içmek yardımcı olur.'")], expect: produce("Es hilft, viel Wasser zu trinken", [tr("Mastar öbeğinde nesne mastardan önce:"), de("Es hilft, viel Wasser zu trinken."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız yöntemi söylüyor: araç bağlacı. Bağlaçtan sonra fiil cümlenin en sonuna gider.")] },
      { say: [tr("Şimdi: 'İnsan hareket ederek sağlıklı kalır.'")], expect: produce("Man bleibt gesund, indem man sich bewegt", [tr("Bağlaçtan sonra fiil en sonda:"), de("Man bleibt gesund, indem man sich bewegt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Man vermeidet Schnupfen, indem wäscht man die Hände."), tr("cümlesi doğru mu?")], expect: truefalse("Man vermeidet Schnupfen, indem wäscht man die Hände.", false, [tr("Bu bağlaçtan sonra çekimli fiil cümlenin sonuna gider:"), de("Man vermeidet Schnupfen, indem man die Hände wäscht.")]) },
      { say: [tr("Son: 'Yarım saat yürümek yeter.'")], expect: produce("Eine halbe Stunde zu laufen reicht schon", [tr("Mastar öbeği özne konumunda:"), de("Eine halbe Stunde zu laufen reicht schon."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir arkadaşına sağlıklı kalmak için ne yaptığını anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın sürekli hasta oluyor ve senden tavsiye istiyor. Ne yaptığını ve bunu nasıl yaptığını anlatıyorsun.",
      partner: "her tavsiyeye 'ama nasıl' diye soran bir arkadaş",
      opening: "Du wirst nie krank — was machst du denn anders als ich?",
      openingTr: "Sen hiç hasta olmuyorsun — benden farklı ne yapıyorsun?",
      goal: "En az üç tavsiye verilmiş ve her birinin nasıl uygulandığı söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-schwangerschaft",
    icon: "baby",
    level: "B1",
    course: "de",
    title: "Bald zu dritt",
    titleTr: "Aile büyüyor",
    summary: "Beklenti ve endişeyi yan cümleyle söylemeyi öğretir.",
    minutes: 10,
    focusId: "Nebensatz-dass",
    vocab: [
      { de: "die Schwangerschaft", tr: "hamilelik" },
      { de: "die Geburt", tr: "doğum" },
      { de: "der Nachwuchs", tr: "yeni nesil" },
      { de: "die Erziehung", tr: "terbiye" },
      { de: "das Ehepaar", tr: "evli çift" },
      { de: "die Scheidung", tr: "boşanma" },
      { de: "mitten", tr: "ortasında" },
      { de: "sowieso", tr: "zaten" },
    ],
    patterns: [
      { de: "Ich hoffe, dass …", tr: "umudunu yan cümleyle söyler" },
      { de: "Ich mache mir Sorgen, dass …", tr: "endişesini yan cümleyle söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Ailede büyük bir haber var. Böyle anlarda cümleler hep aynı iki şeyi taşır: umut ve endişe. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkisi de bir yan cümleyle kurulur ve o yan cümlede fiil en sona gider. Önce kelimeler.")] },
      word("İlk", { de: "die Schwangerschaft", tr: "hamilelik" }),
      word("İkinci", { de: "die Geburt", tr: "doğum" }),
      word("Üçüncü", { de: "der Nachwuchs", tr: "yeni nesil" }),
      word("Dördüncü", { de: "die Erziehung", tr: "terbiye" }),
      word("Beşinci", { de: "das Ehepaar", tr: "evli çift" }),
      word("Altıncı", { de: "die Scheidung", tr: "boşanma" }),
      word("Yedinci", { de: "mitten", tr: "ortasında" }),
      word("Son", { de: "sowieso", tr: "zaten" }),
      { say: [tr("İlk kalıbımız umudu söylüyor: umut etmek fiili ve bağlaç. Bağlaçtan sonra fiil sona gidiyor.")] },
      { say: [tr("Örnek:"), de("Ich hoffe, dass die Geburt gut verläuft."), tr("Tekrar edin:"), de("Ich hoffe, dass die Geburt gut verläuft")], expect: repeat("Ich hoffe, dass die Geburt gut verläuft") },
      { say: [tr("Sıra sende: 'Hamileliğin sorunsuz geçmesini umuyorum.'")], expect: produce("Ich hoffe, dass die Schwangerschaft ohne Probleme verläuft", [tr("Bağlaçtan sonra fiil en sonda:"), de("Ich hoffe, dass die Schwangerschaft ohne Probleme verläuft."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız endişeyi söylüyor: dönüşlü bir öbek ve aynı bağlaç. Dönüşlü zamir fiilden hemen sonra geliyor.")] },
      { say: [tr("Şimdi: 'Zamanın yetmeyeceğinden endişeleniyorum.'")], expect: produce("Ich mache mir Sorgen, dass die Zeit nicht reicht", [tr("Dönüşlü zamir başta, bağlaçtan sonra fiil sonda:"), de("Ich mache mir Sorgen, dass die Zeit nicht reicht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich hoffe, dass wird die Erziehung leichter."), tr("cümlesi doğru mu?")], expect: truefalse("Ich hoffe, dass wird die Erziehung leichter.", false, [tr("Bağlaçtan sonra fiil öne gelmez, sona gider:"), de("Ich hoffe, dass die Erziehung leichter wird.")]) },
      { say: [tr("Son: 'İşin ortasındayız, zaten çok yorgunuz.'")], expect: produce("Wir sind mitten in der Arbeit und sowieso schon müde", [tr("İki bölüm bağlaçla birleşiyor, ikinci bölümde fiil tekrarlanmıyor:"), de("Wir sind mitten in der Arbeit und sowieso schon müde."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi yakın bir arkadaşınla haberi ve endişelerini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Ailede bir bebek bekleniyor. Yakın bir arkadaşınla haberi, umutlarını ve endişelerini konuşuyorsun.",
      partner: "aynı yoldan geçmiş, deneyimini paylaşan bir arkadaş",
      opening: "Das sind ja tolle Neuigkeiten! Und — wie geht es dir damit?",
      openingTr: "Ne harika bir haber! Peki — sen bu konuda nasılsın?",
      goal: "Haber paylaşılmış, en az bir umut ve bir endişe yan cümleyle söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-familie-gross",
    icon: "family",
    level: "B1",
    course: "de",
    title: "Die große Familie",
    titleTr: "Kalabalık aile",
    summary: "Akrabaları yönelme hâlli ilgi cümleleriyle tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Dativ",
    vocab: [
      { de: "der Enkel", tr: "erkek torun" },
      { de: "die Enkelin", tr: "kız torun" },
      { de: "der Neffe", tr: "erkek yeğen" },
      { de: "die Nichte", tr: "kız yeğen" },
      { de: "der Cousin", tr: "kuzen" },
      { de: "die Cousine", tr: "kuzin" },
      { de: "der Onkel", tr: "amca / dayı" },
      { de: "die Tante", tr: "teyze / hala" },
    ],
    patterns: [
      { de: "der Neffe, dem ich …", tr: "yönelme isteyen fiillerde ilgi zamiri" },
      { de: "die Tante, der wir …", tr: "dişil adda yönelme hâlli ilgi zamiri" },
    ],
    lecture: [
      { say: [tr("Merhaba! Kalabalık bir ailede kimin kim olduğunu anlatmak zordur. İlgi cümlesi bunu tek cümlede çözer. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yönelme isteyen fiillerde ilgi zamiri de yönelme hâline girer ve eril ile nötr adda aynı biçimi alır. Dişilde başka bir biçim gelir. Önce kelimeler.")] },
      word("İlk", { de: "der Enkel", tr: "erkek torun" }),
      word("İkinci", { de: "die Enkelin", tr: "kız torun" }),
      word("Üçüncü", { de: "der Neffe", tr: "erkek yeğen" }),
      word("Dördüncü", { de: "die Nichte", tr: "kız yeğen" }),
      word("Beşinci", { de: "der Cousin", tr: "kuzen" }),
      word("Altıncı", { de: "die Cousine", tr: "kuzin" }),
      word("Yedinci", { de: "der Onkel", tr: "amca / dayı" }),
      word("Son", { de: "die Tante", tr: "teyze / hala" }),
      { say: [tr("İlk kalıbımız eril bir adı tanımlıyor. Yardım etmek fiili yönelme hâli istediği için ilgi zamiri de yönelme hâlinde.")] },
      { say: [tr("Örnek:"), de("Das ist der Neffe, dem ich bei den Hausaufgaben helfe."), tr("Tekrar edin:"), de("Das ist der Neffe, dem ich bei den Hausaufgaben helfe")], expect: repeat("Das ist der Neffe, dem ich bei den Hausaufgaben helfe") },
      { say: [tr("Sıra sende: 'Bu, her hafta yazdığım kuzenim.'")], expect: produce("Das ist der Cousin, dem ich jede Woche schreibe", [tr("Yazmak fiili yönelme hâli istiyor:"), de("Das ist der Cousin, dem ich jede Woche schreibe."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız dişil bir adı tanımlıyor. Yönelme hâlinde dişil ilgi zamiri farklı bir biçim alıyor — Türkçe konuşanın en sık kaydığı yer burası.")] },
      { say: [tr("Şimdi: 'Bu, çiçek götürdüğümüz teyzem.'")], expect: produce("Das ist die Tante, der wir Blumen gebracht haben", [tr("Dişil adda yönelme hâlli ilgi zamiri başka bir biçim alır:"), de("Das ist die Tante, der wir Blumen gebracht haben."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist die Nichte, die ich oft helfe."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist die Nichte, die ich oft helfe.", false, [tr("Yardım etmek fiili yönelme hâli ister, o yüzden dişil zamir de değişir:"), de("Das ist die Nichte, der ich oft helfe.")]) },
      { say: [tr("Son: 'Bu, güvendiğimiz kız torunumuz.'")], expect: produce("Das ist die Enkelin, der wir vertrauen", [tr("Güvenmek fiili de yönelme hâli istiyor:"), de("Das ist die Enkelin, der wir vertrauen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir aile fotoğrafındaki kişileri tanıtacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına aile fotoğrafını gösteriyorsun. Kimin kim olduğunu ve her biriyle ilişkini ilgi cümleleriyle anlatıyorsun.",
      partner: "fotoğraftaki herkesi sorup akrabalık bağını çözmeye çalışan bir arkadaş",
      opening: "So viele Leute! Wer ist denn wer auf diesem Foto?",
      openingTr: "Ne çok insan! Bu fotoğrafta kim kim?",
      goal: "En az dört akraba tanıtılmış ve her biriyle ilişki ilgi cümlesiyle anlatılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-generationen",
    icon: "calendar",
    level: "B1",
    course: "de",
    title: "Zwischen den Generationen",
    titleTr: "Kuşaklar arasında",
    summary: "Geçmişte bir kez olan olayı als bağlacıyla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-als",
    vocab: [
      { de: "die Generation", tr: "kuşak" },
      { de: "die Jugend", tr: "gençlik" },
      { de: "der Krieg", tr: "savaş" },
      { de: "die Jugendliche", tr: "genç kız" },
      { de: "zerstören", tr: "yok etmek" },
      { de: "die Verwandte", tr: "kadın akraba" },
      { de: "der Tod", tr: "ölüm" },
      { de: "verraten", tr: "sırrını söylemek" },
    ],
    patterns: [
      { de: "Als meine Großmutter jung war, …", tr: "geçmişte tek seferlik dönemi anlatır" },
      { de: "Heute ist das anders, weil …", tr: "bugünkü farkı gerekçelendirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kuşakları konuşacağız: büyüklerin gençliği nasıldı, bugün ne değişti. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Geçmişte tek seferlik bir dönemi anlatan bağlaç, tekrarlananınkinden ayrıdır. Bir dönem de tek seferlik sayılır — bu ayrımı Türkçe yapmaz. Önce kelimeler.")] },
      word("İlk", { de: "die Generation", tr: "kuşak" }),
      word("İkinci", { de: "die Jugend", tr: "gençlik" }),
      word("Üçüncü", { de: "der Krieg", tr: "savaş" }),
      word("Dördüncü", { de: "die Jugendliche", tr: "genç kız" }, "eril biçimi A1 seviyesinde öğrenildi"),
      word("Beşinci", { de: "zerstören", tr: "yok etmek" }),
      word("Altıncı", { de: "die Verwandte", tr: "kadın akraba" }),
      word("Yedinci", { de: "der Tod", tr: "ölüm" }),
      word("Son", { de: "verraten", tr: "sırrını söylemek" }),
      { say: [tr("İlk bağlacımız geçmişteki bir dönemi anlatıyor. Yan cümlede fiil sona gider, yan cümle başta olursa ana cümle fiille başlar.")] },
      { say: [tr("Örnek:"), de("Als meine Großmutter jung war, gab es kein Telefon."), tr("Tekrar edin:"), de("Als meine Großmutter jung war, gab es kein Telefon")], expect: repeat("Als meine Großmutter jung war, gab es kein Telefon") },
      { say: [tr("Sıra sende: 'Babam gençken herkes daha erken çalışırdı.'")], expect: produce("Als mein Vater jung war, arbeiteten alle früher", [tr("Yan cümlede fiil sonda, ana cümle fiille başlıyor:"), de("Als mein Vater jung war, arbeiteten alle früher."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız bugünkü farkı gerekçelendiriyor: sebep bağlacı, fiil yine sonda.")] },
      { say: [tr("Şimdi: 'Bugün bu farklı, çünkü gençlerin başka olanakları var.'")], expect: produce("Heute ist das anders, weil die Jugendlichen andere Möglichkeiten haben", [tr("Sebep bağlacından sonra fiil en sonda:"), de("Heute ist das anders, weil die Jugendlichen andere Möglichkeiten haben."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn mein Onkel ein Kind war, wohnte er auf dem Land."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn mein Onkel ein Kind war, wohnte er auf dem Land.", false, [tr("Geçmişteki tek bir dönem için başka bir bağlaç gerekir:"), de("Als mein Onkel ein Kind war, wohnte er auf dem Land.")]) },
      { say: [tr("Son: 'Bir akrabam bana ailenin sırrını söyledi.'")], expect: produce("Eine Verwandte hat mir das Geheimnis der Familie verraten", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Eine Verwandte hat mir das Geheimnis der Familie verraten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi kendi ailende kuşaklar arasındaki farkı anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla kuşak farkını konuşuyorsunuz: büyüklerinizin gençliği nasıldı, bugün ne değişti, ne aynı kaldı.",
      partner: "kendi büyüklerinin hikâyesini de anlatan bir arkadaş",
      opening: "Erzähl mal — wie war das eigentlich, als deine Großeltern jung waren?",
      openingTr: "Anlatsana — büyükanne ve büyükbaban gençken nasıldı?",
      goal: "Geçmişteki bir dönem anlatılmış, bugünle en az iki fark gerekçesiyle söylenmiş olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-pflege-zuhause",
    icon: "doctor",
    level: "B1",
    course: "de",
    title: "Wer kümmert sich?",
    titleTr: "Bakımı kim üstlenir?",
    summary: "Bir düzenlemenin amacını damit yan cümlesiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-damit",
    vocab: [
      { de: "die Betreuung", tr: "bakım" },
      { de: "der Betreuer", tr: "bakıcı" },
      { de: "der Pfleger", tr: "hastabakıcı" },
      { de: "der Krankenpfleger", tr: "erkek hemşire" },
      { de: "das Altenheim", tr: "huzurevi" },
      { de: "die Senioren", tr: "yaşlılar" },
      { de: "der Halt", tr: "dayanak" },
      { de: "die Liste", tr: "liste" },
    ],
    patterns: [
      { de: "…, damit sie nicht allein sind", tr: "amaç söyler; özne farklı olduğunda kullanılır" },
      { de: "Wir teilen uns die Aufgaben.", tr: "iş bölümünü söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Ailede biri bakıma muhtaç ve bunu kimin üstleneceğini konuşacaksınız. Her kararın bir amacı var ve o amacı söylemek gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amaç bağlacı özne farklı olduğunda kullanılır: ben yapıyorum ki O rahat etsin. Bağlaçtan sonra fiil sona gider. Önce kelimeler.")] },
      word("İlk", { de: "die Betreuung", tr: "bakım" }),
      word("İkinci", { de: "der Betreuer", tr: "bakıcı" }),
      word("Üçüncü", { de: "der Pfleger", tr: "hastabakıcı" }),
      word("Dördüncü", { de: "der Krankenpfleger", tr: "erkek hemşire" }),
      word("Beşinci", { de: "das Altenheim", tr: "huzurevi" }),
      word("Altıncı", { de: "die Senioren", tr: "yaşlılar" }, "hep çoğul kullanılır"),
      word("Yedinci", { de: "der Halt", tr: "dayanak" }),
      word("Son", { de: "die Liste", tr: "liste" }),
      { say: [tr("İlk kalıbımız amacı söylüyor. Bağlaçtan sonra çekimli fiil cümlenin en sonuna gider.")] },
      { say: [tr("Örnek:"), de("Wir besuchen sie oft, damit sie nicht allein sind."), tr("Tekrar edin:"), de("Wir besuchen sie oft, damit sie nicht allein sind")], expect: repeat("Wir besuchen sie oft, damit sie nicht allein sind") },
      { say: [tr("Sıra sende: 'Bir liste yapıyoruz ki kimse unutulmasın.'")], expect: produce("Wir machen eine Liste, damit niemand vergessen wird", [tr("Bağlaçtan sonra fiil en sonda:"), de("Wir machen eine Liste, damit niemand vergessen wird."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız iş bölümünü söylüyor: dönüşlü bir fiil. Dönüşlü zamir burada 'birbirimiz arasında' anlamı taşıyor.")] },
      { say: [tr("Şimdi: 'Görevleri paylaşıyoruz.'")], expect: produce("Wir teilen uns die Aufgaben", [tr("Dönüşlü zamir fiilden hemen sonra:"), de("Wir teilen uns die Aufgaben."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich rufe jeden Tag an, damit sie hat einen Halt."), tr("cümlesi doğru mu?")], expect: truefalse("Ich rufe jeden Tag an, damit sie hat einen Halt.", false, [tr("Amaç bağlacından sonra fiil öne gelmez, sona gider:"), de("Ich rufe jeden Tag an, damit sie einen Halt hat.")]) },
      { say: [tr("Son: 'Bir bakıcı tutuyoruz ki kardeşim işine devam edebilsin.'")], expect: produce("Wir nehmen einen Betreuer, damit meine Schwester weiterarbeiten kann", [tr("Bağlaçtan sonra modal fiil en sonda:"), de("Wir nehmen einen Betreuer, damit meine Schwester weiterarbeiten kann."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi kardeşinle bakımın nasıl paylaşılacağını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Kardeşinle bir büyüğünüzün bakımını nasıl paylaşacağınızı konuşuyorsunuz: kim ne yapacak, huzurevi mi ev bakımı mı, her kararın amacı ne.",
      partner: "işi yoğun ama sorumluluk almak isteyen kardeşin",
      opening: "Wir müssen das jetzt wirklich klären — wer übernimmt was?",
      openingTr: "Bunu artık gerçekten netleştirmeliyiz — kim neyi üstleniyor?",
      goal: "İş bölümü yapılmış, her kararın amacı söylenmiş ve bir sonraki adım kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-in-pension",
    icon: "clock",
    level: "B1",
    course: "de",
    title: "In Pension",
    titleTr: "Emeklilik",
    summary: "Yaşam biçimlerini karşılaştırmayı ve tercihini söylemeyi öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "der Pensionist", tr: "emekli" },
      { de: "die Pension", tr: "pansiyon" },
      { de: "selber", tr: "kendi" },
      { de: "aufhalten", tr: "alıkoymak" },
      { de: "ziehen", tr: "çekmek" },
      { de: "die Badewanne", tr: "küvet" },
      { de: "Achtung!", tr: "Dikkat!" },
      { de: "die Ordination", tr: "muayenehane" },
    ],
    patterns: [
      { de: "Früher war ich schneller als heute.", tr: "eskiyle bugünü karşılaştırır" },
      { de: "Ich mache das lieber selber.", tr: "kendi yapmayı tercih ettiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün emeklilik konuşacağız. Bu yaşta konuşmanın çoğu karşılaştırmadır: eskiden nasıldı, şimdi nasıl. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karşılaştırmada sıfat ek alır; tercih söylerken ise sevmek zarfının karşılaştırma biçimi kullanılır. Önce kelimeler.")] },
      word("İlk", { de: "der Pensionist", tr: "emekli" }, "Avusturya'da yaygın biçim"),
      word("İkinci", { de: "die Pension", tr: "pansiyon" }, "aynı sözcük emekli maaşı anlamına da gelir"),
      word("Üçüncü", { de: "selber", tr: "kendi" }),
      word("Dördüncü", { de: "aufhalten", tr: "alıkoymak" }),
      word("Beşinci", { de: "ziehen", tr: "çekmek" }),
      word("Altıncı", { de: "die Badewanne", tr: "küvet" }),
      word("Yedinci", { de: "Achtung!", tr: "Dikkat!" }),
      word("Son", { de: "die Ordination", tr: "muayenehane" }, "Avusturya'da doktor muayenehanesi"),
      { say: [tr("İlk kalıbımız eskiyle bugünü karşılaştırıyor: zaman zarfı, sıfatın karşılaştırma biçimi ve kıyas sözcüğü.")] },
      { say: [tr("Örnek:"), de("Früher war ich schneller als heute."), tr("Tekrar edin:"), de("Früher war ich schneller als heute")], expect: repeat("Früher war ich schneller als heute") },
      { say: [tr("Sıra sende: 'Eskiden merdivenler bugünkünden kolaydı.'")], expect: produce("Früher waren die Treppen leichter als heute", [tr("Çoğul özne, sıfat karşılaştırma ekiyle:"), de("Früher waren die Treppen leichter als heute."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız tercihi söylüyor: sevmek zarfının karşılaştırma biçimi. Bağımsızlık konusunda çok geçer.")] },
      { say: [tr("Şimdi: 'Bunu kendim yapmayı tercih ederim.'")], expect: produce("Ich mache das lieber selber", [tr("Tercih zarfı fiilden sonra:"), de("Ich mache das lieber selber."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Heute bin ich mehr langsam als früher."), tr("cümlesi doğru mu?")], expect: truefalse("Heute bin ich mehr langsam als früher.", false, [tr("Karşılaştırma ayrı bir zarfla değil, sıfata gelen ekle yapılır:"), de("Heute bin ich langsamer als früher.")]) },
      { say: [tr("Son: 'Yaşlanmayı kimse durduramaz.'")], expect: produce("Das Alter kann niemand aufhalten", [tr("Nesne başta, modal fiil ikinci sırada, mastar sonda:"), de("Das Alter kann niemand aufhalten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi emekli bir komşunla günlük hayatın nasıl değiştiğini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Emekli bir komşunla sohbet ediyorsun: neyin eskisi gibi olmadığını, neyi hâlâ kendi yaptığını, nerede yardım istediğini konuşuyorsunuz.",
      partner: "bağımsızlığına düşkün, esprili bir emekli komşu",
      opening: "Ach, wissen Sie — früher ging das alles viel schneller. Wie ist das bei Ihnen?",
      openingTr: "Ah, bilirsiniz — eskiden her şey çok daha hızlı oluyordu. Sizde nasıl?",
      goal: "En az üç karşılaştırma yapılmış, bir tercih söylenmiş ve bir yardım teklifi konuşulmuş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-beim-friseur",
    icon: "shopping",
    level: "B1",
    course: "de",
    title: "Beim Friseur",
    titleTr: "Kuaförde",
    summary: "İstediğini dilek kipiyle kibarca tarif etmeyi öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "der Friseur", tr: "kuaför" },
      { de: "die Friseurin", tr: "kadın kuaför" },
      { de: "die Frisur", tr: "saç modeli" },
      { de: "der Bart", tr: "sakal" },
      { de: "die Bürste", tr: "fırça" },
      { de: "die Zahnbürste", tr: "diş fırçası" },
      { de: "der Salon", tr: "salon" },
      { de: "die Drogerie", tr: "kozmetik mağazası" },
    ],
    patterns: [
      { de: "Ich hätte gern …", tr: "kibarca ne istediğini söyler" },
      { de: "Könnten Sie … etwas kürzer machen?", tr: "kibarca bir düzeltme ister" },
    ],
    lecture: [
      { say: [tr("Merhaba! Kuaförde en zor şey ne istediğini tarif etmek. Almancada bunun kibar biçimi dilek kipiyle kurulur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dilek kipi burada istekleri yumuşatıyor. Ama dikkat: yumuşak olması belirsiz olması demek değil, ne istediğini yine net söylemelisin. Önce kelimeler.")] },
      word("İlk", { de: "der Friseur", tr: "kuaför" }),
      word("İkinci", { de: "die Friseurin", tr: "kadın kuaför" }),
      word("Üçüncü", { de: "die Frisur", tr: "saç modeli" }),
      word("Dördüncü", { de: "der Bart", tr: "sakal" }),
      word("Beşinci", { de: "die Bürste", tr: "fırça" }),
      word("Altıncı", { de: "die Zahnbürste", tr: "diş fırçası" }),
      word("Yedinci", { de: "der Salon", tr: "salon" }),
      word("Son", { de: "die Drogerie", tr: "kozmetik mağazası" }, "ilaç değil bakım ürünü satar"),
      { say: [tr("İlk kalıbımız isteği söylüyor: sahip olmak fiilinin dilek kipi artı hoşuma gider zarfı.")] },
      { say: [tr("Örnek:"), de("Ich hätte gern die gleiche Frisur wie letztes Mal."), tr("Tekrar edin:"), de("Ich hätte gern die gleiche Frisur wie letztes Mal")], expect: repeat("Ich hätte gern die gleiche Frisur wie letztes Mal") },
      { say: [tr("Sıra sende: 'Sakalımı kısa isterim.'")], expect: produce("Ich hätte gern den Bart kurz", [tr("İstek kalıbı, sonra nesne ve sıfat:"), de("Ich hätte gern den Bart kurz."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız düzeltme istiyor: yapabilmek fiilinin dilek kipiyle soru. İş sürerken müdahale etmenin kibar yolu.")] },
      { say: [tr("Şimdi: 'Yanlarını biraz daha kısa yapabilir misiniz?'")], expect: produce("Könnten Sie die Seiten etwas kürzer machen", [tr("Dilek kipi başta, mastar sonda:"), de("Könnten Sie die Seiten etwas kürzer machen?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich hätte gern, dass Sie machen die Haare kürzer."), tr("cümlesi doğru mu?")], expect: truefalse("Ich hätte gern, dass Sie machen die Haare kürzer.", false, [tr("Bağlaçtan sonra fiil cümlenin sonuna gider:"), de("Ich hätte gern, dass Sie die Haare kürzer machen.")]) },
      { say: [tr("Son: 'Böyle bir fırçayı nereden alabilirim?'")], expect: produce("Wo könnte ich so eine Bürste kaufen", [tr("Soru sözcüğü başta, dilek kipi ikinci sırada, mastar sonda:"), de("Wo könnte ich so eine Bürste kaufen?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi kuaförde ne istediğini tarif edeceksin.")] },
    ],
    roleplay: {
      scene: "Kuafördesin. Ne istediğini tarif ediyor, iş sürerken bir düzeltme rica ediyor ve sonunda bir ürün soruyorsun.",
      partner: "konuşkan, her adımı soran bir kuaför",
      opening: "Bitte nehmen Sie Platz! Und — was hätten Sie gern heute?",
      openingTr: "Buyurun oturun! Peki — bugün ne yaptırmak istersiniz?",
      goal: "İstenen model tarif edilmiş, bir düzeltme rica edilmiş ve bir ürün sorulmuş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-sucht-gespraech",
    icon: "feelings",
    level: "B1",
    course: "de",
    title: "Darüber sprechen",
    titleTr: "Zor bir konuyu açmak",
    summary: "Çekince belirterek zor bir konuyu açmayı obwohl bağlacıyla öğretir.",
    minutes: 11,
    focusId: "Nebensatz-obwohl",
    vocab: [
      { de: "die Droge", tr: "uyuşturucu" },
      { de: "das Suchtmittel", tr: "bağımlılık yapan madde" },
      { de: "der Raucher", tr: "sigara içen" },
      { de: "der Nichtraucher", tr: "sigara içmeyen" },
      { de: "betrunken", tr: "sarhoş" },
      { de: "sich verstecken", tr: "saklanmak" },
      { de: "fangen", tr: "yakalamak" },
      { de: "das Opfer", tr: "kurban" },
    ],
    patterns: [
      { de: "Obwohl es schwer ist, …", tr: "çekince belirterek yine de bir şey söyler" },
      { de: "Ich mache dir keinen Vorwurf.", tr: "suçlamadığını açıkça söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün zor bir konuyu açacağız. Böyle konuşmalarda tek kural var: suçlamadan söylemek. Çekince bağlacı bunu sağlıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Çekince bağlacı 'zor ama yine de' der. Yan cümlede fiil sona gider ve yan cümle başta olursa ana cümle fiille başlar. Önce kelimeler.")] },
      word("İlk", { de: "die Droge", tr: "uyuşturucu" }),
      word("İkinci", { de: "das Suchtmittel", tr: "bağımlılık yapan madde" }),
      word("Üçüncü", { de: "der Raucher", tr: "sigara içen" }),
      word("Dördüncü", { de: "der Nichtraucher", tr: "sigara içmeyen" }),
      word("Beşinci", { de: "betrunken", tr: "sarhoş" }),
      word("Altıncı", { de: "sich verstecken", tr: "saklanmak" }),
      word("Yedinci", { de: "fangen", tr: "yakalamak" }),
      word("Son", { de: "das Opfer", tr: "kurban" }),
      { say: [tr("İlk kalıbımız çekince belirtiyor. Zor olduğunu kabul ediyorsun ama yine de söylüyorsun — bu ikisi bir arada olunca konuşma kavgaya dönmüyor.")] },
      { say: [tr("Örnek:"), de("Obwohl es schwer ist, möchte ich mit dir darüber reden."), tr("Tekrar edin:"), de("Obwohl es schwer ist, möchte ich mit dir darüber reden")], expect: repeat("Obwohl es schwer ist, möchte ich mit dir darüber reden") },
      { say: [tr("Sıra sende: 'Kızmayacağını bilsem de endişeleniyorum.'")], expect: produce("Obwohl ich weiß, dass du nicht böse wirst, mache ich mir Sorgen", [tr("İki yan cümle iç içe, ana cümle fiille başlıyor:"), de("Obwohl ich weiß, dass du nicht böse wirst, mache ich mir Sorgen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız suçlamadığını açıkça söylüyor. Bu cümle olmadan çekince bağlacı bile yetmez.")] },
      { say: [tr("Şimdi: 'Sana bir suçlama yöneltmiyorum.'")], expect: produce("Ich mache dir keinen Vorwurf", [tr("Yönelme hâlindeki kişi fiilden hemen sonra:"), de("Ich mache dir keinen Vorwurf."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Obwohl er Nichtraucher ist, er raucht manchmal."), tr("cümlesi doğru mu?")], expect: truefalse("Obwohl er Nichtraucher ist, er raucht manchmal.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar, özneyle değil:"), de("Obwohl er Nichtraucher ist, raucht er manchmal.")]) },
      { say: [tr("Son: 'Saklanmana rağmen seni yalnız bırakmayacağım.'")], expect: produce("Obwohl du dich versteckst, lasse ich dich nicht allein", [tr("Yan cümlede dönüşlü fiil sonda, ana cümle fiille başlıyor:"), de("Obwohl du dich versteckst, lasse ich dich nicht allein."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi yakın birine zor bir konuyu suçlamadan açacaksın.")] },
    ],
    roleplay: {
      scene: "Yakın bir arkadaşının son zamanlarda çok içtiğini fark ettin. Konuyu suçlamadan açıyor, endişeni söylüyor ve yardım teklif ediyorsun.",
      partner: "önce konuyu değiştirmeye çalışan ama sonra dinleyen bir arkadaş",
      opening: "Was ist denn los? Du guckst so ernst — ist irgendwas passiert?",
      openingTr: "Ne oldu? Çok ciddi bakıyorsun — bir şey mi oldu?",
      goal: "Konu suçlamadan açılmış, endişe söylenmiş ve somut bir yardım teklif edilmiş olur.",
      minTurns: 9,
    },
  },
];
