import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 2 — Müzakere ve şikâyet (011–020).
 *
 * Bu modülün konusu tek kelimeyle DİPLOMASİ. B1'de öğrenci itirazını
 * söyleyebiliyordu; B2'de itirazını karşı tarafı kaybetmeden söylemesi
 * gerekiyor ve Almanca bunu iki araçla yapıyor: dilek kipi (karar yerine
 * öneri) ve isimleşmiş resmî dil (kişi yerine mesele).
 *
 * Türkçe konuşan için tuzak şurada: Türkçede sertlik tonla ayarlanır, Almanca
 * yazışmada ise DİLBİLGİSİYLE. "Fesih ediyorum" ile "kendimi feshetmek
 * zorunda görüyorum" arasındaki fark bir kibarlık süsü değil, hukuki bir
 * kayıt farkıdır — ve bu modül o farkı çalıştırıyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B02: Lesson[] = [
  {
    id: "de-b2-verhandeln",
    icon: "money",
    level: "B2",
    course: "de",
    title: "Der Preis ist verhandelbar",
    titleTr: "Pazarlık",
    summary: "Fiyat ve koşul pazarlığını dilek kipiyle, kapıyı kapatmadan yürütmeyi öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "verhandeln", tr: "pazarlık etmek" },
      { de: "der Preisnachlass", tr: "fiyat indirimi" },
      { de: "die Geschäftsbedingungen", tr: "sözleşme koşulları" },
      { de: "der Vertragspartner", tr: "sözleşme tarafı" },
      { de: "der Tarif", tr: "tarife" },
      { de: "zusichern", tr: "taahhüt etmek" },
      { de: "unterbieten", tr: "altına inmek" },
      { de: "überteuert", tr: "fahiş fiyatlı" },
    ],
    patterns: [
      { de: "Wir könnten uns … vorstellen.", tr: "teklifi öneri olarak sunar" },
      { de: "Kämen Sie uns bei … entgegen?", tr: "karşı taraftan jest ister" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: müzakere. Pazarlıkta Almancanın kuralı basit — kesin cümle kurarsan karşı tarafın geri adım alanı kalmaz. O yüzden teklif dilek kipiyle söylenir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Kırk euro veriyoruz' bir karardır; 'kırk euroyu düşünebiliriz' bir tekliftir. İkisi de aynı rakam ama ikincisi konuşmayı sürdürür. Önce kelimeler.")] },
      word("İlk", { de: "verhandeln", tr: "pazarlık etmek" }),
      word("İkinci", { de: "der Preisnachlass", tr: "fiyat indirimi" }),
      word("Üçüncü", { de: "die Geschäftsbedingungen", tr: "sözleşme koşulları" }, "Sözleşmenin arkasındaki küçük yazılar."),
      word("Dördüncü", { de: "der Vertragspartner", tr: "sözleşme tarafı" }),
      word("Beşinci", { de: "der Tarif", tr: "tarife" }),
      word("Altıncı", { de: "zusichern", tr: "taahhüt etmek" }),
      word("Yedinci", { de: "unterbieten", tr: "altına inmek" }, "Rakibin fiyatının altına inmek."),
      word("Son", { de: "überteuert", tr: "fahiş fiyatlı" }),
      { say: [tr("Kalıbımız:"), de("Wir könnten uns … vorstellen."), tr("Kelimesi kelimesine 'düşünebilirdik'; iş dilinde 'şuna varız' demektir.")] },
      { say: [tr("Örnek:"), de("Wir könnten uns einen Preis von vierzig Euro vorstellen."), tr("Tekrar edin:"), de("Wir könnten uns einen Preis von vierzig Euro vorstellen")], expect: repeat("Wir könnten uns einen Preis von vierzig Euro vorstellen") },
      { say: [tr("Sıra sende: 'Bu siparişte bir fiyat indirimi mümkün olur muydu?'")], expect: produce("Wäre bei diesem Auftrag ein Preisnachlass möglich", [tr("Dilek kipi başta soru kurar; sıfat en sonda:"), de("Wäre bei diesem Auftrag ein Preisnachlass möglich?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi jest iste: 'Miktar konusunda bize biraz yaklaşır mısınız?'")], expect: produce("Kämen Sie uns bei der Menge entgegen", [tr("Gelmek fiilinin dilek kipi kämen; ayrılabilen önek sonda:"), de("Kämen Sie uns bei der Menge entgegen?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu koşullarla kabul edebilirdik.'")], expect: produce("Zu diesen Geschäftsbedingungen könnten wir zusagen", [tr("Tümleç başta, dilek kipi ikinci sırada, mastar sonda:"), de("Zu diesen Geschäftsbedingungen könnten wir zusagen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Kämen Sie uns bei der Menge entgegen?"), tr("cümlesi doğru mu?")], expect: truefalse("Kämen Sie uns bei der Menge entgegen?", true, [tr("Doğru. Dilek kipi soruyu bir ricaya çeviriyor ve ayrılabilen fiilin öneki cümlenin sonunda duruyor.")]) },
      { say: [tr("Son: 'Ortada bir yerde anlaşalım.'")], expect: produce("Einigen wir uns auf die Mitte", [tr("Rica biçiminde fiil başta; dönüşlü zamir hemen sonra:"), de("Einigen wir uns auf die Mitte."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir tedarikçiyle fiyat pazarlığı yapacaksın: teklifini sun, jest iste ve bir rakamda anlaş.")] },
    ],
    roleplay: {
      scene: "Bir tedarikçiyle yıllık sözleşmenin fiyatını pazarlık ediyorsun. Teklifini dilek kipiyle sun, jest iste, karşı teklife tepki ver ve bir rakamda ya da koşulda anlaş.",
      partner: "deneyimli, kolay indirim vermeyen ama ilişkiyi önemseyen bir satış müdürü",
      opening: "Unser Angebot liegt bei achtundvierzig Euro pro Einheit. Was schwebt Ihnen denn vor?",
      openingTr: "Teklifimiz birim başına kırk sekiz euro. Sizin aklınızda ne var?",
      goal: "Karşılıklı teklifler sunulmuş ve bir fiyat ya da koşul üzerinde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-beschwerde-formell",
    icon: "mail",
    level: "B2",
    course: "de",
    title: "Die formelle Beschwerde",
    titleTr: "Resmî şikâyet",
    summary: "Resmî şikâyet mektubunun isimleşmiş, mesafeli dilini kurmayı öğretir.",
    minutes: 12,
    focusId: "Nominalisierung",
    vocab: [
      { de: "die Beschwerde", tr: "şikâyet" },
      { de: "die Stellungnahme", tr: "görüş bildirme" },
      { de: "der Schriftverkehr", tr: "yazışma" },
      { de: "die Unterlage", tr: "evrak" },
      { de: "der Nachweis", tr: "kanıt" },
      { de: "der Ansprechpartner", tr: "muhatap" },
      { de: "mahnen", tr: "ihtar etmek" },
      { de: "unzumutbar", tr: "kabul edilemez" },
    ],
    patterns: [
      { de: "Bezug nehmend auf …", tr: "yazıya atıf yapar" },
      { de: "Ich sehe mich gezwungen, … zu …", tr: "mecburiyeti mesafeli söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün resmî şikâyet yazacağız. Burada dikkat: Almanca resmî yazışmada öfke tonla değil, dilbilgisiyle taşınır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kilit fark şu: 'sözleşmeyi feshediyorum' bir tehdittir, 'kendimi feshetmek zorunda görüyorum' bir kayıttır. İkincisi daha sert bir belgedir ama daha kibar durur. Önce kelimeler.")] },
      word("İlk", { de: "die Beschwerde", tr: "şikâyet" }),
      word("İkinci", { de: "die Stellungnahme", tr: "görüş bildirme" }),
      word("Üçüncü", { de: "der Schriftverkehr", tr: "yazışma" }, "Bir dosyadaki bütün gidip gelen yazılar."),
      word("Dördüncü", { de: "die Unterlage", tr: "evrak" }),
      word("Beşinci", { de: "der Nachweis", tr: "kanıt" }),
      word("Altıncı", { de: "der Ansprechpartner", tr: "muhatap" }),
      word("Yedinci", { de: "mahnen", tr: "ihtar etmek" }),
      word("Son", { de: "unzumutbar", tr: "kabul edilemez" }),
      { say: [tr("Kalıbımız:"), de("Bezug nehmend auf …"), tr("Mektubun ilk cümlesi neredeyse her zaman budur: neye atıf yapıldığı baştan söylenir.")] },
      { say: [tr("Örnek:"), de("Bezug nehmend auf Ihr Schreiben vom dritten Mai teile ich Ihnen Folgendes mit."), tr("Tekrar edin:"), de("Bezug nehmend auf Ihr Schreiben vom dritten Mai teile ich Ihnen Folgendes mit")], expect: repeat("Bezug nehmend auf Ihr Schreiben vom dritten Mai teile ich Ihnen Folgendes mit") },
      { say: [tr("Sıra sende: 'Sözleşmeyi feshetmek zorunda kalıyorum.'")], expect: produce("Ich sehe mich gezwungen, den Vertrag zu kündigen", [tr("Dönüşlü fiil, sonra virgülle mastar öbeği:"), de("Ich sehe mich gezwungen, den Vertrag zu kündigen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sizden on dört gün içinde görüş bildirmenizi rica ediyorum.'")], expect: produce("Ich bitte Sie um eine Stellungnahme innerhalb von vierzehn Tagen", [tr("bitten fiili um edatıyla; süre en sonda:"), de("Ich bitte Sie um eine Stellungnahme innerhalb von vierzehn Tagen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, tamamen isimleştirerek: 'Yazışmanın bu kadar gecikmesi kabul edilemez.'")], expect: produce("Die Verzögerung des Schriftverkehrs ist unzumutbar", [tr("İki isim tamlama hâlinde bağlanıyor, hüküm sonda:"), de("Die Verzögerung des Schriftverkehrs ist unzumutbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich sehe mich gezwungen, den Vertrag kündigen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich sehe mich gezwungen, den Vertrag kündigen.", false, [tr("Mastar öbeğinde zu eksik:"), de("Ich sehe mich gezwungen, den Vertrag zu kündigen.")]) },
      { say: [tr("Son: 'On iki Mart tarihli faturanıza atıfla yazıyorum.'")], expect: produce("Bezug nehmend auf Ihre Rechnung vom zwölften März schreibe ich Ihnen", [tr("Uzun tümleçten sonra fiil ikinci öğe olarak gelir:"), de("Bezug nehmend auf Ihre Rechnung vom zwölften März schreibe ich Ihnen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir müşteri hizmetleri sorumlusuyla şikâyetini resmî dille anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir müşteri hizmetleri sorumlusuyla telefondasın ve resmî bir şikâyeti dile getiriyorsun: neye atıf yapıyorsun, sorun ne, ne talep ediyorsun ve ne kadar süre tanıyorsun.",
      partner: "kibar ama sorumluluğu üstlenmekten kaçınan bir müşteri hizmetleri sorumlusu",
      opening: "Sie haben uns bereits geschrieben, richtig? Nennen Sie mir bitte kurz, worum es genau geht.",
      openingTr: "Bize daha önce yazmıştınız, değil mi? Kısaca tam olarak neyle ilgili olduğunu söyleyin lütfen.",
      goal: "Şikâyetin konusu ve gerekçesi anlatılmış, somut bir talep ile süre bildirilmiş ve karşı tarafın ne yapacağı söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-hotline",
    icon: "phone",
    level: "B2",
    course: "de",
    title: "In der Warteschleife",
    titleTr: "Çağrı merkezinde",
    summary: "Arızayı tarif etmeyi ve edilgen yerine geçen yapılarla çözüm istemeyi öğretir.",
    minutes: 12,
    focusId: "Passiversatz",
    vocab: [
      { de: "der Kundendienst", tr: "müşteri hizmetleri" },
      { de: "der Sachbearbeiter", tr: "ilgili görevli" },
      { de: "der Dienstleister", tr: "hizmet sağlayıcı" },
      { de: "der Systemausfall", tr: "sistem arızası" },
      { de: "die Fehlermeldung", tr: "hata mesajı" },
      { de: "beheben", tr: "gidermek" },
      { de: "störanfällig", tr: "arızaya yatkın" },
      { de: "die Grundgebühr", tr: "sabit ücret" },
    ],
    patterns: [
      { de: "Das Problem lässt sich …", tr: "çözülebilirliği söyler" },
      { de: "Es ist zu klären, ob/wo …", tr: "netleşmesi gerekeni söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün çağrı merkezi. Burada iki taraf da edilgen konuşur: kimse 'ben yaptım' demez, 'yapılabilir' ya da 'açıklığa kavuşturulması gerekiyor' der. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yapıların Almancada üç biçimi vardı ve ikisini geçen modülde gördün. Bugün onları telefonun hızında kullanacaksın. Önce kelimeler.")] },
      word("İlk", { de: "der Kundendienst", tr: "müşteri hizmetleri" }),
      word("İkinci", { de: "der Sachbearbeiter", tr: "ilgili görevli" }),
      word("Üçüncü", { de: "der Dienstleister", tr: "hizmet sağlayıcı" }),
      word("Dördüncü", { de: "der Systemausfall", tr: "sistem arızası" }),
      word("Beşinci", { de: "die Fehlermeldung", tr: "hata mesajı" }),
      word("Altıncı", { de: "beheben", tr: "gidermek" }, "Arızayı ortadan kaldırmak."),
      word("Yedinci", { de: "störanfällig", tr: "arızaya yatkın" }),
      word("Son", { de: "die Grundgebühr", tr: "sabit ücret" }),
      { say: [tr("Kalıbımız:"), de("Es ist zu klären, ob …"), tr("Kim netleştirecek belli değil; önemli olan netleşmesi gerektiği. Resmî dilin tam kalbi.")] },
      { say: [tr("Örnek:"), de("Das Problem lässt sich meistens aus der Ferne lösen."), tr("Tekrar edin:"), de("Das Problem lässt sich meistens aus der Ferne lösen")], expect: repeat("Das Problem lässt sich meistens aus der Ferne lösen") },
      { say: [tr("Sıra sende: 'Beni ilgili görevliye bağlayabilir misiniz?'")], expect: produce("Können Sie mich mit dem Sachbearbeiter verbinden", [tr("Modal fiil başta soru; mastar en sonda:"), de("Können Sie mich mit dem Sachbearbeiter verbinden?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sistem arızasının nereden geldiğinin açıklığa kavuşturulması gerekiyor.'")], expect: produce("Es ist zu klären, woher der Systemausfall kommt", [tr("Sahte özne es, sonra yan cümlede fiil sonda:"), de("Es ist zu klären, woher der Systemausfall kommt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Müşteri hizmetlerine yirmi dakikadır ulaşamıyorum.'")], expect: produce("Der Kundendienst ist seit zwanzig Minuten nicht erreichbar", [tr("Süre seit ile, yönelme hâlinde; olumsuzluk sıfattan önce:"), de("Der Kundendienst ist seit zwanzig Minuten nicht erreichbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es ist zu klären, woher kommt der Systemausfall."), tr("cümlesi doğru mu?")], expect: truefalse("Es ist zu klären, woher kommt der Systemausfall.", false, [tr("Dolaylı soru bir yan cümledir, fiil sona gider:"), de("Es ist zu klären, woher der Systemausfall kommt.")]) },
      { say: [tr("Son: 'Yarına kadar bana dönmenizi rica ediyorum.'")], expect: produce("Ich bitte Sie, sich bis morgen bei mir zu melden", [tr("Mastar öbeğinde dönüşlü zamir başta, zu ile mastar sonda:"), de("Ich bitte Sie, sich bis morgen bei mir zu melden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir teknik destek hattını arayacaksın: arızayı tarif et, ne denediğini söyle ve bir çözüm ya da randevu al.")] },
    ],
    roleplay: {
      scene: "İnternetin üç gündür kesik ve teknik destek hattını aradın. Arızayı tarif et, ne denediğini söyle, ne zaman düzeleceğini sor ve bir çözüm ya da teknisyen randevusu al.",
      partner: "senaryodan okuyan, önce standart soruları soran bir destek görevlisi",
      opening: "Technischer Support, mein Name ist Weber. Beschreiben Sie mir bitte die Störung — seit wann besteht sie?",
      openingTr: "Teknik destek, ben Weber. Arızayı tarif eder misiniz — ne zamandır sürüyor?",
      goal: "Arıza tarif edilmiş, denenenler söylenmiş ve bir çözüm ya da teknisyen randevusu kararlaştırılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-schadenersatz",
    icon: "law",
    level: "B2",
    course: "de",
    title: "Wer zahlt den Schaden?",
    titleTr: "Tazminat talebi",
    summary: "Zararın sebebini ve hak talebini Genitiv edatlarıyla kurmayı öğretir.",
    minutes: 12,
    focusId: "Genitivpräpositionen",
    vocab: [
      { de: "der Schadenersatz", tr: "tazminat" },
      { de: "infolge", tr: "sonucunda" },
      { de: "haften", tr: "sorumlu olmak" },
      { de: "die Rückerstattung", tr: "geri ödeme" },
      { de: "der Rechtsanspruch", tr: "yasal hak" },
      { de: "die Rechtsgrundlage", tr: "yasal dayanak" },
      { de: "die Beweislast", tr: "ispat yükü" },
      { de: "zustehen", tr: "hakkı olmak" },
    ],
    patterns: [
      { de: "wegen / infolge + Genitiv", tr: "resmî sebep bildirir" },
      { de: "Anspruch auf … haben", tr: "hak talebini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün para isteyeceğiz — ama hukuk diliyle. Bu dilde sebep bildiren edatlar tamlayan hâli ister ve doğru kullanılmadığında talep amatör durur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de kalıplaşmış bir ifade öğreneceğiz: 'bir şeye hakkı olmak'. Almancada bu, isimle ve sabit bir edatla kurulur. Önce kelimeler.")] },
      word("İlk", { de: "der Schadenersatz", tr: "tazminat" }),
      word("İkinci", { de: "infolge", tr: "sonucunda" }, "Ardından tamlayan hâli gelir."),
      word("Üçüncü", { de: "haften", tr: "sorumlu olmak" }),
      word("Dördüncü", { de: "die Rückerstattung", tr: "geri ödeme" }),
      word("Beşinci", { de: "der Rechtsanspruch", tr: "yasal hak" }),
      word("Altıncı", { de: "die Rechtsgrundlage", tr: "yasal dayanak" }),
      word("Yedinci", { de: "die Beweislast", tr: "ispat yükü" }, "Bir iddiayı kimin kanıtlamak zorunda olduğu."),
      word("Son", { de: "zustehen", tr: "hakkı olmak" }),
      { say: [tr("Kalıbımız:"), de("Anspruch auf … haben"), tr("Edat sabittir ve arkasından belirtme hâli gelir; ezberlenmesi gereken bir birliktelik.")] },
      { say: [tr("Örnek:"), de("Wegen des Schadens fordere ich eine Rückerstattung."), tr("Tekrar edin:"), de("Wegen des Schadens fordere ich eine Rückerstattung")], expect: repeat("Wegen des Schadens fordere ich eine Rückerstattung") },
      { say: [tr("Sıra sende: 'Gecikme sonucunda ek masraflar doğdu.'")], expect: produce("Infolge der Verspätung sind zusätzliche Kosten entstanden", [tr("Edat tamlayan hâli ister; ortaç en sonda:"), de("Infolge der Verspätung sind zusätzliche Kosten entstanden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Tazminat hakkım olduğunu düşünüyorum.'")], expect: produce("Ich denke, dass ich Anspruch auf Schadenersatz habe", [tr("Yan cümlede fiil sonda; kalıptaki edat değişmez:"), de("Ich denke, dass ich Anspruch auf Schadenersatz habe."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Zarardan kim sorumlu?'")], expect: produce("Wer haftet für den Schaden", [tr("Soru zamiri özne; fiilin sabit edatı für:"), de("Wer haftet für den Schaden?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Infolge der Verspätung sind zusätzliche Kosten entstanden."), tr("cümlesi doğru mu?")], expect: truefalse("Infolge der Verspätung sind zusätzliche Kosten entstanden.", true, [tr("Doğru. Edattan sonra tamlayan hâli var, hareket fiili sein ile çekilmiş ve ortaç sonda.")]) },
      { say: [tr("Son: 'Bu geri ödemenin bana hakkım olduğunu düşünüyorum.'")], expect: produce("Ich denke, dass mir diese Rückerstattung zusteht", [tr("Yan cümlede fiil sonda; ayrılabilen önek ona yapışır:"), de("Ich denke, dass mir diese Rückerstattung zusteht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir sigorta ya da firma temsilcisinden zararının karşılanmasını isteyeceksin.")] },
    ],
    roleplay: {
      scene: "Bir nakliye firmasının temsilcisiyle konuşuyorsun: taşınmada eşyan hasar gördü. Ne olduğunu anlat, sorumluluğun kimde olduğunu söyle, talebini rakamla belirt ve süreç hakkında bilgi al.",
      partner: "sorumluluğu paylaştırmaya çalışan, belge isteyen bir firma temsilcisi",
      opening: "Ich habe Ihren Schadensfall vor mir. Schildern Sie mir bitte: Was genau ist passiert?",
      openingTr: "Hasar dosyanız önümde. Anlatır mısınız: Tam olarak ne oldu?",
      goal: "Zarar anlatılmış, sorumluluk konuşulmuş, rakamlı bir talep iletilmiş ve sürecin nasıl işleyeceği öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-kompromiss",
    icon: "handshake",
    level: "B2",
    course: "de",
    title: "Der goldene Mittelweg",
    titleTr: "Uzlaşma",
    summary: "İki taraflı bağlaçlarla taviz ve uzlaşma cümleleri kurmayı öğretir.",
    minutes: 12,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "nachgeben", tr: "geri adım atmak" },
      { de: "einvernehmlich", tr: "karşılıklı rızayla" },
      { de: "die Schlichtungsstelle", tr: "uzlaştırma kurulu" },
      { de: "der Streitfall", tr: "uyuşmazlık" },
      { de: "die Zusatzvereinbarung", tr: "ek anlaşma" },
      { de: "verpflichten", tr: "yükümlü kılmak" },
      { de: "bestreiten", tr: "inkâr etmek" },
      { de: "stillschweigend", tr: "üstü kapalı" },
    ],
    patterns: [
      { de: "zwar …, aber …", tr: "kabul edip sınır koyar" },
      { de: "sowohl … als auch …", tr: "iki tarafı birlikte anar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Uzlaşmanın dili iki parçalıdır: önce karşı tarafa hak verirsin, sonra kendi sınırını koyarsın. Almanca bunu çift bağlaçlarla yapar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("En işlevlisi 'gerçi ama' ikilisi: 'gerçi ideal değil, ama iki taraf için de taşınabilir'. Tek cümlede hem anlayış hem sınır var. Önce kelimeler.")] },
      word("İlk", { de: "nachgeben", tr: "geri adım atmak" }),
      word("İkinci", { de: "einvernehmlich", tr: "karşılıklı rızayla" }),
      word("Üçüncü", { de: "die Schlichtungsstelle", tr: "uzlaştırma kurulu" }, "Mahkemeye gitmeden önce başvurulan hakem kurul."),
      word("Dördüncü", { de: "der Streitfall", tr: "uyuşmazlık" }),
      word("Beşinci", { de: "die Zusatzvereinbarung", tr: "ek anlaşma" }),
      word("Altıncı", { de: "verpflichten", tr: "yükümlü kılmak" }),
      word("Yedinci", { de: "bestreiten", tr: "inkâr etmek" }),
      word("Son", { de: "stillschweigend", tr: "üstü kapalı" }, "Kimse söylemeden, sessizce kabul edilmiş."),
      { say: [tr("Kalıbımız:"), de("zwar …, aber …"), tr("İlk parça ana cümlenin içinde durur, ikinci parça yeni bir ana cümle açar.")] },
      { say: [tr("Örnek:"), de("Das ist zwar nicht ideal, aber für beide Seiten ein guter Kompromiss."), tr("Tekrar edin:"), de("Das ist zwar nicht ideal, aber für beide Seiten ein guter Kompromiss")], expect: repeat("Das ist zwar nicht ideal, aber für beide Seiten ein guter Kompromiss") },
      { say: [tr("Sıra sende: 'Hem sizin taraf hem bizim taraf kazanmalı.'")], expect: produce("Sowohl Ihre Seite als auch unsere Seite müssen gewinnen", [tr("Bağlaç iki özneyi birlikte andığı için fiil çoğul olur:"), de("Sowohl Ihre Seite als auch unsere Seite müssen gewinnen."), tr("Tekrar dene.")], ["Sowohl Ihre als auch unsere Seite müssen gewinnen"]) },
      { say: [tr("Şimdi: 'Bu noktada geri adım atmaya hazırım.'")], expect: produce("Ich bin bereit, an dieser Stelle nachzugeben", [tr("Sıfattan sonra virgülle mastar öbeği; ayrılabilen fiilde zu ortaya girer:"), de("Ich bin bereit, an dieser Stelle nachzugeben."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Fiyatta geri adım atmam, ama tarihte esneğim.'")], expect: produce("Beim Preis gebe ich nicht nach, aber beim Termin bin ich flexibel", [tr("Tümleç başta olduğu için fiil ikinci sırada, önek sonda:"), de("Beim Preis gebe ich nicht nach, aber beim Termin bin ich flexibel."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Beim Preis ich gebe nicht nach."), tr("cümlesi doğru mu?")], expect: truefalse("Beim Preis ich gebe nicht nach.", false, [tr("Cümle tümleçle başlayınca özne fiilin arkasına geçer:"), de("Beim Preis gebe ich nicht nach.")]) },
      { say: [tr("Son: 'Sonunda karşılıklı rızayla anlaştık.'")], expect: produce("Am Ende haben wir uns einvernehmlich geeinigt", [tr("Dönüşlü fiil haben ile çekilir, ortaç sonda:"), de("Am Ende haben wir uns einvernehmlich geeinigt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada tıkanmış bir pazarlığı uzlaşmayla bitireceksin.")] },
    ],
    roleplay: {
      scene: "Bir ortak projede iki taraf tıkandı: sen tarihte, karşı taraf bütçede esnemiyor. Karşı tarafa hak verdiğin noktayı söyle, kendi sınırını koy, bir taviz öner ve ortak bir çözümde anlaş.",
      partner: "haklı gerekçeleri olan, ama uzlaşmaya açık bir proje ortağı",
      opening: "Wir drehen uns im Kreis. Sagen Sie mir ehrlich: Wo können Sie wirklich nicht nachgeben?",
      openingTr: "Aynı yerde dönüyoruz. Açık söyleyin: Gerçekten nerede geri adım atamıyorsunuz?",
      goal: "Her iki tarafın sınırı söylenmiş, bir taviz önerilmiş ve iki tarafın da kabul ettiği bir çözümde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-eskalation",
    icon: "feelings",
    level: "B2",
    course: "de",
    title: "Ruhig bleiben",
    titleTr: "Gerilimi düşürmek",
    summary: "Öfkeli bir muhatabı anlayış ve dilek kipiyle yatıştırmayı öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Wut", tr: "öfke" },
      { de: "sachlich", tr: "nesnel" },
      { de: "einfühlsam", tr: "empatik" },
      { de: "respektieren", tr: "saygı duymak" },
      { de: "abklingen", tr: "yatışmak" },
      { de: "impulsiv", tr: "fevri" },
      { de: "zumuten", tr: "katlanmasını beklemek" },
      { de: "die Erleichterung", tr: "rahatlama" },
    ],
    patterns: [
      { de: "Ich kann … gut verstehen.", tr: "duyguyu tanır" },
      { de: "Wäre es hilfreich, wenn …?", tr: "çözümü soru olarak sunar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünün konusu zor: karşındaki sinirli. Almancada gerilimi düşürmenin sırası bellidir — önce duyguyu tanı, sonra konuya dön, en son çözümü öner. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Ve çözüm asla emir kipiyle sunulmaz. 'Size yedek cihaz veriyoruz' değil, 'yedek cihaz versek yardımcı olur mu' denir. Soru, karşı tarafa kontrolü geri verir. Önce kelimeler.")] },
      word("İlk", { de: "die Wut", tr: "öfke" }),
      word("İkinci", { de: "sachlich", tr: "nesnel" }),
      word("Üçüncü", { de: "einfühlsam", tr: "empatik" }),
      word("Dördüncü", { de: "respektieren", tr: "saygı duymak" }),
      word("Beşinci", { de: "abklingen", tr: "yatışmak" }, "Öfke ya da ağrı kendiliğinden hafifler."),
      word("Altıncı", { de: "impulsiv", tr: "fevri" }),
      word("Yedinci", { de: "zumuten", tr: "katlanmasını beklemek" }, "Birinden kaldıramayacağı bir şeyi beklemek."),
      word("Son", { de: "die Erleichterung", tr: "rahatlama" }),
      { say: [tr("Kalıbımız:"), de("Wäre es hilfreich, wenn …?"), tr("Dilek kipinde sahte özne ve koşul cümlesi: en yumuşak çözüm önerme biçimi.")] },
      { say: [tr("Örnek:"), de("Ich kann Ihre Wut gut verstehen."), tr("Tekrar edin:"), de("Ich kann Ihre Wut gut verstehen")], expect: repeat("Ich kann Ihre Wut gut verstehen") },
      { say: [tr("Sıra sende: 'Nesnel kalalım.'")], expect: produce("Lassen Sie uns sachlich bleiben", [tr("lassen ile rica; mastar en sonda:"), de("Lassen Sie uns sachlich bleiben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi çözümü soru yap: 'Size yedek bir cihaz versek yardımcı olur mu?'")], expect: produce("Wäre es hilfreich, wenn wir Ihnen ein Ersatzgerät geben würden", [tr("Dilek kipi başta; koşul cümlesi de dilek kipinde ve fiil sonda:"), de("Wäre es hilfreich, wenn wir Ihnen ein Ersatzgerät geben würden?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu bir suçlama değil, bir rica.'")], expect: produce("Das ist kein Vorwurf, sondern eine Bitte", [tr("Olumsuzluktan sonra düzeltme sondern ile yapılır:"), de("Das ist kein Vorwurf, sondern eine Bitte."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist kein Vorwurf, aber eine Bitte."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist kein Vorwurf, aber eine Bitte.", false, [tr("Olumsuzlanan şeyin yerine doğrusu konuyorsa bağlaç sondern olur:"), de("Das ist kein Vorwurf, sondern eine Bitte.")]) },
      { say: [tr("Son: 'Kararınıza elbette saygı duyarım.'")], expect: produce("Ich würde Ihre Entscheidung selbstverständlich respektieren", [tr("Dilek kipi ikinci sırada, mastar en sonda:"), de("Ich würde Ihre Entscheidung selbstverständlich respektieren."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada öfkeli bir müşteriyle konuşacaksın: önce duyguyu tanı, sonra konuya dön ve bir çözüm öner.")] },
    ],
    roleplay: {
      scene: "Öfkeli bir müşteri seni arıyor: teslimat üçüncü kez gecikti. Önce duygusunu tanı, konuyu nesnel zemine çek, ne olduğunu açıkla ve bir çözüm öner.",
      partner: "sesini yükselten ama haksız olmayan, sonunda yumuşayabilen bir müşteri",
      opening: "Das ist jetzt das dritte Mal! Ich habe wirklich keine Lust mehr auf Ausreden — was machen Sie jetzt?",
      openingTr: "Bu üçüncü kez oluyor! Bahanelerden gerçekten bıktım — şimdi ne yapacaksınız?",
      goal: "Öfke tanınmış, konu nesnel zemine çekilmiş ve müşterinin kabul ettiği somut bir çözüm kararlaştırılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-vertrag-kuendigen",
    icon: "office",
    level: "B2",
    course: "de",
    title: "Das Abo kündigen",
    titleTr: "Abonelik iptali",
    summary: "Fesih bildirimini süre, onay ve cayma diliyle kurmayı öğretir.",
    minutes: 12,
    focusId: "Nominalisierung",
    vocab: [
      { de: "fristgerecht", tr: "süresine uygun" },
      { de: "die Kündigungsfrist", tr: "ihbar süresi" },
      { de: "die Vertragslaufzeit", tr: "sözleşme süresi" },
      { de: "der Widerruf", tr: "cayma" },
      { de: "die Einwilligung", tr: "rıza" },
      { de: "die Auflösung", tr: "fesih" },
      { de: "befristen", tr: "süreyle sınırlamak" },
      { de: "unwirksam", tr: "hükümsüz" },
    ],
    patterns: [
      { de: "fristgerecht zum …", tr: "fesih tarihini bildirir" },
      { de: "Ich bitte um …", tr: "resmî talepte bulunur" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir sözleşmeyi feshedeceğiz. Almanca fesihte üç şey olmazsa yazı geçersiz sayılabilir: tarih, süreye uygunluk ve yazılı onay talebi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu üçü sabit kalıplarla söylenir; cümleyi kendin kurmaya çalışmak yerine kalıbı olduğu gibi kullanmak daha güvenli. Önce kelimeler.")] },
      word("İlk", { de: "fristgerecht", tr: "süresine uygun" }),
      word("İkinci", { de: "die Kündigungsfrist", tr: "ihbar süresi" }),
      word("Üçüncü", { de: "die Vertragslaufzeit", tr: "sözleşme süresi" }),
      word("Dördüncü", { de: "der Widerruf", tr: "cayma" }),
      word("Beşinci", { de: "die Einwilligung", tr: "rıza" }),
      word("Altıncı", { de: "die Auflösung", tr: "fesih" }),
      word("Yedinci", { de: "befristen", tr: "süreyle sınırlamak" }),
      word("Son", { de: "unwirksam", tr: "hükümsüz" }, "Hukuken hiç doğmamış sayılan, geçersiz."),
      { say: [tr("Kalıbımız:"), de("fristgerecht zum …"), tr("Ardından tarih gelir ve tarih yönelme hâlindedir.")] },
      { say: [tr("Örnek:"), de("Hiermit kündige ich meinen Vertrag fristgerecht zum einunddreißigsten Dezember."), tr("Tekrar edin:"), de("Hiermit kündige ich meinen Vertrag fristgerecht zum einunddreißigsten Dezember")], expect: repeat("Hiermit kündige ich meinen Vertrag fristgerecht zum einunddreißigsten Dezember") },
      { say: [tr("Sıra sende: 'Feshin yazılı onayını rica ediyorum.'")], expect: produce("Ich bitte um eine schriftliche Bestätigung der Auflösung", [tr("bitten fiili um edatıyla; ikinci isim tamlayan hâlinde:"), de("Ich bitte um eine schriftliche Bestätigung der Auflösung."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Reklam için verdiğim rızayı geri çekiyorum.'")], expect: produce("Ich widerrufe meine Einwilligung in die Werbung", [tr("Fiilin sabit edatı in ve belirtme hâli:"), de("Ich widerrufe meine Einwilligung in die Werbung."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sözleşme süresinin ne zaman bittiğini bilmek istiyorum.'")], expect: produce("Ich möchte wissen, wann die Vertragslaufzeit endet", [tr("Dolaylı soruda fiil sona gider:"), de("Ich möchte wissen, wann die Vertragslaufzeit endet."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich möchte wissen, wann endet die Vertragslaufzeit."), tr("cümlesi doğru mu?")], expect: truefalse("Ich möchte wissen, wann endet die Vertragslaufzeit.", false, [tr("Dolaylı soru yan cümledir; çekimli fiil sonda durur:"), de("Ich möchte wissen, wann die Vertragslaufzeit endet.")]) },
      { say: [tr("Son: 'İhbar süresine uyarak en yakın tarihte feshediyorum.'")], expect: produce("Ich kündige unter Einhaltung der Kündigungsfrist zum nächstmöglichen Termin", [tr("Uzun tümleçten sonra tarih; tamlayan hâli edatın ardında:"), de("Ich kündige unter Einhaltung der Kündigungsfrist zum nächstmöglichen Termin."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada aboneliğini iptal ettireceksin — ve karşı taraf seni tutmaya çalışacak.")] },
    ],
    roleplay: {
      scene: "Bir spor salonunun müşteri hattını aradın ve üyeliğini iptal ettirmek istiyorsun. Feshi bildir, tarihi söyle, tutma tekliflerine kararlılıkla cevap ver ve yazılı onay iste.",
      partner: "seni tutmak için indirim ve dondurma teklif eden bir müşteri danışmanı",
      opening: "Schade, dass Sie gehen wollen. Darf ich fragen, woran es liegt? Vielleicht finden wir eine Lösung.",
      openingTr: "Ayrılmak istemenize üzüldük. Sebebini sorabilir miyim? Belki bir çözüm buluruz.",
      goal: "Fesih bildirilmiş, tarih netleşmiş, tutma teklifleri reddedilmiş ve yazılı onay sözü alınmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-nachbarschaftsstreit",
    icon: "home",
    level: "B2",
    course: "de",
    title: "Der Lärm von nebenan",
    titleTr: "Gürültü sorunu",
    summary: "Komşu anlaşmazlığını koşullu bağlaçlarla, yönetime gitmeden çözmeyi öğretir.",
    minutes: 12,
    focusId: "Nebensatz-sofern",
    vocab: [
      { de: "die Nachbarschaft", tr: "komşuluk" },
      { de: "die Lärmbelästigung", tr: "gürültü rahatsızlığı" },
      { de: "die Ruhestörung", tr: "huzur bozma" },
      { de: "die Hausverwaltung", tr: "bina yönetimi" },
      { de: "die Gemeinde", tr: "belediye" },
      { de: "der Verstoß", tr: "ihlal" },
      { de: "untersagen", tr: "men etmek" },
      { de: "rücksichtsvoll", tr: "düşünceli" },
    ],
    patterns: [
      { de: "Sofern Sie einverstanden sind, …", tr: "koşullu öneri" },
      { de: "Können wir das unter Nachbarn klären?", tr: "dostane çözüm arar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün komşuyla anlaşmazlık var ve Almanya'da bunun bir kuralı var: yönetime ya da belediyeye gitmeden önce doğrudan konuşulur. Bu deneme dilde de görünür. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Anahtar cümle koşullu olandır: 'siz de kabul ederseniz'. Karşı tarafa itiraz hakkı bırakır ve konuşmayı resmî şikâyetten uzak tutar. Önce kelimeler.")] },
      word("İlk", { de: "die Nachbarschaft", tr: "komşuluk" }),
      word("İkinci", { de: "die Lärmbelästigung", tr: "gürültü rahatsızlığı" }),
      word("Üçüncü", { de: "die Ruhestörung", tr: "huzur bozma" }, "Gece saatlerinde gürültü etmenin resmî adı."),
      word("Dördüncü", { de: "die Hausverwaltung", tr: "bina yönetimi" }),
      word("Beşinci", { de: "die Gemeinde", tr: "belediye" }),
      word("Altıncı", { de: "der Verstoß", tr: "ihlal" }),
      word("Yedinci", { de: "untersagen", tr: "men etmek" }),
      word("Son", { de: "rücksichtsvoll", tr: "düşünceli" }),
      { say: [tr("Kalıbımız:"), de("Sofern Sie einverstanden sind, …"), tr("Yan cümle bağlacı; fiil sona gidiyor ve ana cümle fiille başlıyor.")] },
      { say: [tr("Örnek:"), de("Sofern Sie einverstanden sind, teilen wir die Kosten."), tr("Tekrar edin:"), de("Sofern Sie einverstanden sind, teilen wir die Kosten")], expect: repeat("Sofern Sie einverstanden sind, teilen wir die Kosten") },
      { say: [tr("Sıra sende: 'Bunu komşular arasında çözmeyi tercih ederim.'")], expect: produce("Ich würde das lieber unter Nachbarn lösen", [tr("Dilek kipiyle tercih; mastar sonda:"), de("Ich würde das lieber unter Nachbarn lösen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi olguyu söyle: 'Gürültü neredeyse her gece saat on birde başlıyor.'")], expect: produce("Die Lärmbelästigung beginnt fast jede Nacht um elf", [tr("Özne başta, fiil ikinci sırada, zaman ifadesi sonda:"), de("Die Lärmbelästigung beginnt fast jede Nacht um elf."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Burada anlaşırsak bina yönetimini devreye sokmam.'")], expect: produce("Sofern wir uns hier einigen, schalte ich die Hausverwaltung nicht ein", [tr("Yan cümle önde; ana cümlede ayrılabilen önek sonda:"), de("Sofern wir uns hier einigen, schalte ich die Hausverwaltung nicht ein."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Sofern Sie einverstanden sind, teilen wir die Kosten."), tr("cümlesi doğru mu?")], expect: truefalse("Sofern Sie einverstanden sind, teilen wir die Kosten.", true, [tr("Doğru. Koşul yan cümlesinin fiili sonda, ana cümle fiille başlıyor.")]) },
      { say: [tr("Son: 'Bina yönetmeliği saat yirmi ikiden sonra gürültüyü yasaklıyor.'")], expect: produce("Die Hausordnung untersagt Lärm nach zweiundzwanzig Uhr", [tr("Özne başta, fiil ikinci sırada; zaman ifadesi en sonda:"), de("Die Hausordnung untersagt Lärm nach zweiundzwanzig Uhr."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada komşunla gürültü meselesini konuşacaksın: olguyu söyle, suçlamadan öner ve aranızda bir çözümde anlaş.")] },
    ],
    roleplay: {
      scene: "Üst kattaki komşun neredeyse her gece geç saatlere kadar gürültü yapıyor. Olguyu suçlamadan söyle, ne istediğini belirt, birlikte bir saat sınırı öner ve yönetime gitmeden anlaş.",
      partner: "önce savunmaya geçen, sonra makul davranan bir komşu",
      opening: "Sie wollten mich sprechen? Wenn es um die Musik geht — wir feiern doch nicht jeden Abend, oder?",
      openingTr: "Benimle konuşmak mı istediniz? Müzikle ilgiliyse — her akşam parti yapmıyoruz ya?",
      goal: "Olgu suçlamadan anlatılmış, bir saat sınırı önerilmiş ve bina yönetimine gitmeden bir çözümde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-reklamation-b2",
    icon: "repair",
    level: "B2",
    course: "de",
    title: "Der dritte Defekt",
    titleTr: "Israrlı şikâyet",
    summary: "Tekrarlayan arızayı edilgen geçmişle anlatıp değişim talep etmeyi öğretir.",
    minutes: 12,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "reklamieren", tr: "şikâyet etmek" },
      { de: "die Gewährleistung", tr: "yasal garanti" },
      { de: "das Rückgaberecht", tr: "iade hakkı" },
      { de: "der Kaufbeleg", tr: "satın alma belgesi" },
      { de: "der Rücktritt", tr: "sözleşmeden dönme" },
      { de: "bestehen auf", tr: "ısrar etmek" },
      { de: "die Kulanz", tr: "iyi niyet jesti" },
      { de: "mangelhaft", tr: "kusurlu" },
    ],
    patterns: [
      { de: "… ist bereits … worden", tr: "yapılmış olanı sayar" },
      { de: "Ich bestehe auf …", tr: "talebi kararlı söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün üçüncü kez bozulan bir cihaz var. Bu konuşmanın gücü bir listeden gelir: şimdiye kadar ne YAPILDI. Ve o liste edilgen geçmişle kurulur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Neden edilgen? Çünkü kimin tamir ettiği önemsiz; önemli olan tamirin işe yaramamış olması. Fail silinince olgu öne çıkar. Önce kelimeler.")] },
      word("İlk", { de: "reklamieren", tr: "şikâyet etmek" }),
      word("İkinci", { de: "die Gewährleistung", tr: "yasal garanti" }, "Yasadan doğan iki yıllık ayıp sorumluluğu."),
      word("Üçüncü", { de: "das Rückgaberecht", tr: "iade hakkı" }),
      word("Dördüncü", { de: "der Kaufbeleg", tr: "satın alma belgesi" }),
      word("Beşinci", { de: "der Rücktritt", tr: "sözleşmeden dönme" }),
      word("Altıncı", { de: "bestehen auf", tr: "ısrar etmek" }),
      word("Yedinci", { de: "die Kulanz", tr: "iyi niyet jesti" }, "Yasal zorunluluk olmadan gösterilen esneklik."),
      word("Son", { de: "mangelhaft", tr: "kusurlu" }),
      { say: [tr("Kalıbımız:"), de("… ist bereits … worden"), tr("Edilgen geçmişte yardımcı fiil sona geçerken kısalır — bu ayrıntı cümleyi ya doğru ya yanlış yapar.")] },
      { say: [tr("Örnek:"), de("Das Gerät ist bereits zweimal repariert worden."), tr("Tekrar edin:"), de("Das Gerät ist bereits zweimal repariert worden")], expect: repeat("Das Gerät ist bereits zweimal repariert worden") },
      { say: [tr("Sıra sende: 'Cihaz üçüncü kez bozuldu.'")], expect: produce("Das Gerät ist zum dritten Mal kaputtgegangen", [tr("Hareket ve durum değişimi sein ile çekilir:"), de("Das Gerät ist zum dritten Mal kaputtgegangen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir tamir denendi ama bir işe yaramadı.'")], expect: produce("Eine Reparatur ist bereits versucht worden, aber sie hat nichts gebracht", [tr("İlk cümle edilgen geçmiş, ikincisi normal geçmiş:"), de("Eine Reparatur ist bereits versucht worden, aber sie hat nichts gebracht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yeni bir cihaz konusunda ısrar ediyorum.'")], expect: produce("Ich bestehe auf einem neuen Gerät", [tr("Bu fiilin sabit edatı auf ve arkasından yönelme hâli gelir:"), de("Ich bestehe auf einem neuen Gerät."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Gerät ist bereits zweimal repariert geworden."), tr("cümlesi doğru mu?")], expect: truefalse("Das Gerät ist bereits zweimal repariert geworden.", false, [tr("Edilgen geçmişte yardımcı fiil kısalır:"), de("Das Gerät ist bereits zweimal repariert worden.")]) },
      { say: [tr("Son: 'Cihaz bu hâliyle kusurlu.'")], expect: produce("In diesem Zustand ist das Gerät mangelhaft", [tr("Tümleç başta olduğu için fiil ikinci sırada:"), de("In diesem Zustand ist das Gerät mangelhaft."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada mağazada üçüncü kez bozulan cihazı geri götüreceksin: sayarak anlat ve değişim iste.")] },
    ],
    roleplay: {
      scene: "Aynı cihaz üçüncü kez bozuldu ve mağazadasın. Şimdiye kadar ne yapıldığını sırayla say, cihazın kullanılamaz olduğunu söyle, değişim ya da para iadesi iste ve bir sonuca bağla.",
      partner: "önce yine tamir öneren, ısrar karşısında yetkiliye danışan bir mağaza görevlisi",
      opening: "Sie waren doch schon mal hier, oder? Lassen Sie es mich noch einmal einschicken, das geht am schnellsten.",
      openingTr: "Daha önce de gelmiştiniz, değil mi? Bir kez daha servise göndereyim, en hızlısı bu.",
      goal: "Yapılan tamirler sayılmış, tekrar tamir teklifi reddedilmiş ve değişim ya da iade konusunda bir sonuca varılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-feedbackgespraech",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Kritik verpacken",
    titleTr: "Yapıcı eleştiri",
    summary: "Eleştiriyi gözlem, öneri ve soru sırasıyla vermeyi öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Rückmeldung", tr: "geri bildirim" },
      { de: "der Verbesserungsvorschlag", tr: "iyileştirme önerisi" },
      { de: "die Wertschätzung", tr: "takdir" },
      { de: "die Beurteilung", tr: "değerlendirme" },
      { de: "beurteilen", tr: "değerlendirmek" },
      { de: "der Tadel", tr: "azar" },
      { de: "gewissenhaft", tr: "özenli" },
      { de: "engagiert", tr: "gayretli" },
    ],
    patterns: [
      { de: "Mir ist aufgefallen, dass …", tr: "gözlemi kişiselleştirmeden söyler" },
      { de: "An Ihrer Stelle würde ich …", tr: "öneriyi dilek kipiyle verir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve en faydalısı: eleştiriyi nasıl söylersin. Almancada üçlü bir sıra var — gözlem, öneri, soru. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Gözlem 'sen şöylesin' değil 'şu dikkatimi çekti' diye kurulur; öneri dilek kipindedir; soru da kararı karşı tarafa bırakır. Önce kelimeler.")] },
      word("İlk", { de: "die Rückmeldung", tr: "geri bildirim" }),
      word("İkinci", { de: "der Verbesserungsvorschlag", tr: "iyileştirme önerisi" }),
      word("Üçüncü", { de: "die Wertschätzung", tr: "takdir" }),
      word("Dördüncü", { de: "die Beurteilung", tr: "değerlendirme" }),
      word("Beşinci", { de: "beurteilen", tr: "değerlendirmek" }),
      word("Altıncı", { de: "der Tadel", tr: "azar" }, "Takdirin karşıtı: açık, sert eleştiri."),
      word("Yedinci", { de: "gewissenhaft", tr: "özenli" }),
      word("Son", { de: "engagiert", tr: "gayretli" }),
      { say: [tr("Kalıbımız:"), de("Mir ist aufgefallen, dass …"), tr("Özne sen değilsin, gözlem; suçlama yok, olgu var.")] },
      { say: [tr("Örnek:"), de("Mir ist aufgefallen, dass die Berichte oft spät kommen."), tr("Tekrar edin:"), de("Mir ist aufgefallen, dass die Berichte oft spät kommen")], expect: repeat("Mir ist aufgefallen, dass die Berichte oft spät kommen") },
      { say: [tr("Sıra sende: 'Sizin yerinizde olsam önce ekiple konuşurdum.'")], expect: produce("An Ihrer Stelle würde ich zuerst mit dem Team sprechen", [tr("Tümleç başta, dilek kipi ikinci sırada, mastar sonda:"), de("An Ihrer Stelle würde ich zuerst mit dem Team sprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir iyileştirme önerim olurdu.'")], expect: produce("Ich hätte einen Verbesserungsvorschlag", [tr("Sahip olma fiilinin dilek kipi teklifi yumuşatır:"), de("Ich hätte einen Verbesserungsvorschlag."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, kararı ona bırak: 'Bu konuda ne düşünürsünüz?'")], expect: produce("Was halten Sie davon", [tr("Kalıplaşmış soru; edat davon ile birleşir:"), de("Was halten Sie davon?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("An Ihrer Stelle würde ich zuerst mit dem Team gesprochen."), tr("cümlesi doğru mu?")], expect: truefalse("An Ihrer Stelle würde ich zuerst mit dem Team gesprochen.", false, [tr("würde yardımcı fiilinden sonra ortaç değil mastar gelir:"), de("An Ihrer Stelle würde ich zuerst mit dem Team sprechen.")]) },
      { say: [tr("Son: 'Bunu takdir ederek dile getirmek istiyorum.'")], expect: produce("Ich möchte das mit Wertschätzung ansprechen", [tr("Edat öbeği ortada, ayrılabilen fiilin mastarı sonda:"), de("Ich möchte das mit Wertschätzung ansprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir ekip arkadaşına zor bir geri bildirim vereceksin — gözlem, öneri, soru sırasıyla.")] },
    ],
    roleplay: {
      scene: "Bir ekip arkadaşına zor bir geri bildirim veriyorsun: teslimler sürekli gecikiyor. Önce onun özenli ve gayretli yanını takdir et, gözlemini kişiselleştirmeden aktar, bir öneri ver ve kararı ona bırak.",
      partner: "önce savunmaya geçen, sonra dinleyen bir ekip arkadaşı",
      opening: "Du wolltest reden? Wenn es wieder um die Termine geht — ich hänge selbst an drei Zulieferungen fest.",
      openingTr: "Konuşmak mı istedin? Yine tarihlerle ilgiliyse — ben de üç tedarikte takılı durumdayım.",
      goal: "Takdir ve gözlem ayrı ayrı söylenmiş, bir öneri verilmiş ve karşı tarafın ne yapacağı birlikte kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
];
