import { de, tr, type LectureStep, type Lesson, type Segment } from "../types";

/**
 * B1 · Modül 12 — Alışveriş, para ve banka (111–120).
 *
 * Modül 11 gibi: alan havuzdaki kapsanmamış kümeden çıktı, dilbilgisi odağı
 * modül 1–10'dan geri geliyor. Bu modülün kendine özgü yanı kelimelerin
 * SOMUT olması — bir öğrenci bankada ya da kasada bu sözcükleri duymazsa
 * işlemi yapamaz, tahmin edip geçemez.
 *
 * Yayı işlem sırasına göre: fiyat karşılaştırmaktan iade etmeye, bankadan
 * çevrimiçi siparişe, oradan malzeme ve nihayet yazılı şikâyete. Son ders
 * yazı dili çünkü Almanya'da bir hakkı aramanın yolu telefon değil mektup.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [
      tr(`${n} kelimemiz:`),
      de(w.de),
      tr(`Türkçesi '${w.tr}' demek${note ? ` — ${note}` : ""}. Lütfen`),
      de(w.de),
      tr("deyin."),
    ],
    expect: repeat(w.de),
  };
}

export const deB1B12: Lesson[] = [
  {
    id: "de-b1-preis-vergleichen",
    icon: "shopping",
    level: "B1",
    course: "de",
    title: "Wo ist es günstiger?",
    titleTr: "Fiyat karşılaştırmak",
    summary: "İki satıcıyı karşılaştırmayı ve tercihini rakamla gerekçelendirmeyi öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "der Rabatt", tr: "indirim" },
      { de: "der Katalog", tr: "katalog" },
      { de: "das Schaufenster", tr: "vitrin" },
      { de: "der Händler", tr: "satıcı, tüccar" },
      { de: "der Anbieter", tr: "sağlayıcı" },
      { de: "wertvoll", tr: "değerli" },
      { de: "wertlos", tr: "değersiz" },
      { de: "der Durchschnitt", tr: "ortalama" },
    ],
    patterns: [
      { de: "… bietet mehr Rabatt als …", tr: "iki satıcıyı karşılaştırır" },
      { de: "über dem Durchschnitt", tr: "ortalamayla kıyaslar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün alışverişin ilk adımını yapacağız: karşılaştırmak. Almanya'da fiyat sormak ayıp değil, beklenen bir şey. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karşılaştırma sıfata bir ek getirir. Ortalamayla kıyaslarken ise bir edat kullanılır ve o edat yönelme hâli ister. Önce kelimeler.")] },
      word("İlk", { de: "der Rabatt", tr: "indirim" }),
      word("İkinci", { de: "der Katalog", tr: "katalog" }),
      word("Üçüncü", { de: "das Schaufenster", tr: "vitrin" }),
      word("Dördüncü", { de: "der Händler", tr: "satıcı, tüccar" }),
      word("Beşinci", { de: "der Anbieter", tr: "sağlayıcı" }, "hizmet ya da tarife sunan firma"),
      word("Altıncı", { de: "wertvoll", tr: "değerli" }),
      word("Yedinci", { de: "wertlos", tr: "değersiz" }),
      word("Son", { de: "der Durchschnitt", tr: "ortalama" }),
      { say: [tr("İlk kalıbımız iki satıcıyı karşılaştırıyor: miktar zarfının karşılaştırma biçimi artı kıyas edatı.")] },
      { say: [tr("Örnek:"), de("Dieser Händler bietet mehr Rabatt als der andere."), tr("Tekrar edin:"), de("Dieser Händler bietet mehr Rabatt als der andere")], expect: repeat("Dieser Händler bietet mehr Rabatt als der andere") },
      { say: [tr("Sıra sende: 'Bu sağlayıcı ötekinden daha ucuz.'")], expect: produce("Dieser Anbieter ist billiger als der andere", [tr("Sıfat artı ek, sonra kıyas edatı:"), de("Dieser Anbieter ist billiger als der andere."), tr("Tekrar dene.")], ["Dieser Anbieter ist günstiger als der andere"]) },
      { say: [tr("İkinci kalıbımız ortalamayla kıyaslıyor. Buradaki edat yönelme hâli istiyor, o yüzden artikel değişiyor.")] },
      { say: [tr("Şimdi: 'Fiyat ortalamanın üstünde.'")], expect: produce("Der Preis liegt über dem Durchschnitt", [tr("Edat yönelme hâli istiyor:"), de("Der Preis liegt über dem Durchschnitt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Katalog ist billiger wie das Schaufenster."), tr("cümlesi doğru mu?")], expect: truefalse("Der Katalog ist billiger wie das Schaufenster.", false, [tr("Karşılaştırmada kullanılan kıyas sözcüğü başkadır; benzerlik sözcüğü buraya girmez:"), de("Der Katalog ist billiger als das Schaufenster.")]) },
      { say: [tr("Son: 'Bu takı gerçekten değerli, o değil.'")], expect: produce("Dieser Schmuck ist wirklich wertvoll, der andere ist wertlos", [tr("İki ana cümle, ikisinde de fiil ikinci sırada:"), de("Dieser Schmuck ist wirklich wertvoll, der andere ist wertlos."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi iki mağazayı karşılaştırıp nereden alacağına karar vereceksin.")] },
    ],
    roleplay: {
      scene: "Aynı ürünü iki yerde gördün. Bir arkadaşınla fiyatları, indirimi ve kaliteyi karşılaştırıp nereden alacağınıza karar veriyorsunuz.",
      partner: "her şeyi karşılaştırmadan almayan hesapçı bir arkadaş",
      opening: "Hast du die beiden Preise verglichen? Wo ist es denn günstiger?",
      openingTr: "İki fiyatı karşılaştırdın mı? Nerede daha ucuz?",
      goal: "İki satıcı fiyat ve kalite bakımından karşılaştırılmış ve gerekçeli bir karar verilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-umtausch",
    icon: "shopping",
    level: "B1",
    course: "de",
    title: "Ich möchte das umtauschen",
    titleTr: "İade ve değişim",
    summary: "Bir ürünü iade etmeyi ve gerekçesini sebep cümlesiyle söylemeyi öğretir.",
    minutes: 10,
    focusId: "Nebensatz-weil",
    vocab: [
      { de: "der Umtausch", tr: "değişim" },
      { de: "umtauschen", tr: "değiştirmek" },
      { de: "der Beleg", tr: "makbuz" },
      { de: "die Garantie", tr: "garanti" },
      { de: "der Ersatz", tr: "yedek" },
      { de: "die Verkäuferin", tr: "kadın satıcı" },
      { de: "der Käufer", tr: "alıcı" },
      { de: "der Kauf", tr: "satın alma" },
    ],
    patterns: [
      { de: "Ich möchte … umtauschen, weil …", tr: "iade isteğini gerekçesiyle söyler" },
      { de: "Ich habe den Beleg dabei.", tr: "makbuzun yanında olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Aldığın şey olmadı ve geri götürüyorsun. Almanya'da bunun tek şartı var: gerekçe ve makbuz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Gerekçe sebep bağlacıyla verilir ve o bağlaçtan sonra fiil cümlenin en sonuna gider. Önce kelimeler.")] },
      word("İlk", { de: "der Umtausch", tr: "değişim" }),
      word("İkinci", { de: "umtauschen", tr: "değiştirmek" }, "ayrılabilen bir fiil"),
      word("Üçüncü", { de: "der Beleg", tr: "makbuz" }),
      word("Dördüncü", { de: "die Garantie", tr: "garanti" }),
      word("Beşinci", { de: "der Ersatz", tr: "yedek" }),
      word("Altıncı", { de: "die Verkäuferin", tr: "kadın satıcı" }),
      word("Yedinci", { de: "der Käufer", tr: "alıcı" }),
      word("Son", { de: "der Kauf", tr: "satın alma" }),
      { say: [tr("İlk kalıbımız isteği ve gerekçeyi birleştiriyor: istek ana cümlede, gerekçe yan cümlede. Ayrılabilen fiilin öneki ana cümlenin sonunda kalıyor.")] },
      { say: [tr("Örnek:"), de("Ich möchte das umtauschen, weil es zu klein ist."), tr("Tekrar edin:"), de("Ich möchte das umtauschen, weil es zu klein ist")], expect: repeat("Ich möchte das umtauschen, weil es zu klein ist") },
      { say: [tr("Sıra sende: 'Bunu değiştirmek istiyorum, çünkü çalışmıyor.'")], expect: produce("Ich möchte das umtauschen, weil es nicht funktioniert", [tr("Bağlaçtan sonra fiil en sona:"), de("Ich möchte das umtauschen, weil es nicht funktioniert."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız kanıtı ortaya koyuyor. Bu kısa cümle olmadan konuşma uzar; makbuz varsa tartışma biter.")] },
      { say: [tr("Şimdi: 'Makbuz ve garanti belgesi yanımda.'")], expect: produce("Ich habe den Beleg und die Garantie dabei", [tr("Zarf cümlenin sonunda:"), de("Ich habe den Beleg und die Garantie dabei."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich will einen Ersatz, weil ist die Garantie noch gültig."), tr("cümlesi doğru mu?")], expect: truefalse("Ich will einen Ersatz, weil ist die Garantie noch gültig.", false, [tr("Sebep bağlacından sonra fiil öne gelmez, sona gider:"), de("Ich will einen Ersatz, weil die Garantie noch gültig ist.")]) },
      { say: [tr("Son: 'Alım iki hafta önceydi, o yüzden değişim hâlâ mümkün.'")], expect: produce("Der Kauf war vor zwei Wochen, deshalb ist der Umtausch noch möglich", [tr("Sonuç zarfı başta olunca fiil ikinci sıraya geçer:"), de("Der Kauf war vor zwei Wochen, deshalb ist der Umtausch noch möglich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir mağazadasın ve aldığın şeyi değiştireceksin.")] },
    ],
    roleplay: {
      scene: "İki hafta önce aldığın bir ürünü değiştirmek için mağazaya döndün. Gerekçeni söylüyor, makbuzu gösteriyor ve ne istediğini net söylüyorsun.",
      partner: "kurallara bağlı ama çözüm arayan bir satıcı",
      opening: "Guten Tag! Was kann ich für Sie tun — möchten Sie etwas umtauschen?",
      openingTr: "İyi günler! Size nasıl yardımcı olabilirim — bir şey mi değiştirmek istiyorsunuz?",
      goal: "İade gerekçesi söylenmiş, makbuz gösterilmiş ve değişim ya da para iadesi üzerinde anlaşılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-bank-konto",
    icon: "money",
    level: "B1",
    course: "de",
    title: "Auf der Bank",
    titleTr: "Bankada",
    summary: "Bilmediğin banka ayrıntılarını dolaylı soru kalıplarıyla sormayı öğretir.",
    minutes: 10,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "das Girokonto", tr: "vadesiz hesap" },
      { de: "das Bargeld", tr: "nakit" },
      { de: "der Geldautomat", tr: "bankamatik" },
      { de: "die Einzahlung", tr: "para yatırma" },
      { de: "die Zinsen", tr: "faiz" },
      { de: "abheben", tr: "para çekmek" },
      { de: "die Bankleitzahl", tr: "banka kodu" },
      { de: "die EC-Karte", tr: "banka kartı" },
    ],
    patterns: [
      { de: "Können Sie mir sagen, wie …?", tr: "kibarca bir bilgi sorar" },
      { de: "Ich weiß nicht, ob …", tr: "emin olmadığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bankadayız. Bankada sorulan sorular doğrudan değil dolaylıdır — daha kibar ve daha güvenli. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dolaylı soruda soru sözcüğü bağlaca dönüşür ve fiil en sona gider. Soru sözcüğü yoksa emin olmadığını bildiren bir bağlaç kullanılır. Önce kelimeler.")] },
      word("İlk", { de: "das Girokonto", tr: "vadesiz hesap" }, "günlük işlemler için açılan hesap"),
      word("İkinci", { de: "das Bargeld", tr: "nakit" }),
      word("Üçüncü", { de: "der Geldautomat", tr: "bankamatik" }),
      word("Dördüncü", { de: "die Einzahlung", tr: "para yatırma" }),
      word("Beşinci", { de: "die Zinsen", tr: "faiz" }, "hep çoğul kullanılır"),
      word("Altıncı", { de: "abheben", tr: "para çekmek" }),
      word("Yedinci", { de: "die Bankleitzahl", tr: "banka kodu" }),
      word("Son", { de: "die EC-Karte", tr: "banka kartı" }),
      { say: [tr("İlk kalıbımız bilgi soruyor: kibar bir giriş, sonra soru sözcüğü bağlaç olarak, en sonda fiil.")] },
      { say: [tr("Örnek:"), de("Können Sie mir sagen, wie ich ein Konto eröffne?"), tr("Tekrar edin:"), de("Können Sie mir sagen, wie ich ein Konto eröffne")], expect: repeat("Können Sie mir sagen, wie ich ein Konto eröffne") },
      { say: [tr("Sıra sende: 'Bana banka kodumun ne olduğunu söyleyebilir misiniz?'")], expect: produce("Können Sie mir sagen, wie meine Bankleitzahl lautet", [tr("Soru sözcüğü bağlaç oluyor, fiil sona gidiyor:"), de("Können Sie mir sagen, wie meine Bankleitzahl lautet?"), tr("Tekrar dene.")], ["Können Sie mir sagen, was meine Bankleitzahl ist"]) },
      { say: [tr("İkinci kalıbımız emin olmadığını söylüyor. Soru sözcüğü olmayan sorularda bu bağlaç kullanılır ve fiil yine sona gider.")] },
      { say: [tr("Şimdi: 'Bankamatikten para çekebilir miyim bilmiyorum.'")], expect: produce("Ich weiß nicht, ob ich am Geldautomat Geld abheben kann", [tr("Bağlaçtan sonra modal fiil en sonda:"), de("Ich weiß nicht, ob ich am Geldautomat Geld abheben kann."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich weiß nicht, ob kostet die Einzahlung etwas."), tr("cümlesi doğru mu?")], expect: truefalse("Ich weiß nicht, ob kostet die Einzahlung etwas.", false, [tr("Bu bağlaçtan sonra fiil öne gelmez, cümlenin sonuna gider:"), de("Ich weiß nicht, ob die Einzahlung etwas kostet.")]) },
      { say: [tr("Son: 'Faizin ne kadar olduğunu sorabilir miyim?'")], expect: produce("Darf ich fragen, wie hoch die Zinsen sind", [tr("Soru sözcüğü öbeği bağlaç oluyor, fiil sonda:"), de("Darf ich fragen, wie hoch die Zinsen sind?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bankada hesap açtıracak ve bilmediklerini dolaylı sorularla soracaksın.")] },
    ],
    roleplay: {
      scene: "Bankada hesap açtırmaya geldin. Ücretleri, kartı ve para çekme koşullarını dolaylı sorularla öğreniyorsun.",
      partner: "acelesi olmayan, açıklamayı seven bir banka görevlisi",
      opening: "Guten Tag! Sie möchten ein Konto eröffnen — haben Sie schon Fragen dazu?",
      openingTr: "İyi günler! Hesap açtırmak istiyorsunuz — şimdiden sorunuz var mı?",
      goal: "Hesap türü, ücretler ve kartın nasıl kullanılacağı öğrenilmiş ve hesap açma adımı kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-online-bestellen",
    icon: "tech",
    level: "B1",
    course: "de",
    title: "Online bestellt",
    titleTr: "Çevrimiçi sipariş",
    summary: "Geçmişte olan bir işlemi edilgen çatının geçmiş biçimiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "die Lieferung", tr: "teslimat" },
      { de: "die Bedienungsanleitung", tr: "kullanma kılavuzu" },
      { de: "das Modell", tr: "model" },
      { de: "die Mahnung", tr: "ihtarname" },
      { de: "der Schein", tr: "banknot" },
      { de: "die Münze", tr: "madeni para" },
      { de: "die Mehrwertsteuer", tr: "katma değer vergisi" },
      { de: "die Chipkarte", tr: "çipli kart" },
    ],
    patterns: [
      { de: "Die Lieferung wurde … verschickt.", tr: "geçmişte yapılan bir işlemi anlatır" },
      { de: "Es wurde nichts mitgeschickt.", tr: "bir şeyin eksik olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bir şey sipariş ettin ve bir sorun çıktı. Bugün olanı edilgen çatının geçmişiyle anlatacağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgenin geçmişi bir yardımcı fiilin geçmiş biçimiyle kurulur; asıl fiil yine ortaç hâlinde sonda kalır. Kim yaptı sorusu yine sorulmuyor. Önce kelimeler.")] },
      word("İlk", { de: "die Lieferung", tr: "teslimat" }),
      word("İkinci", { de: "die Bedienungsanleitung", tr: "kullanma kılavuzu" }),
      word("Üçüncü", { de: "das Modell", tr: "model" }),
      word("Dördüncü", { de: "die Mahnung", tr: "ihtarname" }, "ödenmeyen fatura için gelen yazı"),
      word("Beşinci", { de: "der Schein", tr: "banknot" }),
      word("Altıncı", { de: "die Münze", tr: "madeni para" }),
      word("Yedinci", { de: "die Mehrwertsteuer", tr: "katma değer vergisi" }),
      word("Son", { de: "die Chipkarte", tr: "çipli kart" }),
      { say: [tr("İlk kalıbımız geçmişte olan bir işlemi anlatıyor. Yardımcı fiil ikinci sırada ve geçmiş biçiminde, ortaç en sonda.")] },
      { say: [tr("Örnek:"), de("Die Lieferung wurde letzte Woche verschickt."), tr("Tekrar edin:"), de("Die Lieferung wurde letzte Woche verschickt")], expect: repeat("Die Lieferung wurde letzte Woche verschickt") },
      { say: [tr("Sıra sende: 'Yanlış model gönderildi.'")], expect: produce("Das falsche Modell wurde geschickt", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Das falsche Modell wurde geschickt."), tr("Tekrar dene.")], ["Es wurde das falsche Modell geschickt"]) },
      { say: [tr("İkinci kalıbımız eksiği bildiriyor. Öznesi olmayan bir edilgen cümle: bir yer tutucu ile başlıyor.")] },
      { say: [tr("Şimdi: 'Kullanma kılavuzu birlikte gönderilmedi.'")], expect: produce("Die Bedienungsanleitung wurde nicht mitgeschickt", [tr("Olumsuzluk ortaçtan önce:"), de("Die Bedienungsanleitung wurde nicht mitgeschickt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Mahnung wurde gestern schicken."), tr("cümlesi doğru mu?")], expect: truefalse("Die Mahnung wurde gestern schicken.", false, [tr("Edilgende asıl fiil ortaç hâlinde olmalı:"), de("Die Mahnung wurde gestern geschickt.")]) },
      { say: [tr("Son: 'Katma değer vergisi hesaba katılmamıştı.'")], expect: produce("Die Mehrwertsteuer wurde nicht berechnet", [tr("Yardımcı fiil geçmiş biçiminde, ortaç sonda:"), de("Die Mehrwertsteuer wurde nicht berechnet."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi müşteri hizmetlerini arayacak ve siparişinde ne olduğunu anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Çevrimiçi sipariş ettiğin üründe sorun var: yanlış model geldi ve kılavuz eksik. Müşteri hizmetlerini arayıp olanı sırayla anlatıyorsun.",
      partner: "önce sipariş numarasını isteyen, sistemli bir müşteri temsilcisi",
      opening: "Kundenservice, guten Tag! Worum geht es bei Ihrer Bestellung?",
      openingTr: "Müşteri hizmetleri, iyi günler! Siparişinizle ilgili sorun nedir?",
      goal: "Ne sipariş edildiği, ne geldiği ve neyin eksik olduğu anlatılmış ve bir çözüm kararlaştırılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-kleidung-kaufen",
    icon: "shirt",
    level: "B1",
    course: "de",
    title: "Passt das?",
    titleTr: "Kıyafet denemek",
    summary: "Sıfatları ismin önünde doğru çekmeyi öğretir; beden ve kumaş konuşulur.",
    minutes: 10,
    focusId: "Adjektivdeklination",
    vocab: [
      { de: "das Kostüm", tr: "döpiyes" },
      { de: "der Strumpf", tr: "uzun çorap" },
      { de: "die Socke", tr: "çorap" },
      { de: "der Schmuck", tr: "takı" },
      { de: "das Leder", tr: "deri" },
      { de: "die Wolle", tr: "yün" },
      { de: "der Stoff", tr: "kumaş" },
      { de: "elegant", tr: "zarif" },
    ],
    patterns: [
      { de: "ein eleganter Mantel", tr: "belirsiz artikelden sonra sıfat çekimi" },
      { de: "der weiche Stoff", tr: "belirli artikelden sonra sıfat çekimi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kıyafet deniyoruz. Almancada sıfat ismin önüne geçtiğinde çekim alır ve bu çekim artikele göre değişir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şu: belirli artikelden sonra sıfat zayıf çekilir, belirsizden sonra sıfat cinsiyeti kendi taşır. Türkçede sıfat hiç değişmediği için burası dikkat ister. Önce kelimeler.")] },
      word("İlk", { de: "das Kostüm", tr: "döpiyes" }, "ceket ve etekten oluşan takım"),
      word("İkinci", { de: "der Strumpf", tr: "uzun çorap" }),
      word("Üçüncü", { de: "die Socke", tr: "çorap" }),
      word("Dördüncü", { de: "der Schmuck", tr: "takı" }),
      word("Beşinci", { de: "das Leder", tr: "deri" }),
      word("Altıncı", { de: "die Wolle", tr: "yün" }),
      word("Yedinci", { de: "der Stoff", tr: "kumaş" }),
      word("Son", { de: "elegant", tr: "zarif" }),
      { say: [tr("İlk kalıbımız belirsiz artikelli: artikel cinsiyeti göstermediği için sıfat onu göstermek zorunda kalıyor.")] },
      { say: [tr("Örnek:"), de("Das ist ein eleganter Mantel."), tr("Tekrar edin:"), de("Das ist ein eleganter Mantel")], expect: repeat("Das ist ein eleganter Mantel") },
      { say: [tr("Sıra sende: 'Bu zarif bir döpiyes.' Nötr bir ad kullanıyorsun, dikkat et.")], expect: produce("Das ist ein elegantes Kostüm", [tr("Nötr adda belirsiz artikelden sonra sıfat başka bir ek alır:"), de("Das ist ein elegantes Kostüm."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız belirli artikelli: artikel işini yaptığı için sıfat en kısa eki alıyor.")] },
      { say: [tr("Şimdi: 'Yumuşak kumaş daha pahalı.'")], expect: produce("Der weiche Stoff ist teurer", [tr("Belirli artikelden sonra sıfat zayıf çekiliyor:"), de("Der weiche Stoff ist teurer."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich suche ein warmer Pullover aus Wolle."), tr("cümlesi doğru mu?")], expect: truefalse("Ich suche ein warmer Pullover aus Wolle.", false, [tr("Burada ad nesne konumunda, o yüzden hem artikel hem sıfat belirtme hâline girer:"), de("Ich suche einen warmen Pullover aus Wolle.")]) },
      { say: [tr("Son: 'Deri ayakkabıyı yün çorapla giyiyorum.'")], expect: produce("Ich trage die Lederschuhe mit warmen Socken", [tr("Edattan sonra çoğul yönelme hâli, sıfat da ona uyuyor:"), de("Ich trage die Lederschuhe mit warmen Socken."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir mağazadasın ve kıyafet deneyeceksin.")] },
    ],
    roleplay: {
      scene: "Bir mağazada kıyafet deniyorsun. Beden, kumaş ve fiyat konuşuyor, sıfatları ismin önünde kullanarak ne aradığını anlatıyorsun.",
      partner: "her şeyi denetmek isteyen istekli bir satıcı",
      opening: "Kann ich Ihnen helfen? Suchen Sie etwas Bestimmtes?",
      openingTr: "Yardımcı olabilir miyim? Belirli bir şey mi arıyorsunuz?",
      goal: "Aranan parça sıfatlarla tarif edilmiş, denenmiş ve alınıp alınmayacağına karar verilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-material-waehlen",
    icon: "repair",
    level: "B1",
    course: "de",
    title: "Woraus ist das?",
    titleTr: "Neyden yapılmış?",
    summary: "Edatlı ilgi cümlesiyle bir nesnenin neyden yapıldığını tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Präposition",
    vocab: [
      { de: "der Kunststoff", tr: "plastik malzeme" },
      { de: "das Plastik", tr: "plastik" },
      { de: "das Metall", tr: "metal" },
      { de: "das Holz", tr: "ahşap" },
      { de: "das Teil", tr: "parça" },
      { de: "der Kasten", tr: "kasa, kutu" },
      { de: "die Batterie", tr: "pil" },
      { de: "der Stecker", tr: "fiş" },
    ],
    patterns: [
      { de: "der Kasten, aus dem …", tr: "edat ilgi zamirinin önüne gelir ve hâlini belirler" },
      { de: "das Teil, mit dem …", tr: "aracı gösteren edatlı ilgi cümlesi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir nesneyi adını bilmeden tanımlayacağız: neyden yapıldığını, ne işe yaradığını söyleyerek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edat ilgi zamirinin ÖNÜNE gelir ve zamirin hâlini o belirler. Türkçede edat sonda durduğu için sıra ters geliyor. Önce kelimeler.")] },
      word("İlk", { de: "der Kunststoff", tr: "plastik malzeme" }, "sanayide üretilen yapay madde"),
      word("İkinci", { de: "das Plastik", tr: "plastik" }),
      word("Üçüncü", { de: "das Metall", tr: "metal" }),
      word("Dördüncü", { de: "das Holz", tr: "ahşap" }),
      word("Beşinci", { de: "das Teil", tr: "parça" }),
      word("Altıncı", { de: "der Kasten", tr: "kasa, kutu" }),
      word("Yedinci", { de: "die Batterie", tr: "pil" }),
      word("Son", { de: "der Stecker", tr: "fiş" }),
      { say: [tr("İlk kalıbımız malzemeyi soruyor. Kaynağı gösteren edat yönelme hâli ister, o yüzden ilgi zamiri de yönelme hâlinde.")] },
      { say: [tr("Örnek:"), de("Das ist der Kasten, aus dem die Batterie kommt."), tr("Tekrar edin:"), de("Das ist der Kasten, aus dem die Batterie kommt")], expect: repeat("Das ist der Kasten, aus dem die Batterie kommt") },
      { say: [tr("Sıra sende: 'Bu, ahşaptan yapılmış bir parça.'")], expect: produce("Das ist ein Teil, das aus Holz gemacht ist", [tr("Nötr adda ilgi zamiri değişmiyor, fiil sonda:"), de("Das ist ein Teil, das aus Holz gemacht ist."), tr("Tekrar dene.")], ["Das ist ein Teil aus Holz"]) },
      { say: [tr("İkinci kalıbımız aracı gösteriyor: birlikte anlamındaki edat. Bu edat da yönelme hâli ister.")] },
      { say: [tr("Şimdi: 'Bu, fişi taktığın parça.'")], expect: produce("Das ist das Teil, mit dem man den Stecker verbindet", [tr("Edat zamirin önünde, fiil yan cümlenin sonunda:"), de("Das ist das Teil, mit dem man den Stecker verbindet."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist der Kasten, den die Batterie drin ist."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist der Kasten, den die Batterie drin ist.", false, [tr("Yer bildiren bir edat gerekiyor ve o edat zamirin önüne gelip hâlini belirliyor:"), de("Das ist der Kasten, in dem die Batterie ist.")]) },
      { say: [tr("Son: 'Metalden yapılan parçalar daha ağır.'")], expect: produce("Teile aus Metall sind schwerer", [tr("Kaynak edatı ile kısa biçim; ilgi cümlesi şart değil:"), de("Teile aus Metall sind schwerer."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir hırdavatçıda adını bilmediğin bir parçayı tarif edeceksin.")] },
    ],
    roleplay: {
      scene: "Bir hırdavatçıdasın ve aradığın parçanın adını bilmiyorsun. Neyden yapıldığını, ne işe yaradığını ve nereye takıldığını tarif ediyorsun.",
      partner: "tarifi dinleyip doğru parçayı bulmaya çalışan sabırlı bir esnaf",
      opening: "Was suchen Sie denn? Beschreiben Sie es einfach — wozu brauchen Sie es?",
      openingTr: "Ne arıyorsunuz? Anlatın yeter — ne için lazım?",
      goal: "Parça malzemesi ve işleviyle tarif edilmiş ve esnaf doğru parçayı bulmuş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-wirtschaft-reden",
    icon: "chart",
    level: "B1",
    course: "de",
    title: "Wie läuft die Wirtschaft?",
    titleTr: "Ekonomi konuşmak",
    summary: "Ekonomiyi ikili bağlaçlarla dengeli biçimde tartışmayı öğretir.",
    minutes: 11,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "die Wirtschaft", tr: "ekonomi" },
      { de: "die Industrie", tr: "sanayi" },
      { de: "die Fabrik", tr: "fabrika" },
      { de: "der Import", tr: "ithalat" },
      { de: "der Export", tr: "ihracat" },
      { de: "die Produktion", tr: "üretim" },
      { de: "der Hersteller", tr: "üretici" },
      { de: "die Konkurrenz", tr: "rekabet" },
    ],
    patterns: [
      { de: "nicht nur …, sondern auch …", tr: "yalnız bunu değil şunu da kapsar" },
      { de: "entweder … oder …", tr: "iki seçenekten birini gösterir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ekonomi konuşacağız. Bu konuda tek yanlı konuşmak kolay, dengeli konuşmak zor — ikili bağlaçlar tam da bunun için var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İlk bağlacımız bir şeyi eklerken kullanılır ve ikinci parçası özel bir bağlaçtır; sıradan bir bağlaçla değiştirilemez. Önce kelimeler.")] },
      word("İlk", { de: "die Wirtschaft", tr: "ekonomi" }),
      word("İkinci", { de: "die Industrie", tr: "sanayi" }),
      word("Üçüncü", { de: "die Fabrik", tr: "fabrika" }),
      word("Dördüncü", { de: "der Import", tr: "ithalat" }),
      word("Beşinci", { de: "der Export", tr: "ihracat" }),
      word("Altıncı", { de: "die Produktion", tr: "üretim" }),
      word("Yedinci", { de: "der Hersteller", tr: "üretici" }),
      word("Son", { de: "die Konkurrenz", tr: "rekabet" }),
      { say: [tr("İlk kalıbımız iki şeyi kapsıyor ve ikincisini öne çıkarıyor. Türkçedeki 'sadece değil, aynı zamanda' ile aynı işi görüyor.")] },
      { say: [tr("Örnek:"), de("Die Fabrik produziert nicht nur für den Export, sondern auch für den Markt hier."), tr("Tekrar edin:"), de("Die Fabrik produziert nicht nur für den Export, sondern auch für den Markt hier")], expect: repeat("Die Fabrik produziert nicht nur für den Export, sondern auch für den Markt hier") },
      { say: [tr("Sıra sende: 'Sanayi yalnız büyümedi, aynı zamanda değişti.'")], expect: produce("Die Industrie ist nicht nur gewachsen, sondern hat sich auch verändert", [tr("İkinci parçada özne tekrarlanmıyor ama fiil ikinci sırada:"), de("Die Industrie ist nicht nur gewachsen, sondern hat sich auch verändert."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız iki seçenek sunuyor: ya biri ya öteki. Bu bağlaç seçim yapmaya zorlar, dengelemez.")] },
      { say: [tr("Şimdi: 'Ya ithalat artar ya da üretim büyür.'")], expect: produce("Entweder steigt der Import oder die Produktion wächst", [tr("İlk bölüm bağlaçla başladığı için fiil hemen arkasından geliyor:"), de("Entweder steigt der Import oder die Produktion wächst."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Konkurrenz ist nicht nur groß, aber auch schnell."), tr("cümlesi doğru mu?")], expect: truefalse("Die Konkurrenz ist nicht nur groß, aber auch schnell.", false, [tr("Bu ikili bağlacın ikinci parçası sabittir ve sıradan bir zıtlık bağlacıyla değiştirilemez:"), de("Die Konkurrenz ist nicht nur groß, sondern auch schnell.")]) },
      { say: [tr("Son: 'Üretici ya fiyatı düşürür ya da müşterisini kaybeder.'")], expect: produce("Entweder senkt der Hersteller den Preis oder er verliert seine Kunden", [tr("İki bölüm de ana cümle, ikisinde de fiil doğru yerde:"), de("Entweder senkt der Hersteller den Preis oder er verliert seine Kunden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir iş arkadaşınla sektörün gidişatını dengeli biçimde tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir iş arkadaşınla sektörünüzün gidişatını konuşuyorsunuz: üretim, rekabet, ithalat. Her görüşün iki yanını ikili bağlaçlarla söylüyorsun.",
      partner: "kötümser ama veriye açık bir iş arkadaşı",
      opening: "Sag mal, wie siehst du die Lage in unserer Branche gerade?",
      openingTr: "Söylesene, sektörümüzdeki durumu şu an nasıl görüyorsun?",
      goal: "En az üç konuda görüş bildirilmiş, her birinin iki yanı söylenmiş ve ortak bir sonuca varılmış olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-gewinn-verlust",
    icon: "money",
    level: "B1",
    course: "de",
    title: "Gewinn und Verlust",
    titleTr: "Rakamları okumak",
    summary: "Bir tabloyu edilgen cümlelerle anlatmayı ve rakamı yorumlamayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "der Gewinn", tr: "kâr" },
      { de: "der Unternehmer", tr: "girişimci" },
      { de: "die Statistik", tr: "istatistik" },
      { de: "die Tabelle", tr: "çizelge" },
      { de: "das System", tr: "sistem" },
      { de: "der Faktor", tr: "etken" },
      { de: "knapp", tr: "kıt, dar" },
      { de: "die Meldung", tr: "bildirim" },
    ],
    patterns: [
      { de: "In der Tabelle wird … gezeigt.", tr: "bir çizelgenin ne gösterdiğini söyler" },
      { de: "Das wird oft übersehen.", tr: "gözden kaçan bir şeye dikkat çeker" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir tablo okuyacağız. Rakam anlatan cümleler neredeyse hep edilgendir çünkü rakamı kimin çıkardığı önemli değil. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yardımcı fiil ikinci sırada, ortaç en sonda. Cümle bir yer tümleciyle başlarsa özne fiilin arkasına geçer. Önce kelimeler.")] },
      word("İlk", { de: "der Gewinn", tr: "kâr" }),
      word("İkinci", { de: "der Unternehmer", tr: "girişimci" }),
      word("Üçüncü", { de: "die Statistik", tr: "istatistik" }),
      word("Dördüncü", { de: "die Tabelle", tr: "çizelge" }),
      word("Beşinci", { de: "das System", tr: "sistem" }),
      word("Altıncı", { de: "der Faktor", tr: "etken" }),
      word("Yedinci", { de: "knapp", tr: "kıt, dar" }),
      word("Son", { de: "die Meldung", tr: "bildirim" }),
      { say: [tr("İlk kalıbımız tabloyu tanıtıyor. Cümle yer tümleciyle başlıyor, o yüzden yardımcı fiil hemen arkasından geliyor ve özne sonra.")] },
      { say: [tr("Örnek:"), de("In der Tabelle wird der Gewinn pro Jahr gezeigt."), tr("Tekrar edin:"), de("In der Tabelle wird der Gewinn pro Jahr gezeigt")], expect: repeat("In der Tabelle wird der Gewinn pro Jahr gezeigt") },
      { say: [tr("Sıra sende: 'İstatistikte üç etken karşılaştırılıyor.'")], expect: produce("In der Statistik werden drei Faktoren verglichen", [tr("Özne çoğul olduğu için yardımcı fiil de çoğula giriyor:"), de("In der Statistik werden drei Faktoren verglichen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız gözden kaçana dikkat çekiyor. Kısa, kişisiz ve tartışmada çok işe yarar.")] },
      { say: [tr("Şimdi: 'Bu genelde gözden kaçırılır.'")], expect: produce("Das wird oft übersehen", [tr("Sıklık zarfı ortada, ortaç sonda:"), de("Das wird oft übersehen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("In der Meldung wird zwei Zahlen genannt."), tr("cümlesi doğru mu?")], expect: truefalse("In der Meldung wird zwei Zahlen genannt.", false, [tr("Özne çoğul olduğunda yardımcı fiil de çoğula girer:"), de("In der Meldung werden zwei Zahlen genannt.")]) },
      { say: [tr("Son: 'Girişimcinin zamanı dar, o yüzden sistem basit tutuluyor.'")], expect: produce("Die Zeit des Unternehmers ist knapp, deshalb wird das System einfach gehalten", [tr("Sonuç zarfından sonra yardımcı fiil ikinci sırada:"), de("Die Zeit des Unternehmers ist knapp, deshalb wird das System einfach gehalten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir toplantıda tabloyu sunacak ve rakamları yorumlayacaksın.")] },
    ],
    roleplay: {
      scene: "Küçük bir toplantıda geçen yılın rakamlarını sunuyorsun. Tablonun ne gösterdiğini anlatıyor, bir rakamı yorumluyor ve soruları yanıtlıyorsun.",
      partner: "rakamların arkasındaki sebebi soran bir ekip arkadaşı",
      opening: "Danke für die Tabelle. Was wird da eigentlich genau gezeigt?",
      openingTr: "Çizelge için teşekkürler. Orada tam olarak ne gösteriliyor?",
      goal: "Tablonun içeriği anlatılmış, bir rakam yorumlanmış ve en az bir soru yanıtlanmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-anzeige-lesen",
    icon: "mail",
    level: "B1",
    course: "de",
    title: "Die Annonce",
    titleTr: "İlan okumak",
    summary: "Bir ilanı ilgi cümleleriyle tanımlamayı ve ayrıntıyı sormayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Nominativ",
    vocab: [
      { de: "die Annonce", tr: "ilan" },
      { de: "das Inserat", tr: "gazete ilanı" },
      { de: "die Broschüre", tr: "broşür" },
      { de: "die Überschrift", tr: "başlık" },
      { de: "der Abschnitt", tr: "bölüm" },
      { de: "das Detail", tr: "ayrıntı" },
      { de: "die Einzelheit", tr: "ayrıntı" },
      { de: "der Hinweis", tr: "ipucu, uyarı" },
    ],
    patterns: [
      { de: "die Annonce, die … verspricht", tr: "ilanı tanımlayan ilgi cümlesi" },
      { de: "Mir fehlt der Hinweis auf …", tr: "eksik bilgiyi söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir ilan okuyacağız. İlanlar kısa yazılır ve önemli olan çoğu zaman yazmayan şeydir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İlanı tanımlarken ilgi cümlesi kuracağız. Tanımlanan şey yan cümlenin öznesi olduğunda ilgi zamiri yalın hâlde kalır. Önce kelimeler.")] },
      word("İlk", { de: "die Annonce", tr: "ilan" }),
      word("İkinci", { de: "das Inserat", tr: "gazete ilanı" }),
      word("Üçüncü", { de: "die Broschüre", tr: "broşür" }),
      word("Dördüncü", { de: "die Überschrift", tr: "başlık" }),
      word("Beşinci", { de: "der Abschnitt", tr: "bölüm" }),
      word("Altıncı", { de: "das Detail", tr: "ayrıntı" }),
      word("Yedinci", { de: "die Einzelheit", tr: "ayrıntı" }, "aynı anlama gelen ikinci sözcük"),
      word("Son", { de: "der Hinweis", tr: "ipucu, uyarı" }),
      { say: [tr("İlk kalıbımız ilanı tanımlıyor. Tanımlanan şey yan cümlede iş yapan taraf olduğu için zamir yalın hâlde.")] },
      { say: [tr("Örnek:"), de("Das ist die Annonce, die einen guten Preis verspricht."), tr("Tekrar edin:"), de("Das ist die Annonce, die einen guten Preis verspricht")], expect: repeat("Das ist die Annonce, die einen guten Preis verspricht") },
      { say: [tr("Sıra sende: 'Bu, hiçbir ayrıntı vermeyen ilan.'")], expect: produce("Das ist das Inserat, das keine Details nennt", [tr("Nötr adda ilgi zamiri de nötr, fiil sonda:"), de("Das ist das Inserat, das keine Details nennt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız eksiği söylüyor: eksik olmak fiili yönelme hâliyle kurulur, yani eksik olan şey özne olur.")] },
      { say: [tr("Şimdi: 'Bana fiyat bilgisi eksik geliyor.'")], expect: produce("Mir fehlt der Hinweis auf den Preis", [tr("Kişi yönelme hâlinde, eksik olan şey yalın hâlde özne:"), de("Mir fehlt der Hinweis auf den Preis."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist die Broschüre, das alle Einzelheiten zeigt."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist die Broschüre, das alle Einzelheiten zeigt.", false, [tr("İlgi zamiri tanımlanan adın cinsiyetine uyar, yan cümlenin nesnesine değil:"), de("Das ist die Broschüre, die alle Einzelheiten zeigt.")]) },
      { say: [tr("Son: 'Başlıktan sonraki bölüm en önemlisi.'")], expect: produce("Der Abschnitt nach der Überschrift ist der wichtigste", [tr("Edat yönelme hâli istiyor, en üstün derece belirli artikelle:"), de("Der Abschnitt nach der Überschrift ist der wichtigste."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir ilanı arkadaşınla inceleyecek ve eksik bilgileri sayacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla ikinci el bir ilanı inceliyorsunuz. İlanı tanımlıyor, iyi ve şüpheli yanlarını söylüyor, eksik bilgileri sayıyorsun.",
      partner: "ilana kanmaya hazır, iyimser bir arkadaş",
      opening: "Guck mal, diese Annonce hier — klingt doch super, oder?",
      openingTr: "Şuna bak, bu ilan — kulağa harika geliyor, değil mi?",
      goal: "İlan tanımlanmış, en az iki eksik bilgi sayılmış ve satıcıya sorulacak sorular belirlenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-reklamation-brief",
    icon: "pen",
    level: "B1",
    course: "de",
    title: "Der Beschwerdebrief",
    titleTr: "Şikâyet mektubu",
    summary: "Yazılı şikâyetin kibar ama kesin dilini dilek kipiyle öğretir.",
    minutes: 11,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Verwaltung", tr: "idare" },
      { de: "die Vertretung", tr: "vekâlet" },
      { de: "der Stempel", tr: "damga" },
      { de: "der Ordner", tr: "klasör" },
      { de: "die Mappe", tr: "dosya" },
      { de: "besorgen", tr: "temin etmek" },
      { de: "erhalten", tr: "almak" },
      { de: "die Einführung", tr: "giriş" },
    ],
    patterns: [
      { de: "Ich wäre Ihnen dankbar, wenn …", tr: "en kibar yazılı rica" },
      { de: "Ich hätte erwartet, dass …", tr: "beklentinin karşılanmadığını kibarca söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün yazılı şikâyet yazacağız. Almanya'da bir hakkı aramanın yolu telefon değil mektuptur ve mektubun dili konuşmadan daha kibardır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yazılı nezaket dilek kipiyle kurulur. Sert bir talep bile dilek kipine girince kibar kalır ama netliğini kaybetmez. Önce kelimeler.")] },
      word("İlk", { de: "die Verwaltung", tr: "idare" }),
      word("İkinci", { de: "die Vertretung", tr: "vekâlet" }),
      word("Üçüncü", { de: "der Stempel", tr: "damga" }),
      word("Dördüncü", { de: "der Ordner", tr: "klasör" }),
      word("Beşinci", { de: "die Mappe", tr: "dosya" }),
      word("Altıncı", { de: "besorgen", tr: "temin etmek" }),
      word("Yedinci", { de: "erhalten", tr: "almak" }, "resmî dilde 'bekommen' yerine kullanılır"),
      word("Son", { de: "die Einführung", tr: "giriş" }),
      { say: [tr("İlk kalıbımız yazılı ricanın en kibar biçimi: olmak fiilinin dilek kipi, sonra koşul yan cümlesi. Yan cümlede fiil sona gider.")] },
      { say: [tr("Örnek:"), de("Ich wäre Ihnen dankbar, wenn Sie mir den Beleg schicken würden."), tr("Tekrar edin:"), de("Ich wäre Ihnen dankbar, wenn Sie mir den Beleg schicken würden")], expect: repeat("Ich wäre Ihnen dankbar, wenn Sie mir den Beleg schicken würden") },
      { say: [tr("Sıra sende: 'Dosyayı temin ederseniz size minnettar olurum.'")], expect: produce("Ich wäre Ihnen dankbar, wenn Sie die Mappe besorgen würden", [tr("Koşul yan cümlesinde dilek kipi ve fiil sonda:"), de("Ich wäre Ihnen dankbar, wenn Sie die Mappe besorgen würden."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız beklentinin karşılanmadığını söylüyor. Suçlamıyor, yalnız beklentiyi hatırlatıyor — resmî yazının en güçlü cümlesi budur.")] },
      { say: [tr("Şimdi: 'Bir cevap alacağımı beklerdim.'")], expect: produce("Ich hätte erwartet, dass ich eine Antwort erhalte", [tr("Bağlaçtan sonra fiil sona gidiyor:"), de("Ich hätte erwartet, dass ich eine Antwort erhalte."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich wäre dankbar, wenn Sie schicken mir den Stempel."), tr("cümlesi doğru mu?")], expect: truefalse("Ich wäre dankbar, wenn Sie schicken mir den Stempel.", false, [tr("Koşul bağlacından sonra fiil cümlenin en sonuna gider:"), de("Ich wäre dankbar, wenn Sie mir den Stempel schicken.")]) },
      { say: [tr("Son: 'İdareden yazılı bir cevap rica ediyorum.'")], expect: produce("Ich bitte die Verwaltung um eine schriftliche Antwort", [tr("Bu fiil sabit bir edat alıyor ve ondan sonra belirtme hâli geliyor:"), de("Ich bitte die Verwaltung um eine schriftliche Antwort."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir idareyle telefonda konuşacak ve yazılı şikâyetinin ne diyeceğini anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir idareyi arıyorsun: gönderdiğin evrak kaybolmuş. Ne gönderdiğini, ne beklediğini ve yazılı şikâyette ne yazacağını anlatıyorsun.",
      partner: "sorumluluğu üstlenmekten kaçınan ama nazik bir memur",
      opening: "Verwaltung, guten Tag. Wie kann ich Ihnen helfen?",
      openingTr: "İdare, iyi günler. Size nasıl yardımcı olabilirim?",
      goal: "Kaybolan evrak anlatılmış, beklenti kibarca söylenmiş ve yazılı şikâyet için bir adres alınmış olur.",
      minTurns: 9,
    },
  },
];
