import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 3 — Edilgenin bütün hâlleri (021–030).
 *
 * B1'de edilgenin iki zamanı öğrenilmişti. Bu modül onu bir SİSTEME
 * çeviriyor: geçmiş (ist … worden), kipli (muss … werden), durum (ist
 * geöffnet) ve edilgen yerine geçen üç yapı (lässt sich …, ist zu …, -bar).
 *
 * Türkçe konuşan için asıl ayrım şu ikisi arasında: "kapı açılıyor" bir
 * SÜREÇ, "kapı açık" bir DURUM. Türkçede ikisi de edilgen ekle kurulabilir,
 * Almancada iki ayrı yapıdır ve karıştırmak anlamı değiştirir. Bu yüzden
 * modülün ortasında ikisini karşı karşıya koyan bir ders var.
 *
 * Sahneler bilerek dağınık: şantiye, mutfak, kaza raporu, restorasyon, bakım
 * randevusu. Edilgen tek bir alanın dili değil, failin önemsizleştiği HER
 * alanın dili.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B03: Lesson[] = [
  {
    id: "de-b2-passiv-perfekt",
    icon: "office",
    level: "B2",
    course: "de",
    title: "Es ist erledigt worden",
    titleTr: "Edilgen Perfekt",
    summary: "Tamamlanmış işleri edilgen Perfekt ile bildirmeyi öğretir.",
    minutes: 12,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "bearbeiten", tr: "işleme almak" },
      { de: "die Erledigung", tr: "yapılacak iş" },
      { de: "der Arbeitsgang", tr: "iş adımı" },
      { de: "die Abnahme", tr: "kabul" },
      { de: "die Zertifizierung", tr: "sertifikasyon" },
      { de: "der Ausfall", tr: "kesinti" },
      { de: "ausliefern", tr: "sevk etmek" },
      { de: "zügig", tr: "hızlıca" },
    ],
    patterns: [
      { de: "… ist … worden", tr: "tekil: yapılmış oldu" },
      { de: "… sind … worden", tr: "çoğul: yapılmış oldular" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül ve konusu tek bir yapı değil, bütün bir sistem: edilgen. Bugün en çok işine yarayacak hâliyle başlıyoruz — bitmiş işleri bildirmek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şu: sein yardımcı fiili, ortaç, sonra kısalmış biçim. Uzun biçim 'geworden' burada kullanılmaz ve bu, seviyenin en görünür işaretlerinden biri. Önce kelimeler.")] },
      word("İlk", { de: "bearbeiten", tr: "işleme almak" }),
      word("İkinci", { de: "die Erledigung", tr: "yapılacak iş" }),
      word("Üçüncü", { de: "der Arbeitsgang", tr: "iş adımı" }, "Üretimde ya da dosyada tek bir adım."),
      word("Dördüncü", { de: "die Abnahme", tr: "kabul" }, "İşin bittiğini resmen kabul etme."),
      word("Beşinci", { de: "die Zertifizierung", tr: "sertifikasyon" }),
      word("Altıncı", { de: "der Ausfall", tr: "kesinti" }),
      word("Yedinci", { de: "ausliefern", tr: "sevk etmek" }),
      word("Son", { de: "zügig", tr: "hızlıca" }),
      { say: [tr("Kalıbımız:"), de("… ist … worden"), tr("Çoğulda tek değişen yardımcı fiil oluyor: sind.")] },
      { say: [tr("Örnek:"), de("Der Auftrag ist gestern bearbeitet worden."), tr("Tekrar edin:"), de("Der Auftrag ist gestern bearbeitet worden")], expect: repeat("Der Auftrag ist gestern bearbeitet worden") },
      { say: [tr("Sıra sende: 'Bu iş adımı şimdiye kadar işleme alınmadı.'")], expect: produce("Dieser Arbeitsgang ist bislang nicht bearbeitet worden", [tr("Olumsuzluk ortaçtan önce, kısalmış biçim en sonda:"), de("Dieser Arbeitsgang ist bislang nicht bearbeitet worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Proje geçen ay tamamlandı.'")], expect: produce("Das Projekt ist letzten Monat abgeschlossen worden", [tr("Ayrılabilen fiilin ortacı ge- ekini ortada alır:"), de("Das Projekt ist letzten Monat abgeschlossen worden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, çoğulla: 'Bugüne kadar üç başvuru işleme alındı.'")], expect: produce("Bis heute sind drei Anträge bearbeitet worden", [tr("Çoğul özne sind ister:"), de("Bis heute sind drei Anträge bearbeitet worden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Bis heute sind drei Anträge bearbeitet worden."), tr("cümlesi doğru mu?")], expect: truefalse("Bis heute sind drei Anträge bearbeitet worden.", true, [tr("Doğru. Çoğul özne sind alıyor, ortaç ortada ve kısalmış biçim sonda.")]) },
      { say: [tr("Son: 'Mal dün sevk edildi.'")], expect: produce("Die Ware ist gestern ausgeliefert worden", [tr("Ayrılabilen fiilin ortacı ge- ekini ortada alır:"), de("Die Ware ist gestern ausgeliefert worden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada şefine haftanın durumunu bildireceksin: ne yapıldı, ne yapılmadı, sebebi ne.")] },
    ],
    roleplay: {
      scene: "Şefinle haftalık durum görüşmesindesin. Hangi işlerin tamamlandığını, hangilerinin hâlâ beklediğini ve sebebini edilgen geçmişle bildir; kalanlar için tarih ver.",
      partner: "kısa cevap isteyen, tarih soran bir bölüm şefi",
      opening: "Ich habe wenig Zeit — sagen Sie mir kurz: Was ist diese Woche erledigt worden und was nicht?",
      openingTr: "Vaktim az — kısaca söyleyin: Bu hafta ne halledildi, ne halledilmedi?",
      goal: "Biten ve bitmeyen işler sayılmış, gecikmenin sebebi söylenmiş ve kalanlar için tarih verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-passiv-modal",
    icon: "law",
    level: "B2",
    course: "de",
    title: "Das muss geprüft werden",
    titleTr: "Kipli edilgen",
    summary: "Zorunluluk ve imkânı edilgen yapıyla bildirmeyi öğretir.",
    minutes: 12,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "bedenken", tr: "göz önünde bulundurmak" },
      { de: "die Sicherheitsvorschrift", tr: "güvenlik kuralı" },
      { de: "die Betriebsanleitung", tr: "işletme kılavuzu" },
      { de: "vorschreiben", tr: "zorunlu kılmak" },
      { de: "vorlegen", tr: "ibraz etmek" },
      { de: "absegnen", tr: "onaydan geçirmek" },
      { de: "fachgerecht", tr: "tekniğine uygun" },
      { de: "unverzüglich", tr: "derhâl" },
    ],
    patterns: [
      { de: "muss/kann/soll … werden", tr: "kipli edilgen" },
      { de: "Das sollte bedacht werden.", tr: "kişisiz uyarı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün edilgene bir kip ekliyoruz. Resmî yazışmanın en sık cümlesi bu: 'incelenmeli', 'sunulabilir', 'değiştirilemez'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yapı basit ama sırası kritik: çekimli kip fiili ikinci sırada, sonda önce ortaç sonra werden. Bu iki kelimenin sırası çok karıştırılır. Önce kelimeler.")] },
      word("İlk", { de: "bedenken", tr: "göz önünde bulundurmak" }),
      word("İkinci", { de: "die Sicherheitsvorschrift", tr: "güvenlik kuralı" }),
      word("Üçüncü", { de: "die Betriebsanleitung", tr: "işletme kılavuzu" }),
      word("Dördüncü", { de: "vorschreiben", tr: "zorunlu kılmak" }),
      word("Beşinci", { de: "vorlegen", tr: "ibraz etmek" }),
      word("Altıncı", { de: "absegnen", tr: "onaydan geçirmek" }, "Yetkilinin resmen onay vermesi."),
      word("Yedinci", { de: "fachgerecht", tr: "tekniğine uygun" }),
      word("Son", { de: "unverzüglich", tr: "derhâl" }),
      { say: [tr("Kalıbımız:"), de("muss … geprüft werden"), tr("Sondaki iki kelime her zaman bu sırada: önce ortaç, sonra werden.")] },
      { say: [tr("Örnek:"), de("Der Antrag muss bis Freitag geprüft werden."), tr("Tekrar edin:"), de("Der Antrag muss bis Freitag geprüft werden")], expect: repeat("Der Antrag muss bis Freitag geprüft werden") },
      { say: [tr("Sıra sende: 'Belgeler çevrimiçi sunulabilir.'")], expect: produce("Die Unterlagen können online vorgelegt werden", [tr("Çoğul kip fiili, sonda ortaç ve werden:"), de("Die Unterlagen können online vorgelegt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu göz önünde bulundurulmalı.'")], expect: produce("Das sollte bedacht werden", [tr("Kısa ve kişisiz bir uyarı cümlesi:"), de("Das sollte bedacht werden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, olumsuzla: 'Yönetmelik değiştirilemez.'")], expect: produce("Die Sicherheitsvorschrift kann nicht geändert werden", [tr("Olumsuzluk ortaçtan önce gelir:"), de("Die Sicherheitsvorschrift kann nicht geändert werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Unterlagen können online vorgelegt sein."), tr("cümlesi doğru mu?")], expect: truefalse("Die Unterlagen können online vorgelegt sein.", false, [tr("Kipli edilgende sonda sein değil werden bulunur:"), de("Die Unterlagen können online vorgelegt werden.")]) },
      { say: [tr("Son: 'Başvurunun derhâl onaydan geçirilmesi gerekiyor.'")], expect: produce("Der Antrag muss unverzüglich abgesegnet werden", [tr("Zorunluluk müssen ile, sonda ortaç ve werden:"), de("Der Antrag muss unverzüglich abgesegnet werden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kurumda başvurunun hangi adımlardan geçmesi gerektiğini soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir kurumun danışma masasındasın ve başvurunun hangi adımlardan geçmesi gerektiğini soruyorsun: ne sunulmalı, ne incelenecek, ne kadar sürer, hangi belge onaylanmalı.",
      partner: "kuralları yönetmelik diliyle anlatan bir memur",
      opening: "Ihr Antrag liegt bei uns. Bevor er bearbeitet werden kann, muss allerdings noch etwas geklärt werden — wissen Sie, was fehlt?",
      openingTr: "Başvurunuz bizde. Ancak işleme alınabilmesi için bir şeyin netleşmesi gerekiyor — neyin eksik olduğunu biliyor musunuz?",
      goal: "Eksik belge öğrenilmiş, adımların sırası ve süresi netleşmiş ve ne zaman sonuç alınacağı söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-zustandspassiv",
    icon: "key",
    level: "B2",
    course: "de",
    title: "Die Tür ist geöffnet",
    titleTr: "Süreç mi, durum mu?",
    summary: "Süreç edilgeni ile durum edilgenini ayırt etmeyi öğretir.",
    minutes: 12,
    focusId: "Zustandspassiv",
    vocab: [
      { de: "der Vorgang", tr: "işlem" },
      { de: "betriebsbereit", tr: "çalışmaya hazır" },
      { de: "bezugsfertig", tr: "oturmaya hazır" },
      { de: "einwandfrei", tr: "kusursuz" },
      { de: "barrierefrei", tr: "engelsiz" },
      { de: "die Absperrung", tr: "bariyer" },
      { de: "stilllegen", tr: "kapatmak (tesisi)" },
      { de: "beseitigen", tr: "gidermek" },
    ],
    patterns: [
      { de: "wird geöffnet", tr: "süreç: açılıyor" },
      { de: "ist geöffnet", tr: "durum: açık" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü ders küçük bir kelimeye bakıyor ama anlamı tamamen değiştiriyor. Türkçede 'kapı açılıyor' ve 'kapı açık' apayrı şeyler; Almanca bunu iki ayrı edilgenle ayırır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural: werden ile kurulan edilgen SÜREÇTİR — bir şey oluyor. sein ile kurulan edilgen DURUMDUR — bir şey olmuş ve öyle duruyor. Önce kelimeler.")] },
      word("İlk", { de: "der Vorgang", tr: "işlem" }),
      word("İkinci", { de: "betriebsbereit", tr: "çalışmaya hazır" }, "Bir durum bildirir, süreç değil."),
      word("Üçüncü", { de: "bezugsfertig", tr: "oturmaya hazır" }),
      word("Dördüncü", { de: "einwandfrei", tr: "kusursuz" }),
      word("Beşinci", { de: "barrierefrei", tr: "engelsiz" }),
      word("Altıncı", { de: "die Absperrung", tr: "bariyer" }),
      word("Yedinci", { de: "stilllegen", tr: "kapatmak (tesisi)" }),
      word("Son", { de: "beseitigen", tr: "gidermek" }),
      { say: [tr("Kalıbımız iki cümle:"), de("Die Tür wird geöffnet."), tr("süreç;"), de("Die Tür ist geöffnet."), tr("durum.")] },
      { say: [tr("Tekrar edin:"), de("Die Tür wird geöffnet, und danach ist sie geöffnet")], expect: repeat("Die Tür wird geöffnet, und danach ist sie geöffnet") },
      { say: [tr("Sıra sende, süreci söyle: 'Mağaza saat altıda kapatılıyor.'")], expect: produce("Der Laden wird um sechs geschlossen", [tr("Bir şeyin olması werden ile:"), de("Der Laden wird um sechs geschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi durumu söyle: 'Mağaza pazar günleri kapalı.'")], expect: produce("Der Laden ist sonntags geschlossen", [tr("Var olan hâl sein ile:"), de("Der Laden ist sonntags geschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Tesis çalışmaya hazır.'")], expect: produce("Die Anlage ist betriebsbereit", [tr("Bu bir durum, süreç değil:"), de("Die Anlage ist betriebsbereit."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Anlage wird seit einer Stunde betriebsbereit."), tr("cümlesi doğru mu?")], expect: truefalse("Die Anlage wird seit einer Stunde betriebsbereit.", false, [tr("Bir saattir süren şey bir durumdur, süreç değil:"), de("Die Anlage ist seit einer Stunde betriebsbereit.")]) },
      { say: [tr("Son: 'Arka giriş dünden beri engelsiz.'")], expect: produce("Der hintere Zugang ist seit gestern barrierefrei", [tr("Var olan hâl sein ile; sıfat en sonda:"), de("Der hintere Zugang ist seit gestern barrierefrei."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir bina görevlisiyle konuşacaksın: ne zaman ne açılıyor, şu an ne açık.")] },
    ],
    roleplay: {
      scene: "Bir binanın görevlisiyle konuşuyorsun: hangi kapı ne zaman açılıyor, şu an neresi açık, hangi giriş kalıcı olarak kapalı. Süreç ile durumu ayırarak sor ve anlat.",
      partner: "kuralları ezbere bilen, kısa konuşan bir bina görevlisi",
      opening: "Sie stehen vor der falschen Tür — der Haupteingang ist heute geschlossen. Wohin wollen Sie denn?",
      openingTr: "Yanlış kapıdasınız — ana giriş bugün kapalı. Nereye gitmek istiyorsunuz?",
      goal: "Hangi girişin açık, hangisinin kapalı olduğu ve kapıların ne zaman açıldığı öğrenilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-passiversatz-lassen",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Das lässt sich machen",
    titleTr: "Edilgen yerine geçenler",
    summary: "lassen + sich, sein + zu ve -bar sıfatlarını ayırt etmeyi öğretir.",
    minutes: 12,
    focusId: "Passiversatz",
    vocab: [
      { de: "nachweisen", tr: "kanıtlamak" },
      { de: "bewältigen", tr: "üstesinden gelmek" },
      { de: "überschaubar", tr: "idare edilebilir" },
      { de: "wiederverwendbar", tr: "yeniden kullanılabilir" },
      { de: "belastbar", tr: "dayanıklı" },
      { de: "akzeptabel", tr: "kabul edilebilir" },
      { de: "justieren", tr: "ayarlamak" },
      { de: "nachrüsten", tr: "sonradan takmak" },
    ],
    patterns: [
      { de: "Das lässt sich …", tr: "imkân: yapılabilir" },
      { de: "Das ist zu …", tr: "zorunluluk: yapılmalı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün edilgenin üç kısayolunu bir araya getiriyoruz. Üçü de edilgen anlamı taşır ama üçü farklı şey söyler ve karıştırmak cümleyi bozar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Birincisi imkân söyler, ikincisi zorunluluk, üçüncüsü de sıfat gibi durup nitelik söyler. Aynı cümlede ikisini birden kullanmak sık yapılan bir hata. Önce kelimeler.")] },
      word("İlk", { de: "nachweisen", tr: "kanıtlamak" }),
      word("İkinci", { de: "bewältigen", tr: "üstesinden gelmek" }),
      word("Üçüncü", { de: "überschaubar", tr: "idare edilebilir" }, "Göz kararı ölçülebilecek kadar küçük."),
      word("Dördüncü", { de: "wiederverwendbar", tr: "yeniden kullanılabilir" }),
      word("Beşinci", { de: "belastbar", tr: "dayanıklı" }),
      word("Altıncı", { de: "akzeptabel", tr: "kabul edilebilir" }),
      word("Yedinci", { de: "justieren", tr: "ayarlamak" }),
      word("Son", { de: "nachrüsten", tr: "sonradan takmak" }),
      { say: [tr("Kalıbımız:"), de("Das lässt sich bewältigen."), tr("Yani 'bunun üstesinden gelinebilir'. lassen artı dönüşlü zamir artı mastar.")] },
      { say: [tr("Tekrar edin:"), de("Das lässt sich bewältigen")], expect: repeat("Das lässt sich bewältigen") },
      { say: [tr("Sıra sende: 'Zaman planı hâlâ ayarlanabilir.'")], expect: produce("Der Zeitplan lässt sich noch justieren", [tr("Özne, lassen artı sich, mastar en sonda:"), de("Der Zeitplan lässt sich noch justieren."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi zorunluluk biçimiyle: 'Bunun kanıtlanması gerekiyor.'")], expect: produce("Das ist nachzuweisen", [tr("sein artı zu artı mastar; ayrılabilen fiilde zu ortaya girer:"), de("Das ist nachzuweisen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, sıfat biçimiyle: 'Bu malzeme yeniden kullanılabilir.'")], expect: produce("Dieses Material ist wiederverwendbar", [tr("Fiilden türeyen sıfat, sein ile:"), de("Dieses Material ist wiederverwendbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Material lässt sich wiederverwendbar."), tr("cümlesi doğru mu?")], expect: truefalse("Das Material lässt sich wiederverwendbar.", false, [tr("İki yapı birbirine karışmış; ya biri ya öteki:"), de("Das Material lässt sich wiederverwenden."), tr("ya da"), de("Das Material ist wiederverwendbar.")]) },
      { say: [tr("Son bir soru: 'Yük hâlâ idare edilebilir mi?'")], expect: produce("Ist der Aufwand noch überschaubar", [tr("Fiil başta soru; sıfat sonda:"), de("Ist der Aufwand noch überschaubar?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir öneriyi değerlendireceksin: neyin mümkün, neyin zorunlu olduğunu ayır.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın yeni bir çalışma düzeni öneriyor. Önerinin neyinin uygulanabilir olduğunu, neyin zorunlu olarak çözülmesi gerektiğini ve neyin mümkün olmadığını söyleyip ortak bir sonuca varın.",
      partner: "önerisine bağlı ama itiraz dinleyen bir meslektaş",
      opening: "Ich hätte da eine Idee: Wir verlegen die Besprechung auf Montagmorgen. Lässt sich das machen?",
      openingTr: "Bir fikrim var: Toplantıyı pazartesi sabahına alalım. Bu yapılabilir mi?",
      goal: "Önerinin uygulanabilir ve uygulanamaz yanları ayrılmış, çözülmesi gereken nokta söylenmiş ve ortak bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-herstellung",
    icon: "food",
    level: "B2",
    course: "de",
    title: "Wie Schokolade entsteht",
    titleTr: "Üretim süreci",
    summary: "Bir üretim sürecini adım adım edilgenle anlatmayı öğretir.",
    minutes: 12,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "verarbeiten", tr: "işlemek" },
      { de: "der Rohstoff", tr: "hammadde" },
      { de: "die Fertigung", tr: "imalat" },
      { de: "das Fließband", tr: "montaj bandı" },
      { de: "die Montage", tr: "montaj" },
      { de: "die Lagerung", tr: "depolama" },
      { de: "abfüllen", tr: "şişelemek" },
      { de: "die Verpackung", tr: "ambalaj" },
    ],
    patterns: [
      { de: "wird/werden … + Partizip", tr: "süreç anlatımı" },
      { de: "zuerst … anschließend … zum Schluss", tr: "adım sıralaması" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir şeyin nasıl yapıldığını anlatacağız. Böyle anlatımlarda kimin yaptığı hiç söylenmez — önemli olan sıradır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yüzden üretim anlatımı baştan sona edilgendir ve sıra belirteçleriyle bağlanır: önce, ardından, en son. Önce kelimeler.")] },
      word("İlk", { de: "verarbeiten", tr: "işlemek" }),
      word("İkinci", { de: "der Rohstoff", tr: "hammadde" }),
      word("Üçüncü", { de: "die Fertigung", tr: "imalat" }),
      word("Dördüncü", { de: "das Fließband", tr: "montaj bandı" }),
      word("Beşinci", { de: "die Montage", tr: "montaj" }),
      word("Altıncı", { de: "die Lagerung", tr: "depolama" }),
      word("Yedinci", { de: "abfüllen", tr: "şişelemek" }, "Sıvıyı kaba doldurmak."),
      word("Son", { de: "die Verpackung", tr: "ambalaj" }),
      { say: [tr("Kalıbımız:"), de("wird / werden + Partizip"), tr("Şimdiki zaman edilgeni; çoğul öznede werden.")] },
      { say: [tr("Örnek:"), de("Die Bohnen werden zuerst geerntet."), tr("Tekrar edin:"), de("Die Bohnen werden zuerst geerntet")], expect: repeat("Die Bohnen werden zuerst geerntet") },
      { say: [tr("Sıra sende: 'Ardından çekirdekler kavruluyor.'")], expect: produce("Anschließend werden die Bohnen geröstet", [tr("Zarf başta olunca fiil ikinci sıraya geçer:"), de("Anschließend werden die Bohnen geröstet."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kakao birkaç adımda işleniyor.'")], expect: produce("Der Kakao wird in mehreren Schritten verarbeitet", [tr("Tekil özne wird alır, ortaç sonda:"), de("Der Kakao wird in mehreren Schritten verarbeitet."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Hammaddeler işlenmeden önce kontrol ediliyor.'")], expect: produce("Die Rohstoffe werden vor der Verarbeitung geprüft", [tr("Çoğul özne werden alır, ortaç sonda:"), de("Die Rohstoffe werden vor der Verarbeitung geprüft."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Anschließend werden die Bohnen geröstet."), tr("cümlesi doğru mu?")], expect: truefalse("Anschließend werden die Bohnen geröstet.", true, [tr("Doğru. Zarf başta, çekimli fiil ikinci sırada, ortaç en sonda.")]) },
      { say: [tr("Son bir soru: 'İmalat nasıl işliyor?'")], expect: produce("Wie läuft die Fertigung ab", [tr("Ayrılabilen fiilin öneki sonda:"), de("Wie läuft die Fertigung ab?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir fabrika turunda rehbere üretimin adımlarını soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir çikolata fabrikasının turundasın. Üretimin adımlarını sırayla sor, bir adımı kendi cümlenle özetle ve merak ettiğin bir ayrıntıyı sor.",
      partner: "işini seven, ayrıntı vermeyi seven bir fabrika rehberi",
      opening: "Willkommen! Wir stehen hier ganz am Anfang der Produktion. Wissen Sie schon, wie Kakao überhaupt zu uns kommt?",
      openingTr: "Hoş geldiniz! Şu an üretimin en başındayız. Kakaonun bize nasıl geldiğini biliyor musunuz?",
      goal: "Üretimin adımları sırayla öğrenilmiş, bir adım öğrenci tarafından özetlenmiş ve merak edilen bir ayrıntı cevaplanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-restaurierung",
    icon: "city",
    level: "B2",
    course: "de",
    title: "Die Altstadt wird saniert",
    titleTr: "Restorasyon",
    summary: "Yapılmış onarım işlerini edilgen geçmişle anlatmayı öğretir.",
    minutes: 12,
    focusId: "Passiv-Perfekt",
    vocab: [
      { de: "sanieren", tr: "restore etmek" },
      { de: "die Fassade", tr: "cephe" },
      { de: "die Renovierung", tr: "tadilat" },
      { de: "modernisieren", tr: "modernleştirmek" },
      { de: "errichten", tr: "inşa etmek" },
      { de: "das Wahrzeichen", tr: "simge yapı" },
      { de: "die Baugenehmigung", tr: "yapı ruhsatı" },
      { de: "baufällig", tr: "harap" },
    ],
    patterns: [
      { de: "ist … saniert worden", tr: "yapılmış onarım" },
      { de: "ist … errichtet worden", tr: "yapının inşa edildiği zaman" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün eski bir şehir merkezindeyiz. Bu konunun dili tamamen edilgen geçmiş: kimin onardığı değil, neyin onarılmış olduğu konuşulur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de ince bir ayrım var: zaman belirtilmişse süreç anlatılıyordur ve kısalmış biçim gerekir. Bunu dersin sonunda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "sanieren", tr: "restore etmek" }),
      word("İkinci", { de: "die Fassade", tr: "cephe" }),
      word("Üçüncü", { de: "die Renovierung", tr: "tadilat" }),
      word("Dördüncü", { de: "modernisieren", tr: "modernleştirmek" }),
      word("Beşinci", { de: "errichten", tr: "inşa etmek" }, "Resmî dilde 'bauen' yerine geçer."),
      word("Altıncı", { de: "das Wahrzeichen", tr: "simge yapı" }),
      word("Yedinci", { de: "die Baugenehmigung", tr: "yapı ruhsatı" }),
      word("Son", { de: "baufällig", tr: "harap" }),
      { say: [tr("Kalıbımız:"), de("ist … saniert worden"), tr("Tamamlanmış bir onarım süreci.")] },
      { say: [tr("Örnek:"), de("Die Altstadt ist in den letzten Jahren saniert worden."), tr("Tekrar edin:"), de("Die Altstadt ist in den letzten Jahren saniert worden")], expect: repeat("Die Altstadt ist in den letzten Jahren saniert worden") },
      { say: [tr("Sıra sende: 'Cephe üç yıl önce modernleştirildi.'")], expect: produce("Die Fassade ist vor drei Jahren modernisiert worden", [tr("Zarf ortaçtan önce, kısalmış biçim sonda:"), de("Die Fassade ist vor drei Jahren modernisiert worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Simge yapı o zaman taştan inşa edilmiş.'")], expect: produce("Das Wahrzeichen ist damals aus Stein errichtet worden", [tr("Edilgen geçmiş; kısalmış biçim en sonda:"), de("Das Wahrzeichen ist damals aus Stein errichtet worden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Eski pencereler korunabildi.'")], expect: produce("Die alten Fenster konnten erhalten werden", [tr("Kipli edilgenin geçmişi; sonda ortaç ve werden:"), de("Die alten Fenster konnten erhalten werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Fassade ist letztes Jahr modernisiert."), tr("cümlesi doğru mu?")], expect: truefalse("Die Fassade ist letztes Jahr modernisiert.", false, [tr("Zaman belirtildiğine göre anlatılan bir süreçtir, o yüzden kısalmış biçim gerekir:"), de("Die Fassade ist letztes Jahr modernisiert worden.")]) },
      { say: [tr("Son: 'Çalışmalar geçen yıl tamamlandı.'")], expect: produce("Die Arbeiten sind letztes Jahr abgeschlossen worden", [tr("Çoğul özne sind alır:"), de("Die Arbeiten sind letztes Jahr abgeschlossen worden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir şehir turunda rehbere yenilenen binaları soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir şehir turundasın ve rehbere eski merkezin nasıl yenilendiğini soruyorsun: ne onarıldı, ne korunabildi, hangi bina koruma altında, çalışmalar ne zaman bitti.",
      partner: "şehrin tarihini seven, ayrıntı veren bir şehir rehberi",
      opening: "Von hier aus sieht man es am besten: Diese Häuserzeile ist vor drei Jahren komplett saniert worden. Fällt Ihnen etwas auf?",
      openingTr: "Buradan en iyi görünüyor: Bu sıra evler üç yıl önce tamamen yenilendi. Dikkatinizi çeken bir şey var mı?",
      goal: "Neyin onarıldığı, neyin korunduğu ve çalışmaların ne zaman bittiği öğrenilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-unfallbericht",
    icon: "car",
    level: "B2",
    course: "de",
    title: "Der Unfallbericht",
    titleTr: "Kaza raporu",
    summary: "Olayı resmî rapor diliyle, edilgen geçmiş zamanda anlatmayı öğretir.",
    minutes: 12,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "die Unfallstelle", tr: "kaza yeri" },
      { de: "die Einsatzkraft", tr: "müdahale görevlisi" },
      { de: "der Ersthelfer", tr: "ilk yardımcı" },
      { de: "alarmieren", tr: "alarma geçirmek" },
      { de: "verunglücken", tr: "kaza geçirmek" },
      { de: "sperren", tr: "kapatmak (yolu)" },
      { de: "der Sicherheitsabstand", tr: "güvenlik mesafesi" },
      { de: "fahrlässig", tr: "ihmalkâr" },
    ],
    patterns: [
      { de: "wurde … + Partizip", tr: "raporun edilgen geçmişi" },
      { de: "Zeugen werden gesucht.", tr: "resmî çağrı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün resmî rapor dili öğreneceğiz. Polis ve basın raporlarında edilgenin geçmiş zaman hâli kullanılır — konuşurken duyduğun hâlden farklı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Konuşmada 'ist gerufen worden' dersin, raporda 'wurde gerufen' yazar. İkisi de doğru ama tür farklıdır ve rapor okuyabilmek B2'nin işlerinden. Önce kelimeler.")] },
      word("İlk", { de: "die Unfallstelle", tr: "kaza yeri" }),
      word("İkinci", { de: "die Einsatzkraft", tr: "müdahale görevlisi" }, "İtfaiye, ambulans ve polis için ortak resmî sözcük."),
      word("Üçüncü", { de: "der Ersthelfer", tr: "ilk yardımcı" }),
      word("Dördüncü", { de: "alarmieren", tr: "alarma geçirmek" }),
      word("Beşinci", { de: "verunglücken", tr: "kaza geçirmek" }),
      word("Altıncı", { de: "sperren", tr: "kapatmak (yolu)" }),
      word("Yedinci", { de: "der Sicherheitsabstand", tr: "güvenlik mesafesi" }),
      word("Son", { de: "fahrlässig", tr: "ihmalkâr" }, "Kasıtlı değil ama dikkatsiz."),
      { say: [tr("Kalıbımız:"), de("wurde + Partizip"), tr("Çoğulda wurden. Rapor cümleleri neredeyse hep böyle kurulur.")] },
      { say: [tr("Örnek:"), de("Die Einsatzkräfte wurden sofort alarmiert."), tr("Tekrar edin:"), de("Die Einsatzkräfte wurden sofort alarmiert")], expect: repeat("Die Einsatzkräfte wurden sofort alarmiert") },
      { say: [tr("Sıra sende: 'Sürücü hastaneye götürüldü.'")], expect: produce("Der Fahrer wurde ins Krankenhaus gebracht", [tr("Edilgen geçmiş; yön bildiren edat belirtme hâliyle:"), de("Der Fahrer wurde ins Krankenhaus gebracht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yol iki saat kapatıldı.'")], expect: produce("Die Fahrbahn wurde zwei Stunden gesperrt", [tr("Süre ortaçtan önce:"), de("Die Fahrbahn wurde zwei Stunden gesperrt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, şimdiki zamanda: 'Tanıklar aranıyor.'")], expect: produce("Zeugen werden gesucht", [tr("Belirteçsiz çoğul özne, şimdiki zaman edilgeni:"), de("Zeugen werden gesucht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Fahrer wurde ins Krankenhaus gebracht worden."), tr("cümlesi doğru mu?")], expect: truefalse("Der Fahrer wurde ins Krankenhaus gebracht worden.", false, [tr("İki edilgen zaman üst üste binmiş; biri seçilmeli:"), de("Der Fahrer wurde ins Krankenhaus gebracht.")]) },
      { say: [tr("Son: 'Kaza yeri saat yedide yeniden açıldı.'")], expect: produce("Die Unfallstelle wurde um sieben freigegeben", [tr("Saat ortaçtan önce:"), de("Die Unfallstelle wurde um sieben freigegeben."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir polis memuruna tanık olduğun kazayı anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir kazaya tanık oldun ve polis memuruna ifade veriyorsun: ne gördün, hangi sırayla oldu, kim haber verdi, sonra ne oldu. Olayları sırayla ve nesnel anlat.",
      partner: "not tutan, tarih ve saat soran bir polis memuru",
      opening: "Sie haben den Unfall gesehen? Dann fangen wir von vorne an: Was genau ist als Erstes passiert?",
      openingTr: "Kazayı gördünüz mü? O hâlde baştan başlayalım: İlk olarak tam olarak ne oldu?",
      goal: "Olaylar sırayla anlatılmış, kimin ne yaptığı söylenmiş ve ifadenin sonunda iletişim bilgisi verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-rezept-profi",
    icon: "food",
    level: "B2",
    course: "de",
    title: "In der Profiküche",
    titleTr: "Profesyonel mutfak",
    summary: "Mutfak talimatlarını kipli edilgenle vermeyi öğretir.",
    minutes: 12,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "die Zutat", tr: "malzeme" },
      { de: "würzen", tr: "baharatlamak" },
      { de: "abkühlen", tr: "soğumak" },
      { de: "servieren", tr: "servis etmek" },
      { de: "der Hauptgang", tr: "ana yemek" },
      { de: "der Nachtisch", tr: "tatlı" },
      { de: "die Spezialität", tr: "yöresel yemek" },
      { de: "herzhaft", tr: "tuzlu" },
    ],
    patterns: [
      { de: "muss … serviert werden", tr: "mutfak zorunluluğu" },
      { de: "darf nicht … werden", tr: "yasak talimat" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün profesyonel mutfaktayız. Tarif kitabı 'sen şunu yap' demez; 'şu şöyle pişirilmeli' der. Yani kipli edilgen. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu ders geçen derslerdeki yapının mutfaktaki hâli: aynı kural, yeni kelimeler ve çok daha hızlı bir tempo. Önce kelimeler.")] },
      word("İlk", { de: "die Zutat", tr: "malzeme" }),
      word("İkinci", { de: "würzen", tr: "baharatlamak" }),
      word("Üçüncü", { de: "abkühlen", tr: "soğumak" }),
      word("Dördüncü", { de: "servieren", tr: "servis etmek" }),
      word("Beşinci", { de: "der Hauptgang", tr: "ana yemek" }),
      word("Altıncı", { de: "der Nachtisch", tr: "tatlı" }),
      word("Yedinci", { de: "die Spezialität", tr: "yöresel yemek" }),
      word("Son", { de: "herzhaft", tr: "tuzlu" }, "Tatlının karşıtı: tuzlu ve baharatlı."),
      { say: [tr("Kalıbımız:"), de("darf nicht … werden"), tr("Mutfakta yasak talimatı böyle verilir.")] },
      { say: [tr("Örnek:"), de("Die herzhafte Soße darf nicht gekocht werden."), tr("Tekrar edin:"), de("Die herzhafte Soße darf nicht gekocht werden")], expect: repeat("Die herzhafte Soße darf nicht gekocht werden") },
      { say: [tr("Sıra sende: 'Ana yemek ancak en sonda servis edilmeli.'")], expect: produce("Der Hauptgang darf erst zum Schluss serviert werden", [tr("Zorunluluk kip fiiliyle; sonda ortaç ve werden:"), de("Der Hauptgang darf erst zum Schluss serviert werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sos en sonda baharatlanıyor.'")], expect: produce("Die Soße wird zum Schluss gewürzt", [tr("Şimdiki zaman edilgeni; ayrılabilen fiilin ortacı:"), de("Die Soße wird zum Schluss gewürzt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Malzemelerin önce soğuması gerekiyor.'")], expect: produce("Die Zutaten müssen zuerst abkühlen", [tr("Bu fiil edilgen almaz; mastar doğrudan gelir:"), de("Die Zutaten müssen zuerst abkühlen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Soße wird zum Schluss gewürzt werden."), tr("cümlesi doğru mu?")], expect: truefalse("Die Soße wird zum Schluss gewürzt werden.", false, [tr("Şimdiki zaman edilgeninde ikinci werden fazladır:"), de("Die Soße wird zum Schluss gewürzt.")]) },
      { say: [tr("Son bir soru: 'Yöresel yemek burada nasıl hazırlanıyor?'")], expect: produce("Wie wird die Spezialität hier zubereitet", [tr("Soru kelimesi başta, ortaç en sonda:"), de("Wie wird die Spezialität hier zubereitet?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir aşçıdan tarifin püf noktalarını öğreneceksin.")] },
    ],
    roleplay: {
      scene: "Bir aşçıdan zor bir tarifin püf noktalarını öğreniyorsun: neyin nasıl pişirilmesi gerektiğini, neyin yapılmaması gerektiğini ve kıvamın nasıl anlaşıldığını sor.",
      partner: "aceleci ama öğretmeyi seven bir aşçı",
      opening: "Sie wollen es also selbst probieren? Gut. Sagen Sie mir zuerst: Womit fangen Sie an?",
      openingTr: "Demek kendiniz denemek istiyorsunuz? Güzel. Önce şunu söyleyin: Neyle başlıyorsunuz?",
      goal: "Pişirme adımları, bir yasak ve kıvamın nasıl anlaşılacağı öğrenilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-wartung",
    icon: "repair",
    level: "B2",
    course: "de",
    title: "Die große Wartung",
    titleTr: "Bakım süreci",
    summary: "Yapılması gerekenleri sein + zu ile bildirmeyi öğretir.",
    minutes: 12,
    focusId: "Passiversatz",
    vocab: [
      { de: "die Wartung", tr: "bakım" },
      { de: "die Instandhaltung", tr: "bakım onarım" },
      { de: "der Verschleiß", tr: "aşınma" },
      { de: "sich abnutzen", tr: "aşınmak" },
      { de: "das Ersatzteil", tr: "yedek parça" },
      { de: "die Dichtung", tr: "conta" },
      { de: "die Korrosion", tr: "korozyon" },
      { de: "festziehen", tr: "sıkmak" },
    ],
    patterns: [
      { de: "… ist/sind auszutauschen", tr: "yapılması gereken" },
      { de: "… lässt sich noch fahren", tr: "hâlâ mümkün olan" },
    ],
    lecture: [
      { say: [tr("Merhaba! Servisteyiz. Usta sana 'bunu değiştirmelisin' demez; 'bu yenilenmeli' der. Fail yok, iş var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki yapıyı yan yana kullanacağız: zorunlu olan sein artı zu ile, hâlâ mümkün olan lassen artı sich ile. Önce kelimeler.")] },
      word("İlk", { de: "die Wartung", tr: "bakım" }),
      word("İkinci", { de: "die Instandhaltung", tr: "bakım onarım" }, "Bir tesisin ya da binanın düzenli bakımı."),
      word("Üçüncü", { de: "der Verschleiß", tr: "aşınma" }),
      word("Dördüncü", { de: "sich abnutzen", tr: "aşınmak" }),
      word("Beşinci", { de: "das Ersatzteil", tr: "yedek parça" }),
      word("Altıncı", { de: "die Dichtung", tr: "conta" }),
      word("Yedinci", { de: "die Korrosion", tr: "korozyon" }),
      word("Son", { de: "festziehen", tr: "sıkmak" }),
      { say: [tr("Kalıbımız:"), de("Die Dichtungen sind auszutauschen."), tr("Yani 'frenlerin yenilenmesi gerekiyor'. Çoğulda sind.")] },
      { say: [tr("Tekrar edin:"), de("Die Dichtungen sind auszutauschen")], expect: repeat("Die Dichtungen sind auszutauschen") },
      { say: [tr("Sıra sende: 'Araç hâlâ sürülebilir.'")], expect: produce("Das Fahrzeug lässt sich noch fahren", [tr("İmkân lassen artı sich ile; mastar sonda:"), de("Das Fahrzeug lässt sich noch fahren."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Aşınma açıkça görülüyor.'")], expect: produce("Der Verschleiß ist deutlich sichtbar", [tr("Sıfat biçimi; sein ile:"), de("Der Verschleiß ist deutlich sichtbar."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bakımın vadesi geldi.'")], expect: produce("Die Wartung ist fällig", [tr("Kısa hüküm cümlesi:"), de("Die Wartung ist fällig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Dichtungen sind auszutauschen."), tr("cümlesi doğru mu?")], expect: truefalse("Die Dichtungen sind auszutauschen.", true, [tr("Doğru. Çoğul özne sind alıyor ve sein artı zu yapısı zorunluluğu kişisiz söylüyor.")]) },
      { say: [tr("Son: 'Yedek parça yarın teslim edilecek.'")], expect: produce("Das Ersatzteil wird morgen geliefert", [tr("Şimdiki zaman edilgeni gelecek anlamı da taşır:"), de("Das Ersatzteil wird morgen geliefert."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada servisteki ustayla bakımı konuşacaksın: ne zorunlu, ne bekleyebilir, ne kadar tutar.")] },
    ],
    roleplay: {
      scene: "Servisteki ustayla aracın bakımını konuşuyorsun: neyin mutlaka yapılması gerektiğini, neyin bekleyebileceğini, ne kadar tutacağını ve ne zaman hazır olacağını öğren.",
      partner: "dürüst ama acele eden bir servis ustası",
      opening: "Ich war einmal drunter. Zwei Sachen sind fällig, eine davon dringend — wollen Sie beides machen lassen?",
      openingTr: "Bir baktım altına. İki şeyin vakti gelmiş, biri acil — ikisini de yaptırmak ister misiniz?",
      goal: "Zorunlu ve bekleyebilecek işler ayrılmış, fiyat öğrenilmiş ve teslim zamanı kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-organisation",
    icon: "party",
    level: "B2",
    course: "de",
    title: "Wer macht was beim Fest?",
    titleTr: "Organizasyon",
    summary: "Yapılacak işleri kişisiz edilgenle dağıtmayı öğretir.",
    minutes: 12,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "die Aufgabenverteilung", tr: "görev dağılımı" },
      { de: "die Priorisierung", tr: "önceliklendirme" },
      { de: "das Zeitfenster", tr: "zaman aralığı" },
      { de: "die Stellvertretung", tr: "vekâlet" },
      { de: "die Verpflegung", tr: "yeme içme" },
      { de: "ausstatten", tr: "donatmak" },
      { de: "reibungslos", tr: "sorunsuz" },
      { de: "vorrangig", tr: "öncelikli" },
    ],
    patterns: [
      { de: "Es muss noch … werden.", tr: "kişisiz zorunluluk" },
      { de: "… kann übernommen werden", tr: "üstlenilebilir olan" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve edilgenin en pratik hâli: iş bölümü. Kimsenin adını vermeden bütün işleri sayabilirsin. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sahte özne 'es' burada çok işine yarar: 'Es muss noch eingekauft werden' — alışveriş yapılması gerekiyor, kim yapacak henüz belli değil. Önce kelimeler.")] },
      word("İlk", { de: "die Aufgabenverteilung", tr: "görev dağılımı" }),
      word("İkinci", { de: "die Priorisierung", tr: "önceliklendirme" }),
      word("Üçüncü", { de: "das Zeitfenster", tr: "zaman aralığı" }),
      word("Dördüncü", { de: "die Stellvertretung", tr: "vekâlet" }, "Birinin yerine bakma görevi."),
      word("Beşinci", { de: "die Verpflegung", tr: "yeme içme" }),
      word("Altıncı", { de: "ausstatten", tr: "donatmak" }),
      word("Yedinci", { de: "reibungslos", tr: "sorunsuz" }),
      word("Son", { de: "vorrangig", tr: "öncelikli" }),
      { say: [tr("Kalıbımız:"), de("Es muss noch … werden."), tr("Sahte özne es cümleyi başlatır ve fail hiç anılmaz.")] },
      { say: [tr("Örnek:"), de("Es muss noch eingekauft werden."), tr("Tekrar edin:"), de("Es muss noch eingekauft werden")], expect: repeat("Es muss noch eingekauft werden") },
      { say: [tr("Sıra sende: 'Müzik üstlenilebilir.'")], expect: produce("Die Musik kann übernommen werden", [tr("İmkân können ile; sonda ortaç ve werden:"), de("Die Musik kann übernommen werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yeme içme cuma günü sipariş edilmeli.'")], expect: produce("Die Verpflegung muss am Freitag bestellt werden", [tr("Zaman ortaçtan önce:"), de("Die Verpflegung muss am Freitag bestellt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Görev dağılımı öncelikle netleşmeli.'")], expect: produce("Die Aufgabenverteilung muss vorrangig geklärt werden", [tr("Çoğul kip fiili; ayrılabilen fiilin ortacı:"), de("Die Aufgabenverteilung muss vorrangig geklärt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Aufgabenverteilung muss vorrangig klären werden."), tr("cümlesi doğru mu?")], expect: truefalse("Die Aufgabenverteilung muss vorrangig klären werden.", false, [tr("Edilgende mastar değil ortaç gelir:"), de("Die Aufgabenverteilung muss vorrangig geklärt werden.")]) },
      { say: [tr("Son bir soru: 'Vekâleti kim üstleniyor?'")], expect: produce("Wer übernimmt die Stellvertretung", [tr("Soru zamiri özne, fiil ikinci sırada:"), de("Wer übernimmt die Stellvertretung?"), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir etkinliğin hazırlığını paylaşacaksın: ne yapılmalı, kim ne üstleniyor.")] },
    ],
    roleplay: {
      scene: "Bir mahalle şenliğinin hazırlığını iki kişi paylaşıyorsunuz. Yapılması gerekenleri kişisiz edilgenle say, kimin neyi üstleneceğini konuş ve akış planını bir tarihe bağla.",
      partner: "hevesli ama dağınık, sürekli yeni fikir atan bir komşu",
      opening: "Also, ich habe schon mal eine Liste gemacht — die ist allerdings ziemlich lang geworden. Womit sollen wir anfangen?",
      openingTr: "Ben bir liste yaptım — ama epey uzadı. Neyle başlayalım?",
      goal: "Yapılacak işler sayılmış, kimin neyi üstlendiği paylaşılmış ve akış planı bir tarihe bağlanmış olur.",
      minTurns: 9,
    },
  },
];
