import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B1 · Modül 7 — Fikir ve tartışma (061–070).
 *
 * B1'in eşiği burası: A2'ye kadar öğrenci bilgi alışverişi yapıyordu (ne
 * zaman, nerede, kaça); B1'de GÖRÜŞ bildiriyor. Görüş bildirmek üç ayrı
 * beceri istiyor ve modül üçünü de ayrı ayrı çalıştırıyor — fikri söylemek
 * (dass yan cümlesi), iki tarafı tartmak (ikili bağlaçlar) ve karşı çıkarken
 * ilişkiyi bozmamak (dilek kipi).
 *
 * Sonuncusu Türkçe konuşan için en zoru değil ama en gerekenidir: Almancada
 * doğrudan "Nein, das stimmt nicht" demek çoğu ortamda kabadır; aynı itiraz
 * "Da wäre ich vorsichtig" ile söylenir ve kapı açık kalır.
 *
 * Kalan altı ders aynı üç yapıyı gerçek konularda dolaştırıyor: ekran süresi,
 * haber doğruluğu, dizi, kitap, müzik, sergi — çünkü görüş bildirmek bir
 * konu değil, her konuda lazım olan bir alışkanlık.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB1B07: Lesson[] = [
  {
    id: "de-b1-meinung",
    icon: "question",
    level: "B1",
    course: "de",
    title: "Meiner Meinung nach",
    titleTr: "Görüş bildirme",
    summary: "Kendi görüşünü söylemeyi ve başkasınınkine katılıp katılmadığını belirtmeyi öğretir.",
    minutes: 10,
    focusId: "Nebensatz-dass",
    vocab: [
      { de: "die Meinung", tr: "görüş" },
      { de: "die Ansicht", tr: "kanı" },
      { de: "widersprechen", tr: "karşı çıkmak" },
      { de: "zustimmen", tr: "katılmak" },
      { de: "offensichtlich", tr: "besbelli" },
    ],
    patterns: [
      { de: "Meiner Meinung nach …", tr: "görüş bildirir; ardından fiil gelir" },
      { de: "Ich bin überzeugt, dass …", tr: "yan cümlede fiil sona gider" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün yeni bir eşiği geçiyoruz. Şimdiye kadar bilgi verdik: ne zaman, nerede, kaça. Bugün görüş bildireceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki yol var. Birincisi cümlenin başına bir kalıp koymak; o zaman fiil hemen arkasından gelir. İkincisi yan cümle kurmak; o zaman fiil sona gider. Önce kelimeler.")] },
      word("İlk", { de: "die Meinung", tr: "görüş" }),
      word("İkinci", { de: "die Ansicht", tr: "kanı" }),
      word("Üçüncü", { de: "widersprechen", tr: "karşı çıkmak" }),
      word("Dördüncü", { de: "zustimmen", tr: "katılmak" }),
      word("Son", { de: "offensichtlich", tr: "besbelli" }),
      { say: [tr("Kalıbımız:"), de("Meiner Meinung nach …"), tr("Bu bir tümleç olduğu için cümlenin çekimli fiili hemen arkasına gelir. Özne üçüncü sıraya kayar.")] },
      { say: [tr("Örnek:"), de("Meiner Meinung nach ist das keine gute Lösung."), tr("Lütfen tekrar edin:"), de("Meiner Meinung nach ist das keine gute Lösung")], expect: repeat("Meiner Meinung nach ist das keine gute Lösung") },
      { say: [tr("Sıra sende: 'Bence bu karar çok erken geldi.'")], expect: produce("Meiner Meinung nach kam die Entscheidung zu früh", [tr("Tümleç başta, çekimli fiil hemen arkasında:"), de("Meiner Meinung nach kam die Entscheidung zu früh."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi yan cümleyle: 'Haklı olduğuna eminim.'")], expect: produce("Ich bin überzeugt, dass du recht hast", [tr("Yan cümlede çekimli fiil en sona gider:"), de("Ich bin überzeugt, dass du recht hast."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu konuda sana katılıyorum.'")], expect: produce("In diesem Punkt stimme ich dir zu", [tr("Katılmak fiili yönelme ister ve öneki sona gider:"), de("In diesem Punkt stimme ich dir zu."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich bin überzeugt, dass er hat recht."), tr("cümlesi doğru mu?")], expect: truefalse("Ich bin überzeugt, dass er hat recht.", false, [tr("Yan cümlede çekimli fiil en sona gider:"), de("Ich bin überzeugt, dass er recht hat.")]) },
      { say: [tr("Son: 'Bu noktada sana karşı çıkmak zorundayım.'")], expect: produce("In diesem Punkt muss ich dir widersprechen", [tr("Karşı çıkmak fiili de yönelme ister; mastar en sonda:"), de("In diesem Punkt muss ich dir widersprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir tanıdığınla güncel bir konuyu tartışacaksın: görüşünü söyle, gerekçelendir, ona katılıp katılmadığını belirt.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla şehirdeki yeni bir kararı tartışıyorsun: merkeze araba girişinin kısıtlanması. Görüşünü söyle, gerekçelendir, ona katıldığın ve katılmadığın noktaları ayır.",
      partner: "kendi görüşünü savunan, tartışmayı seven bir tanıdık",
      opening: "Hast du gehört? Autos sollen bald nicht mehr in die Innenstadt dürfen. Was hältst du davon?",
      openingTr: "Duydun mu? Yakında arabalar şehir merkezine giremeyecekmiş. Sen ne düşünüyorsun?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-pro-contra",
    icon: "law",
    level: "B1",
    course: "de",
    title: "Dafür oder dagegen?",
    titleTr: "Artı ve eksileri tartmak",
    summary: "Bir konunun iki tarafını ikili bağlaçlarla tartıp sonuca varmayı öğretir.",
    minutes: 10,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "der Vorteil", tr: "avantaj" },
      { de: "der Nachteil", tr: "dezavantaj" },
      { de: "abwägen", tr: "tartmak" },
      { de: "einerseits", tr: "bir yandan" },
      { de: "überwiegen", tr: "ağır basmak" },
    ],
    patterns: [
      { de: "Einerseits …, andererseits …", tr: "iki tarafı yan yana koyar" },
      { de: "Dafür spricht …, dagegen spricht …", tr: "artıyı ve eksiyi adlandırır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir konunun iki tarafını da söylemeyi öğreneceğiz. Bu, tartışmada en güçlü hamledir: karşı tarafın argümanını sen söylersin, sonra kendi sonucunu koyarsın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkili bağlaçlar iki parçadır ve ikisi birden kullanılır. Birini söyleyip ötekini unutmak cümleyi yarım bırakır. Önce kelimeler.")] },
      word("İlk", { de: "der Vorteil", tr: "avantaj" }),
      word("İkinci", { de: "der Nachteil", tr: "dezavantaj" }),
      word("Üçüncü", { de: "abwägen", tr: "tartmak" }),
      word("Dördüncü", { de: "einerseits", tr: "bir yandan" }),
      word("Son", { de: "überwiegen", tr: "ağır basmak" }),
      { say: [tr("Kalıbımız:"), de("Einerseits …, andererseits …"), tr("İki parça da birer tümleçtir, yani ikisinden sonra da fiil hemen gelir.")] },
      { say: [tr("Örnek:"), de("Einerseits ist es billiger, andererseits dauert es länger."), tr("Tekrar edin:"), de("Einerseits ist es billiger, andererseits dauert es länger")], expect: repeat("Einerseits ist es billiger, andererseits dauert es länger") },
      { say: [tr("Sıra sende: 'Bir yandan daha çok zaman kazanıyorum, öte yandan daha çok para ödüyorum.'")], expect: produce("Einerseits spare ich Zeit, andererseits zahle ich mehr", [tr("Her iki parçadan sonra da fiil hemen gelir:"), de("Einerseits spare ich Zeit, andererseits zahle ich mehr."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi artıyı adlandır: 'Bunun lehine olan şey fiyat.'")], expect: produce("Dafür spricht der Preis", [tr("Bu kalıpta tümleç başta, fiil ikinci sırada:"), de("Dafür spricht der Preis."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bence avantajlar ağır basıyor.'")], expect: produce("Meiner Meinung nach überwiegen die Vorteile", [tr("Tümleçten sonra fiil, sonra çoğul özne:"), de("Meiner Meinung nach überwiegen die Vorteile."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Einerseits ist es teuer, andererseits ist es schnell."), tr("cümlesi doğru mu?")], expect: truefalse("Einerseits ist es teuer, andererseits ist es schnell.", true, [tr("Doğru. İkili bağlacın iki parçası da var ve her ikisinden sonra fiil hemen geliyor.")]) },
      { say: [tr("Son: 'Karar vermeden önce iki tarafı da tartmak gerekiyor.'")], expect: produce("Vor der Entscheidung muss man beide Seiten abwägen", [tr("Tümleç başta, modal fiil ikinci, mastar sonda:"), de("Vor der Entscheidung muss man beide Seiten abwägen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla şehir dışına taşınmayı tartışacaksın: artılar, eksiler, senin sonucun.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın şehir dışına taşınmayı düşünüyor ve fikrini soruyor. Artıları ve eksileri ikili bağlaçlarla yan yana koy, sonunda hangisinin ağır bastığını söyle.",
      partner: "kararsız, iki tarafı da duymak isteyen bir arkadaş",
      opening: "Wir überlegen, aufs Land zu ziehen. Sag mal ehrlich: Was spricht dafür und was dagegen?",
      openingTr: "Köye taşınmayı düşünüyoruz. Açık söyle: Neyi lehine, neyi aleyhine görüyorsun?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-diskussion-hoeflich",
    icon: "handshake",
    level: "B1",
    course: "de",
    title: "Sanft widersprechen",
    titleTr: "Kibarca itiraz etmek",
    summary: "Karşı çıkarken ilişkiyi bozmayan yumuşak itiraz kalıplarını öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "vorsichtig", tr: "temkinli" },
      { de: "der Einwand", tr: "itiraz noktası" },
      { de: "nachvollziehen", tr: "anlayabilmek" },
      { de: "teilweise", tr: "kısmen" },
      { de: "der Kompromiss", tr: "uzlaşma" },
    ],
    patterns: [
      { de: "Da wäre ich vorsichtig.", tr: "yumuşak itiraz" },
      { de: "Könnte es nicht sein, dass …?", tr: "itirazı soruya çevirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün öğreneceğin şey dilbilgisinden çok bir davranış: karşı çıkarken kapıyı açık bırakmak. Almancada bunun hazır kalıpları var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Doğrudan 'hayır, bu yanlış' demek çoğu ortamda kabadır. Aynı itiraz dilek kipiyle söylenince tartışma sürer, ilişki bozulmaz. Önce kelimeler.")] },
      word("İlk", { de: "vorsichtig", tr: "temkinli" }),
      word("İkinci", { de: "der Einwand", tr: "itiraz noktası" }),
      word("Üçüncü", { de: "nachvollziehen", tr: "anlayabilmek" }),
      word("Dördüncü", { de: "teilweise", tr: "kısmen" }),
      word("Son", { de: "der Kompromiss", tr: "uzlaşma" }),
      { say: [tr("Kalıbımız:"), de("Da wäre ich vorsichtig."), tr("Düz kipte söylenseydi kesin bir hüküm olurdu; dilek kipi onu bir çekinceye çeviriyor.")] },
      { say: [tr("Örnek:"), de("Da wäre ich vorsichtig, das sehe ich etwas anders."), tr("Tekrar edin:"), de("Da wäre ich vorsichtig, das sehe ich etwas anders")], expect: repeat("Da wäre ich vorsichtig, das sehe ich etwas anders") },
      { say: [tr("Sıra sende: 'Söylediğini anlayabiliyorum ama sadece kısmen.'")], expect: produce("Ich kann das nachvollziehen, aber nur teilweise", [tr("Modal fiil çekimli, mastar en sonda:"), de("Ich kann das nachvollziehen, aber nur teilweise."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi itirazı soruya çevir: 'Tam tersi de olamaz mı?'")], expect: produce("Könnte es nicht sein, dass es umgekehrt ist", [tr("Dilek kipiyle soru, yan cümlede fiil sonda:"), de("Könnte es nicht sein, dass es umgekehrt ist?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Küçük bir itirazım var.'")], expect: produce("Ich hätte da einen kleinen Einwand", [tr("Sahip olma fiilinin dilek kipi; nesne belirtme hâlinde:"), de("Ich hätte da einen kleinen Einwand."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Da würde ich vorsichtig sein, sagt er."), tr("cümlesi doğru mu?")], expect: truefalse("Da würde ich vorsichtig sein, sagt er.", false, [tr("Aktarma cümlesinde araya giren bölümden sonra fiil ikinci sırada kalmaz; doğal biçim şudur:"), de("Er sagt, da würde er vorsichtig sein.")]) },
      { say: [tr("Son: 'Bir uzlaşma bulabilir miyiz?'")], expect: produce("Könnten wir einen Kompromiss finden", [tr("Kibar soruda dilek kipi, mastar sonda:"), de("Könnten wir einen Kompromiss finden?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir toplantıda meslektaşına itiraz edeceksin: önce anladığını göster, sonra çekinceni söyle, sonunda uzlaşma öner.")] },
    ],
    roleplay: {
      scene: "Bir toplantıda meslektaşının önerisine katılmıyorsun. Önce onu anladığını göster, sonra çekinceni yumuşak kalıplarla söyle, sonunda bir uzlaşma öner.",
      partner: "önerisine bağlı ama makul bir meslektaş",
      opening: "Ich schlage vor, wir verschieben das Projekt um drei Monate. Wie siehst du das?",
      openingTr: "Projeyi üç ay ertelemeyi öneriyorum. Sen nasıl görüyorsun?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-medienkonsum",
    icon: "tech",
    level: "B1",
    course: "de",
    title: "Wie viel Handy ist okay?",
    titleTr: "Ekran süresi tartışması",
    summary: "Edatı sabit fiillerle görüş bildirmeyi ve koşula bağlı cevap vermeyi öğretir.",
    minutes: 10,
    focusId: "Verben-mit-Präpositionen",
    vocab: [
      { de: "abhängen", tr: "bağlı olmak" },
      { de: "die Bildschirmzeit", tr: "ekran süresi" },
      { de: "bewusst", tr: "bilinçli" },
      { de: "die Nutzung", tr: "kullanım" },
      { de: "einschränken", tr: "sınırlamak" },
    ],
    patterns: [
      { de: "Es hängt davon ab, ob …", tr: "cevabı koşula bağlar" },
      { de: "Ich halte viel von …", tr: "bir şeye değer verir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün tartışmanın en dürüst cevabını öğreneceğiz: 'duruma göre değişir'. Almancada bunun kalıbı bir edatla kuruluyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bazı fiillerin edatı sabittir ve o edat anlamı taşır. Fiili ezberlerken edatını da ezberlemek gerekiyor. Önce kelimeler.")] },
      word("İlk", { de: "abhängen", tr: "bağlı olmak" }),
      word("İkinci", { de: "die Bildschirmzeit", tr: "ekran süresi" }),
      word("Üçüncü", { de: "bewusst", tr: "bilinçli" }),
      word("Dördüncü", { de: "die Nutzung", tr: "kullanım" }),
      word("Son", { de: "einschränken", tr: "sınırlamak" }),
      { say: [tr("Kalıbımız:"), de("Es hängt davon ab, ob …"), tr("Baştaki küçük kelime edatı taşıyor, asıl koşul virgülden sonra geliyor ve fiili sona gidiyor.")] },
      { say: [tr("Örnek:"), de("Es hängt davon ab, ob man bewusst damit umgeht."), tr("Tekrar edin:"), de("Es hängt davon ab, ob man bewusst damit umgeht")], expect: repeat("Es hängt davon ab, ob man bewusst damit umgeht") },
      { say: [tr("Sıra sende: 'Bu, ekran süresinin ne kadar olduğuna bağlı.'")], expect: produce("Das hängt davon ab, wie lang die Bildschirmzeit ist", [tr("Soru kelimeli koşul; fiil yan cümlenin sonunda:"), de("Das hängt davon ab, wie lang die Bildschirmzeit ist."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi görüş bildir: 'Kurallara pek değer vermiyorum.'")], expect: produce("Ich halte nicht viel von festen Regeln", [tr("Bu fiilin edatı sabittir ve yönelme ister:"), de("Ich halte nicht viel von festen Regeln."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Akşamları kullanımı sınırlıyorum.'")], expect: produce("Abends schränke ich die Nutzung ein", [tr("Zaman zarfı başta, ayrılabilen fiilin öneki sonda:"), de("Abends schränke ich die Nutzung ein."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es hängt ab davon, ob es sinnvoll ist."), tr("cümlesi doğru mu?")], expect: truefalse("Es hängt ab davon, ob es sinnvoll ist.", false, [tr("Önek ile edat yer değiştirmiş; doğru dizilim şudur:"), de("Es hängt davon ab, ob es sinnvoll ist.")]) },
      { say: [tr("Son: 'Çocuklar için bilinçli kullanım daha önemli.'")], expect: produce("Für Kinder ist die bewusste Nutzung wichtiger", [tr("Tümleç başta, fiil ikinci sırada, sıfat karşılaştırma biçiminde:"), de("Für Kinder ist die bewusste Nutzung wichtiger."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir veliyle çocukların ekran süresini tartışacaksın: senin ölçün ne, neye bağlı.")] },
    ],
    roleplay: {
      scene: "Bir veli toplantısında çocukların ekran süresini tartışıyorsun: sence ne kadarı uygun, bu neye bağlı, nasıl sınırlanmalı. Görüşünü edatı sabit fiillerle kur.",
      partner: "kesin kurallar isteyen, endişeli bir veli",
      opening: "Zwei Stunden am Tag — das ist doch viel zu viel für ein Kind. Sehen Sie das auch so?",
      openingTr: "Günde iki saat — bir çocuk için bu çok fazla. Siz de öyle görüyor musunuz?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-fake-news",
    icon: "media",
    level: "B1",
    course: "de",
    title: "Stimmt das wirklich?",
    titleTr: "Kaynak sorgulama",
    summary: "Bir iddiadan şüphe etmeyi ve kaynağını dolaylı soruyla araştırmayı öğretir.",
    minutes: 10,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "bezweifeln", tr: "şüphe duymak" },
      { de: "stammen", tr: "kaynaklanmak" },
      { de: "die Behauptung", tr: "iddia" },
      { de: "verbreiten", tr: "yaymak" },
      { de: "glaubwürdig", tr: "inandırıcı" },
    ],
    patterns: [
      { de: "Ich bezweifle, dass …", tr: "şüpheyi yan cümleyle söyler" },
      { de: "Man sollte prüfen, ob …", tr: "kontrol önerisi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir cümleyi duyduğunda soracağın soruları öğreneceğiz: bu nereden geliyor, kim söylüyor, gerçekten öyle mi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Şüpheyi doğrudan söylemek de mümkün ama daha etkilisi soruya çevirmek. İkisinde de yan cümle var ve fiil sona gidiyor. Önce kelimeler.")] },
      word("İlk", { de: "bezweifeln", tr: "şüphe duymak" }),
      word("İkinci", { de: "stammen", tr: "kaynaklanmak" }),
      word("Üçüncü", { de: "die Behauptung", tr: "iddia" }),
      word("Dördüncü", { de: "verbreiten", tr: "yaymak" }),
      word("Son", { de: "glaubwürdig", tr: "inandırıcı" }),
      { say: [tr("Kalıbımız:"), de("Ich bezweifle, dass …"), tr("Şüphe fiili ana cümlede, şüphe edilen şey yan cümlede.")] },
      { say: [tr("Örnek:"), de("Ich bezweifle, dass diese Zahl stimmt."), tr("Tekrar edin:"), de("Ich bezweifle, dass diese Zahl stimmt")], expect: repeat("Ich bezweifle, dass diese Zahl stimmt") },
      { say: [tr("Sıra sende: 'Bu iddianın nereden geldiğini bilmiyorum.'")], expect: produce("Ich weiß nicht, woher diese Behauptung stammt", [tr("Soru kelimesi başta, fiil sonda:"), de("Ich weiß nicht, woher diese Behauptung stammt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi öneri: 'Kaynağın inandırıcı olup olmadığı kontrol edilmeli.'")], expect: produce("Man sollte prüfen, ob die Quelle glaubwürdig ist", [tr("Evet-hayır sorusu dolaylı hâle gelince bağlaç alır:"), de("Man sollte prüfen, ob die Quelle glaubwürdig ist."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu haber çok hızlı yayıldı.'")], expect: produce("Diese Nachricht wurde sehr schnell verbreitet", [tr("Geçmiş edilgen: wurde artı ortaç:"), de("Diese Nachricht wurde sehr schnell verbreitet."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich frage mich, ob die Zahl wirklich stimmt."), tr("cümlesi doğru mu?")], expect: truefalse("Ich frage mich, ob die Zahl wirklich stimmt.", true, [tr("Doğru. Dolaylı evet-hayır sorusu bağlaçla kuruluyor ve fiil en sonda.")]) },
      { say: [tr("Son: 'Bunu nerede okuduğunu sorabilir miyim?'")], expect: produce("Darf ich fragen, wo du das gelesen hast", [tr("Kibar giriş, soru kelimesi, sonda yardımcı fiil:"), de("Darf ich fragen, wo du das gelesen hast?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sana şaşırtıcı bir haber anlatan birine sorular soracaksın: nereden duydun, kim söylüyor, kontrol ettin mi.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığın sana şaşırtıcı bir haber anlatıyor. İddiayı sorgula: nereden geldiğini, kimin söylediğini ve doğrulanıp doğrulanmadığını dolaylı sorularla öğren.",
      partner: "duyduğuna hemen inanan, heyecanlı bir tanıdık",
      opening: "Hast du das gelesen? Ab nächstem Jahr soll das komplett verboten werden. Wusstest du das?",
      openingTr: "Bunu okudun mu? Gelecek yıldan itibaren tamamen yasaklanacakmış. Biliyor muydun?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-serienabend",
    icon: "film",
    level: "B1",
    course: "de",
    title: "Das Serienfinale",
    titleTr: "Dizi yorumu",
    summary: "Bir yapımı zıtlık cümleleriyle değerlendirmeyi ve beklentiyi anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-obwohl",
    vocab: [
      { de: "die Folge", tr: "bölüm" },
      { de: "die Figur", tr: "karakter" },
      { de: "vorhersehbar", tr: "tahmin edilebilir" },
      { de: "die Wendung", tr: "olay dönüşü" },
      { de: "überzeugend", tr: "inandırıcı" },
    ],
    patterns: [
      { de: "Obwohl das Ende …, fand ich …", tr: "zıtlıkla değerlendirme" },
      { de: "Ich hätte mir … gewünscht.", tr: "gerçekleşmemiş beklenti" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir yapımı değerlendireceğiz. İyi bir yorum tek yönlü olmaz: beğendiğin ve beğenmediğin yan yana durur. Bunun bağlacı zıtlıktır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de beklenti kalıbı öğreneceğiz: olmasını istediğin ama olmayan şey. Dilek kipiyle kuruluyor. Önce kelimeler.")] },
      word("İlk", { de: "die Folge", tr: "bölüm" }),
      word("İkinci", { de: "die Figur", tr: "karakter" }),
      word("Üçüncü", { de: "vorhersehbar", tr: "tahmin edilebilir" }),
      word("Dördüncü", { de: "die Wendung", tr: "olay dönüşü" }),
      word("Son", { de: "überzeugend", tr: "inandırıcı" }),
      { say: [tr("Kalıbımız:"), de("Obwohl das Ende vorhersehbar war, fand ich die Serie gut."), tr("Yan cümle başta, o yüzden ana cümle fiille başlıyor.")] },
      { say: [tr("Tekrar edin:"), de("Obwohl das Ende vorhersehbar war, fand ich die Serie gut")], expect: repeat("Obwohl das Ende vorhersehbar war, fand ich die Serie gut") },
      { say: [tr("Sıra sende: 'Son bölüm uzun olmasına rağmen sıkılmadım.'")], expect: produce("Obwohl die letzte Folge lang war, war mir nicht langweilig", [tr("Yan cümle önde, ana cümle fiille başlar:"), de("Obwohl die letzte Folge lang war, war mir nicht langweilig."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi beklenti: 'Başka bir son isterdim.'")], expect: produce("Ich hätte mir ein anderes Ende gewünscht", [tr("Gerçekleşmemiş beklenti dilek kipiyle ve dönüşlü kurulur:"), de("Ich hätte mir ein anderes Ende gewünscht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'En sevdiğim karakter inandırıcı değildi.'")], expect: produce("Meine Lieblingsfigur war nicht überzeugend", [tr("Olumsuzluk sıfatın önünde:"), de("Meine Lieblingsfigur war nicht überzeugend."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Obwohl die Serie gut war, ich habe sie nicht zu Ende gesehen."), tr("cümlesi doğru mu?")], expect: truefalse("Obwohl die Serie gut war, ich habe sie nicht zu Ende gesehen.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar:"), de("Obwohl die Serie gut war, habe ich sie nicht zu Ende gesehen.")]) },
      { say: [tr("Son: 'Son bölümdeki dönüş beni şaşırttı.'")], expect: produce("Die Wendung in der letzten Folge hat mich überrascht", [tr("Uzun özne öbeği, sonra yardımcı fiil, sonda ortaç:"), de("Die Wendung in der letzten Folge hat mich überrascht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla dizinin finalini tartışacaksın: neyi beğendin, neye rağmen, ne beklerdin.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla izlediğiniz dizinin finalini tartışıyorsunuz: neyi beğendin, neye rağmen beğendin, nasıl bir son beklerdin. Zıtlık ve beklenti kalıpları kur.",
      partner: "finali çok beğenmiş, seni ikna etmeye çalışan bir arkadaş",
      opening: "Also ich fand das Finale großartig. Aber du hast so komisch geguckt — was hat dir nicht gefallen?",
      openingTr: "Bence final harikaydı. Ama sen tuhaf bakıyordun — neyi beğenmedin?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-buchclub",
    icon: "book",
    level: "B1",
    course: "de",
    title: "Im Buchclub",
    titleTr: "Kitap tartışması",
    summary: "Okuduğun bir kitabı ilgi cümleleriyle tanımlayıp önermeyi öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Akkusativ",
    vocab: [
      { de: "das Kapitel", tr: "bölüm (kitapta)" },
      { de: "der Autor", tr: "yazar" },
      { de: "zäh", tr: "ağır ilerleyen" },
      { de: "empfehlenswert", tr: "tavsiye edilir" },
      { de: "der Absatz", tr: "paragraf" },
    ],
    patterns: [
      { de: "Der Roman, den wir gelesen haben, …", tr: "okunan kitabı tanımlar" },
      { de: "Ich empfehle ihn, weil …", tr: "öneriyi gerekçelendirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir kitap kulübündeyiz. Kitap konuşmanın iki parçası var: kitabı tanımlamak ve gerekçe vermek. Tanımlama için ilgi cümlesine döneceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Hatırlatma: tanımlanan şey yan cümlenin nesnesiyse eril zamir değişir. Dişil, nötr ve çoğulda bir şey değişmez. Önce kelimeler.")] },
      word("İlk", { de: "das Kapitel", tr: "bölüm (kitapta)" }),
      word("İkinci", { de: "der Autor", tr: "yazar" }),
      word("Üçüncü", { de: "zäh", tr: "ağır ilerleyen" }),
      word("Dördüncü", { de: "empfehlenswert", tr: "tavsiye edilir" }),
      word("Son", { de: "der Absatz", tr: "paragraf" }),
      { say: [tr("Kalıbımız:"), de("Der Roman, den wir gelesen haben, …"), tr("Roman okunan şey, yani nesne; erilde nesne zamiri başka bir biçimdir.")] },
      { say: [tr("Örnek:"), de("Der Roman, den wir gelesen haben, war sehr ruhig."), tr("Tekrar edin:"), de("Der Roman, den wir gelesen haben, war sehr ruhig")], expect: repeat("Der Roman, den wir gelesen haben, war sehr ruhig") },
      { say: [tr("Sıra sende: 'Beni etkileyen bölüm ortadaydı.'")], expect: produce("Das Kapitel, das mich beeindruckt hat, war in der Mitte", [tr("Bölüm nötr ve burada özne; nötrde zamir değişmez:"), de("Das Kapitel, das mich beeindruckt hat, war in der Mitte."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İlk yüz sayfa ağır ilerliyordu.'")], expect: produce("Die ersten hundert Seiten waren ziemlich zäh", [tr("Çoğul özne, çoğul fiil:"), de("Die ersten hundert Seiten waren ziemlich zäh."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kitabı öneriyorum çünkü yazar çok dürüst.'")], expect: produce("Ich empfehle das Buch, weil der Autor sehr ehrlich ist", [tr("Gerekçe yan cümlesinde fiil sona gider:"), de("Ich empfehle das Buch, weil der Autor sehr ehrlich ist."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Absatz, den mir gefällt, steht auf Seite zehn."), tr("cümlesi doğru mu?")], expect: truefalse("Der Absatz, den mir gefällt, steht auf Seite zehn.", false, [tr("Paragraf beğenilen değil beğendiren taraftır, yani özne; erilde özne zamiri der olur:"), de("Der Absatz, der mir gefällt, steht auf Seite zehn.")]) },
      { say: [tr("Son: 'Bu kitap gerçekten tavsiye edilir.'")], expect: produce("Dieses Buch ist wirklich empfehlenswert", [tr("Basit değerlendirme cümlesi:"), de("Dieses Buch ist wirklich empfehlenswert."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada kitap kulübünde bir kitabı anlatacaksın: neyi sevdin, hangi bölüm zordu, kime önerirsin.")] },
    ],
    roleplay: {
      scene: "Kitap kulübünde okuduğunuz kitabı tartışıyorsunuz: hangi bölüm etkiledi, neresi ağırdı, kime önerirsin. Kitabı ilgi cümleleriyle tanımla.",
      partner: "kitabı yarıda bırakmış, ikna edilmek isteyen bir kulüp üyesi",
      opening: "Ich bin auf Seite achtzig hängen geblieben. Lohnt es sich wirklich, weiterzulesen?",
      openingTr: "Seksen sayfada takıldım. Devam etmeye gerçekten değer mi?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-musikgeschmack",
    icon: "music",
    level: "B1",
    course: "de",
    title: "Über Geschmack streiten",
    titleTr: "Müzik zevki",
    summary: "Zevkleri karşılaştırmayı ve tartışmayı kibarca bitirmeyi öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "die Vorliebe", tr: "tercih" },
      { de: "der Rhythmus", tr: "ritim" },
      { de: "der Liedtext", tr: "şarkı sözü" },
      { de: "die Geschmackssache", tr: "zevk meselesi" },
      { de: "mitsingen", tr: "eşlik ederek söylemek" },
    ],
    patterns: [
      { de: "Live ist besser als …", tr: "karşılaştırma" },
      { de: "Das ist Geschmackssache.", tr: "tartışmayı kibarca bitirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün zevk üzerine konuşacağız — ve zevk tartışmasının bir kuralı var: kimse kimseyi ikna edemez. O yüzden hem karşılaştırmayı hem de tartışmayı bitirmeyi öğreneceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karşılaştırmada iki düzensiz biçim var ve ikisi de çok sık: iyi ve çok. Bunları ezberlemek gerekiyor. Önce kelimeler.")] },
      word("İlk", { de: "die Vorliebe", tr: "tercih" }),
      word("İkinci", { de: "der Rhythmus", tr: "ritim" }),
      word("Üçüncü", { de: "der Liedtext", tr: "şarkı sözü" }),
      word("Dördüncü", { de: "die Geschmackssache", tr: "zevk meselesi" }),
      word("Son", { de: "mitsingen", tr: "eşlik ederek söylemek" }),
      { say: [tr("Kalıbımız:"), de("Live ist besser als im Radio."), tr("İyi anlamındaki sıfat karşılaştırmada tamamen değişiyor; ezberlenecek biçimlerden biri.")] },
      { say: [tr("Tekrar edin:"), de("Live ist besser als im Radio")], expect: repeat("Live ist besser als im Radio") },
      { say: [tr("Sıra sende: 'Eski şarkılar bana daha samimi geliyor.'")], expect: produce("Alte Lieder wirken auf mich ehrlicher", [tr("Karşılaştırma biçimi cümlenin sonunda:"), de("Alte Lieder wirken auf mich ehrlicher."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bende sözler ritimden daha önemli.'")], expect: produce("Bei mir ist der Liedtext wichtiger als der Rhythmus", [tr("Tümleç başta, karşılaştırma bağlacı iki öğeyi bağlar:"), de("Bei mir ist der Liedtext wichtiger als der Rhythmus."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'En sevdiğim şey birlikte söylemek.'")], expect: produce("Am liebsten singe ich mit", [tr("En üstünlük derecesi başta, ayrılabilen fiilin öneki sonda:"), de("Am liebsten singe ich mit."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dieses Album ist gutter als das letzte."), tr("cümlesi doğru mu?")], expect: truefalse("Dieses Album ist gutter als das letzte.", false, [tr("İyi anlamındaki sıfat düzensizdir, ek almaz, biçim değiştirir:"), de("Dieses Album ist besser als das letzte.")]) },
      { say: [tr("Son: 'Sonuçta bu bir zevk meselesi.'")], expect: produce("Am Ende ist das Geschmackssache", [tr("Tümleç başta, fiil ikinci sırada:"), de("Am Ende ist das Geschmackssache."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla müzik zevkinizi karşılaştıracaksınız ve kimse kimseyi ikna edemeyecek.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla müzik zevkinizi tartışıyorsunuz: hangisi daha iyi, neden, sende ne daha önemli. Karşılaştırma yap ve tartışmayı kibarca bitir.",
      partner: "kendi müziğini savunan, şakacı bir arkadaş",
      opening: "Wie kannst du das hören? Das ist doch immer derselbe Rhythmus. Was findest du daran gut?",
      openingTr: "Bunu nasıl dinliyorsun? Hep aynı ritim. Nesini beğeniyorsun?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-kunstausstellung",
    icon: "art",
    level: "B1",
    course: "de",
    title: "In der Ausstellung",
    titleTr: "Sanat yorumu",
    summary: "Bir eserin sende bıraktığı etkiyi edatı sabit fiillerle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Verben-mit-Präpositionen",
    vocab: [
      { de: "die Ausstellung", tr: "sergi" },
      { de: "das Kunstwerk", tr: "sanat eseri" },
      { de: "der Künstler", tr: "sanatçı" },
      { de: "abstrakt", tr: "soyut" },
      { de: "nachdenklich", tr: "düşündürücü" },
    ],
    patterns: [
      { de: "Das erinnert mich an …", tr: "çağrışımı anlatır" },
      { de: "Ich interessiere mich für …", tr: "ilgiyi anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir sergideyiz ve öğreneceğimiz şey şu: bir eser sana ne yaptı. Bunun için edatı sabit birkaç fiil lazım. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu fiillerde edat anlamın parçası; edat değişirse anlam da değişir. O yüzden fiili ve edatı bir arada öğreniyoruz. Önce kelimeler.")] },
      word("İlk", { de: "die Ausstellung", tr: "sergi" }),
      word("İkinci", { de: "das Kunstwerk", tr: "sanat eseri" }),
      word("Üçüncü", { de: "der Künstler", tr: "sanatçı" }),
      word("Dördüncü", { de: "abstrakt", tr: "soyut" }),
      word("Son", { de: "nachdenklich", tr: "düşündürücü" }),
      { say: [tr("Kalıbımız:"), de("Das erinnert mich an …"), tr("Bu fiilin edatı belirtme hâli ister. Türkçede 'bana … hatırlatıyor' diyoruz.")] },
      { say: [tr("Örnek:"), de("Das Bild erinnert mich an meine Kindheit."), tr("Tekrar edin:"), de("Das Bild erinnert mich an meine Kindheit")], expect: repeat("Das Bild erinnert mich an meine Kindheit") },
      { say: [tr("Sıra sende: 'Soyut sanatla ilgileniyorum.'")], expect: produce("Ich interessiere mich für abstrakte Kunst", [tr("Bu dönüşlü fiilin edatı belirtme hâli ister:"), de("Ich interessiere mich für abstrakte Kunst."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu eser beni düşündürdü.'")], expect: produce("Dieses Kunstwerk hat mich nachdenklich gemacht", [tr("Bir sıfatla kurulan kalıp; ortaç en sonda:"), de("Dieses Kunstwerk hat mich nachdenklich gemacht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, soru sor: 'Sanatçı bunun hakkında ne düşünüyor?'")], expect: produce("Was denkt der Künstler darüber", [tr("Edat, soru zamiriyle kaynaşıp tek kelime olur:"), de("Was denkt der Künstler darüber?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich interessiere mich für moderne Fotografie."), tr("cümlesi doğru mu?")], expect: truefalse("Ich interessiere mich für moderne Fotografie.", true, [tr("Doğru. Dönüşlü zamir yerinde, edat doğru ve nesne belirtme hâlinde.")]) },
      { say: [tr("Son: 'Sergi beni çok etkiledi.'")], expect: produce("Die Ausstellung hat mich sehr bewegt", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Die Ausstellung hat mich sehr bewegt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir sergide gördüklerini anlatacaksın: hangi eser, sana neyi hatırlattı, ne hissettirdi.")] },
    ],
    roleplay: {
      scene: "Bir sergiden çıktın ve arkadaşına anlatıyorsun: hangi eser aklında kaldı, sana neyi hatırlattı, ne hissettirdi. Edatı sabit fiillerle kur.",
      partner: "sanattan pek anlamayan ama meraklı bir arkadaş",
      opening: "Und, wie war die Ausstellung? Ich verstehe von Kunst wenig — was ist dir geblieben?",
      openingTr: "Ee, sergi nasıldı? Ben sanattan pek anlamam — aklında ne kaldı?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-debatte-kurz",
    icon: "star",
    level: "B1",
    course: "de",
    title: "Die Blitz-Debatte",
    titleTr: "Mini münazara",
    summary: "Argümanları sıralayıp konuşmayı bir sonuçla kapatmayı öğretir.",
    minutes: 10,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "die Debatte", tr: "münazara" },
      { de: "das Argument", tr: "argüman" },
      { de: "zusammenfassen", tr: "özetlemek" },
      { de: "erstens", tr: "birincisi" },
      { de: "sachlich", tr: "nesnel" },
    ],
    patterns: [
      { de: "Erstens …, zweitens …", tr: "argümanları sıralar" },
      { de: "Zusammenfassend …", tr: "konuşmayı kapatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve bir sınavın da provası: iki dakikada görüşünü savunmak. Bunun için sıralama ve kapanış lazım. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İyi bir savunma üç parçadır: görüş, sıralanmış gerekçeler, kapanış. Sıralama dinleyicinin takip etmesini sağlar. Önce kelimeler.")] },
      word("İlk", { de: "die Debatte", tr: "münazara" }),
      word("İkinci", { de: "das Argument", tr: "argüman" }),
      word("Üçüncü", { de: "zusammenfassen", tr: "özetlemek" }),
      word("Dördüncü", { de: "erstens", tr: "birincisi" }),
      word("Son", { de: "sachlich", tr: "nesnel" }),
      { say: [tr("Kalıbımız:"), de("Erstens …, zweitens …"), tr("Her iki kelime de tümleçtir, yani ikisinden sonra da çekimli fiil gelir.")] },
      { say: [tr("Örnek:"), de("Erstens ist es günstiger, zweitens spart es Zeit."), tr("Tekrar edin:"), de("Erstens ist es günstiger, zweitens spart es Zeit")], expect: repeat("Erstens ist es günstiger, zweitens spart es Zeit") },
      { say: [tr("Sıra sende: 'Birincisi daha sağlıklı, ikincisi daha ucuz.'")], expect: produce("Erstens ist es gesünder, zweitens ist es billiger", [tr("Her sıra kelimesinden sonra fiil hemen gelir:"), de("Erstens ist es gesünder, zweitens ist es billiger."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi bir argüman ekle: 'Yalnızca ucuz değil, aynı zamanda hızlı.'")], expect: produce("Es ist nicht nur billig, sondern auch schnell", [tr("İkili bağlacın ikinci parçası virgülden sonra:"), de("Es ist nicht nur billig, sondern auch schnell."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Nesnel kalmaya çalışıyorum.'")], expect: produce("Ich versuche, sachlich zu bleiben", [tr("Deneme kalıbı artı mastar öbeği:"), de("Ich versuche, sachlich zu bleiben."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Erstens es ist günstiger, zweitens spart es Zeit."), tr("cümlesi doğru mu?")], expect: truefalse("Erstens es ist günstiger, zweitens spart es Zeit.", false, [tr("Sıra kelimesi tümleç olduğu için çekimli fiil hemen arkasından gelir:"), de("Erstens ist es günstiger, zweitens spart es Zeit.")]) },
      { say: [tr("Son: 'Özetle: bence bu doğru bir karar.'")], expect: produce("Zusammenfassend halte ich das für richtig", [tr("Kapanış kelimesi başta, fiil ikinci sırada:"), de("Zusammenfassend halte ich das für richtig."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada iki dakikalık bir münazaraya gireceksin: görüşünü söyle, iki gerekçe sırala, bir cümleyle kapat.")] },
    ],
    roleplay: {
      scene: "Kısa bir münazaradasın: konu hafta sonu marketlerin açık olması. Görüşünü söyle, gerekçelerini sırala ve konuşmayı bir özetle kapat.",
      partner: "karşı tarafı savunan, süreyi tutan bir münazara rakibi",
      opening: "Zwei Minuten für jeden. Ich beginne: Sonntags sollten die Läden geschlossen bleiben. Was sagst du dazu?",
      openingTr: "Her birimize iki dakika. Ben başlıyorum: Pazar günleri dükkânlar kapalı kalmalı. Sen ne diyorsun?",
      minTurns: 5,
    },
  },
];
