import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B1 · Modül 5 — Bürokrasi (041–050).
 *
 * Resmî Almancanın kendine ait bir sesi var ve o ses EDİLGEN: "Hier wird
 * gebaut", "Der Antrag wird bearbeitet", "Es werden Unterlagen benötigt".
 * Sebebi kibarlık değil, kişiyi silmek — dairede işi yapan bir memur değil
 * bir süreçtir. Türkçede karşılığı "-ilir/-iliyor" ekidir ve öğrenci onu
 * zaten biliyor; öğrenmesi gereken şey ANLAM değil, iki parçalı yapı:
 * çekimli werden başta, Partizip II en sonda.
 *
 * Sıra önce kuralı kuruyor (041 şimdiki, 042 geçmiş), sonra altı gerçek
 * işleme sokuyor: oturum izni, itiraz dilekçesi, ehliyet, vergi, sigorta,
 * vekâlet. Araya iki ders başka bir resmî beceri koyuyor — randevu ertelemek
 * (Konjunktiv II ile kibarlık) ve dolaylı soru sormak — çünkü dairede yalnız
 * anlamak yetmiyor, sormak ve rica etmek de gerekiyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB1B05: Lesson[] = [
  {
    id: "de-b1-passiv",
    icon: "city",
    level: "B1",
    course: "de",
    title: "Hier wird gebaut",
    titleTr: "Edilgen çatı: şimdiki zaman",
    summary: "İşi kimin yaptığı önemli olmadığında werden ile edilgen cümle kurmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "bauen", tr: "inşa etmek" },
      { de: "die Baustelle", tr: "şantiye" },
      { de: "sperren", tr: "kapatmak (yolu)" },
      { de: "der Bereich", tr: "alan" },
      { de: "betreten", tr: "girmek (bir yere)" },
    ],
    patterns: [
      { de: "Hier wird gebaut.", tr: "edilgen: çekimli werden başta, Partizip II sonda" },
      { de: "Die Straße wird gesperrt.", tr: "eylemi kimin yaptığı söylenmez" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün resmî Almancanın sesini öğreneceğiz. Tabelalarda, dairelerde, mektuplarda hep aynı yapı var ve ona edilgen çatı diyoruz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Türkçede zaten var: 'yapılıyor', 'kapatılıyor'. Yapan kişi cümleden silinir. Almancada bunun için iki parça gerekir ve bugün ikisini de kuracağız. Önce kelimeler.")] },
      word("İlk", { de: "bauen", tr: "inşa etmek" }),
      word("İkinci", { de: "die Baustelle", tr: "şantiye" }),
      word("Üçüncü", { de: "sperren", tr: "kapatmak (yolu)" }),
      word("Dördüncü", { de: "der Bereich", tr: "alan" }),
      word("Son", { de: "betreten", tr: "girmek (bir yere)" }),
      { say: [tr("Kalıbımız:"), de("Hier wird gebaut."), tr("Çekimli yardımcı fiil ikinci sırada, üçüncü hâl ortacı en sonda. Yani cümle iki uçtan tutulur.")] },
      { say: [tr("Örnek:"), de("Hier wird eine Schule gebaut."), tr("Lütfen tekrar edin:"), de("Hier wird eine Schule gebaut")], expect: repeat("Hier wird eine Schule gebaut") },
      { say: [tr("Sıra sende: 'Yol iki hafta kapatılıyor.'")], expect: produce("Die Straße wird zwei Wochen gesperrt", [tr("Çekimli fiil ikinci sırada, ortaç en sonda:"), de("Die Straße wird zwei Wochen gesperrt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi çoğul bir özneyle: 'Formlar burada doldurulur.'")], expect: produce("Die Formulare werden hier ausgefüllt", [tr("Özne çoğul olduğu için yardımcı fiil de çoğul: werden:"), de("Die Formulare werden hier ausgefüllt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ev her hafta temizleniyor.'")], expect: produce("Die Wohnung wird jede Woche geputzt", [tr("Zaman ifadesi ortada, ortaç sonda:"), de("Die Wohnung wird jede Woche geputzt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Hier wird gebaut ein Haus."), tr("cümlesi doğru mu?")], expect: truefalse("Hier wird gebaut ein Haus.", false, [tr("Ortaç en sona gider, nesne onun önüne:"), de("Hier wird ein Haus gebaut.")]) },
      { say: [tr("Son: 'Bu alana girilemez.' Modal fiille edilgen deneyelim.")], expect: produce("Dieser Bereich darf nicht betreten werden", [tr("Modal fiil çekimli, mastar werden en sonda:"), de("Dieser Bereich darf nicht betreten werden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada mahallendeki şantiyeyi soracaksın: ne yapılıyor, ne zaman bitiyor, hangi yol kapalı.")] },
    ],
    roleplay: {
      scene: "Mahallendeki şantiyenin önünde bir görevliye soru soruyorsun: ne inşa ediliyor, ne zaman bitiyor, hangi yollar kapalı. Sorularını ve anladıklarını edilgen cümlelerle kur.",
      partner: "aceleci ama bilgili bir şantiye görevlisi",
      opening: "Sie wollen sicher wissen, was hier passiert. Was möchten Sie denn genau erfahren?",
      openingTr: "Burada ne olduğunu merak ediyorsunuzdur. Tam olarak neyi öğrenmek istiyorsunuz?",
      goal: "Ne inşa edildiği, ne zaman biteceği ve hangi yolun kapalı olduğu öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-passiv-vergangen",
    icon: "office",
    level: "B1",
    course: "de",
    title: "Der Antrag wurde abgelehnt",
    titleTr: "Edilgen çatı: geçmiş zaman",
    summary: "Geçmişte edilgen cümleyi wurde ile kurmayı ve worden biçimini ayırt etmeyi öğretir.",
    minutes: 10,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "der Bescheid", tr: "karar yazısı" },
      { de: "bearbeiten", tr: "işleme almak" },
      { de: "der Nachweis", tr: "belge" },
      { de: "einreichen", tr: "sunmak" },
      { de: "die Behörde", tr: "resmî daire" },
    ],
    patterns: [
      { de: "Der Antrag wurde abgelehnt.", tr: "geçmişte edilgen: wurde artı Partizip II" },
      { de: "Die Unterlagen wurden geprüft.", tr: "çoğulda wurden" },
    ],
    lecture: [
      { say: [tr("Merhaba! Dün edilgen cümleyi şimdiki zamanda kurduk. Bugün geçmişe taşıyacağız — çünkü resmî mektuplar hep olmuş bitmiş şeyleri anlatır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tek bir şey değişiyor: yardımcı fiil geçmişe çekiliyor. Ortaç yerinde kalıyor. Bir de küçük bir tuzak var, sonunda göstereceğim. Önce kelimeler.")] },
      word("İlk", { de: "der Bescheid", tr: "karar yazısı" }),
      word("İkinci", { de: "bearbeiten", tr: "işleme almak" }),
      word("Üçüncü", { de: "der Nachweis", tr: "belge" }),
      word("Dördüncü", { de: "einreichen", tr: "sunmak" }),
      word("Son", { de: "die Behörde", tr: "resmî daire" }),
      { say: [tr("Kalıbımız:"), de("Der Antrag wurde abgelehnt."), tr("Tekil öznede wurde, çoğulda wurden. Gerisi aynı.")] },
      { say: [tr("Örnek:"), de("Mein Antrag wurde leider abgelehnt."), tr("Tekrar edin:"), de("Mein Antrag wurde leider abgelehnt")], expect: repeat("Mein Antrag wurde leider abgelehnt") },
      { say: [tr("Sıra sende: 'Belgeler kontrol edildi.'")], expect: produce("Die Unterlagen wurden geprüft", [tr("Çoğul özne, çoğul yardımcı fiil:"), de("Die Unterlagen wurden geprüft."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Başvurum iki hafta önce işleme alındı.'")], expect: produce("Mein Antrag wurde vor zwei Wochen bearbeitet", [tr("Zaman ifadesi ortada, ortaç sonda:"), de("Mein Antrag wurde vor zwei Wochen bearbeitet."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Belge zamanında sunuldu.'")], expect: produce("Der Nachweis wurde rechtzeitig eingereicht", [tr("Ayrılabilen fiilin ortacı tek parça: eingereicht:"), de("Der Nachweis wurde rechtzeitig eingereicht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi tuzak. Doğru mu yanlış mı:"), de("Der Antrag ist gestern abgelehnt geworden."), tr("cümlesi doğru mu?")], expect: truefalse("Der Antrag ist gestern abgelehnt geworden.", false, [tr("Edilgen cümlede o kelime kısalır:"), de("worden"), tr("denir:"), de("Der Antrag ist gestern abgelehnt worden.")]) },
      { say: [tr("Son: 'Karar yazısı dün gönderildi.'")], expect: produce("Der Bescheid wurde gestern geschickt", [tr("Tekil özne → wurde; ortaç sonda:"), de("Der Bescheid wurde gestern geschickt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşına başvurunun nasıl sonuçlandığını anlatacaksın: ne zaman verildi, ne kontrol edildi, ne cevap geldi.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın başvurunun ne olduğunu soruyor. Sürecin her adımını geçmiş edilgenle anlat: ne zaman sunuldu, ne kontrol edildi, ne karar verildi.",
      partner: "meraklı ve destekleyici bir arkadaş",
      opening: "Und? Hast du endlich Antwort bekommen? Was ist mit deinem Antrag passiert?",
      openingTr: "Ee? Sonunda cevap geldi mi? Başvurunla ne oldu?",
      goal: "Başvuru süreci adım adım anlatılmış ve sonucun ne olduğu söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-auslaenderbehoerde",
    icon: "office",
    level: "B1",
    course: "de",
    title: "Bei der Ausländerbehörde",
    titleTr: "Oturum işlemleri",
    summary: "Oturma izni işlemlerinde resmî edilgen dili anlamayı ve soru sormayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Aufenthaltserlaubnis", tr: "oturma izni" },
      { de: "benötigen", tr: "gerekmek" },
      { de: "ablaufen", tr: "süresi dolmak" },
      { de: "der Sachbearbeiter", tr: "dosya sorumlusu" },
      { de: "vorlegen", tr: "ibraz etmek" },
    ],
    patterns: [
      { de: "Der Antrag wird bearbeitet.", tr: "işi kimin yaptığı söylenmez" },
      { de: "Es werden … benötigt.", tr: "resmî dilde 'gerekiyor'" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün en çok işine yarayacak yerdeyiz: yabancılar dairesi. Orada duyacağın hemen her cümle edilgen ve aynı üç kalıptan çıkıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amacımız iki yönlü: memurun söylediğini anlamak ve kendi sorunu doğru sormak. İkincisi çoğu zaman daha önemli. Önce kelimeler.")] },
      word("İlk", { de: "die Aufenthaltserlaubnis", tr: "oturma izni" }),
      word("İkinci", { de: "benötigen", tr: "gerekmek" }),
      word("Üçüncü", { de: "ablaufen", tr: "süresi dolmak" }),
      word("Dördüncü", { de: "der Sachbearbeiter", tr: "dosya sorumlusu" }),
      word("Son", { de: "vorlegen", tr: "ibraz etmek" }),
      { say: [tr("Kalıbımız:"), de("Es werden Unterlagen benötigt."), tr("Bu cümlenin başındaki kelime sahte bir öznedir; asıl özne belgelerdir ve fiil ona göre çoğul çekilir.")] },
      { say: [tr("Örnek:"), de("Ihr Antrag wird noch bearbeitet."), tr("Tekrar edin:"), de("Ihr Antrag wird noch bearbeitet")], expect: repeat("Ihr Antrag wird noch bearbeitet") },
      { say: [tr("Sıra sende, soruyu sor: 'Hangi belgeler gerekiyor?'")], expect: produce("Welche Unterlagen werden benötigt", [tr("Soru kelimesi başta, çoğul özne, ortaç sonda:"), de("Welche Unterlagen werden benötigt?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi kendi durumunu söyle: 'Oturma iznim mayısta doluyor.'")], expect: produce("Meine Aufenthaltserlaubnis läuft im Mai ab", [tr("Ayrılabilen fiilin öneki en sona:"), de("Meine Aufenthaltserlaubnis läuft im Mai ab."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, bu kez modal fiille: 'Pasaport ibraz edilmeli.'")], expect: produce("Der Pass muss vorgelegt werden", [tr("Modal çekimli, ortaç ve werden en sonda:"), de("Der Pass muss vorgelegt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Unterlagen wird geprüft."), tr("cümlesi doğru mu?")], expect: truefalse("Die Unterlagen wird geprüft.", false, [tr("Özne çoğul, yardımcı fiil de çoğul olmalı:"), de("Die Unterlagen werden geprüft.")]) },
      { say: [tr("Son: 'Başvuru dört hafta içinde işleme alınır.'")], expect: produce("Der Antrag wird in vier Wochen bearbeitet", [tr("Süre ortada, ortaç sonda:"), de("Der Antrag wird in vier Wochen bearbeitet."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir memurla oturma izni uzatmayı konuşacaksın: neyin gerektiğini sor, kendi durumunu anlat.")] },
    ],
    roleplay: {
      scene: "Yabancılar dairesinde bir memurla oturma izni uzatmayı konuşuyorsun. Hangi belgelerin gerektiğini sor, izninin ne zaman dolduğunu söyle, süreyi öğren.",
      partner: "resmî konuşan, net ama yardımcı bir memur",
      opening: "Guten Tag. Sie haben einen Termin zur Verlängerung — worum geht es genau?",
      openingTr: "İyi günler. Uzatma için randevunuz var — tam olarak konu nedir?",
      goal: "Gereken belgeler öğrenilmiş, iznin bitiş tarihi bildirilmiş ve işlem süresi söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-widerspruch",
    icon: "law",
    level: "B1",
    course: "de",
    title: "Ich lege Widerspruch ein",
    titleTr: "İtiraz dilekçesi",
    summary: "Resmî bir karara yazılı itiraz etmeyi ve ricayı dass yan cümlesiyle kurmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-dass",
    vocab: [
      { de: "begründen", tr: "gerekçelendirmek" },
      { de: "fristgerecht", tr: "süresi içinde" },
      { de: "beifügen", tr: "eklemek" },
      { de: "die Anlage", tr: "ek" },
      { de: "hiermit", tr: "işbu yazıyla" },
    ],
    patterns: [
      { de: "Ich bitte darum, dass …", tr: "resmî rica; yan cümlede fiil sona gider" },
      { de: "Hiermit widerspreche ich …", tr: "dilekçenin açılış cümlesi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bir karar sana haksız geldiyse Almanya'da yapılacak şey bellidir: yazılı itiraz. Bugün o mektubun üç cümlesini kuracağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İtiraz mektubu üç parçadır: neye itiraz ettiğin, neden itiraz ettiğin, ne rica ettiğin. Üçüncüsü için yan cümle gerekiyor. Önce kelimeler.")] },
      word("İlk", { de: "begründen", tr: "gerekçelendirmek" }),
      word("İkinci", { de: "fristgerecht", tr: "süresi içinde" }),
      word("Üçüncü", { de: "beifügen", tr: "eklemek" }),
      word("Dördüncü", { de: "die Anlage", tr: "ek" }),
      word("Son", { de: "hiermit", tr: "işbu yazıyla" }),
      { say: [tr("Kalıbımız:"), de("Ich bitte darum, dass …"), tr("Bu, resmî dilde en kibar rica biçimi. Yan cümle olduğu için çekimli fiil en sona gider.")] },
      { say: [tr("Örnek:"), de("Hiermit widerspreche ich Ihrem Bescheid."), tr("Tekrar edin:"), de("Hiermit widerspreche ich Ihrem Bescheid")], expect: repeat("Hiermit widerspreche ich Ihrem Bescheid") },
      { say: [tr("Sıra sende: 'Kararın yeniden incelenmesini rica ediyorum.'")], expect: produce("Ich bitte darum, dass der Bescheid neu geprüft wird", [tr("Yan cümlede edilgen kurulur ve yardımcı fiil en sona gider:"), de("Ich bitte darum, dass der Bescheid neu geprüft wird."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İtirazımı ekte gerekçelendiriyorum.'")], expect: produce("Ich begründe meinen Widerspruch in der Anlage", [tr("Basit bir etken cümle; ek için 'in der Anlage':"), de("Ich begründe meinen Widerspruch in der Anlage."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Belgeleri ekliyorum.'")], expect: produce("Ich füge die Unterlagen bei", [tr("Ayrılabilen fiilin öneki en sona:"), de("Ich füge die Unterlagen bei."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich bitte darum, dass Sie den Antrag prüfen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich bitte darum, dass Sie den Antrag prüfen.", true, [tr("Doğru. Yan cümlenin çekimli fiili en sonda ve rica kalıbı resmî yazıya uygun.")]) },
      { say: [tr("Son: 'Süresi içinde itiraz ettiğimi düşünüyorum.'")], expect: produce("Ich denke, dass ich fristgerecht widersprochen habe", [tr("Yan cümlede yardımcı fiil en sonda:"), de("Ich denke, dass ich fristgerecht widersprochen habe."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir danışmana itirazını anlatacaksın: neye itiraz ediyorsun, gerekçen ne, ne rica ediyorsun.")] },
    ],
    roleplay: {
      scene: "Bir danışma merkezinde görevliye itiraz etmek istediğin kararı anlatıyorsun: hangi karar, neden haksız buluyorsun, ne rica edeceksin. Ricalarını dass yan cümlesiyle kur.",
      partner: "sakin, adım adım ilerleyen bir danışman",
      opening: "Setzen Sie sich. Sie möchten also Widerspruch einlegen — gegen welchen Bescheid genau?",
      openingTr: "Buyurun oturun. Demek itiraz etmek istiyorsunuz — tam olarak hangi karara karşı?",
      goal: "İtiraz edilecek karar, gerekçen ve ricanın ne olacağı netleşmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-fuehrerschein",
    icon: "car",
    level: "B1",
    course: "de",
    title: "Der Führerschein",
    titleTr: "Ehliyet süreci",
    summary: "Bir resmî süreci sırayla, edilgen ve koşul cümleleriyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "der Führerschein", tr: "ehliyet" },
      { de: "die Fahrstunde", tr: "direksiyon dersi" },
      { de: "der Fahrlehrer", tr: "sürücü eğitmeni" },
      { de: "umschreiben", tr: "tescil ettirmek" },
      { de: "der Sehtest", tr: "göz testi" },
    ],
    patterns: [
      { de: "Die Prüfung wird abgelegt.", tr: "resmî süreç dilinde edilgen" },
      { de: "Erst wenn …, darf man …", tr: "ancak … olunca izin verilir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir süreci baştan sona anlatmayı öğreneceğiz: ehliyet. Süreç anlatımının dili edilgendir, çünkü kimin yaptığı değil sıra önemlidir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de sıraya bağlı izin kalıbı öğreneceğiz: ancak şu olursa şunu yapabilirsin. Türkçede 'ancak … -ince' diyoruz. Önce kelimeler.")] },
      word("İlk", { de: "der Führerschein", tr: "ehliyet" }),
      word("İkinci", { de: "die Fahrstunde", tr: "direksiyon dersi" }),
      word("Üçüncü", { de: "der Fahrlehrer", tr: "sürücü eğitmeni" }),
      word("Dördüncü", { de: "umschreiben", tr: "tescil ettirmek" }),
      word("Son", { de: "der Sehtest", tr: "göz testi" }),
      { say: [tr("Kalıbımız:"), de("Erst wenn …, darf man …"), tr("Başta bir koşul yan cümlesi var, o yüzden ana cümle fiille başlar. Sıralama böyle kurulur.")] },
      { say: [tr("Örnek:"), de("Zuerst wird die theoretische Prüfung abgelegt."), tr("Tekrar edin:"), de("Zuerst wird die theoretische Prüfung abgelegt")], expect: repeat("Zuerst wird die theoretische Prüfung abgelegt") },
      { say: [tr("Sıra sende: 'Önce göz testi yapılır.'")], expect: produce("Zuerst wird der Sehtest gemacht", [tr("Zaman zarfı başta, ortaç sonda:"), de("Zuerst wird der Sehtest gemacht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'On iki direksiyon dersi alınır.'")], expect: produce("Es werden zwölf Fahrstunden genommen", [tr("Sahte özne ile başlayan edilgen; asıl özne çoğul:"), de("Es werden zwölf Fahrstunden genommen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ancak sınavı geçince araba kullanabilirsin.'")], expect: produce("Erst wenn du die Prüfung bestehst, darfst du fahren", [tr("Koşul başta olduğu için ana cümle fiille başlar:"), de("Erst wenn du die Prüfung bestehst, darfst du fahren."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Erst wenn man bestanden hat, darf man allein fahren."), tr("cümlesi doğru mu?")], expect: truefalse("Erst wenn man bestanden hat, darf man allein fahren.", true, [tr("Doğru. Koşul yan cümlesi başta, ana cümle modal fiille başlıyor.")]) },
      { say: [tr("Son: 'Ehliyetim burada tescil edildi.'")], expect: produce("Mein Führerschein wurde hier umgeschrieben", [tr("Geçmiş edilgen: wurde artı ortaç:"), de("Mein Führerschein wurde hier umgeschrieben."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir sürücü kursunda danışacaksın: süreç nasıl işliyor, ne kadar sürüyor, ne gerekiyor.")] },
    ],
    roleplay: {
      scene: "Bir sürücü kursunda danışıyorsun: süreç hangi adımlardan geçiyor, kaç ders gerekiyor, ne kadar sürüyor. Anladıklarını edilgen cümlelerle özetle.",
      partner: "hızlı konuşan, deneyimli bir kurs görevlisi",
      opening: "Willkommen! Sie möchten den Führerschein machen — waren Sie schon einmal bei einer Fahrschule?",
      openingTr: "Hoş geldiniz! Ehliyet almak istiyorsunuz — daha önce hiç sürücü kursuna gittiniz mi?",
      goal: "Sürecin adımları, gereken ders sayısı ve ne kadar süreceği öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-steuer",
    icon: "money",
    level: "B1",
    course: "de",
    title: "Die Steuererklärung",
    titleTr: "Vergi beyanı",
    summary: "Vergi beyanını anlatırken edilgen ve etken cümleyi yerinde kullanmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "die Steuererklärung", tr: "vergi beyannamesi" },
      { de: "absetzen", tr: "gider göstermek" },
      { de: "erstatten", tr: "iade etmek" },
      { de: "der Steuerberater", tr: "mali müşavir" },
      { de: "die Quittung", tr: "makbuz" },
    ],
    patterns: [
      { de: "Es wurde … erstattet.", tr: "sonucu edilgenle söylemek" },
      { de: "Ich habe … eingereicht.", tr: "kendi yaptığını etken söylemek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün yılda bir kez herkesin başına gelen şey: vergi beyanı. İşin dili iki katmanlı — sen ne yaptın, sana ne yapıldı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural basit: kendi yaptığın şeyi etken söylersin, dairenin yaptığı şeyi edilgen. İkisini karıştırmamak resmî dilde çok işe yarar. Önce kelimeler.")] },
      word("İlk", { de: "die Steuererklärung", tr: "vergi beyannamesi" }),
      word("İkinci", { de: "absetzen", tr: "gider göstermek" }),
      word("Üçüncü", { de: "erstatten", tr: "iade etmek" }),
      word("Dördüncü", { de: "der Steuerberater", tr: "mali müşavir" }),
      word("Son", { de: "die Quittung", tr: "makbuz" }),
      { say: [tr("Kalıbımız:"), de("Mir wurden dreihundert Euro erstattet."), tr("İade edilen para çoğul olduğu için yardımcı fiil çoğul, sana ise yönelme hâliyle işaret edilir.")] },
      { say: [tr("Tekrar edin:"), de("Mir wurden dreihundert Euro erstattet")], expect: repeat("Mir wurden dreihundert Euro erstattet") },
      { say: [tr("Sıra sende: 'Vergi beyannamesi geçen ay verildi.'")], expect: produce("Die Steuererklärung wurde letzten Monat eingereicht", [tr("Tekil özne → wurde; ortaç sonda:"), de("Die Steuererklärung wurde letzten Monat eingereicht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yol masrafları gider gösterildi.'")], expect: produce("Die Fahrtkosten wurden abgesetzt", [tr("Çoğul özne → wurden:"), de("Die Fahrtkosten wurden abgesetzt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, bu kez etken: 'Makbuzları sakladım.'")], expect: produce("Ich habe die Quittungen aufgehoben", [tr("Kendi yaptığın iş etken kalır:"), de("Ich habe die Quittungen aufgehoben."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Quittungen wurde geprüft."), tr("cümlesi doğru mu?")], expect: truefalse("Die Quittungen wurde geprüft.", false, [tr("Özne çoğul olduğu için yardımcı fiil de çoğul:"), de("Die Quittungen wurden geprüft.")]) },
      { say: [tr("Son: 'Paranın bir kısmı iade edildi.'")], expect: produce("Ein Teil des Geldes wurde erstattet", [tr("Tekil özne, ortaç sonda:"), de("Ein Teil des Geldes wurde erstattet."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir mali müşavirle beyanını konuşacaksın: neyi gider gösterebilirsin, ne zaman iade gelir.")] },
    ],
    roleplay: {
      scene: "Bir mali müşavirle vergi beyanını konuşuyorsun: hangi masrafları gider gösterebilirsin, hangi belgeler lazım, iade ne zaman gelir. Sürecin adımlarını edilgenle anlat.",
      partner: "titiz, rakamlarla konuşan bir mali müşavir",
      opening: "Guten Tag. Bringen wir Ihre Steuererklärung hinter uns — was haben Sie denn schon vorbereitet?",
      openingTr: "İyi günler. Şu vergi beyanını halledelim — neleri hazırladınız?",
      goal: "Hangi masrafları gider gösterebileceğin, gereken belgeler ve iadenin ne zaman geleceği öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-versicherung",
    icon: "law",
    level: "B1",
    course: "de",
    title: "Ein Fall für die Versicherung",
    titleTr: "Sigorta bildirimi",
    summary: "Bir hasarı sırasıyla anlatmayı ve önce olanı Plusquamperfekt ile söylemeyi öğretir.",
    minutes: 10,
    focusId: "Plusquamperfekt",
    vocab: [
      { de: "die Versicherung", tr: "sigorta" },
      { de: "der Vorfall", tr: "olay" },
      { de: "entstehen", tr: "oluşmak" },
      { de: "der Gutachter", tr: "eksper" },
      { de: "haften", tr: "sorumlu olmak" },
    ],
    patterns: [
      { de: "Nachdem der Schaden entstanden war, …", tr: "önce olan iş: Plusquamperfekt" },
      { de: "Der Schaden wird übernommen.", tr: "sigorta dilinde edilgen" },
    ],
    lecture: [
      { say: [tr("Merhaba! Sigortaya hasar bildirmek bir anlatı işidir: önce ne oldu, sonra ne yaptın. Almanca bu sırayı fiilin biçimiyle gösterir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Daha önce olan iş bir basamak geriye çekilir; buna geçmişin geçmişi diyoruz. Türkçede '-mişti' ekiyle yaptığımız şeyin aynısı. Önce kelimeler.")] },
      word("İlk", { de: "die Versicherung", tr: "sigorta" }),
      word("İkinci", { de: "der Vorfall", tr: "olay" }),
      word("Üçüncü", { de: "entstehen", tr: "oluşmak" }),
      word("Dördüncü", { de: "der Gutachter", tr: "eksper" }),
      word("Son", { de: "haften", tr: "sorumlu olmak" }),
      { say: [tr("Kalıbımız:"), de("Nachdem der Schaden entstanden war, …"), tr("Yan cümle bir basamak geride, ana cümle normal geçmişte. Sıra böyle net olur.")] },
      { say: [tr("Örnek:"), de("Nachdem der Schaden entstanden war, habe ich die Versicherung angerufen."), tr("Tekrar edin:"), de("Nachdem der Schaden entstanden war, habe ich die Versicherung angerufen")], expect: repeat("Nachdem der Schaden entstanden war, habe ich die Versicherung angerufen") },
      { say: [tr("Sıra sende: 'Olayı bildirdikten sonra bir eksper geldi.'")], expect: produce("Nachdem ich den Vorfall gemeldet hatte, kam ein Gutachter", [tr("Önce olan iş bir basamak geride; ana cümle fiille başlar:"), de("Nachdem ich den Vorfall gemeldet hatte, kam ein Gutachter."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi tek cümle: 'Hasar gece oluşmuştu.'")], expect: produce("Der Schaden war in der Nacht entstanden", [tr("Hareket bildiren bu fiil sein ile çekilir:"), de("Der Schaden war in der Nacht entstanden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sigorta masrafları karşılıyor.'")], expect: produce("Die Versicherung übernimmt die Kosten", [tr("Burada özne belli, yani etken cümle yeter:"), de("Die Versicherung übernimmt die Kosten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nachdem ich angerufen hatte, kam der Gutachter."), tr("cümlesi doğru mu?")], expect: truefalse("Nachdem ich angerufen hatte, kam der Gutachter.", true, [tr("Doğru. Önce olan iş bir basamak geride, ana cümle normal geçmişte ve fiille başlıyor.")]) },
      { say: [tr("Son: 'Bu zarardan komşum sorumlu.'")], expect: produce("Für diesen Schaden haftet mein Nachbar", [tr("Cümle bir tümleçle başlayınca fiil ikinci sırada kalır:"), de("Für diesen Schaden haftet mein Nachbar."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sigortayı arayacaksın: ne oldu, ne zaman oldu, sonra ne yaptın.")] },
    ],
    roleplay: {
      scene: "Sigorta şirketini arıyorsun ve bir hasarı bildiriyorsun: ne oldu, ne zaman oldu, sonra ne yaptın. Sıralamayı önce olan işi bir basamak geriye çekerek anlat.",
      partner: "soruları sırayla soran, sakin bir sigorta görevlisi",
      opening: "Versicherung Nordstern, guten Tag. Sie möchten einen Schaden melden — was ist genau passiert?",
      openingTr: "Nordstern Sigorta, iyi günler. Hasar bildirmek istiyorsunuz — tam olarak ne oldu?",
      goal: "Hasar sırayla bildirilmiş ve bundan sonra ne olacağı söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-termin-verschieben",
    icon: "calendar",
    level: "B1",
    course: "de",
    title: "Der Amtstermin",
    titleTr: "Randevu erteleme",
    summary: "Resmî bir randevuyu ertelemek için en kibar rica kalıplarını öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "der Ersatztermin", tr: "yeni randevu" },
      { de: "dankbar", tr: "minnettar" },
      { de: "die Wartezeit", tr: "bekleme süresi" },
      { de: "bestätigen", tr: "onaylamak" },
      { de: "zeitlich", tr: "zaman olarak" },
    ],
    patterns: [
      { de: "Wäre es möglich, …?", tr: "en kibar rica biçimi" },
      { de: "Ich wäre Ihnen dankbar, wenn …", tr: "resmî yazıda kibar dilek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün Almanya'da altın değerinde bir beceri: randevuyu kibarca ertelemek. Kaba bir 'olmuyor' ile kibar bir dilek arasındaki fark tek bir fiil biçiminde. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kibarlığı taşıyan biçime dilek kipi diyoruz. İki fiili yeter: olmak ve sahip olmak. Gerisini bu ikisi taşır. Önce kelimeler.")] },
      word("İlk", { de: "der Ersatztermin", tr: "yeni randevu" }),
      word("İkinci", { de: "dankbar", tr: "minnettar" }),
      word("Üçüncü", { de: "die Wartezeit", tr: "bekleme süresi" }),
      word("Dördüncü", { de: "bestätigen", tr: "onaylamak" }),
      word("Son", { de: "zeitlich", tr: "zaman olarak" }),
      { say: [tr("Kalıbımız:"), de("Wäre es möglich, …?"), tr("Aynı soruyu düz biçimde sorarsan da anlaşılır, ama resmî yazıda bu biçim beklenir.")] },
      { say: [tr("Örnek:"), de("Wäre es möglich, den Termin zu verschieben?"), tr("Tekrar edin:"), de("Wäre es möglich, den Termin zu verschieben")], expect: repeat("Wäre es möglich, den Termin zu verschieben") },
      { say: [tr("Sıra sende: 'Randevuyu bir hafta erteleyebilir miyim?'")], expect: produce("Könnte ich den Termin um eine Woche verschieben", [tr("Dilek kipiyle sorulan kibar soru:"), de("Könnte ich den Termin um eine Woche verschieben?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bana yeni bir randevu verirseniz minnettar olurum.'")], expect: produce("Ich wäre Ihnen dankbar, wenn Sie mir einen Ersatztermin geben", [tr("Ana cümlede dilek kipi, yan cümlede fiil sonda:"), de("Ich wäre Ihnen dankbar, wenn Sie mir einen Ersatztermin geben."), tr("Tekrar dene.")], ["Ich wäre Ihnen dankbar, wenn Sie mir einen Ersatztermin geben würden"]) },
      { say: [tr("Bir tane daha: 'Randevuyu yazılı olarak onaylayabilir misiniz?'")], expect: produce("Könnten Sie den Termin schriftlich bestätigen", [tr("Kibar soruda dilek kipi ve mastar sonda:"), de("Könnten Sie den Termin schriftlich bestätigen?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich wäre Ihnen dankbar, wenn Sie mir helfen würde."), tr("cümlesi doğru mu?")], expect: truefalse("Ich wäre Ihnen dankbar, wenn Sie mir helfen würde.", false, [tr("Özne kibar biçim olduğu için yardımcı fiil de çoğul çekilir:"), de("Ich wäre Ihnen dankbar, wenn Sie mir helfen würden.")]) },
      { say: [tr("Son: 'O gün zaman olarak bana uymuyor.'")], expect: produce("Der Tag passt mir zeitlich leider nicht", [tr("Uymak fiili yönelme ister; olumsuzluk sonda:"), de("Der Tag passt mir zeitlich leider nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada daireyi arayıp randevunu erteleyeceksin: sebebini söyle, yeni tarih iste, onay iste.")] },
    ],
    roleplay: {
      scene: "Daireyi arayıp randevunu ertelemek istiyorsun: sebebini kısaca söyle, yeni bir tarih iste, onayın yazılı gelmesini rica et. Ricalarını dilek kipiyle kur.",
      partner: "kurallara bağlı ama esnetmeye açık bir randevu görevlisi",
      opening: "Bürgeramt, guten Tag. Sie möchten Ihren Termin ändern? Um welchen Termin geht es?",
      openingTr: "Nüfus dairesi, iyi günler. Randevunuzu değiştirmek mi istiyorsunuz? Hangi randevu için?",
      goal: "Erteleme sebebi söylenmiş, yeni tarih alınmış ve onayın yazılı geleceği kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-vollmacht",
    icon: "pen",
    level: "B1",
    course: "de",
    title: "Die Vollmacht",
    titleTr: "Vekâlet verme",
    summary: "Birini adına işlem yapmaya yetkilendiren belgenin dilini öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Vollmacht", tr: "vekâletname" },
      { de: "bevollmächtigen", tr: "yetkilendirmek" },
      { de: "vertreten", tr: "temsil etmek" },
      { de: "das Original", tr: "asıl nüsha" },
      { de: "widerrufen", tr: "geri almak" },
    ],
    patterns: [
      { de: "Hiermit wird … bevollmächtigt.", tr: "belgenin kendi cümlesi: edilgen" },
      { de: "in meinem Namen", tr: "benim adıma" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün küçük ama çok işe yarayan bir belge: vekâletname. Bir satırla başkasının senin adına işlem yapmasını sağlıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Belgenin dili tuhaf gelebilir: kimse konuşmuyor, belge kendi kendine konuşuyor. Bu yüzden edilgen. Önce kelimeler.")] },
      word("İlk", { de: "die Vollmacht", tr: "vekâletname" }),
      word("İkinci", { de: "bevollmächtigen", tr: "yetkilendirmek" }),
      word("Üçüncü", { de: "vertreten", tr: "temsil etmek" }),
      word("Dördüncü", { de: "das Original", tr: "asıl nüsha" }),
      word("Son", { de: "widerrufen", tr: "geri almak" }),
      { say: [tr("Kalıbımız:"), de("Hiermit wird Frau Kaya bevollmächtigt."), tr("Tekil bir kişi yetkilendirildiği için yardımcı fiil tekil, ortaç en sonda.")] },
      { say: [tr("Tekrar edin:"), de("Hiermit wird Frau Kaya bevollmächtigt")], expect: repeat("Hiermit wird Frau Kaya bevollmächtigt") },
      { say: [tr("Sıra sende: 'Kız kardeşim beni dairede temsil ediyor.'")], expect: produce("Meine Schwester vertritt mich auf dem Amt", [tr("Etken cümle; bu fiil kök ünlüsünü değiştirir: vertritt:"), de("Meine Schwester vertritt mich auf dem Amt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi belge dilinde: 'Vekâletname benim adıma imzalanıyor.'")], expect: produce("Die Vollmacht wird in meinem Namen unterschrieben", [tr("Edilgen: yardımcı fiil ikinci sırada, ortaç sonda:"), de("Die Vollmacht wird in meinem Namen unterschrieben."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Asıl nüsha ibraz edilmeli.'")], expect: produce("Das Original muss vorgelegt werden", [tr("Modal fiille edilgen: ortaç ve werden en sonda:"), de("Das Original muss vorgelegt werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Hiermit werde meine Tochter bevollmächtigt."), tr("cümlesi doğru mu?")], expect: truefalse("Hiermit werde meine Tochter bevollmächtigt.", false, [tr("Özne üçüncü tekil kişi, yani yardımcı fiil de tekil çekilir:"), de("Hiermit wird meine Tochter bevollmächtigt.")]) },
      { say: [tr("Son: 'Vekâleti her zaman geri alabilirim.'")], expect: produce("Ich kann die Vollmacht jederzeit widerrufen", [tr("Modal fiil çekimli, mastar en sonda:"), de("Ich kann die Vollmacht jederzeit widerrufen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir yakınına vekâlet vereceksin: neyi yapmasını istiyorsun, hangi belge lazım, ne zaman geçerli.")] },
    ],
    roleplay: {
      scene: "Bir yakınına vekâlet vermek için danışma masasındasın: kimin, neyi, ne zamana kadar yapabileceğini anlat ve hangi belgelerin gerektiğini sor.",
      partner: "kısa ve net konuşan bir danışma görevlisi",
      opening: "Guten Tag. Sie möchten eine Vollmacht ausstellen — wer soll Sie denn vertreten?",
      openingTr: "İyi günler. Vekâletname çıkarmak istiyorsunuz — sizi kim temsil edecek?",
      goal: "Kimin neyi ne zamana kadar yapabileceği netleşmiş ve gereken belgeler öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-einbuergerung",
    icon: "flag",
    level: "B1",
    course: "de",
    title: "Der Einbürgerungstest",
    titleTr: "Vatandaşlık sohbeti",
    summary: "Dolaylı soru kalıplarıyla bilmediğin resmî ayrıntıları sormayı öğretir.",
    minutes: 10,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "die Einbürgerung", tr: "vatandaşlığa geçiş" },
      { de: "die Staatsangehörigkeit", tr: "vatandaşlık" },
      { de: "verlangen", tr: "talep etmek" },
      { de: "das Grundgesetz", tr: "anayasa" },
      { de: "nachweisen", tr: "belgelemek" },
    ],
    patterns: [
      { de: "Ich frage mich, ob …", tr: "dolaylı evet-hayır sorusu" },
      { de: "Wissen Sie, wann …?", tr: "soru kelimeli dolaylı soru" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi. Dairede en çok işine yarayan cümle bir soru değil, sorunun yumuşatılmış hâlidir: 'Acaba … mı?' Bugün onu kuracağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dolaylı soruda iki şey olur: soru kelimesi ya da bir bağlaç başa gelir, çekimli fiil en sona gider. Yani düz soru cümlesi bozulur. Önce kelimeler.")] },
      word("İlk", { de: "die Einbürgerung", tr: "vatandaşlığa geçiş" }),
      word("İkinci", { de: "die Staatsangehörigkeit", tr: "vatandaşlık" }),
      word("Üçüncü", { de: "verlangen", tr: "talep etmek" }),
      word("Dördüncü", { de: "das Grundgesetz", tr: "anayasa" }),
      word("Son", { de: "nachweisen", tr: "belgelemek" }),
      { say: [tr("Kalıbımız:"), de("Ich frage mich, ob …"), tr("Evet-hayır sorusu dolaylı hâle gelince başına bir bağlaç alır ve fiil sona gider.")] },
      { say: [tr("Örnek:"), de("Ich frage mich, ob ich den Test bestehe."), tr("Tekrar edin:"), de("Ich frage mich, ob ich den Test bestehe")], expect: repeat("Ich frage mich, ob ich den Test bestehe") },
      { say: [tr("Sıra sende: 'Ne isteniyor biliyor musunuz?'")], expect: produce("Wissen Sie, was verlangt wird", [tr("Soru kelimesi başta, edilgen fiil sonda:"), de("Wissen Sie, was verlangt wird?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sınavın ne zaman olduğunu bilmiyorum.'")], expect: produce("Ich weiß nicht, wann der Test stattfindet", [tr("Yan cümlede ayrılabilen fiil tek parça ve en sonda:"), de("Ich weiß nicht, wann der Test stattfindet."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Almancamı belgelemem gerekiyor mu acaba?'")], expect: produce("Ich frage mich, ob ich mein Deutsch nachweisen muss", [tr("Modal fiil en sonda, mastar onun önünde:"), de("Ich frage mich, ob ich mein Deutsch nachweisen muss."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wissen Sie, wann kommt der Bescheid?"), tr("cümlesi doğru mu?")], expect: truefalse("Wissen Sie, wann kommt der Bescheid?", false, [tr("Dolaylı soruda fiil en sona gider:"), de("Wissen Sie, wann der Bescheid kommt?")]) },
      { say: [tr("Son: 'Başvurunun ne kadar sürdüğünü sorabilir miyim?'")], expect: produce("Darf ich fragen, wie lange der Antrag dauert", [tr("Kibar giriş, sonra soru kelimesi ve sonda fiil:"), de("Darf ich fragen, wie lange der Antrag dauert?"), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada vatandaşlık danışmanına bilmediklerini soracaksın: ne isteniyor, ne kadar sürüyor, hangi belge gerekiyor.")] },
    ],
    roleplay: {
      scene: "Vatandaşlık danışmanıyla oturuyorsun ve bilmediklerini soruyorsun: hangi şartlar isteniyor, sınav ne zaman, hangi belgeler gerekiyor. Sorularını dolaylı biçimde sor.",
      partner: "bilgili, ayrıntı veren bir vatandaşlık danışmanı",
      opening: "Schön, dass Sie da sind. Sie interessieren sich für die Einbürgerung — was möchten Sie zuerst wissen?",
      openingTr: "Geldiğinize sevindim. Vatandaşlıkla ilgileniyorsunuz — önce neyi öğrenmek istersiniz?",
      goal: "Aranan şartlar, sınavın zamanı ve gereken belgeler öğrenilmiş olur.",
      minTurns: 9,
    },
  },
];
