import { de, tr, type LectureStep, type Lesson, type Segment } from "../types";

/**
 * B1 · Modül 15 — Evde teknik ve onarım (141–150).
 *
 * Bu modülün derdi tek: bir şey bozulduğunda ne diyeceğini bilmek. Almanya'da
 * teknik destek, ev sahibi ve sigorta hep aynı iki şeyi sorar — ne oldu ve ne
 * yaptın. İkisi de kişisiz anlatım ister, o yüzden modülde edilgen çatı ve
 * kişisiz özne baskın.
 *
 * Sözlükçe havuzun teknik-ev kümesinden; hepsi somut nesne ya da somut işlem.
 * Soyut "dijitalleşme" sözcükleri bilerek alınmadı: bozulan bir prizden
 * bahsedemeyen öğrenciye teknoloji tartışması öğretmek sıralamayı bozar.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [
      tr(`${n} kelimemiz:`),
      de(w.de),
      tr(`Türkçesi '${w.tr}' demek${note ? ` — ${note}` : ""}. Lütfen`),
      de(w.de),
      tr("deyin."),
    ],
    expect: repeat(w.de),
  };
}

export const deB1B15: Lesson[] = [
  {
    id: "de-b1-geraet-anschliessen",
    icon: "tech",
    level: "B1",
    course: "de",
    title: "Anschließen und einschalten",
    titleTr: "Cihazı kurmak",
    summary: "Kurulum adımlarını edilgen cümlelerle anlamayı ve anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Steckdose", tr: "priz" },
      { de: "anschließen", tr: "bağlamak" },
      { de: "einschalten", tr: "açmak" },
      { de: "der Lautsprecher", tr: "hoparlör" },
      { de: "die Klimaanlage", tr: "klima" },
      { de: "die Technik", tr: "teknik" },
      { de: "die Anleitung", tr: "kılavuz" },
      { de: "gebrauchen", tr: "kullanmak" },
    ],
    patterns: [
      { de: "Zuerst wird … angeschlossen.", tr: "kurulum adımını kişisiz anlatır" },
      { de: "Erst danach wird eingeschaltet.", tr: "sıranın önemli olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni bir cihaz aldın ve kutudan kılavuz çıktı. Kılavuzlar tarif gibi yazılır: kimin yaptığı söylenmez. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yüzden edilgen çatı kullanıyoruz: yardımcı fiil ikinci sırada, ortaç en sonda. Ayrılabilen fiillerde ortaç önekle birlikte kurulur. Önce kelimeler.")] },
      word("İlk", { de: "die Steckdose", tr: "priz" }),
      word("İkinci", { de: "anschließen", tr: "bağlamak" }, "ayrılabilen bir fiil"),
      word("Üçüncü", { de: "einschalten", tr: "açmak" }),
      word("Dördüncü", { de: "der Lautsprecher", tr: "hoparlör" }),
      word("Beşinci", { de: "die Klimaanlage", tr: "klima" }),
      word("Altıncı", { de: "die Technik", tr: "teknik" }),
      word("Yedinci", { de: "die Anleitung", tr: "kılavuz" }),
      word("Son", { de: "gebrauchen", tr: "kullanmak" }),
      { say: [tr("İlk kalıbımız ilk adımı veriyor. Sıra zarfı başta olduğu için yardımcı fiil hemen arkasından geliyor.")] },
      { say: [tr("Örnek:"), de("Zuerst wird das Kabel an die Steckdose angeschlossen."), tr("Tekrar edin:"), de("Zuerst wird das Kabel an die Steckdose angeschlossen")], expect: repeat("Zuerst wird das Kabel an die Steckdose angeschlossen") },
      { say: [tr("Sıra sende: 'Sonra hoparlör bağlanır.'")], expect: produce("Danach wird der Lautsprecher angeschlossen", [tr("Zarf başta, yardımcı fiil ikinci sırada, ortaç sonda:"), de("Danach wird der Lautsprecher angeschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız sıranın önemli olduğunu söylüyor. Öznesiz bir edilgen: yapan da yapılan da söylenmiyor, yalnız işlem.")] },
      { say: [tr("Şimdi: 'Ancak ondan sonra açılır.'")], expect: produce("Erst danach wird eingeschaltet", [tr("Öznesiz edilgen, yardımcı fiil tekil:"), de("Erst danach wird eingeschaltet."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Klimaanlage wird nach der Anleitung anschließen."), tr("cümlesi doğru mu?")], expect: truefalse("Die Klimaanlage wird nach der Anleitung anschließen.", false, [tr("Edilgende asıl fiil ortaç hâlinde olmalı, mastar hâlinde değil:"), de("Die Klimaanlage wird nach der Anleitung angeschlossen.")]) },
      { say: [tr("Son: 'Cihaz yalnız kapalı alanda kullanılır.'")], expect: produce("Das Gerät wird nur in Innenräumen gebraucht", [tr("Yer tümleci ortada, ortaç sonda:"), de("Das Gerät wird nur in Innenräumen gebraucht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir arkadaşına telefonda cihazı nasıl kuracağını anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın yeni aldığı cihazı kuramıyor ve seni arıyor. Adımları sırayla ve kişisiz biçimde anlatıyorsun.",
      partner: "kılavuzu okumadan başlamış, sabırsız bir arkadaş",
      opening: "Ich habe hier drei Kabel und keine Ahnung — was wird zuerst gemacht?",
      openingTr: "Elimde üç kablo var ve hiçbir fikrim yok — önce ne yapılıyor?",
      goal: "En az dört adım sırayla anlatılmış ve cihaz çalışır duruma gelmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-computer-problem",
    icon: "tech",
    level: "B1",
    course: "de",
    title: "Der Rechner streikt",
    titleTr: "Bilgisayar sorunu",
    summary: "Bir arızanın sebebini weil yan cümlesiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-weil",
    vocab: [
      { de: "der Monitor", tr: "monitör" },
      { de: "die Tastatur", tr: "klavye" },
      { de: "die Taste", tr: "tuş" },
      { de: "die Festplatte", tr: "sabit disk" },
      { de: "der Klick", tr: "tıklama" },
      { de: "die Daten", tr: "veriler" },
      { de: "löschen", tr: "silmek" },
      { de: "sichern", tr: "yedeklemek" },
    ],
    patterns: [
      { de: "Es geht nicht, weil …", tr: "arızanın sebebini söyler" },
      { de: "Ich habe … gesichert.", tr: "ne yaptığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bilgisayar çalışmıyor ve destek hattını arayacaksın. İlk soru hep aynı: neden çalışmıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sebep bağlacından sonra çekimli fiil cümlenin en sonuna gider. Bu tek kural şikâyetini anlaşılır kılıyor. Önce kelimeler.")] },
      word("İlk", { de: "der Monitor", tr: "monitör" }),
      word("İkinci", { de: "die Tastatur", tr: "klavye" }),
      word("Üçüncü", { de: "die Taste", tr: "tuş" }, "klavyedeki tek bir düğme"),
      word("Dördüncü", { de: "die Festplatte", tr: "sabit disk" }),
      word("Beşinci", { de: "der Klick", tr: "tıklama" }),
      word("Altıncı", { de: "die Daten", tr: "veriler" }, "hep çoğul kullanılır"),
      word("Yedinci", { de: "löschen", tr: "silmek" }),
      word("Son", { de: "sichern", tr: "yedeklemek" }),
      { say: [tr("İlk kalıbımız sebebi veriyor: kişisiz bir ana cümle ve sebep bağlacı. Bağlaçtan sonra fiil sona gidiyor.")] },
      { say: [tr("Örnek:"), de("Es geht nicht, weil die Festplatte voll ist."), tr("Tekrar edin:"), de("Es geht nicht, weil die Festplatte voll ist")], expect: repeat("Es geht nicht, weil die Festplatte voll ist") },
      { say: [tr("Sıra sende: 'Çalışmıyor, çünkü bir tuş takılı kalmış.'")], expect: produce("Es geht nicht, weil eine Taste klemmt", [tr("Bağlaçtan sonra fiil en sonda:"), de("Es geht nicht, weil eine Taste klemmt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız ne yaptığını söylüyor. Destek hattı bunu mutlaka sorar: yedek aldın mı.")] },
      { say: [tr("Şimdi: 'Verileri dün yedekledim.'")], expect: produce("Ich habe die Daten gestern gesichert", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Ich habe die Daten gestern gesichert."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Monitor bleibt schwarz, weil ist das Kabel lose."), tr("cümlesi doğru mu?")], expect: truefalse("Der Monitor bleibt schwarz, weil ist das Kabel lose.", false, [tr("Sebep bağlacından sonra fiil öne gelmez, en sona gider:"), de("Der Monitor bleibt schwarz, weil das Kabel lose ist.")]) },
      { say: [tr("Son: 'Hiçbir şey silmedim, çünkü yedeğim yoktu.'")], expect: produce("Ich habe nichts gelöscht, weil ich keine Sicherung hatte", [tr("Bağlaçtan sonra fiil sonda:"), de("Ich habe nichts gelöscht, weil ich keine Sicherung hatte."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi teknik destek hattını arayacak ve sorunu sebebiyle anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bilgisayarın açılmıyor. Teknik destek hattını arıyor, belirtileri sayıyor, ne denediğini ve yedek alıp almadığını söylüyorsun.",
      partner: "sırayla soru soran, adım adım ilerleyen bir destek görevlisi",
      opening: "Technischer Support, guten Tag. Können Sie mir beschreiben, was genau passiert?",
      openingTr: "Teknik destek, iyi günler. Tam olarak ne olduğunu anlatabilir misiniz?",
      goal: "Belirtiler sayılmış, sebep tahmini söylenmiş ve bir sonraki adım kararlaştırılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-netz-stoerung",
    icon: "tech",
    level: "B1",
    course: "de",
    title: "Kein Netz",
    titleTr: "Bağlantı yok",
    summary: "Bilmediğin teknik ayrıntıları dolaylı soru kalıplarıyla sormayı öğretir.",
    minutes: 10,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "das Netzwerk", tr: "ağ" },
      { de: "das Netz", tr: "şebeke" },
      { de: "die Störung", tr: "arıza" },
      { de: "unterbrechen", tr: "kesmek" },
      { de: "verbinden", tr: "bağlantı kurmak" },
      { de: "technisch", tr: "teknik olarak" },
      { de: "weshalb", tr: "neden" },
      { de: "normalerweise", tr: "normalde" },
    ],
    patterns: [
      { de: "Können Sie mir sagen, weshalb …?", tr: "sebebi kibarca sorar" },
      { de: "Ich weiß nicht, wie lange …", tr: "süreyi bilmediğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! İnternet gitti ve sağlayıcıyı arayacaksın. Teknik konuşmalarda doğrudan soru sert durur; dolaylı soru hem kibar hem daha net. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dolaylı soruda soru sözcüğü bağlaç olur ve fiil en sona gider. Önce kelimeler.")] },
      word("İlk", { de: "das Netzwerk", tr: "ağ" }),
      word("İkinci", { de: "das Netz", tr: "şebeke" }),
      word("Üçüncü", { de: "die Störung", tr: "arıza" }),
      word("Dördüncü", { de: "unterbrechen", tr: "kesmek" }),
      word("Beşinci", { de: "verbinden", tr: "bağlantı kurmak" }),
      word("Altıncı", { de: "technisch", tr: "teknik olarak" }),
      word("Yedinci", { de: "weshalb", tr: "neden" }),
      word("Son", { de: "normalerweise", tr: "normalde" }),
      { say: [tr("İlk kalıbımız sebebi soruyor. Soru sözcüğü bağlaca dönüşüyor ve fiil yan cümlenin sonuna geçiyor.")] },
      { say: [tr("Örnek:"), de("Können Sie mir sagen, weshalb die Verbindung unterbrochen wird?"), tr("Tekrar edin:"), de("Können Sie mir sagen, weshalb die Verbindung unterbrochen wird")], expect: repeat("Können Sie mir sagen, weshalb die Verbindung unterbrochen wird") },
      { say: [tr("Sıra sende: 'Arızanın neden olduğunu söyleyebilir misiniz?'")], expect: produce("Können Sie mir sagen, weshalb es eine Störung gibt", [tr("Bağlaçtan sonra fiil en sonda:"), de("Können Sie mir sagen, weshalb es eine Störung gibt?"), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız süreyi soruyor. Burada da soru sözcüğü öbeği bağlaç oluyor.")] },
      { say: [tr("Şimdi: 'Ne kadar süreceğini bilmiyorum.'")], expect: produce("Ich weiß nicht, wie lange es dauert", [tr("Soru sözcüğü öbeği bağlaç, fiil sonda:"), de("Ich weiß nicht, wie lange es dauert."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich frage mich, weshalb funktioniert das Netz nicht."), tr("cümlesi doğru mu?")], expect: truefalse("Ich frage mich, weshalb funktioniert das Netz nicht.", false, [tr("Dolaylı soruda çekimli fiil cümlenin sonuna gider:"), de("Ich frage mich, weshalb das Netz nicht funktioniert.")]) },
      { say: [tr("Son: 'Normalde bağlantının ne kadar sürdüğünü sorabilir miyim?'")], expect: produce("Darf ich fragen, wie lange die Verbindung normalerweise dauert", [tr("Kibar giriş, bağlaç ve sonda fiil:"), de("Darf ich fragen, wie lange die Verbindung normalerweise dauert?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi sağlayıcıyı arayacak ve arızayı soracaksın.")] },
    ],
    roleplay: {
      scene: "Evde internet üç gündür kesik. Sağlayıcıyı arayıp sebebini, ne zaman düzeleceğini ve ücret iadesi olup olmadığını dolaylı sorularla öğreniyorsun.",
      partner: "hazır cümlelerle konuşan ama zorlayınca bilgi veren bir çağrı merkezi görevlisi",
      opening: "Danke für Ihren Anruf. Um welche Adresse geht es denn?",
      openingTr: "Aradığınız için teşekkürler. Hangi adres için arıyorsunuz?",
      goal: "Arızanın sebebi, tahmini süresi ve ücret iadesi konusu öğrenilmiş olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-werkzeug-leihen",
    icon: "repair",
    level: "B1",
    course: "de",
    title: "Werkzeug leihen",
    titleTr: "Alet ödünç almak",
    summary: "Komşudan bir şey istemenin en kibar biçimini dilek kipiyle öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "der Hammer", tr: "çekiç" },
      { de: "die Zange", tr: "pense" },
      { de: "der Nagel", tr: "çivi" },
      { de: "die Leiter", tr: "el merdiveni" },
      { de: "das Loch", tr: "delik" },
      { de: "kleben", tr: "yapıştırmak" },
      { de: "die Mühe", tr: "zahmet" },
      { de: "umsonst", tr: "bedava; boşuna" },
    ],
    patterns: [
      { de: "Dürfte ich mir … leihen?", tr: "en kibar ödünç isteme biçimi" },
      { de: "Es wäre nett, wenn …", tr: "ricayı yumuşatarak söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Evde küçük bir iş var ve aletin yok. Komşudan bir şey istemek Almanya'da normaldir ama biçimi önemlidir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("En kibar isteme biçimi izin fiilinin dilek kipiyle kurulur. Bu biçim rica ile izin isteğini birleştirir. Önce kelimeler.")] },
      word("İlk", { de: "der Hammer", tr: "çekiç" }),
      word("İkinci", { de: "die Zange", tr: "pense" }),
      word("Üçüncü", { de: "der Nagel", tr: "çivi" }),
      word("Dördüncü", { de: "die Leiter", tr: "el merdiveni" }, "aynı sözcüğün eril biçimi 'yönetici' demek"),
      word("Beşinci", { de: "das Loch", tr: "delik" }),
      word("Altıncı", { de: "kleben", tr: "yapıştırmak" }),
      word("Yedinci", { de: "die Mühe", tr: "zahmet" }),
      word("Son", { de: "umsonst", tr: "bedava; boşuna" }, "iki anlamı da yaygın"),
      { say: [tr("İlk kalıbımız izin isteyerek rica ediyor. Dönüşlü zamir burada 'kendim için' anlamını taşıyor.")] },
      { say: [tr("Örnek:"), de("Dürfte ich mir kurz die Leiter leihen?"), tr("Tekrar edin:"), de("Dürfte ich mir kurz die Leiter leihen")], expect: repeat("Dürfte ich mir kurz die Leiter leihen") },
      { say: [tr("Sıra sende: 'Çekicinizi ödünç alabilir miyim?'")], expect: produce("Dürfte ich mir Ihren Hammer leihen", [tr("Dilek kipi başta, dönüşlü zamir arkasında, mastar sonda:"), de("Dürfte ich mir Ihren Hammer leihen?"), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız ricayı yumuşatıyor: kişisiz dilek kipi ve koşul yan cümlesi.")] },
      { say: [tr("Şimdi: 'Bana yardım etseniz çok iyi olurdu.'")], expect: produce("Es wäre nett, wenn Sie mir helfen würden", [tr("Koşul yan cümlesinde dilek kipi ve fiil sonda:"), de("Es wäre nett, wenn Sie mir helfen würden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dürfte ich leihen mir die Zange?"), tr("cümlesi doğru mu?")], expect: truefalse("Dürfte ich leihen mir die Zange?", false, [tr("Soru cümlesinde çekimli fiil başta, mastar en sonda kalır:"), de("Dürfte ich mir die Zange leihen?")]) },
      { say: [tr("Son: 'Bütün zahmet boşunaydı, delik hâlâ orada.'")], expect: produce("Die ganze Mühe war umsonst, das Loch ist immer noch da", [tr("İki ana cümle, ikisinde de fiil ikinci sırada:"), de("Die ganze Mühe war umsonst, das Loch ist immer noch da."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi komşundan alet isteyeceksin.")] },
    ],
    roleplay: {
      scene: "Duvara raf asacaksın ama aletin yok. Komşunun kapısını çalıyor, ne yapacağını anlatıyor ve alet ödünç istiyorsun.",
      partner: "yardım etmeye hazır ama aletine düşkün bir komşu",
      opening: "Oh, hallo! Sie sehen aus, als bräuchten Sie etwas — was kann ich tun?",
      openingTr: "Aa, merhaba! Bir şeye ihtiyacınız varmış gibi görünüyorsunuz — ne yapabilirim?",
      goal: "Ne yapılacağı anlatılmış, alet kibarca istenmiş ve ne zaman geri verileceği söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-putzen-teilen",
    icon: "home",
    level: "B1",
    course: "de",
    title: "Wer putzt was?",
    titleTr: "Temizlik paylaşımı",
    summary: "Bir düzenlemenin amacını damit yan cümlesiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-damit",
    vocab: [
      { de: "das Waschmittel", tr: "deterjan" },
      { de: "der Staub", tr: "toz" },
      { de: "der Schmutz", tr: "kir" },
      { de: "der Dreck", tr: "pislik" },
      { de: "feucht", tr: "nemli" },
      { de: "gründlich", tr: "iyice" },
      { de: "glatt", tr: "kaygan / pürüzsüz" },
      { de: "die Couch", tr: "kanepe" },
    ],
    patterns: [
      { de: "…, damit es nicht schmutzig wird", tr: "amaç söyler; özne farklıdır" },
      { de: "Wir wechseln uns ab.", tr: "dönüşümlü yapıldığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Ortak yaşamın en tartışmalı konusu temizlik. Bugün hem işi bölüşeceğiz hem her kuralın amacını söyleyeceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amaç bağlacı özne farklı olduğunda kullanılır ve fiili sona atar. Amacı söylemek kuralı tartışmadan çıkarır. Önce kelimeler.")] },
      word("İlk", { de: "das Waschmittel", tr: "deterjan" }),
      word("İkinci", { de: "der Staub", tr: "toz" }),
      word("Üçüncü", { de: "der Schmutz", tr: "kir" }),
      word("Dördüncü", { de: "der Dreck", tr: "pislik" }, "günlük dilde daha kaba durur"),
      word("Beşinci", { de: "feucht", tr: "nemli" }),
      word("Altıncı", { de: "gründlich", tr: "iyice" }),
      word("Yedinci", { de: "glatt", tr: "kaygan / pürüzsüz" }),
      word("Son", { de: "die Couch", tr: "kanepe" }),
      { say: [tr("İlk kalıbımız amacı söylüyor. Bağlaçtan sonra çekimli fiil cümlenin en sonuna gider.")] },
      { say: [tr("Örnek:"), de("Ich wische jeden Tag, damit der Boden nicht schmutzig wird."), tr("Tekrar edin:"), de("Ich wische jeden Tag, damit der Boden nicht schmutzig wird")], expect: repeat("Ich wische jeden Tag, damit der Boden nicht schmutzig wird") },
      { say: [tr("Sıra sende: 'Kanepeyi örtüyorum ki toz tutmasın.'")], expect: produce("Ich decke die Couch ab, damit sie keinen Staub bekommt", [tr("Ana cümlede önek sonda, yan cümlede fiil sonda:"), de("Ich decke die Couch ab, damit sie keinen Staub bekommt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız iş bölümünü söylüyor: dönüşlü ve ayrılabilen bir fiil. Önek cümlenin sonunda kalır.")] },
      { say: [tr("Şimdi: 'Her hafta dönüşümlü yapıyoruz.'")], expect: produce("Wir wechseln uns jede Woche ab", [tr("Dönüşlü zamir fiilden hemen sonra, önek sonda:"), de("Wir wechseln uns jede Woche ab."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich putze gründlich, damit muss niemand nachputzen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich putze gründlich, damit muss niemand nachputzen.", false, [tr("Amaç bağlacından sonra çekimli fiil cümlenin sonuna gider:"), de("Ich putze gründlich, damit niemand nachputzen muss.")]) },
      { say: [tr("Son: 'Zemin nemliyken kaygan oluyor, dikkat et.'")], expect: produce("Wenn der Boden feucht ist, wird er glatt, pass auf", [tr("Koşul yan cümlesi, ana cümle fiille başlıyor:"), de("Wenn der Boden feucht ist, wird er glatt, pass auf."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi ev arkadaşınla temizlik düzenini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Ev arkadaşınla temizlik düzenini konuşuyorsunuz: kim neyi ne sıklıkta yapacak ve her kuralın amacı ne.",
      partner: "temizlik konusunda senden gevşek bir ev arkadaşı",
      opening: "Müssen wir wirklich einen Plan machen? Geht das nicht auch so?",
      openingTr: "Gerçekten bir plan yapmamız gerekiyor mu? Böyle olmuyor mu?",
      goal: "İş bölümü yapılmış, en az iki kuralın amacı söylenmiş ve bir düzen üzerinde anlaşılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-einbruch-melden",
    icon: "key",
    level: "B1",
    course: "de",
    title: "Es wurde eingebrochen",
    titleTr: "Hırsızlık bildirimi",
    summary: "Olan biteni edilgen çatının geçmişiyle resmî biçimde anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "der Einbruch", tr: "ev soygunu" },
      { de: "der Einbrecher", tr: "ev hırsızı" },
      { de: "einbrechen", tr: "zorla girmek" },
      { de: "stehlen", tr: "çalmak" },
      { de: "die Gewalt", tr: "şiddet" },
      { de: "der Täter", tr: "fail" },
      { de: "der Dieb", tr: "hırsız" },
      { de: "sichtbar", tr: "görünür" },
    ],
    patterns: [
      { de: "Es wurde eingebrochen.", tr: "faili bilinmeyen olayı bildirir" },
      { de: "… wurde gestohlen.", tr: "neyin çalındığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Eve girilmiş ve polise bildireceksin. Resmî bildirimde fail bilinmediği için edilgen çatı kullanılır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgenin geçmişinde yardımcı fiil geçmiş biçimde ikinci sırada, ortaç en sonda. Öznesiz kullanımda yardımcı fiil tekil kalır. Önce kelimeler.")] },
      word("İlk", { de: "der Einbruch", tr: "ev soygunu" }),
      word("İkinci", { de: "der Einbrecher", tr: "ev hırsızı" }),
      word("Üçüncü", { de: "einbrechen", tr: "zorla girmek" }),
      word("Dördüncü", { de: "stehlen", tr: "çalmak" }),
      word("Beşinci", { de: "die Gewalt", tr: "şiddet" }),
      word("Altıncı", { de: "der Täter", tr: "fail" }),
      word("Yedinci", { de: "der Dieb", tr: "hırsız" }),
      word("Son", { de: "sichtbar", tr: "görünür" }),
      { say: [tr("İlk kalıbımız olayı bildiriyor. Özne yok çünkü kimin yaptığı bilinmiyor; yardımcı fiil tekil kalıyor.")] },
      { say: [tr("Örnek:"), de("Bei uns wurde gestern Nacht eingebrochen."), tr("Tekrar edin:"), de("Bei uns wurde gestern Nacht eingebrochen")], expect: repeat("Bei uns wurde gestern Nacht eingebrochen") },
      { say: [tr("Sıra sende: 'Bilgisayar çalındı.'")], expect: produce("Der Computer wurde gestohlen", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Der Computer wurde gestohlen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız çoğul özneyle çalışıyor. Özne çoğul olunca yardımcı fiil de çoğula girer.")] },
      { say: [tr("Şimdi: 'İki pencere kırıldı.'")], expect: produce("Zwei Fenster wurden aufgebrochen", [tr("Çoğul özne, çoğul yardımcı fiil:"), de("Zwei Fenster wurden aufgebrochen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Täter wurde noch nicht finden."), tr("cümlesi doğru mu?")], expect: truefalse("Der Täter wurde noch nicht finden.", false, [tr("Edilgende asıl fiil ortaç hâlinde olmalı:"), de("Der Täter wurde noch nicht gefunden.")]) },
      { say: [tr("Son: 'Kapıda şiddet izi görünür değildi.'")], expect: produce("An der Tür waren keine Spuren von Gewalt sichtbar", [tr("Yer tümleci başta, fiil ikinci sırada:"), de("An der Tür waren keine Spuren von Gewalt sichtbar."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi polise olayı bildireceksin.")] },
    ],
    roleplay: {
      scene: "Eve döndüğünde kapının zorlandığını gördün. Polise durumu bildiriyor, ne çalındığını sayıyor ve ne zaman fark ettiğini anlatıyorsun.",
      partner: "tutanak tutan, sırayla soru soran bir polis memuru",
      opening: "Guten Tag. Bitte schildern Sie mir genau — wann haben Sie es bemerkt?",
      openingTr: "İyi günler. Lütfen tam olarak anlatın — ne zaman fark ettiniz?",
      goal: "Olay bildirilmiş, çalınanlar sayılmış ve tutanak için gerekli ayrıntılar verilmiş olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-grafik-lesen",
    icon: "chart",
    level: "B1",
    course: "de",
    title: "Was zeigt die Grafik?",
    titleTr: "Görseli okumak",
    summary: "Bir görseli ilgi cümleleriyle tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Nominativ",
    vocab: [
      { de: "die Grafik", tr: "grafik" },
      { de: "die Zeichnung", tr: "çizim" },
      { de: "die Abbildung", tr: "şekil" },
      { de: "die Darstellung", tr: "gösterim" },
      { de: "das Symbol", tr: "sembol" },
      { de: "das Kreuz", tr: "çarpı işareti" },
      { de: "vergrößern", tr: "büyütmek" },
      { de: "die Zeile", tr: "satır" },
    ],
    patterns: [
      { de: "die Grafik, die … zeigt", tr: "görseli tanımlayan ilgi cümlesi" },
      { de: "Das Symbol, das oben steht, …", tr: "görseldeki bir ögeyi tanımlar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir görseli anlatacağız. Sunumda ve sınavda en çok istenen beceri bu: neyin ne olduğunu tek cümlede söylemek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tanımlanan şey yan cümlenin öznesi olduğunda ilgi zamiri yalın hâlde kalır ve tanımlanan adın cinsiyetine uyar. Önce kelimeler.")] },
      word("İlk", { de: "die Grafik", tr: "grafik" }),
      word("İkinci", { de: "die Zeichnung", tr: "çizim" }),
      word("Üçüncü", { de: "die Abbildung", tr: "şekil" }, "kitapta numaralanmış görsel"),
      word("Dördüncü", { de: "die Darstellung", tr: "gösterim" }),
      word("Beşinci", { de: "das Symbol", tr: "sembol" }),
      word("Altıncı", { de: "das Kreuz", tr: "çarpı işareti" }),
      word("Yedinci", { de: "vergrößern", tr: "büyütmek" }),
      word("Son", { de: "die Zeile", tr: "satır" }),
      { say: [tr("İlk kalıbımız görseli tanımlıyor. İlgi zamiri tanımlanan adın cinsiyetini alıyor, fiil yan cümlenin sonuna gidiyor.")] },
      { say: [tr("Örnek:"), de("Das ist die Grafik, die den Verbrauch zeigt."), tr("Tekrar edin:"), de("Das ist die Grafik, die den Verbrauch zeigt")], expect: repeat("Das ist die Grafik, die den Verbrauch zeigt") },
      { say: [tr("Sıra sende: 'Bu, her şeyi açıklayan çizim.'")], expect: produce("Das ist die Zeichnung, die alles erklärt", [tr("Dişil adda ilgi zamiri de dişil, fiil sonda:"), de("Das ist die Zeichnung, die alles erklärt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız görseldeki bir ögeyi tanımlıyor. Nötr adda zamir de nötr olur.")] },
      { say: [tr("Şimdi: 'Yukarıda duran sembol tehlikeyi gösteriyor.'")], expect: produce("Das Symbol, das oben steht, zeigt die Gefahr", [tr("İlgi cümlesi araya giriyor, ana cümlenin fiili ondan sonra:"), de("Das Symbol, das oben steht, zeigt die Gefahr."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist die Abbildung, das die Zahlen zeigt."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist die Abbildung, das die Zahlen zeigt.", false, [tr("İlgi zamiri tanımlanan adın cinsiyetine uyar, nesnesine değil:"), de("Das ist die Abbildung, die die Zahlen zeigt.")]) },
      { say: [tr("Son: 'Son satırdaki çarpıyı büyütebilir misiniz?'")], expect: produce("Können Sie das Kreuz in der letzten Zeile vergrößern", [tr("Modal fiil başta, mastar sonda:"), de("Können Sie das Kreuz in der letzten Zeile vergrößern?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir toplantıda görseli anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Küçük bir toplantıda bir görsel sunuyorsun. Neyin ne olduğunu ilgi cümleleriyle tanımlıyor ve soruları yanıtlıyorsun.",
      partner: "görseli uzaktan göremeyen, ayrıntı soran bir katılımcı",
      opening: "Entschuldigung, ich sehe das von hier nicht so gut — was zeigt die Grafik denn genau?",
      openingTr: "Affedersiniz, buradan iyi göremiyorum — grafik tam olarak neyi gösteriyor?",
      goal: "Görselin ne gösterdiği anlatılmış, en az iki öge tanımlanmış ve bir soru yanıtlanmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-alte-technik",
    icon: "clock",
    level: "B1",
    course: "de",
    title: "Früher war alles anders",
    titleTr: "Eski teknoloji",
    summary: "Eski ve yeni teknolojiyi karşılaştırmayı öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "die Kassette", tr: "kaset" },
      { de: "der Sender", tr: "kanal / verici" },
      { de: "senden", tr: "yayınlamak" },
      { de: "das Studio", tr: "stüdyo" },
      { de: "der Hörer", tr: "dinleyici" },
      { de: "vorläufig", tr: "şimdilik" },
      { de: "mittlerweile", tr: "bu arada" },
      { de: "umgekehrt", tr: "tersine" },
    ],
    patterns: [
      { de: "Früher war … langsamer als heute.", tr: "eskiyle bugünü karşılaştırır" },
      { de: "Mittlerweile ist es umgekehrt.", tr: "durumun tersine döndüğünü söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün eski teknolojiyi konuşacağız: kaset, radyo, ilk bilgisayarlar. Böyle konuşmalar hep karşılaştırmadır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karşılaştırma sıfata ek getirir; durumun tersine döndüğünü söylemek için ayrı bir zarf kullanılır. Önce kelimeler.")] },
      word("İlk", { de: "die Kassette", tr: "kaset" }),
      word("İkinci", { de: "der Sender", tr: "kanal / verici" }),
      word("Üçüncü", { de: "senden", tr: "yayınlamak" }),
      word("Dördüncü", { de: "das Studio", tr: "stüdyo" }),
      word("Beşinci", { de: "der Hörer", tr: "dinleyici" }, "aynı sözcük telefon ahizesi anlamına da gelir"),
      word("Altıncı", { de: "vorläufig", tr: "şimdilik" }),
      word("Yedinci", { de: "mittlerweile", tr: "bu arada" }),
      word("Son", { de: "umgekehrt", tr: "tersine" }),
      { say: [tr("İlk kalıbımız eskiyi bugünle karşılaştırıyor: zaman zarfı, sıfatın karşılaştırma biçimi ve kıyas sözcüğü.")] },
      { say: [tr("Örnek:"), de("Früher war die Technik langsamer als heute."), tr("Tekrar edin:"), de("Früher war die Technik langsamer als heute")], expect: repeat("Früher war die Technik langsamer als heute") },
      { say: [tr("Sıra sende: 'Kaset bugünkü kadar pratik değildi.'")], expect: produce("Die Kassette war nicht so praktisch wie heute", [tr("Eşitlik karşılaştırmasında başka bir kıyas sözcüğü kullanılır:"), de("Die Kassette war nicht so praktisch wie heute."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız değişimi söylüyor: bir zaman zarfı ve tersine anlamına gelen sözcük. Cümle zarfla başladığı için fiil ikinci sıraya geçiyor.")] },
      { say: [tr("Şimdi: 'Bu arada durum tam tersine döndü.'")], expect: produce("Mittlerweile ist es genau umgekehrt", [tr("Zarf başta, fiil ikinci sırada:"), de("Mittlerweile ist es genau umgekehrt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Sender sendet mehr oft als früher."), tr("cümlesi doğru mu?")], expect: truefalse("Der Sender sendet mehr oft als früher.", false, [tr("Bu zarfın karşılaştırma biçimi düzensizdir ve ayrı bir sözcükle kurulur:"), de("Der Sender sendet öfter als früher.")]) },
      { say: [tr("Son: 'Şimdilik eski cihaz stüdyoda kalıyor.'")], expect: produce("Vorläufig bleibt das alte Gerät im Studio", [tr("Zarf başta, fiil ikinci sırada:"), de("Vorläufig bleibt das alte Gerät im Studio."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir arkadaşınla eski ve yeni teknolojiyi karşılaştıracaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla eski teknolojiyi konuşuyorsunuz: kaset, radyo, ilk telefonlar. Neyin daha iyi neyin daha kötü olduğunu karşılaştırıyorsunuz.",
      partner: "eskiye özlem duyan, her yeniliğe şüpheyle bakan bir arkadaş",
      opening: "Ich habe gestern eine alte Kassette gefunden — weißt du noch, wie das war?",
      openingTr: "Dün eski bir kaset buldum — nasıl olduğunu hatırlıyor musun?",
      goal: "En az üç karşılaştırma yapılmış ve neyin gerçekten iyileştiği konusunda bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-reparieren-lassen",
    icon: "repair",
    level: "B1",
    course: "de",
    title: "Reparieren lassen",
    titleTr: "Tamire vermek",
    summary: "Niyeti ve tavsiyeyi mastar öbeğiyle söylemeyi öğretir.",
    minutes: 10,
    focusId: "Infinitiv-zu",
    vocab: [
      { de: "der Kopierer", tr: "fotokopi makinesi" },
      { de: "die Klingel", tr: "zil" },
      { de: "klingeln", tr: "çalmak (zil)" },
      { de: "das Laufwerk", tr: "disk sürücüsü" },
      { de: "einstellen", tr: "ayarlamak" },
      { de: "schalten", tr: "geçirmek / ayarlamak" },
      { de: "testen", tr: "denemek" },
      { de: "nützen", tr: "işe yaramak" },
    ],
    patterns: [
      { de: "Ich habe vor, … zu …", tr: "niyetini söyler" },
      { de: "Es nützt nichts, … zu …", tr: "bir şeyin işe yaramadığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bir şey bozuldu ve tamire mi vereceksin yoksa yenisini mi alacaksın karar vereceksin. Bugün niyet ve tavsiye kalıpları var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Mastar öbeğinde küçük bir edat ve mastar cümlenin sonunda durur; nesne mastardan önce gelir. Önce kelimeler.")] },
      word("İlk", { de: "der Kopierer", tr: "fotokopi makinesi" }),
      word("İkinci", { de: "die Klingel", tr: "zil" }),
      word("Üçüncü", { de: "klingeln", tr: "çalmak (zil)" }),
      word("Dördüncü", { de: "das Laufwerk", tr: "disk sürücüsü" }),
      word("Beşinci", { de: "einstellen", tr: "ayarlamak" }),
      word("Altıncı", { de: "schalten", tr: "geçirmek / ayarlamak" }),
      word("Yedinci", { de: "testen", tr: "denemek" }),
      word("Son", { de: "nützen", tr: "işe yaramak" }),
      { say: [tr("İlk kalıbımız niyeti söylüyor: ayrılabilen bir fiil ve mastar öbeği. Önek ana cümlenin sonunda kalıyor.")] },
      { say: [tr("Örnek:"), de("Ich habe vor, den Kopierer reparieren zu lassen."), tr("Tekrar edin:"), de("Ich habe vor, den Kopierer reparieren zu lassen")], expect: repeat("Ich habe vor, den Kopierer reparieren zu lassen") },
      { say: [tr("Sıra sende: 'Zili yenilemeyi planlıyorum.'")], expect: produce("Ich habe vor, die Klingel zu erneuern", [tr("Nesne mastardan önce, mastar sonda:"), de("Ich habe vor, die Klingel zu erneuern."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız bir şeyin işe yaramadığını söylüyor: kişisiz bir fiil ve mastar öbeği. Tartışmayı bitiren cümledir.")] },
      { say: [tr("Şimdi: 'Tekrar denemek işe yaramıyor.'")], expect: produce("Es nützt nichts, es noch einmal zu testen", [tr("Kişisiz özne, mastar sonda:"), de("Es nützt nichts, es noch einmal zu testen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich habe vor, zu einstellen das Gerät neu."), tr("cümlesi doğru mu?")], expect: truefalse("Ich habe vor, zu einstellen das Gerät neu.", false, [tr("Ayrılabilen fiilde edat önek ile kök arasına girer ve mastar en sona gider:"), de("Ich habe vor, das Gerät neu einzustellen.")]) },
      { say: [tr("Son: 'Sürücüyü değiştirmeyi denemek daha ucuz.'")], expect: produce("Es ist billiger, das Laufwerk zu tauschen", [tr("Sıfat artı mastar öbeği:"), de("Es ist billiger, das Laufwerk zu tauschen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir tamirciyle konuşacak ve tamir mi yenisi mi olduğuna karar vereceksin.")] },
    ],
    roleplay: {
      scene: "Bozulan cihazını tamirciye götürdün. Ne olduğunu anlatıyor, fiyatı soruyor ve tamir mi yenisini almak mı daha mantıklı diye karar veriyorsun.",
      partner: "dürüst ama işini de kaybetmek istemeyen bir tamirci",
      opening: "Zeigen Sie mal her. Seit wann macht das Gerät denn Probleme?",
      openingTr: "Bir bakayım. Cihaz ne zamandır sorun çıkarıyor?",
      goal: "Arıza anlatılmış, fiyat sorulmuş ve tamir ya da yenisi konusunda gerekçeli karar verilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-technik-diskussion",
    icon: "media",
    level: "B1",
    course: "de",
    title: "Macht Technik uns freier?",
    titleTr: "Teknoloji tartışması",
    summary: "Teknolojinin iki yanını ikili bağlaçlarla dengeli tartışmayı öğretir.",
    minutes: 11,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "die Technologie", tr: "teknoloji" },
      { de: "die Medien", tr: "medya" },
      { de: "die Erfindung", tr: "icat" },
      { de: "beeinflussen", tr: "etkilemek" },
      { de: "abhängig", tr: "bağımlı" },
      { de: "süchtig", tr: "müptela" },
      { de: "kritisch", tr: "eleştirel" },
      { de: "unterschiedlich", tr: "farklı" },
    ],
    patterns: [
      { de: "sowohl … als auch …", tr: "iki şeyi birden kapsar" },
      { de: "nicht nur …, sondern auch …", tr: "ikincisini öne çıkararak ekler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi: teknoloji bizi özgürleştiriyor mu, bağımlı mı kılıyor? Böyle sorularda tek yanlı cevap zayıf durur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkili bağlaçlar bir görüşün iki yanını aynı cümlede tutar. İkinci parçası sabittir ve değiştirilemez. Önce kelimeler.")] },
      word("İlk", { de: "die Technologie", tr: "teknoloji" }),
      word("İkinci", { de: "die Medien", tr: "medya" }, "hep çoğul kullanılır"),
      word("Üçüncü", { de: "die Erfindung", tr: "icat" }),
      word("Dördüncü", { de: "beeinflussen", tr: "etkilemek" }),
      word("Beşinci", { de: "abhängig", tr: "bağımlı" }),
      word("Altıncı", { de: "süchtig", tr: "müptela" }),
      word("Yedinci", { de: "kritisch", tr: "eleştirel" }),
      word("Son", { de: "unterschiedlich", tr: "farklı" }),
      { say: [tr("İlk kalıbımız iki şeyi birden kapsıyor: hem o hem bu. İki parça da cümlede görünmek zorunda.")] },
      { say: [tr("Örnek:"), de("Die Technologie hilft sowohl bei der Arbeit als auch zu Hause."), tr("Tekrar edin:"), de("Die Technologie hilft sowohl bei der Arbeit als auch zu Hause")], expect: repeat("Die Technologie hilft sowohl bei der Arbeit als auch zu Hause") },
      { say: [tr("Sıra sende: 'Medya sadece bilgilendirmiyor, aynı zamanda etkiliyor.'")], expect: produce("Die Medien informieren nicht nur, sondern beeinflussen auch", [tr("İkinci parçadan sonra fiil hemen geliyor:"), de("Die Medien informieren nicht nur, sondern beeinflussen auch."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız ikinciyi öne çıkarıyor. İkinci parçası özel bir bağlaçtır ve sıradan bir zıtlık bağlacıyla değiştirilemez.")] },
      { say: [tr("Şimdi: 'Bu icat yalnız hızlı değil, aynı zamanda ucuz.'")], expect: produce("Diese Erfindung ist nicht nur schnell, sondern auch billig", [tr("İkinci parça sabittir:"), de("Diese Erfindung ist nicht nur schnell, sondern auch billig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Viele sind sowohl abhängig aber auch süchtig."), tr("cümlesi doğru mu?")], expect: truefalse("Viele sind sowohl abhängig aber auch süchtig.", false, [tr("Bu ikili bağlacın ikinci parçası sabittir ve zıtlık bağlacıyla değiştirilemez:"), de("Viele sind sowohl abhängig als auch süchtig.")]) },
      { say: [tr("Son: 'İnsanlar bunu çok farklı görüyor, ben eleştirel bakıyorum.'")], expect: produce("Die Menschen sehen das sehr unterschiedlich, ich bin kritisch", [tr("İki ana cümle, ikisinde de fiil ikinci sırada:"), de("Die Menschen sehen das sehr unterschiedlich, ich bin kritisch."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi teknolojinin iki yanını tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla teknolojinin hayatınızı nasıl değiştirdiğini tartışıyorsunuz: neyi kolaylaştırdı, neyi zorlaştırdı, nerede bağımlılık başlıyor.",
      partner: "teknolojiye çok bağlı olduğunu kabul eden ama savunan bir arkadaş",
      opening: "Ohne mein Handy kann ich nicht mehr — findest du das eigentlich schlimm?",
      openingTr: "Telefonum olmadan yapamıyorum — sence bu kötü bir şey mi?",
      goal: "En az üç konuda iki yan da söylenmiş ve kişisel bir sonuca varılmış olur.",
      minTurns: 9,
    },
  },
];
