import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B1 · Modül 4 — İlgi cümleleri (031–040).
 *
 * Modülün derdi tek: TANIMLAMAK. Türkçede tanım fiilden önce gelen bir
 * sıfat-fiildir ("yanımda oturan kadın"); Almancada isimden SONRA gelen bir
 * yan cümledir ("die Frau, die neben mir sitzt"). Türkçe konuşanın zorluğu
 * kelime değil bu yön farkı — ve arkasından gelen iki karar: zamirin hâli
 * (der/den/dem) ve fiilin sona gitmesi.
 *
 * Sıra hâlden hâle: yalın (031), belirtme (032), yönelme (033), edatlı
 * (034). Kalan altı ders aynı yapıyı gerçek işlerde çalıştırıyor — hayal
 * ev, insan tarifi, nesne tarifi, mekân, kayıp eşya, yemek önerisi — çünkü
 * ilgi cümlesi bir konu değil, bir alışkanlık.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB1B04: Lesson[] = [
  {
    id: "de-b1-relativ-nom",
    icon: "greet",
    level: "B1",
    course: "de",
    title: "Der Mann, der lacht",
    titleTr: "İlgi cümlesi: yalın hâl",
    summary: "Bir kişiyi 'kim ne yapıyor' diyerek tanımlamayı öğretir: der, die, das.",
    minutes: 10,
    focusId: "Relativsatz-Nominativ",
    vocab: [
      { de: "zuverlässig", tr: "güvenilir" },
      { de: "neugierig", tr: "meraklı" },
      { de: "sympathisch", tr: "sevimli" },
      { de: "der Eindruck", tr: "izlenim" },
      { de: "beeindrucken", tr: "etkilemek" },
    ],
    patterns: [
      { de: "Der Mann, der …", tr: "kişiyi yaptığı işle tanımlar; fiil yan cümlenin sonuna gider" },
      { de: "Die Frau, die … / Das Kind, das …", tr: "dişil ve nötr yalın ilgi zamiri" },
      { de: "Menschen, die …", tr: "çoğulda ilgi zamiri die" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün insanları tarif etmeyi öğreneceğiz: 'yanımda oturan kadın', 'çok soru soran çocuk'. Almanca bunu bir yan cümleyle yapıyor ve o cümle ismin ARKASINDAN geliyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Türkçede tanım isimden önce gelir: gülen adam. Almancada isimden sonra gelir ve virgülle ayrılır:"), de("der Mann, der lacht"), tr("Önce kelimeler.")] },
      word("İlk", { de: "zuverlässig", tr: "güvenilir" }),
      word("İkinci", { de: "neugierig", tr: "meraklı" }),
      word("Üçüncü", { de: "sympathisch", tr: "sevimli" }),
      word("Dördüncü", { de: "der Eindruck", tr: "izlenim" }),
      word("Son", { de: "beeindrucken", tr: "etkilemek" }),
      { say: [tr("İlk kalıp:"), de("Der Mann, der …"), tr("Buradaki ikinci kelime artikelin aynısı: eril der, dişil die, nötr das, çoğul die. Ve dikkat: fiil yan cümlenin en sonuna gider.")] },
      { say: [tr("Örnek:"), de("Der Mann, der dort steht, ist mein Chef."), tr("Lütfen tekrar edin:"), de("Der Mann, der dort steht, ist mein Chef")], expect: repeat("Der Mann, der dort steht, ist mein Chef") },
      { say: [tr("Sıra sende: 'Yanımda oturan kadın çok sevimli.'")], expect: produce("Die Frau, die neben mir sitzt, ist sehr sympathisch", [tr("Dişilde zamir die, fiil sona:"), de("Die Frau, die neben mir sitzt, ist sehr sympathisch."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi nötr bir isimle: 'Çok soru soran çocuk meraklı.'")], expect: produce("Das Kind, das viele Fragen stellt, ist neugierig", [tr("Nötrde zamir das; 'Fragen stellen' kalıbının fiili sona gider:"), de("Das Kind, das viele Fragen stellt, ist neugierig."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Çok güvenilir bir meslektaşım var.'")], expect: produce("Ich habe einen Kollegen, der sehr zuverlässig ist", [tr("Tanımlanan kelime eril olduğu için zamir der; 'ist' en sonda:"), de("Ich habe einen Kollegen, der sehr zuverlässig ist."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Frau, die spricht Deutsch, ist meine Lehrerin."), tr("cümlesi doğru mu?")], expect: truefalse("Die Frau, die spricht Deutsch, ist meine Lehrerin.", false, [tr("Yan cümlede fiil en sona gider:"), de("Die Frau, die Deutsch spricht, ist meine Lehrerin.")]) },
      { say: [tr("Son: 'Beni etkileyen bir konuşmaydı.'")], expect: produce("Es war eine Rede, die mich beeindruckt hat", [tr("Perfekt'te yardımcı fiil de sona gider:"), de("Es war eine Rede, die mich beeindruckt hat."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir tanıdığınla iş yerindeki insanları konuşacaksın; her kişiyi bir ilgi cümlesiyle tarif et.")] },
    ],
    roleplay: {
      scene: "Yeni bir iş yerindesin ve bir tanıdığın ekibi soruyor. Her meslektaşını 'der/die/das' ile kurulmuş bir ilgi cümlesiyle tanıt: kim ne yapıyor, nasıl biri.",
      partner: "meraklı, sohbeti seven bir tanıdık",
      opening: "Und, wie sind die Leute in deinem neuen Team? Wer ist dir am ersten Tag aufgefallen?",
      openingTr: "Ee, yeni ekibindeki insanlar nasıl? İlk gün kim dikkatini çekti?",
      goal: "Ekipteki en az üç kişi tanıtılmış ve tanıdığın kimin kim olduğunu ayırt edebilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-relativ-akk",
    icon: "film",
    level: "B1",
    course: "de",
    title: "Der Film, den ich liebe",
    titleTr: "İlgi cümlesi: belirtme hâli",
    summary: "Tanımlanan şey yan cümlenin NESNESİ olduğunda der'in den'e döndüğünü öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Akkusativ",
    vocab: [
      { de: "der Roman", tr: "roman" },
      { de: "der Regisseur", tr: "yönetmen" },
      { de: "der Hauptdarsteller", tr: "başrol oyuncusu" },
      { de: "drehen", tr: "çekmek (film)" },
      { de: "berühren", tr: "duygulandırmak" },
    ],
    patterns: [
      { de: "…, den ich …", tr: "tanımlanan şey nesneyse eril zamir den olur" },
      { de: "…, die ich … / …, das ich …", tr: "dişil ve nötrde biçim değişmez" },
    ],
    lecture: [
      { say: [tr("Merhaba! Geçen ders 'gülen adam' vardı: tanımlanan kişi yan cümlenin ÖZNESİYDİ. Bugün tersi: 'sevdiğim film' — film seven değil, sevilen. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İyi haber: dört biçimden yalnızca biri değişiyor. Eril nesnede der yerine den denir; dişil, nötr ve çoğulda hiçbir şey değişmez. Önce kelimeler.")] },
      word("İlk", { de: "der Roman", tr: "roman" }),
      word("İkinci", { de: "der Regisseur", tr: "yönetmen" }),
      word("Üçüncü", { de: "der Hauptdarsteller", tr: "başrol oyuncusu" }),
      word("Dördüncü", { de: "drehen", tr: "çekmek (film)" }),
      word("Son", { de: "berühren", tr: "duygulandırmak" }),
      { say: [tr("Kalıbımız:"), de("Der Film, den ich liebe"), tr("Sorusu şu: yan cümlede o şey ne yapıyor, yoksa ona ne yapılıyor? Yapılıyorsa nesnedir ve erilde den gelir.")] },
      { say: [tr("Örnek:"), de("Der Film, den ich gestern gesehen habe, war großartig."), tr("Tekrar edin:"), de("Der Film, den ich gestern gesehen habe, war großartig")], expect: repeat("Der Film, den ich gestern gesehen habe, war großartig") },
      { say: [tr("Sıra sende: 'Dün okuduğum roman çok güzeldi.'")], expect: produce("Der Roman, den ich gestern gelesen habe, war sehr schön", [tr("Roman eril ve nesne → den; Perfekt sona:"), de("Der Roman, den ich gestern gelesen habe, war sehr schön."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi dişil bir isimle: 'Sevdiğim dizi bitti.'")], expect: produce("Die Serie, die ich liebe, ist zu Ende", [tr("Dişilde nesne olsa da zamir die kalır:"), de("Die Serie, die ich liebe, ist zu Ende."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Herkesin tanıdığı başrol oyuncusu geldi.'")], expect: produce("Der Hauptdarsteller, den jeder kennt, ist gekommen", [tr("Tanıyan 'jeder', tanınan başrol → nesne, yani den:"), de("Der Hauptdarsteller, den jeder kennt, ist gekommen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Roman, der ich gelesen habe, war lang."), tr("cümlesi doğru mu?")], expect: truefalse("Der Roman, der ich gelesen habe, war lang.", false, [tr("Roman burada okunan şey, yani nesne; erilde nesne zamiri den:"), de("Der Roman, den ich gelesen habe, war lang.")]) },
      { say: [tr("Son: 'Beni duygulandıran bir sahneydi.'")], expect: produce("Es war eine Szene, die mich berührt hat", [tr("Sahne duygulandıran taraf, yani özne; dişilde die:"), de("Es war eine Szene, die mich berührt hat."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşına film ve dizi önereceksin; her önerini bir ilgi cümlesiyle tanımla.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın akşam için film arıyor. Beğendiğin filmleri ve dizileri 'den/die/das' ile kurulmuş ilgi cümleleriyle öner ve neden sevdiğini söyle.",
      partner: "seçici ama meraklı bir arkadaş",
      opening: "Ich brauche einen Film für heute Abend. Was hast du zuletzt gesehen, das sich wirklich gelohnt hat?",
      openingTr: "Bu akşam için bir filme ihtiyacım var. Son zamanlarda izlediğin, gerçekten değen bir şey var mı?",
      goal: "En az iki yapım önerilmiş ve arkadaşın akşam ne izleyeceğine karar vermiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-relativ-dativ",
    icon: "handshake",
    level: "B1",
    course: "de",
    title: "Der Freund, dem ich vertraue",
    titleTr: "İlgi cümlesi: yönelme hâli",
    summary: "Yönelme isteyen fiillerde ilgi zamirinin dem, der ve denen olduğunu öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Dativ",
    vocab: [
      { de: "vertrauen", tr: "güvenmek" },
      { de: "zuhören", tr: "kulak vermek" },
      { de: "der Rat", tr: "öğüt" },
      { de: "begegnen", tr: "rastlamak" },
      { de: "verzeihen", tr: "affetmek" },
    ],
    patterns: [
      { de: "…, dem ich …", tr: "eril ve nötrde yönelme zamiri dem" },
      { de: "…, der ich … / …, denen ich …", tr: "dişilde der, çoğulda denen" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün üçüncü hâl: yönelme. Bazı fiiller kendinden sonra yönelme ister — güvenmek, yardım etmek, kulak vermek. İlgi cümlesinde de aynısı olur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Hangi zamiri seçeceğini fiil söyler. Yönelme isteyen bir fiil varsa erilde ve nötrde dem, dişilde der, çoğulda denen gelir. Önce kelimeler.")] },
      word("İlk", { de: "vertrauen", tr: "güvenmek" }),
      word("İkinci", { de: "zuhören", tr: "kulak vermek" }),
      word("Üçüncü", { de: "der Rat", tr: "öğüt" }),
      word("Dördüncü", { de: "begegnen", tr: "rastlamak" }),
      word("Son", { de: "verzeihen", tr: "affetmek" }),
      { say: [tr("Kalıbımız:"), de("Der Freund, dem ich vertraue"), tr("Dikkat: çoğulda zamir denen, yani sonuna bir n eklenir. Bu, yönelme çoğulun genel kuralıyla aynı.")] },
      { say: [tr("Örnek:"), de("Der Freund, dem ich vertraue, wohnt in Berlin."), tr("Tekrar edin:"), de("Der Freund, dem ich vertraue, wohnt in Berlin")], expect: repeat("Der Freund, dem ich vertraue, wohnt in Berlin") },
      { say: [tr("Sıra sende: 'Yardım ettiğim kadın teşekkür etti.'")], expect: produce("Die Frau, der ich geholfen habe, hat sich bedankt", [tr("Yardım etmek yönelme ister; dişilde yönelme zamiri der:"), de("Die Frau, der ich geholfen habe, hat sich bedankt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Dün rastladığım kadın komşumuz.'")], expect: produce("Die Frau, der ich gestern begegnet bin, ist unsere Nachbarin", [tr("Rastlamak da yönelme ister ve Perfekt'i sein ile kurulur:"), de("Die Frau, der ich gestern begegnet bin, ist unsere Nachbarin."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kulak verdiğim çocuk çok mutlu oldu.'")], expect: produce("Das Kind, dem ich zugehört habe, war sehr glücklich", [tr("Nötrde yönelme zamiri de dem olur:"), de("Das Kind, dem ich zugehört habe, war sehr glücklich."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Mann, den ich vertraue, ist mein Bruder."), tr("cümlesi doğru mu?")], expect: truefalse("Der Mann, den ich vertraue, ist mein Bruder.", false, [de("vertrauen"), tr("yönelme ister, belirtme değil:"), de("Der Mann, dem ich vertraue, ist mein Bruder.")]) },
      { say: [tr("Son: 'Güvendiğim çok az arkadaşım var.' Çoğul zamiri unutma.")], expect: produce("Ich habe nur wenige Freunde, denen ich vertraue", [tr("Çoğulda yönelme zamiri denen:"), de("Ich habe nur wenige Freunde, denen ich vertraue."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla güven üzerine konuşacaksın: kime güveniyorsun, kimin öğüdünü dinliyorsun.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla güven üzerine konuşuyorsun: kime güvendiğini, kimin öğüdünü dinlediğini, kime her şeyi anlattığını 'dem, der, denen' ile kurulmuş ilgi cümleleriyle anlat.",
      partner: "açık sözlü, düşündüren bir arkadaş",
      opening: "Mal ehrlich: Gibt es jemanden, dem du wirklich alles erzählen kannst?",
      openingTr: "Açık konuşalım: Gerçekten her şeyi anlatabildiğin biri var mı?",
      goal: "Kime güvendiğin ve kimin öğüdünü dinlediğin anlatılmış, arkadaşın da kendi cevabını vermiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-relativ-praep",
    icon: "city",
    level: "B1",
    course: "de",
    title: "Die Stadt, in der ich lebe",
    titleTr: "Edatlı ilgi cümlesi",
    summary: "İlgi zamirinin önüne edat geldiğinde hâli edatın belirlediğini öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Präposition",
    vocab: [
      { de: "die Gegend", tr: "bölge" },
      { de: "der Bezirk", tr: "semt" },
      { de: "aufwachsen", tr: "büyümek (yetişmek)" },
      { de: "sich wohlfühlen", tr: "kendini iyi hissetmek" },
      { de: "die Umgebung", tr: "çevre" },
    ],
    patterns: [
      { de: "…, in der ich …", tr: "edat zamirin önüne geçer; hâli edat seçer" },
      { de: "…, mit dem ich … / …, über das wir …", tr: "mit yönelme, über belirtme ister" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ilgi cümlesinin en işlek hâli: içinde bir edat olanı. 'İçinde yaşadığım şehir', 'birlikte çalıştığım meslektaş', 'hakkında konuştuğumuz konu'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şaşırtıcı derecede basit: edat en öne gider, zamir hemen arkasına, hâli de edat söyler. Yer bildiren bir edatta yönelme, hareket ya da konu bildirende belirtme. Önce kelimeler.")] },
      word("İlk", { de: "die Gegend", tr: "bölge" }),
      word("İkinci", { de: "der Bezirk", tr: "semt" }),
      word("Üçüncü", { de: "aufwachsen", tr: "büyümek (yetişmek)" }),
      word("Dördüncü", { de: "sich wohlfühlen", tr: "kendini iyi hissetmek" }),
      word("Son", { de: "die Umgebung", tr: "çevre" }),
      { say: [tr("Kalıbımız:"), de("Die Stadt, in der ich lebe"), tr("Türkçede edat yok, ek var: 'yaşadığım şehir'. Almancada edat görünür ve en başa geçer.")] },
      { say: [tr("Örnek:"), de("Die Stadt, in der ich lebe, ist nicht groß."), tr("Tekrar edin:"), de("Die Stadt, in der ich lebe, ist nicht groß")], expect: repeat("Die Stadt, in der ich lebe, ist nicht groß") },
      { say: [tr("Sıra sende: 'Büyüdüğüm semt bugün bambaşka.'")], expect: produce("Der Bezirk, in dem ich aufgewachsen bin, ist heute anders", [tr("Semt eril, yer bildiriyor → in dem:"), de("Der Bezirk, in dem ich aufgewachsen bin, ist heute anders."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Birlikte çalıştığım meslektaş taşındı.'")], expect: produce("Der Kollege, mit dem ich arbeite, ist umgezogen", [de("mit"), tr("her zaman yönelme ister:"), de("Der Kollege, mit dem ich arbeite, ist umgezogen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Hakkında konuştuğumuz konu önemliydi.'")], expect: produce("Das Thema, über das wir gesprochen haben, war wichtig", [de("über"), tr("burada belirtme ister ve konu nötr:"), de("Das Thema, über das wir gesprochen haben, war wichtig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Stadt, in die ich wohne, ist klein."), tr("cümlesi doğru mu?")], expect: truefalse("Die Stadt, in die ich wohne, ist klein.", false, [de("wohnen"), tr("hareket değil yer bildirir, yani yönelme:"), de("Die Stadt, in der ich wohne, ist klein.")]) },
      { say: [tr("Son: 'Kendimi iyi hissettiğim bir bölge arıyorum.'")], expect: produce("Ich suche eine Gegend, in der ich mich wohlfühle", [tr("Dönüşlü fiil sonda, edat başta:"), de("Ich suche eine Gegend, in der ich mich wohlfühle."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada yeni taşınan birine mahalleni anlatacaksın: hangi semtte oturuyorsun, çevrede ne var.")] },
    ],
    roleplay: {
      scene: "Şehre yeni taşınan biri sana semtini soruyor. Oturduğun bölgeyi, büyüdüğün yeri ve çevredeki yerleri edatlı ilgi cümleleriyle anlat.",
      partner: "şehri hiç bilmeyen, her şeyi soran yeni bir komşu",
      opening: "Ich bin gerade hergezogen und kenne hier noch nichts. In welchem Bezirk wohnst du eigentlich?",
      openingTr: "Buraya yeni taşındım ve hiçbir yeri bilmiyorum. Sen hangi semtte oturuyorsun?",
      goal: "Oturduğun bölge, büyüdüğün yer ve çevredeki yerler tarif edilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-traumhaus",
    icon: "home",
    level: "B1",
    course: "de",
    title: "Das Haus, von dem ich träume",
    titleTr: "Hayalindeki evi tanımlama",
    summary: "Edatını fiilden alan ilgi cümleleriyle hayalleri tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Präposition",
    vocab: [
      { de: "träumen", tr: "hayalini kurmak" },
      { de: "die Terrasse", tr: "teras" },
      { de: "sich leisten", tr: "gücü yetmek" },
      { de: "der Kredit", tr: "kredi" },
      { de: "das Grundstück", tr: "arsa" },
    ],
    patterns: [
      { de: "…, von dem ich träume", tr: "edatı fiil belirler: träumen von" },
      { de: "…, auf der wir sitzen / …, für die ich spare", tr: "her fiil kendi edatını getirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Geçen ders edatı yer seçiyordu. Bugün edatı FİİL seçiyor. Örneğin"), de("träumen von"), tr("ya da"), de("sparen für"), tr("Fiili biliyorsan edatı da biliyorsun. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yüzden edatlı fiiller ezberlenirken edatıyla birlikte ezberlenir. İlgi cümlesinde o edat en başa geçer ve hâli belirler. Önce kelimeler.")] },
      word("İlk", { de: "träumen", tr: "hayalini kurmak" }),
      word("İkinci", { de: "die Terrasse", tr: "teras" }),
      word("Üçüncü", { de: "sich leisten", tr: "gücü yetmek" }),
      word("Dördüncü", { de: "der Kredit", tr: "kredi" }),
      word("Son", { de: "das Grundstück", tr: "arsa" }),
      { say: [tr("Kalıbımız:"), de("Das Haus, von dem ich träume"), tr("Fiil"), de("träumen von"), tr("olduğu için edat von, o da yönelme ister: von dem.")] },
      { say: [tr("Örnek:"), de("Das Haus, von dem ich träume, liegt am Meer."), tr("Tekrar edin:"), de("Das Haus, von dem ich träume, liegt am Meer")], expect: repeat("Das Haus, von dem ich träume, liegt am Meer") },
      { say: [tr("Sıra sende: 'Üzerinde oturduğumuz teras çok küçük.'")], expect: produce("Die Terrasse, auf der wir sitzen, ist sehr klein", [de("auf"), tr("yer bildirdiği için yönelme, teras dişil:"), de("Die Terrasse, auf der wir sitzen, ist sehr klein."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Para biriktirdiğim daire çok pahalı.'")], expect: produce("Die Wohnung, für die ich spare, ist sehr teuer", [de("für"), tr("belirtme ister:"), de("Die Wohnung, für die ich spare, ist sehr teuer."), tr("Tekrar dene.")]) },
      { say: [tr("Bir soru sor: 'Bahsettiğin arsa nerede?'")], expect: produce("Wo ist das Grundstück, von dem du gesprochen hast", [de("sprechen von"), tr("→ von dem; soru kelimesi en başta:"), de("Wo ist das Grundstück, von dem du gesprochen hast?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Haus, von das ich träume, hat einen Garten."), tr("cümlesi doğru mu?")], expect: truefalse("Das Haus, von das ich träume, hat einen Garten.", false, [de("von"), tr("yönelme ister, nötrde de dem olur:"), de("Das Haus, von dem ich träume, hat einen Garten.")]) },
      { say: [tr("Son: 'Gücümün yettiği bir kredi arıyorum.'")], expect: produce("Ich suche einen Kredit, den ich mir leisten kann", [tr("Burada kredi nesne, yani den; modal fiil sona:"), de("Ich suche einen Kredit, den ich mir leisten kann."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir emlakçıya hayalindeki evi tarif edeceksin: nasıl bir ev, nerede, bütçen ne.")] },
    ],
    roleplay: {
      scene: "Bir emlakçıyla oturuyorsun ve hayalindeki evi tarif ediyorsun: nasıl bir ev, hangi çevrede, bütçen ne. Tarifleri ilgi cümleleriyle kur.",
      partner: "gerçekçi sorular soran, biraz aceleci bir emlakçı",
      opening: "Erzählen Sie mir einfach mal: Was für ein Haus suchen Sie eigentlich, und wo soll es liegen?",
      openingTr: "Anlatın bakalım: Nasıl bir ev arıyorsunuz ve nerede olsun?",
      goal: "Hayalindeki evin özellikleri, çevresi ve bütçen netleşmiş; emlakçı bir öneri yapmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-menschen-beschreiben",
    icon: "star",
    level: "B1",
    course: "de",
    title: "Leute, die man nicht vergisst",
    titleTr: "İnsanları tarif etmek",
    summary: "jemand, niemand ve çoğul isimlerle ilgi cümlesi kurmayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Nominativ",
    vocab: [
      { de: "großzügig", tr: "cömert" },
      { de: "hilfsbereit", tr: "yardımsever" },
      { de: "humorvoll", tr: "esprili" },
      { de: "der Charakter", tr: "karakter" },
      { de: "prägen", tr: "iz bırakmak" },
    ],
    patterns: [
      { de: "Menschen, die …", tr: "çoğul isimde ilgi zamiri die" },
      { de: "jemand, der … / niemand, der …", tr: "belirsiz kişiye ilgi cümlesi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ilgi cümlesini insan tarifinde çalıştıracağız — ama bu kez belirli bir kişiyle değil, 'insanlar', 'biri', 'kimse' gibi belirsiz sözlerle. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural yine aynı: zamir tanımlanan kelimenin cinsine ve sayısına bakar. 'jemand' ve 'niemand' erildir, yani der; çoğul isimlerde die. Önce kelimeler.")] },
      word("İlk", { de: "großzügig", tr: "cömert" }),
      word("İkinci", { de: "hilfsbereit", tr: "yardımsever" }),
      word("Üçüncü", { de: "humorvoll", tr: "esprili" }),
      word("Dördüncü", { de: "der Charakter", tr: "karakter" }),
      word("Son", { de: "prägen", tr: "iz bırakmak" }),
      { say: [tr("Kalıbımız:"), de("Menschen, die …"), tr("Çoğulda zamir die ve fiil de çoğul çekilir. Belirsiz kişide ise"), de("jemand, der …")] },
      { say: [tr("Örnek:"), de("Ich mag Menschen, die anderen gern helfen."), tr("Tekrar edin:"), de("Ich mag Menschen, die anderen gern helfen")], expect: repeat("Ich mag Menschen, die anderen gern helfen") },
      { say: [tr("Sıra sende: 'Espri anlayışı olan birini arıyorum.'")], expect: produce("Ich suche jemanden, der Humor hat", [de("jemand"), tr("belirtme hâlinde jemanden olur, zamir yine der:"), de("Ich suche jemanden, der Humor hat."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Onun kadar cömert kimse yok.'")], expect: produce("Es gibt niemanden, der so großzügig ist", [de("Es gibt"), tr("belirtme ister → niemanden; sonra zamir der:"), de("Es gibt niemanden, der so großzügig ist."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Anneannem beni şekillendiren bir insandı.'")], expect: produce("Meine Oma war ein Mensch, der mich geprägt hat", [tr("Tanımlanan kelime eril ve özne → der:"), de("Meine Oma war ein Mensch, der mich geprägt hat."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Leute, die viel reden, sagen oft wenig."), tr("cümlesi doğru mu?")], expect: truefalse("Leute, die viel reden, sagen oft wenig.", true, [tr("Doğru. Çoğulda zamir die, fiil yan cümlenin sonunda ve ana cümle virgülden sonra devam ediyor.")]) },
      { say: [tr("Son: 'Yardımsever meslektaşlar işi kolaylaştırır.' Cümleyi ilgi cümlesiyle kur.")], expect: produce("Kollegen, die hilfsbereit sind, machen die Arbeit leichter", [tr("Sıfatı ilgi cümlesine çevir: die hilfsbereit sind:"), de("Kollegen, die hilfsbereit sind, machen die Arbeit leichter."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada hayatında iz bırakan insanları anlatacaksın: kimler, nasıl insanlardı.")] },
    ],
    roleplay: {
      scene: "Bir söyleşide sana hayatında iz bırakan insanlar soruluyor. Her kişiyi ilgi cümlesiyle tarif et: nasıl biriydi, ne yaptı, sana ne kattı.",
      partner: "sakin, dinlemeyi bilen bir söyleşici",
      opening: "Wenn Sie zurückblicken: Wer sind die Menschen, die Sie am meisten geprägt haben?",
      openingTr: "Geriye baktığınızda: Sizi en çok şekillendiren insanlar kimler?",
      goal: "Hayatında iz bırakan en az iki kişi tarif edilmiş ve sana ne kattıkları söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-gegenstand",
    icon: "tech",
    level: "B1",
    course: "de",
    title: "Das Ding, das alles kann",
    titleTr: "Nesne tarif etmek",
    summary: "Adını bilmediğin nesneyi ilgi cümlesiyle tarif etmeyi ve alles/etwas sonrası was kullanmayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Akkusativ",
    vocab: [
      { de: "das Gerät", tr: "cihaz" },
      { de: "die Fernbedienung", tr: "kumanda" },
      { de: "aufladen", tr: "şarj etmek" },
      { de: "erfinden", tr: "icat etmek" },
      { de: "ersetzen", tr: "yerini almak" },
    ],
    patterns: [
      { de: "ein Gerät, das …", tr: "nesneyi işleviyle tanımlar" },
      { de: "alles, was … / etwas, was …", tr: "alles, etwas ve nichts sonrası was gelir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün çok işine yarayacak bir beceri: adını bilmediğin bir şeyi tarif etmek. 'Şu şey var ya, şununla açtığın…' Almancada bu bir ilgi cümlesidir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de küçük bir istisna öğreneceğiz: alles, etwas ve nichts kelimelerinden sonra ilgi zamiri das değil was olur. Önce kelimeler.")] },
      word("İlk", { de: "das Gerät", tr: "cihaz" }),
      word("İkinci", { de: "die Fernbedienung", tr: "kumanda" }),
      word("Üçüncü", { de: "aufladen", tr: "şarj etmek" }),
      word("Dördüncü", { de: "erfinden", tr: "icat etmek" }),
      word("Son", { de: "ersetzen", tr: "yerini almak" }),
      { say: [tr("Kalıbımız:"), de("ein Gerät, das …"), tr("Nesne nötrse zamir das; hem özne hem nesne olarak aynı kalır, yani karar vermek kolay.")] },
      { say: [tr("Örnek:"), de("Das ist ein Gerät, das ich jeden Tag benutze."), tr("Tekrar edin:"), de("Das ist ein Gerät, das ich jeden Tag benutze")], expect: repeat("Das ist ein Gerät, das ich jeden Tag benutze") },
      { say: [tr("Sıra sende: 'Kaybettiğim kumandayı arıyorum.'")], expect: produce("Ich suche die Fernbedienung, die ich verloren habe", [tr("Kumanda dişil ve nesne, ama dişilde zamir die kalır:"), de("Ich suche die Fernbedienung, die ich verloren habe."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi istisnayı deneyelim: 'İhtiyacım olan her şeyi aldım.'")], expect: produce("Ich habe alles gekauft, was ich brauche", [de("alles"), tr("sonrası das değil was:"), de("Ich habe alles gekauft, was ich brauche."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Onun yerini alan cihaz daha küçük.'")], expect: produce("Das Gerät, das es ersetzt, ist kleiner", [tr("Cihaz nötr ve burada özne → das; fiil sona:"), de("Das Gerät, das es ersetzt, ist kleiner."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Alles, das ich brauche, ist hier."), tr("cümlesi doğru mu?")], expect: truefalse("Alles, das ich brauche, ist hier.", false, [de("alles"), tr("sonrası was ister:"), de("Alles, was ich brauche, ist hier.")]) },
      { say: [tr("Son: 'Bunu şarj edebileceğin bir kablo lazım.'")], expect: produce("Ich brauche ein Kabel, mit dem ich das aufladen kann", [de("mit"), tr("yönelme ister ve modal fiil sona gider:"), de("Ich brauche ein Kabel, mit dem ich das aufladen kann."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir mağazada adını bilmediğin bir parçayı tarif edeceksin.")] },
    ],
    roleplay: {
      scene: "Bir elektronik mağazasındasın ve aradığın parçanın adını bilmiyorsun. Ne işe yaradığını, neye benzediğini ilgi cümleleriyle tarif et; satıcı sorularla daraltsın.",
      partner: "sabırlı ama çok soru soran bir satıcı",
      opening: "Guten Tag! Sie suchen etwas, aber Sie wissen den Namen nicht — kein Problem. Wofür brauchen Sie das Teil denn?",
      openingTr: "İyi günler! Bir şey arıyorsunuz ama adını bilmiyorsunuz — sorun değil. Bu parçayı ne için kullanacaksınız?",
      goal: "Aradığın parça tarif edilerek bulunmuş ya da yerine bir seçenek önerilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-lieblingsort",
    icon: "mountain",
    level: "B1",
    course: "de",
    title: "Der Ort, an dem ich auftanke",
    titleTr: "Sevdiğin mekânı anlatmak",
    summary: "Yer tanımlarken an dem, in dem ve wo arasındaki farkı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Präposition",
    vocab: [
      { de: "auftanken", tr: "enerji toplamak" },
      { de: "die Ruhe", tr: "huzur" },
      { de: "der Ausblick", tr: "manzara" },
      { de: "das Ufer", tr: "kıyı" },
      { de: "genießen", tr: "tadını çıkarmak" },
    ],
    patterns: [
      { de: "der Ort, an dem …", tr: "yer bildiren edatla tanımlama" },
      { de: "dorthin, wo …", tr: "yer için kısa yol: wo" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sevdiğin bir yeri anlatmayı öğreneceğiz. Almancada yer tanımlarken iki yol var ve ikisi de doğru: edatlı zamir ya da tek kelimeyle wo. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Uzun yol"), de("an dem"), tr("gibi bir edat artı zamir; kısa yol"), de("wo"), tr("Konuşurken çoğu Alman kısa yolu seçer, ama resmî yazıda uzun yol daha iyi durur. Önce kelimeler.")] },
      word("İlk", { de: "auftanken", tr: "enerji toplamak" }),
      word("İkinci", { de: "die Ruhe", tr: "huzur" }),
      word("Üçüncü", { de: "der Ausblick", tr: "manzara" }),
      word("Dördüncü", { de: "das Ufer", tr: "kıyı" }),
      word("Son", { de: "genießen", tr: "tadını çıkarmak" }),
      { say: [tr("Kalıbımız:"), de("der Ort, an dem ich auftanke"), tr("Yer bildiren edat yönelme ister; ort eril olduğu için dem.")] },
      { say: [tr("Örnek:"), de("Der Ort, an dem ich auftanke, ist das Ufer."), tr("Tekrar edin:"), de("Der Ort, an dem ich auftanke, ist das Ufer")], expect: repeat("Der Ort, an dem ich auftanke, ist das Ufer") },
      { say: [tr("Sıra sende: 'Oturmayı sevdiğim bir bank var.'")], expect: produce("Ich habe eine Bank, auf der ich gern sitze", [de("auf"), tr("yer bildirir, yönelme; bank dişil:"), de("Ich habe eine Bank, auf der ich gern sitze."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi kısa yolu deneyelim: 'Huzur bulduğum yere gidiyorum.'")], expect: produce("Ich gehe dorthin, wo ich Ruhe finde", [de("wo"), tr("yer bildiren ilgi cümlesini tek kelimeyle kurar:"), de("Ich gehe dorthin, wo ich Ruhe finde."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İçinde yürüdüğüm orman çok sakin.'")], expect: produce("Der Wald, in dem ich laufe, ist sehr ruhig", [de("in"), tr("yer bildirir; orman eril → in dem:"), de("Der Wald, in dem ich laufe, ist sehr ruhig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist der Ort, wo ich auftanke."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist der Ort, wo ich auftanke.", true, [tr("Doğru. Yer bildiren ilgi cümlesinde"), de("wo"), tr("kullanılabilir ve"), de("an dem"), tr("ile aynı anlama gelir.")]) },
      { say: [tr("Son: 'Manzaranın tadını çıkardığım bir kafe biliyorum.'")], expect: produce("Ich kenne ein Café, in dem ich den Ausblick genieße", [tr("Kafe nötr, yer bildiren edat → in dem:"), de("Ich kenne ein Café, in dem ich den Ausblick genieße."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşına sevdiğin mekânı anlatacaksın: nerede, neden orası, ne yapıyorsun orada.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın yorgun ve iyi gelecek bir yer arıyor. Sevdiğin mekânı ilgi cümleleriyle tarif et: nerede, orada ne yapıyorsun, neden iyi geliyor.",
      partner: "yorgun ama meraklı bir arkadaş",
      opening: "Ich bin völlig erschöpft. Gibt es einen Ort, an dem du wirklich abschalten kannst?",
      openingTr: "Tamamen tükendim. Gerçekten kafanı boşaltabildiğin bir yer var mı?",
      goal: "Sevdiğin mekân tarif edilmiş ve arkadaşın oraya gitmeye karar vermiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-fundbuero",
    icon: "question",
    level: "B1",
    course: "de",
    title: "Im Fundbüro",
    titleTr: "Kayıp eşya tarif etmek",
    summary: "Kayıp bir eşyayı resmî bir görevliye ilgi cümleleriyle tarif etmeyi öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Akkusativ",
    vocab: [
      { de: "das Fundbüro", tr: "kayıp eşya bürosu" },
      { de: "beschreiben", tr: "tarif etmek" },
      { de: "die Marke", tr: "marka" },
      { de: "der Inhalt", tr: "içindekiler" },
      { de: "auffällig", tr: "dikkat çekici" },
    ],
    patterns: [
      { de: "eine Tasche, die …", tr: "kaybolan eşyayı tanımlar" },
      { de: "Beschreiben Sie das Gerät, das …", tr: "resmî soruda ilgi cümlesi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ilgi cümlelerini gerçek bir işte kullanacağız: bir şeyini kaybettin ve tarif etmen gerekiyor. Görevli tek soru soruyor: hangisi, neye benziyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tarif iki parçadan kurulur: eşyanın adı, sonra onu ayıran ilgi cümlesi. Ne kadar ayırıcı olursa bulma şansı o kadar yüksek. Önce kelimeler.")] },
      word("İlk", { de: "das Fundbüro", tr: "kayıp eşya bürosu" }),
      word("İkinci", { de: "beschreiben", tr: "tarif etmek" }),
      word("Üçüncü", { de: "die Marke", tr: "marka" }),
      word("Dördüncü", { de: "der Inhalt", tr: "içindekiler" }),
      word("Son", { de: "auffällig", tr: "dikkat çekici" }),
      { say: [tr("Kalıbımız:"), de("eine Tasche, die ich verloren habe"), tr("Çanta kaybedilen şey, yani nesne; ama dişil olduğu için zamir yine die.")] },
      { say: [tr("Örnek:"), de("Ich suche eine Tasche, die ich gestern verloren habe."), tr("Tekrar edin:"), de("Ich suche eine Tasche, die ich gestern verloren habe")], expect: repeat("Ich suche eine Tasche, die ich gestern verloren habe") },
      { say: [tr("Sıra sende: 'Unuttuğum telefonu arıyorum.'")], expect: produce("Ich suche das Handy, das ich vergessen habe", [tr("Telefon nötr → das; Perfekt sona:"), de("Ich suche das Handy, das ich vergessen habe."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi görevlinin cümlesi: 'Tarif ettiğiniz çanta burada.'")], expect: produce("Die Tasche, die Sie beschrieben haben, ist hier", [tr("Kibar biçimde özne Sie, fiil Perfekt ve sonda:"), de("Die Tasche, die Sie beschrieben haben, ist hier."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Aradığım ceket dikkat çekici kırmızı.'")], expect: produce("Die Jacke, die ich suche, ist auffällig rot", [tr("Ceket dişil ve nesne, zamir die:"), de("Die Jacke, die ich suche, ist auffällig rot."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Tasche, die ich verloren habe, ist braun."), tr("cümlesi doğru mu?")], expect: truefalse("Die Tasche, die ich verloren habe, ist braun.", true, [tr("Doğru. Dişil isimde nesne de olsa zamir die kalır ve yardımcı fiil sonda duruyor.")]) },
      { say: [tr("Son: 'İçinde kimliğimin olduğu bir cüzdan.'")], expect: produce("Es ist ein Portemonnaie, in dem mein Ausweis ist", [tr("İçinde derken yer bildiren edat ve yönelme:"), de("Es ist ein Portemonnaie, in dem mein Ausweis ist."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada kayıp eşya bürosundasın: eşyanı tarif et, görevli ayrıntı istesin.")] },
    ],
    roleplay: {
      scene: "Kayıp eşya bürosundasın. Kaybettiğin eşyayı ilgi cümleleriyle tarif et: neye benziyor, markası ne, içinde ne vardı, nerede kaybettin.",
      partner: "resmî konuşan, ayrıntı isteyen bir görevli",
      opening: "Guten Tag. Was genau haben Sie verloren, und wo könnte es passiert sein?",
      openingTr: "İyi günler. Tam olarak neyinizi kaybettiniz ve nerede olmuş olabilir?",
      goal: "Eşyan tarif edilmiş, bulunup bulunmadığı öğrenilmiş ve ne yapılacağı söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-rezept-empfehlen",
    icon: "food",
    level: "B1",
    course: "de",
    title: "Das Gericht, das jeder mag",
    titleTr: "Yemek tarifi önermek",
    summary: "Bir yemeği ve malzemelerini ilgi cümleleriyle önermeyi öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Nominativ",
    vocab: [
      { de: "das Gericht", tr: "yemek" },
      { de: "die Zutat", tr: "malzeme" },
      { de: "würzig", tr: "baharatlı" },
      { de: "zubereiten", tr: "hazırlamak" },
      { de: "die Beilage", tr: "garnitür" },
    ],
    patterns: [
      { de: "ein Gericht, das …", tr: "yemeği özelliğiyle tanımlar" },
      { de: "Zutaten, die …", tr: "çoğul malzemede zamir die" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve en lezzetlisi: birine yemek önereceksin. Öneri iyi olsun diye yemeği tanımlaman gerekiyor, yani yine ilgi cümlesi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Üç şeyi tanımlayacağız: yemeğin kendisi, malzemeler ve yanında ne gittiği. Üçü de ilgi cümlesiyle. Önce kelimeler.")] },
      word("İlk", { de: "das Gericht", tr: "yemek" }),
      word("İkinci", { de: "die Zutat", tr: "malzeme" }),
      word("Üçüncü", { de: "würzig", tr: "baharatlı" }),
      word("Dördüncü", { de: "zubereiten", tr: "hazırlamak" }),
      word("Son", { de: "die Beilage", tr: "garnitür" }),
      { say: [tr("Kalıbımız:"), de("ein Gericht, das jeder mag"), tr("Yemek nötr, yan cümlede nesne, ama nötrde zamir yine das. Kolay taraf bu.")] },
      { say: [tr("Örnek:"), de("Ich kenne ein Gericht, das jeder mag."), tr("Tekrar edin:"), de("Ich kenne ein Gericht, das jeder mag")], expect: repeat("Ich kenne ein Gericht, das jeder mag") },
      { say: [tr("Sıra sende: 'Çabuk hazırlanan yemekleri severim.' Cümleyi ilgi cümlesiyle kur.")], expect: produce("Ich mag Gerichte, die schnell gehen", [tr("Çoğulda zamir die; 'schnell gehen' günlük Almancada 'çabuk olur' demek:"), de("Ich mag Gerichte, die schnell gehen."), tr("Tekrar dene.")], ["Ich mag Gerichte, die schnell fertig sind"]) },
      { say: [tr("Şimdi malzemeler: 'Evde bulunan malzemeler yeter.'")], expect: produce("Zutaten, die man zu Hause hat, reichen", [tr("Çoğul özne, zamir die, fiil sonda:"), de("Zutaten, die man zu Hause hat, reichen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yanına iyi giden bir garnitür öneriyorum.'")], expect: produce("Ich empfehle eine Beilage, die gut dazu passt", [tr("Garnitür dişil ve özne → die; 'dazu passen' yanına gitmek demek:"), de("Ich empfehle eine Beilage, die gut dazu passt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ein Gericht, das ist würzig, mag ich sehr."), tr("cümlesi doğru mu?")], expect: truefalse("Ein Gericht, das ist würzig, mag ich sehr.", false, [tr("Yan cümlede fiil sona gider:"), de("Ein Gericht, das würzig ist, mag ich sehr.")]) },
      { say: [tr("Son: 'Yirmi dakikada hazırlayabileceğin bir yemek.'")], expect: produce("Das ist ein Gericht, das man in zwanzig Minuten zubereiten kann", [tr("Modal fiil en sona, mastar onun önüne:"), de("Das ist ein Gericht, das man in zwanzig Minuten zubereiten kann."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir arkadaşına yemek önereceksin: hangi yemek, hangi malzemeler, yanına ne gider.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın akşam misafir bekliyor ve ne pişireceğini bilmiyor. Bir yemek öner: yemeği, malzemeleri ve garnitürü ilgi cümleleriyle tanımla.",
      partner: "mutfakta acemi, telaşlı bir arkadaş",
      opening: "Heute Abend kommen Gäste und ich habe keine Idee. Kennst du ein Gericht, das schnell geht und trotzdem gut ist?",
      openingTr: "Bu akşam misafir geliyor ve hiçbir fikrim yok. Hem çabuk olan hem de iyi bir yemek biliyor musun?",
      goal: "Bir yemek önerilmiş, malzemeleri ve garnitürü söylenmiş; arkadaşın onu yapmaya karar vermiş olur.",
      minTurns: 9,
    },
  },
];
