import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 8 — Para ve kariyer stratejisi (071–080).
 *
 * Bu modülün konusu tek bir dilbilgisi yapısı değil, bir DURUŞ: kendi
 * çıkarını savunurken makul kalmak. Almanca bunu üç araçla yapıyor ve üçü de
 * bu modülde yan yana çalışıyor — dilek kipi (talebi öneriye çevirir),
 * koşullu bağlaçlar (sözü bağlayıcı olmaktan çıkarır) ve isimleşmiş resmî
 * dil (kişiyi cümleden çıkarır).
 *
 * Türkçe konuşan için tuzak şurada: Türkçede maaş konuşurken kibarlık ekle
 * ve tonla kurulur ("şöyle düşünüyordum acaba"). Almancada aynı yumuşaklık
 * KİP ile kurulur ve tonu değiştirmeye gerek kalmaz — "Ich hätte mir …
 * vorgestellt" cümlesi düz sesle söylendiğinde bile bir teklif olarak
 * duyulur.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B08: Lesson[] = [
  {
    id: "de-b2-gehaltsverhandlung",
    icon: "money",
    level: "B2",
    course: "de",
    title: "Mehr Gehalt, bitte",
    titleTr: "Maaş müzakeresi",
    summary: "Ücret talebini dilek kipiyle ve gerekçeyle sunmayı öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Vergütung", tr: "ücretlendirme" },
      { de: "die Gehaltserhöhung", tr: "maaş zammı" },
      { de: "der Stundenlohn", tr: "saat ücreti" },
      { de: "die Prämie", tr: "prim" },
      { de: "der Tarifvertrag", tr: "toplu iş sözleşmesi" },
      { de: "die Festanstellung", tr: "kadrolu iş" },
      { de: "die Aufstiegschance", tr: "yükselme fırsatı" },
      { de: "angemessen", tr: "makul" },
    ],
    patterns: [
      { de: "Ich hätte mir … vorgestellt.", tr: "talebi teklife çevirir" },
      { de: "Gemessen an …", tr: "ölçüt bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: para ve kariyer. İlk ders en gergin konuşma — maaş. Ve iyi haber şu ki gerginliği dil taşıyabiliyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Türkçede kibarlığı tonla kurarız. Almancada kip kurar: 'şöyle düşünmüştüm' cümlesi düz sesle bile bir teklif gibi duyulur. Önce kelimeler.")] },
      word("İlk", { de: "die Vergütung", tr: "ücretlendirme" }),
      word("İkinci", { de: "die Gehaltserhöhung", tr: "maaş zammı" }),
      word("Üçüncü", { de: "der Stundenlohn", tr: "saat ücreti" }),
      word("Dördüncü", { de: "die Prämie", tr: "prim" }, "Maaşın üstüne verilen tek seferlik ödeme."),
      word("Beşinci", { de: "der Tarifvertrag", tr: "toplu iş sözleşmesi" }),
      word("Altıncı", { de: "die Festanstellung", tr: "kadrolu iş" }),
      word("Yedinci", { de: "die Aufstiegschance", tr: "yükselme fırsatı" }),
      word("Son", { de: "angemessen", tr: "makul" }),
      { say: [tr("Kalıbımız:"), de("Ich hätte mir … vorgestellt."), tr("Kelimesi kelimesine 'şöyle hayal etmiştim'; müzakerede 'benim beklentim şu' demektir.")] },
      { say: [tr("Örnek:"), de("Ich hätte mir eine Gehaltserhöhung um fünf Prozent vorgestellt."), tr("Tekrar edin:"), de("Ich hätte mir eine Gehaltserhöhung um fünf Prozent vorgestellt")], expect: repeat("Ich hätte mir eine Gehaltserhöhung um fünf Prozent vorgestellt") },
      { say: [tr("Sıra sende: 'Performansıma göre bu makul olurdu.'")], expect: produce("Gemessen an meiner Leistung wäre das angemessen", [tr("Bu edat yönelme hâli ister; dilek kipi ikinci sırada:"), de("Gemessen an meiner Leistung wäre das angemessen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Toplu iş sözleşmesi daha fazlasını öngörüyor.'")], expect: produce("Der Tarifvertrag sieht mehr vor", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Der Tarifvertrag sieht mehr vor."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ücretlendirme hakkında konuşmak isterim.'")], expect: produce("Ich würde gern über die Vergütung sprechen", [tr("Dilek kipi ricayı yumuşatır; mastar sonda:"), de("Ich würde gern über die Vergütung sprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Gemessen an meine Leistung wäre das angemessen."), tr("cümlesi doğru mu?")], expect: truefalse("Gemessen an meine Leistung wäre das angemessen.", false, [tr("Bu kalıptaki edat yönelme hâli ister:"), de("Gemessen an meiner Leistung wäre das angemessen.")]) },
      { say: [tr("Son bir soru: 'Prim ne kadar?'")], expect: produce("Wie hoch ist die Prämie", [tr("Soru öbeği başta, fiil ikinci sırada:"), de("Wie hoch ist die Prämie?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada şefinle maaşını konuşacaksın: beklentini söyle, gerekçelendir ve bir sonuca bağla.")] },
    ],
    roleplay: {
      scene: "Şefinle yıllık değerlendirme görüşmesindesin ve maaş artışı istiyorsun. Beklentini dilek kipiyle söyle, rakamlarla gerekçelendir, itiraza karşılık ver ve bir sonuca ya da yeni bir tarihe bağla.",
      partner: "bütçe kısıtından söz eden, ama iyi gerekçeye açık bir bölüm şefi",
      opening: "Sie wollten über die Vergütung sprechen. Bevor wir anfangen: Was schwebt Ihnen denn vor?",
      openingTr: "Ücretlendirme hakkında konuşmak istemiştiniz. Başlamadan önce: Aklınızda ne var?",
      goal: "Beklenti rakamla söylenmiş, gerekçelendirilmiş ve bir sonuca ya da yeni bir görüşme tarihine bağlanmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-sparen-anlegen",
    icon: "chart",
    level: "B2",
    course: "de",
    title: "Sparen oder anlegen?",
    titleTr: "Birikim sohbeti",
    summary: "Risk ve getiri ilişkisini orantı bağlacıyla konuşmayı öğretir.",
    minutes: 12,
    focusId: "Je-desto",
    vocab: [
      { de: "die Rendite", tr: "getiri" },
      { de: "streuen", tr: "dağıtmak (risk)" },
      { de: "anlegen", tr: "yatırmak" },
      { de: "die Ersparnis", tr: "birikim" },
      { de: "das Guthaben", tr: "bakiye" },
      { de: "die Aktie", tr: "hisse senedi" },
      { de: "das Wertpapier", tr: "menkul kıymet" },
      { de: "das Vermögen", tr: "servet" },
    ],
    patterns: [
      { de: "Je höher …, desto größer …", tr: "risk-getiri orantısı" },
      { de: "Auf lange Sicht …", tr: "uzun vade ifadesi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün para biriktirmeyi konuşacağız. Bu alanın en temel cümlesi bir orantı: getiri yükseldikçe risk de yükselir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu bağlacı biliyorsun ama ikinci parçadaki dizilim yine dikkat isteyecek: karşılaştırma biçimi hemen bağlacın arkasında, fiil onun arkasında. Önce kelimeler.")] },
      word("İlk", { de: "die Rendite", tr: "getiri" }),
      word("İkinci", { de: "streuen", tr: "dağıtmak (risk)" }, "Parayı tek yere değil birçok yere koymak."),
      word("Üçüncü", { de: "anlegen", tr: "yatırmak" }),
      word("Dördüncü", { de: "die Ersparnis", tr: "birikim" }),
      word("Beşinci", { de: "das Guthaben", tr: "bakiye" }),
      word("Altıncı", { de: "die Aktie", tr: "hisse senedi" }),
      word("Yedinci", { de: "das Wertpapier", tr: "menkul kıymet" }),
      word("Son", { de: "das Vermögen", tr: "servet" }),
      { say: [tr("Kalıbımız:"), de("Je höher …, desto größer …"), tr("İki karşılaştırma biçimi; ikisi de bağlacın hemen arkasında.")] },
      { say: [tr("Örnek:"), de("Je höher die Rendite ist, desto größer ist das Risiko."), tr("Tekrar edin:"), de("Je höher die Rendite ist, desto größer ist das Risiko")], expect: repeat("Je höher die Rendite ist, desto größer ist das Risiko") },
      { say: [tr("Sıra sende: 'Riski dağıtmak gerekir.'")], expect: produce("Man sollte das Risiko streuen", [tr("Öğüt sollte ile; mastar sonda:"), de("Man sollte das Risiko streuen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Önce bir birikim kurmalısın.'")], expect: produce("Zuerst solltest du eine Ersparnis aufbauen", [tr("Zarf başta, kip fiili ikinci sırada, mastar sonda:"), de("Zuerst solltest du eine Ersparnis aufbauen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ne kadar erken başlarsan o kadar az yatırman gerekir.'")], expect: produce("Je früher du anfängst, desto weniger musst du einzahlen", [tr("İkinci parçada fiil karşılaştırma öbeğinden hemen sonra:"), de("Je früher du anfängst, desto weniger musst du einzahlen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Je früher du anfängst, desto weniger du musst einzahlen."), tr("cümlesi doğru mu?")], expect: truefalse("Je früher du anfängst, desto weniger du musst einzahlen.", false, [tr("İkinci parçada çekimli fiil karşılaştırma öbeğinin hemen arkasına gelir, özne ondan sonra:"), de("Je früher du anfängst, desto weniger musst du einzahlen.")]) },
      { say: [tr("Son: 'Uzun vadede parayı yatırmak işe yarıyor.'")], expect: produce("Auf lange Sicht lohnt es sich anzulegen", [tr("Kalıplaşmış ifade başta; ayrılabilen fiilde zu ortaya girer:"), de("Auf lange Sicht lohnt es sich anzulegen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada birikim planını konuşacaksın: ne kadar, nereye, hangi riskle.")] },
    ],
    roleplay: {
      scene: "Bir banka danışmanıyla birikim planını konuşuyorsun: ne kadar ayırabiliyorsun, ne kadar risk alabilirsin, hangi vade sana uygun. Risk ve getiri ilişkisini orantı cümleleriyle konuş.",
      partner: "ürün satmaya meyilli ama soruları dürüstçe cevaplayan bir banka danışmanı",
      opening: "Sie möchten etwas anlegen. Sagen Sie mir zuerst: Wie lange können Sie auf das Geld verzichten?",
      openingTr: "Bir yatırım yapmak istiyorsunuz. Önce şunu söyleyin: Bu paradan ne kadar süre vazgeçebilirsiniz?",
      goal: "Vade, tutar ve risk düzeyi netleşmiş ve bir plan üzerinde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-selbststaendig",
    icon: "idea",
    level: "B2",
    course: "de",
    title: "Der Sprung in die Selbstständigkeit",
    titleTr: "Girişimcilik",
    summary: "Koşullu bağlaçlarla girişim planını anlatmayı öğretir.",
    minutes: 12,
    focusId: "Nebensatz-sofern",
    vocab: [
      { de: "die Existenzgründung", tr: "iş kurma" },
      { de: "das Eigenkapital", tr: "öz sermaye" },
      { de: "die Liquidität", tr: "likidite" },
      { de: "der Umsatz", tr: "ciro" },
      { de: "konkurrieren", tr: "rekabet etmek" },
      { de: "florieren", tr: "iyi gitmek" },
      { de: "scheitern", tr: "başarısız olmak" },
      { de: "absichern", tr: "güvenceye almak" },
    ],
    patterns: [
      { de: "Sofern …, …", tr: "koşullu plan" },
      { de: "auf eigene Rechnung", tr: "kendi hesabına" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kendi işini kurmayı konuşacağız. Bu konuda hiçbir cümle kesin kurulmaz — her şey bir koşula bağlıdır ve dil de öyle. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Koşullu bağlacı ikinci modülde görmüştün; burada bir plan anlatmak için kullanacaksın. Yan cümle, yani fiil sonda. Önce kelimeler.")] },
      word("İlk", { de: "die Existenzgründung", tr: "iş kurma" }),
      word("İkinci", { de: "das Eigenkapital", tr: "öz sermaye" }, "İşe kendi koyduğun para."),
      word("Üçüncü", { de: "die Liquidität", tr: "likidite" }, "Elde duran, hemen harcanabilir para."),
      word("Dördüncü", { de: "der Umsatz", tr: "ciro" }),
      word("Beşinci", { de: "konkurrieren", tr: "rekabet etmek" }),
      word("Altıncı", { de: "florieren", tr: "iyi gitmek" }),
      word("Yedinci", { de: "scheitern", tr: "başarısız olmak" }),
      word("Son", { de: "absichern", tr: "güvenceye almak" }),
      { say: [tr("Kalıbımız:"), de("Sofern …, …"), tr("Koşul yan cümlede, sonuç ana cümlede; ana cümle fiille başlar.")] },
      { say: [tr("Örnek:"), de("Sofern der Plan aufgeht, kann ich davon leben."), tr("Tekrar edin:"), de("Sofern der Plan aufgeht, kann ich davon leben")], expect: repeat("Sofern der Plan aufgeht, kann ich davon leben") },
      { say: [tr("Sıra sende: 'Likidite yeterse yılı atlatırım.'")], expect: produce("Sofern die Liquidität reicht, überstehe ich das Jahr", [tr("Yan cümlede fiil sonda; ana cümle fiille başlar:"), de("Sofern die Liquidität reicht, überstehe ich das Jahr."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kendi hesabıma çalışıyorum.'")], expect: produce("Ich arbeite auf eigene Rechnung", [tr("Kalıplaşmış ifade; belirtme hâlinde:"), de("Ich arbeite auf eigene Rechnung."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kendimi bir yıllığına güvenceye aldım.'")], expect: produce("Ich habe mich für ein Jahr abgesichert", [tr("Dönüşlü fiil; ayrılabilen ortaç sonda:"), de("Ich habe mich für ein Jahr abgesichert."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Sofern die Liquidität reicht, überstehe ich das Jahr."), tr("cümlesi doğru mu?")], expect: truefalse("Sofern die Liquidität reicht, überstehe ich das Jahr.", true, [tr("Doğru. Koşul yan cümlesinin fiili sonda, ana cümle fiille başlıyor.")]) },
      { say: [tr("Son: 'Çoğu girişim ilk üç yılda batıyor.'")], expect: produce("Die meisten Existenzgründungen scheitern in den ersten drei Jahren", [tr("Zaman ifadesi yönelme hâlinde, çoğulda -n eki:"), de("Die meisten Existenzgründungen scheitern in den ersten drei Jahren."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada girişim planını anlatacaksın: ne kuracaksın, hangi koşulla yürür, ne olursa vazgeçersin.")] },
    ],
    roleplay: {
      scene: "Bir girişim danışmanıyla planını konuşuyorsun: ne kurmak istiyorsun, müşteri kitlen kim, hangi koşulla yürür ve ne olursa vazgeçersin. Her adımı koşula bağla.",
      partner: "iyimserliği sorgulayan, rakam soran bir girişim danışmanı",
      opening: "Bevor wir über die Idee reden: Wie lange könnten Sie durchhalten, wenn im ersten Jahr kaum Umsatz kommt?",
      openingTr: "Fikri konuşmadan önce: İlk yıl neredeyse hiç ciro gelmezse ne kadar dayanabilirsiniz?",
      goal: "Girişim fikri, müşteri kitlesi ve dayanma süresi anlatılmış; hangi koşulda devam edileceği ve ne olursa vazgeçileceği söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-buerokratie-gruendung",
    icon: "office",
    level: "B2",
    course: "de",
    title: "Gründen auf Deutsch",
    titleTr: "Şirket kurma",
    summary: "Kurum işlemlerini isimleşmiş resmî dille konuşmayı öğretir.",
    minutes: 12,
    focusId: "Nominalisierung",
    vocab: [
      { de: "das Gewerbe", tr: "ticari faaliyet" },
      { de: "die Bescheinigung", tr: "belge" },
      { de: "das Finanzamt", tr: "vergi dairesi" },
      { de: "der Antragsteller", tr: "başvuru sahibi" },
      { de: "die Umsatzsteuer", tr: "KDV" },
      { de: "die Buchführung", tr: "muhasebe" },
      { de: "bewilligen", tr: "kabul etmek" },
      { de: "gebührenfrei", tr: "ücretsiz" },
    ],
    patterns: [
      { de: "Nach der Bewilligung …", tr: "isim öbeğiyle koşul" },
      { de: "Die Anmeldung des … erfolgt …", tr: "işlemi resmî bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kurumlarla iş yapacağız. Resmî Almanca kişileri cümleden çıkarır ve işlemleri isim yapar: 'başvurduktan sonra' değil, 'belgenin alınmasından sonra'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yapı ilk modülde başladı, burada en yoğun hâline geliyor. Tamlama ekleri de dikkat isteyecek. Önce kelimeler.")] },
      word("İlk", { de: "das Gewerbe", tr: "ticari faaliyet" }),
      word("İkinci", { de: "die Bescheinigung", tr: "belge" }),
      word("Üçüncü", { de: "das Finanzamt", tr: "vergi dairesi" }),
      word("Dördüncü", { de: "der Antragsteller", tr: "başvuru sahibi" }, "Resmî yazıda başvuran kişinin adı budur."),
      word("Beşinci", { de: "die Umsatzsteuer", tr: "KDV" }),
      word("Altıncı", { de: "die Buchführung", tr: "muhasebe" }),
      word("Yedinci", { de: "bewilligen", tr: "kabul etmek" }),
      word("Son", { de: "gebührenfrei", tr: "ücretsiz" }),
      { say: [tr("Kalıbımız:"), de("Nach Erhalt der Bescheinigung …"), tr("Yan cümle yok; koşul bir isim öbeğine sığmış.")] },
      { say: [tr("Örnek:"), de("Nach der Bewilligung können Sie starten."), tr("Tekrar edin:"), de("Nach der Bewilligung können Sie starten")], expect: repeat("Nach der Bewilligung können Sie starten") },
      { say: [tr("Sıra sende: 'Ticari faaliyet kaydı çevrimiçi yapılıyor.'")], expect: produce("Die Anmeldung des Gewerbes erfolgt online", [tr("Nötr isim tamlamada -s ekini alır:"), de("Die Anmeldung des Gewerbes erfolgt online."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bunun için üç belge gerekli.'")], expect: produce("Dafür sind drei Unterlagen erforderlich", [tr("Edat zamirle kaynaşır; sıfat sonda:"), de("Dafür sind drei Unterlagen erforderlich."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kayıttan sonra vergi dairesinden bir numara alıyorsunuz.'")], expect: produce("Nach der Anmeldung erhalten Sie eine Nummer vom Finanzamt", [tr("Edat yönelme hâli ister; fiil ikinci sırada:"), de("Nach der Anmeldung erhalten Sie eine Nummer vom Finanzamt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Anmeldung des Gewerbe erfolgt online."), tr("cümlesi doğru mu?")], expect: truefalse("Die Anmeldung des Gewerbe erfolgt online.", false, [tr("Eril ve nötr isimler tamlama hâlinde -s ekini alır:"), de("Die Anmeldung des Gewerbes erfolgt online.")]) },
      { say: [tr("Son bir soru: 'Burada kim başvuru sahibi sayılıyor?'")], expect: produce("Wer gilt hier als Antragsteller", [tr("Soru zamiri özne; als edatı yalın hâlle:"), de("Wer gilt hier als Antragsteller?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir danışma masasında kuruluş adımlarını soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir ticaret odasının danışma masasındasın ve kendi işini kurmak için ne gerektiğini soruyorsun: hangi kayıt, hangi belgeler, hangi sıra, ne kadar sürer ve ne kadar tutar.",
      partner: "adımları resmî dille sayan, formlara yönlendiren bir danışma görevlisi",
      opening: "Sie möchten ein Gewerbe anmelden. Haben Sie schon eine Vorstellung davon, welche Form das annehmen soll?",
      openingTr: "Ticari faaliyet kaydı yaptırmak istiyorsunuz. Bunun hangi biçimde olacağına dair bir fikriniz var mı?",
      goal: "Gereken belgeler, adımların sırası ve süre öğrenilmiş; bir sonraki somut adım kararlaşmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-work-life",
    icon: "feelings",
    level: "B2",
    course: "de",
    title: "Arbeiten, um zu leben?",
    titleTr: "İş-yaşam dengesi",
    summary: "Amaç cümleleriyle sınır çizmeyi ve dengeyi anlatmayı öğretir.",
    minutes: 12,
    focusId: "Um-zu",
    vocab: [
      { de: "der Ausgleich", tr: "denge" },
      { de: "die Belastung", tr: "yük" },
      { de: "die Arbeitszeit", tr: "çalışma süresi" },
      { de: "die Schichtarbeit", tr: "vardiyalı çalışma" },
      { de: "der Urlaubsanspruch", tr: "izin hakkı" },
      { de: "die Elternzeit", tr: "ebeveyn izni" },
      { de: "die Regeneration", tr: "toparlanma" },
      { de: "erwerbstätig", tr: "iş sahibi" },
    ],
    patterns: [
      { de: "…, um … zu …", tr: "amaç bildirir" },
      { de: "Es geht darum, … zu …", tr: "meselenin ne olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sınır çizeceğiz. Sınır çizmek Almancada bir amaç cümlesiyle kurulur: 'kafamı dinlemek için telefonu kapatıyorum'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu yapıyı B1'de öğrenmiştin; burada zorluk kelime değil, cümlenin işlevi: kendini savunurken suçlayıcı olmamak. Önce kelimeler.")] },
      word("İlk", { de: "der Ausgleich", tr: "denge" }),
      word("İkinci", { de: "die Belastung", tr: "yük" }),
      word("Üçüncü", { de: "die Arbeitszeit", tr: "çalışma süresi" }),
      word("Dördüncü", { de: "die Schichtarbeit", tr: "vardiyalı çalışma" }),
      word("Beşinci", { de: "der Urlaubsanspruch", tr: "izin hakkı" }, "Yılda kaç gün izin hakkın olduğu."),
      word("Altıncı", { de: "die Elternzeit", tr: "ebeveyn izni" }),
      word("Yedinci", { de: "die Regeneration", tr: "toparlanma" }),
      word("Son", { de: "erwerbstätig", tr: "iş sahibi" }),
      { say: [tr("Kalıbımız:"), de("Es geht darum, … zu …"), tr("Meselenin ne olduğunu kişiselleştirmeden söyler.")] },
      { say: [tr("Örnek:"), de("Man arbeitet, um zu leben — nicht umgekehrt."), tr("Tekrar edin:"), de("Man arbeitet, um zu leben, nicht umgekehrt")], expect: repeat("Man arbeitet, um zu leben, nicht umgekehrt") },
      { say: [tr("Sıra sende: 'Kafamı dinlemek için telefonu kapatıyorum.'")], expect: produce("Ich schalte das Handy aus, um abzuschalten", [tr("Ayrılabilen fiilde zu ortaya girer:"), de("Ich schalte das Handy aus, um abzuschalten."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Mesele sınır çizmekte.'")], expect: produce("Es geht darum, Grenzen zu ziehen", [tr("Edat zamirle kaynaşır; mastar öbeği virgülden sonra:"), de("Es geht darum, Grenzen zu ziehen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bilinçli olarak mesaimi bitiriyorum.'")], expect: produce("Ich mache bewusst Feierabend", [tr("Kalıplaşmış ifade; zarf fiilden sonra:"), de("Ich mache bewusst Feierabend."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich schalte das Handy aus, um abschalten."), tr("cümlesi doğru mu?")], expect: truefalse("Ich schalte das Handy aus, um abschalten.", false, [tr("Amaç öbeğinde zu gerekir ve ayrılabilen fiilde ortaya girer:"), de("Ich schalte das Handy aus, um abzuschalten.")]) },
      { say: [tr("Son: 'Vardiyalı çalışmaya karşı bir dengeye ihtiyacım var.'")], expect: produce("Ich brauche einen Ausgleich zur Schichtarbeit", [tr("Belirtisiz eril belirtme hâlinde; edat yönelme hâli ister:"), de("Ich brauche einen Ausgleich zur Schichtarbeit."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada iş yükün üzerine konuşacaksın: neyi neden değiştirmek istiyorsun.")] },
    ],
    roleplay: {
      scene: "Şefinle iş yükünü konuşuyorsun: mesai sonrası mesajlar, hafta sonu erişilebilirlik ve yükün dağılımı. Ne istediğini amaç cümleleriyle söyle, suçlamadan bir sınır öner ve bir düzende anlaş.",
      partner: "iyi niyetli ama ulaşılabilirliği doğal sayan bir şef",
      opening: "Sie wirken in letzter Zeit angespannt. Liegt es an der Menge, oder gibt es etwas anderes?",
      openingTr: "Son zamanlarda gergin görünüyorsunuz. İş yükü mü, yoksa başka bir şey mi var?",
      goal: "Yükün nerede olduğu suçlamadan anlatılmış, somut bir sınır önerilmiş ve üzerinde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-networking-b2",
    icon: "handshake",
    level: "B2",
    course: "de",
    title: "Vitamin B",
    titleTr: "Çevre edinmek",
    summary: "Bağlantı kurmayı edilgen yerine geçen yapılarla konuşmayı öğretir.",
    minutes: 12,
    focusId: "Passiversatz",
    vocab: [
      { de: "die Referenz", tr: "referans" },
      { de: "das Arbeitszeugnis", tr: "iş referansı" },
      { de: "die Personalabteilung", tr: "insan kaynakları" },
      { de: "der Abteilungsleiter", tr: "bölüm müdürü" },
      { de: "die Berufserfahrung", tr: "iş deneyimi" },
      { de: "anwerben", tr: "eleman toplamak" },
      { de: "kooperieren", tr: "işbirliği yapmak" },
      { de: "mitwirken", tr: "yer almak" },
    ],
    patterns: [
      { de: "Kontakte lassen sich …", tr: "bağ kurulabilir" },
      { de: "Gute Arbeit spricht sich herum.", tr: "kendiliğinden yayılır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün çevrenin nasıl kurulduğunu konuşacağız. Bu konunun cümleleri failsizdir: bağ kurulur, iş tavsiyeyle bulunur — kim yapar, söylenmez. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de kendiliğinden olan şeyler için dönüşlü fiiller var: 'kulaktan kulağa yayılır'. Türkçedeki edilgene çok yakın. Önce kelimeler.")] },
      word("İlk", { de: "die Referenz", tr: "referans" }),
      word("İkinci", { de: "das Arbeitszeugnis", tr: "iş referansı" }, "Almanya'da işten ayrılırken verilen resmî değerlendirme."),
      word("Üçüncü", { de: "die Personalabteilung", tr: "insan kaynakları" }),
      word("Dördüncü", { de: "der Abteilungsleiter", tr: "bölüm müdürü" }),
      word("Beşinci", { de: "die Berufserfahrung", tr: "iş deneyimi" }),
      word("Altıncı", { de: "anwerben", tr: "eleman toplamak" }),
      word("Yedinci", { de: "kooperieren", tr: "işbirliği yapmak" }),
      word("Son", { de: "mitwirken", tr: "yer almak" }),
      { say: [tr("Kalıbımız:"), de("Kontakte lassen sich überall aufbauen."), tr("Yani 'her yerde bağ kurulabilir'.")] },
      { say: [tr("Tekrar edin:"), de("Kontakte lassen sich überall aufbauen")], expect: repeat("Kontakte lassen sich überall aufbauen") },
      { say: [tr("Sıra sende: 'Bu sektörde herkes birbirini tanır.'")], expect: produce("In dieser Branche kennt man sich", [tr("Tümleç başta, fiil ikinci sırada, dönüşlü zamir sonra:"), de("In dieser Branche kennt man sich."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İyi iş kulaktan kulağa yayılır.'")], expect: produce("Gute Arbeit spricht sich herum", [tr("Dönüşlü fiil; ayrılabilen önek sonda:"), de("Gute Arbeit spricht sich herum."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yeni insanlar tavsiyeyle toplanıyor.'")], expect: produce("Neue Leute werden über Empfehlungen angeworben", [tr("Şimdiki zaman edilgeni; çoğul özne werden alır:"), de("Neue Leute werden über Empfehlungen angeworben."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Kontakte lassen sich überall aufbauen."), tr("cümlesi doğru mu?")], expect: truefalse("Kontakte lassen sich überall aufbauen.", true, [tr("Doğru. lassen artı dönüşlü zamir edilgen anlamı taşıyor ve mastar cümlenin sonunda duruyor.")]) },
      { say: [tr("Son bir soru: 'Bana bir referans yazar mısınız?'")], expect: produce("Würden Sie mir eine Referenz ausstellen", [tr("Dilek kipiyle kibar soru; ayrılabilen mastar sonda:"), de("Würden Sie mir eine Referenz ausstellen?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir tanıdıktan tavsiye isteyeceksin.")] },
    ],
    roleplay: {
      scene: "Sektöründen bir tanıdığınla konuşuyorsun ve ondan bir tavsiye ya da bağlantı istiyorsun. Ne aradığını söyle, ne yaptığını kısaca anlat, tavsiye iste ve karşılığında ne sunabileceğini belirt.",
      partner: "yardıma açık ama kime tavsiye edeceğine dikkat eden bir tanıdık",
      opening: "Schön, dass Sie sich melden. Sagen Sie — was suchen Sie denn konkret?",
      openingTr: "Aramanız güzel oldu. Söyleyin — tam olarak ne arıyorsunuz?",
      goal: "Ne arandığı ve ne yapıldığı anlatılmış, somut bir tavsiye ya da bağlantı istenmiş ve karşılığında ne sunulacağı söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-jobwechsel",
    icon: "suitcase",
    level: "B2",
    course: "de",
    title: "Der mutige Wechsel",
    titleTr: "İş değiştirmek",
    summary: "Zıtlık bağlacıyla riskli bir kararı anlatmayı öğretir.",
    minutes: 12,
    focusId: "Nebensatz-obwohl",
    vocab: [
      { de: "der Wechsel", tr: "geçiş" },
      { de: "bereuen", tr: "pişman olmak" },
      { de: "die Stellenanzeige", tr: "iş ilanı" },
      { de: "das Anforderungsprofil", tr: "aranan nitelikler" },
      { de: "das Auswahlverfahren", tr: "seçim süreci" },
      { de: "antreten", tr: "göreve başlamak" },
      { de: "ausscheiden", tr: "işten ayrılmak" },
      { de: "betriebsbedingt", tr: "işletme gereği" },
    ],
    patterns: [
      { de: "Obwohl …, …", tr: "zıtlık yan cümlesi" },
      { de: "Der Schritt hat sich gelohnt.", tr: "sonucu değerlendirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün riskli bir kararı anlatacağız ve böyle anlatımların iskeleti zıtlıktır: güvenli olmasına RAĞMEN bıraktım. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu bağlaç yan cümle kurar, yani fiil sona gider. Cümlenin gücü de tam oradan gelir: gerekçe ile karar yan yana durur. Önce kelimeler.")] },
      word("İlk", { de: "der Wechsel", tr: "geçiş" }),
      word("İkinci", { de: "bereuen", tr: "pişman olmak" }),
      word("Üçüncü", { de: "die Stellenanzeige", tr: "iş ilanı" }),
      word("Dördüncü", { de: "das Anforderungsprofil", tr: "aranan nitelikler" }, "İlanın 'sizden beklediklerimiz' bölümü."),
      word("Beşinci", { de: "das Auswahlverfahren", tr: "seçim süreci" }),
      word("Altıncı", { de: "antreten", tr: "göreve başlamak" }),
      word("Yedinci", { de: "ausscheiden", tr: "işten ayrılmak" }),
      word("Son", { de: "betriebsbedingt", tr: "işletme gereği" }, "İşten çıkarmanın resmî gerekçesi."),
      { say: [tr("Kalıbımız:"), de("Obwohl …, …"), tr("Yan cümlede fiil sonda; ana cümle fiille başlar.")] },
      { say: [tr("Örnek:"), de("Obwohl die Stelle sicher war, habe ich gekündigt."), tr("Tekrar edin:"), de("Obwohl die Stelle sicher war, habe ich gekündigt")], expect: repeat("Obwohl die Stelle sicher war, habe ich gekündigt") },
      { say: [tr("Sıra sende: 'Adım değdi.'")], expect: produce("Der Schritt hat sich gelohnt", [tr("Dönüşlü fiil; ortaç sonda:"), de("Der Schritt hat sich gelohnt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bugüne kadar pişman olmadım.'")], expect: produce("Bis heute habe ich es nicht bereut", [tr("Zaman başta, yardımcı fiil ikinci sırada, ortaç sonda:"), de("Bis heute habe ich es nicht bereut."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bir seçim süreci sabır ister.'")], expect: produce("Ein Auswahlverfahren erfordert Geduld", [tr("Kısa ve güçlü bir cümle; nesne belirteçsiz:"), de("Ein Auswahlverfahren erfordert Geduld."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Obwohl die Stelle war sicher, habe ich gekündigt."), tr("cümlesi doğru mu?")], expect: truefalse("Obwohl die Stelle war sicher, habe ich gekündigt.", false, [tr("Bu bağlaç yan cümle kurar; çekimli fiil en sona gider:"), de("Obwohl die Stelle sicher war, habe ich gekündigt.")]) },
      { say: [tr("Son: 'Korkuma rağmen yeni işe başladım.'")], expect: produce("Trotz meiner Angst habe ich die neue Stelle angetreten", [tr("Bu edat tamlayan hâli ister; ayrılabilen ortaç sonda:"), de("Trotz meiner Angst habe ich die neue Stelle angetreten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir iş değişikliğini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın güvenli işinden ayrılmayı düşünüyor ve fikrini soruyor. Kendi deneyimini ya da gözlemini zıtlık cümleleriyle anlat, riskleri adlandır ve ona somut bir tavsiye ver.",
      partner: "kararsız, hem heyecanlı hem korkan bir arkadaş",
      opening: "Die Stelle ist sicher, das Geld stimmt — und trotzdem will ich weg. Bin ich verrückt?",
      openingTr: "İş güvenli, para da iyi — ve yine de gitmek istiyorum. Deli miyim?",
      goal: "Riskler ve gerekçeler zıtlık cümleleriyle konuşulmuş ve arkadaşa somut bir tavsiye verilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-rente",
    icon: "clock",
    level: "B2",
    course: "de",
    title: "An später denken",
    titleTr: "Emeklilik",
    summary: "Gelecekteki belirsizliği öznel kip fiilleriyle konuşmayı öğretir.",
    minutes: 12,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "die Altersvorsorge", tr: "emeklilik birikimi" },
      { de: "die Rentenversicherung", tr: "emeklilik sigortası" },
      { de: "die Betriebsrente", tr: "işyeri emekliliği" },
      { de: "der Ruhestand", tr: "emeklilik" },
      { de: "die Berufsunfähigkeit", tr: "iş göremezlik" },
      { de: "der Zuschuss", tr: "sübvansiyon" },
      { de: "die Lücke", tr: "boşluk" },
      { de: "vorzeitig", tr: "vaktinden önce" },
    ],
    patterns: [
      { de: "Die Rente dürfte …", tr: "temkinli tahmin" },
      { de: "Wer früh anfängt, …", tr: "genel geçer kural" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün uzak bir geleceği konuşacağız ve orada hiçbir şey kesin değil. Tam da bu yüzden öznel kip fiilleri gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de Almancanın güzel bir kalıbı var: 'kim erken başlarsa' diye başlayan genel geçer cümleler. Öğüt vermeden öğüt verir. Önce kelimeler.")] },
      word("İlk", { de: "die Altersvorsorge", tr: "emeklilik birikimi" }),
      word("İkinci", { de: "die Rentenversicherung", tr: "emeklilik sigortası" }),
      word("Üçüncü", { de: "die Betriebsrente", tr: "işyeri emekliliği" }, "Devlet emekliliğinin üstüne işverenin katkısı."),
      word("Dördüncü", { de: "der Ruhestand", tr: "emeklilik" }),
      word("Beşinci", { de: "die Berufsunfähigkeit", tr: "iş göremezlik" }),
      word("Altıncı", { de: "der Zuschuss", tr: "sübvansiyon" }),
      word("Yedinci", { de: "die Lücke", tr: "boşluk" }),
      word("Son", { de: "vorzeitig", tr: "vaktinden önce" }),
      { say: [tr("Kalıbımız:"), de("Die Rente dürfte …"), tr("Tahmin; kesin konuşmadan uyarı yapar.")] },
      { say: [tr("Örnek:"), de("Die Rente dürfte für viele knapp werden."), tr("Tekrar edin:"), de("Die Rente dürfte für viele knapp werden")], expect: repeat("Die Rente dürfte für viele knapp werden") },
      { say: [tr("Sıra sende: 'Erken başlayan daha az yatırır.'")], expect: produce("Wer früh anfängt, zahlt weniger ein", [tr("Yan cümle özne yerine geçer; ana cümlede önek sonda:"), de("Wer früh anfängt, zahlt weniger ein."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi duyulan bilgiyle: 'Bir açık kalacakmış.'")], expect: produce("Es soll eine Lücke bleiben", [tr("Duyulan bilgi sollen ile; mastar sonda:"), de("Es soll eine Lücke bleiben."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Emeklilik birikimini zamanında düşünmek gerekir.'")], expect: produce("Man muss rechtzeitig an die Altersvorsorge denken", [tr("Bu fiilin sabit edatı an, belirtme hâliyle:"), de("Man muss rechtzeitig an die Altersvorsorge denken."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wie weit reicht der Betriebsrente?"), tr("cümlesi doğru mu?")], expect: truefalse("Wie weit reicht der Betriebsrente?", false, [tr("Bu isim dişildir ve burada özne olduğu için yalın hâlde durur:"), de("Wie weit reicht die Betriebsrente?")]) },
      { say: [tr("Son: 'İşyeri emekliliği ne kadar yeter?'")], expect: produce("Wie weit reicht die Betriebsrente", [tr("Dişil özne yalın hâlde:"), de("Wie weit reicht die Betriebsrente?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada emeklilik planını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir danışmanla emeklilik planını konuşuyorsun: bugüne kadar ne yatırdın, ne kadar açık kalacak, ne yapabilirsin. Kesin, olası ve duyulan bilgiyi ayır.",
      partner: "rakamlarla konuşan, aceleye getirmeyen bir emeklilik danışmanı",
      opening: "Viele schieben das Thema auf. Sagen Sie mir zuerst: Was haben Sie bisher schon eingezahlt?",
      openingTr: "Çoğu kişi bu konuyu erteliyor. Önce şunu söyleyin: Şimdiye kadar ne yatırdınız?",
      goal: "Mevcut durum, beklenen açık ve atılabilecek somut bir adım konuşulmuş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-nebenjob",
    icon: "job",
    level: "B2",
    course: "de",
    title: "Das zweite Standbein",
    titleTr: "Ek iş",
    summary: "Ek işin koşullarını Genitiv edatlarıyla konuşmayı öğretir.",
    minutes: 12,
    focusId: "Genitivpräpositionen",
    vocab: [
      { de: "nebenberuflich", tr: "yan iş olarak" },
      { de: "die Genehmigung", tr: "izin" },
      { de: "die Sozialversicherung", tr: "sosyal sigorta" },
      { de: "das Arbeitslosengeld", tr: "işsizlik maaşı" },
      { de: "aufstocken", tr: "takviye etmek" },
      { de: "einträglich", tr: "gelir getiren" },
      { de: "unentgeltlich", tr: "bedelsiz" },
      { de: "die Erschöpfung", tr: "tükenmişlik" },
    ],
    patterns: [
      { de: "während der Woche", tr: "süre bildirir" },
      { de: "trotz der Belastung", tr: "zıtlık bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ek işi konuşacağız ve tamlayan hâli isteyen edatlar burada çok işine yarayacak: hafta içinde, yüke rağmen, yorgunluk yüzünden. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu edatları altıncı modülde çalışmıştın; burada kendi hayatın için kullanacaksın. Önce kelimeler.")] },
      word("İlk", { de: "nebenberuflich", tr: "yan iş olarak" }),
      word("İkinci", { de: "die Genehmigung", tr: "izin" }),
      word("Üçüncü", { de: "die Sozialversicherung", tr: "sosyal sigorta" }),
      word("Dördüncü", { de: "das Arbeitslosengeld", tr: "işsizlik maaşı" }),
      word("Beşinci", { de: "aufstocken", tr: "takviye etmek" }, "Az olan bir geliri üstüne ekleyerek yükseltmek."),
      word("Altıncı", { de: "einträglich", tr: "gelir getiren" }),
      word("Yedinci", { de: "unentgeltlich", tr: "bedelsiz" }),
      word("Son", { de: "die Erschöpfung", tr: "tükenmişlik" }),
      { say: [tr("Kalıbımız:"), de("während der Woche"), tr("Süre bildiren edat, tamlayan hâliyle.")] },
      { say: [tr("Örnek:"), de("Trotz der Belastung mache ich weiter."), tr("Tekrar edin:"), de("Trotz der Belastung mache ich weiter")], expect: repeat("Trotz der Belastung mache ich weiter") },
      { say: [tr("Sıra sende: 'Hafta içinde yan iş olarak çalışıyorum.'")], expect: produce("Während der Woche arbeite ich nebenberuflich", [tr("Tümleç başta, fiil ikinci sırada:"), de("Während der Woche arbeite ich nebenberuflich."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İşsizlik maaşı kirayı karşılamıyor.'")], expect: produce("Das Arbeitslosengeld deckt die Miete nicht", [tr("Nesne belirtme hâlinde; olumsuzluk en sonda:"), de("Das Arbeitslosengeld deckt die Miete nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İşverenin izni gerekiyor.'")], expect: produce("Eine Genehmigung des Arbeitgebers ist nötig", [tr("Eril isim tamlamada -s ekini alır:"), de("Eine Genehmigung des Arbeitgebers ist nötig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Während der Woche arbeite ich nebenberuflich."), tr("cümlesi doğru mu?")], expect: truefalse("Während der Woche arbeite ich nebenberuflich.", true, [tr("Doğru. Edattan sonra tamlayan hâli var ve tümleç başta olduğu için fiil ikinci sırada.")]) },
      { say: [tr("Son: 'Yorgunluk yüzünden azalttım.'")], expect: produce("Wegen der Erschöpfung habe ich reduziert", [tr("Sebep bildiren edat tamlayan hâli ister:"), de("Wegen der Erschöpfung habe ich reduziert."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada ek iş yapmayı konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla ek iş yapmayı konuşuyorsunuz: neden gerekiyor, ne kadar zaman alıyor, izin gerekiyor mu ve yük ne zaman fazla gelir. Sebep ve zıtlığı Genitiv edatlarıyla kur.",
      partner: "ek iş yapan, deneyimini paylaşan bir arkadaş",
      opening: "Ich mache das seit einem Jahr nebenbei. Ehrlich gesagt hätte ich vorher ein paar Sachen wissen sollen — was willst du wissen?",
      openingTr: "Ben bunu bir yıldır ek olarak yapıyorum. Açıkçası önceden birkaç şeyi bilmeliydim — sen ne öğrenmek istiyorsun?",
      goal: "Ek işin sebebi, zaman yükü ve izin koşulu konuşulmuş ve yapılıp yapılmayacağına dair bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-teures-hobby",
    icon: "sport",
    level: "B2",
    course: "de",
    title: "Das Hobby, das Geld frisst",
    titleTr: "Pahalı hobiler",
    summary: "Masraflı bir uğraşı sahiplik ilgi cümleleriyle savunmayı öğretir.",
    minutes: 12,
    focusId: "Relativsatz-Genitiv",
    vocab: [
      { de: "die Ausrüstung", tr: "ekipman" },
      { de: "die Leidenschaft", tr: "tutku" },
      { de: "die Mitgliedschaft", tr: "üyelik" },
      { de: "der Zeitvertreib", tr: "vakit geçirme" },
      { de: "die Ratenzahlung", tr: "taksitle ödeme" },
      { de: "der Haushaltsplan", tr: "bütçe planı" },
      { de: "kostspielig", tr: "masraflı" },
      { de: "maßvoll", tr: "ölçülü" },
    ],
    patterns: [
      { de: "ein Hobby, dessen Kosten …", tr: "sahiplik ilgi cümlesi" },
      { de: "Das ist es mir wert.", tr: "değer yargısı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve konusu keyifli: pahalı hobiler. Ama dilbilgisi ciddi — sahiplik bildiren ilgi cümlesini bir kez daha, bu kez fiil uyumuna dikkat ederek kuracağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dikkat: ilgi zamiri önceki ismin cinsine göre seçilir ama FİİL sonraki ismin sayısına uyar. İki ayrı yere bakman gerekiyor. Önce kelimeler.")] },
      word("İlk", { de: "die Ausrüstung", tr: "ekipman" }),
      word("İkinci", { de: "die Leidenschaft", tr: "tutku" }),
      word("Üçüncü", { de: "die Mitgliedschaft", tr: "üyelik" }),
      word("Dördüncü", { de: "der Zeitvertreib", tr: "vakit geçirme" }, "Hobiye göre daha hafif: sadece vakit geçirme."),
      word("Beşinci", { de: "die Ratenzahlung", tr: "taksitle ödeme" }),
      word("Altıncı", { de: "der Haushaltsplan", tr: "bütçe planı" }),
      word("Yedinci", { de: "kostspielig", tr: "masraflı" }),
      word("Son", { de: "maßvoll", tr: "ölçülü" }),
      { say: [tr("Kalıbımız:"), de("ein Hobby, dessen Kosten steigen"), tr("Zamir nötr isme göre dessen, fiil ise çoğul olan masraflara göre çoğul.")] },
      { say: [tr("Örnek:"), de("Ein Hobby, dessen Kosten steigen, macht trotzdem Freude."), tr("Tekrar edin:"), de("Ein Hobby, dessen Kosten steigen, macht trotzdem Freude")], expect: repeat("Ein Hobby, dessen Kosten steigen, macht trotzdem Freude") },
      { say: [tr("Sıra sende: 'Ekipmanı pahalı olan bir spor.'")], expect: produce("Ein Sport, dessen Ausrüstung teuer ist", [tr("Eril isimden sonra dessen; fiil tekil isme uyar:"), de("Ein Sport, dessen Ausrüstung teuer ist."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu bana değer.'")], expect: produce("Das ist es mir wert", [tr("Kalıplaşmış ifade; zamir sırası sabit:"), de("Das ist es mir wert."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ölçülü harcamayı öğrendim.'")], expect: produce("Ich habe gelernt, maßvoll auszugeben", [tr("Mastar öbeğinde ayrılabilen fiil zu'yu ortasına alır:"), de("Ich habe gelernt, maßvoll auszugeben."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ein Hobby, dessen Kosten steigt, macht trotzdem Freude."), tr("cümlesi doğru mu?")], expect: truefalse("Ein Hobby, dessen Kosten steigt, macht trotzdem Freude.", false, [tr("Fiil zamire değil arkasındaki isme uyar ve masraflar çoğuldur:"), de("Ein Hobby, dessen Kosten steigen, macht trotzdem Freude.")]) },
      { say: [tr("Son: 'Üyelik epey masraflı.'")], expect: produce("Die Mitgliedschaft ist ziemlich kostspielig", [tr("Kısa bir hüküm cümlesi; zarf sıfattan önce:"), de("Die Mitgliedschaft ist ziemlich kostspielig."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada pahalı bir uğraşını savunacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığın pahalı hobine şaşırıyor. Neye ne kadar harcadığını anlat, neden değdiğini savun, karşılığında neyden vazgeçtiğini söyle ve ölçünün ne olduğunu açıkla.",
      partner: "harcamayı gereksiz bulan, ama merak eden bir tanıdık",
      opening: "So viel Geld für ein Hobby, dessen Nutzen ich nicht sehe — was bringt dir das eigentlich?",
      openingTr: "Faydasını göremediğim bir hobiye bu kadar para — sana ne katıyor bu aslında?",
      goal: "Harcamanın büyüklüğü, neden değdiği ve neyden vazgeçildiği anlatılmış; karşı taraf en azından anladığını söylemiş olur.",
      minTurns: 8,
    },
  },
];
