import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B1 · Modül 9 — Çevre ve şehir yaşamı (081–090).
 *
 * Modülün dili TOPLUMSAL: kişisel bir istek değil, herkesi ilgilendiren bir
 * düzen anlatılıyor. Almanca bunu iki yapıyla kuruyor ve modül ikisini
 * dönüşümlü çalıştırıyor — edilgen (Papier wird getrennt entsorgt: kim
 * yaptığı değil kuralın kendisi önemli) ve amaç cümlesi (Um Strom zu sparen:
 * neden böyle yapıldığı).
 *
 * İkisi bir arada olduğunda ortaya çıkan şey, Almanya'da her gün duyulan
 * cümle biçimidir: kural artı gerekçe. Bir mahalle panosunda, bir belediye
 * duyurusunda, bir apartman toplantısında hep bu ikisi yan yana durur.
 *
 * Son iki ders bilinçli olarak kişiselleşiyor (gösteri ve barınak): toplumsal
 * dilin sonu bir istatistik değil, birinin neden orada durduğudur.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB1B09: Lesson[] = [
  {
    id: "de-b1-muelltrennung",
    icon: "recycle",
    level: "B1",
    course: "de",
    title: "Richtig trennen",
    titleTr: "Çöp ayrıştırma",
    summary: "Çöp ayrıştırma kurallarını edilgen cümlelerle anlamayı ve sormayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Mülltrennung", tr: "çöp ayrıştırma" },
      { de: "entsorgen", tr: "atmak (kurala göre)" },
      { de: "das Pfand", tr: "depozito" },
      { de: "die Tonne", tr: "çöp konteyneri" },
      { de: "sortieren", tr: "ayırmak" },
    ],
    patterns: [
      { de: "Papier wird getrennt entsorgt.", tr: "kuralı edilgen anlatır" },
      { de: "Was gehört in …?", tr: "hangisinin nereye gittiğini sorar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Almanya'ya yeni gelenin ilk şaşırdığı şey: çöp bir değil, dört beş kutu. Bugün o kuralların dilini öğreneceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural anlatan cümlelerde kimin yaptığı söylenmez, çünkü kural herkes için aynıdır. Bu yüzden dil edilgendir. Önce kelimeler.")] },
      word("İlk", { de: "die Mülltrennung", tr: "çöp ayrıştırma" }),
      word("İkinci", { de: "entsorgen", tr: "atmak (kurala göre)" }),
      word("Üçüncü", { de: "das Pfand", tr: "depozito" }),
      word("Dördüncü", { de: "die Tonne", tr: "çöp konteyneri" }),
      word("Son", { de: "sortieren", tr: "ayırmak" }),
      { say: [tr("Kalıbımız:"), de("Papier wird getrennt entsorgt."), tr("Yardımcı fiil ikinci sırada, ortaç en sonda. Kuralın kendisi konuşuyor.")] },
      { say: [tr("Örnek:"), de("Glas wird nach Farben sortiert."), tr("Lütfen tekrar edin:"), de("Glas wird nach Farben sortiert")], expect: repeat("Glas wird nach Farben sortiert") },
      { say: [tr("Sıra sende: 'Şişeler markete geri götürülüyor.'")], expect: produce("Die Flaschen werden zum Supermarkt zurückgebracht", [tr("Çoğul özne, çoğul yardımcı fiil, ortaç sonda:"), de("Die Flaschen werden zum Supermarkt zurückgebracht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi soruyu sor: 'Bu hangi konteynere gidiyor?'")], expect: produce("In welche Tonne gehört das", [tr("Soru öbeği başta, fiil ikinci sırada:"), de("In welche Tonne gehört das?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Depozito kasada geri alınıyor.'")], expect: produce("Das Pfand wird an der Kasse zurückgezahlt", [tr("Yer tümleci ortada, ortaç sonda:"), de("Das Pfand wird an der Kasse zurückgezahlt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Papier wird entsorgt getrennt."), tr("cümlesi doğru mu?")], expect: truefalse("Papier wird entsorgt getrennt.", false, [tr("Ortaç en sona gider, zarf onun önünde durur:"), de("Papier wird getrennt entsorgt.")]) },
      { say: [tr("Son: 'Çöp ayrıştırma başta zor geliyor.'")], expect: produce("Am Anfang ist die Mülltrennung schwierig", [tr("Zaman tümleci başta, fiil ikinci sırada:"), de("Am Anfang ist die Mülltrennung schwierig."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir komşuya çöp kurallarını soracaksın: hangisi nereye, depozito nasıl işliyor.")] },
    ],
    roleplay: {
      scene: "Yeni taşındığın binada bir komşuya çöp kurallarını soruyorsun: hangi çöp hangi konteynere, depozito nasıl geri alınıyor, hangi gün toplanıyor.",
      partner: "kuralları iyi bilen, biraz titiz bir komşu",
      opening: "Sie sind neu hier, oder? Beim Müll machen am Anfang alle Fehler — was möchten Sie wissen?",
      openingTr: "Yeni taşındınız, değil mi? Çöp konusunda başta herkes hata yapar — ne öğrenmek istersiniz?",
      goal: "Hangi çöpün nereye gittiği ve depozitonun nasıl geri alındığı öğrenilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-energie-sparen",
    icon: "idea",
    level: "B1",
    course: "de",
    title: "Strom sparen",
    titleTr: "Enerji tasarrufu",
    summary: "Bir davranışın amacını um … zu ile söylemeyi ve tasarrufu anlatmayı öğretir.",
    minutes: 10,
    focusId: "Um-zu",
    vocab: [
      { de: "der Strom", tr: "elektrik" },
      { de: "der Verbrauch", tr: "tüketim" },
      { de: "die Glühbirne", tr: "ampul" },
      { de: "senken", tr: "düşürmek" },
      { de: "die Stromrechnung", tr: "elektrik faturası" },
    ],
    patterns: [
      { de: "Um Strom zu sparen, …", tr: "amaç öbeği cümlenin başında" },
      { de: "Es lohnt sich, … zu …", tr: "değer olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün amaç cümlesini bir yere daha koyacağız: başa. Amaç önce söylenince cümle bir tavsiye gibi durur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amaç öbeği başta duruyorsa ana cümle fiille başlar — koşul cümlelerinde olduğu gibi. Kural aynı kural. Önce kelimeler.")] },
      word("İlk", { de: "der Strom", tr: "elektrik" }),
      word("İkinci", { de: "der Verbrauch", tr: "tüketim" }),
      word("Üçüncü", { de: "die Glühbirne", tr: "ampul" }),
      word("Dördüncü", { de: "senken", tr: "düşürmek" }),
      word("Son", { de: "die Stromrechnung", tr: "elektrik faturası" }),
      { say: [tr("Kalıbımız:"), de("Um Strom zu sparen, …"), tr("Amaç önde, sonra virgül, sonra fiille başlayan ana cümle.")] },
      { say: [tr("Örnek:"), de("Um Strom zu sparen, schalte ich die Geräte ganz aus."), tr("Tekrar edin:"), de("Um Strom zu sparen, schalte ich die Geräte ganz aus")], expect: repeat("Um Strom zu sparen, schalte ich die Geräte ganz aus") },
      { say: [tr("Sıra sende: 'Tüketimi düşürmek için ampulleri değiştirdim.'")], expect: produce("Um den Verbrauch zu senken, habe ich die Glühbirnen gewechselt", [tr("Amaç öbeği başta, ana cümle yardımcı fiille başlar:"), de("Um den Verbrauch zu senken, habe ich die Glühbirnen gewechselt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bunu yapmaya değer.'")], expect: produce("Es lohnt sich, das zu machen", [tr("Sahte özne, sonra mastar öbeği:"), de("Es lohnt sich, das zu machen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Elektrik faturam üçte bir azaldı.'")], expect: produce("Meine Stromrechnung ist um ein Drittel gesunken", [tr("Azalma miktarı bir edatla verilir:"), de("Meine Stromrechnung ist um ein Drittel gesunken."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Um Strom zu sparen, mache ich das Licht aus."), tr("cümlesi doğru mu?")], expect: truefalse("Um Strom zu sparen, mache ich das Licht aus.", true, [tr("Doğru. Amaç öbeği başta, ana cümle fiille başlıyor ve ayrılabilen fiilin öneki sonda.")]) },
      { say: [tr("Son: 'Küçük adımlar da işe yarıyor.'")], expect: produce("Auch kleine Schritte helfen", [tr("Çoğul özne, çoğul fiil:"), de("Auch kleine Schritte helfen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir ev arkadaşınla faturayı konuşacaksın: neyi neden değiştireceksin.")] },
    ],
    roleplay: {
      scene: "Ev arkadaşınla yükselen elektrik faturasını konuşuyorsun: neyi değiştirmeyi öneriyorsun ve neden. Önerilerinin amacını um … zu ile söyle.",
      partner: "tasarrufa mesafeli, rahatını seven bir ev arkadaşı",
      opening: "Die Stromrechnung ist echt hoch geworden. Aber ich will nicht im Dunkeln sitzen — was schlägst du vor?",
      openingTr: "Elektrik faturası cidden yükseldi. Ama karanlıkta oturmak da istemiyorum — ne öneriyorsun?",
      goal: "En az iki öneri amacıyla birlikte sunulmuş ve biri üzerinde anlaşılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-verkehrswende",
    icon: "bike",
    level: "B1",
    course: "de",
    title: "Auto oder Rad?",
    titleTr: "Ulaşım tartışması",
    summary: "Ulaşım tercihini ikili bağlaçlarla tartmayı ve kendi tercihini savunmayı öğretir.",
    minutes: 10,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "das Verkehrsmittel", tr: "ulaşım aracı" },
      { de: "der Parkplatz", tr: "otopark" },
      { de: "die Luft", tr: "hava" },
      { de: "der Ausbau", tr: "genişletme" },
      { de: "die Strecke", tr: "güzergâh" },
    ],
    patterns: [
      { de: "Einerseits bequem, andererseits teuer.", tr: "iki tarafı yan yana koyar" },
      { de: "nicht nur …, sondern auch …", tr: "ikinci bir sebep ekler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün şehirlerin en tartışmalı konusu: araba mı bisiklet mi. Tartışmada güçlü olmak için iki tarafı da söyleyebilmek gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkili bağlaçları biliyorsun; bugün onları toplumsal bir konuda çalıştıracağız. Bir de tercih değişimini anlatmayı öğreneceğiz. Önce kelimeler.")] },
      word("İlk", { de: "das Verkehrsmittel", tr: "ulaşım aracı" }),
      word("İkinci", { de: "der Parkplatz", tr: "otopark" }),
      word("Üçüncü", { de: "die Luft", tr: "hava" }),
      word("Dördüncü", { de: "der Ausbau", tr: "genişletme" }),
      word("Son", { de: "die Strecke", tr: "güzergâh" }),
      { say: [tr("Kalıbımız:"), de("Einerseits bequem, andererseits teuer."), tr("Kısa biçim: fiil bile atılabilir. Konuşmada çok kullanılıyor.")] },
      { say: [tr("Örnek:"), de("Das Auto ist einerseits bequem, andererseits teuer."), tr("Tekrar edin:"), de("Das Auto ist einerseits bequem, andererseits teuer")], expect: repeat("Das Auto ist einerseits bequem, andererseits teuer") },
      { say: [tr("Sıra sende: 'Bisiklet yalnızca ucuz değil, aynı zamanda hızlı.'")], expect: produce("Das Rad ist nicht nur billig, sondern auch schnell", [tr("İkinci parça virgülden sonra:"), de("Das Rad ist nicht nur billig, sondern auch schnell."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Merkezde otopark bulmak zor.'")], expect: produce("In der Innenstadt ist es schwer, einen Parkplatz zu finden", [tr("Sahte özne, sonra mastar öbeği:"), de("In der Innenstadt ist es schwer, einen Parkplatz zu finden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Geçen yıl bisiklete geçtim.'")], expect: produce("Letztes Jahr bin ich aufs Rad umgestiegen", [tr("Zaman tümleci başta, ortaç sonda:"), de("Letztes Jahr bin ich aufs Rad umgestiegen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Rad ist nicht nur billig, aber auch schnell."), tr("cümlesi doğru mu?")], expect: truefalse("Das Rad ist nicht nur billig, aber auch schnell.", false, [tr("İkili bağlacın ikinci parçası başka bir kelimedir:"), de("Das Rad ist nicht nur billig, sondern auch schnell.")]) },
      { say: [tr("Son: 'Bisiklet yollarının genişletilmesi herkese yarıyor.'")], expect: produce("Der Ausbau der Radwege hilft allen", [tr("Uzun özne öbeği, sonra fiil, sonra yönelme nesnesi:"), de("Der Ausbau der Radwege hilft allen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir meslektaşınla işe nasıl gidildiğini tartışacaksın: iki tarafı da söyle, kendi tercihini savun.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşınla işe nasıl gidildiğini tartışıyorsun: araba mı, bisiklet mi, toplu taşıma mı. İki tarafı ikili bağlaçlarla koy ve kendi tercihini gerekçelendir.",
      partner: "arabasına bağlı, pratik düşünen bir meslektaş",
      opening: "Du fährst jetzt jeden Tag mit dem Rad? Bei dem Wetter? Also ich bleibe beim Auto — überzeug mich mal.",
      openingTr: "Artık her gün bisikletle mi gidiyorsun? Bu havada? Ben arabada kalıyorum — hadi ikna et beni.",
      goal: "İki tarafın artı ve eksileri söylenmiş ve kendi tercihin gerekçesiyle savunulmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-nachhaltig-einkaufen",
    icon: "shopping",
    level: "B1",
    course: "de",
    title: "Bewusst konsumieren",
    titleTr: "Sürdürülebilir tüketim",
    summary: "Ürün ve mağazaları ilgi cümleleriyle tanımlayarak tercihini anlatmayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Nominativ",
    vocab: [
      { de: "nachhaltig", tr: "sürdürülebilir" },
      { de: "die Verpackung", tr: "ambalaj" },
      { de: "regional", tr: "yöresel" },
      { de: "die Herkunft", tr: "menşe" },
      { de: "vermeiden", tr: "kaçınmak" },
    ],
    patterns: [
      { de: "Produkte, die …", tr: "ürünü özelliğiyle tanımlar" },
      { de: "Läden, in denen …", tr: "mağazayı yeriyle tanımlar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün alışverişte tercih anlatacağız — ama marka adıyla değil, ÖZELLİKLE. Bunun için ilgi cümlesine dönüyoruz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir hatırlatma: çoğul isimlerde ilgi zamiri die, edatlı hâlde ise çoğulda denen olur. İkisini de kullanacağız. Önce kelimeler.")] },
      word("İlk", { de: "nachhaltig", tr: "sürdürülebilir" }),
      word("İkinci", { de: "die Verpackung", tr: "ambalaj" }),
      word("Üçüncü", { de: "regional", tr: "yöresel" }),
      word("Dördüncü", { de: "die Herkunft", tr: "menşe" }),
      word("Son", { de: "vermeiden", tr: "kaçınmak" }),
      { say: [tr("Kalıbımız:"), de("Produkte, die regional sind, kaufe ich lieber."), tr("Tanımlanan kelime çoğul olduğu için zamir die ve fiil de çoğul.")] },
      { say: [tr("Tekrar edin:"), de("Produkte, die regional sind, kaufe ich lieber")], expect: repeat("Produkte, die regional sind, kaufe ich lieber") },
      { say: [tr("Sıra sende: 'Çok ambalajı olan ürünlerden kaçınıyorum.'")], expect: produce("Ich vermeide Produkte, die viel Verpackung haben", [tr("Çoğulda zamir die, fiil yan cümlenin sonunda:"), de("Ich vermeide Produkte, die viel Verpackung haben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi edatlı hâlde: 'Ambalajsız satan dükkânlar var.'")], expect: produce("Es gibt Läden, in denen man ohne Verpackung kauft", [tr("Çoğulda edatlı ilgi zamiri denen olur:"), de("Es gibt Läden, in denen man ohne Verpackung kauft."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, soru sor: 'Bunun menşei nedir?'")], expect: produce("Was ist die Herkunft von diesem Produkt", [tr("Soru kelimesi başta, edat öbeği sonda:"), de("Was ist die Herkunft von diesem Produkt?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich kaufe Produkte, das aus der Region kommen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich kaufe Produkte, das aus der Region kommen.", false, [tr("Tanımlanan kelime çoğul olduğu için ilgi zamiri de çoğul olur:"), de("Ich kaufe Produkte, die aus der Region kommen.")]) },
      { say: [tr("Son: 'Sürdürülebilir alışveriş her zaman daha pahalı değil.'")], expect: produce("Nachhaltig einkaufen ist nicht immer teurer", [tr("Mastar öbeği özne gibi kullanılıyor:"), de("Nachhaltig einkaufen ist nicht immer teurer."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla alışveriş alışkanlıklarını konuşacaksın: neyi tercih ediyorsun, neden.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla alışveriş alışkanlıklarınızı konuşuyorsunuz: hangi ürünleri tercih ediyorsun, hangi dükkânlara gidiyorsun, neden. Tercihlerini ilgi cümleleriyle tanımla.",
      partner: "fiyatı önemseyen, ikna olmaya açık bir arkadaş",
      opening: "Du kaufst jetzt nur noch im Unverpackt-Laden? Ist das nicht viel teurer? Erzähl mal.",
      openingTr: "Artık sadece ambalajsız dükkândan mı alıyorsun? Çok daha pahalı değil mi? Anlatsana.",
      goal: "Hangi ürünleri ve dükkânları tercih ettiğin gerekçesiyle anlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-garten-projekt",
    icon: "flower",
    level: "B1",
    course: "de",
    title: "Der Gemeinschaftsgarten",
    titleTr: "Ortak bahçe",
    summary: "Ortak bir projenin kurallarını edilgen cümlelerle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "der Gemeinschaftsgarten", tr: "ortak bahçe" },
      { de: "pflanzen", tr: "dikmek" },
      { de: "die Ernte", tr: "hasat" },
      { de: "das Beet", tr: "tarh" },
      { de: "sich beteiligen", tr: "katılmak" },
    ],
    patterns: [
      { de: "Es wird gepflanzt.", tr: "öznesiz edilgen: iş yapılıyor" },
      { de: "Die Ernte wird geteilt.", tr: "ortak kuralı anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir mahalle projesindeyiz: ortak bahçe. Ortak işlerde kurallar kişisel değildir, o yüzden dil yine edilgen. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de öznesiz edilgen öğreneceğiz: kimse söylenmeden yalnızca işin yapıldığı bildirilir. Almancada bu çok yaygın. Önce kelimeler.")] },
      word("İlk", { de: "der Gemeinschaftsgarten", tr: "ortak bahçe" }),
      word("İkinci", { de: "pflanzen", tr: "dikmek" }),
      word("Üçüncü", { de: "die Ernte", tr: "hasat" }),
      word("Dördüncü", { de: "das Beet", tr: "tarh" }),
      word("Son", { de: "sich beteiligen", tr: "katılmak" }),
      { say: [tr("Kalıbımız:"), de("Samstags wird gepflanzt."), tr("Gerçek bir özne yok; cümle yalnızca işin yapıldığını söylüyor.")] },
      { say: [tr("Tekrar edin:"), de("Samstags wird gepflanzt")], expect: repeat("Samstags wird gepflanzt") },
      { say: [tr("Sıra sende: 'Hasat herkes arasında paylaşılıyor.'")], expect: produce("Die Ernte wird unter allen geteilt", [tr("Tekil özne, ortaç sonda:"), de("Die Ernte wird unter allen geteilt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Her tarhtan bir kişi sorumlu.'")], expect: produce("Für jedes Beet ist eine Person verantwortlich", [tr("Tümleç başta, fiil ikinci sırada:"), de("Für jedes Beet ist eine Person verantwortlich."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İsteyen herkes katılabilir.'")], expect: produce("Jeder, der möchte, kann sich beteiligen", [tr("İlgi cümlesi araya giriyor, modal fiil sonra:"), de("Jeder, der möchte, kann sich beteiligen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Im Frühling wird viel gepflanzt."), tr("cümlesi doğru mu?")], expect: truefalse("Im Frühling wird viel gepflanzt.", true, [tr("Doğru. Öznesiz edilgen: yardımcı fiil ikinci sırada, ortaç en sonda.")]) },
      { say: [tr("Son: 'Aletler kulübede saklanıyor.'")], expect: produce("Die Werkzeuge werden im Schuppen aufbewahrt", [tr("Çoğul özne, çoğul yardımcı fiil:"), de("Die Werkzeuge werden im Schuppen aufbewahrt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bahçeye katılmak isteyen birine kuralları anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Ortak bahçeye katılmak isteyen birine kuralları anlatıyorsun: ne zaman çalışılıyor, hasat nasıl paylaşılıyor, kim neyden sorumlu. Kuralları edilgen cümlelerle söyle.",
      partner: "hevesli ama hiçbir şey bilmeyen yeni bir katılımcı",
      opening: "Ich würde gern mitmachen. Wie läuft das hier eigentlich ab — muss man jede Woche kommen?",
      openingTr: "Katılmak isterim. Burada işler nasıl yürüyor — her hafta gelmek gerekiyor mu?",
      goal: "Çalışma günü, hasat paylaşımı ve sorumluluklar anlatılmış; yeni katılımcı kararını söylemiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-wetterextrem",
    icon: "sun",
    level: "B1",
    course: "de",
    title: "Immer heißere Sommer",
    titleTr: "İklim gözlemi",
    summary: "Bir değişimi karşılaştırma biçimleriyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "die Hitze", tr: "sıcaklık (bunaltıcı)" },
      { de: "die Dürre", tr: "kuraklık" },
      { de: "das Hochwasser", tr: "sel" },
      { de: "zunehmen", tr: "artmak" },
      { de: "der Klimawandel", tr: "iklim değişikliği" },
    ],
    patterns: [
      { de: "immer heißer", tr: "sürekli artan değişim" },
      { de: "im Vergleich zu früher", tr: "geçmişle karşılaştırma" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir DEĞİŞİMİ anlatmayı öğreneceğiz: bir şeyin gitgide artması. Almancada bunun çok kısa bir kalıbı var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karşılaştırma biçiminin önüne tek bir kelime konuyor ve anlam 'gitgide daha' oluyor. Türkçede 'gitgide, giderek' diyoruz. Önce kelimeler.")] },
      word("İlk", { de: "die Hitze", tr: "sıcaklık (bunaltıcı)" }),
      word("İkinci", { de: "die Dürre", tr: "kuraklık" }),
      word("Üçüncü", { de: "das Hochwasser", tr: "sel" }),
      word("Dördüncü", { de: "zunehmen", tr: "artmak" }),
      word("Son", { de: "der Klimawandel", tr: "iklim değişikliği" }),
      { say: [tr("Kalıbımız:"), de("immer heißer"), tr("Karşılaştırma biçiminin önündeki kelime değişimin sürekliliğini gösteriyor.")] },
      { say: [tr("Örnek:"), de("Die Sommer werden immer heißer."), tr("Tekrar edin:"), de("Die Sommer werden immer heißer")], expect: repeat("Die Sommer werden immer heißer") },
      { say: [tr("Sıra sende: 'Kuraklık gitgide uzuyor.'")], expect: produce("Die Dürre wird immer länger", [tr("Tekil özne, karşılaştırma biçimi sonda:"), de("Die Dürre wird immer länger."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Eskiye göre çok daha az kar yağıyor.'")], expect: produce("Im Vergleich zu früher schneit es viel weniger", [tr("Tümleç başta, fiil ikinci sırada:"), de("Im Vergleich zu früher schneit es viel weniger."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sel sayısı artıyor.'")], expect: produce("Die Zahl der Hochwasser nimmt zu", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Die Zahl der Hochwasser nimmt zu."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Sommer werden immer mehr heiß."), tr("cümlesi doğru mu?")], expect: truefalse("Die Sommer werden immer mehr heiß.", false, [tr("Sıfat karşılaştırma biçimine girer, önüne ayrı bir kelime konmaz:"), de("Die Sommer werden immer heißer.")]) },
      { say: [tr("Son: 'İklim değişikliğini burada da fark ediyorsun.'")], expect: produce("Den Klimawandel merkt man auch hier", [tr("Nesne başa çekilebilir; fiil yine ikinci sırada:"), de("Den Klimawandel merkt man auch hier."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir komşuyla havanın nasıl değiştiğini konuşacaksın: eskiden nasıldı, şimdi nasıl.")] },
    ],
    roleplay: {
      scene: "Bir komşuyla havanın nasıl değiştiğini konuşuyorsun: eskiden nasıldı, şimdi nasıl, sen ne fark ediyorsun. Değişimi karşılaştırma biçimleriyle anlat.",
      partner: "yılları karşılaştırmayı seven, uzun süredir burada yaşayan bir komşu",
      opening: "So einen Sommer hatten wir früher nie. Merken Sie das auch, oder bilde ich mir das ein?",
      openingTr: "Eskiden böyle bir yaz olmazdı. Siz de fark ediyor musunuz, yoksa bana mı öyle geliyor?",
      goal: "Eskisiyle bugün karşılaştırılmış ve senin fark ettiklerin anlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-ehrenamt",
    icon: "feelings",
    level: "B1",
    course: "de",
    title: "Das Ehrenamt",
    titleTr: "Gönüllülük",
    summary: "Gönüllü çalışmanın sebebini ve kazandırdığını anlatmayı öğretir.",
    minutes: 10,
    focusId: "Um-zu",
    vocab: [
      { de: "das Ehrenamt", tr: "gönüllü görev" },
      { de: "sich engagieren", tr: "gönüllü çalışmak" },
      { de: "freiwillig", tr: "gönüllü olarak" },
      { de: "die Verantwortung", tr: "sorumluluk" },
      { de: "sinnvoll", tr: "anlamlı" },
    ],
    patterns: [
      { de: "Ich engagiere mich, um … zu …", tr: "sebebi amaçla söyler" },
      { de: "Es gibt mir …", tr: "kazandırdığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Almanya'da çok yaygın bir şey var: parasız, gönüllü çalışmak. Bugün bunu anlatmayı öğreneceğiz — ve asıl soru şu: neden. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki kalıp yeter: neden yaptığın ve sana ne kazandırdığı. Birincisi amaç öbeği, ikincisi yönelme hâliyle kurulan bir cümle. Önce kelimeler.")] },
      word("İlk", { de: "das Ehrenamt", tr: "gönüllü görev" }),
      word("İkinci", { de: "sich engagieren", tr: "gönüllü çalışmak" }),
      word("Üçüncü", { de: "freiwillig", tr: "gönüllü olarak" }),
      word("Dördüncü", { de: "die Verantwortung", tr: "sorumluluk" }),
      word("Son", { de: "sinnvoll", tr: "anlamlı" }),
      { say: [tr("Kalıbımız:"), de("Ich engagiere mich, um zu helfen."), tr("Dönüşlü fiil ana cümlede, amaç öbeği virgülden sonra.")] },
      { say: [tr("Tekrar edin:"), de("Ich engagiere mich, um zu helfen")], expect: repeat("Ich engagiere mich, um zu helfen") },
      { say: [tr("Sıra sende: 'Bir şeyi değiştirmek için gönüllü çalışıyorum.'")], expect: produce("Ich engagiere mich, um etwas zu verändern", [tr("Amaç öbeğinde özne tekrar edilmez:"), de("Ich engagiere mich, um etwas zu verändern."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu bana anlamlı bir şey kazandırıyor.'")], expect: produce("Das gibt mir etwas Sinnvolles", [tr("Yönelme nesnesi önce, belirtme nesnesi sonra:"), de("Das gibt mir etwas Sinnvolles."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Haftada iki saat gönüllü çalışıyorum.'")], expect: produce("Ich arbeite zwei Stunden pro Woche freiwillig", [tr("Süre ortada, zarf sonda:"), de("Ich arbeite zwei Stunden pro Woche freiwillig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich engagiere mich, um anderen zu helfen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich engagiere mich, um anderen zu helfen.", true, [tr("Doğru. Yardım etmek fiili yönelme ister ve mastar en sonda duruyor.")]) },
      { say: [tr("Son: 'Bu görev çok sorumluluk gerektiriyor.'")], expect: produce("Diese Aufgabe verlangt viel Verantwortung", [tr("Etken cümle, nesne belirtme hâlinde:"), de("Diese Aufgabe verlangt viel Verantwortung."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir gönüllü kuruluşta tanışma görüşmesi yapacaksın: neden gelmek istiyorsun, ne verebilirsin.")] },
    ],
    roleplay: {
      scene: "Bir gönüllü kuruluşunda tanışma görüşmesindesin: neden gönüllü olmak istediğini, haftada ne kadar vaktin olduğunu ve ne yapabileceğini anlat.",
      partner: "sıcak ama gerçekçi bir gönüllü koordinatörü",
      opening: "Schön, dass Sie da sind. Sagen Sie mir zuerst: Warum möchten Sie sich bei uns engagieren?",
      openingTr: "Geldiğinize sevindim. Önce şunu söyleyin: Neden bizde gönüllü olmak istiyorsunuz?",
      goal: "Gönüllü olma sebebin, ayırabileceğin zaman ve yapabileceklerin anlatılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-stadtentwicklung",
    icon: "city",
    level: "B1",
    course: "de",
    title: "Unser Viertel verändert sich",
    titleTr: "Kentsel dönüşüm",
    summary: "Mahallede olan değişimi geçmiş edilgenle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "das Viertel", tr: "mahalle" },
      { de: "sanieren", tr: "yenilemek" },
      { de: "steigen", tr: "yükselmek" },
      { de: "verdrängen", tr: "yerinden etmek" },
      { de: "der Leerstand", tr: "boş duran konut" },
    ],
    patterns: [
      { de: "Das Haus wurde saniert.", tr: "geçmişte edilgen" },
      { de: "Die Mieten sind gestiegen.", tr: "değişimi anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün mahallenin nasıl değiştiğini anlatacağız. Değişimi kimin yaptığı çoğu zaman belli değildir; o yüzden dil yine edilgen. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Ama bir ayrım var: bazı değişimler kendiliğinden olur ve onlar edilgen değil, normal geçmişle söylenir. İkisini ayırmayı öğreneceğiz. Önce kelimeler.")] },
      word("İlk", { de: "das Viertel", tr: "mahalle" }),
      word("İkinci", { de: "sanieren", tr: "yenilemek" }),
      word("Üçüncü", { de: "steigen", tr: "yükselmek" }),
      word("Dördüncü", { de: "verdrängen", tr: "yerinden etmek" }),
      word("Son", { de: "der Leerstand", tr: "boş duran konut" }),
      { say: [tr("Kalıbımız:"), de("Das Haus wurde saniert."), tr("Birileri yaptı ama kim olduğu söylenmiyor. Kiraların yükselmesi ise kendiliğinden bir değişim.")] },
      { say: [tr("Örnek:"), de("Unser Haus wurde letztes Jahr saniert."), tr("Tekrar edin:"), de("Unser Haus wurde letztes Jahr saniert")], expect: repeat("Unser Haus wurde letztes Jahr saniert") },
      { say: [tr("Sıra sende: 'Eski fırın kapatıldı.'")], expect: produce("Die alte Bäckerei wurde geschlossen", [tr("Geçmiş edilgen: wurde artı ortaç:"), de("Die alte Bäckerei wurde geschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi kendiliğinden olanı söyle: 'Kiralar çok yükseldi.'")], expect: produce("Die Mieten sind stark gestiegen", [tr("Bu değişimi kimse yapmadı; hareket fiili sein ile çekilir:"), de("Die Mieten sind stark gestiegen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Eski komşuların çoğu buradan gitmek zorunda kaldı.'")], expect: produce("Viele alte Nachbarn mussten wegziehen", [tr("Modal fiil çekimli, mastar en sonda:"), de("Viele alte Nachbarn mussten wegziehen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Mieten wurden gestiegen."), tr("cümlesi doğru mu?")], expect: truefalse("Die Mieten wurden gestiegen.", false, [tr("Yükselmek eylemini kimse yapmıyor, yani edilgen kurulmaz:"), de("Die Mieten sind gestiegen.")]) },
      { say: [tr("Son: 'Boş dükkânlar hızla dolduruldu.'")], expect: produce("Der Leerstand wurde schnell gefüllt", [tr("Tekil özne, ortaç sonda:"), de("Der Leerstand wurde schnell gefüllt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada uzun zamandır burada yaşayan biriyle mahallenin değişimini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Mahallede uzun zamandır yaşayan biriyle değişimi konuşuyorsun: ne yenilendi, ne kapandı, kiralar ne oldu, kimler gitti. Değişimi geçmiş edilgenle anlat.",
      partner: "değişime kırgın, eski mahalleyi özleyen bir sakin",
      opening: "Sie hätten das Viertel vor zehn Jahren sehen sollen. Wissen Sie, was hier alles verschwunden ist?",
      openingTr: "Bu mahalleyi on yıl önce görmeliydiniz. Buradan nelerin kaybolduğunu biliyor musunuz?",
      goal: "Neyin yenilendiği, neyin kapandığı ve kiraların ne olduğu konuşulmuş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b1-demo",
    icon: "flag",
    level: "B1",
    course: "de",
    title: "Auf der Demo",
    titleTr: "Gösteride",
    summary: "Bir amaç uğruna orada olmayı damit cümlesiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-damit",
    vocab: [
      { de: "die Demo", tr: "gösteri" },
      { de: "das Transparent", tr: "pankart" },
      { de: "friedlich", tr: "barışçıl" },
      { de: "sich einsetzen", tr: "savunmak" },
      { de: "die Forderung", tr: "talep" },
    ],
    patterns: [
      { de: "Wir sind hier, damit …", tr: "amaç: özne farklı olduğunda damit" },
      { de: "Ich setze mich für … ein.", tr: "bir şeyi savunmak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir gösteride olacağız ve tek bir soru soracağız: neden buradasın. Cevabın kalıbı, özne değiştiği için damit. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Hatırlatma: özne aynıysa kısa yol, farklıysa damit. 'Ben buradayım ki ONLAR duysun' — özne farklı, yani damit. Önce kelimeler.")] },
      word("İlk", { de: "die Demo", tr: "gösteri" }),
      word("İkinci", { de: "das Transparent", tr: "pankart" }),
      word("Üçüncü", { de: "friedlich", tr: "barışçıl" }),
      word("Dördüncü", { de: "sich einsetzen", tr: "savunmak" }),
      word("Son", { de: "die Forderung", tr: "talep" }),
      { say: [tr("Kalıbımız:"), de("Wir sind hier, damit sich etwas ändert."), tr("Yan cümlede çekimli fiil en sona gider.")] },
      { say: [tr("Tekrar edin:"), de("Wir sind hier, damit sich etwas ändert")], expect: repeat("Wir sind hier, damit sich etwas ändert") },
      { say: [tr("Sıra sende: 'Politikacılar duysun diye buradayım.'")], expect: produce("Ich bin hier, damit die Politiker uns hören", [tr("Özne farklı olduğu için damit; fiil sona:"), de("Ich bin hier, damit die Politiker uns hören."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Daha iyi bisiklet yolları için mücadele ediyorum.'")], expect: produce("Ich setze mich für bessere Radwege ein", [tr("Dönüşlü fiilin öneki en sonda, edat belirtme ister:"), de("Ich setze mich für bessere Radwege ein."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Talebimiz açık.'")], expect: produce("Unsere Forderung ist klar", [tr("Kısa ve net bir cümle:"), de("Unsere Forderung ist klar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wir sind hier, damit wir zu ändern etwas."), tr("cümlesi doğru mu?")], expect: truefalse("Wir sind hier, damit wir zu ändern etwas.", false, [tr("Bu yapıda mastar öbeği kullanılmaz; yan cümle kurulur ve fiil sona gider:"), de("Wir sind hier, damit wir etwas ändern.")]) },
      { say: [tr("Son: 'Gösteri barışçıl kaldı.'")], expect: produce("Die Demo blieb friedlich", [tr("Yazı dilinin geçmişiyle kısa bir cümle:"), de("Die Demo blieb friedlich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir gazeteci sana neden orada olduğunu soracak.")] },
    ],
    roleplay: {
      scene: "Bir gösteride bir gazeteci seninle konuşuyor: neden buradasın, talebin ne, ne değişmesini istiyorsun. Amacını damit cümleleriyle anlat.",
      partner: "kısa ve net cevap isteyen bir yerel gazeteci",
      opening: "Entschuldigen Sie, kurz für unsere Zeitung: Warum sind Sie heute hier?",
      openingTr: "Affedersiniz, gazetemiz için kısaca: Bugün neden buradasınız?",
      goal: "Neden orada olduğun ve talebin söylenmiş; ne değişmesini istediğin anlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b1-tierheim",
    icon: "dog",
    level: "B1",
    course: "de",
    title: "Im Tierheim",
    titleTr: "Barınakta",
    summary: "Bir canlıyı yönelme hâlli ilgi cümleleriyle tanımlamayı ve sorumluluk konuşmayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Dativ",
    vocab: [
      { de: "das Tierheim", tr: "hayvan barınağı" },
      { de: "vermitteln", tr: "sahiplendirmek" },
      { de: "scheu", tr: "ürkek" },
      { de: "das Zuhause", tr: "yuva" },
      { de: "sich kümmern", tr: "ilgilenmek" },
    ],
    patterns: [
      { de: "Der Hund, dem wir helfen, …", tr: "yönelme hâlli ilgi cümlesi" },
      { de: "Wer übernimmt Verantwortung?", tr: "sorumluluk sorusu" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve en yumuşağı: barınak. Burada her hayvanın bir hikâyesi var ve hikâye anlatmak için ilgi cümlesi gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu kez yönelme hâlli ilgi cümlelerini kullanacağız — yardım etmek ve ilgilenmek gibi fiiller onu istiyor. Önce kelimeler.")] },
      word("İlk", { de: "das Tierheim", tr: "hayvan barınağı" }),
      word("İkinci", { de: "vermitteln", tr: "sahiplendirmek" }),
      word("Üçüncü", { de: "scheu", tr: "ürkek" }),
      word("Dördüncü", { de: "das Zuhause", tr: "yuva" }),
      word("Son", { de: "sich kümmern", tr: "ilgilenmek" }),
      { say: [tr("Kalıbımız:"), de("Der Hund, dem wir helfen, ist noch scheu."), tr("Yardım etmek yönelme ister, o yüzden erilde zamir dem.")] },
      { say: [tr("Tekrar edin:"), de("Der Hund, dem wir helfen, ist noch scheu")], expect: repeat("Der Hund, dem wir helfen, ist noch scheu") },
      { say: [tr("Sıra sende: 'İlgilendiğim kedi çok ürkek.'")], expect: produce("Die Katze, um die ich mich kümmere, ist sehr scheu", [tr("Bu dönüşlü fiilin edatı belirtme ister, o yüzden zamir die:"), de("Die Katze, um die ich mich kümmere, ist sehr scheu."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ona bir yuva arıyoruz.'")], expect: produce("Wir suchen ihm ein Zuhause", [tr("Yönelme nesnesi önce, belirtme nesnesi sonra:"), de("Wir suchen ihm ein Zuhause."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Geçen yıl iki yüz hayvan sahiplendirildi.'")], expect: produce("Letztes Jahr wurden zweihundert Tiere vermittelt", [tr("Zaman tümleci başta, çoğul edilgen:"), de("Letztes Jahr wurden zweihundert Tiere vermittelt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Hund, den wir helfen, ist scheu."), tr("cümlesi doğru mu?")], expect: truefalse("Der Hund, den wir helfen, ist scheu.", false, [de("helfen"), tr("yönelme ister, belirtme değil:"), de("Der Hund, dem wir helfen, ist scheu.")]) },
      { say: [tr("Son: 'Sorumluluğu kim alıyor?'")], expect: produce("Wer übernimmt die Verantwortung", [tr("Soru zamiri özne, fiil ikinci sırada:"), de("Wer übernimmt die Verantwortung?"), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada barınakta bir görevliyle konuşacaksın: hangi hayvan, nasıl bir yuva gerekiyor, ne sorumluluk getiriyor.")] },
    ],
    roleplay: {
      scene: "Barınakta bir görevliyle konuşuyorsun: hangi hayvanla ilgilenebilirsin, nasıl bir yuva gerekiyor, günlük sorumluluk ne. Hayvanları ilgi cümleleriyle tanımla.",
      partner: "hayvanları çok iyi tanıyan, dürüst bir barınak görevlisi",
      opening: "Kommen Sie mit, ich zeige Ihnen die Tiere. Suchen Sie ein Tier für sich oder für die Familie?",
      openingTr: "Gelin, size hayvanları göstereyim. Kendiniz için mi yoksa aile için mi bir hayvan arıyorsunuz?",
      goal: "Hangi hayvanla ilgilenebileceğin, nasıl bir yuva gerektiği ve günlük sorumluluk konuşulmuş olur.",
      minTurns: 9,
    },
  },
];
