import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B2 · Modül 4 — Medya ve aktarılan söz (031–040).
 *
 * Bu modülün öğrettiği asıl şey bir dilbilgisi kuralı değil, bir OKUMA
 * BİÇİMİ: bir cümlenin kim tarafından, hangi bağlayıcılıkla söylendiğini
 * dilin kendisinden görmek.
 *
 * Almanca bunu iki araçla yapıyor ve ikisi de Türkçede yok. Birincisi
 * aktarım kipi: "die Frist sei zu kurz" yazan bir tutanak o cümleyi
 * ONAYLAMIYOR, sadece aktarıyor. İkincisi öznel kip fiilleri: `soll`
 * başkasından duyulanı, `will` kişinin kendi iddiasını, `dürfte` konuşanın
 * tahminini bildiriyor — üçü de "-mış" ile çevrilir ama üçü ayrı kaynak
 * gösterir.
 *
 * Bu ayrımı görmeyen biri Almanca haber okuyabilir ama haberin ne kadarının
 * doğrulandığını göremez. Modül 4 tam olarak o görmeyi çalıştırıyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB2B04: Lesson[] = [
  {
    id: "de-b2-schlagzeilen",
    icon: "media",
    level: "B2",
    course: "de",
    title: "Hinter der Schlagzeile",
    titleTr: "Manşet dili",
    summary: "Manşetlerin fiilsiz, isimleşmiş dilini çözmeyi ve kurmayı öğretir.",
    minutes: 11,
    focusId: "Nominalisierung",
    vocab: [
      { de: "die Schlagzeile", tr: "manşet" },
      { de: "die Meldung", tr: "haber" },
      { de: "die Auseinandersetzung", tr: "çekişme, tartışma" },
      { de: "zuspitzen", tr: "keskinleştirmek" },
      { de: "knapp", tr: "kısa, az" },
    ],
    patterns: [
      { de: "Anstieg der …", tr: "fiilsiz manşet: … artışı" },
      { de: "Streit über …", tr: "… üzerine tartışma" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: medya. İlk ders manşetler ve manşetlerin garip bir özelliği var — çoğunda fiil yoktur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sebebi yer değil, ton: fiil olmayınca cümle olgu gibi durur, kimsenin yaptığı bir şey gibi değil. Manşet okumak bu yüzden dikkat ister. Önce kelimeler.")] },
      word("İlk", { de: "die Schlagzeile", tr: "manşet" }),
      word("İkinci", { de: "die Meldung", tr: "haber" }),
      word("Üçüncü", { de: "die Auseinandersetzung", tr: "çekişme, tartışma" }),
      word("Dördüncü", { de: "zuspitzen", tr: "keskinleştirmek" }),
      word("Son", { de: "knapp", tr: "kısa, az" }),
      { say: [tr("Kalıbımız:"), de("Anstieg der …"), tr("İsim artı tamlama; fiil yok, özne yok, sadece olgu var.")] },
      { say: [tr("Örnek:"), de("Anstieg der Mieten in den Großstädten."), tr("Tekrar edin:"), de("Anstieg der Mieten in den Großstädten")], expect: repeat("Anstieg der Mieten in den Großstädten") },
      { say: [tr("Sıra sende: 'Fiyatlarda yüzde üç artış.'")], expect: produce("Anstieg der Preise um drei Prozent", [tr("Tamlama hâli ve oran bildiren um edatı:"), de("Anstieg der Preise um drei Prozent."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yeni yasa üzerine tartışma.'")], expect: produce("Streit über das neue Gesetz", [tr("Bu isim über edatını belirtme hâliyle alır:"), de("Streit über das neue Gesetz."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, tam cümleyle: 'Manşet meseleyi fazla keskinleştiriyor.'")], expect: produce("Die Schlagzeile spitzt die Sache zu stark zu", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Die Schlagzeile spitzt die Sache zu stark zu."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Anstieg von die Preise um drei Prozent."), tr("cümlesi doğru mu?")], expect: truefalse("Anstieg von die Preise um drei Prozent.", false, [tr("Manşet dilinde bağlantı edatla değil tamlama hâliyle kurulur:"), de("Anstieg der Preise um drei Prozent.")]) },
      { say: [tr("Son: 'Haber çok kısa tutulmuş.'")], expect: produce("Die Meldung ist sehr knapp gehalten", [tr("Durum bildiren edilgen; ortaç sonda:"), de("Die Meldung ist sehr knapp gehalten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşınla günün manşetini konuşacaksın: ne diyor, ne demiyor.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla günün manşetini konuşuyorsunuz. Manşetin ne dediğini kendi cümlenle söyle, neyi söylemediğini fark ettir ve haberin abartılıp abartılmadığını tartış.",
      partner: "manşete inanmaya meyilli, ama ikna olabilen bir arkadaş",
      opening: "Hast du das gesehen? „Anstieg der Mieten um dreißig Prozent“ — dreißig! Wo soll das denn hinführen?",
      openingTr: "Gördün mü? „Kiralarda yüzde otuz artış“ — otuz! Bu nereye gidiyor?",
      goal: "Manşetin ne dediği ve ne demediği ayrılmış ve haberin abartılı olup olmadığı konusunda ortak bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-er-sagte",
    icon: "question",
    level: "B2",
    course: "de",
    title: "Er sagte, er komme später",
    titleTr: "Dolaylı aktarım",
    summary: "Başkasının sözünü aktarım kipiyle, mesafe koyarak aktarmayı öğretir.",
    minutes: 11,
    focusId: "Indirekte-Rede-Einstieg",
    vocab: [
      { de: "laut", tr: "…-e göre" },
      { de: "angeblich", tr: "iddiaya göre" },
      { de: "wiedergeben", tr: "aktarmak" },
      { de: "die Aussage", tr: "ifade" },
      { de: "behaupten", tr: "iddia etmek" },
    ],
    patterns: [
      { de: "Er sagte, er komme …", tr: "aktarım kipi" },
      { de: "Laut … / angeblich …", tr: "kaynak bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün başkasının sözünü aktaracağız. Almancada bunun ayrı bir fiil biçimi var ve o biçim tek bir şey söyler: bu benim cümlem değil. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Türkçede bunu 'demiş' ekiyle yaparız; Almancada fiilin kendisi değişir. Haber dilinde bu neredeyse zorunludur. Önce kelimeler.")] },
      word("İlk", { de: "laut", tr: "…-e göre" }),
      word("İkinci", { de: "angeblich", tr: "iddiaya göre" }),
      word("Üçüncü", { de: "wiedergeben", tr: "aktarmak" }),
      word("Dördüncü", { de: "die Aussage", tr: "ifade" }),
      word("Son", { de: "behaupten", tr: "iddia etmek" }),
      { say: [tr("Kalıbımız:"), de("Er sagte, er komme später."), tr("Fiil komme biçimine giriyor — bu, aktarıldığının işareti.")] },
      { say: [tr("Tekrar edin:"), de("Er sagte, er komme später")], expect: repeat("Er sagte, er komme später") },
      { say: [tr("Sıra sende: 'Sözcü kararın kesin olduğunu söyledi.'")], expect: produce("Der Sprecher sagte, die Entscheidung sei endgültig", [tr("Olmak fiilinin aktarım biçimi sei:"), de("Der Sprecher sagte, die Entscheidung sei endgültig."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi kaynak bildir: 'Rapora göre müzakereler başarısız oldu.'")], expect: produce("Laut Bericht sind die Verhandlungen gescheitert", [tr("Bu edattan sonra tamlama gerekmez; ana cümle düz kurulur:"), de("Laut Bericht sind die Verhandlungen gescheitert."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İddiaya göre iki hafta önce ayrılmış.'")], expect: produce("Angeblich ist er vor zwei Wochen abgereist", [tr("Zarf başta, fiil ikinci sırada:"), de("Angeblich ist er vor zwei Wochen abgereist."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Sprecher sagte, die Entscheidung sei endgültig."), tr("cümlesi doğru mu?")], expect: truefalse("Der Sprecher sagte, die Entscheidung sei endgültig.", true, [tr("Doğru. Aktarım kipi kullanılmış: cümle sözcünün, aktaran kişi ona katılıp katılmadığını söylemiyor.")]) },
      { say: [tr("Son: 'İfadesini kelimesi kelimesine aktardı.'")], expect: produce("Sie gab seine Aussage wörtlich wieder", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Sie gab seine Aussage wörtlich wieder."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşına duyduğun bir haberi aktaracaksın — ve neyin senin görüşün olduğunu ayıracaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına duyduğun bir haberi aktarıyorsun. Kimin ne söylediğini aktarım kipiyle ver, kaynağını belirt ve kendi görüşünü ayrı bir cümlede söyle.",
      partner: "kaynağı sorgulayan, 'sen ne düşünüyorsun' diye soran bir arkadaş",
      opening: "Warte — sagst du das jetzt, oder hat das jemand gesagt? Das ist ein Unterschied.",
      openingTr: "Dur — bunu sen mi söylüyorsun, yoksa biri mi söyledi? Bu fark eder.",
      goal: "Haberin kaynağı ve içeriği aktarım kipiyle verilmiş, konuşanın kendi görüşü ayrıca söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-soll-angeblich",
    icon: "media",
    level: "B2",
    course: "de",
    title: "Er soll im Ausland sein",
    titleTr: "Söylenti kipi",
    summary: "soll, will ve dürfte ile kaynağı ve emin olma derecesini ayırmayı öğretir.",
    minutes: 11,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "das Gerücht", tr: "söylenti" },
      { de: "sich aufhalten", tr: "bulunmak (bir yerde)" },
      { de: "bestätigen", tr: "doğrulamak" },
      { de: "unbestätigt", tr: "doğrulanmamış" },
      { de: "kursieren", tr: "dolaşmak (söylenti)" },
    ],
    patterns: [
      { de: "Er soll … sein.", tr: "başkaları öyle diyor" },
      { de: "Er will … haben.", tr: "kendisi öyle iddia ediyor" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün Almancanın en ince araçlarından biri: kip fiilleriyle KAYNAK bildirmek. Üç fiil, üç ayrı kaynak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("soll: başkaları öyle diyor. will: kişinin kendi iddiası. dürfte: konuşanın tahmini. Türkçede üçü de 'mış' olur; Almancada üçü ayrı şey. Önce kelimeler.")] },
      word("İlk", { de: "das Gerücht", tr: "söylenti" }),
      word("İkinci", { de: "sich aufhalten", tr: "bulunmak (bir yerde)" }),
      word("Üçüncü", { de: "bestätigen", tr: "doğrulamak" }),
      word("Dördüncü", { de: "unbestätigt", tr: "doğrulanmamış" }),
      word("Son", { de: "kursieren", tr: "dolaşmak (söylenti)" }),
      { say: [tr("Kalıbımız:"), de("Er soll im Ausland sein."), tr("Yani 'yurt dışındaymış — öyle diyorlar'. Sen kaynak değilsin.")] },
      { say: [tr("Tekrar edin:"), de("Er soll im Ausland sein")], expect: repeat("Er soll im Ausland sein") },
      { say: [tr("Sıra sende, bu kez kendi iddiası: 'Onu gördüğünü iddia ediyor.'")], expect: produce("Er will ihn gesehen haben", [tr("Kendi iddiası wollen ile; geçmiş mastar sonda:"), de("Er will ihn gesehen haben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi tahmin: 'Bu doğru olsa gerek.'")], expect: produce("Das dürfte stimmen", [tr("Tahmin dürfte ile; kısa ve kesin olmayan:"), de("Das dürfte stimmen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Söylenti günlerdir dolaşıyor.'")], expect: produce("Das Gerücht kursiert seit Tagen", [tr("Süre seit ile, yönelme hâlinde:"), de("Das Gerücht kursiert seit Tagen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Er soll im Ausland sein — das habe ich selbst gesehen."), tr("cümlesi doğru mu?")], expect: truefalse("Er soll im Ausland sein — das habe ich selbst gesehen.", false, [tr("Bu kip başkasından duyulanı bildirir; kendi gördüğün şey için kullanılmaz:"), de("Er ist im Ausland — das habe ich selbst gesehen.")]) },
      { say: [tr("Son: 'Haber hâlâ doğrulanmadı.'")], expect: produce("Die Meldung ist noch unbestätigt", [tr("Sıfat biçimi; sein ile:"), de("Die Meldung ist noch unbestätigt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir söylentiyi konuşacaksın: neyi duydun, neyi kendin biliyorsun, neyi sadece tahmin ediyorsun.")] },
    ],
    roleplay: {
      scene: "İş yerinde bir söylenti dolaşıyor. Bir meslektaşınla konuşurken duyduğunu, kendin bildiğini ve yalnızca tahmin ettiğini ayrı ayrı söyle ve söylentiye nasıl yaklaşacağınıza karar verin.",
      partner: "söylentiyi hemen yaymaya hevesli bir meslektaş",
      opening: "Hast du es gehört? Die Abteilung soll geschlossen werden. Weißt du was Genaueres?",
      openingTr: "Duydun mu? Bölüm kapatılacakmış. Daha kesin bir şey biliyor musun?",
      goal: "Duyulan, bilinen ve tahmin edilen ayrılmış ve söylentiye nasıl yaklaşılacağı kararlaşmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-interview",
    icon: "phone",
    level: "B2",
    course: "de",
    title: "Das Interview",
    titleTr: "Röportaj",
    summary: "Röportajda soru sormayı, üstüne gitmeyi ve cevabı aktarmayı öğretir.",
    minutes: 11,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "betonen", tr: "vurgulamak" },
      { de: "ausweichen", tr: "kaçamak cevap vermek" },
      { de: "nachhaken", tr: "üstüne gitmek" },
      { de: "zitieren", tr: "alıntılamak" },
      { de: "der Anlass", tr: "vesile, sebep" },
    ],
    patterns: [
      { de: "Auf die Frage, ob …", tr: "sorulan soruyu aktarır" },
      { de: "Er betonte, dass …", tr: "vurguyu aktarır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün röportaj yapacağız. Röportajın iki dili var: soru sorarken doğrudan, yazarken dolaylı. İkisini de kuracağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dolaylı soru bir yan cümledir; yani fiil sona gider. Bu, Türkçe konuşanın en çok kaydığı yer. Önce kelimeler.")] },
      word("İlk", { de: "betonen", tr: "vurgulamak" }),
      word("İkinci", { de: "ausweichen", tr: "kaçamak cevap vermek" }),
      word("Üçüncü", { de: "nachhaken", tr: "üstüne gitmek" }),
      word("Dördüncü", { de: "zitieren", tr: "alıntılamak" }),
      word("Son", { de: "der Anlass", tr: "vesile, sebep" }),
      { say: [tr("Kalıbımız:"), de("Auf die Frage, ob …"), tr("Sorulan soruyu aktarmanın gazete dilindeki biçimi.")] },
      { say: [tr("Örnek:"), de("Auf die Frage, ob er zurücktritt, wollte er nichts sagen."), tr("Tekrar edin:"), de("Auf die Frage, ob er zurücktritt, wollte er nichts sagen")], expect: repeat("Auf die Frage, ob er zurücktritt, wollte er nichts sagen") },
      { say: [tr("Sıra sende: 'Sorumluluğun kendisinde olmadığını vurguladı.'")], expect: produce("Er betonte, dass die Verantwortung nicht bei ihm liege", [tr("Yan cümlede fiil sonda; aktarım kipi mesafeyi korur:"), de("Er betonte, dass die Verantwortung nicht bei ihm liege."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Cevaptan kaçtı.'")], expect: produce("Er wich der Antwort aus", [tr("Bu fiil yönelme hâli ister ve öneki sona gider:"), de("Er wich der Antwort aus."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bir kez daha üstüne gittim.'")], expect: produce("Ich habe noch einmal nachgehakt", [tr("Ayrılabilen fiilin ortacı ge- ekini ortada alır:"), de("Ich habe noch einmal nachgehakt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Er wich die Antwort aus."), tr("cümlesi doğru mu?")], expect: truefalse("Er wich die Antwort aus.", false, [tr("Bu fiil belirtme değil yönelme hâli ister:"), de("Er wich der Antwort aus.")]) },
      { say: [tr("Son: 'Onu kelimesi kelimesine alıntılayabilir miyim?'")], expect: produce("Darf ich ihn wörtlich zitieren", [tr("Modal fiil başta soru; mastar sonda:"), de("Darf ich ihn wörtlich zitieren?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada birine kısa bir röportaj yapacaksın: sor, üstüne git ve söylediğini kendi cümlenle özetle.")] },
    ],
    roleplay: {
      scene: "Bir mahalle gazetesi için birine kısa bir röportaj yapıyorsun. Sebebi sor, bir cevabın üstüne git, kaçamak cevaba karşı kibarca ısrar et ve söylediğini kendi cümlenle özetleyerek onay al.",
      partner: "ölçülü konuşan, bazı sorulardan kaçınan bir muhatap",
      opening: "Fünf Minuten, mehr habe ich leider nicht. Was ist denn der Anlass für Ihr Interview?",
      openingTr: "Beş dakikam var, maalesef daha fazlası yok. Röportajınızın sebebi nedir?",
      goal: "Sebep sorulmuş, bir cevabın üstüne gidilmiş ve söylenen özetlenip onaylatılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-leserbrief",
    icon: "pen",
    level: "B2",
    course: "de",
    title: "Der Leserbrief",
    titleTr: "Okur mektubu",
    summary: "Bir yazıya karşılık verirken iki taraflı bağlaçlarla tartışmayı öğretir.",
    minutes: 11,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "der Leserbrief", tr: "okur mektubu" },
      { de: "die Redaktion", tr: "yayın kurulu" },
      { de: "der Beitrag", tr: "yazı, katkı" },
      { de: "entgegnen", tr: "karşılık vermek" },
      { de: "abschließend", tr: "son olarak" },
    ],
    patterns: [
      { de: "Zwar …, jedoch …", tr: "hak verip itiraz eder" },
      { de: "Einerseits … andererseits …", tr: "iki yanı da tartar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir gazete yazısına karşılık yazacağız. Bu türün kuralı şu: önce hak verirsin, sonra itiraz edersin. Yoksa okunmazsın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Almanca bu iki hamleyi tek cümleye sığdıran çift bağlaçlara sahip ve okur mektubu neredeyse onlardan ibarettir. Önce kelimeler.")] },
      word("İlk", { de: "der Leserbrief", tr: "okur mektubu" }),
      word("İkinci", { de: "die Redaktion", tr: "yayın kurulu" }),
      word("Üçüncü", { de: "der Beitrag", tr: "yazı, katkı" }),
      word("Dördüncü", { de: "entgegnen", tr: "karşılık vermek" }),
      word("Son", { de: "abschließend", tr: "son olarak" }),
      { say: [tr("Kalıbımız:"), de("Einerseits …, andererseits …"), tr("İki parça da cümle başında durur ve ikisinden sonra da fiil hemen gelir.")] },
      { say: [tr("Örnek:"), de("Einerseits verstehe ich die Kritik, andererseits fehlt mir ein Vorschlag."), tr("Tekrar edin:"), de("Einerseits verstehe ich die Kritik, andererseits fehlt mir ein Vorschlag")], expect: repeat("Einerseits verstehe ich die Kritik, andererseits fehlt mir ein Vorschlag") },
      { say: [tr("Sıra sende: 'Yazınızı ilgiyle okudum.'")], expect: produce("Ich habe Ihren Beitrag mit Interesse gelesen", [tr("Okur mektubunun standart açılışı:"), de("Ich habe Ihren Beitrag mit Interesse gelesen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Gerçi yazar haklı, ancak bir şeyi unutuyor.'")], expect: produce("Zwar hat der Autor recht, jedoch vergisst er etwas", [tr("Her iki parçadan sonra da fiil hemen gelir:"), de("Zwar hat der Autor recht, jedoch vergisst er etwas."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu görüşe karşı çıkmak istiyorum.'")], expect: produce("Dieser Meinung möchte ich entgegnen", [tr("Bu fiil yönelme hâli ister; tümleç öne alınmış:"), de("Dieser Meinung möchte ich entgegnen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Zwar hat der Autor recht, jedoch er vergisst etwas."), tr("cümlesi doğru mu?")], expect: truefalse("Zwar hat der Autor recht, jedoch er vergisst etwas.", false, [tr("Bu bağlaç cümlenin ilk öğesidir, o yüzden fiil hemen arkasından gelir:"), de("Zwar hat der Autor recht, jedoch vergisst er etwas.")]) },
      { say: [tr("Son: 'Son olarak bir öneride bulunmak isterim.'")], expect: produce("Abschließend möchte ich einen Vorschlag machen", [tr("Zarf başta, çekimli fiil ikinci sırada:"), de("Abschließend möchte ich einen Vorschlag machen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir yazıya karşılık vereceksin: hak ver, itiraz et ve bir öneri bırak.")] },
    ],
    roleplay: {
      scene: "Bir gazetedeki yazıya karşılık veriyorsun ve yazının yazarıyla konuşuyorsun. Katıldığın noktayı söyle, itirazını gerekçelendir ve son olarak somut bir öneri bırak.",
      partner: "yazısını savunan ama iyi bir argümana açık bir yazar",
      opening: "Sie haben meinen Beitrag gelesen und wollen widersprechen — nur zu. Womit fangen wir an?",
      openingTr: "Yazımı okumuşsunuz ve itiraz etmek istiyorsunuz — buyurun. Neyle başlayalım?",
      goal: "Katılınan nokta ve itiraz ayrı ayrı söylenmiş, itiraz gerekçelendirilmiş ve somut bir öneri bırakılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-doku",
    icon: "film",
    level: "B2",
    course: "de",
    title: "Die packende Doku",
    titleTr: "Belgesel yorumu",
    summary: "Ortaç sıfatlarıyla yoğunlaştırılmış tanımlamalar kurmayı öğretir.",
    minutes: 11,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "der Dokumentarfilm", tr: "belgesel" },
      { de: "die Aufnahme", tr: "çekim, kayıt" },
      { de: "anregen", tr: "harekete geçirmek" },
      { de: "erschütternd", tr: "sarsıcı" },
      { de: "eindringlich", tr: "vurucu, etkileyici" },
    ],
    patterns: [
      { de: "die im Film gezeigten …", tr: "ortaç sıfatı: gösterilen" },
      { de: "zum Nachdenken anregen", tr: "düşündürmek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün Almancanın en yoğun aracı: fiilden sıfat yapmak. Bir ilgi cümlesinin taşıdığı bilgiyi tek bir sıfata sıkıştırıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Filmde gösterilen görüntüler' derken Almanca ilgi cümlesi kurmayabilir; ortacı doğrudan ismin önüne koyar ve sıfat eki verir. Yazı dilinin imzası budur. Önce kelimeler.")] },
      word("İlk", { de: "der Dokumentarfilm", tr: "belgesel" }),
      word("İkinci", { de: "die Aufnahme", tr: "çekim, kayıt" }),
      word("Üçüncü", { de: "anregen", tr: "harekete geçirmek" }),
      word("Dördüncü", { de: "erschütternd", tr: "sarsıcı" }),
      word("Son", { de: "eindringlich", tr: "vurucu, etkileyici" }),
      { say: [tr("Kalıbımız:"), de("die im Film gezeigten Bilder"), tr("Yani 'filmde gösterilen görüntüler'. Ortaç ismin önünde ve sıfat eki almış durumda.")] },
      { say: [tr("Örnek:"), de("Die im Film gezeigten Bilder sind echt."), tr("Tekrar edin:"), de("Die im Film gezeigten Bilder sind echt")], expect: repeat("Die im Film gezeigten Bilder sind echt") },
      { say: [tr("Sıra sende: 'Etkileyici çekimler uzun süre akılda kalıyor.'")], expect: produce("Die eindringlichen Aufnahmen bleiben lange im Kopf", [tr("Sıfat çoğulda belirtili ek alır:"), de("Die eindringlichen Aufnahmen bleiben lange im Kopf."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Röportaj yapılan insanlar isimsiz kalıyor.'")], expect: produce("Die interviewten Menschen bleiben anonym", [tr("Ortaç doğrudan ismin önünde, sıfat ekiyle:"), de("Die interviewten Menschen bleiben anonym."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Belgesel düşünmeye sevk ediyor.'")], expect: produce("Der Dokumentarfilm regt zum Nachdenken an", [tr("Kalıplaşmış ifade; ayrılabilen önek sonda:"), de("Der Dokumentarfilm regt zum Nachdenken an."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die im Film gezeigten Bilder sind echt."), tr("cümlesi doğru mu?")], expect: truefalse("Die im Film gezeigten Bilder sind echt.", true, [tr("Doğru. Ortaç ismin önünde duruyor, sıfat ekini almış ve araya giren edat öbeği doğru yerde.")]) },
      { say: [tr("Son: 'Sarsıcı ama önemli bir film.'")], expect: produce("Ein erschütternder, aber wichtiger Film", [tr("Belirtisiz tekilde iki sıfat da aynı eki alır:"), de("Ein erschütternder, aber wichtiger Film."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada izlediğin bir belgeseli anlatacaksın: ne gösteriyor, seni ne sarstı, kime önerirsin.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına dün izlediğin belgeseli anlatıyorsun: neyi gösteriyor, hangi sahne seni sarstı, filmin eksiği ne ve kime önerirsin.",
      partner: "belgesel izlemeyi sevmeyen, ikna edilmesi gereken bir arkadaş",
      opening: "Eine Doku? Ehrlich gesagt schlafe ich bei sowas meistens ein. Was war denn daran so besonders?",
      openingTr: "Belgesel mi? Açıkçası ben öylelerinde genelde uyuyakalırım. Bunun özel yanı neydi?",
      goal: "Belgeselin konusu, en etkileyici sahnesi ve eksiği anlatılmış; arkadaşın izleyip izlemeyeceğine karar vermiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-podcast-b2",
    icon: "music",
    level: "B2",
    course: "de",
    title: "Im eigenen Podcast",
    titleTr: "Podcast sunumu",
    summary: "Bir bölümü isimleşmiş sunuş diliyle açıp kapatmayı öğretir.",
    minutes: 11,
    focusId: "Nominalisierung",
    vocab: [
      { de: "die Folge", tr: "bölüm" },
      { de: "die Aufzeichnung", tr: "kayıt" },
      { de: "abonnieren", tr: "abone olmak" },
      { de: "die Hörerschaft", tr: "dinleyici kitlesi" },
      { de: "dranbleiben", tr: "takipte kalmak" },
    ],
    patterns: [
      { de: "Thema der heutigen Folge ist …", tr: "bölümü açar" },
      { de: "Beim Zuhören …", tr: "isimleşmiş mastarla zaman" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün mikrofonun arkasına geçiyorsun. Sunuş dili kısa ve isimleşmiştir: 'bugün konuşacağımız konu' değil, 'bugünkü bölümün konusu'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de mastarın isim hâli var: 'dinlerken' Almancada 'dinleme sırasında' olur. Bu yapı sunuşta çok geçer. Önce kelimeler.")] },
      word("İlk", { de: "die Folge", tr: "bölüm" }),
      word("İkinci", { de: "die Aufzeichnung", tr: "kayıt" }),
      word("Üçüncü", { de: "abonnieren", tr: "abone olmak" }),
      word("Dördüncü", { de: "die Hörerschaft", tr: "dinleyici kitlesi" }),
      word("Son", { de: "dranbleiben", tr: "takipte kalmak" }),
      { say: [tr("Kalıbımız:"), de("Thema der heutigen Folge ist …"), tr("Tamlama hâlinde sıfat eki dikkat ister; bunu dersin sonunda sınayacağız.")] },
      { say: [tr("Örnek:"), de("Thema der heutigen Folge ist das Lernen im Erwachsenenalter."), tr("Tekrar edin:"), de("Thema der heutigen Folge ist das Lernen im Erwachsenenalter")], expect: repeat("Thema der heutigen Folge ist das Lernen im Erwachsenenalter") },
      { say: [tr("Sıra sende: 'Bugünkü bölümün konusu şehirde yaşamak.'")], expect: produce("Thema der heutigen Folge ist das Leben in der Stadt", [tr("Tamlama hâlinde sıfat -en ekini alır:"), de("Thema der heutigen Folge ist das Leben in der Stadt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Dinlerken not alabilirsiniz.'")], expect: produce("Beim Zuhören können Sie mitschreiben", [tr("İsimleşmiş mastar tümleç olarak başta, fiil ikinci sırada:"), de("Beim Zuhören können Sie mitschreiben."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kayıt geçen hafta yapıldı.'")], expect: produce("Die Aufzeichnung ist letzte Woche entstanden", [tr("Oluşum bildiren fiil sein ile çekilir:"), de("Die Aufzeichnung ist letzte Woche entstanden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Thema der heutige Folge ist das Leben in der Stadt."), tr("cümlesi doğru mu?")], expect: truefalse("Thema der heutige Folge ist das Leben in der Stadt.", false, [tr("Tamlama hâlinde sıfat -en ekini alır:"), de("Thema der heutigen Folge ist das Leben in der Stadt.")]) },
      { say: [tr("Son: 'Takipte kalın!'")], expect: produce("Bleiben Sie dran", [tr("Rica biçiminde fiil başta; önek sonda:"), de("Bleiben Sie dran!"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir podcast bölümü kaydedeceksin: konuğunu tanıt, konuyu aç ve bölümü kapat.")] },
    ],
    roleplay: {
      scene: "Kendi podcast bölümünü kaydediyorsun ve bir konuğun var. Bölümü aç, konuğunu tanıt, iki soru sor ve bölümü bir kapanış cümlesiyle bitir.",
      partner: "heyecanlı, uzun cevap veren bir podcast konuğu",
      opening: "Danke für die Einladung! Sagen Sie kurz: Für wen ist Ihr Podcast eigentlich gedacht?",
      openingTr: "Davet için teşekkürler! Kısaca söyleyin: Podcast'iniz aslında kimin için?",
      goal: "Bölüm açılmış, konuk tanıtılmış, en az iki soru sorulmuş ve bölüm bir kapanış cümlesiyle bitirilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-pressefreiheit",
    icon: "law",
    level: "B2",
    course: "de",
    title: "Vierte Gewalt",
    titleTr: "Basın özgürlüğü",
    summary: "Tartışmalı bir konuda tahmini ve duyulanı ayırarak konuşmayı öğretir.",
    minutes: 11,
    focusId: "Subjektive-Modalverben",
    vocab: [
      { de: "die Pressefreiheit", tr: "basın özgürlüğü" },
      { de: "unabhängig", tr: "bağımsız" },
      { de: "die Zensur", tr: "sansür" },
      { de: "recherchieren", tr: "araştırmak" },
      { de: "die Quelle", tr: "kaynak" },
    ],
    patterns: [
      { de: "Es dürfte klar sein, dass …", tr: "temkinli kesinlik" },
      { de: "… sollen … behaupten", tr: "duyulanı bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ağır bir konu ve bu tam da öznel kip fiillerinin işe yaradığı yer: tartışmalı bir konuda ne kadar emin olduğunu dilin kendisiyle göstermek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Böyle konularda kesin cümle kurmak riskli; Almanca 'muhtemelen açıktır ki' diyebilen bir yapıya sahip ve bu, tartışmayı sürdüren şey. Önce kelimeler.")] },
      word("İlk", { de: "die Pressefreiheit", tr: "basın özgürlüğü" }),
      word("İkinci", { de: "unabhängig", tr: "bağımsız" }),
      word("Üçüncü", { de: "die Zensur", tr: "sansür" }),
      word("Dördüncü", { de: "recherchieren", tr: "araştırmak" }),
      word("Son", { de: "die Quelle", tr: "kaynak" }),
      { say: [tr("Kalıbımız:"), de("Es dürfte klar sein, dass …"), tr("Kesin söylemeden kesin gibi söylemek; tartışmanın kibar hâli.")] },
      { say: [tr("Örnek:"), de("Es dürfte klar sein, dass unabhängige Berichte wichtig sind."), tr("Tekrar edin:"), de("Es dürfte klar sein, dass unabhängige Berichte wichtig sind")], expect: repeat("Es dürfte klar sein, dass unabhängige Berichte wichtig sind") },
      { say: [tr("Sıra sende: 'Eleştirmenler sansürden söz ediyormuş.'")], expect: produce("Kritiker sollen von Zensur sprechen", [tr("Duyulan bilgi sollen ile; mastar sonda:"), de("Kritiker sollen von Zensur sprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Gazeteciler bağımsız araştırabilmeli.'")], expect: produce("Journalisten müssen unabhängig recherchieren können", [tr("İki mastar üst üste; kip fiili en sonda:"), de("Journalisten müssen unabhängig recherchieren können."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kaynak açıklanmadı.'")], expect: produce("Die Quelle wurde nicht genannt", [tr("Edilgen geçmiş zaman; olumsuzluk ortaçtan önce:"), de("Die Quelle wurde nicht genannt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es dürfte klar sein, dass unabhängige Berichte sind wichtig."), tr("cümlesi doğru mu?")], expect: truefalse("Es dürfte klar sein, dass unabhängige Berichte sind wichtig.", false, [tr("Yan cümlede çekimli fiil en sona gider:"), de("Es dürfte klar sein, dass unabhängige Berichte wichtig sind.")]) },
      { say: [tr("Son: 'Bu tartışmalı olsa gerek.'")], expect: produce("Das dürfte umstritten sein", [tr("Tahmin dürfte ile; mastar sonda:"), de("Das dürfte umstritten sein."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada basının rolünü tartışacaksın: neyi biliyorsun, neyi duydun, ne düşünüyorsun.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla basının rolünü tartışıyorsunuz. Bildiğin, duyduğun ve tahmin ettiğin şeyleri ayır, görüşünü temkinli ama net söyle ve karşı tarafın itirazına karşılık ver.",
      partner: "medyaya güvenmeyen, örnek isteyen bir tanıdık",
      opening: "Ich glaube den Medien schon lange nichts mehr. Warum sollte ich dem, was da steht, überhaupt vertrauen?",
      openingTr: "Ben medyaya uzun zamandır inanmıyorum. Orada yazana neden güveneyim ki?",
      goal: "Bilinen, duyulan ve tahmin edilen ayrılmış, görüş gerekçesiyle söylenmiş ve karşı tarafın itirazına karşılık verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-b2-influencer",
    icon: "tech",
    level: "B2",
    course: "de",
    title: "Werbung oder Meinung?",
    titleTr: "Sosyal medya eleştirisi",
    summary: "Ortaç sıfatlarıyla reklam ve içerik ayrımını konuşmayı öğretir.",
    minutes: 11,
    focusId: "Partizipialattribute",
    vocab: [
      { de: "die Kooperation", tr: "iş birliği" },
      { de: "kennzeichnen", tr: "işaretlemek, etiketlemek" },
      { de: "die Reichweite", tr: "erişim" },
      { de: "glaubwürdig", tr: "inandırıcı" },
      { de: "verschleiern", tr: "gizlemek, örtmek" },
    ],
    patterns: [
      { de: "die beworbenen Produkte", tr: "reklamı yapılan ürünler" },
      { de: "gekennzeichnet werden müssen", tr: "işaretlenmek zorunda" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sosyal medyaya bakıyoruz ve bu ders geçen dersin devamı: ortaç sıfatları. Bu kez reklam ile görüşü ayırmak için. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Reklamı yapılan ürün' tek bir sıfatla söylenir ve tam da bu yoğunluk, kuralın yazıldığı yerde işe yarar. Önce kelimeler.")] },
      word("İlk", { de: "die Kooperation", tr: "iş birliği" }),
      word("İkinci", { de: "kennzeichnen", tr: "işaretlemek, etiketlemek" }),
      word("Üçüncü", { de: "die Reichweite", tr: "erişim" }),
      word("Dördüncü", { de: "glaubwürdig", tr: "inandırıcı" }),
      word("Son", { de: "verschleiern", tr: "gizlemek, örtmek" }),
      { say: [tr("Kalıbımız:"), de("die beworbenen Produkte"), tr("Yani 'reklamı yapılan ürünler'. Ortaç ismin önünde, sıfat ekiyle.")] },
      { say: [tr("Örnek:"), de("Die beworbenen Produkte müssen gekennzeichnet werden."), tr("Tekrar edin:"), de("Die beworbenen Produkte müssen gekennzeichnet werden")], expect: repeat("Die beworbenen Produkte müssen gekennzeichnet werden") },
      { say: [tr("Sıra sende: 'Ücretli iş birlikleri işaretlenmek zorunda.'")], expect: produce("Bezahlte Kooperationen müssen gekennzeichnet werden", [tr("Belirtisiz çoğulda sıfat -e ekini alır; sonda ortaç ve werden:"), de("Bezahlte Kooperationen müssen gekennzeichnet werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Erişimi büyük ama inandırıcılığı düşük.'")], expect: produce("Die Reichweite ist groß, aber die Glaubwürdigkeit gering", [tr("İki kısa hüküm; ikincisinde fiil tekrarlanmıyor:"), de("Die Reichweite ist groß, aber die Glaubwürdigkeit gering."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Reklamı yapılan ürünü kendisi kullanmıyor.'")], expect: produce("Das beworbene Produkt benutzt sie selbst nicht", [tr("Nesne öne alınmış; fiil ikinci sırada:"), de("Das beworbene Produkt benutzt sie selbst nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Bezahlte Kooperationen müssen gekennzeichnet werden."), tr("cümlesi doğru mu?")], expect: truefalse("Bezahlte Kooperationen müssen gekennzeichnet werden.", true, [tr("Doğru. Sıfat belirtisiz çoğulda -e ekini almış ve kipli edilgen sonda ortaç ile werden sırasında.")]) },
      { say: [tr("Son: 'Bazıları reklamı gizliyor.'")], expect: produce("Manche verschleiern die Werbung", [tr("Belirsiz zamir özne, çoğul çekim:"), de("Manche verschleiern die Werbung."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sosyal medyada reklamla görüşün ayrımını tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla sosyal medyada reklamla samimi görüş ayrımını tartışıyorsunuz: neyi işaretlemek gerekir, kim inandırıcı kalır, sen neye güveniyorsun.",
      partner: "takip ettiği kişileri savunan bir arkadaş",
      opening: "Sie sagt doch immer, dass sie das selbst benutzt. Warum sollte ich ihr das nicht glauben?",
      openingTr: "Hep kendisinin kullandığını söylüyor. Ona neden inanmayayım ki?",
      goal: "Reklamla samimi görüş arasındaki ayrım örneklerle konuşulmuş ve neye güvenileceği konusunda ortak bir ölçüte varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-b2-falschmeldung",
    icon: "media",
    level: "B2",
    course: "de",
    title: "Die Ente",
    titleTr: "Yalan haberi çürütmek",
    summary: "Bir iddiayı aktarıp gerçeğiyle karşılaştırarak çürütmeyi öğretir.",
    minutes: 11,
    focusId: "Indirekte-Rede-Einstieg",
    vocab: [
      { de: "die Falschmeldung", tr: "yalan haber" },
      { de: "sich erweisen als", tr: "… olduğu anlaşılmak" },
      { de: "widerlegen", tr: "çürütmek" },
      { de: "die Behauptung", tr: "iddia" },
      { de: "nachprüfen", tr: "doğrulamak" },
    ],
    patterns: [
      { de: "Es wurde behauptet, … sei …", tr: "iddiayı aktarır" },
      { de: "Tatsächlich aber …", tr: "gerçeği karşısına koyar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve bütün modülü topluyor: bir iddiayı önce aktaracaksın, sonra gerçeği karşısına koyacaksın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu iki hamlenin ayrı dilbilgisi var: iddia aktarım kipiyle, gerçek düz kipte. Fark cümlede görünür ve dinleyen kimin ne dediğini karıştırmaz. Önce kelimeler.")] },
      word("İlk", { de: "die Falschmeldung", tr: "yalan haber" }),
      word("İkinci", { de: "sich erweisen als", tr: "… olduğu anlaşılmak" }),
      word("Üçüncü", { de: "widerlegen", tr: "çürütmek" }),
      word("Dördüncü", { de: "die Behauptung", tr: "iddia" }),
      word("Son", { de: "nachprüfen", tr: "doğrulamak" }),
      { say: [tr("Kalıbımız:"), de("Es wurde behauptet, … sei …"), tr("Kişisiz edilgen artı aktarım kipi: iddianın sahibi bile belirsiz.")] },
      { say: [tr("Örnek:"), de("Es wurde behauptet, die Zahl sei doppelt so hoch."), tr("Tekrar edin:"), de("Es wurde behauptet, die Zahl sei doppelt so hoch")], expect: repeat("Es wurde behauptet, die Zahl sei doppelt so hoch") },
      { say: [tr("Sıra sende, gerçeği karşısına koy: 'Ama gerçekte tam tersi geçerli.'")], expect: produce("Tatsächlich aber gilt das Gegenteil", [tr("Zarf başta, fiil ikinci sırada:"), de("Tatsächlich aber gilt das Gegenteil."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kaynağın sahte olduğu anlaşıldı.'")], expect: produce("Die Quelle erwies sich als gefälscht", [tr("Dönüşlü fiil als edatıyla:"), de("Die Quelle erwies sich als gefälscht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İddia çürütülebilir.'")], expect: produce("Die Behauptung lässt sich widerlegen", [tr("Edilgen yerine geçen yapı; mastar sonda:"), de("Die Behauptung lässt sich widerlegen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es wurde behauptet, die Zahl ist doppelt so hoch."), tr("cümlesi doğru mu?")], expect: truefalse("Es wurde behauptet, die Zahl ist doppelt so hoch.", false, [tr("Aktarılan iddiada fiil aktarım kipine girer; düz kip cümleyi senin iddian yapar:"), de("Es wurde behauptet, die Zahl sei doppelt so hoch.")]) },
      { say: [tr("Son: 'Paylaşmadan önce bunu doğruladım.'")], expect: produce("Ich habe das nachgeprüft, bevor ich es geteilt habe", [tr("Yan cümlede fiil sonda; ana cümlede ayrılabilen ortaç:"), de("Ich habe das nachgeprüft, bevor ich es geteilt habe."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada yanlış bir haberi çürüteceksin: iddiayı aktar, kaynağı sorgula, gerçeği koy.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığın sana yanlış olduğunu bildiğin bir haber anlatıyor. İddiayı kendi cümlenle aktar, kaynağını sorgula, gerçeği karşısına koy ve nasıl doğrulanabileceğini göster.",
      partner: "haberi paylaşmış, kolay vazgeçmeyen bir tanıdık",
      opening: "Das stand überall! Willst du sagen, das haben sich alle einfach ausgedacht?",
      openingTr: "Her yerde yazıyordu! Herkesin bunu uydurduğunu mu söylüyorsun?",
      goal: "İddia aktarılmış, kaynağı sorgulanmış, gerçek karşısına konmuş ve nasıl doğrulanacağı gösterilmiş olur.",
      minTurns: 9,
    },
  },
];
