import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * B1 · Modül 8 — Sağlık sistemi (071–080).
 *
 * A1 ve A2 sağlık konusunu bir kez daha geçmişti: neresi ağrıyor, randevu
 * nasıl alınır. B1'de değişen şey konu değil, MUHATAP. Artık tek bir doktor
 * yok, bir sistem var — aile hekimi, sevk, uzman, eczane, sigorta, acil — ve
 * bu sistemin kendi dili var: edilgen (Ein Termin wird vergeben), edatı
 * sabit fiiller (Ich leide unter …), sıralı geçmiş (Nachdem ich gestürzt
 * war …).
 *
 * Modülün ikinci yarısı bilinçli olarak ağrıdan uzaklaşıyor: beslenme, uyku,
 * ruh sağlığı. Sebebi şu — bu konularda konuşmak için gereken dil, şikâyet
 * bildirmekten daha zordur ve daha çok lazım olur.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

/** Standart kelime adımı: "n. kelimemiz: X — anlamı; X deyin." */
function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deB1B08: Lesson[] = [
  {
    id: "de-b1-hausarzt",
    icon: "doctor",
    level: "B1",
    course: "de",
    title: "Beim Hausarzt",
    titleTr: "Aile hekiminde",
    summary: "Sürekli bir şikâyeti edatı sabit fiillerle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Verben-mit-Präpositionen",
    vocab: [
      { de: "der Hausarzt", tr: "aile hekimi" },
      { de: "leiden", tr: "rahatsızlığı olmak" },
      { de: "zusammenhängen", tr: "bağlantılı olmak" },
      { de: "der Befund", tr: "bulgu" },
      { de: "chronisch", tr: "kronik" },
    ],
    patterns: [
      { de: "Ich leide unter …", tr: "sürekli bir şikâyeti anlatır" },
      { de: "Das hängt mit … zusammen.", tr: "iki şeyi birbirine bağlar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Sağlık konusunu A1'de bir kez geçtik: neresi ağrıyor. Bugün bir adım öteye geçiyoruz — sürekli bir şikâyeti anlatmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir günlük ağrı ile aylardır süren bir şikâyet aynı kelimeyle anlatılmaz. Sürekli olan için edatı sabit bir fiil var. Önce kelimeler.")] },
      word("İlk", { de: "der Hausarzt", tr: "aile hekimi" }),
      word("İkinci", { de: "leiden", tr: "rahatsızlığı olmak" }),
      word("Üçüncü", { de: "zusammenhängen", tr: "bağlantılı olmak" }),
      word("Dördüncü", { de: "der Befund", tr: "bulgu" }),
      word("Son", { de: "chronisch", tr: "kronik" }),
      { say: [tr("Kalıbımız:"), de("Ich leide unter …"), tr("Bu fiilin edatı sabittir ve yönelme hâli ister. Türkçede 'şundan muzdaribim' diyoruz.")] },
      { say: [tr("Örnek:"), de("Ich leide seit Monaten unter Kopfschmerzen."), tr("Lütfen tekrar edin:"), de("Ich leide seit Monaten unter Kopfschmerzen")], expect: repeat("Ich leide seit Monaten unter Kopfschmerzen") },
      { say: [tr("Sıra sende: 'İki yıldır uyku sorunu yaşıyorum.'")], expect: produce("Ich leide seit zwei Jahren unter Schlafproblemen", [tr("Süre ortada, edat ve yönelme hâli sonda:"), de("Ich leide seit zwei Jahren unter Schlafproblemen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi bağlantı kur: 'Sanırım bu stresle bağlantılı.'")], expect: produce("Ich glaube, das hängt mit dem Stress zusammen", [tr("Ayrılabilen fiilin öneki yan cümlenin en sonunda:"), de("Ich glaube, das hängt mit dem Stress zusammen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bulgular ne diyor?'")], expect: produce("Was sagen die Befunde", [tr("Çoğul özne, çoğul fiil, soru kelimesi başta:"), de("Was sagen die Befunde?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich leide an Kopfschmerzen seit Monaten unter."), tr("cümlesi doğru mu?")], expect: truefalse("Ich leide an Kopfschmerzen seit Monaten unter.", false, [tr("Edat fiilin arkasına atılmaz, nesnenin önünde durur:"), de("Ich leide seit Monaten unter Kopfschmerzen.")]) },
      { say: [tr("Son: 'Bu kronik bir hastalık mı?'")], expect: produce("Ist das eine chronische Krankheit", [tr("Evet-hayır sorusunda fiil en başta:"), de("Ist das eine chronische Krankheit?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada aile hekiminle sürekli bir şikâyeti konuşacaksın: ne zamandır var, neyle bağlantılı olabilir.")] },
    ],
    roleplay: {
      scene: "Aile hekimindesin ve aylardır süren bir şikâyeti anlatıyorsun: ne zamandan beri, ne zaman artıyor, neyle bağlantılı olabilir. Edatı sabit fiillerle anlat.",
      partner: "acele etmeyen, ayrıntı soran bir aile hekimi",
      opening: "Setzen Sie sich. Sie sagten am Telefon, es geht schon länger so — seit wann genau?",
      openingTr: "Buyurun oturun. Telefonda bir süredir böyle olduğunu söylediniz — tam olarak ne zamandan beri?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-facharzt",
    icon: "doctor",
    level: "B1",
    course: "de",
    title: "Die Überweisung",
    titleTr: "Uzmana sevk",
    summary: "Sevk ve randevu sürecini edilgen cümlelerle anlamayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "der Facharzt", tr: "uzman hekim" },
      { de: "die Überweisung", tr: "sevk" },
      { de: "vergeben", tr: "vermek (randevu)" },
      { de: "betragen", tr: "tutmak (süre, miktar)" },
      { de: "die Diagnose", tr: "teşhis" },
    ],
    patterns: [
      { de: "Ich werde überwiesen.", tr: "sevk edilme: edilgen" },
      { de: "Die Wartezeit beträgt …", tr: "süre bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Almanya'da uzmana genelde doğrudan gidilmez: önce aile hekimi bir kâğıt yazar. O sürecin dili baştan sona edilgendir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sen bu cümlelerde özne değilsin, işlem görensin. Bu yüzden kendini anlatırken bile edilgen kuruyorsun. Önce kelimeler.")] },
      word("İlk", { de: "der Facharzt", tr: "uzman hekim" }),
      word("İkinci", { de: "die Überweisung", tr: "sevk" }),
      word("Üçüncü", { de: "vergeben", tr: "vermek (randevu)" }),
      word("Dördüncü", { de: "betragen", tr: "tutmak (süre, miktar)" }),
      word("Son", { de: "die Diagnose", tr: "teşhis" }),
      { say: [tr("Kalıbımız:"), de("Ich werde überwiesen."), tr("Burada özne sensin ama işi yapan sen değilsin. Türkçede 'sevk ediliyorum' demek.")] },
      { say: [tr("Örnek:"), de("Ich werde zum Facharzt überwiesen."), tr("Tekrar edin:"), de("Ich werde zum Facharzt überwiesen")], expect: repeat("Ich werde zum Facharzt überwiesen") },
      { say: [tr("Sıra sende: 'Randevular yalnızca sabahları veriliyor.'")], expect: produce("Termine werden nur vormittags vergeben", [tr("Çoğul özne, çoğul yardımcı fiil, ortaç sonda:"), de("Termine werden nur vormittags vergeben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi süre sor: 'Bekleme süresi ne kadar?'")], expect: produce("Wie lang ist die Wartezeit", [tr("Soru kelimesiyle basit bir soru:"), de("Wie lang ist die Wartezeit?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bekleme süresi altı hafta tutuyor.'")], expect: produce("Die Wartezeit beträgt sechs Wochen", [tr("Bu fiil resmî dilde süre ve miktar için kullanılır:"), de("Die Wartezeit beträgt sechs Wochen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Diagnose wird morgen gestellt."), tr("cümlesi doğru mu?")], expect: truefalse("Die Diagnose wird morgen gestellt.", true, [tr("Doğru. Tekil özne, yardımcı fiil ikinci sırada ve ortaç en sonda; teşhis için kullanılan fiil de doğru.")]) },
      { say: [tr("Son: 'Sevk kâğıdını yanımda getirmem gerekiyor mu?'")], expect: produce("Muss ich die Überweisung mitbringen", [tr("Modal fiil başta, ayrılabilen mastar sonda:"), de("Muss ich die Überweisung mitbringen?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir uzman muayenehanesinin sekreterliğini arayacaksın: sevkin var, randevu istiyorsun, süreyi soruyorsun.")] },
    ],
    roleplay: {
      scene: "Bir uzman muayenehanesini arıyorsun: sevkin olduğunu söyle, randevu iste, bekleme süresini ve ne getirmen gerektiğini sor.",
      partner: "telefonda hızlı konuşan, dolu bir randevu defteri olan sekreter",
      opening: "Praxis Dr. Ahrens, guten Tag. Haben Sie eine Überweisung von Ihrem Hausarzt?",
      openingTr: "Dr. Ahrens muayenehanesi, iyi günler. Aile hekiminizden sevkiniz var mı?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-apotheke-b1",
    icon: "pill",
    level: "B1",
    course: "de",
    title: "Wechselwirkungen",
    titleTr: "İlaç danışma",
    summary: "İlaç kullanımını koşul cümleleriyle sormayı ve anlamayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-wenn",
    vocab: [
      { de: "die Wechselwirkung", tr: "ilaç etkileşimi" },
      { de: "einnehmen", tr: "almak (ilaç)" },
      { de: "der Beipackzettel", tr: "prospektüs" },
      { de: "kombinieren", tr: "birlikte kullanmak" },
      { de: "die Dosis", tr: "doz" },
    ],
    patterns: [
      { de: "Wenn Sie … einnehmen, …", tr: "koşul yan cümlesi" },
      { de: "Darf ich … kombinieren?", tr: "izin sorusu" },
    ],
    lecture: [
      { say: [tr("Merhaba! Eczanede en önemli soru ilacın adı değil: birlikte alınabilir mi. Bunun için koşul cümlesi lazım. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Koşul yan cümlesi başta duruyorsa ana cümle fiille başlar. Bu kuralı defalarca gördük; bugün onu sağlık bağlamında pekiştiriyoruz. Önce kelimeler.")] },
      word("İlk", { de: "die Wechselwirkung", tr: "ilaç etkileşimi" }),
      word("İkinci", { de: "einnehmen", tr: "almak (ilaç)" }),
      word("Üçüncü", { de: "der Beipackzettel", tr: "prospektüs" }),
      word("Dördüncü", { de: "kombinieren", tr: "birlikte kullanmak" }),
      word("Son", { de: "die Dosis", tr: "doz" }),
      { say: [tr("Kalıbımız:"), de("Wenn Sie das einnehmen, trinken Sie viel Wasser."), tr("Yan cümle önde, ana cümlenin fiili hemen virgülden sonra.")] },
      { say: [tr("Tekrar edin:"), de("Wenn Sie das einnehmen, trinken Sie viel Wasser")], expect: repeat("Wenn Sie das einnehmen, trinken Sie viel Wasser") },
      { say: [tr("Sıra sende: 'Bu ilacı akşamları alırsanız daha iyi uyursunuz.'")], expect: produce("Wenn Sie das Medikament abends einnehmen, schlafen Sie besser", [tr("Koşul başta, ana cümle fiille başlar:"), de("Wenn Sie das Medikament abends einnehmen, schlafen Sie besser."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi izin sor: 'Bunu antibiyotikle birlikte kullanabilir miyim?'")], expect: produce("Darf ich das mit einem Antibiotikum kombinieren", [tr("Modal fiil başta, mastar en sonda:"), de("Darf ich das mit einem Antibiotikum kombinieren?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Emin değilseniz prospektüsü okuyun.'")], expect: produce("Wenn Sie unsicher sind, lesen Sie den Beipackzettel", [tr("Yan cümle önde, emir cümlesi arkadan:"), de("Wenn Sie unsicher sind, lesen Sie den Beipackzettel."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn Sie das nehmen, Sie sollen nicht Auto fahren."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn Sie das nehmen, Sie sollen nicht Auto fahren.", false, [tr("Koşul yan cümlesi başta olduğunda ana cümle fiille başlar:"), de("Wenn Sie das nehmen, sollen Sie nicht Auto fahren.")]) },
      { say: [tr("Son: 'Doz gün içinde kaç kez?'")], expect: produce("Wie oft am Tag ist die Dosis", [tr("Soru öbeği başta, fiil ikinci sırada:"), de("Wie oft am Tag ist die Dosis?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada eczacıya danışacaksın: hangi ilaçları kullanıyorsun, birlikte alınabilir mi, ne zaman alacaksın.")] },
    ],
    roleplay: {
      scene: "Eczanede danışıyorsun: hâlihazırda kullandığın ilaçları söyle, yeni ilaçla birlikte alınıp alınamayacağını sor, doz ve saat sor. Sorularını koşul cümleleriyle kur.",
      partner: "dikkatli, prospektüse bakan bir eczacı",
      opening: "Guten Tag. Bevor ich Ihnen das gebe: Nehmen Sie zurzeit andere Medikamente ein?",
      openingTr: "İyi günler. Bunu vermeden önce: Şu anda başka ilaç kullanıyor musunuz?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-ernaehrung",
    icon: "food",
    level: "B1",
    course: "de",
    title: "Bewusst essen",
    titleTr: "Beslenme",
    summary: "Beslenme alışkanlıklarını mastar öbekleriyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Infinitiv-zu",
    vocab: [
      { de: "die Ernährung", tr: "beslenme" },
      { de: "verzichten", tr: "vazgeçmek" },
      { de: "schwerfallen", tr: "zor gelmek" },
      { de: "ausgewogen", tr: "dengeli" },
      { de: "die Portion", tr: "porsiyon" },
    ],
    patterns: [
      { de: "Ich versuche, … zu …", tr: "denemeyi anlatır" },
      { de: "Es fällt mir schwer, … zu …", tr: "zorlandığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün beslenmeyi konuşacağız — ama liste sayarak değil, kendi çabanı anlatarak. Bunun kalıbı mastar öbeği. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki kalıp öğreneceğiz: neyi denediğin ve neyin zor geldiği. İkisi de virgülden sonra bir mastar öbeği alıyor. Önce kelimeler.")] },
      word("İlk", { de: "die Ernährung", tr: "beslenme" }),
      word("İkinci", { de: "verzichten", tr: "vazgeçmek" }),
      word("Üçüncü", { de: "schwerfallen", tr: "zor gelmek" }),
      word("Dördüncü", { de: "ausgewogen", tr: "dengeli" }),
      word("Son", { de: "die Portion", tr: "porsiyon" }),
      { say: [tr("Kalıbımız:"), de("Es fällt mir schwer, … zu …"), tr("Baştaki küçük kelime sahte özne; zorlanan kişi yönelme hâliyle gösteriliyor.")] },
      { say: [tr("Örnek:"), de("Es fällt mir schwer, auf Zucker zu verzichten."), tr("Tekrar edin:"), de("Es fällt mir schwer, auf Zucker zu verzichten")], expect: repeat("Es fällt mir schwer, auf Zucker zu verzichten") },
      { say: [tr("Sıra sende: 'Daha dengeli beslenmeye çalışıyorum.'")], expect: produce("Ich versuche, mich ausgewogener zu ernähren", [tr("Dönüşlü fiil ve karşılaştırma biçimi bir arada:"), de("Ich versuche, mich ausgewogener zu ernähren."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Akşamları küçük porsiyonlar yiyorum.'")], expect: produce("Abends esse ich kleine Portionen", [tr("Zaman zarfı başta, fiil ikinci sırada:"), de("Abends esse ich kleine Portionen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Etten vazgeçmek bana zor gelmiyor.'")], expect: produce("Es fällt mir nicht schwer, auf Fleisch zu verzichten", [tr("Olumsuzluk sıfatın önünde, mastar öbeği virgülden sonra:"), de("Es fällt mir nicht schwer, auf Fleisch zu verzichten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich versuche, mehr Gemüse essen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich versuche, mehr Gemüse essen.", false, [tr("Mastarın önündeki küçük bağlaç eksik:"), de("Ich versuche, mehr Gemüse zu essen.")]) },
      { say: [tr("Son: 'Dengeli beslenme sadece sebze demek değil.'")], expect: produce("Ausgewogene Ernährung bedeutet nicht nur Gemüse", [tr("Uzun özne öbeği, sonra fiil, sonra olumsuz sınırlama:"), de("Ausgewogene Ernährung bedeutet nicht nur Gemüse."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir beslenme danışmanıyla alışkanlıklarını konuşacaksın: neyi deniyorsun, ne zor geliyor.")] },
    ],
    roleplay: {
      scene: "Bir beslenme danışmanıyla konuşuyorsun: nasıl besleniyorsun, neyi değiştirmeye çalışıyorsun, ne zor geliyor. Cümlelerini mastar öbekleriyle kur.",
      partner: "yargılamayan, somut öneri veren bir beslenme danışmanı",
      opening: "Erzählen Sie mir einfach von einem normalen Tag: Was essen Sie morgens, mittags, abends?",
      openingTr: "Bana sıradan bir gününüzü anlatın: Sabah, öğle, akşam ne yiyorsunuz?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-rueckenschmerz",
    icon: "run",
    level: "B1",
    course: "de",
    title: "Der Bürorücken",
    titleTr: "Ofis ağrıları",
    summary: "Tavsiye vermeyi ve almayı dilek kipiyle kurmayı öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Haltung", tr: "duruş" },
      { de: "dehnen", tr: "esnetmek" },
      { de: "verspannt", tr: "kasılmış" },
      { de: "der Schreibtisch", tr: "çalışma masası" },
      { de: "die Übung", tr: "egzersiz" },
    ],
    patterns: [
      { de: "Sie sollten …", tr: "yumuşak tavsiye" },
      { de: "An Ihrer Stelle würde ich …", tr: "sizin yerinizde olsam" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün masa başında çalışanın klasik sorunu: sırt. Öğreneceğimiz şey ise tavsiye vermenin yumuşak biçimi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Düz kipte 'yapın' demek emirdir; dilek kipiyle söylenince tavsiye olur. Aynı cümle, başka bir ton. Önce kelimeler.")] },
      word("İlk", { de: "die Haltung", tr: "duruş" }),
      word("İkinci", { de: "dehnen", tr: "esnetmek" }),
      word("Üçüncü", { de: "verspannt", tr: "kasılmış" }),
      word("Dördüncü", { de: "der Schreibtisch", tr: "çalışma masası" }),
      word("Son", { de: "die Übung", tr: "egzersiz" }),
      { say: [tr("Kalıbımız:"), de("Sie sollten sich öfter dehnen."), tr("Bu, zorunluluk değil öneri anlatan bir biçim. Emirden bir tık yumuşak.")] },
      { say: [tr("Tekrar edin:"), de("Sie sollten sich öfter dehnen")], expect: repeat("Sie sollten sich öfter dehnen") },
      { say: [tr("Sıra sende: 'Sizin yerinizde olsam masamı yükseltirdim.'")], expect: produce("An Ihrer Stelle würde ich den Schreibtisch höher stellen", [tr("Tümleç başta, çekimli fiil ikinci, mastar sonda:"), de("An Ihrer Stelle würde ich den Schreibtisch höher stellen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Omuzlarım akşamları kasılıyor.'")], expect: produce("Abends sind meine Schultern verspannt", [tr("Zaman zarfı başta, fiil ikinci sırada:"), de("Abends sind meine Schultern verspannt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Her saat başı kısa bir egzersiz yapmalısınız.'")], expect: produce("Sie sollten jede Stunde eine kurze Übung machen", [tr("Öneri biçimi, mastar en sonda:"), de("Sie sollten jede Stunde eine kurze Übung machen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("An Ihrer Stelle würde ich einen Arzt fragen."), tr("cümlesi doğru mu?")], expect: truefalse("An Ihrer Stelle würde ich einen Arzt fragen.", true, [tr("Doğru. Tümleç başta olduğu için çekimli fiil ikinci sırada ve mastar en sonda.")]) },
      { say: [tr("Son: 'Duruş ağrıdan daha önemli.'")], expect: produce("Die Haltung ist wichtiger als der Schmerz", [tr("Karşılaştırma biçimi ve karşılaştırma bağlacı:"), de("Die Haltung ist wichtiger als der Schmerz."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir fizyoterapistle sırt ağrını konuşacaksın: ne zaman oluyor, o ne öneriyor.")] },
    ],
    roleplay: {
      scene: "Bir fizyoterapistle sırt ağrını konuşuyorsun: ne zaman başlıyor, gün içinde nasıl oturuyorsun, ne öneriyor. Tavsiyeleri dilek kipiyle konuş.",
      partner: "pratik öneriler veren, hareket ettiren bir fizyoterapist",
      opening: "Zeigen Sie mir mal, wie Sie am Schreibtisch sitzen. Wann tut es am meisten weh?",
      openingTr: "Masada nasıl oturduğunuzu gösterin bakalım. En çok ne zaman ağrıyor?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-schlaf",
    icon: "bed",
    level: "B1",
    course: "de",
    title: "Endlich gut schlafen",
    titleTr: "Uyku düzeni",
    summary: "Bir günün sırasını bevor ve während bağlaçlarıyla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-bevor-während",
    vocab: [
      { de: "der Schlaf", tr: "uyku" },
      { de: "durchschlafen", tr: "kesintisiz uyumak" },
      { de: "das Ritual", tr: "alışkanlık düzeni" },
      { de: "wach", tr: "uyanık" },
      { de: "erholsam", tr: "dinlendirici" },
    ],
    patterns: [
      { de: "Bevor ich schlafe, …", tr: "önce olanı anlatır" },
      { de: "Während der Nacht …", tr: "süre boyunca olanı anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün uykuyu konuşacağız ve bu, sıralama demek: yatmadan önce ne yapıyorsun, gece boyunca ne oluyor. İki bağlaç yeter. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Biri bir andan önceyi gösteriyor, öteki bir süre boyunca olanı. İkisi de yan cümle kuruyor, yani fiil sona gidiyor. Önce kelimeler.")] },
      word("İlk", { de: "der Schlaf", tr: "uyku" }),
      word("İkinci", { de: "durchschlafen", tr: "kesintisiz uyumak" }),
      word("Üçüncü", { de: "das Ritual", tr: "alışkanlık düzeni" }),
      word("Dördüncü", { de: "wach", tr: "uyanık" }),
      word("Son", { de: "erholsam", tr: "dinlendirici" }),
      { say: [tr("Kalıbımız:"), de("Bevor ich schlafe, lese ich zwanzig Minuten."), tr("Yan cümle başta, ana cümle fiille başlıyor.")] },
      { say: [tr("Tekrar edin:"), de("Bevor ich schlafe, lese ich zwanzig Minuten")], expect: repeat("Bevor ich schlafe, lese ich zwanzig Minuten") },
      { say: [tr("Sıra sende: 'Yatmadan önce telefonu kapatıyorum.'")], expect: produce("Bevor ich ins Bett gehe, schalte ich das Handy aus", [tr("Yan cümle önde; ana cümlede ayrılabilen fiilin öneki sonda:"), de("Bevor ich ins Bett gehe, schalte ich das Handy aus."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi öteki bağlaçla: 'Gece boyunca iki kez uyanıyorum.'")], expect: produce("Während der Nacht wache ich zweimal auf", [tr("Bu bağlaç bir isimle de kullanılabilir; ana cümlede önek sonda:"), de("Während der Nacht wache ich zweimal auf."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kesintisiz uyuyamıyorum.'")], expect: produce("Ich kann nicht durchschlafen", [tr("Modal fiil çekimli, mastar en sonda:"), de("Ich kann nicht durchschlafen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Bevor ich schlafe, ich trinke keinen Kaffee."), tr("cümlesi doğru mu?")], expect: truefalse("Bevor ich schlafe, ich trinke keinen Kaffee.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar:"), de("Bevor ich schlafe, trinke ich keinen Kaffee.")]) },
      { say: [tr("Son: 'Bu düzen bana dinlendirici bir uyku sağlıyor.'")], expect: produce("Dieses Ritual gibt mir einen erholsamen Schlaf", [tr("Yönelme ve belirtme nesnesi bir arada:"), de("Dieses Ritual gibt mir einen erholsamen Schlaf."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir uyku danışmanıyla gecelerini anlatacaksın: yatmadan önce ne yapıyorsun, gece ne oluyor.")] },
    ],
    roleplay: {
      scene: "Bir uyku danışmanıyla konuşuyorsun: yatmadan önceki alışkanlıkların, gece boyunca olanlar, sabah nasıl uyanıyorsun. Sırayı bevor ve während ile anlat.",
      partner: "günlük düzeni adım adım soran bir uyku danışmanı",
      opening: "Beschreiben Sie mir bitte Ihren Abend: Was machen Sie in den zwei Stunden, bevor Sie schlafen gehen?",
      openingTr: "Lütfen akşamınızı anlatın: Yatmadan önceki iki saatte ne yapıyorsunuz?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-psychische-gesundheit",
    icon: "feelings",
    level: "B1",
    course: "de",
    title: "Darüber reden hilft",
    titleTr: "Ruh sağlığı",
    summary: "Zorlandığını söylemeyi ve destek istemeyi edatı sabit fiillerle öğretir.",
    minutes: 10,
    focusId: "Verben-mit-Präpositionen",
    vocab: [
      { de: "sich anvertrauen", tr: "içini dökmek" },
      { de: "belastend", tr: "ağır gelen" },
      { de: "die Therapie", tr: "terapi" },
      { de: "die Überforderung", tr: "aşırı yüklenme" },
      { de: "entlasten", tr: "yükünü hafifletmek" },
    ],
    patterns: [
      { de: "Ich mache mir Sorgen um …", tr: "kaygıyı anlatır" },
      { de: "Ich vertraue mich … an.", tr: "birine açılmayı anlatır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü konu hakkında konuşmak, ağrıdan bahsetmekten zordur: zorlandığını söylemek. Ama dili öğrenilebilir ve bugün onu öğreneceğiz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu alanda üç fiil çok işe yarıyor ve üçünün de edatı sabit. Edatı yanlış seçmek cümleyi anlaşılmaz yapıyor. Önce kelimeler.")] },
      word("İlk", { de: "sich anvertrauen", tr: "içini dökmek" }),
      word("İkinci", { de: "belastend", tr: "ağır gelen" }),
      word("Üçüncü", { de: "die Therapie", tr: "terapi" }),
      word("Dördüncü", { de: "die Überforderung", tr: "aşırı yüklenme" }),
      word("Son", { de: "entlasten", tr: "yükünü hafifletmek" }),
      { say: [tr("Kalıbımız:"), de("Ich mache mir Sorgen um …"), tr("Dönüşlü zamir yönelme hâlinde, edat ise belirtme istiyor.")] },
      { say: [tr("Örnek:"), de("Ich mache mir seit Wochen Sorgen um meine Mutter."), tr("Tekrar edin:"), de("Ich mache mir seit Wochen Sorgen um meine Mutter")], expect: repeat("Ich mache mir seit Wochen Sorgen um meine Mutter") },
      { say: [tr("Sıra sende: 'Bu durum bana çok ağır geliyor.'")], expect: produce("Diese Situation ist sehr belastend für mich", [tr("Sıfat cümlenin sonunda, sonra edat öbeği:"), de("Diese Situation ist sehr belastend für mich."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kız kardeşime içimi döktüm.'")], expect: produce("Ich habe mich meiner Schwester anvertraut", [tr("Bu fiil yönelme ister ve dönüşlüdür; ortaç en sonda:"), de("Ich habe mich meiner Schwester anvertraut."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Konuşmak beni rahatlattı.'")], expect: produce("Das Gespräch hat mich entlastet", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Das Gespräch hat mich entlastet."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich mache mir Sorgen um meinen Vater."), tr("cümlesi doğru mu?")], expect: truefalse("Ich mache mir Sorgen um meinen Vater.", true, [tr("Doğru. Dönüşlü zamir yönelme hâlinde, edattan sonraki nesne belirtme hâlinde.")]) },
      { say: [tr("Son: 'Bir terapi bana iyi gelebilir.'")], expect: produce("Eine Therapie könnte mir guttun", [tr("Dilek kipiyle olasılık, mastar en sonda:"), de("Eine Therapie könnte mir guttun."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada güvendiğin birine zorlandığını anlatacaksın: ne ağır geliyor, ne yardımcı oluyor.")] },
    ],
    roleplay: {
      scene: "Güvendiğin bir arkadaşına son zamanlarda zorlandığını anlatıyorsun: ne ağır geliyor, ne zaman başladı, ne iyi geliyor. Edatı sabit fiillerle kur.",
      partner: "acele ettirmeyen, dinlemeyi bilen bir arkadaş",
      opening: "Du wirkst seit ein paar Wochen anders. Willst du erzählen, was gerade los ist?",
      openingTr: "Birkaç haftadır farklı görünüyorsun. Neler olduğunu anlatmak ister misin?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-notaufnahme",
    icon: "doctor",
    level: "B1",
    course: "de",
    title: "In der Notaufnahme",
    titleTr: "Acil serviste",
    summary: "Acilde olan biteni sırayla, önce olanı geriye çekerek anlatmayı öğretir.",
    minutes: 10,
    focusId: "Plusquamperfekt",
    vocab: [
      { de: "die Notaufnahme", tr: "acil servis" },
      { de: "stürzen", tr: "düşmek" },
      { de: "röntgen", tr: "röntgen çekmek" },
      { de: "die Beobachtung", tr: "gözlem" },
      { de: "der Verdacht", tr: "şüphe (tıbbi)" },
    ],
    patterns: [
      { de: "Nachdem ich gestürzt war, …", tr: "önce olan iş bir basamak geride" },
      { de: "Es wird geröntgt.", tr: "acil dilinde edilgen" },
    ],
    lecture: [
      { say: [tr("Merhaba! Acilde ilk soru hep aynıdır: ne oldu. Cevap bir anlatıdır ve anlatının sırası fiil biçimiyle gösterilir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Önce olan iş bir basamak geriye çekiliyor. Türkçedeki '-mişti' ekiyle aynı iş. Bir de acilin kendi edilgen dili var. Önce kelimeler.")] },
      word("İlk", { de: "die Notaufnahme", tr: "acil servis" }),
      word("İkinci", { de: "stürzen", tr: "düşmek" }),
      word("Üçüncü", { de: "röntgen", tr: "röntgen çekmek" }),
      word("Dördüncü", { de: "die Beobachtung", tr: "gözlem" }),
      word("Son", { de: "der Verdacht", tr: "şüphe (tıbbi)" }),
      { say: [tr("Kalıbımız:"), de("Nachdem ich gestürzt war, konnte ich nicht mehr aufstehen."), tr("Düşme önce oldu, o yüzden bir basamak geride; kalkamamak sonra oldu.")] },
      { say: [tr("Tekrar edin:"), de("Nachdem ich gestürzt war, konnte ich nicht mehr aufstehen")], expect: repeat("Nachdem ich gestürzt war, konnte ich nicht mehr aufstehen") },
      { say: [tr("Sıra sende: 'Merdivende düştükten sonra beni buraya getirdiler.'")], expect: produce("Nachdem ich auf der Treppe gestürzt war, wurde ich hergebracht", [tr("Önce olan iş geride, ana cümle edilgen:"), de("Nachdem ich auf der Treppe gestürzt war, wurde ich hergebracht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi acilin dili: 'Önce röntgen çekiliyor.'")], expect: produce("Zuerst wird geröntgt", [tr("Öznesiz edilgen; yardımcı fiil ikinci, ortaç sonda:"), de("Zuerst wird geröntgt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kırık şüphesi var.'")], expect: produce("Es besteht der Verdacht auf einen Bruch", [tr("Bu kalıp tıp dilinde sabittir; edat belirtme ister:"), de("Es besteht der Verdacht auf einen Bruch."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nachdem ich gestürzt bin, rief ich den Notarzt."), tr("cümlesi doğru mu?")], expect: truefalse("Nachdem ich gestürzt bin, rief ich den Notarzt.", false, [tr("Önce olan iş bir basamak geriye çekilir:"), de("Nachdem ich gestürzt war, rief ich den Notarzt.")]) },
      { say: [tr("Son: 'Bir gece gözlemde kalmam gerekiyor.'")], expect: produce("Ich muss eine Nacht zur Beobachtung bleiben", [tr("Modal fiil çekimli, mastar en sonda:"), de("Ich muss eine Nacht zur Beobachtung bleiben."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada acil servis hemşiresine olanı anlatacaksın: ne oldu, ne zaman, sonra ne yaptın.")] },
    ],
    roleplay: {
      scene: "Acil serviste hemşireye olanı anlatıyorsun: ne oldu, hangi sırayla oldu, şu an neren ağrıyor. Sıralamayı önce olan işi geriye çekerek kur.",
      partner: "hızlı ve net soru soran bir acil servis hemşiresi",
      opening: "Bleiben Sie ruhig sitzen. Erzählen Sie kurz: Was ist passiert und wann war das?",
      openingTr: "Sakin bir şekilde oturun. Kısaca anlatın: Ne oldu ve ne zaman oldu?",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-impfung",
    icon: "pill",
    level: "B1",
    course: "de",
    title: "Der Impftermin",
    titleTr: "Aşı randevusu",
    summary: "Aşı sürecini edilgen cümlelerle anlamayı ve soru sormayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "die Impfung", tr: "aşı" },
      { de: "der Impfpass", tr: "aşı kartı" },
      { de: "auftreten", tr: "ortaya çıkmak" },
      { de: "die Auffrischung", tr: "hatırlatma dozu" },
      { de: "harmlos", tr: "zararsız" },
    ],
    patterns: [
      { de: "Es wird geimpft.", tr: "öznesiz edilgen" },
      { de: "Nebenwirkungen können auftreten.", tr: "olasılık bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Aşı randevusunda duyacağın cümlelerin çoğu edilgendir ve iki tanesi neredeyse her seferinde aynıdır. Bugün onları kuracağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de olasılık kalıbı öğreneceğiz: olabilir ama olmayabilir. Modal fiille kurulur. Önce kelimeler.")] },
      word("İlk", { de: "die Impfung", tr: "aşı" }),
      word("İkinci", { de: "der Impfpass", tr: "aşı kartı" }),
      word("Üçüncü", { de: "auftreten", tr: "ortaya çıkmak" }),
      word("Dördüncü", { de: "die Auffrischung", tr: "hatırlatma dozu" }),
      word("Son", { de: "harmlos", tr: "zararsız" }),
      { say: [tr("Kalıbımız:"), de("Es wird geimpft."), tr("Cümlede gerçek bir özne yok; baştaki kelime yalnızca yer tutuyor.")] },
      { say: [tr("Örnek:"), de("Heute wird nur vormittags geimpft."), tr("Tekrar edin:"), de("Heute wird nur vormittags geimpft")], expect: repeat("Heute wird nur vormittags geimpft") },
      { say: [tr("Sıra sende: 'Aşı kartı getirilmeli.'")], expect: produce("Der Impfpass muss mitgebracht werden", [tr("Modal fiille edilgen; ortaç ve werden en sonda:"), de("Der Impfpass muss mitgebracht werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi olasılık: 'Hafif yan etkiler görülebilir.'")], expect: produce("Leichte Nebenwirkungen können auftreten", [tr("Modal fiil çekimli, ayrılabilen mastar en sonda:"), de("Leichte Nebenwirkungen können auftreten."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, soru sor: 'Hatırlatma dozu ne zaman gerekiyor?'")], expect: produce("Wann ist die Auffrischung nötig", [tr("Soru kelimesi başta, fiil ikinci sırada:"), de("Wann ist die Auffrischung nötig?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Nebenwirkungen kann auftreten."), tr("cümlesi doğru mu?")], expect: truefalse("Nebenwirkungen kann auftreten.", false, [tr("Özne çoğul olduğu için modal fiil de çoğul çekilir:"), de("Nebenwirkungen können auftreten.")]) },
      { say: [tr("Son: 'Bu tamamen zararsız.'")], expect: produce("Das ist völlig harmlos", [tr("Kısa değerlendirme cümlesi:"), de("Das ist völlig harmlos."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada aşı randevusundasın: ne getirmen gerekiyor, yan etkiler ne, hatırlatma dozu ne zaman.")] },
    ],
    roleplay: {
      scene: "Aşı randevusundasın: ne getirmen gerektiğini, olası yan etkileri ve hatırlatma dozunun ne zaman olacağını sor. Duyduğun edilgen cümleleri kendi sözlerinle tekrarla.",
      partner: "kısa ve net konuşan bir muayenehane çalışanı",
      opening: "Guten Tag. Haben Sie Ihren Impfpass dabei? Dann schauen wir gleich, was heute gemacht wird.",
      openingTr: "İyi günler. Aşı kartınız yanınızda mı? O zaman bugün ne yapılacağına bakalım.",
      minTurns: 5,
    },
  },

  {
    id: "de-b1-krankenhaus-besuch",
    icon: "flower",
    level: "B1",
    course: "de",
    title: "Am Krankenbett",
    titleTr: "Hasta ziyareti",
    summary: "Hasta ziyaretinde iyi dilek sunmayı ve yardım teklif etmeyi öğretir.",
    minutes: 10,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "die Station", tr: "servis (hastane)" },
      { de: "die Besuchszeit", tr: "ziyaret saati" },
      { de: "sich schonen", tr: "kendini korumak" },
      { de: "aufmuntern", tr: "neşelendirmek" },
      { de: "die Genesung", tr: "iyileşme" },
    ],
    patterns: [
      { de: "Wenn du etwas brauchst, würde ich …", tr: "koşullu yardım teklifi" },
      { de: "Gute Besserung!", tr: "iyi dilek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve en insani olanı: hasta ziyareti. Söylenecek üç şey var — iyi dilek, yardım teklifi ve moral. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yardım teklifini düz kipte yapmak baskı gibi durabilir; dilek kipi teklifi hafifletiyor ve karşı taraf rahatça hayır diyebiliyor. Önce kelimeler.")] },
      word("İlk", { de: "die Station", tr: "servis (hastane)" }),
      word("İkinci", { de: "die Besuchszeit", tr: "ziyaret saati" }),
      word("Üçüncü", { de: "sich schonen", tr: "kendini korumak" }),
      word("Dördüncü", { de: "aufmuntern", tr: "neşelendirmek" }),
      word("Son", { de: "die Genesung", tr: "iyileşme" }),
      { say: [tr("Kalıbımız:"), de("Wenn du etwas brauchst, würde ich es dir bringen."), tr("Koşul başta, ana cümlede dilek kipi. Teklif yumuşuyor.")] },
      { say: [tr("Tekrar edin:"), de("Wenn du etwas brauchst, würde ich es dir bringen")], expect: repeat("Wenn du etwas brauchst, würde ich es dir bringen") },
      { say: [tr("Sıra sende: 'İstersen alışverişini ben yapardım.'")], expect: produce("Wenn du willst, würde ich für dich einkaufen", [tr("Koşul önde, ana cümlede dilek kipi ve mastar sonda:"), de("Wenn du willst, würde ich für dich einkaufen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Şimdilik kendini kollamalısın.'")], expect: produce("Du solltest dich erst mal schonen", [tr("Öneri biçimi, dönüşlü zamir fiilin arkasında:"), de("Du solltest dich erst mal schonen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, soru sor: 'Ziyaret saatleri ne zaman?'")], expect: produce("Wann sind die Besuchszeiten", [tr("Çoğul özne, çoğul fiil:"), de("Wann sind die Besuchszeiten?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenn du etwas brauchst, ich würde kommen."), tr("cümlesi doğru mu?")], expect: truefalse("Wenn du etwas brauchst, ich würde kommen.", false, [tr("Koşul yan cümlesi başta olduğunda ana cümle fiille başlar:"), de("Wenn du etwas brauchst, würde ich kommen.")]) },
      { say: [tr("Son: 'Sana çabuk bir iyileşme diliyorum.'")], expect: produce("Ich wünsche dir eine schnelle Genesung", [tr("Yönelme ve belirtme nesnesi bir arada:"), de("Ich wünsche dir eine schnelle Genesung."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada hastanede bir yakınını ziyaret edeceksin: nasıl olduğunu sor, yardım teklif et, moral ver.")] },
    ],
    roleplay: {
      scene: "Hastanede bir yakınını ziyaret ediyorsun: nasıl olduğunu sor, yardım teklif et, moral ver. Tekliflerini dilek kipiyle yumuşat.",
      partner: "yorgun ama konuşmak isteyen bir hasta yakının",
      opening: "Schön, dass du da bist. Setz dich — und erzähl mir was von draußen, ja?",
      openingTr: "İyi ki geldin. Otur — ve bana dışarıdan bir şeyler anlat, olur mu?",
      minTurns: 5,
    },
  },
];
