import { de, tr, type LectureStep, type Lesson, type Segment } from "../types";

/**
 * B1 · Modül 17 — Toplum, hukuk ve göç (161–170).
 *
 * Modül 5 bürokrasinin İŞLEMİNİ öğretmişti: dilekçe, itiraz, randevu. Bu
 * modül o işlemlerin arkasındaki toplumu konuşuyor — kim vatandaş, kim
 * azınlık, hangi kural neden var.
 *
 * Kelimelerin çoğu gazete ve resmî yazıdan tanıdık; sınavın okuma
 * bölümünde de tam olarak buradan çıkıyor. B1 öğrencisi bu sözcükleri
 * üretmese bile TANIMAK zorunda, o yüzden dersler okuma ve dinlemeye
 * yakın kurgulandı: metni anlayıp bir görüş bildirmek.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [
      tr(`${n} kelimemiz:`),
      de(w.de),
      tr(`Türkçesi '${w.tr}' demek${note ? ` — ${note}` : ""}. Lütfen`),
      de(w.de),
      tr("deyin."),
    ],
    expect: repeat(w.de),
  };
}

export const deB1B17: Lesson[] = [
  {
    id: "de-b1-migration",
    icon: "flag",
    level: "B1",
    course: "de",
    title: "Angekommen",
    titleTr: "Göç hikâyesi",
    summary: "Geçmişteki bir dönemi als bağlacıyla anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-als",
    vocab: [
      { de: "die Migration", tr: "göç" },
      { de: "der Migrant", tr: "göçmen" },
      { de: "die Migrantin", tr: "kadın göçmen" },
      { de: "die Integration", tr: "uyum" },
      { de: "die Flucht", tr: "kaçış" },
      { de: "fliehen", tr: "kaçmak" },
      { de: "die Muttersprache", tr: "anadil" },
      { de: "die Zweitsprache", tr: "ikinci dil" },
    ],
    patterns: [
      { de: "Als ich ankam, …", tr: "geçmişte tek seferlik olayı anlatır" },
      { de: "Am Anfang war es …", tr: "başlangıcın nasıl olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kendi geliş hikâyeni anlatacaksın. Bu hikâyenin bağlacı belli: geçmişte bir kez olan olay için kullanılan bağlaç. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yan cümlede fiil sona gider ve yan cümle başta olursa ana cümle fiille başlar. Önce kelimeler.")] },
      word("İlk", { de: "die Migration", tr: "göç" }),
      word("İkinci", { de: "der Migrant", tr: "göçmen" }),
      word("Üçüncü", { de: "die Migrantin", tr: "kadın göçmen" }),
      word("Dördüncü", { de: "die Integration", tr: "uyum" }),
      word("Beşinci", { de: "die Flucht", tr: "kaçış" }),
      word("Altıncı", { de: "fliehen", tr: "kaçmak" }),
      word("Yedinci", { de: "die Muttersprache", tr: "anadil" }),
      word("Son", { de: "die Zweitsprache", tr: "ikinci dil" }),
      { say: [tr("İlk kalıbımız geliş anını anlatıyor. Yan cümle başta, ana cümle fiille başlıyor.")] },
      { say: [tr("Örnek:"), de("Als ich ankam, sprach ich kein Wort Deutsch."), tr("Tekrar edin:"), de("Als ich ankam, sprach ich kein Wort Deutsch")], expect: repeat("Als ich ankam, sprach ich kein Wort Deutsch") },
      { say: [tr("Sıra sende: 'İlk işimi bulduğumda uyum kolaylaştı.'")], expect: produce("Als ich die erste Arbeit fand, wurde die Integration leichter", [tr("Yan cümlede fiil sonda, ana cümle fiille başlıyor:"), de("Als ich die erste Arbeit fand, wurde die Integration leichter."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız başlangıcı anlatıyor: bir zaman öbeği ve geçmiş zaman.")] },
      { say: [tr("Şimdi: 'Başta her şey yabancıydı.'")], expect: produce("Am Anfang war alles fremd", [tr("Zaman öbeği başta, fiil ikinci sırada:"), de("Am Anfang war alles fremd."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Als ich hier ankam, ich kannte niemanden."), tr("cümlesi doğru mu?")], expect: truefalse("Als ich hier ankam, ich kannte niemanden.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar, özneyle değil:"), de("Als ich hier ankam, kannte ich niemanden.")]) },
      { say: [tr("Son: 'Anadilim hâlâ evde konuştuğum dil.'")], expect: produce("Meine Muttersprache ist immer noch die Sprache zu Hause", [tr("Basit ana cümle, fiil ikinci sırada:"), de("Meine Muttersprache ist immer noch die Sprache zu Hause."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi kendi geliş hikâyeni anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Bir dil kursunda tanışma turundasın. Nereden geldiğini, ilk zamanların nasıl olduğunu ve neyin değiştiğini anlatıyorsun.",
      partner: "kendi hikâyesini de anlatan, meraklı bir kurs arkadaşı",
      opening: "Wir stellen uns kurz vor — magst du erzählen, wie du hierhergekommen bist?",
      openingTr: "Kısaca tanışalım — buraya nasıl geldiğini anlatmak ister misin?",
      goal: "Geliş anı, ilk zorluklar ve bugünkü durum sırayla anlatılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-konsulat",
    icon: "flag",
    level: "B1",
    course: "de",
    title: "Im Konsulat",
    titleTr: "Konsoloslukta",
    summary: "Resmî kurumda bilmediklerini dolaylı soruyla sormayı öğretir.",
    minutes: 10,
    focusId: "Indirekte-Frage",
    vocab: [
      { de: "das Konsulat", tr: "konsolosluk" },
      { de: "die Botschaft", tr: "büyükelçilik" },
      { de: "das Asyl", tr: "sığınma" },
      { de: "die Bürgerin", tr: "kadın vatandaş" },
      { de: "die Personalien", tr: "kimlik bilgileri" },
      { de: "der Zivilstand", tr: "medeni hâl" },
      { de: "anerkennen", tr: "tanımak, denklik vermek" },
      { de: "zusagen", tr: "söz vermek" },
    ],
    patterns: [
      { de: "Können Sie mir sagen, welche …?", tr: "hangi belgenin gerektiğini sorar" },
      { de: "Ich bin nicht sicher, ob …", tr: "emin olmadığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Konsolosluktasın ve hangi belgenin gerektiğini bilmiyorsun. Resmî kurumda soru dolaylı sorulur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Soru sözcüğü bağlaca döner ve fiil sona gider; soru sözcüğü yoksa emin olmadığını bildiren bağlaç gelir. Önce kelimeler.")] },
      word("İlk", { de: "das Konsulat", tr: "konsolosluk" }),
      word("İkinci", { de: "die Botschaft", tr: "büyükelçilik" }, "aynı sözcük 'mesaj' anlamına da gelir"),
      word("Üçüncü", { de: "das Asyl", tr: "sığınma" }),
      word("Dördüncü", { de: "die Bürgerin", tr: "kadın vatandaş" }),
      word("Beşinci", { de: "die Personalien", tr: "kimlik bilgileri" }, "hep çoğul kullanılır"),
      word("Altıncı", { de: "der Zivilstand", tr: "medeni hâl" }),
      word("Yedinci", { de: "anerkennen", tr: "tanımak, denklik vermek" }),
      word("Son", { de: "zusagen", tr: "söz vermek" }),
      { say: [tr("İlk kalıbımız hangi belgenin gerektiğini soruyor. Soru sözcüğü bağlaç oluyor, fiil sona gidiyor.")] },
      { say: [tr("Örnek:"), de("Können Sie mir sagen, welche Papiere ich brauche?"), tr("Tekrar edin:"), de("Können Sie mir sagen, welche Papiere ich brauche")], expect: repeat("Können Sie mir sagen, welche Papiere ich brauche") },
      { say: [tr("Sıra sende: 'Kimlik bilgilerimin nereye yazıldığını söyleyebilir misiniz?'")], expect: produce("Können Sie mir sagen, wo meine Personalien eingetragen werden", [tr("Bağlaçtan sonra fiil en sonda:"), de("Können Sie mir sagen, wo meine Personalien eingetragen werden?"), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız emin olmadığını söylüyor. Bu kalıp yanlış bilgi vermeni engeller ve resmî yerde bu önemlidir.")] },
      { say: [tr("Şimdi: 'Diplomamın tanınıp tanınmadığından emin değilim.'")], expect: produce("Ich bin nicht sicher, ob mein Diplom anerkannt wird", [tr("Bağlaçtan sonra edilgen yapı, fiil sonda:"), de("Ich bin nicht sicher, ob mein Diplom anerkannt wird."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich frage mich, ob ist das Konsulat heute offen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich frage mich, ob ist das Konsulat heute offen.", false, [tr("Bu bağlaçtan sonra fiil öne gelmez, cümlenin sonuna gider:"), de("Ich frage mich, ob das Konsulat heute offen ist.")]) },
      { say: [tr("Son: 'Bana bir randevu sözü verdiler mi bilmiyorum.'")], expect: produce("Ich weiß nicht, ob sie mir einen Termin zugesagt haben", [tr("Ayrılabilen fiil yan cümlede birleşik kalır, yardımcı fiil sonda:"), de("Ich weiß nicht, ob sie mir einen Termin zugesagt haben."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi konsoloslukta bilmediklerini soracaksın.")] },
    ],
    roleplay: {
      scene: "Konsolosluktasın. Hangi belgelerin gerektiğini, diplomanın tanınıp tanınmadığını ve ne kadar süreceğini dolaylı sorularla öğreniyorsun.",
      partner: "kalabalıkla uğraşan ama net bilgi veren bir konsolosluk görevlisi",
      opening: "Der Nächste bitte. Worum geht es bei Ihnen?",
      openingTr: "Sıradaki lütfen. Konunuz nedir?",
      goal: "Gereken belgeler, denklik durumu ve süre öğrenilmiş, bir sonraki adım kararlaştırılmış olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-sprache-akzent",
    icon: "book",
    level: "B1",
    course: "de",
    title: "Zwei Sprachen",
    titleTr: "İki dilli olmak",
    summary: "Dilleri ve dil düzeylerini karşılaştırmayı öğretir.",
    minutes: 10,
    focusId: "Komparativ",
    vocab: [
      { de: "der Dialekt", tr: "lehçe" },
      { de: "die Aussprache", tr: "telaffuz" },
      { de: "das Alphabet", tr: "alfabe" },
      { de: "das Wörterbuch", tr: "sözlük" },
      { de: "fließend", tr: "akıcı" },
      { de: "duzen", tr: "senli benli konuşmak" },
      { de: "verwandt", tr: "akraba, ilgili" },
      { de: "das Geschlecht", tr: "cinsiyet" },
    ],
    patterns: [
      { de: "… fällt mir leichter als …", tr: "hangisinin daha kolay olduğunu söyler" },
      { de: "Je länger …, desto …", tr: "iki şeyin birlikte arttığını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! İki dil arasında yaşamak bir karşılaştırma hâlidir: hangisi daha kolay, hangisinde daha rahatsın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Karşılaştırma sıfata ek getirir; orantı ise ikili bir bağlaçla kurulur ve ilk bölümde fiil sona gider. Önce kelimeler.")] },
      word("İlk", { de: "der Dialekt", tr: "lehçe" }),
      word("İkinci", { de: "die Aussprache", tr: "telaffuz" }),
      word("Üçüncü", { de: "das Alphabet", tr: "alfabe" }),
      word("Dördüncü", { de: "das Wörterbuch", tr: "sözlük" }),
      word("Beşinci", { de: "fließend", tr: "akıcı" }),
      word("Altıncı", { de: "duzen", tr: "senli benli konuşmak" }, "resmî hitabın karşıtı"),
      word("Yedinci", { de: "verwandt", tr: "akraba, ilgili" }),
      word("Son", { de: "das Geschlecht", tr: "cinsiyet" }, "dilbilgisinde adın cinsi"),
      { say: [tr("İlk kalıbımız hangisinin kolay olduğunu söylüyor: kişi yönelme hâlinde, kolay gelen şey özne oluyor.")] },
      { say: [tr("Örnek:"), de("Die Aussprache fällt mir leichter als die Grammatik."), tr("Tekrar edin:"), de("Die Aussprache fällt mir leichter als die Grammatik")], expect: repeat("Die Aussprache fällt mir leichter als die Grammatik") },
      { say: [tr("Sıra sende: 'Okumak bana konuşmaktan daha kolay geliyor.'")], expect: produce("Lesen fällt mir leichter als Sprechen", [tr("Mastarlar özne oluyor, kişi yönelme hâlinde:"), de("Lesen fällt mir leichter als Sprechen."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız orantı kuruyor: ne kadar çok, o kadar iyi. İlk bölüm yan cümledir, fiil sona gider.")] },
      { say: [tr("Şimdi: 'Ne kadar uzun kalırsam o kadar akıcı konuşuyorum.'")], expect: produce("Je länger ich bleibe, desto fließender spreche ich", [tr("İlk bölümde fiil sonda, ikinci bölümde fiil öznenin önünde:"), de("Je länger ich bleibe, desto fließender spreche ich."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Dialekt ist schwer wie die Standardsprache."), tr("cümlesi doğru mu?")], expect: truefalse("Der Dialekt ist schwer wie die Standardsprache.", false, [tr("Eşitlik karşılaştırmasında sıfattan önce bir zarf gerekir:"), de("Der Dialekt ist so schwer wie die Standardsprache.")]) },
      { say: [tr("Son: 'Türkçe ile Almanca akraba diller değil.'")], expect: produce("Türkisch und Deutsch sind nicht verwandt", [tr("Çoğul özne, sıfat yüklem konumunda çekilmiyor:"), de("Türkisch und Deutsch sind nicht verwandt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi iki dilli olmayı bir arkadaşınla konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla iki dilli olmayı konuşuyorsunuz: hangisi daha kolay, nerede hangi dili kullanıyorsun, neyin zorlandığın.",
      partner: "tek dille büyümüş, merak eden bir arkadaş",
      opening: "Denkst du eigentlich auf Deutsch oder in deiner Muttersprache?",
      openingTr: "Aslında Almanca mı düşünüyorsun yoksa anadilinde mi?",
      goal: "İki dil en az üç ölçütle karşılaştırılmış ve bir zorluk anlatılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-minderheit-mehrheit",
    icon: "city",
    level: "B1",
    course: "de",
    title: "Wer gehört dazu?",
    titleTr: "Çoğunluk ve azınlık",
    summary: "Toplumsal bir konunun iki yanını ikili bağlaçlarla tartışmayı öğretir.",
    minutes: 11,
    focusId: "Zweiteilige-Konnektoren",
    vocab: [
      { de: "die Minderheit", tr: "azınlık" },
      { de: "die Mehrheit", tr: "çoğunluk" },
      { de: "allgemein", tr: "genel" },
      { de: "national", tr: "ulusal" },
      { de: "politisch", tr: "siyasi" },
      { de: "die Reform", tr: "reform" },
      { de: "der Einfluss", tr: "etki" },
      { de: "das Forum", tr: "forum" },
    ],
    patterns: [
      { de: "nicht nur …, sondern auch …", tr: "ikincisini öne çıkararak ekler" },
      { de: "weder … noch …", tr: "iki şeyi birden dışlar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün zor bir konu: kim topluma dâhil sayılıyor. Böyle konularda tek yanlı cümle hemen tartışmaya dönüşür. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkili bağlaçlar bir görüşün iki yanını aynı cümlede tutar. İkinci parçaları sabittir. Önce kelimeler.")] },
      word("İlk", { de: "die Minderheit", tr: "azınlık" }),
      word("İkinci", { de: "die Mehrheit", tr: "çoğunluk" }),
      word("Üçüncü", { de: "allgemein", tr: "genel" }),
      word("Dördüncü", { de: "national", tr: "ulusal" }),
      word("Beşinci", { de: "politisch", tr: "siyasi" }),
      word("Altıncı", { de: "die Reform", tr: "reform" }),
      word("Yedinci", { de: "der Einfluss", tr: "etki" }),
      word("Son", { de: "das Forum", tr: "forum" }),
      { say: [tr("İlk kalıbımız ikinciyi öne çıkarıyor. İkinci parçası özel bir bağlaçtır ve sıradan zıtlık bağlacıyla değiştirilemez.")] },
      { say: [tr("Örnek:"), de("Die Reform betrifft nicht nur die Mehrheit, sondern auch die Minderheit."), tr("Tekrar edin:"), de("Die Reform betrifft nicht nur die Mehrheit, sondern auch die Minderheit")], expect: repeat("Die Reform betrifft nicht nur die Mehrheit, sondern auch die Minderheit") },
      { say: [tr("Sıra sende: 'Bu yalnız siyasi değil, aynı zamanda toplumsal bir soru.'")], expect: produce("Das ist nicht nur eine politische, sondern auch eine soziale Frage", [tr("İkinci parça sabit, sıfat ikinci kez çekiliyor:"), de("Das ist nicht nur eine politische, sondern auch eine soziale Frage."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız ikisini birden dışlıyor. Bu bağlaç zaten olumsuz, ikinci bir olumsuzluk eklenmez.")] },
      { say: [tr("Şimdi: 'Ne ulusal ne de yerel bir çözüm var.'")], expect: produce("Es gibt weder eine nationale noch eine lokale Lösung", [tr("Bağlaç kendi başına olumsuz, sıfatlar çekilmeye devam ediyor:"), de("Es gibt weder eine nationale noch eine lokale Lösung."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Minderheit hat weder Einfluss noch kein Forum."), tr("cümlesi doğru mu?")], expect: truefalse("Die Minderheit hat weder Einfluss noch kein Forum.", false, [tr("Bu ikili bağlaç zaten olumsuzdur, ikinci bir olumsuzluk fazladan:"), de("Die Minderheit hat weder Einfluss noch ein Forum.")]) },
      { say: [tr("Son: 'Genel olarak bu tartışma yeni değil.'")], expect: produce("Allgemein ist diese Diskussion nicht neu", [tr("Zarf başta, fiil ikinci sırada:"), de("Allgemein ist diese Diskussion nicht neu."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bu konuyu dengeli biçimde tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla toplumda kimin sesinin duyulduğunu tartışıyorsunuz. Her görüşün iki yanını ikili bağlaçlarla söylüyorsun.",
      partner: "kesin görüşleri olan ama dinlemeye açık bir arkadaş",
      opening: "Ich finde, es wird zu viel darüber geredet — siehst du das auch so?",
      openingTr: "Bence bu konu fazla konuşuluyor — sen de böyle mi görüyorsun?",
      goal: "En az üç görüşün iki yanı söylenmiş ve ortak bir zemin bulunmuş olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-politik-reden",
    icon: "flag",
    level: "B1",
    course: "de",
    title: "Was denkst du darüber?",
    titleTr: "Siyaset konuşmak",
    summary: "Görüş ve kuşkuyu yan cümleyle söylemeyi öğretir.",
    minutes: 10,
    focusId: "Nebensatz-dass",
    vocab: [
      { de: "die Politik", tr: "siyaset" },
      { de: "der Politiker", tr: "politikacı" },
      { de: "die Versammlung", tr: "toplantı" },
      { de: "die Reaktion", tr: "tepki" },
      { de: "die Realität", tr: "gerçeklik" },
      { de: "die Wirklichkeit", tr: "gerçek" },
      { de: "die Theorie", tr: "kuram" },
      { de: "gerecht", tr: "adil" },
    ],
    patterns: [
      { de: "Ich bin überzeugt, dass …", tr: "inandığını yan cümleyle söyler" },
      { de: "Ich bezweifle, dass …", tr: "kuşkusunu yan cümleyle söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Siyaset konuşmak Almanya'da normaldir ama biçimi vardır: görüş yan cümleyle söylenir, doğrudan iddia edilmez. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bağlaçtan sonra çekimli fiil cümlenin en sonuna gider. Bu yapı görüşü bir cümlenin içine koyar ve tartışmayı yumuşatır. Önce kelimeler.")] },
      word("İlk", { de: "die Politik", tr: "siyaset" }),
      word("İkinci", { de: "der Politiker", tr: "politikacı" }),
      word("Üçüncü", { de: "die Versammlung", tr: "toplantı" }),
      word("Dördüncü", { de: "die Reaktion", tr: "tepki" }),
      word("Beşinci", { de: "die Realität", tr: "gerçeklik" }),
      word("Altıncı", { de: "die Wirklichkeit", tr: "gerçek" }, "aynı anlama gelen ikinci sözcük"),
      word("Yedinci", { de: "die Theorie", tr: "kuram" }),
      word("Son", { de: "gerecht", tr: "adil" }),
      { say: [tr("İlk kalıbımız inancı söylüyor: bir sıfat ve bağlaç. Bağlaçtan sonra fiil sona gidiyor.")] },
      { say: [tr("Örnek:"), de("Ich bin überzeugt, dass die Reform gerecht ist."), tr("Tekrar edin:"), de("Ich bin überzeugt, dass die Reform gerecht ist")], expect: repeat("Ich bin überzeugt, dass die Reform gerecht ist") },
      { say: [tr("Sıra sende: 'Bu kuramın gerçekle uyuşmadığına inanıyorum.'")], expect: produce("Ich bin überzeugt, dass die Theorie nicht zur Wirklichkeit passt", [tr("Bağlaçtan sonra fiil en sonda:"), de("Ich bin überzeugt, dass die Theorie nicht zur Wirklichkeit passt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız kuşkuyu söylüyor. Karşı çıkmanın en kibar biçimi budur: reddetmiyorsun, kuşku duyuyorsun.")] },
      { say: [tr("Şimdi: 'Bunun bir şeyi değiştireceğinden kuşkuluyum.'")], expect: produce("Ich bezweifle, dass das etwas ändert", [tr("Bağlaçtan sonra fiil sonda:"), de("Ich bezweifle, dass das etwas ändert."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich bin überzeugt, dass hat der Politiker recht."), tr("cümlesi doğru mu?")], expect: truefalse("Ich bin überzeugt, dass hat der Politiker recht.", false, [tr("Bağlaçtan sonra çekimli fiil cümlenin sonuna gider:"), de("Ich bin überzeugt, dass der Politiker recht hat.")]) },
      { say: [tr("Son: 'Toplantıdaki tepki güçlüydü.'")], expect: produce("Die Reaktion auf der Versammlung war stark", [tr("Yer öbeği özneyi niteliyor, fiil ikinci sırada:"), de("Die Reaktion auf der Versammlung war stark."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi güncel bir konuda görüşünü söyleyeceksin.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla güncel bir konuyu konuşuyorsunuz. Görüşünü yan cümleyle söylüyor, karşı çıkarken kuşku kalıbını kullanıyorsun.",
      partner: "senden farklı düşünen ama tartışmayı seven bir arkadaş",
      opening: "Hast du gehört, was gestern beschlossen wurde? Ich finde das ehrlich gesagt falsch.",
      openingTr: "Dün ne karar verildiğini duydun mu? Açıkçası bunu yanlış buluyorum.",
      goal: "Bir görüş gerekçesiyle söylenmiş, bir karşı görüşe kuşku kalıbıyla yanıt verilmiş olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-vor-gericht",
    icon: "law",
    level: "B1",
    course: "de",
    title: "Vor Gericht",
    titleTr: "Mahkemede",
    summary: "Mahkeme sürecini edilgen çatının geçmişiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präteritum",
    vocab: [
      { de: "der Richter", tr: "hâkim" },
      { de: "die Richterin", tr: "kadın hâkim" },
      { de: "das Urteil", tr: "hüküm" },
      { de: "der Prozess", tr: "dava" },
      { de: "verurteilen", tr: "mahkûm etmek" },
      { de: "verhaften", tr: "tutuklamak" },
      { de: "die Anwältin", tr: "kadın avukat" },
      { de: "die Zeugin", tr: "kadın tanık" },
    ],
    patterns: [
      { de: "Das Urteil wurde gestern gesprochen.", tr: "geçmişte alınan kararı anlatır" },
      { de: "Er wurde zu … verurteilt.", tr: "cezanın ne olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün mahkeme dilini tanıyacağız. Hukuk dili kişiyi değil işlemi anlatır, o yüzden neredeyse hep edilgendir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgenin geçmişinde yardımcı fiil geçmiş biçimde ikinci sırada, ortaç sonda. Önce kelimeler.")] },
      word("İlk", { de: "der Richter", tr: "hâkim" }),
      word("İkinci", { de: "die Richterin", tr: "kadın hâkim" }),
      word("Üçüncü", { de: "das Urteil", tr: "hüküm" }),
      word("Dördüncü", { de: "der Prozess", tr: "dava" }),
      word("Beşinci", { de: "verurteilen", tr: "mahkûm etmek" }),
      word("Altıncı", { de: "verhaften", tr: "tutuklamak" }),
      word("Yedinci", { de: "die Anwältin", tr: "kadın avukat" }),
      word("Son", { de: "die Zeugin", tr: "kadın tanık" }),
      { say: [tr("İlk kalıbımız kararı anlatıyor. Yardımcı fiil geçmiş biçiminde, ortaç sonda.")] },
      { say: [tr("Örnek:"), de("Das Urteil wurde gestern gesprochen."), tr("Tekrar edin:"), de("Das Urteil wurde gestern gesprochen")], expect: repeat("Das Urteil wurde gestern gesprochen") },
      { say: [tr("Sıra sende: 'Tanık iki kez dinlendi.'")], expect: produce("Die Zeugin wurde zweimal befragt", [tr("Yardımcı fiil ikinci sırada, ortaç sonda:"), de("Die Zeugin wurde zweimal befragt."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız cezayı söylüyor: edilgen ve bir edat öbeği. Gazete haberlerinde tam bu biçimde geçer.")] },
      { say: [tr("Şimdi: 'Para cezasına çarptırıldı.'")], expect: produce("Er wurde zu einer Geldstrafe verurteilt", [tr("Edat yönelme hâli istiyor, ortaç sonda:"), de("Er wurde zu einer Geldstrafe verurteilt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Prozess wurde gestern beginnen."), tr("cümlesi doğru mu?")], expect: truefalse("Der Prozess wurde gestern beginnen.", false, [tr("Edilgende asıl fiil ortaç hâlinde olmalı:"), de("Der Prozess wurde gestern begonnen.")]) },
      { say: [tr("Son: 'Avukat tarafından yeni bir belge sunuldu.'")], expect: produce("Von der Anwältin wurde ein neues Dokument vorgelegt", [tr("Yapan edatla başta, yardımcı fiil ikinci sırada:"), de("Von der Anwältin wurde ein neues Dokument vorgelegt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir haberi arkadaşına anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Gazetede okuduğun bir dava haberini arkadaşına anlatıyorsun: ne olmuş, kim ne demiş, karar ne çıkmış.",
      partner: "haberi duymamış, ayrıntı soran bir arkadaş",
      opening: "Was ist denn da passiert? Ich habe nur die Überschrift gesehen.",
      openingTr: "Orada ne olmuş? Ben yalnız başlığı gördüm.",
      goal: "Olay, süreç ve karar sırayla ve kişisiz biçimde anlatılmış olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-verbrechen-melden",
    icon: "law",
    level: "B1",
    course: "de",
    title: "Die Sache, die ich gesehen habe",
    titleTr: "Tanık olmak",
    summary: "Gördüğün bir olayı ilgi cümleleriyle tanımlamayı öğretir.",
    minutes: 10,
    focusId: "Relativsatz-Akkusativ",
    vocab: [
      { de: "der Verbrecher", tr: "suçlu" },
      { de: "die Verbrecherin", tr: "kadın suçlu" },
      { de: "die Kriminalpolizei", tr: "cinayet masası" },
      { de: "das Gefängnis", tr: "hapishane" },
      { de: "die Polizistin", tr: "kadın polis" },
      { de: "strafbar", tr: "cezayı gerektiren" },
      { de: "untersagt", tr: "yasaklanmış" },
      { de: "das Ereignis", tr: "olay" },
    ],
    patterns: [
      { de: "der Mann, den ich gesehen habe", tr: "tanımlanan kişi yan cümlenin nesnesidir" },
      { de: "Das ist strafbar.", tr: "bir davranışın suç olduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bir olaya tanık oldun ve tarif etmen gerekiyor. Tarif etmenin dili ilgi cümlesidir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tanımlanan şey yan cümlenin NESNESİ olduğunda eril ilgi zamiri biçim değiştirir; dişil ve nötr değişmez. Önce kelimeler.")] },
      word("İlk", { de: "der Verbrecher", tr: "suçlu" }),
      word("İkinci", { de: "die Verbrecherin", tr: "kadın suçlu" }),
      word("Üçüncü", { de: "die Kriminalpolizei", tr: "cinayet masası" }),
      word("Dördüncü", { de: "das Gefängnis", tr: "hapishane" }),
      word("Beşinci", { de: "die Polizistin", tr: "kadın polis" }),
      word("Altıncı", { de: "strafbar", tr: "cezayı gerektiren" }),
      word("Yedinci", { de: "untersagt", tr: "yasaklanmış" }, "resmî yazıda 'verboten' yerine geçer"),
      word("Son", { de: "das Ereignis", tr: "olay" }),
      { say: [tr("İlk kalıbımız gördüğün kişiyi tanımlıyor. Eril ad nesne olduğu için ilgi zamiri belirtme hâline giriyor.")] },
      { say: [tr("Örnek:"), de("Der Mann, den ich gesehen habe, war groß."), tr("Tekrar edin:"), de("Der Mann, den ich gesehen habe, war groß")], expect: repeat("Der Mann, den ich gesehen habe, war groß") },
      { say: [tr("Sıra sende: 'Anlattığım olay dün akşam oldu.'")], expect: produce("Das Ereignis, das ich beschrieben habe, war gestern Abend", [tr("Nötr adda ilgi zamiri değişmiyor, fiil sonda:"), de("Das Ereignis, das ich beschrieben habe, war gestern Abend."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız bir davranışın suç olduğunu söylüyor. Kısa, kesin ve resmî.")] },
      { say: [tr("Şimdi: 'Bu cezayı gerektiren bir şey.'")], expect: produce("Das ist strafbar", [tr("Kısa ana cümle, sıfat yüklem konumunda:"), de("Das ist strafbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Polizistin, die ich gefragt habe, war sehr freundlich."), tr("cümlesi doğru mu?")], expect: truefalse("Die Polizistin, die ich gefragt habe, war sehr freundlich.", true, [tr("Doğru. Dişil adda ilgi zamiri nesne olsa da biçim değiştirmez; yalnız fiil sona gider.")]) },
      { say: [tr("Son: 'Burada fotoğraf çekmek yasaklanmış.'")], expect: produce("Das Fotografieren ist hier untersagt", [tr("Mastar ad gibi kullanılıyor, sıfat yüklem konumunda:"), de("Das Fotografieren ist hier untersagt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi gördüğün bir olayı polise tarif edeceksin.")] },
    ],
    roleplay: {
      scene: "Sokakta bir olaya tanık oldun. Polise gördüklerini tarif ediyorsun: kimi gördün, ne yaptı, ne zaman oldu.",
      partner: "tarifi tutanağa geçiren, ayrıntı isteyen bir polis",
      opening: "Sie haben etwas beobachtet? Beschreiben Sie mir bitte die Person.",
      openingTr: "Bir şey mi gördünüz? Lütfen bana kişiyi tarif edin.",
      goal: "Kişi ve olay ilgi cümleleriyle tarif edilmiş ve zaman bilgisi verilmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-regeln-verstehen",
    icon: "law",
    level: "B1",
    course: "de",
    title: "Was ist hier erlaubt?",
    titleTr: "Kuralları anlamak",
    summary: "Kuralları ve sınırları edilgen cümlelerle anlamayı öğretir.",
    minutes: 10,
    focusId: "Passiv-Präsens",
    vocab: [
      { de: "begrenzt", tr: "sınırlı" },
      { de: "beschränken", tr: "sınırlamak" },
      { de: "behindern", tr: "engellemek" },
      { de: "erforderlich", tr: "gerekli" },
      { de: "zugänglich", tr: "erişilebilir" },
      { de: "ausschließen", tr: "dışlamak" },
      { de: "die Ausnahme", tr: "istisna" },
      { de: "die Begründung", tr: "gerekçe" },
    ],
    patterns: [
      { de: "Der Zugang wird beschränkt.", tr: "sınırlamayı kişisiz anlatır" },
      { de: "Eine Begründung ist erforderlich.", tr: "neyin gerektiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Resmî bir metin okuyacağız. Kural metinleri kimseye seslenmez; edilgen çatıyla yazılır ve bu onları soğuk ama net yapar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Edilgende yardımcı fiil ikinci sırada, ortaç sonda. Sıfat yüklem olduğunda çekilmez. Önce kelimeler.")] },
      word("İlk", { de: "begrenzt", tr: "sınırlı" }),
      word("İkinci", { de: "beschränken", tr: "sınırlamak" }),
      word("Üçüncü", { de: "behindern", tr: "engellemek" }),
      word("Dördüncü", { de: "erforderlich", tr: "gerekli" }),
      word("Beşinci", { de: "zugänglich", tr: "erişilebilir" }),
      word("Altıncı", { de: "ausschließen", tr: "dışlamak" }),
      word("Yedinci", { de: "die Ausnahme", tr: "istisna" }),
      word("Son", { de: "die Begründung", tr: "gerekçe" }),
      { say: [tr("İlk kalıbımız sınırlamayı anlatıyor. Kimin sınırladığı söylenmiyor; kural kendini söylüyor.")] },
      { say: [tr("Örnek:"), de("Der Zugang wird auf zehn Personen beschränkt."), tr("Tekrar edin:"), de("Der Zugang wird auf zehn Personen beschränkt")], expect: repeat("Der Zugang wird auf zehn Personen beschränkt") },
      { say: [tr("Sıra sende: 'Girişler engellenmez.'")], expect: produce("Die Eingänge werden nicht behindert", [tr("Çoğul özne, çoğul yardımcı fiil:"), de("Die Eingänge werden nicht behindert."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız neyin gerektiğini söylüyor: bir sıfat yüklem konumunda, o yüzden çekilmiyor.")] },
      { say: [tr("Şimdi: 'Yazılı bir gerekçe gerekli.'")], expect: produce("Eine schriftliche Begründung ist erforderlich", [tr("Öznede sıfat çekiliyor, yüklemdeki sıfat çekilmiyor:"), de("Eine schriftliche Begründung ist erforderlich."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Halle ist nur begrenzt zugänglich."), tr("cümlesi doğru mu?")], expect: truefalse("Die Halle ist nur begrenzt zugänglich.", true, [tr("Doğru. Buradaki iki sözcük de yüklem konumunda, o yüzden ikisi de çekilmiyor.")]) },
      { say: [tr("Son: 'İstisnalar dışlanmıyor.'")], expect: produce("Ausnahmen werden nicht ausgeschlossen", [tr("Çoğul özne, ayrılabilen fiilin ortacı sonda:"), de("Ausnahmen werden nicht ausgeschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi bir kural metnini birine açıklayacaksın.")] },
    ],
    roleplay: {
      scene: "Bir binanın kullanım kurallarını okudun. Yeni gelen birine neyin serbest, neyin sınırlı ve istisnanın ne olduğunu açıklıyorsun.",
      partner: "kuralları uzun bulan, istisna arayan biri",
      opening: "So viele Regeln — was gilt denn hier überhaupt?",
      openingTr: "Bu kadar çok kural — burada aslında ne geçerli?",
      goal: "En az üç kural kişisiz biçimde açıklanmış ve bir istisna söylenmiş olur.",
      minTurns: 8,
    },
  },
  {
    id: "de-b1-religion-frieden",
    icon: "culture",
    level: "B1",
    course: "de",
    title: "Trotz allem",
    titleTr: "Her şeye rağmen",
    summary: "Çekince belirterek hassas bir konuyu konuşmayı öğretir.",
    minutes: 11,
    focusId: "Nebensatz-obwohl",
    vocab: [
      { de: "die Religion", tr: "din" },
      { de: "der Gott", tr: "tanrı" },
      { de: "der Friede", tr: "barış" },
      { de: "die Mauer", tr: "duvar" },
      { de: "das Unglück", tr: "talihsizlik" },
      { de: "die Katastrophe", tr: "felaket" },
      { de: "tödlich", tr: "ölümcül" },
      { de: "geheim", tr: "gizli" },
    ],
    patterns: [
      { de: "Obwohl wir verschieden sind, …", tr: "farkı kabul edip yine de bir şey söyler" },
      { de: "Trotz allem …", tr: "her şeye rağmen anlamında" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün hassas bir konu var. Böyle konularda tek araç çekince bağlacıdır: farkı kabul edip yine de ortak bir şey söylemek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Çekince bağlacından sonra fiil sona gider. Bir de kısa bir edat öbeği öğreneceğiz, aynı işi tek sözcükle yapıyor. Önce kelimeler.")] },
      word("İlk", { de: "die Religion", tr: "din" }),
      word("İkinci", { de: "der Gott", tr: "tanrı" }),
      word("Üçüncü", { de: "der Friede", tr: "barış" }),
      word("Dördüncü", { de: "die Mauer", tr: "duvar" }, "insan yapımı, taş duvar"),
      word("Beşinci", { de: "das Unglück", tr: "talihsizlik" }),
      word("Altıncı", { de: "die Katastrophe", tr: "felaket" }),
      word("Yedinci", { de: "tödlich", tr: "ölümcül" }),
      word("Son", { de: "geheim", tr: "gizli" }),
      { say: [tr("İlk kalıbımız farkı kabul ediyor. Yan cümle başta, ana cümle fiille başlıyor.")] },
      { say: [tr("Örnek:"), de("Obwohl wir verschiedene Religionen haben, verstehen wir uns gut."), tr("Tekrar edin:"), de("Obwohl wir verschiedene Religionen haben, verstehen wir uns gut")], expect: repeat("Obwohl wir verschiedene Religionen haben, verstehen wir uns gut") },
      { say: [tr("Sıra sende: 'Aramızda bir duvar olsa da konuşuyoruz.'")], expect: produce("Obwohl eine Mauer zwischen uns steht, reden wir miteinander", [tr("Yan cümlede fiil sonda, ana cümle fiille başlıyor:"), de("Obwohl eine Mauer zwischen uns steht, reden wir miteinander."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız aynı işi kısa yapıyor: bir edat ve belirsiz bir zamir. Yan cümle kurmadan çekince belirtir.")] },
      { say: [tr("Şimdi: 'Her şeye rağmen barışa inanıyorum.'")], expect: produce("Trotz allem glaube ich an den Frieden", [tr("Edat öbeği başta, fiil ikinci sırada, bu fiilin edatı sabit:"), de("Trotz allem glaube ich an den Frieden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Obwohl das Unglück groß war, wir haben weitergemacht."), tr("cümlesi doğru mu?")], expect: truefalse("Obwohl das Unglück groß war, wir haben weitergemacht.", false, [tr("Yan cümle başta olduğunda ana cümle fiille başlar:"), de("Obwohl das Unglück groß war, haben wir weitergemacht.")]) },
      { say: [tr("Son: 'Felaketten sonra hiçbir şey gizli kalmadı.'")], expect: produce("Nach der Katastrophe blieb nichts geheim", [tr("Zaman öbeği başta, fiil ikinci sırada:"), de("Nach der Katastrophe blieb nichts geheim."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi farklı düşünen biriyle ortak bir zemin arayacaksın.")] },
    ],
    roleplay: {
      scene: "Senden çok farklı bir arka plandan gelen biriyle konuşuyorsun. Farkları kabul ediyor ama ortak bir zemin arıyorsun.",
      partner: "başta mesafeli, sonra açılan bir tanıdık",
      opening: "Wir kommen ja aus ganz verschiedenen Welten — funktioniert das überhaupt?",
      openingTr: "Bambaşka dünyalardan geliyoruz — bu yürür mü ki?",
      goal: "En az iki fark kabul edilmiş ve en az bir ortak nokta bulunmuş olur.",
      minTurns: 9,
    },
  },
  {
    id: "de-b1-engagement-buerger",
    icon: "handshake",
    level: "B1",
    course: "de",
    title: "Etwas verändern",
    titleTr: "Bir şeyi değiştirmek",
    summary: "Bir eylemin amacını damit yan cümlesiyle anlatmayı öğretir.",
    minutes: 10,
    focusId: "Nebensatz-damit",
    vocab: [
      { de: "streiken", tr: "grev yapmak" },
      { de: "fördern", tr: "desteklemek" },
      { de: "eintreten", tr: "girmek; savunmak" },
      { de: "unterscheiden", tr: "ayırt etmek" },
      { de: "die Aktivität", tr: "etkinlik" },
      { de: "der Beitrag", tr: "katkı" },
      { de: "traditionell", tr: "geleneksel" },
      { de: "vergeblich", tr: "boşuna" },
    ],
    patterns: [
      { de: "…, damit sich etwas ändert", tr: "eylemin amacını söyler" },
      { de: "eintreten für + Akkusativ", tr: "bir şeyi savunduğunu söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi: bir şeyi değiştirmek için ne yapılır. Her eylemin bir amacı olacak ve o amacı söyleyeceksin. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amaç bağlacından sonra fiil sona gider. Bir de edatı sabit bir fiil var; edatı ezberlenir. Önce kelimeler.")] },
      word("İlk", { de: "streiken", tr: "grev yapmak" }),
      word("İkinci", { de: "fördern", tr: "desteklemek" }),
      word("Üçüncü", { de: "eintreten", tr: "girmek; savunmak" }, "edatla birlikte 'savunmak' anlamına gelir"),
      word("Dördüncü", { de: "unterscheiden", tr: "ayırt etmek" }),
      word("Beşinci", { de: "die Aktivität", tr: "etkinlik" }),
      word("Altıncı", { de: "der Beitrag", tr: "katkı" }),
      word("Yedinci", { de: "traditionell", tr: "geleneksel" }),
      word("Son", { de: "vergeblich", tr: "boşuna" }),
      { say: [tr("İlk kalıbımız amacı söylüyor. Bağlaçtan sonra çekimli fiil cümlenin en sonuna gider.")] },
      { say: [tr("Örnek:"), de("Wir streiken, damit sich etwas ändert."), tr("Tekrar edin:"), de("Wir streiken, damit sich etwas ändert")], expect: repeat("Wir streiken, damit sich etwas ändert") },
      { say: [tr("Sıra sende: 'Gençleri destekliyoruz ki katkıda bulunabilsinler.'")], expect: produce("Wir fördern die Jugend, damit sie einen Beitrag leisten kann", [tr("Bağlaçtan sonra modal fiil en sonda:"), de("Wir fördern die Jugend, damit sie einen Beitrag leisten kann."), tr("Tekrar dene.")]) },
      { say: [tr("İkinci kalıbımız savunmayı söylüyor: ayrılabilen bir fiil ve sabit edat. Edattan sonra belirtme hâli gelir.")] },
      { say: [tr("Şimdi: 'Adil koşullar için mücadele ediyorum.'")], expect: produce("Ich trete für gerechte Bedingungen ein", [tr("Edatlı öbek ortada, ayrılabilen fiilin öneki sonda:"), de("Ich trete für gerechte Bedingungen ein."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wir streiken, damit ändert sich etwas."), tr("cümlesi doğru mu?")], expect: truefalse("Wir streiken, damit ändert sich etwas.", false, [tr("Amaç bağlacından sonra çekimli fiil cümlenin sonuna gider:"), de("Wir streiken, damit sich etwas ändert.")]) },
      { say: [tr("Son: 'Bütün çaba boşuna değildi.'")], expect: produce("Die ganze Mühe war nicht vergeblich", [tr("Basit ana cümle, sıfat yüklem konumunda:"), de("Die ganze Mühe war nicht vergeblich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Şimdi mahallende bir şeyi değiştirmek için ne yapacağını konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Mahallende bir sorun var ve bir şey yapmak istiyorsun. Bir komşuyla ne yapılabileceğini ve her adımın amacını konuşuyorsun.",
      partner: "daha önce denemiş ve umudunu kaybetmiş bir komşu",
      opening: "Das haben wir vor Jahren schon versucht — glauben Sie wirklich, dass das etwas bringt?",
      openingTr: "Bunu yıllar önce denedik — gerçekten bir işe yarayacağına inanıyor musunuz?",
      goal: "En az üç adım önerilmiş, her birinin amacı söylenmiş ve komşu bir adımı üstlenmiş olur.",
      minTurns: 9,
    },
  },
];
