import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * C1 · Modül 9 — Mizah, ironi ve kültürel incelik (081–090).
 *
 * Bu modülün ölçtüğü şey dilbilgisi değil ALGI. C1'de bir cümleyi anlamak
 * yetmiyor; söylenenin kastedilenden ne kadar uzak olduğunu duymak
 * gerekiyor. "Na, das lief ja super" cümlesindeki her kelime olumlu ve
 * cümlenin anlamı tam tersi.
 *
 * Türkçe konuşan için asıl güçlük ironiyi anlamamak değil — Türkçede de
 * ironi var — ölçüyü tutturmak: Alman ironisi genellikle SESSİZ, kuru ve
 * abartısız. Aşırı vurguyla söylenen ironi burada şaka değil kabalık sayılır.
 *
 * Bu yüzden modül üç şeyi birlikte çalıştırıyor: ironiyi duymak (081, 089),
 * sınırını bilmek (082, 088) ve kültürel farkı klişeye düşmeden konuşmak
 * (084, 085, 090). 086 ise seviyenin en pratik dersi: "sen"e geçiş — kimin
 * teklif edeceği, nasıl reddedileceği.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deC1B09: Lesson[] = [
  {
    id: "de-c1-ironie",
    icon: "feelings",
    level: "C1",
    course: "de",
    title: "Na, das lief ja super",
    titleTr: "İroniyi duymak",
    summary: "Söylenenle kastedilenin ters olduğu cümleleri tanımayı öğretir.",
    minutes: 12,
    focusId: "Ironie-Untertreibung",
    vocab: [
      { de: "der Unterton", tr: "alt ton" },
      { de: "das Gegenteil", tr: "tam tersi" },
      { de: "der Tonfall", tr: "ses tonu" },
      { de: "sarkastisch", tr: "alaycı" },
      { de: "entlarven", tr: "maskesini düşürmek" },
    ],
    patterns: [
      { de: "Na, das lief ja super.", tr: "ironi: tam tersi" },
      { de: "Gemeint ist das Gegenteil.", tr: "kastedilen tersi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: mizah ve incelik. Ve ilk ders bir ALGI dersi — söylenenin tersini duymak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir örnek:"), de("Na, das lief ja super."), tr("Her kelime olumlu, anlam tam tersi. Alman ironisi genellikle sessiz ve kuru; aşırı vurguyla söylenirse şaka değil kabalık olur. Önce kelimeler.")] },
      word("İlk", { de: "der Unterton", tr: "alt ton" }),
      word("İkinci", { de: "das Gegenteil", tr: "tam tersi" }),
      word("Üçüncü", { de: "der Tonfall", tr: "ses tonu" }),
      word("Dördüncü", { de: "sarkastisch", tr: "alaycı" }),
      word("Son", { de: "entlarven", tr: "maskesini düşürmek" }),
      { say: [tr("Örnek:"), de("Na, das lief ja super."), tr("Tekrar edin:"), de("Na, das lief ja super")], expect: repeat("Na, das lief ja super") },
      { say: [tr("Sıra sende: 'Kastedilen, söylenenin tam tersi.'")], expect: produce("Gemeint ist das Gegenteil des Gesagten", [tr("Ortaç başta; isimleşmiş ortaç tamlama hâlinde:"), de("Gemeint ist das Gegenteil des Gesagten."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İroniyi ses tonundan anlarsın.'")], expect: produce("Die Ironie erkennst du am Tonfall", [tr("Nesne öne alınmış; edat yönelme hâlinde kaynaşmış:"), de("Die Ironie erkennst du am Tonfall."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu cümlede bir alt ton var.'")], expect: produce("In diesem Satz schwingt ein Unterton mit", [tr("Tümleç başta; ayrılabilen önek sonda:"), de("In diesem Satz schwingt ein Unterton mit."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Na, das lief ja super heißt, dass alles gut gelaufen ist.")], expect: truefalse("Na, das lief ja super heißt, dass alles gut gelaufen ist.", false, [tr("Hayır — cümle ironiktir ve tam tersini söyler. Gerçekten iyi gittiyse parçacıksız ve düz söylenirdi:"), de("Das ist wirklich gut gelaufen.")]) },
      { say: [tr("Son: 'Bu bana fazla alaycı geldi.'")], expect: produce("Das kam mir zu sarkastisch vor", [tr("Kişi yönelme hâlinde; ayrılabilen önek sonda:"), de("Das kam mir zu sarkastisch vor."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada ironik bir yorumu çözeceksin.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın toplantıdan sonra ironik bir yorum yaptı ve sen ne demek istediğinden emin değilsin. Duyduğunu söyle, kastettiğini sor, kendi görüşünü açıkça belirt ve konuyu netleştir.",
      partner: "kuru mizah yapan, doğrudan söylemekten kaçınan bir meslektaş",
      opening: "Na, das lief ja super heute. Fandest du nicht auch?",
      openingTr: "Ee, bugün her şey harika gitti. Sence de öyle değil mi?",
      goal: "İronik yorumun ne demek istediği açığa çıkmış ve iki taraf da görüşünü açıkça söylemiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-sarkasmus-grenze",
    icon: "question",
    level: "C1",
    course: "de",
    title: "Witz oder Spitze?",
    titleTr: "Sınırında mizah",
    summary: "Şakanın nerede incitmeye döndüğünü fark etmeyi ve geri almayı öğretir.",
    minutes: 12,
    focusId: "Ironie-Untertreibung",
    vocab: [
      { de: "der Scherz", tr: "şaka" },
      { de: "verletzend", tr: "incitici" },
      { de: "ankommen", tr: "karşılık bulmak" },
      { de: "die Zielscheibe", tr: "hedef tahtası" },
      { de: "zurücknehmen", tr: "geri almak" },
    ],
    patterns: [
      { de: "Das ist nicht gut angekommen.", tr: "iyi karşılanmadı" },
      { de: "Ich nehme das zurück.", tr: "sözünü geri alır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün mizahın sınırı. Aynı şaka bir ortamda güldürür, ötekinde ilişkiyi bozar — ve fark çoğu zaman kimin sırtından yapıldığıdır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de geri alma kalıbı öğreneceğiz. Almanca bunu kısa ve net yapar: uzun açıklama değil, tek cümle. Önce kelimeler.")] },
      word("İlk", { de: "der Scherz", tr: "şaka" }),
      word("İkinci", { de: "verletzend", tr: "incitici" }),
      word("Üçüncü", { de: "ankommen", tr: "karşılık bulmak" }),
      word("Dördüncü", { de: "die Zielscheibe", tr: "hedef tahtası" }),
      word("Son", { de: "zurücknehmen", tr: "geri almak" }),
      { say: [tr("Örnek:"), de("Das war nur ein Scherz — aber er ist nicht gut angekommen."), tr("Tekrar edin:"), de("Das war nur ein Scherz, aber er ist nicht gut angekommen")], expect: repeat("Das war nur ein Scherz, aber er ist nicht gut angekommen") },
      { say: [tr("Sıra sende: 'Şaka birinin sırtından yapılmamalı.'")], expect: produce("Ein Scherz sollte nicht auf Kosten anderer gehen", [tr("Kalıplaşmış ifade tamlama hâlinde; mastar sonda:"), de("Ein Scherz sollte nicht auf Kosten anderer gehen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sözümü geri alıyorum.'")], expect: produce("Ich nehme das zurück", [tr("Ayrılabilen fiilin öneki sonda:"), de("Ich nehme das zurück."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kimse hedef tahtası olmak istemez.'")], expect: produce("Niemand will die Zielscheibe sein", [tr("Belirsiz zamir özne; mastar sonda:"), de("Niemand will die Zielscheibe sein."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist nicht gut ankommen."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist nicht gut ankommen.", false, [tr("Geçmiş zamanda mastar değil ortaç gelir:"), de("Das ist nicht gut angekommen.")]) },
      { say: [tr("Son: 'Bu incitici olabilir.'")], expect: produce("Das könnte verletzend sein", [tr("Dilek kipiyle temkinli uyarı:"), de("Das könnte verletzend sein."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sınırı aşan bir şakayı konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir toplantıda yaptığın şaka birini rahatsız etti. Onunla konuş: nasıl karşılandığını kabul et, niyetini açıkla, sözünü geri al ve bundan sonrasını konuş — savunmaya geçmeden.",
      partner: "rahatsız olmuş ama konuyu büyütmek istemeyen bir meslektaş",
      opening: "Es ist schon okay. Aber ehrlich gesagt war das vor allen ein bisschen viel — hast du das gemerkt?",
      openingTr: "Sorun değil. Ama açıkçası herkesin önünde biraz fazlaydı — fark ettin mi?",
      goal: "Şakanın nasıl karşılandığı kabul edilmiş, söz geri alınmış ve bundan sonrası için bir şey söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-wortspiele",
    icon: "idea",
    level: "C1",
    course: "de",
    title: "Der feine Wortwitz",
    titleTr: "Kelime oyunları",
    summary: "Çift anlamlı kelime oyunlarını fark etmeyi ve çeviri sınırını görmeyi öğretir.",
    minutes: 12,
    focusId: "Wortschatz-Nuancen",
    vocab: [
      { de: "das Wortspiel", tr: "kelime oyunu" },
      { de: "der doppelte Boden", tr: "ikinci anlam, çift dip" },
      { de: "der Kalauer", tr: "ucuz espri" },
      { de: "der Witz", tr: "espri" },
      { de: "gelingen", tr: "tutmak, başarılı olmak" },
    ],
    patterns: [
      { de: "Der Witz hat einen doppelten Boden.", tr: "ikinci anlamı var" },
      { de: "Das Wortspiel geht in der Übersetzung verloren.", tr: "çeviride kaybolur" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kelime oyunları. Ve baştan bir kabul: bunların çoğu çeviriye gelmez — çünkü espri anlamda değil SESTE. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Yine de fark etmek mümkün ve C1'de beklenen bu: gülmek zorunda değilsin, oyunun nerede olduğunu görmen yeterli. Önce kelimeler.")] },
      word("İlk", { de: "das Wortspiel", tr: "kelime oyunu" }),
      word("İkinci", { de: "der doppelte Boden", tr: "ikinci anlam" }),
      word("Üçüncü", { de: "der Kalauer", tr: "ucuz espri" }),
      word("Dördüncü", { de: "der Witz", tr: "espri" }),
      word("Son", { de: "gelingen", tr: "tutmak, başarılı olmak" }),
      { say: [tr("Örnek:"), de("Der Witz hat einen doppelten Boden."), tr("Tekrar edin:"), de("Der Witz hat einen doppelten Boden")], expect: repeat("Der Witz hat einen doppelten Boden") },
      { say: [tr("Sıra sende: 'Ucuz espri de espridir.'")], expect: produce("Auch ein Kalauer ist ein Witz", [tr("Zarf başta; iki belirtisiz isim:"), de("Auch ein Kalauer ist ein Witz."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu espri tuttu.'")], expect: produce("Der Witz ist gelungen", [tr("Bu fiil sein ile çekilir:"), de("Der Witz ist gelungen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İkinci anlamı fark ettin mi?'")], expect: produce("Hast du den zweiten Sinn bemerkt", [tr("Fiil başta soru; ortaç sonda:"), de("Hast du den zweiten Sinn bemerkt?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Wortspiel geht in der Übersetzung verloren."), tr("cümlesi doğru mu?")], expect: truefalse("Das Wortspiel geht in der Übersetzung verloren.", true, [tr("Doğru. Kalıplaşmış ifade değişmeden kullanılmış ve edat yönelme hâlinde konum bildiriyor.")]) },
      { say: [tr("Son: 'Kelime oyunu çeviride kayboluyor.'")], expect: produce("Das Wortspiel geht in der Übersetzung verloren", [tr("Kalıplaşmış ifade; edat yönelme hâlinde:"), de("Das Wortspiel geht in der Übersetzung verloren."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kelime oyununu birlikte çözeceksin.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın Almanca bir kelime oyunu yaptı ve sen anlamadın. Anlamadığını söyle, oyunu birlikte çözün, Türkçede bir karşılığı olup olmadığını tartışın ve kendi dilinden bir örnek ver.",
      partner: "kelime oyunlarına düşkün, açıklamayı seven bir arkadaş",
      opening: "Den musst du dir auf der Zunge zergehen lassen. Merkst du, wo der doppelte Boden ist?",
      openingTr: "Bunu ağzında bir yuvarlaman lazım. Çift anlamın nerede olduğunu fark ettin mi?",
      goal: "Kelime oyunu birlikte çözülmüş, çeviri sınırı konuşulmuş ve öğrenci kendi dilinden bir örnek vermiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-regionale-kultur",
    icon: "map",
    level: "C1",
    course: "de",
    title: "Nord gegen Süd",
    titleTr: "Bölge klişeleri",
    summary: "Bölgesel klişeleri göz kırparak ve toptan yargıya düşmeden konuşmayı öğretir.",
    minutes: 12,
    focusId: "Ironie-Untertreibung",
    vocab: [
      { de: "das Klischee", tr: "klişe" },
      { de: "das Augenzwinkern", tr: "göz kırpma" },
      { de: "zugeknöpft", tr: "kapalı, mesafeli" },
      { de: "der Landstrich", tr: "yöre" },
      { de: "pauschal", tr: "toptan" },
    ],
    patterns: [
      { de: "mit einem Augenzwinkern", tr: "göz kırparak" },
      { de: "Man sagt das, aber …", tr: "klişeye mesafe koyar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bölge klişeleri. Bu konuda konuşmanın bir kuralı var: klişe söylenebilir ama göz kırparak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Almanca bunu iki kalıpla yapıyor: bir mesafe ifadesi ve bir 'öyle derler ama'. İkisi olmadan klişe toptan yargıya döner. Önce kelimeler.")] },
      word("İlk", { de: "das Klischee", tr: "klişe" }),
      word("İkinci", { de: "das Augenzwinkern", tr: "göz kırpma" }),
      word("Üçüncü", { de: "zugeknöpft", tr: "kapalı, mesafeli" }),
      word("Dördüncü", { de: "der Landstrich", tr: "yöre" }),
      word("Son", { de: "pauschal", tr: "toptan" }),
      { say: [tr("Örnek:"), de("Der zugeknöpfte Norden — sagt man jedenfalls."), tr("Tekrar edin:"), de("Der zugeknöpfte Norden, sagt man jedenfalls")], expect: repeat("Der zugeknöpfte Norden, sagt man jedenfalls") },
      { say: [tr("Sıra sende: 'Klişeler göz kırparak söylenir.'")], expect: produce("Klischees sagt man mit einem Augenzwinkern", [tr("Edat yönelme hâli ister:"), de("Klischees sagt man mit einem Augenzwinkern."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Toptan bir yargı kimseye uymaz.'")], expect: produce("Ein pauschales Urteil trifft auf niemanden zu", [tr("Fiilin sabit edatı belirtme hâli ister; önek sonda:"), de("Ein pauschales Urteil trifft auf niemanden zu."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu yörede insanlar daha sessiz sayılır.'")], expect: produce("In diesem Landstrich gelten die Leute als stiller", [tr("Tümleç başta; als artı karşılaştırma biçimi:"), de("In diesem Landstrich gelten die Leute als stiller."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Klischees sagt man mit ein Augenzwinkern."), tr("cümlesi doğru mu?")], expect: truefalse("Klischees sagt man mit ein Augenzwinkern.", false, [tr("Bu edat yönelme hâli ister ve nötr belirteç einem olur:"), de("Klischees sagt man mit einem Augenzwinkern.")]) },
      { say: [tr("Son: 'Öyle derler ama ben başka gördüm.'")], expect: produce("Man sagt das, aber ich habe es anders erlebt", [tr("İki cümle; ikincisinde ortaç sonda:"), de("Man sagt das, aber ich habe es anders erlebt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bölge farklarını klişeye düşmeden konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığın senin ülkene ya da yaşadığın bölgeye dair klişelerle konuşuyor. Klişenin nereden geldiğini kabul et, kendi gözlemini anlat, toptan yargıya nazikçe itiraz et ve karşılığında bir soru sor.",
      partner: "kötü niyetli olmayan ama klişelerle konuşan bir tanıdık",
      opening: "Bei euch ist man doch viel offener als hier im Norden, oder?",
      openingTr: "Sizde insanlar buradaki kuzeydekilerden çok daha açık, değil mi?",
      goal: "Klişenin kaynağı kabul edilmiş, kendi gözlem anlatılmış ve toptan yargıya nazikçe itiraz edilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-dialekte-hoeren",
    icon: "culture",
    level: "C1",
    course: "de",
    title: "Hochdeutsch mit Farbe",
    titleTr: "Lehçe farkındalığı",
    summary: "Bölgesel farkları anlamayı hedefleyen bir dinleme tutumu kazandırır.",
    minutes: 12,
    focusId: "Wortschatz-Nuancen",
    vocab: [
      { de: "der Dialekt", tr: "lehçe" },
      { de: "die Mundart", tr: "yerel ağız" },
      { de: "die Färbung", tr: "tını, renk" },
      { de: "regional", tr: "bölgesel" },
      { de: "sich verständigen", tr: "anlaşmak" },
    ],
    patterns: [
      { de: "Servus im Süden, Moin im Norden.", tr: "bölgesel selamlar" },
      { de: "verstehen, nicht sprechen", tr: "hedef: anlamak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün lehçeler. Ama hedef net: konuşmak değil ANLAMAK. Bir lehçeyi öğrenmek zorunda değilsin; duyduğunda kaybolmaman yeterli. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir örnek: aynı küçük ekmeğin en az üç adı var — Brötchen, Semmel, Schrippe. Üçü de doğru, üçü de başka yerde. Önce kelimeler.")] },
      word("İlk", { de: "der Dialekt", tr: "lehçe" }),
      word("İkinci", { de: "die Mundart", tr: "yerel ağız" }),
      word("Üçüncü", { de: "die Färbung", tr: "tını, renk" }),
      word("Dördüncü", { de: "regional", tr: "bölgesel" }),
      word("Son", { de: "sich verständigen", tr: "anlaşmak" }),
      { say: [tr("Örnek:"), de("Servus im Süden, Moin im Norden."), tr("Tekrar edin:"), de("Servus im Süden, Moin im Norden")], expect: repeat("Servus im Süden, Moin im Norden") },
      { say: [tr("Sıra sende: 'Aynı ekmeğin üç adı var.'")], expect: produce("Dasselbe Brötchen hat drei Namen", [tr("İşaret sıfatı nötr yalın hâlde:"), de("Dasselbe Brötchen hat drei Namen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Ağzı anlamak konuşmaktan kolaydır.'")], expect: produce("Die Mundart zu verstehen ist leichter als sie zu sprechen", [tr("İki mastar öbeği karşılaştırılıyor:"), de("Die Mundart zu verstehen ist leichter als sie zu sprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Konuşmasında hafif bir bölgesel tını var.'")], expect: produce("In seiner Sprache liegt eine leichte regionale Färbung", [tr("Konum bildiren edat yönelme hâli ister:"), de("In seiner Sprache liegt eine leichte regionale Färbung."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("In seine Sprache liegt eine leichte Färbung."), tr("cümlesi doğru mu?")], expect: truefalse("In seine Sprache liegt eine leichte Färbung.", false, [tr("Burada hareket değil konum var, o yüzden edat yönelme hâli ister:"), de("In seiner Sprache liegt eine leichte Färbung.")]) },
      { say: [tr("Son: 'Yine de anlaşabiliyoruz.'")], expect: produce("Wir verständigen uns trotzdem", [tr("Dönüşlü fiil; zarf sonda:"), de("Wir verständigen uns trotzdem."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada lehçesi güçlü biriyle anlaşacaksın.")] },
    ],
    roleplay: {
      scene: "Başka bir bölgeden gelen biriyle konuşuyorsun ve bazı kelimelerini anlamıyorsun. Anlamadığını kibarca söyle, karşılığını sor, kendi bölgendeki kullanımı anlat ve sohbeti sürdür.",
      partner: "kendi ağzıyla konuşan, sorulunca memnuniyetle açıklayan bir tanıdık",
      opening: "Magst du eine Semmel? Oder sagt man bei euch anders dazu?",
      openingTr: "Bir Semmel ister misin? Yoksa sizde başka mı deniyor?",
      goal: "Anlaşılmayan kelimeler sorulup öğrenilmiş, kendi bölgesel kullanım anlatılmış ve sohbet sürdürülmüş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-duzen-siezen-c1",
    icon: "greet",
    level: "C1",
    course: "de",
    title: "Das heikle Du",
    titleTr: "Sen'e geçiş sanatı",
    summary: "Samimiyet biçimini teklif etmeyi ve reddetmeyi kibarca öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II-Diplomatie",
    vocab: [
      { de: "heikel", tr: "hassas" },
      { de: "der Umgangston", tr: "hitap tonu" },
      { de: "vertraulich", tr: "samimi" },
      { de: "ablehnen", tr: "reddetmek" },
      { de: "die Gepflogenheit", tr: "teamül" },
    ],
    patterns: [
      { de: "Wollen wir uns duzen?", tr: "sen'e geçme teklifi" },
      { de: "Ich bleibe lieber beim Sie.", tr: "kibar ret" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün seviyenin en pratik dersi: 'siz'den 'sen'e geçiş. Yanlış anda teklif etmek de reddetmek de zor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Teamül şu: teklifi kıdemli ya da yaşça büyük olan yapar. Reddetmek ayıp değildir ama nazik bir cümle ister. Önce kelimeler.")] },
      word("İlk", { de: "heikel", tr: "hassas" }),
      word("İkinci", { de: "der Umgangston", tr: "hitap tonu" }),
      word("Üçüncü", { de: "vertraulich", tr: "samimi" }),
      word("Dördüncü", { de: "ablehnen", tr: "reddetmek" }),
      word("Son", { de: "die Gepflogenheit", tr: "teamül" }),
      { say: [tr("Örnek:"), de("Wollen wir uns duzen?"), tr("Tekrar edin:"), de("Wollen wir uns duzen")], expect: repeat("Wollen wir uns duzen") },
      { say: [tr("Sıra sende, kibar ret: 'Ben siz'de kalmayı tercih ederim.'")], expect: produce("Ich bleibe lieber beim Sie", [tr("Edat yönelme hâlinde kaynaşmış; hitap biçimi isimleşmiş:"), de("Ich bleibe lieber beim Sie."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Teklifi kıdemli kişi yapar.'")], expect: produce("Das Du bietet die ranghöhere Person an", [tr("Nesne öne alınmış; ayrılabilen önek sonda:"), de("Das Du bietet die ranghöhere Person an."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu teklifi reddetmek zordur.'")], expect: produce("Dieses Angebot abzulehnen ist schwer", [tr("Mastar öbeği özne olarak başta:"), de("Dieses Angebot abzulehnen ist schwer."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich bleibe lieber beim Sie."), tr("cümlesi doğru mu?")], expect: truefalse("Ich bleibe lieber beim Sie.", true, [tr("Doğru. Edat yönelme hâlinde kaynaşmış ve hitap biçimi isim gibi büyük harfle kullanılmış — kibar bir ret cümlesi.")]) },
      { say: [tr("Son: 'Bu konu hassastır.'")], expect: produce("Dieses Thema ist heikel", [tr("Kısa hüküm cümlesi:"), de("Dieses Thema ist heikel."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir 'sen' teklifiyle karşılaşacaksın.")] },
    ],
    roleplay: {
      scene: "Yeni bir iş ortamındasın ve biri sana 'sen' demeyi teklif ediyor. Teklife karşılık ver, ortamın teamülünü sor, kendi tercihini kibarca söyle ve ilişkiyi rahat bırak.",
      partner: "samimi bir ortam kurmak isteyen, teklifi doğal bulan bir meslektaş",
      opening: "Wir siezen uns hier eigentlich nicht. Wollen wir beim Du bleiben?",
      openingTr: "Burada aslında siz diye konuşmuyoruz. Sen'de kalalım mı?",
      goal: "Teklife karşılık verilmiş, ortamın teamülü öğrenilmiş ve kendi tercih kibarca söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-komplimente-c1",
    icon: "star",
    level: "C1",
    course: "de",
    title: "Loben auf Deutsch",
    titleTr: "İnce iltifat",
    summary: "Övgüyü ölçüsünde ve inandırıcı biçimde vermeyi öğretir.",
    minutes: 12,
    focusId: "Ironie-Untertreibung",
    vocab: [
      { de: "das Kompliment", tr: "iltifat" },
      { de: "die Anerkennung", tr: "takdir" },
      { de: "aufrichtig", tr: "samimi" },
      { de: "übertrieben", tr: "abartılı" },
      { de: "verlegen", tr: "mahcup" },
    ],
    patterns: [
      { de: "Alle Achtung!", tr: "ölçülü ama güçlü övgü" },
      { de: "Ich möchte meine Anerkennung aussprechen.", tr: "resmî takdir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün övgü. İkinci modülde ölçülülüğü görmüştük; burada karşı yönden bakıyoruz — nasıl överiz ki inandırıcı olsun. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural: abartılı övgü Almancada güven kaybettirir. Kısa ve somut bir cümle, üç sıfattan daha güçlüdür. Önce kelimeler.")] },
      word("İlk", { de: "das Kompliment", tr: "iltifat" }),
      word("İkinci", { de: "die Anerkennung", tr: "takdir" }),
      word("Üçüncü", { de: "aufrichtig", tr: "samimi" }),
      word("Dördüncü", { de: "übertrieben", tr: "abartılı" }),
      word("Son", { de: "verlegen", tr: "mahcup" }),
      { say: [tr("Örnek:"), de("Alle Achtung!"), tr("İki kelime ama Almancada güçlü bir övgü. Tekrar edin:"), de("Alle Achtung")], expect: repeat("Alle Achtung") },
      { say: [tr("Sıra sende: 'Takdirimi belirtmek isterim.'")], expect: produce("Ich möchte meine Anerkennung aussprechen", [tr("Ayrılabilen mastar sonda:"), de("Ich möchte meine Anerkennung aussprechen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu samimi bir iltifattı.'")], expect: produce("Das war ein aufrichtiges Kompliment", [tr("Belirtisiz nötr yalın hâlde sıfat -es ekini alır:"), de("Das war ein aufrichtiges Kompliment."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Buna saygı duyuyorum.'")], expect: produce("Davor habe ich Respekt", [tr("Edat zamirle kaynaşır ve öne geçer:"), de("Davor habe ich Respekt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Übertriebene Lob macht verlegen."), tr("cümlesi doğru mu?")], expect: truefalse("Übertriebene Lob macht verlegen.", false, [tr("Belirteçsiz nötr isimden önce sıfat -es ekini alır:"), de("Übertriebenes Lob macht verlegen.")]) },
      { say: [tr("Son: 'Abartılı övgü mahcup eder.'")], expect: produce("Übertriebenes Lob macht verlegen", [tr("Belirteçsiz nötr; sıfat -es ekiyle:"), de("Übertriebenes Lob macht verlegen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada birinin işini takdir edeceksin.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın zor bir işi başardı. Onu takdir et — somut, ölçülü ve abartısız. Karşı taraf küçümserse ısrar et, ne öğrendiğini sor ve konuşmayı sıcak bitir.",
      partner: "övgüyü kabul etmekte zorlanan, hemen küçümseyen bir meslektaş",
      opening: "Ach, das war doch nichts Besonderes. Das hätte jeder hinbekommen, oder?",
      openingTr: "Yok canım, özel bir şey değildi. Herkes başarırdı bunu, değil mi?",
      goal: "Somut ve ölçülü bir takdir verilmiş, küçümsemeye karşılık gelmiş ve konuşma sıcak biçimde bitirilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-peinlichkeiten",
    icon: "feelings",
    level: "C1",
    course: "de",
    title: "Der Fettnapf",
    titleTr: "Gaf yönetimi",
    summary: "Gaf yaptıktan sonra durumu kurtarmayı deyimlerle öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "ins Fettnäpfchen treten", tr: "gaf yapmak" },
      { de: "Schwamm drüber", tr: "unutalım gitsin" },
      { de: "sich herausreden", tr: "kendini kurtarmaya çalışmak" },
      { de: "peinlich", tr: "utandırıcı" },
      { de: "die Panne", tr: "aksilik" },
    ],
    patterns: [
      { de: "Da bin ich ins Fettnäpfchen getreten.", tr: "gaf yaptım" },
      { de: "Schwamm drüber.", tr: "unutalım" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün gaf. Herkes yapar; fark, sonrasında ne yaptığında. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Almancanın iki hazır cümlesi var: biri gafı kabul eder, öteki konuyu kapatır. Aradaki tuzak ise kendini kurtarmaya çalışmak — bu her zaman kötüye gider. Önce kelimeler.")] },
      word("İlk", { de: "ins Fettnäpfchen treten", tr: "gaf yapmak" }),
      word("İkinci", { de: "Schwamm drüber", tr: "unutalım gitsin" }),
      word("Üçüncü", { de: "sich herausreden", tr: "kendini kurtarmaya çalışmak" }),
      word("Dördüncü", { de: "peinlich", tr: "utandırıcı" }),
      word("Son", { de: "die Panne", tr: "aksilik" }),
      { say: [tr("Örnek:"), de("Da bin ich ins Fettnäpfchen getreten."), tr("Tekrar edin:"), de("Da bin ich ins Fettnäpfchen getreten")], expect: repeat("Da bin ich ins Fettnäpfchen getreten") },
      { say: [tr("Sıra sende: 'Unutalım gitsin.'")], expect: produce("Schwamm drüber", [tr("İki kelimelik kalıp; olduğu gibi kullanılır:"), de("Schwamm drüber."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kendimi kurtarmaya çalışmak istemiyorum.'")], expect: produce("Ich will mich nicht herausreden", [tr("Dönüşlü fiil; olumsuzluk mastardan önce:"), de("Ich will mich nicht herausreden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu bana çok utandırıcı geldi.'")], expect: produce("Das war mir sehr peinlich", [tr("Kişi yönelme hâlinde:"), de("Das war mir sehr peinlich."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Ins Fettnäpfchen treten heißt, in ein Gefäß zu treten.")], expect: truefalse("Ins Fettnäpfchen treten heißt, in ein Gefäß zu treten.", false, [tr("Hayır — deyim gaf yapmak, yanlış bir şey söylemek demektir; kabın kendisiyle ilgisi yoktur:"), de("Mit der Frage bin ich ins Fettnäpfchen getreten.")]) },
      { say: [tr("Son: 'Böyle aksilikler olur.'")], expect: produce("Solche Pannen passieren", [tr("Belirteçsiz çoğul özne; fiil çoğul:"), de("Solche Pannen passieren."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada yaptığın bir gafı toparlayacaksın.")] },
    ],
    roleplay: {
      scene: "Bir davette yanlış bir şey söyledin ve ortam buz kesti. Gafı kabul et, kendini kurtarmaya çalışmadan özür dile, konuyu kapat ve sohbeti yeniden başlat.",
      partner: "durumu yumuşatmaya çalışan ama gafı fark etmiş bir ev sahibi",
      opening: "Kein Drama — aber das war eben tatsächlich ein bisschen unglücklich. Wollen wir das einfach abhaken?",
      openingTr: "Facia değil — ama az önceki gerçekten biraz talihsizdi. Bunu geride bıraksak mı?",
      goal: "Gaf kabul edilmiş, savunmaya geçilmeden özür dilenmiş ve sohbet yeniden başlatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-deutscher-humor",
    icon: "media",
    level: "C1",
    course: "de",
    title: "Gibt es deutschen Humor?",
    titleTr: "Mizah sohbeti",
    summary: "Kuru mizahı tanımayı ve mizah üzerine konuşmayı öğretir.",
    minutes: 12,
    focusId: "Ironie-Untertreibung",
    vocab: [
      { de: "trocken", tr: "kuru (mizah)" },
      { de: "das Timing", tr: "zamanlama" },
      { de: "unterschätzt", tr: "hafife alınmış" },
      { de: "die Selbstironie", tr: "kendine gülme" },
      { de: "der Humor", tr: "mizah" },
    ],
    patterns: [
      { de: "Deutscher Humor ist trocken, nicht abwesend.", tr: "kuru ama var" },
      { de: "Timing ist alles.", tr: "zamanlama her şey" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir klişeyi sınayacağız: Almanların mizahı yokmuş. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Cevap şu: var ama KURU. Espri yüksek sesle işaretlenmez, cümlenin içine gizlenir ve zamanlama her şeyi belirler. Önce kelimeler.")] },
      word("İlk", { de: "trocken", tr: "kuru (mizah)" }),
      word("İkinci", { de: "das Timing", tr: "zamanlama" }),
      word("Üçüncü", { de: "unterschätzt", tr: "hafife alınmış" }),
      word("Dördüncü", { de: "die Selbstironie", tr: "kendine gülme" }),
      word("Son", { de: "der Humor", tr: "mizah" }),
      { say: [tr("Örnek:"), de("Deutscher Humor ist trocken, nicht abwesend."), tr("Tekrar edin:"), de("Deutscher Humor ist trocken, nicht abwesend")], expect: repeat("Deutscher Humor ist trocken, nicht abwesend") },
      { say: [tr("Sıra sende: 'Zamanlama her şeydir.'")], expect: produce("Timing ist alles", [tr("Kısa ve kalıplaşmış cümle:"), de("Timing ist alles."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kendine gülebilmek bir olgunluk işaretidir.'")], expect: produce("Selbstironie ist ein Zeichen von Reife", [tr("Belirteçsiz özne; edat yönelme hâlinde:"), de("Selbstironie ist ein Zeichen von Reife."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kuru espri hemen anlaşılmaz.'")], expect: produce("Trockener Humor erschließt sich nicht sofort", [tr("Belirteçsiz eril; sıfat -er ekini alır; dönüşlü fiil:"), de("Trockener Humor erschließt sich nicht sofort."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der deutsche Humor wird unterschätzt."), tr("cümlesi doğru mu?")], expect: truefalse("Der deutsche Humor wird unterschätzt.", true, [tr("Doğru. Şimdiki zaman edilgeni kurulmuş, belirtili eril özne sıfatı -e ekiyle almış ve ortaç sonda duruyor.")]) },
      { say: [tr("Son: 'Alman mizahı hafife alınıyor.'")], expect: produce("Der deutsche Humor wird unterschätzt", [tr("Edilgen; ortaç sonda:"), de("Der deutsche Humor wird unterschätzt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada mizah anlayışlarını karşılaştıracaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla iki kültürün mizahını karşılaştırıyorsunuz: neye gülünüyor, neye gülünmüyor, kuru mizah nasıl işliyor ve bir espri neden çeviride ölüyor. Kendi dilinden bir örnek ver.",
      partner: "kendi mizahını savunan, örnek isteyen bir arkadaş",
      opening: "Gib mir mal ein Beispiel: Worüber lacht man bei euch, worüber hier nie?",
      openingTr: "Bana bir örnek ver: Sizde neye gülünür, burada asla neye gülünmez?",
      goal: "İki kültürün mizahı örneklerle karşılaştırılmış ve bir esprinin neden çeviriye gelmediği açıklanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-kulturschock-fein",
    icon: "culture",
    level: "C1",
    course: "de",
    title: "Die feinen Unterschiede",
    titleTr: "İnce kültür farkları",
    summary: "Kültürel farkı yargılamadan adlandırmayı öğretir.",
    minutes: 12,
    focusId: "Wortschatz-Nuancen",
    vocab: [
      { de: "die Pünktlichkeit", tr: "dakiklik" },
      { de: "sparsam", tr: "tutumlu, az" },
      { de: "die Direktheit", tr: "doğrudanlık" },
      { de: "befremdlich", tr: "yadırgatıcı" },
      { de: "gewöhnungsbedürftig", tr: "alışmak gerektiren" },
    ],
    patterns: [
      { de: "Kritik ist direkt, Lob ist sparsam.", tr: "iki ölçü" },
      { de: "Anders, nicht falsch.", tr: "yargısız adlandırma" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve en olgunu: farkı yargılamadan adlandırmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki gözlem yeter: dakiklik burada bir dildir ve eleştiri doğrudan, övgü tutumludur. İkisini bilen biri kırılmaz, sadece hazırlıklı olur. Önce kelimeler.")] },
      word("İlk", { de: "die Pünktlichkeit", tr: "dakiklik" }),
      word("İkinci", { de: "sparsam", tr: "tutumlu, az" }),
      word("Üçüncü", { de: "die Direktheit", tr: "doğrudanlık" }),
      word("Dördüncü", { de: "befremdlich", tr: "yadırgatıcı" }),
      word("Son", { de: "gewöhnungsbedürftig", tr: "alışmak gerektiren" }),
      { say: [tr("Örnek:"), de("Pünktlichkeit ist hier eine Sprache."), tr("Tekrar edin:"), de("Pünktlichkeit ist hier eine Sprache")], expect: repeat("Pünktlichkeit ist hier eine Sprache") },
      { say: [tr("Sıra sende: 'Eleştiri doğrudan, övgü tutumludur.'")], expect: produce("Kritik ist direkt, Lob ist sparsam", [tr("İki kısa hüküm cümlesi:"), de("Kritik ist direkt, Lob ist sparsam."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Başta bu bana yadırgatıcı geldi.'")], expect: produce("Anfangs kam mir das befremdlich vor", [tr("Zarf başta; kişi yönelme hâlinde; önek sonda:"), de("Anfangs kam mir das befremdlich vor."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Alışmak gerekiyor ama mümkün.'")], expect: produce("Es ist gewöhnungsbedürftig, aber machbar", [tr("İki sıfat; ikincisi zıtlık bağlacıyla:"), de("Es ist gewöhnungsbedürftig, aber machbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Anfangs das kam mir befremdlich vor."), tr("cümlesi doğru mu?")], expect: truefalse("Anfangs das kam mir befremdlich vor.", false, [tr("Cümle bir zarfla başlayınca çekimli fiil ikinci sıraya gelir:"), de("Anfangs kam mir das befremdlich vor.")]) },
      { say: [tr("Son: 'Farklı, yanlış değil.'")], expect: produce("Anders, nicht falsch", [tr("İki kelimelik yargısız bir formül:"), de("Anders, nicht falsch."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada yeni gelen birine kültürel farkları anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Yeni gelen birine burada neyin farklı olduğunu anlatıyorsun: dakiklik, doğrudan eleştiri, tutumlu övgü. Yargılamadan adlandır, kendi başlangıcını anlat ve ona somut bir tavsiye ver.",
      partner: "yeni gelmiş, bazı davranışları kabalık sanan biri",
      opening: "Sind die hier immer so schroff? Gestern hat mich jemand vor allen korrigiert — war das jetzt böse gemeint?",
      openingTr: "Buradakiler hep böyle sert mi? Dün biri beni herkesin önünde düzeltti — kötü niyetli miydi bu?",
      goal: "Kültürel fark yargılamadan adlandırılmış, kendi deneyim anlatılmış ve yeni gelene somut bir tavsiye verilmiş olur.",
      minTurns: 8,
    },
  },
];
