import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * C1 · Modül 2 — Kip parçacıkları (011–020).
 *
 * Bu modül dilbilgisi değil TON öğretiyor ve bu yüzden en zorlarından biri.
 * `doch`, `ja`, `mal`, `eben`, `wohl`, `schon`, `bloß` çevrilmez — cümleye
 * anlam eklemezler, konuşanın TAVRINI eklerler. "Komm mit" bir çağrıdır,
 * "Komm doch mit" bir davettir; ikisi de doğru Almancadır ve ikisi ayrı şey
 * söyler.
 *
 * Türkçe konuşan için iyi haber: Türkçede bu iş "hele, bir, işte, canım, ya"
 * ile yapılır, yani kavram tanıdık. Kötü haber: karşılıklar birebir değil ve
 * parçacıkların SIRASI sabit — "ja wohl" olur, "wohl ja" olmaz; "doch mal"
 * olur, "mal doch" olmaz. Modülün doğru/yanlış maddeleri bilerek bu sıraya
 * ve parçacığın anlamına ayrıldı, dilbilgisel hataya değil.
 *
 * İki ders parçacık dışında: 017 Alman ölçülülüğü (az söyleyip çok kastetmek)
 * ve 019 telefonda dilek kipi. İkisi de aynı ailenin üyesi — söylenenle
 * kastedilenin ayrıldığı yer.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deC1B02: Lesson[] = [
  {
    id: "de-c1-doch",
    icon: "feelings",
    level: "C1",
    course: "de",
    title: "Komm doch mit!",
    titleTr: "doch'un renkleri",
    summary: "doch parçacığının davet, pekiştirme ve karşı çıkma işlevlerini öğretir.",
    minutes: 12,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "die Aufforderung", tr: "çağrı, rica" },
      { de: "der Widerspruch", tr: "karşı çıkma" },
      { de: "bekräftigen", tr: "pekiştirmek" },
      { de: "die Ermunterung", tr: "yüreklendirme" },
      { de: "selbstverständlich", tr: "elbette, apaçık" },
    ],
    patterns: [
      { de: "Komm doch mit!", tr: "çağrıyı davete çevirir" },
      { de: "Doch!", tr: "olumsuz soruya olumlu cevap" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül ve konusu dilbilgisi değil TON. Bu küçük kelimeler cümleye anlam eklemez, konuşanın tavrını ekler. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İlk parçacık en çok kullanılanı ve üç ayrı iş yapıyor: çağrıyı yumuşatıyor, bilineni pekiştiriyor ve olumsuz bir soruya olumlu cevap veriyor. Önce kelimeler.")] },
      word("İlk", { de: "die Aufforderung", tr: "çağrı, rica" }),
      word("İkinci", { de: "der Widerspruch", tr: "karşı çıkma" }),
      word("Üçüncü", { de: "bekräftigen", tr: "pekiştirmek" }),
      word("Dördüncü", { de: "die Ermunterung", tr: "yüreklendirme" }),
      word("Son", { de: "selbstverständlich", tr: "elbette, apaçık" }),
      { say: [tr("Örnek:"), de("Komm doch mit, es wird bestimmt nett."), tr("'Komm mit' bir çağrı, 'komm doch mit' bir davet. Tekrar edin:"), de("Komm doch mit, es wird bestimmt nett")], expect: repeat("Komm doch mit, es wird bestimmt nett") },
      { say: [tr("Sıra sende, pekiştirme işleviyle: 'Bu zaten belli.'")], expect: produce("Das ist doch klar", [tr("Parçacık fiilden sonra, sıfattan önce:"), de("Das ist doch klar."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir dene hadi.'")], expect: produce("Probier es doch einfach mal", [tr("İki parçacık üst üste; sıra sabittir:"), de("Probier es doch einfach mal."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunu bana daha önce söyleyebilirdin.'")], expect: produce("Das hättest du mir doch früher sagen können", [tr("Parçacık serzenişi taşır; iki mastar sonda:"), de("Das hättest du mir doch früher sagen können."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Biri sana"), de("Willst du nicht mitkommen?"), tr("diye soruyor ve sen gelmek İSTİYORSUN. Şu cevap doğru mu:"), de("Nein, ich will mitkommen.")], expect: truefalse("Nein, ich will mitkommen.", false, [tr("Olumsuz bir soruya olumlu cevap bu parçacıkla verilir; 'nein' burada gelmek istemediğin anlamına gelirdi:"), de("Doch, ich will mitkommen.")]) },
      { say: [tr("Son: 'Evet, istiyorum!' — olumsuz soruya cevap olarak.")], expect: produce("Doch, ich will", [tr("Tek başına duran parçacık; virgülden sonra cümle:"), de("Doch, ich will!"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada birini ikna edeceksin — ve iki kez itiraz edeceksin.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın etkinliğe gelmek istemiyor. Onu davet et, gerekçelerine karşı çık, olumsuz sorularına olumlu cevap ver ve bir karara bağlayın.",
      partner: "isteksiz, her öneriye bahane bulan ama ikna edilebilir bir arkadaş",
      opening: "Du willst mich doch nicht wirklich zu diesem Ding überreden, oder?",
      openingTr: "Beni gerçekten bu şeye ikna etmeye çalışmıyorsun, değil mi?",
      goal: "Davet edilmiş, bahanelere karşı çıkılmış ve arkadaşın gelip gelmeyeceği karara bağlanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-ja-mal",
    icon: "greet",
    level: "C1",
    course: "de",
    title: "Das ist ja spannend!",
    titleTr: "ja ve mal",
    summary: "Şaşkınlık bildiren ja ile ricayı hafifleten mal parçacığını öğretir.",
    minutes: 12,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "die Überraschung", tr: "şaşkınlık" },
      { de: "auffordern", tr: "rica etmek, davet etmek" },
      { de: "der Nachdruck", tr: "vurgu" },
      { de: "locker", tr: "rahat, gevşek" },
      { de: "erstaunt", tr: "şaşkın" },
    ],
    patterns: [
      { de: "Das ist ja …!", tr: "şaşkınlık ya da ortak bilgi" },
      { de: "Schau mal / Warte mal", tr: "ricayı hafifletir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün iki parçacık: biri şaşırtıyor, öteki yumuşatıyor. İkisi de küçük ama ikisi de cümlenin sesini değiştiriyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Birincisi ya şaşkınlık ya da 'bunu ikimiz de biliyoruz' anlamı taşır. İkincisi ricayı emirlikten çıkarır: 'bak' değil 'bir bak'. Önce kelimeler.")] },
      word("İlk", { de: "die Überraschung", tr: "şaşkınlık" }),
      word("İkinci", { de: "auffordern", tr: "rica etmek, davet etmek" }),
      word("Üçüncü", { de: "der Nachdruck", tr: "vurgu" }),
      word("Dördüncü", { de: "locker", tr: "rahat, gevşek" }),
      word("Son", { de: "erstaunt", tr: "şaşkın" }),
      { say: [tr("Örnek:"), de("Das ist ja spannend!"), tr("Tekrar edin:"), de("Das ist ja spannend")], expect: repeat("Das ist ja spannend") },
      { say: [tr("Sıra sende: 'Bir bak hele.'")], expect: produce("Schau mal", [tr("Emir kipi ve hafifletici parçacık; iki kelime yeter:"), de("Schau mal."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kısa bir dur.'")], expect: produce("Warte mal kurz", [tr("Parçacık fiilden hemen sonra:"), de("Warte mal kurz."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha, ortak bilgi anlamıyla: 'Demek sen de buradasın.'")], expect: produce("Du bist ja auch hier", [tr("Parçacık fiilden sonra, zarftan önce:"), de("Du bist ja auch hier."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Schau mal doch."), tr("cümlesi doğru mu?")], expect: truefalse("Schau mal doch.", false, [tr("İki parçacığın sırası sabittir ve tersine çevrilemez:"), de("Schau doch mal.")]) },
      { say: [tr("Son: 'Bunu bana bir anlatsana.'")], expect: produce("Erzähl mir das mal", [tr("Nesne sırası önce kişi, sonra şey; parçacık en sonda:"), de("Erzähl mir das mal."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada uzun süredir görmediğin birine rastlayacaksın.")] },
    ],
    roleplay: {
      scene: "Sokakta uzun süredir görmediğin birine rastladın. Şaşkınlığını göster, ondan bir şey anlatmasını rica et, kendi haberini ver ve tekrar görüşmek için bir şey kararlaştır.",
      partner: "seni görünce çok sevinen, anlatacak çok şeyi olan eski bir tanıdık",
      opening: "Das gibt's ja nicht — bist du das wirklich? Wie lange ist das jetzt her?",
      openingTr: "Yok artık — sen misin gerçekten? Ne kadar oldu?",
      goal: "Karşılıklı haberler alınmış ve tekrar görüşmek için somut bir şey kararlaştırılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-eben-halt",
    icon: "question",
    level: "C1",
    course: "de",
    title: "So ist es eben",
    titleTr: "Kabullenme tonu",
    summary: "Değiştirilemeyeni kabullenme tonunu eben ve halt ile kurmayı öğretir.",
    minutes: 12,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "sich abfinden", tr: "kabullenmek" },
      { de: "die Gegebenheit", tr: "verili durum" },
      { de: "resigniert", tr: "boyun eğmiş" },
      { de: "unabänderlich", tr: "değiştirilemez" },
      { de: "die Einsicht", tr: "kavrayış, kabul" },
    ],
    patterns: [
      { de: "Das ist eben so.", tr: "kabullenme: böyle işte" },
      { de: "Dann halt nicht.", tr: "vazgeçme tonu" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü ton çok Alman: değiştiremediğin şeyi omuz silkerek kabul etmek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki parçacık aynı işi görüyor — biri kuzeyde, öteki güneyde daha sık. İkisi de 'öyle işte' demenin yolu. Önce kelimeler.")] },
      word("İlk", { de: "sich abfinden", tr: "kabullenmek" }),
      word("İkinci", { de: "die Gegebenheit", tr: "verili durum" }),
      word("Üçüncü", { de: "resigniert", tr: "boyun eğmiş" }),
      word("Dördüncü", { de: "unabänderlich", tr: "değiştirilemez" }),
      word("Son", { de: "die Einsicht", tr: "kavrayış, kabul" }),
      { say: [tr("Örnek:"), de("Das ist eben so."), tr("Tekrar edin:"), de("Das ist eben so")], expect: repeat("Das ist eben so") },
      { say: [tr("Sıra sende: 'O zaman olmasın.'")], expect: produce("Dann halt nicht", [tr("Üç kelimelik tam bir cümle; parçacık ortada:"), de("Dann halt nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bununla kabullenmek zorundayız.'")], expect: produce("Damit müssen wir uns abfinden", [tr("Edat zamirle kaynaşır; dönüşlü fiil mastar hâlinde sonda:"), de("Damit müssen wir uns abfinden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu böyle işte, değiştiremezsin.'")], expect: produce("So ist es eben, ändern kannst du es nicht", [tr("İkinci cümlede mastar öne alınmış:"), de("So ist es eben, ändern kannst du es nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist eben so."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist eben so.", true, [tr("Doğru. Parçacık fiilden sonra duruyor ve cümleye 'değiştirilemez, kabul et' tonunu veriyor.")]) },
      { say: [tr("Son: 'Eh, böyle şeyler olur.'")], expect: produce("Na ja, so etwas kommt vor", [tr("Kalıplaşmış giriş, sonra düz cümle; ayrılabilen önek sonda:"), de("Na ja, so etwas kommt vor."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada değiştiremeyeceğin bir aksiliği konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Değiştiremeyeceğin bir aksilik oldu (iptal, gecikme, kaçırılan fırsat). Bir arkadaşınla konuş: ne olduğunu anlat, kızgınlığını söyle, sonra kabullenme tonuna geç ve bundan sonra ne yapacağını kararlaştır.",
      partner: "önce çözüm üretmeye çalışan, sonra seninle birlikte kabullenen bir arkadaş",
      opening: "Und da kann man wirklich gar nichts mehr machen? Also gar nichts?",
      openingTr: "Ve gerçekten yapılabilecek hiçbir şey yok mu? Hiç mi?",
      goal: "Aksilik anlatılmış, kızgınlık söylenmiş, kabullenme tonuna geçilmiş ve bundan sonrası için bir adım kararlaşmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-wohl",
    icon: "idea",
    level: "C1",
    course: "de",
    title: "Das wird wohl stimmen",
    titleTr: "Tahmin tonu",
    summary: "Emin olmadan söylemeyi wohl parçacığıyla kurmayı öğretir.",
    minutes: 12,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "die Mutmaßung", tr: "tahmin, varsayım" },
      { de: "annehmen", tr: "varsaymak" },
      { de: "der Anhaltspunkt", tr: "dayanak, ipucu" },
      { de: "zweifellos", tr: "kuşkusuz" },
      { de: "kaum", tr: "neredeyse hiç" },
    ],
    patterns: [
      { de: "Das wird wohl …", tr: "temkinli tahmin" },
      { de: "Er ist wohl schon weg.", tr: "parçacık sırası: wohl önce" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün emin olmadan konuşacağız. B2'de bunu kip fiilleriyle yapmıştın; parçacık aynı işi daha hafif yapıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dikkat edeceğin şey sıra: bu parçacık başka bir zarfla yan yana gelirse ÖNCE gelir. Sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "die Mutmaßung", tr: "tahmin, varsayım" }),
      word("İkinci", { de: "annehmen", tr: "varsaymak" }),
      word("Üçüncü", { de: "der Anhaltspunkt", tr: "dayanak, ipucu" }),
      word("Dördüncü", { de: "zweifellos", tr: "kuşkusuz" }),
      word("Son", { de: "kaum", tr: "neredeyse hiç" }),
      { say: [tr("Örnek:"), de("Das wird wohl stimmen."), tr("Tekrar edin:"), de("Das wird wohl stimmen")], expect: repeat("Das wird wohl stimmen") },
      { say: [tr("Sıra sende: 'Herhâlde çoktan gitti.'")], expect: produce("Er ist wohl schon weg", [tr("Parçacık zarftan önce gelir:"), de("Er ist wohl schon weg."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bunu neredeyse hayal edemiyorum.'")], expect: produce("Das kann ich mir kaum vorstellen", [tr("Dönüşlü zamir yönelme hâlinde; mastar sonda:"), de("Das kann ich mir kaum vorstellen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunu varsayıyorum ama kesin değil.'")], expect: produce("Ich nehme das an, sicher ist es aber nicht", [tr("Ayrılabilen önek sonda; ikinci cümlede sıfat öne alınmış:"), de("Ich nehme das an, sicher ist es aber nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Er ist schon wohl weg."), tr("cümlesi doğru mu?")], expect: truefalse("Er ist schon wohl weg.", false, [tr("Parçacık zarfın önünde durur; sıra tersine çevrilemez:"), de("Er ist wohl schon weg.")]) },
      { say: [tr("Son bir soru: 'Bir dayanağımız var mı?'")], expect: produce("Haben wir einen Anhaltspunkt", [tr("Fiil başta soru; belirtisiz eril belirtme hâlinde:"), de("Haben wir einen Anhaltspunkt?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada belirsiz bir durum hakkında tahmin yürüteceksin.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşınla açıklanmamış bir kararı konuşuyorsunuz. Tahminlerini emin olmadığını belli ederek söyle, dayanağın olan ve olmayan şeyleri ayır ve ne yapacağınıza karar verin.",
      partner: "kesin konuşmayı seven, tahminleri olgu gibi sunan bir meslektaş",
      opening: "Die haben das doch längst entschieden. Oder hast du irgendeinen Anhaltspunkt dagegen?",
      openingTr: "Bunu çoktan karara bağlamışlardır. Yoksa aksine dair bir dayanağın mı var?",
      goal: "Dayanağı olan ile olmayan ayrılmış, tahminler emin olmadan söylenmiş ve ne yapılacağı kararlaşmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-schon",
    icon: "sun",
    level: "C1",
    course: "de",
    title: "Das wird schon!",
    titleTr: "Teselli tonu",
    summary: "Yatıştırma ve teselli tonunu schon parçacığıyla kurmayı öğretir.",
    minutes: 12,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "die Zuversicht", tr: "iyimserlik, güven" },
      { de: "trösten", tr: "teselli etmek" },
      { de: "die Gelassenheit", tr: "sükûnet" },
      { de: "aufmuntern", tr: "moral vermek" },
      { de: "zuversichtlich", tr: "umutlu" },
    ],
    patterns: [
      { de: "Das wird schon!", tr: "her şey yoluna girer" },
      { de: "Schon gut.", tr: "boş ver, tamam" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün birini yatıştıracağız. Almancanın bunun için iki kelimelik hazır bir cümlesi var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Aynı parçacık 'zaten' anlamına da gelir; hangisi olduğunu cümlenin işi belirler. Bu ikili kullanım C1'de karışıyor. Önce kelimeler.")] },
      word("İlk", { de: "die Zuversicht", tr: "iyimserlik" }),
      word("İkinci", { de: "trösten", tr: "teselli etmek" }),
      word("Üçüncü", { de: "die Gelassenheit", tr: "sükûnet" }),
      word("Dördüncü", { de: "aufmuntern", tr: "moral vermek" }),
      word("Son", { de: "zuversichtlich", tr: "umutlu" }),
      { say: [tr("Örnek:"), de("Das wird schon!"), tr("Tekrar edin:"), de("Das wird schon")], expect: repeat("Das wird schon") },
      { say: [tr("Sıra sende: 'Tamam, boş ver.'")], expect: produce("Schon gut", [tr("İki kelimelik tam bir kabul cümlesi:"), de("Schon gut."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi ikinci anlamıyla: 'Geç oldu ama devam edelim.'")], expect: produce("Es ist schon spät, aber machen wir weiter", [tr("Burada parçacık 'zaten' anlamında; ikinci cümlede fiil başta:"), de("Es ist schon spät, aber machen wir weiter."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Onu biraz teselli etmek istedim.'")], expect: produce("Ich wollte ihn ein wenig trösten", [tr("Kip fiili çekimli, mastar sonda:"), de("Ich wollte ihn ein wenig trösten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich wollte ihn ein wenig getröstet."), tr("cümlesi doğru mu?")], expect: truefalse("Ich wollte ihn ein wenig getröstet.", false, [tr("Kip fiilinden sonra ortaç değil mastar gelir:"), de("Ich wollte ihn ein wenig trösten.")]) },
      { say: [tr("Son: 'Bu konuda umutluyum.'")], expect: produce("Da bin ich zuversichtlich", [tr("Yer zarfı başta, fiil ikinci sırada:"), de("Da bin ich zuversichtlich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada moralı bozuk birini yatıştıracaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşın kötü bir haber aldı ve morali bozuk. Önce dinle, sonra yatıştır, abartmadan umut ver ve somut bir şey teklif et.",
      partner: "üzgün, kolay teselli olmayan ama konuşmak isteyen bir arkadaş",
      opening: "Sag jetzt bitte nicht, dass das schon wieder wird. Ich habe das so oft gehört — was soll daran gut werden?",
      openingTr: "Lütfen şimdi 'her şey yoluna girer' deme. Bunu çok duydum — bunda ne düzelecek ki?",
      goal: "Arkadaş dinlenmiş, boş teselliye kaçmadan yatıştırılmış ve somut bir yardım teklif edilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-partikel-streit",
    icon: "clock",
    level: "C1",
    course: "de",
    title: "Nun mach doch endlich!",
    titleTr: "Sabırsızlık tonları",
    summary: "Sabırsızlık ve uyarı tonunu parçacıklarla dozunda vermeyi öğretir.",
    minutes: 12,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "die Ungeduld", tr: "sabırsızlık" },
      { de: "drängen", tr: "sıkıştırmak" },
      { de: "die Zurechtweisung", tr: "azarlama" },
      { de: "unterlassen", tr: "yapmaktan kaçınmak" },
      { de: "endlich", tr: "nihayet" },
    ],
    patterns: [
      { de: "Nun mach doch endlich!", tr: "sabırsızlık" },
      { de: "Mach das bloß nicht!", tr: "sert uyarı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sinirlenmeyi öğreneceğiz — ama dozunda. Parçacıklar burada bir ölçek gibi çalışıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Aynı emir, üç ayrı sertlikte söylenebilir. Yanlış parçacık seni ya fazla sert ya fazla yumuşak gösterir; C1'de doz da ölçülüyor. Önce kelimeler.")] },
      word("İlk", { de: "die Ungeduld", tr: "sabırsızlık" }),
      word("İkinci", { de: "drängen", tr: "sıkıştırmak" }),
      word("Üçüncü", { de: "die Zurechtweisung", tr: "azarlama" }),
      word("Dördüncü", { de: "unterlassen", tr: "yapmaktan kaçınmak" }),
      word("Son", { de: "endlich", tr: "nihayet" }),
      { say: [tr("Örnek:"), de("Nun mach doch endlich!"), tr("Tekrar edin:"), de("Nun mach doch endlich")], expect: repeat("Nun mach doch endlich") },
      { say: [tr("Sıra sende, en sert biçim: 'Sakın yapma!'")], expect: produce("Mach das bloß nicht", [tr("Bu parçacık uyarıyı tehdide yaklaştırır:"), de("Mach das bloß nicht!"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi tersi, yumuşak: 'Beni sıkıştırma lütfen.'")], expect: produce("Dräng mich bitte nicht", [tr("Emir kipi; nazik sözcük ortada:"), de("Dräng mich bitte nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Nihayet bir karar verelim.'")], expect: produce("Treffen wir endlich eine Entscheidung", [tr("Rica biçiminde fiil başta; işlev fiili öbeği sonda:"), de("Treffen wir endlich eine Entscheidung."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Mach das bloß nicht."), tr("cümlesi doğru mu?")], expect: truefalse("Mach das bloß nicht.", true, [tr("Doğru. Emir kipinden sonra parçacık ve olumsuzluk bu sırayla gelir; cümle sert bir uyarıdır.")]) },
      { say: [tr("Son: 'Sabırsızlığını anlıyorum.'")], expect: produce("Ich verstehe deine Ungeduld", [tr("Nesne belirtme hâlinde:"), de("Ich verstehe deine Ungeduld."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada gecikmiş bir işi konuşacaksın — sabrını kaybetmeden.")] },
    ],
    roleplay: {
      scene: "Bir işi bekliyorsun ve karşı taraf sürekli erteliyor. Sabırsızlığını dozunda göster, bir uyarı yap, sıkıştırdığını kabul et ve bir son tarihte anlaşın.",
      partner: "sürekli erteleyen, mazereti hazır bir muhatap",
      opening: "Ich weiß, ich weiß — ich bin dran. Muss das denn heute noch sein?",
      openingTr: "Biliyorum, biliyorum — üzerinde çalışıyorum. Bugün olması şart mı?",
      goal: "Sabırsızlık dozunda gösterilmiş, bir uyarı yapılmış ve bağlayıcı bir son tarihte anlaşılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-untertreibung",
    icon: "culture",
    level: "C1",
    course: "de",
    title: "Nicht schlecht!",
    titleTr: "Alman ölçülülüğü",
    summary: "Az söyleyip çok kastetme kültürünü anlamayı ve kullanmayı öğretir.",
    minutes: 12,
    focusId: "Ironie-Untertreibung",
    vocab: [
      { de: "die Untertreibung", tr: "az söyleyip çok kastetme" },
      { de: "das Lob", tr: "övgü" },
      { de: "zurückhaltend", tr: "ölçülü, çekingen" },
      { de: "anerkennend", tr: "takdir edici" },
      { de: "übertreiben", tr: "abartmak" },
    ],
    patterns: [
      { de: "Nicht schlecht!", tr: "aslında: çok iyi" },
      { de: "Da ist noch Luft nach oben.", tr: "aslında: yetersiz" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir kültür dersi. Almancada övgü ölçülüdür ve bunu bilmeyen bir Türk konuşan sürekli yanlış anlar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şu:"), de("Nicht schlecht"), tr("'fena değil' değil, 'çok iyi' demektir. Tersi de geçerli — 'yukarıda hava var' cümlesi kibar bir 'yetersiz'dir. Önce kelimeler.")] },
      word("İlk", { de: "die Untertreibung", tr: "az söyleyip çok kastetme" }),
      word("İkinci", { de: "das Lob", tr: "övgü" }),
      word("Üçüncü", { de: "zurückhaltend", tr: "ölçülü" }),
      word("Dördüncü", { de: "anerkennend", tr: "takdir edici" }),
      word("Son", { de: "übertreiben", tr: "abartmak" }),
      { say: [tr("Örnek:"), de("Nicht schlecht!"), tr("Tekrar edin:"), de("Nicht schlecht")], expect: repeat("Nicht schlecht") },
      { say: [tr("Sıra sende: 'Yapılabilir.' — yani aslında 'iyi olmuş'.")], expect: produce("Kann man machen", [tr("Öznesiz kalıp; üç kelime:"), de("Kann man machen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi kibar eleştiri: 'Daha iyi olabilirdi.'")], expect: produce("Da ist noch Luft nach oben", [tr("Kalıplaşmış ifade; yer zarfı başta:"), de("Da ist noch Luft nach oben."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Almanlar övgüde ölçülüdür.'")], expect: produce("Beim Lob sind die Deutschen zurückhaltend", [tr("Tümleç başta, fiil ikinci sırada:"), de("Beim Lob sind die Deutschen zurückhaltend."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Nicht schlecht heißt mittelmäßig.")], expect: truefalse("Nicht schlecht heißt mittelmäßig.", false, [tr("Tam tersi: bu bir övgüdür ve 'çok iyi' demenin ölçülü hâlidir. Vasat demek istenseydi"), de("Da ist noch Luft nach oben"), tr("gibi bir ifade kullanılırdı.")]) },
      { say: [tr("Son: 'Abartmak istemem ama etkileyiciydi.'")], expect: produce("Ich will nicht übertreiben, aber es war beeindruckend", [tr("İki cümle; ikincisi zıtlık bağlacıyla:"), de("Ich will nicht übertreiben, aber es war beeindruckend."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir işi değerlendireceksin — Alman ölçüsüyle.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşının işini değerlendiriyorsun. Ölçülü övgü ver, eksiği kibar biçimde söyle, karşı taraf 'beğenmedin mi' diye sorarsa açıkla ve net bir sonuç bildir.",
      partner: "abartılı övgüye alışkın, ölçülü dili soğuk bulan bir meslektaş",
      opening: "„Nicht schlecht“ — heißt das jetzt gut oder schlecht? Bei euch weiß man das nie.",
      openingTr: "„Fena değil“ — bu şimdi iyi mi kötü mü? Sizde bu hiç belli olmuyor.",
      goal: "Ölçülü övgü ve kibar eleştiri ayrı ayrı verilmiş, yanlış anlama giderilmiş ve net bir sonuç söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-smalltalk-c1",
    icon: "cafe",
    level: "C1",
    course: "de",
    title: "Small Talk mit Feinschliff",
    titleTr: "İncelikli sohbet",
    summary: "Sohbeti parçacıklar ve hazır kalıplarla akıcı tutmayı öğretir.",
    minutes: 12,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "die Plauderei", tr: "sohbet" },
      { de: "unverfänglich", tr: "masum, tehlikesiz" },
      { de: "anknüpfen", tr: "bağlanmak, devam etmek" },
      { de: "die Floskel", tr: "klişe söz" },
      { de: "auflockern", tr: "yumuşatmak" },
    ],
    patterns: [
      { de: "Sagen Sie mal, …", tr: "sohbeti açar" },
      { de: "Wie man's nimmt.", tr: "bağlayıcı olmayan cevap" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sohbetin ince ayarı. B2'de asansör sohbeti yapmıştın; C1'de mesele sohbeti SÜRDÜRMEK. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki araç var: soruyu yumuşatan parçacık ve bağlayıcı olmayan hazır cevaplar. İkincisi seni köşeye sıkışmaktan kurtarır. Önce kelimeler.")] },
      word("İlk", { de: "die Plauderei", tr: "sohbet" }),
      word("İkinci", { de: "unverfänglich", tr: "masum, tehlikesiz" }),
      word("Üçüncü", { de: "anknüpfen", tr: "bağlanmak" }),
      word("Dördüncü", { de: "die Floskel", tr: "klişe söz" }),
      word("Son", { de: "auflockern", tr: "yumuşatmak" }),
      { say: [tr("Örnek:"), de("Sagen Sie mal, wie lange sind Sie schon hier?"), tr("Tekrar edin:"), de("Sagen Sie mal, wie lange sind Sie schon hier")], expect: repeat("Sagen Sie mal, wie lange sind Sie schon hier") },
      { say: [tr("Sıra sende: 'Vay canına!'")], expect: produce("Ist ja ein Ding", [tr("Öznesiz kalıp; parçacık şaşkınlığı taşır:"), de("Ist ja ein Ding!"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi bağlayıcı olmayan cevap: 'Nasıl bakarsan.'")], expect: produce("Wie man's nimmt", [tr("Kısaltılmış kalıp; günlük dilde böyle söylenir:"), de("Wie man's nimmt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Buna bağlanabilirim.'")], expect: produce("Daran kann ich anknüpfen", [tr("Edat zamirle kaynaşır; ayrılabilen mastar sonda:"), de("Daran kann ich anknüpfen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Sagen Sie mal, wie lange Sie schon hier sind?"), tr("cümlesi doğru mu?")], expect: truefalse("Sagen Sie mal, wie lange Sie schon hier sind?", false, [tr("Buradaki soru dolaylı değil doğrudan sorulmuş; o yüzden fiil ikinci sırada durur:"), de("Sagen Sie mal, wie lange sind Sie schon hier?")]) },
      { say: [tr("Son: 'Havayı biraz yumuşatmak istedim.'")], expect: produce("Ich wollte die Stimmung etwas auflockern", [tr("Kip fiili çekimli; ayrılabilen mastar sonda:"), de("Ich wollte die Stimmung etwas auflockern."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir davette tanımadığın biriyle sohbet edeceksin.")] },
    ],
    roleplay: {
      scene: "Bir iş davetinde tanımadığın biriyle ayaküstü sohbet ediyorsun. Sohbeti aç, ortak bir konu bul, kişisel olmayan bir soruyla derinleştir ve kibarca ayrıl.",
      partner: "kibar ama ilk başta suskun, açıldıkça konuşan bir davetli",
      opening: "Man kennt hier kaum jemanden, oder? Sind Sie öfter bei solchen Sachen?",
      openingTr: "Burada neredeyse kimse kimseyi tanımıyor, değil mi? Siz böyle şeylere sık gelir misiniz?",
      goal: "Sohbet açılmış, ortak bir konu bulunmuş ve konuşma kibar bir vedayla kapatılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-telefonton",
    icon: "phone",
    level: "C1",
    course: "de",
    title: "Der Ton am Telefon",
    titleTr: "Telefonda ton",
    summary: "Telefonda en kibar rica biçimlerini kurmayı öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II-Diplomatie",
    vocab: [
      { de: "durchstellen", tr: "bağlamak (telefonda)" },
      { de: "der Rückruf", tr: "geri arama" },
      { de: "die Leitung", tr: "hat" },
      { de: "hinterlassen", tr: "bırakmak (mesaj)" },
      { de: "umgehend", tr: "derhâl" },
    ],
    patterns: [
      { de: "Dürfte ich Sie kurz stören?", tr: "en kibar giriş" },
      { de: "Wären Sie so freundlich, … zu …", tr: "en kibar rica" },
    ],
    lecture: [
      { say: [tr("Merhaba! Telefonda ton her şeydir çünkü yüz yok. Almancanın en kibar iki kalıbı burada devreye giriyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İkisi de dilek kipinde ve ikisi de soru biçiminde: karşı tarafa hayır deme alanı bırakıyorlar. Önce kelimeler.")] },
      word("İlk", { de: "durchstellen", tr: "bağlamak (telefonda)" }),
      word("İkinci", { de: "der Rückruf", tr: "geri arama" }),
      word("Üçüncü", { de: "die Leitung", tr: "hat" }),
      word("Dördüncü", { de: "hinterlassen", tr: "bırakmak (mesaj)" }),
      word("Son", { de: "umgehend", tr: "derhâl" }),
      { say: [tr("Örnek:"), de("Dürfte ich Sie kurz stören?"), tr("Tekrar edin:"), de("Dürfte ich Sie kurz stören")], expect: repeat("Dürfte ich Sie kurz stören") },
      { say: [tr("Sıra sende: 'Beni bağlar mısınız lütfen?'")], expect: produce("Wären Sie so freundlich, mich durchzustellen", [tr("Mastar öbeğinde ayrılabilen fiil zu'yu ortasına alır:"), de("Wären Sie so freundlich, mich durchzustellen?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir mesaj bırakabilir miyim?'")], expect: produce("Darf ich eine Nachricht hinterlassen", [tr("Modal fiil başta soru; mastar sonda:"), de("Darf ich eine Nachricht hinterlassen?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Hat meşgul.'")], expect: produce("Die Leitung ist besetzt", [tr("Kısa durum cümlesi:"), de("Die Leitung ist besetzt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wären Sie so freundlich, mich durchzustellen?"), tr("cümlesi doğru mu?")], expect: truefalse("Wären Sie so freundlich, mich durchzustellen?", true, [tr("Doğru. Dilek kipi soru biçiminde ve ayrılabilen fiil mastar öbeğinde zu'yu ortasına almış.")]) },
      { say: [tr("Son: 'Derhâl geri arayacağım.'")], expect: produce("Ich rufe umgehend zurück", [tr("Zarf fiilden sonra; ayrılabilen önek sonda:"), de("Ich rufe umgehend zurück."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kurumu arayıp zor bir istekte bulunacaksın.")] },
    ],
    roleplay: {
      scene: "Bir kurumu arıyorsun ve ulaşman gereken kişi yok. Kibarca durumunu anlat, bağlanmayı iste, olmazsa mesaj bırak ve geri arama için bir zaman kararlaştır.",
      partner: "kurallara bağlı, kolayca bağlamayan bir santral görevlisi",
      opening: "Guten Tag, Zentrale. Herr Baumann ist heute leider nicht im Haus — worum geht es denn?",
      openingTr: "İyi günler, santral. Bay Baumann bugün maalesef binada değil — konu nedir?",
      goal: "Konu anlatılmış, mesaj bırakılmış ve geri arama için bir zaman kararlaştırılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-partikel-pruefung",
    icon: "school",
    level: "C1",
    course: "de",
    title: "Der Partikel-Parcours",
    titleTr: "Parçacık senaryosu",
    summary: "Parçacıkları birleşim hâlinde ve doğru sırayla kullanmayı öğretir.",
    minutes: 12,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "die Kombination", tr: "birleşim" },
      { de: "die Nuance", tr: "nüans" },
      { de: "die Betonung", tr: "vurgu" },
      { de: "einsetzen", tr: "kullanmak, devreye sokmak" },
      { de: "treffsicher", tr: "isabetli" },
    ],
    patterns: [
      { de: "doch mal / ja wohl", tr: "sabit birleşimler" },
      { de: "Die Betonung bestimmt die Nuance.", tr: "vurgu anlamı belirler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi: parçacıkları tek tek değil BİRLEŞİM hâlinde kullanmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Almanca iki, hatta üç parçacığı üst üste koyabilir ama sıra sabittir. 'ja wohl' olur, tersi olmaz. Bugün en sık üçünü kuracağız. Önce kelimeler.")] },
      word("İlk", { de: "die Kombination", tr: "birleşim" }),
      word("İkinci", { de: "die Nuance", tr: "nüans" }),
      word("Üçüncü", { de: "die Betonung", tr: "vurgu" }),
      word("Dördüncü", { de: "einsetzen", tr: "kullanmak" }),
      word("Son", { de: "treffsicher", tr: "isabetli" }),
      { say: [tr("Örnek:"), de("Komm doch mal vorbei."), tr("Tekrar edin:"), de("Komm doch mal vorbei")], expect: repeat("Komm doch mal vorbei") },
      { say: [tr("Sıra sende: 'Bu zaten belli, değil mi?'")], expect: produce("Das ist ja wohl klar", [tr("İki parçacık bu sırada gelir ve birlikte hafif bir sitem taşır:"), de("Das ist ja wohl klar."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Şunu bir dinle bakalım.'")], expect: produce("Hör doch mal zu", [tr("Emir kipi, iki parçacık, ayrılabilen önek en sonda:"), de("Hör doch mal zu."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Vurgu nüansı belirliyor.'")], expect: produce("Die Betonung bestimmt die Nuance", [tr("Kısa cümle; nesne belirtme hâlinde:"), de("Die Betonung bestimmt die Nuance."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist wohl ja klar."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist wohl ja klar.", false, [tr("Bu iki parçacığın sırası sabittir ve ters çevrilemez:"), de("Das ist ja wohl klar.")]) },
      { say: [tr("Son: 'Bunu isabetli kullanmak istiyorum.'")], expect: produce("Ich möchte das treffsicher einsetzen", [tr("Zarf mastardan önce; ayrılabilen mastar sonda:"), de("Ich möchte das treffsicher einsetzen."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada tonunu üç kez değiştireceksin: davet, sitem, teselli.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşınla planı bozan bir durumu konuşuyorsun. Konuşma boyunca tonunu üç kez değiştir: önce davet ve yumuşatma, sonra hafif sitem, sonunda teselli ve kabullenme.",
      partner: "planı bozan, önce savunmaya geçen ama sonunda özür dileyen bir arkadaş",
      opening: "Sag mal, bist du jetzt sauer? Das war doch wirklich nicht meine Schuld.",
      openingTr: "Söylesene, kızgın mısın şimdi? Bu gerçekten benim suçum değildi.",
      goal: "Sitem söylenmiş, karşı tarafın gerekçesi dinlenmiş ve konuşma kabullenme ile yeni bir planla kapanmış olur.",
      minTurns: 9,
    },
  },
];
