import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * C1 · Modül 4 — Deyimler ve mecazlar (031–040).
 *
 * Bu modülün riski büyük ve bilerek göze alındı: deyim öğretmek kolayca
 * ezbere listeye dönüşür. Onu önlemek için her ders bir ALANIN etrafında
 * kuruldu (vücut, yiyecek, hayvan, hava, renk, spor, para, müzik) ve her
 * derste deyimin ANLAMI sınanıyor, biçimi değil: doğru/yanlış maddelerinin
 * çoğu "bu deyim şu demektir" hükmünü yargılatıyor.
 *
 * Sebebi ölçülebilir bir kusur: deyimi tanımak ile kullanabilmek ayrı şeyler
 * ve arada üçüncü bir tehlike var — YANLIŞ anladığı hâlde kullanmak.
 * "Das ist mir Wurst" cümlesini sosis sevgisi sanan biri onu doğru telaffuz
 * eder ve yine de yanlış konuşur.
 *
 * 039 bilerek Türkçe konuşana ayrıldı: kelimesi kelimesine çevrilen deyimin
 * neden çökdüğü ve doğru karşılığın nasıl aranacağı. 040 ise dozu öğretiyor —
 * bir konuşmaya sıkıştırılan on deyim, hiç deyim kullanmamaktan daha kötü.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deC1B04: Lesson[] = [
  {
    id: "de-c1-daumen",
    icon: "greet",
    level: "C1",
    course: "de",
    title: "Die Daumen drücken",
    titleTr: "Vücut deyimleri",
    summary: "Vücutla kurulan deyimleri ve kelimesi kelimesine çevirme tuzağını öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "die Redewendung", tr: "deyim" },
      { de: "wörtlich", tr: "kelimesi kelimesine" },
      { de: "unter vier Augen", tr: "baş başa" },
      { de: "Hand und Fuß haben", tr: "tutarlı olmak" },
      { de: "die Daumen drücken", tr: "şans dilemek" },
    ],
    patterns: [
      { de: "Ich drücke dir die Daumen.", tr: "şans dilerim" },
      { de: "unter vier Augen", tr: "yalnız iki kişi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: deyimler. Ve baştan bir uyarı — bu modülde asıl tehlike deyimi bilmemek değil, YANLIŞ bildiği hâlde kullanmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İlk grup vücutla kurulanlar. Türkçede de böyle deyimler var ama karşılıklar birebir değil: Almanca şans dilerken başparmağı sıkar, biz parmak çaprazlamayız. Önce kelimeler.")] },
      word("İlk", { de: "die Redewendung", tr: "deyim" }),
      word("İkinci", { de: "wörtlich", tr: "kelimesi kelimesine" }),
      word("Üçüncü", { de: "unter vier Augen", tr: "baş başa" }),
      word("Dördüncü", { de: "Hand und Fuß haben", tr: "tutarlı olmak" }),
      word("Son", { de: "die Daumen drücken", tr: "şans dilemek" }),
      { say: [tr("Örnek:"), de("Ich drücke dir die Daumen."), tr("Tekrar edin:"), de("Ich drücke dir die Daumen")], expect: repeat("Ich drücke dir die Daumen") },
      { say: [tr("Sıra sende: 'Bunu baş başa konuşalım.'")], expect: produce("Das besprechen wir unter vier Augen", [tr("Nesne öne alınmış; deyim değişmeden sonda:"), de("Das besprechen wir unter vier Augen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Planın eli ayağı tutuyor.'")], expect: produce("Der Plan hat Hand und Fuß", [tr("Deyimde isimler belirteçsiz kalır:"), de("Der Plan hat Hand und Fuß."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Herkes sana şans diliyor.'")], expect: produce("Alle drücken dir die Daumen", [tr("Kişi yönelme hâlinde, nesne belirtili:"), de("Alle drücken dir die Daumen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Die Daumen drücken heißt, jemandem die Hand zu geben.")], expect: truefalse("Die Daumen drücken heißt, jemandem die Hand zu geben.", false, [tr("Hayır — bu deyim şans dilemek demektir. El sıkışmakla ilgisi yok:"), de("Ich drücke dir die Daumen für die Prüfung.")]) },
      { say: [tr("Son: 'Deyimler kelimesi kelimesine çevrilmez.'")], expect: produce("Redewendungen übersetzt man nicht wörtlich", [tr("Nesne öne alınmış, belirteçsiz çoğul:"), de("Redewendungen übersetzt man nicht wörtlich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir arkadaşına önemli bir gün için destek olacaksın.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşının yarın önemli bir sınavı ya da görüşmesi var. Ona destek ol, kaygısını dinle, planının sağlam olduğunu söyle ve baş başa konuşmak istediği bir şey olup olmadığını sor. Deyimleri dozunda kullan.",
      partner: "gergin, kendine güvenmeyen ama konuşmak isteyen bir arkadaş",
      opening: "Ich glaube, ich vermassle das morgen. Sag mal ehrlich — hat mein Plan überhaupt Hand und Fuß?",
      openingTr: "Sanırım yarın bunu batıracağım. Dürüst söyle — planımın eli ayağı tutuyor mu ki?",
      goal: "Kaygı dinlenmiş, plana dair dürüst bir değerlendirme yapılmış ve destek somut bir sözle verilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-tomaten",
    icon: "food",
    level: "C1",
    course: "de",
    title: "Tomaten auf den Augen",
    titleTr: "Yiyecek deyimleri",
    summary: "Yiyecekle kurulan deyimlerin gerçek anlamlarını öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "Tomaten auf den Augen", tr: "göz göre göre görmemek" },
      { de: "Das ist mir Wurst", tr: "umurumda değil" },
      { de: "in den sauren Apfel beißen", tr: "acı lokmayı yutmak" },
      { de: "die Extrawurst", tr: "ayrıcalık" },
      { de: "das Haar in der Suppe", tr: "kılı kırk yarma" },
    ],
    patterns: [
      { de: "Du hast Tomaten auf den Augen.", tr: "gözünün önündekini görmüyorsun" },
      { de: "in den sauren Apfel beißen", tr: "istemeyerek katlanmak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün mutfaktan çıkan deyimler. Hiçbiri yemekle ilgili değil — hepsi insanla ilgili. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu grup Türkçe konuşan için özellikle tuzaklı, çünkü kelimeler tanıdık ve anlam tamamen başka yerde. Önce kelimeler.")] },
      word("İlk", { de: "Tomaten auf den Augen", tr: "göz göre göre görmemek" }),
      word("İkinci", { de: "Das ist mir Wurst", tr: "umurumda değil" }),
      word("Üçüncü", { de: "in den sauren Apfel beißen", tr: "acı lokmayı yutmak" }),
      word("Dördüncü", { de: "die Extrawurst", tr: "ayrıcalık" }),
      word("Son", { de: "das Haar in der Suppe", tr: "kılı kırk yarma" }),
      { say: [tr("Örnek:"), de("Du hast wohl Tomaten auf den Augen!"), tr("Tekrar edin:"), de("Du hast wohl Tomaten auf den Augen")], expect: repeat("Du hast wohl Tomaten auf den Augen") },
      { say: [tr("Sıra sende: 'Acı lokmayı yutmak zorundayız.'")], expect: produce("Wir müssen in den sauren Apfel beißen", [tr("Deyim olduğu gibi kalır; mastar sonda:"), de("Wir müssen in den sauren Apfel beißen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Hep ayrıcalık istiyor.'")], expect: produce("Er will immer eine Extrawurst", [tr("Belirtisiz dişil belirtme hâlinde:"), de("Er will immer eine Extrawurst."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sürekli kusur arıyor.'")], expect: produce("Er sucht ständig das Haar in der Suppe", [tr("Deyimdeki belirteçler sabittir:"), de("Er sucht ständig das Haar in der Suppe."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Das ist mir Wurst heißt, dass man Wurst gern isst.")], expect: truefalse("Das ist mir Wurst heißt, dass man Wurst gern isst.", false, [tr("Hayır — anlamı 'umurumda değil'. Yiyecekle ilgisi yok:"), de("Ob wir heute oder morgen fahren, ist mir Wurst.")]) },
      { say: [tr("Son: 'Bu benim umurumda değil.'")], expect: produce("Das ist mir Wurst", [tr("Kişi yönelme hâlinde; deyim belirteçsiz:"), de("Das ist mir Wurst."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kararı tartışacaksın — bazı şeyler umurunda, bazıları değil.")] },
    ],
    roleplay: {
      scene: "Ortak bir karar veriyorsunuz (tatil, taşınma, bir alım). Hangi noktaların senin için önemli olduğunu, hangilerinin umurunda olmadığını söyle; bir konuda istemeyerek katlanmayı kabul et ve bir sonuca varın.",
      partner: "her ayrıntıda kusur arayan, kolay karar vermeyen bir arkadaş",
      opening: "Also, mir ist das ehrlich gesagt nicht Wurst. Sag du zuerst: Was ist dir wirklich wichtig?",
      openingTr: "Yani, açıkçası benim umurumda. Önce sen söyle: Senin için gerçekten önemli olan ne?",
      goal: "Önemli olan ve olmayan noktalar ayrılmış, bir konuda taviz verilmiş ve ortak bir karara varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-tiere-idiome",
    icon: "dog",
    level: "C1",
    course: "de",
    title: "Schwein gehabt!",
    titleTr: "Hayvan deyimleri",
    summary: "Hayvanla kurulan deyimleri ve güven anlatan kalıpları öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "Schwein gehabt", tr: "şansı yaver gitmiş" },
      { de: "die Katze im Sack kaufen", tr: "görmeden almak" },
      { de: "Pferde stehlen können", tr: "her işe girişilecek kadar güvenmek" },
      { de: "auf den Hund kommen", tr: "batmak, düşmek" },
      { de: "einen Bären aufbinden", tr: "kafaya atmak" },
    ],
    patterns: [
      { de: "Da hast du Schwein gehabt!", tr: "şansın varmış" },
      { de: "Mit ihm kann man Pferde stehlen.", tr: "ona sonuna kadar güvenilir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün hayvanlar. Almanca hayvan deyimleri Türkçedekilerden çok farklı çalışıyor — domuz uğur getiriyor mesela. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İçlerinden biri övgü, biri uyarı, biri de suçlama: 'onunla at çalınır' cümlesi Almancada en güçlü güven ifadelerinden biri. Önce kelimeler.")] },
      word("İlk", { de: "Schwein gehabt", tr: "şansı yaver gitmiş" }),
      word("İkinci", { de: "die Katze im Sack kaufen", tr: "görmeden almak" }),
      word("Üçüncü", { de: "Pferde stehlen können", tr: "sonuna kadar güvenmek" }),
      word("Dördüncü", { de: "auf den Hund kommen", tr: "batmak, düşmek" }),
      word("Son", { de: "einen Bären aufbinden", tr: "kafaya atmak" }),
      { say: [tr("Örnek:"), de("Da hast du aber Schwein gehabt!"), tr("Tekrar edin:"), de("Da hast du aber Schwein gehabt")], expect: repeat("Da hast du aber Schwein gehabt") },
      { say: [tr("Sıra sende: 'Görmeden satın almam.'")], expect: produce("Die Katze im Sack kaufe ich nicht", [tr("Nesne öne alınmış; deyim bozulmadan:"), de("Die Katze im Sack kaufe ich nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Onunla her işe girişilir.'")], expect: produce("Mit ihm kann man Pferde stehlen", [tr("Tümleç başta; mastar sonda:"), de("Mit ihm kann man Pferde stehlen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bana kuyruklu bir yalan söyledi.'")], expect: produce("Er hat mir einen Bären aufgebunden", [tr("Kişi yönelme, nesne belirtme hâlinde; ayrılabilen ortaç sonda:"), de("Er hat mir einen Bären aufgebunden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Schwein gehabt heißt: Glück gehabt.")], expect: truefalse("Schwein gehabt heißt: Glück gehabt.", true, [tr("Doğru. Domuz Almancada uğur sayılır; deyim 'şansın varmış' demektir ve hayvanla ilgisi kalmamıştır.")]) },
      { say: [tr("Son: 'Firma epey battı.'")], expect: produce("Die Firma ist auf den Hund gekommen", [tr("Hareket bildiren deyim sein ile çekilir:"), de("Die Firma ist auf den Hund gekommen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada kıl payı atlatılan bir olayı anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Kıl payı atlatılan bir olayı bir arkadaşına anlatıyorsun: ne oldu, neden şanslıydın, kimin sözüne güvendin ve bir daha ne yapardın. Deyimleri yerinde kullan.",
      partner: "hikâyeyi merakla dinleyen, ayrıntı soran bir arkadaş",
      opening: "Erzähl mal von Anfang an — und sag mir, ob du dabei wirklich Schwein gehabt hast oder ob es Können war?",
      openingTr: "Baştan anlat hadi — ve söyle bakalım, gerçekten şansın mı yaver gitti yoksa beceri miydi?",
      goal: "Olay baştan anlatılmış, şans ile becerinin payı ayrılmış ve bir daha ne yapılacağı söylenmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-wetter-idiome",
    icon: "rain",
    level: "C1",
    course: "de",
    title: "Ein Gewitter zieht auf",
    titleTr: "Hava mecazları",
    summary: "Hava imgeleriyle kurulan duygu ve ortam mecazlarını öğretir.",
    minutes: 12,
    focusId: "Metaphern",
    vocab: [
      { de: "dicke Luft", tr: "gergin hava" },
      { de: "der Lichtblick", tr: "umut ışığı" },
      { de: "im Trüben fischen", tr: "bulanık suda balık avlamak" },
      { de: "der Sturm im Wasserglas", tr: "bardakta fırtına" },
      { de: "eiskalt", tr: "buz gibi, acımasız" },
    ],
    patterns: [
      { de: "Bei uns herrscht dicke Luft.", tr: "ortam gergin" },
      { de: "ein Sturm im Wasserglas", tr: "abartılmış mesele" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün hava. Ama hiçbiri gerçekten havadan bahsetmiyor — hepsi ortamı ve duyguyu anlatıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu grup mecaz, deyim değil: yani sözcükler hâlâ kendi anlamını taşıyor ama başka bir alana taşınmış durumda. Türkçede de 'ortam gergin' deriz. Önce kelimeler.")] },
      word("İlk", { de: "dicke Luft", tr: "gergin hava" }),
      word("İkinci", { de: "der Lichtblick", tr: "umut ışığı" }),
      word("Üçüncü", { de: "im Trüben fischen", tr: "bulanık suda balık avlamak" }),
      word("Dördüncü", { de: "der Sturm im Wasserglas", tr: "bardakta fırtına" }),
      word("Son", { de: "eiskalt", tr: "buz gibi, acımasız" }),
      { say: [tr("Örnek:"), de("Bei uns im Büro herrscht dicke Luft."), tr("Tekrar edin:"), de("Bei uns im Büro herrscht dicke Luft")], expect: repeat("Bei uns im Büro herrscht dicke Luft") },
      { say: [tr("Sıra sende: 'Bu tek umut ışığıydı.'")], expect: produce("Das war der einzige Lichtblick", [tr("Belirtili eril; sıfat -e ekini alır:"), de("Das war der einzige Lichtblick."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu bardakta koparılan bir fırtına.'")], expect: produce("Das ist ein Sturm im Wasserglas", [tr("Mecaz olduğu gibi; edat yönelme hâlinde:"), de("Das ist ein Sturm im Wasserglas."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bulanık suda balık avlıyor.'")], expect: produce("Er fischt im Trüben", [tr("İsimleşmiş sıfat yönelme hâlinde:"), de("Er fischt im Trüben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Dicke Luft bedeutet, dass die Luft im Raum schlecht ist.")], expect: truefalse("Dicke Luft bedeutet, dass die Luft im Raum schlecht ist.", false, [tr("Hayır — mecaz ortamın gerginliğini anlatır, havanın kalitesini değil:"), de("Nach der Sitzung herrschte dicke Luft.")]) },
      { say: [tr("Son: 'Soğukkanlılıkla hesap yaptı.'")], expect: produce("Er hat eiskalt kalkuliert", [tr("Zarf ortaçtan önce:"), de("Er hat eiskalt kalkuliert."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada gergin bir ortamı anlatacaksın.")] },
    ],
    roleplay: {
      scene: "İş yerinde ortam gerginleşti ve bir arkadaşınla konuşuyorsun: gerginlik nereden geliyor, abartılan bir şey mi, umut verici bir gelişme var mı ve ne yapmalısın. Mecazları yerinde kullan.",
      partner: "durumu abartılı bulan, ama kaygını ciddiye alan bir arkadaş",
      opening: "Ist das wirklich so schlimm, oder ist das nicht eher ein Sturm im Wasserglas?",
      openingTr: "Gerçekten bu kadar kötü mü, yoksa bu daha çok bardakta fırtına mı?",
      goal: "Gerginliğin kaynağı anlatılmış, abartı payı tartılmış ve ne yapılacağına dair bir sonuca varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-farben-idiome",
    icon: "art",
    level: "C1",
    course: "de",
    title: "Blau machen",
    titleTr: "Renk deyimleri",
    summary: "Renklerle kurulan deyimleri ve tuzaklarını öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "blaumachen", tr: "işi asmak" },
      { de: "schwarzfahren", tr: "kaçak binmek" },
      { de: "das Gelbe vom Ei", tr: "işin en iyisi" },
      { de: "grünes Licht geben", tr: "yeşil ışık yakmak" },
      { de: "rotsehen", tr: "öfkeden gözü dönmek" },
    ],
    patterns: [
      { de: "Er hat blaugemacht.", tr: "işe gitmedi" },
      { de: "Das ist nicht das Gelbe vom Ei.", tr: "pek iyi değil" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün renkler. Ve bu grup en yanıltıcılarından: hiçbirinde renk gerçek anlamında değil. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki tanesi ayrılabilen fiil gibi çekiliyor, biri de sabit bir öbek. Anlamlarını karıştırmak burada gerçekten mahcup edici olabilir. Önce kelimeler.")] },
      word("İlk", { de: "blaumachen", tr: "işi asmak" }),
      word("İkinci", { de: "schwarzfahren", tr: "kaçak binmek" }),
      word("Üçüncü", { de: "das Gelbe vom Ei", tr: "işin en iyisi" }),
      word("Dördüncü", { de: "grünes Licht geben", tr: "yeşil ışık yakmak" }),
      word("Son", { de: "rotsehen", tr: "öfkeden gözü dönmek" }),
      { say: [tr("Örnek:"), de("Er hat gestern blaugemacht."), tr("Tekrar edin:"), de("Er hat gestern blaugemacht")], expect: repeat("Er hat gestern blaugemacht") },
      { say: [tr("Sıra sende: 'Kaçak binmek pahalıya patlar.'")], expect: produce("Schwarzfahren wird teuer", [tr("İsimleşmiş mastar özne olarak başta:"), de("Schwarzfahren wird teuer."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu da işin en iyisi değil.'")], expect: produce("Das ist auch nicht das Gelbe vom Ei", [tr("Deyim olduğu gibi; belirteç sabit:"), de("Das ist auch nicht das Gelbe vom Ei."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yönetim yeşil ışık yaktı.'")], expect: produce("Die Leitung hat grünes Licht gegeben", [tr("Belirteçsiz nesne; ortaç sonda:"), de("Die Leitung hat grünes Licht gegeben."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Blaumachen heißt, etwas blau anzustreichen.")], expect: truefalse("Blaumachen heißt, etwas blau anzustreichen.", false, [tr("Hayır — anlamı işe gitmemek, işi asmak. Boyayla ilgisi yok:"), de("Er hat am Montag blaugemacht.")]) },
      { say: [tr("Son: 'Bunu duyunca gözü döndü.'")], expect: produce("Als er das hörte, sah er rot", [tr("Yan cümle önde; ana cümle fiille başlar:"), de("Als er das hörte, sah er rot."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir izin ya da onay meselesini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın sık sık işi asıyor ve bu sana yük biniyor. Durumu konuş: ne fark ettin, ne hissediyorsun, yönetimden onay gerekiyor mu ve nasıl devam edeceksiniz.",
      partner: "önce inkâr eden, sonra sebebini anlatan bir meslektaş",
      opening: "Sag mal, hast du irgendein Problem mit mir? Du guckst schon die ganze Woche so.",
      openingTr: "Söylesene, benimle bir sorunun mu var? Bütün hafta öyle bakıyorsun.",
      goal: "Fark edilen durum suçlamadan söylenmiş, sebebi dinlenmiş ve nasıl devam edileceği kararlaşmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-sport-idiome",
    icon: "sport",
    level: "C1",
    course: "de",
    title: "Am Ball bleiben",
    titleTr: "Spor deyimleri",
    summary: "Spordan gelen deyimlerle azim ve rekabet anlatmayı öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "am Ball bleiben", tr: "peşini bırakmamak" },
      { de: "die Latte hoch legen", tr: "çıtayı yükseltmek" },
      { de: "ein Eigentor schießen", tr: "kendi kalesine gol atmak" },
      { de: "das Handtuch werfen", tr: "havlu atmak" },
      { de: "in Führung gehen", tr: "öne geçmek" },
    ],
    patterns: [
      { de: "Bleib am Ball!", tr: "bırakma, devam et" },
      { de: "ein Eigentor schießen", tr: "kendine zarar vermek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün spor. Bu grup iş hayatında en çok kullanılan deyimler — toplantıda futbol terimi duyunca şaşırma. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İyi haber: bu deyimlerin çoğu Türkçede de var, çünkü kaynak aynı. 'Havlu atmak' ve 'kendi kalesine gol' birebir örtüşüyor. Önce kelimeler.")] },
      word("İlk", { de: "am Ball bleiben", tr: "peşini bırakmamak" }),
      word("İkinci", { de: "die Latte hoch legen", tr: "çıtayı yükseltmek" }),
      word("Üçüncü", { de: "ein Eigentor schießen", tr: "kendi kalesine gol atmak" }),
      word("Dördüncü", { de: "das Handtuch werfen", tr: "havlu atmak" }),
      word("Son", { de: "in Führung gehen", tr: "öne geçmek" }),
      { say: [tr("Örnek:"), de("Bleib am Ball, es lohnt sich."), tr("Tekrar edin:"), de("Bleib am Ball, es lohnt sich")], expect: repeat("Bleib am Ball, es lohnt sich") },
      { say: [tr("Sıra sende: 'Çıtayı çok yükseğe koydular.'")], expect: produce("Sie haben die Latte sehr hoch gelegt", [tr("Deyimde nesne belirtili; ortaç sonda:"), de("Sie haben die Latte sehr hoch gelegt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bununla kendi kalesine gol attı.'")], expect: produce("Damit hat er ein Eigentor geschossen", [tr("Edat zamirle kaynaşır; ortaç sonda:"), de("Damit hat er ein Eigentor geschossen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Havlu atmak istemiyorum.'")], expect: produce("Ich will das Handtuch nicht werfen", [tr("Olumsuzluk mastardan önce:"), de("Ich will das Handtuch nicht werfen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Am Ball bleiben heißt: dranbleiben und nicht aufgeben.")], expect: truefalse("Am Ball bleiben heißt: dranbleiben und nicht aufgeben.", true, [tr("Doğru. Deyim futboldan geliyor ama iş hayatında 'peşini bırakma' anlamında kullanılıyor.")]) },
      { say: [tr("Son: 'İkinci yarıda öne geçtik.'")], expect: produce("In der zweiten Halbzeit sind wir in Führung gegangen", [tr("Tümleç başta; hareket fiili sein ile:"), de("In der zweiten Halbzeit sind wir in Führung gegangen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada uzun soluklu bir işi konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Uzun süredir yürüttüğün bir işte tıkandın ve bırakmayı düşünüyorsun. Bir arkadaşınla konuş: neden zorlandığını anlat, kendi hatanı kabul et, bırakmanın ne demek olacağını tart ve bir karara var.",
      partner: "bırakmana karşı çıkan ama gerekçeni dinleyen bir arkadaş",
      opening: "Du willst das Handtuch werfen? Nach zwei Jahren? Sag mir zuerst, was genau nicht mehr geht.",
      openingTr: "Havlu mu atacaksın? İki yıl sonra? Önce tam olarak neyin artık yürümediğini söyle.",
      goal: "Zorluk anlatılmış, kendi payı kabul edilmiş ve devam etme ya da bırakma konusunda bir karara varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-geld-idiome",
    icon: "money",
    level: "C1",
    course: "de",
    title: "Geld zum Fenster hinaus",
    titleTr: "Para deyimleri",
    summary: "Parayla ilgili deyimleri ve kesinlik ifadelerini öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "Geld zum Fenster hinauswerfen", tr: "parayı çöpe atmak" },
      { de: "tief in die Tasche greifen", tr: "cebinden çok para çıkarmak" },
      { de: "auf Heller und Pfennig", tr: "kuruşuna kadar" },
      { de: "ein Vermögen kosten", tr: "servete mal olmak" },
      { de: "knapp bei Kasse sein", tr: "parası kıt olmak" },
    ],
    patterns: [
      { de: "Das ist Geld zum Fenster hinausgeworfen.", tr: "boşa harcama" },
      { de: "auf Heller und Pfennig", tr: "tam tamına" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün para. Bu deyimlerin ikisi eski para birimlerinden geliyor ama hâlâ günlük dilde. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir tanesi özellikle işine yarayacak: parasının kıt olduğunu söylemenin kibar yolu. Türkçede 'sıkışığım' deriz; Almancanın kendi kalıbı var. Önce kelimeler.")] },
      word("İlk", { de: "Geld zum Fenster hinauswerfen", tr: "parayı çöpe atmak" }),
      word("İkinci", { de: "tief in die Tasche greifen", tr: "cebinden çok para çıkarmak" }),
      word("Üçüncü", { de: "auf Heller und Pfennig", tr: "kuruşuna kadar" }),
      word("Dördüncü", { de: "ein Vermögen kosten", tr: "servete mal olmak" }),
      word("Son", { de: "knapp bei Kasse sein", tr: "parası kıt olmak" }),
      { say: [tr("Örnek:"), de("Das ist Geld zum Fenster hinausgeworfen."), tr("Tekrar edin:"), de("Das ist Geld zum Fenster hinausgeworfen")], expect: repeat("Das ist Geld zum Fenster hinausgeworfen") },
      { say: [tr("Sıra sende: 'Bunun için cebinden epey para çıkarman gerekir.'")], expect: produce("Dafür musst du tief in die Tasche greifen", [tr("Edat zamirle kaynaşır; deyim mastar hâlinde sonda:"), de("Dafür musst du tief in die Tasche greifen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kuruşuna kadar geri ödedi.'")], expect: produce("Er hat auf Heller und Pfennig zurückgezahlt", [tr("Deyim değişmez; ayrılabilen ortaç sonda:"), de("Er hat auf Heller und Pfennig zurückgezahlt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu bir servete mal oluyor.'")], expect: produce("Das kostet ein Vermögen", [tr("Belirtisiz nötr belirtme hâlinde:"), de("Das kostet ein Vermögen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Knapp bei Kasse sein heißt, dass die Kasse zu klein ist.")], expect: truefalse("Knapp bei Kasse sein heißt, dass die Kasse zu klein ist.", false, [tr("Hayır — deyim kişinin parasının kıt olduğunu anlatır, kasanın boyutunu değil:"), de("Diesen Monat bin ich knapp bei Kasse.")]) },
      { say: [tr("Son: 'Şu sıra param kıt.'")], expect: produce("Ich bin gerade knapp bei Kasse", [tr("Deyim sein ile; zarf ortada:"), de("Ich bin gerade knapp bei Kasse."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada pahalı bir harcamayı tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Ortak bir harcama konuşuyorsunuz ve sen bunu gereksiz buluyorsun. Neden boşa para olduğunu söyle, kendi durumunu kibarca belirt, daha ucuz bir alternatif öner ve bir karara varın.",
      partner: "pahalı seçeneği savunan, kaliteye para vermeye hazır bir arkadaş",
      opening: "Ich weiß, es ist teuer. Aber billig kaufen heißt oft zweimal kaufen — oder siehst du das anders?",
      openingTr: "Biliyorum, pahalı. Ama ucuz almak çoğu zaman iki kez almak demek — yoksa sen başka mı görüyorsun?",
      goal: "İki tarafın gerekçesi söylenmiş, bütçe durumu kibarca belirtilmiş ve bir karara varılmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-musik-idiome",
    icon: "music",
    level: "C1",
    course: "de",
    title: "Den Ton angeben",
    titleTr: "Müzik deyimleri",
    summary: "Müzikten gelen deyimlerle güç ve etki ilişkilerini anlatmayı öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "den Ton angeben", tr: "havayı belirlemek" },
      { de: "nach jemandes Pfeife tanzen", tr: "birinin borusunu öttürmesi" },
      { de: "Musik in meinen Ohren", tr: "kulağa hoş gelen" },
      { de: "die erste Geige spielen", tr: "birinci kemanı çalmak" },
      { de: "der Ohrwurm", tr: "akıldan çıkmayan şarkı" },
    ],
    patterns: [
      { de: "Bei uns gibt sie den Ton an.", tr: "havayı o belirliyor" },
      { de: "Das ist Musik in meinen Ohren.", tr: "duymak istediğim buydu" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün müzik. Ama konu müzik değil güç: kim havayı belirliyor, kim kimin dediğini yapıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu grup ofiste sık duyulur ve çoğu Türkçedeki karşılığına yakın — 'borusunu öttürmek' ile 'birinin düdüğüne göre dans etmek' aynı yere bakıyor. Önce kelimeler.")] },
      word("İlk", { de: "den Ton angeben", tr: "havayı belirlemek" }),
      word("İkinci", { de: "nach jemandes Pfeife tanzen", tr: "birinin dediğini yapmak" }),
      word("Üçüncü", { de: "Musik in meinen Ohren", tr: "kulağa hoş gelen" }),
      word("Dördüncü", { de: "die erste Geige spielen", tr: "birinci kemanı çalmak" }),
      word("Son", { de: "der Ohrwurm", tr: "akıldan çıkmayan şarkı" }),
      { say: [tr("Örnek:"), de("Bei uns gibt sie den Ton an."), tr("Tekrar edin:"), de("Bei uns gibt sie den Ton an")], expect: repeat("Bei uns gibt sie den Ton an") },
      { say: [tr("Sıra sende: 'Kimsenin dediğini yapmam.'")], expect: produce("Ich tanze nach niemandes Pfeife", [tr("Tamlayan hâlindeki belirsiz zamir; edat sabit:"), de("Ich tanze nach niemandes Pfeife."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu kulağa çok hoş geliyor.'")], expect: produce("Das ist Musik in meinen Ohren", [tr("Deyim değişmez; çoğul yönelme hâlinde -n eki:"), de("Das ist Musik in meinen Ohren."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Orada birinci kemanı o çalıyor.'")], expect: produce("Dort spielt er die erste Geige", [tr("Yer zarfı başta; fiil ikinci sırada:"), de("Dort spielt er die erste Geige."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Den Ton angeben heißt, besonders laut zu singen.")], expect: truefalse("Den Ton angeben heißt, besonders laut zu singen.", false, [tr("Hayır — deyim kimin belirleyici olduğunu anlatır, sesin yüksekliğini değil:"), de("In dieser Abteilung gibt der Betriebsrat den Ton an.")]) },
      { say: [tr("Son: 'Bu şarkı aklımdan çıkmıyor.'")], expect: produce("Das Lied ist ein echter Ohrwurm", [tr("Belirtisiz eril yalın hâlde sıfat -er ekini alır:"), de("Das Lied ist ein echter Ohrwurm."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir ekipteki güç dengesini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Yeni geçtiğin bir ekipte kimin sözünün geçtiğini anlamaya çalışıyorsun. Bir meslektaşına sor: kim havayı belirliyor, kararlar nasıl alınıyor, sen nasıl yer edinebilirsin. Deyimleri dozunda kullan.",
      partner: "ekibi iyi tanıyan, açık sözlü ama diplomatik bir meslektaş",
      opening: "Du bist neu, also sage ich es dir gleich: Auf dem Papier entscheidet die Leitung. Und in Wirklichkeit? Rate mal.",
      openingTr: "Yenisin, o yüzden hemen söyleyeyim: Kâğıt üzerinde kararı yönetim veriyor. Gerçekte? Tahmin et.",
      goal: "Ekipteki gerçek güç dengesi öğrenilmiş ve öğrencinin nasıl yer edineceğine dair somut bir tavsiye alınmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-falsche-freunde-idiome",
    icon: "question",
    level: "C1",
    course: "de",
    title: "Wörtlich wird's falsch",
    titleTr: "Türkçeyle tuzaklar",
    summary: "Deyimi kelimesi kelimesine çevirme tuzağını ve doğru karşılık aramayı öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "die Falle", tr: "tuzak" },
      { de: "sinngemäß", tr: "anlamca" },
      { de: "die Entsprechung", tr: "karşılık" },
      { de: "verwechseln", tr: "karıştırmak" },
      { de: "missverständlich", tr: "yanlış anlaşılır" },
    ],
    patterns: [
      { de: "Wörtlich übersetzt wird daraus Unsinn.", tr: "birebir çeviri çöker" },
      { de: "Dafür gibt es eine Entsprechung.", tr: "karşılığı vardır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün modülün en faydalı dersi: deyimi Türkçeden Almancaya taşımanın neden çökdüğü. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şu: deyim kelimeden değil RESİMDEN oluşur ve resimler dilden dile değişir. Doğru yöntem karşılığı ARAMAK, çevirmek değil. Önce kelimeler.")] },
      word("İlk", { de: "die Falle", tr: "tuzak" }),
      word("İkinci", { de: "sinngemäß", tr: "anlamca" }),
      word("Üçüncü", { de: "die Entsprechung", tr: "karşılık" }),
      word("Dördüncü", { de: "verwechseln", tr: "karıştırmak" }),
      word("Son", { de: "missverständlich", tr: "yanlış anlaşılır" }),
      { say: [tr("Örnek:"), de("Wörtlich übersetzt wird daraus Unsinn."), tr("Tekrar edin:"), de("Wörtlich übersetzt wird daraus Unsinn")], expect: repeat("Wörtlich übersetzt wird daraus Unsinn") },
      { say: [tr("Sıra sende: 'Bunun Almancada bir karşılığı var.'")], expect: produce("Dafür gibt es im Deutschen eine Entsprechung", [tr("Edat zamirle kaynaşır; isimleşmiş dil adı yönelme hâlinde:"), de("Dafür gibt es im Deutschen eine Entsprechung."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kelimesi kelimesine değil, anlamca çevir.'")], expect: produce("Übersetze nicht wörtlich, sondern sinngemäß", [tr("Olumsuzdan sonra düzeltme sondern ile:"), de("Übersetze nicht wörtlich, sondern sinngemäß."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu iki deyimi karıştırıyorum.'")], expect: produce("Diese beiden Redewendungen verwechsle ich", [tr("Nesne öne alınmış; fiil ikinci sırada:"), de("Diese beiden Redewendungen verwechsle ich."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi anlam sorusu. Şu hüküm doğru mu:"), de("Wörtlich übersetzte Redewendungen ergeben oft keinen Sinn.")], expect: truefalse("Wörtlich übersetzte Redewendungen ergeben oft keinen Sinn.", true, [tr("Doğru. Deyim kelimelerden değil resimden oluşur; resim başka dile taşınmaz ve çeviri anlamsızlaşır.")]) },
      { say: [tr("Son: 'Doğrudan çeviri yanlış anlaşılır.'")], expect: produce("Eine direkte Übersetzung ist missverständlich", [tr("Belirtisiz dişil yalın hâlde sıfat -e ekini alır:"), de("Eine direkte Übersetzung ist missverständlich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir Türkçe deyimin Almanca karşılığını arayacaksın.")] },
    ],
    roleplay: {
      scene: "Almanca konuşan bir arkadaşına bir Türkçe deyimi anlatmaya çalışıyorsun. Önce kelimesi kelimesine söyle, neden anlamsız olduğunu fark et, anlamını açıkla ve birlikte Almanca karşılığını bulun.",
      partner: "meraklı, dillerle ilgilenen ve karşılık önermeye çalışan bir Alman arkadaş",
      opening: "Sag das noch mal wörtlich — ich verstehe wirklich nur Bahnhof. Was soll das denn bedeuten?",
      openingTr: "Bir daha kelimesi kelimesine söyle — gerçekten hiçbir şey anlamadım. Bu ne demek oluyor?",
      goal: "Deyimin gerçek anlamı açıklanmış ve birlikte Almanca bir karşılık bulunmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-idiome-alltag",
    icon: "calendar",
    level: "C1",
    course: "de",
    title: "Ein Tag voller Bilder",
    titleTr: "Deyimli günlük anlatı",
    summary: "Deyimleri dozunda ve bağlamında kullanmayı öğretir.",
    minutes: 12,
    focusId: "Redewendungen",
    vocab: [
      { de: "der Alltag", tr: "günlük hayat" },
      { de: "einstreuen", tr: "serpiştirmek" },
      { de: "dosiert", tr: "dozunda" },
      { de: "unauffällig", tr: "göze çarpmadan" },
      { de: "der Zusammenhang", tr: "bağlam" },
    ],
    patterns: [
      { de: "Streue Redewendungen dosiert ein.", tr: "dozunda kullan" },
      { de: "Zu viele davon wirken gekünstelt.", tr: "fazlası yapmacık durur" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve konusu DOZ. Bir konuşmaya sıkıştırılan on deyim, hiç deyim kullanmamaktan daha kötüdür. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Ölçü şu: bir deyim bağlamına oturduğunda göze çarpmaz. Göze çarpıyorsa fazladır. Bugün bunu bir günlük anlatıda deneyeceğiz. Önce kelimeler.")] },
      word("İlk", { de: "der Alltag", tr: "günlük hayat" }),
      word("İkinci", { de: "einstreuen", tr: "serpiştirmek" }),
      word("Üçüncü", { de: "dosiert", tr: "dozunda" }),
      word("Dördüncü", { de: "unauffällig", tr: "göze çarpmadan" }),
      word("Son", { de: "der Zusammenhang", tr: "bağlam" }),
      { say: [tr("Örnek:"), de("Redewendungen wirken nur im richtigen Zusammenhang."), tr("Tekrar edin:"), de("Redewendungen wirken nur im richtigen Zusammenhang")], expect: repeat("Redewendungen wirken nur im richtigen Zusammenhang") },
      { say: [tr("Sıra sende: 'Deyimleri dozunda serpiştir.'")], expect: produce("Streue Redewendungen dosiert ein", [tr("Emir kipi; ayrılabilen önek en sonda:"), de("Streue Redewendungen dosiert ein."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Fazlası yapmacık durur.'")], expect: produce("Zu viele davon wirken gekünstelt", [tr("Çoğul özne, çoğul fiil:"), de("Zu viele davon wirken gekünstelt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Doğru anda göze çarpmadan işe yararlar.'")], expect: produce("Im richtigen Moment wirken sie unauffällig", [tr("Tümleç başta; fiil ikinci sırada:"), de("Im richtigen Moment wirken sie unauffällig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Zu viele davon wirkt gekünstelt."), tr("cümlesi doğru mu?")], expect: truefalse("Zu viele davon wirkt gekünstelt.", false, [tr("Özne çoğul olduğu için fiil de çoğul çekilir:"), de("Zu viele davon wirken gekünstelt.")]) },
      { say: [tr("Son: 'Günlük hayatta hepsini duyarsın.'")], expect: produce("Im Alltag hörst du sie alle", [tr("Tümleç başta; nesne belirtme hâlinde:"), de("Im Alltag hörst du sie alle."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir gününü anlatacaksın — deyimlerle ama dozunda.")] },
    ],
    roleplay: {
      scene: "Bir arkadaşına yoğun geçen bir gününü anlatıyorsun. Deyimleri dozunda kullan: en fazla üç dört tane, hepsi bağlamına otursun. Karşındaki abarttığını söylerse ölçüyü ayarla.",
      partner: "seni iyi tanıyan, abarttığında takılan bir arkadaş",
      opening: "Erzähl, wie war dein Tag? Und bitte ohne Sprichwörterbuch — sag es einfach, wie es war.",
      openingTr: "Anlat bakalım, günün nasıldı? Ve lütfen deyimler sözlüğü olmadan — nasılsa öyle anlat.",
      goal: "Gün anlatılmış, deyimler dozunda kullanılmış ve karşı taraf anlatımı doğal bulduğunu söylemiş olur.",
      minTurns: 8,
    },
  },
];
