import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * C1 · Modül 10 — Ustalık sahneleri (091–100).
 *
 * Son modül yeni kural getirmiyor; C1 boyunca öğrenilenleri gerçek işlerin
 * içinde yan yana çalıştırıyor. Kriz toplantısı işlev fiili öbeklerini,
 * doğaçlama retoriği, arabuluculuk kelime hassasiyetini, final müzakeresi
 * diplomatik dilek kipini, sınav benzetimi akademik isimleştirmeyi istiyor.
 *
 * 097 bilerek bir rol değişimi: öğrenci ilk kez öğreten tarafa geçiyor ve
 * kendi yolunu birine anlatıyor. 098 ve 100 ise kişisel: iki dilli olmanın
 * ne olduğu ve seviyenin sonunda nerede durulduğu.
 *
 * Kapanış dersi (100) bilerek mecazla yazıldı ve son doğru/yanlış maddesi
 * B2'nin ilk modülünde öğretilen edilgen geçmişi sınıyor — beş yüz dersin
 * kapanışı, öğrenilen ilk kurumsal kurala geri dönüyor.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deC1B10: Lesson[] = [
  {
    id: "de-c1-krisensitzung",
    icon: "job",
    level: "C1",
    course: "de",
    title: "Die Krisensitzung",
    titleTr: "Kriz toplantısı",
    summary: "Kriz anında işlev fiili öbekleriyle hızlı karar dilini öğretir.",
    minutes: 12,
    focusId: "Funktionsverbgefüge",
    vocab: [
      { de: "Maßnahmen ergreifen", tr: "önlem almak" },
      { de: "die Schadensbegrenzung", tr: "hasar sınırlama" },
      { de: "Ruhe bewahren", tr: "sakin kalmak" },
      { de: "die Eskalationsstufe", tr: "tırmanma basamağı" },
      { de: "in Kraft setzen", tr: "yürürlüğe koymak" },
    ],
    patterns: [
      { de: "Wir müssen umgehend Maßnahmen ergreifen.", tr: "derhâl önlem" },
      { de: "Ich setze den Notfallplan in Kraft.", tr: "planı yürürlüğe koyar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Son modüldeyiz ve burada yeni kural yok — öğrendiklerin gerçek işlerin içinde yan yana çalışacak. İlk sahne: kriz toplantısı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Krizde cümleler kısalır ve işlev fiili öbekleri öne çıkar: önlem alınır, hasar sınırlanır, plan yürürlüğe konur. Sabit öbekler burada hız kazandırıyor. Önce kelimeler.")] },
      word("İlk", { de: "Maßnahmen ergreifen", tr: "önlem almak" }),
      word("İkinci", { de: "die Schadensbegrenzung", tr: "hasar sınırlama" }),
      word("Üçüncü", { de: "Ruhe bewahren", tr: "sakin kalmak" }),
      word("Dördüncü", { de: "die Eskalationsstufe", tr: "tırmanma basamağı" }),
      word("Son", { de: "in Kraft setzen", tr: "yürürlüğe koymak" }),
      { say: [tr("Örnek:"), de("Wir müssen umgehend Maßnahmen ergreifen."), tr("Tekrar edin:"), de("Wir müssen umgehend Maßnahmen ergreifen")], expect: repeat("Wir müssen umgehend Maßnahmen ergreifen") },
      { say: [tr("Sıra sende: 'Şimdi hasar sınırlaması yapıyoruz.'")], expect: produce("Jetzt betreiben wir Schadensbegrenzung", [tr("Zarf başta; nesne belirteçsiz:"), de("Jetzt betreiben wir Schadensbegrenzung."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sakin kalmak en önemlisi.'")], expect: produce("Ruhe zu bewahren ist das Wichtigste", [tr("Mastar öbeği özne olarak başta:"), de("Ruhe zu bewahren ist das Wichtigste."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Acil planı yürürlüğe koyuyorum.'")], expect: produce("Ich setze den Notfallplan in Kraft", [tr("Öbek belirteçsiz ve cümlenin sonunda:"), de("Ich setze den Notfallplan in Kraft."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich setze den Notfallplan in die Kraft."), tr("cümlesi doğru mu?")], expect: truefalse("Ich setze den Notfallplan in die Kraft.", false, [tr("Bu öbek belirteç almaz:"), de("Ich setze den Notfallplan in Kraft.")]) },
      { say: [tr("Son bir soru: 'Hangi basamaktayız?'")], expect: produce("Auf welcher Eskalationsstufe sind wir", [tr("Soru öbeği başta, edat yönelme hâlinde:"), de("Auf welcher Eskalationsstufe sind wir?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kriz toplantısı yöneteceksin.")] },
    ],
    roleplay: {
      scene: "Bir aksaklık büyüdü ve kriz toplantısını sen yönetiyorsun. Durumu tek cümlede özetle, hangi önlemlerin alınacağını söyle, kimin ne yapacağını dağıt ve bir sonraki durum değerlendirmesinin saatini ver.",
      partner: "panikleyen, sürekli yeni sorun sayan bir ekip üyesi",
      opening: "Es kommen gerade von überall Meldungen rein. Womit fangen wir an?",
      openingTr: "Her yerden bildirim geliyor. Neyle başlıyoruz?",
      goal: "Durum özetlenmiş, önlemler ve sorumluluklar dağıtılmış ve bir sonraki değerlendirme saati verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-improvisation",
    icon: "idea",
    level: "C1",
    course: "de",
    title: "Der Plan B",
    titleTr: "Doğaçlama çözüm",
    summary: "Plan bozulduğunda ara çözüm önermeyi ve dürüstçe sınırını söylemeyi öğretir.",
    minutes: 12,
    focusId: "Rhetorische-Mittel",
    vocab: [
      { de: "sich behelfen", tr: "idare etmek" },
      { de: "kurzfristig", tr: "kısa vadeli, ani" },
      { de: "notdürftig", tr: "derme çatma" },
      { de: "die Zwischenlösung", tr: "ara çözüm" },
      { de: "tragen", tr: "taşımak, dayanmak" },
    ],
    patterns: [
      { de: "Kurzfristig schlage ich Folgendes vor.", tr: "ani öneri" },
      { de: "Wir behelfen uns mit …", tr: "ara çözümle idare" },
    ],
    lecture: [
      { say: [tr("Merhaba! Plan çöktü ve karar senden bekleniyor. Bugün doğaçlama çözümü konuşacağız. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki şey aynı anda gerekiyor: bir öneri ve o önerinin sınırını dürüstçe söylemek. İkincisi olmazsa ara çözüm kalıcı sanılır. Önce kelimeler.")] },
      word("İlk", { de: "sich behelfen", tr: "idare etmek" }),
      word("İkinci", { de: "kurzfristig", tr: "kısa vadeli" }),
      word("Üçüncü", { de: "notdürftig", tr: "derme çatma" }),
      word("Dördüncü", { de: "die Zwischenlösung", tr: "ara çözüm" }),
      word("Son", { de: "tragen", tr: "taşımak, dayanmak" }),
      { say: [tr("Örnek:"), de("Kurzfristig schlage ich Folgendes vor."), tr("Tekrar edin:"), de("Kurzfristig schlage ich Folgendes vor")], expect: repeat("Kurzfristig schlage ich Folgendes vor") },
      { say: [tr("Sıra sende: 'Bir ara çözümle idare ediyoruz.'")], expect: produce("Wir behelfen uns mit einer Zwischenlösung", [tr("Dönüşlü fiil; edat yönelme hâli ister:"), de("Wir behelfen uns mit einer Zwischenlösung."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu derme çatma ama işe yarıyor.'")], expect: produce("Das ist notdürftig, aber es funktioniert", [tr("İki cümle; ikincisinde özne tekrarlanıyor:"), de("Das ist notdürftig, aber es funktioniert."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'B planı hazır.'")], expect: produce("Plan B steht", [tr("Kısa ve kalıplaşmış:"), de("Plan B steht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wir behelfen uns mit eine Zwischenlösung."), tr("cümlesi doğru mu?")], expect: truefalse("Wir behelfen uns mit eine Zwischenlösung.", false, [tr("Bu edat her zaman yönelme hâli ister:"), de("Wir behelfen uns mit einer Zwischenlösung.")]) },
      { say: [tr("Son bir soru: 'Bu ne kadar dayanır?'")], expect: produce("Wie lange trägt das", [tr("Soru öbeği başta; fiil ikinci sırada:"), de("Wie lange trägt das?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada çöken bir planın yerine çözüm üreteceksin.")] },
    ],
    roleplay: {
      scene: "Etkinlik günü ana çözüm çöktü. Bir ara çözüm öner, sınırını dürüstçe söyle, ne kadar dayanacağını belirt ve kalıcı çözüm için bir tarih ver.",
      partner: "ara çözümü kalıcı sanmaya meyilli, rahatlamak isteyen bir sorumlu",
      opening: "Also läuft es jetzt wieder? Dann können wir das doch so lassen, oder?",
      openingTr: "Yani şimdi yeniden çalışıyor mu? O hâlde böyle bırakabiliriz, değil mi?",
      goal: "Ara çözüm önerilmiş, sınırı ve dayanma süresi dürüstçe söylenmiş ve kalıcı çözüm için tarih verilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-vermittlung",
    icon: "map",
    level: "C1",
    course: "de",
    title: "Der Dolmetscher im Kopf",
    titleTr: "Kültür arası çeviri",
    summary: "Kelimesi kelimesine çevrilemeyeni anlamca aktarmayı öğretir.",
    minutes: 12,
    focusId: "Wortschatz-Nuancen",
    vocab: [
      { de: "vermitteln", tr: "aracılık etmek" },
      { de: "der Kontext", tr: "bağlam" },
      { de: "aufgeladen", tr: "yüklü" },
      { de: "gleichbedeutend", tr: "eş anlamlı" },
      { de: "holprig", tr: "pürüzlü" },
    ],
    patterns: [
      { de: "Das lässt sich nicht wörtlich übersetzen.", tr: "birebir çevrilmez" },
      { de: "Gemeint ist Folgendes: …", tr: "kastedileni açar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün iki dil arasında duracaksın. Ve bu bir çeviri dersi değil — ARACILIK dersi. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bazı ifadeler kültürel olarak yüklüdür: kelimeleri çevrilir ama anlamı taşınmaz. O zaman yapılacak şey kastedileni açmaktır. Önce kelimeler.")] },
      word("İlk", { de: "vermitteln", tr: "aracılık etmek" }),
      word("İkinci", { de: "der Kontext", tr: "bağlam" }),
      word("Üçüncü", { de: "aufgeladen", tr: "yüklü" }),
      word("Dördüncü", { de: "gleichbedeutend", tr: "eş anlamlı" }),
      word("Son", { de: "holprig", tr: "pürüzlü" }),
      { say: [tr("Örnek:"), de("Das lässt sich nicht wörtlich übersetzen."), tr("Tekrar edin:"), de("Das lässt sich nicht wörtlich übersetzen")], expect: repeat("Das lässt sich nicht wörtlich übersetzen") },
      { say: [tr("Sıra sende: 'Kastedilen şu:'")], expect: produce("Gemeint ist Folgendes", [tr("Ortaç başta; isimleşmiş sıfat sonda:"), de("Gemeint ist Folgendes."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu ifade kültürel olarak yüklü.'")], expect: produce("Dieser Ausdruck ist kulturell aufgeladen", [tr("Zarf ortaçtan önce:"), de("Dieser Ausdruck ist kulturell aufgeladen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İkisi eş anlamlı değil.'")], expect: produce("Die beiden sind nicht gleichbedeutend", [tr("Belirtili çoğul özne; sıfat sonda:"), de("Die beiden sind nicht gleichbedeutend."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dieser Ausdruck ist kulturell aufgeladen."), tr("cümlesi doğru mu?")], expect: truefalse("Dieser Ausdruck ist kulturell aufgeladen.", true, [tr("Doğru. Zarf ortaçtan önce duruyor ve durum bildiren edilgen sein ile kurulmuş.")]) },
      { say: [tr("Son: 'Çeviri biraz pürüzlü ama anlaşılıyor.'")], expect: produce("Die Übersetzung ist etwas holprig, aber verständlich", [tr("İki sıfat; ikincisi zıtlık bağlacıyla:"), de("Die Übersetzung ist etwas holprig, aber verständlich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada iki taraf arasında aracılık edeceksin.")] },
    ],
    roleplay: {
      scene: "İki kişi birbirini yanlış anlıyor ve sen aradasın. Kültürel olarak yüklü bir ifadeyi aç, kastedileni her iki tarafa da söyle, yanlış anlamayı gider ve konuşmayı onlara geri ver.",
      partner: "karşı tarafın ifadesini kabalık sanan, alınmış bir muhatap",
      opening: "Er hat gesagt, das sei „nicht schlecht“. Soll ich das jetzt als Lob oder als Kritik verstehen?",
      openingTr: "„Fena değil“ dedi. Bunu şimdi övgü olarak mı eleştiri olarak mı anlamalıyım?",
      goal: "Yüklü ifade açıklanmış, yanlış anlama giderilmiş ve konuşma taraflara geri verilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-grosse-rede",
    icon: "star",
    level: "C1",
    course: "de",
    title: "Die große Rede",
    titleTr: "Büyük konuşma",
    summary: "Bütün retorik araçları tek bir konuşmada birleştirmeyi öğretir.",
    minutes: 12,
    focusId: "Rhetorische-Mittel",
    vocab: [
      { de: "die Rede", tr: "konuşma" },
      { de: "der Höhepunkt", tr: "doruk" },
      { de: "der Bogen", tr: "yay" },
      { de: "packen", tr: "yakalamak, sarmak" },
      { de: "nachhallen", tr: "yankılanmak" },
    ],
    patterns: [
      { de: "Eine gute Rede spannt einen Bogen.", tr: "yay kurar" },
      { de: "Der letzte Satz sollte nachhallen.", tr: "son cümle yankılanır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bütün araçları bir araya getiriyoruz: devrik vurgu, üçleme, metafor, duraklama, imtiyaz. Hepsi tek bir konuşmada. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İskelet üç parçalı: dinleyiciyi yakalayan bir açılış, sona doğru gelen bir doruk ve yankılanan bir son cümle. Önce kelimeler.")] },
      word("İlk", { de: "die Rede", tr: "konuşma" }),
      word("İkinci", { de: "der Höhepunkt", tr: "doruk" }),
      word("Üçüncü", { de: "der Bogen", tr: "yay" }),
      word("Dördüncü", { de: "packen", tr: "yakalamak, sarmak" }),
      word("Son", { de: "nachhallen", tr: "yankılanmak" }),
      { say: [tr("Örnek:"), de("Eine gute Rede spannt einen Bogen."), tr("Tekrar edin:"), de("Eine gute Rede spannt einen Bogen")], expect: repeat("Eine gute Rede spannt einen Bogen") },
      { say: [tr("Sıra sende: 'İlk cümle dinleyiciyi yakalamalı.'")], expect: produce("Der erste Satz muss das Publikum packen", [tr("Nesne belirtme hâlinde; mastar sonda:"), de("Der erste Satz muss das Publikum packen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Doruk sona doğru gelir.'")], expect: produce("Der Höhepunkt kommt gegen Ende", [tr("Edat belirtme hâli ister; belirteçsiz isim:"), de("Der Höhepunkt kommt gegen Ende."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sessizlik de bir araçtır.'")], expect: produce("Auch die Stille ist ein Mittel", [tr("Zarf başta, özne ondan sonra:"), de("Auch die Stille ist ein Mittel."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der erste Satz muss das Publikum zu packen."), tr("cümlesi doğru mu?")], expect: truefalse("Der erste Satz muss das Publikum zu packen.", false, [tr("Kip fiilinden sonra mastar zu almaz:"), de("Der erste Satz muss das Publikum packen.")]) },
      { say: [tr("Son: 'Son cümle yankılanmalı.'")], expect: produce("Der letzte Satz sollte nachhallen", [tr("Ayrılabilen mastar sonda:"), de("Der letzte Satz sollte nachhallen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada büyük bir konuşma yapacaksın.")] },
    ],
    roleplay: {
      scene: "Önemli bir vesileyle konuşma yapacaksın. Dinleyiciyi yakalayan bir açılış kur, üç noktayı sırala, bir imge kullan, bir itirazı önden karşıla ve yankılanan bir cümleyle bitir.",
      partner: "konuşmanı önceden dinleyip geri bildirim veren bir arkadaş",
      opening: "Probier den Anfang mal an mir aus — wie fängst du an?",
      openingTr: "Girişi bir bende dene — nasıl başlıyorsun?",
      goal: "Açılış, üç nokta, bir imge ve yankılanan bir kapanış kurulmuş; arkadaş geri bildirimini vermiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-verhandlungsfinale",
    icon: "handshake",
    level: "C1",
    course: "de",
    title: "Alles oder nichts",
    titleTr: "Final müzakeresi",
    summary: "Müzakereyi diplomatik dilek kipiyle kapatmayı öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II-Diplomatie",
    vocab: [
      { de: "der Abschluss", tr: "kapanış, anlaşma" },
      { de: "unterschriftsreif", tr: "imzaya hazır" },
      { de: "nachbessern", tr: "iyileştirme yapmak" },
      { de: "endgültig", tr: "nihai" },
      { de: "der Handschlag", tr: "el sıkışma" },
    ],
    patterns: [
      { de: "Unser letztes Wort wäre …", tr: "nihai teklif, yumuşak" },
      { de: "Kämen Sie uns entgegen, könnten wir …", tr: "koşullu kapanış" },
    ],
    lecture: [
      { say: [tr("Merhaba! Müzakerenin son turundasın. Burada dilin işi tek: kapıyı kapatmadan son sözü söylemek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki kalıp yeter. Biri nihai teklifi dilek kipiyle yumuşatır, öteki koşullu bir kapanış önerir — ikisi de karşı tarafa çıkış bırakır. Önce kelimeler.")] },
      word("İlk", { de: "der Abschluss", tr: "kapanış, anlaşma" }),
      word("İkinci", { de: "unterschriftsreif", tr: "imzaya hazır" }),
      word("Üçüncü", { de: "nachbessern", tr: "iyileştirme yapmak" }),
      word("Dördüncü", { de: "endgültig", tr: "nihai" }),
      word("Son", { de: "der Handschlag", tr: "el sıkışma" }),
      { say: [tr("Örnek:"), de("Unser letztes Wort wäre vierzig."), tr("Tekrar edin:"), de("Unser letztes Wort wäre vierzig")], expect: repeat("Unser letztes Wort wäre vierzig") },
      { say: [tr("Sıra sende: 'Bize biraz yaklaşırsanız bugün bitirebiliriz.'")], expect: produce("Kämen Sie uns entgegen, könnten wir heute abschließen", [tr("Bağlaçsız koşul dilek kipiyle; sonuç da dilek kipinde:"), de("Kämen Sie uns entgegen, könnten wir heute abschließen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sözleşme imzaya hazır.'")], expect: produce("Der Vertrag ist unterschriftsreif", [tr("Kısa hüküm cümlesi:"), de("Der Vertrag ist unterschriftsreif."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bir noktada iyileştirme yapabiliriz.'")], expect: produce("An einem Punkt können wir nachbessern", [tr("Tümleç başta; ayrılabilen mastar sonda:"), de("An einem Punkt können wir nachbessern."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das ist unser endgültige Angebot."), tr("cümlesi doğru mu?")], expect: truefalse("Das ist unser endgültige Angebot.", false, [tr("İyelik sıfatından sonra nötr isimde sıfat -es ekini alır:"), de("Das ist unser endgültiges Angebot.")]) },
      { say: [tr("Son: 'Bu bizim nihai teklifimiz.'")], expect: produce("Das ist unser endgültiges Angebot", [tr("Nötr isimde sıfat -es ekiyle:"), de("Das ist unser endgültiges Angebot."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir müzakereyi kapatacaksın.")] },
    ],
    roleplay: {
      scene: "Uzun bir müzakerenin son turundasın. Nihai teklifini yumuşak biçimde söyle, bir noktada iyileştirme öner, karşı tarafın son isteğini karşıla ve anlaşmayı bir el sıkışmayla kapat — ya da nazikçe bitir.",
      partner: "son anda bir şey daha isteyen, sert ama adil bir müzakereci",
      opening: "Eine Sache noch, dann unterschreibe ich: Kämen Sie mir bei der Laufzeit entgegen?",
      openingTr: "Bir şey daha, sonra imzalıyorum: Sürede bana biraz yaklaşır mısınız?",
      goal: "Nihai teklif söylenmiş, son istek karşılanmış ve müzakere anlaşmayla ya da nazik bir kapanışla bitirilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-pruefungssimulation",
    icon: "school",
    level: "C1",
    course: "de",
    title: "Die C1-Simulation",
    titleTr: "Sınav benzetimi",
    summary: "Sınav formatını ve değerlendirme ölçütlerini akademik dille konuşmayı öğretir.",
    minutes: 12,
    focusId: "Nominalstil",
    vocab: [
      { de: "die Simulation", tr: "benzetim" },
      { de: "der Prüfling", tr: "sınava giren" },
      { de: "die Anforderung", tr: "gereklilik" },
      { de: "die Bewertung", tr: "değerlendirme" },
      { de: "bestehen", tr: "geçmek" },
    ],
    patterns: [
      { de: "Vom Prüfling werden … verlangt.", tr: "kişisiz gereklilik" },
      { de: "Zum Bestehen sind … Punkte nötig.", tr: "geçme eşiği" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sınavın kendisini konuşacağız: ne isteniyor, nasıl değerlendiriliyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sınav yönergeleri kişisiz yazılır — 'sizden isteniyor' değil, 'sınava girenden isteniyor'. Bu dili tanımak bile puan kazandırır. Önce kelimeler.")] },
      word("İlk", { de: "die Simulation", tr: "benzetim" }),
      word("İkinci", { de: "der Prüfling", tr: "sınava giren" }),
      word("Üçüncü", { de: "die Anforderung", tr: "gereklilik" }),
      word("Dördüncü", { de: "die Bewertung", tr: "değerlendirme" }),
      word("Son", { de: "bestehen", tr: "geçmek" }),
      { say: [tr("Örnek:"), de("Der Vortrag wird anschließend bewertet."), tr("Tekrar edin:"), de("Der Vortrag wird anschließend bewertet")], expect: repeat("Der Vortrag wird anschließend bewertet") },
      { say: [tr("Sıra sende: 'Sınava girenden üç şey isteniyor.'")], expect: produce("Vom Prüfling werden drei Dinge verlangt", [tr("Fail von ile; çoğul edilgen:"), de("Vom Prüfling werden drei Dinge verlangt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Değerlendirme ölçütleri önceden açıklanıyor.'")], expect: produce("Die Kriterien der Bewertung werden vorab genannt", [tr("Tamlama artı edilgen; ortaç sonda:"), de("Die Kriterien der Bewertung werden vorab genannt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Geçmek için altmış puan gerekiyor.'")], expect: produce("Zum Bestehen sind sechzig Punkte nötig", [tr("İsimleşmiş mastar yönelme hâlinde:"), de("Zum Bestehen sind sechzig Punkte nötig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Vom Prüfling werden drei Dinge verlangt."), tr("cümlesi doğru mu?")], expect: truefalse("Vom Prüfling werden drei Dinge verlangt.", true, [tr("Doğru. Fail von edatıyla yönelme hâlinde, özne çoğul olduğu için werden çoğul ve ortaç sonda.")]) },
      { say: [tr("Son: 'Gereklilikleri biliyorum.'")], expect: produce("Die Anforderungen kenne ich", [tr("Nesne öne alınmış; fiil ikinci sırada:"), de("Die Anforderungen kenne ich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir sınav benzetimine gireceksin.")] },
    ],
    roleplay: {
      scene: "Bir C1 sınav benzetimindesin: kısa bir sunum yap, gelen iki soruyu cevapla ve sonunda söylediklerini bir cümlede topla. Sınav görevlisi ölçütleri hatırlatabilir.",
      partner: "tarafsız, süreyi tutan ve ölçütleri hatırlatan bir sınav görevlisi",
      opening: "Sie haben zwei Minuten Vortrag, dann zwei Rückfragen. Ihr Thema, bitte?",
      openingTr: "İki dakika sunum, ardından iki soru. Konunuz lütfen?",
      goal: "Kısa bir sunum yapılmış, iki soru cevaplanmış ve söylenenler tek cümlede toplanmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-mentoring-c1",
    icon: "feelings",
    level: "C1",
    course: "de",
    title: "Jetzt hilfst du",
    titleTr: "Yeni öğrenciye akıl",
    summary: "Kendi öğrenme yolunu bir başkasına aktarmayı öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-II",
    vocab: [
      { de: "weitergeben", tr: "aktarmak" },
      { de: "der Rat", tr: "öğüt" },
      { de: "die Geduld", tr: "sabır" },
      { de: "ermutigen", tr: "cesaretlendirmek" },
      { de: "der Rückschlag", tr: "geri tepme" },
    ],
    patterns: [
      { de: "An deiner Stelle würde ich …", tr: "öğüdü dilek kipiyle" },
      { de: "Was mir geholfen hat, war …", tr: "kendi deneyimi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün rol değişiyor: ilk kez sen öğreteceksin. Yeni başlayan birine kendi yolunu anlatacaksın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İyi öğüdün iki kuralı var: dilek kipiyle verilir (emir değil öneri olsun) ve kendi deneyiminden çıkar (genel doğru değil). Önce kelimeler.")] },
      word("İlk", { de: "weitergeben", tr: "aktarmak" }),
      word("İkinci", { de: "der Rat", tr: "öğüt" }),
      word("Üçüncü", { de: "die Geduld", tr: "sabır" }),
      word("Dördüncü", { de: "ermutigen", tr: "cesaretlendirmek" }),
      word("Son", { de: "der Rückschlag", tr: "geri tepme" }),
      { say: [tr("Örnek:"), de("An deiner Stelle würde ich klein anfangen."), tr("Tekrar edin:"), de("An deiner Stelle würde ich klein anfangen")], expect: repeat("An deiner Stelle würde ich klein anfangen") },
      { say: [tr("Sıra sende: 'Bana yardımcı olan şey şuydu:'")], expect: produce("Was mir geholfen hat, war Folgendes", [tr("Yan cümle özne olarak başta; kişi yönelme hâlinde:"), de("Was mir geholfen hat, war Folgendes."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Geri tepmeler bu işin parçası.'")], expect: produce("Rückschläge gehören dazu", [tr("Belirteçsiz çoğul özne; edat zamirle kaynaşmış:"), de("Rückschläge gehören dazu."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Burada en önemli şey sabır.'")], expect: produce("Geduld ist hier das Wichtigste", [tr("Belirteçsiz özne; isimleşmiş üstünlük biçimi:"), de("Geduld ist hier das Wichtigste."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("An deiner Stelle würde ich klein angefangen."), tr("cümlesi doğru mu?")], expect: truefalse("An deiner Stelle würde ich klein angefangen.", false, [tr("Bu yardımcı fiilden sonra ortaç değil mastar gelir:"), de("An deiner Stelle würde ich klein anfangen.")]) },
      { say: [tr("Son: 'Seni cesaretlendirmek istiyorum.'")], expect: produce("Ich möchte dich ermutigen", [tr("Nesne belirtme hâlinde; mastar sonda:"), de("Ich möchte dich ermutigen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada yeni başlayan birine yol göstereceksin.")] },
    ],
    roleplay: {
      scene: "Almanca öğrenmeye yeni başlayan biri senden tavsiye istiyor. Kendi yolunu anlat, işe yarayan ve yaramayan şeyi ayır, gerçekçi bir beklenti kur ve onu somut bir ilk adımla gönder.",
      partner: "hevesli ama sabırsız, 'ne kadar sürer' diye soran yeni bir öğrenci",
      opening: "Wie lange hat das bei dir gedauert? Und sag ehrlich — was hätte ich mir sparen können?",
      openingTr: "Sende ne kadar sürdü? Ve dürüst söyle — neyi yapmasam da olurdu?",
      goal: "Kendi yol anlatılmış, işe yarayan ile yaramayan ayrılmış ve yeni öğrenciye somut bir ilk adım verilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-zweisprachig-leben",
    icon: "culture",
    level: "C1",
    course: "de",
    title: "In zwei Sprachen zu Hause",
    titleTr: "İki dilli kimlik",
    summary: "İki dilli olmayı irreal kıyaslarla anlatmayı öğretir.",
    minutes: 12,
    focusId: "Als-ob",
    vocab: [
      { de: "zweisprachig", tr: "iki dilli" },
      { de: "die Stimme", tr: "ses" },
      { de: "der Reichtum", tr: "zenginlik" },
      { de: "der Riss", tr: "yarık" },
      { de: "wechseln", tr: "geçiş yapmak" },
    ],
    patterns: [
      { de: "Es ist, als hätte ich zwei Stimmen.", tr: "irreal kıyas" },
      { de: "Das ist ein Reichtum, kein Riss.", tr: "yargıyı çevirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kişisel bir ders: iki dilde yaşamak. Ve bunu anlatmak için irreal kıyas gerekiyor, çünkü duygu olguyla anlatılmıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de dikkat edeceğin nokta var: bu yapıda aktarım kipi değil DİLEK kipi kullanılır. İkisi karışırsa cümle bir iddiaya döner. Önce kelimeler.")] },
      word("İlk", { de: "zweisprachig", tr: "iki dilli" }),
      word("İkinci", { de: "die Stimme", tr: "ses" }),
      word("Üçüncü", { de: "der Reichtum", tr: "zenginlik" }),
      word("Dördüncü", { de: "der Riss", tr: "yarık" }),
      word("Son", { de: "wechseln", tr: "geçiş yapmak" }),
      { say: [tr("Örnek:"), de("Es ist, als hätte ich zwei Stimmen."), tr("Tekrar edin:"), de("Es ist, als hätte ich zwei Stimmen")], expect: repeat("Es ist, als hätte ich zwei Stimmen") },
      { say: [tr("Sıra sende: 'Dile göre biraz başka biri oluyorum.'")], expect: produce("Je nach Sprache bin ich ein wenig anders", [tr("Kalıplaşmış ifade başta; fiil ikinci sırada:"), de("Je nach Sprache bin ich ein wenig anders."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu bir zenginlik, bir yarık değil.'")], expect: produce("Das ist ein Reichtum, kein Riss", [tr("İki isim; ikincisinde olumsuz belirteç:"), de("Das ist ein Reichtum, kein Riss."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Cümlenin ortasında dil değiştiriyorum.'")], expect: produce("Mitten im Satz wechsle ich die Sprache", [tr("Tümleç başta; nesne belirtme hâlinde:"), de("Mitten im Satz wechsle ich die Sprache."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es ist, als habe ich zwei Stimmen."), tr("cümlesi doğru mu?")], expect: truefalse("Es ist, als habe ich zwei Stimmen.", false, [tr("İrreal kıyas dilek kipi ister; aktarım kipi burada yanlıştır:"), de("Es ist, als hätte ich zwei Stimmen.")]) },
      { say: [tr("Son: 'Sanki iki evim varmış gibi.'")], expect: produce("Es ist, als hätte ich zwei Zuhause", [tr("Bağlaçsız irreal kıyas; fiil hemen als'ın arkasında:"), de("Es ist, als hätte ich zwei Zuhause."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada iki dilli hayatını anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Biri sana iki dilde yaşamanın nasıl bir şey olduğunu soruyor. Dile göre nasıl değiştiğini anlat, kayıp ve kazanç yanını ayır, bir yanlış anlamayı düzelt ve bunun bir zenginlik olduğunu gerekçelendir.",
      partner: "iki dilliliği bir eksiklik sanan, iyi niyetli bir tanıdık",
      opening: "Fühlt man sich da nicht ein bisschen zerrissen — so zwischen zwei Sprachen?",
      openingTr: "İnsan orada biraz parçalanmış hissetmiyor mu — iki dil arasında öyle?",
      goal: "İki dilliliğin nasıl hissettirdiği anlatılmış, kayıp ile kazanç ayrılmış ve bunun bir zenginlik olduğu gerekçelendirilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-sprachwandel",
    icon: "book",
    level: "C1",
    course: "de",
    title: "Sprache lebt",
    titleTr: "Dilin değişimi",
    summary: "Dil değişimini çöküş söyleminden ayırarak tartışmayı öğretir.",
    minutes: 12,
    focusId: "Wortschatz-Nuancen",
    vocab: [
      { de: "der Sprachwandel", tr: "dil değişimi" },
      { de: "der Anglizismus", tr: "İngilizce alıntı" },
      { de: "die Jugendsprache", tr: "gençlik dili" },
      { de: "der Verfall", tr: "çöküş" },
      { de: "die Norm", tr: "norm" },
    ],
    patterns: [
      { de: "Wandel ist kein Verfall.", tr: "değişim çöküş değil" },
      { de: "Die Norm folgt dem Gebrauch.", tr: "norm kullanımı izler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Sondan bir önceki ders ve konusu tartışmalı: dil bozuluyor mu? Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dilbilimin cevabı net: norm kullanımı izler, tersi değil. Yani bugünün 'yanlış'ı yarının kuralı olabilir — ve bu bir çöküş değil bir hareket. Önce kelimeler.")] },
      word("İlk", { de: "der Sprachwandel", tr: "dil değişimi" }),
      word("İkinci", { de: "der Anglizismus", tr: "İngilizce alıntı" }),
      word("Üçüncü", { de: "die Jugendsprache", tr: "gençlik dili" }),
      word("Dördüncü", { de: "der Verfall", tr: "çöküş" }),
      word("Son", { de: "die Norm", tr: "norm" }),
      { say: [tr("Örnek:"), de("Sprache lebt — Wandel ist kein Verfall."), tr("Tekrar edin:"), de("Sprache lebt, Wandel ist kein Verfall")], expect: repeat("Sprache lebt, Wandel ist kein Verfall") },
      { say: [tr("Sıra sende: 'Yabancı kelimeler her zaman vardı.'")], expect: produce("Fremdwörter gab es immer", [tr("Nesne öne alınmış; kalıplaşmış fiil ikinci sırada:"), de("Fremdwörter gab es immer."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Norm kullanımı izler, tersi değil.'")], expect: produce("Die Norm folgt dem Gebrauch, nicht umgekehrt", [tr("Bu fiil yönelme hâli ister:"), de("Die Norm folgt dem Gebrauch, nicht umgekehrt."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Gençlik dili yarın standart olabilir.'")], expect: produce("Jugendsprache kann morgen Standard sein", [tr("Belirteçsiz özne; mastar sonda:"), de("Jugendsprache kann morgen Standard sein."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Norm folgt dem Gebrauch, nicht umgekehrt."), tr("cümlesi doğru mu?")], expect: truefalse("Die Norm folgt dem Gebrauch, nicht umgekehrt.", true, [tr("Doğru. Fiil yönelme hâli istiyor ve cümle dilbilimsel olarak da yerinde: kural kullanımdan sonra gelir.")]) },
      { say: [tr("Son: 'Buna çöküş demezdim.'")], expect: produce("Einen Verfall würde ich das nicht nennen", [tr("Nesne öne alınmış; dilek kipi ikinci sırada:"), de("Einen Verfall würde ich das nicht nennen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada dilin değişimini tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığın 'dil bozuluyor' diyor. Değişim ile çöküşü ayır, tarihsel bir örnek ver, onun haklı olduğu noktayı kabul et ve ortak bir ölçüt önerin.",
      partner: "yabancı kelimelerden rahatsız, 'eskiden daha düzgündü' diyen bir tanıdık",
      opening: "Hören Sie sich das doch an — kein Satz mehr ohne Englisch. Ist das nicht ein Verfall?",
      openingTr: "Şunu bir dinleyin — İngilizcesiz cümle kalmadı. Bu bir çöküş değil mi?",
      goal: "Değişim ile çöküş ayrılmış, tarihsel bir örnek verilmiş ve ortak bir ölçüt önerilmiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-finale",
    icon: "mountain",
    level: "C1",
    course: "de",
    title: "Angekommen — und weiter",
    titleTr: "C1 finali",
    summary: "Kat edilen yolu mecazlarla değerlendirmeyi öğretir ve seviyeyi kapatır.",
    minutes: 12,
    focusId: "Metaphern",
    vocab: [
      { de: "der Gipfel", tr: "zirve" },
      { de: "das Zuhause", tr: "yuva" },
      { de: "weitergehen", tr: "devam etmek" },
      { de: "die Mühe", tr: "emek" },
      { de: "angekommen", tr: "varmış" },
    ],
    patterns: [
      { de: "Der Gipfel ist erreicht, aber der Weg geht weiter.", tr: "kapanış mecazı" },
      { de: "Diese Sprache ist ein Zuhause.", tr: "dil bir yuva" },
    ],
    lecture: [
      { say: [tr("Merhaba. Son ders. Beş yüz dersin sonundasın ve bugün yeni bir kural yok — sadece bir muhasebe. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir mecazla kapatacağız, çünkü bu yol gerçekten bir tırmanışa benziyor: zirve görünüyor ama yol bitmiyor. Önce kelimeler.")] },
      word("İlk", { de: "der Gipfel", tr: "zirve" }),
      word("İkinci", { de: "das Zuhause", tr: "yuva" }),
      word("Üçüncü", { de: "weitergehen", tr: "devam etmek" }),
      word("Dördüncü", { de: "die Mühe", tr: "emek" }),
      word("Son", { de: "angekommen", tr: "varmış" }),
      { say: [tr("Örnek:"), de("Der Gipfel ist erreicht, aber der Weg geht weiter."), tr("Tekrar edin:"), de("Der Gipfel ist erreicht, aber der Weg geht weiter")], expect: repeat("Der Gipfel ist erreicht, aber der Weg geht weiter") },
      { say: [tr("Sıra sende: 'Bu dil artık bir yuva.'")], expect: produce("Diese Sprache ist inzwischen ein Zuhause", [tr("Zarf ortada; belirtisiz nötr isim:"), de("Diese Sprache ist inzwischen ein Zuhause."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Emek boşa gitmedi.'")], expect: produce("Die Mühe war nicht umsonst", [tr("Kısa hüküm cümlesi; olumsuzluk zarftan önce:"), de("Die Mühe war nicht umsonst."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Vardım ama duracak değilim.'")], expect: produce("Ich bin angekommen, aber stehen bleibe ich nicht", [tr("İkinci cümlede mastar öne alınmış:"), de("Ich bin angekommen, aber stehen bleibe ich nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Ve son doğru/yanlış — B2'nin ilk modülünde öğrendiğin kural:"), de("Ein langer Weg ist zurückgelegt geworden."), tr("cümlesi doğru mu?")], expect: truefalse("Ein langer Weg ist zurückgelegt geworden.", false, [tr("Edilgen geçmişte yardımcı fiil kısalır — beş yüz ders önce başlayan yolun ilk kurumsal kuralı:"), de("Ein langer Weg ist zurückgelegt worden.")]) },
      { say: [tr("Son cümlen: 'Yol devam ediyor.'")], expect: produce("Der Weg geht weiter", [tr("Ayrılabilen fiilin öneki sonda:"), de("Der Weg geht weiter."), tr("Tekrar dene.")]) },
      { say: [tr("C1'i bitirdin. Konuşmada bu yolu son kez birlikte değerlendireceksin — ve bu sefer sen anlatacaksın.")] },
    ],
    roleplay: {
      scene: "Öğretmeninle C1'in sonunda son bir değerlendirme yapıyorsun: yol nasıl geçti, hangi an dönüm noktasıydı, artık neyi yapabiliyorsun, dil senin için ne oldu ve bundan sonra ne var.",
      partner: "seni baştan beri izlemiş, dürüst ve sıcak bir öğretmen",
      opening: "Fünfhundert Lektionen. Bevor wir schließen: Welcher Moment war für Sie der Wendepunkt?",
      openingTr: "Beş yüz ders. Kapatmadan önce: Sizin için dönüm noktası hangi andı?",
      goal: "Dönüm noktası anlatılmış, artık yapılabilenler sayılmış, dilin ne anlama geldiği söylenmiş ve bundan sonraki hedef belirtilmiş olur.",
      minTurns: 9,
    },
  },
];
