import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * C1 · Modül 8 — Toplumsal tartışma (071–080).
 *
 * Bu modül seviyenin en zor işini yapıyor: tartışmalı bir konuda TARAF
 * olmadan taraf tutmak. Araçlar üç grupta toplanıyor ve üçü de burada bir
 * arada çalışıyor:
 *
 *   - İrreal kıyas (`als ob` + dilek kipi): gerçek olmayanı işaretlemek.
 *     "Er tut, als wäre nichts geschehen" cümlesi bir gözlem değil bir
 *     yargıdır ve yargı olduğunu dilin kendisi söyler.
 *   - İmtiyaz bağlaçları (ungeachtet, nichtsdestotrotz, dessen ungeachtet):
 *     karşı tarafa hak verip pozisyonu korumak.
 *   - İrreal koşul (Konjunktiv II): olmamış bir geçmişi ya da kurulmamış bir
 *     geleceği tartışabilmek — "Hätte man früher investiert…".
 *
 * Konular bilerek yakıcı: göç, iklim, eğitim, yapay zekâ etiği, kuşak
 * sözleşmesi, ifade özgürlüğü. Ama sahneler tartışmayı kazanmayı değil
 * AYRIŞTIRMAYI hedefliyor — her rol yapmanın amacı ortak bir ölçüt ya da
 * kabul edilen bir sınır.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deC1B08: Lesson[] = [
  {
    id: "de-c1-als-ob-c1",
    icon: "feelings",
    level: "C1",
    course: "de",
    title: "Als wäre nichts geschehen",
    titleTr: "İrreal kıyas ustalığı",
    summary: "Gerçek olmayan benzetmeyi bağlaçlı ve bağlaçsız biçimde kurmayı öğretir.",
    minutes: 14,
    focusId: "Als-ob",
    vocab: [
      { de: "verdrängen", tr: "bastırmak" },
      { de: "die Illusion", tr: "yanılsama" },
      { de: "aufrechterhalten", tr: "sürdürmek, ayakta tutmak" },
      { de: "die Normalität", tr: "normallik" },
      { de: "der Bruch", tr: "kırılma, kopuş" },
      { de: "die Identifikation", tr: "özdeşleşme" },
      { de: "die Emotion", tr: "duygu" },
      { de: "die Unsicherheit", tr: "belirsizlik" },
    ],
    patterns: [
      { de: "Er tut, als wäre nichts geschehen.", tr: "bağlaçsız: fiil hemen sonra" },
      { de: "Er tut so, als ob nichts geschehen wäre.", tr: "bağlaçlı: fiil sonda" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: toplumsal tartışma. Ve ilk araç, gerçek olmayanı işaretleyen yapı. B2'de girmiştin; burada iki biçimini birden kuracaksın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki biçim var ve dizilimleri farklı:"), de("als ob nichts geschehen wäre"), tr("— fiil sonda;"), de("als wäre nichts geschehen"), tr("— fiil hemen bağlacın arkasında. İkisi de doğru, ikincisi daha edebî.")] },
      { say: [tr("Ortak nokta: ikisinde de dilek kipi zorunlu, çünkü söylenen gerçek değil. Önce kelimeler.")] },
      word("İlk", { de: "verdrängen", tr: "bastırmak" }),
      word("İkinci", { de: "die Illusion", tr: "yanılsama" }),
      word("Üçüncü", { de: "aufrechterhalten", tr: "sürdürmek" }),
      word("Dördüncü", { de: "die Normalität", tr: "normallik" }),
      word("Beşinci", { de: "der Bruch", tr: "kırılma, kopuş" }),
      word("Altıncı", { de: "die Identifikation", tr: "özdeşleşme" }),
      word("Yedinci", { de: "die Emotion", tr: "duygu" }),
      word("Son", { de: "die Unsicherheit", tr: "belirsizlik" }),
      { say: [tr("Örnek:"), de("Er tut, als wäre nichts geschehen."), tr("Tekrar edin:"), de("Er tut, als wäre nichts geschehen")], expect: repeat("Er tut, als wäre nichts geschehen") },
      { say: [tr("Sıra sende: 'Normallik görüntüsünü sürdürüyorlar.'")], expect: produce("Sie halten den Anschein von Normalität aufrecht", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Sie halten den Anschein von Normalität aufrecht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi bağlaçsız biçimle: 'Sanki hiçbir kopuş yaşanmamış gibi.'")], expect: produce("So, als hätte es nie einen Bruch gegeben", [tr("Bağlaçsız biçimde fiil hemen als'ın arkasına gelir:"), de("So, als hätte es nie einen Bruch gegeben."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bastırmak çözmek değildir.'")], expect: produce("Verdrängen ist nicht dasselbe wie Lösen", [tr("İki isimleşmiş mastar; karşılaştırma wie ile:"), de("Verdrängen ist nicht dasselbe wie Lösen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("So, als hat es nie einen Bruch gegeben."), tr("cümlesi doğru mu?")], expect: truefalse("So, als hat es nie einen Bruch gegeben.", false, [tr("Bu yapı gerçek olmayanı anlatır, o yüzden dilek kipi ister:"), de("So, als hätte es nie einen Bruch gegeben.")]) },
      { say: [tr("Son: 'Bu bir yanılsama.'")], expect: produce("Das ist eine Illusion", [tr("Kısa hüküm cümlesi:"), de("Das ist eine Illusion."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada görmezden gelinen bir meseleyi açacaksın.")] },
    ],
    roleplay: {
      scene: "Bir ekipte herkesin bildiği ama kimsenin konuşmadığı bir mesele var. Durumu adlandır, görmezden gelmenin ne yaptığını söyle, karşı tarafın rahatsızlığını kabul et ve konuşmayı bir adıma bağla.",
      partner: "konuyu açmaktan rahatsız olan, 'her şey yolunda' demeyi tercih eden bir meslektaş",
      opening: "Muss das jetzt wirklich sein? Wir kommen doch ganz gut zurecht, oder?",
      openingTr: "Bunun şimdi olması şart mı? Gayet iyi idare ediyoruz, değil mi?",
      goal: "Konuşulmayan mesele adlandırılmış, görmezden gelmenin sonucu söylenmiş ve somut bir adım kararlaştırılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-konzessiv",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Wenngleich und dennoch",
    titleTr: "İmtiyaz bağlaçları",
    summary: "Resmî imtiyaz bağlaçlarını doğru hâl ve dizilimle kullanmayı öğretir.",
    minutes: 14,
    focusId: "Konzessive-Konnektoren",
    vocab: [
      { de: "ungeachtet", tr: "…-e bakılmaksızın" },
      { de: "nichtsdestotrotz", tr: "yine de" },
      { de: "einschränken", tr: "sınırlamak" },
      { de: "abschwächen", tr: "yumuşatmak" },
      { de: "die Gegenposition", tr: "karşı görüş" },
      { de: "tolerieren", tr: "hoş görmek" },
      { de: "beanspruchen", tr: "talep etmek, gerektirmek" },
      { de: "die Übereinkunft", tr: "mutabakat" },
    ],
    patterns: [
      { de: "ungeachtet + Genitiv", tr: "…-e bakılmaksızın" },
      { de: "Dessen ungeachtet …", tr: "buna rağmen" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün tartışmanın en resmî araçları: imtiyaz bağlaçları. Karşı tarafa hak verip pozisyonunu koruyorlar. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Birincisi tamlama hâli ister ve bu çok atlanır. İkincisi ise ana cümlenin başında durur ve fiil hemen arkasına geçer. Önce kelimeler.")] },
      word("İlk", { de: "ungeachtet", tr: "…-e bakılmaksızın" }),
      word("İkinci", { de: "nichtsdestotrotz", tr: "yine de" }),
      word("Üçüncü", { de: "einschränken", tr: "sınırlamak" }),
      word("Dördüncü", { de: "abschwächen", tr: "yumuşatmak" }),
      word("Beşinci", { de: "die Gegenposition", tr: "karşı görüş" }),
      word("Altıncı", { de: "tolerieren", tr: "hoş görmek" }),
      word("Yedinci", { de: "beanspruchen", tr: "talep etmek, gerektirmek" }),
      word("Son", { de: "die Übereinkunft", tr: "mutabakat" }),
      { say: [tr("Örnek:"), de("Ungeachtet der Kosten wurde das Projekt bewilligt."), tr("Tekrar edin:"), de("Ungeachtet der Kosten wurde das Projekt bewilligt")], expect: repeat("Ungeachtet der Kosten wurde das Projekt bewilligt") },
      { say: [tr("Sıra sende: 'Buna rağmen karar değişmedi.'")], expect: produce("Dessen ungeachtet blieb die Entscheidung bestehen", [tr("Kalıplaşmış öbek başta; ayrılabilen fiil sonda:"), de("Dessen ungeachtet blieb die Entscheidung bestehen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yine de bir itirazım var.'")], expect: produce("Nichtsdestotrotz habe ich einen Einwand", [tr("Bağlaç ilk öğe; fiil ikinci sırada:"), de("Nichtsdestotrotz habe ich einen Einwand."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İfadeyi biraz yumuşatmak isterim.'")], expect: produce("Die Aussage möchte ich etwas abschwächen", [tr("Nesne öne alınmış; ayrılabilen mastar sonda:"), de("Die Aussage möchte ich etwas abschwächen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ungeachtet die Kosten wurde das Projekt bewilligt."), tr("cümlesi doğru mu?")], expect: truefalse("Ungeachtet die Kosten wurde das Projekt bewilligt.", false, [tr("Bu edat tamlama hâli ister:"), de("Ungeachtet der Kosten wurde das Projekt bewilligt.")]) },
      { say: [tr("Son: 'Karşı görüşü de duymak gerekir.'")], expect: produce("Die Gegenposition muss man auch hören", [tr("Nesne öne alınmış; mastar sonda:"), de("Die Gegenposition muss man auch hören."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kararı imtiyaz vererek savunacaksın.")] },
    ],
    roleplay: {
      scene: "Tartışmalı bir kararı savunuyorsun. Karşı tarafın maliyet itirazını kabul et, buna rağmen kararın neden doğru olduğunu söyle, kendi ifadeni bir yerde yumuşat ve bir sınır çiz.",
      partner: "maliyeti öne çıkaran, sayılarla konuşan bir muhalif",
      opening: "Die Kosten sind das Dreifache der Schätzung. Wie wollen Sie das noch verteidigen?",
      openingTr: "Maliyet tahminin üç katı. Bunu nasıl savunacaksınız?",
      goal: "İtiraz kabul edilmiş, karar buna rağmen gerekçelendirilmiş ve bir sınır ya da koşul konmuş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-hypothesen",
    icon: "idea",
    level: "C1",
    course: "de",
    title: "Angenommen, es stimmt",
    titleTr: "Varsayım dili",
    summary: "Varsayım kurup sonuçlarını tartışmayı öğretir.",
    minutes: 14,
    focusId: "Als-ob",
    vocab: [
      { de: "die Hypothese", tr: "varsayım" },
      { de: "unterstellen", tr: "varsaymak, atfetmek" },
      { de: "der Gedankengang", tr: "düşünce zinciri" },
      { de: "zutreffen", tr: "geçerli olmak" },
      { de: "hypothetisch", tr: "varsayımsal" },
      { de: "die Schätzung", tr: "tahmin" },
      { de: "hervorrufen", tr: "yol açmak" },
      { de: "sich unterziehen", tr: "tabi olmak" },
    ],
    patterns: [
      { de: "Angenommen, …", tr: "diyelim ki" },
      { de: "Gesetzt den Fall, …", tr: "durum şu olsa" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir düşünce deneyi kuracağız. Tartışmada en güçlü hamlelerden biri: karşı tarafın iddiasını bir an için kabul edip sonucuna bakmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bunun üç girişi var ve üçü de aynı işi görüyor. Ardından gelen cümle çoğunlukla dilek kipinde kurulur, çünkü durum gerçek değil. Önce kelimeler.")] },
      word("İlk", { de: "die Hypothese", tr: "varsayım" }),
      word("İkinci", { de: "unterstellen", tr: "varsaymak" }),
      word("Üçüncü", { de: "der Gedankengang", tr: "düşünce zinciri" }),
      word("Dördüncü", { de: "zutreffen", tr: "geçerli olmak" }),
      word("Beşinci", { de: "hypothetisch", tr: "varsayımsal" }),
      word("Altıncı", { de: "die Schätzung", tr: "tahmin" }),
      word("Yedinci", { de: "hervorrufen", tr: "yol açmak" }),
      word("Son", { de: "sich unterziehen", tr: "tabi olmak" }),
      { say: [tr("Örnek:"), de("Angenommen, es stimmt — was folgt daraus?"), tr("Tekrar edin:"), de("Angenommen, es stimmt, was folgt daraus")], expect: repeat("Angenommen, es stimmt, was folgt daraus") },
      { say: [tr("Sıra sende: 'Diyelim ki durum böyle olsa.'")], expect: produce("Gesetzt den Fall, es wäre so", [tr("Kalıplaşmış giriş belirtme hâlinde; ardından dilek kipi:"), de("Gesetzt den Fall, es wäre so."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bunu bir an için varsayalım.'")], expect: produce("Unterstellen wir das einmal", [tr("Rica biçiminde fiil başta:"), de("Unterstellen wir das einmal."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu varsayım geçerliyse sonuç değişir.'")], expect: produce("Trifft diese Hypothese zu, ändert sich das Ergebnis", [tr("Bağlaçsız koşul cümlesi fiille başlar; ayrılabilen önek sonda:"), de("Trifft diese Hypothese zu, ändert sich das Ergebnis."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dem Gedankengang kann ich folgen."), tr("cümlesi doğru mu?")], expect: truefalse("Dem Gedankengang kann ich folgen.", true, [tr("Doğru. Bu fiil yönelme hâli ister ve tümleç öne alındığı için fiil ikinci sırada duruyor.")]) },
      { say: [tr("Son: 'Düşünce zincirini takip edebiliyorum.'")], expect: produce("Dem Gedankengang kann ich folgen", [tr("Yönelme hâlindeki tümleç başta:"), de("Dem Gedankengang kann ich folgen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir iddiayı varsayarak sınayacaksın.")] },
    ],
    roleplay: {
      scene: "Karşındaki güçlü bir iddia öne sürüyor. İddiayı bir an için doğru varsay, sonuçlarına birlikte bakın, nerede çöktüğünü göster ve varsayımın hangi kısmının ayakta kaldığını söyle.",
      partner: "iddiasına güvenen, varsayım oyununa girmeye istekli bir tartışmacı",
      opening: "Nehmen wir ruhig an, ich habe recht. Was wäre daran so schlimm?",
      openingTr: "Rahatça varsayalım ki haklıyım. Bunun nesi bu kadar kötü olurdu?",
      goal: "İddia varsayımsal olarak kabul edilmiş, sonuçları birlikte incelenmiş ve hangi kısmının ayakta kaldığı söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-migrationsdebatte",
    icon: "culture",
    level: "C1",
    course: "de",
    title: "Zwischen den Stühlen",
    titleTr: "Kimlik tartışması",
    summary: "Aidiyeti iki yönlü imtiyaz cümleleriyle anlatmayı öğretir.",
    minutes: 14,
    focusId: "Konzessive-Konnektoren",
    vocab: [
      { de: "die Zugehörigkeit", tr: "aidiyet" },
      { de: "die Teilhabe", tr: "katılım" },
      { de: "ausgrenzen", tr: "dışlamak" },
      { de: "die Zuschreibung", tr: "atfetme" },
      { de: "beheimatet", tr: "yerleşik, ait" },
      { de: "die Abstammung", tr: "soy, köken" },
      { de: "die Verwandtschaft", tr: "akrabalık" },
      { de: "sich niederlassen", tr: "yerleşmek" },
    ],
    patterns: [
      { de: "So sehr …, so oft …", tr: "iki yönlü imtiyaz" },
      { de: "Beides ist zugleich möglich.", tr: "ikisi aynı anda" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü konu kişisel olabilir: aidiyet. Ve dil burada işe yarıyor, çünkü aidiyet çoğu zaman 'ya o ya bu' değil 'hem o hem bu'. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki yönlü imtiyaz kalıbı tam olarak bunu taşıyor: bir yandan ne kadar, öte yandan ne kadar. İki parçada da fiil hemen sıfattan sonra gelir. Önce kelimeler.")] },
      word("İlk", { de: "die Zugehörigkeit", tr: "aidiyet" }),
      word("İkinci", { de: "die Teilhabe", tr: "katılım" }),
      word("Üçüncü", { de: "ausgrenzen", tr: "dışlamak" }),
      word("Dördüncü", { de: "die Zuschreibung", tr: "atfetme" }),
      word("Beşinci", { de: "beheimatet", tr: "yerleşik, ait" }),
      word("Altıncı", { de: "die Abstammung", tr: "soy, köken" }),
      word("Yedinci", { de: "die Verwandtschaft", tr: "akrabalık" }),
      word("Son", { de: "sich niederlassen", tr: "yerleşmek" }),
      { say: [tr("Örnek:"), de("So sehr ich dazugehöre, so oft werde ich gefragt, woher ich komme."), tr("Tekrar edin:"), de("So sehr ich dazugehöre, so oft werde ich gefragt, woher ich komme")], expect: repeat("So sehr ich dazugehöre, so oft werde ich gefragt, woher ich komme") },
      { say: [tr("Sıra sende: 'İkisi aynı anda mümkün.'")], expect: produce("Beides ist zugleich möglich", [tr("Belirsiz zamir tekil çekim alır:"), de("Beides ist zugleich möglich."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Aidiyet bir belge değildir.'")], expect: produce("Zugehörigkeit ist kein Dokument", [tr("Nötr isim olumsuz belirteci kein alır:"), de("Zugehörigkeit ist kein Dokument."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu atıf beni dışlıyor.'")], expect: produce("Diese Zuschreibung grenzt mich aus", [tr("Ayrılabilen fiilin öneki sonda:"), de("Diese Zuschreibung grenzt mich aus."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Zugehörigkeit ist keine Dokument."), tr("cümlesi doğru mu?")], expect: truefalse("Zugehörigkeit ist keine Dokument.", false, [tr("Bu isim nötrdür; olumsuz belirteç ona göre çekilir:"), de("Zugehörigkeit ist kein Dokument.")]) },
      { say: [tr("Son: 'Katılım ancak birlikte olur.'")], expect: produce("Teilhabe gibt es nur gemeinsam", [tr("Nesne öne alınmış; kalıplaşmış fiil ikinci sırada:"), de("Teilhabe gibt es nur gemeinsam."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada aidiyet üzerine konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Biri sana 'aslında nerelisin' diye soruyor ve bu soru seni yoruyor. Sorunun ardındaki varsayımı adlandır, kendi aidiyetini iki yönlü anlat, karşı tarafı suçlamadan sınırını söyle ve konuşmayı yapıcı bitir.",
      partner: "iyi niyetli ama sorusunun neden yorucu olduğunu bilmeyen bir tanıdık",
      opening: "Ich meine es nicht böse — aber wo kommen Sie ursprünglich her?",
      openingTr: "Kötü niyetle sormuyorum — ama aslen nerelisiniz?",
      goal: "Sorunun ardındaki varsayım adlandırılmış, aidiyet iki yönlü anlatılmış ve konuşma suçlamadan yapıcı biçimde bitirilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-klimadebatte",
    icon: "recycle",
    level: "C1",
    course: "de",
    title: "Wer trägt die Verantwortung?",
    titleTr: "İklim tartışması",
    summary: "Bireysel ve sistemik sorumluluğu isimleşmiş dille ayırmayı öğretir.",
    minutes: 14,
    focusId: "Nominalstil",
    vocab: [
      { de: "der Zielkonflikt", tr: "hedef çatışması" },
      { de: "systemisch", tr: "sistemik" },
      { de: "der Einzelne", tr: "birey" },
      { de: "die Verlagerung", tr: "kaydırma" },
      { de: "verursachen", tr: "sebep olmak" },
      { de: "zunehmend", tr: "giderek artan" },
      { de: "die Adaption", tr: "uyarlanma" },
      { de: "unterbinden", tr: "önüne geçmek" },
    ],
    patterns: [
      { de: "die Verantwortung des Einzelnen", tr: "bireyin sorumluluğu" },
      { de: "die Verlagerung der Verantwortung auf …", tr: "sorumluluğu kaydırmak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün iklim tartışması. Ama asıl konu bir dil hilesi: sorumluluğun bireye kaydırılması ve bunun isimleşmiş dille nasıl yapıldığı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de küçük ama tuzaklı bir dilbilgisi noktası var: isimleşmiş sıfatın tamlamadaki çekimi. Sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "der Zielkonflikt", tr: "hedef çatışması" }),
      word("İkinci", { de: "systemisch", tr: "sistemik" }),
      word("Üçüncü", { de: "der Einzelne", tr: "birey" }),
      word("Dördüncü", { de: "die Verlagerung", tr: "kaydırma" }),
      word("Beşinci", { de: "verursachen", tr: "sebep olmak" }),
      word("Altıncı", { de: "zunehmend", tr: "giderek artan" }),
      word("Yedinci", { de: "die Adaption", tr: "uyarlanma" }),
      word("Son", { de: "unterbinden", tr: "önüne geçmek" }),
      { say: [tr("Örnek:"), de("Die Verantwortung des Einzelnen wird oft überschätzt."), tr("Tekrar edin:"), de("Die Verantwortung des Einzelnen wird oft überschätzt")], expect: repeat("Die Verantwortung des Einzelnen wird oft überschätzt") },
      { say: [tr("Sıra sende: 'Sistemik sebepler daha ağır basıyor.'")], expect: produce("Systemische Ursachen wiegen schwerer", [tr("Belirteçsiz çoğulda sıfat -e ekini alır:"), de("Systemische Ursachen wiegen schwerer."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Burada bir hedef çatışması var.'")], expect: produce("Hier liegt ein Zielkonflikt vor", [tr("Yer zarfı başta; ayrılabilen önek sonda:"), de("Hier liegt ein Zielkonflikt vor."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sorumluluğun bireye kaydırılması kolaycılıktır.'")], expect: produce("Die Verlagerung der Verantwortung auf den Einzelnen ist bequem", [tr("İki tamlama ve bir edat öbeği; edat belirtme hâli ister:"), de("Die Verlagerung der Verantwortung auf den Einzelnen ist bequem."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Verantwortung des Einzelne wird oft überschätzt."), tr("cümlesi doğru mu?")], expect: truefalse("Die Verantwortung des Einzelne wird oft überschätzt.", false, [tr("İsimleşmiş sıfat tamlama hâlinde -n ekini alır:"), de("Die Verantwortung des Einzelnen wird oft überschätzt.")]) },
      { say: [tr("Son bir soru: 'Buna kim sebep oluyor?'")], expect: produce("Wer verursacht das", [tr("Soru zamiri özne, fiil ikinci sırada:"), de("Wer verursacht das?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada sorumluluğun nerede olduğunu tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığınla iklim sorumluluğunu tartışıyorsunuz: birey mi, sistem mi. Sorumluluğun kaydırılmasını adlandır, bireysel adımın ne yaptığını ve yapmadığını söyle, hedef çatışmasını göster ve ortak bir ölçütte buluşun.",
      partner: "her şeyi bireysel davranışa bağlayan bir tanıdık",
      opening: "Wenn jeder bei sich anfängt, ist das Problem doch gelöst. Oder wollen Sie sich nur herausreden?",
      openingTr: "Herkes kendinden başlarsa sorun çözülür. Yoksa siz sadece bahane mi arıyorsunuz?",
      goal: "Bireysel ve sistemik sorumluluk ayrılmış, hedef çatışması gösterilmiş ve ortak bir ölçütte buluşulmuş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-bildungsdebatte",
    icon: "school",
    level: "C1",
    course: "de",
    title: "Bildung neu denken",
    titleTr: "Eğitim tartışması",
    summary: "Olmamış bir geçmişi irreal koşullarla tartışmayı öğretir.",
    minutes: 14,
    focusId: "Konjunktiv-II-irreal",
    vocab: [
      { de: "die Chancengleichheit", tr: "fırsat eşitliği" },
      { de: "versäumen", tr: "ihmal etmek, kaçırmak" },
      { de: "die Weiche", tr: "makas, yön belirleyici" },
      { de: "überfällig", tr: "gecikmiş" },
      { de: "umdenken", tr: "yeniden düşünmek" },
      { de: "voreingenommen", tr: "önyargılı" },
      { de: "das Fachgebiet", tr: "uzmanlık alanı" },
      { de: "die Maxime", tr: "ilke" },
    ],
    patterns: [
      { de: "Hätte man früher …, stünden wir …", tr: "irreal geçmiş koşul" },
      { de: "Es wäre an der Zeit gewesen.", tr: "vakti gelmişti" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün olmamış bir geçmişi tartışacağız — 'keşke şöyle yapılsaydı'. Almanca bunun için tam bir yapıya sahip. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki parça: koşul cümlesinde geçmişin dilek kipi, sonuç cümlesinde ya geçmiş ya şimdi. Karışan yer sonuç cümlesinin zamanı. Önce kelimeler.")] },
      word("İlk", { de: "die Chancengleichheit", tr: "fırsat eşitliği" }),
      word("İkinci", { de: "versäumen", tr: "ihmal etmek" }),
      word("Üçüncü", { de: "die Weiche", tr: "makas, yön belirleyici" }),
      word("Dördüncü", { de: "überfällig", tr: "gecikmiş" }),
      word("Beşinci", { de: "umdenken", tr: "yeniden düşünmek" }),
      word("Altıncı", { de: "voreingenommen", tr: "önyargılı" }),
      word("Yedinci", { de: "das Fachgebiet", tr: "uzmanlık alanı" }),
      word("Son", { de: "die Maxime", tr: "ilke" }),
      { say: [tr("Örnek:"), de("Hätte man früher investiert, stünden wir heute anders da."), tr("Tekrar edin:"), de("Hätte man früher investiert, stünden wir heute anders da")], expect: repeat("Hätte man früher investiert, stünden wir heute anders da") },
      { say: [tr("Sıra sende: 'Bunun vakti çoktan gelmişti.'")], expect: produce("Es wäre längst an der Zeit gewesen", [tr("Geçmişin dilek kipi; ortaç en sonda:"), de("Es wäre längst an der Zeit gewesen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Daha erken karar verilseydi durum başka olurdu.'")], expect: produce("Wäre früher entschieden worden, sähe es anders aus", [tr("Edilgen irreal koşul; sonuç şimdiki dilek kipinde:"), de("Wäre früher entschieden worden, sähe es anders aus."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Yeniden düşünmek gecikti.'")], expect: produce("Das Umdenken ist überfällig", [tr("İsimleşmiş mastar özne olarak:"), de("Das Umdenken ist überfällig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Hätte man früher investiert, stünden wir heute anders da."), tr("cümlesi doğru mu?")], expect: truefalse("Hätte man früher investiert, stünden wir heute anders da.", true, [tr("Doğru. Koşul geçmişin dilek kipinde, sonuç ise bugüne baktığı için şimdiki dilek kipinde kurulmuş.")]) },
      { say: [tr("Son: 'Fırsat eşitliği bir hedef, bir durum değil.'")], expect: produce("Chancengleichheit ist ein Ziel, kein Zustand", [tr("İki isim; ikincisinde olumsuz belirteç:"), de("Chancengleichheit ist ein Ziel, kein Zustand."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada eğitim sistemini tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir veli toplantısında eğitim sistemini tartışıyorsunuz. Geçmişte neyin ihmal edildiğini irreal koşullarla söyle, bugün ne yapılabileceğini ayır, karşı tarafın itirazını kabul et ve somut bir öneri bırak.",
      partner: "sistemin iyi olduğunu savunan, geçmişe bakmayı gereksiz bulan bir veli",
      opening: "Was hätte, hätte — was bringt uns das? Sagen Sie mir lieber, was wir jetzt tun sollen.",
      openingTr: "Olsaydı, yapsaydı — bunun bize ne faydası var? Bana asıl şimdi ne yapmamız gerektiğini söyleyin.",
      goal: "Geçmişteki ihmal irreal koşullarla söylenmiş, bugün yapılabilecek olan ayrılmış ve somut bir öneri bırakılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-ethik-ki",
    icon: "tech",
    level: "C1",
    course: "de",
    title: "Darf KI das?",
    titleTr: "Yapay zekâ etiği",
    summary: "Makinelere atfedilen niteliği irreal kıyasla sorgulamayı öğretir.",
    minutes: 14,
    focusId: "Als-ob",
    vocab: [
      { de: "zurechnen", tr: "isnat etmek" },
      { de: "die Instanz", tr: "merci" },
      { de: "simulieren", tr: "taklit etmek" },
      { de: "empfinden", tr: "hissetmek" },
      { de: "haftbar", tr: "sorumlu tutulabilir" },
      { de: "skrupellos", tr: "vicdansız" },
      { de: "die Intervention", tr: "müdahale" },
      { de: "der Vorsatz", tr: "kasıt" },
    ],
    patterns: [
      { de: "Es wirkt, als ob Maschinen fühlten.", tr: "irreal kıyas" },
      { de: "Wem wird die Verantwortung zugerechnet?", tr: "sorumluluk isnadı" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün yapay zekâ etiği. Ve dilin tam ortada olduğu bir yer: makinelere insan niteliği atfetmek çoğu zaman bir dil kaymasıyla başlıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Sanki hissediyorlarmış gibi görünüyor' cümlesi dürüst;"), de("Maschinen fühlen"), tr("cümlesi ise bir iddia. Aradaki fark dilek kipi. Önce kelimeler.")] },
      word("İlk", { de: "zurechnen", tr: "isnat etmek" }),
      word("İkinci", { de: "die Instanz", tr: "merci" }),
      word("Üçüncü", { de: "simulieren", tr: "taklit etmek" }),
      word("Dördüncü", { de: "empfinden", tr: "hissetmek" }),
      word("Beşinci", { de: "haftbar", tr: "sorumlu tutulabilir" }),
      word("Altıncı", { de: "skrupellos", tr: "vicdansız" }),
      word("Yedinci", { de: "die Intervention", tr: "müdahale" }),
      word("Son", { de: "der Vorsatz", tr: "kasıt" }),
      { say: [tr("Örnek:"), de("Es wirkt, als ob Maschinen fühlten."), tr("Tekrar edin:"), de("Es wirkt, als ob Maschinen fühlten")], expect: repeat("Es wirkt, als ob Maschinen fühlten") },
      { say: [tr("Sıra sende: 'Duyguyu taklit etmek hissetmekle aynı şey değildir.'")], expect: produce("Gefühle zu simulieren ist nicht dasselbe wie sie zu empfinden", [tr("İkinci mastar öbeği de nesnesini taşımalı:"), de("Gefühle zu simulieren ist nicht dasselbe wie sie zu empfinden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sorumluluk kime isnat edilecek?'")], expect: produce("Wem wird die Verantwortung zugerechnet", [tr("Soru zamiri yönelme hâlinde; edilgen sonda:"), de("Wem wird die Verantwortung zugerechnet?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bir makine sorumlu tutulamaz.'")], expect: produce("Eine Maschine kann nicht haftbar gemacht werden", [tr("Kipli edilgen; sonda ortaç ve werden:"), de("Eine Maschine kann nicht haftbar gemacht werden."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es wirkt, als ob Maschinen fühlen."), tr("cümlesi doğru mu?")], expect: truefalse("Es wirkt, als ob Maschinen fühlen.", false, [tr("Bu yapı gerçek olmayanı işaretler ve dilek kipi ister; düz kip cümleyi bir iddiaya çevirir:"), de("Es wirkt, als ob Maschinen fühlten.")]) },
      { say: [tr("Son: 'Sınırı nereye çekiyoruz?'")], expect: produce("Wo ziehen wir die Grenze", [tr("Soru kelimesi başta; nesne belirtme hâlinde:"), de("Wo ziehen wir die Grenze?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada yapay zekânın sorumluluğunu tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir kararı yapay zekâya bırakmanın doğru olup olmadığını tartışıyorsunuz. Makineye atfedilen nitelikleri dille ayır, sorumluluğun kime isnat edileceğini sor, sınırı nereye çektiğini söyle ve ortak bir kural önerin.",
      partner: "sistemin insandan daha iyi karar verdiğini savunan bir meslektaş",
      opening: "Das System entscheidet objektiver als jeder von uns. Warum sollten wir ihm das nicht überlassen?",
      openingTr: "Sistem her birimizden daha nesnel karar veriyor. Bunu ona neden bırakmayalım?",
      goal: "Makineye atfedilen nitelikler dille ayrılmış, sorumluluğun kime ait olacağı konuşulmuş ve ortak bir sınır kuralı önerilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-generationenvertrag",
    icon: "family",
    level: "C1",
    course: "de",
    title: "Wer zahlt für wen?",
    titleTr: "Kuşak sözleşmesi",
    summary: "Kuşaklar arası yükü imtiyaz ve tamlama diliyle tartışmayı öğretir.",
    minutes: 14,
    focusId: "Konzessive-Konnektoren",
    vocab: [
      { de: "der Generationenvertrag", tr: "kuşak sözleşmesi" },
      { de: "solidarisch", tr: "dayanışmacı" },
      { de: "die Umverteilung", tr: "yeniden dağıtım" },
      { de: "zulasten", tr: "…-in aleyhine" },
      { de: "die Beitragslast", tr: "katkı yükü" },
      { de: "kollektiv", tr: "toplu, ortak" },
      { de: "die Bürokratie", tr: "bürokrasi" },
      { de: "der Egoismus", tr: "bencillik" },
    ],
    patterns: [
      { de: "zulasten + Genitiv", tr: "…-in aleyhine" },
      { de: "Nichtsdestotrotz funktioniert …", tr: "yine de işliyor" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kuşaklar arası hesap. Bu tartışmada iki taraf da haklıdır ve tam bu yüzden imtiyaz bağlaçları gerekiyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de tamlama isteyen yeni bir edat var: kimin aleyhine olduğunu söyleyen edat. Sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "der Generationenvertrag", tr: "kuşak sözleşmesi" }),
      word("İkinci", { de: "solidarisch", tr: "dayanışmacı" }),
      word("Üçüncü", { de: "die Umverteilung", tr: "yeniden dağıtım" }),
      word("Dördüncü", { de: "zulasten", tr: "…-in aleyhine" }),
      word("Beşinci", { de: "die Beitragslast", tr: "katkı yükü" }),
      word("Altıncı", { de: "kollektiv", tr: "toplu, ortak" }),
      word("Yedinci", { de: "die Bürokratie", tr: "bürokrasi" }),
      word("Son", { de: "der Egoismus", tr: "bencillik" }),
      { say: [tr("Örnek:"), de("Ungeachtet der Kosten bleibt das System solidarisch."), tr("Tekrar edin:"), de("Ungeachtet der Kosten bleibt das System solidarisch")], expect: repeat("Ungeachtet der Kosten bleibt das System solidarisch") },
      { say: [tr("Sıra sende: 'Bu genç kuşağın aleyhine oluyor.'")], expect: produce("Das geht zulasten der jungen Generation", [tr("Bu edat tamlama hâli ister; sıfat -en ekini alır:"), de("Das geht zulasten der jungen Generation."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Yeniden dağıtım tartışılıyor.'")], expect: produce("Über die Umverteilung wird gestritten", [tr("Kişisiz edilgen; tümleç başta:"), de("Über die Umverteilung wird gestritten."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Katkı yükü artıyor.'")], expect: produce("Die Beitragslast steigt", [tr("Kısa cümle; tekil fiil:"), de("Die Beitragslast steigt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das geht zulasten die junge Generation."), tr("cümlesi doğru mu?")], expect: truefalse("Das geht zulasten die junge Generation.", false, [tr("Bu edat tamlama hâli ister:"), de("Das geht zulasten der jungen Generation.")]) },
      { say: [tr("Son: 'Yine de sistem çalışıyor.'")], expect: produce("Nichtsdestotrotz funktioniert das System", [tr("Bağlaç ilk öğe; fiil ikinci sırada:"), de("Nichtsdestotrotz funktioniert das System."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada kuşaklar arası yükü tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Farklı kuşaktan biriyle emeklilik ve katkı yükünü tartışıyorsunuz. Kimin aleyhine ne olduğunu söyle, karşı tarafın haklı yanını kabul et, yine de kendi noktanı koru ve adil bir ölçüt önerin.",
      partner: "kendi kuşağının hakkını savunan, rakamları bilen bir tanıdık",
      opening: "Wir haben vierzig Jahre eingezahlt. Wollen Sie uns das jetzt streitig machen?",
      openingTr: "Kırk yıl katkı ödedik. Şimdi bunu bize tartışma konusu mu yapacaksınız?",
      goal: "Kimin aleyhine ne olduğu söylenmiş, karşı tarafın haklı yanı kabul edilmiş ve adil bir ölçüt önerilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-meinungsfreiheit",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Die Grenzen des Sagbaren",
    titleTr: "İfade özgürlüğü",
    summary: "Ayrım kuran gönderme diliyle sınırları tanımlamayı öğretir.",
    minutes: 14,
    focusId: "Verweiswörter",
    vocab: [
      { de: "die Meinungsfreiheit", tr: "ifade özgürlüğü" },
      { de: "insofern", tr: "bu bakımdan" },
      { de: "hierbei", tr: "bunda, burada" },
      { de: "abgrenzen", tr: "sınırını çizmek" },
      { de: "die Herabwürdigung", tr: "aşağılama" },
      { de: "die Verleumdung", tr: "iftira" },
      { de: "die Propaganda", tr: "propaganda" },
      { de: "die Unterdrückung", tr: "baskı" },
    ],
    patterns: [
      { de: "Davon zu unterscheiden ist …", tr: "bundan ayrılması gereken" },
      { de: "Insofern hast du recht.", tr: "bu bakımdan haklısın" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün en hassas konu: neyin söylenebileceği. Ve burada dilin işi tarafsız — ayrım kurmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Ayrım kuran ifadeler C1'in en faydalı araçlarından:"), de("Davon zu unterscheiden ist …"), tr("cümlesi karşı tarafı reddetmeden konuyu ikiye böler. Önce kelimeler.")] },
      word("İlk", { de: "die Meinungsfreiheit", tr: "ifade özgürlüğü" }),
      word("İkinci", { de: "insofern", tr: "bu bakımdan" }),
      word("Üçüncü", { de: "hierbei", tr: "bunda, burada" }),
      word("Dördüncü", { de: "abgrenzen", tr: "sınırını çizmek" }),
      word("Beşinci", { de: "die Herabwürdigung", tr: "aşağılama" }),
      word("Altıncı", { de: "die Verleumdung", tr: "iftira" }),
      word("Yedinci", { de: "die Propaganda", tr: "propaganda" }),
      word("Son", { de: "die Unterdrückung", tr: "baskı" }),
      { say: [tr("Örnek:"), de("Davon zu unterscheiden ist die Herabwürdigung von Personen."), tr("Tekrar edin:"), de("Davon zu unterscheiden ist die Herabwürdigung von Personen")], expect: repeat("Davon zu unterscheiden ist die Herabwürdigung von Personen") },
      { say: [tr("Sıra sende: 'Bu bakımdan haklısın.'")], expect: produce("Insofern hast du recht", [tr("Zarf ilk öğe; fiil ikinci sırada:"), de("Insofern hast du recht."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Burada iki şey birbirinden ayrılmalı.'")], expect: produce("Hierbei muss man zwei Dinge voneinander abgrenzen", [tr("Zarf başta; ayrılabilen mastar sonda:"), de("Hierbei muss man zwei Dinge voneinander abgrenzen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu konuda görüşüm net.'")], expect: produce("Diesbezüglich ist meine Position klar", [tr("Zarf başta, fiil ikinci sırada:"), de("Diesbezüglich ist meine Position klar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Insofern hast du recht."), tr("cümlesi doğru mu?")], expect: truefalse("Insofern hast du recht.", true, [tr("Doğru. Zarf cümlenin ilk öğesi olduğu için çekimli fiil hemen arkasından geliyor ve özne ondan sonra duruyor.")]) },
      { say: [tr("Son bir soru: 'Kırmızı çizgi nerede?'")], expect: produce("Wo verläuft die rote Linie", [tr("Soru kelimesi başta; özne fiilden sonra:"), de("Wo verläuft die rote Linie?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada söylenebilirin sınırını tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tartışmada birinin sözü tepki topladı. İfade özgürlüğü ile aşağılamayı ayır, hangi noktada karşı tarafın haklı olduğunu söyle, sınırı nereye çektiğini gerekçelendir ve ortak bir ölçüt arayın.",
      partner: "her eleştiriyi sansür sayan, sınır fikrine karşı çıkan bir tartışmacı",
      opening: "Man wird ja wohl noch alles sagen dürfen. Oder wollen Sie jetzt auch noch Vorschriften machen?",
      openingTr: "İnsan artık her şeyi söyleyebilmeli. Yoksa siz de mi kural koyacaksınız?",
      goal: "İfade özgürlüğü ile aşağılama ayrılmış, karşı tarafın haklı olduğu nokta söylenmiş ve ortak bir ölçüt aranmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-zukunftsvision",
    icon: "idea",
    level: "C1",
    course: "de",
    title: "Deutschland 2050",
    titleTr: "Gelecek vizyonu",
    summary: "Kurulmamış bir geleceği irreal kipte tasarlamayı öğretir.",
    minutes: 14,
    focusId: "Konjunktiv-II-irreal",
    vocab: [
      { de: "entwerfen", tr: "tasarlamak" },
      { de: "der Entwurf", tr: "taslak" },
      { de: "utopisch", tr: "ütopik" },
      { de: "denkbar", tr: "düşünülebilir" },
      { de: "das Szenario", tr: "senaryo" },
      { de: "wiederbeleben", tr: "canlandırmak" },
      { de: "verschmelzen", tr: "kaynaşmak" },
      { de: "die Diktatur", tr: "diktatörlük" },
    ],
    patterns: [
      { de: "Stellte man sich vor, es gäbe …", tr: "irreal tasarım" },
      { de: "Rückblickend aus der Zukunft …", tr: "gelecekten geriye bakış" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve konusu gelecek. Ama tahmin değil TASARIM: olmayan bir dünyayı kurup içinden bugüne bakmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bunun kipi baştan sona irreal. Bir cümlede düz kipe kayarsan tasarım bir iddiaya dönüşür ve tartışma bozulur. Önce kelimeler.")] },
      word("İlk", { de: "entwerfen", tr: "tasarlamak" }),
      word("İkinci", { de: "der Entwurf", tr: "taslak" }),
      word("Üçüncü", { de: "utopisch", tr: "ütopik" }),
      word("Dördüncü", { de: "denkbar", tr: "düşünülebilir" }),
      word("Beşinci", { de: "das Szenario", tr: "senaryo" }),
      word("Altıncı", { de: "wiederbeleben", tr: "canlandırmak" }),
      word("Yedinci", { de: "verschmelzen", tr: "kaynaşmak" }),
      word("Son", { de: "die Diktatur", tr: "diktatörlük" }),
      { say: [tr("Örnek:"), de("Stellte man sich vor, es gäbe keine Autos in der Stadt."), tr("Tekrar edin:"), de("Stellte man sich vor, es gäbe keine Autos in der Stadt")], expect: repeat("Stellte man sich vor, es gäbe keine Autos in der Stadt") },
      { say: [tr("Sıra sende: 'Böyle bir dünya düşünülebilir mi?'")], expect: produce("Wäre eine solche Welt denkbar", [tr("Dilek kipi başta soru; sıfat sonda:"), de("Wäre eine solche Welt denkbar?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir senaryo tasarlayalım.'")], expect: produce("Entwerfen wir ein Szenario", [tr("Rica biçiminde fiil başta:"), de("Entwerfen wir ein Szenario."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu ütopik değil, planlanabilir.'")], expect: produce("Das ist nicht utopisch, sondern planbar", [tr("Olumsuzdan sonra düzeltme sondern ile:"), de("Das ist nicht utopisch, sondern planbar."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Stellte man sich vor, es gibt keine Autos."), tr("cümlesi doğru mu?")], expect: truefalse("Stellte man sich vor, es gibt keine Autos.", false, [tr("Tasarım baştan sona irreal kipte kalmalı; düz kip cümleyi bir iddiaya çevirir:"), de("Stellte man sich vor, es gäbe keine Autos.")]) },
      { say: [tr("Son: 'Gelecekten geriye bakınca bugün ne görünürdü?'")], expect: produce("Rückblickend aus der Zukunft: Was sähe man heute", [tr("Zarf öbeği başta; dilek kipi soru biçiminde:"), de("Rückblickend aus der Zukunft: Was sähe man heute?"), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir gelecek senaryosu tasarlayacaksın.")] },
    ],
    roleplay: {
      scene: "Bir atölyede 2050 için bir senaryo tasarlıyorsunuz. Senaryoyu irreal kipte kur, hangi adımın bugünden başlaması gerektiğini söyle, karşı tarafın 'ütopik' itirazını karşıla ve tasarımı somut bir ilk adıma bağla.",
      partner: "hayalci bulduğu her fikri 'gerçekçi değil' diye eleyen bir katılımcı",
      opening: "Schöne Vision — aber das ist doch reine Utopie. Womit wollen Sie denn anfangen?",
      openingTr: "Güzel bir vizyon — ama tamamen ütopya. Neyle başlamayı düşünüyorsunuz?",
      goal: "Senaryo irreal kipte kurulmuş, 'ütopik' itirazı karşılanmış ve tasarım bugünden başlayacak somut bir ilk adıma bağlanmış olur.",
      minTurns: 9,
    },
  },
];
