import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * C1 · Modül 1 — Zarif iş iletişimi (001–010).
 *
 * C1'in B2'den farkı yeni kural değil, SEÇİM. B2'yi bitiren öğrenci doğru
 * cümleyi kurabiliyor; C1'de aynı içeriği kaç ayrı üslupta söyleyebildiği ve
 * hangisini neden seçtiği ölçülüyor. Bu yüzden modül tek bir yapıyı değil bir
 * REGİSTERİ çalıştırıyor.
 *
 * Omurga işlev fiili öbekleri (Funktionsverbgefüge): `entscheiden` yerine
 * `eine Entscheidung treffen`. Almanca resmî dilde fiil boşalır, anlam isme
 * geçer. Türkçe konuşan için burada beklenmedik bir avantaj var — "karar
 * vermek", "göz önüne almak", "yürürlüğe girmek" aynı mantıkla kurulur. Zor
 * olan kalıbın kendisi değil, kalıbın DEĞİŞMEZLİĞİ: `in Frage kommen`
 * belirteç almaz, `in Kraft treten` de almaz; bir harf eklemek cümleyi
 * amatör yapar.
 *
 * İkinci hat diplomasi: dilek kipiyle itiraz etmek, çekince koymak, kriz
 * bildirmek. C1'de kibarlık bir süs değil bir araç — karşı tarafı kaybetmeden
 * hayır demenin tek yolu.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deC1B01: Lesson[] = [
  {
    id: "de-c1-fvg-treffen",
    icon: "job",
    level: "C1",
    course: "de",
    title: "Eine Entscheidung treffen",
    titleTr: "İşlev fiilleri I",
    summary: "Resmî dilde fiilin isme geçtiği sabit öbekleri kurmayı öğretir.",
    minutes: 14,
    focusId: "Funktionsverbgefüge",
    vocab: [
      { de: "die Erwägung", tr: "değerlendirme" },
      { de: "in Frage kommen", tr: "söz konusu olmak" },
      { de: "zur Verfügung stehen", tr: "hizmete hazır olmak" },
      { de: "in Betracht ziehen", tr: "göz önüne almak" },
      { de: "die Tragweite", tr: "kapsam, ağırlık" },
      { de: "der Beschluss", tr: "karar" },
      { de: "die Bestimmung", tr: "hüküm" },
      { de: "veranlassen", tr: "yol açmak" },
    ],
    patterns: [
      { de: "eine Entscheidung treffen", tr: "karar vermek" },
      { de: "in Frage kommen / in Kraft treten", tr: "belirteçsiz sabit öbek" },
    ],
    lecture: [
      { say: [tr("Merhaba ve C1'e hoş geldin. Bu seviyede yeni kural az; asıl mesele SEÇİM — aynı şeyi kaç ayrı üslupta söyleyebildiğin. İlk modül: kurumsal Almancanın kendi grameri. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Resmî Almancada fiil boşalır ve anlam isme geçer:"), de("entscheiden"), tr("yerine"), de("eine Entscheidung treffen"), tr("Türkçede de öyle deriz — 'karar vermek'. Yani mantık tanıdık.")] },
      { say: [tr("Zor olan kalıbın kendisi değil, DEĞİŞMEZLİĞİ. Bazı öbekler belirteç almaz ve bir harf eklemek cümleyi amatör yapar. Önce kelimeler.")] },
      word("İlk", { de: "die Erwägung", tr: "değerlendirme" }),
      word("İkinci", { de: "in Frage kommen", tr: "söz konusu olmak" }),
      word("Üçüncü", { de: "zur Verfügung stehen", tr: "hizmete hazır olmak" }),
      word("Dördüncü", { de: "in Betracht ziehen", tr: "göz önüne almak" }),
      word("Beşinci", { de: "die Tragweite", tr: "kapsam, ağırlık" }),
      word("Altıncı", { de: "der Beschluss", tr: "karar" }),
      word("Yedinci", { de: "die Bestimmung", tr: "hüküm" }),
      word("Son", { de: "veranlassen", tr: "yol açmak" }),
      { say: [tr("Örnek:"), de("Wir haben eine Entscheidung getroffen."), tr("Tekrar edin:"), de("Wir haben eine Entscheidung getroffen")], expect: repeat("Wir haben eine Entscheidung getroffen") },
      { say: [tr("Sıra sende: 'Bu seçenek bizim için söz konusu değil.'")], expect: produce("Diese Option kommt für uns nicht in Frage", [tr("Öbek belirteçsizdir; olumsuzluk öbekten önce:"), de("Diese Option kommt für uns nicht in Frage."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Her zaman hizmetinizdeyim.'")], expect: produce("Ich stehe Ihnen jederzeit zur Verfügung", [tr("Kişi yönelme hâlinde, öbek sonda:"), de("Ich stehe Ihnen jederzeit zur Verfügung."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunu ciddi biçimde göz önüne alıyoruz.'")], expect: produce("Wir ziehen das ernsthaft in Betracht", [tr("Nesne fiilden hemen sonra, öbek en sonda:"), de("Wir ziehen das ernsthaft in Betracht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Diese Option kommt für uns nicht in die Frage."), tr("cümlesi doğru mu?")], expect: truefalse("Diese Option kommt für uns nicht in die Frage.", false, [tr("Bu öbek belirteç almaz; eklenen belirteç kalıbı bozar:"), de("Diese Option kommt für uns nicht in Frage.")]) },
      { say: [tr("Son: 'Kararın kapsamı henüz net değil.'")], expect: produce("Die Tragweite der Entscheidung ist noch unklar", [tr("İki isim tamlamayla bağlanıyor:"), de("Die Tragweite der Entscheidung ist noch unklar."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir yönetim toplantısında karar süreci yürüteceksin.")] },
    ],
    roleplay: {
      scene: "Bir yönetim toplantısındasın ve zor bir karar alınacak. Hangi seçeneklerin söz konusu olduğunu söyle, birini gerekçesiyle ele, kararın kapsamını belirt ve bir karara bağlayın.",
      partner: "acele karar isteyen, riskleri hafife alan bir yönetim kurulu üyesi",
      opening: "Wir drehen uns seit zwei Sitzungen im Kreis. Welche Optionen kommen aus Ihrer Sicht überhaupt noch in Frage?",
      openingTr: "İki toplantıdır aynı yerde dönüyoruz. Sizce hangi seçenekler hâlâ söz konusu?",
      goal: "Söz konusu seçenekler sayılmış, biri gerekçeyle elenmiş, kararın kapsamı söylenmiş ve bir karara varılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-fvg-stellen",
    icon: "office",
    level: "C1",
    course: "de",
    title: "Einen Antrag stellen",
    titleTr: "İşlev fiilleri II",
    summary: "Kurum dilinin en sık işlev fiili öbeklerini kullanmayı öğretir.",
    minutes: 14,
    focusId: "Funktionsverbgefüge",
    vocab: [
      { de: "in Anspruch nehmen", tr: "yararlanmak" },
      { de: "zum Ausdruck bringen", tr: "dile getirmek" },
      { de: "Abstand nehmen", tr: "vazgeçmek" },
      { de: "Rücksicht nehmen", tr: "gözetmek" },
      { de: "in Kraft treten", tr: "yürürlüğe girmek" },
      { de: "einreichen", tr: "teslim etmek" },
      { de: "die Vollmacht", tr: "vekaletname" },
      { de: "die Bewilligung", tr: "resmî onay" },
    ],
    patterns: [
      { de: "einen Antrag stellen", tr: "başvuruda bulunmak" },
      { de: "… in Anspruch nehmen", tr: "haktan yararlanmak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Dün öbeklerin mantığını kurduk; bugün en çok işine yarayacak beşini ezberleyeceğiz. Bunlar resmî yazışmada neredeyse zorunlu. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Dikkat: öbeğin fiili çekilir, ismi asla değişmez. Yani 'in Anspruch nehmen' öbeğinde yalnız nehmen çekilir. Önce kelimeler.")] },
      word("İlk", { de: "in Anspruch nehmen", tr: "yararlanmak" }),
      word("İkinci", { de: "zum Ausdruck bringen", tr: "dile getirmek" }),
      word("Üçüncü", { de: "Abstand nehmen", tr: "vazgeçmek" }),
      word("Dördüncü", { de: "Rücksicht nehmen", tr: "gözetmek" }),
      word("Beşinci", { de: "in Kraft treten", tr: "yürürlüğe girmek" }),
      word("Altıncı", { de: "einreichen", tr: "teslim etmek" }),
      word("Yedinci", { de: "die Vollmacht", tr: "vekaletname" }),
      word("Son", { de: "die Bewilligung", tr: "resmî onay" }),
      { say: [tr("Örnek:"), de("Ich möchte einen Antrag stellen."), tr("Tekrar edin:"), de("Ich möchte einen Antrag stellen")], expect: repeat("Ich möchte einen Antrag stellen") },
      { say: [tr("Sıra sende: 'Bu haktan yararlanmak istiyorum.'")], expect: produce("Ich möchte dieses Recht in Anspruch nehmen", [tr("Nesne ortada, öbek sonda, mastar en sonda:"), de("Ich möchte dieses Recht in Anspruch nehmen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Çekincelerimi dile getirmek istiyorum.'")], expect: produce("Ich möchte meine Bedenken zum Ausdruck bringen", [tr("Öbeğin ismi değişmez; yalnız fiil çekilir:"), de("Ich möchte meine Bedenken zum Ausdruck bringen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu plandan vazgeçtik.'")], expect: produce("Von diesem Plan haben wir Abstand genommen", [tr("Tümleç başta; ortaç en sonda:"), de("Von diesem Plan haben wir Abstand genommen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Ich möchte dieses Recht in Anspruch genommen."), tr("cümlesi doğru mu?")], expect: truefalse("Ich möchte dieses Recht in Anspruch genommen.", false, [tr("Kip fiilinden sonra ortaç değil mastar gelir:"), de("Ich möchte dieses Recht in Anspruch nehmen.")]) },
      { say: [tr("Son: 'Yeni düzenleme ocakta yürürlüğe giriyor.'")], expect: produce("Die neue Regelung tritt im Januar in Kraft", [tr("Öbek belirteçsiz ve cümlenin sonunda:"), de("Die neue Regelung tritt im Januar in Kraft."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kurumda resmî bir talepte bulunacaksın.")] },
    ],
    roleplay: {
      scene: "Bir kurumda resmî bir talepte bulunuyorsun: neye başvuruyorsun, hangi haktan yararlanmak istiyorsun, hangi çekincen var ve ne zaman yürürlüğe girecek. Kurum dilini kullan.",
      partner: "kalıpları ezbere bilen, formalitelere bağlı bir kurum görevlisi",
      opening: "Sie möchten einen Antrag stellen — worauf genau bezieht sich Ihr Anliegen?",
      openingTr: "Bir başvuruda bulunmak istiyorsunuz — talebiniz tam olarak neye ilişkin?",
      goal: "Başvurunun konusu, dayanılan hak ve yürürlük tarihi netleşmiş; bir çekince kayda geçirilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-diplomatisch",
    icon: "handshake",
    level: "C1",
    course: "de",
    title: "Sagen, ohne zu verletzen",
    titleTr: "Diplomatik üslup",
    summary: "İtirazı karşı tarafı kaybetmeden söylemeyi öğretir.",
    minutes: 14,
    focusId: "Konjunktiv-II-Diplomatie",
    vocab: [
      { de: "die Zurückhaltung", tr: "çekimserlik" },
      { de: "relativieren", tr: "göreceleştirmek, yumuşatmak" },
      { de: "der Vorbehalt", tr: "çekince" },
      { de: "verbindlich", tr: "bağlayıcı" },
      { de: "taktvoll", tr: "incelikli" },
      { de: "der Einwand", tr: "itiraz" },
      { de: "besonnen", tr: "soğukkanlı" },
      { de: "umsichtig", tr: "tedbirli" },
    ],
    patterns: [
      { de: "Ich hätte da einen Einwand.", tr: "itirazı yumuşatır" },
      { de: "Bei allem Respekt, …", tr: "karşı çıkmadan önce" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün C1'in en işlevsel becerisi: hayır demek ama karşı tarafı kaybetmemek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kural şu: itiraz doğrudan söylenmez, bir kabuğun içine konur. Dilek kipi o kabuktur — cümlenin içeriği aynı kalır, bağlayıcılığı düşer. Önce kelimeler.")] },
      word("İlk", { de: "die Zurückhaltung", tr: "çekimserlik" }),
      word("İkinci", { de: "relativieren", tr: "göreceleştirmek" }),
      word("Üçüncü", { de: "der Vorbehalt", tr: "çekince" }),
      word("Dördüncü", { de: "verbindlich", tr: "bağlayıcı" }),
      word("Beşinci", { de: "taktvoll", tr: "incelikli" }),
      word("Altıncı", { de: "der Einwand", tr: "itiraz" }),
      word("Yedinci", { de: "besonnen", tr: "soğukkanlı" }),
      word("Son", { de: "umsichtig", tr: "tedbirli" }),
      { say: [tr("Örnek:"), de("Ich hätte da einen Einwand."), tr("Düz kipte 'itirazım var' bir çatışmadır; dilek kipinde bir katkıdır. Tekrar edin:"), de("Ich hätte da einen Einwand")], expect: repeat("Ich hätte da einen Einwand") },
      { say: [tr("Sıra sende: 'İşin başka türlü olduğu da savunulabilir.'")], expect: produce("Man könnte auch argumentieren, dass es anders liegt", [tr("Belirsiz özne ve dilek kipi; yan cümlede fiil sonda:"), de("Man könnte auch argumentieren, dass es anders liegt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Tüm saygımla, buna katılamıyorum.'")], expect: produce("Bei allem Respekt, dem kann ich nicht zustimmen", [tr("Bu fiil yönelme hâli ister; tümleç öne alınmış:"), de("Bei allem Respekt, dem kann ich nicht zustimmen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunu biraz yumuşatmak isterim.'")], expect: produce("Das würde ich gern etwas relativieren", [tr("Nesne öne alınmış, dilek kipi ikinci sırada:"), de("Das würde ich gern etwas relativieren."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Bei allem Respekt, dem kann ich nicht zustimmen."), tr("cümlesi doğru mu?")], expect: truefalse("Bei allem Respekt, dem kann ich nicht zustimmen.", true, [tr("Doğru. Kalıplaşmış giriş, ardından yönelme hâlindeki tümleç öne alınmış ve fiil ikinci sırada.")]) },
      { say: [tr("Son: 'Bir çekincem var.'")], expect: produce("Ich habe da einen Vorbehalt", [tr("Belirtisiz eril belirtme hâlinde:"), de("Ich habe da einen Vorbehalt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir öneriye karşı çıkacaksın — ama masayı devirmeden.")] },
    ],
    roleplay: {
      scene: "Bir toplantıda üstünün önerisine katılmıyorsun. Önce anladığını göster, itirazını dilek kipiyle koy, çekinceni gerekçelendir ve bir alternatif sun. Reddedilirsen tavrını koru ama ilişkiyi bozma.",
      partner: "önerisine bağlı, itirazı kişisel almaya meyilli bir üst yönetici",
      opening: "Ich habe den Eindruck, Sie sind nicht überzeugt. Sagen Sie es ruhig geradeheraus — was stört Sie?",
      openingTr: "İkna olmadığınız izlenimindeyim. Rahatça açık açık söyleyin — sizi rahatsız eden ne?",
      goal: "İtiraz gerekçesiyle ve incelikle söylenmiş, bir alternatif sunulmuş ve konuşma ilişkiyi bozmadan bir sonuca bağlanmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-zwischen-zeilen",
    icon: "book",
    level: "C1",
    course: "de",
    title: "Zwischen den Zeilen",
    titleTr: "Satır arası okuma",
    summary: "Söylenenle kastedilen arasındaki farkı parçacıklardan sezmeyi öğretir.",
    minutes: 14,
    focusId: "Modalpartikeln",
    vocab: [
      { de: "die Andeutung", tr: "ima" },
      { de: "eigentlich", tr: "aslında" },
      { de: "an sich", tr: "esasen" },
      { de: "unterschwellig", tr: "üstü kapalı" },
      { de: "heraushören", tr: "sezmek (tondan)" },
      { de: "die Perspektive", tr: "bakış açısı" },
      { de: "nachvollziehen", tr: "anlamak" },
      { de: "die Schlussfolgerung", tr: "çıkarım" },
    ],
    patterns: [
      { de: "Das ist ja interessant.", tr: "ton: şaşkınlık ya da ironi" },
      { de: "Eigentlich … / An sich …", tr: "kabul edip çekince koyar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün Almancanın en sinsi tarafı: aynı cümle, iki anlam. Farkı taşıyan şey küçük kelimeler ve ton. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir örnek:"), de("Eigentlich ist die Idee gut."), tr("Kulağa övgü gibi geliyor ama 'eigentlich' bir 'ama' vaat eder. C1'de bunu duymak da kurmak da senden bekleniyor. Önce kelimeler.")] },
      word("İlk", { de: "die Andeutung", tr: "ima" }),
      word("İkinci", { de: "eigentlich", tr: "aslında" }),
      word("Üçüncü", { de: "an sich", tr: "esasen" }),
      word("Dördüncü", { de: "unterschwellig", tr: "üstü kapalı" }),
      word("Beşinci", { de: "heraushören", tr: "sezmek (tondan)" }),
      word("Altıncı", { de: "die Perspektive", tr: "bakış açısı" }),
      word("Yedinci", { de: "nachvollziehen", tr: "anlamak" }),
      word("Son", { de: "die Schlussfolgerung", tr: "çıkarım" }),
      { say: [tr("Örnek:"), de("Das ist ja interessant."), tr("Tekrar edin:"), de("Das ist ja interessant")], expect: repeat("Das ist ja interessant") },
      { say: [tr("Sıra sende: 'Aslında bunu başka türlü düşünmüştüm.'")], expect: produce("Eigentlich hatte ich mir das anders vorgestellt", [tr("Zarf başta olunca fiil ikinci sıraya geçer:"), de("Eigentlich hatte ich mir das anders vorgestellt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Esasen fikir iyi.'")], expect: produce("An sich ist die Idee gut", [tr("Kalıplaşmış ifade başta, fiil ikinci sırada:"), de("An sich ist die Idee gut."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sesinden bir çekince sezdim.'")], expect: produce("Aus seinem Ton habe ich einen Vorbehalt herausgehört", [tr("Tümleç başta; ayrılabilen ortaç en sonda:"), de("Aus seinem Ton habe ich einen Vorbehalt herausgehört."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Eigentlich ich hatte mir das anders vorgestellt."), tr("cümlesi doğru mu?")], expect: truefalse("Eigentlich ich hatte mir das anders vorgestellt.", false, [tr("Cümle bir zarfla başlayınca çekimli fiil ikinci sıraya gelir:"), de("Eigentlich hatte ich mir das anders vorgestellt.")]) },
      { say: [tr("Son: 'Bu bir imaydı, suçlama değil.'")], expect: produce("Das war eine Andeutung, kein Vorwurf", [tr("İki isim; ikincisinde olumsuz belirteç:"), de("Das war eine Andeutung, kein Vorwurf."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada üstü kapalı bir eleştiriyi açığa çıkaracaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın sana üstü kapalı bir eleştiri yöneltti. Ne sezdiğini söyle, doğrudan sor, kendi çekinceni de üstü kapalı olmadan koy ve konuyu açıklığa kavuşturun.",
      partner: "doğrudan konuşmaktan kaçınan, ima ile konuşan bir meslektaş",
      opening: "Also, an sich ist dein Entwurf ja gut. Eigentlich hätte ich es nur … na ja, anders gemacht. Verstehst du, was ich meine?",
      openingTr: "Yani, esasen taslağın iyi. Aslında ben sadece… şey, başka türlü yapardım. Ne demek istediğimi anlıyor musun?",
      goal: "İmanın ardındaki eleştiri açıkça söylenmiş, iki taraf da çekincesini doğrudan koymuş ve konu açıklığa kavuşmuş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-krisenkommunikation",
    icon: "media",
    level: "C1",
    course: "de",
    title: "Die Krise kommunizieren",
    titleTr: "Kriz iletişimi",
    summary: "Kurumsal kriz açıklamasının mesafeli, isimleşmiş dilini öğretir.",
    minutes: 14,
    focusId: "Nominalstil",
    vocab: [
      { de: "bedauern", tr: "üzüntü duymak" },
      { de: "einleiten", tr: "başlatmak" },
      { de: "die Aufarbeitung", tr: "inceleme, hesaplaşma" },
      { de: "die Transparenz", tr: "şeffaflık" },
      { de: "das Versäumnis", tr: "ihmal" },
      { de: "abwenden", tr: "savuşturmak" },
      { de: "abstreiten", tr: "inkâr etmek" },
      { de: "eskalieren", tr: "çığırından çıkmak" },
    ],
    patterns: [
      { de: "Wir bedauern … zutiefst.", tr: "kurumsal üzüntü" },
      { de: "Maßnahmen wurden eingeleitet.", tr: "failsiz eylem bildirimi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kötü haberi kurum adına vereceğiz. Bu dilin iki işi var: sorumluluğu kabul etmek ve paniği büyütmemek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bunu isimleşme ve edilgen birlikte yapıyor: 'önlem aldık' değil, 'önlemler başlatıldı'. Kim yaptığı silinince olay kurumsallaşır. Önce kelimeler.")] },
      word("İlk", { de: "bedauern", tr: "üzüntü duymak" }),
      word("İkinci", { de: "einleiten", tr: "başlatmak" }),
      word("Üçüncü", { de: "die Aufarbeitung", tr: "inceleme" }),
      word("Dördüncü", { de: "die Transparenz", tr: "şeffaflık" }),
      word("Beşinci", { de: "das Versäumnis", tr: "ihmal" }),
      word("Altıncı", { de: "abwenden", tr: "savuşturmak" }),
      word("Yedinci", { de: "abstreiten", tr: "inkâr etmek" }),
      word("Son", { de: "eskalieren", tr: "çığırından çıkmak" }),
      { say: [tr("Örnek:"), de("Wir bedauern den Vorfall zutiefst."), tr("Tekrar edin:"), de("Wir bedauern den Vorfall zutiefst")], expect: repeat("Wir bedauern den Vorfall zutiefst") },
      { say: [tr("Sıra sende: 'Gerekli önlemler başlatıldı.'")], expect: produce("Die erforderlichen Maßnahmen wurden eingeleitet", [tr("Belirtili çoğulda sıfat -en ekini alır; edilgen geçmiş zamanda:"), de("Die erforderlichen Maßnahmen wurden eingeleitet."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İhmali kabul ediyoruz.'")], expect: produce("Wir räumen das Versäumnis ein", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Wir räumen das Versäumnis ein."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Olayın incelenmesi sürüyor.'")], expect: produce("Die Aufarbeitung des Vorfalls läuft", [tr("İki isim tamlamayla bağlanır; eril isim -s eki alır:"), de("Die Aufarbeitung des Vorfalls läuft."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die erforderliche Maßnahmen wurden eingeleitet."), tr("cümlesi doğru mu?")], expect: truefalse("Die erforderliche Maßnahmen wurden eingeleitet.", false, [tr("Belirtili çoğulda sıfat -en ekini alır:"), de("Die erforderlichen Maßnahmen wurden eingeleitet.")]) },
      { say: [tr("Son: 'Şeffaflık sağlamak istiyoruz.'")], expect: produce("Wir wollen Transparenz schaffen", [tr("Belirteçsiz soyut isim; mastar sonda:"), de("Wir wollen Transparenz schaffen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir gazeteciye kriz açıklaması yapacaksın.")] },
    ],
    roleplay: {
      scene: "Kurumunda bir aksaklık yaşandı ve bir gazeteci seninle konuşuyor. Üzüntünü bildir, ne olduğunu kurumsal dille anlat, hangi önlemlerin başlatıldığını söyle ve ne zaman bilgi vereceğini belirt.",
      partner: "sorumluyu arayan, isim isteyen ısrarcı bir gazeteci",
      opening: "Wer trägt dafür die Verantwortung? Und sagen Sie mir bitte nicht, dass Maßnahmen eingeleitet wurden.",
      openingTr: "Bunun sorumluluğunu kim taşıyor? Ve lütfen bana önlemlerin başlatıldığını söylemeyin.",
      goal: "Üzüntü bildirilmiş, olay ve alınan önlemler anlatılmış, sorumluluk sorusu savuşturulmadan karşılanmış ve bir sonraki bilgilendirme tarihi verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-verhandlung-c1",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Das Zünglein an der Waage",
    titleTr: "İleri müzakere",
    summary: "Müzakerede konu açmayı, risk üstlenmeyi ve karşılık istemeyi öğretir.",
    minutes: 14,
    focusId: "Funktionsverbgefüge",
    vocab: [
      { de: "zur Sprache bringen", tr: "gündeme getirmek" },
      { de: "in Kauf nehmen", tr: "göze almak" },
      { de: "die Gegenleistung", tr: "karşılık" },
      { de: "ausloten", tr: "yoklamak, sınırlarını ölçmek" },
      { de: "hinauszögern", tr: "sürüncemede bırakmak" },
      { de: "aushandeln", tr: "müzakere etmek" },
      { de: "das Zugeständnis", tr: "taviz" },
      { de: "unnachgiebig", tr: "taviz vermeyen" },
    ],
    patterns: [
      { de: "… zur Sprache bringen", tr: "konuyu masaya koyar" },
      { de: "… in Kauf nehmen", tr: "riski üstlenir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ileri müzakere. B2'de fiyat pazarlığı yapmıştın; C1'de mesele fiyat değil, hangi konunun ne zaman açılacağı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bunun için iki öbek şart: bir konuyu masaya koymak ve bir riski üstlenmek. İkisi de işlev fiili öbeği ve ikisi de sabit. Önce kelimeler.")] },
      word("İlk", { de: "zur Sprache bringen", tr: "gündeme getirmek" }),
      word("İkinci", { de: "in Kauf nehmen", tr: "göze almak" }),
      word("Üçüncü", { de: "die Gegenleistung", tr: "karşılık" }),
      word("Dördüncü", { de: "ausloten", tr: "yoklamak" }),
      word("Beşinci", { de: "hinauszögern", tr: "sürüncemede bırakmak" }),
      word("Altıncı", { de: "aushandeln", tr: "müzakere etmek" }),
      word("Yedinci", { de: "das Zugeständnis", tr: "taviz" }),
      word("Son", { de: "unnachgiebig", tr: "taviz vermeyen" }),
      { say: [tr("Örnek:"), de("Ich möchte einen Punkt zur Sprache bringen."), tr("Tekrar edin:"), de("Ich möchte einen Punkt zur Sprache bringen")], expect: repeat("Ich möchte einen Punkt zur Sprache bringen") },
      { say: [tr("Sıra sende: 'Bu riski göze alıyoruz.'")], expect: produce("Dieses Risiko nehmen wir in Kauf", [tr("Nesne öne alınmış, fiil ikinci sırada, öbek sonda:"), de("Dieses Risiko nehmen wir in Kauf."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Karşılığında ne sunuyorsunuz?'")], expect: produce("Was bieten Sie als Gegenleistung", [tr("Soru zamiri nesne; edat als ile:"), de("Was bieten Sie als Gegenleistung?"), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sınırları yoklamak istiyorum.'")], expect: produce("Ich möchte die Grenzen ausloten", [tr("Nesne ortada; mastar sonda:"), de("Ich möchte die Grenzen ausloten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dieses Risiko nehmen wir in Kauf."), tr("cümlesi doğru mu?")], expect: truefalse("Dieses Risiko nehmen wir in Kauf.", true, [tr("Doğru. Nesne öne alındığı için fiil ikinci sırada duruyor ve öbeğin ismi belirteçsiz, cümlenin sonunda.")]) },
      { say: [tr("Son: 'Kararı daha fazla sürüncemede bırakmayalım.'")], expect: produce("Lassen Sie uns die Entscheidung nicht länger hinauszögern", [tr("lassen ile rica; mastar en sonda:"), de("Lassen Sie uns die Entscheidung nicht länger hinauszögern."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada tıkanmış bir müzakereyi açacaksın.")] },
    ],
    roleplay: {
      scene: "Uzun süredir tıkanmış bir müzakerede yeni bir konuyu masaya koyuyorsun. Konuyu aç, hangi riski üstlendiğini söyle, karşılığında ne istediğini belirt ve bir sonuca ya da yeni bir tura bağla.",
      partner: "deneyimli, sabırlı ve kolay taviz vermeyen bir karşı taraf müzakerecisi",
      opening: "Wir sind an derselben Stelle wie vor drei Wochen. Haben Sie etwas Neues mitgebracht?",
      openingTr: "Üç hafta önceki noktadayız. Yeni bir şey getirdiniz mi?",
      goal: "Yeni bir konu masaya konmuş, üstlenilen risk ve istenen karşılık söylenmiş ve bir sonuca ya da yeni bir tura bağlanmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-fuehrung",
    icon: "star",
    level: "C1",
    course: "de",
    title: "Führen ohne Titel",
    titleTr: "Liderlik dili",
    summary: "Yönlendirmeyi emir vermeden, öneri ve destek diliyle kurmayı öğretir.",
    minutes: 14,
    focusId: "Konjunktiv-II-Diplomatie",
    vocab: [
      { de: "anregen", tr: "önermek, teşvik etmek" },
      { de: "sich empfehlen", tr: "tavsiye edilir olmak" },
      { de: "übertragen", tr: "devretmek" },
      { de: "die Eigenverantwortung", tr: "kendi sorumluluğu" },
      { de: "der Rückhalt", tr: "destek, arka çıkma" },
      { de: "die Befugnis", tr: "yetki" },
      { de: "die Delegation", tr: "yetki devri" },
      { de: "das Ermessen", tr: "takdir yetkisi" },
    ],
    patterns: [
      { de: "Ich würde anregen, … zu …", tr: "yönlendirmeyi öneriye çevirir" },
      { de: "Es empfiehlt sich, … zu …", tr: "kişisiz tavsiye" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünün konusu unvansız liderlik: yetkin olmadığı hâlde yön verebilmek. Bunun dili emir değil, öneri. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki kalıp yeter: biri öneriyi senin ağzından, öteki kişisiz olarak verir. İkisinde de mastar öbeği ve zu var. Önce kelimeler.")] },
      word("İlk", { de: "anregen", tr: "önermek, teşvik etmek" }),
      word("İkinci", { de: "sich empfehlen", tr: "tavsiye edilir olmak" }),
      word("Üçüncü", { de: "übertragen", tr: "devretmek" }),
      word("Dördüncü", { de: "die Eigenverantwortung", tr: "kendi sorumluluğu" }),
      word("Beşinci", { de: "der Rückhalt", tr: "destek, arka çıkma" }),
      word("Altıncı", { de: "die Befugnis", tr: "yetki" }),
      word("Yedinci", { de: "die Delegation", tr: "yetki devri" }),
      word("Son", { de: "das Ermessen", tr: "takdir yetkisi" }),
      { say: [tr("Örnek:"), de("Ich würde anregen, das Thema zu vertagen."), tr("Tekrar edin:"), de("Ich würde anregen, das Thema zu vertagen")], expect: repeat("Ich würde anregen, das Thema zu vertagen") },
      { say: [tr("Sıra sende: 'Bunu bir kez daha gözden geçirmek tavsiye edilir.'")], expect: produce("Es empfiehlt sich, das noch einmal zu prüfen", [tr("Sahte özne ve dönüşlü fiil; mastar öbeği virgülden sonra:"), de("Es empfiehlt sich, das noch einmal zu prüfen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sorumluluğu ekibe devretmek istiyorum.'")], expect: produce("Ich möchte die Verantwortung an das Team übertragen", [tr("Edat belirtme hâli ister; mastar sonda:"), de("Ich möchte die Verantwortung an das Team übertragen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Tam desteğim arkanızda.'")], expect: produce("Sie haben meinen vollen Rückhalt", [tr("Belirtme hâlinde sıfat -en ekini alır:"), de("Sie haben meinen vollen Rückhalt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Es empfiehlt sich, das noch einmal prüfen."), tr("cümlesi doğru mu?")], expect: truefalse("Es empfiehlt sich, das noch einmal prüfen.", false, [tr("Mastar öbeğinde zu gerekir:"), de("Es empfiehlt sich, das noch einmal zu prüfen.")]) },
      { say: [tr("Son: 'Kendi sorumluluk alanını genişletmeni öneririm.'")], expect: produce("Ich würde anregen, deine Eigenverantwortung zu erweitern", [tr("Dilek kipi ana cümlede, mastar öbeği virgülden sonra:"), de("Ich würde anregen, deine Eigenverantwortung zu erweitern."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir ekibi yetkin olmadan yönlendireceksin.")] },
    ],
    roleplay: {
      scene: "Resmî bir yetkin olmadan bir projeyi yürütüyorsun ve ekipten biri işini aksatıyor. Sorunu adlandır, emir vermeden yön ver, sorumluluğu ona bırak ve desteğini belirt.",
      partner: "senin yetkini sorgulayan, ama iyi niyetli bir ekip üyesi",
      opening: "Mit Verlaub — du bist ja formal gar nicht mein Vorgesetzter. Warum sollte ich das jetzt so machen?",
      openingTr: "Kusura bakma ama sen resmen benim amirim değilsin. Bunu neden şimdi böyle yapayım?",
      goal: "Sorun adlandırılmış, emir vermeden bir yön verilmiş, sorumluluk karşı tarafa bırakılmış ve destek sözü verilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-buerojargon",
    icon: "job",
    level: "C1",
    course: "de",
    title: "Bürodeutsch entschlüsselt",
    titleTr: "Ofis jargonu",
    summary: "Ofis Almancasının kalıplarını anlamayı ve gerektiğinde kullanmayı öğretir.",
    minutes: 14,
    focusId: "Nominalstil",
    vocab: [
      { de: "im Nachgang", tr: "sonrasında" },
      { de: "abstimmen", tr: "mutabakat sağlamak" },
      { de: "die Schnittstelle", tr: "kesişim noktası" },
      { de: "aufsetzen", tr: "kurmak (toplantı, belge)" },
      { de: "der Sachstand", tr: "güncel durum" },
      { de: "übermitteln", tr: "iletmek" },
      { de: "der Ausschuss", tr: "komite" },
      { de: "die Tagung", tr: "bilimsel toplantı" },
    ],
    patterns: [
      { de: "Im Nachgang zu …", tr: "sonrasında, ardından" },
      { de: "etwas mit jemandem abstimmen", tr: "mutabakata bağlamak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ofis Almancası — bazen alay konusu olan ama her toplantıda duyacağın dil. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Amacım bunu sevdirmek değil, ÇÖZDÜRMEK: 'Das nehmen wir mit' bir söz değil, bir erteleme. C1'de bunu duymak da kurmak da gerekiyor. Önce kelimeler.")] },
      word("İlk", { de: "im Nachgang", tr: "sonrasında" }),
      word("İkinci", { de: "abstimmen", tr: "mutabakat sağlamak" }),
      word("Üçüncü", { de: "die Schnittstelle", tr: "kesişim noktası" }),
      word("Dördüncü", { de: "aufsetzen", tr: "kurmak (toplantı, belge)" }),
      word("Beşinci", { de: "der Sachstand", tr: "güncel durum" }),
      word("Altıncı", { de: "übermitteln", tr: "iletmek" }),
      word("Yedinci", { de: "der Ausschuss", tr: "komite" }),
      word("Son", { de: "die Tagung", tr: "bilimsel toplantı" }),
      { say: [tr("Örnek:"), de("Im Nachgang zum Termin sende ich Ihnen die Unterlagen."), tr("Tekrar edin:"), de("Im Nachgang zum Termin sende ich Ihnen die Unterlagen")], expect: repeat("Im Nachgang zum Termin sende ich Ihnen die Unterlagen") },
      { say: [tr("Sıra sende: 'Bunu ekiple mutabakata bağlarım.'")], expect: produce("Das stimme ich mit dem Team ab", [tr("Nesne öne alınmış; ayrılabilen önek sonda:"), de("Das stimme ich mit dem Team ab."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bir görüşme ayarlayalım.'")], expect: produce("Lassen Sie uns einen Termin aufsetzen", [tr("lassen ile rica; mastar sonda ve zu almaz:"), de("Lassen Sie uns einen Termin aufsetzen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Burada iki bölümün kesişimi var.'")], expect: produce("Hier liegt die Schnittstelle zwischen zwei Abteilungen", [tr("Edat yönelme hâli ister:"), de("Hier liegt die Schnittstelle zwischen zwei Abteilungen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Lassen Sie uns einen Termin aufzusetzen."), tr("cümlesi doğru mu?")], expect: truefalse("Lassen Sie uns einen Termin aufzusetzen.", false, [tr("lassen fiilinden sonra mastar zu almaz:"), de("Lassen Sie uns einen Termin aufsetzen.")]) },
      { say: [tr("Son bir soru: 'Güncel durum nedir?'")], expect: produce("Wie ist der aktuelle Sachstand", [tr("Soru kelimesi başta, fiil ikinci sırada:"), de("Wie ist der aktuelle Sachstand?"), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada jargonun arkasındaki gerçek anlamı çıkaracaksın.")] },
    ],
    roleplay: {
      scene: "Bir toplantı sonrası bir meslektaşınla konuşuyorsun: toplantıda söylenen jargonun aslında ne anlama geldiğini birlikte çözün, kimin neyi üstlendiğini netleştirin ve bir sonraki adımı kararlaştırın.",
      partner: "jargonu akıcı konuşan ama netleştirmeye açık bir meslektaş",
      opening: "„Das nehmen wir mit und stimmen es im Nachgang ab“ — mal ehrlich, weißt du, wer jetzt was macht?",
      openingTr: "„Bunu bir alalım, sonrasında mutabakata bağlarız“ — dürüst olalım, şu an kimin ne yapacağını biliyor musun?",
      goal: "Jargonun arkasındaki gerçek anlam çözülmüş, kimin neyi üstlendiği netleşmiş ve bir sonraki adım tarihe bağlanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-pitch",
    icon: "chart",
    level: "C1",
    course: "de",
    title: "Der perfekte Pitch",
    titleTr: "Yatırımcı sunumu",
    summary: "Kısa sürede ikna eden retorik yapıyı kurmayı öğretir.",
    minutes: 14,
    focusId: "Rhetorische-Mittel",
    vocab: [
      { de: "der Clou", tr: "püf noktası" },
      { de: "das Alleinstellungsmerkmal", tr: "ayırt edici özellik" },
      { de: "skalieren", tr: "ölçeklenmek" },
      { de: "der Bedarf", tr: "ihtiyaç" },
      { de: "zünden", tr: "tutmak, etkisini göstermek" },
      { de: "die Strategie", tr: "strateji" },
      { de: "belegen", tr: "belgelemek" },
      { de: "die Überzeugungskraft", tr: "ikna gücü" },
    ],
    patterns: [
      { de: "Stellen Sie sich vor, …", tr: "dinleyiciyi sahneye alır" },
      { de: "Der Clou daran ist, dass …", tr: "püf noktasını açar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Üç dakikan var ve karşındaki kişi para verecek ya da vermeyecek. Bu konuşmanın bir mimarisi var. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sıra şu: dinleyiciyi sahneye al, sorunu göster, çözümü söyle, farkını açıkla, 'neden şimdi' sorusunu cevapla. Bugün bunun cümlelerini kuracağız. Önce kelimeler.")] },
      word("İlk", { de: "der Clou", tr: "püf noktası" }),
      word("İkinci", { de: "das Alleinstellungsmerkmal", tr: "ayırt edici özellik" }),
      word("Üçüncü", { de: "skalieren", tr: "ölçeklenmek" }),
      word("Dördüncü", { de: "der Bedarf", tr: "ihtiyaç" }),
      word("Beşinci", { de: "zünden", tr: "tutmak, etkisini göstermek" }),
      word("Altıncı", { de: "die Strategie", tr: "strateji" }),
      word("Yedinci", { de: "belegen", tr: "belgelemek" }),
      word("Son", { de: "die Überzeugungskraft", tr: "ikna gücü" }),
      { say: [tr("Örnek:"), de("Stellen Sie sich vor, Sie hätten dieses Problem nie wieder."), tr("Tekrar edin:"), de("Stellen Sie sich vor, Sie hätten dieses Problem nie wieder")], expect: repeat("Stellen Sie sich vor, Sie hätten dieses Problem nie wieder") },
      { say: [tr("Sıra sende: 'İşin püf noktası şu: model kendiliğinden ölçekleniyor.'")], expect: produce("Der Clou daran ist, dass das Modell von selbst skaliert", [tr("Yan cümlede fiil sonda:"), de("Der Clou daran ist, dass das Modell von selbst skaliert."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Neden şimdi? Çünkü ihtiyaç şimdi doğdu.'")], expect: produce("Warum jetzt? Weil der Bedarf jetzt entstanden ist", [tr("Soru ve yan cümleyle cevap; fiil sonda:"), de("Warum jetzt? Weil der Bedarf jetzt entstanden ist."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ayırt edici özelliğimiz hız.'")], expect: produce("Unser Alleinstellungsmerkmal ist die Geschwindigkeit", [tr("Uzun bileşik isim özne olarak başta:"), de("Unser Alleinstellungsmerkmal ist die Geschwindigkeit."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Clou daran ist, dass das Modell von selbst skaliert."), tr("cümlesi doğru mu?")], expect: truefalse("Der Clou daran ist, dass das Modell von selbst skaliert.", true, [tr("Doğru. Edat zamirle kaynaşmış ve yan cümlenin çekimli fiili en sonda duruyor.")]) },
      { say: [tr("Son: 'Fikir dinleyicide tuttu.'")], expect: produce("Die Idee hat beim Publikum gezündet", [tr("Edat yönelme hâlinde; ortaç sonda:"), de("Die Idee hat beim Publikum gezündet."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada üç dakikalık bir sunum yapacaksın.")] },
    ],
    roleplay: {
      scene: "Bir yatırımcıya üç dakikalık sunum yapıyorsun. Dinleyiciyi sahneye al, sorunu ve çözümü söyle, ayırt edici özelliğini açıkla, 'neden şimdi' sorusunu cevapla ve bir sonraki adımı iste.",
      partner: "kısa kesen, sert soru soran bir yatırımcı",
      opening: "Sie haben drei Minuten. Und bitte fangen Sie nicht mit der Firmengeschichte an — womit lösen Sie welches Problem?",
      openingTr: "Üç dakikanız var. Ve lütfen şirket tarihçesiyle başlamayın — hangi sorunu neyle çözüyorsunuz?",
      goal: "Sorun, çözüm ve ayırt edici özellik anlatılmış, 'neden şimdi' cevaplanmış ve somut bir sonraki adım istenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-konfliktmoderation",
    icon: "handshake",
    level: "C1",
    course: "de",
    title: "Zwischen den Fronten",
    titleTr: "Arabuluculuk",
    summary: "İki tarafın sözünü tarafsız aktarıp ortak zemin aramayı öğretir.",
    minutes: 14,
    focusId: "Konjunktiv-I-Rede",
    vocab: [
      { de: "schlichten", tr: "arabuluculuk etmek" },
      { de: "die Gegenseite", tr: "karşı taraf" },
      { de: "der Standpunkt", tr: "duruş, görüş" },
      { de: "sich festfahren", tr: "tıkanmak" },
      { de: "die Annäherung", tr: "yakınlaşma" },
      { de: "beschwichtigen", tr: "yatıştırmak" },
      { de: "der Unterhändler", tr: "müzakereci" },
      { de: "erörtern", tr: "ele almak" },
    ],
    patterns: [
      { de: "Herr X sagt, er habe …", tr: "tarafsız aktarım" },
      { de: "Worauf können wir uns einigen?", tr: "ortak zemin arar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve en zoru: iki tarafın arasında durmak. Arabulucunun dili özeldir — söyleneni aktarır ama onaylamaz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bunu yapan şey aktarım kipi. 'Bilmiyormuş' dediğinde tarafsızsın; 'bilmiyordu' dersen bir tarafı tutmuş olursun. C1'de bu fark ölçülüyor. Önce kelimeler.")] },
      word("İlk", { de: "schlichten", tr: "arabuluculuk etmek" }),
      word("İkinci", { de: "die Gegenseite", tr: "karşı taraf" }),
      word("Üçüncü", { de: "der Standpunkt", tr: "duruş, görüş" }),
      word("Dördüncü", { de: "sich festfahren", tr: "tıkanmak" }),
      word("Beşinci", { de: "die Annäherung", tr: "yakınlaşma" }),
      word("Altıncı", { de: "beschwichtigen", tr: "yatıştırmak" }),
      word("Yedinci", { de: "der Unterhändler", tr: "müzakereci" }),
      word("Son", { de: "erörtern", tr: "ele almak" }),
      { say: [tr("Örnek:"), de("Herr Klein sagt, er habe nichts davon gewusst."), tr("Tekrar edin:"), de("Herr Klein sagt, er habe nichts davon gewusst")], expect: repeat("Herr Klein sagt, er habe nichts davon gewusst") },
      { say: [tr("Sıra sende: 'Bayan Yıldız ise bunun böyle kararlaştırıldığını söylüyor.'")], expect: produce("Frau Yıldız hingegen meint, das sei so vereinbart worden", [tr("Aktarım kipinde edilgen geçmiş; fiil öbeği sonda:"), de("Frau Yıldız hingegen meint, das sei so vereinbart worden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Görüşmeler tıkandı.'")], expect: produce("Die Gespräche haben sich festgefahren", [tr("Dönüşlü fiil; ortaç en sonda:"), de("Die Gespräche haben sich festgefahren."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Ne üzerinde anlaşabiliriz?'")], expect: produce("Worauf können wir uns einigen", [tr("Edat soru zamiriyle kaynaşır; dönüşlü zamir ortada:"), de("Worauf können wir uns einigen?"), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Herr Klein sagt, er hat nichts davon gewusst."), tr("cümlesi doğru mu?")], expect: truefalse("Herr Klein sagt, er hat nichts davon gewusst.", false, [tr("Arabulucu söyleneni aktarır, onaylamaz — bunun için aktarım kipi gerekir:"), de("Herr Klein sagt, er habe nichts davon gewusst.")]) },
      { say: [tr("Son: 'İlk bir yakınlaşma görüyorum.'")], expect: produce("Ich sehe eine erste Annäherung", [tr("Belirtisiz dişil belirtme hâlinde sıfat -e ekini alır:"), de("Ich sehe eine erste Annäherung."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada iki taraf arasında arabuluculuk yapacaksın.")] },
    ],
    roleplay: {
      scene: "İki meslektaş arasında arabuluculuk yapıyorsun. Her iki tarafın söylediğini tarafsız aktar, ortak noktayı bul, bir öneri getir ve iki tarafın da kabul edeceği bir adımda anlaştır.",
      partner: "haklı olduğundan emin, öbür tarafı dinlemek istemeyen bir meslektaş",
      opening: "Ich sage Ihnen gleich: Ich habe nichts falsch gemacht. Was hat die andere Seite denn behauptet?",
      openingTr: "Size baştan söyleyeyim: Ben yanlış bir şey yapmadım. Karşı taraf ne iddia etti?",
      goal: "İki tarafın görüşü tarafsız aktarılmış, ortak nokta bulunmuş ve iki tarafın da kabul ettiği bir adımda anlaşılmış olur.",
      minTurns: 9,
    },
  },
];
