import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * C1 · Modül 6 — Hukuk ve sözleşme dili (051–060).
 *
 * Hukuk Almancası ayrı bir lehçe gibi çalışıyor ve öğrenciyi ilk kez gerçek
 * bir SONUÇLA karşı karşıya bırakıyor: bir sözleşme maddesini yanlış anlamak
 * dilbilgisi hatası değil, para ve hak kaybı. Bu yüzden modül anlamayı
 * konuşmaktan önce koyuyor — dersler önce metni çözmeyi, sonra kendi
 * cümleni kurmayı öğretiyor.
 *
 * Üç araç dönüyor: kişisiz kipli edilgen ("Es wird darauf hingewiesen…",
 * "Die Haftung ist ausgeschlossen"), işlev fiili öbekleri (Anspruch erheben,
 * in Verzug geraten, in Haftung nehmen) ve tam dolaylı aktarım (avukatın,
 * tanığın, mahkemenin sözü). Üçü de daha önce öğrenildi; buradaki yenilik
 * hepsinin aynı cümlede ve yüksek bedelle bulunması.
 *
 * Doğru/yanlış maddeleri bilerek "pahalı" hatalara ayrıldı: tamlama eki,
 * yanlış edat hâli, karıştırılan fiil çifti (vorliegen/bevorstehen) ve
 * tutanakta düz kip kullanmak.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deC1B06: Lesson[] = [
  {
    id: "de-c1-vertragsklauseln",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Das Kleingedruckte",
    titleTr: "Sözleşme okuma",
    summary: "Sözleşme maddelerinin isimleşmiş dilini çözmeyi öğretir.",
    minutes: 14,
    focusId: "Nominalstil",
    vocab: [
      { de: "vorbehaltlich", tr: "…-in kaydıyla" },
      { de: "der Verzug", tr: "temerrüt, gecikme" },
      { de: "die Klausel", tr: "madde" },
      { de: "das Kleingedruckte", tr: "küçük yazılar" },
      { de: "die Laufzeit", tr: "süre" },
      { de: "die Verfügung", tr: "talimat" },
      { de: "binden", tr: "bağlamak" },
      { de: "beitreten", tr: "taraf olmak" },
    ],
    patterns: [
      { de: "vorbehaltlich + Genitiv", tr: "…-in kaydıyla" },
      { de: "im Falle des Verzugs", tr: "gecikme hâlinde" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: hukuk dili. Ve burada bir şey değişiyor — bir maddeyi yanlış anlamak dilbilgisi hatası değil, para kaybı. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sözleşme dili neredeyse tamamen isimleşmiştir ve tamlama hâli her yerdedir. Eksik bir ek, cümleyi çözemez hâle getirir. Önce kelimeler.")] },
      word("İlk", { de: "vorbehaltlich", tr: "…-in kaydıyla" }),
      word("İkinci", { de: "der Verzug", tr: "temerrüt, gecikme" }),
      word("Üçüncü", { de: "die Klausel", tr: "madde" }),
      word("Dördüncü", { de: "das Kleingedruckte", tr: "küçük yazılar" }),
      word("Beşinci", { de: "die Laufzeit", tr: "süre" }),
      word("Altıncı", { de: "die Verfügung", tr: "talimat" }),
      word("Yedinci", { de: "binden", tr: "bağlamak" }),
      word("Son", { de: "beitreten", tr: "taraf olmak" }),
      { say: [tr("Örnek:"), de("Vorbehaltlich der Zustimmung des Betriebsrats gilt die Regelung ab Januar."), tr("Tekrar edin:"), de("Vorbehaltlich der Zustimmung des Betriebsrats gilt die Regelung ab Januar")], expect: repeat("Vorbehaltlich der Zustimmung des Betriebsrats gilt die Regelung ab Januar") },
      { say: [tr("Sıra sende: 'Gecikme hâlinde faiz işler.'")], expect: produce("Im Falle des Verzugs fallen Zinsen an", [tr("Tamlama hâlinde eril isim -s eki alır; ayrılabilen önek sonda:"), de("Im Falle des Verzugs fallen Zinsen an."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Küçük yazıları okumak gerekir.'")], expect: produce("Man muss das Kleingedruckte lesen", [tr("İsimleşmiş sıfat belirtme hâlinde:"), de("Man muss das Kleingedruckte lesen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Süre iki yıl.'")], expect: produce("Die Laufzeit beträgt zwei Jahre", [tr("Bu fiil ölçü bildirir ve belirtme hâli ister:"), de("Die Laufzeit beträgt zwei Jahre."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Im Falle des Verzug fallen Zinsen an."), tr("cümlesi doğru mu?")], expect: truefalse("Im Falle des Verzug fallen Zinsen an.", false, [tr("Tamlama hâlinde eril isim -s ekini alır; sözleşme dilinde bu ek atlanamaz:"), de("Im Falle des Verzugs fallen Zinsen an.")]) },
      { say: [tr("Son: 'Bu maddeyi anlamıyorum.'")], expect: produce("Diese Klausel verstehe ich nicht", [tr("Nesne öne alınmış; fiil ikinci sırada:"), de("Diese Klausel verstehe ich nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir sözleşmenin maddelerini sorgulayacaksın.")] },
    ],
    roleplay: {
      scene: "İmzalamak üzere olduğun sözleşmede anlamadığın maddeler var. Karşı tarafa sor: hangi madde ne anlama geliyor, süre ne kadar, gecikmede ne oluyor ve hangi maddenin değiştirilmesini istiyorsun.",
      partner: "sözleşmeyi savunan, 'bu standart madde' diyen bir firma temsilcisi",
      opening: "Das ist unser Standardvertrag — den unterschreiben alle so. Welche Klausel macht Ihnen denn Sorgen?",
      openingTr: "Bu bizim standart sözleşmemiz — herkes böyle imzalıyor. Hangi madde sizi endişelendiriyor?",
      goal: "Anlaşılmayan maddeler açıklanmış, süre ve gecikme sonucu netleşmiş ve en az bir değişiklik talebi iletilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-agb",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Die AGB verstehen",
    titleTr: "Genel şartlar",
    summary: "Genel işlem şartlarının kişisiz kipli edilgen dilini öğretir.",
    minutes: 14,
    focusId: "Passiv-Modal",
    vocab: [
      { de: "der Hinweis", tr: "uyarı, bilgilendirme" },
      { de: "ausgeschlossen", tr: "hariç tutulmuş" },
      { de: "die Haftung", tr: "sorumluluk" },
      { de: "zumutbar", tr: "makul, katlanılabilir" },
      { de: "einbeziehen", tr: "dâhil etmek" },
      { de: "die Rechtfertigung", tr: "haklı çıkarma" },
      { de: "das Pflichtgefühl", tr: "görev duygusu" },
      { de: "verfügen", tr: "resmen karar vermek" },
    ],
    patterns: [
      { de: "Es wird darauf hingewiesen, dass …", tr: "kişisiz uyarı" },
      { de: "Das gilt als vereinbart.", tr: "kabul edilmiş sayılır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün genel şartlar — kimsenin okumadığı ama herkesi bağlayan metin. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bu metinde özne neredeyse hiç yoktur: uyarılır, hariç tutulur, kabul edilmiş sayılır. Bunu çözmek C1'in işi. Önce kelimeler.")] },
      word("İlk", { de: "der Hinweis", tr: "uyarı" }),
      word("İkinci", { de: "ausgeschlossen", tr: "hariç tutulmuş" }),
      word("Üçüncü", { de: "die Haftung", tr: "sorumluluk" }),
      word("Dördüncü", { de: "zumutbar", tr: "makul" }),
      word("Beşinci", { de: "einbeziehen", tr: "dâhil etmek" }),
      word("Altıncı", { de: "die Rechtfertigung", tr: "haklı çıkarma" }),
      word("Yedinci", { de: "das Pflichtgefühl", tr: "görev duygusu" }),
      word("Son", { de: "verfügen", tr: "resmen karar vermek" }),
      { say: [tr("Örnek:"), de("Es wird darauf hingewiesen, dass die Haftung beschränkt ist."), tr("Tekrar edin:"), de("Es wird darauf hingewiesen, dass die Haftung beschränkt ist")], expect: repeat("Es wird darauf hingewiesen, dass die Haftung beschränkt ist") },
      { say: [tr("Sıra sende: 'Zararlar için sorumluluk hariç tutulmuştur.'")], expect: produce("Die Haftung für Schäden ist ausgeschlossen", [tr("Durum edilgeni; edat belirtme hâli ister:"), de("Die Haftung für Schäden ist ausgeschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu şartlar sözleşmeye dâhil edilir.'")], expect: produce("Diese Bedingungen werden in den Vertrag einbezogen", [tr("Bu fiil yön bildirir ve belirtme hâli ister:"), de("Diese Bedingungen werden in den Vertrag einbezogen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bu kabul edilmiş sayılır.'")], expect: produce("Das gilt als vereinbart", [tr("Kalıplaşmış ifade; als artı ortaç:"), de("Das gilt als vereinbart."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Diese Bedingungen werden in dem Vertrag einbezogen."), tr("cümlesi doğru mu?")], expect: truefalse("Diese Bedingungen werden in dem Vertrag einbezogen.", false, [tr("Bu fiilde hareket vardır, o yüzden edat belirtme hâli ister:"), de("Diese Bedingungen werden in den Vertrag einbezogen.")]) },
      { say: [tr("Son: 'Makul olan yapılmalıdır.'")], expect: produce("Zumutbares muss getan werden", [tr("İsimleşmiş sıfat özne; kipli edilgen sonda:"), de("Zumutbares muss getan werden."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir maddenin geçerli olup olmadığını tartışacaksın.")] },
    ],
    roleplay: {
      scene: "Bir hizmetin genel şartlarında sorumluluğu tamamen dışlayan bir madde var. Müşteri hizmetleriyle konuş: maddenin ne dediğini kendi cümlenle söyle, neden fazla geniş olduğunu belirt ve ne talep ettiğini bildir.",
      partner: "maddeyi standart sayan, yetkisi sınırlı bir müşteri hizmetleri sorumlusu",
      opening: "Die Klausel steht in unseren AGB und gilt damit als vereinbart. Worauf möchten Sie hinaus?",
      openingTr: "Madde genel şartlarımızda yer alıyor ve dolayısıyla kabul edilmiş sayılıyor. Neye varmak istiyorsunuz?",
      goal: "Maddenin anlamı kendi cümleyle söylenmiş, neden fazla geniş olduğu belirtilmiş ve somut bir talep iletilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-miete-recht",
    icon: "home",
    level: "C1",
    course: "de",
    title: "Mietminderung?",
    titleTr: "Kiracı hakları",
    summary: "Hak talebini hukuki işlev fiili öbekleriyle kurmayı öğretir.",
    minutes: 14,
    focusId: "Funktionsverbgefüge",
    vocab: [
      { de: "Anspruch erheben", tr: "hak iddia etmek" },
      { de: "in Verzug geraten", tr: "temerrüde düşmek" },
      { de: "die Mietminderung", tr: "kira indirimi" },
      { de: "die Beseitigung", tr: "giderme" },
      { de: "geltend machen", tr: "ileri sürmek" },
      { de: "die Wiedergutmachung", tr: "telafi" },
      { de: "der Rechtsstreit", tr: "hukuki anlaşmazlık" },
      { de: "die Vergeltung", tr: "misilleme" },
    ],
    patterns: [
      { de: "Anspruch auf … erheben", tr: "hak iddia etmek" },
      { de: "eine Frist setzen", tr: "süre vermek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün kiracı hakları. Hukukta bir talep, doğru fiil öbeğiyle söylenmezse talep sayılmaz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Üç öbek işini görür: hak iddia etmek, süre vermek, hakkı ileri sürmek. Üçü de sabit ve üçü de ilk modülde öğrendiğin mantıkta. Önce kelimeler.")] },
      word("İlk", { de: "Anspruch erheben", tr: "hak iddia etmek" }),
      word("İkinci", { de: "in Verzug geraten", tr: "temerrüde düşmek" }),
      word("Üçüncü", { de: "die Mietminderung", tr: "kira indirimi" }),
      word("Dördüncü", { de: "die Beseitigung", tr: "giderme" }),
      word("Beşinci", { de: "geltend machen", tr: "ileri sürmek" }),
      word("Altıncı", { de: "die Wiedergutmachung", tr: "telafi" }),
      word("Yedinci", { de: "der Rechtsstreit", tr: "hukuki anlaşmazlık" }),
      word("Son", { de: "die Vergeltung", tr: "misilleme" }),
      { say: [tr("Örnek:"), de("Ich erhebe Anspruch auf eine Mietminderung."), tr("Tekrar edin:"), de("Ich erhebe Anspruch auf eine Mietminderung")], expect: repeat("Ich erhebe Anspruch auf eine Mietminderung") },
      { say: [tr("Sıra sende: 'Arızanın giderilmesi için süre veriyorum.'")], expect: produce("Für die Beseitigung setze ich eine Frist", [tr("Tümleç başta; fiil ikinci sırada:"), de("Für die Beseitigung setze ich eine Frist."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Haklarımı ileri süreceğim.'")], expect: produce("Meine Rechte werde ich geltend machen", [tr("Nesne öne alınmış; öbek mastar hâlinde sonda:"), de("Meine Rechte werde ich geltend machen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kira indirimi talep ediyorum.'")], expect: produce("Ich fordere eine Mietminderung", [tr("Belirtisiz dişil belirtme hâlinde:"), de("Ich fordere eine Mietminderung."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Vermieter ist in Verzug geraten."), tr("cümlesi doğru mu?")], expect: truefalse("Der Vermieter ist in Verzug geraten.", true, [tr("Doğru. Öbek belirteçsiz, geraten fiili sein ile çekilmiş ve ortaç cümlenin sonunda.")]) },
      { say: [tr("Son: 'Ev sahibi temerrüde düştü.'")], expect: produce("Der Vermieter ist in Verzug geraten", [tr("Durum değişimi sein ile; öbek belirteçsiz:"), de("Der Vermieter ist in Verzug geraten."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada ev sahibinle bir arızayı ve kira indirimini konuşacaksın.")] },
    ],
    roleplay: {
      scene: "Dairende aylardır giderilmeyen bir arıza var. Ev sahibiyle konuş: arızayı ve ne zamandır sürdüğünü bildir, giderilmesi için süre ver, kira indirimi talebini dile getir ve yazılı teyit iste.",
      partner: "sorumluluğu üstlenmekten kaçınan, 'küçük bir şey' diyen bir ev sahibi",
      opening: "Das ist doch eine Kleinigkeit. Wollen Sie deswegen wirklich die Miete kürzen?",
      openingTr: "Küçücük bir şey bu. Bunun için gerçekten kirayı mı kısacaksınız?",
      goal: "Arıza ve süresi bildirilmiş, giderme için süre verilmiş, indirim talebi iletilmiş ve yazılı teyit istenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-arbeitsrecht",
    icon: "office",
    level: "C1",
    course: "de",
    title: "Die Abmahnung",
    titleTr: "İş hukuku sohbeti",
    summary: "Hukuki görüşü aktarım kipiyle nakletmeyi öğretir.",
    minutes: 14,
    focusId: "Konjunktiv-I-Rede",
    vocab: [
      { de: "die Abmahnung", tr: "ihtar" },
      { de: "fristlos", tr: "ihbarsız, derhâl" },
      { de: "der Einspruch", tr: "itiraz" },
      { de: "rechtens", tr: "hukuka uygun" },
      { de: "einlegen", tr: "sunmak (itiraz)" },
      { de: "der Verband", tr: "birlik, sendika" },
      { de: "eingestehen", tr: "kabul etmek" },
      { de: "die Übernahme", tr: "devralma" },
    ],
    patterns: [
      { de: "Der Anwalt sagte, man müsse …", tr: "hukuki görüşü aktarır" },
      { de: "Einspruch einlegen", tr: "itiraz sunmak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün bir avukatın söylediğini başkasına aktaracaksın. Burada aktarım kipi bir üslup değil, sorumluluk sınırı: onun görüşünü kendi hükmün gibi sunamazsın. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de iki terim karışıyor: ihbarsız fesih ile süresine uygun fesih. Aralarındaki fark aylar ve paradır. Önce kelimeler.")] },
      word("İlk", { de: "die Abmahnung", tr: "ihtar" }),
      word("İkinci", { de: "fristlos", tr: "ihbarsız, derhâl" }),
      word("Üçüncü", { de: "der Einspruch", tr: "itiraz" }),
      word("Dördüncü", { de: "rechtens", tr: "hukuka uygun" }),
      word("Beşinci", { de: "einlegen", tr: "sunmak (itiraz)" }),
      word("Altıncı", { de: "der Verband", tr: "birlik, sendika" }),
      word("Yedinci", { de: "eingestehen", tr: "kabul etmek" }),
      word("Son", { de: "die Übernahme", tr: "devralma" }),
      { say: [tr("Örnek:"), de("Der Anwalt sagte, die Abmahnung sei nicht rechtens."), tr("Tekrar edin:"), de("Der Anwalt sagte, die Abmahnung sei nicht rechtens")], expect: repeat("Der Anwalt sagte, die Abmahnung sei nicht rechtens") },
      { say: [tr("Sıra sende: 'Avukat itiraz edilmesi gerektiğini söyledi.'")], expect: produce("Der Anwalt sagte, man müsse Einspruch einlegen", [tr("Aktarım kipinde kip fiili müsse olur; mastar sonda:"), de("Der Anwalt sagte, man müsse Einspruch einlegen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'İhbarsız ve süresine uygun iki ayrı şeydir.'")], expect: produce("Fristlos und fristgerecht sind zwei verschiedene Dinge", [tr("İki zarf özne olarak; fiil çoğul:"), de("Fristlos und fristgerecht sind zwei verschiedene Dinge."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İtirazımı yazılı sundum.'")], expect: produce("Meinen Einspruch habe ich schriftlich eingelegt", [tr("Nesne öne alınmış; ayrılabilen ortaç sonda:"), de("Meinen Einspruch habe ich schriftlich eingelegt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Anwalt sagte, man muss Einspruch einlegen."), tr("cümlesi doğru mu?")], expect: truefalse("Der Anwalt sagte, man muss Einspruch einlegen.", false, [tr("Düz kip görüşü senin hükmün yapar; aktarımda kip fiili de aktarım biçimine girer:"), de("Der Anwalt sagte, man müsse Einspruch einlegen.")]) },
      { say: [tr("Son: 'Bu bence hukuka uygun değil.'")], expect: produce("Das ist meiner Ansicht nach nicht rechtens", [tr("Kalıplaşmış ifade yönelme hâlinde ve isimden sonra:"), de("Das ist meiner Ansicht nach nicht rechtens."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir meslektaşına hukuki görüşü aktaracaksın.")] },
    ],
    roleplay: {
      scene: "Bir meslektaşın ihtar aldı ve panikte. Avukattan duyduklarını aktar, kendi görüşünü ayır, hangi adımın ne zaman atılması gerektiğini söyle ve onu sakinleştir.",
      partner: "panik hâlinde, hemen istifa etmeyi düşünen bir meslektaş",
      opening: "Ich kündige einfach selbst, bevor die mich rauswerfen. Oder was hat dein Anwalt gesagt?",
      openingTr: "Beni atmadan önce kendim istifa edeyim. Yoksa avukatın ne dedi?",
      goal: "Avukatın görüşü aktarım kipiyle nakledilmiş, konuşanın kendi görüşü ayrılmış ve atılacak ilk adım tarihiyle söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-datenschutz-c1",
    icon: "tech",
    level: "C1",
    course: "de",
    title: "Die Einwilligung",
    titleTr: "Veri koruma dili",
    summary: "Veri koruma metinlerinin tamlama yoğun dilini öğretir.",
    minutes: 14,
    focusId: "Nominalstil",
    vocab: [
      { de: "die Verarbeitung", tr: "işleme" },
      { de: "widerruflich", tr: "geri alınabilir" },
      { de: "die Zweckbindung", tr: "amaca bağlılık" },
      { de: "die Löschung", tr: "silme" },
      { de: "die Weitergabe", tr: "üçüncü tarafa aktarım" },
      { de: "steuern", tr: "yönlendirmek" },
      { de: "die Bezeichnung", tr: "adlandırma" },
      { de: "besagen", tr: "şunu söylemek" },
    ],
    patterns: [
      { de: "die Verarbeitung personenbezogener Daten", tr: "tamlamalı terim" },
      { de: "jederzeit widerruflich", tr: "her zaman geri alınabilir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün veri koruma metinleri. Bu metinlerin özelliği tamlama zinciri: bir terim üç isimden oluşabiliyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kritik ayrıntı sıfat eki:"), de("personenbezogener Daten"), tr("— belirteçsiz tamlamada sıfat -er alır. Bunu sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "die Verarbeitung", tr: "işleme" }),
      word("İkinci", { de: "widerruflich", tr: "geri alınabilir" }),
      word("Üçüncü", { de: "die Zweckbindung", tr: "amaca bağlılık" }),
      word("Dördüncü", { de: "die Löschung", tr: "silme" }),
      word("Beşinci", { de: "die Weitergabe", tr: "üçüncü tarafa aktarım" }),
      word("Altıncı", { de: "steuern", tr: "yönlendirmek" }),
      word("Yedinci", { de: "die Bezeichnung", tr: "adlandırma" }),
      word("Son", { de: "besagen", tr: "şunu söylemek" }),
      { say: [tr("Örnek:"), de("Die Verarbeitung personenbezogener Daten ist zweckgebunden."), tr("Tekrar edin:"), de("Die Verarbeitung personenbezogener Daten ist zweckgebunden")], expect: repeat("Die Verarbeitung personenbezogener Daten ist zweckgebunden") },
      { say: [tr("Sıra sende: 'Rıza her zaman geri alınabilir.'")], expect: produce("Die Einwilligung ist jederzeit widerruflich", [tr("Sıfat biçimi; zarf ortada:"), de("Die Einwilligung ist jederzeit widerruflich."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Verilerin silinmesini talep ediyorum.'")], expect: produce("Ich verlange die Löschung der Daten", [tr("İki isim tamlamayla bağlanır:"), de("Ich verlange die Löschung der Daten."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Üçüncü taraflara aktarım hariç tutulmuştur.'")], expect: produce("Eine Weitergabe an Dritte ist ausgeschlossen", [tr("Edat belirtme hâli ister; isimleşmiş sayı sıfatı:"), de("Eine Weitergabe an Dritte ist ausgeschlossen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Verarbeitung personenbezogene Daten ist zweckgebunden."), tr("cümlesi doğru mu?")], expect: truefalse("Die Verarbeitung personenbezogene Daten ist zweckgebunden.", false, [tr("Belirteçsiz tamlamada sıfat -er ekini alır:"), de("Die Verarbeitung personenbezogener Daten ist zweckgebunden.")]) },
      { say: [tr("Son: 'Amaca bağlılık ilkesi geçerlidir.'")], expect: produce("Es gilt der Grundsatz der Zweckbindung", [tr("Sahte özne ile başlayan resmî yapı; tamlama sonda:"), de("Es gilt der Grundsatz der Zweckbindung."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada verilerinin nasıl işlendiğini soracaksın.")] },
    ],
    roleplay: {
      scene: "Bir hizmet sağlayıcıya verilerinin nasıl işlendiğini soruyorsun. Hangi verilerin hangi amaçla işlendiğini, üçüncü taraf aktarımı olup olmadığını sor; rızanı geri çek ve silme talebini ilet.",
      partner: "metinden okuyan, ayrıntıya girmekten kaçınan bir veri koruma sorumlusu",
      opening: "Die Verarbeitung erfolgt auf Grundlage Ihrer Einwilligung. Welche Auskunft benötigen Sie konkret?",
      openingTr: "İşleme, rızanıza dayanarak yapılıyor. Somut olarak hangi bilgiye ihtiyacınız var?",
      goal: "İşlenen veriler ve amaçları öğrenilmiş, üçüncü taraf aktarımı sorulmuş, rıza geri çekilmiş ve silme talebi iletilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-polizei-aussage",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Die Zeugenaussage",
    titleTr: "İfade verme",
    summary: "Tanık ifadesini gerçeğe uygun ve sınırlarını belirterek vermeyi öğretir.",
    minutes: 14,
    focusId: "Konjunktiv-I-Rede",
    vocab: [
      { de: "die Zeugenaussage", tr: "tanık ifadesi" },
      { de: "zu Protokoll geben", tr: "tutanağa geçirmek" },
      { de: "der Tathergang", tr: "olayın seyri" },
      { de: "wahrheitsgemäß", tr: "gerçeğe uygun" },
      { de: "die Erinnerungslücke", tr: "hafıza boşluğu" },
      { de: "die Notwehr", tr: "meşru müdafaa" },
      { de: "das Urteilsvermögen", tr: "muhakeme yetisi" },
      { de: "vortäuschen", tr: "numara yapmak" },
    ],
    patterns: [
      { de: "Ich gebe zu Protokoll, dass …", tr: "resmî ifade" },
      { de: "Er sagte, der Mann sei …", tr: "başkasının sözünü aktarır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün ifade vereceksin. Buradaki dilin iki kuralı var: gördüğünü düz kiple, duyduğunu aktarım kipiyle söyle. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Bir de dürüstlük kalıbı: hatırlamadığını söylemek ifadeyi zayıflatmaz, güçlendirir. Önce kelimeler.")] },
      word("İlk", { de: "die Zeugenaussage", tr: "tanık ifadesi" }),
      word("İkinci", { de: "zu Protokoll geben", tr: "tutanağa geçirmek" }),
      word("Üçüncü", { de: "der Tathergang", tr: "olayın seyri" }),
      word("Dördüncü", { de: "wahrheitsgemäß", tr: "gerçeğe uygun" }),
      word("Beşinci", { de: "die Erinnerungslücke", tr: "hafıza boşluğu" }),
      word("Altıncı", { de: "die Notwehr", tr: "meşru müdafaa" }),
      word("Yedinci", { de: "das Urteilsvermögen", tr: "muhakeme yetisi" }),
      word("Son", { de: "vortäuschen", tr: "numara yapmak" }),
      { say: [tr("Örnek:"), de("Ich gebe zu Protokoll, dass ich den Wagen gesehen habe."), tr("Tekrar edin:"), de("Ich gebe zu Protokoll, dass ich den Wagen gesehen habe")], expect: repeat("Ich gebe zu Protokoll, dass ich den Wagen gesehen habe") },
      { say: [tr("Sıra sende, bu kez duyduğunu aktar: 'Adamın uzun boylu olduğunu söyledi.'")], expect: produce("Er sagte, der Mann sei groß gewesen", [tr("Aktarım kipinde geçmiş; ortaç ve sein sonda:"), de("Er sagte, der Mann sei groß gewesen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Olayın seyrini gerçeğe uygun anlattım.'")], expect: produce("Den Tathergang habe ich wahrheitsgemäß geschildert", [tr("Nesne öne alınmış; ortaç sonda:"), de("Den Tathergang habe ich wahrheitsgemäß geschildert."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Orada bir hafıza boşluğum var.'")], expect: produce("Da habe ich eine Erinnerungslücke", [tr("Yer zarfı başta; fiil ikinci sırada:"), de("Da habe ich eine Erinnerungslücke."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Er sagte, der Mann sei groß gewesen."), tr("cümlesi doğru mu?")], expect: truefalse("Er sagte, der Mann sei groß gewesen.", true, [tr("Doğru. Duyulan söz aktarım kipiyle verilmiş ve geçmiş biçimi ortaç ile sein birleşimiyle kurulmuş.")]) },
      { say: [tr("Son: 'Bunu tutanağa geçirmek istiyorum.'")], expect: produce("Das möchte ich zu Protokoll geben", [tr("Nesne öne alınmış; öbek mastar hâlinde sonda:"), de("Das möchte ich zu Protokoll geben."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir olayla ilgili ifade vereceksin.")] },
    ],
    roleplay: {
      scene: "Tanık olduğun bir olayla ilgili ifade veriyorsun. Kendi gördüğünü düz kiple, başkasından duyduğunu aktarım kipiyle söyle; hatırlamadığın yerleri açıkça belirt ve ifadeni tutanağa geçirt.",
      partner: "kesin cevap isteyen, ayrıntı üstüne giden bir memur",
      opening: "Bitte nur, was Sie selbst gesehen haben. Also: Was genau haben Sie beobachtet?",
      openingTr: "Lütfen yalnızca kendi gördüklerinizi. Yani: Tam olarak neyi gözlemlediniz?",
      goal: "Görülen ile duyulan ayrı ayrı aktarılmış, hatırlanmayan noktalar açıkça belirtilmiş ve ifade tutanağa geçirilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-versicherungsfall",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Der strittige Fall",
    titleTr: "Sigorta ihtilafı",
    summary: "İmtiyaz bağlaçlarıyla ihtilaflı bir talebi savunmayı öğretir.",
    minutes: 14,
    focusId: "Konzessive-Konnektoren",
    vocab: [
      { de: "wenngleich", tr: "her ne kadar" },
      { de: "gleichwohl", tr: "yine de" },
      { de: "sich vorbehalten", tr: "hakkını saklı tutmak" },
      { de: "der Deckungsumfang", tr: "teminat kapsamı" },
      { de: "die Obliegenheit", tr: "yükümlülük" },
      { de: "das Ministerium", tr: "bakanlık" },
      { de: "unterbringen", tr: "barındırmak" },
      { de: "das Dilemma", tr: "ikilem" },
    ],
    patterns: [
      { de: "Wenngleich …, besteht …", tr: "kabul edip talebi korur" },
      { de: "Wir behalten uns … vor.", tr: "hakkı saklı tutar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün sigortayla ihtilaf. Bu yazışmanın dili imtiyaz bağlaçlarıyla dolu: kabul eder gibi görünüp talebi korur. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki bağlaç yeter ve ikisi de resmîdir. Birincisi yan cümle kurar, ikincisi ana cümlenin başında durur. Önce kelimeler.")] },
      word("İlk", { de: "wenngleich", tr: "her ne kadar" }),
      word("İkinci", { de: "gleichwohl", tr: "yine de" }),
      word("Üçüncü", { de: "sich vorbehalten", tr: "hakkını saklı tutmak" }),
      word("Dördüncü", { de: "der Deckungsumfang", tr: "teminat kapsamı" }),
      word("Beşinci", { de: "die Obliegenheit", tr: "yükümlülük" }),
      word("Altıncı", { de: "das Ministerium", tr: "bakanlık" }),
      word("Yedinci", { de: "unterbringen", tr: "barındırmak" }),
      word("Son", { de: "das Dilemma", tr: "ikilem" }),
      { say: [tr("Örnek:"), de("Wenngleich der Schaden gemeldet wurde, besteht kein Anspruch."), tr("Tekrar edin:"), de("Wenngleich der Schaden gemeldet wurde, besteht kein Anspruch")], expect: repeat("Wenngleich der Schaden gemeldet wurde, besteht kein Anspruch") },
      { say: [tr("Sıra sende: 'Yine de bir talep hakkı var.'")], expect: produce("Gleichwohl besteht ein Anspruch", [tr("Bağlaç ilk öğe; fiil ikinci sırada:"), de("Gleichwohl besteht ein Anspruch."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Hakkımızı saklı tutuyoruz.'")], expect: produce("Wir behalten uns das Recht vor", [tr("Dönüşlü zamir yönelme hâlinde; ayrılabilen önek sonda:"), de("Wir behalten uns das Recht vor."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Teminat kapsamı sınırlı.'")], expect: produce("Der Deckungsumfang ist begrenzt", [tr("Kısa hüküm cümlesi:"), de("Der Deckungsumfang ist begrenzt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Wenngleich der Schaden wurde gemeldet, besteht kein Anspruch."), tr("cümlesi doğru mu?")], expect: truefalse("Wenngleich der Schaden wurde gemeldet, besteht kein Anspruch.", false, [tr("Bu bağlaç yan cümle kurar; çekimli fiil sona gider:"), de("Wenngleich der Schaden gemeldet wurde, besteht kein Anspruch.")]) },
      { say: [tr("Son: 'Yükümlülük yerine getirilmedi.'")], expect: produce("Die Obliegenheit wurde nicht erfüllt", [tr("Edilgen geçmiş zaman; olumsuzluk ortaçtan önce:"), de("Die Obliegenheit wurde nicht erfüllt."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada reddedilen bir hasar talebini savunacaksın.")] },
    ],
    roleplay: {
      scene: "Sigorta hasar talebini reddetti. Temsilciyle konuş: ret gerekçesini öğren, kabul ettiğin noktayı söyle, yine de talebini koru ve bir sonraki adımı bildir.",
      partner: "gerekçesini maddelerle savunan, kolay geri adım atmayan bir sigorta temsilcisi",
      opening: "Der Fall ist geprüft: Die Obliegenheit wurde nicht erfüllt, deshalb besteht kein Anspruch. Was möchten Sie einwenden?",
      openingTr: "Dosya incelendi: Yükümlülük yerine getirilmemiş, dolayısıyla talep hakkı yok. Neye itiraz etmek istersiniz?",
      goal: "Ret gerekçesi öğrenilmiş, kabul edilen nokta söylenmiş, talep korunmuş ve bir sonraki adım bildirilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-buergschaft",
    icon: "handshake",
    level: "C1",
    course: "de",
    title: "Für jemanden bürgen",
    titleTr: "Kefalet",
    summary: "Kefalet üstlenmenin sonuçlarını hukuki dille konuşmayı öğretir.",
    minutes: 14,
    focusId: "Funktionsverbgefüge",
    vocab: [
      { de: "die Bürgschaft", tr: "kefalet" },
      { de: "der Bürge", tr: "kefil" },
      { de: "in Haftung nehmen", tr: "sorumlu tutmak" },
      { de: "sich verpflichten", tr: "yükümlenmek" },
      { de: "das Ausfallrisiko", tr: "temerrüt riski" },
      { de: "die Absicherung", tr: "güvence" },
      { de: "sich revanchieren", tr: "karşılığını vermek" },
      { de: "sich auszahlen", tr: "kendini amorti etmek" },
    ],
    patterns: [
      { de: "eine Bürgschaft übernehmen", tr: "kefil olmak" },
      { de: "in Haftung genommen werden", tr: "sorumlu tutulmak" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü konu bir imzayla hayat değiştirebilir: kefalet. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Almanca burada iki öbek kullanıyor: biri üstlenmeyi, öteki sorumlu tutulmayı anlatıyor. İkincisi edilgendir — çünkü karar senin değildir. Önce kelimeler.")] },
      word("İlk", { de: "die Bürgschaft", tr: "kefalet" }),
      word("İkinci", { de: "der Bürge", tr: "kefil" }),
      word("Üçüncü", { de: "in Haftung nehmen", tr: "sorumlu tutmak" }),
      word("Dördüncü", { de: "sich verpflichten", tr: "yükümlenmek" }),
      word("Beşinci", { de: "das Ausfallrisiko", tr: "temerrüt riski" }),
      word("Altıncı", { de: "die Absicherung", tr: "güvence" }),
      word("Yedinci", { de: "sich revanchieren", tr: "karşılığını vermek" }),
      word("Son", { de: "sich auszahlen", tr: "kendini amorti etmek" }),
      { say: [tr("Örnek:"), de("Ich möchte keine Bürgschaft übernehmen."), tr("Tekrar edin:"), de("Ich möchte keine Bürgschaft übernehmen")], expect: repeat("Ich möchte keine Bürgschaft übernehmen") },
      { say: [tr("Sıra sende: 'Kefil sorumlu tutulabilir.'")], expect: produce("Der Bürge kann in Haftung genommen werden", [tr("Kipli edilgen; sonda ortaç ve werden:"), de("Der Bürge kann in Haftung genommen werden."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bununla yükümlenmiş oluyorsun.'")], expect: produce("Damit verpflichtest du dich", [tr("Dönüşlü zamir özneye uyar:"), de("Damit verpflichtest du dich."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Temerrüt riskini hafife alma.'")], expect: produce("Unterschätze das Ausfallrisiko nicht", [tr("Emir kipi; olumsuzluk sonda:"), de("Unterschätze das Ausfallrisiko nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Damit verpflichtest du sich."), tr("cümlesi doğru mu?")], expect: truefalse("Damit verpflichtest du sich.", false, [tr("Dönüşlü zamir öznenin kişisine uyar; ikinci tekil şahısta dich olur:"), de("Damit verpflichtest du dich.")]) },
      { say: [tr("Son: 'Bunu iyi düşünmek gerekir.'")], expect: produce("Das sollte man sich gut überlegen", [tr("Dönüşlü zamir yönelme hâlinde; mastar sonda:"), de("Das sollte man sich gut überlegen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada senden kefil olman isteniyor.")] },
    ],
    roleplay: {
      scene: "Bir yakının senden kefil olmanı istiyor. Ne anlama geldiğini birlikte konuş: hangi durumda sorumlu tutulursun, risk ne kadar, hangi koşulla kabul edebilirsin ya da neden reddediyorsun.",
      partner: "sana güvenen, riski küçümseyen ve ısrarcı bir yakın",
      opening: "Es ist doch nur eine Formsache, die Bank will das eben sehen. Du musst nie wirklich zahlen — oder glaubst du mir nicht?",
      openingTr: "Sadece formalite, banka görmek istiyor. Gerçekte hiç ödemen gerekmez — yoksa bana inanmıyor musun?",
      goal: "Kefaletin sonuçları anlatılmış, risk konuşulmuş ve kabul ya da ret gerekçesiyle net biçimde söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-einspruch",
    icon: "pen",
    level: "C1",
    course: "de",
    title: "Der Einspruch",
    titleTr: "Resmî itiraz ustalığı",
    summary: "Süreyi koruyan itirazı ve gerekçe sonradan sunmayı öğretir.",
    minutes: 14,
    focusId: "Nominalstil",
    vocab: [
      { de: "fristwahrend", tr: "süreyi koruyan" },
      { de: "die Begründung", tr: "gerekçe" },
      { de: "nachreichen", tr: "sonradan sunmak" },
      { de: "der Bescheid", tr: "karar, tebligat" },
      { de: "die Aufhebung", tr: "iptal" },
      { de: "die Rechtsprechung", tr: "içtihat" },
      { de: "die Buße", tr: "kefaret" },
      { de: "die Institution", tr: "kurum" },
    ],
    patterns: [
      { de: "fristwahrend Einspruch einlegen", tr: "süreyi koruyarak itiraz" },
      { de: "Die Begründung reiche ich nach.", tr: "gerekçeyi sonra sunar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün çok işine yarayacak bir numara: itirazı süre dolmadan sun, gerekçeyi sonra yolla. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Almanca bunun için tek bir sıfat kullanıyor: süreyi koruyan. O kelime yazınca hakkın kaybolmaz. Önce kelimeler.")] },
      word("İlk", { de: "fristwahrend", tr: "süreyi koruyan" }),
      word("İkinci", { de: "die Begründung", tr: "gerekçe" }),
      word("Üçüncü", { de: "nachreichen", tr: "sonradan sunmak" }),
      word("Dördüncü", { de: "der Bescheid", tr: "karar, tebligat" }),
      word("Beşinci", { de: "die Aufhebung", tr: "iptal" }),
      word("Altıncı", { de: "die Rechtsprechung", tr: "içtihat" }),
      word("Yedinci", { de: "die Buße", tr: "kefaret" }),
      word("Son", { de: "die Institution", tr: "kurum" }),
      { say: [tr("Örnek:"), de("Hiermit lege ich fristwahrend Einspruch gegen den Bescheid ein."), tr("Tekrar edin:"), de("Hiermit lege ich fristwahrend Einspruch gegen den Bescheid ein")], expect: repeat("Hiermit lege ich fristwahrend Einspruch gegen den Bescheid ein") },
      { say: [tr("Sıra sende: 'Gerekçeyi sonradan sunacağım.'")], expect: produce("Die Begründung reiche ich nach", [tr("Nesne öne alınmış; ayrılabilen önek sonda:"), de("Die Begründung reiche ich nach."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kararın iptalini talep ediyorum.'")], expect: produce("Ich beantrage die Aufhebung des Bescheids", [tr("İki isim tamlamayla bağlanır; eril isim -s eki alır:"), de("Ich beantrage die Aufhebung des Bescheids."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İtiraz süreyi koruyacak biçimde sunuldu.'")], expect: produce("Der Einspruch wurde fristwahrend eingelegt", [tr("Edilgen geçmiş zaman; ayrılabilen ortaç sonda:"), de("Der Einspruch wurde fristwahrend eingelegt."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Dem Bescheid widerspreche ich."), tr("cümlesi doğru mu?")], expect: truefalse("Dem Bescheid widerspreche ich.", true, [tr("Doğru. Bu fiil yönelme hâli ister ve tümleç öne alındığı için fiil ikinci sırada duruyor.")]) },
      { say: [tr("Son: 'Tebligata itiraz ediyorum.'")], expect: produce("Dem Bescheid widerspreche ich", [tr("Yönelme hâlindeki tümleç başta:"), de("Dem Bescheid widerspreche ich."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir karara itiraz edeceksin.")] },
    ],
    roleplay: {
      scene: "Bir kurumdan aldığın karara itiraz edeceksin ama süre daralıyor. Danışma masasıyla konuş: süreyi koruyacak itirazı nasıl sunacağını sor, gerekçeyi ne zamana kadar tamamlaman gerektiğini öğren ve teyit iste.",
      partner: "usule sıkı bağlı, form numarası veren bir kurum görevlisi",
      opening: "Die Frist läuft in zwei Tagen ab. Haben Sie Ihre Begründung denn schon fertig?",
      openingTr: "Süre iki gün sonra doluyor. Gerekçeniz hazır mı?",
      goal: "Süreyi koruyan itirazın nasıl sunulacağı öğrenilmiş, gerekçe için son tarih netleşmiş ve teyit sözü alınmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-gericht",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Vor Gericht",
    titleTr: "Duruşma sahnesi",
    summary: "Duruşma dilini ve tutanak aktarımını anlamayı öğretir.",
    minutes: 14,
    focusId: "Konjunktiv-I-Rede",
    vocab: [
      { de: "aussagen", tr: "ifade vermek" },
      { de: "das Urteil", tr: "karar, hüküm" },
      { de: "verkünden", tr: "ilan etmek" },
      { de: "die Kammer", tr: "heyet, daire" },
      { de: "die Verhandlung", tr: "duruşma" },
      { de: "die Haftanstalt", tr: "cezaevi" },
      { de: "bestechen", tr: "rüşvet vermek" },
      { de: "vorbestraft", tr: "sabıkalı" },
    ],
    patterns: [
      { de: "Der Zeuge gab an, er habe …", tr: "tutanak aktarımı" },
      { de: "Die Verhandlung wird vertagt.", tr: "duruşma ertelenir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi ve en resmî sahnesi: duruşma. Burada her cümlenin kaynağı belirtilir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Tutanakta hiç kimse 'dedi ki şöyleydi' demez; herkes aktarım kipiyle aktarılır. Bir de yan cümle dizilimi burada affetmez. Önce kelimeler.")] },
      word("İlk", { de: "aussagen", tr: "ifade vermek" }),
      word("İkinci", { de: "das Urteil", tr: "karar, hüküm" }),
      word("Üçüncü", { de: "verkünden", tr: "ilan etmek" }),
      word("Dördüncü", { de: "die Kammer", tr: "heyet, daire" }),
      word("Beşinci", { de: "die Verhandlung", tr: "duruşma" }),
      word("Altıncı", { de: "die Haftanstalt", tr: "cezaevi" }),
      word("Yedinci", { de: "bestechen", tr: "rüşvet vermek" }),
      word("Son", { de: "vorbestraft", tr: "sabıkalı" }),
      { say: [tr("Örnek:"), de("Der Zeuge gab an, er habe nichts gesehen."), tr("Tekrar edin:"), de("Der Zeuge gab an, er habe nichts gesehen")], expect: repeat("Der Zeuge gab an, er habe nichts gesehen") },
      { say: [tr("Sıra sende: 'Duruşma ertelendi.'")], expect: produce("Die Verhandlung wurde vertagt", [tr("Edilgen geçmiş zaman; ortaç sonda:"), de("Die Verhandlung wurde vertagt."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Heyet kararı yarın açıklıyor.'")], expect: produce("Die Kammer verkündet das Urteil morgen", [tr("Nesne belirtme hâlinde; zaman zarfı sonda:"), de("Die Kammer verkündet das Urteil morgen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Sanık suçlamayı reddettiğini söyledi.'")], expect: produce("Der Angeklagte sagte, er weise den Vorwurf zurück", [tr("Aktarım kipinde ayrılabilen fiil; önek sonda:"), de("Der Angeklagte sagte, er weise den Vorwurf zurück."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Der Zeuge wollte nicht aussagen, weil er hatte Angst."), tr("cümlesi doğru mu?")], expect: truefalse("Der Zeuge wollte nicht aussagen, weil er hatte Angst.", false, [tr("Bu bağlaç yan cümle kurar; çekimli fiil sona gider:"), de("Der Zeuge wollte nicht aussagen, weil er Angst hatte.")]) },
      { say: [tr("Son: 'Tanık ifade vermek istemedi.'")], expect: produce("Der Zeuge wollte nicht aussagen", [tr("Kip fiili çekimli; mastar sonda:"), de("Der Zeuge wollte nicht aussagen."), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir duruşmayı başkasına aktaracaksın.")] },
    ],
    roleplay: {
      scene: "Bir duruşmayı izledin ve orada olmayan birine aktarıyorsun. Kimin ne söylediğini aktarım kipiyle ver, mahkemenin kararını ayrı söyle, kendi izlenimini ayır ve bundan sonra ne olacağını anlat.",
      partner: "davanın sonucunu merak eden, taraf tutan bir tanıdık",
      opening: "Und? Haben sie ihm geglaubt oder nicht? Erzähl mal von Anfang an.",
      openingTr: "Ee? Ona inandılar mı, inanmadılar mı? Baştan anlat hadi.",
      goal: "Söylenenler aktarım kipiyle nakledilmiş, mahkemenin kararı ayrı verilmiş, kişisel izlenim ayrılmış ve sonraki adım anlatılmış olur.",
      minTurns: 9,
    },
  },
];
