import { de, tr, type Lesson, type LectureStep, type Segment } from "../types";

/**
 * C1 · Modül 5 — Basın ve akademik aktarım (041–050).
 *
 * B2'de dolaylı aktarıma giriş yapılmıştı; burada tamamlanıyor. Fark
 * teknikten çok İŞLEVDE: gazetede ve akademide aktarım kipi bir üslup süsü
 * değil, sorumluluğun kimde olduğunu gösteren bir işaret. "Der Effekt sei
 * groß" yazan bir metin o cümleyi ONAYLAMIYOR — kaynağına iade ediyor.
 * Bunu görmeyen okur, aktarılan iddiayı yazarın hükmü sanır.
 *
 * Modülün ikinci hattı akademik isimleştirme: `es lässt sich festhalten`,
 * `daraus ergibt sich`, `unter Berücksichtigung von`. Bu dil kişiyi cümleden
 * çıkarır ve bulguyu öne alır — B2'deki kurum dilinin bilimsel akrabası.
 *
 * 044 bilerek kaynak eleştirisine ayrıldı ve doğru/yanlış maddesi dilbilgisi
 * değil MANTIK sınıyor: aktarım kipi bir iddianın doğru olduğunu değil,
 * yalnızca birinin öyle söylediğini bildirir. Bu ayrım C1'in okuma
 * becerisinin kalbi.
 *
 * Adım dengesi: her derste 5 kelime tekrarı + 4 üretim + 1 doğru/yanlış.
 */

const repeat = (target: string): LectureStep["expect"] => ({ kind: "repeat", target });
const produce = (target: string, hint: Segment[], accept?: string[]): LectureStep["expect"] => ({ kind: "produce", target, accept, hint });
const truefalse = (statement: string, answer: boolean, why: Segment[]): LectureStep["expect"] => ({ kind: "truefalse", statement, answer, why });

function word(n: string, w: { de: string; tr: string }, note?: string): LectureStep {
  return {
    say: [tr(`${n} kelimemiz:`), de(w.de), tr(`'${w.tr}' demek.${note ? ` ${note}` : ""} Lütfen`), de(w.de), tr("deyin.")],
    expect: repeat(w.de),
  };
}

export const deC1B05: Lesson[] = [
  {
    id: "de-c1-konjunktiv1",
    icon: "media",
    level: "C1",
    course: "de",
    title: "Er sei im Ausland",
    titleTr: "Dolaylı aktarım tam",
    summary: "Aktarım kipinin bütün biçimlerini ve ne işe yaradığını öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-I-Rede",
    vocab: [
      { de: "die Wiedergabe", tr: "aktarım" },
      { de: "sich distanzieren", tr: "mesafe koymak" },
      { de: "der Wortlaut", tr: "lafız, metin" },
      { de: "übereinstimmen", tr: "örtüşmek" },
      { de: "zuschreiben", tr: "atfetmek" },
    ],
    patterns: [
      { de: "er sei / sie habe / man solle", tr: "aktarım kipi biçimleri" },
      { de: "Wer wiedergibt, distanziert sich.", tr: "aktarım mesafe koyar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Yeni modül: basın ve akademi. B2'de aktarım kipine girmiştin; burada tamamlıyoruz. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Ama asıl mesele biçim değil İŞLEV:"), de("Der Effekt sei groß"), tr("yazan bir metin o cümleyi onaylamıyor — kaynağına iade ediyor. Bunu görmeyen okur, aktarılan iddiayı yazarın hükmü sanır.")] },
      { say: [tr("Biçimler tanıdık: olmak fiili sei, sahip olmak habe, gerekmek solle, gelmek komme. Önce kelimeler.")] },
      word("İlk", { de: "die Wiedergabe", tr: "aktarım" }),
      word("İkinci", { de: "sich distanzieren", tr: "mesafe koymak" }),
      word("Üçüncü", { de: "der Wortlaut", tr: "lafız, metin" }),
      word("Dördüncü", { de: "übereinstimmen", tr: "örtüşmek" }),
      word("Son", { de: "zuschreiben", tr: "atfetmek" }),
      { say: [tr("Örnek:"), de("Er sagte, er sei nicht informiert worden."), tr("Tekrar edin:"), de("Er sagte, er sei nicht informiert worden")], expect: repeat("Er sagte, er sei nicht informiert worden") },
      { say: [tr("Sıra sende: 'Sözcü kararın verildiğini söyledi.'")], expect: produce("Der Sprecher sagte, die Entscheidung sei gefallen", [tr("Aktarım kipinde olmak fiili sei; ortaç sonda:"), de("Der Sprecher sagte, die Entscheidung sei gefallen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bakanlığa göre bir önlem alınmalıymış.'")], expect: produce("Dem Ministerium zufolge solle eine Maßnahme ergriffen werden", [tr("Bu edat yönelme hâli ister ve isimden sonra gelir; kipli edilgen sonda:"), de("Dem Ministerium zufolge solle eine Maßnahme ergriffen werden."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Aktaran kişi söylenene mesafe koyar.'")], expect: produce("Wer wiedergibt, distanziert sich vom Gesagten", [tr("Yan cümle özne olarak başta; isimleşmiş ortaç yönelme hâlinde:"), de("Wer wiedergibt, distanziert sich vom Gesagten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Er sagte, er ist nicht informiert worden."), tr("cümlesi doğru mu?")], expect: truefalse("Er sagte, er ist nicht informiert worden.", false, [tr("Düz kip cümleyi yazarın hükmü yapar; aktarımda aktarım kipi gerekir:"), de("Er sagte, er sei nicht informiert worden.")]) },
      { say: [tr("Son: 'Lafız tutanakla örtüşüyor.'")], expect: produce("Der Wortlaut stimmt mit dem Protokoll überein", [tr("Edat yönelme hâli ister; ayrılabilen önek sonda:"), de("Der Wortlaut stimmt mit dem Protokoll überein."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada duyduğun bir açıklamayı aktaracaksın — kendi görüşünü ayırarak.")] },
    ],
    roleplay: {
      scene: "Bir toplantıda söylenenleri, orada olmayan bir meslektaşına aktarıyorsun. Kimin ne söylediğini aktarım kipiyle ver, kendi değerlendirmeni ayrı bir cümlede söyle ve neyin kesin, neyin iddia olduğunu belirt.",
      partner: "kimin ne dediğini tam olarak bilmek isteyen, ayrıntı soran bir meslektaş",
      opening: "Und was genau hat die Leitung gesagt — mit ihren Worten, nicht mit deiner Bewertung?",
      openingTr: "Peki yönetim tam olarak ne dedi — senin değerlendirmenle değil, kendi sözleriyle?",
      goal: "Söylenenler aktarım kipiyle verilmiş, konuşanın kendi görüşü ayrılmış ve neyin kesin neyin iddia olduğu belirtilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-pressebericht",
    icon: "media",
    level: "C1",
    course: "de",
    title: "Laut Angaben der Behörden",
    titleTr: "Ajans dili",
    summary: "Haber ajansı dilinde kaynak bildirmeyi ve aktarmayı öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-I-Rede",
    vocab: [
      { de: "der Sachverhalt", tr: "vaka, durum" },
      { de: "dementieren", tr: "yalanlamak" },
      { de: "die Quellenlage", tr: "kaynak durumu" },
      { de: "vorliegen", tr: "mevcut olmak, elde bulunmak" },
      { de: "einordnen", tr: "yerine oturtmak" },
    ],
    patterns: [
      { de: "Laut Angaben … habe …", tr: "kaynak artı aktarım" },
      { de: "Dem Bericht zufolge …", tr: "rapora göre" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün haber dili. Ajans metninde her cümlenin bir sahibi vardır ve o sahip cümlenin başında belirtilir. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("İki kalıp yeter ve ikisi de aktarım kipiyle birlikte gelir. Bir de sık karıştırılan bir fiil çifti var — sonda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "der Sachverhalt", tr: "vaka, durum" }),
      word("İkinci", { de: "dementieren", tr: "yalanlamak" }),
      word("Üçüncü", { de: "die Quellenlage", tr: "kaynak durumu" }),
      word("Dördüncü", { de: "vorliegen", tr: "mevcut olmak" }),
      word("Son", { de: "einordnen", tr: "yerine oturtmak" }),
      { say: [tr("Örnek:"), de("Laut Angaben der Behörden habe es keine Verletzten gegeben."), tr("Tekrar edin:"), de("Laut Angaben der Behörden habe es keine Verletzten gegeben")], expect: repeat("Laut Angaben der Behörden habe es keine Verletzten gegeben") },
      { say: [tr("Sıra sende: 'Şirket bunu yalanladı.'")], expect: produce("Das Unternehmen hat das dementiert", [tr("Yabancı kökenli fiilin ortacı ge- almaz:"), de("Das Unternehmen hat das dementiert."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Rapora göre görüşmeler sürüyormuş.'")], expect: produce("Dem Bericht zufolge dauerten die Gespräche an", [tr("Bu edat isimden SONRA gelir ve yönelme hâli ister:"), de("Dem Bericht zufolge dauerten die Gespräche an."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kaynak durumu zayıf.'")], expect: produce("Die Quellenlage ist dünn", [tr("Kısa hüküm cümlesi:"), de("Die Quellenlage ist dünn."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Eine Stellungnahme liegt noch nicht bevor."), tr("cümlesi doğru mu?")], expect: truefalse("Eine Stellungnahme liegt noch nicht bevor.", false, [tr("İki fiil karışmış: 'vorliegen' elde bulunmak, 'bevorstehen' ise yaklaşmak demektir:"), de("Eine Stellungnahme liegt noch nicht vor.")]) },
      { say: [tr("Son: 'Henüz bir açıklama gelmedi.'")], expect: produce("Eine Stellungnahme liegt noch nicht vor", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Eine Stellungnahme liegt noch nicht vor."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir olayı haber diliyle aktaracaksın.")] },
    ],
    roleplay: {
      scene: "Bir yerel radyoya bir olayı aktarıyorsun. Neyin doğrulandığını, neyin yalnızca iddia olduğunu ve kaynak durumunun ne olduğunu ayır; abartıya kaçmadan bir değerlendirme yap.",
      partner: "kesin cümle isteyen, 'evet mi hayır mı' diye soran bir radyo sunucusu",
      opening: "Ganz kurz und ohne Konjunktiv: Ist da nun jemand verletzt worden oder nicht?",
      openingTr: "Kısaca ve dolaylı kip olmadan: Orada biri yaralandı mı, yaralanmadı mı?",
      goal: "Doğrulanan ile iddia edilen ayrılmış, kaynak durumu söylenmiş ve abartıya kaçmayan bir değerlendirme yapılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-wissenschaftssprache",
    icon: "school",
    level: "C1",
    course: "de",
    title: "Es lässt sich festhalten",
    titleTr: "Akademik üslup",
    summary: "Bulguyu kişisiz akademik dille bildirmeyi öğretir.",
    minutes: 12,
    focusId: "Nominalstil",
    vocab: [
      { de: "sich ergeben", tr: "doğmak, çıkmak (sonuç)" },
      { de: "die Berücksichtigung", tr: "dikkate alma" },
      { de: "der Befund", tr: "bulgu" },
      { de: "voraussetzen", tr: "varsaymak, şart koşmak" },
      { de: "die Annahme", tr: "varsayım" },
    ],
    patterns: [
      { de: "Es lässt sich festhalten, dass …", tr: "bulguyu kişisiz bildirir" },
      { de: "Daraus ergibt sich …", tr: "sonuç çıkarır" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün akademik dil. Kuralı tek cümlede söylenebilir: yazan kişi cümleden çıkar, bulgu öne geçer. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("'Bence etki küçük' yerine 'etkinin küçük olduğu söylenebilir' denir. Bu, B2'de öğrendiğin kurum dilinin bilimsel akrabası. Önce kelimeler.")] },
      word("İlk", { de: "sich ergeben", tr: "doğmak, çıkmak" }),
      word("İkinci", { de: "die Berücksichtigung", tr: "dikkate alma" }),
      word("Üçüncü", { de: "der Befund", tr: "bulgu" }),
      word("Dördüncü", { de: "voraussetzen", tr: "varsaymak" }),
      word("Son", { de: "die Annahme", tr: "varsayım" }),
      { say: [tr("Örnek:"), de("Es lässt sich festhalten, dass der Effekt gering ist."), tr("Tekrar edin:"), de("Es lässt sich festhalten, dass der Effekt gering ist")], expect: repeat("Es lässt sich festhalten, dass der Effekt gering ist") },
      { say: [tr("Sıra sende: 'Bundan şu sonuç doğuyor:'")], expect: produce("Daraus ergibt sich Folgendes", [tr("Edat zamirle kaynaşır; dönüşlü fiil ikinci sırada:"), de("Daraus ergibt sich Folgendes."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bağlam dikkate alınarak değerlendirilmelidir.'")], expect: produce("Unter Berücksichtigung des Kontexts ist das zu bewerten", [tr("İsim öbeği başta; sein artı zu yapısı zorunluluğu kişisiz söyler:"), de("Unter Berücksichtigung des Kontexts ist das zu bewerten."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bulgu varsayımı desteklemiyor.'")], expect: produce("Der Befund stützt die Annahme nicht", [tr("Nesne belirtme hâlinde; olumsuzluk sonda:"), de("Der Befund stützt die Annahme nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Daraus ergibt sich Folgendes."), tr("cümlesi doğru mu?")], expect: truefalse("Daraus ergibt sich Folgendes.", true, [tr("Doğru. Edat zamirle kaynaşmış, dönüşlü fiil ikinci sırada ve isimleşmiş sıfat nesne olarak sonda.")]) },
      { say: [tr("Son: 'Bu, sabit koşulları varsayar.'")], expect: produce("Das setzt konstante Bedingungen voraus", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Das setzt konstante Bedingungen voraus."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir bulguyu akademik dille savunacaksın.")] },
    ],
    roleplay: {
      scene: "Bir çalışma toplantısında kendi bulgunu sunuyorsun. Bulguyu kişisiz dille bildir, hangi varsayıma dayandığını söyle, bir sınırlılığı kabul et ve sonucun ne kadar genellenebileceğini belirt.",
      partner: "yöntemi sorgulayan, genelleme sınırlarını soran bir araştırmacı",
      opening: "Bevor wir über die Deutung reden: Auf welcher Annahme beruht Ihr Befund eigentlich?",
      openingTr: "Yorumu konuşmadan önce: Bulgunuz aslında hangi varsayıma dayanıyor?",
      goal: "Bulgu kişisiz dille bildirilmiş, dayandığı varsayım ve bir sınırlılık söylenmiş ve genellenebilirliği belirtilmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-quellenkritik",
    icon: "law",
    level: "C1",
    course: "de",
    title: "Wer sagt das?",
    titleTr: "Kaynak eleştirisi",
    summary: "Aktarılan iddia ile kanıtlanmış olguyu ayırmayı öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-I-Rede",
    vocab: [
      { de: "nachweislich", tr: "kanıtlanabilir biçimde" },
      { de: "die Primärquelle", tr: "birincil kaynak" },
      { de: "nachprüfbar", tr: "doğrulanabilir" },
      { de: "die Interessenlage", tr: "çıkar durumu" },
      { de: "verlässlich", tr: "güvenilir" },
    ],
    patterns: [
      { de: "Der Studie zufolge sei …", tr: "aktarılan iddia" },
      { de: "Das bleibt zu belegen.", tr: "kanıt eksiğini söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugünkü ders bir okuma becerisi: aktarılan iddia ile kanıtlanmış olguyu ayırmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Kilit nokta şu: aktarım kipi bir şeyin DOĞRU olduğunu söylemez; yalnızca birinin öyle söylediğini bildirir. Bunu dersin sonunda sınayacağız. Önce kelimeler.")] },
      word("İlk", { de: "nachweislich", tr: "kanıtlanabilir biçimde" }),
      word("İkinci", { de: "die Primärquelle", tr: "birincil kaynak" }),
      word("Üçüncü", { de: "nachprüfbar", tr: "doğrulanabilir" }),
      word("Dördüncü", { de: "die Interessenlage", tr: "çıkar durumu" }),
      word("Son", { de: "verlässlich", tr: "güvenilir" }),
      { say: [tr("Örnek:"), de("Der Studie zufolge sei der Effekt groß."), tr("Tekrar edin:"), de("Der Studie zufolge sei der Effekt groß")], expect: repeat("Der Studie zufolge sei der Effekt groß") },
      { say: [tr("Sıra sende: 'Bunun kanıtlanması gerekiyor.'")], expect: produce("Das bleibt zu belegen", [tr("bleiben artı zu artı mastar: yapılması gerekeni kişisiz söyler:"), de("Das bleibt zu belegen."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Birincil kaynağı incelemek gerekir.'")], expect: produce("Man muss die Primärquelle prüfen", [tr("Nesne belirtme hâlinde; mastar sonda:"), de("Man muss die Primärquelle prüfen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Kim söylüyor ve nasıl bir çıkarı var?'")], expect: produce("Wer sagt das, und welche Interessenlage hat er", [tr("İki soru; ikincisinde soru sıfatı nesneyi belirliyor:"), de("Wer sagt das, und welche Interessenlage hat er?"), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi mantık sorusu. Şu hüküm doğru mu:"), de("Der Studie zufolge sei der Effekt groß — damit ist er bewiesen.")], expect: truefalse("Der Studie zufolge sei der Effekt groß — damit ist er bewiesen.", false, [tr("Hayır. Aktarım kipi bir şeyin doğru olduğunu değil, birinin öyle söylediğini bildirir; kanıt ayrıca aranır:"), de("Der Studie zufolge sei der Effekt groß — belegt ist das damit noch nicht.")]) },
      { say: [tr("Son: 'İddia kanıtlanabilir biçimde yanlış.'")], expect: produce("Die Behauptung ist nachweislich falsch", [tr("Zarf sıfattan önce:"), de("Die Behauptung ist nachweislich falsch."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir kaynağı birlikte tartacaksın.")] },
    ],
    roleplay: {
      scene: "Bir tanıdığın bir çalışmaya dayanarak güçlü bir iddia öne sürüyor. Kaynağı sorgula, aktarılan ile kanıtlanmışı ayır, çıkar durumunu sor ve ne kadarına güvenilebileceğinde ortak bir sonuca varın.",
      partner: "çalışmaya güvenen, kaynağı sorgulamayı gereksiz bulan bir tanıdık",
      opening: "Es steht doch in der Studie. Was willst du denn noch — soll ich die Autoren anrufen?",
      openingTr: "Çalışmada yazıyor işte. Daha ne istiyorsun — yazarları mı arayayım?",
      goal: "Aktarılan iddia ile kanıtlanmış olgu ayrılmış, kaynak ve çıkar durumu sorgulanmış ve neye ne kadar güvenileceğinde uzlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-abstract",
    icon: "pen",
    level: "C1",
    course: "de",
    title: "Das Abstract",
    titleTr: "Özet yazma dili",
    summary: "Bir çalışmanın özetini akademik kalıplarla yazmayı öğretir.",
    minutes: 12,
    focusId: "Nominalstil",
    vocab: [
      { de: "sich stützen auf", tr: "dayanmak" },
      { de: "nahelegen", tr: "işaret etmek, düşündürmek" },
      { de: "die Fragestellung", tr: "araştırma sorusu" },
      { de: "die Vorgehensweise", tr: "yöntem, izlenen yol" },
      { de: "aufzeigen", tr: "ortaya koymak" },
    ],
    patterns: [
      { de: "Die vorliegende Arbeit untersucht …", tr: "özetin açılışı" },
      { de: "Die Ergebnisse legen … nahe.", tr: "bulguyu temkinli bildirir" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün özet yazacağız — bir çalışmanın yüz elli kelimelik vitrini. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Özetin dört parçası vardır: soru, yöntem, bulgu, sonuç. Dördü de hazır kalıplarla söylenir ve kalıp olması iyi — okur nerede ne bulacağını bilir. Önce kelimeler.")] },
      word("İlk", { de: "sich stützen auf", tr: "dayanmak" }),
      word("İkinci", { de: "nahelegen", tr: "işaret etmek" }),
      word("Üçüncü", { de: "die Fragestellung", tr: "araştırma sorusu" }),
      word("Dördüncü", { de: "die Vorgehensweise", tr: "yöntem" }),
      word("Son", { de: "aufzeigen", tr: "ortaya koymak" }),
      { say: [tr("Örnek:"), de("Die vorliegende Arbeit untersucht den Einfluss von Schlaf auf die Konzentration."), tr("Tekrar edin:"), de("Die vorliegende Arbeit untersucht den Einfluss von Schlaf auf die Konzentration")], expect: repeat("Die vorliegende Arbeit untersucht den Einfluss von Schlaf auf die Konzentration") },
      { say: [tr("Sıra sende: 'Yöntem olarak niteliksel görüşmelere dayanıyor.'")], expect: produce("Methodisch stützt sich die Arbeit auf qualitative Interviews", [tr("Zarf başta; dönüşlü fiil ve sabit edat belirtme hâliyle:"), de("Methodisch stützt sich die Arbeit auf qualitative Interviews."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Sonuçlar bir bağlantıya işaret ediyor.'")], expect: produce("Die Ergebnisse legen einen Zusammenhang nahe", [tr("Ayrılabilen fiilin ikinci parçası cümlenin sonunda ve ayrı yazılır:"), de("Die Ergebnisse legen einen Zusammenhang nahe."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Araştırma sorusu üç bölümlü.'")], expect: produce("Die Fragestellung ist dreiteilig", [tr("Kısa hüküm cümlesi:"), de("Die Fragestellung ist dreiteilig."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die Ergebnisse legen einen Zusammenhang nah."), tr("cümlesi doğru mu?")], expect: truefalse("Die Ergebnisse legen einen Zusammenhang nah.", false, [tr("Ayrılan parça 'nahe' biçimini korur; 'nah' burada yanlıştır:"), de("Die Ergebnisse legen einen Zusammenhang nahe.")]) },
      { say: [tr("Son: 'Çalışma bir boşluk ortaya koyuyor.'")], expect: produce("Die Arbeit zeigt eine Lücke auf", [tr("Ayrılabilen fiilin öneki en sonda:"), de("Die Arbeit zeigt eine Lücke auf."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada kendi çalışmanı bir dakikada özetleyeceksin.")] },
    ],
    roleplay: {
      scene: "Bir konferansta biri sana çalışmanı soruyor ve bir dakikan var. Araştırma sorunu, yöntemini, ana bulgunu ve neyi açık bıraktığını sırayla söyle; gelen soruya kısa cevap ver.",
      partner: "az vakti olan ama gerçekten ilgilenen bir meslektaş",
      opening: "Ich habe genau eine Minute — worum geht es in Ihrer Arbeit und was ist das eine Ergebnis, das zählt?",
      openingTr: "Tam bir dakikam var — çalışmanız neyle ilgili ve önemli olan tek bulgu ne?",
      goal: "Araştırma sorusu, yöntem, ana bulgu ve açık kalan nokta bir dakikada anlatılmış ve bir soru cevaplanmış olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-vortrag-uni",
    icon: "school",
    level: "C1",
    course: "de",
    title: "Das Kolloquium",
    titleTr: "Akademik savunma",
    summary: "İtirazı kabul edip tezini savunmayı akademik dille öğretir.",
    minutes: 12,
    focusId: "Konzessive-Konnektoren",
    vocab: [
      { de: "einwenden", tr: "itiraz etmek" },
      { de: "entgegenhalten", tr: "karşı çıkmak" },
      { de: "mit Verlaub", tr: "kusura bakmayın ama" },
      { de: "die These", tr: "tez" },
      { de: "schlüssig", tr: "tutarlı" },
    ],
    patterns: [
      { de: "Einerseits ließe sich einwenden, dass …", tr: "itirazı kendin dile getirir" },
      { de: "Dem ist entgegenzuhalten, dass …", tr: "itiraza karşı çıkar" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün akademik savunma. Buradaki ustalık, itirazı karşı taraftan önce SEN söylemek. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Sıra şu: itirazı dile getir, sonra ona karşı çık. İkisi de kalıp ve ikisi de dilek kipi ile kişisiz yapıdan besleniyor. Önce kelimeler.")] },
      word("İlk", { de: "einwenden", tr: "itiraz etmek" }),
      word("İkinci", { de: "entgegenhalten", tr: "karşı çıkmak" }),
      word("Üçüncü", { de: "mit Verlaub", tr: "kusura bakmayın ama" }),
      word("Dördüncü", { de: "die These", tr: "tez" }),
      word("Son", { de: "schlüssig", tr: "tutarlı" }),
      { say: [tr("Örnek:"), de("Einerseits ließe sich einwenden, dass die Stichprobe klein ist."), tr("Tekrar edin:"), de("Einerseits ließe sich einwenden, dass die Stichprobe klein ist")], expect: repeat("Einerseits ließe sich einwenden, dass die Stichprobe klein ist") },
      { say: [tr("Sıra sende: 'Buna şu karşı çıkılabilir: yöntem sağlam.'")], expect: produce("Dem ist entgegenzuhalten, dass die Methode robust ist", [tr("Yönelme hâlindeki tümleç başta; sein artı zu yapısı:"), de("Dem ist entgegenzuhalten, dass die Methode robust ist."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Kusura bakmayın ama tez tutarlı değil.'")], expect: produce("Mit Verlaub, die These ist nicht schlüssig", [tr("Kalıplaşmış giriş, sonra düz cümle:"), de("Mit Verlaub, die These ist nicht schlüssig."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'İtirazınızı kabul ediyorum.'")], expect: produce("Ihren Einwand lasse ich gelten", [tr("Nesne öne alınmış; ikinci fiil mastar hâlinde sonda:"), de("Ihren Einwand lasse ich gelten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Gleichwohl ändert sich das Ergebnis nicht."), tr("cümlesi doğru mu?")], expect: truefalse("Gleichwohl ändert sich das Ergebnis nicht.", true, [tr("Doğru. Bu bağlaç cümlenin ilk öğesidir, o yüzden fiil hemen arkasından geliyor ve dönüşlü zamir özneden sonra duruyor.")]) },
      { say: [tr("Son: 'Yine de sonuç değişmiyor.'")], expect: produce("Gleichwohl ändert sich das Ergebnis nicht", [tr("Bağlaç ilk öğe; fiil ikinci sırada:"), de("Gleichwohl ändert sich das Ergebnis nicht."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada tezini savunacaksın.")] },
    ],
    roleplay: {
      scene: "Bir kolokyumda çalışmanı savunuyorsun. En güçlü itirazı önce sen dile getir, sonra ona karşı çık; jüri üyesinin haklı olduğu bir noktayı kabul et ve yine de tezini koru.",
      partner: "hazırlıklı, yöntem eleştirisi yapan bir jüri üyesi",
      opening: "Mit Verlaub — Ihre Stichprobe trägt die Schlussfolgerung nicht. Wie begegnen Sie diesem Einwand?",
      openingTr: "Kusura bakmayın ama örnekleminiz bu sonucu taşımıyor. Bu itiraza nasıl karşılık veriyorsunuz?",
      goal: "En güçlü itiraz önce dile getirilmiş, karşı çıkılmış, bir nokta kabul edilmiş ve tez korunmuş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-fachdiskussion",
    icon: "idea",
    level: "C1",
    course: "de",
    title: "Unter Experten",
    titleTr: "Uzman tartışması",
    summary: "Katılım öbekleriyle sıkıştırılmış uzman dilini anlamayı öğretir.",
    minutes: 12,
    focusId: "Partizipialkonstruktionen",
    vocab: [
      { de: "zugrunde liegen", tr: "temelinde olmak" },
      { de: "verkürzt", tr: "kısaltılmış" },
      { de: "der Diskurs", tr: "söylem" },
      { de: "die Prämisse", tr: "öncül" },
      { de: "differenzieren", tr: "ayrıştırmak" },
    ],
    patterns: [
      { de: "die dem Modell zugrunde liegende Annahme", tr: "katılım öbeği" },
      { de: "verkürzt dargestellt", tr: "kısaca söylersek" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün uzmanların kendi aralarında konuştuğu dil: sıkıştırılmış. Bir ilgi cümlesi ismin önüne, tek bir öbeğe katlanıyor. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Örnek:"), de("die Annahme, die dem Modell zugrunde liegt"), tr("cümlesi"), de("die dem Modell zugrunde liegende Annahme"), tr("hâline geliyor. Okurken çözebilmen, yazarken kurabilmen gerekiyor. Önce kelimeler.")] },
      word("İlk", { de: "zugrunde liegen", tr: "temelinde olmak" }),
      word("İkinci", { de: "verkürzt", tr: "kısaltılmış" }),
      word("Üçüncü", { de: "der Diskurs", tr: "söylem" }),
      word("Dördüncü", { de: "die Prämisse", tr: "öncül" }),
      word("Son", { de: "differenzieren", tr: "ayrıştırmak" }),
      { say: [tr("Örnek:"), de("Die dem Modell zugrunde liegende Annahme ist umstritten."), tr("Tekrar edin:"), de("Die dem Modell zugrunde liegende Annahme ist umstritten")], expect: repeat("Die dem Modell zugrunde liegende Annahme ist umstritten") },
      { say: [tr("Sıra sende: 'Kısaca söylersek şöyle:'")], expect: produce("Verkürzt dargestellt heißt das Folgendes", [tr("Ortaç öbeği başta; fiil ikinci sırada:"), de("Verkürzt dargestellt heißt das Folgendes."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Burada ayrıştırmak gerekiyor.'")], expect: produce("Hier muss man differenzieren", [tr("Yer zarfı başta; mastar sonda:"), de("Hier muss man differenzieren."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Öncül kanıtlanmamış.'")], expect: produce("Die Prämisse ist unbewiesen", [tr("Kısa hüküm cümlesi:"), de("Die Prämisse ist unbewiesen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Die dem Modell zugrunde liegende Annahme sind umstritten."), tr("cümlesi doğru mu?")], expect: truefalse("Die dem Modell zugrunde liegende Annahme sind umstritten.", false, [tr("Özne tekildir; araya giren uzun öbek bunu değiştirmez:"), de("Die dem Modell zugrunde liegende Annahme ist umstritten.")]) },
      { say: [tr("Son: 'Bu söylemde iki taraf var.'")], expect: produce("In diesem Diskurs gibt es zwei Lager", [tr("Tümleç başta; kalıplaşmış fiil ikinci sırada:"), de("In diesem Diskurs gibt es zwei Lager."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada uzman diliyle kurulmuş bir iddiayı çözeceksin.")] },
    ],
    roleplay: {
      scene: "Bir uzman sana çok sıkıştırılmış cümlelerle bir iddia anlatıyor. Anlamadığın öbeği açtır, kendi cümlenle sadeleştir, öncülün ne olduğunu sor ve nerede ayrıştırmak gerektiğini söyle.",
      partner: "hızlı ve teknik konuşan, sadeleştirmeye direnen bir uzman",
      opening: "Die dem Verfahren zugrunde liegende Annahme ist, verkürzt dargestellt, trivial. Sehen Sie das anders?",
      openingTr: "Yöntemin temelindeki varsayım, kısaca söylersek, basit. Siz başka mı görüyorsunuz?",
      goal: "Sıkıştırılmış öbek açılmış, iddia sadeleştirilmiş ve öncülün neresinin tartışmalı olduğu söylenmiş olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-populaerwissenschaft",
    icon: "tech",
    level: "C1",
    course: "de",
    title: "Einfach erklärt",
    titleTr: "Bilimi sadeleştirme",
    summary: "Karmaşık bir konuyu doğruluğu bozmadan sadeleştirmeyi öğretir.",
    minutes: 12,
    focusId: "Metaphern",
    vocab: [
      { de: "vereinfachen", tr: "basitleştirmek" },
      { de: "anschaulich", tr: "somut, göz önüne getiren" },
      { de: "die Faustregel", tr: "kaba kural" },
      { de: "zugänglich", tr: "erişilebilir" },
      { de: "greifbar", tr: "elle tutulur" },
    ],
    patterns: [
      { de: "Vereinfacht gesagt …", tr: "basitleştirerek anlatır" },
      { de: "Der Vergleich hinkt, aber …", tr: "benzetmenin sınırını söyler" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün zor bir denge: sadeleştirmek ama yanlış anlatmamak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Almancanın bu iş için dürüst bir kalıbı var: benzetmeyi kurduktan sonra sınırını da söylemek —"), de("Der Vergleich hinkt, aber er hilft."), tr("Önce kelimeler.")] },
      word("İlk", { de: "vereinfachen", tr: "basitleştirmek" }),
      word("İkinci", { de: "anschaulich", tr: "somut" }),
      word("Üçüncü", { de: "die Faustregel", tr: "kaba kural" }),
      word("Dördüncü", { de: "zugänglich", tr: "erişilebilir" }),
      word("Son", { de: "greifbar", tr: "elle tutulur" }),
      { say: [tr("Örnek:"), de("Stellen Sie sich das Gehirn wie eine Bibliothek vor."), tr("Tekrar edin:"), de("Stellen Sie sich das Gehirn wie eine Bibliothek vor")], expect: repeat("Stellen Sie sich das Gehirn wie eine Bibliothek vor") },
      { say: [tr("Sıra sende: 'Basitçe söylersek şöyle işliyor.'")], expect: produce("Vereinfacht gesagt funktioniert es so", [tr("Ortaç öbeği başta; fiil ikinci sırada:"), de("Vereinfacht gesagt funktioniert es so."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Benzetme topal ama işe yarıyor.'")], expect: produce("Der Vergleich hinkt, aber er hilft", [tr("İki cümle; ikincisinde özne tekrarlanıyor:"), de("Der Vergleich hinkt, aber er hilft."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Bunu elle tutulur hâle getirmek istiyorum.'")], expect: produce("Das möchte ich greifbar machen", [tr("Nesne öne alınmış; mastar sonda:"), de("Das möchte ich greifbar machen."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Als Faustregel man kann zehn Prozent nehmen."), tr("cümlesi doğru mu?")], expect: truefalse("Als Faustregel man kann zehn Prozent nehmen.", false, [tr("Cümle bir tümleçle başlayınca çekimli fiil ikinci sıraya gelir:"), de("Als Faustregel kann man zehn Prozent nehmen.")]) },
      { say: [tr("Son: 'Kaba kural olarak yüzde on alınabilir.'")], expect: produce("Als Faustregel kann man zehn Prozent nehmen", [tr("Tümleç başta, kip fiili ikinci sırada, mastar sonda:"), de("Als Faustregel kann man zehn Prozent nehmen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir konuyu meraklı bir dinleyiciye sadeleştireceksin.")] },
    ],
    roleplay: {
      scene: "Bir podcast için uzmanlık konunu geniş kitleye anlatıyorsun. Bir benzetme kur, benzetmenin nerede topalladığını söyle, bir kaba kural ver ve dinleyicinin sorusunu sadeleştirerek cevapla.",
      partner: "meraklı, sürekli 'yani şöyle mi' diye özetleyen bir podcast sunucusu",
      opening: "Erklären Sie es mir bitte so, dass ich es abends beim Essen weitererzählen kann — geht das?",
      openingTr: "Bunu akşam yemekte anlatabileceğim şekilde açıklar mısınız — mümkün mü?",
      goal: "Benzetme kurulmuş, sınırı söylenmiş, bir kaba kural verilmiş ve sunucu konuyu kendi cümlesiyle doğru özetlemiş olur.",
      minTurns: 8,
    },
  },

  {
    id: "de-c1-zitat",
    icon: "book",
    level: "C1",
    course: "de",
    title: "Richtig zitieren",
    titleTr: "Alıntı ve atıf",
    summary: "Alıntının doğru aktarımını ve çarpıtmanın nerede başladığını öğretir.",
    minutes: 12,
    focusId: "Konjunktiv-I-Rede",
    vocab: [
      { de: "die Fußnote", tr: "dipnot" },
      { de: "treffend", tr: "isabetli" },
      { de: "die Urheberschaft", tr: "eser sahipliği" },
      { de: "entstellen", tr: "çarpıtmak" },
      { de: "die Passage", tr: "pasaj" },
    ],
    patterns: [
      { de: "Wie X treffend bemerkte, sei …", tr: "atıflı aktarım" },
      { de: "aus dem Zusammenhang gerissen", tr: "bağlamından koparılmış" },
    ],
    lecture: [
      { say: [tr("Merhaba! Bugün alıntı. Ve bir uyarı: alıntının en tehlikeli hâli yanlış olan değil, doğru ama bağlamından koparılmış olandır. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("Doğru atıf üç şey ister: kim, ne dedi, nerede. Aktarım kipi bunlardan ikincisini üstleniyor. Önce kelimeler.")] },
      word("İlk", { de: "die Fußnote", tr: "dipnot" }),
      word("İkinci", { de: "treffend", tr: "isabetli" }),
      word("Üçüncü", { de: "die Urheberschaft", tr: "eser sahipliği" }),
      word("Dördüncü", { de: "entstellen", tr: "çarpıtmak" }),
      word("Son", { de: "die Passage", tr: "pasaj" }),
      { say: [tr("Örnek:"), de("Wie Weber treffend bemerkte, sei der Wandel unumkehrbar."), tr("Tekrar edin:"), de("Wie Weber treffend bemerkte, sei der Wandel unumkehrbar")], expect: repeat("Wie Weber treffend bemerkte, sei der Wandel unumkehrbar") },
      { say: [tr("Sıra sende: 'Kaynağı dipnotta belirtiyorum.'")], expect: produce("Die Quelle nenne ich in der Fußnote", [tr("Nesne öne alınmış; edat yönelme hâlinde:"), de("Die Quelle nenne ich in der Fußnote."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Bu pasaj anlamı çarpıtıyor.'")], expect: produce("Diese Passage entstellt den Sinn", [tr("Nesne belirtme hâlinde:"), de("Diese Passage entstellt den Sinn."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Eser sahipliği tartışmalı.'")], expect: produce("Die Urheberschaft ist umstritten", [tr("Kısa hüküm cümlesi:"), de("Die Urheberschaft ist umstritten."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("Das Zitat ist aus dem Zusammenhang gerissen."), tr("cümlesi doğru mu?")], expect: truefalse("Das Zitat ist aus dem Zusammenhang gerissen.", true, [tr("Doğru. Durum bildiren edilgen kullanılmış ve kalıplaşmış ifade olduğu gibi korunmuş.")]) },
      { say: [tr("Son: 'Alıntı bağlamından koparılmış.'")], expect: produce("Das Zitat ist aus dem Zusammenhang gerissen", [tr("Durum edilgeni; ortaç sonda:"), de("Das Zitat ist aus dem Zusammenhang gerissen."), tr("Tekrar dene.")]) },
      { say: [tr("Hazırsın. Konuşmada bir alıntı tartışması yürüteceksin.")] },
    ],
    roleplay: {
      scene: "Bir metinde senin sözün alıntılanmış ama bağlamından koparılmış. Yazarla konuş: tam olarak ne dediğini aktar, nerede çarpıtıldığını göster, düzeltme iste ve nasıl atıf yapılması gerektiğini söyle.",
      partner: "alıntıyı doğru bulduğunu savunan, ama dinlemeye açık bir yazar",
      opening: "Ich habe Sie wörtlich zitiert — das können Sie nachlesen. Wo genau sehen Sie das Problem?",
      openingTr: "Sizi kelimesi kelimesine alıntıladım — kontrol edebilirsiniz. Sorunu tam olarak nerede görüyorsunuz?",
      goal: "Söylenenin tamamı aktarılmış, çarpıtmanın nerede olduğu gösterilmiş ve bir düzeltme üzerinde anlaşılmış olur.",
      minTurns: 9,
    },
  },

  {
    id: "de-c1-podiumsdiskussion",
    icon: "star",
    level: "C1",
    course: "de",
    title: "Auf dem Podium",
    titleTr: "Panel tartışması",
    summary: "Panelde söz almayı, ayrıştırmayı ve süre yönetmeyi öğretir.",
    minutes: 12,
    focusId: "Konzessive-Konnektoren",
    vocab: [
      { de: "das Podium", tr: "panel, kürsü" },
      { de: "berechtigt", tr: "haklı" },
      { de: "die Redezeit", tr: "konuşma süresi" },
      { de: "sich einbringen", tr: "katkı vermek" },
      { de: "abwägend", tr: "tartarak" },
    ],
    patterns: [
      { de: "So berechtigt … ist, so … ist …", tr: "iki yönlü imtiyaz" },
      { de: "Ich möchte differenzieren.", tr: "ayrıştırma talebi" },
    ],
    lecture: [
      { say: [tr("Merhaba! Modülün son dersi: panel. Burada zorluk konuşmak değil, kısa ve tam yerinde konuşmak. Hazır mısın?")], expect: { kind: "confirm" } },
      { say: [tr("En güçlü hamle ayrıştırmak: karşı tarafın haklı yanını söyleyip yanlış yanını ayırmak. Kalıbın iki parçasında da fiil hemen sıfattan sonra gelir. Önce kelimeler.")] },
      word("İlk", { de: "das Podium", tr: "panel, kürsü" }),
      word("İkinci", { de: "berechtigt", tr: "haklı" }),
      word("Üçüncü", { de: "die Redezeit", tr: "konuşma süresi" }),
      word("Dördüncü", { de: "sich einbringen", tr: "katkı vermek" }),
      word("Son", { de: "abwägend", tr: "tartarak" }),
      { say: [tr("Örnek:"), de("So berechtigt der Einwand ist, so einseitig ist die Schlussfolgerung."), tr("Tekrar edin:"), de("So berechtigt der Einwand ist, so einseitig ist die Schlussfolgerung")], expect: repeat("So berechtigt der Einwand ist, so einseitig ist die Schlussfolgerung") },
      { say: [tr("Sıra sende: 'Ayrıştırmak istiyorum.'")], expect: produce("Ich möchte differenzieren", [tr("Kısa ve net; mastar sonda:"), de("Ich möchte differenzieren."), tr("Tekrar dene.")]) },
      { say: [tr("Şimdi: 'Buna kısaca katkı vermek isterim.'")], expect: produce("Dazu möchte ich mich kurz einbringen", [tr("Edat zamirle kaynaşır; dönüşlü zamir ortada:"), de("Dazu möchte ich mich kurz einbringen."), tr("Tekrar dene.")]) },
      { say: [tr("Bir tane daha: 'Tartarak bir sonuca varalım.'")], expect: produce("Kommen wir zu einem abgewogenen Schluss", [tr("Rica biçiminde fiil başta; ortaç sıfatı yönelme hâlinde -en ekini alır:"), de("Kommen wir zu einem abgewogenen Schluss."), tr("Tekrar dene.")]) },
      { say: [tr("Doğru mu yanlış mı:"), de("So berechtigt der Einwand ist, so einseitig die Schlussfolgerung ist."), tr("cümlesi doğru mu?")], expect: truefalse("So berechtigt der Einwand ist, so einseitig die Schlussfolgerung ist.", false, [tr("İkinci parçada çekimli fiil sıfattan hemen sonra gelir, sona atılmaz:"), de("So berechtigt der Einwand ist, so einseitig ist die Schlussfolgerung.")]) },
      { say: [tr("Son bir soru: 'Konuşma sürem doldu mu?'")], expect: produce("Ist meine Redezeit schon vorbei", [tr("Fiil başta soru; zarf sonda:"), de("Ist meine Redezeit schon vorbei?"), tr("Tekrar dene.")]) },
      { say: [tr("Modülü bitirdin. Konuşmada bir panelde yer alacaksın.")] },
    ],
    roleplay: {
      scene: "Bir panelde tartışmalı bir konudasın ve konuşma sürenle karşı tarafın iddiaları arasında dengeyi kurman gerekiyor. Söz al, karşı tarafın haklı yanını kabul et, ayrıştır ve kısa bir kapanış cümlesiyle bırak.",
      partner: "sözü uzatan, sürekli araya giren bir panel konuğu",
      opening: "Ich mache es kurz — aber wirklich kurz: Die Zahlen geben Ihre Position schlicht nicht her. Mögen Sie darauf antworten?",
      openingTr: "Kısa keseceğim — ama gerçekten kısa: Rakamlar sizin duruşunuzu basitçe desteklemiyor. Cevap vermek ister misiniz?",
      goal: "Karşı tarafın haklı yanı kabul edilmiş, iddiası ayrıştırılmış ve kısa bir kapanış cümlesiyle söz bırakılmış olur.",
      minTurns: 9,
    },
  },
];
